### ISSUE TITLE
Siri No Longer Works ("Sorry, I didn't hear back")

### ISSUE THREAD

**Issue by walksonair** [nfarina/homebridge#1000]
I am using iOS 10.2 and for some reason Siri no longer is able to control my HomeBridge devices. It is just affecting my HomeBridge devices as I have two thermostats that are linked to Homekit via their manufacturer's integration and they are working fine w/ Siri. 

The HomeBridge devices do respond nicely through the HOME app but not when I ask Siri to control them. I have tried making sure I say the exact name of the device, resetting my Homekit home, configuration, restarting Homebridge, reinstalling it, and rebooting the server it runs on. I also tried installing the latest NPM and latest plugins...all to no avail. I also tried opening the port on my router for the server running HB.

Like I mentioned, HOME app works but controlling via SIRI does not. All I get is Siri trying to control the device and then it comes back saying it didnt hear anything back.

**Comment by KhaosT** [comment]
Interesting, can you share what plugins are you using? Maybe also try turn off Siri on your iOS device wait a bit and turn it back on to force a sync.

**Comment by snowdd1** [comment]
Off-topic: Siri made it to issue #1000!

I just did the update to 10.2 on my devices and I cannot confirm any issue with Siri. It even still works from remote (iPad w/10.2 at home as central device). I did not have any beta on my devices before updating.

**Comment by walksonair** [comment]
Hello, thanks for the responses. I did turn Siri off and then back on again. It did not help the situation. Then I did a bit more troubleshooting and have something to report. I have two plugins: SmartThings (ST) and MyQ. What is happening is quite odd. I added some lights to my ST Homebridge devices and they work perfectly with Siri. I mostly use Siri for locks and garage doors so I thought it was a Siri issue. However, now, with the lights being working quite well, I am wondering what on earth is the issue with the locks and the garage doors. As I mentioned before, the devices activate through the HOME app just fine but not when I ask Siri to control them...which is the main reason I wanted to use HomeBridge in the first place...

**Comment by KhaosT** [comment]
Maybe the MyQ plugin failed to send response to Siri’s request? Home app and Siri uses different logic and if Siri didn’t get a success replied before timeout, it will say failed… Can you try to run Homebridge in debug mode ``DEBUG=* homebridge`` and then re-try the voice command with Siri and post the log at here?

Best Wishes,
Tian

**Comment by walksonair** [comment]
Hi Tian, thanks for the response. I am pasting below a snippet of the log from where I used the HOME app to cycle a lock and then when I asked Siri. I should note that there was no change in the Terminal when Siri was saying she was working on my request...

Also, I should point out that Siri used to work just fine...but I did update to iOS 10.2 and had to get a new router. Not sure any of these are culprits though it appears Siri is not being able to query HomeBridge at all now...



` Accessory [Homebridge] Setting Characteristic "Lock Target State" to value 1 +0ms
  EventedHTTPServer [::ffff:10.0.0.10] Sending HTTP event '31.9' with data: {"characteristics":[{"aid":31,"iid":9,"value":1}]} +707ms
  EventedHTTPServer [::ffff:10.0.0.13] Sending HTTP event '31.9' with data: {"characteristics":[{"aid":31,"iid":9,"value":1}]} +1ms
  EventedHTTPServer [::ffff:10.0.0.4] Muting event '31.9' notification for this connection since it originated here. +0ms
  EventedHTTPServer [::ffff:10.0.0.4] HTTP Response is finished +0ms
  EventedHTTPServer [::ffff:10.0.0.10] Sending HTTP event '31.8' with data: {"characteristics":[{"aid":31,"iid":8,"value":1}]} +5s
  EventedHTTPServer [::ffff:10.0.0.13] Sending HTTP event '31.8' with data: {"characteristics":[{"aid":31,"iid":8,"value":1}]} +1ms
  EventedHTTPServer [::ffff:10.0.0.4] Sending HTTP event '31.8' with data: {"characteristics":[{"aid":31,"iid":8,"value":1}]} +0ms
  EventedHTTPServer [::ffff:10.0.0.13] Sending HTTP event '23.10' with data: {"characteristics":[{"aid":23,"iid":10,"value":9.4}]} +4s
  EventedHTTPServer [::ffff:10.0.0.4] Sending HTTP event '23.10' with data: {"characteristics":[{"aid":23,"iid":10,"value":9.4}]} +1ms
  EventedHTTPServer [::ffff:10.0.0.4] HTTP request: /characteristics +1s
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /characteristics +0ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":31,"iid":9,"value":0}] +0ms
  Accessory [Homebridge] Setting Characteristic "Lock Target State" to value 0 +0ms
  EventedHTTPServer [::ffff:10.0.0.10] Sending HTTP event '31.9' with data: {"characteristics":[{"aid":31,"iid":9,"value":0}]} +578ms
  EventedHTTPServer [::ffff:10.0.0.13] Sending HTTP event '31.9' with data: {"characteristics":[{"aid":31,"iid":9,"value":0}]} +1ms
  EventedHTTPServer [::ffff:10.0.0.4] Muting event '31.9' notification for this connection since it originated here. +0ms
  EventedHTTPServer [::ffff:10.0.0.4] HTTP Response is finished +0ms
  EventedHTTPServer [::ffff:10.0.0.10] Sending HTTP event '31.8' with data: {"characteristics":[{"aid":31,"iid":8,"value":0}]} +5s
  EventedHTTPServer [::ffff:10.0.0.13] Sending HTTP event '31.8' with data: {"characteristics":[{"aid":31,"iid":8,"value":0}]} +0ms
  EventedHTTPServer [::ffff:10.0.0.4] Sending HTTP event '31.8' with data: {"characteristics":[{"aid":31,"iid":8,"value":0}]} +0ms
  EventedHTTPServer [::ffff:10.0.0.13] Sending HTTP event '11.8' with data: {"characteristics":[{"aid":11,"iid":8,"value":26}]} +7s
  EventedHTTPServer [::ffff:10.0.0.4] Sending HTTP event '11.8' with data: {"characteristics":[{"aid":11,"iid":8,"value":26}]} +1ms
  EventedHTTPServer [::ffff:10.0.0.4] HTTP request: /characteristics +4s
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /characteristics +0ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":31,"iid":9,"value":true}] +0ms
  Accessory [Homebridge] Setting Characteristic "Lock Target State" to value true +1ms
  EventedHTTPServer [::ffff:10.0.0.13] Sending HTTP event '10.8' with data: {"characteristics":[{"aid":10,"iid":8,"value":14}]} +10s
  EventedHTTPServer [::ffff:10.0.0.4] Sending HTTP event '10.8' with data: {"characteristics":[{"aid":10,"iid":8,"value":14}]} +0ms
  EventedHTTPServer [::ffff:10.0.0.13] Sending HTTP event '14.8' with data: {"characteristics":[{"aid":14,"iid":8,"value":11.8}]} +1ms
  EventedHTTPServer [::ffff:10.0.0.4] Sending HTTP event '14.8' with data: {"characteristics":[{"aid":14,"iid":8,"value":11.8}]} +0ms
  EventedHTTPServer [::ffff:10.0.0.13] Sending HTTP event '12.8' with data: {"characteristics":[{"aid":12,"iid":8,"value":12.6}]} +3s
  EventedHTTPServer [::ffff:10.0.0.4] Sending HTTP event '12.8' with data: {"characteristics":[{"aid":12,"iid":8,"value":12.6}]} +0ms
  EventedHTTPServer [::ffff:10.0.0.13] Sending HTTP event '13.8' with data: {"characteristics":[{"aid":13,"iid":8,"value":12.8}]} +38s
  EventedHTTPServer [::ffff:10.0.0.4] Sending HTTP event '13.8' with data: {"characteristics":[{"aid":13,"iid":8,"value":12.8}]} +0ms
  EventedHTTPServer [::ffff:10.0.0.13] Sending HTTP event '11.8' with data: {"characteristics":[{"aid":11,"iid":8,"value":26.2}]} +5s
  EventedHTTPServer [::ffff:10.0.0.4] Sending HTTP event '11.8' with data: {"characteristics":[{"aid":11,"iid":8,"value":26.2}]} +0ms
  EventedHTTPServer [::ffff:10.0.0.4] Client connection closed +4s
  EventedHTTPServer [::ffff:10.0.0.4] HTTP connection was closed +2ms
  EventedHTTPServer [::ffff:10.0.0.4] HTTP server was closed +0ms
  EventedHTTPServer [::ffff:10.0.0.13] Sending HTTP event '15.8' with data: {"characteristics":[{"aid":15,"iid":8,"value":11.5}]} +16s

`

**Comment by walksonair** [comment]
Here is a snippet of the log for when I use just Siri to control a light (and works, cycled on and then off):

EventedHTTPServer [::ffff:10.0.0.4] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:10.0.0.13] Sending HTTP event '14.8' with data: {"characteristics":[{"aid":14,"iid":8,"value":12.2}]} +9s
  EventedHTTPServer [::ffff:10.0.0.4] Sending HTTP event '14.8' with data: {"characteristics":[{"aid":14,"iid":8,"value":12.2}]} +1ms
  EventedHTTPServer [::ffff:10.0.0.13] Sending HTTP event '10.8' with data: {"characteristics":[{"aid":10,"iid":8,"value":14.4}]} +1ms
  EventedHTTPServer [::ffff:10.0.0.4] Sending HTTP event '10.8' with data: {"characteristics":[{"aid":10,"iid":8,"value":14.4}]} +1ms
  EventedHTTPServer [::ffff:10.0.0.4] HTTP request: /characteristics +1s
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /characteristics +1ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":17,"iid":8,"value":true}] +0ms
  Accessory [Homebridge] Setting Characteristic "On" to value true +0ms
  EventedHTTPServer [::ffff:10.0.0.13] Sending HTTP event '17.8' with data: {"characteristics":[{"aid":17,"iid":8,"value":true}]} +680ms
  EventedHTTPServer [::ffff:10.0.0.4] Muting event '17.8' notification for this connection since it originated here. +0ms
  EventedHTTPServer [::ffff:10.0.0.4] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:10.0.0.13] Sending HTTP event '12.8' with data: {"characteristics":[{"aid":12,"iid":8,"value":13}]} +200ms
  EventedHTTPServer [::ffff:10.0.0.4] Sending HTTP event '12.8' with data: {"characteristics":[{"aid":12,"iid":8,"value":13}]} +1ms
  EventedHTTPServer [::ffff:10.0.0.4] HTTP request: /characteristics +6s
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /characteristics +0ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":17,"iid":8,"value":false}] +1ms
  Accessory [Homebridge] Setting Characteristic "On" to value false +0ms
  EventedHTTPServer [::ffff:10.0.0.13] Sending HTTP event '17.8' with data: {"characteristics":[{"aid":17,"iid":8,"value":false}]} +406ms
  EventedHTTPServer [::ffff:10.0.0.4] Muting event '17.8' notification for this connection since it originated here. +0ms
  EventedHTTPServer [::ffff:10.0.0.4] HTTP Response is finished +0ms

**Comment by KhaosT** [comment]
So based on the log I can only say homebridge is working correctly with HomeKit... I'm not really sure what Siri is doing with your request. If possible, can you try to create a new room in your home and then move one of the lock to the new room and try command ``unlock the {name of the room}``?

**Comment by leonmf** [comment]
I had this happen in the transition to ios 10.0. The homekit apps worked 
fine but Siri refused to actuate my devices. The end solution for me was 
to delete the home from homekit and recreate it.

I'll be paying attention to see if you find a better solution!

Khaos Tian wrote:

**Comment by walksonair** [comment]
Ok, I created a room called TestRoom and moved the lock there. I tried cycling via HOME app and this is the log:

Accessory [Homebridge] Processing characteristic set: [{"aid":31,"iid":9,"value":1}] +0ms
  Accessory [Homebridge] Setting Characteristic "Lock Target State" to value 1 +0ms
  EventedHTTPServer [::ffff:10.0.0.10] Sending HTTP event '31.9' with data: {"characteristics":[{"aid":31,"iid":9,"value":1}]} +362ms
  EventedHTTPServer [::ffff:10.0.0.13] Sending HTTP event '31.9' with data: {"characteristics":[{"aid":31,"iid":9,"value":1}]} +0ms
  EventedHTTPServer [::ffff:10.0.0.4] Muting event '31.9' notification for this connection since it originated here. +1ms
  EventedHTTPServer [::ffff:10.0.0.4] HTTP Response is finished +0ms
  EventedHTTPServer [::ffff:10.0.0.10] Sending HTTP event '31.8' with data: {"characteristics":[{"aid":31,"iid":8,"value":1}]} +5s
  EventedHTTPServer [::ffff:10.0.0.13] Sending HTTP event '31.8' with data: {"characteristics":[{"aid":31,"iid":8,"value":1}]} +1ms
  EventedHTTPServer [::ffff:10.0.0.4] Sending HTTP event '31.8' with data: {"characteristics":[{"aid":31,"iid":8,"value":1}]} +0ms
  EventedHTTPServer [::ffff:10.0.0.4] HTTP request: /characteristics +2s
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /characteristics +0ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":31,"iid":9,"value":0}] +1ms
  Accessory [Homebridge] Setting Characteristic "Lock Target State" to value 0 +0ms
  EventedHTTPServer [::ffff:10.0.0.10] Sending HTTP event '31.9' with data: {"characteristics":[{"aid":31,"iid":9,"value":0}]} +617ms
  EventedHTTPServer [::ffff:10.0.0.13] Sending HTTP event '31.9' with data: {"characteristics":[{"aid":31,"iid":9,"value":0}]} +0ms
  EventedHTTPServer [::ffff:10.0.0.4] Muting event '31.9' notification for this connection since it originated here. +1ms
  EventedHTTPServer [::ffff:10.0.0.4] HTTP Response is finished +0ms
  EventedHTTPServer [::ffff:10.0.0.10] Sending HTTP event '31.8' with data: {"characteristics":[{"aid":31,"iid":8,"value":0}]} +5s
  EventedHTTPServer [::ffff:10.0.0.13] Sending HTTP event '31.8' with data: {"characteristics":[{"aid":31,"iid":8,"value":0}]} +0ms
  EventedHTTPServer [::ffff:10.0.0.4] Sending HTTP event '31.8' with data: {"characteristics":[{"aid":31,"iid":8,"value":0}]} +1ms

Now, when I use Siri and use  the command `lock the TestRoom`, this is what I get in the terminal:

Accessory [Homebridge] Processing characteristic set: [{"aid":31,"iid":9,"value":true}] +0ms
  Accessory [Homebridge] Setting Characteristic "Lock Target State" to value true +0ms
  EventedHTTPServer [::ffff:10.0.0.13] Sending HTTP event '11.8' with data: {"characteristics":[{"aid":11,"iid":8,"value":23.4}]} +18s
  EventedHTTPServer [::ffff:10.0.0.4] Sending HTTP event '11.8' with data: {"characteristics":[{"aid":11,"iid":8,"value":23.4}]} +1ms
  EventedHTTPServer [::ffff:10.0.0.4] Client connection closed +43s
  EventedHTTPServer [::ffff:10.0.0.4] HTTP connection was closed +1ms
  EventedHTTPServer [::ffff:10.0.0.4] HTTP server was closed +0ms
 
I also tried `Unlock the TestRoom` even though the lock was unlocked and this is what I got when Siri reported it didnt hear back:

  Accessory [Homebridge] Setting Characteristic "Lock Target State" to value false +0ms
  EventedHTTPServer [::ffff:10.0.0.13] Sending HTTP event '11.8' with data: {"characteristics":[{"aid":11,"iid":8,"value":22.2}]} +16s
  EventedHTTPServer [::ffff:10.0.0.13] Sending HTTP event '14.8' with data: {"characteristics":[{"aid":14,"iid":8,"value":12.1}]} +12s

**Comment by walksonair** [comment]
@leonmf, I also deleted my entire home and re did everything from scratch. It's a very weird situation for me as Siri still doesnt control my garage doors and my locks. It works great with the light I just tried...and again, the weird part is that the Home App works flawlessly but not Siri.

**Comment by KhaosT** [comment]
by comparing the log, the success one looks like this 

```
Accessory [Homebridge] Processing characteristic set: [{"aid":31,"iid":9,"value":1}] +0ms
Accessory [Homebridge] Setting Characteristic "Lock Target State" to value 1 +0ms
EventedHTTPServer [::ffff:10.0.0.10] Sending HTTP event '31.9' with data: {"characteristics":[{"aid":31,"iid":9,"value":1}]} +362ms
EventedHTTPServer [::ffff:10.0.0.13] Sending HTTP event '31.9' with data: {"characteristics":[{"aid":31,"iid":9,"value":1}]} +0ms
EventedHTTPServer [::ffff:10.0.0.4] Muting event '31.9' notification for this connection since it originated here. +1ms
EventedHTTPServer [::ffff:10.0.0.4] HTTP Response is finished +0ms
```

and the failed one looks like this 

```
Accessory [Homebridge] Processing characteristic set: [{"aid":31,"iid":9,"value":true}] +0ms
Accessory [Homebridge] Setting Characteristic "Lock Target State" to value true +0ms
EventedHTTPServer [::ffff:10.0.0.13] Sending HTTP event '11.8' with data: {"characteristics":[{"aid":11,"iid":8,"value":23.4}]} +18s
EventedHTTPServer [::ffff:10.0.0.4] Sending HTTP event '11.8' with data: {"characteristics":[{"aid":11,"iid":8,"value":23.4}]} +1ms
EventedHTTPServer [::ffff:10.0.0.4] Client connection closed +43s
```

I think the plugin failed to handle the case where Siri sent value ``true`` instead of ``1`` and failed to send response, causing Homebridge blocking the connection and eventually time out. This might be related to iOS 10.2 or a server side change in Siri. As for now, I'd suggest you contact plugin developer to add a workaround to handle a boolean value for ``Lock Target State`` to workaround this issue.

**Comment by walksonair** [comment]
I will try sending the log to the ST plug-in developer, thanks for your help! Could you help me understand why the lights that I just added seem to work fine with both HOME (used 0 & 1) and Siri (used true & false). Here's that log:

Accessory [Homebridge] Processing characteristic set: [{"aid":17,"iid":8,"value":1}] +0ms
  Accessory [Homebridge] Setting Characteristic "On" to value 1 +0ms
  EventedHTTPServer [::ffff:10.0.0.13] Sending HTTP event '17.8' with data: {"characteristics":[{"aid":17,"iid":8,"value":1}]} +446ms
  EventedHTTPServer [::ffff:10.0.0.4] Muting event '17.8' notification for this connection since it originated here. +0ms
  EventedHTTPServer [::ffff:10.0.0.4] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:10.0.0.4] HTTP request: /characteristics +1s
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /characteristics +0ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":17,"iid":8,"value":0}] +1ms
  Accessory [Homebridge] Setting Characteristic "On" to value 0 +0ms
  EventedHTTPServer [::ffff:10.0.0.13] Sending HTTP event '17.8' with data: {"characteristics":[{"aid":17,"iid":8,"value":0}]} +644ms
  EventedHTTPServer [::ffff:10.0.0.4] Muting event '17.8' notification for this connection since it originated here. +1ms
  EventedHTTPServer [::ffff:10.0.0.4] HTTP Response is finished +0ms
  EventedHTTPServer [::ffff:10.0.0.13] Sending HTTP event '17.8' with data: {"characteristics":[{"aid":17,"iid":8,"value":true}]} +96ms
  EventedHTTPServer [::ffff:10.0.0.4] Sending HTTP event '17.8' with data: {"characteristics":[{"aid":17,"iid":8,"value":true}]} +0ms
  EventedHTTPServer [::ffff:10.0.0.13] Sending HTTP event '17.8' with data: {"characteristics":[{"aid":17,"iid":8,"value":false}]} +2s
  EventedHTTPServer [::ffff:10.0.0.4] Sending HTTP event '17.8' with data: {"characteristics":[{"aid":17,"iid":8,"value":false}]} +1ms
  EventedHTTPServer [::ffff:10.0.0.4] HTTP request: /characteristics +4s
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /characteristics +0ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":17,"iid":8,"value":true}] +1ms
  Accessory [Homebridge] Setting Characteristic "On" to value true +0ms
  EventedHTTPServer [::ffff:10.0.0.13] Sending HTTP event '17.8' with data: {"characteristics":[{"aid":17,"iid":8,"value":true}]} +330ms
  EventedHTTPServer [::ffff:10.0.0.4] Muting event '17.8' notification for this connection since it originated here. +1ms
  EventedHTTPServer [::ffff:10.0.0.4] HTTP Response is finished +0ms
  EventedHTTPServer [::ffff:10.0.0.4] HTTP request: /characteristics +13s
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /characteristics +0ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":17,"iid":8,"value":false}] +1ms
  Accessory [Homebridge] Setting Characteristic "On" to value false +0ms
  EventedHTTPServer [::ffff:10.0.0.13] Sending HTTP event '17.8' with data: {"characteristics":[{"aid":17,"iid":8,"value":false}]} +643ms
  EventedHTTPServer [::ffff:10.0.0.4] Muting event '17.8' notification for this connection since it originated here. +1ms
  EventedHTTPServer [::ffff:10.0.0.4] HTTP Response is finished +0ms

**Comment by gijoecool** [comment]
I agree with @KhaosT. Something similar happened for me after updating to 10.2 and using homebridge-zway.

**Comment by walksonair** [comment]
@gijoecool, what was the outcome of your issue? Did you have to contact the developer of your plug-in?

**Comment by KhaosT** [comment]
Because most plugin developers assume ``true`` == ``1`` so it should work in most of cases that expect a boolean value. ``Lock Target State`` itself is defined as a integer enum which developers expects numerical values like 0,1,2 and if they use strict logic to compare the requested value, it may miss the case causing callback not being invoked.

**Comment by gijoecool** [comment]
I ended up modifying the code and submitting a PR. It's probably something really simple... but I don't have ST so I wouldn't be able to test.

**Comment by walksonair** [comment]
Yeah, I have no clue how to modify the code on my own. I've setup an issue on the ST plugin GitHub page...
