### ISSUE TITLE
[Homebridge Server] ERROR: No 'config.json' found!

### ISSUE THREAD

**Issue by Slip7000** [nfarina/homebridge#1001]
HI all

I'm also new to this Homebridge home automation and having problems starting my Homebridge.
 
My initial aim is to have a Homebridge server running on a Mac with a MQTT server to control my Sonoff's in my home that I have loaded with @arendst custom firmware.

So I loaded the Homebridge via this guide https://github.com/nfarina/homebridge 
and got this error:

MQTT:.homebridge MQTT$ homebridge
[12/21/2016, 3:53:07 PM] Loaded plugin: homebridge-server
[12/21/2016, 3:53:07 PM] Registering platform 'homebridge-server.Server'
[12/21/2016, 3:53:07 PM] ---
[12/21/2016, 3:53:07 PM] Loaded config.json with 1 accessories and 1 platforms.
[12/21/2016, 3:53:07 PM] ---
[12/21/2016, 3:53:07 PM] Loading 1 platforms...
[12/21/2016, 3:53:07 PM] [Homebridge Server] Initializing Server platform...
[12/21/2016, 3:53:07 PM] [Homebridge Server] !!!
[12/21/2016, 3:53:07 PM] [Homebridge Server] !!!
[12/21/2016, 3:53:07 PM] [Homebridge Server] ERROR: No 'config.json' found!
[12/21/2016, 3:53:07 PM] [Homebridge Server] Please specify the path of your 'config.json'! E.g.: '-U /home/pi/.homebridge'

But the config.json file is in the .homebridge 

Please assist

**Comment by radinsky** [comment]
Please read README and follow instructions:

> Once you've installed a Plugin or two, you can run Homebridge again:
> 
> $ homebridge
> Couldn't find a config.json file [snip]
> However, Homebridge won't do anything until you've created a config.json file containing your accessories and/or platforms. You can start by copying and modifying the included config-sample.json file which includes declarations for some example accessories and platforms. Each Plugin will have its own expected configuration; the documentation for Plugins should give you some real-world examples for that plugin.
> 
> NOTE: Your config.json file MUST be inside of .homebridge, which is inside of your home folder. On MacOS and Linux, the full path for your config.json would be ~/.homebridge/config.json. Any error messages will contain the exact path where your config is expected to be found.

**Comment by Slip7000** [comment]
@radinsky thank you for the quick reply. 
The config.json file is definitely in the .homebridge folder. If I remove it and try to start homebridge it runs  and with the config_sample.json file.

Maybe my config file is not correct. This is what my config file consist of:

{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:4D:E3:DE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    
    "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",

    "accessories": [
        {
           
        }
    ],

    "platforms": [
        {
		"platform": "Server",
		"port": 8765,
		"name": "Homebridge Server",
		"log" : "/Users/MQTT/Documents/MQTT LOGS"
        }
    ]
}

This is the screenshot of the config file in the .homebridge folder 
<img width="481" alt="config_file in folder" src="https://cloud.githubusercontent.com/assets/17448977/21390574/06f3ba7c-c7a1-11e6-8d35-003f0c87ea04.PNG">

**Comment by Slip7000** [comment]
This is the homebridge running with no config file in .homebridge

<img width="449" alt="homebridge running with default config" src="https://cloud.githubusercontent.com/assets/17448977/21390656/75bc57ca-c7a1-11e6-8616-f181740868a2.PNG">

**Comment by gismo141** [comment]
I have fixed this issue in my current release of the `homebridge-server`-plugin.
Please update and the plugin should now successfully retrieve your `config.json`.

**Comment by Slip7000** [comment]
Thank you for everybody's help ! Got it working! well its not giving me an error anymore. I removed the brackets in my config file and now its working after the update.
