### ISSUE TITLE
How to setup iptables with homebridge

### ISSUE THREAD

**Issue by farion** [nfarina/homebridge#1003]
Hi,

I'm running homebridge alongside with some other services on a linux machine. Basically this machine is secured by iptables, which only opens specific ports for in and out. I'm dropping everything except what I especially need. In short, I do whitelisting.

I opened the ports homebridge is listening on (8283 and 51826  for both ipv4 and ipv6). And initially I'm able to connect with my iPhone. Everything works, I can get all my devices and control them. I'm using FHEM only btw. no other plugins are active. In the homebridge logs I see basically what happens. But after some time the homebridge device can not be accessed anymore without any further error message, neither on the iphone nor in the homebridge log (which I set to debug). If I restart homebridge everything works fine again for some time till the issue arrises again.

If I do not setup iptables the connection does not break.

Do I need something special with iptables? Maybe a range of ports like it is necessary for FTP?

Best,
farion

**Comment by NorthernMan54** [comment]
Homebridge uses mdns/bonjour for device discovery which I believe is on udp port 5353.  You would need this configured as well.  If you watch the iptables logging doesn't it show the dropped packets?
