### ISSUE TITLE
Auto restart homebridge when it has stopped?

### ISSUE THREAD

**Issue by D-an-W** [nfarina/homebridge#1008]
Hi folks,
Not a bug, more of a request.
Would anyone know of a way to get home bridge to restart when stops (Not sure why it is stopping)?

**Comment by klaasjoerg** [comment]
Hi, I just created a simple bash-shell-script for that job. Just looks if a process is still running, and if not, it simply restarts honebridge again.  It's more or less a one-line script.... ;-)

**Comment by NorthernMan54** [comment]
@D-an-W the proper way of doing this is with systemd if your system supports this.   Take a look at this

https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi#running-homebridge-on-bootup-systemd.

**Comment by D-an-W** [comment]
Thanks, I am currently using the init.d method from that page which I guess is why it doesn't restart if it stops for any reason?

I will try and move across to the systemd method.

**Comment by roe1974** [comment]
@klaasjoerg
Can you send me the bash-shell-script for restarting homebridge (init.d) when stopped due to failure ?
thx, richard

**Comment by justme-1968** [comment]
i suggest using node forever for this. it works perfectly.

**Comment by roe1974** [comment]
@justme-1968 
ok, how to use node-forever exactly ?
i am currently starting homebridge with init.d .....

**Comment by justme-1968** [comment]
just have a look at the docu at https://github.com/foreverjs/forever

**Comment by roe1974** [comment]
sorry ... i allready looked at the docu ... thats to complicated for me ;-)
is there a "how to" for homebridge anywhere ? ;-)

**Comment by klaasjoerg** [comment]
@roe1974 
Actually, meanwhile I am not using this bash-shell-check-script anymore, but systemctl/service and defined there to restart if something goes wrong. However, below you'll find the possibly easiest way of starting something, check if it's still there and restart if it crashed. Works fine.

```
#!/bin/bash
sleep 60
while :
do
ps -xa | grep -i homebridge | grep -v grep || su - pi -c "/usr/bin/homebridge > /dev/null 2>&1 &"
sleep 60
done
```
Just start the above script during system start or manually with `nohup restartscript.sh &`

Good luck.

**Comment by roe1974** [comment]
@klaasjoerg 

THX a LOT !!!

but i normaly restart homebridge with:

sudo /etc/init.d/homebridge restart

Is that true with your script?

Richard

**Comment by klaasjoerg** [comment]
You still can do that. But it's important then, that you also start the shell-script which then in turn restarts homebridge in case it crashes.....

**Comment by roe1974** [comment]
@klaasjoerg 
ok..... 2 questions:
I understand:

ps -xa | grep -i homebridge | grep -v grep ||

but here

su - pi -c "/usr/bin/homebridge > /dev/null 2>&1 &

you start homebridge with user "pi" ? .... my homebridge is running with user "root" ... so i have to change here to root ?

... and how can i stop the shell-script to stop homebridge for changes ?

thx ! Richard

**Comment by klaasjoerg** [comment]
You can start it however you like it. That's how I ran it.
Stopping is as usual just kill .....  Should be easy with sufficient linux know how... ;-)

**Comment by vijaydembla1** [comment]
> @roe1974
> Actually, meanwhile I am not using this bash-shell-check-script anymore, but systemctl/service and defined there to restart if something goes wrong. However, below you'll find the possibly easiest way of starting something, check if it's still there and restart if it crashed. Works fine.
> 
> ```
> #!/bin/bash
> sleep 60
> while :
> do
> ps -xa | grep -i homebridge | grep -v grep || su - pi -c "/usr/bin/homebridge > /dev/null 2>&1 &"
> sleep 60
> done
> ```
> Just start the above script during system start or manually with `nohup restartscript.sh &`
> 
> Good luck.

Hi,
Just trying this script and it doesn’t appear to be working in my case. Would be helpful if you could provide step by step instructions on this.

Currently I have created a script with name homebridge.sh in /home/Pi folder
That script includes all what you mentioned above and than included a line in RC.local as 

/home/Pi/homebridge.sh &

I have double checked the location of homebridge and is correct

Please help
