### ISSUE TITLE
Raspberry Pi instructions update, new node_modules path

### ISSUE THREAD

**Issue by robertvorthman** [nfarina/homebridge#1009]
When I got to these instructions: `cd /usr/local/lib/node_modules/homebridge/` I got error `No such file or directory`.  Maybe Raspian was updated because the path is now `/usr/lib/node_modules/homebridge`

**Comment by GatoPharaoh** [comment]
did you install node using the apt-get method? because the wiki states that this will change the directory from` /usr/local/lib` to `/usr/lib/`

**Comment by robertvorthman** [comment]
Oh whoops.  I did not see that note.  I use these instructions to install node:

http://thisdavej.com/beginners-guide-to-installing-node-js-on-a-raspberry-pi/#install-node
