### ISSUE TITLE
Illegal Instruction

### ISSUE THREAD

**Issue by LiljebergXYZ** [nfarina/homebridge#1011]
Hello,

As I try to run homebridge on my raspberry pi I get the following output
```
pi@berry ~ $ homebridge
Illegal instruction
```

Is there any known issue?

**Comment by jespertheend** [comment]
I'm getting this issue too all of a sudden, what fixed it for you?

**Comment by LiljebergXYZ** [comment]
@jespertheend Oh shoot, I was sure I had written the reason all those years ago. But I am fairly sure I resolved it by completely re-installing node. I believe it's a bug in the ARM version of node

**Comment by jespertheend** [comment]
Hmm alright thanks! Weird, it was working just fine yesterday. I haven't tried rebooting my system yet (I want to figure out what caused it first to prevent it from happening again) but if that doesn't work I'll be sure to reinstall node. Thanks!

**Comment by jespertheend** [comment]
Rebooting fixed it. I guess we'll never know what caused it..

**Comment by LiljebergXYZ** [comment]
It's certainly a strange occurrence. I experienced it this one time in 2016, and I've never seen it since

**Comment by jespertheend** [comment]
Ah alright well then it's probably not worth it to figure out the cause. Also, I don't even think it's related to homebridge anyway, since I was getting the same error when trying to start a node shell.

**Comment by LiljebergXYZ** [comment]
Indeed, as I said it's a node issue and it has nothing to do with homebridge. Hence why reinstalling node could've been a solution
