### ISSUE TITLE
Hombridge install fails on Windows 10

### ISSUE THREAD

**Issue by rafi1975** [nfarina/homebridge#1012]
Hi,

I'm just trying to install Homebridge on Windows 10 and it fails with the following error:

Failed at the mdns@2.3.3 install script 'node-gyp rebuild

node v7.3.0
npm v.3.10.10

Can anyone help, please?

Thanks,

Rafal

**Comment by gitKad** [comment]
Same issue

I have:
- mdns 2.3.3
- Python 2.7.13
- NodeJs 6.9.1
- node-gyp 3.4.0
- npm 4.1.1

**Comment by Dirtrunner702** [comment]
Did you both install the full visual studio portion of the walk through?

**Comment by gitKad** [comment]
I did install Visual Studio Communitiy and created a C++ project like the wiki page said.

**Comment by rafi1975** [comment]
Hi,

Yup. The same with me as per the Wiki article - Microsoft Visual Studio
Community 2015.
