### ISSUE TITLE
Uninstall Homebridge to fix not paring issue?

### ISSUE THREAD

**Issue by Flawl3ssSWE** [nfarina/homebridge#1013]
Hi my homebridge wont show up in the home app so i wonder if there is some way to uninstall homebridge to get a fresh start so I can solve the problem!

**Comment by KhaosT** [comment]
Remove the .homebridge folder under your user directory.

Best Wishes,
Tian

**Comment by cerniuk** [comment]
How about the /usr/local/node_modules/homebridge directory?
