### ISSUE TITLE
433mhz dimmer 

### ISSUE THREAD

**Issue by Flawl3ssSWE** [nfarina/homebridge#1014]
Hi I got a Nexa WMR-252 for christmas. It is a 433mhz reciver that you place in your ceiling light. I wonder how if someone have code for doing it with homebridge. So i can controll it with my phone and turn the light % up and down.
Pre thanks,
Anton

**Comment by ehusar** [comment]
If it is 433mhz then it is pretty easy to control.  First you need to know what the codes that are for the remote buttons.  Every RF remote button has a unique code.  I am guessing your dinner has a code that the device seems and reduces the light down 10%.  

I have a Raspberry setup with an RF receiver on it. A receiver cost less than $10.  I can point any RF remote at it and press a button. The raspberry then shows me the code.  Once I know the code then I use codesend that is part of an rfoutlets script to send them which is entered it my config file as an accessory.    

If you want more details I can come back and comment to give you specifics on setting this up.  I didn't write any of the code by the way.  It is all done by people before us and works great.

**Comment by Flawl3ssSWE** [comment]
I do aswell have a raspberry pi. I would love to get your way of doing it. I haven't jet been able to install it jet but hopefully soon. I just dont know how to get the dimming codes when i have installed it. The code for on and off have I been able to get for other devices so that should be no problems. But the dimming codes am i unsure if i will be able to get. I think that that's probably done by a normal "wall" dimmer. 

Thanks for the help!

**Comment by ehusar** [comment]
Did you get a RF receiver and transmitter yet?

**Comment by Flawl3ssSWE** [comment]
@ehusar Yes I got a normal 433mhz transmitter and reciver but I haven't installed the wall dimmer jet.

**Comment by Flawl3ssSWE** [comment]
Now have I finally gotten it installed. It works by using the Telldus-Live plugin!

Thanks for the help!
