### ISSUE TITLE
Is it normal about the Temperature setting in the file of HomeKitTypes.js

### ISSUE THREAD

**Issue by uqc** [nfarina/homebridge#1015]
Characteristic.CurrentTemperature = function() {
  Characteristic.call(this, 'Current Temperature', '00000011-0000-1000-8000-0026BB765291');
  this.setProps({
    format: Characteristic.Formats.FLOAT,
    unit: Characteristic.Units.CELSIUS,
    maxValue: 100,
    minValue: 0,    ### <==== ###  
    minStep: 0.1,
    perms: [Characteristic.Perms.READ, Characteristic.Perms.NOTIFY]
  });
  this.value = this.getDefaultValue();
};

Thanks.

**Comment by NorthernMan54** [comment]
Yes, this is normal/expected.   Take a look at this issue with hap-nodejs, where they show how to properly correct if for your plugin.

https://github.com/KhaosT/HAP-NodeJS/issues/251#issuecomment-225127963

Also, as this is an hap-nodejs file, this issue should be raised there.

**Comment by uqc** [comment]
Many thanks for the guides.
