### ISSUE TITLE
Groups and Scenes now working with more than one accessory.

### ISSUE THREAD

**Issue by ehusar** [nfarina/homebridge#1017]
I have everything setup up and running on a Raspberry Pi 3.   I have 5 RF 433mhz outlets that all work when I turn them on/off individually.  I created both a Group and a Scene for the outlets in the Living Room.  Here is some testing I am doing that hopefully helps explain what is happening.  When in a Group or Scene no outlets turn on.

I am running tail -f /var/log/homebridge.err to see these results.

First I turn on two outlets individually.  Each one turns on a lamp without issue.  Here is the homebridge.err results.

`Wed, 28 Dec 2016 08:26:59 GMT EventedHTTPServer [::ffff:10.0.112.18] HTTP request: /characteristics
Wed, 28 Dec 2016 08:26:59 GMT HAPServer [A1:B2:C3:E3:CE:AB] HAP Request: PUT /characteristics
Wed, 28 Dec 2016 08:26:59 GMT Accessory [House] Processing characteristic set: [{"aid":2,"iid":9,"value":1}]
Wed, 28 Dec 2016 08:26:59 GMT Accessory [House] Setting Characteristic "On" to value 1
Wed, 28 Dec 2016 08:26:59 GMT EventedHTTPServer [::ffff:10.0.112.9] Sending HTTP event '2.9' with data: {"characteristics":[{"aid":2,"iid":9,"value":1}]}
Wed, 28 Dec 2016 08:26:59 GMT EventedHTTPServer [::ffff:10.0.112.21] Sending HTTP event '2.9' with data: {"characteristics":[{"aid":2,"iid":9,"value":1}]}
Wed, 28 Dec 2016 08:26:59 GMT EventedHTTPServer [::ffff:10.0.112.18] Muting event '2.9' notification for this connection since it originated here.
Wed, 28 Dec 2016 08:26:59 GMT EventedHTTPServer [::ffff:10.0.112.18] HTTP Response is finished
Wed, 28 Dec 2016 08:27:01 GMT EventedHTTPServer [::ffff:10.0.112.18] HTTP request: /characteristics
Wed, 28 Dec 2016 08:27:01 GMT HAPServer [A1:B2:C3:E3:CE:AB] HAP Request: PUT /characteristics
Wed, 28 Dec 2016 08:27:01 GMT Accessory [House] Processing characteristic set: [{"aid":3,"iid":9,"value":1}]
Wed, 28 Dec 2016 08:27:01 GMT Accessory [House] Setting Characteristic "On" to value 1
Wed, 28 Dec 2016 08:27:01 GMT EventedHTTPServer [::ffff:10.0.112.9] Sending HTTP event '3.9' with data: {"characteristics":[{"aid":3,"iid":9,"value":1}]}
Wed, 28 Dec 2016 08:27:01 GMT EventedHTTPServer [::ffff:10.0.112.21] Sending HTTP event '3.9' with data: {"characteristics":[{"aid":3,"iid":9,"value":1}]}
Wed, 28 Dec 2016 08:27:01 GMT EventedHTTPServer [::ffff:10.0.112.18] Muting event '3.9' notification for this connection since it originated here.
Wed, 28 Dec 2016 08:27:01 GMT EventedHTTPServer [::ffff:10.0.112.18] HTTP Response is finished`

Now I created a group and try to turn on the same two outlets in a group. Here is err results again.  The outlets never turn on the lamps connected to them.

`Wed, 28 Dec 2016 08:31:13 GMT EventedHTTPServer [::ffff:10.0.112.18] HTTP request: /characteristics
Wed, 28 Dec 2016 08:31:13 GMT HAPServer [A1:B2:C3:E3:CE:AB] HAP Request: PUT /characteristics
Wed, 28 Dec 2016 08:31:13 GMT Accessory [House] Processing characteristic set: [{"aid":3,"iid":9,"value":1},{"aid":2,"iid":9,"value":1}]
Wed, 28 Dec 2016 08:31:13 GMT Accessory [House] Setting Characteristic "On" to value 1
Wed, 28 Dec 2016 08:31:13 GMT Accessory [House] Setting Characteristic "On" to value 1
Wed, 28 Dec 2016 08:31:13 GMT EventedHTTPServer [::ffff:10.0.112.9] Sending HTTP event '3.9' with data: {"characteristics":[{"aid":3,"iid":9,"value":1}]}
Wed, 28 Dec 2016 08:31:13 GMT EventedHTTPServer [::ffff:10.0.112.21] Sending HTTP event '3.9' with data: {"characteristics":[{"aid":3,"iid":9,"value":1}]}
Wed, 28 Dec 2016 08:31:13 GMT EventedHTTPServer [::ffff:10.0.112.18] Muting event '3.9' notification for this connection since it originated here.
Wed, 28 Dec 2016 08:31:13 GMT EventedHTTPServer [::ffff:10.0.112.9] Sending HTTP event '2.9' with data: {"characteristics":[{"aid":2,"iid":9,"value":1}]}
Wed, 28 Dec 2016 08:31:13 GMT EventedHTTPServer [::ffff:10.0.112.21] Sending HTTP event '2.9' with data: {"characteristics":[{"aid":2,"iid":9,"value":1}]}
Wed, 28 Dec 2016 08:31:13 GMT EventedHTTPServer [::ffff:10.0.112.18] Muting event '2.9' notification for this connection since it originated here.
Wed, 28 Dec 2016 08:31:13 GMT EventedHTTPServer [::ffff:10.0.112.18] HTTP Response is finished`

Does this look normal or give an indication why Groups or Scenes are not working for me?

**Comment by n8henrie** [comment]
What library are you using to switch them on and off?

homebridge-rcswitch-gpiomem has a [known issue](https://github.com/n8henrie/homebridge-rcswitch-gpiomem/issues/3) that I haven't sorted out yet.
