### ISSUE TITLE
what bulbs are supported by homebridge?

### ISSUE THREAD

**Issue by sunsgs** [nfarina/homebridge#1018]
And what if i close the light normally ? (with the native switch)

**Comment by maragelis** [comment]
There are many plugins for known bulbs (Phillips,Lifx...) you can also use mqtt to open close relays. 
Here are some plugins https://www.npmjs.com/search?q=homebridge

**Comment by ehusar** [comment]
I recently found a switch that is very small.  It's designed to fit inside the switch box behind your standard light switch.   They say is will update the light state if you flip the switch manually.   It's an alternative to buying special bulbs. Google this:   Enerwave Z-Wave Plus ZWN-RSM1 Hidden Switch

I've not tried it yet but it's on my list.
