### ISSUE TITLE
Accessories "not responding"

### ISSUE THREAD

**Issue by AdamskiEM** [nfarina/homebridge#1019]
Hi,
I seem to be having a persistent issue with homebridge on my Ubuntu server..

When I first start it up (clean ~/.homebridge/persist directory), my iPhone can find it fine, and add all the accessories. Everything is good for a couple of days, Siri works as expected etc.

However after a while, the Home app, and anything else I try to use e.g. Eve, show all the accessories as not responding. (The message in Eve for each accessory is "The accessory is currently blocked")

What is strange though, is if I keep push notifications enabled for my front-door lock, what I lock and unlock it (physically, not via an app), the notifications **still come through** from the Home app... even though as far as it is concerned, the accessory is not responding.

The only reliable way I have managed to find to get it working again is to shut down Homebridge, delete the contents of the persist directory, and then re-add the device back on my phone... Or, delete the home from my iCloud and re-add it within the Home app. But since I then I have to set up all the room configs again, it's not great.

My config file is very simple... I am only using the smartthings homebridge plugin, no other accessories. Looking at the homebridge log file, there are no errors. If I stop and start the service, there are no errors.

If anyone has any ideas it'd be very much appreciated. I'd love to have a consistently working Home app!

![img_7521](https://cloud.githubusercontent.com/assets/5247209/21523692/58fbf930-cd08-11e6-85e1-8f9bc91dac31.PNG)

**Comment by maragelis** [comment]
had this problem, check what you are sending to homebridge sometimes a bad value can do this like sending 1 instead of "1" or true (string) instead of true (bool).

**Comment by AdamskiEM** [comment]
I thought the same thing while still having my Heatmiser wifi thermostat running via a plugin. But I've literally got the Smartthings plugin and nothing else now. Without debugging the entire Smartthings plugin, I can't really tell

**Comment by ooii** [comment]
I'm having the same behavior but restarting homebridge fixes the "not responding" status.
