### ISSUE TITLE
After Change network 

### ISSUE THREAD

**Issue by Sunbelife** [nfarina/homebridge#1020]
How can i reset homebridge?
or do i need to reset homebridge?

after I change network, my phone can't find homebridge, and here is the log :

```
pi@raspberrypi:~/homebridge $ homebridge
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[12/29/2016, 5:01:06 AM] Loaded plugin: homebridge-yeelight
[12/29/2016, 5:01:06 AM] Registering platform 'homebridge-yeelight.yeelight'
[12/29/2016, 5:01:07 AM] ---
[12/29/2016, 5:01:07 AM] Loaded config.json with 0 accessories and 1 platforms.
[12/29/2016, 5:01:07 AM] ---
[12/29/2016, 5:01:07 AM] Loading 1 platforms...
[12/29/2016, 5:01:07 AM] [yeelight] Initializing yeelight platform...
[12/29/2016, 5:01:07 AM] [yeelight] YeePlatform Init
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[12/29/2016, 5:01:07 AM] [yeelight] DidFinishLaunching
[12/29/2016, 5:01:07 AM] Homebridge is running on port 51825.
add to multicast group
listen on 0.0.0.0
no did or loc found!
[12/29/2016, 5:01:07 AM] [yeelight] cached accessory: 0x0000000002e031a1
already in device list!
connect ok!
[12/29/2016, 5:01:07 AM] [yeelight] accesseory reachable
[12/29/2016, 5:01:07 AM] [yeelight] dev connected 0x0000000002e031a1 true
```

**Comment by GatoPharaoh** [comment]
could you elaborate a little - you are changing from which to which network?

**Comment by AdamskiEM** [comment]
This sounds like basically what I'm getting... (#1019) Maybe... It works fine while you're on the same network, but as soon as I go out of the house for decent period of time, when I get back, my phone can't talk to any of the accessories

**Comment by jyen** [comment]
I think I have the same issue as well (#1030). Although, I see this happen more often when changing network, but while staying on the same network, it eventually become like that as well. The only way I am able to fix it is to reconnect homebridge via homekit ( which sometimes involve removing persist folder & changing mac address) which is quite annoying as this happens pretty frequent for me.

**Comment by mfang0126** [comment]
I got the same problem as well. But the wemo seems working perfectly.

**Comment by Sunbelife** [comment]
Finally I change a router to solve this problem, It seems my router can't support some protocol or something else.
If you have this problem, you could try to change a router.

**Comment by Dirtrunner702** [comment]
You could also hardwire your homekit hub (apple tv) and hombridge server to the same lan. that resolved my issues. no wifi from homekit hub to hombridge. Google OnHub has IGMP enabled by default, which some have said caused trouble but it has not proven to be the case for me. 
see my last comment for more details.  https://github.com/nfarina/homebridge/issues/1059
