### ISSUE TITLE
Blinds automation

### ISSUE THREAD

**Issue by Flawl3ssSWE** [nfarina/homebridge#1021]
Hi I have today ordered a tubular motor with built in 433 mhz. To automate my window blind so it can go up and down by "itself". I wonder if someone out there has the code for homebridge to be able to run it up and down. Even better would it be if someone has code that can set it to like 10%,20%,30% etc. Like a slider in the home app. 

Pre Thanks,
Anton

**Comment by nitaybz** [comment]
Homebridge-NooLite-HTTP-Blinds by JenRus
homebridge-blinds-udp by nitaybz(me)

both are having the option to open the curtains X%, you just need a RF module that can learn the remote and can get HTTP requests or UDP packets.

I'm using Broadlink RM2 Pro to control the RF switched in my house and I send it UDP packets that I've captured on my phone.

**Comment by alisdairjsmyth** [comment]
When I looked to automate my blinds I did so based on the sun position in the sky and climatic conditions.  I packaged this logic in a Node-RED node called [node-red-contrib-blindcontroller](https://github.com/alisdairjsmyth/node-red-contrib-blindcontroller).  Actual control of the blinds will require you to reverse engineer the RF signals.  The above mentioned Node-RED node might be of interest to you to compliment integration with homebridge once you are able to programatically send commands to your blinds.

**Comment by simonrb2000** [comment]
I simply learnt the open/close RF commands (RFXCOM) and use domoticz to control my blinds - they open/close for sunrise/sunset automatically. I have exposed them to HomeKit using the fantastic edomoticz platform for homebridge. I can now say open/close all blinds or name specific blinds to open and close.

I haven't yet set % using this method - I'm not even sure it would be possible as the blinds are a simple open/close/stop. (433mhz ?40 eBay jobby) but it suits my needs. Hope this helps.

On 31 Dec 2016, at 11:51, alisdairjsmyth <notifications@github.com<mailto:notifications@github.com>> wrote:


When I looked to automate my blinds I did so based on the sun position in the sky and climatic conditions. I packaged this logic in a Node-RED node called node-red-contrib-blindcontroller<https://github.com/alisdairjsmyth/node-red-contrib-blindcontroller>. Actual control of the blinds will require you to reverse engineer the RF signals. The above mentioned Node-RED node might be of interest to you to compliment integration with homebridge once you are able to programatically send commands to your blinds.

-

**Comment by Flawl3ssSWE** [comment]
Thanks for the answers. Right now my setup of a 433mhz transmittor and reciver. Is not able to pick up any 433mhz code from the remote. So I wonder if someone out there can help me to find a way to decode it. 

Pre Thanks,
Anton

**Comment by alisdairjsmyth** [comment]
Here are a couple links I used:

   -
   https://github.com/r-ohare/Amateur-SIGINT/blob/master/Amateur%20Signals%20Intelligence.pdf

   - http://gqrx.dk/doc/practical-tricks-and-tips

I used Gqrx and a RTL-SDR dongle to record the transmission and Audacity to
read and decipher.  Good luck.

**Comment by Flawl3ssSWE** [comment]
I would like to it with something that I already have but ty anyways

**Comment by toshibochan** [comment]
You need 433Mhz RF Transmitter and Receiver Link Kit for Arduino/ARM/MCU WL https://www.amazon.com/dp/B016V18KZ8/ref=cm_sw_r_cp_api_N6lBybQQ6M0CD

Here is tutorial video you can use to scan the codes https://youtu.be/5UUazFbK-Hg

**Comment by ehusar** [comment]
What remote is it? Do you have a link to it?

**Comment by Flawl3ssSWE** [comment]
@ehusar I bought it from a Swedish site but I will link one with the same article number: http://www.bofumotor.com/index_in.asp?id=32 it at the Swedish website: https://www.m.nu/fjarrkontroller-433mhz/fjarrkontroll-till-433mhz-tubmotor the article number is BF-101

**Comment by ehusar** [comment]
It has three different frequency setting.  Is there an option to set it to one particular one?

**Comment by Flawl3ssSWE** [comment]
@ehusar No I haven't found a way of doing it. But I'm able to use a Tellstick classic to controll it and that one only supports 433mhz.

**Comment by Flawl3ssSWE** [comment]
@ehusar at the Swedish site they say only say that the remote supports 433mhz
