### ISSUE TITLE
Question:  multiple RPi setup

### ISSUE THREAD

**Issue by ehusar** [nfarina/homebridge#1023]
I have Homebridge setup and working on a single RPi located in my living room.  I also have a RPi in my garage that is used to control the garage door and a temp sensor.  If I want to get the temp and control my garage do I need to install Homebridge on the second RPi in the garage?

**Comment by klaasjoerg** [comment]
I would say yes, as it would simply show as a second homebridge delivering additional devices to HomeKit. Of course you should change the serial number/key as well the name to differentiate them easier. Worked at least fine for me.

**Comment by ehusar** [comment]
Excellent.  Thank you.

**Comment by NorthernMan54** [comment]
Can confirm that having multiple instances of homebridge on multiple rpi's is supported, you just need a unique username in the config. Unique port would also be required if you are running multiple on the same rpi.

**Comment by ehusar** [comment]
Thanks for the response.
