### ISSUE TITLE
value changes are not propagated through the EventedHTTP server

### ISSUE THREAD

**Issue by Kosta-Github** [nfarina/homebridge#1024]
my setup:
* `homebridge 0.4.16`
* `HAP-NodeJS 0.4.20`
* `iPad/iPhone iOS 10.2`
* `AppleTV 9.2(?)`

My value changes are not propagated back the the actual running homekit instances (e.g., the `Home` or `Elgato Eve` apps, and when used as a trigger for an automation, the trigger is also not fired.

I traced it back to this [line in `HAP`](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/util/eventedhttp.js#L156), which returns without sending back the changed values to `homekit`. As soon as I comment this `return` out, it works/updates as expected.

Maybe there is something fishy with the management of the `events` filter stored in `this._events` within the `EventedHTTP` server?

Someone else experienced this issue?

**Comment by jspv** [comment]
Did you ever make any progress on this?  Having similar issues with some of my events, particularly changes in MotionDetected state not being propagated.

**Comment by Kosta-Github** [comment]
no further progress

for me it is only working as expected if I remove/out-comment the line mentioned above...
