### ISSUE TITLE
Homebridge will not response if plugin crash

### ISSUE THREAD

**Issue by littlechu** [nfarina/homebridge#1026]
In general, if one of the plugin is not working correctly and crash, it will causes the entire home bridge to not response to the IOS device.

For example, this issue here: https://github.com/plasticrake/homebridge-hs100/issues/11

When the HS100 plugin fail to access one of the device because the device IP changes, it crash and cause homebridge to not sent response of other device back to the IOS device.

Is it possible for homebridge to send response for the 'OK' device while not response to the non-responsive device?

Also, will be nice if there is a way to clear the accessory directory and reload a plugin in case of failure occur.

**Comment by quacktacular** [comment]
This would be great.

**Comment by snowdd1** [comment]
In general, plugins are supposed not to crash upon simple failures such as an unsuccessful connection attempt.  
However, in some plugins it might be so vital that muting the error in homebridge might be something you do not want. As a plugin programmer for the KNX platform, I want my users with their nose deep in the config if they messed up the connection to the hardware, and not preventing everything went fine. That said, KNX is a fairly stable system and could run for years if you don't want to have security updates on your raspberry bridges and such. Others are known to fail much more frequently, but I would address this to my fellow plugin programmers: Catch exceptions if you do not want the bridge to fail.

## Autostart
To users that do not see any security issues [I saw](https://github.com/nfarina/homebridge/issues/1216#issuecomment-288794639) just run you homebridge as a systemd service with auto restart.  
I did so until I noticed that I wanted to see the broken thing so I can better fix it before restarting it. I usually have uptimes of several months before shutting it down for Raspbian update.

## Fail fast
For my platform I decided that it should fail (throw an exception) if the connection to the hardware is unsuccessful. KNX users usually have their home completely wired, the failure of the bus is fatal to any light switch on the wall, so why not for homebridge? If you think it should come back automatically if the bus wire is live again, see paragraph above.  
If a harmony hub is having its rogue five minutes in which it is inaccessible, the TV set or stereo is unresponsive. Huh, so what? Connect to it later again!

## Error handling in code
While searching for methods to enclose the event handlers in `try ... catch ...` blocks, I learned you simply can't. At least not in a feasible way. If a package you are using fails inside of an event handler your doomed. So much for code reusability, if the code isn't stable it simply does not work. Interesting article [here](https://www.sitepoint.com/proper-error-handling-javascript/)  

# Synopsis
Whenever the libraries used by fellow plugin authors (such as harmony hub) are not stable enough for proper every day use, the platform is supposed to run on a separated bridge instance (using the -U parameter to differentiate the home directories) and run that systemd service with an auto restart parameter.  
For plugins that are supposed to be stable, and you might want to investigate each failure, use an instance without auto restart.

**Comment by GvnCampbell** [comment]
I have been running homebridge as a service with autorestart set as recommended above. I do however have an extra command though so that it emails me whenever it restarts. This gives me an idea as to how often it happens.
