### ISSUE TITLE
on boot using init.d  - unable to resolve host

### ISSUE THREAD

**Issue by ehusar** [nfarina/homebridge#1027]
I am able to start home bridge by SSH and just typing 'homebridge'.  Everything works fine starting the system that way.  

I am trying to get the init.d method of starting it up on boot.  I have run through the instructions and following the steps without issue. I am positive I installed home bridge with the -g option.  When I reboot, homebridge doesn't start on boot.  If I type.  `sudo /etc/init.d/homebridge start`  I get the following message.

```
pi@GarageCam:~ $ sudo /etc/init.d/homebridge start
Starting home bridge
Unable to start, see /var/log/homebridge.log and /var/log/homebridge.err
```

I check homebriget.log and it is empty.  When I check homebridge.err I see the following.

```
sudo: unable to resolve host GarageCam
sudo: /usr/local/bin/homebridge: command not found
sudo: /usr/local/bin/homebridge: command not found
sudo: unable to resolve host GarageCam
sudo: /usr/local/bin/homebridge: command not found
sudo: /usr/local/bin/homebridge: command not found
sudo: unable to resolve host GarageCam
sudo: /usr/local/bin/homebridge: command not found
sudo: unable to resolve host GarageCam
sudo: /usr/local/bin/homebridge: command not found
sudo: /usr/local/bin/homebridge: command not found
sudo: /usr/local/bin/homebridge: command not found
sudo: /usr/local/bin/homebridge: command not found
sudo: /usr/local/bin/homebridge: command not found
sudo: /usr/local/bin/homebridge: command not found
sudo: /usr/local/bin/homebridge: command not found
sudo: /usr/local/bin/homebridge: command not found
```

Seeing the mention of GarageCam which is the hostname of the RPi I have home bridge installed on I checked two files. 

`/etc/hostname` and `/etc/hosts`  

I can verify that the hostnames match and GarageCam shows up correcting on my router.

Then I verify that the hostname is in fact correct like so.

```
pi@GarageCam:~ $ hostname
GarageCam
```

Any ideas why I am getting this error and the init.d is not working for me?

**Comment by ehusar** [comment]
I figured something out but I need help understanding how to fix this.

I compared another RPi homebridge install to the GarageCam RPi install and it led me to the /usr/local/bin/ directory. 

On my fully working version of homebridge this is what my /usr/local/bin looks like.
```
pi@Development:/usr/local/bin $ ls
gpio        node       piscope         rpi-rf_send
homebridge  node-gyp  npm    rpi-rf_receive
```

Now here is the GaragePi /usr/local/bin.  Clearly the home bridge is missing from this directory.

```
pi@GarageCam:/usr/local/bin $ ls

```
 Now sure what why the has happened.  Any suggestions?

**Comment by NorthernMan54** [comment]
It appears that your homebridge was installed without the -g option.   Try the command

which homebridge

It will show where homebridge is running and use that instead of /user/local/bin in your init.d script.

Also you may want to share your init.d script, as it shouldn't have output like that.

**Comment by ehusar** [comment]
I did use -g.  Per the instructions I just didn't install in the local.

> Install Homebridge and dependencies
> 
> (note that /usr/local/lib should be replaced with /usr/lib/ if you installed node using apt-get method above)
> 
> sudo npm install -g --unsafe-perm homebridge hap-nodejs node-gyp
> cd /usr/local/lib/node_modules/homebridge/
> sudo npm install --unsafe-perm lignum
> cd /usr/local/lib/node_modules/hap-nodejs/node_modules/mdns
> sudo node-gyp BUILDTYPE=Release rebuild

I single changed the init.d from this.

```
dir="/home/pi"
cmd="DEBUG=* /usr/local/bin/homebridge"
user="pi"
```

to this...

```
dir="/home/pi"
cmd="DEBUG=* /usr/bin/homebridge"
user="pi"
```

I am not sure what the impact of this is.  Once I did this it not boots at start.
