### ISSUE TITLE
optional characteristics are not recreated for a cached accessory

### ISSUE THREAD

**Issue by Kosta-Github** [nfarina/homebridge#1028]
The `accessory` provided to the `Platform.prototype.configureAccessory(accessory)` always has empty `optionalCharacteristics` arrays for all contained `services`, the mandatory `characteristics` are present/provided as expected.

Whereas a newly created `accessory` for lists the corresponding `optionalCharacteristics` correctly for each added `service`.

Are the missing `optionalCharacteristics` in `configureAccessory()` by intent or a bug?

**Comment by KhaosT** [comment]
It's intentional as homebridge expects plugin to have all services being properly configured when adding the accessory to homebridge. ``configureAccessory`` is for plugin to restore getter and setter after homebridge restart.

**Comment by Kosta-Github** [comment]
is there a way, to query the `optional` characteristics for a given `service`?

**Comment by snowdd1** [comment]
What about the passed **Service[*serviceName*].optionalCharacteristics** array of the API object instead of the instance passed to `configureAccessory`?
