### ISSUE TITLE
HOWTO: Install homebridge from scratch

### ISSUE THREAD

**Issue by nzhome** [nfarina/homebridge#103]
Hope this quick guide helps newbies get up and running fast. this is the steps I just took to get up and running in about 5 minutes.

1) plug in your raspberry pi to your ethernet cable and power.

2) using a web browser goto your router 10.1.1.1  and look in your dhcp table for raspberry pi to get the ip address

3) download putty for windows to connect to your raspberry pi ip address.
http://the.earth.li/~sgtatham/putty/latest/x86/putty.exe

4) login with default username pi with the password raspberry

5) install nodejs with these 3 commands
https://learn.adafruit.com/node-embedded-development/installing-node-dot-js

6) run this before step 7, else you will get an error.
sudo apt-get install libavahi-compat-libdnssd-dev

7) run this command to install homebridge and its dependency modules.
npm install homebridge

8) cd node_modules/homebridge

9) ls  

10) you should now be at this folder prompt: pi@raspberrypi ~/node_modules/homebridge $   run this command to edit your setup, remove any platforms or accessories you do not want using ctrl+K for each line:  

sudo nano config-sample.json

11) press ctrl+O to save as another name  config.json
save as another name: Yes.
ctrl+X

12) ls

13) npm run start

if you get any parse errors, its because the config-sample.json is a complete disaster,  remove any comments including // forward slashes.  and press End to delete those stupid | symbols after milight.. then you might actually get it to work.

**Comment by nfarina** [comment]
Thanks, I've merged this with the previous RPi setup document in the wiki: https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi

Also if you think `config-sample.json` is a mess, then I suggest you make a PR fixing it!
