### ISSUE TITLE
trigger button via HTTP request from IFTTT Maker channel

### ISSUE THREAD

**Issue by farstreet** [nfarina/homebridge#1031]
I want to trigger a switch by sending a HTTP request from an IFTTT applet, using the IFTTT Maker channel.   I am using DynDNS and was considering opening a specific port on my airport to tunnel the request all the way to the machine that is running homebridge.  But I don't seem to be able to find a plugin that would be able to receive this request and trigger the virtual switch.

Pretty sure I'm just looking over it, but have been searching for so long for it now that I decided to give up and just ask here :)

**Comment by benzman81** [comment]
Use my plugin homebridge-http-webhooks ;-)

**Comment by farstreet** [comment]
I found it in the mean time 😀 and it works like a charm!   Only had quite some difficulties to find out how to set up IFTTT maker web request exactly, but once I figured it out, it was super.
