### ISSUE TITLE
NPM Warning. Wanting v4.3.2

### ISSUE THREAD

**Issue by Latouth** [nfarina/homebridge#1032]
pi@Homebridge-PiZero:/usr/local/bin $ sudo npm install -g --unsafe-perm homebridge hap-nodejs node-gyp
npm WARN engine hap-nodejs@0.4.21: wanted: {"node":">=4.3.2"} (current: {"node":"4.0.0","npm":"2.14.2"})
npm WARN engine homebridge@0.4.16: wanted: {"node":">=4.3.2"} (current: {"node":"4.0.0","npm":"2.14.2"})
npm WARN engine hap-nodejs@0.4.20: wanted: {"node":">=4.3.2"} (current: {"node":"4.0.0","npm":"2.14.2"})

Details:

https://blog.wia.io/installing-node-js-v4-0-0-on-a-raspberry-pi
I used that to install NodeJS
Because NodeJS Came installed was an old version from 2014. (0.10.29) 
So I uninstalled it, and installed it using the wiki link.

When I get to https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi#install-homebridge-and-dependencies
And I get that error, I'm using a Raspberry Pi Zero. (16gb micro sd, running a Raspbian Jessie from Nov 11 2016, latest one on the raspberry pi website)

Versions:
gcc (Raspbian 4.9.2-10) 4.9.2
NodeJS V4.0.0

**Comment by gijoecool** [comment]
Can you install using https://nodejs.org/dist/v4.3.2/node-v4.3.2-linux-armv7l.tar.xz? That should solve the version requirement.

**Comment by Latouth** [comment]
I tried using v4.0.0 armv7l, but it came with an error.
Should I attempt the v4.3.2 arm7l?
