### ISSUE TITLE
Deleted homebridge in Home app, some accessories persist and can't be deleted

### ISSUE THREAD

**Issue by jojost1** [nfarina/homebridge#1033]
I deleted homebridge, the hub, from the iOS 10 Home app, some sensors from the homebridge-people plugin are still there and I can't delete them. Also, I don't plan on running Homebridge again in the near future, but trying to run it again gives some errors (see screenshots). Any solutions?

Screenshots:
![schermafbeelding 2017-01-01 om 21 36 23](https://cloud.githubusercontent.com/assets/8880568/21582932/5ab3b94c-d06a-11e6-9c08-b1feefb14ac5.png)
![img_1603](https://cloud.githubusercontent.com/assets/8880568/21582933/6d1aa4c4-d06a-11e6-8d65-e889684bc405.PNG)
![img_1602](https://cloud.githubusercontent.com/assets/8880568/21582934/7056f4a8-d06a-11e6-8ddc-ed0b79c9b411.PNG)

**Comment by klaasjoerg** [comment]
Looks like there is already a running  homebridge-instance and you tried to start it twice...?

**Comment by jojost1** [comment]
Could be. How can I delete the leftover sensors?

**Comment by StallionV** [comment]
On your pie go to home bridge directory and remove the accessories
cd /home/pi/.homebridge
sudo rm -r persist/
sudo rm -r accessories/
