### ISSUE TITLE
How to adjust time / timezone?

### ISSUE THREAD

**Issue by rafacampoamor** [nfarina/homebridge#1036]
My hombridge is logging with one hour "delay" from my timezone. Raspi is with the correct time and timezone, but home bridge must be using GMT. ¿Is there a way to solve this? I need this to be accurate for the "people" plugin to work and I'm completely lost.

**Comment by MrRobotoGit** [comment]
+1 Same here

**Comment by elie195** [comment]
I had a similar issue after fixing the timezone in raspi-config: The homebridge log was still showing timestamps in GMT. Looking at the [logger code](https://github.com/nfarina/homebridge/blob/master/lib/logger.js#L70), it appears it uses the `date.toLocaleString()` method, which should be timezone-specific to your environment. More info about the method [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString).

I just restarted the Pi and the logs started using the correct timestamp.

**Comment by JacVid** [comment]
+1 Same here

**Comment by microfx** [comment]
+1...
