### ISSUE TITLE
Allow setting bridge ID via config.json

### ISSUE THREAD

**Issue by SphtKr** [nfarina/homebridge#104]
Three use cases for this come to mind:

1. If someone wants to run two copies of HomeBridge (e.g. one stable and one less stable)
2. Dorm WiFi or similar shared network?
3. If you make HomeKit "mad" enough at you that you that it won't talk to your ID anymore...I've accomplished this a few times now.

Looks like it'd be fairly easy to implement, I just don't know if there's a downside I'm missing.

**Comment by nfarina** [comment]
Great idea. Number 3 drives me crazy - if you pair and un-pair enough it's rather easy to get into a state where a device is in HomeKit's DB but not exposed to (and deletable) by the user; so iOS just keeps trying to "login" (verify) without success, forever.

**Comment by SphtKr** [comment]
Yep...killing me right now.

Oh, and the friendly name of the bridge too...but that's more a nice-to-have than a needed feature.

**Comment by nzhome** [comment]
is there an easy command that can clear out the homekit database on iphone?

**Comment by SphtKr** [comment]
@nzhome Yes, in iOS settings, go to privacy > HomeKit > Reset HomeKit configuration. 

I've had trouble with it though, it some how broke iCloud sync among my devices (just for HomeKit, but still) that took me a while to sort out. So I've tried to avoid using it and changing the bridge ID a few times instead.

**Comment by nzhome** [comment]
by bridge id, do you mean the username field in app.js that looks like a mac address?

**Comment by SphtKr** [comment]
Yep. I'll do a pull request today probably, simply a matter of putting the stuff in `config.json` and if it's there, allowing it to override the defaults. While I'm in there I'll make it possible to set the bridge label, port and (duh) PIN code as well.
