### ISSUE TITLE
Suggestion: Patchnotes in releases

### ISSUE THREAD

**Issue by jjwedemyer** [nfarina/homebridge#1042]
Hi,
maybe it's would be great to have a changelog in the releases.
Regards.

**Comment by AppleTechy** [comment]
The [commits](https://github.com/nfarina/homebridge/commits/master) section tells you what the changes were suppose to fix as well as you can see the actual code changes

**Comment by plasticrake** [comment]
Actually as a plugin developer this would be very helpful to have at least a brief changelog summary for each release. There have been breaking changes before that has broken my plugin.

@nfarina thoughts?

**Comment by AppleTechy** [comment]
@plasticrake What were your thoughts on implementing it?  Some sort of Wiki page? The only issue I foresee is that so many changes get pushed that it would be time consuming to add a new entry every time a commit is pushed

**Comment by plasticrake** [comment]
I have a [changelog like this](https://github.com/plasticrake/hs100-api/blob/master/CHANGELOG.md) that is updated with each new new version. You can also have a workflow that updates the changelog when the relevant code is committed. When someone is ready to release a new version you can run something like `git log --oneline --decorate` to see the recent commits and make sure the changelog isn't missing anything.

Considering this is used by other plugin developers changes should be communicated. Although the issue I was referring to before was in [HAP-NodeJS](https://github.com/KhaosT/HAP-NodeJS) so unless that repo starts a changelog I wouldn't have known about the breaking changes either.

**Comment by AppleTechy** [comment]
@plasticrake Hmm not exactly sure I am understanding the benefit of this over the commit log. Are you wanting a more indepth explanation of what is occurring in the commit or just an easier way to read the changes than the commit log? The other pertinent person to get involved in making this happen would be @KhaosT. What are your thoughts?

**Comment by KhaosT** [comment]
I mean ideally yes, having changelog attached to each version would make sense... however, most of changes these day only contains one or two commits so I felt it's about the same of reading the commit log between last release and current one?

**Comment by i3laze** [comment]
Really, how's that hard to maintain a Changelog or Release Notes?
Commit list works, but that's not the perfect choise:
https://github.com/nfarina/homebridge/commits/master

Check the example:
https://github.com/arendst/Sonoff-Tasmota/blob/development/sonoff/_releasenotes.ino
