### ISSUE TITLE
Anyway to See Active Running Log On Raspberry Pi

### ISSUE THREAD

**Issue by erfind** [nfarina/homebridge#1043]
Sorry for so many questions, but I'm new to using a Raspberry Pi.  I was wondering if there was any way to see an active (running in real time) log on a Raspberry Pi concerning homebridge activities.  I used to use Console to watch the log file when running homebridge on my iMac, and it was extremely helpful in locating issues.  Is there anything like this for the Raspberry Pi?

**Comment by StallionV** [comment]
tail -f /var/log/homebridge.log

**Comment by flippamike** [comment]
The solution stallionV gave only worked for me when running as a service

**Comment by jsmeyers** [comment]
I recommend using a syslog service like papertrail. I found it helpful for troubleshooting without having to run further infrastructure.
