### ISSUE TITLE
iOS 10 HomeKit

### ISSUE THREAD

**Issue by ridn** [nfarina/homebridge#1044]
I've got homebridge running on a RPi 3B. Works fairly well, and i was able to add the bridge to my iOS 10 device no problem. However, after a bit HomeKit isn't able to receive updates from the bridge. The bridge hasn't crashed however. Instead it will repeatedly attempt to send an update from the looks of it. On the iOS device the status shows **_`Updating`_** indefinitely. Interestingly enough if i go over to my iOS 9 iPad, and open a 3rd party home kit app (since there isn't a home app) and send a command, it seems to go through and stop the loop. However, once i try to get an update from the iOS 10 device its the same loop. Here's the specific output that seems to loop from DEBUG from command line session (not currently running as a service).

```bash
 EventedHTTPServer [::ffff:192.168.1.160] HTTP request: /characteristics?id=8.19,8.10,8.13,8.16,3.8,3.9,3.11,3.10,6.14,6.13,6.11,6.10,2.11,2.10,4.10,5.13,5.11,5.10,5.14 +273ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: GET /characteristics?id=8.19,8.10,8.13,8.16,3.8,3.9,3.11,3.10,6.14,6.13,6.11,6.10,2.11,2.10,4.10,5.13,5.11,5.10,5.14 +0ms
  Accessory [Homebridge] Getting value for Characteristic "On" +1ms
  Accessory [Homebridge] Got Characteristic "On" value: 0 +0ms
  Accessory [Homebridge] Getting value for Characteristic "On" +1ms
  Accessory [Homebridge] Got Characteristic "On" value: false +0ms
  Accessory [Homebridge] Getting value for Characteristic "On" +0ms
  Accessory [Homebridge] Got Characteristic "On" value: false +0ms
  Accessory [Homebridge] Getting value for Characteristic "On" +0ms
  Accessory [Homebridge] Got Characteristic "On" value: false +0ms
  Accessory [Homebridge] Getting value for Characteristic "On" +0ms
  Accessory [Homebridge] Got Characteristic "On" value: false +0ms
  Accessory [Homebridge] Getting value for Characteristic "Brightness" +1ms
  Accessory [Homebridge] Got Characteristic "Brightness" value: 100 +0ms
  Accessory [Homebridge] Getting value for Characteristic "Saturation" +0ms
  Accessory [Homebridge] Got Characteristic "Saturation" value: 100 +0ms
  Accessory [Homebridge] Getting value for Characteristic "Hue" +0ms
  Accessory [Homebridge] Got Characteristic "Hue" value: 342 +0ms
  Accessory [Homebridge] Getting value for Characteristic "Saturation" +0ms
  Accessory [Homebridge] Got Characteristic "Saturation" value: 0 +0ms
  Accessory [Homebridge] Getting value for Characteristic "Hue" +1ms
  Accessory [Homebridge] Got Characteristic "Hue" value: 0 +0ms
  Accessory [Homebridge] Getting value for Characteristic "Brightness" +0ms
  Accessory [Homebridge] Got Characteristic "Brightness" value: 100 +0ms
  Accessory [Homebridge] Getting value for Characteristic "On" +0ms
  Accessory [Homebridge] Getting value for Characteristic "Brightness" +1ms
  Accessory [Homebridge] Got Characteristic "Brightness" value: 75 +0ms
  Accessory [Homebridge] Getting value for Characteristic "On" +0ms
  Accessory [Homebridge] Getting value for Characteristic "Current Temperature" +0ms
  Accessory [Homebridge] Got Characteristic "Current Temperature" value: 21.7 +1ms
  Accessory [Homebridge] Getting value for Characteristic "Hue" +0ms
  Accessory [Homebridge] Got Characteristic "Hue" value: 0 +0ms
  Accessory [Homebridge] Getting value for Characteristic "Brightness" +0ms
  Accessory [Homebridge] Got Characteristic "Brightness" value: 100 +0ms
  Accessory [Homebridge] Getting value for Characteristic "On" +0ms
  Accessory [Homebridge] Getting value for Characteristic "Saturation" +1ms
  Accessory [Homebridge] Got Characteristic "Saturation" value: 0 +0ms
[1/6/2017, 12:41:04 AM] [homebridge-lifx-lan.LifxLan] LIFX White 800 - Get power: 0
  Accessory [Homebridge] Got Characteristic "On" value: false +115ms

```

has anyone else run into this issue, or have any tips?
Currently only have Lifx (which didn't have to be added to config?) and Smartthings plugin running.
The local IP is the iOS 10 device.

**Comment by StallionV** [comment]
Try deleting home bridge form the home app
On your RBPi go to your home bridge directory 
cd /home/pi/.homebridge
sudo rm -r persist/
sudo rm -r accessories/
Add home bridge again from home app

**Comment by ridn** [comment]
Forgot to mention restarting homebridge fixes the issue for a short time. More specifically it seems if I use any method to access home that's not polling for an update the home does (basically any HomeKit app except the default including control center) then the requests continue to go through.

**Comment by StallionV** [comment]
Did the steps helps?

**Comment by ridn** [comment]
For the time being the homebridge is still responding to the iOS 10 device, though it has stalled a couple times on *`updating`* before getting a "response finished" from homebridge. I'm thinking the issue will still persist

**Comment by ridn** [comment]
Looks like the issue might be related to a light that is offline because the manual switch is flipped off. Is there anything that can be done about that? If a single bulb is offline then suddenly Home app can't receive an update?

**Comment by ridn** [comment]
This **appears** to be an issue with the way [lifx-lan](https://github.com/devbobo/homebridge-lifx-lan/) deals with offline devices, i've found a not so perfect solution for the problem for the time being. Thus im closing the issue here.
