### ISSUE TITLE
Homebridge - KNX - HomeKit Scenes not working

### ISSUE THREAD

**Issue by ND00** [nfarina/homebridge#1045]
Hi

After setting up Homebridge - KNX at my home (which went smoothly), I started to explore the usage of HomeKit scenes. I tried to perform a simple scene were 4 lights should turn off once activating the scene.

While testing it, I'm getting the following results:
1. Only 2 lights are turned off. The other 2 are staying on.
2. Home (or Eve) app indicates all 4 are off.

I tried to play with other 4 lights combination and I'm getting a consistent results.

Not sure if this is a specific knx issue or a general platform issue. 

Any ideas?

Thanks

ND

**Comment by snowdd1** [comment]
This is a duplicate of https://github.com/snowdd1/homebridge-knx/issues/73 which was solved. Please close this issue here.

**Comment by ND00** [comment]
Right. Thanks.
