### ISSUE TITLE
Add support for defining automations using Homebridge

### ISSUE THREAD

**Issue by sethfowler** [nfarina/homebridge#1047]
I'm interesting in the possibility of defining simple automations directly in Homebridge.

The use-case for this is to provide bi-directional communication between Homebridge and e.g. Home Assistant. Some accessories are *only* controllable via closed platforms like HomeKit and Alexa. If we want to involve them in automation at the Home Assistant level, the only way to do that right now is to expose a virtual switch from Home Assistant that both HomeKit and Home Assistant can see, and write HomeKit automation rules to keep the virtual switch and the real device always in sync. This requires four automation rules for a single switch, and obviously rapidly grows in complexity when you want to expose more and more things.

If we had a programmatic way of defining automations, we could provide a simple way to create mappings like this in Homebridge.

Unfortunately, based on my (quite limited) understanding of how HomeKit works, this is fundamentally different than other Homebridge features in that it requires access to the user's iCloud account, and the use of a different set of APIs. It's possible that Homebridge isn't the right place to do this at all. I'm hoping that folks with more HomeKit development experience will have some ideas. =)

**Comment by cflurin** [comment]
For this purpose I've developed homebridge-mqtt. Using homebridge-mqtt and node-red you are able to solve "all" your automation-cases.

https://github.com/cflurin/homebridge-mqtt
https://nodered.org/

node-red is preinstalled on a Raspberry.

**Comment by dylanslewis** [comment]
@cflurin your plugin looks cool, but how can it actually be set up to allow bi-directional communication with HomeKit? I can't see where the communication with HomeKit only devices happens. Cheers

**Comment by cflurin** [comment]
@dylanslewis it actually supports bi-directional communication. Have a look at:

https://github.com/cflurin/homebridge-mqtt
and
https://github.com/cflurin/homebridge-mqtt/wiki
