### ISSUE TITLE
Homebridge and Open-Zwave on the same RPi?

### ISSUE THREAD

**Issue by ehusar** [nfarina/homebridge#1049]
Has anyone installed Open-Zwave server on the same Raspberry Pi that is running Homebridger?  I thought I'd check before going down this rabbit hole. I am hoping to avoid a headache tonight if at all possible.

Thank you.

**Comment by flippamike** [comment]
Any update? I am buying a smoke detector that works on Zwave hope it works!

You also have a special stick to receive zwave signale?

**Comment by ehusar** [comment]
No luck getting the open server working at all.   I've moved on to trying to get Home Assistant up and running for the zwave stuff and using the HomeAssistant plugging for Homebridge.   But unfortunately the support for Home Assistant is not very good at all.   The instructions on their site are not accurate.   At least that's the experience I'm having.  Home Assistant is suppose to install the zwave open server as part of the install. 

If I can get this attempt at Home Assistant working then I'm returning my Z-Stick and getting a hub that I don't have to setup myself.   Most likely the Wink hub. 

But lots of people have zwave working via this plugin.  But you have to get the zwave server setup if you are going the open server route. 

Good luck if you go the open server route!

**Comment by gijoecool** [comment]
I went the openHAB route with the Z-Stick and it works great. There's even a homebridge extension for openHAB.

**Comment by ehusar** [comment]
I'm going to have to give it a try.  I'm using Home so I just need a quick at to get zwave server going.

**Comment by ehusar** [comment]
After literally weeks trying to get my first z-wave dimmer light switch going I finally had success tonight.  I tried to get Home Assistant working  for a couple of weeks.  6 installs and multiple forum posts nothing worked. The documentation is way out of whack.   In complete frustration tonight I tried Domoticz. It look 5 minutes and it was working with the Z-stick.  Home Assistant was a huge waste of time.  After getting Domoticz up and running I see no reason why you can't get have it running on the same RPi as Homebridge since Domoticz uses port 8080. I used the https://www.npmjs.com/package/homebridge-edomoticz plug and it worked perfectly.

So to answer my question, yes it is possible.
