### ISSUE TITLE
Adding devices error: "Your home's configuration has..."

### ISSUE THREAD

**Issue by rawmean** [nfarina/homebridge#105]
Sometimes adding the device fails and I get the following message:
'Your homes's configuration has changed and the device, room, zone, home, schedule or scene could not be found'

When this happens, these "zombie" devices stick around and show up when you try to add a device.  
My work-around is to change the device name in the config file and try to add them again, but the zombie devices don't go away even if I reset the homebridge server.

**Comment by nfarina** [comment]
What app are you using? And when you say "show up" do you mean show up in your app all the time, or just when adding a new device?

**Comment by rawmean** [comment]
I'm using Insteon+ (which seems to be the most full-featured client so far) and I have also used MyTouchHomekit and HomeKitDemo.  When I select "add device" these zombie devices appear in the list and tapping on them gives me the message listed above.

In order to get rid of it, I have to remove the contents of the persist directory, but that wipes out all devices.

**Comment by nfarina** [comment]
Sorry the latest Homebridge introduces breaking changes that will require you to re-add devices - but this time you should only need to add one single device. Could you try the latest version and see if it works for you?

**Comment by nzhome** [comment]
add one single device.. hmmm.  thats odd.   why do I have to add them individually still, where does npm get its sourcecode from?  I did the following at least 48 hours after you merged PR for HAPnodeJS and Homebridge...

rm -r homebridge, 
npm install homebridge
