### ISSUE TITLE
Individual Accessory Works but Home App Scenes Do Not

### ISSUE THREAD

**Issue by blockyear** [nfarina/homebridge#1051]
First Homebridge installation. I've successfully created a system using the Etekcity 433Mhz outlet switches as described in Tim Leland's blog here [https://timleland.com/wireless-power-outlets/](url) and here [https://timleland.com/use-siri-to-control-wireless-power-outlets-homebridge/](url).

All works well at the first level, I have the switches appearing in the Home app on my IOS 10 device, turns them on and off, voice activation works. All good.

But! When I create a scene, with one of the switches controlled by Homebridge and a couple of other Lutron Caseta dimmers, the scene turns only the Caseta units on and off. The icon for the Homebridge lamp switch goes dim and bright as if it were being activated, but he actual physical lamp does not turn on and off.

Thoughts? 

    - Brian -

**Comment by jay-hankins** [comment]
I am also having this issue.
