### ISSUE TITLE
Homebridge and Lon Hand Wifi relay.

### ISSUE THREAD

**Issue by marcoach** [nfarina/homebridge#1053]
Hi All,

I am a very rookie in programming and electronics but I am very well impressed in home automation and Homebridge.

Recently I bought a "Lon Hand" wi-fi relay. On the vendor sheets there was assured that it can be remotely managed via HTTP. Unfortunately the only thing i can do via http is the main configuration but i cannot set on or off the relay.

They gave me a manual where is written it network protocol and how to set up a tcp packet to turn on/off and get the relay status.

I tried to connect through telnet on its port but I cannot send the right command .

Any one of you does have already tried this kind of relay ?
is there a way to manage him or do you know if there is already an home bridge plug-in ?

The item is this one : https://community.flexradio.com/flexradio/topics/remote-on-off-control-lonhand-usr-wm1s  

thanks in advance .

Marco.

**Comment by tomwoodhams** [comment]
I have one of these too - never managed to het it working with homebridge - web interface mac and iOS app working fine. It can be controlled via an API and they provided me a window version of the app which reveals the coms to the unit, but I couldn't get it to work at all. Would love this to work with homebridge.,

**Comment by marcoach** [comment]
Top

Inviato da iPad
