### ISSUE TITLE
HomeBridge not being found by Home app or bonjour browser 

### ISSUE THREAD

**Issue by MatthewTheMeep** [nfarina/homebridge#1054]
Hey! I just tried to install homebridge on my Hackintosh, and the install succeeded, but neither my Ipad Mini 4 or my 7 Plus can find the bridge in the app called "home" nor do they with a bonjour browser.

I made a setup at my dad's and it's working well, his network is very simple though, mine is quite complicated, i shall explain soon.

let me post my config.json:
START CONFIG.JSON ( it makes some grey box, ignore it)
{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},

	"accessories": [{
		"accessory": "NefitEasy",
		"name": "thermostaat",
		"options": {
			"serialNumber": "XXXXXX",
			"accessKey": "XXXXXXX",
			"password": "XXXXXX"
		}

	}]
}

END CONFIG.JSON

I added the only thing i need, which is my thermostat as plugin and I of course added the stuff i needed to add in config.json for it.

When I run homebridge in terminal it starts just fine and without any problems, it's just it doesnt go on the network!

Sooo, my network:

cable from ISP> into ISP router> Airport Extreme configured as switch (DHCP off and Wireless off) > UniFi AP AC PRO. this is my wireless network.

Then, because I have a hackintosh, I have no WiFi ability, so I have my old ThinkPad with Win10 set up to share it's wifi connection over Ethernet with my computer. My computer and laptop are then connected with an ethernet cable and the thinkpad shares the wifi it has over ethernet with my computer. Could something be wrong with this?

Greetings, Matthew

**Comment by flippamike** [comment]
I would first start simple. All by cable! Any err logs?

**Comment by RXM307** [comment]
On 11 January 2017 at 06:24, flippamike <notifications@github.com> wrote:

> I would first start simple. All by cable! Any err logs?
>
really sounds like you have mdns/bonjour issues on your network, I'd try
enabling wifi on your Airport and connecting all the required devices
devices (homebridge home & ipad/iphones to the airport to test, it may need
up needing some extra configuration on the UnFi AP, on my Cisco AP's I
needed to enable mdns snooping for _hap._tcp.local. and additionally I'm
running an mdns reflector for good measure.

Anthony
