### ISSUE TITLE
Plugin for Frontier Silicon powered devices (speakers + radios)

### ISSUE THREAD

**Issue by QBJack** [nfarina/homebridge#1056]
Hello guys,

I'm just using homebridge for a few days now with Harmony plugin which works very well. I got myself a few Frontier Silicon powered audio devices - speakers and a web radio with DAB+/FM, BT, USB etc. - which all are multi room capable. Unfortunately there is no plugin for these devices written and I'm absolutely stuck when looking at plugin code examples. There are already some APIs available which surely could help. Who can help please with creating a simple plugin for these devices? 

General info: https://github.com/openhab/openhab/wiki/Frontier-Silicon-Radio-Binding

API for python: https://github.com/tiwilliam/fsapi
API for php: https://github.com/flammy/fsapi

Thanks in advance.

**Comment by QBJack** [comment]
Nobody can help?

**Comment by QBJack** [comment]
I am still after this but had no luck in finding something to get it working. Who can help please?

**Comment by QBJack** [comment]
Please someone help on that.

**Comment by plasticrake** [comment]
I'm not sure if you're having issues writing a homebridge pluging or getting the device to work in node.

If you're trying to learn how to make a plugin your best bet is to look at some other homebridge plugins and learn from that.

**Comment by QBJack** [comment]
@Kohle81 
In the meantime there is a new plugin for this, [Homebridge-frontier-silicon-plugin](https://www.npmjs.com/package/homebridge-frontier-silicon-plugin). But it is in early dev stage and did not run very well for me.

I managed to setup simple on / off buttons with [homebridge-cmdaccessory](https://www.npmjs.com/package/homebridge-cmdaccessory) - it's controlling my speakers with simple http get commands like: curl 'http://IP-OF-SPEAKER/fsapi/SET/netRemote.sys.power?pin=1234&value=1 for turning it on, value=0 for turning off. And a simple bash script to get status if speaker is on or off.

It works quiet good for my six devices.

**Comment by Kohle81** [comment]
Ok, thanks for your help. I will try it to do it myself!👍
