### ISSUE TITLE
Homebridge accessories stopped responding

### ISSUE THREAD

**Issue by jpstephens** [nfarina/homebridge#1058]
I had my Homebridge devices working perfectly up until two weeks ago.  I had my Nest and Alarm.com account working perfectly.  I changed my internet to use Eero routers over the Christmas Break and since then nothing is responding.  I don't know if they are related, but everything else is responding but the home bridge items.  

How can I troubleshoot this?

**Comment by Sunrise17** [comment]
Have you solved this problem? I am planning to buy eero and i have homebridge on raspberry pi 3.

**Comment by davidvanvo** [comment]
i have homebridge with eero and has been working fine since day one. i assume @jpstephens issue is unrelated to eero.
