### ISSUE TITLE
One way input?

### ISSUE THREAD

**Issue by AmitMY** [nfarina/homebridge#1060]
I have a door, that uses a lock I can control over the network.
Whenever the lock releases, the door automatically opens (because of a slight misalignment and force of gravity)
So all I can do over the network is "Open Door"
I can not tell if the door is open or not.

Is there an option to create not a toggle, but a button, to open the door?

**Comment by AlexGustafsson** [comment]
@AmitMY you could write your own plugin that meets your criteria.

**Comment by AmitMY** [comment]
A better question would be if there is a service that works like a button, not like a switch?
Of course I'm gonna write my own plugin, it's just that I need a service to control

**Comment by AlexGustafsson** [comment]
A button is more or less a switch that turns itself off immediately. Couldn't you use a switch as a service type and then turn it off when it has been turned on?

**Comment by AmitMY** [comment]
That is a good idea. Thanks!
