### ISSUE TITLE
[REQUEST] Is it possible to store each accessory's current values in a JSON file instead of being stored in the memory?

### ISSUE THREAD

**Issue by jcbriones** [nfarina/homebridge#1062]
Is it possible to store each accessory's current values in a JSON file instead of being stored in the memory? This way, we can integrate the data from those accessories to something else. I am planning to make a web interface for homebridge and also wants to control those accessories on the web as well.

**Comment by iksaku** [comment]
I think the best approach to this will be to have a Web API to control your instances and make your homebridge plugin to rely on it. You can create this REST API with Python or PHP easily, then make sure to update your plugin to create calls to that API in order to interact with your devices.

**Comment by jcbriones** [comment]
Yes that's what I did in the first place but I need to modify all plugins which I don't like modifying someone's code 😂

**Comment by iksaku** [comment]
You can keep a fork of the plugin with the changes you need for your own system 😉

**Comment by jcbriones** [comment]
Haha that's the problem now. Since I really don't know how nodejs really work. It might take a while. 😂 but for sure will learn how to 😊

**Comment by gijoecool** [comment]
Another option might be to use another system to integrate. For example I use openHAB, then expose those devices through homebridge-openhab. This way openHAB does all the REST heavy lifting... but you'd need to reconfigure your system to integrate.

**Comment by jcbriones** [comment]
True. Since openhab system already has the web stuff. I'll try to figure this one out. Let's see

**Comment by cflurin** [comment]
have a look at node-red and homebridge-mqtt:

http://nodered.org/
https://github.com/cflurin/homebridge-mqtt

node-red has also a dashboard (web-ui):

https://flows.nodered.org/node/node-red-dashboard
