### ISSUE TITLE
Homebridge stopped working with iOS Beta

### ISSUE THREAD

**Issue by anfalas** [nfarina/homebridge#1063]
Since Installation of iOS 10.2.1 Beta 3 homebridge devices stopped working. Beta 4 brings no relief.

All Homebridge devices are still visible and working fine on iOS Devices running iOS release version 10.2 an 10.2.1 prior to Beta 3

**Comment by KhaosT** [comment]
Interesting, I'll take a look later today.

**Comment by joyciticonti** [comment]
in the same boat. tried repairing devices and accounts, but it seems to be code related. ill dig around during the weekend.

**Comment by KhaosT** [comment]
I just tested homebridge 0.4.16 with iOS 10.2.1 Beta 4 and it's working fine. Please check your plugins are not malfunctioning. And it might be helpful if you two can list the plugins you used and see if there is a common one there.

**Comment by joyciticonti** [comment]
im having trouble with harmonyhub plugin. tried to update & upgrade, but to no luck.
ive cleared the config files, deleted homebridge from Home.app and re-added it, and it now works fine.

**Comment by anfalas** [comment]
I'm using the HomeMatic and ZWayServer - both (and home bridge itself) updated to the latest version.
Respectively disabling the two plugins makes no difference: the two devices (iPhone and iPad) with iOS 10.2.1 Beta are still not working, 2 iPhones and another iPad running the release version of iOS 10 are working flawlessly.
My AppleTV ist Rundung iOS 10.1 - maybe I'll have time later to install iOS 10.2 on the AppleTV. @joyciticonti - are you using an AppleTV as HomeKit hub? And if yes - what iOS version have you running?

**Comment by joyciticonti** [comment]
atv - hub - yes - 10.1.1b2
iphones / ipads - 10.2.1b4

running homebridge on a macbook shoved in my server closet.

**Comment by anfalas** [comment]
After a complete reset (clearing all caches, cleaning Home App on iOS) Homebeige now works fine. However it could be interesting to find out what was the cause since reconfiguring/reinstalling Homebridge and the plugins every time a new version is released is a bit of a hassle. 
Nonetheless - thank you all for your good work
