### ISSUE TITLE
Request: Insteon Plugin

### ISSUE THREAD

**Issue by THX723** [nfarina/homebridge#1065]
I know there's an unofficial way to get general Insteon support using a modified X10 legacy-plugin. I actually did manage to get that working. However, it does not detect events outside of Homekit/Homebridge (i.e. when an Insteon wall switch is toggled, Homebridge/Homekit does not update the state accordingly).

It also appears there was a "homebridge-platform-insteon" being worked on at one point, but has since gone 404. 

Anyone else up for the challenge?

I would gladly help, but must warn that I don't code for living (am an EE), so my ability to contribute may be limited ... at least as far as codes go.

**Comment by NorthernMan54** [comment]
Sorry, can't help with the insteon plugin at this time, but I can say that the homebridge-heyu x10 plugin does support the sending of x-10 events to home kit.  And it works quite well, and even supports the x-10 motion sensors.  But unless you have a x-10 cm11a, it may not help with your ask.  I use it with my legacy x-10 devices and with my newer insteon devices that support the x-10 protocol.

**Comment by rehafer** [comment]
I'm not a plug-in writer either; but I can share 2 points. 
1. Insteon devices respond exclusively to the controller the sent the command. As in, only the controller that told the switch to turn on knows the switch is on. 
2. The Insteon Hub Pro works with HomeKit, may be useful.

**Comment by webdeck** [comment]
Another option is to use the Indigo software (http://www.indigodomo.com) on your Mac, along with a compatible Insteon interface, which gives immensely more control over Insteon (and Z-Wave) devices, and you can use homebridge-indigo (https://www.npmjs.com/package/homebridge-indigo) to add HomeKit support.

**Comment by macjeff** [comment]
Universal Devices makes the ISY controller for insteon and z-wave as well as x-10.  

It works with amazon Alexa and has a home bridge plugin that works great.

**Comment by THX723** [comment]
Thanks fellas!
I was trying to avoid having to get another control hub, as I already have the Insteon Hub (non-HomeKit). As for the HomeKit compatible Insteon Hub Pro, that was mentioned, it is a total bust that fails to even work with it's own devices reliably.

**Comment by VeniceNerd** [comment]
Man, I'm also really struggling with Insteon and HomeKit. The Hub Pro is a disaster. If I press a keypad button it does not update the HomeKit status so keypads and HomeKit are constantly out of sync. It's a huge headache. 

If anyone can figure out ANY solution to keep the Insteon keypads and HomeKit in sync I'd be so grateful.

**Comment by THX723** [comment]
By the way, I have an Insteon Hub that I would sent someone to assist with the development. Just let me know and I will arrange to have it shipped to you.

Now back to the previously mentioned "homebridge-platform-insteon" plugin development (now defunct).  Looks like there is substantial code base already in place. With my limited knowledge, they look fairly good, but obviously have issues. I ran into an "Unexpected Identifier" error:

ERROR LOADING PLUGIN homebridge-platform-insteon:
/usr/lib/node_modules/homebridge-platform-insteon/index.js:94
        var authtoken = "Bearer " + self.SecurityToken;
            ^^^^^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Plugin.load (/usr/lib/node_modules/homebridge/lib/plugin.js:65:22)
    at Server.&lt;anonymous&gt; (/usr/lib/node_modules/homebridge/lib/server.js:132:14)

The package is still in the NPM repository for installation: https://preview.npmjs.com/package/homebridge-platform-insteon

Alternatively, can manually install the package via the direct download link here:
https://libraries.io/npm/homebridge-platform-insteon

Would someone please help debug.

-CC

**Comment by THX723** [comment]
Made a bit easier for those interested. Cut 'n Paste of the code below ...

```
var request = require("request");
var moment = require('moment');
var util = require('util');
var Service, Characteristic, LastUpdate;

'use strict';

module.exports = function(homebridge) {
    Service = homebridge.hap.Service;
    Characteristic = homebridge.hap.Characteristic;
    homebridge.registerPlatform("homebridge-platform-insteon", "Insteon", InsteonPlatform);

    LastUpdate = function() {
        var self = this;

       Characteristic.call(self, 'Last Activity', '');

       self.setProps({
           format: Characteristic.Formats.STRING,
           perms: [Characteristic.Perms.READ, Characteristic.Perms.NOTIFY]
       });

        self.value = self.getDefaultValue();
    };
    require('util').inherits(LastUpdate, Characteristic);
}
function InsteonPlatform(log, config) {
    var self = this;
    self.config = config;
    self.log = log;
    self.host = 'https://connect.insteon.com'
    self.refreshInterval = 30 * 1000;
    self.apikey = 'APIKey ' + self.config['client_id'];
}
InsteonPlatform.prototype.login = function(onSuccess, onFail) {
    var self = this;
    var fbody = "grant_type=password&username=" + self.config['user'] + "&password=" + self.config['pass']
        + "&client_id=" + self.config['client_id'];
    request.post({
        url : self.host + '/api/v2/oauth2/token',
        body : fbody,
        headers: {
          "Content-Type" : "application/x-www-form-urlencoded"
        }
    }, function (error, response, body) {
        if (!error && response.statusCode == 200) {
            if (body.ReturnCode !== '0') {
                if(onFail) {
                    onFail.call(self, body.ReturnCode, body.ErrorMessage);
                } else {
                    self.retry_login.call(self, onSuccess);
                }
            } else if(onSuccess) {
                var jsonObj = JSON.parse(body);
                self.SecurityToken = jsonObj.access_token;
                self.log.debug('SecurityToken: [%s]', self.SecurityToken);
            }
        }
        else {
            self.log.error('[%s]: Error while login', moment().format('YYYYMMDDHHmmss.SSS'));
            self.log.error(error);
            self.log.error(response);
            self.log.error(body)
            if(!body) {
                body = {};
            }
            if(onFail) {
                onFail.call(self, body.ReturnCode, body.ErrorMessage);
            } else {
                self.retry_login.call(self, onSuccess);
            }
        }
    });
}
InsteonPlatform.prototype.retry_login = function(onSuccess) {
    var self = this;
    self.log.warn('[%s]:retrying login.', moment().format('YYYYMMDDHHmmss.SSS'));

    self.login(onSuccess, function(returnCode, errorMessage) {
        setTimeout(function() {
            self.retry_login.call(self, onSuccess);
        }.bind(self), self.refreshInterval);
    });
}

InsteonPlatform.prototype.getDevices = function(onSuccess, onFail) {
    var self = this;
    self.log.debug('[%s]: retrieving devices', moment().format('YYYYMMDDHHmmss.SSS'));
    if(!self.SecurityToken && onFail) {
        onFail.call(self);
        return;
    }
    request.get({
        var authtoken = "Bearer " + self.SecurityToken;

        url : self.host + '/api/v2/devices?properties=all',
        headers : {
          "Content-Type" : "application/json",
  				"Authentication" : self.apikey,
  				"Authorization" : authtoken
        }
    }, function (error, response, body) {
        if (!error && response.statusCode == 200) {
            var json = JSON.parse(body);
                if(json.DeviceList && json.DeviceList.length > 0) {
                    var insteon_devices = [];
                    json.DeviceList.forEach(function(device) {
                            insteon_devices.push(device);
                        }
                    })
                    onSuccess.call(self, insteon_devices);
                } else if(onFail) {
                  onFail.call(self, error, response);
                } else {
                  self.retry_login(onSuccess);
                }
        } else if(onFail) {
            onFail.call(self, error, response);
        } else {
            self.retry_login(onSuccess);
        }
    });
}

InsteonPlatform.prototype.sendCommand = function(level, device_id, state, callback) {
    var self = this;
    var authtoken = "Bearer " + self.SecurityToken;

    request.post({
        url : self.host + '/api/v2/commands',
        headers : {
          "Content-Type" : "application/json",
  				"Authentication" : self.apikey,
  				"Authorization" : authtoken
        },
        json : {
            command : state,
            level : level,
            device_id: device_id
        }
    }, function (error, response, body) {
        if (!error && response.statusCode == 200 && body.ReturnCode === '0') {
            self.log.info('[%s]: send command successed, level=[%s],state=[%s]', moment().format('YYYYMMDDHHmmss.SSS'), level, state);
            callback(body);
        } else {
            self.log.error('[%s]: send command failed.', moment().format('YYYYMMDDHHmmss.SSS'));
            self.log.error(error);
            self.log.error(response);
            self.log.error(body);
        }
    });
}
InsteonPlatform.prototype.dimmer_on = function(device_id, callback) {
    var self = this;
    self.sendCommand.call(self, '100', device_id, 'on', callback);
}
InsteonPlatform.prototype.dimmer_off = function(device_id, callback) {
    var self = this;
    self.sendCommand.call(self, '0', device_id, 'off', callback);
}
InsteonPlatform.prototype.dimmer_status = function(device_id, callback) {
    var self = this;
    self.sendCommand.call(self, '0', device_id, 'get_status', callback);
}

InsteonPlatform.prototype.accessories = function(callback) {
    var self = this;
    self.login.call(self, function() {
        self.getDevices.call(self, function(insteon_devices) {
            self.foundAccessories = [];
            insteon_devices.forEach(function(device) {
                self.foundAccessories.push(new InsteonAccessory(self, device));
            });
            callback(self.foundAccessories);
            self.timer = setTimeout(self.deviceStateTimer.bind(self), self.refreshInterval);
        }, function(returnCode, errorMessage) {
            self.log.error('[%s]:Insteon Server error when list accessories, returncode=[%s], errormessage=[%s]', moment().format('YYYYMMDDHHmmss.SSS'), returnCode, errorMessage);
            throw new Error("homebridge-platform-insteon has intentially brought down HomeBridge - please restart!");
        });
    }, function(returnCode, errorMessage) {
        self.log.error('[%s]:Insteon Server error, returncode=[%s], errormessage=[%s]', moment().format('YYYYMMDDHHmmss.SSS'), returnCode, errorMessage);
        throw new Error("homebridge-platform-insteon has intentially brought down HomeBridge - please fix your configuration!");
    });
}
InsteonPlatform.prototype.deviceStateTimer = function() {
    var self = this;
    if(self.timer) {
        clearTimeout(self.timer);
        self.timer = null;
    }
    self.getDevices(function(insteon_devices) {
        self.foundAccessories.forEach(function(accessory) {
            accessory.updateDevice(insteon_devices);
        });
        self.timer = setTimeout(self.deviceStateTimer.bind(self), self.refreshInterval);
    });
}

InsteonPlatform.prototype.dateTimeToDisplay = function(unixtime) {
    return moment(unixtime, 'x').fromNow()
}

function InsteonAccessory(platform, device) {
    var self = this;
    platform.log.debug(device);
    self.init.call(self, platform, device)
}
InsteonAccessory.prototype.init = function(platform, device) {
    var self = this;

    self.platform = platform;
    self.log = platform.log;
    self.currentState = '';
    self.name = device.InsteonID;
    self.updateDevice([device]);
}

InsteonAccessory.prototype.descState = function(state) {
    switch(state) {
        case Characteristic.CurrentDimmerState.ON:
        return 'on';
        case Characteristic.CurrentDimmerState.OFF:
        return 'off';
        default:
        return state;
    }
}

InsteonAccessory.prototype.updateDevice = function(devices) {
    var self = this;
    var isMe = false;
    if(!devices) {
        return false;
    }
    for(var i=0; i< devices.length; i++){
        if(!self.device || self.device.DeviceID === devices[i].DeviceID) {
            self.device = devices[i];
            isMe = true;
            break;
        }
    }
    if(!isMe || !self.device) {
        return false;
    }
    return true;
}

InsteonAccessory.prototype.getServices = function() {
    var self = this;
    var services = [];
    var service = new Service.AccessoryInformation();
    service.setCharacteristic(Characteristic.Name, self.DeviceName)
        .setCharacteristic(Characteristic.Manufacturer, 'Insteon')
        .setCharacteristic(Characteristic.Model, 'Insteon')
        .setCharacteristic(Characteristic.SerialNumber, self.SerialNumber || '')
        .setCharacteristic(Characteristic.FirmwareRevision, self.FirmwareVersion || '')
        .setCharacteristic(Characteristic.HardwareRevision, '');
    services.push(service);
    if(self.service) {
        services.push(self.service);
    }
    return services;
}

function InsteonAccessory(platform, device) {
    InsteonAccessory.call(this, platform, device);
    var self = this;
    self.log.info('[%s]: found Insteon Device, deviceid=%s', moment().format('YYYYMMDDHHmmss.SSS'), self.DeviceID);
}

function InsteonDimmerAccessory(platform, device) {
    InsteonAccessory.call(this, platform, device);
    var self = this;
    self.log.info('[%s]: found Dimmer Device, deviceid=%s', moment().format('YYYYMMDDHHmmss.SSS'), self.DeviceID);
}
util.inherits(InsteonDimmerAccessory, InsteonAccessory);

InsteonDimmerAccessory.prototype.init = function(platform, device) {
    var self = this;
    self.service = new Service.Switch(self.DeviceName);
    self.service.addCharacteristic(LastUpdate);
    InsteonDimmerAccessory.super_.prototype.init.call(self, platform, device);

    self.service.getCharacteristic(Characteristic.On).value = '';
    self.service.getCharacteristic(Characteristic.Name).value = self.DeviceName;
    self.service.getCharacteristic(LastUpdate).value = self.platform.dateTimeToDisplay(self.stateUpdatedTime);

    self.service.getCharacteristic(LastUpdate).on('get', function(cb) {
        cb(null, self.platform.dateTimeToDisplay(self.stateUpdatedTime));
    }.bind(self));

    self.service
        .getCharacteristic(Characteristic.On)
        .on('get', function(callback) {
            self.log.debug("[%s]: Getting current dimmer state...", moment().format('YYYYMMDDHHmmss.SSS'));
            self.platform['dimmer_status'].call(self.platform, self.DeviceID, function(body){
                self.log.debug(body);
                var json = JSON.parse(body);
                if (json.status != "succeeded") {
                  self.currentState = "off";
                } else {
                  if(json.response.level) {
                    self.currentState = "on";
                  } else {
                    self.currentState = "off";
                  }
                }
                self.stateUpdatedTime = moment().format('x');
                self.service.getCharacteristic(Characteristic.On).setValue(self.currentState);
                self.service.getCharacteristic(LastUpdate).setValue(self.platform.dateTimeToDisplay(self.stateUpdatedTime));
                callback(null);
            });
            callback(null, self.currentState);
        }.bind(self))
        .on('set', function(state, callback) {
            if(state !== self.currentState) {
                self.log.debug("[%s]: set current dimmer state...[%s]", moment().format('YYYYMMDDHHmmss.SSS'), state);
                self.platform['dimmer_' + (state ? 'on':'off')].call(self.platform, self.DeviceID, function(body){
                    self.log.debug(body);
                    self.currentState = state;
                    self.stateUpdatedTime = moment().format('x');

                    self.service.getCharacteristic(Characteristic.On).setValue(self.currentState);
                    self.service.getCharacteristic(LastUpdate).setValue(self.platform.dateTimeToDisplay(self.stateUpdatedTime));
                    callback(null);
                });
            } else {
                callback(null);
            }
        }.bind(self));
}

InsteonDimmerAccessory.prototype.updateDevice = function(devices) {
    var self = this;
    if(InsteonDimmerAccessory.super_.prototype.updateDevice.call(self, devices) && self.lightstateUpdateTime) {
        if(self.stateUpdatedTime !== self.lightstateUpdateTime && self.service) {
            self.stateUpdatedTime = self.lightstateUpdateTime;
            self.service.getCharacteristic(LastUpdate).setValue(self.platform.dateTimeToDisplay(self.stateUpdatedTime));
        }
        if(self.currentState !== self.lightstate && self.service) {
            self.currentState = self.lightstate === 'on' ? true:false;
            self.service.getCharacteristic(Characteristic.On).setValue(self.currentState);
        }
        self.log.debug('[%s]: Light[%s] Light State=[%s], Updated time=[%s]',
            moment().format('YYYYMMDDHHmmss.SSS'),
            self.DeviceName,
            self.lightstate === '1' ? 'on':'off',
            self.platform.dateTimeToDisplay(self.stateUpdatedTime)
        );
    }
}
```

**Comment by THX723** [comment]
Okay got a bit further. It dawned on me that the previous error was caused by not having the platform defined in the config.json, which would looks something like this ...

```
    "bridge": {},
    "description": "",
    "platforms": [
        {
	  "platform": "Insteon",
          "name": "Insteon Platform",
	  "user": "user@example.com",
	  "pass": "passw0rd",
	  "client_id": "client_id"
	}
    ]
```
Got another step further after the above, then discovered a bug in the the code at line 110; there was an extra '}'. After removing that, the plug-in now loads!!! :)

So now I'm stuck. Looks like this plug-in was written to leverage the official public API on the Insteon server, which requires a developer's client_id.

I'm wondering if it's possible to leverage the Insteon API package here instead:
https://preview.npmjs.com/package/insteon-api
(p.s. I do have a spare 2245 hub ... let me know if a developer would like to have it).
 
Now this is really starting to get over my head where to go from here ... could really use some help with people more knowledgeable.

**Comment by ishiiworld** [comment]
I use OpenHab with Insteon support, then use the OpenHab plugin in Homebridge.

**Comment by THX723** [comment]
Interesting. So with OpenHab + Homebridge, you do get device status updates within Homekit?

**Comment by THX723** [comment]
So I did some reading on openHAB. Cools stuff! It also appears openHAB 2 already has a HomeKit add-on. Is there a reason why you would run Homebridge on top? Perhaps it's because you're on the 1.x, which I'm guess did not have the HomeKit add-on?

**Comment by gijoecool** [comment]
Yeah, I'm on 1.8, I wasn't ready to dive into version 2 when I set mine up.

**Comment by VeniceNerd** [comment]
How does openHAB interface with the Insteon devices? Through the regular Insteon Hub? Also, I assume you would need to be able to add Insteon "scenes" into HomeKit as devices then in order to keep them in sync with the Insteon Keypad buttons, no? Since the keypads trigger scenes, not devices. .

**Comment by THX723** [comment]
@gijoecool I've been playing with both openHAB 1.8 and 2.0, but haven't had much luck running it with the Hombridge openHAB plugin. Could really use your assistance (perhaps offline?).

**Comment by kuestess** [comment]
Hi all, I've published a working version of homebridge-platform-insteon at [https://github.com/kuestess/homebridge-platform-insteon](https://github.com/kuestess/homebridge-platform-insteon), adapted from the code pasted above.  At best, I'm a hacker so I'm sure that there are better ways to integrate Insteon gear.. but at least it works.  Requires a Hub2 and a developer API key.  Currently only supports switches/dimmer modules/micro dimmers.  Working on adding leak sensor and IO Line support.

**Comment by THX723** [comment]
Great work @kuestess. Unfortunately without a developer API key, I'm unable to test. How did you manage to get approved for one (from Insteon)?

**Comment by kuestess** [comment]
@THX723 I just filled out the request form [here](http://www.insteon.com/become-an-insteon-developer) and got approved.  It was a while back, but I do remember that it took them a while to respond.  I'm not a developer, but apparently what I described in the request was interesting enough :).  Give it a try - you may be able to get a key.

**Comment by kuestess** [comment]
@THX723 I've just published a version of the Insteon plugin with local control via an Insteon hub (no API key needed) at [homebridge-platform-insteonlocal](https://github.com/kuestess/homebridge-platform-insteonlocal).  Unfortunately, it currently only supports one device at a time, as Insteon only provides device status via a buffer on the hub.  Once you send a command make another status request to the Hub, that buffer gets blown away.  This is a problem, considering the async nature of Homebridge and Node.  Posting as-is, with the hope that someone more skilled than I can come up with a better solution to enable multiple devices.

**Comment by THX723** [comment]
@kuestess Wow fantastic work! I can't wait to peek into your code and see how you implemented it.

**Comment by rawmean** [comment]
can you please give an example of the config.json that includes an accessory?

**Comment by rawmean** [comment]
@kuestess This works great except that it only finds 5 of my devices and the rest are missing

Any idea?

This is a portion of the log:

[2017-9-18 02:13:15] [Insteon Platform] Initializing platform accessory 'Cabinets'...
[2017-9-18 02:13:15] [Insteon Platform] Initializing platform accessory 'Couch'...
[2017-9-18 02:13:15] [Insteon Platform] Initializing platform accessory 'Lamp 1'...
[2017-9-18 02:13:15] [Insteon Platform] Initializing platform accessory 'Nightstand'...
[2017-9-18 02:13:15] [Insteon Platform] Initializing platform accessory 'Outside Light'...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘

**Comment by rawmean** [comment]
Update: I was able to solve the problem described above by modifying the following lines:

                           ` if(device.DeviceTypeTraits.TypeDescription != 'Leak Sensor' && device.DeviceTypeTraits.TypeDescription != 'Device') {
                            insteon_devices.push(device);}

                            // if(device.DeviceTypeTraits.TypeDescription === 'Dimmer Switch' || device.DeviceTypeTraits.TypeDescription === 'Dimmer Module' || device.DeviceTypeTraits.TypeDescription === 'Dimmer Micro Module') {
                            // insteon_devices.push(device);}
`

Siri works fine but if you try to use the iOS Home app, status updates fail because (as @kuestess pointed out) the Hub can't deal with multiple devices at the same time.

I encountered the same problem when I developed my iOS app [ControlHub](https://itunes.apple.com/us/app/controlhub/id936293111?mt=8).  In my app, I had to use semaphores to limit the number of simultaneous requests sent to the Hub and it works perfectly.

I'm not a javascript programmer, so I don't know how to do the same in javascript.  I hope someone else can here help.

Note: the app works perfectly with Siri (which is the main reason I'm interested in HomeKit/homebridge).  If I want to use an app to interact with my insteon devices, I prefer to use my ControlHub app/Widget.

**Comment by kuestess** [comment]
@rawmean From the modified code snippet, it looks like you're using the Insteon API platform [plugin](https://github.com/kuestess/homebridge-platform-insteon) rather than the local control plugin.  You shouldn't have any issues using the Insteon API to get status for multiple devices, as it doesn't have the same limitations as the Hub.  I haven't encountered the problem you had above, but glad you got it working.  I'm not a javascript programmer either, but if you have ideas on how to throttle/queue requests to the Hub it would be great to get the [homebridge-platform-insteonlocal](https://github.com/kuestess/homebridge-platform-insteonlocal) version of the plugin working.

**Comment by wveilleux** [comment]
Hi kuestess, when you say this homebridge plugin works with Insteon Hub, is it the model 2243-222 (Pro) or the 2245-222 ?

**Comment by kuestess** [comment]
@wveilleux The plugin only supports the Hub model 2242 and 2245.  It replicates the functionality of the Hub Pro.  I have just published a new release of [homebridge-platform-insteonlocal](https://github.com/kuestess/homebridge-platform-insteonlocal) that leverages [home-controller](https://github.com/automategreen/home-controller) to support multiple devices.  Unlike the Hub Pro, the plugin should also update device status when manually operating a switch.

**Comment by wveilleux** [comment]
OK, thanks kuestess. I already have a 2242-222. Is there much features with the 2245 ?

**Comment by kuestess** [comment]
@wveilleux I have both, and I can say that the 2245 is more reliable - seems like scenes trigger more reliably and fewer 'retry' issues when you create scenes/links/etc.  I think the other advantage is the REST API and the ability to use it with the Echo and other connected services.  To my knowledge, you aren't able to do that with the 2242.  I got mine for $39 and I think its a good deal at that price, assuming that you would use the additional features or benefit from reliability.  One advantage of the 2242 is that it still has the PLM interface which has been dropped from the 2245.

**Comment by sphawk88** [comment]
i got your plugin working last night using my pi3 board (running for the chamberlain support - way cheaper than the OEM option). i need to look into it more, however your plugin gets wiped on reboot, which is somewhat annoying (i can script an install at bootup worst case) - i also run into a error on installation. if i have time i will look into adding fan support to your existing local plugin. great work thus far BTW; i love how incredibly snappy this plugin works compared to both the hub pro (i already returned) and the 'regular' insteon hub app.

```
pi@raspberrypi:/tmp/homebridge-platform-insteonlocal $ sudo npm -g install --unsafe-perm

> serialport@5.0.0 install /tmp/homebridge-platform-insteonlocal/node_modules/serialport
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/5.0.0/serialport-v5.0.0-node-v57-linux-arm.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for serialport@5.0.0 and node@8.9.4 (node-v57 ABI) (falling back to source compile with node-gyp)
make: Entering directory '/tmp/homebridge-platform-insteonlocal/node_modules/serialport/build'
  CXX(target) Release/obj.target/serialport/src/serialport.o
  CXX(target) Release/obj.target/serialport/src/serialport_unix.o
  CXX(target) Release/obj.target/serialport/src/poller.o
  SOLINK_MODULE(target) Release/obj.target/serialport.node
  COPY Release/serialport.node
make: Leaving directory '/tmp/homebridge-platform-insteonlocal/node_modules/serialport/build'
+ homebridge-platform-insteonlocal@0.2.0
added 222 packages and updated 1 package in 43.881s

```

**Comment by kuestess** [comment]
@sphawk88 Glad you got the plugin running - agree that it's much faster than the Hub Pro (still have mine, sits unused).  You can ignore the error with serial port.  That's a dependency of home-controller that is only used if you are connecting via serial to an Insteon PLM, which the plugin doesn't support.  I'm not sure why the plugin is getting wiped.  It sounds like an issue with npm for which I'm admittedly no expert.  Looks like you're installing from /tmp - is the installation linked to the homebridge-platform-insteonlocal directory in /tmp which gets deleted on reboot?  Maybe clone to your user directory and then install and see if that persists.

**Comment by kuestess** [comment]
@THX723 The plugin currently only supports individual devices and not scenes at this point.  Scene commands are sent to a group so the event listener doesn't pick up those events, however the polling functionality should pick up the new status within a poll cycle.  After that, you should be able to turn off the individual devices either via an app or Siri.  It would be fairly easy to add scene on/off/dim capability, but getting status of the devices (instantaneously) is harder because of the way Insteon works.  Homekit behavior is to not send any command if it thinks that a device is already in the commanded state (rather than repeating the command) which is why Siri does nothing.

**Comment by jeffwhalen** [comment]
@kuestess I installed your plugin tonight. Thank you so much this is awesome! I am curious about getting devices like on/off switches to be recognized in the home app. Right now i've set these devices to dimmable = "no" in the config file, but they are still showing up with dimmable controls in the home app. Any idea how i can get these to be recognized correctly?

Thanks again!

**Comment by kuestess** [comment]
@jeffwhalen I missed a test for whether a device is dimmable in one section of the code.  I've uploaded a new release that should fix the problem.

**Comment by jeffwhalen** [comment]
@kuestess Thanks for the looking into this so fast!  I just updated, and unfortunately only it works for about 5 minutes, than it reverts back to the dimmer controls. Maybe it's reverting back because of the poll at 300 seconds?

**Comment by kuestess** [comment]
@jeffwhalen Sorry, found one more that I missed.  0.2.2 uploaded now - should hopefully fix it (you were right - it was in the poll function).  Thanks for testing for me :-).

**Comment by jeffwhalen** [comment]
@kuestess Thanks! Seems to be working just fine. By the way, great work on this. It's way better then my last insteon plugin I was using.  Now I just need to tinker and see if i can get some of them to show up as switches! ;)  Thanks again!

**Comment by THX723** [comment]
@kuestess Looks like you reworked the code quite a bit! Great job. I will hopefully get to test out 0.2.2 this week.

**Comment by miked1987** [comment]
@kuestess @THX723 Hey guys, Homebridge noob here - getting the following error which shuts down Homebridge whenever I hit the Light icon in the home app that I have added from the Insteon hub

Error setting level for Kitchen Dimmer
/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:12
      throw new Error("This callback function has already been called by someone else; it can only be called one time.");
      ^

Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:12:13
    at /usr/local/lib/node_modules/homebridge-platform-insteonlocal/index.js:447:7
    at Request._callback (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/index.js:364:4)
    at self.callback (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/node_modules/request/request.js:186:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/node_modules/request/request.js:878:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:309:9)

**Comment by kuestess** [comment]
@miked1987 This is likely an issue connecting to your Hub.  I've found that the latest firmware update mangles the password for your Hub so even though it appears the same in the Insteon app, it won't allow you to log in.  Couple things to try - try running Homebridge with the plugin and go to http://[ip of your homebridge machine]:[port for the express server]/links and see if that works.  If not, go into the Insteon app and change the password to your Hub - update the password in your config.json and then try the plugin again.  Hopefully that will take care of the problem.

**Comment by miked1987** [comment]
@kuestess thanks for the quick reply! The ability to change my password in the app is greyed out - only allows me to Delete Account 

Excuse me ahead of time for super silly questions but, which IP should I be using in config.json?
Local IP
Public IP
Gateway IP

I am almost certain the password I am using is correct, and I just recently installed the hub and created the account, not really remember doing a firmware update (although I could be wrong)

**Comment by kuestess** [comment]
@miked1987 The password to change/check is the password for your hub.  Im on iOS, and once in the Insteon app I go to Settings and then tap House.  Down near the bottom you can tap 'Hub Username' or 'Hub Password' to change either.  The 'host' and 'port' in your config.json should be the local IP and port for your hub (on the same screen in the Insteon app where you can change the password).  Once you get that set, you should be able  to go to http://[ip of your mac]:[server_port from config.json]/links and get a list of links (note that it may take a while depending upon the number of devices/links you have).  The port value that you use is the server_port (default 3000) for insteonlocal in your config.json and not the homebridge port.  Hope that helps.

**Comment by miked1987** [comment]
@kuestess Works like a charm! Thanks so much!!

Are dimmer switches my only options?  I have The 6 button keypads. Ideally would like HomeKit to control those so that the physical buttons sync up and I don't have to physically hit buttons twice

Works with Alexa now because I named the scenes "Kitchen", "Living Room", etc.   Anyway to add the Insteon scenes?

**Comment by THX723** [comment]
@miked1987 This goes along with what I pointed in my previous comment. Adding scene command shouldn’t be too hard. Polling for scenes is where it’ll be tricky.
