### ISSUE TITLE
Homebridge reconnecting, reboot IOS

### ISSUE THREAD

**Issue by Pytr** [nfarina/homebridge#1068]
Hi,

My Homebridge stops randomly working. A scheduled reboot combined with an automated restart of the service keeps it alive a bit longer (days) until it finally stops connecting with the 'home' app.
I stop the process through ssh with: 'sudo killall homebridge' and reboot. This sometimes helps but sometimes the 'home' app is still not responding. In these cases I can not find  ' _hap._tcp' either with IOS. ('Discovery' app)
Today I found out that when I reboot the Iphone the connection is back and I can also see  _hap._tcp. Could it be that the problem is more in IOS than on the Homebridge side?
Does somebody know how to check _hap._tcp with OSX? Maybe the service is running fine but is my IOS somehow getting stuck in listening to it?
thnx,

**Comment by NorthernMan54** [comment]
Please take a look at my response on issue 1061, and provide the log output with enough detail to determine where homebridge is exiting.

**Comment by Pytr** [comment]
I am sorry but this rebooting IOS is not helping out. It worked twice but ever since I can't reproduce it. I thought it would work in the case where people had problems reconnecting to the Home app after for whatever reason restarting the service. My apologies for the confusion.
