### ISSUE TITLE
Airconditioner service?

### ISSUE THREAD

**Issue by AmitMY** [nfarina/homebridge#1069]
I have a very stupid "smart" control over AC. I can turn it on, and off.
The Thermostat service is way too much for such idiotic control, so I was looking for a list of services or maybe a light AC service to control this.
Is there one?

(I like to have this control mainly for automation)

**Comment by alisdairjsmyth** [comment]
Sounds like a Switch service.  You could probably use the [HTTP Plugin](https://www.npmjs.com/package/homebridge-http).

**Comment by AmitMY** [comment]
@alisdairjsmyth Yep, I guess that would do it.
Ill write my own plugin though, thanks anyway!
