### ISSUE TITLE
Setting fetch interval?

### ISSUE THREAD

**Issue by gustafnilklint** [nfarina/homebridge#107]
Hi there!
Really love this project and I'm really happy that i got both my telldus live and my garage door opener to work with a minimal effort!

Although I have a question, the garage port accessory I made (based on the example with liftmaster) works fine with Siri when I ask explicit questions: "Is my garageDoor open?" then Siri asks the accessory for state and answer correctly.

But if I open the HomeKit app (I use Insteon+) it indicates as if the port is open.. but I see no logs that it has asked for the current state. Is this accessory configured wrong? or perhaps the app is faulty not getting accessory state before showing it in the user interface?

//
cheers! Gustaf

**Comment by nfarina** [comment]
Glad to hear you got it working! So iOS does not always query for current state by default. When you ask Siri, she does query for state before answering your question. But when you're using an app, it may display the cached "last known value" for a characteristic, or it may call `readValueWithCompletionHandler` which fetches the latest value from Homebridge.

See the docs for `HMCharacteristic` under `value` and `readValue...` for some discussion about this: https://developer.apple.com/library/prerelease/ios/documentation/HomeKit/Reference/HMCharacteristic_Class/index.html#//apple_ref/occ/instp/HMCharacteristic/value

**Comment by justme-1968** [comment]
if the state of an accessory changes you should push the new state back to homekit with characteristic.updateValue(new_value, null);

**Comment by nfarina** [comment]
Yes, but keep in mind iOS still may not know about it unless it has signed up for "events" for that particular characteristic.

**Comment by gustafnilklint** [comment]
I don't think I will implement support for pushing state changes any time soon =). But it kind of surprised me that it doesn't even check for current state at startup of the service.. and that the app (Insteon) doesn't request current state when I choose to show the room of the accessory to be able to show a reliable state.

**Comment by nfarina** [comment]
Try the "Eve" app - it's quite aggressive about fetching state.

**Comment by nfarina** [comment]
Closing this as "HomeKit working as designed" :)
