### ISSUE TITLE
OpenWrt Package

### ISSUE THREAD

**Issue by TLCary** [nfarina/homebridge#1071]
Running Homebridge on the WIFI Router itself as an OpenWRT Package would simplify the infrastructure overhead.  I see that there is a Node.JS Package already https://github.com/brimstone/nodejs-openwrt.  
Before I dive in and try to wrap this up into an OpenWRT Package, is this a stupid idea?  Did I miss something?   Has anyone done this?  Does anyone else have any interest in this?

**Comment by nxhack** [comment]
Hi @TLCary 

https://github.com/nxhack/openwrt-node-packages/tree/master/node-homebridge

If you are interested please try it.
