### ISSUE TITLE
Homebridge loading very slow on wifi

### ISSUE THREAD

**Issue by m3lvn** [nfarina/homebridge#1074]
Hi, 

My homebridge is working fine and all the accessories are working properly. However, the strange thing is that since a day or 2 both iOS Home and EVE are having issues with loading the accessories whilst on a my wifi connection. They keep "loading" for ages but in the end they do work. When I turn off wifi they are connected instantly. 

I've checked my wifi connection and everything is up and running with full bandwidth (150 Mbps down, 15 up). I've also checked all the connected IP addresses and there are no duplicates what might cause the issue.

Any thoughts on this?

**Comment by danemacmillan** [comment]
I installed HomeBridge just last night and immediately noted this behaviour. Prior to the install, my 30+ accessories would have their status updated immediately instead of being stuck on "Updating." Turning off Wifi, so the Home app uses LTE, immediately updates the status of all my accessories. If I'm out of the house and on another Wifi network, the status of all my accessories are updated without delay as well. The performance is affected only while using my home network's Wifi.

**Comment by Dirtrunner702** [comment]
Do you both have a dedicated HomeKit server such as an Apple TV hardwired to your network router or using an iPad on a wireless connection? I too am facing similar slowness on an initial query after a long period of inactivity. I currently only have an iPad running homekit and interfaced with HomeBridge.

I run HomeBridge on a Windows 10 instance that reboots daily.

**Comment by Dirtrunner702** [comment]
Hello! 
I wanted to give an update on this.
I just installed a new Apple TV 4th Gen with an Ethernet only connection, no wifi. My homebridge server is on the same LAN as my Apple TV. I no longer have the "Updating" issues as before. Accessories now update immediately upon pulling up the iPhone card for homekit or the homekit app. Doesn't matter if my iPhone is on my home on wifi or on LTE. It just works now! 

I removed everything from all ios devices, waited about 5 minutes and rebooted all ios devices. 
I then setup the Apple TV to be a homekit hub and set it to never sleep. I re-added homebridge from my iPhone in the Homekit app and then the accessories showed up right after. 

Siri works great now too. 
I currently use a chamberlain garage door and Samsung tv modules in Homebridge. I will update this if anything changes moving forward.

**Comment by benzman81** [comment]
Same issue here. Apple tv4 and homebridge server both connected via LAN. This started happenin a few weeks ago. :-(

**Comment by burtamcgna** [comment]
Having the same issue.  It can take 60-120 seconds for Home to load accessories.  Dedicated Ubuntu running on separate VMServer. Using AppleTV  Gen 4 as Homekit server hardwired LAN.

**Comment by KhaosT** [comment]
Please check your plugins and make sure they responded the requests within a reasonable time.

**Comment by benzman81** [comment]
Its not the plugins, because over 3g/4g it loads in aboit 3 seconds. Via WLAN it takes about 10 seconds.

**Comment by KhaosT** [comment]
Huh ah I missed that part. In that case I'd suggest you run homebridge in debug mode using ``DEBUG=* homebridge`` and perform a read from your iOS device over WLAN and post the log here.

**Comment by roflcoopter** [comment]
Any update on this? I too am having the issue of devices showing 'Updating' for a minute or two before showing their state. This happens on and off and isn't a constant problem, nonetheless its frustrating.

The logs indicate no errors

**Comment by patrickroux** [comment]
+1 here !

**Comment by bjh22** [comment]
I was able to solve this issue by restarting my Apple TV Gen 4, YMMV

**Comment by estevanb** [comment]
+1 here

**Comment by i3laze** [comment]
Stale bot sucks...

+1, I’d one of devices is unresponsive, update can last for ages.

**Comment by alfienero** [comment]
+1 Now I wait roughly 30 seconds for 20-30 accessories to update. Could the high number of accessories affect the Home app startup time?

**Comment by GForceBJJ** [comment]
Can anyone help me connect my raspberry on home bridge to Wi-Fi I have no idea how to do it the device does have built-in Wi-Fi

**Comment by Marco4223** [comment]
+1 
waiting up to 50sec

**Comment by skullthug** [comment]
+1
Why is this closed? It seems to be a prominent issue.

**Comment by Kepete** [comment]
+1 issue still exists today on newest homebridge update.

**Comment by mexmetmx** [comment]
+1 
Homekit accessories bridget (tuya accesories) over homebridge control wery slow. I am using Ipad for hub.
