### ISSUE TITLE
Error: This callback function has already been called by someone else; it can only be called one time.

### ISSUE THREAD

**Issue by Schnittcher** [nfarina/homebridge#1075]
Hello, can everyone help me?
I get the following error:
```

/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:11
      throw new Error("This callback function has already been called by someone else; it can only be called one time.");
      ^

Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:11:13
    at IPSymcon.<anonymous> (/usr/lib/node_modules/homebridge-ip-symcon/index.js:97:9)
    at Request._callback (/usr/lib/node_modules/homebridge-ip-symcon/index.js:66:6)
    at Request.self.callback (/usr/lib/node_modules/homebridge-ip-symcon/node_modules/request/request.js:186:22)
    at emitTwo (events.js:100:13)
    at Request.emit (events.js:185:7)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-ip-symcon/node_modules/request/request.js:1081:10)
    at emitOne (events.js:90:13)
    at Request.emit (events.js:182:7)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-ip-symcon/node_modules/request/request.js:1001:12)
```

Can anybody help me? Here is the code of my plugin:

https://github.com/Schnittcher/homebridge-ip-symcon/blob/master/index.js

Thanks.

**Comment by KhaosT** [comment]
Your code invoked ``callback`` twice when an error occurred for request. [Here](https://github.com/Schnittcher/homebridge-ip-symcon/blob/master/index.js#L90) and [here](https://github.com/Schnittcher/homebridge-ip-symcon/blob/master/index.js#L97).

**Comment by Schnittcher** [comment]
Thank you for the answer, but what i must do?
Sorry i am a newbie.

**Comment by Schnittcher** [comment]
I have found my mistake:

At this function: https://github.com/Schnittcher/homebridge-ip-symcon/blob/master/index.js#L113

When I use .GetValue() it works.

But antoher question when I want to set the switch, how do I get the response?
I used this:

```
                this.switchService
                .getCharacteristic(Characteristic.On)
                .on('set', this.setSwitchState.bind(this))
```

 ```
   setSwitchState(callback) {
        this.log("Set Switch State...");
        if (this.data == 1) {
          var url = encodeURI(this.SetURLOff + "&device="+ this.name);
        }
        else {
          var url = encodeURI(this.SetURLOn + "&device="+ this.name);
        }
        this.log(url);
        this.httpRequest(url, "", "GET", "", "", "", function(error, response, responseBody) {
        if (error) {
          this.log('getSwitchState function failed: %s', error.message);
          callback(error);
        } else {
                 var binaryState = parseInt(responseBody);
            }
          var powerOn = binaryState > 0;
          this.data = powerOn;
          this.log("currently %s", binaryState);
    callback(null, this.data);
        }.bind(this))

      }
```

Thanks for helping me and sorry for my bad english.

**Comment by snowdd1** [comment]
Your function signature for the 'set' event function is wrong, it is supposed to be `function(value, callback, context)`  
value: the new value selected in homekit app
callback: a function you must call when your action is completed
context: an object you get passed from any `Characteristic.setValue()` invocation, so you can avoid to catch your own updates in a loop.  

[Here is how I did it.](https://github.com/snowdd1/homebridge-knx/blob/master/lib/characteristic-knx.js#L128), and if you find German comments in the code you're probably able to read it anyway!

**Comment by Schnittcher** [comment]
Thanks you, it works. :)
