### ISSUE TITLE
Homebridge with buttons

### ISSUE THREAD

**Issue by PierfrancescoElia** [nfarina/homebridge#1076]
Hello everybody!
I'm very satisfied of Homebridge and so proud of its developers! :)

I have my home, with a standard electronic plant with [buttons](http://www.dgelettroshop.it/WebRoot/StoreIT/Shops/66424/53D1/435E/8817/A7F4/7FF4/3E95/9310/952A/bticino_matix_AM5005_PULSANTE_1P_10_NO.jpg) and [step by step relay](http://laboratorioscolastico.altervista.org/wp-content/uploads/2016/02/6-rel%C3%A8-impulsi-27.jpg). (this links are examples of products that I use)

I have set up Homebridge with a test led and it works like a charm, but now I would be really happy if Homebridge could read inputs from my existing buttons, and turn on/off lights.

Reading input signals in Raspberry Pi is very easy, but if I can read a signal from a GPIO port, I don't know how to tell Homebridge "Please turn on that light!".

Does anyone have my problem? Thanks to all! :)

Edit: And if I use an NFC reader, how could I open a door when the correct tag is read? (same problem)

**Comment by cflurin** [comment]
Have a look here:
https://github.com/cflurin/homebridge-mqtt

https://github.com/cflurin/homebridge-mqtt/wiki

**Comment by PierfrancescoElia** [comment]
Thank you!

So with that plugin, I'll be able to send a JSON formatted request to the Pi (localhost) for managing my Hombridge devices, right?

I don't understand the difference between /hombridge/to/set and /hombridge/from/set....

**Comment by cflurin** [comment]
Please read the docs and take a look at the examples.

For homebridge-mqtt related issues/questions/feedback please go to:
https://github.com/cflurin/homebridge-mqtt

**Comment by PierfrancescoElia** [comment]
Hi, thanks @cflurin , but there as a misunderstanding.

I don't want to turn on a light through MQTT protocol, but I'm looking for a way to tell Homebridge that he has to turn on an existing light, maybe with an HTTP request...

**Comment by PierfrancescoElia** [comment]
Found partially the solution in #506

**Comment by snowdd1** [comment]
@PierfrancescoElia 

if you want to do some coding, and not to use the MQTT/node-red way (which is the most elegant to do it IMHO) you can take https://github.com/snowdd1/homebridge-cmd as an example how to send commands (using external - like shell scripts - programs) and how to get data into Homebridge from the shell (using `socat` [ install: `sudo apt-get install socat` on Raspbian ] )   

Happy coding.

**Comment by snowdd1** [comment]
Ahh, but reading your commend 3 days ago, you might mistaking homebridge for something that it just isn't.  

homebridge is a bridge between Apple's HomeKit and other equipment, which usually isn't HomeKit enabled, and it is not a bridge between different equipments - there you are definitely better suited using node-red, and build connectors for your buttons and actors!

**Comment by Paulraita** [comment]
Hi, PierfrancescoElia!
I have a same issue. I am trying to turn the LED on/off by external button.
Of course it works in Home App. I can control LED by clicking repository.
But can't trigger the button status in Homebridge.
If you solved this kind of issue, could you please share me your experience?
Thanks.
