### ISSUE TITLE
Can't scan code

### ISSUE THREAD

**Issue by sfyfe31** [nfarina/homebridge#1078]
I'm setting up homebridge. Got an accessory and platform set up and working. But when I try to scan the code in the iOS HomeKit app, I select "Homebridge" and it gives me less than a second to scan the code. Which isn't enough time to line it up with the camera and focus, so it fails. 

Any ideas?

![img_1114](https://cloud.githubusercontent.com/assets/10885475/22081872/46738376-ddbd-11e6-952b-c4417da1772e.PNG)
![img_1115](https://cloud.githubusercontent.com/assets/10885475/22081871/4672bc7a-ddbd-11e6-85fa-3ef63210045b.PNG)

**Comment by spopky** [comment]
I am having a similar issue, my homebridge had been working fine then all of a sudden I could not control anything with it. I deleted it from my home app on my iphone and when I try to add it again it just shows the "Select an accessory..." screen with nothing coming up.

**Comment by ehusar** [comment]
Enter the code manually.

**Comment by sfyfe31** [comment]
I can't, the "Enter Code Manually" option is only on the screen for about half a second, before it changes to the "Couldn't add Homebridge" screen. I can time repeatedly pressing it before it changes, but it still won't let me enter it manually.

**Comment by simonrb2000** [comment]
Try deleting home then removing your persist folder then restart homebridge and try again.

On 27 Jan 2017, at 23:17, sfyfe31 <notifications@github.com<mailto:notifications@github.com>> wrote:


I can't, the "Enter Code Manually" option is only on the screen for about half a second, before it changes to the "Couldn't add Homebridge" screen. I can time repeatedly pressing it before it changes, but it still won't let me enter it manually.

-

**Comment by sfyfe31** [comment]
Done. Still the same:
1. Add Accessory
2. Homebridge
3. "Position the HomeKit code in the frame" page with "Enter Code Manually" option remains on screen for about half a second. Tapping on "Enter Code Manually" does nothing.
4. "Couldn't add Homebridge" page with "Back" and "Dismiss" options.

**Comment by ehusar** [comment]
Can you get the status of Homebrige before and after you try to add it? I am not sure how you setup the load on boot but I wonder if it is crashing for some reason.  I can use the following for a quick status check.

systemctl status home bridge

Also, stop it and start it manually to see if it throws up any errors.

Maybe this will give us some clue.

Last, can you share your config file back with us?

**Comment by sfyfe31** [comment]
I just run "homebridge" in terminal on my Mac, with the following output:

```
Scotts-Mac-mini:~ scott$ homebridge
[1/28/2017, 3:31:22 PM] Loaded plugin: homebridge-nest
[1/28/2017, 3:31:22 PM] Registering platform 'homebridge-nest.Nest'
[1/28/2017, 3:31:22 PM] ---
[1/28/2017, 3:31:24 PM] Loaded plugin: homebridge-wemo
[1/28/2017, 3:31:24 PM] Registering accessory 'homebridge-wemo.WeMo'
[1/28/2017, 3:31:24 PM] ---
[1/28/2017, 3:31:24 PM] Loaded config.json with 1 accessories and 1 platforms.
[1/28/2017, 3:31:24 PM] ---
[1/28/2017, 3:31:24 PM] Loading 1 platforms...
[1/28/2017, 3:31:24 PM] Initializing Nest platform...
[1/28/2017, 3:31:24 PM] Fetching Nest devices.
[1/28/2017, 3:31:24 PM] Loading 1 accessories...
[1/28/2017, 3:31:24 PM] [Electric Blanket] Initializing WeMo accessory...
[1/28/2017, 3:31:24 PM] [Electric Blanket] Searching for WeMo device with exact name 'Electric Blanket'...
[1/28/2017, 3:31:24 PM] [Electric Blanket] Found 'Electric Blanket' device at 192.168.0.3
[1/28/2017, 3:31:29 PM] Software version for Hallway Thermostat is: 5.6-7
[1/28/2017, 3:31:29 PM] Current temperature for Hallway Thermostat is: 21.5 C
[1/28/2017, 3:31:29 PM] Current heating for Hallway Thermostat is: Heating
[1/28/2017, 3:31:29 PM] Current humidity for Hallway Thermostat is: 40%
[1/28/2017, 3:31:29 PM] Target temperature for Hallway Thermostat is: 22 C
[1/28/2017, 3:31:29 PM] Target heating for Hallway Thermostat is: Heating
[1/28/2017, 3:31:29 PM] Away for Hallway Thermostat is: 1
[1/28/2017, 3:31:29 PM] Initializing platform accessory 'Hallway Thermostat'...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[1/28/2017, 3:31:29 PM] Homebridge is running on port 56530.
```

When I try to add it in the Home app on my iPhone, nothing else is logged. Again, just goes immediately to "Couldn't add Homebridge" screen.

Here's my config file (I've changed the connection keys):

```
{
  "bridge": {
    "name": "Homebridge",
    "username": "CC:22:3D:E3:CE:30",
    "port": 56530,
    "pin": "031-45-154"
  },

  "description": "This is an example configuration file",

  "accessories": [
    {
      "accessory": "WeMo",
      "name": "Laura's Electric Blanket",
      "wemo_name": "Lauras Electric Blanket"
    }
  ],
  "platforms": [
    {
      "platform": "Nest",
      "token": "blahblahblah",
      "clientId": "blahblahblah",
      "clientSecret": "blahblahblah",
      "code": "blahblahblah"
    }
  ]
}
```

**Comment by ehusar** [comment]
No errors so I don't see anything wrong there.  Out of curiosity cut your Nest out and see if it fails again.  Also change your user name to force a refresh.

**Comment by sfyfe31** [comment]
Done and done. Still the same. Also tried removing the WeMo, still the same.

**Comment by ehusar** [comment]
What apple device and iOS version are you running?   Do you have more than one device to test with?

**Comment by ehusar** [comment]
I just noticed your port is different than mine.  Did you setup that custom port?   It would seem like if the port isn't accessible it might fail immediately.

**Comment by ehusar** [comment]
If you want to try another port mine is set to 36631.

**Comment by sfyfe31** [comment]
Not sure where I got that port from. Possibly the original guide I read on how to setup homebridge. Tried the one from the sample config (51826) and 36631. Still the same.

**Comment by natedlee** [comment]
I am having the exact same issue. @sfyfe31 did you figure anything out? 

Also, that default port is what's in the config-sample.

**Comment by hyperbart** [comment]
Just for shits and giggles, try changing the name, mac address and the pairing PIN, then remove persist and retry. Once had this problem too.

**Comment by xupapaya** [comment]
hi,It took me a week's time,I have successfully solved this problem.My previous ios version was 10.2.Now has been updated 10.3.The key to the 10.3 “HOME ”APP has a new button allows you to delete the family configuration.Deleted after a new family,It will tell you whether to allow mistrust of accessories.you call yes,than,it's can Add your parts, give it a try.

**Comment by WeiyiLi** [comment]
Hi @sfyfe31 , I have the same issue, have you figured out the solution for it? Can you share your solution?

**Comment by NSCabezon** [comment]
same issue here... :(

**Comment by respectTheCode** [comment]
Same issue here. Changing name, pin and port had no effect. Tried with both iOS 10.3 and iOS 11 dev beta 3.

After entering my code I get the "Couldn't add Homebridge" screen.

**Comment by AppleTechy** [comment]
@respectTheCode Sounds like a compatibility issue with the way homebridge exposed stuff to homekit and thats why the pairing failed. I would try updating to the latest homebridge as I believe most of the IOS 11 issues have been fixed.

**Comment by respectTheCode** [comment]
I can confirm that homebridge is working again

**Comment by AppleTechy** [comment]
@respectTheCode Glad to hear that!

**Comment by tristanpemble** [comment]
I had this issue and disabling my macOS firewall fixed it.
