### ISSUE TITLE
Homebridge wont connect iphone 7 plus ios10.2

### ISSUE THREAD

**Issue by Lestercity** [nfarina/homebridge#1082]
I have the strangest issue and cant manage it myself after couple of hours trial and error. I had homebridge running perfectly fine with following plugins: hue, harmony, denon-volume. Today I made some wiring changes to my devices and some devices ip changed and I needed to do some changes in the config.json. After that the devices in homekit app added by homebridge plugins were very slow reacting so I started to reset my whole homebridge setup by deleting homebridge and with it all the plugins to do a fresh install. End of the story: when I try to add accessory in Home app iphone 7 plus ios10.2 it sees Homebridge but it wont connect, it keeps spinning and after a long time it fails connecting. The strange thing is when I open the Home app on my wifes iPad ios 10.2 it connects perfectly fine. The things I already tried: uninstall homebridge and plugins, reinstall homebridge and plugins, but  connecting still fails. Deleting persits folder and accessory folder, but connecting still fails. Changed bridge name, username in config.json, but connecting still fails. Signed out of iCloud from my iPhone and Atv4, but connecting still fails. The last thing I did, because it was connecting perfectly fine with iPad on the same ios 10.2 so thought it was a problem on the iPhone side, was restoring my iphone as new iPhone, but after it wont connect too. Now I am at the point that I dont no what to do next. Please help me out.

**Comment by ehusar** [comment]
I am on iPhon 7 Plus without any issues.

Would recommend removing all entires from your config file except one. See if you can get that one work. Then add the rest in one at a time.  Most likely there is an error in your config.  

This would be my plan of action anyway.  Good luck.
