### ISSUE TITLE
Completely uninstall

### ISSUE THREAD

**Issue by VeniceNerd** [nfarina/homebridge#1086]
Hey guys,

can anyone help me to completely uninstall Homebridge? I'd like to remove every trace of it so that I can start with a fresh install. Simply using the terminal "uninstall" command does not need to solve my issues. I would like a complete fresh start so that I can get Homebridge working again.

Thanks,

Philipp

**Comment by rfiorentino1** [comment]
Same question here. I tried to do something with a plug-in to incorporate another commit and I messed it up. Now when I try to reinstall home bridge complains about an already existing UU ID. Very annoying, and now I can't use it at all  :(

**Comment by phathak** [comment]
Anyone found an answer to that? I'm trying to achieve the same here. 
Thanks
