### ISSUE TITLE
Homeautomation with iPad wont work

### ISSUE THREAD

**Issue by MarcelS04** [nfarina/homebridge#1088]
Hi guys maybe you can help me.

I'm running homebridge for a few month now and everything runs well.

Now i got a new iPad and wanted to test the automation but it won't work. I tried several configuration (multiple or single devices etc.)

Did it work for anyone of you or is this a common problem?

**Comment by snowdd1** [comment]
Can you access the home from iPad? Can you access your home using cellular, with iPad as homekit central? 
When I switched to iOS10 last year, I had to re-create my home on my iPad before everything went smoothly. iCloud sync didn't do the trick somehow.

**Comment by MarcelS04** [comment]
Hi,

I can access everything and also from my iPhone in cellular mode.

I restarted homebridge and deleted it from HomeKit + paired it again. Still it's not working.

**Comment by MarcelS04** [comment]
Nevermind, after updating the iPad with newest iOS and restarting the router it works like a charm.
