### ISSUE TITLE
Error on starting server

### ISSUE THREAD

**Issue by cali0028** [nfarina/homebridge#109]
Getting the following error when trying to run "npm run start"

Starting HomeBridge server...
_________________________________________________________________________
IMPORTANT: Homebridge is in the middle of some big changes.
           Read more about it here:
           https://github.com/nfarina/homebridge/wiki/Migration-Guide
_________________________________________________________________________
undefined:2
	 "description": "JSON API”, 
	                            ^
SyntaxError: Unexpected token 

    at Object.parse (native)
    at Object.<anonymous> (/home/pi/homebridge/app.js:31:19)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

npm ERR! Linux 3.18.11+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
npm ERR! node v0.12.6
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE
npm ERR! homebridge@0.0.0 start: `DEBUG=* node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the homebridge@0.0.0 start script 'DEBUG=* node app.js'.
npm ERR! This is most likely a problem with the homebridge package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     DEBUG=* node app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls homebridge
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/homebridge/npm-debug.log

**Comment by nfarina** [comment]
It looks like there is an error with your `config.json` - perhaps a missing colon directly above the line it calls out:

> "description": "JSON API”,

**Comment by cali0028** [comment]
Nope there is no other line before that. This is how it starts

{ "description": "JSON API”,
  "platforms": [
        {       "platform": "SmartThings”,
                "name": "SmartThings”,
                "app_id":

**Comment by nfarina** [comment]
Can you try pasting the entire file here: http://jsonlint.com and validating?

**Comment by cali0028** [comment]
I found the problem...it was the quote in the end... it's diff.

**Comment by nfarina** [comment]
Ah good catch. I just made some commits to master that should improve the messaging for this scenario in the future.
