### ISSUE TITLE
auto restart service on Ubuntu mate

### ISSUE THREAD

**Issue by lowrisk** [nfarina/homebridge#1090]
Hi, 

I didn't manage to auto start on Ubuntu Mate, any official tutorial ?
I run the homebridge command on the Ubuntu Mate from SSH (on OSX Server) so I often have message like Pipe Broke or socked hangup and have to restart manually.

**Comment by NorthernMan54** [comment]
The tutorial you are looking for is here

https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi#running-homebridge-on-bootup-systemd
