### ISSUE TITLE
how-to accessory a ADS1115?

### ISSUE THREAD

**Issue by diogenisd** [nfarina/homebridge#1091]
Nick hi,
Is there an easy way to make an accessory and use my ADS1115 with homebridge server?

**Comment by NorthernMan54** [comment]
This is definitely doable, but would need a fair bit of effort.  Is their an existing plugin that is close to what you are attempting to monitor with ADS1115?   I’m using one to monitor open/close on my garage door.

My pattern is a bit complex though, as I’m using the ESP8266 to monitor the door and other things, and I have homebridge calling a web service to read the ADS1115 connected to the ESP.

**Comment by diogenisd** [comment]
well there is a guy that used have used it to read his soil sensor here: https://github.com/lucavb/homebridge-soil-moisture-sensor-digital
