### ISSUE TITLE
Calling scene 'Good Night' screwing configuration up

### ISSUE THREAD

**Issue by sirdir1972** [nfarina/homebridge#1092]
I've been redonig my configuration over and over again. Now I think I've found the tripping point: Whenever I call the  scene 'Good night', shortly after everyhting goes south. Sometimes a device disappears and doesn't come back, sometimes other things happen. This time everyhting seems to be mixed up. My garage door sudeenly hat a temperature instead of a state, my termp. sensor was suddenly a lamp, the lamp something else... I'll avoid defining a scene now and see whether that helps.

**Comment by Dirtrunner702** [comment]
This sounds like very odd behavior. When was the last time you rebooted your homebridge instance? 
What platform do you have homebride running on?

**Comment by sirdir1972** [comment]
Oh, I'm rebooting it 'constantly' (every day at least once) right now because I'm fiddling with homeassistant and I get 'too many open files' after some restarts. 
It's on an old mac mini running  Ubuntu 16.04.1 LTS.
I'm not even sure if homebridge is to blame, might also be an apple problem (!?)

**Comment by danielsen2009** [comment]
I was running on a core 2 Mac mini for a while (won't support Sierra so used ubuntu), after switching to a pi3 as a gateway I haven't had any random/weird problems. I've tested with a 2011 iMac and everything runs fine as well. It seems like the older minis are a bit unstable. At least the core 2s IMO.

**Comment by sirdir1972** [comment]
> Am 30.01.2017 um 17:36 schrieb Erik <notifications@github.com>:
> 
> I was running on a core 2 Mac mini for a while (won't support Sierra so used ubuntu), after switching to a pi3 as a gateway I haven't had any random/weird problems. I've tested with a 2011 iMac and everything runs fine as well. It seems like the older minis are a bit unstable. At least the core 2s IMO.
> 

Huh, I had it running on a pi2 for a long time as well (but with a much simpler config) … but that pi2 is outside, near the main gate and connected to the lan by powerline… and gets disconnected every now and then… so I wanted to have it on a ‚stable‘ computer ^^…
but I’ll see, I have alternatives. But I can’t really believe it’s really mini-related. I had a crash every 6 months or so, but otherwise it has been running without problems.

**Comment by sirdir1972** [comment]
I switched to an other pc now. Just tried ‚good night‘ again - this time, all netatmo sensors (or the ones that get bridged from homeassistant at least, co2 doesn’t show up, no matter what I try) ‚jumped‘ from their respective rooms to ‚Standardraum‘ (guess it’s called standardroom in English).
Needless to say that ‚Good night‘ doesn’t change anything regarding the sensors, they’re basically ‚read only‘ anyway.

BTW the reason why I used them bridged instead of directly with homebridge is that I have stations from other people connected to my account and it seems you can’t hide them in homebridge, but you can in homeassistant. 

regards
Patrick
