### ISSUE TITLE
generic set temperature (http thermostat)

### ISSUE THREAD

**Issue by sommo** [nfarina/homebridge#1093]
Hi,
i have a wemos with dht (for temperature and humdity) and a relay, both are managed via wifi (http).
so i would to know how to start to use it as a wifi thermostat, for setting up a desired temperature (like a dimmer from homekit), reading temperature and turn it on or off)...
I read around but i can't figured it out how to start.. if someone could point me to a project.. thank you ppl!

**Comment by metbosch** [comment]
You can search plugins in www.npmjs.com. I think that you are looking for that:
https://www.npmjs.com/package/homebridge-http-temperature
https://www.npmjs.com/package/homebridge-http-thermostat

**Comment by sommo** [comment]
thank u @metbosch , i read those plugin, but i still have a question:
how can i set a target temperature.
my setup is:
-arduino with dht tempeture and relay (all exposed and controlled by http), simple as that, but:
i would like to read the temperature (and i did it)
i would like to control the relay on/off (and i did it)
i would like to set a temperature (so the relay stay "up" until it get the temperature desired), how can i do that?
did the homebridge store the value of the target temperature, or i have to create into the arduino a webpage dedicated to expose a trigger value?
the final result, in my thought, is that i have an icon (on homekit dashboard) that i can read the temperature, push it and set it on by selecting the target temperature (dimmable selection, like brightness for hue).
does it works like that homekit compatible thermostat?
thank you

**Comment by metbosch** [comment]
@sommo 
Sorry for my first response, I didn't check the homebridge-http-thermostat and it is more or less the same as homebridge-http-temperature.
As you already found, what you need is https://github.com/PJCzx/homebridge-thermostat. This will expose all the devices that you want (temperature, humidity and thermostat), the README is quite simple but should be enough for you.
Your Arduino has to provide two main API calls:
 * <arduino ip>/status: That returns a JSON with the current state.
 * <arduino ip>/targetTemperature/<desired temp>: That sets the target temperature and is the arduino which switches on the relay until the DHT reads the target temperature.
Also looking the code, there are other API calls:
 * <arduino ip>/off: Turn off the thermostat.
 * <arduino ip>/comfort: Activate the heating mode.
 * <arduino ip>/no-froost: Activate the cooling mode.
 * <arduino ip>/auto: Automatic heating/cooling mode.
