### ISSUE TITLE
Error when own 2 tellsticks

### ISSUE THREAD

**Issue by yabbah** [nfarina/homebridge#1095]
Hi, at my home I have 2 tellstick nets, and when fire homekit up I got an error when it came to add my devices on the second unit:

`Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 9879f625-6d9e-4397-8ded-0c3225a76ca3
`

Any idea how to solve it?

I tried specify "tellstick downstairs" and "tellstick upstairs" in config.json without success.

**Comment by KhaosT** [comment]
This is a issue with the plugin. Please have the plugin provide a unique accessory identifier by provide a unique name for the accessory or set `uuid_base` on the accessory instance to a different value for each accessory.

**Comment by yabbah** [comment]
uhm, I dont really understand what you mean with this? Can you point me to the config where I shall change?

**Comment by KhaosT** [comment]
There is no way you can do that by just changing the configuration file. It has to be done by the developer who made the plugin.
