### ISSUE TITLE
When the light is on and i say siri turn the light on it turns off

### ISSUE THREAD

**Issue by Schnittcher** [nfarina/homebridge#1097]
Hello,

when the light is on and i say siri turn the light on, it turns off is that a bug?

**Comment by snowdd1** [comment]
Can you elaborate some more on the setup?  
AFAIK that hasn't been reported by anyone else, so it might be very specific to your configuration. Which plugin did you use for the light?

**Comment by Neelrp12** [comment]
Remove homebridge from the home app then add it again.
