### ISSUE TITLE
Problem after adding homebridge-delay-switch accessories

### ISSUE THREAD

**Issue by zork17** [nfarina/homebridge#1098]
After I added 5 DelaySwitch-es to my config.json as accessories, I had to remove Homebridge from the house, empty persist and accessories folders and add the bridge from the start.
The house appeared empty and the bridge was not accessible.

The only other plugins that are installed are http-webhooks and KNX.

**Comment by snowdd1** [comment]
Sorry, did I miss the question in your issue?

**Comment by zork17** [comment]
I will try to give more details.
1) I had the system working with knx and HttpWebHooks plugins and DelaySwitch accessories.
2) I then added HomeAssistant plugin. HomeAssistant is not installed on the same machine.
3) When I restarted homebridge, I couldn't connect to it from IOS.
4) I started to remove plugins and uninstall them.
5) Now I have only knx and HttpWebHooks installed and working.
6) When I add even one DelaySwitch accessory and restart homebridge - when I open the Home app in IOS I see that the home is empty (no devices). It asks me to add the first device.
7) The homebridge hub is in the main room but it is with red text saying no response status.
8) This is the debug log:
[daemon.txt](https://github.com/nfarina/homebridge/files/757565/daemon.txt)
9) After I deleted homebridge from the main room on IOS and deleted the persist folder on raspberry pi.
And I still can't add homebridge as a device.
10 I get the following log:

Feb 6 15:03:29 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:29 GMT EventedHTTPServer [::ffff:10.0.0.51] New connection from client
Feb 6 15:03:29 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:29 GMT EventedHTTPServer [::ffff:10.0.0.51] HTTP server listening on port 42391
Feb 6 15:03:29 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:29 GMT EventedHTTPServer [::ffff:10.0.0.51] HTTP request: /pair-setup
Feb 6 15:03:29 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:29 GMT HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-setup
Feb 6 15:03:29 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:29 GMT HAPServer [CC:22:3D:E3:CE:30] Pair step 1/5
Feb 6 15:03:30 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:30 GMT EventedHTTPServer [::ffff:10.0.0.51] HTTP Response is finished
Feb 6 15:03:39 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:39 GMT EventedHTTPServer [::ffff:10.0.0.51] HTTP request: /pair-setup
Feb 6 15:03:39 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:39 GMT HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-setup
Feb 6 15:03:39 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:39 GMT HAPServer [CC:22:3D:E3:CE:30] Pair step 2/5
Feb 6 15:03:40 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:40 GMT EventedHTTPServer [::ffff:10.0.0.51] HTTP Response is finished
Feb 6 15:03:40 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:40 GMT EventedHTTPServer [::ffff:10.0.0.51] HTTP request: /pair-setup
Feb 6 15:03:40 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:40 GMT HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-setup
Feb 6 15:03:40 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:40 GMT HAPServer [CC:22:3D:E3:CE:30] Pair step 3/5
Feb 6 15:03:40 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:40 GMT HAPServer [CC:22:3D:E3:CE:30] Pair step 4/5
Feb 6 15:03:40 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:40 GMT HAPServer [CC:22:3D:E3:CE:30] Pair step 5/5
Feb 6 15:03:40 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:40 GMT Accessory [Homebridge] Paired with client F0DDFA9D-38B6-4FE6-94C1-6B95407DF026
Feb 6 15:03:40 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:40 GMT EventedHTTPServer [::ffff:10.0.0.51] HTTP Response is finished
Feb 6 15:03:40 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:40 GMT EventedHTTPServer [::ffff:10.0.0.51] Client connection closed
Feb 6 15:03:40 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:40 GMT EventedHTTPServer [::ffff:10.0.0.51] HTTP connection was closed
Feb 6 15:03:40 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:40 GMT EventedHTTPServer [::ffff:10.0.0.51] HTTP server was closed
Feb 6 15:03:40 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:40 GMT EventedHTTPServer [::ffff:10.0.0.51] New connection from client
Feb 6 15:03:40 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:40 GMT EventedHTTPServer [::ffff:10.0.0.51] HTTP server listening on port 41380
Feb 6 15:03:40 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:40 GMT EventedHTTPServer [::ffff:10.0.0.51] HTTP request: /pair-verify
Feb 6 15:03:40 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:40 GMT HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify
Feb 6 15:03:40 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:40 GMT HAPServer [CC:22:3D:E3:CE:30] Pair verify step 1/2
Feb 6 15:03:40 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:40 GMT EventedHTTPServer [::ffff:10.0.0.51] HTTP Response is finished
Feb 6 15:03:40 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:40 GMT EventedHTTPServer [::ffff:10.0.0.51] HTTP request: /pair-verify
Feb 6 15:03:40 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:40 GMT HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify
Feb 6 15:03:40 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:40 GMT HAPServer [CC:22:3D:E3:CE:30] Pair verify step 2/2
Feb 6 15:03:40 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:40 GMT HAPServer [CC:22:3D:E3:CE:30] Client F0DDFA9D-38B6-4FE6-94C1-6B95407DF026 verification complete
Feb 6 15:03:40 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:40 GMT EventedHTTPServer [::ffff:10.0.0.51] HTTP Response is finished
Feb 6 15:03:40 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:40 GMT EventedHTTPServer [::ffff:10.0.0.51] HTTP request: /accessories
Feb 6 15:03:40 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:40 GMT HAPServer [CC:22:3D:E3:CE:30] HAP Request: GET /accessories
Feb 6 15:03:40 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:40 GMT EventedHTTPServer [::ffff:10.0.0.51] HTTP Response is finished
Feb 6 15:03:41 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:41 GMT EventedHTTPServer [::ffff:10.0.0.51] HTTP request: /pairings
Feb 6 15:03:41 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:41 GMT HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pairings
Feb 6 15:03:41 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:41 GMT HAPServer [CC:22:3D:E3:CE:30] Removing pairing info for client
Feb 6 15:03:41 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:41 GMT Accessory [Homebridge] Unpairing with client F0DDFA9D-38B6-4FE6-94C1-6B95407DF026
Feb 6 15:03:41 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:41 GMT EventedHTTPServer [::ffff:10.0.0.51] HTTP Response is finished
Feb 6 15:03:41 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:41 GMT EventedHTTPServer [::ffff:10.0.0.51] Client connection closed
Feb 6 15:03:41 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:41 GMT EventedHTTPServer [::ffff:10.0.0.51] HTTP connection was closed
Feb 6 15:03:41 RSBPI homebridge[1503]: Mon, 06 Feb 2017 13:03:41 GMT EventedHTTPServer [::ffff:10.0.0.51] HTTP server was closed

If I remove the DelaySwitch accessory I could add homebridge again.

This is what is installed:
npm list -g --depth=0
/usr/lib
├── homebridge@0.4.9
├── homebridge-delay-switch@0.0.1
├── homebridge-http-webhooks@0.0.22
├── homebridge-knx@0.3.3
├── node-gyp@3.4.0
└── npm@3.10.8

What is the problem?
What can I do in order to add DelaySwitch accessories?

**Comment by snowdd1** [comment]
Looks as if the response to HomeKit is non compliant with the delay switches. The whole bridge gets unpaired from HomeKit.  

BTW update your homebridge-knx, too!

**Comment by snowdd1** [comment]
You might try to raise the question at the delay-switch repository.

**Comment by zork17** [comment]
How do I update homebridge-knx?
I ran:  sudo npm -g update homebridge-knx
but it stayed on 0.3.3

How can I know what is the latest version and how can I force an update?
If 0.3.3 is not the latest, why there was no update?

**Comment by snowdd1** [comment]
No idea, you might try putting the `-g` after the `update`. Or just `npm install` it over the old version.

**Comment by zork17** [comment]
@snowdd1 
I updated all the plugins. Indeed -g was necessary.
The homebridge-delay-switch still causes homebridge to be inaccessible from IOS and then I must delete it from the home, delete persist and accesssories folders on Raspberry PI and start everything from the beginning (90+ knx devices in many rooms...) = nightmare.

Maybe you can think of something?
Or do you know of another way to have a delay? I want some lights to go off after a certain amount of minutes have passed.
