### ISSUE TITLE
Error: ENOENT, no such file or directory

### ISSUE THREAD

**Issue by nzhome** [nfarina/homebridge#110]
pi@raspberrypi ~/node_modules $ npm install homebridge
node.js:720
    var cwd = process.cwd();
                      ^
Error: ENOENT, no such file or directory
    at Error (native)
    at Function.startup.resolveArgv0 (node.js:720:23)
    at startup (node.js:63:13)
    at node.js:814:3

**Comment by nzhome** [comment]
fixed it 
cd /node_modules
rm -r homebridge
npm install homebridge

**Comment by nfarina** [comment]
If you're installing homebridge from npm, I recommend updating to the latest version (just published) as there are many changes since the last npm version.
