### ISSUE TITLE
Homebridge + 433mhz + transmitters + status lamp

### ISSUE THREAD

**Issue by poudenes** [nfarina/homebridge#1100]
Hi There,

Im so happy i found homebridge in combination with my Raspberry!!! Some config and all my stuff are controlled now !!! (KaKu lamp, Nest Thermostat, Harmony Hub, ifttt, ssh and some info things like weather, temperature RPi, and web hooks)

Im using the new KaKu transmitters and receivers. (Auto learning) and want to know if Homebridge have the power and plugin to do follow (I know Domoticz can)

I turn on a lamp using a switch on the wall (Transmitter) the lamp goes on. Now i want have a plugin or config so Homebridge receive same command and put the lamp on in his config. 

Now when i put on a lamp using a switch on the wall, the lamp goes on, but in homebridge/Homekit lamp still show off, because there was no interaction to put it on as well.

Cheers,
Peter

// Keep up the good work !!!

**Comment by snowdd1** [comment]
You need to install a plugin that understands the wall switch's protocol. Did you search npmjs.org for a plugin that might fit? Or contact the maintainer of the KaKu lamp plugin, if th feedback can be integrated into the existing plugin.

**Comment by poudenes** [comment]
installed the KaKu plugin and then got a error. Homebridge didn't startup.
I will do a clean install of everything because i also was playing around with Pimatic and Domoticz on same system ...

**Comment by Yardco** [comment]
Kaku switches only support one way communication e.q. receiving commands and not sending them, so it doesn't provide any feedback about it's on or off state back to homebridge. So when switching lights off or on using the wall switch, homebridge has no way of telling the status of the lamp has changed.
