### ISSUE TITLE
Motion Sensor Status over Internet

### ISSUE THREAD

**Issue by djnews24** [nfarina/homebridge#1101]
Hi ,
anyone notice that motion sensors are not react to changes when the phone is remote only?
AppleTV 4 works correctly i see my other things will send push notification when for example i open my windows. But the Motion Sensor added via Homebridge will send only notifications when i am on the same wlan. I configurated the sensor to send notifciations on changes.

**Comment by StefanMeGit** [comment]
sorry, wich motion sensor plugin are u using? Try to find one...

**Comment by ebaauw** [comment]
@sbpaul I do get `Motion detected in ...` notifications from Home on my iPhone over 4G.  I suspect you need a Home Hub for that, though.  Maybe the sync of your HomeKit configuration to your AppleTV failed?  Mine does every once in a while...

@StefanMeGit I'm using Philips Hue motion sensors through my homebirdge-hue plugin.

**Comment by StefanMeGit** [comment]
Ah ok. Thx!

The over cellular notifications are also working for me now quiet good. I use a AppleTV 4 as HomeKit Bridge.

**Comment by sbpaul** [comment]
Found a solution for me: https://github.com/jspv/HAP-NodeJS/commit/932ef587bee27cd3788c066d52cfd559ab556b3a#diff-00b357729430bdec42cba36540307f8a
