### ISSUE TITLE
Video intercom support question

### ISSUE THREAD

**Issue by brownad** [nfarina/homebridge#1104]
Hi

I've created a very simple video doorbell which sends the iOS notification correctly when the doorbell is pressed.  Using the ffmpeg plugin and my one for doorbird to listen to the doorbird api. This is fine.

When the notification is shown you get the option to swipe across and 'View' bringing the camera to live on the notification. Similar to the keynote.  On the video stream the 'intercom' is disabled so it's not possible to stream two way. Given the doorbird supports two way in their api is there a way to do this in homebridge / HomeKit? Or can't work yet due to ffmpeg?

**Comment by KhaosT** [comment]
Yeah, ffmpeg is not designed for this. You'll need to write your own plugin for this purpose.

**Comment by brownad** [comment]
Cool

Are there any other video plugins out there with similar audio support?

**Comment by KhaosT** [comment]
I think there is a foscam one that supports bidirectional audio

**Comment by brownad** [comment]
Thanks I'll look into it.  Btw is there such support for video doorbell type yet or I need to separate the doorbell and the video platforms?

**Comment by KhaosT** [comment]
HomeKit defines two separate services, Doorbell Service and Stream Management Service. You can have both on an accessory instance.
