### ISSUE TITLE
Not a issue, but a idea

### ISSUE THREAD

**Issue by poudenes** [nfarina/homebridge#1106]
Hi All,

Im not a programmer so love everyone who are... 
I love the homebridge tool include the plugins. 

Is it a idea that Homebridge stores the settings of all accessories, platform etc into a database.
Because if you have to reset your RPi and everything restart the app on phone shows for example every licht bulb is off.. but before resetting your RPI you turned on the lichts using the app on phone.

Cheerts,
Peter

p.s. i know pimatic does, but would be cool if you can use 1 solid application for eveything

**Comment by snowdd1** [comment]
Depends on the plugin today. All plugins that use the 2016 API and use the "dynamic" platform model get their data cached in homebridge.  
Those that don't , don't. 

See enhancements in #1039, mandatory accessory caching.
