### ISSUE TITLE
homebridge running iphone will not connect

### ISSUE THREAD

**Issue by typhoonss92** [nfarina/homebridge#1107]
I had homebridge up and running for months on a RPi raspbian jessie with systemd. no issues then last week it just disconnected. My setup is the RPi with OpenHab and homebridge, Apple TV4 which allowed outside access and automation and 2 iPhone 6. I noticed the ATV4 updated to IOS 10.1.1 from 10.0.1 and the iPhones are on 10.2.1. I have done all the basic things like change the name, username, port and pin in the config.json file. Also deleted the persist and accessories folders multiple times. I used the Bonsour browser from my macOS and see the hap service running on the RPi. I have a backup of just Openhab for the RPi and restored to that and reinstalled homebridge, same thing verify it is running on the RPi and that it is seeing the sensors and no errors using (homebridge -U /var/homebridge) in the terminal to see if all is running good. The iPhone homeapp see's the homebridge and I put in the pin but then says coundn't connect. Also I have turned off ipv6 as I saw that has helped others. I did not update the RPi or make any other changes to network besides the ATV4 updating. Anyone seen anything like this?

**Comment by fireheadman** [comment]
Having a similar issue, posted to this issue  [https://github.com/nfarina/homebridge/issues/1110](https://github.com/nfarina/homebridge/issues/1110)

I was able to use my ipad to reconnect to homebridge... afterwards my iphone started seeing my devices in the Devices and Home Apps.

**Comment by typhoonss92** [comment]
I have 2 things to helpout with. 
to see journal logs I have to run the following hopefully this can help others
sudo journalctl -u homebridge -f

Second if anyone is having couldn't connect to this accessory from device to homebridge verify how many accessories you have, I have one platform openHAB but every accessory created in it or item is concidered an accessory. there is no error for over 100 accessories and 100 is the max per homebridge. For the openhab to homebrige addon there is a skipitem true function you can add to your config.json which will not sync the items you do not need. This will take time to sync mine took around 24 hours before I could access the accessories just use the journal line above and once it starts showing your accessories getting data not resgitering you will be good.
Hope this helps anyone with this issue
