### ISSUE TITLE
Can we make homebridge 'appear' as a Lutron Smart Bridge?

### ISSUE THREAD

**Issue by infernusdomoso** [nfarina/homebridge#1108]
I'm trying to add my raspberry pi homebridge to my Harmony hub. NOT the other way around - I have homebridge controlling the harmony just fine. I want to add the homebridge to harmony, so I can set up a Harmony activity, where when I press 'watch tv' on my Harmony remote, in addition to turning on the TV, it will turn off the homebridge controlled lights.

So far nothing I do in the Harmony app will find or add the homebridge. Is there an easy way to do this?

**Comment by crzcrz** [comment]
You need to create an automation in Home app on iOS. Create a trigger "An accessory is controlled" and add any actions you want.
