### ISSUE TITLE
Error:Cannot find module

### ISSUE THREAD

**Issue by DTO213** [nfarina/homebridge#1109]
I've install "mdns" but the program can't find "dns_sd_bindings"

module.js:472
    throw err;

Error: Cannot find module '../built/Release/dns_sd_bindings'

What should I do？cp the files to the correct position？

Please help me.

**Comment by roadiemoose** [comment]
Since you closed this issue, I assume you found a solution?? Care to share with the rest of the group in case someone else is having this same problem?

Thanks

**Comment by DTO213** [comment]
reinstall node and nodejs then reinstall homeassistant.I think “node”or“nodejs”may cause the issue.

**Comment by DTO213** [comment]
@roadiemoose
