### ISSUE TITLE
Add HomeKit Accessory timeout, can not recover.

### ISSUE THREAD

**Issue by nzhome** [nfarina/homebridge#111]
if the "enter the code" to add accessory times-out.   Then an error shows, and the accessory disappears, and never comes back :(  can this please be looked at?

Client Disconnected
Server Disconnected
New Session 51080
Server Connection Established 58339
Client Disconnected
New Session 51081
Server Connection Established 58340
Start Verify M1
Verify M1 Finished
Server Disconnected
Start Verify M3
M3: Verify Success

**Comment by cflurin** [comment]
I hat a similar case too, check the "intitalValue: "  in your service. I think if it's undefind then it doesn't work.

**Comment by nzhome** [comment]
not sure.  I am just going to reset the homekit on the iphone and rm  the homebridge and try again.

**Comment by nzhome** [comment]
I reset everything, took me 27 minutes to reinstall homebridge and reset homekit on iphone.

this time if I entered the code quicker it worked.  but if you leave it for a minute.. it all falls apart, and you have little choice but to throw it all away and start again :(

TCP server accepting connection on port: 51882
HAP Server is listening
New Session 51126
Server Connection Established 58585
Start Pair M1
Start Pair M3
Start Pair M5
Client Disconnected
New Session 51127
Server Connection Established 58586
Start Verify M1
Verify M1 Finished
Server Disconnected
Start Verify M3
M3: Verify Success

**Comment by nfarina** [comment]
Can you try using the latest homebridge from npm or from master branch of this repo? The pairing process has been majorly reworked since last npm version.

**Comment by nzhome** [comment]
@nfarina yes I am using your new version ALWAYS. i clearly stated I have done "npm install homebridge".

**Comment by KhaosT** [comment]
@nzhome the latest version shouldn't log anything like this ... 
``
Start Verify M1
Verify M1 Finished
Server Disconnected
Start Verify M3
M3: Verify Success
``

**Comment by nzhome** [comment]
@nfarina, thanks for updating the npm install homebridge..  thats much better now.
"nfarina published 15 hours ago"  new https://www.npmjs.com/package/homebridge  
the new version comes via npm install, thanks.   I will close the issue.

**Comment by younghyunjo** [comment]
@KhaosT
What was the problem?
I am working with ESP32, i am struggling same issue
