### ISSUE TITLE
Pairing Homebridge - will not connect

### ISSUE THREAD

**Issue by fireheadman** [nfarina/homebridge#1110]
Craziest thing happened today so far....
I know there was some connectivity issues with ST today (saw the alerts and got the status email).... also know there was an email about pdlove (homebridge-smartthings) app in regards to settings from ST (also got that email).

This evening I tried to use Siri and she didn't know about anything, so opened up the Home app and most of my devices had a "No Response" coming from them.   So I restarted homebridge.   This did nothing.

I check my versions... those seemed ok.
I then removed/deleted my "home" from the Devices App and attempted to build everything back up from scratch.

...BUT now I am stuck with homebridge starting up ok and Devices just sitting there at the PAIRING HOMEBRIDGE screen.   Hoping maybe there is a debug for this?  Open to suggestions.
It was working flawlessly for over a month.

**Comment by fireheadman** [comment]
I will add this too...
I have stripped out the smartthings piece just to simplify things.

```
[user@fire .homebridge 3058]$ cat config.json
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "003-14-037"
    }

}
```

**Comment by fireheadman** [comment]
To make this issue more interesting....   I saw another issue that mentioned it wasn't working with their iphone.   So I pulled out my ipad.

Both my iphone and ipad are connect to the same WiFi network.   However, I was able to PAIR HOMEBRIDGE using my iPad.   Afterwards, I opened Devices App on my iphone and now I see everything again.

Something isn't compatible/working with the iPhone7.

**Comment by KhaosT** [comment]
Err, have you tried to reboot your iPhone?

**Comment by fireheadman** [comment]
yes, rebooted phone already.
My issues appears to be related to another open issue [https://github.com/nfarina/homebridge/issues/1107](url)

For now, the workaround is to add homebridge via my ipad, then I can access everything on my iphone.

**Comment by tmarcus02** [comment]
What version of IOS are you running I'm having the same issue with my iPhone & iPad. I have Homebridge running on MacOS which just update the same day I started having issues, also my iPhone & iPad have updated to 10.2.1

**Comment by Neelrp12** [comment]
Delete your accessory and persist folders on your computer then try and run homebridgeagain , then try to add it to your iphone. Make sure bluetooth is turned on when your are pairing it.

**Comment by fireheadman** [comment]
what role does bluetooth have in this?  homebridge is run from my mac-mini.... It should be running over the network, through the router, connecting through the JSON API on smartthings.
  
A little confused on the bluetooth piece.
But for $hits and Giggles, I wiped those dirs out, turned on bluetooth for my iPhone, and started homebridge back up.   I see no errors in the output, however I get the same issue..   My iphone will not connect or see the devices.

**Comment by NorthernMan54** [comment]
Sometimes iCloud/HomeKit gets confused and you need to change/increment the username to get around these issues.  Stop homebridge, delete the persist and accessories directory, increment the username in config and start homebridge.

Then in the Home app delete your existing setup, delete the existing home and start again.

Have you ensured that your iCloud setup is the same on each iOS device?  And are using 2 factor authentication everywhere?  And followed the Apple troubleshooting steps?

**Comment by fireheadman** [comment]
I believe I have narrowed down the issue.
I will take the blame on most of it....   When I first stumbled upon homebridge-smartthings  (not the plain homebridge), I saw a nice write-up on installing it.  The deviation that I believe was causing my issues was installing the "Devices" app on iOS.   The author of that write-up was raving about how much easier it is to manage and group devices using this app, then only using the home app to view and interact.

After reading the responses in this thread along with a few others having similar issues, I noticed the "Devices" app was not being used, so I uninstalled it.   Also taking the advice to remove the /persist and /accesssories dirs along with incrementing the username in config.json, I was able to re-pair directly through the "Home" iOS app.   It does take a little bit longer to do the initial configuration of every device.    

Very happy it is working as designed.  Perhaps other having similar issues are using the "Devices" app??    Seems the man in the middle was not translating or communicating correctly.  Could be the "Devices" app used to work, but the recent iOS update broke some of the functionality?   

Wanted to say thanks to those in this thread that provided a guiding light!

**Comment by fireheadman** [comment]
Looks like the issue is back... after a month of running smoothly.   My iphone shows all devices "Not Responding"...  ipad show them running.

Doing a restore of persist and accessories dirs along with config.json doesn't help, so back to the drawing board.

I really like when this works... but man it is becoming a major drag to recreate frequently.

**Comment by myusernamehasalreadybeentaken** [comment]
Not pairing either

Lloyds-MacBook-Pro:.homebridge lloyd$ homebridge
[5/21/2017, 2:46:26 PM] Loaded plugin: homebridge-hs100
[5/21/2017, 2:46:26 PM] Registering platform 'homebridge-hs100.Hs100'
[5/21/2017, 2:46:26 PM] ---
[5/21/2017, 2:46:26 PM] Loaded config.json with 0 accessories and 1 platforms.
[5/21/2017, 2:46:26 PM] ---
[5/21/2017, 2:46:26 PM] Loading 1 platforms...
[5/21/2017, 2:46:26 PM] [TV] Initializing Hs100 platform...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-156 │     
    └────────────┘     
                       
[5/21/2017, 2:46:27 PM] Homebridge is running on port 51827.
[5/21/2017, 2:46:27 PM] [TV] New Plug Online: Smart Plug [800629A07324DFEBE2C1E7252B9A8DCD184E225E]
[5/21/2017, 2:46:27 PM] [TV] Configuring: Smart Plug
[5/21/2017, 2:46:57 PM] [TV] Online: Smart Plug [800629A07324DFEBE2C1E7252B9A8DCD184E225E]
[5/21/2017, 2:47:27 PM] [TV] Online: Smart Plug [800629A07324DFEBE2C1E7252B9A8DCD184E225E]

Iphone just spins on trying to pair.

Config.json is 

{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51827,
        "pin": "031-45-156"
    },


    "description": "My Bridge",

        "platforms": [
            {
                "platform" : "Hs100",
                "name" : "TV",
                "ip_address" : "192.168.1.224"

            }
        ]
}


Any ideas?

**Comment by GeorgeBgk** [comment]
Delete `persist` directory

**Comment by myusernamehasalreadybeentaken** [comment]
Cheers George, but I tried that one, tried changing the mac address, pin etc to no avail too. Sees it, just doesn't want to pair with it.

**Comment by robcar1** [comment]
I’m having exactly the same problem, also with hs100 plugs. Did you find a solution?
