### ISSUE TITLE
TypeError: this.log is not a function

### ISSUE THREAD

**Issue by sirdir1972** [nfarina/homebridge#1112]
After updating today, I had a crash of homebridge for the first time: 

Feb 03 18:54:14 cs homebridge[15360]: [2017-2-3 18:54:14] [HomeAssistant] Setting power state on the 'Wohnzimmer' to on
Feb 03 18:54:15 cs homebridge[15360]: [2017-2-3 18:54:15] [HomeAssistant] Successfully set power state on the 'Wohnzimmer' to on
Feb 03 18:54:15 cs homebridge[15360]: /usr/local/lib/node_modules/homebridge-homeassistant/accessories/light.js:139
Feb 03 18:54:15 cs homebridge[15360]:             this.log('Setting brightness on the \''+this.name+'\' to ' + level);
Feb 03 18:54:15 cs homebridge[15360]:                  ^
Feb 03 18:54:15 cs homebridge[15360]: TypeError: this.log is not a function
Feb 03 18:54:15 cs homebridge[15360]:     at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-homeassistant/accessories/light.js:139:18)
Feb 03 18:54:15 cs homebridge[15360]:     at ontimeout (timers.js:365:14)
Feb 03 18:54:15 cs homebridge[15360]:     at tryOnTimeout (timers.js:237:5)
Feb 03 18:54:15 cs homebridge[15360]:     at Timer.listOnTimeout (timers.js:207:5)
Feb 03 18:54:15 cs systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
Feb 03 18:54:15 cs systemd[1]: homebridge.service: Unit entered failed state.
Feb 03 18:54:15 cs systemd[1]: homebridge.service: Failed with result 'exit-code'.

**Comment by norman-thomas** [comment]
This seems to be an issue with the [`homebridge-homeassistant`](https://github.com/home-assistant/homebridge-homeassistant) plugin you're using. You should report it there.
