### ISSUE TITLE
REQUEST: Mi flora plant 

### ISSUE THREAD

**Issue by MrRobotoGit** [nfarina/homebridge#1113]
Any chances to have a plugin for the Mi flora plant sensor?

https://home-assistant.io/components/sensor.miflora/
https://www.npmjs.com/package/node-mi-flora

**Comment by Kolbi** [comment]
You may use FHEM (https://fhem.de/fhem.html) and then use homebridge-fhem in order to get Mi Flora Plant working in Homekit.

**Comment by MrRobotoGit** [comment]
Hi Kolbi, still waiting to get my mifloras from gearbest so not tested yet. i think i'm gonna use Domoticz end homebridge-domoticz for now. There are a lot of people there using miflora.

**Comment by Kolbi** [comment]
Sure like you want.

Just some FHEM links for MiFlora (most in German): https://fhem.de/commandref.html#XiaomiFlowerSens ; https://wiki.fhem.de/wiki/XiaomiFlowerSens ; https://forum.fhem.de/index.php/topic,60914.0.html

**Comment by MrRobotoGit** [comment]
Thank you, i will take a look at that!

**Comment by sorriso93** [comment]
any update on this? I browsed the links but no way to have a simple plugin in homebridge without adding other systems as domoticz or other...

**Comment by honkmaster** [comment]
Please check out [homebridge-mi-flower-care](https://github.com/honkmaster/homebridge-mi-flower-care).
