### ISSUE TITLE
Couldn't find config-punt.json

### ISSUE THREAD

**Issue by Mightyred81** [nfarina/homebridge#1115]
Loading 1 platforms...
[2/5/2017, 11:12:26 AM] [punt] Initializing punt platform...
Couldn't find a config-punt.json file at /home/pi/.homebridge/plugins/homebridge-punt.
pi@raspberrypi:~/.homebridge $ 

My config.json file

{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:36",
		"port": 51826,
		"pin": "031-45-154"
	},

	"description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",

	"accessories": [{
		"accessory": "WeMo",
		"name": "Bedroom Lamp"
	}],

	"platforms": [{
		"platform": "punt",
		"name": "punt"
	}]
}

My config-punt.json file

{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:36",
		"port": 51826,
		"pin": "031-45-154"
	},

	"description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",

	"accessories": [{
		"accessory": "WeMo",
		"name": "Bedroom Lamp"
	}],

	"platforms": [{
		"platform": "punt",
		"name": "punt"
	}]
}

Logging when starting homebridge

*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[2/5/2017, 11:12:12 AM] Loaded plugin: homebridge-philipshue
[2/5/2017, 11:12:12 AM] Registering platform 'homebridge-philipshue.PhilipsHue'
[2/5/2017, 11:12:12 AM] ---
[2/5/2017, 11:12:19 AM] Loaded plugin: homebridge-punt
homebridge API version: 2.1
[2/5/2017, 11:12:19 AM] Registering platform 'homebridge-punt.punt'
[2/5/2017, 11:12:19 AM] ---
[2/5/2017, 11:12:26 AM] Loaded plugin: homebridge-wemo
[2/5/2017, 11:12:26 AM] Registering accessory 'homebridge-wemo.WeMo'
[2/5/2017, 11:12:26 AM] ---
[2/5/2017, 11:12:26 AM] Loaded config.json with 1 accessories and 1 platforms.
[2/5/2017, 11:12:26 AM] ---
[2/5/2017, 11:12:26 AM] Loading 1 platforms...
[2/5/2017, 11:12:26 AM] [punt] Initializing punt platform...
Couldn't find a config-punt.json file at /home/pi/.homebridge/plugins/homebridge-punt.
pi@raspberrypi:~/.homebridge $ 

I really need help here, Im new to this and I can't get past this stage

**Comment by maplesteve** [comment]
As far I can see, your config-punt file is just a copy of the config.json. That's not the way to configure homebridge-punt. See https://github.com/cflurin/homebridge-punt for an example of config-punt.json.

**Comment by Mightyred81** [comment]
Ive now got this as my config-punt.json to take it back to basics:

"gateway": {
	"name": "fhem",
	"url": "127.0.0.1",
	"port": "8083",
	"auth": {"user": "foo", "password": "bar"},
	"run": false,
	"longpoll": true
},

Ive got this as my config.jason

{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},

	"platforms": [{
		"platform": "punt",
		"name": "punt"
	}],

	"accessories": [{
		"accessory": "WeMo",
		"name": "Bedroom Lamp"
	}]
}

But I still get the same error message

**Comment by Mightyred81** [comment]
I erased the SD Card and installed Raspbian Jessie and followed the script to a T and its now working. Thanks
