### ISSUE TITLE
Disk Space Issue

### ISSUE THREAD

**Issue by 1liminal1** [nfarina/homebridge#1117]
Hi guys, 

Not sure if I have underestimated what was needed, but my homebridge--vg-root folder is taking up 6gb. Can anyone advise how to either free up some space, or add more?

Thanks :)

**Comment by RXM307** [comment]
If its anything like mine and your running debug logs, try rotating your
homebridge.log & homebridge.err

**Comment by 1liminal1** [comment]
Thanks for that, but im not sure what you mean by rotating?

**Comment by RXM307** [comment]
logrotate https://linux.die.net/man/8/logrotate


eg. my /etc/logrotate.d/homebridge is as below

/var/log/homebridge.log {
  rotate 7
  daily
  compress
  missingok
  notifempty
  prerotate
    /usr/sbin/service homebridge stop > /dev/null
  endscript
}

/var/log/homebridge.err {
  rotate 7
  daily
  compress
  missingok
  notifempty
  postrotate
    /usr/sbin/service homebridge start > /dev/null
  endscript
}

**Comment by 1liminal1** [comment]
Thanks for that!

I have resized the partition, but its still saying its full, still trying to get to the bottom of it. Gparted says its been extended, the /dev/mapper/HomeBridge--vg-root is still saying 0 space. 

Anyway

Is there just a way to delete all the logs for now?

**Comment by RXM307** [comment]
Yeah you can just shutdown homebridge (typically service homebridge stop)
delete the log files and then start homebridge back up again (service
homebridge start).

although it sounds like you've extended the partition but you also need to
extend the LVM Volume

lvextend -l +100%FREE /dev/mapper/HomeBridge--vg-root
&
resize2fs /dev/mapper/HomeBridge--vg-root
(From Memory)

**Comment by 1liminal1** [comment]
I could kiss you... except that would be weird. 

Thank you so much, that worked, I now have homebridge back up and running after being down for a few days.

I'm a windows sys admin, so while I know, I have no idea when it comes to Linux lol

To clear out the logs, where are they? If I ls /var/log I dont see anything about the file HomeBridge.err you mentioned before?

Anyway, thanks again for that massive help.

**Comment by RXM307** [comment]
Your welcome,

If you take a look at your init script ie. /etc/init.d/homebridge

it may say something like

stdout_log="/var/log/$name.log"
stderr_log="/var/log/$name.err"

otherwise it may be in your home dir

**Comment by 1liminal1** [comment]
Thanks mate! Appreciate that

**Comment by bprigg** [comment]
What id is used to sign onto the VM console window.  My Homebridge which has run fine for about 2 years seems to have stopped and might be the Disk Full error referenced above.
