### ISSUE TITLE
Add Home Accessory missing after you remove it.

### ISSUE THREAD

**Issue by nzhome** [nfarina/homebridge#112]
After I added a home accessory, it was all good but I then realized that I had added it at the Home level, not at the room level.  so I removed it using Eve,  but now when I go to add the accessory back again to the Room, it is no longer available in the list to choose from :(

**Comment by nfarina** [comment]
Latest version of homebridge should not have this issue; you'll add the bridge itself then you are free to move accessories between rooms without deleting and re-adding.

**Comment by nzhome** [comment]
@nfarina yes I am using your new version ALWAYS. I would never log an issue unless I was using the latest. I also mentioned above that I have done 
rm -r homebridge, 
npm install homebridge

**Comment by nzhome** [comment]
@nfarina, thanks for updating the npm install homebridge..  thats much better now.
"nfarina published 15 hours ago"  new https://www.npmjs.com/package/homebridge  
the new version comes via npm install, thanks.   I will close the issue.
