### ISSUE TITLE
 Cannot read property 'indexOf' of undefined 

### ISSUE THREAD

**Issue by Downlosc** [nfarina/homebridge#1120]
Hi i get this error, i googled a bit but i cant get it working. 

this is the json

`{
"bridge":{
  "name": "Homebridge",
  "username":"CC:22:3D:E3:CE:30",
  "port":51826,
  "pin":"031-45-154"
},

"descriptions":"this is my Homebridge Config file",

"platforms":[
      {
          "platoform":"netatmo",
          "name":"netatmo weather",
          "ttl":5,
          "auth":{
          "client_id":"***********",
          "client_secret":"**********",
          "username":"**********",
          "password":"******"
       }
     }
   ]
}`

**Comment by maplesteve** [comment]
Can you post the full error message? This is a bit difficult with just the config.
