### ISSUE TITLE
User-defined callback or hook on state change

### ISSUE THREAD

**Issue by jdtsmith** [nfarina/homebridge#1121]
Does homebridge offer a facility for users to request a command line callback or hook for specific state changes of plugin characteristics?  I have homebridge running with homebridge-nest on a raspberry pi. In addition to the Nest, the RPi also controls a separate radiant heat thermostat via its GPIO pins. I'd like to run user configurable code whenever a given device's characteristic changes (here the `Away` Characteristic of a specific thermostat — I have 2).  I could scan the logs... but that's pretty fragile.

**Comment by snowdd1** [comment]
Not unless you use a kind of broker between homebridge and the devices. Plugins usually support only "their" hardware, and do not mix, say Nest and Webhooks or cmdline.  
That however might change with the next version of the API, where new plugin types might surface. See #1039.
