### ISSUE TITLE
Simple Motion sensor plugin?

### ISSUE THREAD

**Issue by StefanMeGit** [nfarina/homebridge#1122]
I just need a very simple MOTION SENSOR. Is there no one existing as plugin? Just want to check the motion by an GPIO.

Has anyone a hint?

**Comment by marcelkordek** [comment]
Hi, you can try this one -> https://github.com/lucavb/homebridge-hc-sr501

**Comment by StefanMeGit** [comment]
Ah thx! How can i install this? I have to copy this manually into the plugin dir?

**Comment by danielsen2009** [comment]
Are you using the GPIO on a pi, Arduino, esp?..

**Comment by marcelkordek** [comment]
If you installed homebridge globally you can install this plugin with: 
`sudo npm install -g https://github.com/lucavb/homebridge-hc-sr501`

After that you must add this to your homebridge config.json:
```
{
    "accessory" : "HC-SR501", // Required. Has to be "HC-SR501"
    "name" : "Motion Sensor", // Required. The name of this accessory. This will appear in your homekit app
    "pinId" : 24 // Required. The pin you connected the motion sensor to.
}
```
This may only work if you have a HC-SR501 Motion Sensor.

**Comment by StefanMeGit** [comment]
Ah thanks!! Works perfectly for what i need. I was not aware of this:

`sudo npm install -g https://github.com/lucavb/homebridge-hc-sr501`

**Comment by VincentvanDuijn** [comment]
it's not working for me :( maybe im doing something wrong, i have plugged it into pin 24. and tested it in python and it is working. im using a HC-SR501 (from Aliexpres) so maybe it is an fake HC-SR501?

**Comment by kiko26373** [comment]
it's not working for me either. It doesn't trigger the sensor

**Comment by kiko26373** [comment]
what identification should I use for the Pin? Physical, wPi or BCM?

**Comment by RealLittleSherman** [comment]
it's not working for me either. It doesn't trigger the sensor :( any workarround?
