### ISSUE TITLE
Error installing Homebridge

### ISSUE THREAD

**Issue by stevens-r** [nfarina/homebridge#1123]
if anyone knows what the problem here is help would be greatly appreciated i have included a copy of the terminal text and the log file

Robs-Mac-mini:~ Rob$ sudo npm -g install homebridge
Password:
/usr/local/bin/homebridge -> /usr/local/lib/node_modules/homebridge/bin/homebridge

> mdns@2.3.3 install /usr/local/lib/node_modules/homebridge/node_modules/mdns
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/Users/Rob/.node-gyp/6.9.5"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/homebridge/node_modules/mdns/.node-gyp"

Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.

Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.

gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 69
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.4.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/homebridge/node_modules/mdns
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
/usr/local/lib
└── (empty)

npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "-g" "install" "homebridge"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! mdns@2.3.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mdns@2.3.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mdns package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mdns
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mdns
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Rob/npm-debug.log
npm ERR! code 1
Robs-Mac-mini:~ Rob$ 

[npm-debug.log.txt](https://github.com/nfarina/homebridge/files/764843/npm-debug.log.txt)

**Comment by maplesteve** [comment]
Try to run `sudo xcodebuild -license` before that; scroll to the end of the license and enter 'agree'. I assume, that the compiler (which is part of Xcode) needs the license agreement to work.

**Comment by stevens-r** [comment]
i figured it out about 10 mins ago i just had to open xcode and click agree thanks for the help anyways

**Comment by stevens-r** [comment]
any idea how to get it to work with the config.json file works fine without it not with it

**Comment by maplesteve** [comment]
"What" exactly doesn't work? Are there any errors reported by homebridge?

**Comment by stevens-r** [comment]
without the config file i can turn my wemo switch on and off thats it siri doesn't work the instruction on how to make the file dont really tell you how to make it at all so maybe i did it wrong

{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },

    "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",

    "accessories": [
        {
            "accessory": "WeMo",
            "name": "Bedroom"
        }
    ],
    "platforms": [
      {
        "platform": "BelkinWeMo",
        "name": "WeMo Platform",
        "noMotionTimer": 60,
        "ignoredDevices": []
      }
  ]


}

**Comment by maplesteve** [comment]
O.k., so likely not a problem with homebridge itself, but with the plugin. Please ask the plugin developer for help with the config.

**Comment by stevens-r** [comment]
@maplesteve do you know of any articles i cloud read about creating and editing the config file if i get this working for the wemo switch i am going to be buying quite a few more devices switches, plugs, sensors, locks, ect.
