### ISSUE TITLE
Homebridge on Boot

### ISSUE THREAD

**Issue by bachoo786** [nfarina/homebridge#1124]
Hi 

I have installed Homebridge by the following commands: 

sudo npm install -g --unsafe-perm homebridge hap-nodejs node-gyp
cd /usr/local/lib/node_modules/homebridge/
sudo npm install --unsafe-perm bignum
cd /usr/local/lib/node_modules/hap-nodejs/node_modules/mdns
sudo node-gyp BUILDTYPE=Release rebuild

and I wanted Homebridge to start on boot on my raspberry pi.

Can someone please help me?

Thanks.

**Comment by NorthernMan54** [comment]
Start on boot instructions are part of the wiki, take a look at the section around using systemd for startup.  This is the recommended approach as it will restart after crashes.

https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi#running-homebridge-on-bootup-systemd
