### ISSUE TITLE
Samsung Air Conditioner

### ISSUE THREAD

**Issue by jetmcquack** [nfarina/homebridge#1128]
Can someone develop a Samsung air conditioner plugin? i have found that someone has started something in npm but it is not much more than a basic interface..
https://www.npmjs.com/package/node-samsung-airconditioner

i can test it for you if you would like to code it..

thanks in advance,

Francesco

**Comment by cicciovo** [comment]
I, have you resolve?

**Comment by jetmcquack** [comment]
Not at all, nobody seems interested in integrating this air conditioning!

**Comment by cicciovo** [comment]
I want try to develop a plugin, but for me it's the first time to use javascript, i develop in java. Do you run this script in your pc? is it work?

**Comment by brunofosi** [comment]
It would be great having a plugin for samsung smart ac!

**Comment by cicciovo** [comment]
Hi, i write the plugin! it's is not very beautiful code, but it's work! For now it's a beta version... this night i will try to pubblicate it

**Comment by HajLender** [comment]
Hello. Were you able to publish the code? 
Thank you

**Comment by cicciovo** [comment]
Sure. https://github.com/cicciovo/homebridge-samsung-airconditioner 
it's in work

**Comment by cicciovo** [comment]
Do you have try? Work for you?

Inviato da iPhone

Il giorno 31 gen 2018, alle ore 20:32, HajLender <notifications@github.com<mailto:notifications@github.com>> ha scritto:


Hello. Were you able to publish the code?
Thank you

**Comment by HajLender** [comment]
I am not able to make it work, but I have no programming skills at all. I don't know what is jq and curl and how to install it. I don't know where to get the aircon token neither. I know the aircon IP address only, but it is not enough :) 
Will it be able to control more than one aircon, because I have two of them

**Comment by pasqui7** [comment]
Ciao Ciccio! Ho provato ad applicare il tuo script. Hombridge mi permette di riconoscere i climatizzatori ma ci deve essere qualche errore nella compilazione. 

Puoi aiutarmi? 
Scrivimi su pasqui7@gmail.com
Grazie

**Comment by pasqui7** [comment]
Hi guys, I can confirm that this solution works fine ! A little bit  portion of code will be need modify to each user because the paths of file request is different based at the position of the same
Great! Thank you!
