### ISSUE TITLE
MotionSensor status not updating if Home app is in background

### ISSUE THREAD

**Issue by AlexLardschneider** [nfarina/homebridge#1130]
Hello,

I build a simple motion sensor plugin which subscribes to a MQTT topic to detect motion and update the motion status in Homebridge. So far I noticed the value only updates if I open the Home app and all other devices are fetched, and not if the app is in the background or idling. I enabled "Allow notifications" in the device settings, but the notification only triggers as soon as I open the home app. It also takes a really long time for the value to update if the app is open, but not fetching device status.

Maybe I misunderstood something, but isn't HomeKit/Homebridge supposed to almost instantly update the motion sensor status and notify me? So far no notifications have arrived yet if the app was closed.

The code I used:

```
var Service, Characteristic;
var mqtt = require('mqtt');

module.exports = function (homebridge) {
    Service = homebridge.hap.Service;
    Characteristic = homebridge.hap.Characteristic;
    homebridge.registerAccessory("homebridge-motionsensor", "MotionSensor", MotionSensorAccessory);
};

function MotionSensorAccessory(log, config) {
    var that = this;

    this.log = log;
    this.name = config["name"];
    this.url = config['url'];
    this.topic = config['topic'];
    this.client_Id = 'mqttjs_' + Math.random().toString(16).substr(2, 8);

    this.options = {
        keepalive: 10,
        clientId: this.client_Id,
        protocolId: 'MQTT',
        protocolVersion: 4,
        clean: true,
        reconnectPeriod: 1000,
        connectTimeout: 30 * 1000,
        will: {
            topic: 'WillMsg',
            payload: 'Connection Closed abnormally..!',
            qos: 0,
            retain: false
        },
        username: config["username"],
        password: config["password"],
        rejectUnauthorized: false
    };

    this.service = new Service.MotionSensor(this.name);

    this.client = mqtt.connect(this.url, this.options);
    this.client.subscribe(this.topic);

    this.client.on('message', function (topic, message) {
        that.log("Motion: " + message);

        var data = JSON.parse(message);
        if (data === null) {
            that.log("Invalid JSON: " + message);
            return null;
        }

        var newState = Boolean(data);

        that.service.getCharacteristic(Characteristic.MotionDetected)
            .setValue(newState);

    });

}

MotionSensorAccessory.prototype.getState = function (callback) {
    this.log(this.name, "getState()");
    callback(null, false);
};

MotionSensorAccessory.prototype.getServices = function () {
    return [this.service];
};
```

The line `that.log("Motion: " + message);` is called and I can see the message in the Homebridge log, which seems to suggest the staus gets updated correctly.

I am running the latest version of Homebridge (0.4.16) and iOS 10.3 Beta 1.

**Comment by NorthernMan54** [comment]
You are correct, it does update almost immediately even if the app is in the background.  I have 10.2.1 and it is okay.

Could it be an issue with the beta release?

**Comment by AlexLardschneider** [comment]
Hello @NorthernMan54,

I just updated to iOS 10.3 Beta 2 and the issue seems to be fixed. Thanks!
