### ISSUE TITLE
Homebridge doesn´t show up in Home app

### ISSUE THREAD

**Issue by PG000** [nfarina/homebridge#1132]
Homebridge shows up in bonjour brower but not in the home app. I have no plugins installed so that schouldn´t be the problem. I allready tried things like disabling ipv6 and changing the mac adress. Now I don´t know what eles to do.
Does somebody have an idea what to do ?

**Comment by lsj881224** [comment]
Hi,I have the same problem.do you solve this problem？Or do you have a solution?

**Comment by joshhighet** [comment]
(inside of home dir)

**Comment by lsj881224** [comment]
inside of homebirdge dir
accessories
persist
config.json
install.sh
