### ISSUE TITLE
Plugin that runs webpage

### ISSUE THREAD

**Issue by Zandor300** [nfarina/homebridge#1133]
Hello,

Is it possible to use homebridge to control my webbased lightswitch? It can by turned on by opening `IP/index.html?o0=1` in a webbrowser and turned off using `IP/index.html?o0=0`.

Thanks!

**Comment by jthurston** [comment]
There is a HTTP plugin found here...
https://github.com/rudders/homebridge-http

**Comment by snowdd1** [comment]
We really should have a link in the README, how to search for plugins on NPM.

**Comment by snowdd1** [comment]
Oh, there already is, only no one is reading it: https://github.com/nfarina/homebridge#installing-plugins

**Comment by hplato** [comment]
I've put one together for http control of lots of different objects (blind, light, switch, garage door, thermostat, fan) https://github.com/hplato/homebridge-httpmulti

**Comment by r4m235** [comment]
@snowdd1 not everyone
