### ISSUE TITLE
Manipulate with own requests

### ISSUE THREAD

**Issue by cheapjoe** [nfarina/homebridge#1134]
Hey,

maybe this is the wrong place to come up with this idea, but I hope it's ok.

I'm using homebridge since several weeks (especially with milight-bulbs) and I totally love it.
I recently bought an Amazon Dot speaker with Alexa. I had the Idea to connect my Milight Bulbs to Alexa by [IFTTT](https://ifttt.com/discover).
Is there a way I can "manipulate" the homebridge server from the outside? Like sending requests to the node-server?
Or even CLI commands would be great so I could write my own node-server to handle this. This interface should enable to call a specific device/platform set an action.

An alternative would be to use another node server than homebridge that provides connection functionality to milight bulbs. But why use another tool when I'm happy with this one?

Also a "get current information service" would be great, because homekit can't be routed (doesn't work if you access network by VPN). So I could write my own little "mini-Homekit/Homebridge-server" that solves this problem.

Thank you very much for your time :)

**Comment by AlexGustafsson** [comment]
This may be added in v1 of homebridge. There's an issue by the author that proposes a feature called "observable plugins" that don't host any accessories but relay information. I've tried to do what you speak of (great idea by the way 😉) but it's not possible right now with homebridge since it doesn't expose the needed interface.

**Comment by NorthernMan54** [comment]
Take a look at homebridge-alexa on github, I believe this may do what you are thinking about.
