### ISSUE TITLE
Homebridge inconsistency

### ISSUE THREAD

**Issue by rfiorentino1** [nfarina/homebridge#1135]
Hi all,

Wondering if someone here can help me. I've been using home bridge on Mac OS for about a month now, and am confused and a little frustrated by a few things.

Homebridge worked just fine for about a day after I first installed it. I had the harmony hub plugin and the ring doorbell plugin active and working. Then, home bridge decided to start crashing, presumably an issue with the harmony hub. I fixed this by making a launchd plist to keep home bridge running. Again,, everything was fine.

Then I saw the commit/issues about implementing the volume service into harmony. I tried to download the commit ad replace necessary files to get this to work, but I ended up messing up something and homebridge completely failed to start/work correctly. I replaced everything back to the original state, and by finally figuring out how to delete the accessory caches, I was back on track again.

Yesterday, I updated to Sierra, and now, everything is broken. Homebridge is telling me to pair with my IOS device even though it was already paired. I deleted the ring doorbell plugin because it was complaining that it wasn't configured but it still seems to want to look for it/load it. I repaired with home bridge, but harmony hub will not load, and home bridge throws some error about listening 6991 and won't finish starting. I can't reinstall home bridge or plugins because doing this seems to have no effect on anything. Is there something I'm missing? Documentation somewhere/faq/troubleshooting? Any suggestions would be greatly appreciated.

I absolutely love this concept and the underlying capabilities with this framework, and am willing to work with bugs, etc. but I need to get it working first. :) I'd also be willing to write documentation/troubleshooting guides if someone can give me some information to put in them.

Thanks so much,

Rocco

**Comment by brownad** [comment]
Harmony hub plugin causes quite a few issues, unfortunately it hasnt been updated at all to address them.  Compounded by Harmony's own updates to firmware this `unofficial` plugin will need more love to keep on top of the problems experienced.  I trashed it out, in favour of running via Alexa instead.  Needed a complete removal and node_modules too, it gets cached in lots of places.

**Comment by tokamac** [comment]
Hi Rocco @rfiorentino1 , 
Did you manage to resolve your homebridge issue? 
You said you own a Ring Doorbell. Did you install the camera-ffmpeg homebridge plugin and can you see the video stream from the doorbell cam in the Home app? If so, can you converse with people at your door from the Home app?

**Comment by rfiorentino1** [comment]
I did, after lengthy troubleshooting. I wasn’t aware that the camera plugin worked with Ring until you told me. I’ve searched for information on how to get it working with no luck. Have you had any success with it, and if so, can you explain what you did?

Sent from my iPhone

On Sep 7, 2017, at 2:57 AM, flux_capacitor <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Rocco @rfiorentino1<https://github.com/rfiorentino1> ,
Did you manage to resolve your homebridge issue?
You said you own a Ring Doorbell. Did you install the camera-ffmpeg homebridge plugin and can you see the video stream from the doorbell cam in the Home app? If so, can you converse with people at your door from the Home app?
