### ISSUE TITLE
How Do I Change Siri Voice Commands?

### ISSUE THREAD

**Issue by NDNELSON** [nfarina/homebridge#1137]
Hi fistly Great tutorial en thanks for all. I installed the bridge following the steps of the main tutorial, it works perfectly. In my iphone 6 i can detect the bridge via homekit, but I just only have one issue.

When I Use the spanish language siri works when I say "Encender luz de mi cuarto" but it doesn´t work when I say "Enciende la luz de mi cuarto" I know in spanish there are many differents way to turn on one light. How can I do it works with both commands above?, is there on some file in installation folder´s homebridge? Thanks for all

**Comment by snowdd1** [comment]
You just can't.  
Siri's Homekit actions are defined by Apple, and other languages than English suffer a bit, at least.
Sorry.
