### ISSUE TITLE
Motion Sensor does not push refresh by itself (only when i pull up the control center)

### ISSUE THREAD

**Issue by StefanMeGit** [nfarina/homebridge#1140]
Hi, 

i used a plugin from "homebridge-hc-sr501" and customiced it for me. 

I want to activate an motionSensor when a pin is detecting something and and deactivate when another pin detect something. Sounds very easy :)

I got now the main function, but i get the notification at least when i pull up (refresh) the Control center on my iPhone. I think i missed the function to pull the service by its own...

Can anyone help me there? 

Is it correct that the `	this.service.getCharacteristic(Characteristic.MotionDetected)
		.on('get', this.getState.bind(this));` should take care of this?

```
var Service;
var Characteristic;
var HomebridgeAPI;
var Gpio = require('onoff').Gpio;
var insideTriggered = false;
var outsideTriggered = false;

module.exports = function(homebridge) {
    Service = homebridge.hap.Service;
    Characteristic = homebridge.hap.Characteristic;
    HomebridgeAPI = homebridge;

    // console.log(Service.ContactSensor);
    homebridge.registerAccessory("homebridge-hc-sr501", "HC-SR501", SR501);
};

function SR501(log, config) {
	this.log = log;
	this.name = config.name;
	this.pinIdInside = config.pinIdInside;
	this.pinIdOutside = config.pinIdOutside;

	this.sensorInside = new Gpio(this.pinIdInside, 'in', 'both');
	this.sensorOutside = new Gpio(this.pinIdOutside, 'in', 'both');

	this.sensorInside.watch(function (err, value) {
		if (err) {
    		throw err;
  		}
  		console.log("SENSOR INSIDE -sensorInside.watch" + value);
		if (value == 1){
			insideTriggered = true;
			outsideTriggered = false;
			console.log("SENSOR INSIDE -insideTriggered: " + insideTriggered + " -outsideTriggered: " + outsideTriggered);
		}
	});
	this.sensorOutside.watch(function (err, value) {
		if (err) {
    		throw err;
  		}
  		console.log("SENSOR OUTSIDE -sensorOutside.watch" + value);
		if (value == 1){
			outsideTriggered = true;
			insideTriggered = false;
			console.log("SENSOR OUTSIDE -insideTriggered: " + insideTriggered + " -outsideTriggered: " + outsideTriggered);
		}
	});

	// info service
	this.informationService = new Service.AccessoryInformation();
	    
	this.informationService
	.setCharacteristic(Characteristic.Manufacturer, "PIR Manufacturer")
	.setCharacteristic(Characteristic.Model, config.model || "HC-SR501")
	.setCharacteristic(Characteristic.SerialNumber, config.serial || "4BD53931-D4A9-4850-8E7D-8A51A942FA29");


	this.service = new Service.MotionSensor(this.name);

	this.service.getCharacteristic(Characteristic.MotionDetected)
		.on('get', this.getState.bind(this));


	var that = this;
	
	if (insideTriggered == true) {
	that.service.setCharacteristic(Characteristic.MotionDetected, 1);
	insideTriggered = false;
	console.log("OUTSIDE TRIGGERED -Characteristic.MotionDetected 1");
	}

	if (outsideTriggered == true) {
	that.service.setCharacteristic(Characteristic.MotionDetected, 0);
	outsideTriggered = false;
	console.log("INSIDE TRIGGERED -Characteristic.MotionDetected 0");
	}


	process.on('SIGINT', function () {
		that.motionSensor.unexport();
	});
}

SR501.prototype.getState = function(callback) {
	var val = insideTriggered;
	console.log("MANUAL UPDATE -getState insideTriggered: " + insideTriggered);
	callback(null, val);
};

SR501.prototype.getServices = function() {
	console.log("??? getServices this.informationService " + this.informationService);
	console.log("??? getServices this.service " + this.service);
  return [this.informationService, this.service];
};
```

**Comment by snowdd1** [comment]
No, the `get` event happens when you refresh the data manually in a HomeKit app, or when you open such an app and it actively requests the data.  
For notifications to work you need to change the value in your watch function using the `characteristic.update()` function.

**Comment by StefanMeGit** [comment]
Thx! Is there any "Wiki" or documentation about all this stuff? Didnt found anything...

**Comment by snowdd1** [comment]
Well, problem with documentation is that it outdates so fast... most people here are eager building things, not writing docs so much. I tried to write some docs, but usually ran out of spare time, and months later it was outdated already.  
BUT. You can search the issues, also the closed ones if you remove the is:open in the search box. The topic has been discussed a dozen times at least.

**Comment by snowdd1** [comment]
And of course there are hundreds of homebridge-plugins on github which you can also look at!

**Comment by StefanMeGit** [comment]
OK... yes i searched a lot in other plugins ect. But it takes a while to understand all the stuff if u are not very familier with JS ect.

So i can do it like this at the bottome of the Script? Does the updateValue triggers by its own while the `that.service.setCharacteristic(Characteristic.MotionDetected, 1/0);` is changing?  Or i have to Call the function somehow u said in the "watch"?

```
SR501.prototype.updateValue = function(callback) {
	var value = insideTriggered;
	console.log("AUTOMATIC UPDATE -updateValue insideTriggered: " + value);
	callback(insideTriggered, null);
};
```

**Comment by snowdd1** [comment]
the latter.  
In your watch function you change your internal variable to the new state, you just have to inform homebridge that it has changed, by adding the **characteristic's** updateValue() function, not an updateValue function of your accessory.  

See my example:  
https://github.com/snowdd1/homebridge-cmd/blob/master/index.js#L87  
I get the characteristic from the service and change its value.


In your code something like that:  

Add a that variable:
```
        var that=this; // required as "this" in callbacks is bound to something strange.
```
```
	this.sensorInside.watch(function (err, value) {
		if (err) {
    		throw err;
  		}
  		console.log("SENSOR INSIDE -sensorInside.watch" + value);
		if (value == 1){
			insideTriggered = true;
			outsideTriggered = false;
			console.log("SENSOR INSIDE -insideTriggered: " + insideTriggered + " -outsideTriggered: " + outsideTriggered);
```
now add the line that changes the value in HomeKit:
```
			that.service.getCharacteristic(Characteristic.MotionDetected).updateValue(insideTriggered?1:0);                        
```
```
		}
	});
```

**Comment by snowdd1** [comment]
...and the same for the other event, too, of course.

**Comment by StefanMeGit** [comment]
Ahhhh! With an example on my script i think i got it now.  Thanks! I ll make some tryouts and try to learn more about this. Hard to understand the "first steps", but now i think i understand how it works.

**Comment by StefanMeGit** [comment]
Sorry i have one more question.

After edditing this:
```
	this.sensorInside.watch(function (err, value) {
		if (err) {
    		throw err;
  		}
  		console.log("SENSOR INSIDE -sensorInside.watch" + value);
		if (value == 1){
			insideTriggered = true;
			outsideTriggered = false;
			console.log("SENSOR INSIDE -insideTriggered: " + insideTriggered + " -outsideTriggered: " + outsideTriggered);
			that.service.getCharacteristic(Characteristic.MotionDetected).updateValue(1);
		}
	});
```
This is not nessecary... is this correct? Because the `Characteristic.MotionDetected` is allready set to 1.
```
	if (insideTriggered == true) {
	that.service.setCharacteristic(Characteristic.MotionDetected, 1);
	console.log("OUTSIDE TRIGGERED -Characteristic.MotionDetected 1");
	insideTriggered = false;
	}
```

**Comment by snowdd1** [comment]
Right. That part of the code was *dead* anyhow, because it was executed only once when creating the accessory, and not regularly at the events.  
By the way, what is this function you call upon SIGINT event? `that.motionSensor` seems not to be defined anywhere, so it will probably raise an exception when pressing ctrl-c.

**Comment by StefanMeGit** [comment]
Ah ok! 

Yes, was a wrong variable... should unexport like this:
```
	process.on('SIGINT', function () {
		that.pinIdInside.unexport();
		that.pinIdOutside.unexport();
	});
```
From the Gpio ONOFF-Plugin

```
unexport()

Reverse the effect of exporting the GPIO to userspace
```

Not shure what the SIGINT is. I just took it over from the **homebridge-hc-sr501**

**Comment by snowdd1** [comment]
https://en.wikipedia.org/wiki/Unix_signal#SIGINT

Usually ctrl-c in terminal.
