### ISSUE TITLE
creating com.homebridge.server.plist

### ISSUE THREAD

**Issue by natedlee** [nfarina/homebridge#1141]
I am completely failing at creating com.homebridge.server.plist to auto run Homebridge in the background. I'm reading this page https://github.com/nfarina/homebridge/wiki/Install-Homebridge-on-macOS. In ~/Library/LaunchAgents I entered:
> touch com.homebridge.server.plist
>vi com.homebridge.server.plist

and pasted in
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>Label</key>
    <string>com.homebridge.server</string>
    <key>ProgramArguments</key>
    <array>
        <string>/usr/local/bin/homebridge</string>
        <string>-I</string>
    </array>
    <key>StandardOutPath</key>
            <string>/path/to/logfile.log</string>
    <key>StandardErrorPath</key>
            <string>/path/to/logfile.log</string>
    <key>EnvironmentVariables</key>
    <dict>
            <key>PATH</key>
            <string>/usr/local/bin/:$PATH</string>
    </dict>
</dict>
</plist>
```
Am I supposed to change anything in this file?

**Comment by tannebil** [comment]
The paths to StandardOutPath and StandardErrorPath need to point to actual locations. For example, mine are:

    <key>StandardErrorPath</key>
		<string>/users/_userid_/Library/Logs/Homebridge/homebridge.err</string>
	<key>StandardOutPath</key>
		<string>/users/_userid_/Library/Logs/Homebridge/homebridge.out</string>

Where _userid_ is the account I'm using for Homebridge.

**Comment by natedlee** [comment]
@tannebil you are awesome. thanks! It's working now. I didn't think I **must** set that, but it makes sense now.
