### ISSUE TITLE
Homebridge Crashing

### ISSUE THREAD

**Issue by reallybman** [nfarina/homebridge#1142]
Hi all - please take a look below - trying to figure out why auto-restart is not happening:

pi@raspberrypi:~ $ systemctl status homebridge
● homebridge.service - Node.js HomeKit Server
   Loaded: loaded (/etc/systemd/system/homebridge.service; enabled)
   Active: activating (auto-restart) (Result: exit-code) since Wed 2017-02-15 19:50:40 EST; 4s ago
  Process: 1779 ExecStart=/usr/bin/homebridge $HOMEBRIDGE_OPTS (code=exited, status=1/FAILURE)
 Main PID: 1779 (code=exited, status=1/FAILURE)

**Comment by KhaosT** [comment]
Please post homebridge’s log by using journalctl: journalctl -f -u homebridge

Best Wishes,
Tian

**Comment by reallybman** [comment]
The response is "no journal files were found."

**Comment by NorthernMan54** [comment]
Pls add sudo to the front of the command

**Comment by snowdd1** [comment]
As it is a plugin that fails, I would recommend to raise te issue at the *homebridge-vera* repository.
