### ISSUE TITLE
iPad (also home hub) works but shows no response until tile touched, iPhone doesn't work at all

### ISSUE THREAD

**Issue by jdshkolnik** [nfarina/homebridge#1143]
Hi,

I have Homebridge running on a Mac desktop. I can control everything non-Homebridge-related on both devices without issue. When I open Home on my iPad, all tiles belonging to Homebridge show up as "No Response" but work correctly when I touch them. I guess this forces them to refresh or something. For example, a Nest Thermostat tile shows "No Response" but touching it quickly updates it to show "Heat to 74" and I'm able to change the temperature. My iPhone, on the other hand, shows the same "No Response" but nothing I do can get that to change. 

Both iPad Air 2 and iPhone 7 are on latest iOS, connected to same exact wifi network, have Home enabled, and are signed in to my iCloud account.

**Comment by Dirtrunner702** [comment]
Hello, I just wanted to point out that I had a similar problem with things not responding after some time. I was using an iPad as a homekit hub over wifi. Recently replaced my homekit hub with an Apple TV gen 4 hard wired to my LAN and no wifi, and the problems went away for good.

**Comment by jdshkolnik** [comment]
Hi,

I have two Apple TV gen 4's; one downstairs, one upstairs, both enabled as hubs.
