### ISSUE TITLE
Problem installing NPM (mac running Yosemite)

### ISSUE THREAD

**Issue by saint3** [nfarina/homebridge#115]
npm ERR! git rev-list -n1 legacy-updatevalue: fatal: ambiguous argument 'legacy-updatevalue': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 legacy-updatevalue: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 legacy-updatevalue: 'git [...] -- [...]'
npm ERR! git rev-list -n1 legacy-updatevalue: 
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm v2.11.3
npm ERR! code 128

npm ERR! Command failed: git rev-list -n1 legacy-updatevalue
npm ERR! fatal: ambiguous argument 'legacy-updatevalue': unknown revision or path not in the working tree.
npm ERR! Use '--' to separate paths from revisions, like this:
npm ERR! 'git [...] -- [...]'
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR! https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR! /usr/local/bin/homebridge/npm-debug.log

**Comment by nfarina** [comment]
Ah damn - forgot to update that dependency. Could you grab the latest from npm?

**Comment by saint3** [comment]
Hi Nick,

Thanks to be that fast !

 i have run npm v2.11.3 from an alias inside the Homebridge directory and i had that response :
> homebridge@0.0.0 start /usr/local/bin/homebridge
> DEBUG=* node app.js || true

module.js:338
    throw err;
          ^
Error: Cannot find module 'node-persist'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/bin/homebridge/app.js:3:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)


Thanks again !

Au plaisir !

Alain Lambert
Les Productions Saint
www.productionssaint.com
514 730-6080

**Comment by nfarina** [comment]
Hm if you installed via npm or used `npm install` then it should have created a directory `node_modules/node-persist`. Can you verify?

**Comment by saint3** [comment]
i have installed npm via node.js 12.7
and npm was installed at

   /usr/local/bin/npm


Here’s some sreeenshots




Au plaisir !

Alain Lambert
Les Productions Saint
www.productionssaint.com
514 730-6080

**Comment by nfarina** [comment]
I just verified that running `npm install homebridge` does properly install homebridge with `node-persist` and all other dependencies, and running it works OK. Could you try re-installing homebridge?

**Comment by saint3** [comment]
Thanks again for your help Nick!

I’ve remove all the old npm files and restart from scratch and it works. Now i’m at the config.json file state.
Here’s the hue lamp list on my hue bridge, How should i integrate them in the file. the ip address of the hue bridge is 10.0.1.4


{
	"12": {
		"state": {
			"on": false,
			"bri": 11,
			"hue": 12521,
			"sat": 225,
			"effect": "none",
			"xy": [
				0.5261,
				0.4132
			],
			"ct": 497,
			"alert": "none",
			"colormode": "hs",
			"reachable": true
		},
		"type": "Extended color light",
		"name": "Hue Spot 1",
		"modelid": "LCT003",
		"manufacturername": "Philips",
		"uniqueid": "00:17:88:01:00:d2:40:7d-0b",
		"swversion": "66010732",
		"pointsymbol": {
			"1": "none",
			"2": "none",
			"3": "none",
			"4": "none",
			"5": "none",
			"6": "none",
			"7": "none",
			"8": "none"
		}
	},
	"13": {
		"state": {
			"on": false,
			"bri": 195,
			"hue": 24612,
			"sat": 134,
			"effect": "none",
			"xy": [
				0.4009,
				0.4473
			],
			"ct": 278,
			"alert": "none",
			"colormode": "hs",
			"reachable": true
		},
		"type": "Extended color light",
		"name": "Hue Spot 2",
		"modelid": "LCT003",
		"manufacturername": "Philips",
		"uniqueid": "00:17:88:01:00:d2:32:aa-0b",
		"swversion": "66010732",
		"pointsymbol": {
			"1": "none",
			"2": "none",
			"3": "none",
			"4": "none",
			"5": "none",
			"6": "none",
			"7": "none",
			"8": "none"
		}
	},
	"14": {
		"state": {
			"on": false,
			"bri": 1,
			"hue": 12520,
			"sat": 225,
			"effect": "none",
			"xy": [
				0.5261,
				0.4132
			],
			"ct": 497,
			"alert": "none",
			"colormode": "hs",
			"reachable": true
		},
		"type": "Extended color light",
		"name": "Hue Spot 3",
		"modelid": "LCT003",
		"manufacturername": "Philips",
		"uniqueid": "00:17:88:01:00:d2:30:ba-0b",
		"swversion": "66010732",
		"pointsymbol": {
			"1": "none",
			"2": "none",
			"3": "none",
			"4": "none",
			"5": "none",
			"6": "none",
			"7": "none",
			"8": "none"
		}
	},
	"15": {
		"state": {
			"on": false,
			"bri": 254,
			"hue": 12521,
			"sat": 225,
			"effect": "none",
			"xy": [
				0.5261,
				0.4132
			],
			"ct": 497,
			"alert": "none",
			"colormode": "hs",
			"reachable": true
		},
		"type": "Extended color light",
		"name": "Hue Spot 4",
		"modelid": "LCT003",
		"manufacturername": "Philips",
		"uniqueid": "00:17:88:01:00:d4:30:8b-0b",
		"swversion": "66010732",
		"pointsymbol": {
			"1": "none",
			"2": "none",
			"3": "none",
			"4": "none",
			"5": "none",
			"6": "none",
			"7": "none",
			"8": "none"
		}
	},
	"16": {
		"state": {
			"on": false,
			"bri": 23,
			"hue": 43459,
			"sat": 254,
			"effect": "none",
			"xy": [
				0.1435,
				0.1392
			],
			"alert": "none",
			"colormode": "hs",
			"reachable": true
		},
		"type": "Color light",
		"name": "LightStrips 1",
		"modelid": "LST001",
		"manufacturername": "Philips",
		"uniqueid": "00:17:88:01:00:cc:1c:66-0b",
		"swversion": "66013452",
		"pointsymbol": {
			"1": "none",
			"2": "none",
			"3": "none",
			"4": "none",
			"5": "none",
			"6": "none",
			"7": "none",
			"8": "none"
		}
	},
	"17": {
		"state": {
			"on": false,
			"bri": 127,
			"hue": 49515,
			"sat": 170,
			"effect": "none",
			"xy": [
				0.282,
				0.176
			],
			"ct": 153,
			"alert": "none",
			"colormode": "hs",
			"reachable": true
		},
		"type": "Extended color light",
		"name": "Hue Lamp 1",
		"modelid": "LCT001",
		"manufacturername": "Philips",
		"uniqueid": "00:17:88:01:00:d8:ba:30-0b",
		"swversion": "66013452",
		"pointsymbol": {
			"1": "none",
			"2": "none",
			"3": "none",
			"4": "none",
			"5": "none",
			"6": "none",
			"7": "none",
			"8": "none"
		}
	},
	"18": {
		"state": {
			"on": false,
			"bri": 84,
			"hue": 33946,
			"sat": 5,
			"effect": "none",
			"xy": [
				0.3791,
				0.3759
			],
			"ct": 248,
			"alert": "none",
			"colormode": "ct",
			"reachable": true
		},
		"type": "Extended color light",
		"name": "Hue Lamp 2",
		"modelid": "LCT001",
		"manufacturername": "Philips",
		"uniqueid": "00:17:88:01:00:dd:d8:ac-0b",
		"swversion": "66013187",
		"pointsymbol": {
			"1": "none",
			"2": "none",
			"3": "none",
			"4": "none",
			"5": "none",
			"6": "none",
			"7": "none",
			"8": "none"
		}
	},
	"19": {
		"state": {
			"on": false,
			"bri": 1,
			"hue": 47095,
			"sat": 254,
			"effect": "none",
			"xy": [
				0.1671,
				0.0402
			],
			"ct": 500,
			"alert": "none",
			"colormode": "hs",
			"reachable": true
		},
		"type": "Extended color light",
		"name": "Hue Lamp 3",
		"modelid": "LCT001",
		"manufacturername": "Philips",
		"uniqueid": "00:17:88:01:00:dd:c8:a2-0b",
		"swversion": "66013187",
		"pointsymbol": {
			"1": "none",
			"2": "none",
			"3": "none",
			"4": "none",
			"5": "none",
			"6": "none",
			"7": "none",
			"8": "none"
		}
	},
	"20": {
		"state": {
			"on": false,
			"bri": 2,
			"hue": 47095,
			"sat": 254,
			"effect": "none",
			"xy": [
				0.1671,
				0.0402
			],
			"ct": 500,
			"alert": "none",
			"colormode": "hs",
			"reachable": true
		},
		"type": "Extended color light",
		"name": "Hue Lamp 4",
		"modelid": "LCT001",
		"manufacturername": "Philips",
		"uniqueid": "00:17:88:01:00:dd:c9:be-0b",
		"swversion": "66013187",
		"pointsymbol": {
			"1": "none",
			"2": "none",
			"3": "none",
			"4": "none",
			"5": "none",
			"6": "none",
			"7": "none",
			"8": "none"
		}
	},
	"21": {
		"state": {
			"on": false,
			"bri": 7,
			"hue": 44963,
			"sat": 254,
			"effect": "none",
			"xy": [
				0.191,
				0.0876
			],
			"ct": 500,
			"alert": "none",
			"colormode": "hs",
			"reachable": true
		},
		"type": "Extended color light",
		"name": "Hue Lamp 5",
		"modelid": "LCT001",
		"manufacturername": "Philips",
		"uniqueid": "00:17:88:01:00:fb:15:4b-0b",
		"swversion": "66013452",
		"pointsymbol": {
			"1": "none",
			"2": "none",
			"3": "none",
			"4": "none",
			"5": "none",
			"6": "none",
			"7": "none",
			"8": "none"
		}
	}
}
Au plaisir !

Alain Lambert
Les Productions Saint
www.productionssaint.com
514 730-6080

**Comment by nfarina** [comment]
Have a look at the comments at the top of the Hue platform JS: https://github.com/nfarina/homebridge/blob/master/platforms/PhilipsHue.js

**Comment by saint3** [comment]
Hi Nick,

Everything is working fine ! Thanks a lot for your generous help.

Have a nice sunday !


Au plaisir !

Alain Lambert
Les Productions Saint
www.productionssaint.com
514 730-6080

**Comment by nfarina** [comment]
Great to hear!
