### ISSUE TITLE
Homebridge starts automatically, but HomeKit can't see it. I have to killall home bridge & restart

### ISSUE THREAD

**Issue by dkrayberg** [nfarina/homebridge#1150]
Homebridge starts automatically, but HomeKit can't see it. I have to killall homebridge & restart.

Can anyone comment? I've gone the plist route, which was way too complicated for a simple add something to your System Preferences, Users & Groups, me, Login Items, +.

It starts automatically, I can see the terminal session running when I logon, but HomeKit doesn't see it.

Thoughts?

**Comment by jdshkolnik** [comment]
I'm having the same issue but rebooting doesn't seem to change anything. It was working when I first set it up but now it isn't.

**Comment by bachoo786** [comment]
Same here
