### ISSUE TITLE
Fails on startup - claims to "cannot add a bridged accessory with the same UUID..."

### ISSUE THREAD

**Issue by AmitMY** [nfarina/homebridge#1151]
I have an embedded "smart home" system, which I am trying to add Apple Homekit support to.
I register a platform, and on my init event fetch all of the devices from the system's server, and try to register them as accessories.

On startup, it calls `configureAccessory` and sends to identical accessories, then continues no further, and crashes:
>Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 79ca3fdc-7d11-4e22-b63a-daa6c08e31c1

Here is my `configureAccessory`:
```
configureAccessory(accessory) {
    this.log("configureAccessory Init");
}
```

So I am stuck with no ability to do anything. Help?

**Comment by snowdd1** [comment]
you're sure that's in that function? I would assume it's in registerPlatformAccessories() and you give no distinct UUIDs.

**Comment by snowdd1** [comment]
or you try to add the same accessories again, next time at start? homebridge caches them for you, you have to connect your implementation to the cached accessories during `configureAccessory()`

**Comment by AmitMY** [comment]
@snowdd1 Thank you, however, that is not the case.
I realised that homebridge caches the accessories (which is great), but for some reason, after I did `register` a couple of times, now, without any register, just console logs, it crashes on startup

**Comment by andyrooo82** [comment]
I had a similar issue using the harmony hub plugin even though I haven't renamed anything. I deleted the accessories directory (which then got automatically recreated) and it worked fine after that.

**Comment by AmitMY** [comment]
@andyrooo82 Thanks, that fixed the issue.

**Comment by AmitMY** [comment]
@snowdd1 Just to close this thing properly with good news - I started with registering just 80 devices, and it works perfectly (a little delay, but I'll sort that out). Thanks!

**Comment by snowdd1** [comment]
Looks like it somehow can happen to register a duplicate UUID which then gets cached. Have to admit I never had something like that, but it might be worth @khaost takes a look into that.
