### ISSUE TITLE
WindowCovering does not use PositionState

### ISSUE THREAD

**Issue by AmitMY** [nfarina/homebridge#1153]
I am using a `WindowCovering` service, that knows how to change state, and get the current state.
When I press `open`, it opens the blinds, but forever says `Opening....` (until I refresh the app, then it says "open")

I realised I need to use a `PositionState` charecteristic, so I added this:
```
this.blindsService
    .getCharacteristic(globals.Characteristic.PositionState)
    .on("get", this.getPositionState.bind(this));
```

And this:
```
getPositionState(callback) {
    let state = Config.currentStates[this.cardId];
    let lstState = Config.lastStates[this.cardId];

    console.log("getPositionState");

    if (state !== undefined && lstState !== undefined) {
        console.log(state, lstState);
        let char = (state > lstState) ? globals.Characteristic.PositionState.INCREASING :
            (state < lstState) ? globals.Characteristic.PositionState.DECREASING :
                globals.Characteristic.PositionState.STOPPED;
        console.log(char);
        callback(null, char);
    } else
        callback("No state found", null)
}
```

It doesn't work, and no log is shown on `console`.

I verified, that if I add a `console.log` to my `setState` function, it does print it when trying to set a state.

What am I doing wrong?

**Comment by snowdd1** [comment]
Apple's Home app compares TargetPosition and CurrentPosition to derive the PositionState instead of using the separated characteristic. 
So make sure that on end of the motion the both values are equal.

**Comment by m8335la** [comment]
Hi,

@AmitMY, I'm experiencing the same issue. Did you find a solution?

@snowdd1, in which interval are the values checked by homebridge? Or do I have to notify about the end of the movement?

**Comment by AmitMY** [comment]
I only had:
```js
service.getCharacteristic(globals.Characteristic.CurrentPosition)
      .on("get", this.getState.bind(this));

service.getCharacteristic(globals.Characteristic.TargetPosition)
      .on("set", this.setState.bind(this));
```

And I should have also added a get to the targetposition:
```js
service.getCharacteristic(globals.Characteristic.CurrentPosition)
      .on("get", this.getState.bind(this));

service.getCharacteristic(globals.Characteristic.TargetPosition)
      .on("get", this.getTargetState.bind(this))
      .on("set", this.setState.bind(this));
```

which I first initialize as the current position, and when I call "setState" I save the value for target. Furthermore, every 10 seconds I update the target position to be the current blinds value. (so it works if I change them out of the app, with a switch)
