### ISSUE TITLE
Too many devices make homebridge "unavailable"

### ISSUE THREAD

**Issue by AmitMY** [nfarina/homebridge#1155]
If I add around 100 devices, homebridge still pairs. However, if I add all of my devices (125), homebridge suddenly becomes unavailable on my device.

If I then un-pair homebridge, it doesn't show on the addable accessories.
So I remove `persist`, and try again. Now it does show on the accessories list, but when trying to add (after passcode) it loads then says:
> Couldn't add Homebridge. 
Home couldn't connect to this accessory.
>
>Dismiss (button)

Is there a device limit for Homebridge?
Is it my device? I am running on an RPi 3, but it seems to go string and not crash at all, even with all of those devices.
![image](https://cloud.githubusercontent.com/assets/5757359/23209650/c6f34076-f902-11e6-96e3-304db2bbad39.png)

**Comment by snowdd1** [comment]
Search the closed issues for "100".  
There is a fixed limit of 99 accessories per bridge (Apple). You can aggregate more services into one accessory to put all functionality into one bridge.

**Comment by AmitMY** [comment]
@snowdd1 Thanks!
So I will try running 2 bridges on the device, hopefully that won't be a catastrophy
