### ISSUE TITLE
accessories not responding on iPhone, but fine on iPad

### ISSUE THREAD

**Issue by JangoBritt** [nfarina/homebridge#1157]
Hi all,

So here's an odd thing: I have my iPad mini set up as my home hub, and all the homebridge accessories are showing up just fine there.

on my iPhone, they're showing as No Response (native homekit devices are showing just fine)

Is there a way I can re-sync the settings from the iPad? Any way to remove my iphone from the persist folder, without removing the iPad?

I tried disabling the Home option from the iCloud settings on the iphone, but when I re-enabled it, everything came back as No Response again.

I'd like to avoid having to remove and re-add the homebridge from my iphone, and re-allocate all the rooms, re-create all the scenes and automation, as I've done many many times over so far :-(

**Comment by JangoBritt** [comment]
Looking inside the persist\Accessoryinfo.xxx.json, I see two entries under pairedClients, but no indication of a friendly name for either.

Oddly, one has dashes, the other does not

**Comment by Downlosc** [comment]
Same problem here. Second time it happens, it would be such a pity to delete it and re-pair it.

**Comment by bachoo786** [comment]
@Downlosc  what do you mean by delete it? how do you do that?

**Comment by JangoBritt** [comment]
@bachoo786 remove the homebridge accessory, and then re-add it... it's what we're trying to avoid doing here.

**Comment by Downlosc** [comment]
Any news? I still have the same issue.. holy cow

**Comment by Downlosc** [comment]
Maybe i'll try to do this. 
iOS device has gotten your Homebridge username (looks like a MAC address) "stuck" somehow, where it's in the database but inactive. Fix: change your username in the "bridge" section of config.json to be some new value.

**Comment by JangoBritt** [comment]
I have a feeling this happens every time I accidentally load the home app, or home control centre when I'm outside the LAN, because it's only happening on the iPhone, and not the iPad which is my HomeKit hub.

Once the HomeKit loses the HomeBridge, it never regains that pairing. I can remove and re-add the accessory just fine though

Is it possible that the HomeBridge is not playing nicely with iCloud?
