### ISSUE TITLE
Not picking up all lights - LIFX

### ISSUE THREAD

**Issue by joshhighet** [nfarina/homebridge#1159]
probrally a simple one, but my homebridge set often misses a single light. It is not that the light is disconnected as I can still control it through the LIFX app, but it will only discover 3/4 sometimes less. It alternates as to which one it won't recignise - and this isn't all the time. Sorry if this is a duplicate of another issue.

**Comment by Bluebie** [comment]
this issue is with whichever lifx plugin you're using, not the core homekit platform. and, i agree. the lifx plugins suck. been meaning to try and build one that works well.

**Comment by AppleTechy** [comment]
Please create an issue on the plugin's github page not the main homebridge page
