### ISSUE TITLE
Command, directory, file, anything homebridge isn't found. Cannot install.

### ISSUE THREAD

**Issue by sjbradley98** [nfarina/homebridge#1163]
I have followed the tutorial for installing on raspberry pi, and I'm confident node is installed because I can visit /usr/lib/node_modules, and list some 'nodes?'.

I have used sudo npm install -g homebridge, as well as using the --unsafe-perm flag. Both methods execute properly, and it looks to me as if it has worked with no errors. The output looks like this.

/opt/node/bin/homebridge -> /opt/node/lib/node_modules/homebridge/bin/homebridge
/opt/node/lib
└── homebridge@0.4.16  

So now the tutorial suggests I could run home bridge by simply typing 'homebridge', but command is not found. In addition /home/pi/homebridge file or directory is not found either. Can anybody please tell me what I'm missing, I've been trying for hours :)

**Comment by Harry-Harrison** [comment]
I've also having this with my new Raspberry Pi Zero W running Node 7.7.1

**Comment by tommyd75** [comment]
I'm also having the same exact issue with my Pi Zero W.

**Comment by JMCAcademy** [comment]
did anyone solve this? same issue

**Comment by tommyd75** [comment]
Bump, 😬
Did anyone get this working with the newer Pi Zero W

**Comment by KhaosT** [comment]
Depends on how you installed npm, I guess it didn't set the $PATH env correctly.

**Comment by gursharan29** [comment]
/opt/node/lib
└── homebridge@0.4.16
Same issue... running on Pi Zero.

pi@raspberrypi:~ $ homebridge
-bash: homebridge: command not found

**Comment by NorthernMan54** [comment]
Looking back at the history, it appears to be here

/opt/node/lib/node_modules/homebridge/bin/homebridge

**Comment by dgaust** [comment]
I used these instructions to install node on my Pi Zero Wireless. https://blog.miniarray.com/installing-node-js-on-a-raspberry-pi-zero-21a1522db2bb

Just needed to change the version of node to 4.3.2 (replace 4.2.4 wherever appearing). Then went through the normal setup process and homebridge is up and running.
