### ISSUE TITLE
Hombridge accessories without bridges

### ISSUE THREAD

**Issue by daniel4099** [nfarina/homebridge#1164]
Hi 

I have a few questions about using homebridge

How to use homebridge for controlling wifi light bulb if I don't have bridge for example Lightify Osram, Philips hue or Xiaomi. 

What's is the cheapest way to use homebridge lights ? What kind of stuff buy ?

How to use temperature and motion sensor for example xiaomi without bridge, or belkin ?

What kind of sensor buy ?

**Comment by toshibochan** [comment]
You can't control just hue bulb without hue bridge

**Comment by daniel4099** [comment]
It's for all bulbs, Even without bridge ? How about the xiaomi temperatur and motion sensors ?

**Comment by toshibochan** [comment]
If xiaomi use bridge to control the devices probably need the bridge to. The homebridge is just for connect HomeKit to other bridges

**Comment by daniel4099** [comment]
What kind of bulbs, and motion sensors will be the cheapest options supported by homebridge ?

**Comment by lagunacomputer** [comment]
iDevices Switch works without bridge
