### ISSUE TITLE
Actively using HomeBridge? I would love your input!

### ISSUE THREAD

**Issue by Dirtrunner702** [nfarina/homebridge#1165]
Hello, 

I am currently running Lowes Iris home automation and am planning to get rid of it. 
I have a working version of Homebridge up and running. 

I am planning to purchase a Nest thermostat and Chamberlain garage door opener since there are HomeBridge plugins available. 

I really would like to not go back to depending on another hub to interface with HomeBridge. I would prefer to piece meal it if I can but I am not sure that It makes sense. 

My question is, what hubs are you all using to interface with HomeBridge that you are happy with? e.g. SmartThings and the like. I would like to get door sensors, glass break sensors and door locks and an alarm but would like input on what you all have as set ups before making any purchases. 

Thank you all!

**Comment by ericgingras** [comment]
RPi 3 with Home Assistant and a Aeotec Z-wave USB stick. I didn't want to use ST because I don't want to have to depend on their cloud for all of my sensors to work.

**Comment by Dirtrunner702** [comment]
Excellent! I too do not want to rely solely on a cloud based system any longer. Thanks for your input.
