### ISSUE TITLE
PLEASE HELP

### ISSUE THREAD

**Issue by bachoo786** [nfarina/homebridge#1167]
Hi can someone please help me?

I couldn't find my homebridget in my home kit app so I deleted the persist folder and I still have the same problem. 

So I ran homebridge manually by typing “homebridge” on my terminal of my raspberry pi and I get the following errors:

Error: EACCES: permission denied, open '/home/pi/.homebridge/persist/AccessoryInfo.AA223DE3CE30.json'
at Error (native)
at Object.fs.openSync (fs.js:640:18)
at Object.fs.writeFileSync (fs.js:1333:33)
at Object.persistKeySync (/usr/lib/node_modules/homebridge/node_modules/node-persist/local-storage.js:457:12)
at Object.setItemSync (/usr/lib/node_modules/homebridge/node_modules/node-persist/local-storage.js:275:14)
at Object.nodePersist.setItemSync (/usr/lib/node_modules/homebridge/node_modules/node-persist/node-persist.js:99:29)
at AccessoryInfo.save (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/model/AccessoryInfo.js:161:11)
at Bridge.Accessory.publish (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:439:23)
at Server._publish (/usr/lib/node_modules/homebridge/lib/server.js:114:16)
at Server. (/usr/lib/node_modules/homebridge/lib/server.js:372:14)

Also if I type “sudo homebridge” I get the following errors:

[2/23/2017, 7:15:49 PM] config.json (/root/.homebridge/config.json) not found.
Load homebridge-mqtt.mqtt
[2/23/2017, 7:15:49 PM] [homebridge-mqtt.mqtt] config undefined or null!
[2/23/2017, 7:15:49 PM] [homebridge-mqtt.mqtt] storagePath = /root/.homebridge

Mind you I have setup Homebridge to run on boot without any issues and when I check the log by "sudo journalctl -u homebridge” I get no errors. 

And when I check the status by "systemctl status homebridge” I get the following with no errors:

● homebridge.service - Node.js HomeKit Server
Loaded: loaded (/etc/systemd/system/homebridge.service; enabled)
Active: active (running) since Thu 2017-02-23 18:53:38 GMT; 23min ago
Main PID: 505 (homebridge)
CGroup: /system.slice/homebridge.service
└─505 homebridge

Can someone please help me?

Thanks.

**Comment by inzlabs** [comment]
Hey, not an expert here, but I believe this happened to me before. The issue is that the config.json is in your user/.hombridge folder but not in the root/.homebridge folder. I think if you clear that up, and the issues persist maybe someone can catch what's the problem.

**Comment by bachoo786** [comment]
so what is this user/.homebridge folder? is it home/pi/.homebridge?

**Comment by cflurin** [comment]
Try:
1) delete the content of `.homebridge/persist/`
2) delete the content of `.homebridge/accessories`
3) start homebridge:
```sh
$ homebridge
````
If it doesn't work, post log and your `config.json`
note: `.homebridge` on a RPi should be in the folder `home/pi/`

**Comment by bachoo786** [comment]
I done what you asked me to do and I get the following errors:

`Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
2/27/2017, 5:50:45 PM >                        
2/27/2017, 5:50:45 PM >     ┌────────────┐     
2/27/2017, 5:50:45 PM >     │ 222-33-444 │     
2/27/2017, 5:50:45 PM >     └────────────┘     
2/27/2017, 5:50:45 PM >                        
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EACCES: permission denied, open '/home/pi/.homebridge/persist/AccessoryInfo.CC223DE3CE30.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.writeFileSync (fs.js:1333:33)
    at Object.persistKeySync (/usr/lib/node_modules/homebridge/node_modules/node-persist/local-storage.js:457:12)
    at Object.setItemSync (/usr/lib/node_modules/homebridge/node_modules/node-persist/local-storage.js:275:14)
    at Object.nodePersist.setItemSync (/usr/lib/node_modules/homebridge/node_modules/node-persist/node-persist.js:99:29)
    at AccessoryInfo.save (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/model/AccessoryInfo.js:161:11)
    at Bridge.Accessory.publish (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:439:23)
    at Server._publish (/usr/lib/node_modules/homebridge/lib/server.js:114:16)
    at Server.<anonymous> (/usr/lib/node_modules/homebridge/lib/server.js:372:14)`

my config.json is:

`{
        "bridge": {
                "name": "Homebridge",
                "username": "CC:22:3D:E3:CE:30",
                "port": 51811,
                "pin": "222-33-444"
        },
        "platforms": [{
                        "platform": "mqtt",
                        "name": "mqtt",
                        "url": "http://XXXX",
                        "topic_prefix": "mydevices/irtransmitter",
                        "username": “XXXX",
                        "password": “XXXX"
                }, {
                        "platform": "HomeAssistant",
                        "name": "HomeAssistant",
                        "host": "http://XXXX",
                        "password": “XXXX",
                        "supported_types": ["light", "switch", "scene"]
                }

        ]
}
`

**Comment by cflurin** [comment]
check the permission:
```sh
cd /home/pi/.homebridge
ls -l
```
you should get something like:
```sh
drwxr-sr-x 3 pi pi 4096 Feb 21 20:50 accessories
-rw-r--r-- 1 pi pi  297 Feb 21 20:54 config.json
drwxr-sr-x 3 pi pi 4096 Feb 21 20:54 persist
```

**Comment by bachoo786** [comment]
I done a sudo killall homebridge and then ran homebridge it worked i rebooted the pi and I have setup homebridge to run on boot I get the message that its running fine (see below) but on my iphone the homebridge accessory says its not responding, when I run it manually again on terminal it works fine.

● homebridge.service - Node.js HomeKit Server
   Loaded: loaded (/etc/systemd/system/homebridge.service; enabled)
   Active: active (running) since Mon 2017-02-27 18:10:34 GMT; 46s ago
 Main PID: 1226 (homebridge)
   CGroup: /system.slice/homebridge.service
           └─1226 homebridge

**Comment by bachoo786** [comment]
with regards to the permission, I get:

total 68
drwxr-xr-x 2 pi   pi    4096 Feb 27 18:06 accessories
-rw-r--r-- 1 root root   502 Feb 25 16:38 config.json
-rw------- 1 pi   pi   10348 Feb 27 18:02 nohup.out
-rw-r--r-- 1 pi   pi    3085 Feb 25 16:38 npm-debug.log.1043298792
-rw-r--r-- 1 pi   pi    3083 Feb 25 16:40 npm-debug.log.1068464915
-rw-r--r-- 1 pi   pi    3166 Feb 27 18:02 npm-debug.log.1237251798
-rw-r--r-- 1 pi   pi    3164 Feb 27 17:55 npm-debug.log.2100934864
-rw-r--r-- 1 pi   pi    3164 Feb 27 17:16 npm-debug.log.2184727736
-rw-r--r-- 1 pi   pi    3083 Feb 23 19:06 npm-debug.log.239552560
-rw-r--r-- 1 pi   pi    3619 Feb 23 19:02 npm-debug.log.2616976422
-rw-r--r-- 1 root root  3075 Feb 25 16:39 npm-debug.log.3941375272
-rw-r--r-- 1 pi   pi       0 Feb 23 19:11 npm-debug.log.4050418629
-rw-r--r-- 1 pi   pi    3166 Feb 27 18:01 npm-debug.log.4182372596
-rw-r--r-- 1 pi   pi    3164 Feb 27 18:00 npm-debug.log.795953643
-rw-r--r-- 1 root root  3615 Feb 25 16:38 npm-debug.log.820015163
drwxr-xr-x 2 pi   pi    4096 Feb 27 17:59 persist

**Comment by cflurin** [comment]
the config.json owner should  be `pi`
use chmod to set it or make a copy  and delete the old one. Do not use `sudo`

you might delete all *.log files

**Comment by cflurin** [comment]
... i use init.d on my RPi
https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi#running-homebridge-on-bootup-initd

**Comment by bachoo786** [comment]
do I have to use this command to make the config.json owner pi:
sudo chmod -R 0777 /var/homebridge

**Comment by cflurin** [comment]
I usually make a copy:
```sh
cp config.json config.tmp
rm config.json
mv config.tmp config.json
ls -l
```

**Comment by bachoo786** [comment]
when I try: chmod -R 0777 config.json

it gives me:
chmod: changing permissions of ‘config.json’: Operation not permitted

**Comment by cflurin** [comment]
try the copy method above

**Comment by cflurin** [comment]
...  this should also work:
```sh
sudo chown pi:pi config.json
```

**Comment by bachoo786** [comment]
that worked thanks alot.

pi@raspberrypi:~/.homebridge $ sudo chown pi:pi config.json
pi@raspberrypi:~/.homebridge $ ls -l
total 68
drwxr-xr-x 2 pi   pi    4096 Feb 27 18:06 accessories
-rw-r--r-- 1 pi   pi     502 Feb 27 18:21 config.json
-rw------- 1 pi   pi   10348 Feb 27 18:02 nohup.out
-rw-r--r-- 1 pi   pi    3085 Feb 25 16:38 npm-debug.log.1043298792
-rw-r--r-- 1 pi   pi    3083 Feb 25 16:40 npm-debug.log.1068464915
-rw-r--r-- 1 pi   pi    3166 Feb 27 18:02 npm-debug.log.1237251798
-rw-r--r-- 1 pi   pi    3164 Feb 27 17:55 npm-debug.log.2100934864
-rw-r--r-- 1 pi   pi    3164 Feb 27 17:16 npm-debug.log.2184727736
-rw-r--r-- 1 pi   pi    3083 Feb 23 19:06 npm-debug.log.239552560
-rw-r--r-- 1 pi   pi    3619 Feb 23 19:02 npm-debug.log.2616976422
-rw-r--r-- 1 root root  3075 Feb 25 16:39 npm-debug.log.3941375272
-rw-r--r-- 1 pi   pi       0 Feb 23 19:11 npm-debug.log.4050418629
-rw-r--r-- 1 pi   pi    3166 Feb 27 18:01 npm-debug.log.4182372596
-rw-r--r-- 1 pi   pi    3164 Feb 27 18:00 npm-debug.log.795953643
-rw-r--r-- 1 root root  3615 Feb 25 16:38 npm-debug.log.820015163
drwxr-xr-x 2 pi   pi    4096 Feb 27 17:59 persist

also did you say to remove the log files in .homebridge folder? 

and finally when I edit my config.json do I have to only edit in the .homebridge folder or also in the var/lib/homebridge folder as I followed the instructions on here to set it up on boot: 

https://gist.github.com/johannrichard/0ad0de1feb6adb9eb61a/

I am using the (systemd) method to run on boot

**Comment by cflurin** [comment]
yes, the *.log files in .homebridge, you don't need them.

as I said I use init.d, I can't help regarding systemd

**Comment by bachoo786** [comment]
thanks alot
