### ISSUE TITLE
New version: Failed with OSStatus code -6723 (Communication Failure)  server jammed?

### ISSUE THREAD

**Issue by nzhome** [nfarina/homebridge#117]
Steps to reproduce:
rm -r homebridge
npm install homebridge
privacy->homekit->reset
DEBUG=* node app.js
Open MyTouchHome
Add room
Click on room
Add accessory
Click Homebridge
Enter code: 03145154   
*popup message on iphone* "Failed with OSStatus code -6723 (Communication Failure)"
Click Ok 

  HAPServer [CC:22:3D:E3:CE:30] Client FE06A1D3-9A30-465E-B395-4F29ED675FE4 verification complete +18ms
  EventedHTTPServer [10.1.1.11] HTTP Repsonse is finished +7ms
  EventedHTTPServer [10.1.1.11] HTTP request: /accessories +23ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: GET /accessories +2ms
  EventedHTTPServer [10.1.1.11] HTTP Repsonse is finished +37ms
  EventedHTTPServer [10.1.1.11] Client connection closed +468ms
  EventedHTTPServer [10.1.1.11] HTTP connection was closed +11ms
  EventedHTTPServer [10.1.1.11] HTTP server was closed +4ms
  EventedHTTPServer [10.1.1.11] New connection from client +18ms
  EventedHTTPServer [10.1.1.11] HTTP server listening on port 54826 +3ms
  EventedHTTPServer [10.1.1.11] HTTP request: /pair-verify +13ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +2ms
  HAPServer [CC:22:3D:E3:CE:30] Pair verify step 1/2 +5ms
  EventedHTTPServer [10.1.1.11] HTTP Repsonse is finished +47ms
  EventedHTTPServer [10.1.1.11] Client connection closed +250ms
  EventedHTTPServer [10.1.1.11] HTTP connection was closed +6ms
  EventedHTTPServer [10.1.1.11] HTTP server was closed +3ms

ctrl+c on raspberry pi
privacy->homekit->reset
DEBUG=* node app.js
 EventedHTTPServer Server listening on port 51826 +0ms
Click on room
Add Accessory
--->  nothing ever shows up,,, the server is jammed?
ctrl+c on raspberry pi
privacy->homekit->reset
DEBUG=* node app.js
 EventedHTTPServer Server listening on port 51826 +0ms
Click on room
Add Accessory
--->  nothing ever shows up,,, the server is jammed?

**Comment by KhaosT** [comment]
@nzhome in this situation you needs to remove ./persist/ to reset server.

**Comment by nzhome** [comment]
@KhaosT  thanks, yes I had come to the realization that something was persisting somewhere. 

is there a way to detect when the user puts in the wrong code and handle "OSStatus code -6723 " more gracefully?  


 Accessory [Homebridge] Creating new AccessoryInfo for our HAP server +0ms
  Accessory [Homebridge] Creating new IdentifierCache +76ms
  EventedHTTPServer Server listening on port 51826 +354ms

**Comment by nzhome** [comment]
oh *snap*  I did put in the correct code and it still gives that OSStatus code -6723. I even capture a screenshot to prove to myself I was entering in the correct code to match that in app.js 03145154

**Comment by nfarina** [comment]
There could be something that HomeKit doesn't like about your accessory configuration. Can you try adding first with an "empty" `config.json`?

**Comment by nzhome** [comment]
but it worked ok with the same config file after I deleted the AccessoryInfo and IdentifierCache.  Can you also try your config with a brand new npm install? because I replayed the steps to reproduce twice, and I still got the same outcome.

**Comment by nzhome** [comment]
@KhaosT  in this situation,  this is a brand new npm install.  does everyone have to remove the /persist/ folder when they do a brand new install?  maybe we should add that to the installation instructions.

**Comment by nzhome** [comment]
@nfarina yes the problem does not exist with an empty config.json, but it does when adding actual accessories it does have the problem, BUT if i delete the persist files 3 times, and reset the privacy->homekit 2 times.  then the same config file *does* actually work.   so whats up with that I wonder?

cd persist
rm *.json

**Comment by cflurin** [comment]
Just try another "username": "CC:12:3D:E3:CE:27",
e.g. change the setting to  "AC:12:3D:E3:CE:27",
in config.json

**Comment by nzhome** [comment]
@cflurin but this is reproducable on a brand new homebridge npm install, and on a phone with no homekit databases.  why the hacks?

**Comment by cflurin** [comment]
It depends on iCloud, does it work?

**Comment by nzhome** [comment]
@cflurin  what does iCloud have to do with receiving an error one minute, and working another?  but never have I seen it work first time from a fresh install.

**Comment by cflurin** [comment]
hmm, this is another issue, sorry i cannot help you.

**Comment by nzhome** [comment]
is there a way I can log more details on ios or on homekit about this?  seems that the logging on homebridge is not detailed enough to figure out what is going wrong?

**Comment by nzhome** [comment]
ios9 is so close to being released, I'm thinking of holding off any more testing until then.

**Comment by nzhome** [comment]
Apple's iOS 9 update is rumored to launch on September 16 for iPhone and iPad.

**Comment by volschin** [comment]
Often they release at the day of the keynote. Last times this was during IFA, where they do not attend, last year Tuesday. So I bet on September 8.
