### ISSUE TITLE
Wifi connected wall control panel ?

### ISSUE THREAD

**Issue by SPINACHCEO** [nfarina/homebridge#1170]
hello there. Would anyone please help me with some ways to control homebridge outside home kit ? For example let some accessory to trigger scenes or control other accessory?

My problem is i am trying to make a wall panel with wifi connection, but the panel doesn’t directly connected to any home hardware circuit

**Comment by cflurin** [comment]
Have a look at:
http://nodered.org/
and
https://github.com/cflurin/homebridge-mqtt

**Comment by SPINACHCEO** [comment]
Thanks cflurin.
I have setup some devices using mqtt.
But all they can do is receive commands from home bridge. I am looking for if there is some way to let an accessory send command to homebridge like we do in Home app.

Is this possible or any workaround ?

**Comment by cflurin** [comment]
https://github.com/cflurin/homebridge-mqtt#set-value-to-homebridge

https://github.com/cflurin/homebridge-mqtt/wiki/homebridge2NodeRED

**Comment by snowdd1** [comment]
Are the both of you talking about the same thing?  
I understand that @SPINACHCEO wants to change values of non-mqtt devices (like Hues or something). As far as I know this is only possible by using homebridge insecurely and post (e.g. using `curl`) or create MQTT devices and use automations to "pass" the trigger from one accessory to another.  
Am I right?

**Comment by cflurin** [comment]
Hi @snowdd1,
Maybe, it isn't always easy to catch the "intention".

As far as I remember you are using KNX-devices.
How are you doing your automation stuff?
e.g. a motion sensor turns on a light for 3 minutes but only when it's dark and the alarm system is off.

**Comment by snowdd1** [comment]
@cflurin : Most of the people using a KNX installation have (at least) one HomeServer or other logic device, and several of the actuators have logic themselves. It's more a communication among a lot of peers using a broadcasting protocol. So in your example: The motion sensor might send a telegram stating that motion was detected, and the light actuator receives that telegram in a logic component, checks if the last broadcasted status of the alarm device was off, checks whether the last broadcasted status of the ambient light sensor was "dark", and starts a stairway light scene with a predefined lightning time. The actuator might also actively broadcast his activity and also the status update when the light is off again, so other peers might react on that - e.g. I use it to always switch on the cellar aisle light for 5 minutes if the light in any cellar room is switched off, no matter how it was switched off.  
As mentioned above, you can also use a central component (like a Gira HomeServer in my case) for more centralized activities (or things so individual that it doesn't fit into the logic components of the actuators/sensors)) - disadvantage: If that component fails, you might end up in the dark, or cold. Stand KNX components are all individual logic devices, dependent only on bus power (and main power for the actuators, of course).  
So also homebridge-knx is listening to all the individual broadcasts from the bus wire and reacts accordingly - updates HomeKit status etc. And of course, at any time one could inject data like bus telegrams anywhere into that system to switch things, if that is a goal. I am using a visualization that lets me switch any light in the house, any blind, any heater valve for the floor heating and such

**Comment by cflurin** [comment]
@snowdd1: I see, It's probably an evolution of the last years.

That's the point I'm often trying to explain: IMO Homekit (iOS) isn't the ideal approach for home automation.
I used several systems in the past but my latest favorite one is note-red (3 RPis) and Mqtt for the communication, not only with homebridge but also with ESP8266's and node-red to node-red.

**Comment by snowdd1** [comment]
@cflurin Yep, I see it as an extra layer of visualization with some added features like push notifications on the iOS devices. It's nice that Siri can switch some lights or open the garage door when your out there with the bike and have your hands in the gloves and no hand for the keys or the phone.  But then, Siri has a stroke sometimes and can't remember anything...
