### ISSUE TITLE
Can't install -  Error: `gyp` failed with exit code: 1

### ISSUE THREAD

**Issue by jasongold** [nfarina/homebridge#1172]
I tried installing on my pi. 

This was in the log:

2122 error mdns@2.3.3 install: `node-gyp rebuild`
2122 error Exit status 1
2123 error Failed at the mdns@2.3.3 install script.
2123 error This is most likely a problem with the mdns package,
2123 error not with npm itself.
2123 error Tell the author that this fails on your system:
2123 error     node-gyp rebuild
2123 error You can get their info via:
2123 error     npm owner ls mdns
2123 error There is likely additional logging output above.
2124 error System Linux 4.4.38-v7+
2125 error command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "--unsafe-perm" "homebridge"
2126 error cwd /usr/local/lib/node_modules
2127 error node -v v0.10.29
2128 error npm -v 1.4.21
2129 error code ELIFECYCLE
2130 verbose exit [ 1, true ]

**Comment by snowdd1** [comment]
> 2127 error node -v v0.10.29

Update your node [installation to 6.x LTS](https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi#nodejs-package-manager-apt-get-install)

ELIFECYCLE errors always mean "End Of Life Cycle"

**Comment by GeorgeBgk** [comment]
Run `sudo apt-get install libavahi-compat-libdnssd-dev`
I had this problem too. You just have to install libavahi-compat-libdnssd-dev package

**Comment by amomat** [comment]
I have tried installing avahi like mentioned above but I get this error:

The following packages have unmet dependencies:
 libavahi-compat-libdnssd-dev : Depends: libavahi-client-dev but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

New to all this so dont know what more info you want. Have updated node to 4.2.1 and nodejs to 6.10.0 but just cant install avahi. Running Rpi 2 with Raspbian Jessie

**Comment by snowdd1** [comment]
You can try to fix broken dependencies with `sudo apt-get install -f`

**Comment by snowdd1** [comment]
Node and nodejs are supposed to be the same (actually node is commonly a link to nodejs). If they show different versions
`node -v`

`nodejs -v`

then you have two different installations with different versions which is most probably going to provoke strange errors.

**Comment by amomat** [comment]
Thanks. Reinstalled node so that it now shows the same version when I run node -v and nodejs -v. 6.10.0. Ran npm install without errors. Tried running:

sudo apt-get install -f libavahi-compat-libdnssd-dev

But still get the same error:

The following packages have unmet dependencies:
 libavahi-compat-libdnssd-dev : Depends: libavahi-client-dev but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

Any ideas where to go from here?

**Comment by snowdd1** [comment]
You could try this: http://askubuntu.com/questions/164587/how-can-you-unhold-remove-a-hold-on-a-package
That's what google found.

**Comment by amomat** [comment]
Think it had to do with my install of netatalk. Removed that and now I can install avahi. Thanks.
