### ISSUE TITLE
How to reainstall homebridge 

### ISSUE THREAD

**Issue by daniel4099** [nfarina/homebridge#1173]
Hello, I have a problem with hombridge Afryce reinstall NPM. 

While hombridge is running with some plugins it Agora informatorom, plugin not find. I m 100% shure It's installed

How Can I fully reinstall hombridge and all plugins and make clean installarion ?

**Comment by jspv** [comment]
if you want to fully remove and not just update:

delete homebridge and the homebridge plugins from node_modules (possibly in /usr/lib/node_modules
 or /usr/local/lib/node_modules if you installed with -g)

npm install homebridge (if installing locally)
npm install -g homebridge (if installing globally)

Do the same for your plugins.

You *may* also want to clear out your configuration and persistent state (essentially everything in the .homebridge directory) - in all likelihood, you issues may reside there.
