### ISSUE TITLE
Homebridge systemctl autostart issue

### ISSUE THREAD

**Issue by moment77** [nfarina/homebridge#1175]
If I start homebridge using just the node command ```homebridge``` it connects to my "Home" app on iPhone and shows both of my Apple TV's (using this with Home Assistant), but when I start up using _systemctl_ it connects, but with no accessories visible / availiable, just the screen saying "Add devices" or similar.

So my troubleshooting says that homebridge starts up just fine, but cannot connect to my Home Assistan service. Anyone else stumbled upon this issue?

**Comment by snowdd1** [comment]
Looks like your systemd service definition uses another user than you use in shell. Then you use a different path and different access rights.
