### ISSUE TITLE
Any way to access original requests?

### ISSUE THREAD

**Issue by drewcovi** [nfarina/homebridge#1179]
It seems that for HomeKit, Lightbulb brightness requests include both a Characteristic.On request and a Characteristic.Brightness request.  I've been digging around for quite some time trying to determine the origin of these requests once the setter is called, yet it seems these are isolated events.

Is this a limitation in homebridge? or HAPNode?

I'm working on a plugin that would **ignore** any Characteristic.On requests for Brightness changes, but right now have resorted to a hack...

**Comment by justme-1968** [comment]
this behavior has been introduced by homekit with iOS 10 or 10.1. i (and many others) think it is a homekit bug and should be fixed on apples side.

there is no realy good workaround as there are indeed separate events. you can only delay sending the On event to your device vor a little while and ignore it if there is a following Brighntess event. 

there is already at least one other thread about this.

**Comment by drewcovi** [comment]
https://github.com/nfarina/homebridge/issues/807
