### ISSUE TITLE
New version: Makes MyTouchHome accessories not room addressable

### ISSUE THREAD

**Issue by nzhome** [nfarina/homebridge#118]
adding the accessory homebridge to a room does not work, it just lumps all my dozens of homebridge accessories of the homebridge bridge under Home (default)  instead of the room I was in when I added the accessory, :(

you can no longer address via Siri each device behind the homebridge bridge in separate rooms.  :(

then I go to a new room, and you can no longer add accessories to that room.  :(

**Comment by nzhome** [comment]
In fact it has made MyTouchHome practically un-usable with homebridge now...  time to move to Eve or another software.

**Comment by KhaosT** [comment]
@nzhome It's an app problem. Please try Eve or Insteon+

**Comment by nzhome** [comment]
Yes Eve from the AppStore allows me to assign each accessory individually to its own room. thank you.
