### ISSUE TITLE
My MotionSensor updates are inconsistent

### ISSUE THREAD

**Issue by jspv** [nfarina/homebridge#1182]
I'm attempting to trigger the MotionDetected characteristic in a simulated MotionDetector accessory.  When I set the value to 'true' - sometimes it shows triggers on my phone, rarely (but occasionally) it will be trigger an automation it is set to trigger.  It never works if I don't have my phone actively watching and almost never works when connecting remotely from a different network (via AppleTV)

I've tried multiple ways to set the Characteristic, spend hours looking through examples and the debug logs, but for the life of me can't figure out why sometimes it works, and sometimes not.  Below are two log snips - where you can see one time it's sending the HTTP event, and one time it doesn't.

Working: 
```
[3/4/2017, 4:48:55 PM] [AWS] Messages matches TestMotion
[3/4/2017, 4:48:55 PM] [AWS] >>>>>> doing stuff <<<<<<<
[3/4/2017, 4:48:55 PM] [AWS] (set): TestMotion -> true
Sat, 04 Mar 2017 21:48:55 GMT EventedHTTPServer [::ffff:192.168.171.120] Sending HTTP event '12.9' with data: {"characteristics":[{"aid":12,"iid":9,"value":true}]}
```
Not Working:
```
[3/4/2017, 4:46:11 PM] [AWS] Messages matches TestMotion
[3/4/2017, 4:46:11 PM] [AWS] >>>>>> doing stuff <<<<<<<
[3/4/2017, 4:46:11 PM] [AWS] (set): TestMotion -> true
```
Here are the multiple ways I've tried calling

```javascript
 // service.getCharacteristic(Characteristic.MotionDetected).setValue(true);
// service.setCharacteristic(Characteristic.MotionDetected, true);
service.getCharacteristic(Characteristic.MotionDetected).updateValue(true);
```
I'd really appreciate a pointer in the right direction.  The code is pretty straightforward:

https://github.com/jspv/homebridge-sqs/blob/updatedebug/index.js#L190

**Comment by jspv** [comment]
Note: due some pushes on that branch, the motion sensor code is about 25 lines further down now.

**Comment by snowdd1** [comment]
It looks as if your Apple TV does not register this characteristic for events, just the open HomeKit app on your phone does - is your Apple TV set up as the home hub ? Just search the issues here (also closed) a lot of people had the problems, and there are several ways to address that!

**Comment by jspv** [comment]
Yes, two Apple TVs actually, and I can see them getting event notifications regularly from homebridge - but to your point -  not consistently for these events.

**Comment by jspv** [comment]
From the logs, it **Appears** that the iOS device is first registering to see the MotionDetected events, and then repeatedly unregisters them.  In the log below the MotionSensor is aid:6, and the MotionDetected Characteristic is iid:9. 

```
 EventedHTTPServer [::ffff:192.168.XXX.XXX] HTTP request: /characteristics +5ms
  HAPServer [XXX] HAP Request: PUT /characteristics +0ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":6,"iid":9,"ev":true}] +0ms
  Accessory [Homebridge] Registering Characteristic "Motion Detected" for events +0ms
  EventedHTTPServer [::ffff:192.168.XXX.XXX] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:192.168.XXX.XXX] HTTP request: /characteristics +4ms
  HAPServer [XXX] HAP Request: PUT /characteristics +0ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":6,"iid":9,"ev":false}] +0ms
  Accessory [Homebridge] Unregistering Characteristic "Motion Detected" for events +0ms
  EventedHTTPServer [::ffff:192.168.XXX.XXX] HTTP Response is finished +1ms
...
  EventedHTTPServer [::ffff:192.168.XXX.XXX] HTTP request: /characteristics +22ms_
  HAPServer [XXX] HAP Request: PUT /characteristics +0ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":6,"iid":9,"ev":false}] +0m
  Accessory [Homebridge] Unregistering Characteristic "Motion Detected" for events +0ms
'''

**Comment by rahulmr999** [comment]
any update on this ? :)

**Comment by KhaosT** [comment]
Not really, I'd suggest you check iOS log and figure out why HomeKit unregister the notification for this characteristic.

**Comment by jspv** [comment]
I believe I've tracked this one down to an iOS bug.  I've reproduced the behavior of 'Registering' for "Motion Detected" events immediately followed by 'Unregistering' events using just the Homekit Accessory Simulator and three iOS devices on 10.2.1.  No homebridge, no HAP-Node.js - just vanilla Apple and the problem of many non-propagating Motion Detection events is consistent.

Good new: I installed the iOS 10.3 beta on one of my devices and the problem is gone, so it looks like Apple found this one.

For now: in case anyone absolutely needs it, I've made a trivial modification to my HAP-Node.js fork to ignore Unregister events for the "Motion Detected" characteristic.  (https://github.com/jspv/HAP-NodeJS)

It appears to fix the problem for me until 10.3 is released.  I don't know what other consequences ignoring the event will cause; but so far so good.

**Comment by rahulmr999** [comment]
Is it really necessary to set the data[0].ev = true; based on aid and iid because aid and iid keeps changing for me .
Why can't we directly set the ev to true in accessory.js incase of motion detection. ?

```
var eventName = aid + '.' + iid;
            if (characteristic.displayName == "Motion Detected" && ev === false) {
             
                ev = true;
            }

          
```

**Comment by KhaosT** [comment]
@rahulmr999 because accessory should not send notification to iOS device unless iOS device asked for it.

**Comment by NorthernMan54** [comment]
FYI - I  have 10.3 installed, and have this issue so I installed the hack, and the problem is gone ;-)

**Comment by brownad** [comment]
The hack is king at the moment. Wouldn't receive camera motion snapshots without it

**Comment by rahulmranjith** [comment]
Is it just about the camera motion shots in the alerts ? I don't even receive the alerts once connected through the apple tv.

**Comment by brownad** [comment]
Nope it's having consistency on all motion alerts, just happens I notice it more when the doorbell rings and no alert is sent, requiring a reboot and then after a day they stop. The hack has held up so far no reboot and they all push through.   I use an iPad and Apple TV as hub(s) might be something there..

You might want to check your logs and setup

**Comment by rahulmranjith** [comment]
I think you misread my comment. I was asking whether the camera motion still images was the only issue before the hack ? I think it is not . even the normal notifications for the motion sensor was not working over apple tv. (If no camera is linked, motion sensor sensor gives some plain notification.) Yes. that hack works for all kind of notifications. I made the changes limited to the accessory.js  as mentioned in one of my earlier comments and it also works without any issues.

**Comment by brownad** [comment]
No, I read it correctly and said notifications is random without this hack and appreciate the hack because it enables doorbell alerts with a snapshot, without it the state was broken. Its just I notice and expect notifications when the doorbell is pressed, whereas I notice less the failure with internal house movement alerts (hue) because there's no secondary way to check without testing it all the time.

**Comment by NorthernMan54** [comment]
For me i noticed the broken behavior with motion sensor and camera in the same room.  And inconsistently receiving picture notifications.  I have an ATV4 as the home hub, but I also have a recent iPad.  After reviewing the logs when it was working versus not working, I found that when the iPad was at home it worked, but when the iPad wasn't available it stopped.

I also have a garage door open/close sensor and this always worked.

**Comment by kernelheap** [comment]
I have the same problem even with iOS 10.3. The hack worked but I wonder if the hack will prevent motion detected automations from ever being deleted (even when i WANT them deleted)

**Comment by NorthernMan54** [comment]
With the hack, I can still turn off notifications in the Home app.

**Comment by simonrb2000** [comment]
Silly question. I have stumbled upon this thread by accident. I also have an issue where notifications with pictures work at home however do not work whilst out the house; I use an Apple TV 4 as a hub. I assume this 'hack' fixes that issue. If this is the case what's the easiest way of installing the hack without interfering with me existing setup (the rooms and scenes took a long time to sort out and get right!! Lol)

Many thanks!!

On 20 Apr 2017, at 11:19, NorthernMan54 <notifications@github.com<mailto:notifications@github.com>> wrote:

With the hack, I can still turn off notifications in the Home app.

**Comment by NorthernMan54** [comment]
As a coder, I just went into the code and directly made the change.  If your comfortable editing source files, it is an easy update.

**Comment by simonrb2000** [comment]
NorthernMan53, does your Alexa build have this 'hack' baked in?

Cheers

On 20 Apr 2017, at 19:24, NorthernMan54 <notifications@github.com<mailto:notifications@github.com>> wrote:

As a coder, I just went into the code and directly made the change. If your comfortable editing source files, it is an easy update.

**Comment by NorthernMan54** [comment]
@simonrb2000 As of 30 minutes ago, yes

**Comment by simonrb2000** [comment]
I might install that then, for my echo coming 👍

On 21 Apr 2017, at 00:25, NorthernMan54 <notifications@github.com<mailto:notifications@github.com>> wrote:

@simonrb2000 As of 30 minutes ago, yes

**Comment by skrollme** [comment]
Is there an "current state" on this? Did the later/stable 10.3.x iOS Versions fix this for you @jspv?
I'm still facing the problem with - for example homebridge-people (register and immediate unregister >> no realtime pushes on state changes) - but with the Homekit Accessory Simulator the occupancy-statechanges pop up in realtime inside Home.app.
