### ISSUE TITLE
Installing on de Raspberry Pi Zero W

### ISSUE THREAD

**Issue by gielk** [nfarina/homebridge#1183]
I keep getting stuck at Install Homebridge and dependencies i installed 
I have used Node.js binaries install method.

```
pi@raspberrypi:/opt/node/lib/node_modules/hap-nodejs/node_modules/mdns $ sudo node-gyp BUILDTYPE=Release rebuild
sudo: node-gyp: command not found
```

**Comment by snowdd1** [comment]
Which node version? From what source? Do you have gcc installed? See Wiki pages for Raspberry install!

**Comment by gielk** [comment]
I Have followed the wiki page and used this example

wget https://nodejs.org/dist/v6.9.5/node-v6.9.5-linux-armv6l.tar.xz
tar xJvf node-v6.9.5-linux-armv6l.tar.xz
sudo mkdir -p /opt/node
sudo mv node-v6.9.5-linux-armv6l/* /opt/node/
sudo update-alternatives --install "/usr/bin/node" "node" "/opt/node/bin/node" 1
sudo update-alternatives --install "/usr/bin/npm" "npm" "/opt/node/bin/npm" 1



Op 6 mrt. 2017 om 20:01 heeft Raoul <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Which node version? From what source? Do you have gcc installed? See Wiki pages for Raspberry install!

**Comment by gielk** [comment]
GCC is default already installed

**Comment by snowdd1** [comment]
Is the node-gyp package installed? It seams not to find it. According to  
https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi#install-homebridge-and-dependencies  
...you should have installed node-gyp along with the other packages.

**Comment by gielk** [comment]
```
sudo npm install -g --unsafe-perm homebridge hap-nodejs node-gyp
cd /opt/node/lib/node_modules/homebridge/
sudo npm install --unsafe-perm bignum
cd /opt/node/lib/node_modules/hap-nodejs/node_modules/mdns
sudo node-gyp BUILDTYPE=Release rebuild

```
@snowdd1 i used the code as described above so i have installed node-gyp right ?

**Comment by snowdd1** [comment]
Should be so. With my old Pi1b it worked back then.  
Why do you build mdns by hand? That should be taken care of by `npm install` of hap-nodejs

**Comment by Pltnorwich** [comment]
Hi, Im having the exact same issue,     sudo node-gyp BUILDTYPE=Release rebuild  returns command not found and followed all the steps 

Node binaries installed same as gielk's 2nd post to for ARMV6.

I did have this error thrown up as someone else was trying to help me trouble shoot if and where npm or node has been installed.

npm ERR! extraneous: bignum@0.12.5 /opt/node/lib/node_modules/homebridge/node_modules/bignum

**Comment by snowdd1** [comment]
I just found out I used the older installation instructions before @nrobinson2000 added that change: https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi/_compare/993ccfb9f1f7a1091f1bb4e441c0e5738377dc54  
I didn't need that.  But I do not know why. Worked without re-building mdns manually.

**Comment by mediaj** [comment]
Did you managed to get it working? I am stuck with the same error. sudo node-gyp BUILDTYPE=Release rebuild doesn't seem to be working. Followed the guide to the letter, but still doesn't work. I am on a Raspi Zero with Jessie Lite.

**Comment by gielk** [comment]
I used the Node.js manual install method 

[http://blog.wia.io/installing-node-js-v4-0-0-on-a-raspberry-pi/](url)

and was able to `sudo node-gyp BUILDTYPE=Release rebuild`

but now when i start homebridge there is no plugin found. I have installed some plugins... what to do ?
