### ISSUE TITLE
Siri can't execute Scenes

### ISSUE THREAD

**Issue by sats4eva** [nfarina/homebridge#1184]
Siri for some reason cannot execute any home bridge scenes. I used to be able to say "unlock garage door" and it worked fine. Now it says it can't find it and to try it another way or something like that. All official home kit devices still work. I changed nothing in my config, no new plugins. Just happened out of nowhere...Ive tried to delete the accessories, persist folder, reinstall home bridge, on node 6.10.0....not sure what else to do...

**Comment by justme-1968** [comment]
these kinds of problems and errors are nearly always located on apples side. they often change tings in siri and then some words are not recognized any more or recognized differently.

tray to name the scene in a different way without garage. garage door is a known device type for homekit and probably apple has changed the precedence of device types vs scene names.

maybe tomorrow everything is back to normal. i had this happening a few times for the german words for blind.

**Comment by sats4eva** [comment]
I have another one for a side entry door. Same thing. TV on and TV off used to work with harmony bridge. Damn Apple

**Comment by sats4eva** [comment]
Any other thoughts?
