### ISSUE TITLE
No Plugins found

### ISSUE THREAD

**Issue by gielk** [nfarina/homebridge#1186]
when i start homebridge there is no plugin found. I have installed some plugins... what to do ?
```

*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[3/8/2017, 11:07:17 AM] No plugins found. See the README for information on installing plugins.
[3/8/2017, 11:07:18 AM] config.json (/home/pi/.homebridge/config.json) not found.
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[3/8/2017, 11:07:18 AM] Homebridge is running on port 35281.
```

what should be the folder where the plugins are installed ? Do I need to move them ?

```
npm -v
2.15.5
```

```
node -v
v4.4.5
```

**Comment by snowdd1** [comment]
some info about where you installed homebridge to, and where the plugins to? And which plugins you might be talking about?

**Comment by gielk** [comment]
@snowdd1 i just installed it by using the ssh function on sudo

/home/pi/node_modules
here are the plugins and also homebridge.
also homebridge config is here
/home/pi/.homebridge
![schermafbeelding 2017-03-15 om 19 56 36](https://cloud.githubusercontent.com/assets/24224715/23965892/c5ff4102-09b9-11e7-9521-1dd235f1e977.png)
![schermafbeelding 2017-03-15 om 19 58 48](https://cloud.githubusercontent.com/assets/24224715/23965915/daf538e6-09b9-11e7-9889-86e850e9a7b2.png)

**Comment by gielk** [comment]
FOUND THE PROBLEM !!

i have copied the plugins to the folder where homebridge is searching for plugins

`sudo cp -a /home/pi/node_modules/"plugin that installed"  /usr/local/lib/node_modules`

**Comment by NorthernMan54** [comment]
I'm glad you found your issue

2 tips for this

1 - if you install the plugin with the -g option it installs in that location, but you need to use sudo as well

2 - you can use the -P option when starting homebridge to indicate where to find the plugins, i.e.

homebridge -P node_modules/

**Comment by rnglad** [comment]
@NorthernMan54 
Thanks for this -P hint. I always run home bridge with -P to show the folder with node_modules (on my raspberry pi)
But what do I do to run it as a service with this -P????
