### ISSUE TITLE
Make homebridge function as a Hub

### ISSUE THREAD

**Issue by hyperbart** [nfarina/homebridge#1187]
Going wild here a little bit but since HomeBridge is already connected to our LAN at home wouldn't it be possible to make Homebridge function as a Hub itself too instead of an Apple TV or iPad?

Or are there technical complexities from Apple that prevent this?

**Comment by andyrooo82** [comment]
It would be good if we didn't have to rely of ATV for automations that's for sure.

**Comment by hyperbart** [comment]
My experience is that an ATV works fine, but the iPad can't always seem to keep it's WIFI connection alive although it should, but sometimes our iPad isn't used for like 1 or 2 days and then it does seem to drop the connection.

Since I started using ATV and disabled all other iDevices in my home as Home Hub it works perfectly.

**Comment by justme-1968** [comment]
no it is not possible. has been discussed many times.

atv (and iPad) are the only real ways to get remote access and push notifications.

regarding the automation: use a 'real'  home automation system and use homebridge/homekit only as on of many different frontends.

using homekit as the central system for automation is not sensible for many different reasons.

**Comment by andyrooo82** [comment]
@justme-1968 could you recommend a good 'real' home automation system?

**Comment by justme-1968** [comment]
i can recommend fhem. it is flexible and has support for a huge range of systems and devices. but it is not an 'easy' system and requires some time getting used to. also the forum and wiki ist mostly in german.

others would be openhab, home assistant, maybe node-red, ... there are many and to find the right one for your needs will take some time and searching. and some things will not be plug and play. 

you will have to invest time and energy but you will be able to create a system that integrates many components from different vendors.

**Comment by andyrooo82** [comment]
Home assistant looks good. Just need to find out how to install it on the same Pi as homebridge

**Comment by hyperbart** [comment]
Home assistant is very accessible and a nice one, but since I am using KNX and HA isn't compatible with it I am diverting to OpenHAB (for now).

**Comment by andyrooo82** [comment]
Luckily I'm using Mi-Light, Harmony Hub, Locative and IFTTT all of which are supported by Home Assistant so it would seem to be a good fit for me. I can then use homebridge to expose to HomeKit so I can use Siri. 

Will I still be able to use iOS Home App as a front end or just Siri?

**Comment by andyrooo82** [comment]
Looking at the open issues though with the Home assistant plugin there seems to be some trouble setting scenes. This is really important for me. Probably more so than automations.

**Comment by jonathanweinberg** [comment]
@justme-1968 oddly enough, I think I just saw mention of the ability to use a Lightning to Ethernet adapter in an upcoming release of iOS. I'll try to find it when I'm not half asleep.

**Comment by jonathanweinberg** [comment]
Here's something: http://www.gottabemobile.com/how-to-connect-an-ipad-to-ethernet/

iOS added Ethernet settings in 10.2.

**Comment by justme-1968** [comment]
but what good is an iPad that is tied to a cord? an iPad is a frontend/gui device. not an automation server that runs 24/7 tucked away in the background.

even my old gen3 Apple TV from ebay is better for providing remote access to homekit as it never goes to sleep, never runs out of batteries, is never switched off accidentally by someone, ...

but the main reason for not recomending homekit as the homeautomation center is that it really limits your range of devices and interactions.

i love iOS and use it every day. i would not want to use any other os for my mobile device. and i use only macs as my desktops and laptops. but i would never ever user homekit as my homeautiomation system. as a frontend (one of the frontends) it is great. but that's it.

**Comment by andyrooo82** [comment]
@justme-1968 I agree with your sentiments. I got really fed of of automations not firing so I took the plunge at the weekend and installed Home Assistant on my pi along side Homebridge. I'm not completely finished yet as I cannot get my home and away automations to work (but I know it's something I can fix and don't have to rely on Apple) 

I've recreated most of my scenes and easy automations which fire of scripts which In tun fire off scenes. I haven't installed homebridge-Home assistant plugin yet either, I'll do this once I'm happy everything in Home assistant is working. So I'll still be able to use siri as a front end and I'll have control over my automations. 

I've only looked at it over 2 days but already I can see there's a lot more potential for automations in home assistance than HomeKit. They'll also work consistently which iOS just isn't.

**Comment by hyperbart** [comment]
Same here, will be using OpenHAB when they finish the V2 of their KNX binding. HomeKit is absolutely fantastic as a front-end but not really for automation EXCEPT for when you arrive home and want to turn on your porchlight or something like that 👍

**Comment by andyrooo82** [comment]
I found Arrive Home hit and miss and Leave Home pretty much miss. The two most import ones for me hence ditching iOS automations.

**Comment by hyperbart** [comment]
Haven't been able to test it thoroughly here because for some reason the Wifi database Apple is using still puts me a couple of streets of from my real location when I am paired with wifi. But initially it worked fine when I had temp wifi.

**Comment by cicciovo** [comment]
Hi, do you know if can i use an old iPhone (iPhone 5s) as a hub with homebridge instead an appletv or ipad?

**Comment by hyperbart** [comment]
Nope not possible.

**Comment by cicciovo** [comment]
So i can use homebridge when i’m not in my home only with a hub as appleTv or a new iPad... it’s right?

**Comment by hyperbart** [comment]
Correct

**Comment by pmansvelder** [comment]
I am using homebridge with Home Assistant and it works fine, even the scenes I add work better than expected. I was wondering about remote access too, but my workaround is to use Home Assistant and a private VPN to connect remotely. I find Home Assistant gives roughly the same functionality as Apple Homekit, it just has a different way of configuring. I really like the opprtunity to give Voice commands through Siri, though... ;)

**Comment by yceballost** [comment]
I don't understand why raspberry can't be a HUB. I was thinking the solution about public ip addresses or something like that... but I don't understand why it is impossible to set up like a hub. 

Some detail about the problem?

**Comment by pdlove** [comment]
It's how HomeKit's protocol works. It only communicates with the local network due to how the iPhone handles discovery.
It's conceivably possible to have Homebridge communicate directly with iCloud and emulate and Apple TV or iPad, but the problem with that is that you would have to have a program written that is going to violate the iCloud terms of service and potentially get Apple to come after that project to shut it down.

**Comment by MickL** [comment]
Do you guys think this might change some day? Basically the RaspberryPi is exactly the always-on device that is needed. As of 2019, is there no other device than iPad, Homepod and AppleTV that can be a hub?

How does all the automation work when using Mijia Home App only? All triggers are coming from the internet/cloud not from the gateway itself so they dont work when offline?

**Comment by louia** [comment]
Apple sucks, fuck Apple.

**Comment by JBFUK** [comment]
> Apple sucks, fuck Apple.

Sadly true since the departure of Steve Jobs.  No innovation, lower quality products, higher prices.

**Comment by liv3010m** [comment]
Hi guys, does anybody know if the AppleTV app from some of the new televisions works as an "Home Hub"?

PS: hopefully someday we got an opensource "Home Hub" implementation. :)

**Comment by mafyata** [comment]
No, apple tv app on smart tv is for watching shows , episodes , film from apple tv+ service

**Comment by liv3010m** [comment]
> No, apple tv app on smart tv is for watching shows , episodes , film from apple tv+ service

thanks for the fast reply!
