### ISSUE TITLE
uninstall all components of homebridge

### ISSUE THREAD

**Issue by iracohen1946** [nfarina/homebridge#1188]

**Comment by iracohen1946** [comment]
How do I uninstall all components of homebridge

**Comment by KhaosT** [comment]
``npm uninstall -g homebridge`` should be enough.

**Comment by cerniuk** [comment]
it would be nice to have a listing of every homebridge owned path and every home bridge file orphan (aka file not in a homebridge owned directory)

**Comment by Shana611** [comment]
Can we run Nest & Garage door opener in the same Raspberry pi 3?

**Comment by mewejo** [comment]
@Shana611  Yes, that's possible

**Comment by leecollings** [comment]
> `npm uninstall -g homebridge` should be enough.

So after doing this, I go to a browser to visit the home bridge page, and it's still running... how can this be then?

Seems the command that 'should be enough' does nothing.

**Comment by LeakedDave** [comment]
What's up guys, where's the full uninstall instructions?

**Comment by RealRyn** [comment]
Run the Node.js command prompt as administrator and type:
npm uninstall -g homebridge
hb-service uninstall

Then check C:\Users\[User-Name] and if there is an .homebridge folder, delete it.

now http://localhost:8581/ should be dead and homebridge is completely gone.
