### ISSUE TITLE
Cant find config.json file using mac terminal 

### ISSUE THREAD

**Issue by akif1** [nfarina/homebridge#1190]
Since upgrading to ios 10 , homebridge stopped working with HC2 . I also updated my HC2 and had to change the password . 

Now I am trying to find the Config.json file but it appears blank when i try to access it. 

the file is usually accessed by CD /root/ homebridge 

then: sudo nano config.json

This opens the file and it appears blank 

Any help would be appreciated....

**Comment by snowdd1** [comment]
Are you running homebridge as root? Usually the ".homebridge" folder is not located in the root Home folder.

**Comment by akif1** [comment]
Hi .

Thanks for that I wasn't typing the . Before homebridge . 

Prior to the iOS 10 upgrade . Siri was working perfectly. I  currently using Raspberry pi 2 model B . Although the home ridge is running perfectly, I cannot find this on the home app on the phone . Any help would be appreciated.

**Comment by ijobain** [comment]
sudo find / -name config.json
