### ISSUE TITLE
homebridge-chamberlain SyntaxError: Unexpected token < in JSON

### ISSUE THREAD

**Issue by dtydings** [nfarina/homebridge#1191]
A few weeks ago I had a similar problem with the liftmaster plugin and now it's happening with the chamberlain one since I switched over. It's been running flawlessly for a couple weeks until now and I haven't changed anything at all in my configuration. Could this be a problem on chamberlain's end?
Also I have a perfectly valid JSON according to jsonlint.com and up-to-date versions of the plugin, homebridge, and npm. 

SyntaxError: Unexpected token < in JSON at position 0
    at Object.parse (native)
    at /usr/local/lib/node_modules/homebridge-chamberlain/node_modules/node-fetch/lib/body.js:48:15
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by Neelrp12** [comment]
Use this plugin in instead of chamberlain. Put this into you jason.config file and put in your chamberlain username and password it worked for me.

https://github.com/luisiam/homebridge-liftmaster2
