### ISSUE TITLE
Multiple homes

### ISSUE THREAD

**Issue by NicAshby** [nfarina/homebridge#1194]
I have successfully installed homebridge on two raspberry pi 3s in two different homes. The first is set up perfectly on one iphone. The second homebridge is not found in the second home (same ios device and icloud account). Another ios device in the second home can find and connect to the homebridge device fine, but the original ios can not. i have changed device names and pins so they are unique to the device. am i missing something?

**Comment by snowdd1** [comment]
You're aware that one homebridge can only be paired with one iCloud account? Others need invitations as guests.

**Comment by NorthernMan54** [comment]
I have the following setup, which works fine.

House 1 - ATV4, multiple homebridges, all on one iCloud account,  multiple iOS devices on same iCloud account, and a couple of guests.

House 2 - ATV3, homebridge, same iCloud account, same iOS devices, and different guests.

I think you are seeing the feature of HomeKit of only pairing with a single iCloud account.  In your house 2, you need to take one of the iOS devices paired with house 1, reset homebridge ( remove accessories and persist directory, and change username in config ) and have that iOS device add it to house 2.  You will then have house 1 and 2 on the same iCloud account.

**Comment by NicAshby** [comment]
I only have the one iOS device at home 1. Home two has the two iOS devices. 
This is a "feature" that makes it so I can't use two home bridges in two homes on one iOS device?

**Comment by NorthernMan54** [comment]
All devices need to be the same iCloud account, then it just works.  If you don't want them to share the same iCloud account, i.e. Different people, then you need to invite them as a guest.

**Comment by snowdd1** [comment]
Apple security feature.

**Comment by NicAshby** [comment]
I don't think I'm being understood. All is under one iCloud account and one iOS device. Home 1 and home 2 both have functioning home bridges running. After adding home bridge 1 to home 1 in HomeKit, I am unable to add homebridge 2 to home 2 on the same iOS device. My wife's phone is able to create a home and add the homebridge 2 just fine.

**Comment by NorthernMan54** [comment]
At house 2, you need to be the first to add. The you can add your wife as guest.   You can only add a homebridge instance once.  That is a HomeKit feature. 

If you can't add house 2's homebridge, then you need to 'reset' that homebridge instance.  And try again.

**Comment by NicAshby** [comment]
I am aware I need to be the first to add it. I am just saying that it's visible and COULD be added on the wife's phone, but it doesn't show up on mine.

**Comment by NicAshby** [comment]
Solved: changed the username in the config.json

**Comment by snowdd1** [comment]
Then it was blacklisted for some reason in your iCloud account. It might have given an incomliant answer some time back when it was queried for accessories. HomeKit is sometimes very resentful.  
Changing the username in config.json essentially makes it a new, unknown device for HomeKit.
