### ISSUE TITLE
Losing connection with HomeKit randomly

### ISSUE THREAD

**Issue by MohammadAhmad1990** [nfarina/homebridge#1196]
I am losing connection of homebridge with homekit randomly and it gets back on and off randomly. below is the log. Kindly help

I have installed homeassistant and homebridge on the same raspberry pi. I have two switches on homeassistant and one samsung led plugin on homebridge. After Homebridge and homekit lose connectivity the samsumg plugin keeps working as is shown on the homeassistant web interface and works fine. The only issue is the random disconnection between homebridge and homekit 

below is the log for your reference 

****************************************************
[3/13/2017, 10:31:33 AM] [HomeAssistant] Setting power state on the 'Television' to on
  EventedHTTPServer [fe80::c0a:b0c3:d795:ce16] Sending HTTP event '3.8' with data: {"characteristics":[{"aid":3,"iid":8,"value":true}]} +21ms
  EventedHTTPServer [fe80::18b7:46a8:8df5:2f7d] Sending HTTP event '3.8' with data: {"characteristics":[{"aid":3,"iid":8,"value":true}]} +2ms
[3/13/2017, 10:31:33 AM] [HomeAssistant] Successfully set power state on the 'Television' to on
  EventedHTTPServer [fe80::c0a:b0c3:d795:ce16] Sending HTTP event '3.8' with data: {"characteristics":[{"aid":3,"iid":8,"value":1}]} +11ms
  EventedHTTPServer [fe80::18b7:46a8:8df5:2f7d] Muting event '3.8' notification for this connection since it originated here. +1ms
  EventedHTTPServer [fe80::18b7:46a8:8df5:2f7d] HTTP Response is finished +0ms
  EventedHTTPServer [fe80::18b7:46a8:8df5:2f7d] Writing pending HTTP event data +1ms
  EventedHTTPServer [fe80::18b7:46a8:8df5:2f7d] HTTP request: /characteristics +2s
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /characteristics +0ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":3,"iid":8,"value":0}] +1ms
  Accessory [Homebridge] Setting Characteristic "On" to value 0 +1ms
*****************************************************************************************

[11:18]  
*************************************************************************************
[3/13/2017, 10:31:34 AM] [HomeAssistant] Setting power state on the 'Television' to off
  EventedHTTPServer [fe80::c0a:b0c3:d795:ce16] Sending HTTP event '3.8' with data: {"characteristics":[{"aid":3,"iid":8,"value":false}]} +36ms
  EventedHTTPServer [fe80::18b7:46a8:8df5:2f7d] Sending HTTP event '3.8' with data: {"characteristics":[{"aid":3,"iid":8,"value":false}]} +2ms
[3/13/2017, 10:31:34 AM] [HomeAssistant] Successfully set power state on the 'Television' to off
  EventedHTTPServer [fe80::c0a:b0c3:d795:ce16] Sending HTTP event '3.8' with data: {"characteristics":[{"aid":3,"iid":8,"value":0}]} +19ms
  EventedHTTPServer [fe80::18b7:46a8:8df5:2f7d] Muting event '3.8' notification for this connection since it originated here. +2ms
  EventedHTTPServer [fe80::18b7:46a8:8df5:2f7d] HTTP Response is finished +1ms
  EventedHTTPServer [fe80::18b7:46a8:8df5:2f7d] Writing pending HTTP event data +0ms
********************************************************************************************************************

[11:20]  
******************************************************************************************************
 EventedHTTPServer [fe80::18b7:46a8:8df5:2f7d] Client connection closed +3m
  EventedHTTPServer [fe80::18b7:46a8:8df5:2f7d] HTTP connection was closed +1ms
  EventedHTTPServer [fe80::18b7:46a8:8df5:2f7d] HTTP server was closed +1ms
**************************************************************************************************

[11:22]  
The connection was lost as soon as my iphone was autolock. then unlocking it didnt restore the connection

[11:23]  
***************************************************************************************************
 EventedHTTPServer [fe80::c0a:b0c3:d795:ce16] Client connection error: read ETIMEDOUT +3m
  EventedHTTPServer [fe80::c0a:b0c3:d795:ce16] Client connection closed +0ms
  EventedHTTPServer [fe80::c0a:b0c3:d795:ce16] HTTP connection was closed +2ms
  EventedHTTPServer [fe80::c0a:b0c3:d795:ce16] HTTP server was closed +1ms
*****************************************************************************************************

[11:26]  
And now it makes a new connection randomly and shows this result 
*******************************************************************************************************
 EventedHTTPServer [::ffff:192.168.4.101] New connection from client +3m
  EventedHTTPServer [::ffff:192.168.4.101] HTTP server listening on port 34238 +0ms
  EventedHTTPServer [::ffff:192.168.4.101] HTTP request: /pair-verify +3ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +0ms
  HAPServer [CC:22:3D:E3:CE:30] Pair verify step 1/2 +1ms
  EventedHTTPServer [::ffff:192.168.4.101] HTTP Response is finished +19ms
  EventedHTTPServer [::ffff:192.168.4.101] HTTP request: /pair-verify +37ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +0ms
  HAPServer [CC:22:3D:E3:CE:30] Pair verify step 2/2 +0ms
  HAPServer [CC:22:3D:E3:CE:30] Client 6D13EF56-B8C6-45D6-BE47-335CD84F8B54 verification complete +3ms
  EventedHTTPServer [::ffff:192.168.4.101] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:192.168.4.101] HTTP request: /accessories +107ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: GET /accessories +0ms
  EventedHTTPServer [::ffff:192.168.4.101] HTTP Response is finished +5ms
  EventedHTTPServer [::ffff:192.168.4.101] HTTP request: /characteristics +69ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /characteristics +0ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":4,"iid":10,"ev":true},{"aid":4,"iid":13,"ev":true},{"aid":16,"iid":10,"ev":true},{"aid":16,"iid":13,"ev":true},{"aid":3,"iid":10,"ev":true},{"aid":3,"iid":13,"ev":true}] +1ms
  Accessory [Homebridge] Registering Characteristic "Reachable" for events +0ms
  Accessory [Homebridge] Registering Characteristic "Category" for events +1ms
  Accessory [Homebridge] Registering Characteristic "Reachable" for events +0ms
  Accessory [Homebridge] Registering Characteristic "Category" for events +0ms
  Accessory [Homebridge] Registering Characteristic "Reachable" for events +0ms
  Accessory [Homebridge] Registering Characteristic "Category" for events +0ms
  EventedHTTPServer [::ffff:192.168.4.101] HTTP Response is finished +1ms

[11:26]  
EventedHTTPServer [::ffff:192.168.4.101] HTTP request: /characteristics +110ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /characteristics +1ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":4,"iid":8,"ev":true}] +0ms
  Accessory [Homebridge] Registering Characteristic "On" for events +0ms
  EventedHTTPServer [::ffff:192.168.4.101] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:192.168.4.101] HTTP request: /characteristics +66ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /characteristics +1ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":3,"iid":8,"ev":true}] +3ms
  Accessory [Homebridge] Registering Characteristic "On" for events +1ms
  EventedHTTPServer [::ffff:192.168.4.101] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:192.168.4.101] HTTP request: /characteristics +19ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /characteristics +1ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":16,"iid":8,"ev":true}] +0ms
  Accessory [Homebridge] Registering Characteristic "On" for events +1ms
  EventedHTTPServer [::ffff:192.168.4.101] HTTP Response is finished +0ms
  EventedHTTPServer [::ffff:192.168.4.101] HTTP request: /characteristics?id=4.8,3.8,16.8 +23ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: GET /characteristics?id=4.8,3.8,16.8 +1ms
  Accessory [Homebridge] Getting value for Characteristic "On" +0ms
  Accessory [Homebridge] Getting value for Characteristic "On" +2ms
  Accessory [Homebridge] Getting value for Characteristic "On" +1ms
[3/13/2017, 10:40:33 AM] [HomeAssistant] fetching power state for: Samsung LED40 (UA40F5500)
  Accessory [Homebridge] Got Characteristic "On" value: false +23ms
  EventedHTTPServer [::ffff:192.168.4.101] Muting event '4.8' notification for this connection since it originated here. +1ms
  Accessory [Homebridge] Got Characteristic "On" value: false +6ms
  EventedHTTPServer [::ffff:192.168.4.101] Muting event '3.8' notification for this connection since it originated here. +1ms
  Accessory [Homebridge] Got Characteristic "On" value: false +5ms
  EventedHTTPServer [::ffff:192.168.4.101] Muting event '16.8' notification for this connection since it originated here. +0ms
  EventedHTTPServer [::ffff:192.168.4.101] HTTP Response is finished +1ms
******************************************************************************************************

[11:27]  
******************************************************************************************************
 EventedHTTPServer [::ffff:192.168.4.101] Sending HTTP event 'keepalive' with data: {"characteristics":[]} +52s
******************************************************************************************************

[11:28]  
And then on unclock it gets disconnect again
******************************************************************************************************
EventedHTTPServer [::ffff:192.168.4.101] Client connection closed +2m
EventedHTTPServer [::ffff:192.168.4.101] HTTP connection was closed +1ms
EventedHTTPServer [::ffff:192.168.4.101] HTTP server was closed +0ms
******************************************************************************************************

[11:32]  
http://myip/accessories
{"status":-70401}

**Comment by MohammadAhmad1990** [comment]
config.json for your reference

{
        "bridge": {
                "name": "Homebridge",
                "username": "CC:22:3D:E3:CE:30",
                "port": 51826,
                "pin": "031-45-154"
        },

        "platforms": [{
                "platform": "HomeAssistant",
                "name": "HomeAssistant",
                "host": "http://127.0.0.1:8123",
                "password": "raspberry_pi",
                "supported_types": ["binary_sensor", "cover", "fan", "input_boolean", "light", "lock", "media_player", "scene", "sensor", "switch"],
                "logging": false
        }]


}

**Comment by MohammadAhmad1990** [comment]
I would like to update that I figured out the issue
It was something to do with my home class wifi router.
I attached the homebridge server directly with my cisco switch 2950 and it is stable for the last 10 hours
seems the home class wifi routers and not that capable in handling traffic and maintain the connections
I had a this similar connectivity issue while running a vmware server connected to home class wifi router. The virtual machines would just lose connectivity randomly. As soon as i connected the vmware vsphere server with a cisco router the connectivity issue never happened again

I am closing this issue.

**Comment by thetom89** [comment]
Hi MohammedAhmad1990

I'm having the exact same issue as you.

I'm running homebridge on a MacBook Pro, OS Sierra.

It runs fine, until I randomly get the following in Terminal Debug:

 EventedHTTPServer [::ffff:192.168.0.24] Client connection closed +3m
 EventedHTTPServer [::ffff:192.168.0.24] HTTP connection was closed +1ms
 EventedHTTPServer [::ffff:192.168.0.24] HTTP server was closed +0ms

My MacBook Pro is connected wirelessly to a Virgin Media wifi box.

Would you have any suggestion as to how I might resolve this issue?

**Comment by MohammadAhmad1990** [comment]
@thetom89 Try to connect it directly to the wifibox over Ethernet and see the results. If that does not help then try a cisco product. Some how it seems these home grade wifi boxes are not capable of keeping the servers live.

My problem was solved when I connected my raspberry pi directly to my cisco managed switched over the Ethernet. Same should work for OS Sierra

My Hardware:
Cisco router 2621
Cisco managed switch 2950

**Comment by thetom89** [comment]
Hi MohammadAhmad1990

I've connected the laptop directly to the router.  It's only been a few minutes, but when the HTTP server closes, it opens up immediately when I switch back on my iPhone.  You were correct, thanks very much for your help.

The only problem is that I can't keep my laptop plugged in to the router in the kitchen.  Would you have any recommendation as to which raspberry pi to get and would it be very difficult to get it up and running on it?

**Comment by MohammadAhmad1990** [comment]
I am glad that I could help 
You may use the latest Raspberry Pi 3
https://www.raspberrypi.org/products/raspberry-pi-3-model-b/

No it is not difficult to set it up, plus its a palm size linux based comupter with additional inputs and outs that you can use as per your requirement. 

If you are looking towards home automation try having a look at homeassistant. They have a pre configured Raspberry pi OS jessi. you just have to install homebridge, homeassistant-homebridge plugin and update your config.json. You can find all the information for the setup on homeassistant website. They have a very good documentation.

Link for the homeassistant pre-configured OS. Just burn on the class 10 high speed micro SD card
https://home-assistant.io/docs/hassbian/installation/ 

Read the homeassistant documentation "Docs" for your reference
https://home-assistant.io/

**Comment by MohammadAhmad1990** [comment]
@thetom89 you can also use Nodemcu esp8266 and connect it homeassistant over mqtt and control its I/O over the wifi

Its like a wireless switch 

have a look at this project. very informative and a head start 
https://github.com/mertenats/Open-Home-Automation

**Comment by thetom89** [comment]
@MohammadAhmad1990 

Thanks very much for all of your help!  Hopefully I'll be able to get it all up and running before long!
