### ISSUE TITLE
how to use homebridge in public network?

### ISSUE THREAD

**Issue by linuxu2015** [nfarina/homebridge#1199]
thanks very much~ when the server and phone in the same wifi, it can work,but if they are not in the same network,should i do something else?i want deploy the homebridge in the remote server,so no matter where i am ,i can control my device by my phone, is there some way to handle this?

**Comment by snowdd1** [comment]
Yes. Search for "remote access" here. There are tons of issues.

**Comment by benzman81** [comment]
For remote access you just need an apple tv 4 or an ipad thats always home. They act as a brdige for homekit to enable your devices to be controlled from anywhere in the world.

**Comment by justme-1968** [comment]
for remote access gen3 also works. a cheap one from ebay is sufficient.

**Comment by HansWurst90** [comment]
@justme-1968 Is it right that the Apple TV 3 only works for remote access?
For Automation you still need the Apple TV 4?

**Comment by snowdd1** [comment]
@hanswurst90 yes, or an idle iPad with iOS 10.0+

**Comment by HansWurst90** [comment]
@justme-1968 I have an iPad 2 but it is not supported by iOS 10 😞

**Comment by justme-1968** [comment]
apple tv gen3 is only for remote access. and you can configure geofencing rules. they are run on your iPhone directly.

for other homekit rules you need a gen4. but i can just say again: use a real automation system in your home and homekit/homebridge only as a frontend. you will have so much more possibilities.

**Comment by simonrb2000** [comment]
Yup. That's what I do, domoticz is my home automation program which does everything and Homebridge is just a UI really. Domoticz exposes all the switches I want to homebridge. Works great.

On 30 Mar 2017, at 09:29, justme-1968 <notifications@github.com<mailto:notifications@github.com>> wrote:


apple tv gen3 is only for remote access. and you can configure geofencing rules. they are run on your iPhone directly.

for other homekit rules you need a gen4. but i can just say again: use a real automation system in your home and homekit/homebridge only as a frontend. you will have so much more possibilities.
