### ISSUE TITLE
Homebridge with Raspberry and TSL2561 Luminosity sensor

### ISSUE THREAD

**Issue by mediaj** [nfarina/homebridge#1200]
Hi, I am trying to get the TSL2561 luminosity sensor to work with Homebridge. The sensor is connected to my Raspberry Pi Zero and works: I can run a Python script and it gives me the values. 

I'd like to send the values to Homebridge and have the sensor show up in Homebridge, but I can't find a plugin. I did however find a MQTT-lux plugin. But, since my coding skills are not really good, how do I transfer the values generated by the Python script to my MQTT-broker (set up on the same Pi). 

I think I have to use the Paho MQTT-client that fetches the data and publishes it to the MQTT broker, but who can help me out with a script?

**Comment by cflurin** [comment]
Have a look here:

https://flows.nodered.org/node/node-red-contrib-tsl2561
to read the value and use:

https://github.com/cflurin/homebridge-mqtt
to send the value to homebridge.

**Comment by mediaj** [comment]
Thanks for the two links. I am going to try this out, although I'm under the impression it won't be a walk in the park ;)

**Comment by bzl1990626** [comment]
I come from China, can you give me some information?
