### ISSUE TITLE
Crash after a few days 

### ISSUE THREAD

**Issue by thoduh** [nfarina/homebridge#1201]
Bekomme immer nach einigen Tagen das hier zu sehen:
Verify Fail
Layer Decrypt fail!
Packet: 0004c033820d0a2813867396132ac9f030fcf40e3e418bbd85c5302bbbb68d62e8d5abfced9a1b05963bfd245dac2ae60898ef7781e64a5c981cae3eb867986758a870d9d614eb69d68a36593978e20cab00467e95034afd6f363cb75b6085348a01e9c25c0eb202c9fafd55b3c739a38b954658e73163c9df5764d162b14e62a21b5e7d2f70de3f657fe7ebc52bfaabca6fe6a8fabf23cfd815e94ba41b01e69accb756071847724b6f082f130bf3a4c96f31febe35d6c39465b89903db6fc58e8878fe82ddeb8d7bbb84ce9702beafa22bd3b3a664365a8ae892233800058b9b459160a6700230533ddf1295965b5229416e4c8c5dc156c85b5899461659d62f0de7636ddd09c581d8e766871ac9c24007f133eb0e7592e81d8b28dec97d733e95cc849bf86bece450ccbdd9b0231643b36742739f0ba965d57f1275a904497848ffe6dd327a632daf4a755172acf4e3100368089df2d5dc3892974e5077112111c56c430bbe5a0592a8c631a572ae9ab1bcf02d8bda52d2f6747ff3067a59701cdb7abd369bc959929b00169e0af4216a6799efd6891edba79eaf39c9116691a72eeec87dbd5980df7e1e72146e6b00f2ff657a9fa93d68f2027f33b7392c171bc8a1f79481eaee3b44140211e9490c0e08761deb5127f51eaf409e04401f0c20760ac9a8278b4a590d8a4d18ed484d3cb7a3643bb5858c8dea86af246f3670433adc80873844b653b39b3ee347348ade7f90d7b0ea045f17655d693cf1e9bac6efde93a27a6663217d507a32bc2066e842851535fd0cbc7377cf13767f810a3ad22c188bc65fdf3bcbe37988f7d2cec937fc0c2147b02b7cb552743af15b8494a526aea84167bd295a505abb44b471aaf1c5c7dacdbce93f542e58524b68bb914af5e83ca41ef52583514a550ddeb7ce3bd4c1212bb823951a78799c4edac92e3acba6ea40aaabf4aaf4914869e774be3cd0034155a60c0a6ee09b60830cd0ca2f710baddf426ab0dcc70aba6d0c380d0f869ae535661f2a6d63a8ed97ef07f8a424d5319d9d60b8eba4118d9fc94b0b45ac785a5ebd287103fd1c64b1eab4797e4a192cf9eec29bed279a50a3ada7aaf21829f8fd6b4b488d25855f68cebaf8efe3ddd5a112b0ece1ae0bd7bb64c638d6444609218b95fdaceca8aa2f8c5d0ef35b1b38df5ba3adabc71189d1ba794c952fa57d071ca25c07541e00d70c92075606127d57982584cc0e2fbb349440796c455c775bee09bed0310b125cd271a91a8c1a3d511dbc82e101ee2bc685f34978711ab06b1be5e0fa1bd63f3a5fae67790ddb77b4450eabf866d854d1a61382cb9388d4a2dae6792a37e03eb3a81fd0d813c26ae494c853c89c46dab8647a726002d9057fb562eae9e4f23a25e35e7d0a481ef97dd24467375f988da28093fab9e6411323506ffed4d14d165a3518cff0843dd9dfd3d5f3c6abf2f26e8ae35e00049f2ad6fc4551cc911b59d986bf85d2c1a127a04ba4b20000ab57fc7552dda24d014beed89a7b3f5e60c0d26b41d3e52473853cf34c2245f90a7ed14abe43741198a001b3f495c7c03ae7ec4ea4147925ff1dcdab9fa5ca55162ed68e1935433b65cfc3464a4821f2b75c0c639c5725c13c6b0557132cd02367aab0133820b3e5c4694133ea849f4a73d05c9cc28a0447fb8d5619af40d3541a4ba4b685c7ae17038e004350d3856bdb17fcfcaa063ef624ab14b6083baa256b8c29aa338d4e61f5f0902e3c486c5886aea42ae40fd6983af44e74c298de44e0df881d96a6121a649419799a79a6fd4fd0d8221b72dbccadf176b054ea25259e39dc580a0117681f083f52cb8bf5a5218c09ab64b3a8e19cf0c13e877dc8e2417970294d2c2809010cef4ed06e201ec921b77914353c258a4c312d581352e73484eb4afa8d8e85e13ede282607aaadb94990981591f9b0565f459c472c7a74c1a635b474d22dc9922ae977ad450fe243e2616d9fb3c5e17cfe86d34a59fcdd38428b8ff6667fa5b0b0f0bd4e2661fea33a87cadb9d0858e8f9aec6
Verify Fail
Layer Decrypt fail!
Packet: 754434ceca2fc82c06fd09f08dabb532275ef5ba07a05906acd0de4bb408d0d5d64f0e2a0605ed6e41665a18883756b0c2a6ed7337f28b8462ec3667a800acbab95024d38dd9fe8b683e6917b13ba16397c72149731ced8c74fdc2749a3c337e08673160955d8be79caa90eab1634ec4a6640c04712bbb36b4e336286ca7ba0eb038f4015bdc89f4eb8a504a1c4da20d0bd79e8295c9e443238b9a743858bd461e31085acb9830da9d3c0e07319bbfdc81078776d6b21fa56df80766d5423b494f2f151573b4bade5cf4b36e89d089b3fc61cb68a6c03c80c562adc026f1ac3a4b364b2c9a38bd22a1ccb5422a934bfd5b69a721f75822c7c30a0f9b9edc1ef9df7fc0ffae8cf89cf35a2b3151af1c2a215186a22d224b3428e48e3ad3a49e09c6fa446d1130117c29188fbbe7f297afefc0506bf81532b2de14097089fbf8a48193f300e665571c4b8c08c18297db92708a1efb5eabeeea97a38c406f56d8c6bb342e317a9a10fc4518f6e0061dec9520293bec6f5cfb8f43215742588bb161bcd1558e8e0fba39496b0ae370f697bc026e4880793581e25326e522576c5e87239e97806135c216e8fc21f1f480b1b253ac96ae94868198041cf2e43b38ba7321c8623e240864bb8a3deb230767dd47622605cfc22370fd12431662b74fb180f8b550ccbd036bb393b85ed40d63a3f7b84e825cea14665d82140b42167dedb4af3a5cd47ff042824142efd4eb5b7bc1815af7d494f2dc93fd427783e27607f2d511063451a7d197a62a2e18eb6fde13a9194501da2b5fb6ec94640b0c394c366cfd06d32f981e1382eca230525b1fc92ab5af2c33c92e10dcf53bcb1b1d7212e4f1282deb24c79938ea57134a6dc38a444c305ffee902d13f62025b0004201b54e6875efd3cc0cd0f44bafab076d4570979bbaee545a73b4f5f8780121aad43555115af6405b74903813f9488015c6ee8a03a5ec059d6b4d9517e4ec365279385e9c3d7c6847c1f930ac6e75e0fca1c2dfff6b6d124623b6f814af85bc15d86fae8d4cfdf8dba21766a62989ff5a3cfeb0818836ca6139c9a2cafc94f054f01845307ad0476b356d90be42e1135ad928dff985ebeff60c01d10d3c8066ff8d58381b836f5ab09ec39560d5a8d358e606c60e89e919f20564600e17f834aabbf6946d9bd9bb6a057f9296098fd8e4a617577b717ef01f54b557bd014105e51e592c881e31a14293c40ad2f6b6c9a7c6149c333198b2b6917758cd3f5b77838f33f54c6bcda5492e175bede66cbfc6798d874085134ba80bf6c3d63b0c6c17ef61ee0e953b4536c36ff3404094a39334f6aed1c7956fdc08ab0ca9d95d5c514e9cda734974eca6ab52cc8022eddda708342de72d6676d55220db5ced95477ae740f2e06155ec08a9a902b0891121fc96765a3708582aeb92278fdba23fcf5401a76977e94a6a356840a3b4ad356713eb39a3411fdde8ccca2468e1cd6eeb87577c58a9cc834aac22b433d32301496e8c4c655d183cb850f8a6dd067cf958551b19ee3f4884a951a00962b1cc655a8ccedbafc7fe2d8326b650f5e94e1fa8dd52e55ac7857a2cef3bf91a41cfaba770e491c267547d5462a55152c5a0dfdb400a07cea97542f92500a1e30050e1df3408061eac5485db8b51468cdc029ec314835e3295277b54a60f5bcf2f232b218f13843c2403c632035618f3d9397d05e463ddbe3f9cebc29515c3c4fa07f908c5bdc4836a291166d0220af2525ddaa318b81107c3ef62e00bba5eccbc3c88e5a615e2a34d6e9b473e10cafb1e4b8d675f793c5c4aadf3ac519a123fb124164a4507711362d646da98d6da304ca1c03a12c389f40fc04b579c0030b27d58bb1546d402ae02f0dab9cf9b83657dba1364ac3c1734fda1a583100bbb40e6ffd0819ad334e4ea0defd3cae63892e611a412a57208c188c72f9aa2ea271102bb516c01722b06b99eb0666077ec137304fb16c1a1e90f014d33fc99c528e239c1cda3694808e56bd88d109936f6b8e5e4d84015cd421632cfa31bb61c0
Verify Fail
Layer Decrypt fail!
Packet: b6a9129a954fd2e141abed21043a4cfd7f3faec30612730de2ab77be55021be98eec057ff12c2bf7c7845bdf651a533e52238d1763a87bf45c07dfe565b7bdeafbf613cf1af781294c62ef84e0d43d11f79fa6db0a915e5bd92e652553ba95e4d9c0e64ad56cdbd934367937c4562f6efd33abd34cd75ba60172c165b343cd5ce74faec39add136007360b0238606f6c26b8cb5770e839502fda74ad3f56aeef0cd1772b2fd73c6e4a8c18da47344e0fcfaf76497bea5d97fcc29466754cc54ff903b31d2b2a7e5090f558c7f46a9992757a9dbba442d312fd47fe6364d5334e31c5bfa3477d00041ddfc4617f221ed6cbd25d650fe810d321b1b457c6583918caba566e22ec8ba255868a4e3f2ac8b51dc12edd44fb2c856951537b0e57a0f616e4e3a8593d1f22ad7fb155cac909f2caae7b0debe137f3b57187cfcf9a1f5cc244298349578250d5bd9660b0ac701e931de92efe374dc69e7c42dca032a424575c5bc10c9f365e4f1a8a69149005271f1abc3fa81d8ecd4281d87cd9fa4cb4797c1ee4db74b8d7d12b104ac2c135ffb6a7ec161b0c711ab70acf856579b44e05089edc1b2b097310de738b6d95b2546bd3227933958911fcc3c1dfd74b7872c313c58291e772cb4e5746ba4a545bcc5c476043a8eb82dde9bc74d2f76da0a468bd8d4ca261089ee98960a7fce36c90b6d2f1c7aaffc66bf1739c28fd09373511e22c9bef6443e12f5663c98e820fa99b2ef441352c5caf0307ed12f0c29d1641b41ea62819b31252f62ce54a6762ddfd5dc7dfcdbd6753935989683d6cefc725c65318c218c0b9f120a41d2249145ab0eae865a633382f129f4bddddfc6b6f07129df19df4f8f5bf25797c9721d72c7789544ba3e91eb9fa37261a05899380202e506c53054af8e36643f260ac026092bca22911c9b0166d86e43351934241598eca3875294e1c00e36f21679898a48a6892723974de60259f13b355209280fa7128701b8bdedb0b90e97777dcb48dcded46605a72ce15faafd6d999ff6ad9df813656cc7413c3634268dff98a97a086bc6e88156321d50adfe3f85762da675861fd6cc8e9e3141a06f24ae427f1239c20651e9ce5e76a77a840fefd9e378ca02fa0f16af2962ba06c9b0669973ba785f9622f57512484deb69c32270e806746e36aa059be4ace3da953a83d31fa6035892ee9a73e88df00edbed7bda01570421574d7f72567e34b3f63299de3c29d203cc1f6a60abb7d3b99d393087fcd2bf367e73d0ced0860c04ee90f53b4776861d8a13d13db302a25b6a8d2e4cbc7417e8489436f90ce92d6e136458dcfcf54d31f6ae99b862bccada2d7d26a0974d9a7b714cd136a29bfb2e13fada36b6aabef347c1ae316834a525e8ac2784dd1759cd6694fd18c189a65129a82c66aa271c04382e5af6fb86d381bf92a33c02716625bb4ed931774930c3e284131603e5d413b7c7d0bb6c1f70f1a2e744d6cdc495ef8b7cdb0585c8b881dc7d8d980081c1331178e3c565504dbd3237db666cfbeda07a253900c49abb95d3db558f7748df35fba0a4c57daf30dc7a60b4ac19a453f9e7144b950778ea80df95093fb4f24f979d178ba3ddf6c2d8d0c22a5ef8d854f61d21cea923add5bbaf6551491412a1cd29cfd1873f1664fedd009b1be09628b38e1a06db8f98eb58079b5cc4f8118c170f21021d446eb88425ecf666e13b40291c48eb3617491da650064f7286a2b60e72d43b80e2f621691a5687aaa4869c63a7d5f181387ccdfae88bf0b44699943a7a9ef3baa62ef2201fe73f850d61ecab9ba0027dd1b9b5d2183c5487703fa1df746d3abdc419f2f87018f130286afbce4acbbf0690c8cea616c982d012504b2f2faf72a19952d782bc1be4e6845d31a46f200783b2fadb8d43509846173ffe8f7ca6a10967c664c9ffbfc2ca93c852ffa7146ec5f20ec6e0a50109cad4c190643387294f240818eaf3af761a8957a986f9f4b4b2022a38bda3511942b4aeff82ef7f28a6542de69cadd3b482be16c5f2f59462d323cc71287faeda3a13f68ece104aa91506e901962b7c1881660831f3c71ae6f11eaf4f2e111d997057bcfd3b7a94b4492a1011b34827c01a3737dd297652222482d311a6c37aa287f25cde9e6476d3ecf23ce17aa4ac208461dd4552f1849bbd934ce4433f372c213b0ae3b876f099bb289852c6d844d71517a138ad526beb549a6d09fe72a3f
undefined:1
{"characteristics":[{"aid":2,"iid":12,"ev":true},{"aid":2,"iid":15,"ev":true},{"aid":3,"iid":12,"ev":true},{"aid":3,"iid":15,"ev":true},{"aid":4,"iid":12,"ev":true},{"aid":4,"iid":15,"ev":true},{"aid":5,"iid":12,"ev":true},{"aid":5,"iid":15,"ev":true},{"aid":6,"iid":12,"ev":true},{"aid":6,"iid":15,"ev":true},{"aid":7,"iid":12,"ev":true},{"aid":7,"iid":15,"ev":true},{"aid":8,"iid":14,"ev":true},{"aid":8,"iid":17,"ev":true},{"aid":9,"iid":14,"ev":true},{"aid":9,"iid":17,"ev":true},{"aid":10,"iid":14,"ev":true},{"aid":10,"iid":17,"ev":true},{"aid":11,"iid":11,"ev":true},{"aid":11,"iid":14,"ev":true},{"aid":12,"iid":11,"ev":true},{"aid":12,"iid":14,"ev":true},{"aid":13,"iid":13,"ev":true},{"aid":13,"iid":16,"ev":true},{"aid":14,"iid":13,"ev":true},{"aid":14,"iid":16,"ev":true},{"aid":15,"iid":13,"ev":true},{"aid":15,"iid":16,"ev":true},{"aid":16,"iid":13,"ev":true},{"aid":16,"iid":16,"ev":t

SyntaxError: Unexpected token

**Comment by KhaosT** [comment]
Are you on latest homebridge? This should already be fixed.

Best Wishes,
Tian

**Comment by thoduh** [comment]
0.4.11

**Comment by KhaosT** [comment]
and HAP-NodeJS version is at least 0.4.14?

**Comment by thoduh** [comment]
Where can i find this?
NPM 4.1.2
Node v7.0.0

**Comment by KhaosT** [comment]
Try this? ``npm list -g hap-nodejs``

**Comment by thoduh** [comment]
Last login: Tue Mar 14 19:29:29 on ttys001
MacMini-LAN:~ MacMini$ killall homebridge
MacMini-LAN:~ MacMini$ npm list -g hab-nodejs
/usr/local/lib
└── (empty)

**Comment by KhaosT** [comment]
... you typed the name wrong

**Comment by thoduh** [comment]
MacMini-LAN:~ MacMini$ npm list -g hap-nodejs
/usr/local/lib
└─┬ homebridge@0.4.16
  └── hap-nodejs@0.4.13  invalid

npm ERR! invalid: hap-nodejs@0.4.13 /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs

**Comment by KhaosT** [comment]
so it's 0.4.13 ... should work fine ... Is this a one time thing or does this keep happening to you?

**Comment by thoduh** [comment]
Always comes after a few days. Will testing homebridge v 0.4.16...

**Comment by KhaosT** [comment]
Huh I'm not really sure, if it's an issue in program it should always happen instead of only happen after a few days.

**Comment by thoduh** [comment]
When it occurs again, I sign up again. Thank you
