### ISSUE TITLE
Everything works perfectly, but after approximately 5 to 30 mins, HomeKit/MyHome Can No Longer Get a Response.  It appears that iPhone is Spontaneously sending a muting even notification which is closing down the Server.

### ISSUE THREAD

**Issue by thetom89** [nfarina/homebridge#1203]
Hi

I have been able to install home bridge (and an associated LifX plugin), and at first they work perfectly across all of my devices.

After a variable amount of time, (as little as five minutes and at most a half an hour), My Home simply gets no response from any of my devices (LifX lights).  I've tried multiple reinstallations to no effect.

I wondered if anyone might have an idea as to how to fix this?
![fullsizeoutput_4f13](https://cloud.githubusercontent.com/assets/26391824/23918929/c49e73fa-08ec-11e7-830e-91f642539ccb.jpeg)

**Comment by thetom89** [comment]
I deleted and replaced the persist file, and changed the username back and then forth and now it works again.  I suspect that I'll have the same problem in the next half an hour.

**Comment by thetom89** [comment]
Yup, same problem again.  Why won't they respond?

**Comment by NorthernMan54** [comment]
Have you isolated the problem to a particular component?

Phone to homebridge

Homebridge itself

The plugin

Or plugin to device?

There is a lot of complexity in the connectivity, with a lot of variables.   Looking at the homebridge log may help break it down to a component, either upstream or downstream.

**Comment by thetom89** [comment]
Hi NorthernMan54

Thanks for your reply.

I haven't.  Homebridge appears to still be running in Terminal, and its process is still active in activity monitor.

How do I access the home bridge log?

**Comment by thetom89** [comment]
When I killall homebridge and then restart it again with homebridge, it immediately reconnects.

**Comment by NorthernMan54** [comment]
If you running in a terminal, then the terminal would have the regular logging output.  I would expect that if it is homebridge, it would have a verbose message when it fails.

If that isn't conclusive, a more verbose debug log may be required.

**Comment by thetom89** [comment]
Hi NorthernMan54

Thanks for your advice.

Nothing happens on Terminal when it fails, Terminal seems to think that it is still running fine.  Actually, when I switch off the lights at the wall, Terminal registers that they have gone offline, even though HomeKit no longer recognises them.  I suppose I can conclude that it's rather a problem with HomeKit talking to homebridge?

Would you have any further advice?

**Comment by NorthernMan54** [comment]
That sounds very likely.   You can install an app called Fing onto your phone and use it to determine if you have a network connectivity issue between your phone and homebridge.   You may also want to take a look at your home network to see if something isn’t working right.

**Comment by thetom89** [comment]
Hi

I've managed to run a full debug on the problem.

Spontaneously, and in coincidence with the onset of the lack of response from HomeKit, the following script appears in Terminal:

 EventedHTTPServer [::ffff:xxx.xxx.x.x4] Muting event '2.10' notification for this connection since it originated here. +60ms
  EventedHTTPServer [::ffff:xxx.xxx.x.x4] HTTP Response is finished +0ms
  EventedHTTPServer [::ffff:xxx.xxx.x.x4] Client connection closed +4m
  EventedHTTPServer [::ffff:xxx.xxx.x.x4] HTTP connection was closed +1ms
  EventedHTTPServer [::ffff:xxx.xxx.x.x4] HTTP server was closed +1ms

My iPhone (I've redacted the full IP) seems to just decide to send a muting event leading to the server closing.  Would anyone have an idea how one might fix this?

**Comment by NorthernMan54** [comment]
Your symptoms are very similar to issue 1196, which was a network router issue.

I would recommend looking into connectivity issues between your phone and homebridge.  This doesn't appear to be a homebridge issue.

**Comment by thetom89** [comment]
Hi NorthernMan54

Could you please link me to 1196, I can't seem to locate it.

**Comment by thetom89** [comment]
Hi NorthernMan54

I managed to find it, it had been closed.  Thanks for your help.  I will try and pursue this line.

**Comment by thetom89** [comment]
Hi NorthernMan54

When connected directly with a LAN cable, it works beautifully.
I just need to get it on to a raspberry pi now.
