### ISSUE TITLE
Plugin request: Raspberry pi gpio thermostat

### ISSUE THREAD

**Issue by dinosaurer** [nfarina/homebridge#1204]
Hello. My house have been running on homebridge for years now. It's great! Wondering if someone can help me out. Making a plugin combining gpio temperature sensor and a gpio relay as actuator turning the heater on or off. Thermostat service?

**Comment by cflurin** [comment]
One easy solution would be to use an esp8266 with esp easy and homebridge-mqtt.
Alternatively you might start with homebridge-mvc.

https://www.letscontrolit.com/wiki/index.php/ESPEasy
https://github.com/cflurin/homebridge-mqtt
https://github.com/cflurin/homebridge-mvc
