### ISSUE TITLE
dns service error

### ISSUE THREAD

**Issue by Anuj79** [nfarina/homebridge#1205]
hi, 
 i am trying to run homebridge in docker on a qnap system 
https://hub.docker.com/r/marcoraddatz/homebridge

the docker is crashing on this error. i checked and following daemons were installed but its still giving me this error .. any thoughts on what i can do 
avahi-daemon is already the newest version.
libavahi-compat-libdnssd-dev is already the newest version.

Error: dns service error: unknown
    at Error (native)
    at new Advertisement (/usr/lib/node_modules/homebridge/node_modules/mdns/lib/advertisement.js:56:10)
    at Object.create [as createAdvertisement] (/usr/lib/node_modules/homebridge/node_modules/mdns/lib/advertisement.js:64:10)
    at Advertiser.startAdvertising (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Advertiser.js:43:30)
    at Bridge.Accessory._onListening (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:539:20)
    at emitOne (events.js:96:13)
    at HAPServer.emit (events.js:188:7)
    at HAPServer._onListening (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:190:8)
    at emitOne (events.js:96:13)
    at EventedHTTPServer.emit (events.js:188:7)

**Comment by benzman81** [comment]
On my synology i had this issue

**Comment by benzman81** [comment]
On my synology i had this issue, too. You need to runnthe image with --net=host

**Comment by Anuj79** [comment]
thats what i am using  but still having that issue 
docker run -d --name HomeBridge --restart=always --net=host -p 51826:51826 -v /share/CACHEDEV1_DATA/docker/homebridge:/root/.homebridge marcoraddatz/homebridge:latest

i was trying to get the ip address before it crashes and weirdly its giving the dns server/ router address as its ip address using this command 
root@MyNAS:/usr/src/app# /sbin/ip route|awk '/default/ { print $3 }'
192.168.1.90
right now i haven't configured anything on the virtual switch so the ip address should be 10.0.3.0-254 range which is the default. and when i set up another container , ubuntu the ip address is correctly defined.

**Comment by Anuj79** [comment]
i tried to see in the var/log to see if can pick up anything from the logs but doesn't seem the files are being updated. 
'
root@MyNAS:/var/log# ls -lrt
total 364
-rw-rw-r--+ 11 root utmp      0 Jun  8  2016 wtmp
-rw-rw----+ 11 root utmp      0 Jun  8  2016 btmp
-rw-r-----+ 11 root adm      31 Jun  8  2016 dmesg
-rw-r--r--+ 11 root root  49020 Jun  8  2016 bootstrap.log
-rw-r--r--+  5 root root    751 Feb 26 16:27 fontconfig.log
-rw-rw-r--+  5 root utmp  30952 Feb 26 16:27 lastlog
-rw-r--r--+  5 root root   3392 Feb 26 16:27 faillog
-rw-r--r--+  5 root root 249512 Feb 26 16:27 dpkg.log
-rw-r--r--+  5 root root  11485 Feb 26 16:27 alternatives.log
drwxr-xr-x+  2 root root   4096 Mar 12 23:23 apt
drwxr-xr-x+  2 root root   4096 Mar 12 23:23 fsck
root@MyNAS:/var/log# ls -lrt[/share/CACHEDEV1_DATA/docker] #

**Comment by Anuj79** [comment]
it sees like the the avahi-daemon service is not starting.. not sure what the error is 
> [FAIL] Starting Avahi mDNS/DNS-SD Daemon: avahi-daemon failed
