### ISSUE TITLE
homebridge fails to start module did not self register

### ISSUE THREAD

**Issue by jerryrw** [nfarina/homebridge#1207]
Running nodejs v7.7.3 on Linux Mint 17.3 (Ubuntu 14.04)

seems to install fine with no errors or warnings

 on running the program either privileged or non it throws the same error.

`/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/mdns/lib/dns_sd.js:35
    throw ex;
    ^

Error: Module did not self-register.
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/mdns/lib/dns_sd.js:24:20)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
`

I have seen this error on several searches and all of the fixes presented there don't work and the others are all closed.  Have already tried uninstall and reinstall.  Checked for every suggested library update.  Still no go.

I am very much not a Node.JS guy so trouble shooting this is a bit beyond me.

**Comment by usamitysam** [comment]
I just had this problem too, but solved it.  Bottom line rerun
sudo npm install -g --unsafe-perm homebridge

It happened because I followed the default ubuntu install instruction here
https://www.npmjs.com/package/homebridge/tutorial

But the command must be old because i got 
nodejs -v
v0.10.48

Instead I ran
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -

But then I got the error you got from homebridge.  Rerunning the npm command at the top fixed the issue.

Hope it helps you

**Comment by snowdd1** [comment]
This "tutorial" is auto-generated by npm and does not help. Use the installation hints in the wiki of homebridge instead.

**Comment by unitof** [comment]
I'm getting this as well, working on my first Accessory plugin.

When I launch `homebridge`:
```bash
$ homebridge 
[7/26/2018, 7:54:26 PM] Loaded config.json with 1 accessories and 0 platforms.
[7/26/2018, 7:54:26 PM] ---
[7/26/2018, 7:54:26 PM] ====================
[7/26/2018, 7:54:26 PM] ERROR LOADING PLUGIN homebridge-inbuzzer:
[7/26/2018, 7:54:26 PM] Error: Module did not self-register.
    at Object.Module._extensions..node (module.js:678:18)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at bindings (/Users/jacob/repos/homebridge-inbuzzer/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/Users/jacob/repos/homebridge-inbuzzer/node_modules/epoll/epoll.js:1:99)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
[7/26/2018, 7:54:26 PM] ====================
[7/26/2018, 7:54:26 PM] No plugins found. See the README for information on installing plugins.
[7/26/2018, 7:54:26 PM] Loading 1 accessories...
/usr/local/lib/node_modules/homebridge/lib/api.js:64
      throw new Error("The requested accessory '" + name + "' was not registered by any plugin.");
      ^

Error: The requested accessory 'DoorBuzzer' was not registered by any plugin.
    at API.accessory (/usr/local/lib/node_modules/homebridge/lib/api.js:64:13)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:285:42)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:86:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:43:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
```

The main `export` of my accessory plugin:
```js
module.exports = function(homebridge) {
    console.log("homebridge API version: " + homebridge.version)

    // Accessory must be created from PlatformAccessory Constructor
    Accessory = homebridge.platformAccessory;

    // Service and Characteristic are from hap-nodejs
    Service = homebridge.hap.Service;
    Characteristic = homebridge.hap.Characteristic;
    UUIDGen = homebridge.hap.uuid;
    Types = homebridge.hapLegacyTypes;

    homebridge.registerAccessory('homebridge-inbuzzer', 'DoorBuzzer', DoorBuzzer);
}
```

I've tried `nvm`ing to Node 8, 9, and 10, but no luck. Currently running Node `v10.7.0`

**Comment by NorthernMan54** [comment]
In this scenario there are errors earlier on startup, related to the plugin failing to load.  Take a look there

**Comment by unitof** [comment]
What I pasted is the entire `homebridge` startup stdout (the `$ homebridge` line is me starting homebridge). Where would these earlier errors be?

**Comment by NorthernMan54** [comment]
This is from one of mine that works, do you have a function DoorBuzzer?

module.exports = function(homebridge) {
  Service = homebridge.hap.Service;
  Characteristic = homebridge.hap.Characteristic;
  FakeGatoHistoryService = require('fakegato-history')(homebridge);
  homebridge.registerAccessory("homebridge-dht", "Dht", DhtAccessory);
}

function DhtAccessory(log, config) {
  this.log = log;
  this.log("Adding Accessory");
  this.config = config;
  this.name = config.name;

**Comment by unitof** [comment]
I do.

That said, this is my first plugin and I'm having a real hard time debugging it, since none of the errors I'm getting here reference my code. I'm pasting the whole plugin as it is now below. No doubt there are other bugs in here, but the goal right now is simply to get it to register so I can continue debugging.

```
let pin

const gpio = require('onoff').Gpio;

module.exports = function(homebridge) {
    console.log("homebridge API version: " + homebridge.version)

    // Accessory must be created from PlatformAccessory Constructor
    Accessory = homebridge.platformAccessory;

    // Service and Characteristic are from hap-nodejs
    Service = homebridge.hap.Service;
    Characteristic = homebridge.hap.Characteristic;
    UUIDGen = homebridge.hap.uuid;
    Types = homebridge.hapLegacyTypes;

    homebridge.registerAccessory('homebridge-inbuzzer', 'DoorBuzzer', DoorBuzzer);
}

function DoorBuzzer(log, config) {
  this.services = [];
  
  if(!config.name) throw new Error("'name' parameter is missing for accessory " + config.type);
  if(!config.pin && !config.pins) throw new Error("'pin(s)' parameter is missing for accessory " + config.name);
  
  var infoService = new Service.AccessoryInformation();
  infoService.setCharacteristic(Characteristic.Manufacturer, 'Jacob Ford')
  infoService.setCharacteristic(Characteristic.Model, config.type)
  //infoService.setCharacteristic(Characteristic.SerialNumber, 'Raspberry');
  this.services.push(infoService)
  
  this.device = new LockMechanism
}

function LockMechanism(accesory, log, config) {
  this.log = log;
  this.pin = config.pin;
  this.inverted = config.inverted || false;
  this.duration = config.duration || false;
  
  this.gpio = new gpio(this.pin, 'out')
  this.gpio.writeSync(this.inverted ? 1 : 0) // lock
  
  this.service = new Service[config.type](config.name);
  this.target = this.service.getCharacteristic(Characteristic.LockTargetState)
    .on('set', this.setLockState.bind(this))
    .updateValue(Characteristic.LockTargetState.SECURED);
  this.state = this.service.getCharacteristic(Characteristic.LockCurrentState)
    .on('get', this.getLockState.bind(this))
    .updateValue(Characteristic.LockCurrentState.SECURED);
  
  accesory.addService(this.service);
}

LockMechanism.prototype = {
  setLockState: function(value, callback) {
    var that = this;
    var OPEN = this.inverted ? 0 : 1;
    var CLOSE = this.inverted ? 1 : 0;
    
    if(value == Characteristic.LockTargetState.UNSECURED) {
      that.gpio.writeSync(OPEN)
      this.state.updateValue(Characteristic.LockCurrentState.UNSECURED);
      callback();
      if(this.duration) {
        setTimeout(function(){
          that.gpio.writeSync(CLOSE)
          that.target.updateValue(Characteristic.LockTargetState.SECURED);
          that.state.updateValue(Characteristic.LockCurrentState.SECURED);
        }, this.duration * 1000);
      }
    } else {
      that.gpio.writeSync(OPEN)
      this.state.updateValue(Characteristic.LockCurrentState.SECURED);
      callback();
    }
  },
  
  getLockState: function(callback) {
    var state = this.gpio.readState();
    if(this.inverted)
      state = !state;
    callback(null, state ? Characteristic.LockCurrentState.UNSECURED : Characteristic.LockCurrentState.SECURED);
  }
}
```

I have a testing script in my `package.json` which runs `DEBUG=* homebridge -D -P ./`, but I've also tried running `npm I -g ./` from my plugin's root to install my `homebridge-inbuzzer` globally, then running `homebridge` as usual. Same `Module did not self-register` error either way.

Thanks @NorthernMan54.

**Comment by unitof** [comment]
Sure thing. Just pushed lastest to https://github.com/unitof/homebridge-inbuzzer/tree/onoffify. Make sure you checkout the branch `onoffify`.

**Comment by NorthernMan54** [comment]
If your on slacks homebridge channel, we can chat directly as well

**Comment by NorthernMan54** [comment]
For people googling this, the problem was with a dependent npm package gpio/epoll.  Temporarily commenting out the “require” line in the plugin for the package got past this.
