### ISSUE TITLE
Not issue, just a question

### ISSUE THREAD

**Issue by felipebraz** [nfarina/homebridge#1209]
I'm quite a newbie on Arduino, ESPs,... I'm learning now... So, sorry for these questions:

I haven't understood exactly the ideia of this project... 
I want to connect my NodemCU (wich is an home automation hub - temperature, humidity, lights,...) to the Home app of the iOS, through MQTT protocol. I have any other devices wich I want to connect at this moment. 
Is this the idea of this project?

I've installed the homebridge and homebridge-mqtt plugin on a Debian server and I believe the I've configured correctly, but on my iOS Home app nothing appears.

**Comment by snowdd1** [comment]
`homebridge` is a framework and server for hardware specific plugins. I think you got this part. If you want to see anything in a HomeKit app (such as *apple home*, *elgato eve*, or others) you need to  
- install at least one plugin (you did)
- configure that plugin (if it requires configuration, see the plugin's repository) 
- if the hardware (in your case probably the software - mqtt broker) needs configuration, do that
- start homebridge (there multiple ways depending on OS and preferences, see Wiki pages)
- add homebridge as accessory to HomeKit (home -> add -> homebridge should show up -> warning, add anyway -> enter code manually (scanning works almost never). This is called pairing just as with Bluetooth devices, but in the HomeKit apps.

Now the plugins should provide the services to homebridge, which itself bridges to HomeKit. The services should show up in the HomeKit apps. 

Some thinks to remember: 
- one homebridge instance can only be paired with one iCloud account.
- access is restricted to local LAN unless you have an Apple TV 4 (3 works for some), or an ios10 iPad configured with the same iCloud account as the *home hub* - and it's always on.

Regarding mqtt: we have an expert here @cflurin , but questions to that platform might better be posted to the homebridge-mqtt repository.

**Comment by felipebraz** [comment]
Thank you very much for your tips @snowdd1 !!!!!

I'm gonna study more... I've tried to find some tutorials or tips of using MQTT + HomeBridge but I couldn't find anything that really helped me. The most of tutorials are confusing and uses the ESP Easy (an ESP8266 custom firmware, that I really don't like).
If you or someone did it and have any tips or suggestions and can share...

But, again, thank you very much!!!

**Comment by NorthernMan54** [comment]
I took a different approach to the same problem statement, and built my own esp8266 code in Lua, and a custom plugin in homebridge to pull the data into HomeKit.  It is something you might consider as an approach.  It does require rolling up your sleeves though.

Take a look at this.

https://www.instructables.com/id/Homebridge-MCU-IOT/

**Comment by felipebraz** [comment]
Great ideia @NorthernMan54 !!

In fact the idea is really good, but I have some other stuff that uses the MQTT protocol (such as integration between NodemCUs).

But I'll keep in mind your tips to try in another opportunity.

Thanks!!
