### ISSUE TITLE
Apple TV plugin support

### ISSUE THREAD

**Issue by kapps7** [nfarina/homebridge#1210]
Wondering if there is anyway to connect the Apple TV 4th gen itself or its remote control to homebridge. I basically want to be able pass simple commands like pressing the home button or sleep.

I know that the remote control can only be paired to one device so if you pair it to the Mac then I dont think it will forward instructions to the Apple TV.

**Comment by neilgupta** [comment]
It is not possible to execute arbitrary commands on the Apple TV over WiFi. You can however use a third party IR remote to relay those commands. I would recommend getting a Logitech Harmony Hub, and use the homebridge-harmony plugin to control your Apple TV.

**Comment by tilledminds** [comment]
I don't think this is correct as both iRule and Homey can do this via software and don't require IR.

**Comment by kapps7** [comment]
> It is not possible to execute arbitrary commands on the Apple TV over WiFi.

Thats not true.

**Comment by RXM307** [comment]
Looks like the protocol has been partially reverse engineered

https://github.com/jeanregisser/mediaremotetv-protocol

http://stackoverflow.com/questions/35355807/has-anyone-reversed-engineered-the-protocol-used-by-apples-ios-remote-app-for-c

Cheers,

Anthony

**Comment by kapps7** [comment]
Can this library not be used to build a plugin to control the Apple TV
https://github.com/postlund/pyatv

**Comment by NorthernMan54** [comment]
@kappa7

Just looking at this, and the python pieces look usable to create a plugin around.  But I was thinking more about usability from the Home App.  The icon choices and functions are quite limited.  For my Yamaha stereo, I ended up mapping power and volume to a light bulb as there wasn't anything else available.  Dimming the light bulb changes the volume.

**Comment by lprhodes** [comment]
I'm starting development on this now so watch https://github.com/lprhodes/homebridge-apple-tv for updates

**Comment by kapps7** [comment]
Luke you're a legend. I can probably not do much more than test at this stage but I am ready to help. Thanks!
