### ISSUE TITLE
Homebridge connected over WIFI -> no remote over Internet??

### ISSUE THREAD

**Issue by StefanMeGit** [nfarina/homebridge#1212]
I have 4 RaspberryPis in use. Two connected over Ethernet (1 PiZero and 1 Pi3) and two over Ethernet (2 Pi3s). I can control them perfectly on my local wifi, but if i leave the house, the two homebridges connected over wifi are not responding. The two with the ethernet are working fine!

```
wlan0     IEEE 802.11bgn  ESSID:"StefanMes Netzwerk 2.4"  
          Mode:Managed  Frequency:2.427 GHz  Access Point: F0:79:59:CF:31:68   
          Bit Rate=57.7 Mb/s   Tx-Power=31 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Power Management:off
          Link Quality=62/70  Signal level=-48 dBm  
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:1  Invalid misc:0   Missed beacon:0

lo        no wireless extensions.

eth0      no wireless extensions.
```

Any idea what is the problem? Must be an issue with the wifi... maybe on pi side or on my Router (ASUS RT-AC68U)?

**Comment by maragelis** [comment]
You need a apple device (iPad or appletv) at home connected to homebridge for you to be able to remotely control homekit devices.

**Comment by StefanMeGit** [comment]
As I wrote above the other devices connected over Ethernet are working perfect remotely. Of course there is an AppleTV in my network :)

Found the problem now. I had to logout \ restart \ login in the Apple TV again. Then the remote access works fine.

Looks like he doesn't recognize the newer Wifi Bridges... . Burn thanks fir the help!

Thanks for the hole great project! I ll donate it! ( have to look where I can do this...)

**Comment by roycepope** [comment]
Thank you @StefanMeGit I was having problems but after restarting my AppleTV remote access works again

**Comment by cicciovo** [comment]
Hi, do you know if i can use a old iphone (Iphone5s) as a hub? instead an appleTv or iPad?

**Comment by ebaauw** [comment]
Yes, I know.  No, you cannot.  See https://support.apple.com/en-us/HT207057.
