### ISSUE TITLE
Raspberry Pi Install Error (Anyone Else Experiencing Down Server?)

### ISSUE THREAD

**Issue by erfinb** [nfarina/homebridge#1215]
When trying to run the command:

sudo apt-get install libavahi-compat-libdnssd-dev

I get a time our error, is there anywhere else to get this from?

0% [Connecting to mirror.sjc02.svwh.net (72.5.72.15)]

Thanks!

**Comment by KhaosT** [comment]
What error are you getting?

**Comment by erfinb** [comment]
i@OfficeHomebridge:~ $ sudo apt-get install libavahi-compat-libdnssd-dev -y
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following extra packages will be installed:
  libavahi-client-dev libavahi-common-dev libavahi-compat-libdnssd1
  libdbus-1-dev
The following NEW packages will be installed:
  libavahi-client-dev libavahi-common-dev libavahi-compat-libdnssd-dev
  libavahi-compat-libdnssd1 libdbus-1-dev
0 upgraded, 5 newly installed, 0 to remove and 0 not upgraded.
Need to get 340 kB/402 kB of archives.
After this operation, 1,160 kB of additional disk space will be used.
Err http://mirrordirector.raspbian.org/raspbian/ jessie/main libavahi-compat-libdnssd1 armhf 0.6.31-5
  Could not connect to mirror.sjc02.svwh.net:80 (72.5.72.15), connection timed out [IP: 72.5.72.15 80]
Err http://mirrordirector.raspbian.org/raspbian/ jessie/main libdbus-1-dev armhf 1.8.22-0+deb8u1
  Unable to connect to mirror.sjc02.svwh.net:http: [IP: 2606:c680:0:b:3830:34ff:fe66:6663 80]
Err http://mirrordirector.raspbian.org/raspbian/ jessie/main libavahi-client-dev armhf 0.6.31-5
  Unable to connect to mirror.sjc02.svwh.net:http: [IP: 2606:c680:0:b:3830:34ff:fe66:6663 80]
Err http://mirrordirector.raspbian.org/raspbian/ jessie/main libavahi-compat-libdnssd-dev armhf 0.6.31-5
  Unable to connect to mirror.sjc02.svwh.net:http: [IP: 2606:c680:0:b:3830:34ff:fe66:6663 80]
E: Failed to fetch http://mirrordirector.raspbian.org/raspbian/pool/main/a/avahi/libavahi-compat-libdnssd1_0.6.31-5_armhf.deb  Could not connect to mirror.sjc02.svwh.net:80 (72.5.72.15), connection timed out [IP: 72.5.72.15 80]

E: Failed to fetch http://mirrordirector.raspbian.org/raspbian/pool/main/d/dbus/libdbus-1-dev_1.8.22-0+deb8u1_armhf.deb  Unable to connect to mirror.sjc02.svwh.net:http: [IP: 2606:c680:0:b:3830:34ff:fe66:6663 80]

E: Failed to fetch http://mirrordirector.raspbian.org/raspbian/pool/main/a/avahi/libavahi-client-dev_0.6.31-5_armhf.deb  Unable to connect to mirror.sjc02.svwh.net:http: [IP: 2606:c680:0:b:3830:34ff:fe66:6663 80]

E: Failed to fetch http://mirrordirector.raspbian.org/raspbian/pool/main/a/avahi/libavahi-compat-libdnssd-dev_0.6.31-5_armhf.deb  Unable to connect to mirror.sjc02.svwh.net:http: [IP: 2606:c680:0:b:3830:34ff:fe66:6663 80]

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by KhaosT** [comment]
This has nothing to do with homebridge, your apt source is broken. Check [here](https://www.raspberrypi.org/forums/viewtopic.php?f=66&t=177783)
