### ISSUE TITLE
HTTP-API

### ISSUE THREAD

**Issue by HansWurst90** [nfarina/homebridge#1219]
Hi,
this is not an issue and I'm sorry to use this place for this question but I can't seem to find a board or  something similar to post my question.
I wanted to ask If there is a way to communicate with homebridge via Http. I'd like to be able to make request with my Pebble smartwatch. I can only find plugins that make homebridge support making own Http-Requests but I can't find anything that help making it recieve them to set states etc.
Thank's in advance.

Jan

**Comment by NorthernMan54** [comment]
Jan,

During my initial investigation into integrating Amazon Alexa into Homebridge, I wrote a some shim code from Alexa into the homebridge http API.

Take a look at the code here, and the OLD_README.  This is a working example of what you are looking for.

https://github.com/NorthernMan54/homebridge-alexa/blob/master/OLD_README.md

Please note, that since I built this, I changed my approach and have added Alexa support directly into homebridge, by modifying the hap-nodejs web server.

**Comment by HansWurst90** [comment]
Hi NorthernMan54,
thanks for the response. If I understand your code right Your using Alexa to trigger IFTTT-HTTP-Requests and Homebridge exposes the accessories. Is that correct?
Can you give me a little more info? I'm not too familiar with homebridge plugins and node.js yet.
Basically I'm looking for my accessories exposed via local URL. So I can call them with parameters like on/off for example.

**Comment by benzman81** [comment]
My plug in homebridge-http-webhooks can create various accessesories and receive http calls to switch states.

**Comment by HansWurst90** [comment]
Hi @benzman81,
that sounds promissing. I will give it try this afternoon.
I'm not sure if I understand the config, though.
How would I enable this accessory or these plattforms to be able to change them via HTTP?
```json
"accessories": [{
        "accessory": "FakeBulb",
        "name": "Test-Lampe",
        "bulb_name": "Test-Lampe"
    }]
```

```json
"platforms": [{
        "platform": "ParticleIO",
        "name": "Particle Devices",
        "access_token": "xxxxx",
        "cloud_url": "https://api.particle.io/v1/devices/",
        "devices": [{
            "name": "Particle",
            "type": "lightbulb",
            "device_id": "xxxxx",
            "function_name": "onoff",
            "args": "{STATE}"
        }]
    }, {
        "platform": "cmdSwitch2",
        "name": "CMD Switch",
        "switches": [{
            "name": "Playstation",
            "on_cmd": "ps4-waker",
            "off_cmd": "ps4-waker standby",
            "state_cmd": "ps4-waker search | grep -i '200 Ok'",
            "polling": true,
            "interval": 5,
            "manufacturer": "Sony Corporation",
            "model": "CUH-1001A",
            "serial": "XXXXXXXXXXX"
        }]
    }]
```

**Comment by benzman81** [comment]
@HansWurst90 You cant. If the plugin of the platform or accessesory does not support this, than you can not add this functionality. My plugin only works by itself, but lights are currently not supported. I would add an issue to the plugins github repository so that they add support for it.

**Comment by HansWurst90** [comment]
@benzman81 
Then I don't seem to understand it. does your plugin add "virtual" accessories?

**Comment by benzman81** [comment]
@HansWurst90 yes, it adds the ability to homebridge to add accessories to homekit for devices, that can send http calls on state change.

**Comment by NorthernMan54** [comment]
Jan,

My code example leverages homebridge's undocumented http API that is exposed with the -I option on the homebridge startup command line.  This is the same API that is used by HomeKit to discover and control your homebridge accessories.

You can explore this interface using the curl command.  Later tonight when I'm home I will post some examples.

**Comment by HansWurst90** [comment]
@NorthernMan54 allright. I'll do a little exploration 😄

**Comment by NorthernMan54** [comment]
Curl examples.  This turns off the device at aid 2 iid 9

curl -X PUT http://127.0.0.1:51826/characteristics --header "Content-Type:Application/json" --header "authorization: 031-45-154" --data "{ \"characteristics\": [{ \"aid\": 2, \"iid\": 9, \"value\": 0}] }"


This is all the accessories

curl -X PUT http://127.0.0.1:51826/accessories --header "Content-Type:Application/json" --header "authorization: 031-45-154”

**Comment by HansWurst90** [comment]
Thank you @NorthernMan54 
I found the same commands yesterday evening but couldn't figure out which `iid` I had to use.
After your comment I gave it another try and it works. Now I only have to figure out the watch side of my whole idea. 😄

**Comment by lprhodes** [comment]
@NorthernMan54 Thanks for those - using them and node-red I have a nice easy to use solution for combining Alexa-homebridge (while keeping the "official"/maintained version of homebridge and hap)

**Comment by CapoD** [comment]
Hi,
is there a possibility to access the REST API without having to allow insecure access with -I? The thing is that I would like to write a GUI application that allows my desktop computer to control stuff, but I do not want to make the Homebridge insecure.

**Comment by snowdd1** [comment]
@CapoD You want to be able to access homebridge without encryption but you don't want homebridge to be insecure 😟 ?  
That just is contradictory. The INSECURE option just does that - making the API accessible without the need for the original encryption.  
There is a new API in the pipeline that will allow the implementation of `manager` and `listener` plugins, whatever the exact definition of those will be. I assume that manager plugins will have the ability to control the state of characteristics from other plugins - and that somebody will very soon implement a web interface plugin with that new API. Some of the guy around here have already nice web interfaces for their plugins.

**Comment by CapoD** [comment]
@snowdd1 I do not see the contradiction. Maybe there is a hidden (secure) REST api or there are examples how you could implement a client that is able to access the home bridge like an iOS device. Unfortunately, I cannot find anything on this. 
But according to your answer I just have to wait until the new api is released.

**Comment by lprhodes** [comment]
I too would love to know if there was a secure option available @snowdd1. From what I can tell, the insecure argument is the only way to access the API at the moment.

**Comment by jespertheend** [comment]
@snowdd1 any update on these new plugin apis? Also where did you find out about it? I can't seem to find it anywhere.
