### ISSUE TITLE
Please add provided patch; added parameter to disables scenes, fixed issues with dimmers

### ISSUE THREAD

**Issue by EddyK69** [nfarina/homebridge#122]
platforms/Domoticz.js | 28 ++++++++++++++++++++++------
 1 file changed, 22 insertions(+), 6 deletions(-)

diff --git a/platforms/Domoticz.js b/platforms/Domoticz.js
index a9e8e72..dbd895a 100644
--- a/platforms/Domoticz.js
+++ b/platforms/Domoticz.js
@@ -8,6 +8,12 @@
 // - Added support for Scenes
 // - Sorting device names
 //
+// 24 August 2015 [Eduard Kuijt]
+// - Added usescenes parameter
+// - Fixed issue with dimmer levels; was 0-100, should be 0-16
+// - Fixed issue with switches showing as dimmers; checking SwitchType now instead of HaveDimmer
+//
+//
 // Domoticz JSON API required
 // https://www.domoticz.com/wiki/Domoticz_API/JSON_URL's#Lights_and_switches
 //
@@ -18,7 +24,8 @@
 //         "name": "Domoticz",
 //         "server": "127.0.0.1",
 //         "port": "8080",
-//         "roomid": 123 (0=no roomplan)
+//         "roomid": 123, (0=no roomplan)
+//         "usescenes": 0 (0=no, 1=yes)
 //     }
 // ],
 //
@@ -47,6 +54,10 @@ function DomoticzPlatform(log, config){
 	if (typeof config["roomid"] != 'undefined') {
 		this.roomid = config["roomid"];
 	}
+        this.usescenes  = 1;
+        if (typeof config["usescenes"] != 'undefined') {
+                this.usescenes = config["usescenes"];
+        }
 }
 
 function sortByKey(array, key) {
@@ -101,7 +112,8 @@ DomoticzPlatform.prototype = {
 						sArray.map(function(s) {
 							//only accept switches for now
 							if (typeof s.SwitchType != 'undefined') {
-								accessory = new DomoticzAccessory(that.log, that, false, s.idx, s.Name, s.HaveDimmer, s.MaxDimLevel, (s.SubType=="RGB")||(s.SubType=="RGBW"));
+								var havedimmer = (s.SwitchType == 'Dimmer')
+								accessory = new DomoticzAccessory(that.log, that, false, s.idx, s.Name, havedimmer, s.MaxDimLevel, (s.SubType=="RGB")||(s.SubType=="RGBW"));
 								foundAccessories.push(accessory);
 							}
 						})
@@ -112,25 +124,28 @@ DomoticzPlatform.prototype = {
 				}
 			});
 	    }
+            if (this.usescenes == 1) {
+
 		//Get Scenes
 		foundAccessories = [];
 		request.get({
 			url: this.urlForQuery("type=scenes"),
-	      	json: true
-	    }, function(err, response, json) {
+		      	json: true
+		    }, function(err, response, json) {
 			if (!err && response.statusCode == 200) {
 				if (json['result'] != undefined) {
 					var sArray=sortByKey(json['result'],"Name");
 					sArray.map(function(s) {
 						accessory = new DomoticzAccessory(that.log, that, true, s.idx, s.Name, false, 0, false);
 						foundAccessories.push(accessory);
-	          		})
+	          			})
 				}
 				callback(foundAccessories);
 			} else {
 				that.log("There was a problem connecting to Domoticz.");
-	      	}
+	      		}
 		});
+            }
 	}
 }
 
@@ -158,6 +173,7 @@ DomoticzAccessory.prototype = {
 				url = this.platform.urlForQuery("type=command&param=setcolbrightnessvalue&idx=" + this.idx + "&hue=" + value + "&brightness=100" + "&iswhite=false");
 			}
 			else if (c == "setLevel") {
+				value = Math.round((value / 100) * 15)
 				url = this.platform.urlForQuery("type=command&param=switchlight&idx=" + this.idx + "&switchcmd=Set%20Level&level=" + value);
 			}
 			else if (value != undefined) {

**Comment by nfarina** [comment]
Could you make a PR with your suggested edits? https://help.github.com/articles/using-pull-requests/

**Comment by EddyK69** [comment]
Hi,

I’m pretty new to GitHub - did not made any pull request before, so i must find out how to do this using TortoiseGit…




Op 24 aug. 2015, om 17:54 heeft Nick Farina <notifications@github.com <mailto:notifications@github.com>> het volgende geschreven:

Could you make a PR with your suggested edits? https://help.github.com/articles/using-pull-requests/ <https://help.github.com/articles/using-pull-requests/>

**Comment by EddyK69** [comment]
Made a pull-request which was already merged :D
