### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by ryan-peters** [nfarina/homebridge#1220]
Homebridge was working correctly, but after a restart I am experiencing issues I cannot resolve. It seems to run correctly initially. However, after it loads, it presents me with 

    (node:5973) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): SyntaxError: Unexpected token < in JSON at position 0
    (node:5973) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I have tried re-installing Homebridge to no avail.

**Comment by KhaosT** [comment]
This is an error from one of your plugin ... not from homebridge itself.

**Comment by mrose17** [comment]
@KhaosT - do you think it might be worthwhile for us to add a https://nodejs.org/api/process.html#process_event_unhandledrejection handler to homebridge in order to make it easier for folks to identify which plugin is misbehaving?

**Comment by intrepidsilence** [comment]
Right now it is impossible to tell which plugin is generating this error. Can something be added to make it more obvious?

**Comment by NorthernMan54** [comment]
@intrepidsilence this is a closed issue from years ago, please open a new issue and include a detailed log file showing the error and the diagnostics around it.   Please keep in mind that this will likely be a plugin issue and the issue needs to be ultimately opened there
