### ISSUE TITLE
Find my Friends integration

### ISSUE THREAD

**Issue by kapps7** [nfarina/homebridge#1223]
I am wildly guessing the answer maybe no ;)

Is it possible to integrate Find my Friends notifications within homebridge ?
Thanks

**Comment by MystK** [comment]
What do you mean? Do other homekit compatible applications have Find my Friends integration built in? Do you have an example?

**Comment by AppleTechy** [comment]
@kapps7 Please elaborate. If you are talking about geofencing that would need to be done through whichever homekit app you are using to control Homekit
