### ISSUE TITLE
Integrate lights to Flash as an action

### ISSUE THREAD

**Issue by kapps7** [nfarina/homebridge#1225]
Is there a way to make a connected light flash as an action in response to  a trigger such as a sensor action ?

I guess one way is for it to trigger an  applescript but I can't see a native way within Homekit .All the scenes and light accessories only turn the light off or on.

**Comment by snowdd1** [comment]
That's right. You would need to create your own plugin to handle that, or use a server side script that is called by a plugin.

**Comment by kapps7** [comment]
Ok will do thanks. I thought it would be a common request. Maybe its a feature Apple will add down the track.
