### ISSUE TITLE
Accessories Reachability in Dynamic Platforms Plugins

### ISSUE THREAD

**Issue by raidolo** [nfarina/homebridge#1226]
Hi all,

I've developed a new platform plugin and I'm playing a bit with dynamic platforms. 
I have some problems understanding why, even if I can update the accessories reachability to false, on the iOS Home App nothing changes. My Accesories are always available and the commands runs as usual. Right now I have just a Switch service in my Pugin and I've debugged my functions deep in the HAP classes too, and I'm sure that the HAP updateReachability() function is correctly called and the reachable attribute is modified as intended. 
Am I missing something? What's the point in changing the reachable attribute of an accessory?

Thanks in advance...

**Comment by snowdd1** [comment]
As far as I understood it is more or less a convenience feature: in my plugin when I change reachability to false it shows the service as unreachable in Home app, but if you tap it, it tries to trigger the action anyway. So it's not a mean to block access to the accessory, if that was your intention. 

The only thing I do (and I think I copied it from the sample) with reachability is to set all devices to unreachable during initial config (when they are read from cache) https://github.com/snowdd1/homebridge-knx/blob/master/index.js#L156 and later, if they are properly identified to match an existing device from my platforms own config file and bound to an implementation, set to true https://github.com/snowdd1/homebridge-knx/blob/master/lib/knxdevice.js#L120

I hope that helps.

**Comment by cflurin** [comment]
It depends on the iOS app. Eve detects the reachability, Home doesn't.
The only solution I've found is to send back an error in the get function:

Have a look here:
https://github.com/cflurin/homebridge-mvc/blob/master/lib/accessory.js#L225
```js
  if (this.reachable) {
      ...
    callback(null, value);
  } else {
    callback("no_response");
  }
```

**Comment by raidolo** [comment]
Thanks cflurin, that's exactly what I was looking for! Really appreciated.
