### ISSUE TITLE
Siri (italian) wrong answer when turn on the switch

### ISSUE THREAD

**Issue by zonasoluzioni** [nfarina/homebridge#1228]
Hi, a few days ago, I finally installed and configured the homebridge platform.
After the first check, I proceed to install the "homebridge-cmdswitch2" with success...

Success, yes, but when I ask at Siri to turn on the switch named "luci garage" (garage lights in english) the answer is:

    OK, le luci garage è **masculine**

Instead of: OK, le luci garage è acceso

I have tried to turn off the switch with Siri and the answer is correct (OK, le luci garage è spento), and finally I tried to change the Siri language to English to make other test, and the answer on toogle switch is correct!

Have you got any idea how to solve it?

I' m attaching some screenshots to demonstrate the issue.

Thanks

In italian (the first image is the wrong one)
![unadjustednonraw_thumb_808](https://cloud.githubusercontent.com/assets/26680135/24326760/1e4d6696-11b6-11e7-85b4-8066ba2f3ddd.jpg)
![unadjustednonraw_thumb_809](https://cloud.githubusercontent.com/assets/26680135/24326759/1e4a2eb8-11b6-11e7-8a36-4a6d23e040cc.jpg)

In English
![unadjustednonraw_thumb_80a](https://cloud.githubusercontent.com/assets/26680135/24326757/1e1d5834-11b6-11e7-811d-f6680203caea.jpg)
![unadjustednonraw_thumb_80b](https://cloud.githubusercontent.com/assets/26680135/24326758/1e4604d2-11b6-11e7-94ee-9ad67f0037a4.jpg)

**Comment by astrojetson8** [comment]
Looks like Siri Italian cousin doesn't understand correct Italian?

**Comment by zonasoluzioni** [comment]
it's the idea.
the command is well pronounced (pronounced the same in English), but when you turn on / turn / open etc. responds with a word that might seem (risking a literal translation):

ok, the light is STRONG

within the program, there are special settings that impact Siri answers?

Thanks

**Comment by KhaosT** [comment]
Not really, those response are generated by Apple from server side. You can probably contact Apple Support and report the issue.

**Comment by BonRm** [comment]
me had the same answer a couple of days ago too and was not  thinking was an issue but just Siri trying to be smart/cool with some sentences.

**Comment by lorenzo999** [comment]
Same issue, something went wrong when translating this sentence. :)

**Comment by githubberboy** [comment]
Buongiorno Zonasoluzioni, ti contatto riguardo il problema con Siri e la sua risposta "masculine" alla richiesta di attivazione degli switch in homekit. Condivido anche il tuo pensiero riguardo la mancanza di un feedback sul reale stato dei relé. Mi chiedevo se tu avessi risolto anche solo uno di questi problemi, proprio adesso sto per fare un hard reset dell'iPhone perchè non so più dove sbattere la testa, dal momento che ha funzionato correttamente per una settimana prima di iniziare a dare i numeri. Grazie!
