### ISSUE TITLE
Add HAP-NodeJS accessory files

### ISSUE THREAD

**Issue by legotheboss** [nfarina/homebridge#1229]
Is there any way to just add existing HAP-NodeJS accessory files to homebridge? Can we drag and drop them into .homebridge/accessories or is there no way possible?

**Comment by jat80** [comment]
I too would like to know if there is an easy way of doing this.

**Comment by snowdd1** [comment]
There is no "easy" way. You would need to write a plugin that can load these "configuration free" accessories and returns them to homebridge in the expected way.  
However, for any accessory that's any good I would recommend reprogramming it into a proper homebridge plugin. You gain configuration support and a great way of sharing your plugins via npm.
