### ISSUE TITLE
Homebridge server not starting with Domoticz platform

### ISSUE THREAD

**Issue by rhannink** [nfarina/homebridge#123]
Hello,

I installed Node.js and homebridge on a Raspberry Pi. I have changed the config.son to:

```json
{
    "description": "Configuration file for Domoticz platform.",
    "platforms": [
        {
            "platform": "Domoticz",
            "name": "Domoticz",
            "server": "192.168.1.101",
            "port": "8080"
        }
    ],
    "accessories": [
    ]
}
```

When I now start de Homebridge server I get:
```nodejs
pi@raspberrypi ~/homebridge $ npm run start

> homebridge@0.1.1 start /home/pi/homebridge
> DEBUG=* node app.js || true

*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
Starting HomeBridge server...
_____________________________________________________________________
IMPORTANT: Homebridge is in the middle of some big changes.
           Read more about it here:
           https://github.com/nfarina/homebridge/wiki/Migration-Guide
_____________________________________________________________________

Loading 1 platforms...
[Domoticz] Initializing Domoticz platform...
[Domoticz] Fetching Domoticz lights and switches...
Loading 0 accessories...
[Domoticz] Initializing device with name Woonkamer...
[Domoticz] Loaded services for Woonkamer
  EventedHTTPServer Server listening on port 51826 +0ms
[Domoticz] Initializing device with name Woonkamer...
[Domoticz] Loaded services for Woonkamer
/home/pi/homebridge/node_modules/HAP-NodeJS/lib/Accessory.js:159
      throw new Error("Cannot add a bridged Accessory with the same UUID as an
            ^
Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 2464e1f8-1e93-4e56-ae1f-a56e1ae086ae
    at Bridge.Accessory.addBridgedAccessory (/home/pi/homebridge/node_modules/HAP-NodeJS/lib/Accessory.js:159:13)
    at /home/pi/homebridge/app.js:145:26
    at Request._callback (/home/pi/homebridge/platforms/Domoticz.js:129:5)
    at Request.self.callback (/home/pi/homebridge/node_modules/request/request.js:373:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/home/pi/homebridge/node_modules/request/request.js:1318:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/home/pi/homebridge/node_modules/request/request.js:1266:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
```

Anyone any idea what Iam doing wrong ?

With kind regards,

Remco Hannink

**Comment by nfarina** [comment]
I believe this is happening because it is trying to add two devices with the same name "Woonkamer". Are those different devices?

**Comment by rhannink** [comment]
Hello,

There's only one device in Domoticz and it is called Woonkamer (living room). When I add a second device called test, it behaves the same. Its adds both devices successful and then it starts adding both devices again with the same error (id already used).

Somehow it reads all devices again from Domoticz but i have no idea why.

Regards,

Remco

**Comment by gerard33** [comment]
I have the same "Cannot add a bridged Accessory with the same UUID as an..." error.
When I was using a previous version, this was working okay.

Also when I only add one device in the room that I am loading, the error is still there.

**Comment by nfarina** [comment]
Could you try PR #125? I can't actually test this myself (not owning this hardware) but I did notice some incorrect async callback behavior in `accessories()` - it was calling the callback more than once which is not allowed.

**Comment by rhannink** [comment]
nfarina,

Thanks for the (very) fast respons. I replaced Domoticz.js by he new version.
In Domoticz I have defined one light switch (woonkamer). When I start Homebridge I get:

```
Loading 1 platforms...
[Domoticz] Initializing Domoticz platform...
[Domoticz] Fetching Domoticz lights and switches...
Loading 0 accessories...
[Domoticz] Initializing device with name Woonkamer...
[Domoticz] Loaded services for Woonkamer
  EventedHTTPServer Server listening on port 51826 +0ms
```

Is this correct? I see 0 accessories while I would expect one (woonkamer) ?

regards,

Remco

**Comment by nfarina** [comment]
Yes it's a bit confusing but the "Loading 0 accessories..." refers to the array of manually-entered `accessories` in config.json (as opposed to `platforms`).

**Comment by gerard33** [comment]
Thanks! The fix in Domoticz.js works :+1:

**Comment by nfarina** [comment]
Awesome! :dancers:

**Comment by rhannink** [comment]
Yeah,

Works now, I see my Domoticz lamps in other Homekit apps and I can control them via Siri. Very cool, even my wife was impressed ;-)
There is now another issue with switch/dimmer from domoticz, but I will open a new issue for that

Thanks for the great work and support

Remco

**Comment by midevit** [comment]
Hi,
this is my problem :(((

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'start' ]
2 info using npm@2.14.7
3 info using node@v4.2.1
4 verbose stack Error: missing script: start
4 verbose stack     at run (/usr/local/lib/node_modules/npm/lib/run-script.js:142:19)
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/run-script.js:58:5
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:345:5
4 verbose stack     at handleExists (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:318:20)
4 verbose stack     at FSReqWrap.cb [as oncomplete] (fs.js:212:19)
5 verbose cwd /home/pi/homebridge
6 error Linux 4.1.19-v7+
7 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
8 error node v4.2.1
9 error npm  v2.14.7
10 error missing script: start
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
