### ISSUE TITLE
Error starting homebridge on reboot

### ISSUE THREAD

**Issue by DinRigtigeFar** [nfarina/homebridge#1230]
Hi
When I try to set up homebridge to start on bootup (Raspberry Pi running latest raspbian) I get the following error:
/usr/lib/node_modules/homebridge/node_modules/mkdirp/index.js:74
raspberrypi homebridge[10978]: throw err0;
raspberrypi homebridge[10978]: ^
aspberrypi homebridge[10978]: Error: EACCES: permission denied, mkdir '/var/lib/homebridge'
raspberrypi homebridge[10978]: at Error (native)
aspberrypi homebridge[10978]: at Object.fs.mkdirSync (fs.js:922:18)
raspberrypi homebridge[10978]: at sync (/usr/lib/node_modules/homebridge/node_modules/mkdirp/index.js:55:12)
raspberrypi homebridge[10978]: at Function.sync (/usr/lib/node_modules/homebridge/node_modules/mkdirp/index.js:61:24)
raspberrypi homebridge[10978]: at Object.parseDirSync (/usr/lib/node_modules/homebridge/node_modules/node-persist/local-storage.js:615:20)
raspberrypi homebridge[10978]: at Object.parseDataDirSync (/usr/lib/node_modules/homebridge/node_modules/node-persist/local-storage.js:545:21)
raspberrypi homebridge[10978]: at Object.initSync (/usr/lib/node_modules/homebridge/node_modules/node-persist/local-storage.js:145:14)
raspberrypi homebridge[10978]: at Object.nodePersist.initSync (/usr/lib/node_modules/homebridge/node_modules/node-persist/node-persist.js:41:29)
raspberrypi homebridge[10978]: at Object.init (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/index.js:29:13)
raspberrypi homebridge[10978]: at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:24:7)
raspberrypi systemd[1]: homebridge.service: main process exited, code=exited, status=1/FAILURE
raspberrypi systemd[1]: Unit homebridge.service entered failed state.

I already have a homebridge directory in the specified path so I don't need a new. Otherwise I think it may just be a permission issue, but I'm fairly new to the Pi so I don't know how to fix it.
Any help is appreciated.

Thanks in advance

**Comment by snowdd1** [comment]
Its a permission issue.  

Please post your *homebridge.service file* and the result of `ls -ahl /var/lib/homebridge `

**Comment by DinRigtigeFar** [comment]
ls -ahl /var/lib/homebridge
total 20K
drwxr-xr-x  4 homebridge homebridge 4,0K mar 27 22:13 .
drwxr-xr-x 49 root       root       4,0K mar 27 21:59 ..
drwxr-xr-x  2 homebridge homebridge 4,0K mar 27 14:48 accessories
-rw-r--r--  1 root       root       1,7K mar 27 22:13 config.json
drwxr-xr-x  2 homebridge homebridge 4,0K mar 27 14:48 persist

And

[Unit]
Description=Node.js HomeKit Server
After=syslog.target network-online.target

[Service]
Type=simple
User=homebridge
EnvironmentFile=/etc/default/homebridge
# Adapt this to your specific setup (could be /usr/bin/homebridge)
# See comments below for more information
ExecStart=/usr/bin/homebridge $HOMEBRIDGE_OPTS
Restart=on-failure
RestartSec=10
KillMode=process

[Install]
WantedBy=multi-user.target

**Comment by snowdd1** [comment]
Given I do not see the contents of */etc/default/homebridge* I assume it sets HOMEBRIDGE_OPTS to `-U /var/lib/homebridge`, does it? - I cannot see any wrong. For some reason node_persist, the package that creates the persist folder (and the file within) tries to create the homebridge folder first, which apparently is already there.

Can you post the contents of the environment file if you are unsure?

**Comment by DinRigtigeFar** [comment]
`# Defaults / Configuration options for homebridge
# The following settings tells homebridge where to find the config.json file and where to persist the data (i.e. pairing and others)
HOMEBRIDGE_OPTS=-U /var/lib/homebridge

# If you uncomment the following line, homebridge will log more 
# You can display this via systemd's journalctl: journalctl -f -u homebridge
DEBUG=*`

**Comment by DinRigtigeFar** [comment]
For some reason it works now. I think it may have been a name conflict in the config.json file I had in /home/pi/.homebridge.
