### ISSUE TITLE
Having trouble re-adding homebridge to homekit

### ISSUE THREAD

**Issue by rc999985** [nfarina/homebridge#1231]
Homebridge seems to be running without issue. I removed homebridge in order to troubleshoot an issue I was having, and can't seem to get Homekit to recognize it again. I have tried restarting the homebridge server as well as all of the iOS devices. Thanks in advance

**Comment by DinRigtigeFar** [comment]
If it's a problem with discovering the bridge after having had it paired once, deleting the "persist" folder in your homebridge directory did the trick for me.

**Comment by Sturgeon637** [comment]
We lost power at home for a few minutes.  Homebridge did not connect to homekit.  Did all the trips and still nothing.

**Comment by astrojetson8** [comment]
here's what i had to do re-add:
1. kill homebridge
2. delete persist and accessories 
3. delete homebridge from Home
4. fire up homebridge 
5. go to Home and add homebridge

**Comment by Sturgeon637** [comment]
Hello Astrojetson8,  I did your list with no luck. Could this be an iOS 10.3 issue with homebridge?

**Comment by rc999985** [comment]
Hi Sturgeon637, 

Have you tried changing the bridge "username" slightly in your ~/.homebridge/config.json ? This seemed to work for me

**Comment by mpr131** [comment]
like rc said, changing the username in the config.json should do the trick. it's the key to resyncing it up. you will likely lose any configs you did within homekit.  e.g., if you assigned a device to a specific room, it will go back to the default room. at least it did for me.

**Comment by cavalol** [comment]
It seems that adding the same hub to multiple iOS devices via "Add Accessory" in the Homekit App is not the intended use of the "Hub" type in Homekit (may be different as last 'stale' post was ~5 months ago).

What worked gloriously for myself (once I found it) was as follows:
  - remove all "Home"s on all iOS devices to-be connected to shared HomeKit instance
	- to remove a homekit instance, open homekit, hit "home" -> hit the [location-services icon] -> scroll-down fully and hit "remove home"
  - on what i'll call the "admin" iOS device (of your choosing), add the hub via the "Add Accessory" method
	- now, you'll need to create outgoing shares from this same "admin" device to the icloud accounts on each "guest" device
	- to add a "guest" to a homekit instance, open homekit, hit "home" -> hit the [location-services icon] -> hit "Invite..."
	
That's about all she wrote

**Comment by fredericpfisterer** [comment]
Adding my 2 cents here since I tried everything and what fix it was to simply restart my router :-)

**Comment by elgwhoppo** [comment]
> here's what i had to do re-add:
> 
> 1. kill homebridge
> 2. delete persist and accessories folders
> 3. delete homebridge from Home
> 4. fire up homebridge
> 5. go to Home and add homebridge

This worked for me.

**Comment by hepcat72** [comment]
I had partially gotten through setting homebridge up without success a couple months ago.  I re-tackled it today and had an issue at first showing my devices in the home app.  I'd already added homebridge 2 months ago.  I was able to remove the homebridge device. It was the only one on the screen. After re-adding it (which involved deleting persist, changing the user name, and finally turning airplane mode on and off, I was able to re-add it. But now I just tried adding it to my wife's phone and when I try to add it, it says it's already been added. However, there are no devices on the screen for me to remove.  I don't know how to re-add it to her device... I'm stumped.  It keeps telling me to reset the device. How do I do that?

**Comment by mpr131** [comment]
> I had partially gotten through setting homebridge up without success a couple months ago. I re-tackled it today and had an issue at first showing my devices in the home app. I'd already added homebridge 2 months ago. I was able to remove the homebridge device. It was the only one on the screen. After re-adding it (which involved deleting persist, changing the user name, and finally turning airplane mode on and off, I was able to re-add it. But now I just tried adding it to my wife's phone and when I try to add it, it says it's already been added. However, there are no devices on the screen for me to remove. I don't know how to re-add it to her device... I'm stumped. It keeps telling me to reset the device. How do I do that?
---------------------------------------------
you don't need to re-add it to her phone.  you can invite her within the home app on your phone to share the home you have added.  that's how i had to set it up.

**Comment by hepcat72** [comment]
I thought of that, as I’d read that somewhere, but I don’t see where or how to invite someone anywhere in the Home app. Is that a feature in a specific app or iOS version? Can you share a screenshot that shows where you invite someone?

**Comment by mpr131** [comment]
> I thought of that, as I’d read that somewhere, but I don’t see where or how to invite someone anywhere in the Home app. Is that a feature in a specific app or iOS version? Can you share a screenshot that shows where you invite someone?

try this link: https://support.apple.com/en-us/HT208709.  

it's somewhat pretty straightforward there.  basically hit the little Home icon above your home name in the top left corner of the home app then you'll see a People section...and under that there should be an Invite option.  let me know if it works!

**Comment by knuckleheadsmiff** [comment]
> It seems that adding the same hub to multiple iOS devices via "Add Accessory" in the Homekit App is not the intended use of the "Hub" type in Homekit (may be different as last 'stale' post was ~5 months ago).
> 
> What worked gloriously for myself (once I found it) was as follows:
> 
> * **remove all "Home"s from all iOS devices to-be connected to shared HomeKit instance**
>   _to remove a homekit instance, open homekit, hit "home" -> hit the [location-services icon] -> scroll-down fully and hit "remove home"_
> * **on what i'll call the "admin" iOS device (of your choosing), add the hub via the "Add Accessory" method**
> * **now, you'll need to create outgoing shares from this same "admin" device to the icloud accounts on each "guest" device**
>   _to add a "guest" to a homekit instance, open homekit, hit "home" -> hit the [location-services icon] -> hit "Invite..."_
> 
> That's about all she wrote!
> 
> _Edited: Spacing of bullets_



> It seems that adding the same hub to multiple iOS devices via "Add Accessory" in the Homekit App is not the intended use of the "Hub" type in Homekit (may be different as last 'stale' post was ~5 months ago).
> 
> What worked gloriously for myself (once I found it) was as follows:
> 
> * **remove all "Home"s from all iOS devices to-be connected to shared HomeKit instance**
>   _to remove a homekit instance, open homekit, hit "home" -> hit the [location-services icon] -> scroll-down fully and hit "remove home"_
> * **on what i'll call the "admin" iOS device (of your choosing), add the hub via the "Add Accessory" method**
> * **now, you'll need to create outgoing shares from this same "admin" device to the icloud accounts on each "guest" device**
>   _to add a "guest" to a homekit instance, open homekit, hit "home" -> hit the [location-services icon] -> hit "Invite..."_
> 
> That's about all she wrote!
> 
> _Edited: Spacing of bullets_

Thanks! That did it for me. I was going crazy! Was a pita to re configure home app (i had a number of automations and accessories that needed  tot be recreated/added), wish I know an easier way but it worked.
