### ISSUE TITLE
Indigo Accessory UUIDs don't always persist

### ISSUE THREAD

**Issue by dscottbuch** [nfarina/homebridge#1232]
I have Indigo 7 , homebridge and homebridge-indigo up and running.  I have all the startup worked out so the system reliably can re-boot and start everything up but sometimes, not always, the UUIDs for the accessories change so the room, scene and automation assignments in Home no longer connect to the devices in Indigo and they all have to be reconstituted.  Any ideas why?  I see in homebridge-indigo I could implement my own persistence function and store the UUID's first generated by the hap.uuid but it seems this is already built into homebridge but I can't find where to try and debug.  Any help appreciated.

Scott

**Comment by snowdd1** [comment]
Where do the UUIDs come from? Are the generated by using the accessory names (that's default behavior) or does the plugin use the uuid function on a kind of key to generate them? And why do you think the name (or the key for the uuid function) might change between reboots?  
BTW for my plugin I decided to generate random UUIDs upon first encounter with a new accessory and persist that uuid for later use. Of course the plugin needs its own config file and write access to it.

**Comment by dscottbuch** [comment]
In reading the homebridge-indigo index.js its using the homebridge uuid generator with the device name so it should persist but it doesn't always.  Mostly it does but then the scenes, rooms and automations lose track of the devices.  That's why i'm assuming it doesn't keep the UUIDs.  HomeKit tracks the devices by uuids for purposes of these functions.  After a presumed loss of UUID's the device list looks the same in Home app but the rooms, automations, etc. all show no associated devices.

**Comment by snowdd1** [comment]
Any idea why the device names should change?

**Comment by dscottbuch** [comment]
The device names are NOT changing, which is the puzzle.  But, it did find a potential cause. I had my homebridge/Indigo system running on a different computer on my network.  After moving it I apparently didn't remove the launchd scripts on the initial system so I had two systems running homebridge with identical configuration.  I've cleaned that up and am running now with only 1 system and waiting to see if the problem repeats.

**Comment by dscottbuch** [comment]
Well still seems to lose continuity sometimes on re-boot so the multiple instances of homebridge running on the network was not the problem.  To re-iterate, the names of the devices, and the devices ID's are not changing from run to run.  The symptom I'm seeing is that the association between devices and both rooms, scenes and automations in the Home app on IOS is lost, sometimes.  I would presume this is due to either the device UUID's changing or the Accessory UUID changing, although the later I would expect to have to re-establish connection with the Accessory, not the Devices.  Note that I can still manually control the Devices, they all show up on the Home app interface, just their association with the other objects in HomeKit - Scenes, Rooms, Automations.

**Comment by dscottbuch** [comment]
Well, It's not the uuid's of the devices, at lease not what is assigned by the homebridge-indigo plugin.  I added a statement to log the uuid's to the error log on each start up and they have remained the same even though the Home app lost connection between rooms/automations at the devices.  Any ideas where this disconnect might be happening?

**Comment by dscottbuch** [comment]
This is still happening. I thought a recent update had solved this but recently it’s happening on every reboot.

**Comment by pdlove** [comment]
I recommend you pester the developer to convert it to homebridge's version 2 API which caches accessories.
I've got a similar issue with my smartthings plugin. What happens is that when it first comes up the order of the devices sometimes changes so the AID that is generated by HAP-NodeJS moves. In testing that doesn't happen when it's using the cached accessories.
This is primarily an issue when there are multiple plugins or the accessories don't always get added in the exact same order.

**Comment by dscottbuch** [comment]
Thanks.  I believe that homebridge-indigo does use the caching, etc. and version 2.0 as best I can tell.  2.0 was introduced back in Jan 2016.  In my homebridge folder there is both accessories/cachedaccessories, which has zero content but is new as of the last invocation of homebridge and there is the persist folder with AccessoryInfo... and IdentityCache... both of which have identical information to the pre-reboot, which I saved.  Can you tell me from this if it's using 2.0 API?

Thanks

**Comment by webdeck** [comment]
I haven't updated homebridge-indigo to use version 2.0 yet.  However, my hope is that this fix addresses the underlying problem: https://github.com/KhaosT/HAP-NodeJS/pull/491

As I understand it, which could be wrong, the problem happens when homebridge starts up and homebridge-indigo can't connect to indigo, so it starts up with no accessories, and HAP-NodeJS clears the cache and that results in the devices getting new AIDs the next time around, even though they have the same device names.

**Comment by dscottbuch** [comment]
Thanks for the feedback.  My startup would definitely trigger this as I start both indigo server and homebridge from LaunchDaemons at boot and then restart homebridge after the indigo server is up and running, a couple of minutes later.  As far as I know I'm up-to-date with versions. Homebridge is 0.4.29 and homebridge-indigo is 0.3.11.  Should the above referenced fix prevent this?  In any case I will change launch sequence so I don't launch homebridge until indigo is up an running.
