### ISSUE TITLE
Homebridge Won't Stop

### ISSUE THREAD

**Issue by jer78** [nfarina/homebridge#1233]
I'm running Homebridge on a Mac and I recently must have ran some command to have Homebridge run non-stop. Problem is, I need to kill it to make some changes and restart but it seems impossible. 

I tried:

1. sudo killall homebridge 
2. killall homebridge
3. forever stopall 
4. Tried to force quit in the Activity Tracker

Nothing! The thing is bullet proof. Normally it's a good thing but right now I really need to figure out how to axe it so I can make some changes. I've been pulling my hair out trying to figure a way to make it stop. Suggestions??

**Comment by astrojetson8** [comment]
you might need to unload the plist
`launchctl unload ~/Library/LaunchAgents/com.homebridge.server.plist
`

also after kiillall restart your terminal

**Comment by jer78** [comment]
Perfect. That works. Thanks so much!

**Comment by ApopheniaPays** [comment]
Doesn't work. I can see the service is in LaunchAgents, and see that it's running, but the launchctl unload line tells me it doesn't exist.

**Comment by ApopheniaPays** [comment]
It just keeps restarting. I can't kill it or remove it.
