### ISSUE TITLE
No connection between Homebridge and Apple HomeKit in iOS 10.3

### ISSUE THREAD

**Issue by medicus07** [nfarina/homebridge#1234]
After the iOS update to version 10.3 Homebridge did not work any more...

**Comment by Sturgeon637** [comment]
Same thing here.

**Comment by SkyJohn** [comment]
Do you have an iOS 10.2 device to test things with? Just to make sure it isn't a coincidence that things broke when you upgraded the OS.

I've been on the iOS 10.3 Betas for a while and haven't had any issues with Homebridge.

**Comment by Sturgeon637** [comment]
I had the complete homebrigde system running with 10.3 until I had a power cycle event in the house.  So the Raspberry PI essentialy rebooted.

**Comment by intelliarm** [comment]
Similar issue today. One of the accessory (XiaoMi infrared human monitor) went missing on iOS 10.3. I've reset the XiaoMi device, rebooted raspberry Pi, deleted current home configuration in iOS10.3. When I tried to add homebridge back again to home app, iOS10.3 cannot find anything.

I have a ipad which still runs iOS10.2, which can still find homebridge and all the devices that are connected to it.

**Comment by obiwade** [comment]
Homebridge launches for me, can be found in HomeKit, but nothing responds to HomeKit commands.

**Comment by macjeff** [comment]
We have found it's a plug in.  Add them one at a time. 

Jeff

**Comment by ZykezIX** [comment]
Can you let us know what plugin was giving you trouble? Just so that others referring to this issue down the line might be able to find answers to these fringe incidents. 

As an additional note: A fresh installation works on iOS 10.3 just fine.

**Comment by NorthernMan54** [comment]
I just upgraded to 10.3, and did not experience any issues at all.

**Comment by kode54** [comment]
I needed to delete the device from the Home app, and when I went to add it again, it refuses to find it now, from iOS 10.3.1.

**Comment by intelliarm** [comment]
@kode54 try deleting "persist" and "accessories" folders under ~/.homebridge and restart homebridge.
Delete the current home in the home app, then add everything back.

**Comment by kode54** [comment]
Yes, that fixed it for me.

**Comment by cben0ist** [comment]
I had to remove the bridge from the home app and add it again after upgrading to iOS 10.3. I lost all my scenes using some of these bridge devices but at least it's working again

**Comment by peaz** [comment]
Ok. been searching around and trying to figure out the reason why it works sometimes and not always. For me, it comes down to two things: (1) making sure multicast plays nicely on the router configs and (2) ensure that the WLAN interface on the RaspberryPi has its power saving mode disabled. I blogged it here in further detail to avoid repeating myself on what I did. https://www.atpeaz.com/fixing-homebridge-no-accessories-responding-problem/ Not sure if it would work for everyone but I suppose no harm sharing?

**Comment by sommo** [comment]
i had all running ok on 10.3.2, after few days (maybe a week) when Apple take out 10.3.3 i started having issue.. homebridge was working rightly (active running) but homekit can't see it (first time happened that..usually whomebridge when having issue was homebridge side, stopped/crashed)..
i had to that:
-stopped homebridge service
-removed accessories and persist folder
-upgraded my iphone and ipad (hub homekit)
-removed the home from home app
-run homebridge service
-create new home
-added homebridge

all oks till now

**Comment by sommo** [comment]
i also have a crontab that restart homebridge service every night

**Comment by bhilmer** [comment]
I'm pretty new to this and setting up Wink on my first Raspberry Pi. Could someone tell me how to find my homebridge's IP address? I need it for the Wink API application. 

Thanks!
