### ISSUE TITLE
Remove dynamically from cache

### ISSUE THREAD

**Issue by 4ilo** [nfarina/homebridge#1235]
Hi,

I am adding new accessory's to my platform based on my own config file i read.

Is it possible to remove accessory's on startup from the cache from within the configureAccessory function when the accessory isn't available anymore in my config file?

4ilo

**Comment by snowdd1** [comment]
Yes - it's `api.unregisterPlatformAccessoies(pluginName, platformName, accessories[])` - of the parameters, you just need to to pass the accessories array, pluginName and platformName are not used and can be undefined. So basically you call `api.unregisterPlatformAccessoies(undefined, undefined, [accessory])` for each accessory you want to delete from cache. See https://github.com/nfarina/homebridge/blob/master/lib/api.js#L166

But as written on slack, I would at least consider that the orphaning of the accessory was a configuration (I.e. User) error and the user should have the possibility to see and to delete the accessory himself.
