### ISSUE TITLE
Problem installing a second plugin (demo-platform) to homebridge running from boot up on systemd, seem to have write access problem

### ISSUE THREAD

**Issue by thetom89** [nfarina/homebridge#1236]
Hi

I have homebridge running on my raspberry pi 3 from boot up with systemd.  It has one plugin (LIFX) installed.

When I try to install a second plug in (wemo-platform) by typing:

npm install -g homebridge-platform-wemo

I get the following:

npm WARN checkPermissions Missing write access to /usr/lib/node_modules
/usr/lib
└─┬ homebridge-platform-wemo@1.1.7 
  ├─┬ debug@2.6.3 
  │ └── ms@0.7.2 
  └─┬ wemo-client@0.11.2 
    ├─┬ debug@2.2.0 
    │ └── ms@0.7.1 
    ├── entities@1.1.1 
    ├─┬ node-ssdp@2.8.0 
    │ └── ip@1.1.5 
    ├─┬ xml2js@0.4.17 
    │ ├── sax@1.2.2 
    │ └─┬ xmlbuilder@4.2.1 
    │   └── lodash@4.17.4 
    └── xmlbuilder@8.2.2 

npm ERR! Linux 4.4.50-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "homebridge-platform-wemo"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10
npm ERR! path /usr/lib/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/usr/lib/node_modules'
npm ERR!     at Error (native)
npm ERR!  { Error: EACCES: permission denied, access '/usr/lib/node_modules'
npm ERR!     at Error (native)
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/lib/node_modules' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/npm-debug.log

I assume this has to do with my creating a new user for system d.  Would anyone have any idea how to resolve this?

Kind regards

Tom

**Comment by snowdd1** [comment]
Use `sudo` for installation of global packages. Might require --unsafe-perm also for gyp.

**Comment by thetom89** [comment]
Hi, thanks very much for that!
