### ISSUE TITLE
Hesperus question mark accesories

### ISSUE THREAD

**Issue by SzilagyiR** [nfarina/homebridge#1237]
Hi!

I make a completly new install to a new sd card. When I add Homebridge to HomeKit with Hesperus it apears some ? accesories.

How can I remove it?

![hesperusprobl](https://cloud.githubusercontent.com/assets/26599357/24579067/5a191a48-16ee-11e7-8342-7e990a14051b.PNG)

**Comment by KhaosT** [comment]
What are those accessories suppose to be? You can hide them from the app.

**Comment by SzilagyiR** [comment]
They are a "ghost copy" of the real switches. Where can I hide them?

**Comment by KhaosT** [comment]
That's strange, it should not show two copy of them... You can hide them under Space Settings (Upper left gear) -> Accessories, swipe from right to left on the device you want to hide, there should have a hide option in the menu.

**Comment by SzilagyiR** [comment]
Thank you very mutch!
