### ISSUE TITLE
Rules engine

### ISSUE THREAD

**Issue by anthonywebb** [nfarina/homebridge#1239]
We have been discussing potentially adding a rules engine to our homebridge plugin.  At its core it would basically listen for events from the devices, and then if an expression was "true" it would execute an array of "commands"  Commands could be maybe an http call, sms, email, etc.  This would allos for some very dynamic use cases.

There is an example of some of the commands, and more discussion here:
https://github.com/anthonywebb/homebridge-cbus/issues/39

I think that a global observer and rules engine would be a very nice addition and am wondering if this should live in our plugin or inside homebridge itself?

Would love to get some feedback from people.

**Comment by NorthernMan54** [comment]
I can imagine how what you are describing would work.   You have plugin A, which has a switch, and when switch A is turned on, you want a device in plugin B to be turned on.  Isn't this available today in eve as an automation?

**Comment by simonhac** [comment]
@anthonywebb there's some mention in #1039 -- manager plugin / automation -- but it might just be a thought balloon.

accessories in platform plugins already fully expose themselves through a really nice API to `homebridge`, so it should be reasonably straightforward to wire up something like  [json-rules-engine](https://github.com/cachecontrol/json-rules-engine) -- but of course no point starting from scratch if someone is already working on it...

@NorthernMan54 what is `eve`? are we missing something significant?

**Comment by NorthernMan54** [comment]
Elgato eve, it's another HomeKit client app.  You can find it in the App Store

**Comment by anthonywebb** [comment]
@NorthernMan54 I'm thinking of something a little more advanced than what eve has, and not a mobile app both rather something more permanent that runs on homebridge and can do some more sophisticated tasks, like making http calls, etc.  There are some real powerful use cases to be had if you had an "event machine" with realtime callbacks as devices changed state.  A rules engine in homebridge is the glue that would help tie these systems together.

**Comment by NorthernMan54** [comment]
@anthonywebb What your saying makes perfect sense, are you also considering the multiple homebridge runtime environment?  In my house, I'm running 3 different instances of Homebridge so a rules engine would need to amalgamate multiple homebridges into a single view for processing. So in my mind the rules engine would run above homebridge, likely leveraging the same interface as home kit uses to interface to homebridge.

**Comment by snowdd1** [comment]
What about running node-red on the RPi and connecting homebridge to that? I would recommend against implementing yet another Home server into homebridge, there are so many out there.

**Comment by simonhac** [comment]
@NorthernMan54 out of interest, why are you running three instances of homebridge? that sounds like an unnecessary complication.

**Comment by simonhac** [comment]
@snowdd1 that's an interesting idea. have you managed to get node-red working with homebridge? (i trust that node-red can run on the same server as homebridge -- ie. it doesn't have to run on a RPi. correct?)

**Comment by NorthernMan54** [comment]
@simonhac I'm running multiple instances, to increase the reliability and performance of Homebridge.  So I split my plugins so each instance only runs a few plugins, so if a plugin causes homebridge to fail I only lose access to that instance's accessories and not everything.  Also if you have a large number of accessories it will update faster on startup of the Home app if you split across multiple instances.

Plus I'm always tweaking the plugin code, so I have one instance where I'm making code changes.

I currently have 44 accessories, across 8 plugins.

**Comment by simonhac** [comment]
thanks @NorthernMan54 for the explanation.

**Comment by bondjw07** [comment]
@anthonywebb I would **love** this addition.  I was just looking for this today which brought be to this thread.  In my searching, I found this app that works with smartthings and is pretty similar to something I'd love to see: http://smartrulesapp.com/

It would be awesome to be able to add a rule for the following scenarios: 

- "When the time is 11:00 PM if both people are home then lock the front and back doors."
- "When I call a switch "leaving" and there is < 2 people home (me) turn off all devices and lock the door"
- "When I call a switch "leaving" and there is > 1 people home, only lock the door"

**Comment by kapps7** [comment]
I would consider seeing the beta release of iOS 11 before putting working into this.

**Comment by chrisn-au** [comment]
Guys,

Any progress on this - would love to be able to expose homebridge accessories (instantiated  through plugins ) to node red as the rules engine ( ideally using mqtt or we sockets )

**Comment by iRonin** [comment]
No progress on this? I really dislike having to install Home Assistant for automations, esp. that Tahoma windows do not work properly there…

**Comment by NorthernMan54** [comment]
Take a look at this

https://github.com/NorthernMan54/HAP-NodeRed

I’m pretty close to being ready to publish, has some documentation etc to complete but it is usable today.

**Comment by bondjw07** [comment]
> Take a look at this
> 
> https://github.com/NorthernMan54/HAP-NodeRed
> 
> I’m pretty close to being ready to publish, has some documentation etc to complete but it is usable today.

This is very promising, looking forward to watching it develop.

**Comment by maisun** [comment]
Does anyone know if the automation support native HK devices (not added via HB)?
If not is there any way to get data from them? I know iOS apps like Eve can get status of all devices so there must be some API available......

**Comment by mafyata** [comment]
Yes , I have esp8266 devices with ravencore software and they work without homebridge and with automation

**Comment by maisun** [comment]
> Yes , I have esp8266 devices with ravencore software and they work without homebridge and with automation

But what about native HomeKit devices added directly from iOS? Can Node-red/HAP plugin read status from them? In my scenario all devices are made available in HomeKit, including lots of certified devices which are directly supported by HK.

**Comment by mafyata** [comment]
I don’t know. Here is my nodeMcu with dht22 sensor. Work without homebridge. 

![CB66DA7A-6E20-4120-8DE5-FDA0C90F4C12](https://user-images.githubusercontent.com/48009267/59046183-37877780-888a-11e9-8176-4f31c35e7ff1.png)

**Comment by NorthernMan54** [comment]
For homebridge, there is this I created

https://github.com/NorthernMan54/node-red-contrib-homebridge-automation

Works really well
