### ISSUE TITLE
Homebridge doesn't appear in Homekit - cannot pair

### ISSUE THREAD

**Issue by pplucky** [nfarina/homebridge#1241]
Hello.

I am running Homebridge on a RPi3, in which I have not been able to make it appear in HomeKit.
iDevices run iOS 10.2 or 10.2.1 and in RPi3, I have node v7.8.0 installed on RPi.

I have installed homebridge as per README and currently my config.json only has:
```
{
    "bridge": {
        "name": "Homebridge",
        "username": "3F:23:80:EE:5A:1D",
        "pin": "031-54-145"
    }
}
```

Tried multiple different usernames, pin, removed port line from config.json, deleted both persist and accessories folders, deleted home from Homekit, but nothing seems to work, although homebridge seems to be running properly:

**Output of DEBUG=* homebridge**
```
*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
[2017-4-3 12:57:59] No plugins found. See the README for information on installing plugins.
[2017-4-3 12:57:59] Loaded config.json with 0 accessories and 0 platforms.
[2017-4-3 12:57:59] ---
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-54-145 │     
    └────────────┘     
                       
  EventedHTTPServer Server listening on port 34967 +0ms
[2017-4-3 12:57:59] Homebridge is running on port 34967.
```

I didn't add any plugins yet, because I wanted to make sure I could pair homebridge with Homekit before going into that.

It is important to mention that I have pimatic installed in a different RPi3 in the same network (with pimatic-hap plugin installed), which works properly and is recognized by HomeKit (using port 51826, but with a different username).

I tried checking the Bonjour announcement for Homekit (with Bonjour browser app), and homebridge does not appear there, only the Pimatic bridge (announced from pimatic-hap).

Has anyone faced a similar issue before?

Thanks in advance.

**Comment by fastender** [comment]
Have at the moment the same problem.

**Comment by snowdd1** [comment]
Sounds like a network issue to me. Can you see anything else if the RPi on the network?

**Comment by pplucky** [comment]
The RPi is also a VPN server at the same time, I can connect without issues to all the network when connecting through the VPN, so I suppose it might not be.

My next step will be to setup a new Raspbian image and just install homebridge to it...

**Comment by rainlake** [comment]
quick guess, mdns is publishing on wrong ip address?

**Comment by pplucky** [comment]
When pinging .local address, I can find the proper internal network IP, not sure if that's what you meant

**Comment by pplucky** [comment]
Installed VPN server on the fresh Raspbian + homebridge microSD card and homebridge started working intermittently. 

When I was about to quit, googled a bit more and saw more than one person suggesting to disable IPv6 on avahi-daemon.conf and config.txt (for instance, [here](https://github.com/nfarina/homebridge/issues/607#issuecomment-210268844)) and it worked 100%. 

Thanks for your help.
