### ISSUE TITLE
Cannot connect to homebridge

### ISSUE THREAD

**Issue by kentcalero** [nfarina/homebridge#1245]
Noticed phone was no longer connecting to homebridge. Decided to remove homebridge from home app and try to re-add, HomeKit could. It find homebridge. 

Stopped all services, deleted persist, tried again. Homebridge found but failed with error "Home couldn't connect to this accessory". Went back and tried changing username and pin in config file, same issue. 

Ran with debug mode, gathered following logs:

EventedHTTPServer Server listening on port 51826 +0ms
[4/6/2017, 1:00:54 AM] Homebridge is running on port 51826.
  EventedHTTPServer [::ffff:10.0.0.136] New connection from client +27s
  EventedHTTPServer [::ffff:10.0.0.136] HTTP server listening on port 46193 +6ms
  EventedHTTPServer [::ffff:10.0.0.136] HTTP request: /pair-setup +39ms
  HAPServer [CC:23:3D:E3:CE:33] HAP Request: POST /pair-setup +3ms
  HAPServer [CC:23:3D:E3:CE:33] Pair step 1/5 +12ms
  EventedHTTPServer [::ffff:10.0.0.136] HTTP Response is finished +1s
  EventedHTTPServer [::ffff:10.0.0.136] HTTP request: /pair-setup +2s
  HAPServer [CC:23:3D:E3:CE:33] HAP Request: POST /pair-setup +1ms
  HAPServer [CC:23:3D:E3:CE:33] Pair step 2/5 +3ms
  EventedHTTPServer [::ffff:10.0.0.136] HTTP Response is finished +1s
  EventedHTTPServer [::ffff:10.0.0.136] HTTP request: /pair-setup +89ms
  HAPServer [CC:23:3D:E3:CE:33] HAP Request: POST /pair-setup +1ms
  HAPServer [CC:23:3D:E3:CE:33] Pair step 3/5 +1ms
  HAPServer [CC:23:3D:E3:CE:33] Pair step 4/5 +44ms
  HAPServer [CC:23:3D:E3:CE:33] Pair step 5/5 +4ms
  Accessory [Homebridge] Paired with client 2DF75DF0-F99B-42B9-9C75-BD0490242F05 +12ms
  EventedHTTPServer [::ffff:10.0.0.136] HTTP Response is finished +6ms
  EventedHTTPServer [::ffff:10.0.0.136] Client connection closed +55ms
  EventedHTTPServer [::ffff:10.0.0.136] New connection from client +7ms
  EventedHTTPServer [::ffff:10.0.0.136] HTTP server listening on port 40739 +1ms
  EventedHTTPServer [::ffff:10.0.0.136] HTTP connection was closed +4ms
  EventedHTTPServer [::ffff:10.0.0.136] HTTP server was closed +2ms
  EventedHTTPServer [::ffff:10.0.0.136] HTTP request: /pair-verify +9ms
  HAPServer [CC:23:3D:E3:CE:33] HAP Request: POST /pair-verify +0ms
  HAPServer [CC:23:3D:E3:CE:33] Pair verify step 1/2 +3ms
  EventedHTTPServer [::ffff:10.0.0.136] HTTP Response is finished +15ms
  EventedHTTPServer [::ffff:10.0.0.136] HTTP request: /pair-verify +15ms
  HAPServer [CC:23:3D:E3:CE:33] HAP Request: POST /pair-verify +1ms
  HAPServer [CC:23:3D:E3:CE:33] Pair verify step 2/2 +2ms
  HAPServer [CC:23:3D:E3:CE:33] Client 2DF75DF0-F99B-42B9-9C75-BD0490242F05 verification complete +8ms
  EventedHTTPServer [::ffff:10.0.0.136] HTTP Response is finished +3ms
  EventedHTTPServer [::ffff:10.0.0.136] HTTP request: /accessories +12ms
  HAPServer [CC:23:3D:E3:CE:33] HAP Request: GET /accessories +1ms
  EventedHTTPServer [::ffff:10.0.0.136] HTTP Response is finished +113ms
  EventedHTTPServer [::ffff:10.0.0.136] HTTP request: /pairings +735ms
  HAPServer [CC:23:3D:E3:CE:33] HAP Request: POST /pairings +1ms
  HAPServer [CC:23:3D:E3:CE:33] Removing pairing info for client +2ms
  Accessory [Homebridge] Unpairing with client 2DF75DF0-F99B-42B9-9C75-BD0490242F05 +0ms
  EventedHTTPServer [::ffff:10.0.0.136] HTTP Response is finished +5ms
  EventedHTTPServer [::ffff:10.0.0.136] Client connection closed +8ms
  EventedHTTPServer [::ffff:10.0.0.136] HTTP connection was closed +1ms
  EventedHTTPServer [::ffff:10.0.0.136] HTTP server

Stopped service, deleted persist and accessories, restarted

Accessory [Homebridge] Creating new AccessoryInfo for our HAP server +0ms
  Accessory [Homebridge] Creating new IdentifierCache +11ms
  EventedHTTPServer Server listening on port 51826 +208ms
[4/6/2017, 1:05:38 AM] Homebridge is running on port 51826.
  EventedHTTPServer [::ffff:10.0.0.136] New connection from client +1m
  EventedHTTPServer [::ffff:10.0.0.136] HTTP server listening on port 38145 +5ms
  EventedHTTPServer [::ffff:10.0.0.136] HTTP request: /pair-setup +38ms
  HAPServer [CC:23:3D:E3:CE:33] HAP Request: POST /pair-setup +4ms
  HAPServer [CC:23:3D:E3:CE:33] Pair step 1/5 +11ms
  EventedHTTPServer [::ffff:10.0.0.136] HTTP Response is finished +1s
  EventedHTTPServer [::ffff:10.0.0.136] HTTP request: /pair-setup +2s
  HAPServer [CC:23:3D:E3:CE:33] HAP Request: POST /pair-setup +1ms
  HAPServer [CC:23:3D:E3:CE:33] Pair step 2/5 +4ms
  EventedHTTPServer [::ffff:10.0.0.136] HTTP Response is finished +1s
  EventedHTTPServer [::ffff:10.0.0.136] HTTP request: /pair-setup +169ms
  HAPServer [CC:23:3D:E3:CE:33] HAP Request: POST /pair-setup +1ms
  HAPServer [CC:23:3D:E3:CE:33] Pair step 3/5 +2ms
  HAPServer [CC:23:3D:E3:CE:33] Pair step 4/5 +26ms
  HAPServer [CC:23:3D:E3:CE:33] Pair step 5/5 +4ms
  Accessory [Homebridge] Paired with client 2DF75DF0-F99B-42B9-9C75-BD0490242F05 +9ms
  EventedHTTPServer [::ffff:10.0.0.136] HTTP Response is finished +6ms
  EventedHTTPServer [::ffff:10.0.0.136] Client connection closed +114ms
  EventedHTTPServer [::ffff:10.0.0.136] HTTP connection was closed +5ms
  EventedHTTPServer [::ffff:10.0.0.136] HTTP server was closed +1ms
  EventedHTTPServer [::ffff:10.0.0.136] New connection from client +5ms
  EventedHTTPServer [::ffff:10.0.0.136] HTTP server listening on port 36547 +2ms
  EventedHTTPServer [::ffff:10.0.0.136] HTTP request: /pair-verify +9ms
  HAPServer [CC:23:3D:E3:CE:33] HAP Request: POST /pair-verify +0ms
  HAPServer [CC:23:3D:E3:CE:33] Pair verify step 1/2 +2ms
  EventedHTTPServer [::ffff:10.0.0.136] HTTP Response is finished +15ms
  EventedHTTPServer [::ffff:10.0.0.136] HTTP request: /pair-verify +303ms
  HAPServer [CC:23:3D:E3:CE:33] HAP Request: POST /pair-verify +1ms
  HAPServer [CC:23:3D:E3:CE:33] Pair verify step 2/2 +2ms
  HAPServer [CC:23:3D:E3:CE:33] Client 2DF75DF0-F99B-42B9-9C75-BD0490242F05 verification complete +8ms
  EventedHTTPServer [::ffff:10.0.0.136] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:10.0.0.136] HTTP request: /accessories +19ms
  HAPServer [CC:23:3D:E3:CE:33] HAP Request: GET /accessories +0ms
  EventedHTTPServer [::ffff:10.0.0.136] HTTP Response is finished +116ms
  EventedHTTPServer [::ffff:10.0.0.136] HTTP request: /pairings +651ms
  HAPServer [CC:23:3D:E3:CE:33] HAP Request: POST /pairings +0ms
  HAPServer [CC:23:3D:E3:CE:33] Removing pairing info for client +2ms
  Accessory [Homebridge] Unpairing with client 2DF75DF0-F99B-42B9-9C75-BD0490242F05 +1ms
  EventedHTTPServer [::ffff:10.0.0.136] HTTP Response is finished +5ms
  EventedHTTPServer [::ffff:10.0.0.136] Client connection closed +9ms
  EventedHTTPServer [::ffff:10.0.0.136] HTTP connection was closed +1ms
  EventedHTTPServer [::ffff:10.0.0.136] HTTP server was closed +1ms

I noticed that after everything fails, a person folder is recreated and there is one line in the IdentifierCache JSON file. 

Any help would be greatly appreciated. 

Ps: I have an ios9 iPad in wall that received HomeKit notifications and 3 iOS 10 devices that used HomeKit.

**Comment by KhaosT** [comment]
For your case, HomeKit successfully paired with homebridge but due to one of your plugin malfunctioning, HomeKit decided to not add homebridge to its database. You can try disable some plugins and isolate the issue or use Console app on macOS to check why homed refuse to accept homebridge.

```
HAPServer [CC:23:3D:E3:CE:33] Pair step 5/5 +4ms
Accessory [Homebridge] Paired with client 2DF75DF0-F99B-42B9-9C75-BD0490242F05 +12ms
EventedHTTPServer [::ffff:10.0.0.136] HTTP Response is finished +6ms
EventedHTTPServer [::ffff:10.0.0.136] Client connection closed +55ms
EventedHTTPServer [::ffff:10.0.0.136] New connection from client +7ms
EventedHTTPServer [::ffff:10.0.0.136] HTTP server listening on port 40739 +1ms
EventedHTTPServer [::ffff:10.0.0.136] HTTP connection was closed +4ms
EventedHTTPServer [::ffff:10.0.0.136] HTTP server was closed +2ms
EventedHTTPServer [::ffff:10.0.0.136] HTTP request: /pair-verify +9ms
HAPServer [CC:23:3D:E3:CE:33] HAP Request: POST /pair-verify +0ms
HAPServer [CC:23:3D:E3:CE:33] Pair verify step 1/2 +3ms
EventedHTTPServer [::ffff:10.0.0.136] HTTP Response is finished +15ms
EventedHTTPServer [::ffff:10.0.0.136] HTTP request: /pair-verify +15ms
HAPServer [CC:23:3D:E3:CE:33] HAP Request: POST /pair-verify +1ms
HAPServer [CC:23:3D:E3:CE:33] Pair verify step 2/2 +2ms
HAPServer [CC:23:3D:E3:CE:33] Client 2DF75DF0-F99B-42B9-9C75-BD0490242F05 verification complete +8ms
EventedHTTPServer [::ffff:10.0.0.136] HTTP Response is finished +3ms
EventedHTTPServer [::ffff:10.0.0.136] HTTP request: /accessories +12ms
HAPServer [CC:23:3D:E3:CE:33] HAP Request: GET /accessories +1ms
EventedHTTPServer [::ffff:10.0.0.136] HTTP Response is finished +113ms
EventedHTTPServer [::ffff:10.0.0.136] HTTP request: /pairings +735ms
HAPServer [CC:23:3D:E3:CE:33] HAP Request: POST /pairings +1ms
HAPServer [CC:23:3D:E3:CE:33] Removing pairing info for client +2ms
Accessory [Homebridge] Unpairing with client 2DF75DF0-F99B-42B9-9C75-BD0490242F05 +0ms
EventedHTTPServer [::ffff:10.0.0.136] HTTP Response is finished +5ms
```
