### ISSUE TITLE
Two homebridge instances as TWO SERVICES

### ISSUE THREAD

**Issue by PatiB87** [nfarina/homebridge#1246]
Hey,

I can already successfully run two Homebridge, one is currently set up as service (init.d on Raspberry Pi on Jessie) and the other one is started manually via the command line.
I therefore copied the /home/pi/.homebridge folder to /home/pi/.homebridge-k to have a second config.json file.
Now I can successfully run the second instance with "sudo homebridge -U /home/pi/.homebridge-k" but I don't know how to set up a second service.

I tried just to create a "homebridge-k" service in a similar fashion as I created the original "homebridge" service (according to these instruction: https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi#running-homebridge-on-bootup-initd) but it ain't working. :(

Thanks a lot for helping. :)

**Comment by SkyJohn** [comment]
You mean you can't add both in the Home app?

I think you'd need to give each a different name in the config file to do that.

**Comment by PatiB87** [comment]
Hey, thanks for he reply :)

No, that works fine.
I just don't know how to start two separate instances as service with init.d or how to use the -U flag in a second service respectively?

**Comment by dkrizic** [comment]
I think the services should have different IP addresses, different names and different "usernames" (the hex string) so HomeKit knows that there are actually two different HomeKit bridges.

**Comment by NorthernMan54** [comment]
For a second instance I wrote this up for someone else



1)	Create the .homebridge directory, but with a different name.  In my case I used .homehue as I wanted a separate instance for the hue plugin.

	mkdir ~/.homehue

2)	Create the config.json in the .homehue directory, and only include in the config the plugins you want enabled.  You must change the port number, name and username in the config.json or else homebridge will not start. 

3)	Start homebridge with the -U option and specify where to locate this instances .homebridge directory, which is this case is .homehue

	homebridge -U ~/.homehue

Tada, you now have a second instance running.   You will need to add the new homebridge instance in the Home app, but that’s it

**Comment by kapps7** [comment]
What is the advantage of having more than one instance off home bridge

**Comment by NorthernMan54** [comment]
If you have a large number of devices and plugins, splitting them increases reliability and performance.  By limiting exposure to homebridge crashes to only the devices attached to the crashed instance, and performance is increased when launching as the requests are spread across multiple homebridge.

**Comment by kapps7** [comment]
Thanks, thats a good tip. Only yesterday I was thinking a search function in the Home app would be useful ;) 
By your standards what do you consider a large number of accessories for a stable home bridge.

**Comment by NorthernMan54** [comment]
I have 3 instances running, and the first has over 20 devices on a single plugin, second has about 5 plugins with one or two devices each and a third for Hue.

I settled on this as the first one runs most of my devices and is the most stable.  The second has all the plugins I have been working on for the last few months.  And the third has Hue which I needed to separate as part of supporting Alexa.

I had everything running in one but kept having to reset all my devices on a regular basis, so I moved all the ones I was playing with to a different instance. It wasn't number based.  But other people have commented that having a large number of devices would cause a slow startup.

**Comment by kapps7** [comment]
I have roughly 20 accessories running on the single instance and keep an eye out on stability. 

On a side note, if I run homebridge on a remote computer and want to add it to my HomeKit as a second instance , will I need to be on the local network of that computer ?

**Comment by jenskastensson** [comment]
Just to confirm: the number of bridge instances is not related to/will not affect the maximum number of devices (=100) right?

**Comment by KhaosT** [comment]
Nope, each bridge can host 99 accessories. (Although HomeKit does have a maximum 1000 accessories limit).

**Comment by NorthernMan54** [comment]
@kapps7 I believe they need to be on the same network and share the same HomeKit hub.  From your phone you would need access to them all at the same time. Without digging into complex network topology, it likely wouldn't work.

In my case I have several on the same machine.  I also have a second machine on the same network.

Also, I forgot about the fourth instance I'm running.  My daughter wanted control of the lights etc, but didn't want to be a HomeKit guest with me, so I spun up an instance just for her, but she doesn't have remote access as I don't have a HomeKit hub for her.

**Comment by kapps7** [comment]
I see or perhaps  if you had a hub at the remote location signed into the same iCloud id as yours ?
I suppose its too complex to add an accessory remotely instead.

**Comment by ebaauw** [comment]
> By your standards what do you consider a large number of accessories for a stable home bridge.

I'm running a single homebridge instance on my Mac mini server with homebridge-hue exposing 79 accessories (from a v2 Hue bridge) and homebridge-zp exposing 4 accessories.

> Although HomeKit does have a maximum 1000 accessories limit

You'll hit the [CKRecord limit](https://forums.developer.apple.com/thread/64682) way before that.

**Comment by simonrb2000** [comment]
I have just setup my second homebridge instance as am now over 100 devices. Wondered how you get the command "homebridge -U ~/.homebridge2" (which is mine) to run as a service? 

Cheers

**Comment by viictor924** [comment]
Hey @PatiB87 ,

Were you able to figure out a solution to your problem? @NorthernMan54's response helped me set up a second instance of homebridge which I can run manually but I haven't been able to add this second instance to init.d/. Which I think was your original issue but then this thread conversation got derailed. My first homebridge instance gets run on reboot successfully but the second one doesn't. Also, when I do "sudo /etc/init.d/homesean start" the terminal outputs "starting", but if I follow up with "sudo /etc/init.d/homesean status" I get "Not running"

#================================================
#/etc/init.d/homebridge
#first homebridge instance
dir="/home/pi"
cmd="DEBUG=* /usr/bin/homebridge"
user="pi"
#================================================

#================================================
#/etc/init.d/homesean
#second homebridge instance
dir="/home/pi"
cmd="DEBUG=* /usr/bin/homebridge -U ~/.homesean"
user="pi"
#================================================

Strangely, when I do this manually homebridge will run successfully:
$ cd /home/pi
$ /usr/bin/homebridge -U ~/.homesean

.. which I don't think makes sense since that is the same cmd in the init.d file.

**Comment by ramsnerm** [comment]
Hi @viictor924,
Crosscheck your settings again. I see in your message you use following command to start

`cmd="DEBUG=* /usr/bin/homebridge -U ~/.homesean"`

Here you are using ~ as a short way to point to your directory but be aware that a service is no started with your username (if not explicitly set) so try it again with a fully qualified path e.g. 

`/home/pi/.homesan.`

Hope this helps
BR / Marin

**Comment by viictor924** [comment]
Thanks @ramsnerm, I changed the path and then did "sudo update-rc.d homesean defaults" and it seems to be working now!

**Comment by viictor924** [comment]
Actually, I spoke too soon! homesean runs on startup now but homebridge stopped running on startup. I can still run both simultaneously by doing "/etc/init.d/homesean start" and "/etc/init.d/homebridge start". However, when I reboot the pi only homesean starts running 

#================================================
#/etc/init.d/homebridge
#first homebridge instance
#I added "-U /home/pi/.homebridge" to the cmd
dir="/home/pi"
cmd="DEBUG=* /usr/bin/homebridge -U /home/pi/.homebridge" 
user="pi"
#================================================

#================================================
#/etc/init.d/homesean
dir="/home/pi"
cmd="DEBUG=* /usr/bin/homebridge -U /home/pi/.homesean"
user="pi"
#================================================
I edited the init.d files as above and then ran the following:
$ sudo chmod 755 /etc/init.d/homesean
$ sudo chmod 755 /etc/init.d/homebridge
$ sudo update-rc.d homesean defaults 
$ sudo update-rc.d homebridge defaults 
$ sudo reboot

However, after the pi reboots only homesean is running.

**Comment by ebaauw** [comment]
Before goong Docker, you could try and specify a different plugin directory for the second instance (I think this is done through the `-P` command line parameter).

**Comment by jeylites** [comment]
@ebaauw Sorry - How to use the -p command line, below is how I have my directory setup

**Homebridge 1**
/var/homebridge

**Homebridge 2**
/var/homecam

**Comment by ebaauw** [comment]
See https://github.com/nfarina/homebridge#plugin-development.  I guess you could start Homebridge 2 as:
```
homebridge -U ~/.homecam -P /usr/lib/node_modules/homebridge-camera-ffmpeg-omx
```

If not, move the camera plugin to a different directory and specify that for `-P`.

**Comment by NorthernMan54** [comment]
@jeylites

Looking at the log you shared, I don’t think that the edomoticz plugin should have an error that causes homebridge to exit if it can’t find a valid config entry.  Raise an issue against edomoticz and ask them to trap your error, and log a warning instead.  It should be a 10 minute fix for the developer.

**Comment by jeylites** [comment]
@ebaauw - "-p" Will give it a go to see what comes out of it.
@NorthernMan54 - I took your advice and have raised the question on edomoticz, hope it gets address soon.

The other thing is I've been experimenting with homebridge Docker compiled by [@oznu](https://github.com/oznu/docker-homebridge), very cool stuff. If anyone wants to give it a go, check his [GitHub link](https://github.com/oznu/docker-homebridge). 

With his help, I was able to set up several instances in containers. The only bummer for me is since I need ffmpeg-omx to run my cameras,  omx is not Alpine Linux compatible from what I was told.  However, there's a ffmpeg image available on Alpine hub.

The other thing is, I have no idea how to set up a container running Peter Scargill scrip and/or a container running Rasbian to install whatever stuff in it.... similar to a VM. 

cheers :)

**Comment by sherazan** [comment]
Hi, about running 2 hombridges istances, my question is: if I install a new plugin in this environment, this plugin will be available for both istances, also if I can configure the plugin only in one config.json file. Is this right?

**Comment by ebaauw** [comment]
Depending on the plugin, you could actually configure it in both instances.

On startup, homebridge first loads all plugins from the `node_modules` directory, registering the platforms (and, I suppose, accessories):
```
[3/23/2019, 10:34:17 AM] ---
[3/23/2019, 10:34:17 AM] Loaded plugin: homebridge-ws
[3/23/2019, 10:34:17 AM] Registering platform 'homebridge-ws.WS'
[3/23/2019, 10:34:17 AM] ---
[3/23/2019, 10:34:17 AM] Loaded plugin: homebridge-zp
[3/23/2019, 10:34:17 AM] Registering platform 'homebridge-zp.ZP'
[3/23/2019, 10:34:17 AM] ---
```
Then it initialises the plugins that are listed under `"platforms"` or `"accessories"`  in `config.json` (as well as any dynamic platform plugins).  
```
[3/23/2019, 10:34:17 AM] Loaded config.json with 0 accessories and 2 platforms.
...
[3/23/2019, 10:34:17 AM] [Weather] Initializing WS platform...
...
[3/23/2019, 10:34:18 AM] [Sonos] Initializing ZP platform...
```
To prevent plugins from being loaded (and dynamic platform plugins from being initialised), use the `"plugins"` key in `config.json` to whitelist the plugins you want.

For example, on my production Pi, I run two homebridge services, one for homebridge-hue, on for my other plugins.  The corresponding `config.json` files are:
```
$ cat .homebridge/config.json 
{
  "bridge": {
    "name": "pi2",
    "username": "CC:22:3D:E3:CD:31",
    "port": 51827,
    "pin": "xxx-xx-xxx"
  },
  "plugins": [
    "homebridge-p1",
    "homebridge-ws",
    "homebridge-zp"
  ],
  "platforms": [
    {
      "platform": "P1"
    },
    {
      "platform": "WS",
      "name": "Weather",
      "openweathermap": {
        "apikey": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "locations": ["Amsterdam"]
      }
    },
    {
      "platform": "ZP",
      "name": "Sonos",
      "speakers": true,
      "searchTimeout": 15
    }
  ]
}
$ cat .homebridge-hue/config.json 
{
  "bridge": {
    "name": "pi2 hue",
    "username": "CC:22:3D:E3:CD:30",
    "port": 51826,
    "pin": "xxx-xx-xxx"
  },
  "plugins": [
    "homebridge-hue"
  ],
  "platforms": [
    {
      "platform": "Hue",
      "host": "127.0.0.1",
      "users": {
	"00212EFFFFxxxxxx": "xxxxxxxxxx"
      },
      "sensors": true,
      "hueDimmerRepeat": true,
      "lowBattery": 10,
      "lights": true,
      "groups": false,
      "schedules": true,
      "heartrate": 5
    }
  ]
}
```

**Comment by beatpaul** [comment]
Hi!
@ebaauw 
is whitelisting working on a mac too?

Is there any way of running 2 instances on a mac as a service? / how to?
( i have the problem that some plugins slow down / crash  homebridge if wifi connection to the accessory is lost, so i want to separate these plugins)

Greez paul

**Comment by ebaauw** [comment]
> is whitelisting working on a mac too?

Yes.

> Is there any way of running 2 instances on a mac as a service?

See the Wiki, https://github.com/nfarina/homebridge/wiki/Install-Homebridge-on-macOS#starting-homebridge-automatically-with-launchd.  You would have to create two `.plist` files, one for each instance, and add `-H /Users/user/.homebridge2`(or something similar) to one.

**Comment by beatpaul** [comment]
I created the file, not sure about the -H
Could it be -U ?

**Comment by jeylites** [comment]
I said it before, will say it again Incase it got forgotten.

There’s a well documented docker based homebridge that runs on Raspberry pi, Synology and/ or may  be Mac available at OZNU github page.


Some of the good features that I like 

- One can deploy multiple instances quickly without  going through the hassle of creating multiple directories. 

- web browse access to the following ;

 config directories, instances performance check, individual instances reboot, terminal, installation & un-installation of libraries, etc. 

Just google OZNU Homebridge it should show up.

**Comment by julien94800** [comment]
Hello,
I had a look on this wiki that is really helpful and complete. 
Nevertheless, I did not find any information on how to set up two homebridge substances on a Synology by using docker. 
Do you know where I could find this?
Thanks in advance

**Comment by mafyata** [comment]
There are so many videos on youtube , shows step by step.

**Comment by jeylites** [comment]
Currently I’m running 6 instances on my RPI, instance 1-5 does all my daily automation stuff, instance 6 - I use it to run test, r&d stuff. It’s been 2 years can’t complain about using this method. 

Here’s some information for you

https://github.com/oznu/docker-homebridge/issues/32

**Comment by julien94800** [comment]
Hello again,
Thanks very much for your feedback. Indeed I previously read this but it seems to be easier to apply it on a raspberry rather than on a Synology due to the fact that you have better access. I will try to apply it to the Synology in order to see how I can do
Thanks again

**Comment by jeylites** [comment]
Synology, I’m pretty sure someone worked on something similar. Or at least the setup should be far off compared to RPI.  I would raise the question for the sake of discussion.

**Comment by ebaauw** [comment]
> I created the file, not sure about the -H
Could it be -U ?

Sorry, my bad.  Updated my comment to reflect `-U`.

**Comment by julien94800** [comment]
@jeylites Indeed in docker for synology there is an option to duplicate in one click...
I only had to create an other folder for setting config files on it (and modify settings as names and port) and then modify the path. After this, everything was working perfectly without any effort
Thanks again

**Comment by beatpaul** [comment]
> > I created the file, not sure about the -H
> > Could it be -U ?
> 
> Sorry, my bad. Updated my comment to reflect `-U`.

Working now after some trial and error :) thx for your help

**Comment by twentyNoise** [comment]
> > Is there any way of running 2 instances on a mac as a service?
> 
> See the Wiki, https://github.com/nfarina/homebridge/wiki/Install-Homebridge-on-macOS#starting-homebridge-automatically-with-launchd. You would have to create two `.plist` files, one for each instance, and add `-U /Users/user/.homebridge2`(or something similar) to one.

Hi @ebaauw 

Since you're running multiple instances in this way I'm hoping you can help.

I've been running a single instance of Homebridge as a service with the .plist file for some time. I wanted to setup a 2nd instance and so I created the other home bridge folder and all that, as well as a second .plist file. The instance will runs fine through Terminal:

`homebridge -U -I /Users/test/.homebridge2`

But the 2nd .plist file and using launchctl doesn't work. I don't see any errors and the service is 'loaded' but the the homebridge process doesn't load.

Any idea why?

Thanks!

`launchctl load ~/Library/LaunchAgents/com.homebridge2.server.plist`

.plist file:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>RunAtLoad</key>
	<true/>
	<key>KeepAlive</key>
	<true/>
	<key>Label</key>
	<string>com.homebridge2.server</string>
	<key>ProgramArguments</key>
	<array>
		<string>/usr/local/bin/homebridge</string>
		<string>-I</string>
		<string>-U</string>
		<string>/Users/test/.homebridge2</string>
	</array>
	<key>StandardOutPath</key>
	<string>/Users/test/homebridge2/logs/logfile.log</string>
	<key>StandardErrorPath</key>
	<string>/Users/test/homebridge2/logs/logfile.log</string>
	<key>EnvironmentVariables</key>
	<dict>
		<key>PATH</key>
		<string>/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH</string>
	</dict>
</dict>
</plist>
```
