### ISSUE TITLE
2/3 IP cameras with nearly identical configurations show up and json validates

### ISSUE THREAD

**Issue by rc999985** [nfarina/homebridge#1247]
Trying to figure out what's up with the third. Doesn't seem to show up in HomeKit. Any tips would be greatly appreciated.

{
			"platform": "Camera-ffmpeg",
			"cameras": [{
				"name": "Back Yard",
				"videoConfig": {
					"source": "-re -i http://admin:password@192.168.1.16:8081",
					"stillImageSource": "-re -i http://192.168.1.16/picture/1/frame/",
					"maxStreams": 2,
					"maxWidth": 1280,
					"maxHeight": 720,
					"maxFPS": 30
				}
			}, {
				"name": "Outside Front Left",
				"videoConfig": {
					"source": "-re -i http://admin:password@192.168.1.10:8081",
					"stillImageSource": "-re -i http://192.168.1.10:8765/picture/1/current/",
					"maxStreams": 2,
					"maxWidth": 1280,
					"maxHeight": 720,
					"maxFPS": 30
				}
			}, {
				"name": "Outside Front Right",
				"videoConfig": {
					"source": "-re -i http://admin:password@192.168.1.28:8081",
					"stillImageSource": "-re -i http://admin:password@192.168.1.28/picture/1/frame/",
					"maxStreams": 2,
					"maxWidth": 1280,
					"maxHeight": 720,
					"maxFPS": 30
				}

**Comment by KhaosT** [comment]
First ... you need to post the full config, instead of just a segment of it... Second, this issue should be filed under [homebridge-camera-ffmpeg](https://github.com/KhaosT/homebridge-camera-ffmpeg) instead of here.

**Comment by rc999985** [comment]
Zing! Thank you friend. I don't know if you still want the whole config but here you go. Thanks for pointing me in the right direction.

{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:23:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},



	"accessories": [{
			"accessory": "SamsungTV",
			"name": "TV Living Room",
			"ip_address": "192.168.1.12",
			"send_delay": 400
		},


		{
			"accessory": "VSX",
			"name": "VSX-822",
			"description": "Reciever",
			"ip": "192.168.1.3",
			"port": 8102
		},

		{
			"accessory": "Xbox",
			"name": "Xbox",
			"ipAddress": "192.168.1.17"
		}
	],

	"platforms": [{
			"platform": "Nest",
			"token": “token”,

			"clientId": “id”,
			"clientSecret": “secret”,
			"code": “code”,

			"username": “email@icloud.com",
			"password": “password”

		},

		{
			"platform": "HarmonyHub",
			"name": "Harmony Hub"
		},

		{
			"platform": "Camera-ffmpeg",
			"cameras": [{
				"name": "Back Yard",
				"videoConfig": {
					"source": "-re -i http://admin:password@192.168.1.16:8081",
					"stillImageSource": "-re -i http://192.168.1.16/picture/1/frame/",
					"maxStreams": 2,
					"maxWidth": 1280,
					"maxHeight": 720,
					"maxFPS": 30
				}
			}, {
				"name": "Outside Front Left",
				"videoConfig": {
					"source": "-re -i http://admin:password@192.168.1.10:8081",
					"stillImageSource": "-re -i http://192.168.1.10:8765/picture/1/current/",
					"maxStreams": 2,
					"maxWidth": 1280,
					"maxHeight": 720,
					"maxFPS": 30
				}
			}, {
				"name": "Outside Front Right",
				"videoConfig": {
					"source": "-re -i http://admin:password@192.168.1.28:8081",
					"stillImageSource": "-re -i http://admin:password@192.168.1.28/picture/1/frame/",
					"maxStreams": 2,
					"maxWidth": 1280,
					"maxHeight": 720,
					"maxFPS": 30
				}
			}]
		}
	]
}

**Comment by KhaosT** [comment]
@rc999985 and which camera didn't show up in Home app?

**Comment by rc999985** [comment]
The last one, Outside Front Right. Thanks again

**Comment by KhaosT** [comment]
Huh... It looks fine to me. What do you see when you start homebridge on your computer? Does it show "Outside Front Right is running on port xxx" ?

**Comment by rc999985** [comment]
[4/6/2017, 10:32:08 PM] [Xbox] Initializing Xbox accessory...
[4/6/2017, 10:32:08 PM] Outside Front Right is running on port 46689.
[4/6/2017, 10:32:08 PM] Outside Front Right is running on port 35291.
[4/6/2017, 10:32:08 PM] Outside Front Right is running on port 33261.
[4/6/2017, 10:32:11 PM] Software version for Hallway Thermostat is: 5.6-7

**Comment by rc999985** [comment]
also just cleared the persist and accessories folder

**Comment by KhaosT** [comment]
Ignore the duplicated name (it's a known issue, wouldn't affect anything), homebridge did publish 3 cameras. If you open Home app now, and go to add accessory screen, you can only see two of them?

**Comment by rc999985** [comment]
That is correct

**Comment by KhaosT** [comment]
Can you try rename "Outside Front Right" to something different and see if that works?

**Comment by rc999985** [comment]
That worked my friend!! Thank you!!

**Comment by KhaosT** [comment]
Interesting... I can only assume the UUID generated for that name is somehow collide with other one causing HomeKit not to show it.
