### ISSUE TITLE
Start fails since yesterday because of hap-nodejs

### ISSUE THREAD

**Issue by benzman81** [nfarina/homebridge#1251]
Error is cannot find module curve25519-n.

**Comment by KhaosT** [comment]
Please make sure you updated both homebridge and hap-nodejs.

**Comment by KhaosT** [comment]
I think npm has issue with updating dependencies when you update a package.

**Comment by benzman81** [comment]
Ok, works now when updating hap-nodejs before updating homebridge (using a docker image).
