### ISSUE TITLE
Suggestions to control power to switch on/off  dumb monitor

### ISSUE THREAD

**Issue by kapps7** [nfarina/homebridge#1255]
Looking for some suggestions. I have a dumb monitor (http://www.lg.com/us/monitors/lg-27UD68-W-4k-uhd-led-monitor). It has a spare HDMI connector. I just want to be able to control the power of this ie. turn it off and on via Homebridge.

There aren't any smart outlets available for Australia. I thought may be RasPi3. Wondering if there was another more inexpensive method.

Thanks.

**Comment by samuelemarazzita** [comment]
I0ve made it with my raspberry pi3 and this plugin: https://www.npmjs.com/package/homebridge-lgtv2

**Comment by kapps7** [comment]
I use that plugin also. It connects  to my LG TV webOS directly. Homebridge is installed on a Mac mini,
Are you plugging the raspi3 into your LGTV HDMI connector ?

I was also looking at possible ardunio solutions.

**Comment by samuelemarazzita** [comment]
My raspi3 is on my library and I get access to it by ssh or vnc so no HDMI connection. Anyway I'm not sure the plugin is ok for your led monitor, you need to check if it has wifi connection and after that enable the wake-on-lan function.

**Comment by kapps7** [comment]
No it won't work like that since the monitor isn't a connected monitor. I mentioned raspi3 because there is a homebrige plugin that can control power using hdmi cec which works by directly plugging the rasbpi3 into the dumb monitor.

I forgot to mention there are plenty of wifi power outlets (not a native HomeKit one for Aus) so perhaps a plugin supports one of those will be enough.

**Comment by samuelemarazzita** [comment]
Maybe try with this.

https://github.com/x2c/homebridge-hdmi <https://github.com/x2c/homebridge-hdmi>
