### ISSUE TITLE
Homebridge needs a forum 

### ISSUE THREAD

**Issue by maragelis** [nfarina/homebridge#1258]
I think its time homebridge gets its own forum so that we can help each other around problems. 
what do you all think ?

**Comment by SkyJohn** [comment]
There is the Homebridge subreddit.

https://www.reddit.com/r/homebridge/

But it isn't very active.

**Comment by Hedda** [comment]
Recommend MyBB free and open source forums:

https://mybb.com

It also have loads of plugins (including for third-party integrations) and themes:

https://community.mybb.com/mods.php?action=browse&category=plugins
https://community.mybb.com/mods.php?action=browse&category=themes

**Comment by NorthernMan54** [comment]
Isn't that what slack is for?

**Comment by Hedda** [comment]
@NorthernMan54 No, Slack is more for real-time messaging, as a replacement for IRC.

**Comment by giannimp** [comment]
Hi, I have a smart plug amazon model hd34bx, is there a plugin for homebridge for this device?
Thank you

**Comment by zoroo07** [comment]
Homebridge does need a forum!  What can we do about it!

**Comment by llamafilm** [comment]
I just joined the slack workspace but i only see an empty general channel and it’s read-only. Do I have to request permission somehow?

**Comment by alexmyczko** [comment]
where's the #homebridge irc channel?
