### ISSUE TITLE
MY Q config.json Issue

### ISSUE THREAD

**Issue by oodom285** [nfarina/homebridge#1259]
heres what I'm using. Ive filled in the username and password. But I'm not sure if the Application ID is the same for all. And not sure what BrandID and LogLevel are.... 

Any help would be greatly appreciated

 "platform": "MyQ",
			 "name": "Garage Door",
			 "MyQApplicationId": "NWknvuBd7LoFHfXmKNMBcgajXtZEgKUh4V7WNzMidrpUUluDpVYVZx+xT4PCM5Kx",
			 "UserAgent": "Chamberlain/2793 (iPhone; iOS 9.3; Scale/2.00)",
			 "BrandId": "2",
			 "culture": "en",
			 "username": "",
			 "password": "",
			 "loglevel":"0"

**Comment by snowdd1** [comment]
Just guessing you are using https://github.com/rainlake/homebridge-platform-myq   

So maybe it is more helpful to open the issue there?

**Comment by Neelrp12** [comment]
Use this plugin instead and just put in your myq info in it.
https://github.com/luisiam/homebridge-liftmaster2

**Comment by oodom285** [comment]
Thank u! That worked. The lift master2 plugin worked and much less credentials to put in
