### ISSUE TITLE
Interface to HomeSeer

### ISSUE THREAD

**Issue by RienduPre** [nfarina/homebridge#126]
Hi,

First of all, I love the Homebridge initiative !!

I’m now busy writing a plug-in (interface) for HomeSeer. Because I want the HomeSeer user in control which devices will be controlled by HomeKit, I just use the HomeBridge as a HTTP bridge. It basically adds entries to the config.son if the HomeSeer user enables HomeKit integration for a specific devices.
This works now for On/Off devices, but I like to have more functionality

Couple of question, I hope you can and will answer:
- Is/must the pincode 031-45-154 always the same or is this user configurable ?

- How to get the On/Off status of a device. HomeKit knows the status when it has been controlled by HomeKit, But what If I turn a lamp on with Homekit and turn it off manually (by HomeSeer or physical switch)

- Is it possible to get sensor information via the HomeBridge ? For instance Temperature, Volume, Power Usage or other status information.

Sorry for any duplicate questions, I searched but could not find the exact answer yet, or I don't understand (yet) how to do it.

Many thanks in advance for your help.

Best regards,
Rien

**Comment by volschin** [comment]
I have changed user, pin and port for my installation for security reasons. Works fine. And this is why this is not hardcoded, but in the config.json in the newest version.

**Comment by volschin** [comment]
For your other questions check the existing accessories and platforms and the HomeKitTypes.js in HAP-NodeJS.

**Comment by cflurin** [comment]
> How to get the On/Off status of a device. HomeKit knows the status when it has been controlled by
 > HomeKit, But what If I turn a lamp on with Homekit and turn it off manually (by HomeSeer or physical >switch)

>Is it possible to get sensor information via the HomeBridge ? For instance Temperature, Volume, Power >Usage or other status information

On: https://gist.github.com/cflurin you'll find examples like FhemSwitch.js, FhemTemperaturerSenor.js.
the values have to be set using setValue()
