### ISSUE TITLE
Execute HomeKit Scenes or Accessories via Homebridge / command line

### ISSUE THREAD

**Issue by kapps7** [nfarina/homebridge#1261]
Is it possible to control or execute the configured accessories via command line or scripting. I understand that scenes probably cannot be since they are created within HomeKit.

I am basically trying to create a virtual trigger ie. as if someone pressed the on switch on the accessory via the iOS app - but on the desktop environment

Thanks

Edited:

So thinking about this a bit more...
Can 'Homebridge' usage be customised to point and run a plugin eg.
Homebridge -p -e   (for example)

This way we have the ability to bring homekit to the desktop or atleast the homebridge part of it.

**Comment by NorthernMan54** [comment]
There could be a couple of approaches for this, ie modifying a plugin to generate an event that could be used as part of an automation. For example, a switch that triggers an automation in the Home App.

Or use the homebridge http-API ( which is not documented ) via insecure mode to change the state of accessories ( I used this in one of my Alexa integration attempts )

**Comment by snowdd1** [comment]
You could also start with the cmd plugin. I've made a sample at https://github.com/snowdd1/homebridge-cmd to show how to generate a switch that takes a Unix socket as incoming connection - so it is local only on that machine, and not open as a web socket etc. would be. 
happy coding!
