### ISSUE TITLE
Rasberry Pi vs OS X Terminal

### ISSUE THREAD

**Issue by macjeff** [nfarina/homebridge#1262]
Since I dont think there is a forum to post this I am posting it here.

I have multiple instances of homebridge running in terminal on OS X server and its all perfect.

Is there any reason to move everything to a Pi?   Even if I retire the current server I could keep it as a homebridge only server.

I am just trying to get some advice if anyone has any comments.

**Comment by NorthernMan54** [comment]
I'm using headless RaspberryPI's, due to concerns about power consumption of my other machines.  The PI's sip on electricity versus my other machines which consume a lot of power.

**Comment by lolfr** [comment]
I've done this move for the same reason, power consumption. Also it give me the opportunity to use and try different stuff on my OS X server without breaking my homebridge setup.

**Comment by macjeff** [comment]
Ok but if the server is running for other things anyways then it is probably less power than another device.

But if I retire the server then you convinced me to go Pi then.  Its just all working perfectly the way it is and although the pi server is cheap, its more time to move things and reinstall stuff.

Jeff

**Comment by NorthernMan54** [comment]
Jeff,

In my environment, I use my Mac as a development environment to work on plugins etc, then promote to production on my 'PI's'.

**Comment by macjeff** [comment]
Once you get the basics installed can you just copy over the directories for each plugin    I don’t want to spend a day doing this when everything is working.

Jeff

**Comment by NorthernMan54** [comment]
My workflow is to check the plugin changes into github/npm then do a npm install on the PI.  Using npm on the PI allows npm to manage the dependencies. For the config.json changes I do these manually.
