### ISSUE TITLE
Custom Plugin Development

### ISSUE THREAD

**Issue by macjeff** [nfarina/homebridge#1263]
Anyone out there interested in developing plugins for a fee let me know.  We work with companies doing Alexa and other plugins and some of them are interested in homebridge plugins.   So I am trying to figure out if this is something we could do or not.  

Jeff

**Comment by crhan** [comment]
Why not to develop the Home Assistant's plugin?

**Comment by mrose17** [comment]
@macjeff - i suspect that you could probably get folks to write plugins just for the cool hardware. seriously...

**Comment by macjeff** [comment]
I am working with this company 

http://weatherflow.com/smart-home-weather-stations/

and they are interested in a plugin. 

They are a competitor to Netatmo and a LOT BETTER

Also a pool company but I doubt they would send their system as it is about 10k.   But they have a demo system I am running that we could use.

I can’t mention the pool company name yet…sorry.

Jeff

**Comment by mrose17** [comment]
well, you have to love a company with a product called _fishweather_ (-;

let's not worry about the pool company for now. (some folks might drop $10K on such a system, but even when i had a pool a few years back, it's hard to imagine going there.)

here's my take: i don't work in IoT any more, but still contribute open source -- https://github.com/homespun -- and i happen to like environmental sensors, so i might be interested in doing the work just to see another cool thing on homekit. you can reach me at mrose17@homespun.io to discuss further, but for now, here are some things to think about:

1. using Wi-Fi with homebridge is not a problem, use BLE with homebridge probably _will_ be a problem. there are node modules that enable BLE [Sandeep Mistry](https://github.com/sandeepmistry/noble) is the guru on that, but even with his work, BLE isn't as reliable as i[d like.

2. the we'll store your data in the cloud and then you can access it remotely works well if the only way to get at the data is via a proprietary app. with things like homebridge, the devices don't need to go to their own cloud to store data. i am a lot more comfortable letting the folks at apple manage my IoT data than N third-party companies (no offense intended to anyone). the API can be accessed by either an API key or an oauth token. a homebridge token can be written for either. when i get into work this morning, i'll take a look at the API in more detail.

3. keeping in mind (2), it may be better to have the device just multicast a snapshot when it contacts the cloud. this would allow for a zero-configuration set-up.

4. one of the things i haven't read yet is how often the device reports information. that will have a big impact on battery life (as does the use of wifi)...

5. unrelated: pi don't see a link to integration with [Wink](https://www.wink.com/) on the site. if you're going to integrate with SmartThings you should probably integrate with Wink as well. (disclosure: i worked there a couple of years ago... even though i am a homekit and elgato eve fanatic, i remain a big fan of the wink apps!)

enjoy!

**Comment by macjeff** [comment]
Actually the 10k is all the circuits, valves, etc.   That allows it to work from a remote.  The internet interface is a grand or so.

Its actually pretty popular.

**Comment by macjeff** [comment]
https://weatherflow.github.io/SmartWeather/api/ <https://weatherflow.github.io/SmartWeather/api/>   

They have API.

I also emailed them asking if they would send you a free unit.

Jeff

**Comment by lprhodes** [comment]
Hi @macjeff - I'd be interested. Check out [homebridge-broadlink-rm](https://github.com/lprhodes/homebridge-broadlink-rm) as an example of my homebridge work.

**Comment by macjeff** [comment]
Please contact me offline via the contact form (don’t want to post email here for BOTS to pick up)

Just put For Jeff- Homebridge in the subject

www.midatlanticconsulting.com

I will answer very quickly.  If not post back here.   We just moved our site to new 

thanks,

Jeff
