### ISSUE TITLE
Homebridge crashes after a couple of hours.

### ISSUE THREAD

**Issue by Luckyman123** [nfarina/homebridge#1264]
After a couple of hours, i can't switch on my light with my iPhone. 
Pleas can someone help me to run home bridge stable? 

**I am Getting this error:** 

**This is in my homebridge.err file** 
tail -f /var/log/homebridge.err 

at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at Server._listen2 (net.js:1236:14)
    at listen (net.js:1272:10)
    at Server.listen (net.js:1368:5)
    at EventedHTTPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:60:19)
    at HAPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:158:20)
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:509:16)
    at Server._publish (/usr/local/lib/node_modules/homebridge/lib/server.js:114:16)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:372:14)

**after running the command**  
sudo killall homebridge
and sudo reboot
homebridge runs again 

Thank you 👍

**Comment by Pltnorwich** [comment]
what are you running homebridge on? for example if you are using a raspberry pi and ssh into it from a mac and run the command 'homebridge' when the mac goes to sleep this will terminate the homebridge session. hence you'll have to restart it - that maybe your problem without know your setup.

**Comment by Luckyman123** [comment]
I am running homebridge on 
raspberry pi 
ssh from a mac 

i tried to autostart it with 
1) Running Homebridge on Bootup (init.d)
but it did not work 

then i tried screen and it works for a while but not stable. 

What is the best method to autostart home bridge and run it stable?

**Comment by Pltnorwich** [comment]
I tried with screen too and as you found it does not work well with that.

Right at this moment I'm just about to setup to auto start and will let you know in a bit.
The option I have been using currently was to set the pi to boot to desktop, vnc into that,  then open a terminal run homebridge in that- it works but seemed a few seconds slower updating but never had a crashing issue.

Sent from my iPhone

On 26 Apr 2017, at 21:44, Luckyman123 <notifications@github.com<mailto:notifications@github.com>> wrote:


I am running homebridge on
raspberry pi
ssh from a mac

i tried to autostart it with

  1.  Running Homebridge on Bootup (init.d)
but it did not work

then i tried screen and it works for a while but not stable.

What is the best method to autostart home bridge and run it stable?

**Comment by Pltnorwich** [comment]
@Luckyman123,

Ive just gone through some settings and mine is now verified as auto starting on boot (similar to z way server) 
Steps I took were.

1)ssh into your pi
2) type 'sudo nano /etc/init.d/homebridge'
3)paste the following into the window ( change username or password if you altered) copy from the first hash too below exit 0.
4)ctrl+o = to save, then ctrl+x = to exit
5)sudo chmod 755 /etc/init.d/homebridge
6)sudo update-rc.d homebridge defaults
7) go to home app on phone and then reboot pi, watch homebrige loses response in app, then refresh it after about 2 mins (giving the pi time to boot and auto load) I don't know how long or stable this is but I'm now running this too.


#!/bin/sh
### BEGIN INIT INFO
# Provides: homebridge
# Required-Start:    $network $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

dir="/home/pi"
cmd="DEBUG=* /usr/local/bin/homebridge"
user="pi"

name=`basename $0`
pid_file="/var/run/$name.pid"
stdout_log="/var/log/$name.log"
stderr_log="/var/log/$name.err"

get_pid() {
    cat "$pid_file"
}

is_running() {
    [ -f "$pid_file" ] && ps `get_pid` > /dev/null 2>&1
}

case "$1" in
    start)
    if is_running; then
        echo "Already started"
    else
        echo "Starting $name"
        cd "$dir"
        if [ -z "$user" ]; then
            sudo $cmd >> "$stdout_log" 2>> "$stderr_log" &
        else
            sudo -u "$user" $cmd >> "$stdout_log" 2>> "$stderr_log" &
        fi
        echo $! > "$pid_file"
        if ! is_running; then
            echo "Unable to start, see $stdout_log and $stderr_log"
            exit 1
        fi
    fi
    ;;
    stop)
    if is_running; then
        echo -n "Stopping $name.."
        kill `get_pid`
        for i in {1..10}
        do
            if ! is_running; then
                break
            fi

            echo -n "."
            sleep 1
        done
        echo

        if is_running; then
            echo "Not stopped; may still be shutting down or shutdown may have failed"
            exit 1
        else
            echo "Stopped"
            if [ -f "$pid_file" ]; then
                rm "$pid_file"
            fi
        fi
    else
        echo "Not running"
    fi
    ;;
    restart)
    $0 stop
    if is_running; then
        echo "Unable to stop, will not attempt to start"
        exit 1
    fi
    $0 start
    ;;
    status)
    if is_running; then
        echo "Running"
    else
        echo "Stopped"
        exit 1
    fi
    ;;
    *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0

**Comment by Pltnorwich** [comment]
@Luckyman123 sorry about the different fonts, its where i have edited in notes. you should copy from 
#!bin.........
.......
exit 0

**Comment by Luckyman123** [comment]
When i copy and past your script i get this error...

insserv: warning: script 'K01homebridge' missing LSB tags and overrides

**Comment by Pltnorwich** [comment]
Did you copy all - including the ### lines at the start to below .....exit 0
Save, exit then run the 2 sudo commands?

Sent from my iPhone

On 26 Apr 2017, at 22:44, Luckyman123 <notifications@github.com<mailto:notifications@github.com>> wrote:


When i copy and past your script i get this error...

insserv: warning: script 'K01homebridge' missing LSB tags and overrides

**Comment by Pltnorwich** [comment]
I think it may have been my formatting, try again but copy below in between the quotes and follow the rest again. 
"
#!/bin/sh
### BEGIN INIT INFO
# Provides:
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

dir="/var/homebridge"
cmd="DEBUG=* /usr/bin/homebridge -U /var/homebridge"
user="homebridge"

name=`basename $0`
pid_file="/var/run/$name.pid"
stdout_log="/var/log/$name.log"
stderr_log="/var/log/$name.err"

get_pid() {
    cat "$pid_file"
}

is_running() {
    [ -f "$pid_file" ] && ps `get_pid` > /dev/null 2>&1
}

case "$1" in
    start)
    if is_running; then
        echo "Already started"
    else
        echo "Starting $name"
        cd "$dir"
        if [ -z "$user" ]; then
            sudo $cmd >> "$stdout_log" 2>> "$stderr_log" &
        else
            sudo -u "$user" $cmd >> "$stdout_log" 2>> "$stderr_log" &
        fi
        echo $! > "$pid_file"
        if ! is_running; then
            echo "Unable to start, see $stdout_log and $stderr_log"
            exit 1
        fi
    fi
    ;;
    stop)
    if is_running; then
        echo -n "Stopping $name.."
        kill `get_pid`
        for i in {1..10}
        do
            if ! is_running; then
                break
            fi

            echo -n "."
            sleep 1
        done
        echo

        if is_running; then
            echo "Not stopped; may still be shutting down or shutdown may have failed"
            exit 1
        else
            echo "Stopped"
            if [ -f "$pid_file" ]; then
                rm "$pid_file"
            fi
        fi
    else
        echo "Not running"
    fi
    ;;
    restart)
    $0 stop
    if is_running; then
        echo "Unable to stop, will not attempt to start"
        exit 1
    fi
    $0 start
    ;;
    status)
    if is_running; then
        echo "Running"
    else
        echo "Stopped"
        exit 1
    fi
    ;;
    *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0
"

**Comment by Pltnorwich** [comment]
Follow the steps again but copy and paste from this page.     https://raw.githubusercontent.com/fhd/init-script-template/master/template

Then carry on with what I wrote - should work then.

**Comment by Luckyman123** [comment]
Thanks bro :) 
it works...

I uninstalled all of the other start on boot software and files. 
And install this one and now it works :)

**Comment by Pltnorwich** [comment]
Glad it worked for you.

Are you running many plugins in homebridge? which ones?

I've tried the homebridge-Bluetooth but unsuccessfully could not add my Bluetooth lock.


Sent from my iPhone

On 27 Apr 2017, at 06:57, Luckyman123 <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks bro :)
it works...

I uninstalled all of the other start on boot software and files.
And install this one and now it works :)

**Comment by Luckyman123** [comment]
I am only running Home Assistant at the moment. 

I use it to switch on my lights with Siri ;) 

Do you also have an home automation system? :)

**Comment by Pltnorwich** [comment]
Yes I have automation, I originally had Philips hue lights running through their app for a few years, then iOS 10 came out with the Home app.
I then add the lights to that, I bought a smart thermostat (tado) and also a door lock (Danalock v2 zwave+Bluetooth)

These last 2 I was using their own apps as well to control ( making a total of 3- even though functions were automated in the apps .....lock /unlock.....)

A few months ago I got a pi from work and found homebridge, I the installed the tado plugin and zwave server (uzb1 stick)

So now all my heating and lights and lock are or easily control in the one app on my iPhone, any timer functions for thermostat or users for the lock is then edited in their own apps.

Works great.



Sent from my iPhone

On 27 Apr 2017, at 08:13, Luckyman123 <notifications@github.com<mailto:notifications@github.com>> wrote:


I am only running Home Assistant at the moment.

I use it to switch on my lights with Siri ;)

Do you also have an home automation system? :)

**Comment by Luckyman123** [comment]
My next project are: 
install alexa with the amazon fire tv stick on an benq projector.
Turn on and off my ps4 trough home assistant 
Install live Public Transport time Vienna
