### ISSUE TITLE
Problems Installing Homebridge on Windows 10

### ISSUE THREAD

**Issue by Dadditude** [nfarina/homebridge#1266]
Hi, there. I'm trying to install Homebridge on Windows 10 using the guide at https://github.com/nfarina/homebridge/wiki/Install-Homebridge-on-Windows, but I get the following errors on Step 4:

MSBUILD : error MSB4132: The tools version "2.0" is unrecognized. Available tools versions are "4.0".
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Users\daddi\AppData\Roaming\npm\node_modules\homebridge\node_modules\curve25519-n2
gyp ERR! node -v v5.0.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm\cli.js" "install" "-g" "homebridge"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE

npm ERR! curve25519-n2@1.1.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the curve25519-n2@1.1.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the curve25519-n2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls curve25519-n2
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Windows\system32\npm-debug.log

So I guess what I need to know is:
1. Can anyone help me figure out what the problem is?
2. Do I need to post the npm-debug.log file here?

Thanks in advance!

**Comment by jeffvautin** [comment]
… I just hit the same issue on macOS.

**Comment by Dadditude** [comment]
The only thing I can think it could be is that the guide calls for  Visual Studio 2015 on Windows, but the only download link I could find was for Visual Studio 2017, but i don't see how that could be the problem for you on Mac...

**Comment by kaytek** [comment]
For the first error you can find older versions of VS here: https://www.visualstudio.com/vs/older-downloads/
I used VSC 2015 w/ Update 3. 

I think you had the same issue that I had where you just had to update node. So try running `npm install -g npm@next` and then install homebridge again. It should work from there. GL!
