### ISSUE TITLE
homebridge error with 403: Forbidden

### ISSUE THREAD

**Issue by ItownTech** [nfarina/homebridge#1268]
Apr 30 00:27:27 [24816]: undefined:1
Apr 30 00:27:27 24816]: 403: Forbidden
Apr 30 00:27:27 [24816]: ^
Apr 30 00:27:27 [24816]: SyntaxError: Unexpected token : in JSON at position 3

**Comment by NorthernMan54** [comment]
This is an issue with your plugin, which plugin is it?  You may want to open an issue against the plugin.

**Comment by ItownTech** [comment]
homebridge-homeassistant

**Comment by NorthernMan54** [comment]
Looks like a config error with the plugin, please open an issue with the home-assistant plugin.

**Comment by ItownTech** [comment]
thanks
