### ISSUE TITLE
Homebridge-Domoticz-FibaroDimmer2

### ISSUE THREAD

**Issue by RCJN** [nfarina/homebridge#1269]
Hi all, 

I am new to domoticz and have been trying to get my fibaro dimmer 2 to work with homekit. 
Hopefully you can help me out. 

I am using the following setup
raspberry pi raspbian jessie lite
fibaro dimmer 2
aeotec z-stick

1. installed jessie lite
2. followed domoticz/homebridge installation steps  https://possible.tweakblogs.net/blog/14173/homebridge-en-domoticz-installeren-op-een-raspberry-pi#r_206585

3. included z-stick in domoticz
4. installed the plugin for fibaro HC2 (sudo npm install -g homebridge-fibaro-hc2)

Homebridge if visible in my homekit app but i says I need to identify an accessory. 

I assume I did something wrong in the homebridge/config.json. But I can't be sure. 

Please help.

**Comment by AppleTechy** [comment]
From what you posted it appears you have nothing wrong. If homebridge is visible you need to pair it to your phone which is the "identify an accessory".
