### ISSUE TITLE
cannot control aqara swith

### ISSUE THREAD

**Issue by mayat82** [nfarina/homebridge#1273]
Hi,
  I have installed homebridge on my raspberrt pi, and I can control any other aqara devices but only switch.
  Switch can be found on my homekit and can power on or power off, but the hardware don't have any response here.
  Did anyone occure same issue before?

**Comment by GeorgeBgk** [comment]
Wiki says 
> If you are expereincing errors with plugin, create an issue on plugin's repo

**Comment by theo-69** [comment]
@mayat82 having the same problem did you find a solution?

**Comment by mayat82** [comment]
@theo-69 finally I use domoticz to control all devices

**Comment by theo-69** [comment]
@mayat82 yep me two, working real good
