### ISSUE TITLE
can fibaro HCL integrated with homebridge??

### ISSUE THREAD

**Issue by audiocafe123** [nfarina/homebridge#1276]
hello ..
i have a fibaro HCl can it be integrated with homebridge??
what is the plugin used for fibaro HCl..
i find plugins for Fibaro HC2,will that work with HCl.
thanks you

**Comment by Mx-Razvan** [comment]
Yes - the fibaro HC2 plugin is working with HCL

**Comment by audiocafe123** [comment]
thanks for the information....
