### ISSUE TITLE
Homebridge listens on tcp6 only

### ISSUE THREAD

**Issue by dkrizic** [nfarina/homebridge#1277]
Hi,

I have two HomeBridge instances running. The problematic one is on Debian:

```
root@supermicro:/etc# netstat -an | grep 51828 | grep LISTEN
tcp6       0      0 :::51828                :::*                    LISTEN     
```

It listens on IPv6 only, but is advertised with IPv4 and IPv6:

```
root@supermicro:/etc# avahi-browse --verbose _hap._tcp | grep Supermicro
Server version: avahi 0.6.31; Host name: Supermicro.local
E Ifce Prot Name                                          Type                 Domain
+   eth1 IPv6 Homebridge Supermicro                         _hap._tcp            local
+   eth1 IPv4 Homebridge Supermicro                         _hap._tcp            local
+   eth0 IPv6 Homebridge Supermicro                         _hap._tcp            local
+   eth0 IPv4 Homebridge Supermicro                         _hap._tcp            local
```

Another instance on a Mac works fine:

```
➜  ~ netstat -an | grep 51826  
tcp46      0      0  *.51826                *.*                    LISTEN     
```

This one listens on both, IPv4 and IPv6 and is advertised as such. 

How can I force hombridge to use both, IPv4 and IPv6 or advertise IPv6 only?

**Comment by cybermerlo** [comment]
same issue here

**Comment by fuzzy01** [comment]
This the result of the way nodejs creates the server socket, see here:
(homebridge / hap-nodejs creates the server socket without specifying a hostname)

https://github.com/nodejs/node/issues/9390
and here
https://github.com/nodejs/node/commit/12cf3594235e6c4c6838ae7588b5e73ad9775dfa

It looks like the behaviour of nodejs on Ubuntu/Debian has changed, it opens only a tcp6 socket.

It is easy to test it, if you start a simple server:

```
node -e "net.createServer(c=>console.log).listen(5555)"

netstat -a | grep 5555
tcp6       0      0 [::]:5555               [::]:*                  LISTEN    
```

The solution is to modify hap-nodejs to create a tcp4 server socket or both.

**Comment by RobotLimeLtd** [comment]
fuzzy01's fix worked for me - thanks!

**Comment by Sailing74** [comment]
It just worked for me as well - thanks!

Any plans to include this into homebridge in some way?

**Comment by mrvnklm** [comment]
For everyone running the docker image, adding the following to `startup.sh` in your shared homebridge folder does the trick, even when the container is rebuilt:
`sed -i.bak "s/this._tcpServer.listen(targetPort);/this._tcpServer.listen(targetPort, '0.0.0.0');/" /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js
`

**Comment by ohmantics** [comment]
Fast forward a few years and this is still happening.

**Comment by jlindsey1** [comment]
Is there a fix for this in late 2022, as the solutions above do not seem to work any more.
Where do I find `bridge.bind`? grep is turning up nothing.

**Comment by vnnkl** [comment]
@jlindsey1 
the `bridge.bind` refers to the value that you can find in the `config.json` 

```
"bridge": {
        "name": "My Homebridge",
        "username": "YY:YY:YY:XX:XX:XX",
        "port": 51813,
        "pin": "1337-1337-1337",
        "advertiser": "ciao",
        "bind": [
            "0.0.0.0"
        ]
    },
```
