### ISSUE TITLE
Domoticz on/off switches and dimmers got mixed up

### ISSUE THREAD

**Issue by rhannink** [nfarina/homebridge#128]
Hello,

Within Domoticz I have 2 lights, one behind an on/off switch and one behind a dimmer. When connected to homebridge, the on/off light show up with dimmable aspects and the dimmable light shows up as an on/off light ??? Any idea what goes wrong here?

With kind regards,

Remco Hannink

**Comment by rhannink** [comment]
The problem described above is fixed. Thanks for this.
But the dimmers in Domoticz are not working correctly. The code says the values are changed from 0-100 to 0-16 steps, but 50% in a homekit app is 5-10% dim level with my lamp. It doesn't go any higher.

**Comment by nfarina** [comment]
Sounds like a percentage conversion problem - can you see from the logs what the underlying value HomeKit is setting is?

**Comment by rhannink** [comment]
Hello,

Where can I find the logs from Homebridge when I start it on the background ? Or do you mean the logs from domoticz ?

Gr. Remco

**Comment by rhannink** [comment]
I use Domoticz with a RFLink 433Mhz transceiver. The 433Mhz dimmers know 16 different levels. With Domoticz the dimmers work fine. I noticed that domoticz only sends the desired dim (eg 6) level while Homebridge also sends all the intermediate levels (eg 1-2-3-4-5-6 when dimming from 0 to 40%)
I can't get any useful information from the Domoticz logfile. Haven't found a Homebridge logfile when running homebridge in the background.

**Comment by rhannink** [comment]
Ok,
found something by running Hoemkit interactive. When I set a dimmer to 44% I see the following lines from homebridge:

```
 EventedHTTPServer [::ffff:192.168.1.106] HTTP request: /characteristics +15ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /characteristics +0ms
  Accessory [Homebridge] Processing characteristic set: {"characteristics":[{"aid":8,"iid":10,"value":44}]} +0ms
  Accessory [Homebridge] Setting Characteristic "Adjust Brightness of Light" to value 44 +0ms
[Domoticz] Slaapkamer Niels sending command setLevel with value 44
  EventedHTTPServer [::ffff:192.168.1.106] HTTP Repsonse is finished +1ms
  EventedHTTPServer [::ffff:192.168.1.106] HTTP request: /characteristics +50ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /characteristics +0ms
  Accessory [Homebridge] Processing characteristic set: {"characteristics":[{"aid":8,"iid":10,"value":44}]} +1ms
  Accessory [Homebridge] Setting Characteristic "Adjust Brightness of Light" to value 44 +0ms
[Domoticz] Slaapkamer Niels sending command setLevel with value 44
  EventedHTTPServer [::ffff:192.168.1.106] HTTP Repsonse is finished +1ms
[Domoticz] Slaapkamer Niels sent command setLevel
[Domoticz] Slaapkamer Niels sent command setLevel
[Domoticz] Slaapkamer Niels sent command setLevel
[Domoticz] Slaapkamer Niels sent command setLevel
[Domoticz] Slaapkamer Niels sent command setLevel
[Domoticz] Slaapkamer Niels sent command setLevel
[Domoticz] Slaapkamer Niels sent command setLevel
[Domoticz] Slaapkamer Niels sent command setLevel
[Domoticz] Slaapkamer Niels sent command setLevel
[Domoticz] Slaapkamer Niels sent command setLevel
[Domoticz] Slaapkamer Niels sent command setLevel
[Domoticz] Slaapkamer Niels sent command setLevel
[Domoticz] Slaapkamer Niels sent command setLevel
[Domoticz] Slaapkamer Niels sent command setLevel
[Domoticz] Slaapkamer Niels sent command setLevel
[Domoticz] Slaapkamer Niels sent command setLevel
[Domoticz] Slaapkamer Niels sent command setLevel
[Domoticz] Slaapkamer Niels sent command setLevel
[Domoticz] Slaapkamer Niels sent command setLevel
[Domoticz] Slaapkamer Niels sent command setLevel
[Domoticz] Slaapkamer Niels sent command setLevel
[Domoticz] Slaapkamer Niels sent command setLevel
[Domoticz] Slaapkamer Niels sent command setLevel
[Domoticz] Slaapkamer Niels sent command setLevel
[Domoticz] Slaapkamer Niels sent command setLevel
[Domoticz] Slaapkamer Niels sent command setLevel
[Domoticz] Slaapkamer Niels sent command setLevel
[Domoticz] Slaapkamer Niels sent command setLevel
[Domoticz] Slaapkamer Niels sent command setLevel
[Domoticz] Slaapkamer Niels sent command setLevel
[Domoticz] Slaapkamer Niels sent command setLevel
[Domoticz] Slaapkamer Niels sent command setLevel
```

Looks like it still is sending 0-100 instead of 0-16 And all intermediate levels are sent also.......

**Comment by lukeredpath** [comment]
I'm also seeing this, dimmers simply don't work properly as its not respecting the dimmer scale.

**Comment by lukeredpath** [comment]
@rhannink this should now be fixed by #169 which has been merged.

**Comment by rhannink** [comment]
Hey,

lukeredpath,

Thanks for your update, it is working better now. 0-100% is now now 0-100% in Domoticz. But it is working very slow, because when I slide the dimmer in an homebridge app from 0-50%, this results in 50 messages from Homebridge to domoticz with all the intermediate levels. Dimming from 0-50% takes about 10-25 secs. Domoticz just sends the required level. So when I set the slider in Domoticz to 50% one message is being sent to the dimmer go to 50%. The dimmer itself slowly increases to 50% in about 1-2 secs.

Is it possible to get this behavior ?

Gr. Remco

**Comment by lukeredpath** [comment]
Unfortunately this is down to the implementation in the app you're using and has nothing to do with HomeKit or HomeBridge.

**Comment by snowdd1** [comment]
Well, you could try to intercept if the user is still sliding, so if the command has not been sent (and I understand it is piling up wait times) abort it (and the wait time) if another command for the same characteristic is in the pipeline.
