### ISSUE TITLE
New accessory in SmartThings not showing up in HomeKit 

### ISSUE THREAD

**Issue by rchoughton** [nfarina/homebridge#1281]
I have added a new accessory to SmartThings.  I do not know how to get HomeKit to pull in that new accessory into the HomeBridge accessory. If I remove the HomeBridge accessory and then add it again to HomeKit it finds it. I just do not want to do all the reconfiguration every time I make a SmartThings change.

**Comment by rchoughton** [comment]
Found my issue. Needed to go into SmartApps in SmartThings app and select new device to show.

**Comment by ElanX** [comment]
@rchoughton Can you explain how you fixed it? Having a similar issue.

**Comment by rchoughton** [comment]
To be honest, I have not been able to. I plan to soon go back and delete it all and start over and see if that works.
