### ISSUE TITLE
Homebridge just quit and won't restart

### ISSUE THREAD

**Issue by burtamcgna** [nfarina/homebridge#1285]
Homebridge, running on UBUNTU 16.x has been running steadily for ~2-3 weeks zero issues.  I have not added a component in more than 1 week.

tonight is stopped and I rebooted and tried to start.  It gets to loading the Smartthings devices, does the final smartthings "direct Connect" load and then simply stops loading further....no errors, nothing.  

Seen this?  Where are the logs for this?

**Comment by jarvismeier** [comment]
same problem..  it stops after parsing all my devices and does not show the home bridge PIN code.  If i delete my config.json it starts working but as soon as i recreate it then the problem re-occurs.

**Comment by schmittx** [comment]
I'm suddenly experiencing similar issues with Homebridge and Home Assistant plugin. Maybe it's something on Apple's system side?

**Comment by jarvismeier** [comment]
delete or rename your config.json and see if it fully loads.

**Comment by sleepyarmistice** [comment]
I have the exact same situation. I can also get it to load by removing the confit file. Tried deleting the persist and accessories folders for good measure, but that didn't make any difference.

**Comment by schmittx** [comment]
@jarvismeier Renaming my config.json and deleting cached accessories fixed the problem. I reinstated the config.json and the problem reappeared.

**Comment by mgawley4** [comment]
Same problem for me too. Deleted cached accessories, renamed config file, homebridge starts. Reinstate config file, broken again. Homebridge has been running great for months until tonight. I have homebridge running on a Mac.

**Comment by B1tMaster** [comment]
Generate new MAC address for id in ur confg.json.

**Comment by jarvismeier** [comment]
@B1tMaster Already tried... problem still exists.  There is a bigger issue going on.

**Comment by SnapdGIT** [comment]
Just thought I'd chip in and add i'm experiencing the same issue. Homebridge crashed at about 4am (UK time) this morning and now won't show the HomeKit PIN when it's restarted. I have Homebridge running on a Mac.

**Comment by phpdiddy** [comment]
Same here. Just all the sudden stopped working. Nothing in logs to indicate why it stopped.

**Comment by B1tMaster** [comment]
I have it running on Raspberry Pi with home assistant-homebridge plugin and it keeps running normally. It is bizarre that everybody who was affected is running on a MAC OS.  Check to see if any security updates were pushed by Apple last night?

**Comment by samu12345** [comment]
Experiencing exact same issue on Raspberry Pi...

**Comment by KhaosT** [comment]
Can you guys share what plugins are you using? It feels like one of the API vendor changed something and breaks a specific plugin which causes the issue.

**Comment by jamieshaw** [comment]
Same issues here. No pin displayed, using:

```
homebridge@0.4.20
homebridge-homeassistant@2.1.0
homebridge-info@1.1.1
homebridge-nest@1.1.2
homebridge-platform-wemo@1.2.0
homebridge-server@1.0.24
homebridge-websocket@0.1.13
```

Prior to this morning, everything has been fine.

**Comment by gizbod** [comment]
Same issue with me running on Rpi. 
Also running Nest so could be the cause somehow.

**Comment by ToddGreenfield** [comment]
Try removing all plugins except something simple like homebridge-delay-switch from the config.json and see if homebridge starts. Then start adding back one at a time to see which is the culprit plugin.

**Comment by jamieshaw** [comment]
Added Nest back broke HB again. Definitely Nest in my configuration.

Interestingly, Home Assistant isn't having any issues connecting to Nest. HB and HA both have the same level of permissions. Must be something within the plugin...

**Comment by gizbod** [comment]
Removed Nest from mine and working fine. I agree seems something to do with the Nest plugin is causing the problem.

**Comment by sleepyarmistice** [comment]
I'm running homebridge-harmonyhub, home bridge-nest, homebridge-netatmo, homebridge-people, homebridge-platform-wemo, and homebridge-server on an rpi. 

Removing nest from my config file lets it load properly, which is a real drag.

**Comment by jamieshaw** [comment]
Looks like the issue over on the [https://github.com/KraigM/homebridge-nest/issues/125](homebridge-nest) page.  Does look as though that repo has gone stale over the past 12 months – I hope this doesn't fall by the wayside.

**Comment by burtamcgna** [comment]
I removed NEST and mine's working now.

**Comment by brownad** [comment]
Bit of a workaround, but using homeassistant plugin to serve up nest (and many more plugins) instead of the broken Nest plugin saved the day for me

**Comment by jamieshaw** [comment]
> Bit of a workaround, but using homeassistant plugin to serve up nest (and many more plugins) instead of the broken Nest plugin saved the day for me

This does work, but it doesn't quite work as smoothly.  My house is currently in "Eco" at the moment (which is reflected by a 10º "level").  Turning the thermostat in HomeKit doesn't turn it off in Home Assistant however.

Certainly better than nothing at this stage, however.

**Comment by burtamcgna** [comment]
I turned HomeAssistant off months ago.  Can someone explain the benefits of HA?  Besides accessing things from a computer/webpage (which seems pretty boring to me?)   I get that right now loading HA would give me access to the Nest device in Homebridge, but HA itself seems pretty useless overall.

**Comment by brownad** [comment]
Comparing the plugin development to HA - its pretty obvious which one moves faster, granted the experience in HA is not HomeKit, but having a single route to serve up all the plugins is way better than lots of poorly supported plugins.  Its getting better every release for the homekit usage, worth watching.  Unless the siloed plugin development leaps forward - doubt  it though, the developers have left it aside and no way to commit changes forward.

**Comment by jamieshaw** [comment]
Automation and scripting.

HomeKit automation is pretty basic; if this then that.  I've got some advanced automations set up in Home Assistant that, for example:
• Change the 'arrival' scene of a person depending on where they arrived from e.g. Light bedroom is home from gym.
• Preheat the home if a threshold is crossed, and travelling towards home (but stop after the estimated time until arrival is passed – they're not coming home...)
• Set different morning routines based on whether it's a workday, weekend, public holiday or if my work calendar has a vacation scheduled.

**Comment by burtamcgna** [comment]
I agree that Automation in Homekit is really terrible (er....basic).  So basic I use my smartthings hub for most automation.

**Comment by brownad** [comment]
HA is about to make rule creation a lot easier, in time it will eclipse most platforms out there, especially the plugin availability its grown massively, nothing out there compares

**Comment by jarvismeier** [comment]
nest plugin works if you delete the token, client, and code lines.  it will fall back to legacy API.  make sure you have
"username" : "nest@username.com",
"password" : "your secret nest password"

**Comment by jamieshaw** [comment]
Apparently not if you have two-factor enabled; it's just rapidly firing requests off and triggering SMS auth codes. Hmmm...

**Comment by starlessblack** [comment]
So did the Nest plugin developer use an API that is now deprecated by Nest or something? How can we resolve this (besides falling back to legacy mode which Nest will surely deprecate at some point)?

**Comment by starlessblack** [comment]
See also this issue on Nest plugin page: https://github.com/KraigM/homebridge-nest/issues/125

**Comment by starlessblack** [comment]
Anyone try regenerating the client token of the homebridge nest plugin?

**Comment by Tiger519** [comment]
@mgawley4 I'm experiencing the same thing. Was working fine for months and despite anything I've done, I haven' been able to get it to run for more than a few minutes since last Thursday. No idea what is going on here.

**Comment by samu12345** [comment]
@Tiger519 I never found the culprit, as I don't have the Nest plugin. I ended up formatting my Pi's SD card and installing Raspbian and Homebridge again. Works great now.

**Comment by h00pak** [comment]
I'm interested in using the Home Assistant plug in for home bridge. I currently have the smartthings and nest plug ins installed. Can anyone tell me, please, if I need to uninstall those to use Home Assistant? Thanks, Robby

**Comment by jamieshaw** [comment]
@h00pak You can have as many plugins installed in Homebridge as you'd like, but you may find duplicate entries for your devices e.g. one thermostat from Home Assistant, and one from the Nest plugin itself.  In my case, I use the Nest plugin and apply "homebridge-hidden: True" to the thermostat in Home Assistant to hide it.
