### ISSUE TITLE
Launchd

### ISSUE THREAD

**Issue by Patrick1610** [nfarina/homebridge#1291]
Hi, 

Somehow I cannot get the launchctl thing to Work and get the following message when I try to load it: 

Patricks-Mac-Mini:~ patrickvanbavel$ launchctl load ~/Library/LaunchAgents/com.homebridge.server.plist
/Users/patrickvanbavel/Library/LaunchAgents/com.homebridge.server.plist: Invalid or missing service identifier

Any idea what this could be and how to fix it? 
This would be the last aspect to finish my Homebridge Setup. 

Regards Patrick

**Comment by Patrick1610** [comment]
I've tried to edit Some of the plist settings but nothing helped. 
The plist i've copied from https://github.com/nfarina/homebridge/wiki/Install-Homebridge-on-macOS also didn't Work. 

Anyone any clue what could be happening?

**Comment by Patrick1610** [comment]
Anyone..?

**Comment by fabvis** [comment]
try with this plist file

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>homebridge</string>
  <key>ProgramArguments</key>
  <array>
       <!-- Modify these two lines to reflect your node location and homebridge install location -->
       <string>/usr/local/bin/node</string>
       <string>/usr/local/bin/homebridge</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
</dict>
</plist>
```

**Comment by DJay79** [comment]
@fabvis Thanks. This saved me a lot of time today. 👍🏻❤️

**Comment by vdrover** [comment]
I have this problem. The alternate plist above did not work for me.

**Comment by gaojie429** [comment]
@vdrover 
did you install node by using "nodebrew"?
If so, you have to replace `<string>/usr/local/bin/node</string>` to `<string>/Users/xxxxx/.nodebrew/current/bin/node</string>`.
*you also have to change "xxxxx" to your use name on this code.
