### ISSUE TITLE
Init.d Fails to launch Homebridge (Ubuntu 16.04)

### ISSUE THREAD

**Issue by alucarddelta** [nfarina/homebridge#1293]
Hi,

Im using Ubuntu 16.04 server to run Homebridge. How ever I get the following errors.

> root@Micro:~# systemctl status homebridge.service
> ● homebridge.service - LSB: Start daemon at boot time
>    Loaded: loaded (/etc/init.d/homebridge; bad; vendor preset: enabled)
>    Active: failed (Result: exit-code) since Tue 2017-05-16 11:56:20 AEST; 17s ago
>      Docs: man:systemd-sysv-generator(8)
>   Process: 1383 ExecStart=/etc/init.d/homebridge start (code=exited, status=1/FAILURE)
> 
> May 16 11:56:20 Micro systemd[1]: Starting LSB: Start daemon at boot time...
> May 16 11:56:20 Micro homebridge[1383]: Starting
> May 16 11:56:20 Micro homebridge[1383]: /etc/init.d/homebridge: 35: /etc/init.d/homebridge: cannot create : Directory nonexistent
> May 16 11:56:20 Micro homebridge[1383]: Unable to start, see  and
> May 16 11:56:20 Micro homebridge[1383]: /etc/init.d/homebridge: 33: /etc/init.d/homebridge: cannot create : Directory nonexistent
> May 16 11:56:20 Micro systemd[1]: homebridge.service: Control process exited, code=exited status=1
> May 16 11:56:20 Micro systemd[1]: Failed to start LSB: Start daemon at boot time.
> May 16 11:56:20 Micro systemd[1]: homebridge.service: Unit entered failed state.
> May 16 11:56:20 Micro systemd[1]: homebridge.service: Failed with result 'exit-code'.

> root@Micro:/etc/init.d# tail /var/log/homebridge.log
> root@Micro:/etc/init.d# tail /var/log/homebridge.err
> root@Micro:/etc/init.d# /var/run/homebridge.pid
> bash: /var/run/homebridge.pid: No such file or directory

I am using 
```
dir="/var/homebridge"
cmd="DEBUG=* /usr/local/bin/homebridge -U /var/homebridge"
user="homebridge"
```

As which is telling me 
```
root@Micro:~# which homebridge
/usr/local/bin/homebridge
```
Running the `homebridge` command works normally. Am I doing something wrong?

**Comment by alucarddelta** [comment]
full init.d file

> #!/bin/sh
> ### BEGIN INIT INFO
> # Provides: Homebridge
> # Required-Start:    $remote_fs $syslog
> # Required-Stop:     $remote_fs $syslog
> # Default-Start:     2 3 4 5
> # Default-Stop:      0 1 6
> # Short-Description: Start daemon at boot time
> # Description:       Enable service provided by daemon.
> ### END INIT INFO
> 
> dir="/var/homebridge"
> cmd="DEBUG=* /usr/local/bin/homebridge -U /var/homebridge"
> user="homebridge"
> get_pid() {
>     cat "$pid_file"
> }
> 
> is_running() {
>     [ -f "$pid_file" ] && ps `get_pid` > /dev/null 2>&1
> }
> 
> case "$1" in
>     start)
>     if is_running; then
>         echo "Already started"
>     else
>         echo "Starting $name"
>         cd "$dir"
>         if [ -z "$user" ]; then
>             sudo $cmd >> "$stdout_log" 2>> "$stderr_log" &
>         else
>             sudo -u "$user" $cmd >> "$stdout_log" 2>> "$stderr_log" &
>         fi
>         echo $! > "$pid_file"
>         if ! is_running; then
>             echo "Unable to start, see $stdout_log and $stderr_log"
>             exit 1
>         fi
>     fi
>     ;;
>     stop)
>     if is_running; then
>         echo -n "Stopping $name.."
>         kill `get_pid`
>         for i in {1..10}
>         do
>             if ! is_running; then
>                 break
>             fi
> 
>             echo -n "."
>             sleep 1
>         done
>         echo
> 
>         if is_running; then
>             echo "Not stopped; may still be shutting down or shutdown may have failed"
>             exit 1
>         else
>             echo "Stopped"
>             if [ -f "$pid_file" ]; then
>                 rm "$pid_file"
>             fi
>         fi
>     else
>         echo "Not running"
>     fi
>     ;;
>     restart)
>     $0 stop
>     if is_running; then
>         echo "Unable to stop, will not attempt to start"
>         exit 1
>     fi
>     $0 start
>     ;;
>     status)
>     if is_running; then
>         echo "Running"
>     else
>         echo "Stopped"
>         exit 1
>     fi
>     ;;
>     *)
>     echo "Usage: $0 {start|stop|restart|status}"
>     exit 1
>     ;;
> esac
> 
> exit 0

**Comment by snowdd1** [comment]
Why are using init file for a systemd system?

**Comment by alucarddelta** [comment]
I was just following the instructions in the Homebridge Wiki page.

**Comment by snowdd1** [comment]
Your Ubuntu 16.4 is more like the Raspbian in these instructions: https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi#running-homebridge-on-bootup-systemd

The instructions you've followed was for Ubuntu 14.4 which was a [init.d-system](https://en.wikipedia.org/wiki/Init#SysV-style), and most major Linux distributions switched to [systemd](https://en.wikipedia.org/wiki/Systemd) in or around 2015.
