### ISSUE TITLE
Got SIGTERM?

### ISSUE THREAD

**Issue by joq3** [nfarina/homebridge#1294]
Hi,

I use Homebridge on my Debian server.
Right now it works, but it shuts down and restarts all the time.
This is the message in the log:
[5/18/2017, 7:40:10 AM] Got SIGTERM, shutting down Homebridge...

After this it starts up again and the same thing happens over and over.

Any ideas?

**Comment by KhaosT** [comment]
Your system is keep trying to kill homebridge... You need to figure out where that SIGTERM is coming from.

**Comment by joq3** [comment]
Could it be my init.d settings?
Because I want it to shut down and restart when Homebridge-Harmonyhub crashes, which happens all the time (the plugin isn't updated in a while).
This is my init.d/homebridge:
https://pastebin.com/PjmKUnGe

**Comment by KhaosT** [comment]
I'm not really familiar with init.d script so can't help with that... Hope somebody else see this and can answer the question.

**Comment by joq3** [comment]
Is it possible to hide the erros Homebridge always creates? That way it would restart when a real error appears? Because that is what I'm thinking, Homebridge starts, creates the usual errors:
`*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
`

**Comment by KhaosT** [comment]
@joq3 this is a warning created by Avahi. If you like, you can hide it by setting env variable `AVAHI_COMPAT_NOWARN` to 1.

**Comment by joq3** [comment]
Where would I put this setting?

**Comment by KhaosT** [comment]
@joq3 ask [Google](http://stackoverflow.com/questions/3864877/how-can-i-set-environment-variables-in-my-linux-service-for-asterisk-even-though)?

**Comment by joq3** [comment]
Tried adding this line:
AVAHI_COMPAT_NOWARN=1
In /etc/init.d/homebridge without any success?
