### ISSUE TITLE
Homebridge/homebridge-indigo details don't survive MacOS update

### ISSUE THREAD

**Issue by dscottbuch** [nfarina/homebridge#1295]
I've got things configured so homebridge is running under launchctl, as is Indigo server. Everything works great with restarting on reboot, keeping homebridge up and running, etc. Through any reboot etc. the HomeKit database is maintained and scenes and room associations are fine BUT if I do a system OS upgrade then all the associated data goes missing, Room assignments, scenes, all the accessories are no longer associated with automations, etc.

I've verified that the UUIDs assigned by Homebridge are properly maintained, they don't change, BUT the uniqueIdentifiers in the HomeKit do change when this happen. Weirdly, not for every accessory but for most.  They don't change during reboots and the like.

I've also confirmed that the persist directory is not removed.  All of the UUID's in the Accessory.XXX.json are maintained including for paired clients and the name of the Accessory.XXX.json file is maintained.  The only difference in the Accessory.XXX.json file before/after the MacOS upgrade was the configVersion.  It went from 26 to 28.  The config hash did not change.

Note I don't lose the devices themselves, they are all there, just any associations I've created in the Home app such as room assignments, scenes, and associations with automations. The automations are still there they just no longer have any device associated with them and are therefore disabled.

I can't find decent documentation as to how these are assigned and maintained by HomeKit so I'm looking for help in that area. I know that the uniqueIdentifier are different from IOS device to IOS device so I'm caching them on each device for comparison, which is how I know they're changing.

Thanks in advance for any help.

**Comment by dscottbuch** [comment]
Once again, on update 10.12.6 everything was bolloxed as described above.  Any help on at least where to look/debug would be greatly appreciated.

**Comment by dscottbuch** [comment]
I thought that I may have found an underlying reason for this happening. On upgrading to iOS 11 on my iPad I found that one device was consistently being removed from the home. I would add it back  by restarting homebridge and then a short while later they would be gone. I would be adding it back on iOS 10.

Then I noticed that in iOS 11 that device, before it was removed, appeared as an accessory, a home, and it was marked as not allowed. It seems that the name is a reserved name. I had named my front door as "Entry". Since changing the name to "Front Entry" everything seems to be working.

Everything was humming along fine through a number of reboots until I updated to the latest Sierra Beta and, once again, all the rom and automation connections vanished. Does anyone have a hint as to where in the code I can/should look? Very frustrating.

**Comment by dscottbuch** [comment]
Just went through an update to the latest 12.6 beta - 10.12.6 Beta (16G23a) and had the problem.  I've compared the UUID's assigned by homebridge-indigo before and after - they are Identical.  I've compared the Accessories and Identities persist files before and after and they are NOT QUITE identical. 

 In the Accessories there are two differences.  
<     [configVersion] => 13
<     [configHash] => 4a142ddf95a2f0b329242e491d24f8a94e1f9089
---
>     [configVersion] => 11
>     [configHash] => 6a2cb3b957ed58976cd3e369eca5e785a4308b09
 where left is after and right is before.

In the Identities all of the 'Top Level' Key-Value pair for each accessory has changed the value, not the key.

15,16c15,16
<             [|nextAID] => 31
<             [148089d9-7298-478c-8149-bcf4ff55ef65] => 2
---
>             [|nextAID] => 33
>             [148089d9-7298-478c-8149-bcf4ff55ef65] => 30
31c31
<             [e5f476ab-ed57-49e0-9d03-a71a5611d764] => 3
---
>             [e5f476ab-ed57-49e0-9d03-a71a5611d764] => 29
47c47
<             [ca3ba660-f9b5-4f2d-b6e9-5169a039d2b1] => 4
---
>             [ca3ba660-f9b5-4f2d-b6e9-5169a039d2b1] => 2
62c62
<             [6ce53d5e-1388-42d0-a05d-99f1ec3012ab] => 5
---
>             [6ce53d5e-1388-42d0-a05d-99f1ec3012ab] => 3
77c77
<             [c1665f28-b87f-4283-9079-01fefc18b879] => 6
---
>             [c1665f28-b87f-4283-9079-01fefc18b879] => 4
92c92
<             [73662ca6-8974-4763-a93e-b6c727f8d9ba] => 7
---
>             [73662ca6-8974-4763-a93e-b6c727f8d9ba] => 5
107c107
<             [d907785c-3a00-4811-ab9a-093f1073bb33] => 8
---
>             [d907785c-3a00-4811-ab9a-093f1073bb33] => 6
122c122
<             [5ce3b746-a1a8-4893-9b50-c280f776a5bc] => 9
---
>             [5ce3b746-a1a8-4893-9b50-c280f776a5bc] => 31
137c137
<             [b3286ca0-a804-475c-b7d8-c8f7cf170d33] => 10
---
>             [b3286ca0-a804-475c-b7d8-c8f7cf170d33] => 8
152c152
<             [78cdde06-23de-4f1d-bba0-cfcc13acd35b] => 11
---
>             [78cdde06-23de-4f1d-bba0-cfcc13acd35b] => 28
168c168
<             [f0373057-c86b-4406-a85a-f25ce252468d] => 12
---
>             [f0373057-c86b-4406-a85a-f25ce252468d] => 9
183c183
<             [45c45507-e87f-4a9d-8d15-841ba2dc537d] => 13
---
>             [45c45507-e87f-4a9d-8d15-841ba2dc537d] => 10
199c199
<             [06529022-4b63-48af-a3e4-feee4d8a18d4] => 14
---
>             [06529022-4b63-48af-a3e4-feee4d8a18d4] => 11
214c214
<             [13d41697-9e0e-4b8a-9061-9074b69fb8ce] => 15
---
>             [13d41697-9e0e-4b8a-9061-9074b69fb8ce] => 12
230c230
<             [9e968f7b-ef26-491d-a5b9-09368244e8f9] => 16
---
>             [9e968f7b-ef26-491d-a5b9-09368244e8f9] => 13
246c246
<             [f0f66ff0-2a91-4f3f-9391-3fdc1b43e90e] => 17
---
>             [f0f66ff0-2a91-4f3f-9391-3fdc1b43e90e] => 14
262c262
<             [b96118cf-283e-43fd-8b98-48dbb2bddb22] => 18
---
>             [b96118cf-283e-43fd-8b98-48dbb2bddb22] => 15
278c278
<             [8f602650-9fdb-4b98-8eae-01a8f1f64834] => 19
---
>             [8f602650-9fdb-4b98-8eae-01a8f1f64834] => 16
293c293
<             [7a3e4ebd-55c0-4848-a3bd-78652b6c53ce] => 20
---
>             [7a3e4ebd-55c0-4848-a3bd-78652b6c53ce] => 17
308c308
<             [24bed4cb-a7d1-42e7-a179-4d2144c17804] => 21
---
>             [24bed4cb-a7d1-42e7-a179-4d2144c17804] => 18
323c323
<             [84a3cacd-6de6-44bb-9935-ad7483360e5e] => 22
---
>             [84a3cacd-6de6-44bb-9935-ad7483360e5e] => 19
338c338
<             [ca09fb5a-4663-4683-9188-08002fcffc49] => 23
---
>             [ca09fb5a-4663-4683-9188-08002fcffc49] => 20
353c353
<             [ca87e13e-2649-401a-ae0b-beb631c57b8e] => 24
---
>             [ca87e13e-2649-401a-ae0b-beb631c57b8e] => 21
368c368
<             [dd49ad44-76ba-452f-9171-6a4d91913069] => 25
---
>             [dd49ad44-76ba-452f-9171-6a4d91913069] => 22
383c383
<             [a615b603-122b-4c1e-b3c7-087113aa1663] => 26
---
>             [a615b603-122b-4c1e-b3c7-087113aa1663] => 23
398c398
<             [8a877522-f045-46f5-aecd-6800db395f03] => 27
---
>             [8a877522-f045-46f5-aecd-6800db395f03] => 24
413c413
<             [e27fc1cf-7eea-41f8-9cb1-b3f43d22114e] => 28
---
>             [e27fc1cf-7eea-41f8-9cb1-b3f43d22114e] => 25
428c428
<             [c9d17b45-91eb-4998-ac89-19a55009d060] => 29
---
>             [c9d17b45-91eb-4998-ac89-19a55009d060] => 26
443c443
<             [923a3ad3-62aa-4d09-b129-11dd695b9d3c] => 30
---
>             [923a3ad3-62aa-4d09-b129-11dd695b9d3c] => 27

I'm working my way through the code but again, any help would be greatly appreciated.

**Comment by dscottbuch** [comment]
Any thoughts?

**Comment by danielsen2009** [comment]
Having similar issues with os updates. No solution so far.

**Comment by webdeck** [comment]
I am hoping this PR on HAP-NodeJS addresses the underlying issue: https://github.com/KhaosT/HAP-NodeJS/pull/491
