### ISSUE TITLE
Change accessory type from Switch to Garage Door

### ISSUE THREAD

**Issue by rahalb** [nfarina/homebridge#1297]
Hi, I was hoping someone can tell me if this is possible. 

Right now my current setup is: Garage Door <---WeMo Switch--->IFTTT--->HomeBridgeIFTTT.

Everything is working well, but my question is, is there any way to change the accessory type in the Home app from a switch to a Garage Door?

Currently, I can tell Siri to "turn on/off Garage Door" but when I say open or close garage door it says that its not possible.

Im wondering if I can alter the HomebridgeIFTTT plugin to change the accessory type, or if there is any other fix that I can do. Thanks!

**Comment by GvnCampbell** [comment]
You would have to modify the homebridge-ifttt plugin and change it to a garage door accessory type.  However that may require more than just a few lines of code as the Characteristics are different.

Another thing to note is that changing it to a garage door also changes the way it works with Siri for security reasons.  To open a garage door accessory with Siri your phone must be unlocked.  Just throwing that in there as it bugs me sometimes but I can see why they did it.

**Comment by rahalb** [comment]
Okay thanks for the feedback, I appreciate it.

**Comment by daniel2029** [comment]
i need help with this too

**Comment by vsidlu** [comment]
I have wemo Make as gate opener. I use https://github.com/rudders/homebridge-platform-wemo for all my Wemo devices.
When you use this homebridge-platform-wemo plugin it recognizes your make as switch or door opener.

If SwitchMode == Momentary, I configure the device as Service.GarageDoorOpener.
If SwitchMode == Toggle, I configure the device as Service.Switch. Additionally, if SensorPresent == 1, I also add Service.ContactSensor.

But I suggest to stay as switch - as it is working from locked iPhone.

I have also ifttt for wemo Make and Siri opens gate when I asks. Try to change name of swithc to OPEN GATE. 

hope it will help - more info about this matter - https://github.com/rudders/homebridge-platform-wemo/issues/62
