### ISSUE TITLE
Can find the device in Home app but cannot pair.

### ISSUE THREAD

**Issue by frannnnk** [nfarina/homebridge#1301]
I finish set up and using the Home app can see the device configured, but it take one minutes to pari and then say fail to connect to this device. no output at homebridge console. 

anything i can do? tried every possible way like restart, remove the device and persist dir but non of them works.

**Comment by snowdd1** [comment]
I had this while developing my platform, when accessories return illegal values during initial scan. Some HomeKit apps give more detailed error messages on pairing.  
You need to find out which accessory/platform is the culprit.
