### ISSUE TITLE
Connecting 2 iDevices to Homebridge

### ISSUE THREAD

**Issue by lupe** [nfarina/homebridge#1302]
Have Homebridge setup on a Pi with some basic plugins for testing.

It's working fine with one iPhone connected. but it doesn't show up on a second iDevice. I've reset Homebridge and it shows up on **both** devices, but as soon as I connect (either) one it disappears from list of available devices on the other.

Is this expected behaviour or have I missed something obvious?

If it's relevant the two iDevices are using different Apple IDs

Thanks.

**Comment by NorthernMan54** [comment]
For the second idevice you will need to invite them as a guest thru the Home app.

**Comment by lupe** [comment]
Ah I see, didn't realise that. Thanks.
