### ISSUE TITLE
Optional characteristics don't get persisted.

### ISSUE THREAD

**Issue by ebaauw** [nfarina/homebridge#1304]
I'm (finally) changing my plugins to use dynamic platform accessories.

I find that optional characteristics don't get persisted to `~/.homebridge/accessories/cachedAccessories`.  This causes `Service.getCharacteristic()` to behave differently for restored vs newly created services.  For a newly created service, it creates and returns the optional characteristic, for a restored service, it returns `undefined`(when the optional characteristic wasn't created in a previous session).

Is this intentional?

**Comment by KhaosT** [comment]
Yep, it's intentional. Is there a particular reason that you cannot add all needed optional characteristics when you register accessory?

**Comment by ebaauw** [comment]
New device firmware or device bridge software supporting additional optional characteristics.  Granted, that won't happen daily ;-).

**Comment by KhaosT** [comment]
In that case, instead of rely on optional characteristics, you can probably create characteristic object yourself and add it to the service since it won't happen frequently.

**Comment by ebaauw** [comment]
Thanks, that's what I figured.  I now do a
```json
(service.getCharacteristic(optChar) || service.addCharacteristic(optChar)).setValue(value);`
```
