### ISSUE TITLE
same uuid

### ISSUE THREAD

**Issue by sirdir1972** [nfarina/homebridge#1305]
All of a sudden, homebridge stopped working with the following message:

`Mai 26 02:40:11 cs homebridge[13984]: [2017-5-26 02:40:11] [netatmo platform] Initializing platform accessory 'Finca Benissa Wohnzimmer'...
Mai 26 02:40:11 cs homebridge[13984]: [2017-5-26 02:40:11] [netatmo platform] Initializing platform accessory 'Finca Benissa Aussen'...
Mai 26 02:40:11 cs homebridge[13984]: [2017-5-26 02:40:11] [netatmo platform] Initializing platform accessory 'Finca Benissa Schlafzimmer Ursula'...
Mai 26 02:40:11 cs homebridge[13984]: [2017-5-26 02:40:11] [netatmo platform] Initializing platform accessory 'Finca Benissa Niederschlagsmesser'...
Mai 26 02:40:11 cs homebridge[13984]: [2017-5-26 02:40:11] [netatmo platform] Initializing platform accessory 'Finca Benissa Schlafzimmer Patrick'...
Mai 26 02:40:11 cs homebridge[13984]: [2017-5-26 02:40:11] [netatmo platform] Initializing platform accessory 'Finca Benissa Wind'...
Mai 26 02:40:11 cs homebridge[13984]: [2017-5-26 02:40:11] [netatmo platform] Initializing platform accessory 'Heizung Finca Benissa'...
Mai 26 02:40:11 cs homebridge[13984]: [2017-5-26 02:40:11] [netatmo platform] Initializing platform accessory 'Finca Benissa'...
Mai 26 02:40:11 cs homebridge[13984]: [2017-5-26 02:40:11] [netatmo platform] Initializing platform accessory 'Heizung Finca Benissa'...
Mai 26 02:40:11 cs homebridge[13984]: /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:228
Mai 26 02:40:11 cs homebridge[13984]:       throw new Error("Cannot add a bridged Accessory with the same UUID as another bridged Accessory: " + existing.UUID);
Mai 26 02:40:11 cs homebridge[13984]:       ^
Mai 26 02:40:11 cs homebridge[13984]: Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 91ddd316-2fe3-40df-8ce8-d9e4cac3064c
Mai 26 02:40:11 cs homebridge[13984]:     at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:228:13)
Mai 26 02:40:11 cs homebridge[13984]:     at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:367:24)
Mai 26 02:40:11 cs homebridge[13984]:     at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:16:19
Mai 26 02:40:11 cs homebridge[13984]:     at NetatmoPlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-netatmo/index.js:56:7)
Mai 26 02:40:11 cs homebridge[13984]:     at /usr/local/lib/node_modules/homebridge-netatmo/node_modules/async/dist/async.js:3679:13
Mai 26 02:40:11 cs homebridge[13984]:     at /usr/local/lib/node_modules/homebridge-netatmo/node_modules/async/dist/async.js:952:25
Mai 26 02:40:11 cs homebridge[13984]:     at iteratorCallback (/usr/local/lib/node_modules/homebridge-netatmo/node_modules/async/dist/async.js:997:17)
Mai 26 02:40:11 cs homebridge[13984]:     at /usr/local/lib/node_modules/homebridge-netatmo/node_modules/async/dist/async.js:847:20
Mai 26 02:40:11 cs homebridge[13984]:     at /usr/local/lib/node_modules/homebridge-netatmo/node_modules/async/dist/async.js:3676:17
Mai 26 02:40:11 cs homebridge[13984]:     at /usr/local/lib/node_modules/homebridge-netatmo/node_modules/async/dist/async.js:339:31
Mai 26 02:40:11 cs systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
Mai 26 02:40:11 cs systemd[1]: homebridge.service: Unit entered failed state.
Mai 26 02:40:11 cs systemd[1]: homebridge.service: Failed with result 'exit-code'.
`

I already tried to delete the acessories subdir, that didn't help.

**Comment by sirdir1972** [comment]
Still the same problem. Somehow I think it's adding the heating twice.

**Comment by Trunks78** [comment]
Hi sirdir1972, after months I've finally found a solution to this error.
In the netatmo app be sure that Home, Relay, Room and Thermostat DON'T have the same name.
For me the problem was that Home and Relay were both named "Casa"; renaming the Relay to "Relè" solved the problem...
I hope this helps.

**Comment by sirdir1972** [comment]
Hi!

Yes, I’ve run into this issue before, too. 
This isn’t the problem now. But your posting made me think of something: Maybe the problem might be that the base station for weather, thermostat and security (cameras) all have the same name. This hasn’t been a problem before, but maybe now. I’ll try. 

Regards
Patrick
