### ISSUE TITLE
Multiple roomids in config.json

### ISSUE THREAD

**Issue by shadi1989** [nfarina/homebridge#1309]
Hello,

Is it possible to set more then 1 roomid in the config.json?
I'm configuring all my devices in rooms in Domoticz and i want just a few rooms shown in Homekit. so i would like to know if i just can put the roomid's in the config.json so i dont need to double configure them in domoticz.

**Comment by morilm** [comment]
You just need to create another Domoticz entry for the second/third..... room

      {
          "platform": "eDomoticz",
          "name": "eDomoticz",
          "server": "127.0.0.1",
          "port": "8080",
          "ssl": 0,
          "roomid": 2,
          "usescenes": 0,
          "mqttenable": 1,
          "mqttserver": "127.0.0.1",
          "mqttport": "1883",
          "mqttauth": 0,
          "mqttuser": "",
          "mqttpass": ""
        },
        {
            "platform": "eDomoticz",
            "name": "eDomoticz",
            "server": "127.0.0.1",
            "port": "8080",
            "ssl": 0,
            "roomid": 3,
            "usescenes": 0,
            "mqttenable": 1,
            "mqttserver": "127.0.0.1",
            "mqttport": "1883",
            "mqttauth": 0,
            "mqttuser": "",
            "mqttpass": ""
          },

**Comment by astrapowerrr** [comment]
Hi

I tried this setup. 
But it gives me error that accessory is used by another uuid??

**Comment by Andruxxxxxa** [comment]
when i try suggested config, i see the following when restart homebridge:

```
There was a problem reading your config.json file.
Please try pasting your config.json file here to validate it: http://jsonlint.com
```

Validation o fsuggested config in http://jsonlint.com shows error.

What i'm doing wrong?

**Comment by valentinoeval** [comment]
Wouldn't we be able to specify the room id the plan id instead? That way we'll have all the peripherals of our home at once. Especially since repeating a config per part is deprecated as indicated by the error message
