### ISSUE TITLE
Issues with Harmony

### ISSUE THREAD

**Issue by lyonsad** [nfarina/homebridge#131]
I cannot get the harmony integration to work.  It retrieves my activities but cannot use them.  I get this error on startup  even though node-StringPrep is installed

node-stringprep Cannot load StringPrep-0.7.2 bindings (using fallback). You may need to `npm install node-stringprep` +0ms
  node-stringprep Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (/home/blah/homebridge/node_modules/harmonyhubjs-client/node_modules/node-xmpp-core/node_modules/node-stringprep/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/home/blah/homebridge/node_modules/harmonyhubjs-client/node_modules/node-xmpp-core/node_modules/node-stringprep/index.js:10:39)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32) +3ms

**Comment by madmod** [comment]
Try running `npm rebuild`. See [this stackoverflow](http://stackoverflow.com/questions/28486891/uncaught-error-module-did-not-self-register) for more things to try if that doesn’t work.

-- 
John Wells


On August 28, 2015 at 8:52:16 PM, lyonsad (notifications@github.com) wrote:

I cannot get the harmony integration to work. It retrieves my activities but cannot use them. I get this error on startup even though node-StringPrep is installed

node-stringprep Cannot load StringPrep-0.7.2 bindings (using fallback). You may need to npm install node-stringprep +0ms
node-stringprep Error: Module did not self-register.
at Error (native)
at Module.load (module.js:355:32)
at Function.Module._load (module.js:310:12)
at Module.require (module.js:365:17)
at require (module.js:384:17)
at bindings (/home/blah/homebridge/node_modules/harmonyhubjs-client/node_modules/node-xmpp-core/node_modules/node-stringprep/node_modules/bindings/bindings.js:76:44)
at Object. (/home/blah/homebridge/node_modules/harmonyhubjs-client/node_modules/node-xmpp-core/node_modules/node-stringprep/index.js:10:39)
at Module._compile (module.js:460:26)
at Object.Module._extensions..js (module.js:478:10)
at Module.load (module.js:355:32) +3ms

**Comment by lyonsad** [comment]
thanks i tried that.  I even completely uninstalled my whole node env and rebuilt. same issue.

**Comment by madmod** [comment]
Are you running it on an ARM device like the rasperry pi?

**Comment by lyonsad** [comment]
nope Ubuntu 14.04.3 LTS (GNU/Linux 3.13.0-57-generic x86_64) on intel platform.  node v0.12.3.  I should say the smartthings integration is working like a champ so its not my whole homebridge environment that is messed up.

**Comment by madmod** [comment]
Make sure that you have libicu-dev installed. (`sudo apt-get install libicu-dev`)

The [node-stringprep docs](http://node-xmpp.org/doc/stringprep.html) suggest trying these for node-gyp issues which might be related as this is a binary package error. (Really just guessing here haha) Maybe you could try the solution posted by @rex [in this node-gyp issue](https://github.com/nodejs/node-gyp/issues/363).

-- 
John Wells


On September 1, 2015 at 2:06:56 PM, lyonsad (notifications@github.com) wrote:

nope Ubuntu 14.04.3 LTS (GNU/Linux 3.13.0-57-generic x86_64) on intel platform. node v0.12.3. I should say the smartthings integration is working like a champ so its not my whole homebridge environment that is messed up.

**Comment by madmod** [comment]
Make sure that you have libicu-dev installed. (`sudo apt-get install libicu-dev`)

The [node-stringprep docs](http://node-xmpp.org/doc/stringprep.html) suggest trying these for node-gyp issues which might be related as this is a binary package error. (Really just guessing here haha) Maybe you could try the solution posted by @rex [in this node-gyp issue](https://github.com/nodejs/node-gyp/issues/363).

EDIT: Sorry for the noise. My markdown wasn't working when I sent this from an email.

**Comment by lyonsad** [comment]
libicu-dev was missing, installed.  cleared up the error messages.  However, harmony still not working.  If I go into a home bridge app I can see my various activities turn off and on based on what I tell siri, but it has no effect on my harmony device.  If I use the harmony app it works fine.

**Comment by madmod** [comment]
Try restarting the harmony device and send commands to it infrequently. Also make sure your phone and the harmony are on the same network. (e.g. some people have 5GHz and 2.5GHz wifi networks.) In my experience the harmony smart control has a very slow response time when used with third party libraries especially when sending many commands to it. If you want more info run home bridge with `DEBUG=* npm start`.

-- 
John Wells


On September 1, 2015 at 3:54:24 PM, lyonsad (notifications@github.com) wrote:

libicu-dev was missing, installed. cleared up the error messages. However, harmony still not working. If I go into a home bridge app I can see my various activities turn off and on based on what I tell siri, but it has no effect on my harmony device. If I use the harmony app it works fine.

**Comment by lyonsad** [comment]
I just learned harmony is moving away from their LAN API and moving to a cloud API.  I wonder if that is the source of my issue.

**Comment by maddox** [comment]
@lyonsad omfg are you serious? Do you have a link? I JUST got mine, if they go cloud only that might be a deal breaker for me, ugh, why would they do that. 

What if your damn internet is down, why don't these companies understand this?!

**Comment by madmod** [comment]
I haven’t updated mine to the latest firmware version yet, but to be honest it is kind of unreliable for me even with the official app.

-- 
John Wells


On September 4, 2015 at 12:40:56 PM, Jon Maddox (notifications@github.com) wrote:

@lyonsad omfg are you serious? Do you have a link? I JUST got mine, if they go cloud only that might be a deal breaker for me, ugh, why would they do that.

What if your damn internet is down, why don't these companies understand this?!

**Comment by lyonsad** [comment]
I cant find the post but it was on the Smartthings community.  They describe their new integration strategy with Harmony and specify they are going to cloud to cloud api because Logitech will not be supporting the old API any longer.

**Comment by maddox** [comment]
Everyone is moving their Cloud APIs to local, while Logitech is moving to the cloud. Brilliant. I don't know why I bothered buying into Harmony after hating it for a decade. I thought they might finally be doing something right. I should have known better than that, lol.

Also, I don't see why it has to be either/or. Just use the cloud as a proxy to the local API, done. So sad.

**Comment by KraigM** [comment]
Several fixes and enhancements to harmony have been merged in as part of #299.  See if that works for you guys
