### ISSUE TITLE
Homebridge keeps stopping

### ISSUE THREAD

**Issue by ehusar** [nfarina/homebridge#1310]
I have been running Homebridge for months now without any issues. Just recently I'm having an issue where Homebridge keeps stopping after I start it up.  I use the following commands to start, stop, and check status.

sudo /etc/init.d/homesbridge status/stop/start

I have make no changes to my config.json file. I am guessing it has something to do with the Raspberry PI update/upgrade that has caused this.

How would I troubleshoot this issue.

**Comment by NorthernMan54** [comment]
Step 1 would be to look at the logs to determine why it is stopping.   Typically stoping is caused by a malfunctioning plugin.

**Comment by Tiger519** [comment]
If you run in console via debug=* homebridge -D you'll get some additional details (I do it in a Windows bash, I'm assuming you can do the same from RPi). I'm experiencing the same issue (working for months and now doesn't run for more than 5 minutes typically), though when I say "stop" I really mean that the hap.tcp service stops being advertised. The server itself keeps running. I'm getting a client connection closed message. No idea if that is the same thing happening to you though. Run in debug and see what it's saying when you experience the failures.

**Comment by bartdorsey** [comment]
I believe this exact thing is happening to me. Homebridge works shortly after i start it, and then some time later, my iPhone can't see it anymore. I Just see No Response on all my home bridge devices. I don't see anything in the home bridge logs, so the theory that the hap.tcp service stops being advertised seems likely, Is this something to do with avahi? I"m running my home bridge on a raspberry  pi 3 on raspbian jessie.

**Comment by Tiger519** [comment]
@bartdorsey Did you try running in debug mode? I'm not seeing an error per se, but I'm seeing the following events while the connection is sitting idle:

  EventedHTTPServer [::ffff:192.168.11.108] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:192.168.11.108] Sending HTTP event 'keepalive' with data: {"characteristics":[]} +3m
  EventedHTTPServer [::ffff:192.168.11.108] Client connection closed +8m
  EventedHTTPServer [::ffff:192.168.11.108] HTTP connection was closed +1ms
  EventedHTTPServer [::ffff:192.168.11.108] HTTP server was closed +0ms

keepalive event is happening every 10m, but sometimes the client connection closes almost immediately after that event. I've noticed that when this happens, I can no longer see the hap.tcp service being advertised from the IP address (using Flame app on iOS to find Bonjour services. updates in real time and is free!). What's really strange is that other, unrelated services from that IP (my Windows 10 PC) can "wake up" the connection. Sometimes (but not always) opening and/or closing iTunes will cause HomeBridge to come back to life. My understanding is that the connection closing isn't necessarily a bad thing, but you're supposed to be able to open a new connection, and 99% of the time it's just not happening for me without some kind of intervention.

My current workaround is to have HomeBridge installed as a service, and then schedule a task to restart the service every 5 minutes, but sometimes it doesn't even run that long, and it's pretty poor practice. I was going to pick up an RPi3 to see if I had any better luck, but I'm discouraged now that I will possibly find the same issues there. So much for blaming Bill Gates. :-)

**Comment by bartdorsey** [comment]
I don't get any of those EventedHTTPServer messages when mine is in debug mode. I only get stuff where homebridge is pinging my home-assistant server.

**Comment by Sibelle65** [comment]
I have the same problem...  **HTTP Response is finished**

 right after running homebridge on raspberry pi . Nest thermostat does not turn up in home app, rest of the platforms in homebridge run perfect. Nest thermos was working before but due to problems in Nest account, the Nest helpdesk had to finish my account and open a new one. I installed the thermos again, new codes etc. on developperpage. Homebridge runs but I get this error.
