### ISSUE TITLE
wemo-plugin stopped working

### ISSUE THREAD

**Issue by sirdir1972** [nfarina/homebridge#1312]
Hi!

Is it me? Some days ago the netatmo plugin stopped working, now after an update it hit the wemo plugin: 

`Mai 30 23:07:49 cs homebridge[4284]: [2017-5-30 23:07:49] [HomeAssistant] Fetching HomeAssistant devices.
Mai 30 23:07:49 cs homebridge[4284]: [2017-5-30 23:07:49] [WeMo Platform] Initializing BelkinWeMo platform...
Mai 30 23:07:49 cs homebridge[4284]: events.js:160
Mai 30 23:07:49 cs homebridge[4284]:       throw er; // Unhandled 'error' event
Mai 30 23:07:49 cs homebridge[4284]:       ^
Mai 30 23:07:49 cs homebridge[4284]: TypeError: Cannot read property 'UDN' of null
Mai 30 23:07:49 cs homebridge[4284]:     at module.exports.addDiscoveredDevice (/usr/local/lib/node_modules/homebridge-platform-wemo/index.js:102:43)
Mai 30 23:07:49 cs homebridge[4284]:     at /usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/wemo-client/index.js:48:14
Mai 30 23:07:49 cs homebridge[4284]:     at Parser.<anonymous> (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/xml2js/lib/xml2js.js:489:18)
Mai 30 23:07:49 cs homebridge[4284]:     at emitOne (events.js:96:13)
Mai 30 23:07:49 cs homebridge[4284]:     at Parser.emit (events.js:188:7)
Mai 30 23:07:49 cs homebridge[4284]:     at SAXParser.onclosetag (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/xml2js/lib/xml2js.js:447:26)
Mai 30 23:07:49 cs homebridge[4284]:     at emit (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:640:35)
Mai 30 23:07:49 cs homebridge[4284]:     at emitNode (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:645:5)
Mai 30 23:07:49 cs homebridge[4284]:     at closeTag (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:905:7)
Mai 30 23:07:49 cs homebridge[4284]:     at SAXParser.write (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:1452:13)
Mai 30 23:07:49 cs homebridge[4284]:     at Parser.exports.Parser.Parser.parseString (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/xml2js/lib/xml2js.js:508:31)
Mai 30 23:07:49 cs homebridge[4284]:     at Parser.parseString (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/xml2js/lib/xml2js.js:7:59)
Mai 30 23:07:49 cs systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
Mai 30 23:07:49 cs systemd[1]: homebridge.service: Unit entered failed state.
Mai 30 23:07:49 cs systemd[1]: homebridge.service: Failed with result 'exit-code'.
`
any idea?

**Comment by jdshkolnik** [comment]
https://github.com/rudders/homebridge-platform-wemo/issues/96

**Comment by devbobo** [comment]
@sirdir1972 wemo-client changes their underlying API for one of their calls, should be fixed now in homebridge-platform-wemo@1.3.0

**Comment by sirdir1972** [comment]
Yes it is. Thank you
