### ISSUE TITLE
new NodeJS and npm versions

### ISSUE THREAD

**Issue by morilm** [nfarina/homebridge#1314]
Hi.

Just got updated to new Node.Js and NPM versions and Homebrigde refuses to lunch

0|homebrid | Error: The module '/usr/lib/node_modules/homebridge/node_modules/mdns/build/Release/dns_sd_bindings.node'
0|homebrid | was compiled against a different Node.js version using
0|homebrid | NODE_MODULE_VERSION 51. This version of Node.js requires
0|homebrid | NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
0|homebrid | the module (for instance, using `npm rebuild` or `npm install`).
0|homebrid |     at Object.Module._extensions..node (module.js:598:18)
0|homebrid |     at Module.load (module.js:503:32)
0|homebrid |     at tryModuleLoad (module.js:466:12)
0|homebrid |     at Function.Module._load (module.js:458:3)
0|homebrid |     at Module.require (module.js:513:17)
0|homebrid |     at require (internal/module.js:11:18)
0|homebrid |     at Object.<anonymous (/usr/lib/node_modules/homebridge/node_modules/mdns/lib/dns_sd.js:24:20)
0|homebrid |     at Module._compile (module.js:569:30)
0|homebrid |     at Object.Module._extensions..js (module.js:580:10)
0|homebrid |     at Module.load (module.js:503:32)

$ node -v
v8.0.0
$ npm -v
5.0.0

Seems we might need to get some update.

Regards,
Miguel

**Comment by snowdd1** [comment]
That is a cached compiled version, which was compiled before you upgraded. There are some tickets here that had the same issue with older node versions, use the search to learn how to re-compile the dependencies of homebridge.

**Comment by morilm** [comment]
Thanks Snowdd1

I just sudo unistall homebrige....  

sudo npm uninsstall homebrigde -g

and reinstall again

sudo npm install -g --unsafe-perm homebridge

this fixed the issue!!!!

thanks for the tip

**Comment by nicoh88** [comment]
**ERROR**

```
/usr/lib/node_modules/homebridge/node_modules/mdns/lib/dns_sd.js:35
    throw ex;
    ^

Error: The module '/usr/lib/node_modules/homebridge/node_modules/mdns/build/Release/dns_sd_bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
```

**DOCUMENTATION**

```
npm uninstall homebrigde -g
rm -Rf /usr/lib/node_modules/homebridge/
npm install homebridge -g --unsafe-perm
```

Works for me.

**Comment by felsmann** [comment]
> FIX (DOCUMENTATION)

npm uninstall homebrigde -g
rm -Rf /usr/lib/node_modules/homebridge/
npm install homebridge -g --unsafe-perm

> 

Would doing this require to reconfigure homebridge or does everything com back how it was?

**Comment by fsantiago07044** [comment]
this is happening now after upgrading to fedora 29. following established remedy produces this error:

npm install homebridge -g --unsafe-perm
/usr/bin/homebridge -> /usr/lib/node_modules/homebridge/bin/homebridge

> curve25519-n@1.4.0 install /usr/lib/node_modules/homebridge/node_modules/curve25519-n
> node-gyp rebuild

sh: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin/node-gyp: Permission denied
npm ERR! code ELIFECYCLE
npm ERR! errno 126
npm ERR! curve25519-n@1.4.0 install: `node-gyp rebuild`
npm ERR! Exit status 126
npm ERR!
npm ERR! Failed at the curve25519-n@1.4.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-11-18T00_53_47_877Z-debug.log

what now? worked fine under fedora 28. originally installed under fedora 27.
