### ISSUE TITLE
Cannot find module '../build/Release/dns_sd_bindings'

### ISSUE THREAD

**Issue by Didel** [nfarina/homebridge#1315]
![img_0697](https://cloud.githubusercontent.com/assets/915243/26666119/832bd986-469e-11e7-8853-b68b9b85892b.PNG)

I just installed a clean and fresh installation of **Raspbian Jessie Lite** on my **Raspberry Pi 3**, and the very first thing I did was to install Homebride right after that. I followed every step of the installation guide, but can't succeed in getting homebridge to run.

```
npm -v = 4.2.0
node -v = 7.10.0
```

Might be possibly related to #1314.

**Comment by SeanJohn888** [comment]
I habe the same Problem, what can i do?
![img_1524](https://cloud.githubusercontent.com/assets/27686185/26695888/d529e214-470c-11e7-80eb-4c927d867dc3.PNG)

**Comment by Didel** [comment]
I fixed it, I found the solution in the answer to [#905](https://github.com/nfarina/homebridge/issues/905#issuecomment-274251797) (slightly edited):

```
cd /usr/lib/node_modules/homebridge/
sudo npm install --unsafe-perm mdns
sudo npm rebuild --unsafe-perm
```

**Comment by Sibelle65** [comment]
After 'sudo npm install --unsafe-perm mdns' I get 'sudo: npm: opdracht niet gevonden' What to do next?

**Comment by ebaauw** [comment]
Most likely, the `npm` programme is not in the `$PATH` for `root`.

What OS are you on?  Where did you install node and npm?  What does `which npm` report?

**Comment by Sibelle65** [comment]
Hi, thanx for responding! 
/usr/lib/node_modules/npm
Raspbian on a raspberry pi 3 B+

**Comment by ebaauw** [comment]
Odd.  On Raspbian, the installation should have created a symlink in `/usr/bin` to npm.  Probably best to re-install NodeJS (see https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions), which includes npm, update npm, uninstall homebridge and re-install homebirdge:
```
$ curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
$ sudo apt-get install -y nodejs
$ sudo npm -g i npm
$ sudo npm -g un homebridge
$ sudo npm -g i homebridge --unsafe-perm
```
> I don't know if this is important, but I work with a VNC server/viewer and use a macbook as keyboard, screen, mouse etc.

That shouldn’t matter.  I’m running homebridge on a headless Raspberry Pi 3 B+ over vnc or ssh without any issues.

**Comment by Sibelle65** [comment]
This seems to work, I only get this - config.json warning - as I check homebridge installation:
$ homebridge
Loaded plugin: homebridge-nest
Registering platform 'homebridge-nest.Nest'
 ---
**config.json (/home/pi/.homebridge/config.json) not found.**
Setup Payload:

**Comment by Sibelle65** [comment]
This seems to work, I only get this - config.json warning - as I check homebridge installation:
$ homebridge
Loaded plugin: homebridge-nest
Registering platform 'homebridge-nest.Nest'
 ---
config.json (/home/pi/.homebridge/config.json) not found.
Setup Payload:

**Comment by ebaauw** [comment]
You need to create the `.homebridge` directory and a `config.json` in there, see https://github.com/nfarina/homebridge#installation-details and https://github.com/KraigM/homebridge-nest#configuration.

**Comment by Sibelle65** [comment]
I already have this:
/usr/lib/node_modules/homebridge
en een uitvoerbaar scriptbestand met de naam homebridge:
search:///usr?recursive=1&show_hidden=1&name=homebridge&name_ci=1

Is this not ok?

**Comment by ebaauw** [comment]
You’ve installed homebridge and the homebridge-nest plugin, now you need to configure it.

**Comment by Sibelle65** [comment]
Sorry, I do not get it: You wrote: You need to create the .homebridge directory and a config.json in there, see https://github.com/nfarina/homebridge#installation-details and https://github.com/KraigM/homebridge-nest#configuration.
And I answered: I have already the homebride with a config-sample.json living in it.
path: /usr/lib/node_modules/homebridge
but it as lives in a different spot... (my config.json  is not living in /home/pi/.homebridge/config.json )
my question is:
Is it ok like this or do I have to replace something?

**Comment by ebaauw** [comment]
You don’t need to replace anything.  homebridge is installed to `/usr/lib/node_modules/homebridge`.  homebridge-next is installed to `/usr/lib/node_modules/homebridge-next`.  The next step is to configure homebridge, telling homebridge to use the homebridge-next plugin and telling homebridge-next how to connect to your Next devices.  You need to create `/home/pi/.homebridge/config.json` and edit it, as described in the links.

**Comment by Sibelle65** [comment]
I created a /home/pi/homebridge file by hand and created a config.json in it.
I did it by creating a file in Raspberry Pi and copy the sample code. (used Atom editor)
So I copied the sample code from the sample config.json and edited it for NEST use.
If a search in my Raspberry for homebridge files now, I find 2 homebrigde files, so that is ok.
I did a reboot on Raspberry Pi.
And still, as I run: `$ homebridge` I  get this `config.json file not found`.


` $ homebridge
Loaded plugin: homebridge-nest
Registering platform 'homebridge-nest.Nest'
 ---
config.json (/home/pi/.homebridge/config.json) not found.
Setup Payload:
X-HM://----number----
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:`

and a QR-code.

Because I am not at home I can not scan the QR now (Nest should be near), so that is for later.

Why he still does not find the file?

**Comment by ebaauw** [comment]
Delete the old `.homebridge` directory (just to be sure) and rename `homebridge` to `.homebridge`:
```
$ rm -r .homebridge
$ mv homebridge .homebridge
```

**Comment by Sibelle65** [comment]
Well.... My homebridge now is not vissible anymore, it is .homebridge now which is hidden I guess.
The config.json is in it, as I did it before I changed homebridge in .homebridge. 
As I run .homebridge I get a long list of code, part of it is an error:
`/usr/lib/node_modules/homebridge/lib/api.js:64
      throw new Error("The requested accessory '" + name + "' was not registered by any plugin.");
      ^

Error: The requested accessory 'WeMo' was not registered by any plugin.
    at API.accessory (/usr/lib/node_modules/homebridge/lib/api.js:64:13)
    at Server._loadAccessories (/usr/lib/node_modules/homebridge/lib/server.js:264:42)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:86:38)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous>`

Is this ok?

**Comment by ebaauw** [comment]
Yes, files and directories starting with a dot are hidden.  Use `ls -a` to see them.

> Error: The requested accessory 'WeMo' was not registered by any plugin.

So you’ve specified the WeMo plugin in your config.json, but you haven’t installed the plugin (in the right directory).  Make sure to install plugins with `sudo npm -g i homebridge-`_plugin_.

**Comment by Sibelle65** [comment]
I just forgot to take the fake accessories out of the config.json file...
tomorrow I will be near the NEST thermostate, so I can try to make it word.
Thanx for all the help and patience! I hope this will work!
