### ISSUE TITLE
Update node 8.0.0 (homebridge-soundtouch Plugin no Working)

### ISSUE THREAD

**Issue by Nastra888** [nfarina/homebridge#1317]
Hello, I have since the update on node.js 8.0.0 and npm 5.0 following problem with the homebridge-soundtouch plugin. Does anyone have an idea how I can fix it? If I remove Bose from the Config, the Homebridge will work again. Have the plugin already several times installed and uninstalled.

Thank You for your help!

Jun 03 05:45:27 hbridge2 homebridge[978]: *** WARNING *** Please fix your application to use the native API of Avahi!
Jun 03 05:45:27 hbridge2 homebridge[978]: *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
Jun 03 05:45:29 hbridge2 homebridge[978]: [2017-6-3 05:45:29] ====================
Jun 03 05:45:29 hbridge2 homebridge[978]: [2017-6-3 05:45:29] ERROR LOADING PLUGIN homebridge-soundtouch:
Jun 03 05:45:29 hbridge2 homebridge[978]: [2017-6-3 05:45:29] Error: Cannot find module '../build/Release/dns_sd_bindings'
Jun 03 05:45:29 hbridge2 homebridge[978]: at Function.Module._resolveFilename (module.js:485:15)
Jun 03 05:45:29 hbridge2 homebridge[978]: at Function.Module._load (module.js:437:25)
Jun 03 05:45:29 hbridge2 homebridge[978]: at Module.require (module.js:513:17)
Jun 03 05:45:29 hbridge2 homebridge[978]: at require (internal/module.js:11:18)
Jun 03 05:45:29 hbridge2 homebridge[978]: at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-soundtouch/node_modules/mdns/lib/dns_sd.js:32:22)
Jun 03 05:45:29 hbridge2 homebridge[978]: at Module._compile (module.js:569:30)
Jun 03 05:45:29 hbridge2 homebridge[978]: at Object.Module._extensions..js (module.js:580:10)
Jun 03 05:45:29 hbridge2 homebridge[978]: at Module.load (module.js:503:32)
Jun 03 05:45:29 hbridge2 homebridge[978]: at tryModuleLoad (module.js:466:12)
Jun 03 05:45:29 hbridge2 homebridge[978]: at Function.Module._load (module.js:458:3)
Jun 03 05:45:29 hbridge2 homebridge[978]: [2017-6-3 05:45:29] ====================
Jun 03 05:45:29 hbridge2 homebridge[978]: [2017-6-3 05:45:29] No plugins found. See the README for information on installing plugins.
Jun 03 05:45:29 hbridge2 homebridge[978]: [2017-6-3 05:45:29] Loaded config.json with 1 accessories and 0 platforms.
Jun 03 05:45:29 hbridge2 homebridge[978]: [2017-6-3 05:45:29] ---
Jun 03 05:45:29 hbridge2 homebridge[978]: [2017-6-3 05:45:29] Loading 0 platforms...
Jun 03 05:45:29 hbridge2 homebridge[978]: [2017-6-3 05:45:29] Loading 1 accessories...
Jun 03 05:45:29 hbridge2 homebridge[978]: /usr/local/lib/node_modules/homebridge/lib/api.js:64
Jun 03 05:45:29 hbridge2 homebridge[978]: throw new Error("The requested accessory '" + name + "' was not registered by any plugin.");
Jun 03 05:45:29 hbridge2 homebridge[978]: ^
Jun 03 05:45:29 hbridge2 homebridge[978]: Error: The requested accessory 'SoundTouch' was not registered by any plugin.
Jun 03 05:45:29 hbridge2 homebridge[978]: at API.accessory (/usr/local/lib/node_modules/homebridge/lib/api.js:64:13)
Jun 03 05:45:29 hbridge2 homebridge[978]: at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:254:42)
Jun 03 05:45:29 hbridge2 homebridge[978]: at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:81:38)
Jun 03 05:45:29 hbridge2 homebridge[978]: at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
Jun 03 05:45:29 hbridge2 homebridge[978]: at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
Jun 03 05:45:29 hbridge2 homebridge[978]: at Module._compile (module.js:569:30)
Jun 03 05:45:29 hbridge2 homebridge[978]: at Object.Module._extensions..js (module.js:580:10)
Jun 03 05:45:29 hbridge2 homebridge[978]: at Module.load (module.js:503:32)
Jun 03 05:45:29 hbridge2 homebridge[978]: at tryModuleLoad (module.js:466:12)
Jun 03 05:45:29 hbridge2 homebridge[978]: at Function.Module._load (module.js:458:3)
Jun 03 05:45:29 hbridge2 systemd[1]: homebridge.service: main process exited, code=exited, status=1/FAILURE
Jun 03 05:45:29 hbridge2 systemd[1]: Unit homebridge.service entered failed state.

**Comment by NorthernMan54** [comment]
As the issue is with the sound-touch plugin, you should raise the issue against the plugin rather than here.

**Comment by SeanJohn888** [comment]
I have made. Unfortunately, the plugin has not been further developed for several months. That's why I hoped to get help here.
