### ISSUE TITLE
node 8.0.0 with last version homebridge - mqtt updates dont work

### ISSUE THREAD

**Issue by uronito** [nfarina/homebridge#1318]
with node 8.0.0 and last version of homebridge mqtt updates dont work

**Comment by xTheRamon** [comment]
I think this issue is related to npm module caching.
Have answered this question here:

https://github.com/PatchworkBoy/homebridge-edomoticz/issues/83

**Comment by uronito** [comment]
Hi @xTheRamon , i tried  this option and homekit work correctly, But real-time updates per mqtt only work the first two times. Then homekit is still running but is no longer updated in real time.

Thanks

**Comment by xTheRamon** [comment]
Hi @uronito,

Thank you for your clarification. I have forwarded your issue to https://github.com/KhaosT/HAP-NodeJS/issues/455.

I'm experiencing the same problem myself.

Thank you.

**Comment by xTheRamon** [comment]
Hi @uronito 

Please update all of the modules to the latest version (`npm update`) in the homebridge directory.
I can confirm the issue is now resolved.

https://github.com/nodejs/node/issues/13391

**Comment by uronito** [comment]
Thanks @xTheRamon !!!!!!

Regards
