### ISSUE TITLE
Homekit not controlling TP-Link Smart Bulbs.

### ISSUE THREAD

**Issue by islesailor** [nfarina/homebridge#1319]
Have Homebridge running on Raspberry Pi 3. Have two TP-Link LED Smart Bulbs and One TP-Link Smart WiFi Switch installed. Home on my iPhone links with Homebridge.and detects 3 devices, den lamp, bedroom lamp, and pool light. The pool light is on the switch. The pool light button turns the light on/off. The buttons for the lamps show on/off on the button when tapped but the lamp doesn't respond..Everything works using Kasa.Do I need to have the IP or MAC addresses of the light bulbs in the config file?
Any suggestions how to fix this? config.json is:
{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},

	"description": "This is my configuration file with  one  platform. ",

	"accessories": [

	],

	"platforms": [{
		"platform": "Hs100"
	}]
}

**Comment by TheTrollCaptain** [comment]
This technically only supports the Smart Plugs and Smart Plug-Mini's. I am in the same boat. I really wish this amazing plug-in would be more amazing with full color-bulb support... 

I did find another plugin (https://www.npmjs.com/package/homebridge-tplink-hs100-lightbulbs) that runs alongside this one. Unfortunately, it is broken and pointless. I tried removing the module in the code which breaks it (line 27 in index.json)  but it is needed to separate the smart plugs from the bulbs. (I would fix it, but I don't know json)

**Comment by Tiger519** [comment]
@islesailor Have you tried https://www.npmjs.com/package/homebridge-tplink-lightbulb? That usually works well for me, though if the lightbulbs drop off the network, they become unresponsive (button in Homekit will still work but the bulb won't change state, could even be what you were experiencing previously), and it can timeout your Homebridge instance if it takes too long querying the bulbs. I'd strongly suggest running this plugin in it's own Homebridge instance in case it crashes.

If you're not aware, you can create a separate folder (I used ~/.tplinkbridge), put a separate JSON in that folder with just the tplink configuration, and change the port (important!), username/MAC, and PIN. You then run it with `/opt/node/bin/homebridge -U ~/.tplinkbridge` (if you're on RPi and not running it as a service, but you should be able to do this regardless of method you are using).

**Comment by TylerD89** [comment]
Actually, the new version of the hs-100 plugin, now TplinkSmarthome, has full bulb and plug support. The colors are a little wonky, but it does work...

**Comment by brianjoshua** [comment]
I’m trying to use the homebridge-to link-smarthome. There’s an entry for “Broadcast address” in the JSON. What should I put for that? Is that my router’s IP?

**Comment by TylerD89** [comment]
Broadcast Address should be left at default unless you specifically changed it for your network... it is basically the place where UDP devices wait to be descovered (in simple terms). Do not specify a broadcast address in the Json... could be why you’re running into issues
