### ISSUE TITLE
Missing Plugin for affordable Sen.se ThermoPeanut with API 

### ISSUE THREAD

**Issue by DJay79** [nfarina/homebridge#1321]
Recently I discovered the very affordable [Sen.se Peanut](https://sen.se/store/c/peanuts/) series and I bought two [ThermoPeanut](https://sen.se/store/thermopeanut/).
They are small, handy size, reliable and deliver a good overview over the collected data.
Sen.se already even offer a free [API and documentation](https://sen.se/developers/documentation/).
So this could be something very helpful to integrate as a plugin to homebridge.
Hopefully a developer will get into this and publish a plugin. Till now I was not able to already find a Plugin. 
Thanks in advance. 😉👍🏻

**Comment by Inva0** [comment]
Doesn't the homebridge-sense ([npm](https://www.npmjs.com/package/homebridge-sense)/[GitHub](https://github.com/luc-ass/homebridge-sense)) package provide access to these sensors?

**Comment by DJay79** [comment]
No. Unfortunately not. This is a different kind of product with the ["Mother" by Sen.se](https://sen.se/store/mother/) and the Mother Cookies, but not for the Peanut.
But you gave me the impulse to also place this request there. Thx.

**Comment by j0k3r** [comment]
@DJay-X did you find/build something to connect a thermopeanut to homebridge?
