### ISSUE TITLE
Homebridge on iOS 10.3.2 stopped working

### ISSUE THREAD

**Issue by paviro** [nfarina/homebridge#1324]
Seems like Homebridge no longer works on iOS 10.3.2? 
My devices stopped responding after I updated the OS. I tried to remove the bridge but iOS can't find it anymore...

**Comment by islesailor** [comment]
I am running IOS 10.3.2 and have Homebridge working. cd to your accessories and persist directories and delete the files in them. In the home app, edit My Home, select home and delete home. Start Homebridge, then in the home app start home, add accessories, select homebridge, manually input bridge number and reprogram your devices.

**Comment by walksonair** [comment]
Yep, just followed this recommendation. I deleted the PERSIST and ACCESSORIES folders and then removed my homebridge bridge from the Home app. Re-added the bridge and everything is working peachy again. Wish I knew if there was a better way than this nuke method.

**Comment by islesailor** [comment]
Glad to help. Had this problem when I changed config.json. Took a while to figure it out but this is the only solution I could come up with that worked.

**Comment by paviro** [comment]
Alright will try when I am back at home, thank you!

**Comment by stedurso** [comment]
Thank you walksonair, i had same problem of paviro, and the solution worked for me. I have homebridge on Qnap.

**Comment by peteakalad** [comment]
does this work for a long time?  I've similar issue with homebridge stop responding.  Have tried removing persist and accessories dir and re-pairing homebridge - but every time after  a day or so they stop responding.  I check and homebridge is still running with logs being written ok.

**Comment by stedurso** [comment]
Unfortunately after a day there is the same problem. The accessories stop responding, while homebridge is still running...the solution is ok for 2/3 hours.

**Comment by peteakalad** [comment]
I've split up each of my devices to run as separate homebridge services - hopefully will help diagnose which module is causing the problem.

**Comment by iamrane** [comment]
I've 
* stop home bridge
* deleted persistant and accessories
* deleted home from home app
* start homebridge.

I still can't add homebridge back :/

**Comment by toshibochan** [comment]
You have to change the  "AD:32:2D:E3:CE:31" A~E and 1~5

**Comment by toshibochan** [comment]
You have to change the "AD:32:2D:E3:CE:31" "A to E and 1 to 5"

**Comment by toshibochan** [comment]
You can use A B C D E 1 2 3 4 5

**Comment by RodBruno** [comment]
No issues here with IOS 1.3.2 after I assigned fixed IPs to all devices involved.

**Comment by yaggayoyo** [comment]
Same issue as iamrane. Please help.

**Comment by toshibochan** [comment]
My homebridge start having same problem to! Deleted the homebridge from my home, deleted accessories cash and persistence and add to home again and work again but today happens again! Please help

**Comment by peteakalad** [comment]
So I set up seperate homebridge instances (diff port / username) for each of the 4 modules I use.

All 4 go not responding at the same time after some hours.  This would appear to rule out a particular module problem and its more likely to be either homebridge itself or some bug in the iphone itself.  Saying that, my philips homekit hue hub works fine throughout this, it never goes not responding...

**Comment by yaggayoyo** [comment]
Now I am getting "Endpoint Subscription Expired. No longer storing changes for devices." in my smart things debug log.

**Comment by yaggayoyo** [comment]
Tried same process delete folders and restart HomeBridge but then tried to add from an iPhone i have running 10.3.3. SUCCESS! Is this an apple bug/restriction/something? The same home app on my 10.3.2 device now has the device added but shows no response but works just fine from my 10.3.3 device.

**Comment by yaggayoyo** [comment]
*Update* Accessories also show No response on iPad running 10.3.3. Still works on iPhone running 10.3.3 hmmmmm

**Comment by ciotlosm** [comment]
I have tried everything I could to make it work on 10.3.2. So far:
- iPad on 10.3.2 does not want to detect any accessory
- iPhone on 10.3.2 could detect initially but now at 2nd name change and RaspberryPi3 cold reboot does not want to

Things tried:
- Change "name" to something different
- Change "username" to something different respecting even restrictions mentioned in this post
- Change "port"
- Change "pin"
- Remove "persist" after each action above
- Delete "Home" icon and re-download
- Delete "My Home" inside "Home" application and restart from scratch - also after many of the above combinations

I have restarted the service after each action above with no success, I have installed some things extra as mentioned here: https://github.com/cflurin/homebridge-punt/wiki/Running-Homebridge-on-a-Raspberry-Pi#troubleshooting with no success.

**Comment by NebzHB** [comment]
systemctl restart avahi-daemon solve those problems... but not a long term solution... something have avahi crash but still active and enabled

**Comment by tne7laa** [comment]
Finally!  I deleted the PERSIST and ACCESSORIES folders in the ~/.homebridge directory and it works again (hope it will last...)

**Comment by yaggayoyo** [comment]
Same here.....also working on IOS11 on iPad.

**Comment by rmadrid20** [comment]
Im able to add but  I dont see any accesories??? weird??  its happening to any of you?

**Comment by michaelyasay** [comment]
Same issue with rmadrid20 here, iOS 10.3.2 on iPhone

**Comment by orpolaczek** [comment]
@NebzHB 
I had the same issue. Out of nowhere my homebridge (running on a Raspberry Pi) stopped responding completely.

Nothing helped! 
It's installed as system service and has custom plugins that worked perfectly. 
Restarts, changes of conf, nothing helped until `sudo systemctl restart avahi-daemon`.

Solved it all in a sec. Thanks!

**Comment by delfuego** [comment]
@orpolaczek THIS. This is what fixed everything for me. THANK YOU.
