### ISSUE TITLE
HomeKit iOS 11 Speaker support?

### ISSUE THREAD

**Issue by timstans** [nfarina/homebridge#1326]
Any plans?

**Comment by denizkoekden** [comment]
First AirPlay 2 has to be implemented. IDK if there already is someone, who tries to update his Project to AirPlay 2.

**Comment by pdlove** [comment]
I'm excited about the possibility of implementing Airplay 2 on a raspberry pi hooked to my current in-wall speakers. I'm definitely interested in this project if it gets going. There are a few projects for airplay on node in github. I'm not sure that airplay really fits in with homebridge, but we'll have to see how the HomeKit side of it is implemented. I'll get the developer tools downloaded and take a look at some point this week to see if I can figure it out.

**Comment by KhaosT** [comment]
Based on brief disassemble of the code, it looks like AirPlay 2 support has nothing directly to do with HAP. homed just asks system what AirPlay 2 devices are available and will show them as unpaired accessories which you can add to home. Essentially, if any existing AirPlay implementation adds support for AirPlay 2 then it should show up in Home app automatically.

**Comment by hadolphs** [comment]
Immediate question that came to my head was wether now we can actually make sonos speakers show like speakers in the sonos plugin(s) ... would love to see that happening.  I would be interested in that project as well.

**Comment by justme-1968** [comment]
yes. that would also be the main application for this with the fhem platform plugin. to make various av devices appear as speakers. most of them (especially sonos) will probably never implement airplay.

**Comment by hadolphs** [comment]
Yeah, its clear that sonos is partnering with Amazon and Apple explicitly called them as a competitor in the presentation... so I doubt sonos will do airplay 2 (they never did airplay 1 for starters).    So definitely the way to go is homebridge to sonos.

**Comment by ebaauw** [comment]
I fitted my home with Sonos throughout and I don't subscribe to Apple Music - I won't be moving to HomePod anytime soon.  I'm eager to update my homebridge-zp plugin as soon as we know the new characteristics and services.  Would be cool for Siri to understand Volume instead of having to expose it as brightness.

**Comment by benzman81** [comment]
Actually, what I would like to have is that sonos can be integrated in homekit, so that I can tell the HomePod to Play Michael Jackson in the Living room on my Sonos group. If thats not possible via homekit and just with airplay2 than we actually need an airplay2 to sonos bridge. And that would have nothing to do with homebridge.

**Comment by fraannk** [comment]
It would be amazing if HomeKit could show existing Chromecast Audios as AirPlay 2 speakers with a Homebridge plugin.

**Comment by pdlove** [comment]
From what I can tell, Airplay 2 isn't technically a HomeKit device. This mirrors what KhaosT said above. This being said, there are Airplay 1 solutions out there using a Raspberry Pi. I'm sure they won't take long to get to Airplay 2 once examples are out.

**Comment by philipsaad** [comment]
The 'Speaker' accessory and AirPlay 2 are two completely different things. The former describes how to control a speaker (Mute & Volume) while the later streams audio to that device.

According to the public [HomeKit Accessory Protocol Specification](https://developer.apple.com/homekit/specification/), the Speaker accessory type is defined as follows:

> **UUID**: 00000113-0000-1000-8000-0026BB765291
> **Type**: public.hap.service.speaker
> 
> **Required Characteristics**:
> Mute: 
> - Type: public.hap.characteristic.mute
> - UUID: 0000011A-0000-1000-8000-0026BB765291
> 
> **Optional Characteristics**:
> Name
> - Type: public.hap.characteristic.name
> - UUID: 00000023-0000-1000-8000-0026BB765291
> 
> Volume: 
> - Type: public.hap.characteristic.volume
> - UUID: 00000119-0000-1000-8000-0026BB765291

**Comment by JosephDuffy** [comment]
I have just tried to use this as part of a [plugin I create for computer speaker](https://github.com/JosephDuffy/homebridge-pc-volume), but when I create a [Speaker](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js#L3184) with [Mute](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js#L1180) and [Volume](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js#L2473) characteristics I see "Not Supported" within the Home app. I am on the latest version of Homebridge. Currently I have [my code in another branch](https://github.com/JosephDuffy/homebridge-pc-volume/blob/feature/speaker-homekit-service/index.js).

I am running the iOS 11 GM, which I was expecting would support the speaker.

**Comment by aficustree** [comment]
@JosephDuffy, same here, seems odd

**Comment by meijerpeter** [comment]
Would be awesome if Speakers would be supported! Currently I use my Mac Mini as a central hub and Airfoil to stream to my other Airplay speakers. I run an JSON API (https://github.com/meijerpeter/airfoil-api) on my Mac Mini to control these speakers (volume, on/off) via the homebridge-http plugin. Would be amazing if we can use the native speakers in iOS 11 for this too!

**Comment by suderman** [comment]
Looking forward to speaker support in the Home app. I guess we'll have to wait for some point release in iOS 11.x? So far, I've been using the fan accessory to control volume in my home theatre. It works, but the icon is weird! 😛

**Comment by NorthernMan54** [comment]
Fan, that’s interesting. I’ve been using a light bulb.  On/Off and brightness for volume.

**Comment by ebaauw** [comment]
Using a fan seems odd, but it allows Siri control of volume through fan speed.  Using brightness for that seems less odd, but Siri will also change the speaker volume when you only want her to change the lights.  homebridge-zp lets you choose how you to expose the Sonos speakers.

So far I haven’t seen any changes in iOS 11 for handling the Speaker service, nor for the Volume and Mute characteristics.  My AppleTV, now on iOS 11, which should do Airplay2, shouldn’t it, doesn’t show in Home either.

**Comment by vswraith** [comment]
Did anyone get this to work yet on ios11?

**Comment by ebaauw** [comment]
Sonos announced Airplay2 support coming next year!

**Comment by fraannk** [comment]
Alright, I tried with the new iOS 11.2 beta. I've added my Sonos speakers as "speakers" with the homebridge-zp plugin. While they show as a speaker accessory in the Eve app, it now just crashes the built in Home app... Back to setting up my speakers as fans, so they work in the built in Home app... :(

**Comment by aficustree** [comment]
fingers crossed it cleans up with the next beta. i had to give up living with the beta builds but curious to see how it comes along. I don't like the fan or light switch hacks as "siri turn the downstairs lights off" results in a sudden reduction in teh usefulness of my receiver.

**Comment by ebaauw** [comment]
Apparently, Apple’s Home app on iOS 11.2 beta also crashes on Stateless Programmable Switches, so, fingers crossed, it would seem they’re changing something...

Until that time it remains a develish dilemma:
- Using _Speaker_/_Volume_ makes most sense, but isn’t supported by Siri nor by Apple’s home;
- Using _Fan_/_Rotation Speed_ makes no sense at all, but enables Siri to change the speaker volume and light brightness independently;
- Using _Light_/_Brightness_ hardly makes more sense than _Rotation Speed_, is supported by Siri, but linked to the light brightness.

I ended up using _Switch_/_Volume_, which still makes sense, supports on/off from Siri and Apple’s Home app, but not volume.

**Comment by ebaauw** [comment]
> Alright, I tried with the new iOS 11.2 beta. I've added my Sonos speakers as "speakers" with the homebridge-zp plugin. While they show as a speaker accessory in the Eve app, it now just crashes the built in Home app.

Which beta version was that?  In 11.2 public beta 2, with the `"service": "speakers"` setting, Home just shows a _Not Supported_ tile as with 11.1 and earlier versions.

**Comment by fraannk** [comment]
I was using developer beta 1 at the time. Beta 2 also shows “Not Supported” for me now.

**Comment by fraannk** [comment]
Still “Not Supported” when using the speaker service, in iOS 11.2 developer beta 3.

**Comment by garethallenstringer** [comment]
How are things looking on iOS11.2b6 (15C114)?
(CC: @ebaauw @fraannk)

**Comment by fraannk** [comment]
Same, still "Not Supported" :(

**Comment by fraannk** [comment]
iOS 11.2.5 b1 still not supported. My bet is support in 11.3 :)

**Comment by mdshw5** [comment]
Following

**Comment by fraannk** [comment]
I still get a "Not Supported" tile as of the official 11.2.5 release. 🙁 

![img_c1215413a54d-1](https://user-images.githubusercontent.com/11140089/35301559-27dcea7c-008c-11e8-85a3-ecdea5428f49.jpeg)

**Comment by aficustree** [comment]
Do we know what iOS will be needed to support the HomePod?

**Comment by philipsaad** [comment]
11.2.5 is what is needed to support the HomePod.

https://www.macrumors.com/2018/01/23/apple-releases-ios-11-2-5/

**Comment by aficustree** [comment]
quite interesting, would seem to then imply that home will not be able to manage the home pod on day 1 or that we're doing something wrong.

**Comment by mdshw5** [comment]
https://9to5mac.com/2018/01/23/homepod-airplay/

If multi-room playback is managed through HomeKit, then that makes sense given Apple's announcement. Personally I'm a bit disappointed about the UI changes surrounding Airplay. It seems like Apple doesn't write know what they're doing, or they haven't communicated their user stories/experiences to key people in.

**Comment by ebaauw** [comment]
Looks like we need to wait for Airplay2, which is _not_ yet available at the launch of the HomePod.  No ETA on Airplay 2 either...

**Comment by sebj** [comment]
Perhaps (hopefully!) AirPlay 2 may ship in iOS 11.3, just not in the first beta. 

https://twitter.com/iryantldr/status/956228515191500800

**Comment by fraannk** [comment]
Yeah, I think you're right. Tried the first beta of 11.3, and still no luck. :)

**Comment by mdshw5** [comment]
Ask and yea shall receive: https://9to5mac.com/2018/01/24/airplay-2-rolling-out-ios-11-3/

**Comment by simonrb2000** [comment]
It’s in iOS 11.3 beta 1 as mentioned above. Remember you will need your Apple TV also running on the new tvOS 11.3 Beta 1 otherwise it won’t work...

**Comment by KhaosT** [comment]
I thought I was clear enough in my original comment but apparently not.

Home app's media accessory (HomePod, Apple TV, AirPlay 2 devices) support in iOS 11 is not using HomeKit Accessory Protocol, there is simply no services/characteristics you can create to just have your HAP accessory to show up as a "speaker" in Home app. To have Home app recognize a device as a "speaker", you need to implement AirPlay 2 protocol instead of HAP. And currently as of iOS 11.3 beta 1, non-Apple AirPlay 2 devices will not actually show up unless you have a special configuration profile installed to override iOS settings.

The existing `Speaker` and `Microphone` services defined in HAP is only for IP Camera. It has nothing to do with iOS 11's Whole House Audio.

**Comment by simonrb2000** [comment]
KhaosT; I was only referencing that its now out to try, not that it needs implementing on Homebridge. Like you said it will show up if in the home app if you have an AirPlay 2 compatible speaker.

**Comment by philipsaad** [comment]
Removed in the 11.3 GM, meh.

**Comment by henry-spanka** [comment]
Still no luck with iOS 11.4. Speaker still shown as unsupported accessory :(

**Comment by mriksman** [comment]
It’s unlikely it’ll ever be a part of the Homekit space; it uses Airplay 2. It’s like hoping ARKit will be a part of Homekit. Or ‘OK Google’. Or ‘Hey Alexa’....

Regards,

Michael Riksman

Sent from iPhone

On 3 Jun 2018, at 7:37 pm, Henry Spanka <notifications@github.com<mailto:notifications@github.com>> wrote:


Still no luck with iOS 11.4. Speaker still shown as unsupported accessory :(

**Comment by jeylites** [comment]
Has anyone tried the speaker function on IOS 13? I would be a nice feature to add.
