### ISSUE TITLE
iOS 11: No connection from external

### ISSUE THREAD

**Issue by marcodesantis71** [nfarina/homebridge#1327]
HI,

when I try to connect from 4G network, I can't connect to my homebridge.

Via WiFi it works

**Comment by Quiqui64** [comment]
Are you using a appleTv 3 for a hub? If so it will not work.

**Comment by marcodesantis71** [comment]
Hi,
no. I use a 4th generation. With iOS10 I have not a problem.
I can't connect only with iOS 11 beta (of course it is a beta...)

**Comment by justme-1968** [comment]
same here. ios10 works with atv3. ios11 says atv not responding.

**Comment by DerThommy83** [comment]
The same yesterday - it also doesn't worked inside the local network. Today after rebooting the phone everything works fine. I'm using an atv4 for the external connection.

**Comment by justme-1968** [comment]
just had to reboot an ios10 iPhone to get remote connectivity back. and i noticed this morning that siri does not understand turning a homekit switch named radio on any more. is they are probably working on the homekit/siri server side ...

**Comment by marcodesantis71** [comment]
Yes. I confirm now it works.

Same problem for Siri Name.

**Comment by xTheRamon** [comment]
Yup same here. iOS 11 and Homebridge don’t play nice. Also have an AppleTV 4. Even on my home network my devices are unreachable. Using an iPhone 6 Plus. 

Everything is working flawlessly on an iPhone 6 with iOS 10. 

I must say I recently upgraded to node.js 8.0.0 which was giving me some issues as well.

**Comment by xoniq** [comment]
No issues here. Apple TV running tvOS 10 and my iPhone 7 running iOS 11. However it takes a while to refresh devices, but it might be my local machine which is quite busy sometimes. Still need to put it on a dedicated Raspberry Pi.

**Comment by fedor1210** [comment]
Solved this by restarting both iPad (Hub) & iPhone (iOS 11).
