### ISSUE TITLE
Best practice to update HAP-NodeJS

### ISSUE THREAD

**Issue by cflurin** [nfarina/homebridge#133]
What is the best practice to update HAP-NodeJS in homebridge/node_modules?

Just now I do it this way:
- remove HAP-NodeJS
- copy the new version of HAP-NodeJS into the folder homebridge/node_module
- npm install

**Comment by nfarina** [comment]
So we've been referencing HAP-NodeJS via a git-based dependency and "pinning" it to the last known version that works with homebridge, in package.json. Generally you can just type `npm update` and it will update the git version if needed.

**Comment by cflurin** [comment]
Thanks for the quick reply.
It's really easy :smile:
