### ISSUE TITLE
Setting "No response" from accessory in plug-in

### ISSUE THREAD

**Issue by Arduingo** [nfarina/homebridge#1330]
Hi,

I´m trying to write a plugin for my own developed accessory that workd over MQTT, I´m new to node and homebridge plug in dev, so far is working ok but there is one thing I´m not able to make it work.

I want that if the accessory is offline and cannot answer to my status request or the mqtt broker send the "last will" message the widget at the Home app change to a status of "No Response", its there any API call I may use achieve this behavior?, receive and read mqtt messages is not the problem, I´m doing it and the plugin is receiving all the needed messages, what I don´t know is what to set to set a device as no response or unavailable.

Thanks for the help.

**Comment by danielsen2009** [comment]
Use the last will and testament with your mqtt broker to set the status. That way when it can't connect it assumes its dead and sets the status accordingly.

**Comment by Arduingo** [comment]
Nevermind, I found a solution to my problem by setting the reachability to false when the LWT is detected and in my .getStatus use the flag to set the callback to no_response

**Comment by riteesh3** [comment]
Hello,

By any chance did you upgrade to using dynamic platform in your plugin ?
If yes did you foind any way to show no response in Homkit Kit App using Characeteristic or Acessory?

**Comment by NorthernMan54** [comment]
This is covered in the documentation

https://developers.homebridge.io/#/api/service#serviceupdatecharacteristic
