### ISSUE TITLE
HomeKit iOS 11 - Open Protocol Specifications

### ISSUE THREAD

**Issue by IAmTheMitchell** [nfarina/homebridge#1334]
Hi everyone,

I'm new to Github and coding, but I have been following this project for awhile. 
Stumbled upon this today: https://developer.apple.com/homekit/specification/

How will this effect the future of Homebridge? It seems like it could make things a lot easier!

**Comment by AppleTechy** [comment]
This should be discussed on, https://github.com/KhaosT/HAP-NodeJS/issues/457 . Already discussed on this repo under issue #1328
