### ISSUE TITLE
iOS11 Beta: Garage Shows as "Not Supported"

### ISSUE THREAD

**Issue by jake-b** [nfarina/homebridge#1337]
I have a fairly custom setup involving an MQTT cover device in HomeAssistant controlling my garage.  I am using homebridge-homeassistant with homebridge to expose these devices to HomeKit.

All works fine in the iOS10 Home app.  I can control the garage and receive push notifications when the garage opens or closes.

In the iOS11 beta, however, the Device shows up as "Not Supported".
![img_1c38d6dba4f6-1](https://user-images.githubusercontent.com/1012393/27002310-bc36918e-4dac-11e7-84e7-37512cd64a06.jpeg)

Other devices seem to work fine from the iOS11 app, like lights and switches.

**Comment by honcheng** [comment]
I'm having the same problem

**Comment by aryelevin** [comment]
I It your first accessory on the config file?

**Comment by jake-b** [comment]
It is not a specific accessory in the homebridge config.json -- instead it is configured through a platform, using the homebridge-homeassistant plugin:

```
  "platforms": [
    {
      "platform": "HomeAssistant",
      "name": "HomeAssistant",
      "host": "http://127.0.0.1:8123",
      "password": "xxxxxxxxxxxx",
      "supported_types": ["binary_sensor", "climate", "cover", "device_tracker", "fan", "group", "input_boolean", "light", "lock", "media_player", "scene", "sensor", "switch"],
      "logging": true
    }
  ]

```

I acknowledge that given the fact that there are so many components in my setup (Custom Wemos device configured as an MQTT cover, HomeAssistant, HomeAssistant-HomeBrige Plugin, HomeBridge itself, HomeKit) it may not be an issue with HomeBridge directly but one of the other components in the chain. 

It is just odd to me that it works fine in iOS10 and not in iOS11 beta, which leads me to believe there is a change in behavior to HomeKit that is causing the issue, and thats why I think (possibly wrongly) that it might be at the HomeBridge level.

**Comment by AppleTechy** [comment]
Please post an issue on the Homebridge-homeassistant repo.

**Comment by neruve** [comment]
I also have an issue similar to this one but it changes. I'm using the switchtech and ecoplugs addins. The problem is its random. My first install the ecoplugs worked fine and all but one of the switchtecs worked. On the second install all the switchtecs work and one of the two ecoplugs says not supported. I have a feeling it is the last device homebridge loads. So i'm thinking this may be an issue with homebridge itself as its happened with both installs with different results. homebridge itself is the only common denominator.

**Comment by askusbloodfist** [comment]
I hade the Same Problem as you Guys. but with my Telldus Device. 

My solution was to readd the device to the Telldus Interface. Then readded the new id to the Config. 
Then all worked. Allso deleted Accessories directory and persist direktory. but i did that before and had no effekt. So think readding will do just fine.

**Comment by boojew** [comment]
I have the same issue using HASS. I have 2 Insteon covers exposed by ISY and they are configured exactly the same way - only one of the two works properly

@askusbloodfist for your solution, I am not sure how you did this.
