### ISSUE TITLE
Multiple config.json entries for same platform plugin

### ISSUE THREAD

**Issue by ebaauw** [nfarina/homebridge#1339]
Is homebridge supposed to support multiple entries in config.json for the same platform plugin?

When using static accessories, homebridge seems to support specifying the same platform plugin multiple times in config.json.  The platform constructor is invoked multiple times, with a different value for `config` corresponding to each config.json entry.  This works brilliantly for homebridge-hue, to specify different settings for different Hue bridges in different config.json entries.

I'm (finally ;-) refactoring homebridge-hue to use dynamic accessories instead and I'm running into an issue.  The platform constructor is invoked multiple times, just as for static accessories, but only the last (most recently created) platform instance receives the `accessoryRestored` event.  Also, there's no reference to the instance (or config.json entry) that orginally created the accessory.  Consequently, the earlier (original) platform instance doesn't know the accessory has been restored, tries to create it, and obviously receives an error _Cannot add a bridged Accessory with the same UUID as another bridged Accessory_.  I catch the error, so homebridge and homebridge-hue continue to work, but the last (most recently created) platform instance doesn't know the earlier (original) config.json settings that should still apply to the restored accessory.

Did any of you run into this issue for other plugins?  How did you address it?  
I suppose I could try and work around this issue by linking the accessories to the platform _class_ rather than to the platform _instance_.  And by somehow using the accessory context to keep track of which instance (or config.json entry) originally created the accessory.  However, this seems overly complicated and error prone.  
Alternatively, I could just issue an error message and exit homebridge when the platform is specified more than once in config.json.  However this seems like a check homebridge should be doing.

**Comment by snowdd1** [comment]
Hi ebaauw,
I use generated UUIDs which are saved to an extra file for recovering the accessories. But I don't have multiple instances of the platform, just one instance which restores all accessories and handles them.

About here: https://github.com/snowdd1/homebridge-knx/blob/v0.3.10/index.js#L202

I have to admit that I never tested to put multiple entries for the platform into config.json, as my platform uses its own config file it doesn't appear in the config.json at all - dynamic platforms are loaded if they do not have a section in the config.json.
 Before that, I had a accessories section *within* the platform section (before dynamic platforms existed, so you had *one* platform entry consisting of connection information to the hardware and multiple accessory entries in an encapsulated accessories array [(Time travel link)](https://github.com/snowdd1/homebridge-knx/tree/v0.2.0#syntax-of-the-configjson)

**Comment by ebaauw** [comment]
Thanks, @snowdd1 

> I use generated UUIDs which are saved to an extra file for recovering the accessories

I save the additional info I need (including the ID on which the the UUID is based) under the accessory `context`, which gets persisted in `~/.homebridge/accessories/cachedAccessories`.  In `configureAccessory()` I just save the restored accessory under "my" ID.  On `didFinishLoading` I do my regular device discovery, linking the discovered devices to the saved accessories, and marking them reachable.

> I have to admit that I never tested to put multiple entries for the platform into config.json

Neither had I, until one of my users found out this worked.  Hence my question: is this intentional or accidental?

> dynamic platforms are loaded if they do not have a section in the config.json

Indeed, with the `config` parameter holding value `undefined`.  I figured this would be a good cue to remove the restored accessories, so you wouldn't have to delete or manually edit `~/.homebridge/accessories/cachedAccessories` when you want to uninstall the plugin.  I don't suppose there's a standard how dynamic platform plugins are suppose to uninstalled?

**Comment by snowdd1** [comment]
I implemented a tiny web server component that shows the orphaned cache entries, with a link to delete them.

**Comment by nicoduj** [comment]
Hi @ebaauw . 
I am facing the same problem for my harmony plugin moving to dynamic platform. I have 2 modes currently, that were working fine before dynamic mode by adding 2 instances of the platform in the config . Many users are doing that, so that they can have one legacy mode (switches) and a test mode with beta versions of IOS 12.2 (TV accessory mode).

However, it doesn't work anymore since each platform doesn't restore its own accessory. if I combine them.

I am new to this, do you have any idea on how I could solve it ? 

(code there : https://github.com/nicoduj/homebridge-harmony/tree/Dynamic-Platform ) 

Thank you for any advice.

**Comment by ebaauw** [comment]
You don’t.  Either change the plugin, so a single instance can support both modes simultaneously, or run two separate homebridge instances.

**Comment by nicoduj** [comment]
Thnak you, will combine I think !

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
