### ISSUE TITLE
UUID conflicts

### ISSUE THREAD

**Issue by volschin** [nfarina/homebridge#134]
I plan to use two homebridge instances (one for productive and one for development) using the same device pool. The bridges are configured with different usernames. But they generate the same UUID's for the devices.

I'm not sure if this is the right behaviour or the bridge username should be part of the UUID.
So changing this
```javascript
    var accessoryUUID = uuid.generate(accessoryInstance.constructor.name + ":" + displayName);
```
to this
```javascript
    var accessoryUUID = uuid.generate(bridgeConfig.username + ":" + accessoryInstance.constructor.name + ":" + displayName);
```

**Comment by nfarina** [comment]
Does duplicate UUIDs in this case cause any problems? Accessory UUID is only used within a Bridge to determine the allocation of IDs; HomeKit shouldn't even know about them.

**Comment by volschin** [comment]
OK, it seems to be a misunderstanding on my side. I thought, the UUID would be passed to homekit. Thanks for clarification.

It was a theoretical question at the moment because my productive version is running on the old homebridge version yet and the development on the newly designed one.
