### ISSUE TITLE
tail -f /var/log/homebridge.log shows old data

### ISSUE THREAD

**Issue by junior466** [nfarina/homebridge#1340]
After installation, I started running Homebridge simply by issuing the command but later changed to running it as service. It seems that when I try to see the log when running "tail -f /var/log/homebridge.log", it only shows logs prior to running it as a service. I know this because of the date of the logs. 

How can I view the logs now that it runs a s service?

**Comment by Arduingo** [comment]
Try with tail -F /var/log/daemon.log or systemctl status -l homebridge.

**Comment by junior466** [comment]
The first command works perfectly. Thank you very much!
