### ISSUE TITLE
Fakehome kit device

### ISSUE THREAD

**Issue by QuadDepo** [nfarina/homebridge#1343]
Is there a way i could make a fake homekit device that i could control with my iphone?

**Comment by skrollme** [comment]
You can Download the "Hardware IO Tools for Xcode" in the Apple Developer Section (https://developer.apple.com/download/more/) This package contains an HomeKit Accessory Simulator

**Comment by QuadDepo** [comment]
@skrollme I just downloaded it, is there also a way to connect it with homebridge?

**Comment by skrollme** [comment]
Why would you do this? HomeBridge is a bridge that offers real (or simulated) accessories, and the accessory simulator is an app which offers - surprise - simulated accessories. They basically do the same thing.

**Comment by QuadDepo** [comment]
Ah allright, im about to set homebridge up on my R'pi. I used to have it on my mac and could setup actions that would trigger applescripts and open or close windows etc. I was trying to do the same but the homebridge server isnt running on my mac anymore thats why i was searching for a solution

**Comment by GvnCampbell** [comment]
You would probably need to figure out a way to remotely run commands on your mac from the rpi and use something like the scripts2 plugin to run a script. I know it can be done with windows. Not too familiar with macs though.

**Comment by AppleTechy** [comment]
Just use CMDSwitch2 and it allows you to trigger terminal/cmd commands. I would just then write a bash file for it to execute
