### ISSUE TITLE
Stop lock notifications

### ISSUE THREAD

**Issue by quacktacular** [nfarina/homebridge#1344]
Writing a custom plugin. Does anyone know if there is a Characteristic to stop / suppress HomeKit notifications when a lock is unlocked?

Currently the notifications have to be disabled on each device (in the Home app), which is not ideal.

**Comment by dermotos** [comment]
Not that I'm aware of. I believe it to be a security feature, in the same way you cannot unlock a lock when the iPhone is not unlocked itself. A hack/way around this is to write your plugin as a device that you can tell Siri to "Open", but which is not a lock, such as a window covering.
