### ISSUE TITLE
raspberry pi zero w installation

### ISSUE THREAD

**Issue by goncalvesdiogo** [nfarina/homebridge#1347]
I'm having problems to install homebridge in my Rpi Zero W. After following all the steps of the wiki when I try to start homebridge I get the "command not found" message.
Does anyone have the same problem?

**Comment by tomashedenius** [comment]
Just installed on my pi zero w and it works fine

**Comment by weissenheimer** [comment]
Please run „which homebridge“ and report back.

**Comment by goncalvesdiogo** [comment]
Hi @weissenheimer 
I did not understand what you asked me for...
Can you be more specific?

Tks in advance.

**Comment by goncalvesdiogo** [comment]
I had tried it again and now is working, my problem was the node version, I'm using the 4.0.0 now. Tks everyone.
