### ISSUE TITLE
Some direction on a garage door opener

### ISSUE THREAD

**Issue by d0n13** [nfarina/homebridge#1348]
Hi all

Just need some help on how to work a garage door opener with the GarageDoorOpener service. It's not too well documented.

I have 3 pins on the Raspberry Pi already wired up to the door and working when I toggle them with a C or bash script, but I really want to use this service instead of node.js or anything like that because it shouldn't need it, although it would be easier. I'm also just worried about having a server on the door that can just open the door if I poke a URL. I know there are ways to fix that but I don't have the time to invest in learning how to do it even though I probably should...

Basically, I'd rather get my head around doing it directly in the accessory code. I've made a start as shown below but I'm a little stuck.

Anybody got an implementation that works and wouldn't mind sharing?

Thansk
Donie

```javascript
var request = require("request");
var Service, Characteristic;

// These are wiringPi ping numbers
PINS = {
    OpenPIN  : 0,
    ClosePIN : 21,
    StopPIN  : 24
}

module.exports = function(homebridge) {
    Service = homebridge.hap.Service;
    Characteristic = homebridge.hap.Characteristic;

    homebridge.registerAccessory("homebridge-MainGarage", "MainGarage", MainGarageAccessory);
}

function MainGarageAccessory(log, config) {
    this.log = log;
    this.config = config;
    this.name = config["name"];

    this.service = new Service.GarageDoorOpener(this.name);
    this.service
        .getCharacteristic(Characteristic.CurrentDoorState)
        .on('get', this.getCurrentDoorState.bind(this));
    this.service
        .getCharacteristic(Characteristic.TargetDoorState)
        .on('get', this.getTargetDoorState.bind(this))
        .on('set', this.setTargetDoorState.bind(this));
    this.service
        .getCharacteristic(Characteristic.ObstructionDetected)
        .on('get', this.getObstructionDetected.bind(this));
}

MainGarageAccessory.prototype.getCurrentDoorState = function(callback) {
        
    callback(null, 1); // OPEN=0, CLOSED=1, OPENING=2, CLOSING=3, STOPPED=4
}

MainGarageAccessory.prototype.getTargetDoorState = function(callback) {
        
   callback(null, 1); // OPEN=0, CLOSED=1
}

MainGarageAccessory.prototype.setTargetDoorState = function(targetState, callback) {
        
   callback(null, targetState); // OPEN=0, CLOSED=1
}

MainGarageAccessory.prototype.getObstructionDetected = function(callback) {

   callback(null, 0); // 0=NO, 1=YES
}

MainGarageAccessory.prototype.getServices = function() {
    return [this.service];
}
```

**Comment by toshibochan** [comment]
i use https://github.com/benlamonica/homebridge-rasppi-gpio-garagedoor

**Comment by d0n13** [comment]
@toshibochan That's awesome. Nicely done. I'll be using it for reference. I like the way you figured out how to detect if the door was open or not. That was giving me a few issues on how to detect it simply. 

Thank you!

**Comment by toshibochan** [comment]
Please close this issue if you find the answer. Thanks!

**Comment by Quiqui64** [comment]
Did you ever find an answer?
