### ISSUE TITLE
Homekit Devices Endlessly Updating

### ISSUE THREAD

**Issue by CalebLun** [nfarina/homebridge#1354]
Hello GitHub and Homebridge community,

Just thought I would start off by saying I very much new to this, but have been running homebridge with little to no issues for a few months. 

However, over the last couple of days I noticed that all my homekit devices are constantly in state of updating. I have stooped and started homebridge with no success. I completely deleted the home from homekit and reset the bridge brand new to no avail. Just wondering what you all might think might be going wrong?

Thanks,

Caleb

**Comment by kalety** [comment]
Here same... I think there is something in "the Apple side". I hope everything returns to normal, as soon as possible...

**Comment by CalebLun** [comment]
Good to know I am not alone with this problem, Kalety. I had I thought that it was that.

**Comment by B1tMaster** [comment]
Run "top" command to see the CPU % your haas and homebridge process are using.
If high, that would explain the issue.

Why it is high, is another question. Maybe ur db got too big or something else. Setup purging ur DB often. 
I had similar issue before and that was the cause.

**Comment by cmcken** [comment]
I unfortunately have this issue too, and also tried deleting everything and starting from scratch to no avail.

Anyone figure out what is going on yet?

**Comment by simonrb2000** [comment]
Have you guys deleted the persist and accessories folder? Change username in the confit file and then reset HomeKit and read home.

On 23 Jun 2017, at 15:24, cmcken <notifications@github.com<mailto:notifications@github.com>> wrote:


I unfortunately have this issue too, and also tried deleting everything and starting from scratch to no avail.

Anyone figure out what is going on yet?

**Comment by cmcken** [comment]
@simonrb2000 Yes, I certainly have tried all of those options.

**Comment by cmcken** [comment]
Figured it out - it was my router. Was using a BT Smart Hub (Home Hub 6) which has had issues in the past! Now in the cupboard and back to my Home Hub 5 which works perfectly.

**Comment by CalebLun** [comment]
Ok so I have not had a router change at all and the problem still persists, anyone have any other possible solutions or ideas about whats going wrong?

**Comment by CalebLun** [comment]
I finally solved my problem by doing a fresh install and updating everything. I don't know if this specifically solved my problem as I did it many times before to no avail. But its worth a try if you encounter this issue. Anyways everything is working perfectly.
