### ISSUE TITLE
How to gracefully exit Homebridge from a plugin ?

### ISSUE THREAD

**Issue by NebzHB** [nfarina/homebridge#1358]
Hello,

If something wrong with my dynamically added accessories, I do : process.exit(1), but that kinda break persist and/or cache, is there a gracefully way to exit ? Something like stopping the multicast then saving the cache and close the connections properly ?

Thank you in advance,

**Comment by snowdd1** [comment]
You should remove the defective accessories first, AFAIK

**Comment by NebzHB** [comment]
first before what ? before exiting ? is it because the cache/persist have a non-complete accessory ? do you have any more details about it ? what need to be removed ? the accessory ? the bridgedaccessory ? the plateform ?

**Comment by snowdd1** [comment]
Well, if you create an Accessory object in a dynamic platform, it is not linked to the homebridge yet. You need to call registerAccessory() to put it into the list of accessories of the platform. From that moment the accessories are added to homebridge's cache system, and need to be removed if they are faulty for some reason - to do that, you need to call unregisterAccessory() with the culprit as parameter (wrapped in an array), so you should always have an object reference at hand. If you cleaned up that way, you should not have any issues with the cache/persist mechanism.    

If you have that cleaned up, you might still want to stop homebridge - there's no documented way to do that, for developing purposes I added a method to throw a defined exception ("committed_suicide") so homebridge comes down. However, I do not think that's a proper way, yet, I think you can't send an OS signal from within an application to call homebridge's ctrl-c handler for a graceful shutdown.

**Comment by snowdd1** [comment]
EDIT: it's `registerPlatformAccessories()` and the corresponding `unregisterPlatformAccessories()`

**Comment by NebzHB** [comment]
I've seen a destroy method somewhere in hap-nodejs, could it help?

**Comment by NebzHB** [comment]
And thank you for those informations, I'll keep the reference to unregistered it if it already registred

**Comment by yene** [comment]
You can send it a ctrl-c `process.kill(process.pid, 'SIGINT');`
