### ISSUE TITLE
Beginner Looking for extreme help

### ISSUE THREAD

**Issue by spower99** [nfarina/homebridge#1359]
Starting this for the first time, loads up, and produces the error message (included below) and my config is as follows:

{
     "bridge": {
        "name": "HomeBridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    
    "description": "HomeBridge HTTP Status Control",

  "accessories": [
   	{
   		"accessory": "Http",
   		"service": "Switch",
   		"name": "Sean's Room",
   		"apiBaseUrl": "http://http://localhost:8080/paperui/index.html#/configuration/things/view/orvibo:s20:ACCF23997E28",
   		"apiSuffixUrl": "",
   		"forceRefreshDelay": 0
   	},
   	{
   		"accessory": "Http",
   		"service": "Switch",
   		"name": "Front Room 1",
   		"apiBaseUrl": "http://http://localhost:8080/paperui/index.html#/configuration/things/view/orvibo:s20:ACCF2335B5AE",
   		"apiSuffixUrl": "",
   		"forceRefreshDelay": 0
   	},
   	{
   		"accessory": "Http",
   		"service": "Switch",
   		"name": "Front Room 2",
   		"apiBaseUrl": "http://http://localhost:8080/paperui/index.html#/configuration/things/view/orvibo:s20:ACCF23997F64",
   		"apiSuffixUrl": "",
   		"forceRefreshDelay": 0
   	}
  ],		
									    
     "platforms": [
      {
        "host": "192.168.1.135",
        "name": "openHAB",
        "platform": "openHAB",
        "port": "8080",
        "sitemap": "default",
        "useLabelForName": true
      },
{
"platform": "Orvibo",
"name": "Orvibo"
}
]
}
![capture](https://user-images.githubusercontent.com/29741514/27613465-8f1819da-5b93-11e7-9fc7-158ebcdf575e.PNG)

All help is welcomed 
Thanks

**Comment by alexsalex** [comment]
http://http://localhost:8080/

try to delete  http://... 

`"apiBaseUrl": "http://localhost:8080/paperui/index.html#/configuration/things/view/orvibo:s20:ACCF2335B5AE",`

**Comment by spower99** [comment]
No change
