### ISSUE TITLE
Error after move to USB on Raspberry Pi 3B

### ISSUE THREAD

**Issue by heathpitts** [nfarina/homebridge#1362]
Long shot to see if anyone else has seen this issue. I have a working raspbian image on an RPi3 using an SD card. Only software it runs is Homebridge and Home Assistant. Now that the RPi3 can boot from USB, I thought I'd move my imahe over to a USB drive and make it arguably more reliable than the SD card. I figured out the steps to get it booting off the USB drive and thought all was well. Home Assistant worked fine and I was about to call it a success until I opened up the home app. Couldn't connect to Homebridge. Service was running but I couldn't connect. So I bit the bullet and removed the bridge from Home. Simply couldn't find Homebridge. I changed everything I could find in the config (code, user, etc) along with removing the persist directory. Even removed Homebridge completely and reinstalled. I simply couldn't get it to pair again. To see if it was something odd with the USB boot, I installed Homebridge on another RPi that I had moved over to a USB drive. Worked perfectly fine. I ended up just reverting to the old SD card and Homebridge worked immediately. In fact, I tried it by copying the same image I had over to another SD card and Homebridge worked fine there as well. 

Has anyone else seen this? If so, could you give me any pointers about getting this to work? I'd love to try this again and boot from USB. but I don't want to completely rebuild homebridge and homeassistant on a new image

**Comment by snowdd1** [comment]
Hadn't had any issue like that when I moved my Raspbian to NFS boot. 
Might your Raspberry get another IP when booting off USB or other change that might make HomeKit think it's not the same bridge, even if it has the same "username"?

**Comment by heathpitts** [comment]
I have a static IP for this particular one. So you had zero issues during the move? Just used the same image as before?

**Comment by snowdd1** [comment]
Yep. I copied everything over the LAN to my NAS, set up NFS boot and voila (after some trouble with my NFS configuration on my Synology NAS) it just worked. I now have three Raspberries booting off NFS for different purposes (homebridge development, homebridge production, octoprint) and all went flawlessly, except for the occasional hiccup with NFS config on Synology (each release has new *features*)   
I haven't tried to boot off USB, but my assumption would have been that it would behave the same.  

Did you see anything in the homebridge log (assuming you use system service: in the syslog *journalctl*)?

Once you remove the home while it's not reacting, you need to delete /persist and /accessories folders for a clean restart, and I recommend changing the "username" in the config.json, too; just in case the bridge was blacklisted by homekit for some reason.

**Comment by heathpitts** [comment]
Didn't look in the journalctl but I will after I try this again. Assuming I run into the same issues. Just copied the image to a USB drive again this morning. It is a new backup fwiw. Only thing I'll do differently this time is not resizing the / partition with gparted. I moved from a 32 gig SD card to a 64 gig USB drive for this. Doubtful that makes a difference but I'll check anyways. 

Also, I did try all the steps you listed but still no dice on adding it back. I'll report back

**Comment by heathpitts** [comment]
Same exact problem this time. Homebridge just will not show up when I boot the copied image. The only other issue I see is that I need to reconfigure the ecobee api key after I boot the copied image. I tried all the normal troubleshooting but all the devices just show no response. Put the original SD card back in and remove the USB drive, works perfectly. Additional info that I can think of is that this is the exact same RPi and also I did not remove the homebridge bridge from the home app this time. I am also using DD to copy the disk. My script shuts down homebridge and home assistant services while backing up. It works if I DD this image to another SD card. I'm out of ideas at this point. Looks like I am stuck using the SD card until I rebuild a new homebridge and home assistant image

**Comment by snowdd1** [comment]
But apart from that, your copied image runs fine? 
I would suggest to copy a fresh raspbian lite to the USB disk and install everything online, takes only about 30 min on a 3b - then you should have a clean and working image on disk

**Comment by heathpitts** [comment]
Update on this. I did manage to get this working. As I said, I was backing up using DD to an .img file. Then I was restoring that to the USB drive using DD as well. This does work for the most part. However, something was in use or just improperly copied during the DD. I brought the RPi back up with the original working SD card and then use rsync to sync files over to the USB drive. Completed that and rebooted. Everything is fine now. Moral of the story is to use rsync for backups :) command below that I used along with the exclude script



rsync -avH --delete-during --delete-excluded --exclude-from=/usr/bin/rsync-exclude.txt / /mnt/PiData/PiBackup/


rsync-exclude.txt:


/proc/*
/sys/*
/dev/*
/boot/*
/tmp/*
/run/*
/mnt/*

.Trashes
._.Trashes
.fseventsd
.Spotlight-V100
.DS_Store
.AppleDesktop
.AppleDB
Network Trash Folder
Temporary Items

.bash_history
/etc/fake-hwclock.data
/var/lib/rpimonitor/stat/

**Comment by heathpitts** [comment]
Never mind. Problems returned after a reboot.

**Comment by heathpitts** [comment]
Issue doesn't exist. This has now been stable for a week now for me. Closing issue

**Comment by Samfox2** [comment]
Does homebridge react faster after the transfer 2 usb or is the performance the same?

**Comment by heathpitts** [comment]
It honestly does seem to but that may just be a placebo. So far so good though and I'm happy to worry less about the drive going bad
