### ISSUE TITLE
Is there anyway to indicate to Siri that Homebridge Accessories are available from iPhone lock screen?

### ISSUE THREAD

**Issue by ssllii** [nfarina/homebridge#1363]
I installed Homebridge and Homebridge-assurelink2 plug-in.  From the "Home" app, I am able to open/close my garage door.  I can even use Siri to do that after the phone has been unlocked.

However from the lock screen, Siri will ask me to unlock the iPhone first.  Is there anyway to tell Siri/Home that I want that accessory to be available from lock screen as well?

**Comment by maragelis** [comment]
That is the correct way to do it, imagine someone else telling siri to open the door to your home without siri asking for a password !!
With lights and other devices Siri does not ask for unlock.

**Comment by ssllii** [comment]
Yes, you are right.
Apple solved it with another piece of their hardware, Apple Watch.  Once I logged into my watch, I can use Siri on the Watch to open the garage door.  That addresses my need.

Thanks.
