### ISSUE TITLE
Update to v0.4.21?

### ISSUE THREAD

**Issue by maciboy** [nfarina/homebridge#1368]
Hi,
My pi3 is nicely running v0.4.10.
Now a new release was published and I have two major questions:

-are there such improvements worth updating? A changelog is not available and I don‘t get wise from the commit notes. 
-how to perform such an update? Do I have to completely reinstall or is there a routine that keeps my setup?

Thanks in advance for answering these, maybe stupid, questions!

**Comment by KhaosT** [comment]
It's always nice to ask if you are not sure :)

Between 0.4.10 to 0.4.21, the main changes are adding support for new service types that Apple added in iOS 10 era along with some bug fixes. It's always a good idea to update to latest version.

Normally running `npm update --depth 9999 -g homebridge` should do the work.

**Comment by maciboy** [comment]
Unfortunately, I get this error:

```
pi@rasp:~ $ npm update --depth 9999 -g homebridge
npm ERR! Linux 4.9.35-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "update" "--depth" "9999" "-g" "homebridge"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10

npm ERR! Maximum call stack size exceeded
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/npm-debug.log

```
Any idea, what causes this or what „Maximum call stack size exceeded“ means in this case?
Thanks a lot!
