### ISSUE TITLE
harmonyhubjs Windows x64: file dependencies have exceeded the 255 character limit for folder path and file name

### ISSUE THREAD

**Issue by nzhome** [nfarina/homebridge#137]
bugger..  263 characters...   limit is 255.  why are the folders so deep.. any way around this?

C:\Program Files\nodejs\node_modules\homebridge\node_modules\harmonyhubjs-client\node_modules\node-xmpp-client\node_modules\request\node_modules\har-validator\node_modules\is-my-json-valid\node_modules\generate-object-property\node_modules\is-property\.npmignore

**Comment by nzhome** [comment]
if only the word "node_modules"  was shorter, this would be a non-issue.  also if projects would pull in some of the code from other node_modules rather than linking them :)

**Comment by Damienbarifon** [comment]
Try to long path tool. It is very helpful.
