### ISSUE TITLE
Can homebrdige support apple authentication coprocessor?

### ISSUE THREAD

**Issue by nhyjq** [nfarina/homebridge#1371]
We‘re planing to manufactured some bridge product for engineering project based on homebridge and raspberry pi. 
For avoiding warning message "This accessory is not certified and may not work reliably whit HomeKit" when pairing device,  we bought some authentication coprocessor chips(2.0c).  But how to connect authentication coprocessor to hardware or can homebridge support  authentication coprocessor?

Thank you very much.

**Comment by KhaosT** [comment]
Basically you need to connect the co-processor to I2C port on Raspberry Pi and make some changes under [pair-setup](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/HAPServer.js#L375) to follow the MFi version of spec to sign the MFi challenge using the co-processor.

**Comment by KhaosT** [comment]
Since those parts are covered under MFi NDA, it's not possible for homebridge to support it directly.
