### ISSUE TITLE
/usr/bin/homebridge: No such file or directory

### ISSUE THREAD

**Issue by johnx102** [nfarina/homebridge#1374]
Hi, i change my pi 2 with a pi 0.
So i reinstall nodejs and every modules because its arm6
first i have a mismatch error when i launch home bridge (because i think he's not same node version)
So i try several thing, and reinstall totally home bridge plugin , seems ok but when i want launch homebridge i have this error : bash /usr/bin/homebridge: No such file or directory

any idea ?

**Comment by EdwinJS** [comment]
Perhaps that is not the directory homebridge was installed into. To check the directory run this command: "which homebridge". What does that return?

**Comment by GeorgeBgk** [comment]
> sudo npm i -g --unsafe-perm homebridge

**Comment by EdwinJS** [comment]
@GeorgeBgk He may have done this, probably not, but to check the current directory of homebridge @johnx102 must perform the **which homebridge** command for us to know the current installed location.

**Comment by johnx102** [comment]
Hey, thank's for the answer, when i do which home bridge, he return me nothing. no error just nothing ....

**Comment by johnx102** [comment]
So @EdwinJS like you say i already reinstall home bridge with unsafe-perm...but it resolve nothing.
maybe this can help ou, when i do "sudo npm i -g --unsafe-perm homebridge"
i have this when it's finish ... : /opt/nodejs/bin/homebridge -> /opt/nodejs/lib/node_modules/homebridge/bin/homebridge
/opt/nodejs/lib
└── homebridge@0.4.22

**Comment by EdwinJS** [comment]
Wait so which homebridge doesn't return anything? Try >sudo which homebridge

**Comment by johnx102** [comment]
EdwinJS i do but same problem.
So i erase and reinstall everything from beginning, now it's working ...
Thank's for help ..
