### ISSUE TITLE
Is there any way to collect history of data ?

### ISSUE THREAD

**Issue by andriuskr** [nfarina/homebridge#1378]
Is it possible to collect all the data of sensors connected to homebridge (temperature, humidity, etc) ? Or even there is solution to visualise (charts) this data ?

**Comment by NorthernMan54** [comment]
I have updated my collection of sensor plugins to log there data to google sheets.  If you look at

Homebridge-dot
Homebridge-mcuiot
And my fork of homebridge-bme280

These all use a common package mcuiot-logger to log the sensor data to google sheets.

**Comment by mrose17** [comment]
https://github.com/homespun/homebridge-accessory-neurio/blob/master/index.js#L106

**Comment by andriuskr** [comment]
These suggestions are for individual sensors....
I am looking for an option co collect data from all sensors connected to homebridge.
