### ISSUE TITLE
Lutron Caseta and Pico Remote

### ISSUE THREAD

**Issue by jpaquino3** [nfarina/homebridge#1380]
I've been using homebridge for a while and love it! Thank you for all the hard work! As of now my whole home is either Philips Hue or Lutron Caseta. The homebridge-hue plugin works amazingly, thank you ebaaw, but I really would love to have the functionality l of Lutron Pico remotes in HomeKit as well. Does anyone know if there is a plugin that would work? I've searched and have only found homebridge integration with Lutron RadioRa 2.

**Comment by Joegratz** [comment]
This will never be possible with a Caseta Smart Bridge (non-PRO), since the LEAP protocol it uses doesn't provide information about Pico button presses.

This could in theory be done with a Caseta Smart Bridge PRO, since the telnet-based LIP protocol it uses does provide information about Pico button presses. That protocol is basically the same between the Caseta Smart Bridge PRO and RadioRA2.

One issue is that the buttons on a Pico are really best described as stateless programmable switches, and the support for those in HomeKit is currently not really there. There are various ways to fake that, though. What is it that you want to do with a Pico? Trigger a HomeKit scene, I assume?

**Comment by jpaquino3** [comment]
Thank you for all the info! Yes I would like to trigger scenes that include hue lights. If I buy a pro bridge would I be able to use the RadioRA2 plugin to expose my pico remotes to HomeKit? 

Josh Aquino
(845) 475-6075
Jpaquino3@gmail.com

On Jul 10, 2017, at 1:27 AM, Joegratz <notifications@github.com> wrote:

This will never be possible with a Caseta Smart Bridge (non-PRO), since the LEAP protocol it uses doesn't provide information about Pico button presses.

This could in theory be done with a Caseta Smart Bridge PRO, since the telnet-based LIP protocol it uses does provide information about Pico button presses. That protocol is basically the same between the Caseta Smart Bridge PRO and RadioRA2.

One issue is that the buttons on a Pico are really best described as stateless programmable switches, and the support for those in HomeKit is currently not really there. There are various ways to fake that, though. What is it that you want to do with a Pico? Trigger a HomeKit scene, I assume?

**Comment by Joegratz** [comment]
Nope. As it sits the homebridge-radiora plugin (https://github.com/djMax/homebridge-radiora/) exposes RadioRA-controlled lights as HomeKit bulbs, but doesn't do anything with Picos. So it's great for people who have a RadioRA system without a HomeKit-compatible Smart Bridge, but not much use to people with a HomeKit-compatible Smart Bridge.

But! The thing you want to do is possible (with a pro bridge); the software just doesn't exist yet (afaik). What you would do is have a HomeKit plugin that listened for updates to Pico state over telnet from the Smart Bridge Pro, then exposed them as a fake HomeKit lightbulb or fan that has a particular state when you press a particular button on the pico.  Then you would trigger a HomeKit automation off that state that goes to the scene you want.

(Note that the other thing you can do, outside Homebridge entirely, is have the middle "preset" button on your Pico set one of your Lutron devices to some unlikely value, then trigger the scene as a HomeKit automation off that Lutron device being at that unlikely value. Only gets you one scene per pico, though.)

I have a hacked-together half-NodeJS/half-Python setup that could be pretty easily adapted to do this -- one of these days I will clean it up and post it, but it's not ready for prime time. (It's primarily a custom scene controller that lets me have adjustable fade times, and trigger those scenes either from any button on any pico or from HomeKit by setting a fake bulb to a certain brightness as part of a HomeKit scene.)

**Comment by justinfanok** [comment]
@Joegratz would LOVE to get my hands on that NodeJS/Python script 🤤

**Comment by Joegratz** [comment]
Here you go: https://github.com/Joegratz/scenesetter

**Comment by QandnotU** [comment]
@Joegratz I'm a little green when it comes to understanding how these things play nice together, but what is the feasibility of getting a Lutron Connected Bulb Remote (Zigbee), to be used as a scene/accessory remote in HomeKit similar to the Hue Tap.

**Comment by Joegratz** [comment]
So the Lutron Connected Bulb Remote, as you say, is a ZigBee device and appears to share nothing (other than looks) with other Lutron wireless gear.  (So the stuff I wrote doesn't help you.)

It looks like it is just a regular ZigBee Light Link remote. This project supports a number of other ZigBee remotes in HomeBridge -- perhaps the Lutron Connected Bulb Remote could be added:

https://github.com/ebaauw/homebridge-hue

**Comment by QandnotU** [comment]
@Joegratz thank you for pointing me in the right direction.

**Comment by jcoleman** [comment]
@Joegratz I’m confused by the comments about  HomeKit not supporting stateless programmable switches. Isn’t that what the ProgrammableSwitchEvent characteristic describes? Or is that new since your comment?
