### ISSUE TITLE
Accessory Reachability update is no longer being supported.

### ISSUE THREAD

**Issue by tagyoureit** [nfarina/homebridge#1383]
Hi,

just wondering about this debug line I'm seeing in 0.4.22. `Accessory Reachability update is no longer being supported.`  

Does this mean Homebridge isn't supporting it?  Or HomeKit?  

And what action should we take on our plug-ins?  Is this being deprecated in favor of something else or should we just remove it?

thx!

**Comment by KhaosT** [comment]
iOS removed support for that. Right now there isn't a way for bridge to inform HomeKit about bridged accessory reachability so I'd say just remove it from the code.

**Comment by bwoodruff** [comment]
I'm seeing this repeatedly in my logs.

> Accessory Reachability update is no longer being supported.

How can I tell which plug-in is misbehaving?
