### ISSUE TITLE
Question: How to disable Plugin from loading 

### ISSUE THREAD

**Issue by maragelis** [nfarina/homebridge#1384]
I have two instances running on a linux server, everything is running fine with about 30 accessories on each instance. The problem is that when i try add a plugin that uses a network resource like YEELIGHT which binds to 0.0.0.0:1901. With out even adding the plugin to the config.json homebridge tries to load the plugin causing a crash in one instance <cannot bind to 0.0.0.0:1901 port already in use>. 
Is there a way to not load the plugin on one instance? 
Thanks in advance for any help

**Comment by snowdd1** [comment]
For plugins that do not require a config.json entry (dynamic platforms) and that do not have some kill switch you can only install them locally instead of globally and use a command line parameter to point your homebridge instance to your local plugin directory (`-P`). Do not forget to set the user rights accordingly to the user/group that starts the service!

**Comment by maragelis** [comment]
Thanks @snowdd1  you are a life saver . Thanks a million.

**Comment by jdtsmith** [comment]
This is a great tip.  If you are running multiple `homebridge` instances on one device, put the `homebridge` plugin itself in the "default" location (for me `/usr/local/lib/node_modules`, whatever `npm -g` wants) and then created a separate plugin directory for each instance (I just left them in my homebridge user's home directory).  Then you can configure each instance to use `-P /home/homebridgeuser/homebridge-XXX` or similar, putting just the plugins you want to load in those per-instance directories.  Speeds up load time considerably.  

I find that a few `homebridge` instances each doing less (<10 plugins) gives better performance and less 'Updating' freezes in Home app.

**Comment by ebaauw** [comment]
Or use the `plugins` key in config.json to whitelist which plugins to load.

**Comment by jdtsmith** [comment]
Thanks @ebaauw, didn't know that one!
