### ISSUE TITLE
homebridge in constant reboot

### ISSUE THREAD

**Issue by chezpaul** [nfarina/homebridge#1386]
I setup the systemctl startup way of having homebridge always running but it seems like it's always rebooting.

pi@raspberrypi:~ $ systemctl status homebridge
● homebridge.service - Node.js HomeKit Server
   Loaded: loaded (/etc/systemd/system/homebridge.service; enabled)
   Active: active (running) since Fri 2017-07-14 04:42:17 UTC; 2s ago
 Main PID: 20976 (homebridge)
   CGroup: /system.slice/homebridge.service
           ├─20976 homebridge
           ├─20982 /bin/sh -c /bin/echo -n "$(npm -g prefix)/lib/node_modules...
           └─20983 npm
pi@raspberrypi:~ $ systemctl status homebridge
● homebridge.service - Node.js HomeKit Server
   Loaded: loaded (/etc/systemd/system/homebridge.service; enabled)
   Active: activating (auto-restart) (Result: exit-code) since Fri 2017-07-14 04:43:15 UTC; 2s ago
  Process: 21036 ExecStart=/usr/bin/homebridge $HOMEBRIDGE_OPTS (code=exited, status=1/FAILURE)
 Main PID: 21036 (code=exited, status=1/FAILURE)
pi@raspberrypi:~ $ systemctl status homebridge
● homebridge.service - Node.js HomeKit Server
   Loaded: loaded (/etc/systemd/system/homebridge.service; enabled)
   Active: active (running) since Fri 2017-07-14 04:43:42 UTC; 689ms ago
 Main PID: 21075 (homebridge)
   CGroup: /system.slice/homebridge.service
           └─21075 homebridge
pi@raspberrypi:~ $ systemctl status homebridge
● homebridge.service - Node.js HomeKit Server
   Loaded: loaded (/etc/systemd/system/homebridge.service; enabled)
   Active: activating (auto-restart) (Result: exit-code) since Fri 2017-07-14 04:43:49 UTC; 8s ago
  Process: 21075 ExecStart=/usr/bin/homebridge $HOMEBRIDGE_OPTS (code=exited, status=1/FAILURE)
 Main PID: 21075 (code=exited, status=1/FAILURE)
pi@raspberrypi:~ $ systemctl status homebridge
● homebridge.service - Node.js HomeKit Server
   Loaded: loaded (/etc/systemd/system/homebridge.service; enabled)
   Active: activating (auto-restart) (Result: exit-code) since Fri 2017-07-14 04:44:06 UTC; 2s ago
  Process: 21096 ExecStart=/usr/bin/homebridge $HOMEBRIDGE_OPTS (code=exited, status=1/FAILURE)
 Main PID: 21096 (code=exited, status=1/FAILURE)
pi@raspberrypi:~ $ 

I followed these instructions for systemtcl setup

1. sudo nano /etc/default/homebridge and paste this gist
2. sudo nano /etc/systemd/system/homebridge.service and paste this gist
    1. I had to remove local from:  ExecStart=/usr/local/bin/homebridge $HOMEBRIDGE_OPTS  because my homebridge installed in /usr/bin/
3. Create a user to run service: sudo useradd --system homebridge
4. sudo mkdir /var/homebridge
5. sudo cp ~/.homebridge/config.json /var/homebridge/
6. sudo cp -r ~/.homebridge/persist /var/homebridge
7. sudo chmod -R 0777 /var/homebridge
8. sudo systemctl daemon-reload
9. sudo systemctl enable homebridge
10. sudo systemctl start homebridge

When I launched home bridge on it's own, manually it seemed to be working fine.

**Comment by chezpaul** [comment]
I have been playing now with home bridge ran manually and I can tell that it also quits within 30 seconds tops. Sometimes it will quit right away, other, I will have time to add home bridge and start adding one or two devices and bam, I lose connection because it quit again.

This is what I did to install:
Now do this:
sudo apt-get update
sudo apt-get upgrade

Then install Node.js:
curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
sudo apt-get install -y nodejs

Install Avahi and other dependencies:
sudo apt-get install libavahi-compat-libdnssd-dev
sudo apt-get install git-core libnss-mdns
sudo npm config set registry http://registry.npmjs.org/
sudo npm install -g node-gyp

Now we install Homebridge:
sudo npm install -g --unsafe-perm homebridge

Then install the homebridge-vera plugin (a Homebridge plugin):
sudo npm install -g --unsafe-perm homebridge-vera

Edit your homebridge config.json file located on ~/.homebridge/config.json :

cd ~/.homebridge/
sudo nano config.json

And paste this:

{
"bridge": {
"name": "Homebridge",
"username": "CC:22:3D:E3:CE:30",
"pin": "031-45-154"
},
"accessories": [],
"platforms": [{
"platform": "Vera",
"name": "Vera",
"veraIP": "192.168.1.110"
}]
}

**Comment by ebaauw** [comment]
You need to figure what's causing homebridge to quit.  What messages does homebridge output before it quits?  You might want to run
```
DEBUG=* homebridge -D
```
for more detailed messages.

**Comment by chezpaul** [comment]
Thanks that helped. 
Seems like it was running. I had to change username and delete persist directory.
The Apple Home app kept on quoting my setup once I added homebridge.
I just had to go in manually after adding homebridge and edit each device.

It helped me in that I realized the app wasn't quitting.

At least by running it manually. Now I need to try ti through systemtcl.

What would be the same Debug command to run for: 10. sudo systemctl start homebridge

**Comment by ebaauw** [comment]
If you followed the [WiKi](https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi#running-homebridge-on-bootup-systemd), you would need to edit `/etc/default/homebridge`, adding `-D` to `HOMEBRIDGE_OPTS` and uncommenting the `DEBUG=*` line.

**Comment by chezpaul** [comment]
Thanks...
So 

# Defaults / Configuration options for homebridge
# The following settings tells homebridge where to find the config.json file and where to persist the data (i.e. pairing and others)
HOMEBRIDGE_OPTS -D=-U /var/homebridge

# If you uncomment the following line, homebridge will log more 
# You can display this via systemd's journalctl: journalctl -f -u homebridge
DEBUG=*

It seems like when I setup HOME in iOS by running homebridge (without the systemctl) it all works.
But if I then run the systemctl way, then iOS doesn't see my devices. And yes it is the same config.json.

**Comment by chezpaul** [comment]
I also have another quick question.
I launch homebridge from terminal window on my mac by ssh. But each time I close the terminal window, it terminates homebridge. Homebridge is running on my Raspberry so what am I doing wrong?

**Comment by ebaauw** [comment]
In `/etc/defaults/homebridge` use: `HOMEBRIDGE_OPTS=-U /var/homebridge -D`.  It's an environment variable, used in `/etc/systemd/system/homebridge.service`, so you need to add `-D` to the value, to the right hand side of the `=`, not to the name.

From the command line use: `DEBUG=* nohup homebridge -D &`.   When you close the terminal window, it sends a signal to any running command, causing it to exit.  `nohup` prevents this.  Note that `nohup` redirects the output of homebridge to a file, `nohup.out`.  To follow the output in real-time use `tail -f nohup.out`.

**Comment by dariusz** [comment]
Thanks for the info here @ebaauw .. after debugging I realized that my persist/ and accessories/ folders were owned by `root` rather than by `homebridge` via a debugging error.  That was causing a constant loop of restarts.

**Comment by BeansSi** [comment]
> Thanks for the info here @ebaauw .. after debugging I realized that my persist/ and accessories/ folders were owned by `root` rather than by `homebridge` via a debugging error. That was causing a constant loop of restarts.

Hey dariusz, i got the same issue as you, but cant figure out how to change the ownership of my folders.

Can you tell me how you solved that?

**Comment by remko2000** [comment]
> Thanks for the info here @ebaauw .. after debugging I realized that my persist/ and accessories/ folders were owned by `root` rather than by `homebridge` via a debugging error. That was causing a constant loop of restarts.

Hai Dariusz, i've got the same question. How do you solve this?
