### ISSUE TITLE
Automations based on Harmony Activities no longer working

### ISSUE THREAD

**Issue by RobotLimeLtd** [nfarina/homebridge#1388]
Automations based on Harmony Activities are no longer triggering. 

For example, I have a Harmony Activity that starts my PS4, TV and Sound system (which is picked up by Homebridge) and I have a PS4-Waker configured to be able to wake/suspend my PS4.  Each works fine on its own in the iOS Home app, but if I set up an automation so that launching the Harmony activity wakes the PS4, or quitting the Harmony activity suspends the PS4, the PS4-Waker event is never triggered.

This all used to work (albeit a little flaky),  but then I did a major update of Node/NPM and all the various modules I'm using with Homebridge.  

Where can I start troubleshooting this?  I've been through everything Apple have suggested, including completely removing everything from the Home app and starting again.  The Home app is correctly connected to my AppleTV as a remote Hub.  Automations based on Hue lighting (using the Hue bridge) work fine.  

Could it still be a bug in Apple's Home app, or is there something not happening in either homebridge, homebridge-harmony, or ps4-waker module?

**Comment by justme-1968** [comment]
homekit has no concept of order or dependencies. so homekit is (currently) not the right place to do this. alexa has just added ordered and unordered variants for groups/scenes. so maybe homekit will provide something like this in the future.

but as mentioned already in other threads: use a 'real' home automation system and use i as the central system for all automations and dependencies. then add homekit and the harmony and alexa and whatever other device as io for input and output.

this will give you many many more benefits in the long run.
