### ISSUE TITLE
AdministratorOnlyAccess

### ISSUE THREAD

**Issue by ebaauw** [nfarina/homebridge#1389]
Has any-one used the `AdministratorOnlyAccess` characteristic in their plugin?

I understand the characteristic isn't supposed to do anything by itself - the accessory needs to implement the restrictions (see https://stackoverflow.com/questions/32742645/set-custom-permission-to-guest-user-for-accessory-in-homekit).  I would like to implement this for my plugin, but I don't understand how that's done.  In particular:
1. How would a plugin determine whether a characteristic change comes from an admin or non-admin user?
2. How would a plugin report back that this change is not allowed for a non-admin user, so that HomeKit can return an `HMErrorCodeInsufficientPrivileges` to the HomeKit app?

**Comment by grover** [comment]
By my understanding the first paired iOS controller is always an administrator. The iOS controller adds additional controllers with the Add Pairing Request and is supposed to specify their permissions there.

Looking at the HAPServer.js implementation HAP-NodeJS ignores those parameters.

**Comment by ebaauw** [comment]
See https://github.com/KhaosT/HAP-NodeJS/pull/702
