### ISSUE TITLE
raspberry pi - can't find config.json file location

### ISSUE THREAD

**Issue by iHakia** [nfarina/homebridge#1391]
Hey noob here!
I'm trying to delete the config.json file. 
apparently I can't find the location.
I deleted the config.json in the /home/pi/.homebridge 
But when i'm running homebridge it's still seems to load a config.json somewhere.

Any idea? /.

**Comment by toshibochan** [comment]
Try
cd ~/.homebridge
ls

**Comment by toshibochan** [comment]
If you looking in the finder
Type
~/.homebridge

**Comment by iHakia** [comment]
It wasn't there neither. 
He loading it from somewhere.

 Loaded plugin: homebridge-tado-ac
[7/15/2017, 1:01:19 AM] Registering accessory 'homebridge-tado-ac.TADO'
[7/15/2017, 1:01:19 AM] ---
[7/15/2017, 1:01:19 AM] Loaded config.json with 1 accessories and 0 platforms.
[7/15/2017, 1:01:19 AM] ---
[7/15/2017, 1:01:19 AM] Loading 1 accessories...
[7/15/2017, 1:01:19 AM] [Tado] Initializing TADO accessory...
[7/15/2017, 1:01:20 AM] [Tado] Minimum setpoint 16
[7/15/2017, 1:01:20 AM] [Tado] Maximum setpoint 31

**Comment by aycgit** [comment]
What happens when you try to place a new config in the place you think your config was at?

**Comment by dmikhalsky** [comment]
try to look at /root/.homebridge
Mine is loaded from there

**Comment by toshibochan** [comment]
Config.json not make automatically! You have to make your config.json file in ~/.homebridge
Just type:
sudo nano ~/.homebridge/config.json

And paste your configuration and save.

**Comment by ioveracker** [comment]
I just found mine in /var/lib/homebridge on a Raspberry Pi I set up in 2017.

**Comment by kevinmpowell** [comment]
Mine was in `/var/homebridge/` from a Raspberry PI I set up in 2016.

`cd /` and
`find -name 'config.json'`

Allowed me to locate it.
