### ISSUE TITLE
What do you use as a platform for sonos in homebridge?

### ISSUE THREAD

**Issue by Reuben-jones** [nfarina/homebridge#1392]
I am installing Homebridge to Play and pause my Sonos system but I can't find the information anywhere that tells me what to use for the platform. Please, could someone help?

**Comment by ToddGreenfield** [comment]
You need to do a search on either github or npm. You can search for homebridge-plugin (to see all plugins) or just try homebridge-sonos... here's the link - https://github.com/nfarina/homebridge-sonos. That page has specific directions.

**Comment by Reuben-jones** [comment]
Neither of them has any information on the Platform used.

**Comment by ToddGreenfield** [comment]
Suggest you move your request for help over to the homebridge Slack team site at http://homebridge-slackin.herokuapp.com/  There is a group specific to Sonos.

**Comment by Reuben-jones** [comment]
There is nothing there.
![screen shot 2017-07-15 at 17 21 51](https://user-images.githubusercontent.com/20084729/28240936-1b0072f2-6982-11e7-8b86-6dfdd054bf2a.png)

**Comment by ebaauw** [comment]
You might want to checkout my platform plugin for Sonos: https://github.com/ebaauw/homebridge-zp
