### ISSUE TITLE
Homebridge on Windows: What workloads in Visual Studio Community do I need?

### ISSUE THREAD

**Issue by sndrsk** [nfarina/homebridge#1394]
I am following this guide to install Homebridge on Windows 10: https://github.com/nfarina/homebridge/wiki/Install-Homebridge-on-Windows

I am at the step of installing Visual Studio Community. What workloads do I need to install to get this to work?

**Comment by pdlove** [comment]
The easiest way to get what you need is to do "npm install --global windows-build-tools"
