### ISSUE TITLE
How to update...

### ISSUE THREAD

**Issue by junior466** [nfarina/homebridge#1396]
Pardon my newbie question but what is the best way to update homebridge to the latest version? I searched and found the command `npm update --depth 9999 -g homebridge` but that doesn't do anything.

Thanks!

**Comment by skrollme** [comment]
Vou can update homebridge (or other npms) by simply running the install command again. At least that is the way I normally do this. So...

`npm install -g homebridge`

should do it. Maybe with a `sudo `. Depends on your setup and how you installed it

**Comment by junior466** [comment]
I installed it originally with 

`sudo npm install -g --unsafe-perm homebridge` so just run that again? Won't it overwrite my current config?

**Comment by skrollme** [comment]
Simply run `sudo npm install -g homebridge` (without the --unsafe-perm). This will update your homebridge setup. Of course you can save your config before. Just make a backup of the config-file in the .homebridge directory.
