### ISSUE TITLE
Raspberry Pi as Locally Monitored Security System

### ISSUE THREAD

**Issue by jpaquino3** [nfarina/homebridge#1405]
Has anyone tried tapping into their home security system using the raspberry pi gpio pins?

Currently I have a disabled Brinks system that needs to stay unplugged. This is because ADT (who now owns Brinks) doesn't allow local monitoring and without a proper connection to their servers, an obnoxious beep happens every 24 hours until canceled. 

It feels like such a waste to let the preexisting equipment go unused.  Currently, I know there is a plugin for contact sensors but I was wondering if anyone has done a diy overhaul of a security system in their house. One that can successfully arm and disarm, use the contact and motion sensors, door chimes, and siren.

**Comment by jonathanweinberg** [comment]
I don't meet the requirements of what you're looking for in terms of having done it before.

But....where does the beep come from?

**Comment by jpaquino3** [comment]
The beep comes from the brinks keypads. It says CP error and happens 24 hours after the error is canceled. To my knowledge CP error is associated with not being able to communicate with ADT since we do not have a land line connected to the house. I've also heard these keypads need proprietary hardware to make the system to work locally and they refuse to do anything if you're not a paying customer.
