### ISSUE TITLE
Support for multiple "homes" in the same homebridge

### ISSUE THREAD

**Issue by wahlly** [nfarina/homebridge#1409]
I was wondering if it is possible to add support for more than one home to the same homebridge.

**Comment by justme-1968** [comment]
why would you want to do that?

just run two homebridge instances with separate config files.

**Comment by Krocko** [comment]
@justme-1968 how to do that?

**Comment by det-box** [comment]
run homebridge with,
"homebridge -U /home/pi/.homebridge/config.json"
and
"homebridge -U /var/homebridge/config.json"
