### ISSUE TITLE
Problems during install

### ISSUE THREAD

**Issue by consoleman** [nfarina/homebridge#141]
I am installing on a RPi Version B with raspbian.
Getting this during install:
pm ERR! mdns@2.2.9 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mdns@2.2.9 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the mdns package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls mdns
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/homebridge/npm-debug.log

Could someone help a bloody Linux newbie?

**Comment by consoleman** [comment]
Nobody can help me?

**Comment by KhaosT** [comment]
@consoleman please read [wiki](https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi) first... especially the ``Install Avahi`` section.

**Comment by consoleman** [comment]
Great, thanks for the hint, didn't see the wiki.
Now compiled but I have problems starting the server as the config.json seems to be not correct. I did a copy/Paste for hue and milight.
As I try to start the server I get an error reading the config. I can find no error.., plz help

{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    

    "platforms": [
        {
            "platform": "PhilipsHue",
            "name": "Phillips Hue",
            "username": ""
        }
   ]

    "accessories": [
        {
            "accessory":"MiLight",
            "name": "Lamp",
            "ip_address": "192.168.1.23",
            "port": 8899,
            "zone": 1,
            "type": "rgbw",
            "delay": 35,
            "repeat": 3
        }
    ]
}

**Comment by KhaosT** [comment]
@consoleman You missed "," before accessories.

```
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    "platforms": [
        {
            "platform": "PhilipsHue",
            "name": "Phillips Hue",
            "username": ""
        }
    ],
    "accessories": [
        {
            "accessory": "MiLight",
            "name": "Lamp",
            "ip_address": "192.168.1.23",
            "port": 8899,
            "zone": 1,
            "type": "rgbw",
            "delay": 35,
            "repeat": 3
        }
    ]
}
```

**Comment by snowdd1** [comment]
As I am frequently failing to write legal JSON I found khaosT's hint of http://jsonlint.com very helpful. Try to remind myself at each change (still failing at that too).

**Comment by consoleman** [comment]
Now it is up and running!
Thanks for your help
