### ISSUE TITLE
SSH Homebridge

### ISSUE THREAD

**Issue by node-ks** [nfarina/homebridge#1410]
Is there a known issue where the homebridge command doesn't work while you connect to Raspberry Pi running Raspbian via SSH? Homebridge works fine when I use VNC as a remote desktop and run homebridge natively via terminal but not via SSH. 

Maybe Im not fully aware of how Unix works.

**Comment by SkyJohn** [comment]
Are you using SSH under the same user you use for VNC?

**Comment by node-ks** [comment]
@SkyJohn Yes I am. Basically if I am in the desktop environment and I launch homebridge, everything works fine. If I SSH into it, the JS Object files cannot be found, although homebridge does run normally without any other issues.
