### ISSUE TITLE
Help on controlling Kodi With homeBridge

### ISSUE THREAD

**Issue by tonyschuite** [nfarina/homebridge#1413]
So I want to create a switch using an Http Json request called "Kodi Party mode" that triggers the following URL:

http://192.168.1.207:3444/jsonrpc?request={"jsonrpc":"2.0","id":"1","method":"Player.Open","params":{"item":{"partymode":"music"}}}

the Http plugins I am able to find are only for thermostats and such.
can anyone guide me in the right direction to setting this up with the right plugin?

**Comment by NorthernMan54** [comment]
Tony,

You may want to give this a try, its a little something I pulled together to control a web based IR Blaster I was playing with.  It is simple switches, and fires a url for each button press.

https://www.npmjs.com/package/homebridge-http-irblaster <https://www.npmjs.com/package/homebridge-http-irblaster>

**Comment by tonyschuite** [comment]
Thnx for the reply!
for those interested:

after quite some tinkering, I managed to make it work using switcheroo:

{
                "accessory": "Switcheroo",
                "type": "switch",
                "name": "Kodi Party Mode",
                "manufacturer": "OpenElec",
                "model": "V8.0.3",
                "host": "http://192.168.1.207:3444/jsonrpc?request=",
                "http_method": "GET",
                "username": "XXXX",
                "password": "XXXX",
                "on": "{\"jsonrpc\":\"2.0\",\"id\":\"1\",\"method\":\"Player.Open\",\"params\":{\"item\":{\"partymode\":\"music\"}}}",
                "off": "{\"jsonrpc\":\"2.0\",\"id\":0,\"method\":\"Player.Stop\",\"params\":{\"playerid\":0}}"
        }

**Comment by felipesalomao** [comment]
Hi @tonyschuite , i tried same thing... But it doesnt work.. 

See my code:
```
{
			"accessory": "Switcheroo",
			"type": "switch",
			"name": "Kitchen Light",
                      
                         
			"host": "http://192.168.1.158:8080/jsonrpc?request=",
                        "http_method": "GET",
                        "username": "",
                        "password": "",
			"on": {"jsonrpc":"2.0","method":"GUI.ActivateWindow","params":{"window":"videos","parameters":["RecentlyAddedMovies"]},"id":1},
			"off": {"jsonrpc":"2.0","method":"GUI.ActivateWindow","params":{"window":"videos","parameters":["recentlyaddedepisodes"]},"id":1}
		}
```

I am trying open Recenctly Added Movies and tv shows by command.. Its works  well when i type directly on brownswer using
`http://192.168.1.158:8080/jsonrpc?request={"jsonrpc":"2.0","method":"GUI.ActivateWindow","params":{"window":"videos","parameters":["recentlyaddedepisodes"]},"id":1}`

But using Switcheroo, it just not work.. Homebridge inicialize normally, but when i switch command, nothing happens.. I leaved my user and pass in blank on kodi to avoid any problem.. Also tried using admin:admin user and pass to test.. 
The only difference on my code for yours is:

You use "":
`"on": "{"jsonrpc":"2.0","id":"1","method":"Player.Open","params":{"item":{"partymode":"music"}}}",`

i Use: 
`"on": {"jsonrpc":"2.0","method":"GUI.ActivateWindow","params":{"window":"videos","parameters":["RecentlyAddedMovies"]},"id":1},`

As you can see, there is no " after `"on":`
If i try add, homebridge break and say config.json file is invalid.. 
On syntax checker, when i add it also say there is syntax  error.. https://jsonlint.com/

I think problem is related with this..
Thanks

**Comment by badnimits** [comment]
```
I solved this by escaping the " " chars from the line, it had a problem escaping the first " so I went with this and it worked for me:
  {
    "accessory": "Switcheroo",
    "type": "multiswitch",
    "name": "Kodi",
    "host": "http://192.168.1.10:8080/jsonrpc?r",
    "multiswitch":
 [
       { "name" : "RecentlyAdded"     , 
"path" :"equest={\"jsonrpc\":\"2.0\",\"method\":\"GUI.ActivateWindow\",\"params\":{\"window\":\"videos\",\"parameters\":[\"recentlyaddedepisodes\"]},\"id\":1}" },
 
    ]
}
```
