### ISSUE TITLE
Installation Guide

### ISSUE THREAD

**Issue by kingphil123** [nfarina/homebridge#1417]
Could anyone point me in the direction of a decent installation guide for Linux? Im new to this and can't find anything that tells me what Linux OS to use and all the installation steps.

**Comment by jm0477** [comment]
@kingphil123  almost the same step with the Rasberry Pi.  Recommend you to install it on ubuntu distribution, it's package system is same as the Rasberry Pi. so the command is also the same.

**Comment by cerniuk** [comment]
The only way I got my Raspberry PI Zero W (#rbp0w) working was with this:

cd /home/pi
sudo apt-get update
sudo apt-get remove nodejs nodejs-legacy -y
sudo apt-get install git-core libnss-mdns libavahi-compat-libdnssd-dev -y
sudo wget http://node-arm.herokuapp.com/node_latest_armhf.deb
sudo dpkg -i node_latest_armhf.deb
sudo rm -rf node_latest_armhf.deb
sudo npm install -g node-gyp
sudo npm install -g n
sudo n lts
sudo npm install -g --unsafe-perm homebridge hap-nodejs node-gyp

Other installs just failed, including the directions here on GitHub. Still having issues getting HomeBridge to announce itself on the network reliably when starting up as system vs under a user account (aka no user logged in, Homebridge starting and then available on network)
