### ISSUE TITLE
Another variance of "No Response" issue

### ISSUE THREAD

**Issue by pbeast** [nfarina/homebridge#1418]
Homebridge was installed, configured and running on the raspberry pi. Load on start set using systemd.There are only three plugins installed - one is [mqtt-switch-tasmota](https://www.npmjs.com/package/homebridge-mqtt-switch-tasmota) and other two are mine. My iPad acts as a home hub.

I'm able to add Homebridge to Home, distribute accessories over the rooms and configure automation triggers. So, everything is running perfectly from several hours to several days, BUT without the obvious reason (maybe it happens when my phone leaves the home network, but not always), Home App (more correctly to say HomeKit) stops seeing the bridge. Then nothing will help, only deleting Homebridge from the HomeKit database, remove accessories and persist folders from Homebridge deployment location and add Homebridge again using Home App.
There are no crashes in the log and all devices, including Homebridge, are accessible.

**Comment by Giorgiofox** [comment]
with new beta 5?

**Comment by pbeast** [comment]
No. iOS 10.3.3

Regards,
Pavel Yankelevich

**Comment by javefang** [comment]
Same issue here after ios 10.3.3 upgrade

**Comment by pbeast** [comment]
@javefang , you know, I haven't noticed that, but update to 10.3.3 makes perfect timing with the problem

**Comment by pbeast** [comment]
In other thread ( #1390, #126), people think that issue maybe caused by [homematic plugin](https://github.com/thkl/homebridge-homematic) in a case on of the devices become unresponsive.
I believe that it's not about the specific plugin, but Homebridge bug. Maybe, when Homebrige fails to access one of the devices, it marks all devices, connected to it,  as unavailable?

**Comment by nicoh88** [comment]
Same here - second time.

**Comment by justinshuls** [comment]
Restored a raspberry PI running homebridge with an identical config but getting "no response", is there other factors to how HomeKit recognizes a bridge? Static IP?

**Comment by riesch** [comment]
Same here with raspberry pi 3 with domoticz, homebridge and the domoticz plugin. Happend after restart, made sire everything was running

**Comment by nicoh88** [comment]
@justinshuls MAC (username) and Name (name)

@justinshuls @riesch @javefang 

**A few questions on the exact cause of the problem:**
1. Which plugins are configured in your config.json (npm -g list | grep -i homebridge)?
2. Do you have an original [Philips Hue Bridge](https://www.howtogeek.com/wp-content/uploads/2015/10/ximg_561e966beee38.png.pagespeed.gp+jp+jw+pj+ws+js+rj+rp+rw+ri+cp+md.ic.O2B_X_9wwF.png) on HomeKit in use?
3. Do you have an [HA-Bridge](https://github.com/bwssytems/ha-bridge) in use?
4. Do you have a [Devolo HomeControl](http://www.devolo.de/home-control/)?
5. Do you have an AppleTV or iPad as a HomeKit Home Hub in use? If so, which device and which iOS version?

**My answer:** 
1. homebridge-cmdswitch2, homebridge-devolo, homebridge-fritz, homebridge-harmonyhub, homebridge-homematic, homebridge-neato, homebridge-netatmo, homebridge-samsungtv-control, homebridge-sonos, homebridge-sonybraviatv, homebridge-vorwerk
2. Yes, v2.
3. [Yes, for my logitech harmony hub](https://www.loggn.de/logitech-harmony-companion-haussteuerungstasten-fremd-belegen-ha-bridge/).
4. Yes.
5. Yes. 
5.1. Home Hub: iPad mini 3 with iOS 10.3.3.
5.2. Client Devices: iPhone 7 with iOS 11b5 and iPad Air 2 with iOS 11b5.

**Comment by riesch** [comment]
My answers:
1. Cannot execute that command at this point, other than that I only installed the edomotic plugin for domoticz.  I  cleared the sd-card and have yet to reinstall homebridge
2. I have hue bridge 2, but not installed on homekit or homebridge
3. No
4. No
5. No, I have those devices but do not use them as home hub
6. I do not use homematic

**Comment by javefang** [comment]
I only use hombridge as a homekit bridge for homeassistant, so my answers are:
1. Just 'homebridge-homeassistant'
2. No
3. No, other than the homeassistant running on the same rpi3
4. No
5. No
6. N/A (don't have one)

**Comment by pbeast** [comment]
1. mqtt-switch-tasmota and two homemade plugins
2. No
3. No
4. No
5. iPad Mini 3 as home hub iOS 10.3.3
6. Don't have one

**Comment by nicoh88** [comment]
https://github.com/nfarina/homebridge/issues/1428

**Comment by pdlove** [comment]
Give it a try with Homebridge 0.4.25 which was just updated.  It may not fix the Not Responding issue but should prevent you having to delete the persist folder to recover.

**Comment by pbeast** [comment]
Updated to 0.4.26 yesterday. So far so good :-)

**Comment by macjeff** [comment]
Been working fine for 3 days now

**Comment by nicoh88** [comment]
Works. Issue can be closed.

**Comment by pbeast** [comment]
Runs without issues for the 10 days.
Closing the issue.

Thanks a lot!
