### ISSUE TITLE
Please clarify preference 'raw' service descriptions vs. 'class based'

### ISSUE THREAD

**Issue by desvdp** [nfarina/homebridge#142]
Thanks for providing this project, loving it ... and making my own platforms :-)
But here's where I'm struggling: by looking at existing implementations I noticed there are two styles for coding services/accessories:
- The "raw" method where the services are assembled manually as data structures (e.g. just like in the Hue platform implementation) 
- The class based method where the Service/Characteristic classes are used to define the service (e.g. as in the MiLight accessory) 

I understand both probably yield similar results, but is there a preferred way for implementing new platforms, are there any advantages/disadvantages to either (better future compatibly?). I'd love to get your opinion on this.

**Comment by snowdd1** [comment]
The API method is absolutely preferable. See the Wiki page on [migration](https://github.com/nfarina/homebridge/wiki/Migration-Guide)
Regards
Raoul

**Comment by snowdd1** [comment]
Even better, see the [roadmap](https://github.com/nfarina/homebridge/wiki/Roadmap), migration does only point to that.

**Comment by desvdp** [comment]
Thanks, that's clear: I'll close the issue
