### ISSUE TITLE
ignore plugin?

### ISSUE THREAD

**Issue by imperialjoy** [nfarina/homebridge#1421]
Would it be possible to add an ignore option for plugins? 

The plugin homebridge-mi-aqara has a problem, once its installed, all instances of homebridge must have a mac address and password for the aqara device defined. Since plugins can have their own issues, it would be best to be able to dynamically load plugins instead of loading everything every time (for example plugin-name-ignore.txt). But until then, I'd settle for a knx-ignore.txt style solution too, say "aqara-ignore.txt".

**Comment by snowdd1** [comment]
Post that at aqara plugin repo?
