### ISSUE TITLE
HELPPP

### ISSUE THREAD

**Issue by LeonIOM** [nfarina/homebridge#1426]
Hey

Really tearing my hair out here. Is anyone able to help me out at all? Stuck on the following in GIT-CMD:

C:\Users\Leon>npm install -g homebridge
C:\Users\Leon\AppData\Roaming\npm\homebridge -> C:\Users\Leon\AppData\Roaming\npm\node_modules\homebridge\bin\homebridge

> mdns@2.3.3 install C:\Users\Leon\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns
> node-gyp rebuild

C:\Users\Leon\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns>if not defined npm_config_node_gyp (node "C:\Users\Leon\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  dns_sd.cpp
  dns_service_browse.cpp
  dns_service_enumerate_domains.cpp
  dns_service_get_addr_info.cpp
c:\users\leon\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Cannot
 open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\dns_service_browse.cpp) [C:\Use
rs\Leon\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
c:\users\leon\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Cannot
 open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\dns_service_get_addr_info.cpp)
[C:\Users\Leon\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  dns_service_process_result.cpp
  dns_service_ref.cpp
c:\users\leon\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Cannot
 open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\dns_service_enumerate_domains.c
pp) [C:\Users\Leon\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  dns_service_ref_deallocate.cpp
c:\users\leon\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Cannot
 open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\dns_sd.cpp) [C:\Users\Leon\AppD
ata\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  dns_service_ref_sock_fd.cpp
c:\users\leon\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Cannot
 open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\dns_service_process_result.cpp)
 [C:\Users\Leon\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
c:\users\leon\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Cannot
 open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\dns_service_ref.cpp) [C:\Users\
Leon\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  dns_service_register.cpp
c:\users\leon\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Cannot
 open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\dns_service_ref_deallocate.cpp)
 [C:\Users\Leon\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  dns_service_resolve.cpp
  dns_service_update_record.cpp
c:\users\leon\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Cannot
 open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\dns_service_ref_sock_fd.cpp) [C
:\Users\Leon\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  mdns_utils.cpp
c:\users\leon\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Cannot
 open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\dns_service_register.cpp) [C:\U
sers\Leon\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
c:\users\leon\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Cannot
 open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\dns_service_resolve.cpp) [C:\Us
ers\Leon\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  network_interface.cpp
c:\users\leon\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Cannot
 open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\dns_service_update_record.cpp)
[C:\Users\Leon\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  socket_watcher.cpp
  txt_record_ref.cpp
c:\users\leon\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Cannot
 open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\mdns_utils.cpp) [C:\Users\Leon\
AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  txt_record_create.cpp
c:\users\leon\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Cannot
 open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\network_interface.cpp) [C:\User
s\Leon\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
c:\users\leon\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Cannot
 open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\txt_record_ref.cpp) [C:\Users\L
eon\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
c:\users\leon\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Cannot
 open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\socket_watcher.cpp) [C:\Users\L
eon\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  txt_record_deallocate.cpp
  txt_record_set_value.cpp
  txt_record_get_length.cpp
c:\users\leon\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Cannot
 open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\txt_record_create.cpp) [C:\User
s\Leon\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  txt_record_buffer_to_object.cpp
c:\users\leon\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Cannot
 open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\txt_record_deallocate.cpp) [C:\
Users\Leon\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
c:\users\leon\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Cannot
 open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\txt_record_set_value.cpp) [C:\U
sers\Leon\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  win_delay_load_hook.cc
c:\users\leon\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Cannot
 open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\txt_record_get_length.cpp) [C:\
Users\Leon\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
c:\users\leon\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Cannot
 open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\txt_record_buffer_to_object.cpp
) [C:\Users\Leon\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Leon\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\Leon\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Leon\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns
gyp ERR! node -v v5.0.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mdns@2.3.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mdns@2.3.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Leon\AppData\Roaming\npm-cache\_logs\2017-08-11T18_44_47_026Z-debug.log

Many thanks in advance!
Leon

**Comment by pdlove** [comment]
Have you done "npm install --global windows-build-tools" yet? And is iTunes installed? I'm not sure if that is still required on windows installs as it's part of my base installs any more.
