### ISSUE TITLE
"No response" after running about several days

### ISSUE THREAD

**Issue by nhyjq** [nfarina/homebridge#1428]
hardware: Raspberry Pi 3B
homebridge version: 0.4.22
nodejs version: 6.11.2
iOS version: 10.3.2

We implemented a platform plugin(as a bridge) that communicate our original lighting control through serialport. There are dozens of accessories in bridge.  System runs well and Home App control is also well. But after several days, all accessories icon in Home App display "No Response".  It cannot be recovered by restarting  Raspberry Pi, Home App or my iPad.  Surely to change username in config.json and delete persist/* files can recovery it.  
It perhaps stuck somehow(reference in common issues of README.md). But we hope our product could be stable because it is planning to sale. Could anybody know the real reason and how to solve it?

**Comment by iCarl** [comment]
I have the same issue,
By the way, are you planing on selling Homebridge as a product?
Pretty sure that is illegal.

**Comment by pdlove** [comment]
I have Homebridge installations that have run flawlessly for months. It is only as stable as the most unstable plugin.
FYI, Apple’s open HomeKit license does not apply to sold products. Those must be MFI certified and the current Homebridge implementation does not support the hardware chip required for that. You might be able to get around that by simply charging for implementation services of your free plugin. I’d be wary of that because the spirit of the open license is that it is for “personal development” only and we can only slip by here because you install your own product.

**Comment by pdlove** [comment]
One more note.. your symptoms described are often caused by invalid values being set on characteristics. You can try using my fork of hap-nodejs in place of the npm release. It contains validation checks designed to prevent that kind of total loss of an installation.

**Comment by nhyjq** [comment]
Thank you pdlove. Our product is not for retail market, just intergrate enginnering project, so this product based on Rpi and plugin can be free for customer. 
Let's focus on technology.  I've never seen invalid values  in debug level log. So I‘m curious what will happen if  characteristics was set a invalid value. in Characteristic.prototype.setValue source code, it seems that only handle undefine and null.  And if a numeric characteristic is set a string?

And which release should I clone from you fork or just clone master? 

Thank you very much again.

**Comment by pdlove** [comment]
@nhyjq It shouldn't be much longer until the changes are merged into the master. You might simply want to wait a week or so to test it then. If you can't wait, you can pull it from the fork I've got. To implement this, I've added a validateValue function that is called when the characteristic's value is being change. The change can come from a setCharacteristic/updateCharacteristic and it's also validated when a function performs it's callback. The validate process attempts to coerce a valid value and will retain the original if it can't figure out what you're doing. Here's a link to the current iteration so you can see: https://github.com/pdlove/HAP-NodeJS/blob/c04ea56a15ddcedea47e7ce9a07585c8f4d7d284/lib/Characteristic.js#L172

**Comment by nicoh88** [comment]
Workaround: `npm install -g git+https://git@github.com/pdlove/HAP-NodeJS.git`

@pdlove Thank you very much! 👍

**Comment by pdlove** [comment]
The changes have been merged into the latest HAP-NodeJS and homebridge should be updated shortly for the new version.

**Comment by iCarl** [comment]
Should install it by running "sudo npm install -g homebridge", or just HAP-NodeJS?

**Comment by nhyjq** [comment]
@pdlove Thank you very much. I'll test this version ASAP.

**Comment by iCarl** [comment]
Works great so far!

**Comment by nicoh88** [comment]
Works. Issue can by closed.
