### ISSUE TITLE
Homebridge restart = Loss of all configuration (rooms, scenes,...)

### ISSUE THREAD

**Issue by cariacou** [nfarina/homebridge#1434]
Hello.

I have installed homebridge and it works great for my devices.
However, when I need to restart homebridge (power surge, or manually), I lose all the previously set configuration. All the room assignment or scene assignment is gone.

Am I doing something wrong? Does anyone else have this issue? 

My config.json is very simple, only fields filled are 'bridge', 'description', 'platform' (no accessories, could that be the issue?)

**Comment by pdlove** [comment]
You shouldn't lose the room settings. That's typically caused by a faulty plugin. Which plugins are you using?

**Comment by cariacou** [comment]
I am running homebridge & smartthings. I think that's all the homebridge plugins I have

**Comment by michaelbrown2** [comment]
I have a similar issue but only occasionally, I use SmartThings and the Logitech plugins. It seems to happen if I've recently added a new device, after the HomeKit service starts again. It's happened twice in the last few weeks and it's quite frustrating. I run HomeKit in an ubuntu 16.04 virtual machine.

**Comment by pdlove** [comment]
I've never experienced this, but I run SmartThings in it's own instance of Homebridge. I've got a version of smartthings plugin ready to go for the newer Homebridge API that may resolve the issue of losing rooms. I was hoping they would announce/release their internal API before I put that out but it looks like it's going to be another couple of months. I'll open an Issue on the Smartthings github tonight to canvas people and see how many experience this. In the next few days I should be able to have an update available on that plugin.

**Comment by cariacou** [comment]
Thank you!
Your work is really appreciated pdlove. 
I'll monitor the homebridge-smartthings to make sure I don't miss the commit

**Comment by keithcroshaw** [comment]
Hey I'm having this same issue whenever my RPi restarts. Now it's in a docker Pi setup, I'm not sure what kind of variables that could introduce but it seems to be the same issue. The gateway is still there but the devices re-appear in the default room and all of my scenes are gone. Any assistance is appreciated. Thanks for making awesome.

**Comment by turnepf** [comment]
Has there been any resolution to this? I continue to have this issue when cycling the raspberry pi. 

And as everyone else has said, thanks for this @pdlove. It's a game changer in my home automation!

**Comment by keithcroshaw** [comment]
I'm up to date and my issue still exists.
I just pray for no power failures.
I need a battery backup...

**Comment by turnepf** [comment]
Yah @keithcroshaw , I've gotten pretty fast at adjusting the settings on my 60 devices whenever I cycle that machine but boy I'd love to not have to do it!

**Comment by turnepf** [comment]
@keithcroshaw - checking it out, thanks. If it saves you on your next reboot please let me know.

**Comment by Anuj79** [comment]
any update on this ?

**Comment by hakkespetten** [comment]
I have the same problem. All room associations are gone after a restart of my RPi with Homeseer.  Does anybody know where this config is stored? Whenever I restart my Pi I use an app on my iphone called "MyTouchHome" where I can put my devices back to the rooms. This app does not communicate with my Pi, so I assume the config is done in apple clouds... I guess homebridge must somehow send these instructions to the cloud when starting??

**Comment by turnepf** [comment]
for me, if I run it in a console, it doesn't lose the settings when rebooting the pi. It's only when running it as a service (which is the normal way I run it) that the settings are gone on reboot. Touch MyTouchHome have a way to automatically restore the settings? I have controller (mentioned ^) but haven't tried the restore function yet. Would prefer to have a real solution.

**Comment by hakkespetten** [comment]
>Touch MyTouchHome have a way to automatically restore the settings?

The MyTouchHome -app for ios doesn't have any automatic restore. I have to drag and drop each of my devices into the room they belongs to after a restart.

**Comment by AndrewVIsh** [comment]
Any updates on this? still loosing room assignments when powers goes out. Thank you

**Comment by hakkespetten** [comment]
This problem was solved after I installed a fresh homebridge on a new rpi without homeseer running on the same host.

**Comment by bryanbarton525** [comment]
Ran into this issue myself, just figured I would leave a quick comment. There is is an option under accessories gear called "toggle layout lock", selecting this option resolved the issue for me.
