### ISSUE TITLE
homebridge starts ok, but is unresponsive after hour(s)

### ISSUE THREAD

**Issue by jeroen1973** [nfarina/homebridge#1438]
hi there

i have a rapberrypi 3 with raspbian jessie updated to the latest version. 

plugins:
homebridge-homewizard 0.0.59
homebridge-nest

When i start homebridge al runs well, no errors,  i can find homebridge in homekit on iphone.

After several hours it becomes unresponvive and cant be controlled anymore....

what is going wrong?

**Comment by pdlove** [comment]
Any errors when it is unresponsive?
On the apple side in Home does it show as Not Responding or shows normal and just doesn't work?
Have you upgraded Homebridge?

**Comment by jeroen1973** [comment]
At first on Apple side everything works, then is says 28 accesories are unavailable, dont respond. Homebridge is running on pi side

Jeroen van der Wal

Op 16 aug. 2017 om 22:50 heeft pdlove <notifications@github.com> het volgende geschreven:

Any errors when it is unresponsive?
On the apple side in Home does it show as Not Responding or shows normal and just doesn't work?
Have you upgraded Homebridge?

**Comment by jeroen1973** [comment]
Homebridge is latest version, but also prior version had Same problem. The latest version Now also had problema Reading The 'homewizard' settings

**Comment by kstaniek** [comment]
The same from me. Stops working after 1-2 hours.

**Comment by pdlove** [comment]
Can y'all identify which plugins are in use? That's critical to be able to help with these things.

**Comment by jeroen1973** [comment]
Homewizard and nest


Op 17 aug. 2017 om 15:09 heeft pdlove <notifications@github.com> het volgende geschreven:

Can y'all identify which plugins are in use? That's critical to be able to help with these things.

**Comment by kstaniek** [comment]
I've got only homebridge-homeassistant installed. Nothing more.

**Comment by macjeff** [comment]
I am getting this too with latest version of homebridge.   

Jeff

**Comment by pdlove** [comment]
Was it working for more time before I started tinkering with HAP-NodeJS?

**Comment by macjeff** [comment]
It was running for me non stop except when I did an update sometimes it would mess up

AND of course one device was not supported.

This seemed to be ok until version .23   I never did .24 and went right to .25.

Now just installed .26.

I will update later

Jeff

**Comment by jeroen1973** [comment]
Found the solution! all is working fine now!  here are the steps i did:

Stop homebridge,

update homebridge  (sudo npm install -g --unsafe-perm homebridge)

Deleted the PERSIST and ACCESSORIES folders in the ~/.homebridge directory 
R
estart Avahi (sudo systemctl restart avahi-daemon)

Delete homekit house on ios

start homebridge

add to homekit andf it works like a charm!
