### ISSUE TITLE
Querying homebridge to deliver values of plugins

### ISSUE THREAD

**Issue by qudarr** [nfarina/homebridge#1443]
Is it possible to query homebridge to deliver infos of the connected devices?
I would like to integrate this data into node RED and other analytic tools to find out how the temperature curve is, etc.

**Comment by NorthernMan54** [comment]
Yes it is feasible, the easiest approach is explore "insecure mode".  If you look around you can see examples of accessing it using curl.

**Comment by qudarr** [comment]
Thanks for the quick response!
