### ISSUE TITLE
Can't get iOS to see Homebridge

### ISSUE THREAD

**Issue by AKWillows** [nfarina/homebridge#1445]
Hi

I have a problem getting iOS to "see" home bridge when I try to add it in the Home app. I'm new to the world of RaspberryPi and have really enjoyed problem solving and getting to the point where I have it running.

A few days ago, I tried to set up Homebridge using a Homebridge app that is available in the iOS app store. All went well and I was able to add it to iOS. Unfortunately, the configuration didn't seem to work and I could not get the plug-ins to install and run properly. So I completely started again, formatting the RaspPi SD card and deleted the accessory in the iOS app.

By following the instructions here and the linked WIKI, I now have everything running properly with my plug ins up and running too, but when I try to add the accessory in iOS Home app it just continues to search and finds nothing.

I have tried the following:
1) deleted homebridge/persist directory
2) changed the username in the "bridge" section of config.json (I used the actual MAC address of the RPi)

No luck. So then I tried repeating the above and also changed the "name" and "pin" in the "bridge" section of the config.json. I also changed the IP address of the RPi in the hope that iOS would see it as something new.

Still to no avail. Is there anything else I can try/check? Is it a problem that I have previously paired this device with iOS?

(One dumb Q.... once I start Homebridge by typing homebridge in the terminal... it appears everything loads and it gives me the PIN and tells me it is listening on a particular port. The terminal window then sits there with no prompt so I assume it is still running. How would I know if it had crashed?)

**Comment by shidevil** [comment]
Since you type homebridge on terminal, it will show if the homebridge have crash with error. 

If it doesn't, we can assume it is running. 

Post the log please and also your config.json

**Comment by AKWillows** [comment]
Yes, still running it in terminal - haven't got as far as setting it up to run at startup yet.

Stupid question, but I can't find the log file location! The troubleshooting section here says that it will be in var/log/homebridge.log, but it's not! I've done a file search in File Manager, showing hidden files, but still can't find it.

Here is my config.json (i've changed a lot of the values in the "bridge" section to try to get iOS to "see" it

{
    "bridge": {
        "name": "BrenchleyHomebridge",
        "username": "B8:27:EB:99:EB:56",
        "port": 51826,
        "pin": "031-45-155",
        "manufacturer": "maker",
        "model": "Homebridge",
        "serialNumber": "0.4.21"
    },
    
    "platforms": [
       {
           "platform" : "LightWaveRF",
           "name" : "LightWaveRF",
           "ip_address": "192.168.1.15",
           "devices": [
               {
                   "roomId": 1,
                   "roomName": "Kitchen",
                   "deviceId": 1,
                   "deviceName": "Ceiling1",
                   "deviceType": "D"
               },
               {
                   "roomId": 1,
                   "roomName": "Kitchen",
                   "deviceId": 2,
                   "deviceName": "Toplights",
                   "deviceType": "S"
               },
               {
                   "roomId": 1,
                   "roomName": "Kitchen",
                   "deviceId": 3,
                   "deviceName": "Worktop",
                   "deviceType": "S"
               },
               {
                   "roomId": 1,
                   "roomName": "Kitchen",
                   "deviceId": 4,
                   "deviceName": "Plinth",
                   "deviceType": "S"
               }
           ]
       }
]
}

**Comment by shidevil** [comment]
Copy the logs from the terminal when you run homebridge. Could you check what is your iOS version? 

delete homebridge/persist and homebridge/accessories. 

Could you try this config.json? 

{
"bridge": {
"name": "MyHomebridge",
"username": "B8:27:EB:99:EB:56",
"port": 51826,
"pin": "031-45-155"
},

"platforms": [
   {
       "platform" : "LightWaveRF",
       "name" : "LightWaveRF",
       "ip_address": "192.168.1.15",
       "devices": [
           {
               "roomId": 1,
               "roomName": "Kitchen",
               "deviceId": 1,
               "deviceName": "Ceiling1",
               "deviceType": "D"
           },
           {
               "roomId": 1,
               "roomName": "Kitchen",
               "deviceId": 2,
               "deviceName": "Toplights",
               "deviceType": "S"
           },
           {
               "roomId": 1,
               "roomName": "Kitchen",
               "deviceId": 3,
               "deviceName": "Worktop",
               "deviceType": "S"
           },
           {
               "roomId": 1,
               "roomName": "Kitchen",
               "deviceId": 4,
               "deviceName": "Plinth",
               "deviceType": "S"
           }
       ]
   }
],
"accessories": []
}

**Comment by AKWillows** [comment]
Hi - thanks for coming back so quickly - I REALLY appreciate it!! My iOS version is 10.3.3. AppleTV is my HomeKit hub and that is running 10.2.2. (Both the latest release versions i think)

I have made the amendment to the config.sys file and deleted the two folders as suggested. Unfortunately HomeKit still doesn't seem to be able see the homebridge.

I have my RaspberryPi connected via LAN cable... is this ok? The homekit guides seem to say that Wifi and bluetooth have to be enabled on the hub. (Although that hasn't changed since I WAS able to add it to Home with my previous homebridge configuration).

The output is as follows. There is an error line saying that config can't be found, but I think this is normal as there is two ways of setting up the lamps in the Lightwave plugin depending on which type of lightwave account you have.

pi@raspberrypi:~ $ homebridge
*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
[2017-8-19 08:52:04] Loaded plugin: homebridge-lightwaverf
[2017-8-19 08:52:04] Registering platform 'homebridge-lightwaverf.LightWaveRF'
[2017-8-19 08:52:04] ---
[2017-8-19 08:52:04] Loaded config.json with 0 accessories and 1 platforms.
[2017-8-19 08:52:04] ---
[2017-8-19 08:52:04] Loading 1 platforms...
[2017-8-19 08:52:04] [LightWaveRF] Initializing LightWaveRF platform...
[2017-8-19 08:52:04] [LightWaveRF] LightWaveRF Platform Plugin Version 0.1.3
[2017-8-19 08:52:04] [LightWaveRF] Fetching LightWaveRF switches and dimmers...
No email or pin specified. The server configuration (rooms, devices, etc.) cannot be obtained
device = 
{ roomId: 1,
  roomName: 'Kitchen',
  deviceId: 1,
  deviceName: 'Ceiling1',
  deviceType: 'D' }
device = 
{ roomId: 1,
  roomName: 'Kitchen',
  deviceId: 2,
  deviceName: 'Toplights',
  deviceType: 'S' }
device = 
{ roomId: 1,
  roomName: 'Kitchen',
  deviceId: 3,
  deviceName: 'Worktop',
  deviceType: 'S' }
device = 
{ roomId: 1,
  roomName: 'Kitchen',
  deviceId: 4,
  deviceName: 'Plinth',
  deviceType: 'S' }
[2017-8-19 08:52:04] [LightWaveRF] Initializing platform accessory 'Kitchen Ceiling1'...
[2017-8-19 08:52:04] [LightWaveRF] Initializing platform accessory 'Kitchen Toplights'...
[2017-8-19 08:52:04] [LightWaveRF] Initializing platform accessory 'Kitchen Worktop'...
[2017-8-19 08:52:04] [LightWaveRF] Initializing platform accessory 'Kitchen Plinth'...
[2017-8-19 08:52:04] Loading 0 accessories...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-155 │     
    └────────────┘     
                       
Receiver socket listening 0.0.0.0:9761
[2017-8-19 08:52:04] Homebridge is running on port 51826.

**Comment by AKWillows** [comment]
One other Q - I am trying to do all of this before i set up homebridge to launch on startup. (Just to prove that my setup it does actually work). If I pair it with Home now, will that change once I have got the auto start up set up?

**Comment by shidevil** [comment]
@AKWillows Yes that will change if you were to set up homebridge to launch on startup. You will have to redo everything unless you copy over the homebridge/persist and accessories.

Could you remove the plugins by doing a sudo npm -g uninstall homebridge-lightwaverf then remove the configuration at config.json to test if u can detect homebridge on your iOS? 

thank you

**Comment by AKWillows** [comment]
I think I should probably get it running on startup first then - otherwise i will hit all of this again I think. I'll work on that and then try again!

**Comment by shidevil** [comment]
@AKWillows most important is that the iOS must be able to find homebridge. I think there's some problem somewhere..

**Comment by AKWillows** [comment]
Yes, exactly. I think what I will do is to uninstall the Lightwave plug in... just in case that is causing issues, then set up home bridge to launch on startup (maybe with another plugin), then delete the persist and accessories, change the MAC address and name in "bridge" settings and try with iOS again? Then can reinstall Lightwave plugin if it all works? What do you think?

**Comment by shidevil** [comment]
@AKWillows that sounds good. you can install a fake plugin

https://github.com/schemish/homebridge-fakebulb

to test it out

**Comment by AKWillows** [comment]
Ah great - will do that :-) Will be tomorrow now... have to get away from my screen and have a life for a bit! :-)

**Comment by AKWillows** [comment]
HI @shidevil - thanks very much for your assistance. I did exactly as I outlined above and everything seems to be working perfectly! *fingers crossed* !

**Comment by shidevil** [comment]
@AKWillows that sounds good. Do mark this as close if it's working

**Comment by AKWillows** [comment]
Will do - cheers
