### ISSUE TITLE
Build Error (new to Node.js myself)

### ISSUE THREAD

**Issue by JupiterFlux** [nfarina/homebridge#1450]
Upon trying to install with 
sudo npm install -g —unsafe-perm homebridge
I get many errors but I figure if I eliminate them one at a time the rest may just go away on their own. 
First. (Pardon formatting, will fix if I can figure it out.)
(Note this is my first time doing anything with Node.js so I may be missing something obvious.)

Fatal error: dns_sd.h: no such file or directory
dns_sd_bindings.target.mk:153: recipe for target ‘Release/obj.target/dns_sd_bindings/src/dns_sd.o’ failed
Make: [that last path] Error 1
Make leaving directory... 
Error make failed with exit code 2

It goes on for a while with errors and locations in a script where the error occurred. But I know enough to figure that fixing the first errors may fix the rest. I can add more information if necessary. 

I’m using Ubuntu 16.04. And I can not easily copy and paste or type here on that computer, so I retyped and shortened some things. Let me know if additional information is needed for proper debugging.

**Comment by shidevil** [comment]
Try this sudo apt-get install libavahi-compat-libdnssd-dev

**Comment by JupiterFlux** [comment]
Thanks. That solved the problem. Don’t know why, I sort of assumed it was installed already and completely ignored that part of the installation guide.
