### ISSUE TITLE
Check if homebridge is running

### ISSUE THREAD

**Issue by noaboa97** [nfarina/homebridge#1451]
Hi, 
So I was wondering, if there is any command to check if homebridge is running?

When I use the command:
service homebridge status
 homebridge.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)

althought I just started homebridge and it's running and working.
 
and if I use 
 service --status-all

then homebridge doesn't show up in the list.

Because I would like to somehow check if homebridge is still running and maybe I will have it displayed somewhere thats its still running.

Thanks

**Comment by shidevil** [comment]
Did you install homebridge as systemd or initd? 

If systemd, Try sudo systemctl status homebridge

**Comment by noaboa97** [comment]
none of them I always start the homebridge by hand.

**Comment by shidevil** [comment]
If you start homebridge by hand. The terminal will show if it's running? If there's error the terminal will show as well?
