### ISSUE TITLE
Listing all available characterstics with AID and IID?

### ISSUE THREAD

**Issue by qudarr** [nfarina/homebridge#1452]
How can I list all available characteristics?
I would like to poll them similar to this:

> curl -X GET http://127.0.0.1:51826/characteristics?id=2.9 --header "Content-Type:Application/json" --header 'authorization: 031-45-777'

Where 2 equals the AID and 9 the IID

**Comment by natanrolnik** [comment]
For the record (and myself in the future), to list all the devices and characteristics, homebridge returns them in a get request under the `/accessories` path:

```sh
curl http://127.0.0.1:51826/accessories -H "Content-Type: Application/json" -H "Authorization: 031-45-777"
```
