### ISSUE TITLE
"Updating" every time I open show the accesories

### ISSUE THREAD

**Issue by greensouth** [nfarina/homebridge#1454]
Hi!

I don't know it is happening to me only, but every time I open either the Home app or the panel with my favourite accessories, it ALWAYS refresh their status. It just take a couple of seconds or five, but it's kinda annoying. I don't know if it's a common behaviour or something is just wrong with caches or whatever.

Happens both, when I'm at home and when I'm not. Using an ATV4 and iPad as bridge.

Best regards :)

**Comment by maragelis** [comment]
That's how HomeKit works.

**Comment by pdlove** [comment]
I will say that some plugins update quicker than others. But the Home app requests an update every time you enter it.

**Comment by cquanu** [comment]
Me too... but my non homebridge accessories load faster (almost instantly). Anyone knows what’s the problem?

**Comment by bencharlesrhys** [comment]
Same thing is happening with me. Sometimes it takes 4-5 seconds with "Updating..." before I can control HomeBridge devices. Native/signed homekit devices are instant. I'm guessing it's the plugins I'm using and I need to eliminate them 1-by-1 to check the cause.

**Comment by NorthernMan54** [comment]
What your seeing is a plugin design / implementation issue, if a plugin pulls the current status for an accessory, and it takes time to do this it will cause this.  If a plugin pushes status with a status change event and uses updateValue to update homebridge it won’t. 

Your native HomeKit devices, when they are asked for status are able to immediately reply, while most homebridge ones need a second request to the actual device to get status, hence the delay.  What makes the delay so long when the Home app is opened, is that Home updates the status for I think everything on the screen when you open it.
