### ISSUE TITLE
Homematic Shutter-Contact & Nuki-PlugIn

### ISSUE THREAD

**Issue by roe1974** [nfarina/homebridge#1456]
Since Update to 0.4.27 i have two problems:
Homematic Shutter-Contatcs are not updating state (only when i reboot homebridge the state is correct9
Nuki-Plugin.....same issue
can this due to the homebridge update ?

regards, Richard

**Comment by shidevil** [comment]
You can revert back to the old homebridge to check? 

sudo npm install -g homebridge@0.4.2x

**Comment by roe1974** [comment]
ok...i will try tonight.
i also upgraded nodejs from 8.1.4 to 8.4.0
could this be the reason to ?
Richard

**Comment by shidevil** [comment]
@roe1974 Node may or may not have issue. best would be to revert to the original one and try

**Comment by roe1974** [comment]
how can i go back to nodejs 8.1.4 ?
thx richard

**Comment by shidevil** [comment]
@roe1974 You can read this up https://www.abeautifulsite.net/how-to-upgrade-or-downgrade-nodejs-using-npm

But i suggest you downgrade the homebridge first and test it out. It may be just homebridge issue.

**Comment by roe1974** [comment]
back to 0.4.22 .... everything works fine now :-)
thx !
richard

**Comment by shidevil** [comment]
@roe1974 No problem please close this issue

**Comment by roe1974** [comment]
works only for a certain time after restarting the homebridge. After the time i have to restart the "Home" app on my iPhone every time to see the actual state of the shutter contact.....
any idea ?
Richard

**Comment by shidevil** [comment]
That is because the shutter isn't polling the status. You need to ask the plugin creator.

**Comment by roe1974** [comment]
ok, thx
