### ISSUE TITLE
Group more then one Lights to one accessory

### ISSUE THREAD

**Issue by luxus** [nfarina/homebridge#146]
Hi,
i have 2 rooms with 2 big lamps (with 3 bulbs)
in the philips hue app i can group them together to change color/hue/brightness at ones
i would love to have the same functionality in homebridge.
at the moment it looks like that:
![img_0309](https://cloud.githubusercontent.com/assets/7449/9704006/0d7cf72a-5496-11e5-961b-c3bed6666fde.jpg)

i found a conversation about a similar issue, but my node.js skills are to basic to understand it 
https://github.com/nfarina/homebridge/issues/139

**Comment by snowdd1** [comment]
The issue mentioned was a bit different, that was about the relationship between `accessories` and `services`.

I understand you want your multi-hue be controlled with one set of controls. I am not into the hue shim, but I assume that you probably can modify it to send the same commands to multiple hues at once.

**Comment by KhaosT** [comment]
@luxus You're talking about an app side issue. In HomeKit there is something called "Service Group" which allows you group services together and control theme all at once. However, so far I haven't seen any app implements that ... There is nothing can be done on the server side.

**Comment by luxus** [comment]
@KhaosT you are right, Service Group is exactly what im looking for. Do you know what's happens if you create a Group with one app will it be availible for other apps even if you can't create Service Groups there?

https://developer.apple.com/library/prerelease/ios/documentation/HomeKit/Reference/HMServiceGroup_Class/index.html

**Comment by KhaosT** [comment]
@luxus Other apps will have access to that service group but since they didn't implement anything to control service group, it won't do anything...

**Comment by nzhome** [comment]
why not just put them all under one room called "downstairs"   then you can say "downstairs lights off"  all current apps can do that now.

**Comment by luxus** [comment]
i want to be able to change the colors/hue of 3 lamps at once with the apps.. as far as i know thats not possible to do it via siri
i use the room feature a lot .. but sometimes u just want to change the colors of the lamps a little bit

i talked to the developer of MyTouchHome he is considering to add the feature in a future release, he is working on a iOS9 update right now.

**Comment by justme-1968** [comment]
grouping them in homekit or homebridge is not the right approach i think. at least not for hue multisource lamps. the hue api provides groups for this and these lights automatically create a group in the hue hup for this. the 'correct' way would be to extend the hue shim to include support for these hue groups.

if you happen to use fhem this should already work.

**Comment by SphtKr** [comment]
Yes, the Hue shim could probably expose the group as its own device, that would be good.

However, this gets me thinking about a general purpose master-slave device...you could possibly make an Accessory in Homebridge that would forward events it received to another Accessory...that would let you do what @luxus is describing not just for Hue bulbs, but for WeMo switches or Z-Way devices or whatever...it's an interesting thought.

Arguably, yes, Service Groups is where this should be implemented, but unfortunately I'm not sure there's a client that supports that yet, no.

**Comment by luxus** [comment]
The iOS 9 Demo catalogue Supports Service Groups! Even the eve app does! But they just Group them for Siri! It's not possible to change hue of a Service Group in the apps! There is no Group Display with merged Charactertics

**Comment by KhaosT** [comment]
@luxus Yeah, it's up to app to decided what kind feature Service Group should support ... right now HMCatalog only support creating service group but not doing anything useful with that .
