### ISSUE TITLE
How do i change an accessory type or someone do it for me

### ISSUE THREAD

**Issue by daniel2029** [nfarina/homebridge#1460]
Hi,

I am using home bridge to open and close my garage door.

The relay doesn't seem to speak the same language as the plugins so the plugins cannot read when my door is open or not.

I found a plugin called http-switch except it thinks the accessory is a light when i want it to be a garage.

Could someone change the plugin for me so its a garage

**Comment by shidevil** [comment]
Which plugin are you using right now?

and the plugin call http-switch, which one are you referring?

**Comment by daniel2029** [comment]
i am using the homebridge-http-switch
