### ISSUE TITLE
Using multiple plugins

### ISSUE THREAD

**Issue by lessphiling** [nfarina/homebridge#1464]
I'm trying to use the Nest and Dyson plugins and I can't figure out how to combine the config files. 

Here is my current config:
`{
        "bridge": {
                "name": "Homebridge",
                "username": "CC:22:3D:E3:CE:30",
                "port": 51826,
                "pin": "031-45-154",
                "manufacturer": "@nfarina",
                "model": "Homebridge",
                "serialNumber": "0.4.20"
        },

        "platforms": [{
                "platform": "Nest",

                "token": "",

                "clientId": "",
                "clientSecret": "",
                "code": "DALHCTNG",

                "username": "username",
                "password": "password"
        }]
}
`

And I need to add
`"platforms": [
    // This is the config for this plugin  
    {
      "platform": "DysonPlatform",
      "name": "DysonPlatform",
      "accessories": [
        {
          "ip": "ip of your device",
          "displayName": "Name to be shown on Home App",
          "serialNumber": "DYSON-XXX-XX-XXXXXXXX-XXX",
          "password": "password of your device"
        },
        {
          "ip": "ip of your second device",
          "displayName": "Name to be shown on Home App",
          "serialNumber": "DYSON-XXX-XX-XXXXXXXX-XXX",
          "password": "password of your second device"
        }
        // If you have more than one device(s), just add the same config below
      ]
    }
    // End of the config
  ],`

**Comment by shidevil** [comment]
{ 
"bridge": { 
"name": "Homebridge", 
"username": "CC:22:3D:E3:CE:30",
 "port": 51826
, "pin": "031-45-154",
 "manufacturer": "@nfarina",
 "model": "Homebridge",
 "serialNumber": "0.4.20"
 },
    "platforms": [{
            "platform": "Nest",
            "token": "",
            "clientId": "",
            "clientSecret": "",
            "code": "DALHCTNG",
            "username": "username",
            "password": "password"
    },
      {
      "platform": "DysonPlatform",
      "name": "DysonPlatform",
      "accessories": [
        {
          "ip": "ip of your device",
          "displayName": "Name to be shown on Home App",
          "serialNumber": "DYSON-XXX-XX-XXXXXXXX-XXX",
          "password": "password of your device"
        }
      ]
    }
]
}

**Comment by toshibochan** [comment]
Copy and past you config here http://jsonlint.com!
There you can see what is missing
