### ISSUE TITLE
Siri and door look command is reverse

### ISSUE THREAD

**Issue by fennec622** [nfarina/homebridge#1466]
Hi since last update i can't open and closed my garage with siri
button is ok in Home app
Use plugin homebridge-edomoticz

With Siri command is reverse

With button when the garage is closed  command is
MQTT: Topic: domoticz/in, Message: {"command":"switchlight","idx":498,"switchcmd":"Off"} and it's ok garage open
but with siri when the garage is closed the command is
MQTT: Topic: domoticz/in, Message: {"command":"switchlight","idx":498,"switchcmd":"On"}

Thanks for help

**Comment by fennec622** [comment]
The bug is in homebridge 

i come back in version 0.4.22 and now 
button for door locked and siri command door locked is the same

**Comment by junior466** [comment]
Came here to report that Siri is no longer unlocking my doors and found this thread. 
Running latest beta of iOS 11.

**Comment by fennec622** [comment]
The bug is on hap-nodejs
You must downgrade hap-nodejs to version 0.4.27
And siri is ok to unlocked your doors

**Comment by fennec622** [comment]
The bug is on hap-nodejs
You must downgrade hap-nodejs to version 0.4.27
And siri is ok to unlocked your doors

**Comment by junior466** [comment]
Care to explain how I can achieve that on a raspberry pi?

Thank you for your help.

**Comment by fennec622** [comment]
on ubuntu 
sudo service homebridge stop
cd /usr/local/lib/node_modules/homebridge/node_modules
sudo rm -rf hap-nodejs
sudo wget https://github.com/KhaosT/HAP-NodeJS/archive/v0.4.27.zip
sudo unzip v0.4.27.zip -d /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs
sudo rm -rf v0.4.27.zip
cd hap-nodejs
sudo npm install
sudo service homebridge start

On rpi i don't know if the folder is the same but you can adjust

**Comment by junior466** [comment]
Thank you!

**Comment by junior466** [comment]
Just to update: This method didn’t work. I followed the instructions and sucessfully downgraded but still doesn’t lock or unlock.

**Comment by fennec622** [comment]
try to delete accessories and persist

**Comment by fennec622** [comment]
Fix in 0.4.33 hap-nodejs
