### ISSUE TITLE
Can't edit device.

### ISSUE THREAD

**Issue by baembaem** [nfarina/homebridge#1467]
Hello. :)
I've got a problem with the home app. Whenever I add a new accessory, it will be shown in home but I can't edit the name/room. The app just keeps telling me that I cant edit the device. Anyone knows what the problem can be?

Edit: I can edit some accessories. Like 1 out of 5

**Comment by SummerFrog** [comment]
Have you tried to `rm -rf persist` and `rm -rf persist-plugins` first, then restart your homebridge? This happened to me several times, and this method works for me.

**Comment by baembaem** [comment]
Restarting the iPad also solves the problem :)
