### ISSUE TITLE
Status of sensors by "homebridge-homematic" aren't updated anymore since 0.4.23

### ISSUE THREAD

**Issue by Sonsi79** [nfarina/homebridge#1468]
Since version **0.4.23** there is an error in communication betwen **homebridge-homematic** and **homebridge**.
I'm using a Homematic Door-Sensor "HM-Sec-SCo".

Since 0.4.23 the status of sensor isn't updated anymore for homebridge.
The CCU2 (Bridge for Homematic) shows every change of the sensor immediately, but it isn't updaten to homebridge anymore.
I have to close and restart HomeKit App to get the current Status of Sensor.

If have to use **homebridge@0.4.22** to get the updated status of my sensor automaticaly.

Is there any woraround to get the actualy homebridge works again with homematic?

**Comment by Sonsi79** [comment]
Same error by using other homematic devices which have to send back informations to the CUU2 :(

**Comment by CooperCGN** [comment]
I have the same problem with the homebridge-neato plugin which exposes the dock as a sensor.
