### ISSUE TITLE
Not an issue, but enquiry -  get information/interact with Apple TV 4?

### ISSUE THREAD

**Issue by psyciknz** [nfarina/homebridge#1470]
Homekit uses an Apple TV if there as it's hub.

Is there any interaction that homebridge is able to perform on the Apple tv?  Either to obtain information or make requests?

I'm after things like can we obtain a status, a media playback status from the apple tv regardless of the app doing the playback.

**Comment by NorthernMan54** [comment]
Have you seen this?

https://github.com/postlund/pyatv

**Comment by psyciknz** [comment]
Ahh, no, thanks.  Probably does what I want.  I'd actually like to get
what's playing and push it to trakt.tv regardless of what service it's
coming from.
