### ISSUE TITLE
IOS 11 will support NFC and Scan code

### ISSUE THREAD

**Issue by kevinkm** [nfarina/homebridge#1471]
So how about homebridge, do we build the two funtions insteand of the pin nums?

**Comment by KhaosT** [comment]
Any thoughts on how can we present the QR code to user?

**Comment by jonathanweinberg** [comment]
https://github.com/fumiyas/qrc/blob/master/README.md

**Comment by moritzmhmk** [comment]
is there any documentation on what information the QR code should contain?

**Comment by pdlove** [comment]
The QR Code seems to change depending on device's User ID (MAC Address) and device type. I assume the  PIN is in there as well. 
A bridge device called test35 with a User ID of A4:2F:A7:E0:02:CE and a PIN of 453-59-204 produces a QR code containing "X-HM://00247XRHGBZBQ".
I can't control the MAC and Pin closely enough to increment them and see what is happening in the HomeKit Accessory Simulator.

**Comment by dotsam** [comment]
I dug in to the HAPAccessoryKit.framework from the latest version of the accessory simulator, and it looks like these X-HM URI's are built from a set of flags, a category, version, some sort of reserved bit, and the PIN, along with something referred to as a setupID.

So either we'll need to dig in to exactly how this works more, or hope that apple releases a noncommercial HAP specifications R2 that includes how to generate these codes.

**Comment by KhaosT** [comment]
It's already in.
