### ISSUE TITLE
access home kit device through homebridge

### ISSUE THREAD

**Issue by tobyjcol** [nfarina/homebridge#1472]
Is it possible to automate a homekit supported device through homebridge? 

I want to use home bridge as an entry point to control home kit devices automatically that otherwise don't have an SDK / API?

**Comment by pdlove** [comment]
I have half written a plugin to connect HomeKit Accessories to Homebridge. I have since moved on to other projects with the expectation of shoring up other things about Homebridge before completing that plugin later in the year.

**Comment by NorthernMan54** [comment]
What about just using automation in Home?

**Comment by tobyjcol** [comment]
@northernman54 , can you elaborate?

**Comment by NorthernMan54** [comment]
I was referring to the automation function built into the home app.  Where you can setup automation of various events.  Lights on and off at various times etc

**Comment by Zootallure** [comment]
i am looking for the same functionality. let me explain why.
wanting tombuild a home automation system for multi-zone heating. 
using node-red i can create al sorts of complex tasks, requiring more then lights on/off.
the only issue i have is getting wifi controllable radiator valves. i already have 1 elgato eve valve, which ismhomekit enabled. i now would like to query/control that valve with node-red, via mqtt, homebridge to homekit....
