### ISSUE TITLE
Question about homebridge and plugins 

### ISSUE THREAD

**Issue by maragelis** [nfarina/homebridge#1474]
Which is more optimized, having 1 instance of homebridge running  with many plugins and devices, or many instances with one plugin and just a few devices running on each instance?

Thanks in advance

**Comment by pdlove** [comment]
I prefer having multiple instances with just a few plugins so that IOS has a smaller accessory file to parse. It also makes it so that if a plugin has an issue then it only causes issues for the specific accessories under that plugin.

**Comment by maragelis** [comment]
true didn't think of that, had many plugins crash on me.
