### ISSUE TITLE
No Response issue on iPhone/ipad Home App

### ISSUE THREAD

**Issue by robboz4** [nfarina/homebridge#1476]
I have had homebridge running for over  month controlling Hue, TV and Wemo lights without an issue. Siri was happily turning things on and off for me. Then I tried to add a new plug in (htthpgaragedoor) but homebridge wouldn't run properly even though the config.json file passed jsonlint program. So I restored my previously saved config.json file and now I get "no response" in the App to all the configured models. I have rebooted the Pi; removed all files in accessories and persist directories in the .homebridge directory. I have bumped up the user number in the config file, but nothing is fixing the issue this time. The homebridge device (Pi) is not even showing up if I try to add a new bridge.
So any advice on how to troubleshoot this issue? AS I said it was happily working and should be back to the same configuration. Although httpgaragedoor is installed as a plugin, but not configured. Could that be the case? If so how do I remove it? 

relevant info:
homebridge version
*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
0.4.25

...
[9/4/2017, 2:10:12 PM] Loaded plugin: homebridge-hue
[9/4/2017, 2:10:12 PM] Registering platform 'homebridge-hue.Hue'
[9/4/2017, 2:10:12 PM] ---
[9/4/2017, 2:10:14 PM] Loaded plugin: homebridge-platform-wemo
[9/4/2017, 2:10:14 PM] Registering platform 'homebridge-platform-wemo.BelkinWeMo'
[9/4/2017, 2:10:14 PM] ---
[9/4/2017, 2:10:14 PM] Loaded plugin: homebridge-samsungtv-control
[9/4/2017, 2:10:14 PM] Registering accessory 'homebridge-samsungtv.SamsungTV'
[9/4/2017, 2:10:14 PM] ---
[9/4/2017, 2:10:14 PM] Loaded config.json with 1 accessories and 2 platforms.
[9/4/2017, 2:10:14 PM] ---
[9/4/2017, 2:10:14 PM] Loading 2 platforms...
[9/4/2017, 2:10:14 PM] [WeMo Platform] Initializing BelkinWeMo platform...
[9/4/2017, 2:10:14 PM] [Hue] Initializing Hue platform...
[9/4/2017, 2:10:14 PM] [Hue] homebridge-hue v0.5.19, node v7.10.1, homebridge v0.4.25
[9/4/2017, 2:10:14 PM] Loading 1 accessories...
[9/4/2017, 2:10:14 PM] [TV Living room] Initializing SamsungTV accessory...
[9/4/2017, 2:10:15 PM] [WeMo Platform] Online: porch [6038E0448F50]
[9/4/2017, 2:10:19 PM] [Hue] Club-Robbo: BSB001 bridge v01038802, api v1.16.0
[9/4/2017, 2:10:20 PM] [Hue] Club-Robbo: 7 accessories
[9/4/2017, 2:10:20 PM] [Hue] Initializing platform accessory 'Club-Robbo'...
[9/4/2017, 2:10:20 PM] [Hue] Club-Robbo: 3 services
[9/4/2017, 2:10:20 PM] [Hue] Initializing platform accessory 'Hue Lamp 1'...
[9/4/2017, 2:10:20 PM] [Hue] Initializing platform accessory 'Hue Lamp 2'...
[9/4/2017, 2:10:20 PM] [Hue] Initializing platform accessory 'Hue Lamp 3'...
[9/4/2017, 2:10:20 PM] [Hue] Initializing platform accessory 'Daylight'...
[9/4/2017, 2:10:20 PM] [Hue] Initializing platform accessory 'Hue Tap 1'...
[9/4/2017, 2:10:20 PM] [Hue] Initializing platform accessory 'Go to sleep'...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[9/4/2017, 2:10:20 PM] Homebridge is running on port 51826.

Thanks

**Comment by shidevil** [comment]
Sudo npm -g uninstall <http garage door>

It should be call homebridge-httpgaragedoor?

**Comment by robboz4** [comment]
Thanks. It's gone but still no homebridge on the iPad....

**Comment by robboz4** [comment]
One other interesting note is that there is no further output from homebridge. It should be issuing a call every 30 seconds to the Hue bridge. So although it says it's started and which port to monitor, homebridge is not running. It's stuck somewhere. I don't think it's an iPad HomeKit issue.

**Comment by shidevil** [comment]
Please paste ur config.json thank you. 

try to delete the persisted cached and accessories directory again

**Comment by robboz4** [comment]
A,ready done that twice now, but no luck.

 "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:35",
        "port": 51826,
        "pin": "031-45-154"
    },
    

    "accessories": [
               {
                        "accessory": "SamsungTV",
                        "name": "TV Living room",
                        "ip_address": "192.168.1.98",
            "send_delay": 400
                }

     ],

    "platforms": [
       {
           "platform": "BelkinWeMo",
           "name": "WeMo Platform"
       },
  
    {
      "platform": "Hue",
      "name": "Hue",
      "users": {
        "001788FFFE099838": "6lDKzxatSH7SH-R82pRm0kZ2E4q-OlykO9wIzLFt"
      },
      "sensors": true,
      "excludeSensorTypes": ["CLIPPresence", "Geofence"],
      "lights": true,
      "philipsLights": true,
      "heartrate" : 30
    }

     
 ]
}

**Comment by shidevil** [comment]
@robboz4 when you mean no home kit on iPad. Have you added the homekit accessories to iPad home app? 

1) delete the existing home accessory on ipad

also ur config.json maybe wrong or u didn't include a colon at the start.

{
"bridge": {
"name": "Homebridge",
"username": "CC:22:3D:E3:CE:35",
"port": 51826,
"pin": "031-45-154"
},

"accessories": [
           {
                    "accessory": "SamsungTV",
                    "name": "TV Living room",
                    "ip_address": "192.168.1.98",
        "send_delay": 400
            }

 ],

"platforms": [
   {
       "platform": "BelkinWeMo",
       "name": "WeMo Platform"
   },

{
  "platform": "Hue",
  "name": "Hue",
  "users": {
    "001788FFFE099838": "6lDKzxatSH7SH-R82pRm0kZ2E4q-OlykO9wIzLFt"
  },
  "sensors": true,
  "excludeSensorTypes": ["CLIPPresence", "Geofence"],
  "lights": true,
  "philipsLights": true,
  "heartrate" : 30
}
]
}

**Comment by cerniuk** [comment]
My favorite JSON checker…

https://jsonlint.com

--
R/Wm.

**Comment by robboz4** [comment]
I have checked my config.json file against jsonlint many time and have no errors, no missing ":" . I have reverted back to my very first config file with just the wemo. I have purged accessories and persist directories. I have removed the bridge from the iPad. I restarted with the -D option. No device shows up on the iPad. I manually turned on the wemo and did get state changes in the homebridge output. So in conclusion the iPad is not seeing the homebridge. How do I check my network to see if homebridge is listening/transmitting on the port? Do I try an http results to the port number to see if I get a response? All this was working fine till I tried to add one more device. What breaks it and why is it so difficult to get it back? Last time I did a complete reinstall of everything...
Sorry to gripe I really like the program and it's abilities and thanks for the help so far.

**Comment by shidevil** [comment]
Change the username in ur config.json.

**Comment by robboz4** [comment]
That hasn't fixed it either this time. The two digits are now 40. Is there a range or do just increment?
The reason I'm stuck is that I have tried all the suggestions from previous posts and none seem to work this time. I might go back to a clean install again...

**Comment by robboz4** [comment]
Ok I'm at a complete loss. Reinstalled homebridge but it never shows up on the homekit app on my iPad or iPhone. I have Apple TV as the hub it is running 10.2.2. The only thing I changed was an entry to the config.json file for a new device. The config file passed jsonlint.  I guess I will try a new Pi  OS .install on SD.

**Comment by robboz4** [comment]
I did a clean install following the instructions and I am back to a working version. Hue, Samsung TV and Weemo all back under Siri control. I guess this is the only solution when it goes belly up. In review it looks like a plugin that has not  been updated to reflect new npm or node.js or homebridge code updates some how makes it unresponsive to Apple. Next step is to clone this working SD card and then start adding more  plugins.
