### ISSUE TITLE
couldn't add homebridge 

### ISSUE THREAD

**Issue by santoshb710** [nfarina/homebridge#1477]
Having issues while adding homebridge accessory in home app for first time configuration. I have deleted home,persist,accessories and changed the configuration file with the different name, username and pin. I am getting home couldn't connect to this accessory.

Node Version: V7
Homebridge-0.4.22
IOS:10.3.3

**Comment by shidevil** [comment]
@santoshb710 please paste ur config.json and the homebridge log? 

thank you.

**Comment by santoshb710** [comment]
Attached is the log and configuration file.

thanks 


[homebridge.txt](https://github.com/nfarina/homebridge/files/1276145/homebridge.txt)

[config.txt](https://github.com/nfarina/homebridge/files/1276147/config.txt)

**Comment by shidevil** [comment]
Try this.

{
	"bridge": {
		"name": "home",
		"username": "CC:22:3D:E3:CE:28",
		"port": 51826,
		"pin": "001-00-001"
	},

	"description": "This is an example cnfiguration file. You can use this as a template for creating your own configuration file.",

	"platforms": [{
			"platform": "FibaroHC2",
			"name": "FibaroHC2",
			"host": "192.168.2.34”,
			"username": "admin",
			"password": "ampasswordin",
			"pollerperiod": "2",
			"grouping": "room",
			"securitysystem": "disabled"

		}

	],

	"accessories": []
}

**Comment by maragelis** [comment]
Change you pin to something more secure apple does not allow easy passwords like that.

**Comment by maragelis** [comment]
I would change the pin some pins are not allowed if they are to easy

**Comment by santoshb710** [comment]
I have changed the configuration and updated with the new password. Still having the same issue. 
`  EventedHTTPServer [fe80::8f4:7ab0:51a8:470c] New connection from client +24s
  EventedHTTPServer [fe80::8f4:7ab0:51a8:470c] HTTP server listening on port 64794 +1ms
  EventedHTTPServer [fe80::8f4:7ab0:51a8:470c] HTTP request: /pair-setup +5ms
  HAPServer [CC:22:3D:E3:CE:28] HAP Request: POST /pair-setup +0ms
  HAPServer [CC:22:3D:E3:CE:28] Pair step 1/5 +1ms
  EventedHTTPServer [fe80::8f4:7ab0:51a8:470c] HTTP Response is finished +128ms
  EventedHTTPServer [::ffff:192.168.5.205] New connection from client +972ms
  EventedHTTPServer [::ffff:192.168.5.205] HTTP server listening on port 64797 +1ms
  EventedHTTPServer [::ffff:192.168.5.205] Client connection closed +1ms
  EventedHTTPServer [::ffff:192.168.5.205] HTTP connection was closed +0ms
  EventedHTTPServer [::ffff:192.168.5.205] HTTP server was closed +1ms
  EventedHTTPServer [fe80::8f4:7ab0:51a8:470c] HTTP request: /pair-setup +18s
  HAPServer [CC:22:3D:E3:CE:28] HAP Request: POST /pair-setup +0ms
  HAPServer [CC:22:3D:E3:CE:28] Pair step 2/5 +1ms
  HAPServer [CC:22:3D:E3:CE:28] Error while checking pincode: client did not use the same password +109ms
  EventedHTTPServer [fe80::8f4:7ab0:51a8:470c] HTTP Response is finished +1ms
  EventedHTTPServer [fe80::8f4:7ab0:51a8:470c] HTTP request: /pair-setup +13s
  HAPServer [CC:22:3D:E3:CE:28] HAP Request: POST /pair-setup +0ms
  HAPServer [CC:22:3D:E3:CE:28] Pair step 1/5 +0ms
  EventedHTTPServer [fe80::8f4:7ab0:51a8:470c] HTTP Response is finished +109ms
  EventedHTTPServer [fe80::8f4:7ab0:51a8:470c] HTTP request: /pair-setup +610ms
  HAPServer [CC:22:3D:E3:CE:28] HAP Request: POST /pair-setup +0ms
  HAPServer [CC:22:3D:E3:CE:28] Pair step 2/5 +1ms
  EventedHTTPServer [fe80::8f4:7ab0:51a8:470c] HTTP Response is finished +105ms
  EventedHTTPServer [fe80::8f4:7ab0:51a8:470c] HTTP request: /pair-setup +18ms
  HAPServer [CC:22:3D:E3:CE:28] HAP Request: POST /pair-setup +0ms
  HAPServer [CC:22:3D:E3:CE:28] Pair step 3/5 +1ms
  HAPServer [CC:22:3D:E3:CE:28] Pair step 4/5 +6ms
  HAPServer [CC:22:3D:E3:CE:28] Pair step 5/5 +1ms
  Accessory [home] Paired with client 4C21F004-72C8-4EC5-8509-DFBEADE3CFE0 +1ms
  EventedHTTPServer [fe80::8f4:7ab0:51a8:470c] HTTP Response is finished +3ms
  EventedHTTPServer [fe80::8f4:7ab0:51a8:470c] Client connection closed +11ms
  EventedHTTPServer [fe80::8f4:7ab0:51a8:470c] HTTP connection was closed +1ms
  EventedHTTPServer [fe80::8f4:7ab0:51a8:470c] HTTP server was closed +0ms
  EventedHTTPServer [::ffff:192.168.5.205] New connection from client +150ms
  EventedHTTPServer [::ffff:192.168.5.205] HTTP server listening on port 64818 +0ms
  EventedHTTPServer [::ffff:192.168.5.205] HTTP request: /pair-verify +2ms
  HAPServer [CC:22:3D:E3:CE:28] HAP Request: POST /pair-verify +0ms
  HAPServer [CC:22:3D:E3:CE:28] Pair verify step 1/2 +1ms
  EventedHTTPServer [::ffff:192.168.5.205] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:192.168.5.205] HTTP request: /pair-verify +178ms
  HAPServer [CC:22:3D:E3:CE:28] HAP Request: POST /pair-verify +0ms
  HAPServer [CC:22:3D:E3:CE:28] Pair verify step 2/2 +1ms
  HAPServer [CC:22:3D:E3:CE:28] Client 4C21F004-72C8-4EC5-8509-DFBEADE3CFE0 verification complete +2ms
  EventedHTTPServer [::ffff:192.168.5.205] HTTP Response is finished +0ms
  EventedHTTPServer [::ffff:192.168.5.205] HTTP request: /accessories +27ms
  HAPServer [CC:22:3D:E3:CE:28] HAP Request: GET /accessories +0ms
  EventedHTTPServer [::ffff:192.168.5.205] HTTP Response is finished +42ms
  EventedHTTPServer [::ffff:192.168.5.205] HTTP request: /pairings +841ms
  HAPServer [CC:22:3D:E3:CE:28] HAP Request: POST /pairings +1ms
  HAPServer [CC:22:3D:E3:CE:28] Removing pairing info for client +0ms
  Accessory [home] Unpairing with client 4C21F004-72C8-4EC5-8509-DFBEADE3CFE0 +0ms
  EventedHTTPServer [::ffff:192.168.5.205] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:192.168.5.205] Client connection closed +5ms
  EventedHTTPServer [::ffff:192.168.5.205] HTTP connection was closed +1ms
  EventedHTTPServer [::ffff:192.168.5.205] HTTP server was closed +0ms
^Z
[1]+  Stopped                 DEBUG=* homebridge -D`

**Comment by maragelis** [comment]
ok then, because i have been there many times, (last night) try this. 
1.) stop the instance
2.) delete persist and accessories folders
3.)change the port and username in the config file.
4.)start instance 

That worked for me .

**Comment by myloveruanqin** [comment]
npm ERR! Linux 4.4.21-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "--unsafe-perm" "homebridge"
npm ERR! node v7.10.1
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! mdns@2.3.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mdns@2.3.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mdns package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mdns
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mdns
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/.npm/_logs/2016-09-23T05_42_51_541Z-debug.log

**Comment by maragelis** [comment]
Try these

curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
sudo apt-get install -y nodejs
sudo apt-get install libavahi-compat-libdnssd-dev
sudo npm install -g --unsafe-perm homebridge

then run using
homebridge

**Comment by ktc312** [comment]
Have same issue here, couldn't add home bridge on my iPhone (iOS 10.3.3) and iPad (iOS 11.2.1).
Node Version: v4.8.7
Homebridge Version: 0.4.33

I have already tried different username, port and pin in my config.json

could not find homebridge.log or homebridge.err either

what should I do next?

thank you.
