### ISSUE TITLE
HomeBridge support for Hydrawise

### ISSUE THREAD

**Issue by hjhmedia** [nfarina/homebridge#1478]
Hi Everyone. I am as dumb as a box of hammers when it comes to coding. But would someone please make a HomeBridge plug-in for the Hydrawise Sprinkiler system. It is like a Rachio controlller. If you need my email and password to test and see if you can do it please email me at harrison@hjh-media.com thank you to anyone who can help. 

https://www.hydrawise.com/
https://app.hydrawise.com/config/login

**Comment by MtSamsonite** [comment]
I would also be interested if anyone can help.

I did find there is already an NPM package for the API located here: https://www.npmjs.com/package/hydrawise-api.  This might be useful as a starting point for development of a homebridge plugin.

Not being a developer though I'm not sure how to take the next step.

**Comment by martijndierckx** [comment]
I’ve spent last weekend developing a plugin. Have a look.
https://www.npmjs.com/package/homebridge-hydrawise

**Comment by storkpkp** [comment]
Hello, I was able to install and see my zones, but they won't activate. They just spin idle and then time out.
