### ISSUE TITLE
Accessory UUID not unique

### ISSUE THREAD

**Issue by desvdp** [nfarina/homebridge#148]
A little context: I building a shim for an existing home-automation system (NikoBus), where all the lights in a house are enumerated in a platform (just like in the HUE platform). Problem is I'd like to have some of the lights to have the same name (i.e. "Desk" can exists in multiple rooms or zones). 
It seems I can't do this: because the UUID would not be unique, I believe I traced it back to the following call in  app.js/createAccessory:
 >  var accessoryUUID = uuid.generate(accessoryInstance.constructor.name + ":" + displayName);

since only displayName is used my accessory is not unique, wouldn't it make sense to base the UUID on a combination including the serial number / address  / ... based on their existence ... ?

**Comment by nfarina** [comment]
Yeah this isn't the best solution I agree. We can make it so that platforms can return accessories with a new property defined for this purpose; would that work? In addition to defining `name` for the accessories you return from the `accessories` call, you could define `uuid` or a similar property?

**Comment by desvdp** [comment]
How about this: you currently use the name property form the constructor, what if we assume the existence of a SerialNumber property in that same constructor and if it does add it to the UUID calculation.

If the serial number is defined, we can use it in the information service as well : Characteristic.SerialNumber. If it isn't defined the device might have no serial number (can happen), still the designer of the platform may decide to generate one (probably good anyhow). 

just my two cents.
