### ISSUE TITLE
Z-wave + smartthings + homebridge + ATV4. Most devices work remotely but 2 do not.

### ISSUE THREAD

**Issue by popepay** [nfarina/homebridge#1483]
Hello,

I have a very weird issue yet very repetitive.

I have 5 Leviton light switches DZ6HD and 1 garage opener Iris GD-00Z-1. All are Zwave devices.
1 Apple TV 4 as hub

- 4 Light switches work seamlessly (on home wifi, on cellular data, etc.)
- 1 Light switch & garage opener work great on home wifi. Never had an issue.
However, these 2 do not work outside of that scope (cellular data). All are connected to the same "home" via smartthings + homebridge + apple TV 4. 
- The 2 problematic devices however work great on smartthings. Both on home wifi and remotely. No issues. The notifications (garage door opened/closed) still make it to the iphone.

I have rebooted everything, the problem keeps coming back. It is always the same 2 devices. Any idea?

I know it sounds very odd, but I have had that problem for 2month now, and no amount of reboots are solving it. I would appreciate any help, and would be happy to help troubleshooting it further.

Using versions:

homebridge@0.4.27
homebridge-nest@1.1.2
homebridge-smartthings@0.5.1
latest ATV4 tsOS
latest iOS

**Comment by andrewjones141** [comment]
i have a similar issue where my native homekit devices (elgato eve) work remotely, but the homebridge devices do not. recently upgraded to latest homebridge version, and running mix of ios10 / 11 beta devices.

**Comment by uronito** [comment]
i have the same problem with door contact switch in homebridge.

in wifi context works correctly, but over atv4 remotely, this coor contact switch don't receive updates.

Thanks

**Comment by cariacou** [comment]
Same issue here. 
Some of my homebridge devices don't work remotely while the other ones do
