### ISSUE TITLE
Remove an accessory from config.json is not enough under OSX

### ISSUE THREAD

**Issue by ooii** [nfarina/homebridge#1484]
I have a configuration file that works very well under ubuntu. I wanted to use it on OSX because I have more power to use `ffmpeg`. First, I could not get the HS100 plugin to work. So I removed it from the configuration file. But every time I started `homebridge`, it was still crashing because of the HS100 plugin. I had to delete the module from `/usr/local/lib/node_modules/homebridge-hs100` so I could run it.
Under ubuntu, when I don't need a plugin anymore, removing it from the `config.json` is enough. Is there a different behavior under OSX?
Thank you.

**Comment by igreulich** [comment]
Make sure you have taken the accessory out of your `config.json`.

Then, in your homebridge directory, for me its `~/.homebridge`, delete the `/accessories` directory. Then run `homebridge` again.
