### ISSUE TITLE
HomeKit in parallel with Plex server 

### ISSUE THREAD

**Issue by macguru341** [nfarina/homebridge#1485]
Hello
First thanks for watching my post.
I’m going to install a Plex server on my new RP 3 today as my main requirement from this great board.
I would like to know if it’s possible to install after I’ve installed the Plex server use it also as an HomeKit server , or I need a separate RP

**Comment by NorthernMan54** [comment]
I haven't tried out that combination, but I can't see why it shouldn't work.  I run mine with kodi on the same rpi and don't have any issues.

A concern would be network ports, and possible collisions between them.  This would be something to watch out for.

**Comment by rjmcfadd** [comment]
Yes, it works fine. I've been running both for over a year with no problems.

**Comment by maragelis** [comment]
I have been running both no problem

**Comment by alon112** [comment]
Hello,
how can i run it in parallel? 
i mean i installed PLEX media player (HTPC), so no OS interface like windows.
how i install homebridge on it also and configure it from another PC?
thanks
