### ISSUE TITLE
How to combine accessory's json   

### ISSUE THREAD

**Issue by nikki-reprap** [nfarina/homebridge#1492]
I have been trying to combine these two json files without much luck i have checked them with jsonlint but i am not sure where the error is.

```
{

"bridge": {
    "name": "Homebridge",
    "username": "CC:22:3D:E3:CE:30",
    "port": 51826,
    "pin": "031-45-154"
},

"description": "This is an example configuration file. You can use this as a template for creating your own configuration file.",

"platforms": [],
  "accessories": [
    {
		"accessory": "mqtt-switch-tasmota",
		"switchType": "outlet",
	
		"name": "NAME OF THIS ACCESSORY",
	
		"url": "mqtt://MQTT–BROKER-ADDRESS",
		"username": "MQTT USER NAME",
		"password": "MQTT PASSWORD",
	
		"topics": {
			"statusGet": "stat/sonoff/RESULT",
			"statusSet": "cmnd/sonoff/POWER",
			"stateGet": "tele/sonoff/STATE"
		},
		"onValue": "ON",
		"offValue": "OFF",
	
		"activityTopic": "tele/sonoff/LWT",
        "activityParameter": "Online",
    
		"startCmd": "cmnd/sonoff/TelePeriod",
		"startParameter": "60",
		
		"manufacturer": "ITEAD",
		"model": "Sonoff",
		"serialNumberMAC": "MAC OR SERIAL NUMBER OR EMPTY"
	}
]
}
```

`
  ```
  "bridge": {
        "name": "Bart",
        "username": "CC:22:3D:E3:CD:39",
        "port": 51826,
        "pin": "031-45-154"
    },

    "description": "HomeBridge",

"platforms": [
    { "platform":	"mcuiot",
    "name":     "MCUIOT" }
     ],

"accessories": [ ]

}`
```

**Comment by nikki-reprap** [comment]
This I what i have so far :

`{
    "bridge": {
    "name": "Homebridge",
    "username": "CC:22:3D:E3:CE:30",
    "port": 51826,
    "pin": "031-45-154"
    },
    "description": "JSON API",
    "platforms": [
        {
            "platform": "mcuiot",
            "name": "mcuiot",
            
        }
    ],
    "accessories": [
        {
            "accessory": "mqtt-switch-tasmota",
		"switchType": "outlet",
	
		"name": "NAME OF THIS ACCESSORY",
	
		"url": "mqtt://MQTT–BROKER-ADDRESS",
		"username": "MQTT USER NAME",
		"password": "MQTT PASSWORD",
	
		"topics": {
			"statusGet": "stat/sonoff/RESULT",
			"statusSet": "cmnd/sonoff/POWER",
			"stateGet": "tele/sonoff/STATE"
		},
		"onValue": "ON",
		"offValue": "OFF",
	
		"activityTopic": "tele/sonoff/LWT",
        "activityParameter": "Online",
    
		"startCmd": "cmnd/sonoff/TelePeriod",
		"startParameter": "60",
		
		"manufacturer": "ITEAD",
		"model": "Sonoff",
		"serialNumberMAC": "MAC OR SERIAL NUMBER OR EMPTY"
        },
        {
            "platforms": [
    { "platform":	"mcuiot",
    "name":     "MCUIOT" }
     ],

"accessories": [ ]
            
        }
    ]
}`

**Comment by acenqiu** [comment]
try this.

```json
{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},
	"description": "This is an example configuration file. You can use this as a template for creating your own configuration file.",
	"platforms": [{
		"platform": "mcuiot",
		"name": "MCUIOT"
	}],
	"accessories": [{
		"accessory": "mqtt-switch-tasmota",
		"switchType": "outlet",
		"name": "NAME OF THIS ACCESSORY",
		"url": "mqtt://MQTT–BROKER-ADDRESS",
		"username": "MQTT USER NAME",
		"password": "MQTT PASSWORD",
		"topics": {
			"statusGet": "stat/sonoff/RESULT",
			"statusSet": "cmnd/sonoff/POWER",
			"stateGet": "tele/sonoff/STATE"
		},
		"onValue": "ON",
		"offValue": "OFF",
		"activityTopic": "tele/sonoff/LWT",
		"activityParameter": "Online",
		"startCmd": "cmnd/sonoff/TelePeriod",
		"startParameter": "60",
		"manufacturer": "ITEAD",
		"model": "Sonoff",
		"serialNumberMAC": "MAC OR SERIAL NUMBER OR EMPTY"
	}]
}
```

**Comment by nikki-reprap** [comment]
It works perfectly thank you !
