### ISSUE TITLE
Strange CO2 sensor accessory behavior.

### ISSUE THREAD

**Issue by theopoon** [nfarina/homebridge#1495]
I am new to the dev, so please excuse if my code is bad.
I have spend 2 days on the topic, puzzles me...
Currently I made a plugin for accessory by reading from fs, simple code,

`var Service, Characteristic;
var fs = require('fs');

module.exports = function(homebridge) {
	Service = homebridge.hap.Service;
	Characteristic = homebridge.hap.Characteristic;
	homebridge.registerAccessory("homebridge-dummy-file", "dummy-file", theDummy);
}

function theDummy(log, config) {
	this.log = log;
	this.name = config["name"];
	this.path = config['path'];
	this.type = config['type'];
	var that = this;
	var interval = setInterval(function() {
		fs.readFile(that.path, 'utf8', function(err, data) {
			if (err) {
				return 0;
			}
			that.value = 0;
			if (that.service) {
				that.value = parseFloat(data);
				that.service.getCharacteristic(Characteristic.CarbonDioxideDetected).updateValue(that.value);
			}
		});
	},this.refresh);
}

theDummy.prototype = {
	Identify: function (callback) {
		callback(); // success
	},
	getState: function(callback){	//is it really called?
		that = this;
		this.log('[DBG]: getState fired, is it really being called?');
	},
	getServices: function(){
		that = this;
		this.service = new Service.CarbonDioxideSensor(this.name);
		this.service
			.getCharacteristic(Characteristic.CarbonDioxideDetected)
			.on('get', function(callback) {callback(null, that.value)});
		return [this.service];
	}
}`

config.json
`
{
                "accessory": "dummy-file",
                "name":"CO2 Level",
                "type":"carbondioxidesensor",
                "path":"/mnt/ramdrv/data/sensors/co2/value.txt"
}
`

and I set 0 to the value.txt

It works ok when I am in the Home App, value get pushed and set correctly, but every time when I quit the Home app on iOS and relaunch it, I get notification on "Carbon dioxide abnormal in Default Room.". (yes I have notification set to On on the iOS Home App), looks like it was sets off, and 1s later (possibility the set interval it gets back to correct value)

Can anyone please give me a help?

Thanks in advance.

**Comment by theopoon** [comment]
Just notice this happens when I have multiple accessories with the plugin....

**Comment by theopoon** [comment]
It is my bad programming, nothing strange there. 
3rd day and many cups of coffee helped, my apology.
case close.

**Comment by alexuaua** [comment]
> It is my bad programming, nothing strange there.
> 3rd day and many cups of coffee helped, my apology.
> case close.

@theopoon I see that your question was more than year ago, but if you still have the code you asked about, could you please share fixed version? I'm playing with your code above to read values from airsensor app (for generic CO2 sensor like Volcraft).

**Comment by theopoon** [comment]
@alexuaua Sorry I moved on and the code were merged to a multiple-service-type plugin.

looking in the new code, it was almost the same, just improved the flows, added support to different sensor services...

In getState, I added callback the value
getState: function(callback){
                callback(null,this.value);                //return value from fs read here.....
}

Changed to use bind on service:
this.service = new Service.CarbonDioxideSensor(this.name);
this.service.getCharacteristic(Characteristic.CarbonDioxideDetected).on('get', this.getState.bind(this));
