### ISSUE TITLE
Lock -> activate Pin XX -> deactivate after 3 sec.

### ISSUE THREAD

**Issue by StefanMeGit** [nfarina/homebridge#1496]
I search for an lock a-plugin, that just swtich on an relais who is connected to an pin on the PI. Does someone know a solution?

**Comment by maragelis** [comment]
use node-red and  homebridge-mqtt plugin, node-red gives you the ability to trigger gpio on raspberry very easy. if you are running raspberry pi just type node-red-start then go http://Your_ip-address:1880
