### ISSUE TITLE
Homebridge does not work anymore after update of node 8.5.0

### ISSUE THREAD

**Issue by Nastras** [nfarina/homebridge#1497]
Hello, after the update on node 8.5.0 I get the following error message:

Sep 16 05:01:27 Homebridge homebridge [768]: / usr / local / bin / node [768]: ../src/cares_wrap.cc:194
4: void node :: cares_wrap :: {anonymous} :: GetAddrInfo (const v8 :: FunctionCallbackInfo <v8 :: Value> &):
 Assertion `args [4] -> IsBoolean () 'failed.
Sep 16 05:01:27 Homebridge systemd [1]: homebridge.service: main process exited, code = killed, s
tatus = 6 / ABRT
Sep 16 05:01:27 Homebridge systemd [1]: Unit homebridge.service entered failed state.
Sep 16 05:01:37 Homebridge systemd [1]: homebridge.service holdoff time
 over, scheduling restart.
Sep 16 05:01:37 Homebridge systemd [1]: Stopping Node.js HomeKit Server
...
Sep 16 05:01:37 HomeBridge systemd [1]: Starting Node.js HomeKit Server
...
Sep 16 05:01:37 Homebridge systemd [1]: Started Node.js HomeKit Server.
^ Cpi @ Homebridge: ~ $

If I go back to 8.4.0 it works again, has one an idea why?

I installed Homebridge 0.4.28, npm 5.4.2

**Comment by maragelis** [comment]
what i know about homebridge it only works with nodejs 7

**Comment by pdlove** [comment]
My Homebridge dev machine is node 8.2. I’ll update it to 8.5 and see if I can reproduce your error.
