### ISSUE TITLE
Not working with IOS11

### ISSUE THREAD

**Issue by theo-69** [nfarina/homebridge#1501]
I just updated to IOS 11 and homebridge stopped working.
So I reinstalled with sudo npm install -g --unsafe-perm homebridge, still nothing, homebridge is starting but all Items are not responding and showing with !

**Comment by sendorm** [comment]
I have an iphone on ios 10.2. Homebridge is still working. Also have an ipad pro on ios 11, homebridge is not working on the ipad.

**Comment by theo-69** [comment]
@sendorm same here old iPhone with 10.3 still working

**Comment by dkrizic** [comment]
I have running iOS 11 on all devices and everything working, but... I have homebridge 0.4.25. And I have no problems, either directly nor via Apple TV (also running iOS 11)

**Comment by theo-69** [comment]
just updated homebridge to 0.4.28, still nothing

**Comment by theo-69** [comment]
using the old Version from backup again and surprise after restarting the PI its working again

**Comment by reallybman** [comment]
Same issue. Working on legacy devices but not IOS 11 devices.

**Comment by B1tMaster** [comment]
Upgaded just now both my ipad and iphone to IOS11. My Apple TV is still NOT upgraded to latest TvOS.
Everything works like a charm.  I am running latest version of homebridge. Did not have to change a thing.

**Comment by VeniceNerd** [comment]
I am having the same issue. Updated both my iPad Pro and iPhone 7 Plus to iOS 11 today and Home shows all devices connected through Homebridge with "No Response" and the "!". Updating both my Apple TV's to iOS 11 made no difference either.

**Comment by martinorob** [comment]
Sale issue here.. all devices updates (iPhone iPad appletv) and homebridge not working

**Comment by martinorob** [comment]
Solved:
Deleghe homebridge from home app
Kill homebridge
Remote cachedaccessories
Change Mac address of homebridge with new one 
Remote temp folder
Start homebridge 
Readd homebridge to home app on iOS 11

**Comment by matevzg** [comment]
What I see is homebridge being recognized as a thermostat and not a bridge in iOS 11. It still has all accessories attached to it in Home.app though, but it's status is No Response.

In Matthias Hochgatterer's Home app, homebridge is also recognized as thermostat with Error status.

In any way, after a few minutes of running, homebridge, all accessories become unresponsive. Restarting homebridge helps. All devices running iOS/tvOS 11.

Strange.

**Comment by DoctorOgg** [comment]
tried the procedure that @martinorob has shared, and still nothing...

**Comment by snakedog116** [comment]
I'm having issues with ios11 as well and wanted to add some info for troubleshooting.
1. I have upgraded my appleTV gen4  and my iPhone 7 to the newest versions that just came out. My iPhone can no longer use any of the home bridge devices. My iPad is also on iOS 11 and has 'no response' from any of the devices.

However, my wife's iphone 6s is still on iOS 10 and that phone works fine.
---

Thanks @martinorob, just a couple of things to clarify about your steps.

Step 1: When you say delete homebridge from the home app are you talking about the apple home app? or deleting the smart app from smarthings?

Step 3: 'remote' cashedaccessories do you mean 'remove'? Where do we remove them from?

If I follow your steps will it remove all devices from my phone?

**Comment by drgonz0** [comment]
I've been running IOS 11 on an iPhone 6S for a couple weeks, and have had HomeBridge working.  I have been getting odd disconnects where I need to reboot my Rasp Pi, even though actions are updating in home kit.  However this pre-ceded my IOS11 upgrade. Just updated HomeBridge to latest version, and I can report it's still working.

**Comment by VeniceNerd** [comment]
Seems like martinorob is suggesting to delete the configuration and set up as new again. I’ve read somewhere else that this could help. However, I have over 40 devices connected to my Homebridge and it’s a major effort to add them all back in and re configure all scenes. 

Is there really no other solution?

**Comment by NorthernMan54** [comment]
I’m just updated to IOS 11 and had zero issues.  I was already running the latest version homebridge, and it just worked with no restarts or other issues.

Also, I had made the update while being remote to my house.

**Comment by krfr** [comment]
I updated to IOS11 this morning (07.00 Swedish time zone) Then everything worked. Now in the evening it stopped working (20.00 Swedish time zone)

**Comment by martinorob** [comment]
Which version of hb and node?

**Comment by mifi** [comment]
What I did which worked for me was:
* Upgrade homebridge to newest version: `npm install -g homebridge`
* Stop `homebridge` service
* `rm -rf ~/.homebridge/persist`
* `rm -rf ~/.homebridge/accessories`
* Under `~/.homebridge/config.json`, change your `"username": "11:22:33:44:55:66"` to something else
* Start `homebridge` service
* Delete homebridge accessory from home app
* Add homebridge accessory to home app and enter pin etc

Note that as others pointed out, you will lose all configurations and scenes etc

**Comment by davemee** [comment]
Change your username in `config.json` by a single value, as suggested in #1491 - this worked for me.

**Comment by arnif** [comment]
At first it didn't work for me to only change the username. I reverted the change and restarted homebridge service and all is working now :) thx for the tips !

**Comment by snakedog116** [comment]
I changed the username, and completed removed and reinstalled homebridge. it's working now.

**Comment by DoctorOgg** [comment]
i did also try changing the username with no success..

**Comment by coryking** [comment]
Made sure all devices are updated (appletv, ios, etc...).  Removed homebridge from homekit, changed the username, re-added the homebridge accessory and everything is working.

It did nuke all my room assignments and stuff though :-(

**Comment by Ant1q** [comment]
Last night homebridge stop working with "no response", im still on ios 10.1 and wife on ios10.3

**Comment by matevzg** [comment]
There might be two issues at hand here. Certainly iOS 11 has some issues (most probably in specific configurations, not all) with sharing the hub to the outside world. Also, during the upgrade somehow homebridge is not recognized correctly.

In my situation the homebridge No Response problem got solved by signing out, rebooting and signing back into iCloud on Apple TV 4.

Sporadic connectivity issues when I'm not at home remain, however.

**Comment by sendorm** [comment]
After quite a fiddling (reseting user name, restarting homebridge, deleting persists and temp folder) the solution I found was to delete everything and setup a new accessory from a ios 11 device. Which was the thing I was trying to avoid, but it was the only solution.

**Comment by lastowl** [comment]
Incase its useful to someone, I was stuck on the no response issue, in the end I had to turn off my apple tv, then restart the home bridge server waiting for everything to connect in the home app then turn the apple tv back on and all is working

**Comment by DoctorOgg** [comment]
did that as well, and still no joy :(

**Comment by stich86** [comment]
my current setup has only ATV4 on iOS11 (damn automatically update...). I've restarted ATV4 and then Homebridge and everything works like before. I will wait an update of iOS11 (still to bugged) from my iPhone

**Comment by Tiger519** [comment]
I ended up both signing out of and back in to iCloud, and also deleting/re-adding Homebridge after changing the username. Seems to have fixed it. Not sure if one or both did the trick. It worked on wifi which made me thing it was an Apple tvOS11 thing, but native HomeKit devices worked remote, which made me think it was a HomeBridge thing... It's been stable for 24+ hours now (and had been stable just about since I got it up and running), so hopefully these two steps were enough!

Note that if you sign out of iCloud, it's possible the HomeKit option won't show up for a while. I had restarted a few times and still nothing. Eventually it came back (and connected) without me doing anything. Seems it may take some time to sync up.

**Comment by robboz4** [comment]
I think this might be the simple recipe for updating to IOS 11 and homebridge on Raspberry Pi.
1) upgrade iPhone to iOS 11.
2) check it all still works: iPhone on 11; iPad on 10.xx; AppleTv 10.xx
3) upgrade iPad to 11.
4) check it all still works. iPhone & iPad on 11; AppleTv 10.xx
5) Stop homebridge on Raspberry Pi.
6) Upgrade AppleTv to 11.
7) check AppleTv is working ok.
8) restart homebridge on the Raspberry Pi.
9) check all is working! Success!!

This worked for me without any hiccups.

**Comment by Tiger519** [comment]
@robboz4 I really should turn off automatic updating on the ATV. For me it was "Apple TV automatically updates to tvOS11 while everything else is iOS10 and everything breaks" :-). Glad to hear you had good success with this. I've been dreading upgrading my iPhone to iOS11 but I'm getting a new one in a few months anyway so it's going to have to happen. I think if the hub is working though, the phone should be ok.

**Comment by robboz4** [comment]
Actually my Appletv is set to auto update and it didn’t. So perhaps I was saved any problems by that and changing only one thing  at a time. That’s an old troubleshooting technique I learned a long time ago: change one variable at a time and check what happens...

**Comment by Addiw** [comment]
IOS 11 says that my devices of type blind are not supported. Worked on IOS 10 without problems.

**Comment by B1tMaster** [comment]
Problem solved: https://github.com/B1tMaster/haas-config/issues/54
This is the best way to solve it as it is pretty much guaranteed to work, since you would be installing the homebridge plugin via Docker and your environment, libraries , settings etc will be same regardless of what OS you run.

**Comment by HSkul** [comment]
I installed Homebridge via Docker on my Raspberry Pi running Stretch Lite and when I ran Homebridge according to the instructions it didn’t have access to the GPIO pins. So not the ultimate solution for everyone.

**Comment by B1tMaster** [comment]
@HSkul , what do you mean you did not have access to GPIO pins?  
If you mean the PIN code you need to enter for homebridge , you can see it in the log of HomeBridge inside the plugin. There is a button to click for logs at the bottom and you can see the PIN.  

You can also see it in the config.json file.. I also installed the "SAMBA" plugin and it mounts the directory with all configs to your laptop as a windows drive.  you can edit all the files just as before with an editor.

**Comment by HSkul** [comment]
Yes it is probably different for Haas.io but following the instructions for installing Homebridge through Docker for some reason leaves the Pi user without access to the GPIO pins (I dont remember the virtual path). No I’m not talking about the PIN code that I set for setting Homebridge up in the Home app.  
  Does Haas.io come without desktop environment?  Don’t need that on an appliance.

**Comment by B1tMaster** [comment]
@HSkul , but with haas.io you don't install anything thru docker.. Even though it is using it as a underneath. It is all pre-configured and packaged as a web-based plugin install. just click and go..

There is NO desktop environment. you still can go everything via command line (SSH) or (SAMBA).
Or you can use WebBased GUI (same as a regular HA has). But it has some awesome additional menus under "haas.io" that allow you to manage your host /supervisor right from the web based gui.

And you can install Homebridge plugin right from the GUI and it works right out of the box. 
(you still have direct access to config.json and other config files for the software. 

I highly recommend going this route. Once you gone thru the pain of migrating.. All things going forward will be easy.   Cheers mate and good luck. I am done with this issue and moving on to new things to develop for my house..

**Comment by HSkul** [comment]
Alright, let me take it for spin and see if it works for my setup.  I'll post the results in couple of hours.

**Comment by LeoCal** [comment]
Folks, in the end I managed to get everything working again. No need to run homebridge in Docker or to install Hass.io. What you need to do is a cleanup of your PI.
I basically removed all the packages (nodejs, npm, node-server, nodered, hap-nodejs, homebridge) and installed everything from scratch following the installing procedures at:
- https://github.com/KhaosT/HAP-NodeJS
- https://github.com/nfarina/homebridge
Special thanks to the support from @KhaosT and @nfarina while I was trying to troubleshoot their code (in the end their code was just fine :-)).

**Comment by J7mbo** [comment]
Following @mifi's instructions above, changing the name *did not work* for me, but following all of his steps showed Homebridge again once restarting in the Home app.

**Comment by michbeck100** [comment]
I've had this problem in my competitive homekit plugin [pimatic-hap](https://github.com/michbeck100/pimatic-hap). This was (hopefully) fixed with https://github.com/michbeck100/pimatic-hap/commit/636e45e5a0e9d563c3857cfecfb1b7828680a13b
The problem was that with https://github.com/KhaosT/HAP-NodeJS/commit/445b3408484315be9b5573e552b1b2a899fcda2b setting Service.BridgingState was removed from hap-nodejs (as of version 0.4.26).

**Comment by Walek001** [comment]
iPad say the accessory is not ready.
I follow all of the steps here. 
The home bridge is running on macOS to try it out ;). Any reasons why it could happened?

**Comment by michbeck100** [comment]
See my last comment. This is the reason. Someone would have to update the homebridge code.

**Comment by Walek001** [comment]
@michbeck100 
I fixed that with: 
    `    "bridge": { 
    "name": "Homebridge", 
  "username": "CC:22:3D:E3:CE:30", 
"port": 51826, 
"pin": "031-45-154", 
"manufacturer": "@nfarina", 
"model": "Homebridge", 
"serialNumber": "0.4.20" 
},`

**Comment by DiMarcello77** [comment]
Hello All, I had this same issue and I solved it today. homebridge was found but all accesoires where 'Not Responding' 

I thought it was because of an IOS 11 update first but after completely removing / reinstalling my PI3 with homebridge the issue was still there. I googled a lot and in my case my router (Netgear Orbi) had this multicast feature set to **disabled**: 

_Disable IGMP Proxying. IGMP proxying allows a computer on the local area network (LAN) to receive the multicast traffic it is interested in from the Internet._

After enabling this multicast feature and rebooting the router it was completely running fine again!

It's unknown to me why this setting was disabled but now it is working like a charm again :-) 

Keep up the good work nfarina! I love homebridge!

**Comment by Maxime-Drivet** [comment]
@Walek001 Thank you, that works perfectly !

**Comment by Ugmaxie** [comment]
That’s actual for now. And one of reasons which can cause such kind of issue is ‘homebridge-broadlink-rm’ (of course if you use this plugin) and keys about default cool and heat temperatures. If remove them from config - homebridge becomes stable.  Strange situation at all.

**Comment by fredericpfisterer** [comment]
Adding my 2 cents here since I tried everything and what fix it was to simply restart my router :-)

**Comment by tleo86** [comment]
hello all!
i have a problem with homebridge and sonoff basic relay.
i see that reley in my homekit but when i try to say:
Hello Siri turn on light.
Siri says: the light doesn't responce.
But if i change state relay in eWelink app homekit changing state. 
have somebody same problem?
