### ISSUE TITLE
Unable to update JSON Complete API from app (Error saving)

### ISSUE THREAD

**Issue by vaficionado** [nfarina/homebridge#1502]
Just as the title says - get an error saving the JSON Complete API in the SmartThings app (exact error message in the app reads "There was a problem processing your request. Please try again."

In the SmartApp live logging I see the following:

java.util.concurrent.TimeoutException: Execution time exceeded 20 app execution seconds: 30832761404324 @ line 313

Net result of this is that when trying to add the Homebridge device to HomeKit, at least one device comes up as "Not Supported" due to an inability to discover the services. Log from Homebridge itself reads as follows when it hits the item that failed to update

Sep 19 20:49:18 retropie homebridge[17834]: [9/19/2017, 8:49:18 PM] [SmartThings] Unknown Capabilities: ["Health Check","Light","Relay Switch","Media Controller","Image Capture","Button","Valve"]

Screenshots attached below:

![img_2900](https://user-images.githubusercontent.com/25127543/30626530-59ba9abe-9d7f-11e7-936a-5f614d3d6096.PNG)

<img width="1145" alt="screen shot 2017-09-19 at 9 09 31 pm" src="https://user-images.githubusercontent.com/25127543/30626533-60d40ba0-9d7f-11e7-8849-e64b7fc06dfd.png">

**Comment by vaficionado** [comment]
Forgot to mention that the smartapp is version 0.5.5 (which should be the newest) and that Homebridge is 0.4.16 (I know that’s a touch out of date but am not sure how to update it - npm doesn’t seem to see it installed)

**Comment by vaficionado** [comment]
I did update Homebridge just now (as well as the homebridge-smartthings plugin) both to the latest version via npm... same issue (not that I had any expectation that the local nodejs code would have an impact on the SmartApp API timeout in the first place)

**Comment by jacobwtyler** [comment]
Same issue here now

**Comment by jacobwtyler** [comment]
Were you able to find any solution?

**Comment by vaficionado** [comment]
Nope, never did - there is another thread about this over on the SmartThings forum (https://community.smartthings.com/t/hello-home-homekit-and-siri-control-via-homebridge/16701) that has had some updates posted, but no - I still see the issue. The last time I did an update it managed to go catch all my devices, so I'm considering that lucky and leaving it alone for now. But the timeouts definitely still exist.
