### ISSUE TITLE
Error Node.js recompile?

### ISSUE THREAD

**Issue by joq3** [nfarina/homebridge#1505]
Hi,

I have been running Homebridge for a while without much trouble.
Was about to install a plugin, but it requires Node.js version over 7.6.0.
And I read about it, that uninstalling homebridge and plugins would be the best way to go.

So I saved the config and uninstalled homebridge, npm, nodejs, node-gyp.
And then installed everything again:
This is the version I am left with now:
node -v v8.5.0
npm -v 3.10.10 (which is weird because I told it to install the latest which is 5.4.2, I cannot get it to update over this version?)

And Homebridge 0.4.28.

This is the result when running it and checking the logs:
`Error: The module '/usr/lib/node_modules/homebridge/node_modules/mdns/build/Release/dns_sd_bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (module.js:653:18)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/mdns/lib/dns_sd.js:24:20)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
`

I have tried npm rebuild, no difference.
npm install gives me this result:
`npm WARN saveError ENOENT: no such file or directory, open '/root/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/root/package.json'
npm WARN root No description
npm WARN root No repository field.
npm WARN root No README data
npm WARN root No license field.
`

What can I try next?

By the way I had to install homebridge with --unsafe-perm, otherwise I got this error:
`gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/8.5.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/homebridge/node_modules/curve25519-n2/.node-gyp"
`

**Comment by roe1974** [comment]
i think the problem is due to node 8.5.0 (allready postet here)
try 8.4.0 (i use this version)
Richard

**Comment by joq3** [comment]
@roe1974 I tried uninstalling nodejs and do this:
`
root@NAS:~# npm install nodejs@8.4.0 -g
npm ERR! code ETARGET
npm ERR! notarget No matching version found for nodejs@8.4.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-09-22T17_27_52_549Z-debug.log
`

But as you see I got another error when trying to install 8.4.0
Am I doing anything wrong?

**Comment by IMNotMax** [comment]
sudo npm install -g n
then 
sudo n stable
and you will be with:
```
pi@RaspberryPi3:~ $ nodejs -v
v4.8.2
pi@RaspberryPi3:~ $ node -v
v8.4.0
pi@RaspberryPi3:~ $ npm -v
5.3.0
```

**Comment by joq3** [comment]
@IMNotMax Thank you, but I just tried and this is what I got:
root@NAS:~# nodejs -v
v8.4.0
root@NAS:~# node -v
v8.4.0
root@NAS:~# npm -v
5.3.0

This is the error I receive now when running Homebridge and looking at the logfile:
`    at Object.Module._extensions..node (module.js:602:18)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/mdns/lib/dns_sd.js:24:20)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
`

**Comment by Merlinuf** [comment]
Same problem here, why did the even update the app with the abilty to upgrade homebridge if it crashes it...

**Comment by IMNotMax** [comment]
Hi there. 

I had similar issues after the last update of node and homebridge. 
I found some plugins I use (I currently use 7 plugins) are not working well with node 8...
I was enable to uninstall these plugins... thus, I remove all the plugins directories manually from /user/local/lib/node_modules, install again one plugin and test homebridge... 7 times to find which was the source of the trouble. 

Then cleaned the config.json to have homebridge back online ASAP and open an issue in the plugins’ github ;)

Hope this helps !

**Comment by Merlinuf** [comment]
Well it is the latest node 8.5 that crashes it, had to reinstall homebridge, not fun

**Comment by gwyner** [comment]
node -v
v8.4.0
npm -v
5.3.0

I'm getting the same error message:

> `Error: The module '/usr/local/lib/node_modules/homebridge/node_modules/mdns/build/Release/dns_sd_bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (module.js:602:18)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/mdns/lib/dns_sd.js:24:20)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
`

I've deleted homebridge from node_modules and I've done
`sudo npm install --unsafe-perm mdns
sudo npm rebuild --unsafe-perm`

Any ideas what else I can try?

**Comment by joelrichards** [comment]
I'm having the same issue. From reading this thread I don't see a clear conclusion.

**Comment by NorthernMan54** [comment]
The underlying issue here with mdns and needing to recompile the bindings was resolved by switching from mdns to bonjour a few months ago.

This issue when it relates to mdns should no longer be occurring if you are on the latest version.
