### ISSUE TITLE
rpi ZeroW installation problems

### ISSUE THREAD

**Issue by JangoBritt** [nfarina/homebridge#1506]
Hi all,

I have a Raspberry Pi Zero W, on which I installed Raspbian Stretch Light as the OS, from rpi.org.

I followed the instructions found here: https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi

For some reason, this seems to have installed homebridge into /opt/node/lib/node_modules/homebridge/bin

When following the instructions above, it all goes wrong when trying to set up homebridge as a service to boot on startup. It seems to have just sent my RPI into a loop, and as I'm running it headless, I've had to revert the changes via the SD card.

What have I done wrong? The instructions are SOOOO confusing!

**Comment by AndreiFAD** [comment]
Hi!

today I wrote a setup file for Rpi Zero W, it works for me:

sudo su
sudo wget -O -  https://raw.githubusercontent.com/AndreiFAD/rpi_install_homebridge_with_plugins/master/install.sh | bash
