### ISSUE TITLE
Error callback is not defined EHOSTUNREACH

### ISSUE THREAD

**Issue by ToXiiK** [nfarina/homebridge#1507]
Hello, I have an error which I cannot solve, indeed, I have an arduino with module ip on which is connected a led and a sensor of temperature. If I put only the led or only the sensor of temperature in the configuration file of homebridge everything works perfectly, but if I puts both in the configuration file, as soon as I throw homebridge on my iPhone, that this crash and shows an error message.

Is it a problem of compatibility in the http plugin homebridge and the plugin homebridge-http-temperature?
How to solve the problem?

**Comment by ToXiiK** [comment]
Hello,
After several hours of intensive research and testing, the only solution I found for this to work is not to specify a status_url in the configuration file.

However, this solution presents a major disadvantage, I no longer have the information of whether the lamp is switched on or off.

I hope someone will find a solution to solve this problem and have the lamp state.

cordially

**Comment by tvillingett** [comment]
I would recommend to have a look at the homebridge-mqtt plugin, which is well suited for microprocessors, and updates the homekit end directly when sending update.
