### ISSUE TITLE
Keen Smart Vents

### ISSUE THREAD

**Issue by mikeyobryan** [nfarina/homebridge#1508]
I'm curious if I can donate to someone who can write a plugin for my Keen Smart Vents hub.  I'd like to have the ability to open and close the vents and maybe even expose the pressure or temp sensors built into the units.  I would like to have the option of not exposing those sensors as well.  If anyone can help please let me know.

**Comment by macjeff** [comment]
I asked them a while back and they said homekit support was in the plans.   

Jeff

**Comment by ebaauw** [comment]
We added support for these to deCONZ, see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/269.  homebridge-hue should already expose these to HomeKit, as a dimmable light for control and as a temperature and pressure sensor.  I could change the light to something more appropriate in homebridge-hue, please open an issue there.
