### ISSUE TITLE
raspberry pi systemd load on boot?

### ISSUE THREAD

**Issue by JangoBritt** [nfarina/homebridge#1511]
Hi all,

I have a Raspberry Pi Zero W, on which I installed Raspbian Stretch Light as the OS, from rpi.org.

I followed the instructions found here: https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi

For some reason, this seems to have installed homebridge into /opt/node/lib/node_modules/homebridge/bin

All the instructions I've seen have it installing either in /usr/local/bin or /user/bin

What have I done wrong? The instructions are SOOOO confusing!

How can I configure my systemd to run homebridge, with it in the different folder?

Cheers!

**Comment by dmikhalsky** [comment]
use these instructions https://timleland.com/setup-homebridge-to-start-on-bootup/
and change ExecStart=/usr/local/bin/homebridge to (you guess it :-) /opt/node/lib/node_modules/homebridge/bin/homebridge

**Comment by dmikhalsky** [comment]
btw, my .homebridge directory (and probably yours) is not /home/pi/.homebridge, but /root/,homebridge so put config.json there

**Comment by JangoBritt** [comment]
Got it! Thanks
