### ISSUE TITLE
Avahi errors?

### ISSUE THREAD

**Issue by JangoBritt** [nfarina/homebridge#1512]
Any ideas how I can resolve this Warning on my Raspberry Pi installation? suggested URL doesn't exist.

*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>

**Comment by EdwinJS** [comment]
This is a warning many of us have seen before and is nothing to be alarmed about, most of us ignore it. No need to worry about it I think.

**Comment by Tiger519** [comment]
It has something to do with using emulated Bonjour support within Avahi (which is a similar but competing protocol). It's just saying that it wants you to use native Avahi instead of Bonjour. Homebridge uses Bonjour since that's the Apple standard. You can safely ignore the error.

**Comment by JangoBritt** [comment]
OK, thanks for the info!
