### ISSUE TITLE
config.json being pulled in from somewhere else

### ISSUE THREAD

**Issue by winstano** [nfarina/homebridge#1515]
Hi all,

Got a bit of an issue with Homebridge where it's not picking up much in my home at all. Long and short of it, I've been doing a bunch of diagnosis, and I think my config.json file is being pulled in from a location other than /usr/local/lib/node_modules/homebridge

There is no config.json in there, but when Homebridge launches, it states "Loaded config.json with 0 accessories and 1 platforms." - I think this is where the issue is, as I've completely uninstalled and reinstalled Homebridge, but it still pulls in an old config file from somewhere on my machine, but I can't for the life of me find it.

Is there a way to display the full file location of the config.json file that it's pulling across?

Edit: This is on OSX

**Comment by EdwinJS** [comment]
If you did the installation as specified for OSX, it is most likely that you have a hidden folder in your user folder named ".homebridge". This is where the config.json will probably be located 👍

**Comment by toshibochan** [comment]
Use terminal to go to homebridge folder!

Run homebridge once and this will automatic creat homebridge folder. Stop homebridge:
To start type:
homebridge
To stop:
Control C

Go to folder type:
cd ~/.homebridge

Creat config.json type:
sudo nano config.json

To go to homebridge in finder:
Just from menu
Go to
And type:
~/.homebridge
