### ISSUE TITLE
Error Retrieving Devices

### ISSUE THREAD

**Issue by kenlpeters** [nfarina/homebridge#1519]
Help Need for this Noob.  I have been getting the Error Retrieving Devices when Homebridge starts up.  I have uninstalled home bridge, the JSON Complete API, got my new app ID, updated the config, and well tried everything else I have found on the forums and I not crack this issue.  What I have not tried.

attached is my config

{
    "bridge": {
        "name": "Homebridge",
        "username": "CD:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-153"
    },
    "description": "JSON API",
    "platforms": [
        {
            "platform": "homebridge-smartthings.SmartThings",
            "name": "SmartThings",
            "app_url": "https://graph.api.smartthings.com:443/api/smartapps/installations/",
            "app_id": "removed",
            "access_token": "removed",
	    "polling_seconds": 3600,
	    "update_method": "direct",
	    "direct_ip": "192.168.1.8",
	    "direct_port": 8000,
	    "api_seconds": 30
        }
    ]
}

**Comment by maragelis** [comment]
This is a plugin problem, head over too their page and post the issue, I am sure someone will know something.
[https://github.com/pdlove/homebridge-smartthings/issues](https://github.com/pdlove/homebridge-smartthings/issues)
