### ISSUE TITLE
Distant access with dns ?

### ISSUE THREAD

**Issue by KiboOst** [nfarina/homebridge#1526]
Hi,

I know we have to use AppleTV or iPad to get distant access.

But isn't it possible to access the rasp via a dynamic DNS, and set this dynDNS in config.json to access it when not at home ?
Problem may be to access it at home over dynDNS then but who knows.

**Comment by toshibochan** [comment]
HomeKit outside access is connect to iCloud account! Not homebridge!

**Comment by toshibochan** [comment]
You need appletv or compatible iPad in the house to work as HomeKit hub

**Comment by KiboOst** [comment]
The logic is to have a device always on local network, which can synchronise with iCloud so those outside can get data from iCloud, right?
No way to hack it so the raspberry with homebridge is connected to iCloud and play this synch part ?

**Comment by toshibochan** [comment]
Probably Apple never going to allow anyone get access to HomeKit hub

**Comment by phpfs** [comment]
Simply use a VPN - Most routers include a vpn server these days :)

**Comment by eruizdechavez** [comment]
@KiboOst my guess is that you are trying to control your devices while not at home. As the previous comments briefly explain, remote access for your Home App is handled via iCloud. That said, it is perfectly valid to install something like https://www.npmjs.com/package/homebridge-config-ui and use that UI instead of the Home App to control your Homebridge when you are not at home.

**Comment by KiboOst** [comment]
wow, wasn't aware of this ! Will give it a test ;-)

**Comment by phpfs** [comment]
Actually, I thought that a HomeKit device can only be bound to one peer, so either an iCloud-Account (including Personal devices and iCloud-Accounts of ‚allowed‘ People (and their devices!)) or homebridge-ui can be used with one homebridge instance.
Isn‘t this still the case?

**Comment by ebaauw** [comment]
> Simply use a VPN - Most routers include a vpn server these days :)

You would need a bridging VPN or Bonjour won't work remotely.  Without Bonjour, your HomeKit app will still not find homebridge (or any other accessory), even though technically it can reach it.  Unfortunately, my router (a Fritz!Box) use a routing VPN.
