### ISSUE TITLE
Relay plugin doesn't work

### ISSUE THREAD

**Issue by noelbuechte** [nfarina/homebridge#1527]
Hi!

I've been running homebridge since a year now, using the relay plugin to switch dooropener, lamps and cameras.

It worked fine, but suddently it stops.

Debugging says:

Error when trying to open pin 33 (and for every other)
Gpio-admin: could not flush data to /sys/class/gpio/export: Device or resource busy

I'm using ios11

In the home-app all switched are labeled "not responsing"

I even tried to setup a complete new raspberry, same problem here. Supplyvoltage is adjusted to 5,00 volts on the usb port on the raspberry. The red led is off.

Can anyone help, please?

**Comment by AndreiFAD** [comment]
did you try this?

"
TROUBLESHOOTING

Error: gpio-admin: could not flush data to /sys/class/gpio/export: Device or resource busy

This message is related to a bug in the quick2wire-gpio-admin library, where if you attempt to export something that's already exported, gpio-admin crashed.

The simplest solution is to reboot. Alternatively, you can do the following, which will un-export all items. Note that this may lead to other hardware items on the box failing. A reboot may be the better option then.

sudo -s cd /sys/class/gpio

This command finds all items like 'gpio23' in the /sys/class/gpio, and then

runs a command like 'gpio-admin unexport 23'

ls -d gpio[0-9][0-9] | sed -e 's/gpio//g' | xargs -r -t -l1 -exec gpio-admin unexport exit # go back to a standard user
"

 (I have see here: https://github.com/oskarpearson/raspberry-pi-access-control-system/blob/master/SETUP.md)

**Comment by noelbuechte** [comment]
Hi,

Thanks for your hint, but it doesn't help. Reboot doesn't either.

**Comment by AndreiFAD** [comment]
sorry, for me only this plugin (https://www.npmjs.com/package/homebridge-gpio-device) worked well, with gpios, but only as root

**Comment by AppleTechy** [comment]
I'm going to close this issue due to it being plugin related. Please create an issue on the related github page for the plugin as well as the terminal log to further diagnose your issue. If it is determined to be a Homebridge framework issue go ahead and create a new issue and refrence the issue you created over on the github page for the plugin
