### ISSUE TITLE
Error (homebridge-harmonyhub)

### ISSUE THREAD

**Issue by RobotLimeLtd** [nfarina/homebridge#1529]
I'm getting the following error repeatedly, which causes homebridge to restart.  Inbetween restarts, it seems to be working fine.

I'm not sure if its the "Cannot add a bridged Accessory with the same UUID as another bridged Accessory" that eventually causes the failure, or whether the subsequent "Cannot update reachability on non-bridged accessory" is unrelated and actually causes the failure.

Node v8.6.0
NPM 5.3.0
Homebridge 0.4.28
OS NAME="Raspbian GNU/Linux"
  VERSION_ID="8"
  VERSION="8 (jessie)"

> Oct 02 12:54:53 homebridge homebridge[598]: Unhandled rejection Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: da4e91d9-37f7-4045-b8d8-4ac29e639448
> Oct 02 12:54:53 homebridge homebridge[598]: at Bridge.Accessory.addBridgedAccessory (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:257:13)
> Oct 02 12:54:53 homebridge homebridge[598]: at Bridge.Accessory.addBridgedAccessories (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:283:10)
> Oct 02 12:54:53 homebridge homebridge[598]: at Server._handleRegisterPlatformAccessories (/usr/lib/node_modules/homebridge/lib/server.js:437:16)
> Oct 02 12:54:53 homebridge homebridge[598]: at Server.<anonymous> (/usr/lib/node_modules/homebridge/lib/server.js:36:10)
> Oct 02 12:54:53 homebridge homebridge[598]: at emitOne (events.js:115:13)
> Oct 02 12:54:53 homebridge homebridge[598]: at API.emit (events.js:210:7)
> Oct 02 12:54:53 homebridge homebridge[598]: at API.registerPlatformAccessories (/usr/lib/node_modules/homebridge/lib/api.js:159:8)
> Oct 02 12:54:53 homebridge homebridge[598]: at /usr/lib/node_modules/homebridge-harmonyhub/lib/home-platform.js:149:15
> Oct 02 12:54:53 homebridge homebridge[598]: at PassThroughHandlerContext.finallyHandler (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/finally.js:57:23)
> Oct 02 12:54:53 homebridge homebridge[598]: at PassThroughHandlerContext.tryCatcher (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/util.js:16:23)
> Oct 02 12:54:53 homebridge homebridge[598]: at Promise._settlePromiseFromHandler (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/promise.js:512:31)
> Oct 02 12:54:53 homebridge homebridge[598]: at Promise._settlePromise (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/promise.js:569:18)
> Oct 02 12:54:53 homebridge homebridge[598]: at Promise._settlePromise0 (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/promise.js:614:10)
> Oct 02 12:54:53 homebridge homebridge[598]: at Promise._settlePromises (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/promise.js:693:18)
> Oct 02 12:54:53 homebridge homebridge[598]: at Promise._fulfill (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/promise.js:638:18)
> Oct 02 12:54:53 homebridge homebridge[598]: at Promise._resolveCallback (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/promise.js:432:57)
> Oct 02 12:54:53 homebridge homebridge[598]: at Promise._settlePromiseFromHandler (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/promise.js:524:17)
> Oct 02 12:54:53 homebridge homebridge[598]: at Promise._settlePromise (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/promise.js:569:18)
> Oct 02 12:54:53 homebridge homebridge[598]: at Promise._settlePromise0 (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/promise.js:614:10)
> Oct 02 12:54:53 homebridge homebridge[598]: at Promise._settlePromises (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/promise.js:693:18)
> Oct 02 12:54:53 homebridge homebridge[598]: at Promise._fulfill (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/promise.js:638:18)
> Oct 02 12:54:53 homebridge homebridge[598]: at PromiseArray._resolve (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/promise_array.js:126:19)
> Oct 02 12:54:53 homebridge homebridge[598]: at PromiseArray._promiseFulfilled (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/promise_array.js:144:14)
> Oct 02 12:54:53 homebridge homebridge[598]: at Promise._settlePromise (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/promise.js:574:26)
> Oct 02 12:54:53 homebridge homebridge[598]: at Promise._settlePromise0 (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/promise.js:614:10)
> Oct 02 12:54:53 homebridge homebridge[598]: at Promise._settlePromises (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/promise.js:693:18)
> Oct 02 12:54:53 homebridge homebridge[598]: at Promise._fulfill (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/promise.js:638:18)
> Oct 02 12:54:53 homebridge homebridge[598]: at Promise._resolveCallback (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/promise.js:432:57)
> Oct 02 12:55:53 homebridge homebridge[598]: /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:243
> Oct 02 12:55:53 homebridge homebridge[598]: throw new Error("Cannot update reachability on non-bridged accessory!");
> Oct 02 12:55:53 homebridge homebridge[598]: ^
> Oct 02 12:55:53 homebridge homebridge[598]: Error: Cannot update reachability on non-bridged accessory!
> Oct 02 12:55:53 homebridge homebridge[598]: at Accessory.updateReachability (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:243:11)
> Oct 02 12:55:53 homebridge homebridge[598]: at PlatformAccessory.updateReachability (/usr/lib/node_modules/homebridge/lib/platformAccessory.js:129:34)
> Oct 02 12:55:53 homebridge homebridge[598]: at ActivityAccessory.refreshConnection (/usr/lib/node_modules/homebridge-harmonyhub/lib/hub-accessory-base.js:56:17)
> Oct 02 12:55:53 homebridge homebridge[598]: at emitOne (events.js:120:20)
> Oct 02 12:55:53 homebridge homebridge[598]: at HubConnection.emit (events.js:210:7)
> Oct 02 12:55:53 homebridge homebridge[598]: at HubConnection._OnConnectionChanged (/usr/lib/node_modules/homebridge-harmonyhub/lib/hub-connection.js:151:7)
> Oct 02 12:55:53 homebridge homebridge[598]: at HubConnection.refreshAsync (/usr/lib/node_modules/homebridge-harmonyhub/lib/hub-connection.js:140:7)
> Oct 02 12:55:53 homebridge homebridge[598]: at HubConnection.refresh (/usr/lib/node_modules/homebridge-harmonyhub/lib/hub-connection.js:132:7)
> Oct 02 12:55:53 homebridge homebridge[598]: at HubConnection._HandleConnectionOffline (/usr/lib/node_modules/homebridge-harmonyhub/lib/hub-connection.js:127:14)
> Oct 02 12:55:53 homebridge homebridge[598]: at emitNone (events.js:105:13)
> Oct 02 12:55:53 homebridge homebridge[598]: at Client.emit (events.js:207:7)
> Oct 02 12:55:53 homebridge homebridge[598]: at Client.<anonymous> (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-client/lib/Client.js:157:12)
> Oct 02 12:55:53 homebridge homebridge[598]: at emitOne (events.js:120:20)
> Oct 02 12:55:53 homebridge homebridge[598]: at Connection.emit (events.js:210:7)
> Oct 02 12:55:53 homebridge homebridge[598]: at Socket.onDisconnect (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/reconnect-core/index.js:59:17)
> Oct 02 12:55:53 homebridge homebridge[598]: at emitNone (events.js:110:20)
> Oct 02 12:55:53 homebridge homebridge[598]: at Socket.emit (events.js:207:7)
> Oct 02 12:55:53 homebridge homebridge[598]: at endReadableNT (_stream_readable.js:1059:12)
> Oct 02 12:55:53 homebridge homebridge[598]: at _combinedTickCallback (internal/process/next_tick.js:138:11)
> Oct 02 12:55:53 homebridge homebridge[598]: at process._tickCallback (internal/process/next_tick.js:180:9)
> Oct 02 12:55:53 homebridge systemd[1]: homebridge.service: main process exited, code=exited, status=1/FAILURE
> Oct 02 12:55:53 homebridge systemd[1]: Unit homebridge.service entered failed state.
> Oct 02 12:56:03 homebridge systemd[1]: homebridge.service holdoff time over, scheduling restart.
> Oct 02 12:56:03 homebridge systemd[1]: Stopping Node.js HomeKit Server...
> Oct 02 12:56:03 homebridge systemd[1]: Starting Node.js HomeKit Server...
> Oct 02 12:56:03 homebridge systemd[1]: Started Node.js HomeKit Server.

**Comment by eruizdechavez** [comment]
I am going to blindly comment here. From the very first line seems something is attempting to add an accessory that is already added. Any chances a second instance of homebridge is trying to be opened, maybe duplicate script?

**Comment by plasticrake** [comment]
You may want to submit this to the [homebridge-harmonyhub](https://github.com/kraigm/homebridge-harmonyhub) repo as that is where the error is originating form.
