### ISSUE TITLE
Multiple Sonos Players: This callback function has already been called by someone else; it can only be called one time.

### ISSUE THREAD

**Issue by iphoting** [nfarina/homebridge#153]
I have the following config file:
```json
{
...
    "platforms": [
        {
            "platform": "Sonos",
            "name": "Sonos",
            "play_volume": 15
        }
    ],

    "accessories": [

    ]
}
```

When I run homebridge, I get the following error:
```bash
$ cd homebridge
$ npm run start
> homebridge@0.1.1 start /Users/iphoting/Development/Node.js/homebridge
> DEBUG=* node app.js || true

Starting HomeBridge server...
_____________________________________________________________________
IMPORTANT: Homebridge is in the middle of some big changes.
           Read more about it here:
           https://github.com/nfarina/homebridge/wiki/Migration-Guide
_____________________________________________________________________

Loading 1 platforms...
[Sonos] Initializing Sonos platform...
[Sonos] Fetching Sonos devices.
Loading 0 accessories...
[Sonos] Found device at 192.168.0.173
[Sonos] Found playable device - Dining Room
[Sonos] Initializing platform accessory 'Dining Room Sonos'...
  Accessory [Homebridge] Creating new AccessoryInfo for our HAP server +0ms
  Accessory [Homebridge] Creating new IdentifierCache +7ms
  EventedHTTPServer Server listening on port 51826 +18ms
[Sonos] Found device at 192.168.0.172
[Sonos] Found playable device - Ronald's Bedroom
/Users/iphoting/Development/Node.js/homebridge/node_modules/HAP-NodeJS/lib/util/once.js:11
      throw new Error("This callback function has already been called by someo
            ^
Error: This callback function has already been called by someone else; it can only be called one time.
```

Is there anyway to support multiple Sonos players?

**Comment by snowdd1** [comment]
Hi, I am sorry I to say the platform shim has a flaw there. It does not wait for all sonos devices to be discovered, but calls the callback immediately after discovering the first player.

**Comment by bezzers** [comment]
Bring me up to speed here? This used to work when I first wrote it. Has something changed in the way accessories are handled?

**Comment by snowdd1** [comment]
I don't know how it was before I joined here, today each platform must call the callback with the accessories array exactly once, because homebridge is counting the answers to know when to start the server and start advertising (all) the devices. 
If Sonos calls it twice and another platform did not yet answer, the server would be already starting and the Sonoses would be in, the other platform out...
@nfarina : Probably there is a way to push accessories into the running bridge some day?

**Comment by snowdd1** [comment]
Correction, everything seems to be in as long as not all accessories (not platforms) from the accessories section of the config.json are loaded. They are synchronous and might take a moment, so during that time multiple callbacks might have worked.
Today there is a protection on the callback with `once()`, so each platform can only call it once.

**Comment by bezzers** [comment]
Aha. Ok so I imagine that, if you have any slow-returning accessories, the old code would work. I do (a call to the Tesla API). If you don't it will fail.

I think your timeout approach looks like a good solution to the problem. I can't think how else you could do it given the asynchronous nature of the Sonos library.

I suppose the only other approach would be to retrieve the network topology of the Sonos network and figure it out from there. But that seems like overkill!

Sent from my iPhone

On Sep 8, 2015, at 8:09 AM, Raoul <notifications@github.com<mailto:notifications@github.com>> wrote:


Correction, everything seems to be in as long as not all accessories (not platforms) from the accessories section of the config.json are loaded. They are synchronous and might take a moment, so during that time multiple callbacks might have worked.
Today there is a protection on the callback with once(), so each platform can only call it once.

—
Reply to this email directly or view it on GitHub<https://github.com/nfarina/homebridge/issues/153#issuecomment-138533987>.

________________________________
This e-mail and any attachments may be confidential or legally privileged. If you received this message in error or are not the intended recipient, you should destroy the e-mail message and any attachments or copies, and you are prohibited from retaining, distributing, disclosing or using any information contained herein. Please inform us of the erroneous delivery by return e-mail. Thank you for your cooperation.

**Comment by snowdd1** [comment]
A quick google survey I did to figure that out returned to patterns: Count the callbacks (if you know how many to expect) and timeout (if you don't). As I am not into Sonos, simply when for the latter.

The same might apply to other platforms as well, so if it proves working I will add it to the wiki page as "proven practice" (as opposed to best prectice...)

**Comment by nfarina** [comment]
This is a problem with the platform approach that I think will become more common. For home devices that are "network discovered", we don't know how many there are until they show up. And we don't want to return early from our discovery since Homebridge will move on without us and serve a partial list of devices. 

I am still pondering ways to improve this - ideas are welcome. I'll post my current best idea in a separate issue for discussion.

**Comment by maddox** [comment]
@nfarina there could be some sort of way to call directly into the registration process. IE, let platforms register their own devices. So then you can spin up a platform lib, and tell it to discover, and as discovery happens, the platform lib registers each device.

**note**: this suggestions comes 100% without knowing ANYTHING about the new internals, heh.

**Comment by SphtKr** [comment]
Hitting this in YamahaAVR too, I just noticed.
