### ISSUE TITLE
Homebridge-Wink3 compatibility

### ISSUE THREAD

**Issue by jack-hub** [nfarina/homebridge#1530]
If I use this plug-in, either Homebridge or Homebridge-wink3 is not going to be happy with the version of node I'm running. In other words, if I "nvm use 4" then Homebridge starts up fine. If I install the Wink3 plugin, it will not load, unless I "nvm use 8" -- but Homebridge fails. MacOS High Sierra.

I'm using the Homebridge-Wink plugin instead. Not sure which Wink plugin to use?

**Comment by AppleTechy** [comment]
This is the latest and will be continued to be supported [Wink Plugin.](https://www.npmjs.com/package/homebridge-wink3) . Please post an output of the terminal failure message to further examine the issue

**Comment by jack-hub** [comment]
I gave up and started running it on MacOS instead of my Pi3.
