### ISSUE TITLE
Working characteristic for setting time (int/float/string) value?

### ISSUE THREAD

**Issue by pendowski** [nfarina/homebridge#1531]
I would rather ask on Slack or something but the site isn't working.

I've been writing a plugin for an RGB lamp which is controlled by ESP8266, so HTTP protocol.
I finally got the colors working correctly but have a problem with additional functionality.

My lamp has a timer mode where I can set that it should turn off after given amount of time. Obviously, Lightbulb service doesn't support that in any way. The closest thing that could work in theory would be `DigitalZoom` or `OpticalZoom` characteristics - both having Read and Write of float, but I wasn't able to add those to any Service.

An alternative could be also `LockManagementAutoSecurityTimeout` for `LockManagement`, but I wasn't successful in setting it up as a service. I guess I'm missing something in should return in `LockControlPoint` but it doesn't appear in Home app when I just call callbacks in `LockControlPoint` and `Version` get and set events.

Do you know any plugin that has `LockManagement` working or ability to set an arbitrary number or string from the Home app?

**Comment by NorthernMan54** [comment]
Or how about brightness?

I used that to control speaker volume

**Comment by pendowski** [comment]
@NorthernMan54 brightness is pretty useful on its own when it comes to the lightbulb, so probably not. Unless I would duplicate the plugin and use the slider on the duplicate. I did something similar when I was trying to use fan rotation speed (turned out to be just a percentage value).
The main issue here is that you have to have hardcoded value of timer and use the slider to set percentage of that value, which is far from ideal. Would rather have some number input (maybe something with + and - for steps) or just text input I would parse.

**Comment by tvillingett** [comment]
iOS 11 has timeout for setting automation, so you can have it to turn off 1-60 minutes after you turn it on. But that is of course then not changeable directy, other than in the settings for the automation.

**Comment by plasticrake** [comment]
You may know this, but you can have multiple services attached to an accessory. So you can have two lightbulbs or a lightbulb and a door lock / thermostat, etc. It's a shame Homekit is really only good at what it can do, you can't really expand on it without hacks.

**Comment by ebaauw** [comment]
I'm using a custom characteristic, `Duration` for the duration before motion sensors turn off the lights after there's no more motion detected.  Works on almost all HomeKit apps, except Apple's Home and Siri.  If you create a scene with a custom characteristic using another HomeKit app, you can still recall it (and use it in rules) from Apple's Home or Siri.

**Comment by pendowski** [comment]
Thanks, guys. I was hoping that it would work with Apple's Home.app, but the timer isn't that essential for everyday use. I added custom characteristic and it seems to work so I'll play a bit with that and use Eve or some other app when I would want to activate the sleep timer.

👍 

It's really odd that they didn't add some way to edit those custom characteristics from the built-in app. I would understand that it wouldn't be perfect, wouldn't work with Siri but come on - a slider or just a text field to edit those values would be better than forcing accessory manufacturers to build their own apps just to set an int/float/bool/string that Apple didn't think that certain accessory would need.
