### ISSUE TITLE
Need help with config.json

### ISSUE THREAD

**Issue by ggamehdtv** [nfarina/homebridge#1532]
Hello,

I am trying to setup nefit-easy with homebridge but the config keeps giving errors which I can't find.
Can someone tell me where the error is in the config?

{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154",
        "manufacturer": "@nfarina",
        "model": "Homebridge",
        "serialNumber": "0.4.20"
    },
    
    "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",

    "accessories": [
        {
            "accessory" : "NefitEasy",
            "name"      : "Thermostaat",
	    "options"   : {
   		"serialNumber" : "NEFIT_SERIAL_NUMBER",
		"accessKey"    : "NEFIT_ACCESS_KEY", 
		"password"     : "NEFIT_PASSWORD" 
        }
    ],

    "platforms": [
        {
            "platform" : "PhilipsHue",
            "name" : "Hue"
        }
    ]
}

Hope that someone can help me.

Best Regards Justinn

**Comment by AndreiFAD** [comment]
here can you validate: https://jsonlint.com/


Error: Parse error on line 21:
...IT_PASSWORD"			}		],		"platforms": [
---------------------^
Expecting '}', ',', got ']'


here:
....
			"password": "NEFIT_PASSWORD"
		}
	}],
....

**Comment by maragelis** [comment]
{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154",
		"manufacturer": "@nfarina",
		"model": "Homebridge",
		"serialNumber": "0.4.20"
	},

	"description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",

	"accessories": [{
		"accessory": "NefitEasy",
		"name": "Thermostaat",
		"options": {
			"serialNumber": "NEFIT_SERIAL_NUMBER",
			"accessKey": "NEFIT_ACCESS_KEY",
			"password": "NEFIT_PASSWORD"
		}
	}],

	"platforms": [{
		"platform": "PhilipsHue",
		"name": "Hue"
	}]
}
