### ISSUE TITLE
automatically start Homebridge with launchd

### ISSUE THREAD

**Issue by wheinsky** [nfarina/homebridge#1534]
I created a plist file with the listed contents, dropped it in ~/Library/LaunchAgents, but I can't seem to get Homebridge to start up on boot. I tried running the load/unload command manually, it executes but Homebridge does not actually start. When I start Homebridge by typing Homebridge in a terminal window it runs no problem. 

Any help would be greatly appreciated

**Comment by maragelis** [comment]
just follow this wiki page https://github.com/nfarina/homebridge/wiki/Homebridge-autostart-at-boot-(init.d)-on-Ubuntu-(linux)

**Comment by retroneo** [comment]
I have updated the Mac wiki page with instructions that actually work.

https://github.com/nfarina/homebridge/wiki/Install-Homebridge-on-macOS

**Comment by vdrover** [comment]
Following up here: launchd is not working for me, but things work fine when I run homebridge manually. 

I'm a bit concerned that on my system homebridge is installed in `.homebridge` while other folks seem to have it in `homebridge`.

In any case, I did actually create my own homebridge directory for logs but that also didn't work.

Here is my plist (my actual username redacted):

```<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>RunAtLoad</key>
        <true/>
    <key>KeepAlive</key>
        <true/>
    <key>Label</key>
        <string>com.homebridge.server</string>
    <key>ProgramArguments</key>
        <array>
             <string>/usr/local/bin/homebridge</string>
             <string>-I</string>
        </array>
    <key>StandardOutPath</key>
        <string>/Users/NAME/Documents/homebridge/logfile.log</string>
    <key>StandardErrorPath</key>
        <string>/Users/NAME/Documents/homebridge/logfile.log</string>
    <key>EnvironmentVariables</key>
        <dict>
        <key>PATH</key>
            <string>/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
        <key>HOME</key>
            <string>/Users/NAME</string>
        </dict>
</dict>
</plist>```
