### ISSUE TITLE
Does Homebridge Support Latest Devices

### ISSUE THREAD

**Issue by VeniceNerd** [nfarina/homebridge#1535]
Does Homebridge supports all of Homekits 10 and 11 device types (listed here https://www.apple.com/ios/home/accessories/) yet? Mainly wondering about Curtains/Shutters. Seems like Homebridge may still be stuck in iOS 9 land in regards to devices?

**Comment by ggamehdtv** [comment]
If you are asking if homebridge only works with iOS9 then the answer is no. I am using it with iOs 10 and 11

**Comment by VeniceNerd** [comment]
No I'm wondering weather Homebridge  supports the new device types that iOS 10 and iOS 11 introduced. Curtains/Shutters/Cameras/Sprinklers, etc...

**Comment by KhaosT** [comment]
@VeniceNerd Yep it does, all [those services](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js) are there for developers to use.
