### ISSUE TITLE
Guide to install Homebridge on OpenWRT/LEDE

### ISSUE THREAD

**Issue by lam560** [nfarina/homebridge#1538]
Is there any guide to install home bridge on openWRT or LEDE ?
I tried many things but it failed every time : 
`Error: not found: make`

`Failed at the curve25519-n2@1.1.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the curve25519-n2 package,
npm ERR! not with npm itself.`

**Comment by daniel0076** [comment]
If help is still needed, I have successfully install HomeBridge on my LEDE Reboot.
you can check out this [Repo](https://github.com/nxhack/openwrt-node-packages) if you are making your ROM from the source code. You may add them in menuconfig

Or if you want to install on your LEDE router follow the steps,
1. Install node from opkg,  and need to install `node-gyp` with npm
`opkg update & opkg install node node-npm`
 `npm install -g node-gyp `
2. Install make tools from opkg, `gcc` and `make` is needed
`opkg install gcc make`
3. Go back to your LEDE source code, 
`make menuconfig`
and select **Package the LEDE-Base Toolchain**
save and make. The cross-compiled libpthread.a is needed.
4. Copy `/path/to/lede/source/staging_dir/toolchain-[YOUR ARCH]/lib/libpthread.a` to your LEDE `/usr/lib`
5. Use npm to install HomeBridge
`npm install -g homebridge`

The `libpthread.a` in step 4 is used for compiling `node-mdns`, which is required by HomeBridge

**Comment by lam560** [comment]
thank you a lot, I will try it, how many disk memory you need for the installation ?
I have 22MB free, I guess I will need to make an external memory.

**Comment by daniel0076** [comment]
@lam560  It's around 250MB or more. You need extroot I think.

**Comment by shawnchain** [comment]
Checkout this feed, and you can directly build out the node-homebridge ipk file.
https://github.com/nxhack/openwrt-node-packages

**Comment by perryraskin** [comment]
Has anyone successfully done this? I would LOVE to have this working.

**Comment by daniel0076** [comment]
@perryraskin Not sure if any other done this, but it has been working fine since Sep. 2017  on my LEDE (now is merged back to OpenWRT) router.

**Comment by perryraskin** [comment]
I am having an issue using NPM. Node installed successfully, but when i try `npm install` for anything, i get `segmentation fault`

**Comment by shawnchain** [comment]
check if you're using some mips cpus with fpu emulation disabled in kernel, if true, recompile the kernel with fpu_emulation enabled.

**Comment by perryraskin** [comment]
lol would you be able to elaborate, i'm not so sure what you are saying. how do i check things like that? how to i recompile, etc? TIA

**Comment by OoHerbethoO** [comment]
@perryraskin Here is a guide to how to check and enable emulation of FPU in the kernel OpenWrt
http://shmichen.blogspot.com/2017/08/how-to-enable-fpu-emulator-on-openwrt.html

**Comment by faxioman** [comment]
@daniel0076 no needs to compile libpthreads from source. Pthread is part of libc so you only need to create an ar archive using:

```
ar -rc /usr/lib/libpthread.a
```

**Comment by WiZaR5789** [comment]
Hi, looking for help... Im succesfuly installed homebridge but when im trying to start service an error ocures...


root@lede-R:~# homebridge
Initializing HAP-NodeJS v0.9.1...
/usr/lib/node_modules/homebridge/node_modules/fs-extra/lib/mkdirs/make-dir.js:85
      } catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/fs-extra/lib/mkdirs/index.js:3:44)

**Comment by Hi-hass** [comment]
I can't run ’hb-service install‘ to create a config, where is the default config dir?
