### ISSUE TITLE
Dynamic Platform Configuration (configurationRequestHandler?)

### ISSUE THREAD

**Issue by plasticrake** [nfarina/homebridge#1539]
I currently have a dynamic platform that detects accessories on the network. I'd like to include a way for users to remove accessories that no longer exist (since stale accessories are cached) without having to the remove the `/persist/` and `/accessories/` folders.

I tested out `configurationRequestHandler` using `Hesperus` (which was kind of hidden, took me awhile to find it 😱 ). Is it true that CRH is not supported by the Apple Home app?

While not the most user friendly method, I'm thinking of exposing an HTTP endpoint like shown [here](https://github.com/nfarina/homebridge/blob/b6f382950ceba1b640808ffdc1de358c4738ec09/example-plugins/homebridge-samplePlatform/index.js#L43). And including the `curl` commands in my README.

I know that better configuration options are planned #1039 (any updates on this?), but are their any existing platforms that are offering simple configuration that I can look at?

Thanks! 😸

**Comment by KhaosT** [comment]
@plasticrake Hi Patrick, the configuration request handler is a thing created for Homebridge and it's not something Apple defined official so Home app doesn't support it.

Honestly I'm not sure what's the best approach here, there are plugins (like [this](https://github.com/devbobo/homebridge-lifx-lan/blob/master/index.js#L230)) supports modifying stuff using configuration request handler but moving forward we are definitely interested in having a proper web interface to do this kind of stuff. However, time just doesn't work in my favor and I can't guarantee any timeline for now.

**Comment by ebaauw** [comment]
Personally, I would prefer to update the configuration from HomeKit, rather than having an additional web-based interface.  As I'm still on static platform accessories, I haven't really implemented any of this, apart from the heartrate controlling the polling of the Hue bridge.  I do see some caveats:
- As mentioned: Apple's Home app doesn't support custom services nor custom characteristics, so you'd need another app (I'll have a look at Hesperus);
- You would want to be able to limit access to the configuration, but I've got no clue how to realise that using `AdministratorOnlyAccess` (see #1389)

**Comment by plasticrake** [comment]
@ebaauw I don't think HomeKit / Home was designed to have extra configuration interfaces built-in. All custom configuration is to be done by 3rd party apps. (like the Philips Hue app for Hue products, etc). So for homebridge configuration it would need some sort of interface outside HomeKit, whether that is web or app. All I really want is a "remove accessory" button for my platform devices, but even that seems out of scope for HomeKit.

According to the documentation the `AdministratorOnlyAccess` characteristic is a flag that locks down a device to only accept commands from an administrator, it doesn't seem to have to do with configuration. The docs specifically use it as an example for Door Locks (who can open).
