### ISSUE TITLE
Closing GitHub Issues

### ISSUE THREAD

**Issue by plasticrake** [nfarina/homebridge#1543]
I would ask this on slack but it's still down.

There are almost 700 open issues on this repo, many issues are really just troubleshooting and many are issues with plugins that don't belong here.

I realize the authors may not have time to monitor the issues, but I see people responding (some marked as contributors) either solving issues or redirecting them to the plugin's repos, but the issues stay open since they don't have the ability to close them. 

Might I suggest adding some collaborators to the repo to help close issues? I know GitHub's permissions are limited unless this repo is moved into an organization, but I'd be willing to help if I was given permission to close issues and I bet some others here would too.

Any thoughts? @nfarina @KhaosT 

Thanks!

**Comment by nfarina** [comment]
I would absolutely love some help here. I've just added you as a collaborator and if anyone else would like to pitch in on Issues I would greatly appreciate it! (If you have suggestions for people let me know)

**Comment by NorthernMan54** [comment]
You can add me as well.

I think we need to make it easier for people to self serve on issues, and have them look for similar or resolved issues first before opening new issues.

**Comment by nfarina** [comment]
We could add a "new issue template" perhaps? I've seen other large OSS projects use those to try and guide people's behavior when posting issues - asking for reproducible steps, asking if they've searched for similar issues, etc.

**Comment by AppleTechy** [comment]
I must partially apologize for this too. @nfarina other things in my life have just taken priority and I have some what life Homebridge in the dust. I’ll try and be more active in closing issues.

**Comment by maragelis** [comment]
Count me in ..

**Comment by AndreiFAD** [comment]
I can help you as well

**Comment by AppleTechy** [comment]
I went ahead and created a Slack channel for anyone who has moderating power(collaborator,etc) over the Github page. If I missed anyone feel free to contact me on Slack @ applegeek or tag me on here with your slack username and I can add you.

**Comment by AndreiFAD** [comment]
@AppleTechy AndreiFAD
