### ISSUE TITLE
Cannot add homebridge as accessory in Home App

### ISSUE THREAD

**Issue by alantahoe** [nfarina/homebridge#1545]
I have homebridge up and running on a Linux virtual machine. Was finally able to get he config to load everything but now when I go to the home app and enter the code it just keeps searching and never finds it. What am i doing wrong?

**Comment by jamitupya** [comment]
this just started happening for me today. i'm looking at it as well but cant see the issue yet.

i've already changed the MAC address to test this, but no joy. still looking.

**Comment by vraicovi** [comment]
You don't have a firewall running on the VM or the host, do you?  That was the first issue I ran into when I ran it on a Linux VM.

**Comment by aaronjedwards** [comment]
I also can't seem to add the accessory to home kit. It doesn't show up after entering in the code. im running on macOS

**Comment by jamitupya** [comment]
@vraicovi no, not for myself, but seems may have been a stale volume i was dealing with under docker. for me, i updated my repo and changed the MAC / user account its using. also changed the default pin and it started working again.

**Comment by cpp-dev** [comment]
any solve here? i have the same issue.

**Comment by fdmfm** [comment]
was this solved. changing the username everytime i reboot homekit is not an option for me really.

**Comment by barquestdan** [comment]
I'm hitting the same issue... I went from telling Siri "Goodnight" and everything in my house shutting down through SmartThings to none of my accessories talking to homekit at all.

I even deleted the entire .homebridge folder and started over again from scratch.
Homebridge is working perfectly on my mac mini which is hardwired into the airport extreme that my phone is connected to.  I manually enter the code into my home app on my phone and the "wheel of opportunity" just keeps spinning and spinning until it times out.

I feel like I'm on the Oregon trail every time I have to open my stupid SmartThings app to change my thermostat or turn off my TV :0/

**Comment by JeremyChiang1992** [comment]
Hey ,I'm hitting the same issue...But in the morning today , it works normal. And I try to recovery the config.json ,it dose not work...Then , I try to that way from README.md ----- delete the persist/ directory ...and so on...now , it just keeps searching and never finds it.... : (

**Comment by JeremyChiang1992** [comment]
I found that the  specified port which is  define in the "bridge" section of config.json is not open~~~~ Why?

**Comment by JeremyChiang1992** [comment]
Well , I found that if there are a lots of equipment on the Wifi network, like at the company ,  my Home app can not find the homebridge ; if  there are a few equipment on the Wifi network, like at home ,my Home app can find the homebridge quickly .  Do you have this issue?
