### ISSUE TITLE
Issues Installing on macOS

### ISSUE THREAD

**Issue by allkindsofralph** [nfarina/homebridge#1547]
I tried to install on macOS and it did not create the .homebridge folder in the user folder. I would run homebridge and it would say that it didn't find the config.json file, which is what I am assuming is due to the folder not being there. So I copied the sample and created the folder in the correct location and it was still not working right.

I then deleted the npm folder in my User folder and tried to install again. Installing homebridge acts as it updates, but homebridge-harmonyhub gives an access error. I also don't know if this was due to the NPM update I did.

Is there a way to delete the installs so far and start again?

**Comment by toshibochan** [comment]
Try reinstall node, homebridge and homebridge-harmonyhub
Run homebridge one time. This will make homebridge folder automatically. Stop home bridge. 
To go to homebridge folder in terminal:
cd ~/.homebridge
To go to homebridge folder:
In folder menu select GO TO FOLDER and type ~/.homebridge
In homebridge folder you can creat config.json

**Comment by toshibochan** [comment]
Homebridge will make homebridge folder after run first time but not going to make config.joson! You have to make config.json
Just run
sudo nano ~/.homebridge/config.json
And past your configuration and save.
And run homebridge
