### ISSUE TITLE
Cannot find logs

### ISSUE THREAD

**Issue by honcheng** [nfarina/homebridge#1548]
I can’t seem to find logs for homebridge.
I start homebridge with this command 

`sudo systemctl start homebridge `

I have checked /var/logs, there’re no logs there for homebridge. 
I have used journalctl, but it shows ‘no journal files were found’.

Whenever homebridge crashes and I need to debug, I can only use 
`sudo systemctl status homebridge `
But that usually gives me insufficient lines to find out what’s wrong. 

Can someone help to point me in the right direction? Thanks.

**Comment by maragelis** [comment]
tail -f /var/log/syslog

**Comment by honcheng** [comment]
Thanks!
