### ISSUE TITLE
Homebridge cant be discovered on second IOS device

### ISSUE THREAD

**Issue by Exodus000** [nfarina/homebridge#1549]
I add homebridge with 2 lamps to my homekit but when I try another iPhone with different apple id it doesn't show at all. 

Does homebridge only support devices with same apple id?

**Comment by toshibochan** [comment]
In the home app you can invite people! Go to Home app setting and invite the other email address

**Comment by daniel2029** [comment]
The way the HomeKit protocol works is by connecting to a single device. Then by using iCloud sharing the home with other devices. I have it set up on my phone and then shared with my wife and kids.
