### ISSUE TITLE
"Outside" access

### ISSUE THREAD

**Issue by alveman** [nfarina/homebridge#1550]
I have an Apple TV 4 at home (WiFi connected). I supposes that the TV will work as a bridge for external Connections, and if I look at it, it's connected to Raspberry and everything work as long I'm at the local network. But from the outside I don't get any Connection to all my devices.

 This is very strange because it has worked before and as far as I know I have not changed anything. Do you have any suggestions where I will start looking for this error?

 I think maybe this started when I updated the iPhone to iOS 11.0.3

**Comment by KhaosT** [comment]
Open Home app, check home settings and see if your "Home Hubs" are connected.

**Comment by alveman** [comment]
Yes it's connected

**Comment by KhaosT** [comment]
In that case maybe try use Siri on Apple TV and see if Apple TV itself can control homebridge devices?

**Comment by alveman** [comment]
I logged in and out twice from icloud with the Apple TV and now it works. Thanx for your help!!!

**Comment by KhaosT** [comment]
No problem.
