### ISSUE TITLE
Can't find info on orange pi zero

### ISSUE THREAD

**Issue by sballoz** [nfarina/homebridge#1555]
Hi I have home bridge running on my Raspberry! I want to run some tests on a new orange pi zero running debian xfce but I cannot find specific info, anyone can help me on that?
thanks a lot

**Comment by plasticrake** [comment]
I'm not sure what you're asking. But homebridge should run the same as on your rapsberry pi.

**Comment by sballoz** [comment]
ok thanks. That's good news :-)
