### ISSUE TITLE
Notifications from Switches

### ISSUE THREAD

**Issue by zama36** [nfarina/homebridge#1557]
Is there any way for homebridge to enable notifications for switch devices either through code or tags?    Or is this simply a limitations of the homekit platform? 

Ultimate goal, get a notification like a sensor notification when a switch is turned on or off.

Thanks.

**Comment by zama36** [comment]
Was thinking I could use IFTTT's Webhooks.  While initial testing seemed fine but further testing showed how it is unreliable.  calls into the service aren't registered.  No warning of potentially hitting limits.  Any thoughts or suggestions would be appreciated.

**Comment by ricargr** [comment]
Could you finally to do it? i am interested in get home kit notifications from switches. Thanks

**Comment by zama36** [comment]
Sorry, no.

**Comment by ricargr** [comment]
I found and alternative if could be valid for you
https://www.npmjs.com/package/homebridge-http-motion-sensor
Regards

**Comment by ebaauw** [comment]
> Could you finally to do it? i am interested in get home kit notifications from switches. Thanks

Homekit will only issue notifications on security-releated services/characteristics (e.g. motion sensors, door sensors, etc).  Either you (the homebridge plugin) need to expose the switch as a security device, or you need to expose a security device which is set by the switch, see e.g. https://github.com/ebaauw/homebridge-hue/issues/179.
