### ISSUE TITLE
Refresh speed

### ISSUE THREAD

**Issue by 45clouds** [nfarina/homebridge#1559]
Hi,

Each time I run Home.app on my phone/tablet I have to wait few seconds (up to 5) until application receive status of devices connected via homebridge. On the other hand Philips Hue lights (which are connected "directly" without using homebridge) update their status almost immediately. Has someone resolved this issue? Or maybe I'm the only one who has this problem? Any ideas?

Homebridge is running on MacMini (i5, wired gigabit network, a lot of memory, ssd). I assume it is not a problem with slow hardware.

Bests,
Michal

**Comment by xtremforce** [comment]
Same problem here.

**Comment by vsidlu** [comment]
Check homebridge plugins. I got this problem when installed and configured plugin is not in use. Then status update is slower!

**Comment by janbsson** [comment]
Did you get the issue resolved? I also have this issue :(

**Comment by andig** [comment]
Same here https://github.com/andig/homebridge-fritz/issues/30. I suspect that home updates every device before opening.

**Comment by janbsson** [comment]
I found that instead of using numeric up address like 10.0.1.67, I used url like myownip.nu and the I ran really fast.  I guess localhost also works much faster than 127.0.0.1 but have not tested.

**Comment by Hohnjo** [comment]
Has someine figured out how to solve the issue ?

**Comment by 45clouds** [comment]
No. The issue is still opened.

**Comment by janbsson** [comment]
As I wrote above, if you use url name instead of numeric ip, the delay disappeared, at least for me

**Comment by Hohnjo** [comment]
Thanks @janbsson ! Which file do you edit to change the ip adress ? Is it the config.json ? When I find it I just need to replace the numeric adress by "myownip.nu" ? Sorry for the beginer questions..

**Comment by janbsson** [comment]
Hello Hohnjo,

You shall edit the ip address in config.json. I have a public URL which I used to replace the IP address with. I wrote myownip.nu but it’s not the real address I have (I just don’t want to reveal by web site). If you do not have a public IP address to your web server, either create one and make the web server public by opening up port 80 in your router to point to the servers up.

Another, easier way you could test is to replace the ip with localhost in case you run homebridge in the same computer as the web server, I have not tried that but it might do. In that case you don’t need to have a public server.

I suppose the reason for the delay is that the homebridge first tries to convert the alphanumeric url to a numeric one but since the url is already numeric, the conversion times out and the the original numeric url is returned. This timeout takes some theme and thus the delay. 

If you try using localhost, it would be helpful for other is you report back the result here. 

I think it would be good to check the homebridge code for my suspicions and add a check if the url is already numeric, just skip the conversion. Maybe I will do that someday but not now.

Good luck!

**Comment by Hohnjo** [comment]
Thanks for the time you've taken to answer ! 

I run homebridge on a raspberry pi connected to my router by ethernet, only used for this and 24/7 power on.

So I should try to edit my config.json this way ?

{
"bridge": {
"name": "Homebridge",
"username": "mac adress of my rapsberry",
"port": localhost,
"pin": "011-12-399"
},


Not sure the "localhost" is to be written after "port"...

**Comment by Samfox2** [comment]
No, I think you are talking about different things. @janbsson means if you are using a plugin like homebridge-http you should change the ip-adresses with their network names or localhost. Than this plugin can answer faster.

**Comment by janbsson** [comment]
Yes exactly Samfox2!

Like this:
  "accessories": [
   {
      "accessory": "HttpAccessory",
      "service": "TemperatureSensor",
      "name": "Jacuzzi",
      "apiBaseUrl": "localhost",
      "apiSuffixUrl": "val.php?sensor=sensId_87_Jacuzzi_temp",
      "forceRefreshDelay": 0
    },

But as i said earlier, i have note tested with localhost, instead i have my website url.

Good luck!

**Comment by Hohnjo** [comment]
Ojay thanks both of you, i'm using homebridge plugin (not http), so the solution isn't possible for me !

**Comment by janbsson** [comment]
Can you show us your content of config.json here?

**Comment by Hohnjo** [comment]
Yes of course ! I've replaced some things by xxx and kind of "zedzedzedzedzd"



{
	"bridge": {
		"name": "Homebridge",
		"username": "xxx",
		"pin": "xxx"
	},
	"accessories": [{
		"accessory": "MiGatewaySecurity",
		"ip": "xxx",
		"token": "xxx",
		"name": "xxx",
		"disable": true,
		"switchName": "xxx",
		"switchDisable": false
	}],
	"platforms": [{
			"platform": "MiAqaraPlatform",
			"gateways": {
				"xxx": "xxx"
			},
			"defaultValue": {
				"xxx": {
					"Gateway_Lightbulb": {
						"name": "gateway light",
						"disable": true
					},
					"Gateway_LightSensor": {
						"name": "living room light sensor",
						"disable": true
					},
					"Gateway_Switch_JoinPermission": {
						"name": "living room gateway join permission switch",
						"disable": true
					}
				},
				"zddzdzedzedz": {
					"Gateway_Lightbulb": {
						"name": "gateway light",
						"disable": true
					},
					"Gateway_LightSensor": {
						"name": "living room light sensor",
						"disable": true
					},
					"Gateway_Switch_JoinPermission": {
						"name": "living room gateway join permission switch",
						"disable": true
					}
				},
				"zedzdz": {
					"ContactSensor_ContactSensor": {
						"name": "xxx"
					}
				},
				"zedzedz": {
					"TemperatureAndHumiditySensor_TemperatureSensor": {
						"name": "xxx"
					}
				},
				"zedzefdze": {
					"Global": {
						"disable": true
					},
					"Button_StatelessProgrammableSwitch": {
						"name": "xxx",
						"disable": false
					}
				}
			},
			"xxx": {
				"WaterDetector_LeakSensor": {
					"name": "xxx"
				}
			},
			"zdzedz": {
				"PlugBase_Outlet": {
					"name": "xxx"
				}
			},
			"zedzefzf": {
				"PlugBase_Outlet": {
					"name": "xxx"
				}
			},
			"zefzefzf": {
				"PlugBase_Outlet": {
					"name": "xxx"
				}
			},
			"zefzefzef": {
				"PlugBase_Outlet": {
					"name": "xxx"
				}
			},
			"zefzefzefzf": {
				"MotionSensor_MotionSensor": {
					"name": "xxx"
				}
			},
			"zefzefzefez": {
				"MotionSensor_MotionSensor": {
					"name": "xxx"
				}
			}
		},
		{
			"platform": "BroadlinkRM",
			"name": "Broadlink RM",
			"hideScanFrequencyButton": true,
			"scanFrequency": true,
			"hideLearnButton": true,
			"accessories": [{
				"name": "xxx",
				"type": "switch",
				"data": {
					"on": "xxx",
					"off": "xxx"
				}
			}]
		},
		{
			"platform": "MiPhilipsLightPlatform",
			"deviceCfgs": [{
				"type": "MiPhilipsSmartBulb",
				"ip": "xxx",
				"token": "xxx",
				"lightName": "xxx",
				"lightDisable": false
			}, {
				"type": "MiPhilipsSmartBulb",
				"ip": "xxx",
				"token": "xxx",
				"lightName": "xxx",
				"lightDisable": false
			}, {
				"type": "MiPhilipsSmartBulb",
				"ip": "xxx",
				"token": "xxx",
				"lightName": "xxx",
				"lightDisable": false
			}, {
				"type": "MiPhilipsSmartBulb",
				"ip": "xxx",
				"token": "xxx",
				"lightName": "xxx",
				"lightDisable": false
			}, {
				"type": "MiPhilipsSmartBulb",
				"ip": "xxx",
				"token": "xxx",
				"lightName": "xxx",
				"lightDisable": false
			}, {
				"type": "MiPhilipsSmartBulb",
				"ip": "xxx",
				"token": "xxx",
				"lightName": "xxx",
				"lightDisable": false
			}, {
				"type": "MiPhilipsSmartBulb",
				"ip": "xxx",
				"token": "xxx",
				"lightName": "xxx",
				"lightDisable": false
			}, {
				"type": "MiPhilipsSmartBulb",
				"ip": "xxx",
				"token": "xxx",
				"lightName": "xxx",
				"lightDisable": false
			}, {
				"type": "MiPhilipsSmartBulb",
				"ip": "xxx",
				"token": "xxx",
				"lightName": "xxx",
				"lightDisable": false
			}, {}]
		}
	]
}

**Comment by janbsson** [comment]
Ok, I think you shall try replacing the ip: addresses in the accessory part with alphanumeric url’s, if the up address is the same as where homebridge executes, you can try localhost...

**Comment by Hohnjo** [comment]
The MiPhilipsLightPlatform plugin works with ip adress but not the MiAqaraPlatform. Everything is connected to the same network so i will try the localhost solution (the alphanumeric solution seems difficult to me i'm not that good in computers..) but even if it works the MiAqaraPlatform will still be slow :/

**Comment by OlehProkopenko** [comment]
Hi, I've just fixed this issue by replacing IP addresses with the network URLs for my Sonoffs, and now everything works without any lag. Looks like the problem was in them because replace of IP for other devices changed nothing.

**Comment by janbsson** [comment]
Great!

**Comment by Hucksleyy91** [comment]
I can confirm after changing my WOL IP address and 1 other accessories from an ip like “192.168.1.50” to “device name on network” so I just used my router app and found the device name or you can use localhost and finally ! No more updating on all my accessories edit your config file I’ve had this issue forever and finally found the fix :)

**Comment by andredewaard** [comment]
Anyone got a solution for this? If I change it to device name like so: ‘LGwebOSTV‘ because my tv‘s name is displayed like that on my router it doesn’t work. 

My config looks like this:
```
{
    "bridge": {
        "name": "HOOBS",
        "username": "0E:F3:04:74:1E:8F",
        "port": 51826,
        "pin": "263-54-530"
    },
    "description": "This file is used for plugin configuration.",
    "accessories": [
        {
            "accessory": "webostv",
            "name": "TV",
            "ip": "192.168.178.16",
            "mac": "...”,
            "channelControl": false,
            "volumeControl": false,
            "tvservice": true,
            "inputs": [
                {
                    "appId": "com.webos.app.hdmi1",
                    "name": "Ziggo"
                },
                {
                    "appId": "com.webos.app.hdmi2",
                    "name": "Apple TV"
                },
                {
                    "appId": "com.webos.app.hdmi3",
                    "name": "Playstation"
                },
                {
                    "appId": "netflix",
                    "name": "Netflix"
                },
                {
                    "appId": "youtube.leanback.v4",
                    "name": "YouTube"
                },
                {
                    "appId": "videoland2014",
                    "name": "Videoland"
                }
            ]
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8080,
            "auth": "form",
            "theme": "amber",
            "sudo": true,
            "standalone": true,
            "restart": "sudo -n systemctl restart homebridge homebridge-config-ui-x",
            "temp": "/sys/class/thermal/thermal_zone0/temp",
            "log": {
                "method": "custom",
                "command": "sudo -n journalctl -o cat -n 500 -f -u homebridge -u homebridge-config-ui-x"
            },
            "platform": "config"
        },
        {
            "platform": "DysonPlatform",
            "name": "DysonPlatform",
            "email": "...",
            "password": "...",
            "accessories": [
                {
                    "ip": "Dyson",
                    "displayName": "Dyson",
                    "serialNumber": "...”
                }
            ]
        }
    ]
}
```
