### ISSUE TITLE
Classify notifications triggered by Alexa as such instead of as unknown notifications

### ISSUE THREAD

**Issue by vraicovi** [nfarina/homebridge#1560]
I'm running Homebridge with homebridge-Wink3, homebridge-pivot-power-genius, homebridge-liftmaster2, and homebridge-harmonyhub.  I have my Wink system all connected to Alexa for voice control in the house.  I have loved the functionality that running homebridge has added to my setup, namely triggering certain actions from outside the house and the use of the Home app on iOS.  On to my feature request/question...

If I ask Siri to lock the front door, homebridge shows this:

> [10/16/2017, 6:12:34 PM] [Comus] Sending update: Front Door (lock/141933) { locked: true }
> [10/16/2017, 6:12:34 PM] [Comus] Update sent successfully: Front Door (lock/141933)
> [10/16/2017, 6:12:36 PM] [Comus] Received update notification: Front Door (lock/141933)

Any time I ask Alexa to do something, homebridge shows it as an unknown notification, followed by a 'received update notification.'  Below are two examples - one locking a door and one turning a light on.  Is there something I can do just to have homebridge show that a status update was triggered by Alexa and not show all the extraneous information?  Is this output/logging coming from homebridge or homebridge-wink3?

*** Begin Examples

*** If I ask Alexa to lock the front door, Homebridge shows this:

> [10/16/2017, 5:57:07 PM] [Comus] Received unknown notification: { capabilities:
>    { fields:
>       [ [Object],
>         [Object],
>         [Object],
>         [Object],
>         [Object],
>         [Object],
>         [Object],
>         [Object],
>         [Object],
>         [Object],
>         [Object] ],
>      home_security_device: true,
>      polling_interval: 7200 },
>   created_at: 1489869104,
>   desired_state:
>    { alarm_enabled: true,
>      alarm_mode: null,
>      alarm_sensitivity: 0.6,
>      auto_lock_enabled: false,
>      beeper_enabled: true,
>      key_code_length: 7,
>      locked: true,
>      vacation_mode_enabled: false },
>   device_manufacturer: 'schlage',
>   hidden_at: null,
>   hub_id: '99700',
>   last_reading:
>    { alarm_activated: false,
>      alarm_activated_changed_at: 1503951355.2392585,
>      alarm_activated_updated_at: 1503951355.2392585,
>      alarm_enabled: true,
>      alarm_enabled_updated_at: 1508189025.3123143,
>      alarm_mode: null,
>      alarm_mode_updated_at: 1508189025.3123143,
>      alarm_sensitivity: 0.6,
>      alarm_sensitivity_updated_at: 1508189025.3123143,
>      auto_lock_enabled: false,
>      auto_lock_enabled_updated_at: 1508189025.3123143,
>      battery: 0.98,
>      battery_changed_at: 1508178542.2624984,
>      battery_updated_at: 1508189025.3123143,
>      beeper_enabled: true,
>      beeper_enabled_updated_at: 1508189025.3123143,
>      connection: true,
>      connection_updated_at: 1508189025.3123143,
>      desired_alarm_enabled_changed_at: null,
>      desired_alarm_enabled_updated_at: 1508120128.927852,
>      desired_alarm_mode_changed_at: null,
>      desired_alarm_mode_updated_at: 1508120128.927852,
>      desired_alarm_sensitivity_changed_at: null,
>      desired_alarm_sensitivity_updated_at: 1508120128.927852,
>      desired_auto_lock_enabled_changed_at: null,
>      desired_auto_lock_enabled_updated_at: 1508120128.927852,
>      desired_beeper_enabled_changed_at: null,
>      desired_beeper_enabled_updated_at: 1508120128.927852,
>      desired_key_code_length_changed_at: null,
>      desired_key_code_length_updated_at: 1508120128.927852,
>      desired_locked: true,
>      desired_locked_changed_at: 1508191074.278378,
>      desired_locked_updated_at: 1508191074.278378,
>      desired_vacation_mode_enabled_changed_at: null,
>      desired_vacation_mode_enabled_updated_at: 1508120128.927852,
>      key_code_length: 7,
>      key_code_length_updated_at: 1508189025.3123143,
>      last_error: 'bolt_jammed',
>      last_error_changed_at: 1506466755.1359413,
>      last_error_updated_at: 1508074311.65377,
>      locked: true,
>      locked_changed_at: 1508189025.3123143,
>      locked_updated_at: 1508189025.3123143,
>      vacation_mode_enabled: false,
>      vacation_mode_enabled_updated_at: 1508189025.3123143 },
>   lat_lng: [ ***Changed*** ],
>   linked_service_id: null,
>   local_id: '49',
>   locale: 'en_us',
>   location: '***Changed***',
>   lock_id: '141933',
>   manufacturer_device_id: null,
>   manufacturer_device_model: 'schlage_zwave_lock',
>   model_name: 'BE469',
>   name: 'Front Door',
>   primary_upc_code: 'GENERIC_SCHLAGE_ZWAVE_LOCK',
>   radio_type: 'zwave',
>   subscription:
>    { pubnub:
>       { channel: '0fd7c4c3842f5cad6ca482ade529e236828f304d|lock-141933|user-182912',
>         subscribe_key: 'sub-c-f7bf7f7e-0542-11e3-a5e8-02ee2ddab7fe' } },
>   triggers: [],
>   units: {},
>   upc_code: '043156312214',
>   upc_id: '11',
>   user_ids: [ '182912' ],
>   uuid: '0ccab428-68f8-4a56-b780-e809362fb1df',
>   nonce: '183411357' }
> [10/16/2017, 5:59:32 PM] [Comus] Received update notification: Front Door (lock/141933)
> 
> 

***Here's turning on a light:

> [10/16/2017, 10:06:35 PM] [Comus] Received unknown notification: { binary_switch_id: '379312',
>   capabilities: { fields: [ [Object], [Object] ] },
>   created_at: 1485026657,
>   current_budget: null,
>   desired_state: { powered: true },
>   device_manufacturer: 'ge',
>   gang_id: null,
>   hidden_at: null,
>   hub_id: '99700',
>   last_reading:
>    { connection: true,
>      connection_updated_at: 1508156517.865564,
>      desired_powered: true,
>      desired_powered_changed_at: 1508206041.8767996,
>      desired_powered_updated_at: 1508206041.8767996,
>      powered: false,
>      powered_changed_at: 1508156517.865564,
>      powered_updated_at: 1508156517.865564 },
>   lat_lng: [ null, null ],
>   linked_service_id: null,
>   local_id: '45',
>   locale: 'en_us',
>   location: '',
>   manufacturer_device_id: null,
>   manufacturer_device_model: 'ge_jasco_binary',
>   model_name: 'Binary Switch',
>   name: 'Kitchen Table',
>   order: 0,
>   primary_upc_code: 'JASCO_ZWAVE_BINARY_POWER',
>   radio_type: 'zwave',
>   subscription:
>    { pubnub:
>       { channel: 'ab84a506316807e9edc800b1c07ea228b608dd1d|binary_switch-379312|user-182912',
>         subscribe_key: 'sub-c-f7bf7f7e-0542-11e3-a5e8-02ee2ddab7fe' } },
>   triggers: [],
>   units: {},
>   upc_code: 'JASCO_ZWAVE_BINARY_POWER',
>   upc_id: '200',
>   user_ids: [ '182912' ],
>   uuid: 'e211c63d-7772-46a3-9ac7-f9ae5e0695b0',
>   nonce: '2018035247' }
> [10/16/2017, 10:06:35 PM] [Comus] Received update notification: Kitchen Table (binary_switch/379312)

**Comment by plasticrake** [comment]
You're going to want to bring this up with whatever plugin you're referring to. (Comus?)

**Comment by vraicovi** [comment]
I apologize.  I thought I was on homebridge-wink3, not homebridge, when I posted this.

(Comus is the name of one of my Wink Hubs)

**Comment by christensonautohome** [comment]
did you ever find that these notifications have caused a problem with your setup or just an annoyance with your history on homebridge?  I just started getting these when i upgraded to v2.0

**Comment by vraicovi** [comment]
more annoyance than anything.  I haven't actually noticed them in a while,
but I'll check again when I get home in front of the console.
