### ISSUE TITLE
System Time on home bridge server is incorrect

### ISSUE THREAD

**Issue by daniel2029** [nfarina/homebridge#1561]
The time on my home bridge server is an hour behind the system time (Mac OS). This occurred when Daylight Savings Time started in Australia. The Mac OS time changed by itself but the home bridge console time didn't

How could i change it?

**Comment by NorthernMan54** [comment]
Homebridge doesn’t use or control time, so I’m afraid I don’t understand the question.  Logging will display using time that is all.

**Comment by daniel2029** [comment]
@NorthernMan54 the time is incorrect, it's an hour behind the system time making the time of when the accessory was interacted with incorrect. Say my son unlocked the door at 5, the log will say it was unlocked at 4. I would like to fix that

**Comment by NorthernMan54** [comment]
Can you share a log where your seeing the incorrect time?

As homebridge just uses system time, I’m thinking this is a time zone configuration issue on the machine your running homebridge on.

**Comment by rob0101** [comment]
I just noticed my homebridge logs being one hour behind daylight savings, so I guess this issue still exists.

The correct timezone is ACDT (Australian Central Daylight-Savings Time). GMT +10:30

<img width="284" alt="Screenshot 2023-10-15 at 10 26 03 am" src="https://github.com/homebridge/homebridge/assets/19808721/42d211b9-33cb-49f1-96c9-4571266c3e21">
