### ISSUE TITLE
Simple commands to and from a TCP based device

### ISSUE THREAD

**Issue by DeetAus** [nfarina/homebridge#1563]
I have a TCP based device that I want to send commands to/from Homekit. The commands themselves can be anything I want, and I am able to generate feedback for those commands

Simple ON/OFF is all I need from Homekit

The device can be configured as a client or server, on any port number I want to use

Ideally what I want to be able to do is create a button with a label on the homekit app, and when pressed I get sent that label name to the TCP device. 

It could be called "Garage Door" or "Welcome Home" or "Goodnight" or "Living Room Lamp"
I dont care what kind of device Homekit sees it as. Lock or Lamp (or an option of both) would probably be the simplest solution.

As I mentioned above I can return a string that includes feedback

Plan is to run this on a Pi3 if that makes any difference.

Can this be done in homebridge?

**Comment by tommyd75** [comment]
Have a look at this, I'm using it to send http commands, maybe this would work?

https://github.com/rudders/homebridge-http

**Comment by DeetAus** [comment]
Thanks

I have been trying to get that plugin to work for a few days now. I can get the commands to work, but i am struggling to get the feedback to work. i get parse errors

any hints on how to format the json I send back to homebridge and example on_status would be frontyard/light/on

**Comment by tommyd75** [comment]
I’m using it to show a http light status and I’m just having my home automation software write to a text file with either a 0 for off or a 1 for on. 

The status url portion of my config file just points to that text file. I made a text file for each light and the automation software writes to each file and changes the status by either having a 1 or 0. 
There’s nothing else on that file just a 0 or 1
So your json return should be the same.

**Comment by DeetAus** [comment]
I need to write script to generate to entire json string. I have tied lots of formats, but I am just getting nowhere

What I really need to see is a wireshark of the script that another device sends to the homebridge-http plugin so I can make sure i have all the various json elements in place

0/1 doesnt work

**Comment by mabnz** [comment]
Did you ever find a solution here? I'd also like Homebridge to send data over an arbitrary TCP port to a host.
