### ISSUE TITLE
npm update check failed

### ISSUE THREAD

**Issue by 350d** [nfarina/homebridge#1565]
How to fix this message on every Homebridge start?
````
┌──────────────────────────────────────────────────────────────┐
│                   npm update check failed                    │
│             Try running with sudo or get access              │
│             to the local update config store via             │
│ sudo chown -R $USER:$(id -gn $USER) /home/homebridge/.config │ 
└──────────────────────────────────────────────────────────────┘
````

if I run this command on Pi I have this `chown: cannot access '/home/homebridge/.config': No such file or directory`
Homebridge works as a service on my setup.

**Comment by DYKN5000** [comment]
Same issue

**Comment by prashanthpadala** [comment]
npm version is - 5.0.3 I've also same problem when I use any npm command. npm command is working fine but why this code is showing, I don't know....

I think it was in npm version 5.0.x issue. I updated 5.0.3 to 5.2.0 with this command

sudo chown -R $USER:$(id -gn $USER) /home/prashanth/.config

npm install -g npm
now npm is working fine.

**Comment by pkanyerezi** [comment]
Having the same problem

**Comment by jocamero** [comment]
Also getting this issue.  Any suggestions?

Running on a Pi and using systemd to start.

**Comment by djvolz** [comment]
Also seeing this on a pi using systemd.
