### ISSUE TITLE
Can someone put up a detailed guide or video for installing this on Windows 10

### ISSUE THREAD

**Issue by Dheeraj1712** [nfarina/homebridge#1566]
I am not a tech guy. But i am really impressed by this homebridge concept. However, i am stuck at OpenSSL Installation and other packages and going through lot of errors while installing this in windows 10. It would be great if someone could post a detailed tutorial (possibly a video) for a non tech guy who really wants to implement this in their system.

I own a Broadlink RM Mini. I want to attach it with homebridge.

Thank u!

**Comment by dkrizic** [comment]
Honestly, buy a Raspberry Pi and use one of the many tutorials for installing Homebridge on a Raspberry.

**Comment by toshibochan** [comment]
Definitely use raspberry pi! I use raspberry pi zero, pi zero w, pi 2 and pi 3. Control may garage, RF outlets, nest relays, older Hue, and many other things!  If you don’t want use much money buy raspberry pi zero WiFi on amazon. I think have power supply and pi and case for $24. And you can use 8GB SD card.

**Comment by DarthCruiser** [comment]
Hi @Dheeraj1712 I have some zero cost options for you:- 

 - If you have Windows 10 Professional as I do - Enable Hyper-V and setup a virtual Machine installing Debian Linux. 
 - If you do not have Windows 10 Professional - Install Virtual Box on Windows 10 and do the same thing. 

Googling around - many of the Nodejs/NPM/Homebridge tutorials show the Debian Linux strategy/commands which are sufficiently detailed to enable installation of required Debian base packages in addition to Nodejs/NPM/Homebridge deployment. 

See below the one I used - after installing Debian 9 I just had to install the 'apt' package  - from then on its a simple matter of copy/paste from the tutorials - see below a starter for 10 which includes installation of the HASS Plugin:
 
https://www.youtube.com/watch?v=lFwRfVPgzAQ

At the point of plugin installation switch to the Broadlink RM Mini tutorial and come back to the below to setup Homebridge as a service.

This is enough to get you up and running, but once you have Homebridge installed, it is worth taking 5 and having a trawl through the Github/NPM stuff and have a think about the wider strategy for future proofing your plugin structure. You may choose to run several discrete instances of Homebridge simultaneously to manage the risk/impact of plugin crashes, or simply to multiply the 99 accessory limit, or just have an additional instance running to play with plugins you think may be useful.

All the best.
