### ISSUE TITLE
Can't connect with more than 1 device to homebridge

### ISSUE THREAD

**Issue by maddhin** [nfarina/homebridge#1568]
Hi,

I have an iPhone6 with iOS11 and an iPhone7 with iOS10 but I can only connect one of the devices! I run the latest version of Homebridge on ArchLinux on a RPi (and FHEM).

Once I connected one of those devices, the other one cannot find Homebridge anymore and even stops connecting when trying to add the devices at the same time. 

I can "reset" Homebridge by changing the user id in the config and erasing the persist folder and add one or the other again but this behavior is really annoying. 

Does anybody have a solution for that?

Many thanks in advance!

**Comment by plasticrake** [comment]
You add Homebridge to your "Home" and then you share your "Home" in iOS to your other devices. You don't connect Homebridge to multiple devices.

**Comment by maddhin** [comment]
Interesting... I will try to figure this out. That ‚sharing‘ works across accounts? Say I share my „Home“ with my wife then so she can access? 

Seems to be a bit complicated system or just RTFM? Is that documented?

**Comment by maddhin** [comment]
K & cheers for the help, I tried „fixing“ this for days... 
If possible maybe add a link to the HomeKit stuff in the docu so dummies/noobs like me can find answers;)

**Comment by lixmch** [comment]
homebridge on archlinux(armhf)   HOW to do? 
pacman -S python git libavahi-compat-libdnssd-dev
error: you cannot perform this operation unless you are root.
[android@localhost ~]$ pacman -S libavahi-compat-libdnssd-dev
error: you cannot perform this operation unless you are root.
