### ISSUE TITLE
Siri unable to lock door locks, she always unlocks instead 

### ISSUE THREAD

**Issue by Krillle** [nfarina/homebridge#1569]
When asking Siri to lock a door, the lock is always opened instead of locked. Nevertheless voice feedback, is "Ok, door is locked." Locking same door via HomeApp works fine.

Not sure if this is a homebridge issue. Hard to say where the issue is in the chain of systems. 
Same process with Homebridge, NUKI Plugin and NUKI lock is reported to work fine.

My System-Setup: 
iPhone 7, iOS 11.0.3, Siri in German localization
homebridge-fibaro-hc2 Plugin, v2.0.6
homebridge, v0.4.27
Fibaro HC2, v4.140
Danalock V3 Z-Wave, v1.2

German Siri command "Verriegele die Wohnungstür" (Lock the flat door)
Siri reply "Ok, das Gerät 'Wohnungstür' ist abgeschlossen" (ok, device 'flat door' is locked)
Homebridge Output:
Oct 20 11:42:15 raspberrypi homebridge[10197]: [10/20/2017, 11:42:15 AM] [FibaroHC2] Setting value to device:  273  parameter: Lock Target State
Oct 20 11:42:15 raspberrypi homebridge[10197]: [10/20/2017, 11:42:15 AM] [FibaroHC2] Command:  unsecure, value: 0, to: 273

Issue might be in relation to issue #922

**Comment by maragelis** [comment]
0.4.28 resolved the issue you are having with locks.

**Comment by Krillle** [comment]
Yes indeed. Thanks for the hint.

**Comment by Krillle** [comment]
Yes indeed. Thanks for the hint.
0.4.28 resolved the issue.
