### ISSUE TITLE
Version check breaks homebridge updated to version higher that required by plugins

### ISSUE THREAD

**Issue by oglodyte** [nfarina/homebridge#1571]
Version 0.4.29 hardcodes working dir to be ~/.homebridge that breaks service configuration suggested [here](https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi#running-homebridge-on-bootup-systemd)

**Comment by oglodyte** [comment]
Oops. My bad. Must be something else. That was just for default dir.  Have these errors after  upgrading: 

> Error: Plugin /usr/lib/node_modules/homebridge-hue requires a HomeBridge version of 0.4.28 which does not satisfy the current HomeBridge version of 0.4.29. You may need to upgrade your installation of HomeBridge.

What does that mean?..

**Comment by oglodyte** [comment]
Strange it showed up on 0.4.29. Looks like it is older code that requires exact version match and throws error if homebridge version is **higher** that required by plugins. Does that make sense? Should it throw error only for lower homebridge version?  (and maybe warning if higher) Otherwise what would be update procedure? Wait till all plugins update before updating homebridge?

**Comment by oglodyte** [comment]
Looks like few plugins (homebridge-hue and homebridge-zp) recently started to put exact homebridge version (instead of higher than) for dependency..  So is it plugin's problem then?  Or homebridge better do warning and leave the check to plugins?..

**Comment by KhaosT** [comment]
Huh interesting, I wonder why those plugins put a fixed version there... Maybe it should be a warning if the version is higher and fault crash if it's lower?

**Comment by ebaauw** [comment]
> I wonder why those plugins put a fixed version there.

Because that’s the version I develop and test against.  See also https://github.com/nfarina/homebridge/pull/1541.

> Maybe it should be a warning if the version is higher and fault crash if it's lower?

Maybe.  That still won’t solve the issue of different plugins requiring different versions...

**Comment by KhaosT** [comment]
@ebaauw I think the correct way here is to have plugin define a minimal version it needs, and then the check logic would make sense.

**Comment by ebaauw** [comment]
> I think the correct way here is to have plugin define a minimal version it needs

@KhaosT: will do.

**Comment by oglodyte** [comment]
Thank you!
