### ISSUE TITLE
SMS ON OFF GSM WEBASTO HEATING

### ISSUE THREAD

**Issue by muchskywoker** [nfarina/homebridge#1572]
Hi,

I have a question, is it possible to somehow send text message from my phone using homebridge? For example i have GSM module in my car connected to WEBASTO HEATING system. It is turn on and off by sending text message "on" and "off". 

Now the question is can I do this by homebridge and how?

**Comment by dkrizic** [comment]
You will not get this out-of-the box, but you can use a plugin that executes a local command like [homebridge-cmdswitch2](https://github.com/luisiam/homebridge-cmdswitch2) and then you need a CLI tool that is able to send an SMS like [Gammu](https://wammu.eu/gammu/). I used Gammu for long time, it requires a local USB-Stick that provides GSM.

**Comment by filippocobelli** [comment]
Hi I'm trying to to this trick. Could you explain me how to make work cmd switch 2 and gammu together. thanks a lot
