### ISSUE TITLE
Weird behavior after /characteristics

### ISSUE THREAD

**Issue by Radstake** [nfarina/homebridge#1574]
When I have successfully curled /characteristics and switch off a light, eg:

`curl -X PUT http://localhost:51826/characteristics --header "Content-Type:Application/json" --header "authorization: 031-45-154" --data "{\"characteristics\":[{\"aid\":33,\"iid\":10,\"value\":false}]}"`

It only turns off the specific light, so that's good. But in the homekit app or eve, all the devices are visually set to off in the interface, they are still on, but appear off.

**Comment by NorthernMan54** [comment]
Sorry your wording is rough, what are you asking?

Also, I think your false should be a 0 for it to work correctly

**Comment by Radstake** [comment]
Sorry not intended. What happens is that the light is turn off, but according to the homekit app, all the lights went off, but thats not true.

> Op 27 okt. 2017 om 04:28 heeft NorthernMan54 <notifications@github.com> het volgende geschreven:
> 
> Sorry your wording is rough, what are you asking?
> 
> Also, I think your false should be a 0 for it to work correctly
> 
> Sent from my iPad
>

**Comment by Radstake** [comment]
0, instead of false, did the trick
