### ISSUE TITLE
Path to plugins?

### ISSUE THREAD

**Issue by Rubenfer** [nfarina/homebridge#1579]
Hi everyone.

Where can I find the path to the installed plugins to modify it?

Another question is that someone know a plugin for Nest that not is homebridge-nest (it don't work)

Thanks in advance!

**Comment by plasticrake** [comment]
That is entirely dependent on your [node installation and setup](https://docs.npmjs.com/files/folders). You can use the `-P` option as documented in the README to add additional plugin folders for homebridge to use.
