### ISSUE TITLE
Home app no longer finds the bridge

### ISSUE THREAD

**Issue by jack-hub** [nfarina/homebridge#1581]
All devices went non-responsive. Found homebridge to be running fine with no errors. Stopped and restarted it anyway and no luck. Deleted the homebridge from the Home app and tried to re-add it and it won't find it. Changed the username, pin, and both -- still no luck.

Again, Homebridge starts up and runs fine. Home app isn't seeing it.

**Comment by mondelus** [comment]
I'm having the same issue

**Comment by ronaldvans** [comment]
I am experiencing the same problem. Homebridge is running, I see the changes but the Home app losses connection after a while. Running the latest version 0.4.29 and 1 plugin (homebridge-hue) installed.

**Comment by arakian** [comment]
I have the same problem! First time config its ok but if I shut down or restart Homebridge Home app don't work.

**Comment by ronaldvans** [comment]
Here's some output from syslog:

EventedHTTPServer [::ffff:192.168.2.231] New connection from client
EventedHTTPServer [::ffff:192.168.2.231] HTTP server listening on port 42175
EventedHTTPServer [::ffff:192.168.2.231] HTTP request: /pair-verify
HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify
EventedHTTPServer [::ffff:192.168.2.231] HTTP Response is finished
EventedHTTPServer [::ffff:192.168.2.219] New connection from client
EventedHTTPServer [::ffff:192.168.2.219] HTTP server listening on port 35249
EventedHTTPServer [::ffff:192.168.2.231] Client connection closed
EventedHTTPServer [::ffff:192.168.2.231] HTTP connection was closed
EventedHTTPServer [::ffff:192.168.2.231] HTTP server was closed
EventedHTTPServer [::ffff:192.168.2.219] HTTP request: /pair-verify
HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify
EventedHTTPServer [::ffff:192.168.2.219] HTTP Response is finished
EventedHTTPServer [::ffff:192.168.2.219] Client connection closed
EventedHTTPServer [::ffff:192.168.2.219] HTTP connection was closed
EventedHTTPServer [::ffff:192.168.2.219] HTTP server was closed

**Comment by aguedob** [comment]
Also me. Same symptoms and after deleting accessories and persist folders, changing username and ping. Homebridge working but not detected by Home app in two different devices with two different Apple accounts :(

**Comment by sieren** [comment]
Probably related: https://github.com/nfarina/homebridge/issues/1528

I noticed this on multiple occasions (with both homebridge and my other HAP-NodeJS installation, which homebridge is based on). Deleting the `persist` folder usually fixes it, but it's annoying as I have to rebuilt my configuration in the Home app.

syslog messages are the same as @ronaldvans - leading me to believe the initial verification/encryption/handshake data is corrupted somehow.

**Comment by SJNix** [comment]
I'm having the same issue, has anyone been able to find a fix?

**Comment by jack-hub** [comment]
This did it for me:

1. Stop Homebridge in Terminal and Exit
2. Delete the persist folder
3. Kill the home app
4. Restart Homebridge and check the Home App
If this does not fix it, repeat steps 1-3 and then:
5. Change any character in the username and pin section to the config.json.
6. Restart Homebridge and check the Home App
If this does not fix it, repeat steps 1-2 and then:
7. Delete Homebridge out of the Home App (Warning. You're starting over in the Home App. Room names and pictures remain, but assignments and automations are all gone.)
8. Kill the Home app.
9. Restart Homebridge and check the Home App.

I had to go to through all of these steps. In the past, sometimes 1-4 worked for me. It has been up for two or three days now.

**Comment by aguedob** [comment]
I did this process several times but didn’t work. Finally, I remove everything from the Home App, kill the app and reset all settings in my homebridge. I wait several hours before trying again and it worked! Just remove it, and be patient before adding it again :) It should be an iCloud issue.

**Comment by DiMarcello77** [comment]
Hello All, I had this same issue and I solved it today. homebridge was found but all accesoires where 'Not Responding' 

I thought it was because of an IOS 11 update first but after completely removing / reinstalling my PI3 with homebridge the issue was still there. I googled a lot and in my case my router (Netgear Orbi) had this multicast feature set to **disabled**: 

_Disable IGMP Proxying. IGMP proxying allows a computer on the local area network (LAN) to receive the multicast traffic it is interested in from the Internet._

After enabling this multicast feature and rebooting the router it was completely running fine again!

It's unknown to me why this setting was disabled but now it is working like a charm again :-) 

Keep up the good work nfarina! I love homebridge!

**Comment by snizzleorg** [comment]
same issue here. re-added and it worked for a day or so. now iOS doesn't find home bridge anymore.

My router has no way of turning disabling IGMP.

**Comment by DiMarcello77** [comment]
OK so new update here from me after disabling IGMP it worked for a 1,5 day and got the problem again. So the status now is that Siri works and automation in the iOS home app also works. But most of the accessoires are not responding again. 

I am completely surprised and do not know what exactly the problem is and how to resolve it. I have tried with downgrading and upgrading my router and IGMP settings but it does not impact the result. So again Siri commands seem to work but the Home app accessoires cannot (most of them) be controlled. Homebridge on my raspberry pi is working fine without errors in the logs.

any suggestions?

**Comment by snizzleorg** [comment]
I deleted the persist folder and re-added homebridge on my iPhone

better than here. For me it worked only about 30 min...


logs of homebridge look fine, gets the updates from home-assistant just no mention of any iOS device...

**Comment by snizzleorg** [comment]
I somehow suspect the appletv to be part of the problem... not sure if and why. But I will try with the appletv disconnected. Do you have appleTV?

**Comment by ilovehotmilk** [comment]
@DiMarcello77 I got the same issue,How did you connect pi3 to the router? I use wifi. Homebridge on my raspberry pi3 got the error in /var/log/homebridge.err like this:
EventedHTTPServer [::ffff:192.168.2.219] HTTP Response is finished
EventedHTTPServer [::ffff:192.168.2.219] Client connection closed
EventedHTTPServer [::ffff:192.168.2.219] HTTP connection was closed
EventedHTTPServer [::ffff:192.168.2.219] HTTP server was closed

**Comment by DiMarcello77** [comment]
Hi, I use LAN cable but also tested with Wifi. I have also experienced the above messages!

**Comment by DiMarcello77** [comment]
I do not have the apple TV but using my ipad air 2 as home hub. I tried with disable and enable this but did not solve any problem.

**Comment by snizzleorg** [comment]
Update from my side. Without the appleTV (I unplugged them) I have had no problems fro the last 3 days. I will keep it running for a few more days and then plug the appleTV back in and see what happens...

**Comment by ilovehotmilk** [comment]
When I use LAN cable,the problem seemed to be sloved. I hope this method works

**Comment by mondelus** [comment]
seems like homebridge is not a dependable source
