### ISSUE TITLE
Homebridge Multiple Platforms issue

### ISSUE THREAD

**Issue by RickHOZ** [nfarina/homebridge#1582]
Hi All,

I keep reading how everybody else solved this issue but I can't seem to get mine to work. Please see copy of complete config.json file pasted below. Any help appreciated.

p.s. The issue always seems to occur between the two platforms.

```json
{
  "bridge": {
    "name": "Samara",
    "username": "CC:22:3D:E3:CE:30",
    "port": 51826,
    "pin": "031-45-154"
  },

  "description": "My home HomeKit API configuration file",

  "platforms": [
    {
      "platform": "ElkM1",
      "name": "ElkM1",
      "elkAddress": "192.168.1.2",
      "elkPort": "2101",
      "area": "1",
      "keypadCode": "0000",
      "zoneTypes": {
      "1": "contact",
      "2": "contact",
      "3": "contact",
      "4": "contact",
      "5": "motion",
      "6": "motion",
      "7": "motion",
      "8": "motion",
      "openOutput":"11",
      "closeOutput":"11",
      "name":"Garage door"
                  },
                  {
      "platform": "homebridge-cbus.CBus",
      "name": "CBus",
      "client_ip_address": "127.0.0.1",
      "client_controlport": 20023,
      "client_cbusname": "SAMARA",
      "client_network": 254,
      "client_application": 56,
      "client_debug": true,

      "platform_export": "/Users/SamaraServer/.homebridge/samara_platform.json",
    }
    ]
  }

      "accessories": [
        { "type": "light", "id": 11, "name": "Office lights" },
        { "type": "light", "id": 12, "name": "Office Store"},
        { "type": "light", "id": 74, "name": "AirCon Office"},
        { "type": "light", "id": 13, "name": "Office Toilet"},
        { "type": "dimmer", "id": 18, "name": "Office Hall"},
        { "type": "light", "id": 50, "name": "Office Toilet Exhaust Fan"},


        { "type": "dimmer", "id": 1, "name": "Master Bedroom"},
        { "type": "light", "id": 75, "name": "Master Suite AirCon"},
        { "type": "shutter", "id": 63, "name": "Master Suite Shear", "invert": "false"},
        { "type": "shutter", "id": 64, "name": "Master Suite Curtain", "invert": "false"},
        { "type": "light", "id": 2, "name": "Master Suite Feature"},
        { "type": "dimmer", "id": 3, "name": "Master Suite Ensuite"},
        { "type": "light", "id": 4, "name": "Master Suite Ensuite Mirror"},
        { "type": "dimmer", "id": 5, "name": "Master Suite Toilet"},
        { "type": "light", "id": 6, "name": "Master Suite Robe"},
        { "type": "light", "id": 48, "name": "Master Suite Ensuite Exhaust Fan"},
        { "type": "light", "id": 49, "name": "Master Suite Toilet Exhaust Fan"},
        { "type": "light", "id": 83, "name": "Master Suite Windows Close"},
        { "type": "light", "id": 144, "name": "Master Suite Windows Open)"},


        { "type": "dimmer", "id": 7, "name": "Retreat"},
        { "type": "dimmer", "id": 8, "name": "Retreat Cove"},
        { "type": "dimmer", "id": 9, "name": "Retreat Stairs"},
        { "type": "light", "id": 76, "name": "AirCon Retreat"},
        { "type": "light", "id": 145, "name": "Retreat Feature"},



        { "type": "dimmer", "id": 15, "name": "Media Room"},
        { "type": "dimmer", "id": 16, "name": "Media Cove"},
        { "type": "light", "id": 73, "name": "AirCon Media"},


        { "type": "dimmer", "id": 21, "name": "Kitchen"},
        { "type": "light", "id": 22, "name": "Kitchen Benches"},
        { "type": "light", "id": 71, "name": "AirCon Kitchen"},
        { "type": "light", "id": 86, "name": "Kitchen Bulkhead"},


        { "type": "light", "id": 23, "name": "Scullery"},


        { "type": "dimmer", "id": 24, "name": "Dining Room"},
        { "type": "light", "id": 10, "name": "House Features"},


        { "type": "dimmer", "id": 26, "name": "Lounge"},
        { "type": "light", "id": 72, "name": "AirCon Lounge"},
        { "type": "light", "id": 85, "name": "Fireplace"},

        { "type": "dimmer", "id": 40, "name": "Sala Treatment Room"},
        { "type": "dimmer", "id": 38, "name": "Sala"},
        { "type": "light", "id": 39, "name": "Sala Feature"},
        { "type": "light", "id": 56, "name": "Sala Bathroom Exhaust Fan"},


        { "type": "light", "id": 35, "name": "Laundry"},
        { "type": "light", "id": 36, "name": "Laundry Store"},
        { "type": "light", "id": 37, "name": "Laundry Clothesline"},
        { "type": "dimmer", "id": 19, "name": "Laundry Hall"},
        { "type": "light", "id": 110, "name": "Externals Rear and Clothesline"},


        { "type": "light", "id": 45, "name": "Pool Pump Room"},
        { "type": "light", "id": 46, "name": "Wine Cellar"},


        { "type": "light", "id": 67, "name": "Fountain"},
        { "type": "light", "id": 68, "name": "Garden Lighting"},
        { "type": "light", "id": 69, "name": "Green Garden Lights"},
        { "type": "light", "id": 58, "name": "Pond Light"},
        { "type": "light", "id": 57, "name": "Pond Pump"},


        { "type": "light", "id": 70, "name": "Pool Lights"},
        { "type": "light", "id": 62, "name": "Pool Spa Blower"},
        { "type": "light", "id": 43, "name": "Deck Pool"},
        { "type": "light", "id": 60, "name": "Pool Pump"},
        { "type": "light", "id": 61, "name": "Pool Spa Pump"},



        { "type": "dimmer", "id": 28, "name": "Bridge Suite"},
        { "type": "dimmer", "id": 29, "name": "Bridge Suite Ensuite"},
        { "type": "light", "id": 30, "name": "Bridge Suite Ensuite Mirror"},
        { "type": "light", "id": 77, "name": "Bridge Suite AirCon"},
        { "type": "light", "id": 44, "name": "Bridge Suite Deck"},
        { "type": "light", "id": 53, "name": "Bridge Suite Ensuite Exhaust Fan"},
        { "type": "light", "id": 66, "name": "Bridge Suite AV Features"},


        { "type": "dimmer", "id": 31, "name": "Kingfisher Bed"},
        { "type": "light", "id": 78, "name": "Kingfisher Bed AirCon"},

        { "type": "dimmer", "id": 32, "name": "Kingfisher lounge"},
        { "type": "light", "id": 79, "name": "Kingfisher Lounge AirCon"},

        { "type": "dimmer", "id": 33, "name": "Bathroom Kingfisher"},
        { "type": "light", "id": 54, "name": "Bathroom Exhaust Fan Kingfisher"},
        { "type": "dimmer", "id": 34, "name": "Kingfisher Toilet"},
        { "type": "light", "id": 55, "name": "Kingfisher Toilet Exhaust Fan"},

        { "type": "dimmer", "id": 20, "name": "Guest Hall"},


        { "type": "light", "id": 47, "name": "Portico"},
        { "type": "switch", "id": 80, "name": "Front Door Open", "activeDuration": "5s"},
        { "type": "light", "id": 87, "name": "Chandelier"},
        { "type": "light", "id": 25, "name": "Foyer"},

        { "type": "switch", "id": 105, "name": "Front Gate Open", "activeDuration": "100ms"},
        { "type": "switch", "id": 103, "name": "Garage Door Open", "activeDuration": "100ms"},
        { "type": "light", "id": 14, "name": "Garage"},

        { "type": "light", "id": 52, "name": "Solar Hot Water Boost"},

        { "type": "dimmer", "id": 112, "name": "Lounge Feature 1"},
        { "type": "dimmer", "id": 113, "name": "Lounge Feature 2"}
      ]
    }
  ],
  "accessories": [ ]
}
```

**Comment by plasticrake** [comment]
I edited your comment to add [code blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/) for easy reading.

There are a few issues here, your file is long so hard to list them all out. A few things:
On line 19  zoneTypes is opened with `{` but it's not closed at the right place. The file has dangling commas a few areas. There is a duplicate `accessories` at the bottom etc.

Use a good text editor that can validate/beautify your JSON to see these. or a web tool like: https://jsonformatter.curiousconcept.com/

**Comment by RickHOZ** [comment]
Hi plasticcrake, thanks for your time.

I had been using ATOM and jsonlint but could not work out the issues. I have now had a look at your comments and made some adjustments which supposedly give me clean code but now when I try to load it on the server I get the following errors.

![screen shot 2017-10-31 at 8 56 53 am](https://user-images.githubusercontent.com/33169283/32199710-7c3f6028-be19-11e7-8f2a-0fe3220279b1.png)

Please see new (cleaned on https://jsonformatter.curiousconcept.com) config.json file below. As always any help would be appreciated.

Rick

{
  "bridge": {
    "name": "Samara",
    "username": "CC:22:3D:E3:CE:30",
    "port": 51826,
    "pin": "031-45-154"
  },

  "description": "My home HomeKit API configuration file",

  "platforms": [
    {
      "platform": "ElkM1",
  			"name": "ElkM1",
  			"elkAddress": "192.168.1.2",
  			"elkPort": "2101",
  			"area": "1",
  			"keypadCode": "3733",
        "zoneTypes": {
                "4": "contact",
                "5": "contact",
                "6": "contact",
                "7": "contact",
                "8": "motion",
                "9": "motion",
                "10": "motion",
                "11": "motion"
  			},
  			"garageDoors": [{
  				"stateZone": "2",
  				"openOutput": "11",
  				"closeOutput": "11",
  				"name": "Garage door"
  			}]
  		},
  		{
      "platform": "homebridge-cbus.CBus",
      "name": "CBus",
      "client_ip_address": "127.0.0.1",
      "client_controlport": 20023,
      "client_cbusname": "SAMARA",
      "client_network": 254,
      "client_application": 56,
      "client_debug": true,

      "platform_export": "/Users/SamaraServer/.homebridge/samara_platform.json",

      "accessories": [
        { "type": "light", "id": 11, "name": "Office lights" },
        { "type": "light", "id": 12, "name": "Office Store"},
        { "type": "light", "id": 74, "name": "AirCon Office"},
        { "type": "light", "id": 13, "name": "Office Toilet"},
        { "type": "dimmer", "id": 18, "name": "Office Hall"},
        { "type": "light", "id": 50, "name": "Office Toilet Exhaust Fan"},


        { "type": "dimmer", "id": 1, "name": "Master Bedroom"},
        { "type": "light", "id": 75, "name": "Master Suite AirCon"},
        { "type": "shutter", "id": 63, "name": "Master Suite Shear", "invert": "false"},
        { "type": "shutter", "id": 64, "name": "Master Suite Curtain", "invert": "false"},
        { "type": "light", "id": 2, "name": "Master Suite Feature"},
        { "type": "dimmer", "id": 3, "name": "Master Suite Ensuite"},
        { "type": "light", "id": 4, "name": "Master Suite Ensuite Mirror"},
        { "type": "dimmer", "id": 5, "name": "Master Suite Toilet"},
        { "type": "light", "id": 6, "name": "Master Suite Robe"},
        { "type": "light", "id": 48, "name": "Master Suite Ensuite Exhaust Fan"},
        { "type": "light", "id": 49, "name": "Master Suite Toilet Exhaust Fan"},
        { "type": "light", "id": 83, "name": "Master Suite Windows Close"},
        { "type": "light", "id": 144, "name": "Master Suite Windows Open)"},


        { "type": "dimmer", "id": 7, "name": "Retreat"},
        { "type": "dimmer", "id": 8, "name": "Retreat Cove"},
        { "type": "dimmer", "id": 9, "name": "Retreat Stairs"},
        { "type": "light", "id": 76, "name": "AirCon Retreat"},
        { "type": "light", "id": 145, "name": "Retreat Feature"},



        { "type": "dimmer", "id": 15, "name": "Media Room"},
        { "type": "dimmer", "id": 16, "name": "Media Cove"},
        { "type": "light", "id": 73, "name": "AirCon Media"},


        { "type": "dimmer", "id": 21, "name": "Kitchen"},
        { "type": "light", "id": 22, "name": "Kitchen Benches"},
        { "type": "light", "id": 71, "name": "AirCon Kitchen"},
        { "type": "light", "id": 86, "name": "Kitchen Bulkhead"},


        { "type": "light", "id": 23, "name": "Scullery"},


        { "type": "dimmer", "id": 24, "name": "Dining Room"},
        { "type": "light", "id": 10, "name": "House Features"},


        { "type": "dimmer", "id": 26, "name": "Lounge"},
        { "type": "light", "id": 72, "name": "AirCon Lounge"},
        { "type": "light", "id": 85, "name": "Fireplace"},

        { "type": "dimmer", "id": 40, "name": "Sala Treatment Room"},
        { "type": "dimmer", "id": 38, "name": "Sala"},
        { "type": "light", "id": 39, "name": "Sala Feature"},
        { "type": "light", "id": 56, "name": "Sala Bathroom Exhaust Fan"},


        { "type": "light", "id": 35, "name": "Laundry"},
        { "type": "light", "id": 36, "name": "Laundry Store"},
        { "type": "light", "id": 37, "name": "Laundry Clothesline"},
        { "type": "dimmer", "id": 19, "name": "Laundry Hall"},
        { "type": "light", "id": 110, "name": "Externals Rear and Clothesline"},


        { "type": "light", "id": 45, "name": "Pool Pump Room"},
        { "type": "light", "id": 46, "name": "Wine Cellar"},


        { "type": "light", "id": 67, "name": "Fountain"},
        { "type": "light", "id": 68, "name": "Garden Lighting"},
        { "type": "light", "id": 69, "name": "Green Garden Lights"},
        { "type": "light", "id": 58, "name": "Pond Light"},
        { "type": "light", "id": 57, "name": "Pond Pump"},


        { "type": "light", "id": 70, "name": "Pool Lights"},
        { "type": "light", "id": 62, "name": "Pool Spa Blower"},
        { "type": "light", "id": 43, "name": "Deck Pool"},
        { "type": "light", "id": 60, "name": "Pool Pump"},
        { "type": "light", "id": 61, "name": "Pool Spa Pump"},



        { "type": "dimmer", "id": 28, "name": "Bridge Suite"},
        { "type": "dimmer", "id": 29, "name": "Bridge Suite Ensuite"},
        { "type": "light", "id": 30, "name": "Bridge Suite Ensuite Mirror"},
        { "type": "light", "id": 77, "name": "Bridge Suite AirCon"},
        { "type": "light", "id": 44, "name": "Bridge Suite Deck"},
        { "type": "light", "id": 53, "name": "Bridge Suite Ensuite Exhaust Fan"},
        { "type": "light", "id": 66, "name": "Bridge Suite AV Features"},


        { "type": "dimmer", "id": 31, "name": "Kingfisher Bed"},
        { "type": "light", "id": 78, "name": "Kingfisher Bed AirCon"},

        { "type": "dimmer", "id": 32, "name": "Kingfisher lounge"},
        { "type": "light", "id": 79, "name": "Kingfisher Lounge AirCon"},

        { "type": "dimmer", "id": 33, "name": "Bathroom Kingfisher"},
        { "type": "light", "id": 54, "name": "Bathroom Exhaust Fan Kingfisher"},
        { "type": "dimmer", "id": 34, "name": "Kingfisher Toilet"},
        { "type": "light", "id": 55, "name": "Kingfisher Toilet Exhaust Fan"},

        { "type": "dimmer", "id": 20, "name": "Guest Hall"},


        { "type": "light", "id": 47, "name": "Portico"},
        { "type": "switch", "id": 80, "name": "Front Door Open", "activeDuration": "5s"},
        { "type": "light", "id": 87, "name": "Chandelier"},
        { "type": "light", "id": 25, "name": "Foyer"},

        { "type": "switch", "id": 105, "name": "Front Gate Open", "activeDuration": "100ms"},
        { "type": "switch", "id": 103, "name": "Garage Door Open", "activeDuration": "100ms"},
        { "type": "light", "id": 14, "name": "Garage"},

        { "type": "light", "id": 52, "name": "Solar Hot Water Boost"},

        { "type": "dimmer", "id": 112, "name": "Lounge Feature 1"},
        { "type": "dimmer", "id": 113, "name": "Lounge Feature 2"}
      ]
      },
      {
        "accessories": [ ]
        }]}

**Comment by plasticrake** [comment]
@RickHOZ , again it makes it easier to read if you use  [code blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/). In the future please use them.

Since the issue is happening with the Cbus plugin you may want to ask them.

**Comment by RickHOZ** [comment]
Hi Patrick, Sorry about that, still very much in the learning phase.

Ill have a look at the code blocks instructions and try and implement.
