### ISSUE TITLE
Cannot Change Existing Accessory DisplayName

### ISSUE THREAD

**Issue by washcroft** [nfarina/homebridge#1585]
Hello,
Once an accessory is registered (under a platform) it doesn't appear possible to change it's display name without fully unregistering it and then readding it.

An accessories' display name isn't shown anywhere in the Home app, but other HomeKIt apps do display it.

Here's what I've tried (and then later adding/removing services to force through a config update to HAP/HomeKit).

```
this.platformAccessory.displayName = newDisplayName;
this.platformAccessory._associatedHAPAccessory.displayName = newDisplayName;

var accessoryInformationService = this.platformAccessory.getService(Service.AccessoryInformation) || this.platformAccessory.addService(Service.AccessoryInformation));

(accessoryInformationService.getCharacteristic(Characteristic.Name) || accessoryInformationService.addCharacteristic(Characteristic.Name)).setValue(newDisplayName);
```

**Comment by washcroft** [comment]
This may be a HomeKit issue, I'm fairly certain it pulls the accessory name from Service.AccessoryInformation, and that is changing successfully with the above code.

**Comment by graanco** [comment]
I hate to chime in but did anyone figure this out??
