### ISSUE TITLE
Safe to update to tvOS 11?

### ISSUE THREAD

**Issue by siavashvj** [nfarina/homebridge#1586]
My Apple TV is on tvOS 10 and my iOS devices are on iOS11. Everything regarding HomeBridge works smoothly. 

However, I really need to update my Apple TV to tvOS11, but I fear that it will mess up my HomeBridge installation. 

When tvOS 11 was in beta, I tried it once, but ran into lots of problems and ultimately rolled back my Apple TV to tvOS10. 

I'm wondering if anyone knows if the problems that existed during the tvOS 11 beta period have been solved in the lates versions of HomeBridge? Is it safe to upgrade to tvOS 11 now?

**Comment by oznu** [comment]
I upgraded mine with no issues.

**Comment by macbisho** [comment]
I can say that beta 11.1 and 11.2 on tvOS has utterly broken HomeKit on my atv. 

I no longer am able to like to HomeKit. 

TvOS 11 release version is fine. Or at least, it was.

**Comment by macbisho** [comment]
Link to HomeKit. Not like.

**Comment by macjeff** [comment]
Working fine for us

**Comment by Uweklaus** [comment]
My apple TV 4 with tvOS 11 works fine with homebridge on a Pi3
