### ISSUE TITLE
Minimum Node Version?

### ISSUE THREAD

**Issue by plasticrake** [nfarina/homebridge#1587]
@nfarina  I don't see any clear documentation on the minimum node version required. Would be great to add this to the Installation section of the README (and update package.json)

- package.json says v4.3.2
- @KhaosT says v5.10 [here](https://github.com/nfarina/homebridge/issues/889)

**Comment by KhaosT** [comment]
@plasticrake I believe node 4.x worked again after someone submitted a change to accommodate both type of buffer init.

**Comment by roe1974** [comment]
i use 8.4.0 without any problems....

**Comment by plasticrake** [comment]
Thanks @KhaosT, I just submitted PR #1590 to add this to the readme.
