### ISSUE TITLE
How to store and handle Setup ID in homebridge?

### ISSUE THREAD

**Issue by nhyjq** [nfarina/homebridge#1588]
There is a new concept: Setup ID in the newest specification. it helps us to combine a QRCode, so user can pair accessory quickly by scanning QRCode in Home App(iOS 11).
Does anybody know how to store or handle a setup id in homebridge? I've tried to generate a random setup id and combine a QRCode with other elements, then Home App recognised  it, but pairing failed finally.
Thank you very much.

@KhaosT @nfarina

**Comment by KhaosT** [comment]
Homebridge currently don't support Setup ID.

**Comment by nhyjq** [comment]
Thank you KhaosT, Is there any development plan or idea about it?

**Comment by KhaosT** [comment]
Any suggestion on how to present a QR code in terminal?

**Comment by nnmalex** [comment]
Two options:
1. Something like https://www.npmjs.com/package/qrcode-terminal
2. Bring up simple http server and give a link via the terminal

**Comment by pdlove** [comment]
@nhyjq The Setup ID becomes the sh value on the MDNS entry that IOS uses to make sure it's picking the correct HomeKit device. I think that in order to make this work the QR string would need to be generated by HAP-NodeJS and passed to homebridge for the actual display of it as a QR code. Display could be through qrcode-terminal or some other mechanism... HAP-NodeJS would simply be generating the value that was used.
One thing I don't know is SetupID has to persist or if it can be a different value with every execution.

**Comment by nhyjq** [comment]
As mentioned in specification, Setup ID is persistent across reboots and factory reset and unique for each accessory instance.
If test in linux/Rasberry Pi, QR Code could be displayed by qrcode-terminal. QR string is just a setup payload string based on X-HM URI

**Comment by pdlove** [comment]
Ok... I guess the better way to put it is that the SetupID is SUPPOSED to persist. I don't know if it is REQUIRED to. I suppose that for initial testing it doesn't really matter.  We probably need to add it as a config option in Homebridge's config.json and simply provide a way to pass it to HAP-NodeJS. Have you made a simply function to generate the QR string yet? I'd rather not have to write it if someone else already has. :)

**Comment by nhyjq** [comment]
I've written a python version, please allow me transfer to js, wait for a moument, please.

**Comment by nhyjq** [comment]
'use strict'

var bases = require('bases/bases');
var bignum = require('bignum');

var HAP_TYPE_IP = 0;
var HAP_TYPE_BLE = 1;
var HAP_TYPE_IP_WAC = 2;

var ACCESSORY_CATEGORY_BRIDGES = 2;

function generate_setup_payload_uri(category_id, hap_type, setup_code, setup_id) {
    var payload = 0x00;
    payload = bignum(category_id).shiftLeft(31);
    if(hap_type == HAP_TYPE_IP_WAC) payload = payload.or(bignum(1).shiftLeft(30));
    if(hap_type == HAP_TYPE_BLE) payload = payload.or(bignum(1).shiftLeft(29));
    if(hap_type == HAP_TYPE_IP || hap_type == HAP_TYPE_IP_WAC) payload = payload.or(bignum(1).shiftLeft(28));
    payload = payload.or(bignum(setup_code));
    return "X-HM://00" + bases.toBase36(payload).toUpperCase() + setup_id;
}

console.log(generate_setup_payload_uri(ACCESSORY_CATEGORY_BRIDGES, HAP_TYPE_IP, '12345678', 'ABCD'));

this code is depend on bases and bignum module. 
output result is X-HM://0023OA632ABCD

**Comment by nhyjq** [comment]
Above code disregarded NFC tags. I think it is very probably that Setup ID is persist, so we could put it in config.json.
And a little sugesstion:  Should we provide some tools to help developer generating random username(device id) and setup id?

**Comment by KhaosT** [comment]
Cool, I can try to add this to hap-nodejs and add support in homebridge later today.

**Comment by pdlove** [comment]
I think it would be useful to automatically generate and save a userid, pin and setupid if is blank in the config.json file.

**Comment by KhaosT** [comment]
@pdlove I think the default behavior should be hap-nodejs generate a random setup ID every time it launches, with the option to override it in publish function. From homebridge side, a new field `setupID` will be added to bridge configuration payload which is optional.

**Comment by ebaauw** [comment]
Why not gerive the `SetupID` from the `username`?

**Comment by KhaosT** [comment]
@ebaauw because spec asked not to do that.

**Comment by nhyjq** [comment]
@KhaosT  Please refer to section 4.2.2 in spec R10.  
Do you think setup ID is alway persist or should change after reboot or factory reset?

**Comment by KhaosT** [comment]
@nhyjq for our case it doesn't really matter I think...

**Comment by pdlove** [comment]
If we test it and it pairs fine but doesn't work after restarting Homebridge.... then we'll know it matters!

**Comment by KhaosT** [comment]
Alright it's done, check out homebridge v0.4.30.

**Comment by KhaosT** [comment]
Let me know if you have issue with it.

**Comment by macjeff** [comment]
Sorry but been out of the loop a little.  Should everyone update or is this for a specific issue?

Jeff

**Comment by KhaosT** [comment]
@macjeff this is for new accessory setup. If you already paired with homebridge then this change won’t make any difference to you.

**Comment by nitaybz** [comment]
@KhaosT FYI, I got an issue on my plugin:

```
[2017-11-1 21:25:38] Registering platform 'homebridge-tado-ac.TadoAC'
[2017-11-1 21:25:38] ---
[2017-11-1 21:25:38] Loaded config.json with 0 accessories and 1 platforms.
[2017-11-1 21:25:38] ---
[2017-11-1 21:25:38] Loading 1 platforms...
[2017-11-1 21:25:38] [Tado AC] Initializing TadoAC platform...
[2017-11-1 21:25:38] Loading 0 accessories...
[2017-11-1 21:25:38] [Tado AC] Found new Zone: Aire Acondicionado (2) ...
[2017-11-1 21:25:39] [Tado AC] Initializing platform accessory 'Aire Acondicionado Tado'...
[2017-11-1 21:25:39] [Tado AC] Initializing platform accessory 'Outside Temperature'...
[2017-11-1 21:25:39] [Tado AC] Initializing platform accessory 'User 1'...
[2017-11-1 21:25:39] [Tado AC] Initializing platform accessory 'User 2'...
[2017-11-1 21:25:39] [Tado AC] Initializing platform accessory 'User 3'...
[2017-11-1 21:25:39] [Tado AC] Initializing platform accessory 'Anyone'...
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:384
  var encodedPayload = (buffer.readUInt32BE(4) + (buffer.readUInt32BE(0) * Math.pow(2, 32))).toString(36).toUpperCase().padStart(9, '0');
                                                                                                                        ^

TypeError: (buffer.readUInt32BE(...) + (buffer.readUInt32BE(...) * Math.pow(...))).toString(...).toUpperCase(...).padStart is not a function
    at Bridge.Accessory.setupURI (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:384:121)
    at Server._printSetupInfo (/usr/lib/node_modules/homebridge/lib/server.js:600:32)
    at Server._publish (/usr/lib/node_modules/homebridge/lib/server.js:128:8)
    at Server.<anonymous> (/usr/lib/node_modules/homebridge/lib/server.js:381:14)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:16:19
    at /usr/lib/node_modules/homebridge-tado-ac/index.js:331:13
    at /usr/lib/node_modules/homebridge-tado-ac/node_modules/async/dist/async.js:421:16
    at next (/usr/lib/node_modules/homebridge-tado-ac/node_modules/async/dist/async.js:5302:29)
    at /usr/lib/node_modules/homebridge-tado-ac/node_modules/async/dist/async.js:906:16
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-tado-ac/index.js:324:29)
```

this issue happens only in the latest version... also with hue platform:
```
[2017-11-1 22:15:10] [Hue] Philips hue: 1 accessories
[2017-11-1 22:15:10] [Hue] Initializing platform accessory 'Philips hue'...
[2017-11-1 22:15:10] [Hue] Philips hue: 3 services
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
[2017-11-1 22:15:10] [Hue] (buffer.readUInt32BE(...) + (buffer.readUInt32BE(...) * Math.pow(...))).toString(...).toUpperCase(...).padStart is not a function
[2017-11-1 22:15:10] Homebridge is running on port 51826.
```

**Comment by KhaosT** [comment]
@nitaybz What's the version of the node? and what platform are you running this on?

**Comment by nitaybz** [comment]
I think he had  v 6.x on a raspberry pi

**Comment by KhaosT** [comment]
Okay it looks like `padStart` is added at a later stage. Let me fix this. Sorry.

**Comment by plasticrake** [comment]
Yeah, v8.2.1. I use http://node.green/ a lot, very helpful to know what features you can use.

**Comment by KhaosT** [comment]
😅 Okay it's fixed.
