### ISSUE TITLE
HAP Warning Issue, Anyone Seen This, Know How To Fix ?

### ISSUE THREAD

**Issue by Wildcat1** [nfarina/homebridge#1592]
Seeing this issue recently after updating. Anyone have any ideas on what its referencing and how to fix:

'HAP Warning: Characteristic not in required or optional characteristics for service . Adding anyway.'

Thanks

**Comment by harishperfect** [comment]
I seem to have the same error. I had no issues configuring Homebridge and setting up the Home App. But this warning came up after I had grouped my accessories from within Home App and restarted Homebridge. After the restart, my Home App lost the grouping and I had to do that again. Maybe this is a related issue. Is anyone able to reproduce this issue?
