### ISSUE TITLE
Problems on install

### ISSUE THREAD

**Issue by samuelandersson** [nfarina/homebridge#1597]
### Expected Behavior

Home bridge should be installed without errors

### Current Behavior

Home bridge is not fully installed and cannot be installed.

### Steps to Reproduce (for bugs)

Follow [this](https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi) installation guide for Raspberry Pi.
### Versions

- **Homebridge**: `N/A (could not install)`
- **Node**:       `v7.10.1`
- **OS**:        `PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"`
### Configuration

```json

```

### Homebridge Log / Command Output

```
udo npm install -g --unsafe-perm homebridge
/usr/bin/homebridge -> /usr/lib/node_modules/homebridge/bin/homebridge

> mdns@2.3.3 install /usr/lib/node_modules/homebridge/node_modules/mdns
> node-gyp rebuild

make: Entering directory '/usr/lib/node_modules/homebridge/node_modules/mdns/build'
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
make: g++: Command not found
dns_sd_bindings.target.mk:149: recipe for target 'Release/obj.target/dns_sd_bindings/src/dns_sd.o' failed
make: *** [Release/obj.target/dns_sd_bindings/src/dns_sd.o] Error 127
make: Leaving directory '/usr/lib/node_modules/homebridge/node_modules/mdns/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.1.18-v7+
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/homebridge/node_modules/mdns
gyp ERR! node -v v7.10.1
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok 
/usr/lib
└── (empty)

npm ERR! Linux 4.1.18-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "--unsafe-perm" "homebridge"
npm ERR! node v7.10.1
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! mdns@2.3.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mdns@2.3.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mdns package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mdns
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mdns
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/.npm/_logs/2017-11-03T14_00_36_090Z-debug.log
```

**Comment by plasticrake** [comment]
Hi @samuelandersson, look like this is the line with the issue: `make: g++: Command not found`.

Did you follow the PI install guide? https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi

I don't have a PI running Jessie, but I'd make sure you have g++ installed, etc `g++ -v` and as the error says, maybe check out and submit an issue with `mdns` as that is where the problem is coming from.

**Comment by cerniuk** [comment]
@plasticrake that link was more than the typical hobbyist "noise". Appreciate you posting.  

One thing that has been a continuous issue has been nodejs and the incompatibilities between versions of that, of npm, of avahi, install order, install locations, the host name, and even the processor (ARM 6L) on the Raspberry Pi Zero Wi-Fi. Netatalk by contrast is a much more mature program.

With a clue in the link that you provided, and the last 8 hours of work, my son (an electrical engineer) and I (software engineer) got this thing off the ground.  Counting our time, this Raspberry Pi Zero is the most expensive computer in the house. (typing this on a 12 core MacPro).
