### ISSUE TITLE
Upgraded to node v8.9.0 from v6.10.2, homebridge wont' start

### ISSUE THREAD

**Issue by pponce** [nfarina/homebridge#1599]
Was running homebridge successfully using node v6.10.2. I upgraded to 8.9.0 by doing the following.
nvm install 8
nvm reinstall-packages 6.10.2
nvm use 8
npm uninstall -g homebridge
npm install -g homebridge

Then i manually started homebrigde
sudo -u homebridge /home/pi/.nvm/versions/node/v8.9.0/bin/homebridge -U /var/homebridge/

received that error that i paste below.

I tried 
npm rebuild 
and receive the same error when trying to start.
i've tried npm uninstall of all my homebridge plugins and re-installed them all.
Same error.
I can't seem to figure this out! Any ideas would be appreciated.

### Expected Behavior

Expecting homebridge to start without error

### Current Behavior

receive error pasted below.

### Versions

- **Homebridge**: `homebridge --version`
v0.4.31
- **Node**:       `node --version`
v8.9.0
- **OS**:         
pi3

### Configuration

```json

```

### Homebridge Log / Command Output

```
/home/pi/.nvm/versions/node/v8.9.0/lib/node_modules/homebridge/node_modules/mdns/lib/dns_sd.js:35
    throw ex;
    ^

Error: Module version mismatch. Expected 48, got 57.
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/pi/.nvm/versions/node/v8.9.0/lib/node_modules/homebridge/node_modules/mdns/lib/dns_sd.js:24:20)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)

```

**Comment by tomsteenbakkers** [comment]
I had the same issue. Try this, it’s solved my problems 
```
sudo npm install --unsafe-perm mdns 
cd /usr/local/lib/node_modules/homebridge
sudo npm rebuild --unsafe-perm
```

**Comment by tomsteenbakkers** [comment]
And if you reinstall homebridge use this command. 

`sudo npm install -g --unsafe-perm homebridge`

**Comment by pponce** [comment]
i've never had to use sudo for installing packages.
npm install --unsafe-perm mdns 
cd /usr/local/lib/node_modules/homebridge
npm rebuild --unsafe-perm (appeared to do nothing)
npm install--unsafe-perm (did work appear to re-install homebridge)

I then ran: 
cd /usr/local/lib/node_modules/
npm rebuild --unsafe-perm
Which rebuilt every module.

But i get the same error. so no luck

**Comment by pponce** [comment]
i figured it out.
I had a rogue version of node in /usr/local/bin that was being used and messing things up.

**Comment by WingTangWong** [comment]
This post REALLY helped. Allowed me to get my HomeBridge working post OS update.

**Comment by openfirmware** [comment]
I had this too with nvm, where I had node 10 as default although I am using node 8 for homebridge. My systemd script to start homebridge using a bash login shell would load node 10 and try to run the homebridge from node 8, and it would have the version mismatch error. Setting node 8 as my default fixed it, although I think updating the systemd script to switch node version should also work.
