### ISSUE TITLE
I don't see qrcode in 0.4.31

### ISSUE THREAD

**Issue by uronito** [nfarina/homebridge#1601]
> [22042]: [2017-11-5 19:41:15] [homebridge-tplink-smarthome.TplinkSmarthome] homebridge-tplink-smarthome v3.10.0, node v8.4.0, homebridge v0.4.31
Nov 05 19:41:15 raspberrypi homebridge[22042]: [2017-11-5 19:41:15] [homebridge-tplink-smarthome.TplinkSmarthome] Configuring cached accessory: [Enchufe Despacho] 80067D13E0B63549B3C421437CC2A3EF170F269C 620ddee9-
Nov 05 19:41:15 raspberrypi homebridge[22042]: [2017-11-5 19:41:15] [homebridge-tplink-smarthome.TplinkSmarthome] Configuring cached accessory: [Enchufe Salon] 8006D6898FE186D00ACAC4BA2882F84117F6ED0D 1aa747c6-602
Nov 05 19:41:15 raspberrypi homebridge[22042]: Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
Nov 05 19:41:15 raspberrypi homebridge[22042]:
Nov 05 19:41:15 raspberrypi homebridge[22042]:
Nov 05 19:41:15 raspberrypi homebridge[22042]:
Nov 05 19:41:15 raspberrypi homebridge[22042]:
Nov 05 19:41:15 raspberrypi homebridge[22042]:
Nov 05 19:41:15 raspberrypi homebridge[22042]:
Nov 05 19:41:15 raspberrypi homebridge[22042]:
Nov 05 19:41:15 raspberrypi homebridge[22042]:
Nov 05 19:41:15 raspberrypi homebridge[22042]:
Nov 05 19:41:15 raspberrypi homebridge[22042]:
Nov 05 19:41:15 raspberrypi homebridge[22042]:
Nov 05 19:41:15 raspberrypi homebridge[22042]:
Nov 05 19:41:15 raspberrypi homebridge[22042]:
Nov 05 19:41:15 raspberrypi homebridge[22042]:
Nov 05 19:41:15 raspberrypi homebridge[22042]:
Nov 05 19:41:15 raspberrypi homebridge[22042]:
Nov 05 19:41:15 raspberrypi homebridge[22042]:
Nov 05 19:41:15 raspberrypi homebridge[22042]:
Nov 05 19:41:15 raspberrypi homebridge[22042]:
Nov 05 19:41:15 raspberrypi homebridge[22042]:
Nov 05 19:41:15 raspberrypi homebridge[22042]:
Nov 05 19:41:15 raspberrypi homebridge[22042]:
Nov 05 19:41:15 raspberrypi homebridge[22042]:
Nov 05 19:41:15 raspberrypi homebridge[22042]:
Nov 05 19:41:15 raspberrypi homebridge[22042]:
Nov 05 19:41:15 raspberrypi homebridge[22042]:
Nov 05 19:41:15 raspberrypi homebridge[22042]:
Nov 05 19:41:16 raspberrypi homebridge[22042]: [2017-11-5 19:41:16] Homebridge is running on port 50080.
Nov 05 19:41:16 raspberrypi homebridge[22042]: [2017-11-5 19:41:16] Camara Dahua is running on port 46563.
Nov 05 19:41:16 raspberrypi homebridge[22042]: [2017-11-5 19:41:16] Camara Habitacion is running on port 44843.

**Comment by oznu** [comment]
I have seen the same thing happen when running Homebridge in Docker on a Synology NAS - the user interface only shows plain text logs so the QR code gets scrambled.

Would it be worth continuing to display the pairing pin below the QR code output, perhaps alongside instructions of how to enter it manually in iOS 11? This would also keep it backwards compatible for those still running iOS 10.

**Comment by det-box** [comment]
Hello,
I want back the display of the code in text form for the console.

Thank you

**Comment by frenck** [comment]
Same issue here... The QR code is not visible is many cases!
Please add an option to switch between the new and the old?

Would be very helpful. It breaks the Homebridge add-on for Home Assistant (since Hass.io relies on Docker with a web interface showing the logs).

**Comment by frenck** [comment]
Wow, just read a lot about the packages that generates the QR code.

Seriously? Adding a package that basically hasn't received any commits or other maintenance for years? With rendering issues open for Windows 10 & MacOS? And a couple of PR's that are left to collect dust?

What does that say about this project?

**Comment by frenck** [comment]
Maybe @KhaosT can tell us a little more?

**Comment by KhaosT** [comment]
I'm really sorry about how the recent change of QR code breaks on some platforms. I should be more careful with that one. Do you guys think I should just switch back to printing the code, or try find another package for printing QR code in terminal?

**Comment by oznu** [comment]
I think just printing the code in the same way it was in the previous version *under* the new QR code would satisfy everyone.

I don't think we'll ever have much luck getting the QR code to print correctly in plain text terminals like Synology or Hass.io use.

**Comment by KhaosT** [comment]
Okay I added back the normal code form in 0.4.32. Once again, really sorry about that.

**Comment by Krocko** [comment]
With 0.4.32 i got this:

```
Nov 14 10:01:15 raspberrypi homebridge[31374]: Setup Payload:
Nov 14 10:01:15 raspberrypi homebridge[31374]: X-HM://0023ISYWYXMAP
Nov 14 10:01:15 raspberrypi homebridge[31374]: Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
Nov 14 10:01:16 raspberrypi homebridge[31374]:                                                       
Nov 14 10:01:16 raspberrypi homebridge[31374]:                                                       
Nov 14 10:01:16 raspberrypi homebridge[31374]:                                                       
Nov 14 10:01:16 raspberrypi homebridge[31374]:                                                       
Nov 14 10:01:16 raspberrypi homebridge[31374]:                                                       
Nov 14 10:01:16 raspberrypi homebridge[31374]:                                                       
Nov 14 10:01:16 raspberrypi homebridge[31374]:                                                       
Nov 14 10:01:16 raspberrypi homebridge[31374]:                                                       
Nov 14 10:01:16 raspberrypi homebridge[31374]:                                                       
Nov 14 10:01:16 raspberrypi homebridge[31374]:                                                       
Nov 14 10:01:16 raspberrypi homebridge[31374]:                                                       
Nov 14 10:01:16 raspberrypi homebridge[31374]:                                                       
Nov 14 10:01:16 raspberrypi homebridge[31374]:                                                       
Nov 14 10:01:16 raspberrypi homebridge[31374]:                                                       
Nov 14 10:01:16 raspberrypi homebridge[31374]:                                                       
Nov 14 10:01:16 raspberrypi homebridge[31374]:                                                       
Nov 14 10:01:16 raspberrypi homebridge[31374]:                                                       
Nov 14 10:01:16 raspberrypi homebridge[31374]:                                                       
Nov 14 10:01:16 raspberrypi homebridge[31374]:                                                       
Nov 14 10:01:16 raspberrypi homebridge[31374]:                                                       
Nov 14 10:01:16 raspberrypi homebridge[31374]:                                                       
Nov 14 10:01:16 raspberrypi homebridge[31374]:                                                       
Nov 14 10:01:16 raspberrypi homebridge[31374]:                                                       
Nov 14 10:01:16 raspberrypi homebridge[31374]:                                                       
Nov 14 10:01:16 raspberrypi homebridge[31374]:                                                       
Nov 14 10:01:16 raspberrypi homebridge[31374]:                                                       
Nov 14 10:01:16 raspberrypi homebridge[31374]:                                                       
Nov 14 10:01:16 raspberrypi homebridge[31374]: Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:
Nov 14 10:01:16 raspberrypi homebridge[31374]: ┌────────────┐
Nov 14 10:01:16 raspberrypi homebridge[31374]: │ undefined │
Nov 14 10:01:16 raspberrypi homebridge[31374]: └────────────┘
Nov 14 10:01:16 raspberrypi homebridge[31374]: [2017-11-14 10:01:16] Homebridge is running on port 42837.
```

**Comment by cis2131** [comment]
I really like this new QR-Code, but agree that the pin might still be needed.

Is there some way to generate the code from another application, i would like tp thow it on a webpage.

**Comment by KhaosT** [comment]
@cis2131 Yeah, you can create yourself. See the `Setup Payload` part with a URL like `X-HM://0023ISYWYJMRW`, simply create an QR code based on that and iOS will scan it.

**Comment by KhaosT** [comment]
@Krocko try again with 0.4.33?

**Comment by Krocko** [comment]
@KhaosT now the pin is visible. Trank you.

**Comment by cis2131** [comment]
Thanks, but is there a way to get it after start (other than searching trough the logfile), or to konw the value before start?.

**Comment by KhaosT** [comment]
@cis2131 Once it's there, it remains the same until you reset the accessory. Technically you can put the setupID in the bridge configuration file and then manually compute the setup payload in advance...

**Comment by cis2131** [comment]
Is that possible with current version?

**Comment by KhaosT** [comment]
@cis2131 for how to compute setup payload, see here (https://github.com/nfarina/homebridge/issues/1588#issuecomment-341158722)
