### ISSUE TITLE
How to write a gate accessory

### ISSUE THREAD

**Issue by d0n13** [nfarina/homebridge#1604]
I can't find a suitable accessory type for a gate. Do we have to use a door as the basis for a gate opener?

Sorry for the basic question

**Comment by NorthernMan54** [comment]
You could potentially could use any accessory type for your gate, what will matter the most is does it support the proper characteristics for what your trying to do with your gate.  In my setup, I’m using the Fan accessory as a Fireplace and the Lightbulb as a Stereo.

**Comment by d0n13** [comment]
I've written an accessory for a garage door and the icon in the home app shows the door going up and down. This is cool.

My gate goes left and right :) WOuld be nice if there was a matching accessory for a gate. 

The door has the relevant characteristics but would like the app to signify it as gate rather than a door :( Can't believe they have fans, doors, windows etc and no gate!!! Or am I missing something?

**Comment by d0n13** [comment]
I've been using this for reference https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js
