### ISSUE TITLE
This has got to be user error somewhere.  - Error: The requested accessory 'sonymutetv' was not registered by any plugin.

### ISSUE THREAD

**Issue by russellh76** [nfarina/homebridge#1605]
Hi Guys,
There are plenty of posts with this exact same error.
So far all of those issues are misspellings or capitalization.

In my case I've got to be missing something obvious.
Working on writing my own plugin.  All was working fine and then all of a sudden I started seeing the below.

It's not a case thing, it's not spelling
Has to be misunderstanding on my part.

Thanks for any help you can provide.

Russells-MBP-2:.homebridge russellhogg$ DEBUG=* homebridge -D -P /../HBDEV/
[2017-11-9 01:10:32] Plugin /usr/local/lib/node_modules/homebridge-sonymutetv does not have a package name that begins with 'homebridge-'.
[2017-11-9 01:10:32] Loaded plugin: homebridge-sonybraviatv
[2017-11-9 01:10:32] Registering accessory 'homebridge-sonybraviatv.SonyBraviaTV'
[2017-11-9 01:10:32] ---
[2017-11-9 01:10:32] Loaded config.json with 1 accessories and 0 platforms.
[2017-11-9 01:10:32] ---
[2017-11-9 01:10:32] Loading 1 accessories...
/usr/local/lib/node_modules/homebridge/lib/api.js:64
      throw new Error("The requested accessory '" + name + "' was not registered by any plugin.");
      ^

Error: The requested accessory 'sonymutetv' was not registered by any plugin.
    at API.accessory (/usr/local/lib/node_modules/homebridge/lib/api.js:64:13)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:263:42)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:86:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)

Russells-MBP-2:.homebridge russellhogg$ npm list -g --depth=0
/usr/local/lib
├── homebridge@0.4.31
├── homebridge-sonybraviatv@0.0.7
├── npm@5.5.1
└── sonymutetv@1.0.0 -> /Users/russellhogg/HBDEV

Russells-MBP-2:.homebridge russellhogg$ 

{
"bridge": {
"name": "HBDev0003",
"username": "CA:22:3D:E3:CE:30",
"port": 51826,
"pin": "111-11-111"
},
"description": "config.json for DEV purposes",
  "accessories": [
    {
      "accessory": "sonymutetv",
      "name": "TV Mute",
      "macaddress": "44:1c:a8:91:b3:89",
      "ipaddress": "192.168.1.157",
      "presharedkey": "0000"
    }
  ]
}

Pulling my hair out, has to be something stupid.
Russell

**Comment by ebaauw** [comment]
Try `”accessory”: “homebridge-sonymutetv”` in config.json.

**Comment by russellh76** [comment]
Thanks for the speedy reply,
That's where I started.  I shortened up while grasping at straws.
It's back at homebridge-sonymutetv now and still showing the same issue.

I'm new to this, but I believe that if I had an issue in index.js I would see it when I tried to npm install it.  I gather that this error is happening before that code would ever execute anyway.  

I've actually completely removed and reinstalled nodeJS over the last several hours as well.
Wiped the persist and accessories directories.  

Scratching my head.

-R

**Comment by ebaauw** [comment]
> [2017-11-9 01:10:32] Plugin /usr/local/lib/node_modules/homebridge-sonymutetv does not have a package name that begins with 'homebridge-'.

This one is issued by homebridge when loading the plugin.  Make sure the name in the plugin’s package.json matches the directory name.

**Comment by russellh76** [comment]
The name of the directory has to match?
the directory now is HBDEV.  I'd need to make it homebridge-sonymutetv?

**Comment by russellh76** [comment]
I see the warning you mentioned, but I can't find any information on how to resolve that.
I did change my folder name to match the plugin name.  That doesn't seem to have had any affect.

**Comment by ebaauw** [comment]
Typically, the name of the package (as specified in its package.json) equals the name of the diectory.  This name must match the package name passed by index.js in `registerAccessory()` or `registerPlatform()`.  The plugin name in that call should match the value of `accessory` or `platform` in config.json.

**Comment by russellh76** [comment]
It started working after getting the keywords in there.  I guess it's possible I'd tweaked something else.  I'm a little bleary-eyed.  Thank you much for the help.  I probably won't know I have it for sure until tomorrow.

**Comment by russellh76** [comment]
I'm in good shape here.  Thanks to @ebaauw 
Thank you Erik!
