### ISSUE TITLE
appletv 4 tvos 11.0 not show homekit options

### ISSUE THREAD

**Issue by uronito** [nfarina/homebridge#1606]
Homebridge 0.4.31
Appletv 4 tvos 11.0 don't show homekit options.
Can't configure remote access
Regards.

**Comment by jvmahon** [comment]
I'm not in front of my Apple TV, so this is from memory but .... the Apple TV only gives very limited information about your Homekit setup. The main thing to check is that your phone and your Apple TV need to be logged into the same iCloud login. Once you do that, I think the only other setting is to go to the Apple TV accounts / iCloud Account option and there may be a homekit toggle (my recollection is that by default, it is toggled "on" so you should not even need to check this).  You can then test that the Apple TV is working with homekit by asking Siri to perform a function using the Apple TV remote's microphone (Hold down the microphone button on the remote and ask "Siri how many lights are on", "Siri turn on all lights" or the like). If that works, and it works on your phone, you should have remote access.

**Comment by macbisho** [comment]
Hi Uronito,

Are you running public beta for tvOS on your apple tv?

If you are, I think that it's a bug. 

Just to compare - I'm currently running Public Beta tvOS and "release" iOS 11.3 on my iPhone, iPad etc. and there is no ability to enable HomeKit in the Settings > Accounts > iCloud area 

It's *very* frustrating.
