### ISSUE TITLE
Error loading accessories 

### ISSUE THREAD

**Issue by Tommrodrigues** [nfarina/homebridge#1607]
Hey there, 
I'm having some problems loading any of my homebridge accessories. I had a number of accessories and platforms associated with homebridge along with their respective plugins and they were all working fine until I updated both my homebridge and npm version. Now I get the following error whenever I try to load homebridge with any accessories in the config.json file: 
<img width="645" alt="screen shot 2017-11-09 at 13 05 55" src="https://user-images.githubusercontent.com/33377034/32604962-dfcd0752-c54f-11e7-8c77-15311cdd4266.png">
This is strange because it is an error to to with accessories particularly as when I delete all accessories from the config.json and just leave the platforms, it loads perfectly. Furthermore, it is no one accessory that is causing this error as I have tried deleting all accessory plugins and installing and placing in the config.json one at a time and still get this error. This leads me to believe that there is some error in homebridge itself to do with the way it reads the accessories that is causing this error. Any advice or solutions would be much appreciated. Thank you in advance,
Tom

**Comment by djh82uk** [comment]
Im getting this error too

**Comment by Tommrodrigues** [comment]
This problem still persists for me, is anyone aware of a fix for this?
Thanks

**Comment by jeryci** [comment]
Hi !

noob to homebridge.. i am getting this error, config.json seems ok, i don't know what causes this error, anyone has an idea ?
thank you !

**Comment by jeryci** [comment]
nevermind.. 

an empty accessories section "accessories":[{}] in config.json caused the issue, i removed the whole accessories section and got it to pass.
