### ISSUE TITLE
Homebridge doesn't work as systemd but standalone

### ISSUE THREAD

**Issue by jeGit** [nfarina/homebridge#1608]
Hi, 
I have configured Homebridge to run in the background using systemd as described here and at [johannrichard](https://gist.github.com/johannrichard/0ad0de1feb6adb9eb61a/).

Homebridge starts well and is discoverable when starting it manually in terminal. I have all my devices configured and accessible on my iPad

But when I terminate homebridge and instead running it systemctl start homebridge it is no longer accessible form my iPad.
I noticed that the out put via systemctl status also looks different to the one when starting in terminal:
sudo systemctl status homebridge
● homebridge.service - Node.js HomeKit Server
   Loaded: loaded (/etc/systemd/system/homebridge.service; enabled)
   Active: active (running) since Thu 2017-11-09 17:25:18 CET; 52s ago
 Main PID: 3099 (homebridge)
   CGroup: /system.slice/homebridge.service
           └─3099 homebridge

Nov 09 17:25:50 raspberrypi homebridge[3099]: Thu, 09 Nov 2017 16:25:50 GMT EventedHTTPServer Server listening on port 51826
Nov 09 17:25:50 raspberrypi homebridge[3099]: [11/9/2017, 5:25:50 PM] Homebridge is running on port 51826.
Nov 09 17:25:51 raspberrypi homebridge[3099]: Thu, 09 Nov 2017 16:25:51 GMT EventedHTTPServer [::ffff:192.168.178.37] New connection from client
Nov 09 17:25:51 raspberrypi homebridge[3099]: Thu, 09 Nov 2017 16:25:51 GMT EventedHTTPServer [::ffff:192.168.178.37] HTTP server listen...rt 43917
Nov 09 17:25:52 raspberrypi homebridge[3099]: Thu, 09 Nov 2017 16:25:52 GMT EventedHTTPServer [::ffff:192.168.178.37] HTTP request: /pair-verify
Nov 09 17:25:52 raspberrypi homebridge[3099]: Thu, 09 Nov 2017 16:25:52 GMT HAPServer [CC:22:3D:E3:CE:32] HAP Request: POST /pair-verify
Nov 09 17:25:52 raspberrypi homebridge[3099]: Thu, 09 Nov 2017 16:25:52 GMT EventedHTTPServer [::ffff:192.168.178.37] HTTP Response is finished
Nov 09 17:25:52 raspberrypi homebridge[3099]: Thu, 09 Nov 2017 16:25:52 GMT EventedHTTPServer [::ffff:192.168.178.37] Client connection closed
Nov 09 17:25:52 raspberrypi homebridge[3099]: Thu, 09 Nov 2017 16:25:52 GMT EventedHTTPServer [::ffff:192.168.178.37] HTTP connection was closed
Nov 09 17:25:52 raspberrypi homebridge[3099]: Thu, 09 Nov 2017 16:25:52 GMT EventedHTTPServer [::ffff:192.168.178.37] HTTP server was closed
Hint: Some lines were ellipsized, use -l to show in full.

Any ideas what's wrong?
Tia, Jens

**Comment by Kiter1988** [comment]
Same Issue here. 
I have reinstall my raspberry witch stretch and homebridge too. 

pi@raspberrypi:~ $ homebridge
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[2017-11-24 19:34:29] Loaded plugin: homebridge-fhem
homebridge API version: 2.2
this homebridge-fhem 0.3.7
