### ISSUE TITLE
Just installed home bridge, will not start

### ISSUE THREAD

**Issue by p4madeus** [nfarina/homebridge#1609]
### Expected Behavior - 
it starts up

### Current Behavior - it does not start up, displays this:
module.js:538
    throw err;
    ^
Error: Cannot find module '../build/Release/dns_sd_bindings'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/mdns/lib/dns_sd.js:32:22)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)

### Steps to Reproduce (for bugs)
run home bridge command

### Versions 

- **Homebridge**: `4.31
- **Node**:       v8.9.1
- **OS**:         macOS 10.13

### Configuration

{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "xxx-xx-xxx"
    },
    
    "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",

    "accessories": [
        {
            "accessory": "WeMo",
            "name": "Coffee Maker"
        }
    ],

    "platforms": [
        {
        	"platform" : "EcoPlug",
        	"name" : "EcoPlug"
        }
    ]
}

### Homebridge Log / Command Output

```

```

**Comment by maragelis** [comment]
sudo apt-get install libavahi-compat-libdnssd-dev

**Comment by rgerr** [comment]
Same issue, same error, same Homebridge and Node version, only difference is that mine is on Raspberry Pi 3B.

@maragelis Already tried, makes no difference.

**Comment by maragelis** [comment]
I would bring down nodejs to ver 7

**Comment by bprskalo** [comment]
is the upper configuration your file ?

**Comment by rgerr** [comment]
How to downgrade nodejs? Which command(s)?

**Comment by wickeym** [comment]
I also encountered this error. The solution in this issue, fixed it for me
https://github.com/nfarina/homebridge/issues/905

I am running node version 8.9.1

**Comment by rgerr** [comment]
Fixed it, downgraded node.js to v7.9.0, deleted 9.x, then 
sudo npm install --unsafe-perm mdns
cd /usr/local/lib/node_modules/homebridge
sudo npm rebuild --unsafe-perm

**Comment by LudicEyes** [comment]
I needed to do 

npm install -g --unsafe-perm mdns
cd to node module location
npm rebuild --unsafe-perm
