### ISSUE TITLE
I think I have a formatting error in my config file but I can't seem to locate it.

### ISSUE THREAD

**Issue by tystik4056** [nfarina/homebridge#1613]
Admittedly I'm new to this, but I had it working up up until I added the mi-light plug in. I added my platform in stages to make sure everything worked. I figure I'm missing a comma or something. Any help is appreciated!!

<img width="675" alt="screen shot 2017-11-10 at 3 48 39 pm" src="https://user-images.githubusercontent.com/33555410/32683234-a62cf4be-c62e-11e7-8bea-edaeee624acb.png">

{
  "bridge":{
    "name":"Homebridge",
    "username":"CD:22:3D:E3:CE:32",
    "port":51826,
    "pin":"031-45-156"
  },
  "description":"Homebridge",
  "accessories":[

  ],
  "platforms":[
    {
      "platform": "TplinkSmarthome",
    "name": "TplinkSmarthome"
 },
 {
      "platform": "Hue",
      "users": {
        "001788FFFExxxxxx": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "001788FFFEyyyyyy": "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy"
      },
      "sensors": true,
      "excludeSensorTypes": ["CLIPPresence", "Geofence"],
      "lights": true,
      "nativeHomeKit": false
    },

    {
            "platform":"MiLight",
            "name":"MiLight",
            "bridges": [
              {
                "ip_address": "10.0.1.25",
                "version": "v6",
                "lights": {"fullColor": ["Kitchen",null,"Bedroom","Hallway"],
                           "rgbw": ["Living Room", "Downstairs Bedroom"]},
                "repeat": 1,
                "delay": 100
              },
              {
                "ip_address": "10.0.1.26",
                "lights": {"white": ["Dining Room", "Den"],
                           "rgbw": ["Master Bedroom"]}
              }
    ]}

**Comment by ebaauw** [comment]
Looks like you’re missing a closing `]}`.  Try https://jsonlint.com.

**Comment by tystik4056** [comment]
Thanks!
