### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by stonerocky** [nfarina/homebridge#1616]
i am from China ,sorry for my poor English.but I need your help .my homebridge crashed .could you help me.

here is the log

{"id":-1,"method":"get_prop","params":["power"]}
send hb to: 0x00000000036fee76
{"id":-1,"method":"get_prop","params":["power"]}
/usr/lib/node_modules/homebridge-aqara/lib/AqaraAccessoryFactory.js:75
    var gatewaySid = this.gatewaySids[accessory.UUID];
                                               ^

TypeError: Cannot read property 'UUID' of undefined
    at AqaraAccessoryFactory.autoRemoveAccessory (/usr/lib/node_modules/homebridge-aqara/lib/AqaraAccessoryFactory.js:75:48)
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-aqara/lib/AqaraPlatform.js:103:15)
    at ontimeout (timers.js:386:11)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)

here is my config.json
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    }, 
    "platforms": [
    {
    "platform": "MiAqaraPlatform",
    "sid": ["395c72b82c51413a"],
    "password": ["34ce00idbd86"] 
    },
      ]
    }

**Comment by NorthernMan54** [comment]
Hi,

As this problem is with the homebridge-aqara plugin, please raise an issue there.
