### ISSUE TITLE
The requested platform '" + name + "' was not registered by any plugin.

### ISSUE THREAD

**Issue by bd0r** [nfarina/homebridge#1619]
any help please!!

![untitled000](https://user-images.githubusercontent.com/23739528/32856445-eab46952-ca55-11e7-8494-231190383be8.png)

### Versions

- **Homebridge**: `homebridge --version`
- **Node**:       `node --version`
- **OS**:         

### Configuration

```json

```

### Homebridge Log / Command Output

```

```

**Comment by igreulich** [comment]
What does your `config.json` look like?

**Comment by bd0r** [comment]
fixed by removing homebridge from /opt/node/lib/node_modules/homebridge & /home/.homebridge
and reinstalled homebridge thanks !!!
