### ISSUE TITLE
Pin code rejected

### ISSUE THREAD

**Issue by Jborn4christ** [nfarina/homebridge#162]
For the life of me can't figure out why the pin code is being rejected on setup. I tried the default a few times, and the changed it, but the app immediately says invalid code, etc. Any ideas?

**Comment by Jborn4christ** [comment]
Running on a Mac mini.

**Comment by KhaosT** [comment]
@Jborn4christ What's the error on the server side? Can you post the log?

**Comment by nzhome** [comment]
For detailed server logs start homebridge like this:

Raspberry PI:
    DEBUG=* node app.js


FOR Windows put this in a start.bat file:

    set DEBUG=*,-not_this
    FOR /L %%A IN (1,1,200) DO (
      ECHO HomeBridge Startup #%%A
      ECHO To Exit press Ctrl+C, press Y, then press Enter.
      node app.js
    )
    pause

**Comment by Jborn4christ** [comment]
How should I run it on a Mac? Sorry. I know just enough  to be dangerous.

**Comment by Jborn4christ** [comment]
Here's what I get in the server when trying to connect through Eve.

  Accessory [Homebridge] Creating new AccessoryInfo for our HAP server +0ms
  Accessory [Homebridge] Creating new IdentifierCache +4ms
  EventedHTTPServer Server listening on port 51826 +16ms
  EventedHTTPServer [fe80::104d:f492:a046:5395] New connection from client +13s
  EventedHTTPServer [fe80::104d:f492:a046:5395] HTTP server listening on port 54826 +1ms
  EventedHTTPServer [fe80::104d:f492:a046:5395] HTTP request: /pair-setup +5ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-setup +0ms
  HAPServer [CC:22:3D:E3:CE:30] Pair step 1/5 +2ms
  EventedHTTPServer [fe80::104d:f492:a046:5395] HTTP Repsonse is finished +19ms
  EventedHTTPServer [fe80::104d:f492:a046:5395] HTTP request: /pair-setup +23s
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-setup +0ms
  HAPServer [CC:22:3D:E3:CE:30] Pair step 1/5 +1ms
  EventedHTTPServer [fe80::104d:f492:a046:5395] HTTP Repsonse is finished +9ms

**Comment by nfarina** [comment]
Closing this old issue; reopen if necessary.

**Comment by Raccooon** [comment]
anyone can help?
