### ISSUE TITLE
Only find the accessory "Homebridge" But did not find any other accessory like the light blub

### ISSUE THREAD

**Issue by pxfeng** [nfarina/homebridge#1620]
I Follow step by step. But when i go to Home, it only find the accessory called" Homebridge" but no any other accessory such as my Mi light bulb that have already connect to MIHome. 

here is my config.json
{"bridge":{"name":"Homebridge","username":"CC:22:3D:E3:CE:23","port":51826,"pin":"233-62-666"},"platforms":[{"platform":"MiAqaraPlatform","sid":[""],"password":[""]}]}

I have put sid and password by following the info in mihome.

**Comment by KhaosT** [comment]
Yeah that’s expected. Homebridge exposes those accessories as bridged accessories so you only need to pair with the bridge with HomeKit.

**Comment by pxfeng** [comment]
@KhaosT Thank you for reply!
![img_5efd3dee62b3-1](https://user-images.githubusercontent.com/33710087/32875629-d6f2ec0c-ca4d-11e7-91c7-0bf5d3bf1fa6.jpeg)
I know that I only need to pair the homebridge then every other accessory will shows up by themselves.
but this is the only one shows in Home after pair the bridge.
I really don't know what is wrong lol

**Comment by KhaosT** [comment]
In the log does MiAqaraPlatform report any error?

**Comment by KhaosT** [comment]
Also, where did you saw that `sid` and `password` config? I checked their project repo and the configuration suppose to be something like
```
{
    "platforms": [{
        "platform": "MiAqaraPlatform",
        "gateways": {
            "6409802da3b3": "02i44k56zrgg578b"
        }
    }]
}
```

**Comment by pxfeng** [comment]
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[2017-11-16 05:53:49] Loaded plugin: homebridge-mi-aqara
[2017-11-16 05:53:49] Registering platform 'homebridge-mi-aqara.MiAqaraPlatform'
[2017-11-16 05:53:49] ---
failed to load BLE module!
[2017-11-16 05:53:49] Loaded plugin: homebridge-yeelight
[2017-11-16 05:53:49] Registering platform 'homebridge-yeelight.yeelight'
[2017-11-16 05:53:49] ---
[2017-11-16 05:53:49] Loaded config.json with 0 accessories and 1 platforms.
[2017-11-16 05:53:49] ---
[2017-11-16 05:53:49] Loading 1 platforms...
[2017-11-16 05:53:49] [MiAqaraPlatform] Initializing MiAqaraPlatform platform...
[2017-11-16 05:53:49] [MiAqaraPlatform] [INFO]**************************************************************
[2017-11-16 05:53:49] [MiAqaraPlatform] [INFO]           MiAqaraPlatform v0.6.5 By YinHang
[2017-11-16 05:53:49] [MiAqaraPlatform] [INFO]  GitHub: https://github.com/YinHangCode/homebridge-mi-aqara  
[2017-11-16 05:53:49] [MiAqaraPlatform] [INFO]                                         QQ Group: 107927710  
[2017-11-16 05:53:49] [MiAqaraPlatform] [INFO]**************************************************************
[2017-11-16 05:53:49] [MiAqaraPlatform] [INFO]start success...
Load homebridge-yeelight.yeelight
[2017-11-16 05:53:49] [homebridge-yeelight.yeelight] YeePlatform Init
Setup Payload:
X-HM://0023UUAUI4AOP
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                                                             
Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 233-62-666 │     
    └────────────┘     
                       
[2017-11-16 05:53:49] [homebridge-yeelight.yeelight] DidFinishLaunching
no ble cap, skip ble device discovery
[2017-11-16 05:53:49] [MiAqaraPlatform] [INFO]server is listening on port 9898.
[2017-11-16 05:53:49] Homebridge is running on port 51826.
add to multicast group
listen on 0.0.0.0
no did or loc found!

**Comment by pxfeng** [comment]
@KhaosT  
![img_912b1b1513f4-1](https://user-images.githubusercontent.com/33710087/32876067-fe91715a-ca4f-11e7-825b-7cf874dd2156.jpeg)
I found password on here.

**Comment by KhaosT** [comment]
@pxfeng yeah, I mean the configuration setting.
Instead of
```
{
	"platform": "MiAqaraPlatform",
	"sid": [""],
	"password": [""]
}
```
it seems `MiAqaraPlatform` wants
```
{
	"platform": "MiAqaraPlatform",
	"gateways": {
		"gateway's MAC address (lower case without colon)": "password"
	}
}
```

**Comment by pxfeng** [comment]
lol now i changed to your format. even the "homebridge" accessory disappear lol. Even i changed back to the previous setting still nothing shows up in Home now lol.
it is something wrong when it said:
add to multicast group
listen on 0.0.0.0
no did or loc found!


seems like this code is not showing before.

**Comment by KhaosT** [comment]
@pxfeng also try change the username from `CC:22:3D:E3:CE:23` to a difference one like `EE:22:3D:A3:CE:3F`.

**Comment by pxfeng** [comment]
@KhaosT finally make it lol! Thank you so much!

**Comment by KhaosT** [comment]
Glad it works :)
