### ISSUE TITLE
hi, thx for the homebridge code. Is it also possible to connect sonoff products without flashing?thx. chris

### ISSUE THREAD

**Issue by chrisfle** [nfarina/homebridge#1622]
hi, thx for the homebridge code. Is it also possible to connect sonoff products without flashing?thx. chris

**Comment by maragelis** [comment]
no, this will have to be done by itead.

**Comment by chrisfle** [comment]
thx. Are flashed sonoff products also in the ewe-link app??

**Comment by maragelis** [comment]
no

**Comment by dotmaster** [comment]
After flashing Tasmota on your sonogram install: https://www.npmjs.com/package/homebridge-mqtt-switch-tasmota
