### ISSUE TITLE
All accessories showing as "no response" 

### ISSUE THREAD

**Issue by dpyy** [nfarina/homebridge#1627]
All accessories showing as "no response" 

It's been working for months but all of a sudden it stopped working. I've tried readding the bridge, same thing. I tried rebooting both apple tv as hub. Same thing. Please help!

**Comment by dotmaster** [comment]
+1

**Comment by dotmaster** [comment]
solved, by setting a new user in config.json

**Comment by dpyy** [comment]
what new user?

**Comment by dotmaster** [comment]
create a different user in config.json. It looks like a MAC Address. The restart homebridge. (Eventually also delete the folders .homebridge/persist and .homebridge/accessories.

See also: https://github.com/nfarina/homebridge#common-issues

It worked for me, but I had to rename the MAC Address at the beginningand end:
e.g. You have to change the "AD:32:2D:E3:CE:31" "A to E and 1 to 5"
You can use A B C D E 1 2 3 4 5

See also this issue: https://github.com/nfarina/homebridge/issues/1324

**Comment by michaeljanich** [comment]
I believe you can use all HEX numbers 0..9 A..F

**Comment by codenoxi** [comment]
thanks @dotmaster, that works for me.
the only problem is that homebridge shows up as a new hub and therefor you have reconfigure all the devices in the home app again.

**Comment by dpyy** [comment]
I find that every time I reboot the router, I have to reset the whole thing again which is a huge pain. What is going on? Why is homebridge so prone to "no response" problems?

**Comment by michaeljanich** [comment]
I found that too, when I (had to) reboot my router.

But it seems it's a linux problem, because even ping did not work. I have not
had the chance to search for "raspberry pi, no access after router reboot" to
investigate further...

**Comment by JBowness** [comment]
I'm finding this to be the case too with my new hass.io installation with a couple of z-wave switches.  Toggling the switches from the Home Assistant control panel seems to "wake up" the HomeBridge in Apple Home on my iPhone, but sometimes it takes a few toggles before it is visible to iOS.  

IGMP Proxy is enabled on my router (TP-Link Archer C9).   

I'd love to have HA/HB running reliably.  I'll try creating a new user and seeing if that does the trick.
