### ISSUE TITLE
Cannot install Homebridge macOS High Sierra

### ISSUE THREAD

**Issue by havknfrack** [nfarina/homebridge#1628]
Homebridge stopped working after updating to iOS 11 and macOS 10.13. I was trying to update Homebridge, and eventually tried uninstalling, intending to reinstall. Either way, I received the included error which prevented updating and now reinstalling. 

### Expected Behavior

Trying to install Homebridge on macOS High Sierra

### Current Behavior

Receive a failed installation error

### Steps to Reproduce (for bugs)

Typing sudo npm install -g homebridge 

### Versions

- **Homebridge**: `homebridge --version` currently uninstalled.
- **Node**:       `node --version` 6.9.2
- **OS**:          macOS 10.13.1

### Configuration

```json

```

### Homebridge Log / Command Output

```
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/homebridge/node_modules/mdns/build'
gyp ERR! stack     at Error (native)
gyp ERR! System Darwin 17.2.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/homebridge/node_modules/mdns
gyp ERR! node -v v6.9.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mdns@2.3.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mdns@2.3.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by michaeljanich** [comment]
EACCES: permission denied
Have you tried sudo? If yes, add --unsafe-perm to npm install

**Comment by tbridge** [comment]
Just confirming that it doesn't requires `sudo`, but using ``--unsafe-perm` to the `npm` command resolved this issue for me.

Ideally, it would be nice not to require that.
