### ISSUE TITLE
debin install Homebridge

### ISSUE THREAD

**Issue by huyifanstar** [nfarina/homebridge#1629]
root@debian:~# npm --version
5.5.1

root@debian:~# node --version
v8.9.1

============================================================
Linux debian 4.9.0-4-amd64 #1 SMP Debian 4.9.51-1 (2017-09-28) x86_64 GNU/Linux
================================================================

root@debian:/usr/local/lib/node_modules/homebridge# npm install --unsafe-perm bignum

> bignum@0.12.5 install /usr/local/lib/node_modules/homebridge/node_modules/bignum
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://rvagg-node.s3-us-west-2.amazonaws.com/bignum/v0.12.5/bignum-v0.12.5-node-v57-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for bignum@0.12.5 and node@8.9.1 (node-v57 ABI, glibc) (falling back to source compile with node-gyp) 
^C
root@debian:/usr/local/lib/node_modules/homebridge# npm install --unsafe-perm bignum      --fallback-to-build

> bignum@0.12.5 install /usr/local/lib/node_modules/homebridge/node_modules/bignum
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://rvagg-node.s3-us-west-2.amazonaws.com/bignum/v0.12.5/bignum-v0.12.5-node-v57-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for bignum@0.12.5 and node@8.9.1 (node-v57 ABI, glibc) (falling back to source compile with node-gyp) 
=====================================
help  me!!!

**Comment by aswathraja** [comment]
have you installed the linux dependencies of HAPNode-JS? the libavahi-compat-libdnssd-dev package: sudo apt-get install libavahi-compat-libdnssd-dev
