### ISSUE TITLE
Installed homebridge but never got to see any accessories, yet see errors I don't understand

### ISSUE THREAD

**Issue by redomo** [nfarina/homebridge#1632]
I've installed homebridge, but never got to see any accessories. 

{
    "bridge": {
        "name": "Homebridge",
        "username": "XX:XX:XX:XX:XX:XX",
        "port": 51826,
        "pin": "031-45-154"
    },
    "description": "Configuration file for Domoticz platform.",
    "platforms": [
        {
            "platform": "eDomoticz",
            "name": "Domoticz",
            "server": "127.0.0.1",
            "port": "8080",
            "ssl": 0,
            "roomid": 2,
            "mqtt": 1
        }
    ],
    "accessories": []
}

This is my config.json where roomplan is set to 2 (as that what is shown in Domoticz), 
but tried also with  0 and 1. No matter what, no accessories are shown. Same for mqtt. Tried both 0 and 1.

I've tried upgrading Nodejs to 9.2. That didn't work, so I went back to 8.9.1
Did a new install and now the below happens. Anybody have any idea what's going on and of course how to resolve it and get the devices to show?

pi@raspberrypi:~/.homebridge/accessories$ pm2 show 0
 Describing process with id 0 - name homebridge
┌───────────────────┬───────────────────────────────────────────┐
│ status            │ online                                    │
│ name              │ homebridge                                │
│ restarts          │ 0                                         │
│ uptime            │ 17m                                       │
│ script path       │ /usr/bin/homebridge                       │
│ script args       │ N/A                                       │
│ error log path    │ /home/pi/.pm2/logs/homebridge-error-0.log │
│ out log path      │ /home/pi/.pm2/logs/homebridge-out-0.log   │
│ pid path          │ /home/pi/.pm2/pids/homebridge-0.pid       │
│ interpreter       │ node                                      │
│ interpreter args  │ N/A                                       │
│ script id         │ 0                                         │
│ exec cwd          │ /home/pi/.homebridge                      │
│ exec mode         │ fork_mode                                 │
│ node.js version   │ 8.9.1                                     │
│ watch & reload    │ ✘                                         │
│ unstable restarts │ 0                                         │
│ created at        │ 2017-11-25T16:32:52.941Z                  │
└───────────────────┴───────────────────────────────────────────┘
 Code metrics value
┌────────────┬────────┐
│ Loop delay │ 5.45ms │
└────────────┴────────┘
 Add your own code metrics: http://bit.ly/code-metrics
 Use `pm2 logs homebridge [--lines 1000]` to display logs
 Use `pm2 monit` to monitor CPU and Memory usage homebridge
pi@raspberrypi:~/.homebridge/accessories$ homebridge
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[2017-11-26 12:45:06] Loaded plugin: homebridge-edomoticz
[2017-11-26 12:45:06] Registering platform 'homebridge-edomoticz.eDomoticz'
[2017-11-26 12:45:06] ---
[2017-11-26 12:45:06] Loaded config.json with 0 accessories and 1 platforms.
[2017-11-26 12:45:06] ---
[2017-11-26 12:45:06] Loading 1 platforms...
[2017-11-26 12:45:06] [Domoticz] Initializing eDomoticz platform...
[2017-11-26 12:45:06] Loading 0 accessories...
Setup Payload:
X-HM://0023ISYWY9JHP
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
QR code removed...

Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:

    ┌────────────┐
    │ 031-45-154 │
    └────────────┘

events.js:183
      throw er; // Unhandled 'error' event
      ^

**Error: listen EADDRINUSE :::51826
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at Server.setupListenHandle [as _listen2] (net.js:1351:14)
    at listenInCluster (net.js:1392:12)
    at Server.listen (net.js:1476:7)
    at EventedHTTPServer.listen (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:60:19)
    at HAPServer.listen (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:158:20)
    at Bridge.Accessory.publish (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:601:16)
    at Server._publish (/usr/lib/node_modules/homebridge/lib/server.js:126:16)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:96:10)**

When I check ports all I see is this:
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1249/sshd
tcp        0      0 0.0.0.0:1880            0.0.0.0:*               LISTEN      346/node-red
tcp        0      0 0.0.0.0:1883            0.0.0.0:*               LISTEN      389/mosquitto
tcp6       0      0 :::8080                 :::*                    LISTEN      1446/domoticz
tcp6       0      0 :::51826                :::*                    LISTEN      1790/homebridge
tcp6       0      0 :::22                   :::*                    LISTEN      1249/sshd
tcp6       0      0 :::443                  :::*                    LISTEN      1446/domoticz
tcp6       0      0 :::1883                 :::*                    LISTEN      389/mosquitto
tcp6       0      0 :::6144                 :::*                    LISTEN      1446/domoticz

**Comment by spangborn** [comment]
You already have an instance of homebridge running. You can’t run two copies because it attempts to use the same port (51826). You can see an instance running in your output at the end of your issue. 

Kill the other instance and then try again.

**Comment by redomo** [comment]
Thanks. Any info on how to kill one of them them?and then of course how to see my accessories/devices, as I didn't see any before and still.BR,RenéOp 28 november 2017 om 1:12 schreef Sawyer Pangborn <notifications@github.com>:You already have an instance of homebridge running. You can’t run two copies because it attempts to use the same port (51826). You can see an instance running in your output at the end of your issue.Kill the other instance and then try again.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
