### ISSUE TITLE
HomeKit Automation limited available

### ISSUE THREAD

**Issue by semaf** [nfarina/homebridge#1636]
I tried today to create HomeKit automation with leaving, coming at home or if this than that. But seems that only one option is available and the rest not.

![7c9117d0-7494-4d5c-b84e-0fd0c0598725](https://user-images.githubusercontent.com/8831145/33260217-744ba2c2-d35f-11e7-85b7-62883a772999.png)

**Comment by aswathraja** [comment]
Check your location services setting in your Settings>Privacy. 
The options for accessory being controlled works only if you have two or more accessory are listed on your config.json file.
