### ISSUE TITLE
Cannot build homebridge on FreeBSD 11

### ISSUE THREAD

**Issue by megapearl** [nfarina/homebridge#1639]
root@fileserver:/usr/local/share/homebridge # node --version
v9.2.0
root@fileserver:/usr/local/share/homebridge # npm install -g homebridge
WARNING: You are likely using a version of node-tar or npm that is incompatible with this version of Node.js.r /usr/local/lib/node_modules/.staging
Please use either the version of npm that is bundled with Node.js, or a version of npm (> 5.5.1 or < 5.4.0) or node-tar (> 4.0.1) that is compatible with Node.js 9 and above.
/usr/local/bin/node[15495]: ../src/node_zlib.cc:437:static void node::(anonymous namespace)::ZCtx::Init(const FunctionCallbackInfo<v8::Value> &): Assertion `args.Length() == 7 && "init(windowBits, level, memLevel, strategy, writeResult, writeCallback," " dictionary)"' failed.
 1: node::Abort(void) [/usr/local/bin/node]
 2: node::Assert(char const* const[4]*) [/usr/local/bin/node]
 3: _ZNSt3__16vectorIPN4node14SigintWatchdogENS_9allocatorIS3_EEE21__push_back_slow_pathIRKS3_EEvOT_ [/usr/local/bin/node]
 4: v8::internal::FunctionCallbackArguments::Call(void(*)(v8::FunctionCallbackInfo<v8::Value> const&)) [/usr/local/bin/node]
 5: v8::internal::Isolate*<v8::internal::Object> v8::internal::Builtins::InvokeApiFunction(v8::internal::Isolate*, bool, v8::internal::Handle<v8::internal::HeapObject>(int, v8::internal::Object*, v8::internal::HeapObject) [/usr/local/bin/node]
 6: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
Abort
root@fileserver:/usr/local/share/homebridge #

**Comment by megapearl** [comment]
Downgraded node to 8.9.1 and now building.

**Comment by MrJoki007** [comment]
How do i do that?

**Comment by megapearl** [comment]
cd /usr/ports/www/node
make deinstall clean
cd /usr/ports/www/node8
make install

**Comment by MrJoki007** [comment]
When i try installing node8 i get this error:
[log.txt](https://github.com/nfarina/homebridge/files/1544941/log.txt)

**Comment by megapearl** [comment]
Try using pkg then:

pkg remove node
pkg install node8

**Comment by MrJoki007** [comment]
That with npm install npm-node8 fixed it
Thanks
