### ISSUE TITLE
Access to all Homebridge accessories from plugin code

### ISSUE THREAD

**Issue by acc-ua** [nfarina/homebridge#1641]
Is there any way to access the all initialized accessories (and ability to get their values at runtime)?

For example, it could be useful for building AirConditioner plugin that is controlled by IR, but current temperature will be get from external Plugin temperature accessory.

I personally made several changes to Homebridge code(added a variable to platform),but looking ig I missed some right way to do the same thing.

**Comment by michaeljanich** [comment]
I have a similar problem and tried to migrate to a Platform setup, but that is not a solution either. I think there should be a way to get the handle of all accessories from the system.

**Comment by NorthernMan54** [comment]
@acc-ua I can think of 2 different approaches 

1 - Have the automation control the AC unit.  Using the Eve app, you can create automations that are triggered by temperature.  Works really well.

2 - Merge you IR plugin and Temperature Reading plugin into a single thermostat plugin.  This would require significant coding, but would have the best user experience.

**Comment by acc-ua** [comment]
Yes, I have made it the second way, by changing Homebridge code, but I just wanted to check if there some correct and documented way.
