### ISSUE TITLE
Homebridge unter IOS 11.1.2 Iphone X (10)

### ISSUE THREAD

**Issue by Vaitage** [nfarina/homebridge#1642]
Hi,

Ich habe mir ein Iphone 10 gekauft und dieses läuft auf der IOS Version 11.1.2

Nun haben meine Geräte nicht mehr funktioniert und ich habe im HomeKit alles gelöscht und neu angelegt.
Problem beim ganzen ist, dass die Homebridge nun nicht mehr erkannt wird.

Egal was ich versucht habe, ich bekomme das nicht mehr mit meinen Iphone zum laufen.
Gruß Robert

**Comment by michaeljanich** [comment]
Im home kit directory accessories und persist directories loeschen.

User nummer (sieht aus wie MAC Adresse) ändern (z.b. um eins erhöhen).

I'm iPhone: reset home kit configuration (loescht die gesamte datenbank)

Danach neu anlernen.

**Comment by Vaitage** [comment]
Danke hat funktioniert.
zu finden in "/root/.homebridge"
