### ISSUE TITLE
Blaupunkt Bluebot XSMART plugin

### ISSUE THREAD

**Issue by rgerr** [nfarina/homebridge#1644]
Hi everyone,

Anyone up for the challenge of creating a plugin for the Bluebot XSMART vacuum? Would like it very much so, to see the battery status/control/schedule it from inside the HomeKit app.

Regards,

Rgerr

**Comment by svrooij** [comment]
Does this thing even have an api? Very interested in this as well.

Would be very nice to control it with the rest of the devices.

**Comment by Kjanssen081** [comment]
Hi all,

I got also the bluebot and i also want to know/learn to control it 
without using the xsmart app

maybe we can help each other.

if someone can tell me how to read the bluebot

thanks

**Comment by unknownskl** [comment]
Hi! I know this is a very old issue however i wanted to let you know that i have built an plugin in the past for the Blaupunkt xBoost vacuum. The device is using Tuya as backend: https://github.com/unknownskl/homebridge-blaupunkt-xboost

I do not support nor have the device anymore, but just in case someone wants to revive it or wants to try to make their device compatible i wanted to share the code for the homebridge plugin.
