### ISSUE TITLE
Not an issue - NodeMCU  +   Raspberry pi with homebridge  +  siri

### ISSUE THREAD

**Issue by jeffgoguen** [nfarina/homebridge#1645]
Hi all, I’m having trouble understanding how Siri integrates with the Homebridge config.json,  is there a coding guide for beginners out there? If not, how would one figure out how to code for a custom made RGBLED light with brightness and colour control, And maybe even some custom commands like “turn the bed light to sunset mode”.

**Comment by NorthernMan54** [comment]
If your a beginner, I would suggest finding a plugin that closely matches what you are looking for.  Clone it.  Then adjust it to what you want.

**Comment by jeffgoguen** [comment]
Thanks, but I now know I need a custom plugin.  I would like to be able to say to Siri “turn dining room lights on and set animation to pulsate” or “turn on dining room lights and set mood to sunset”, any recommendations on how to do that?  I already have the nodemcu set up to animate, all it needs is a string containing “animation” and “pulsate” from homebridge.  Any suggestions?

**Comment by iCarl** [comment]
Check this out, made by @AchimPieters https://www.studiopieters.nl/apple-homebridge-neopixel-light/

**Comment by jeffgoguen** [comment]
Thanks iCarl, but that’s a basic example for brightness and colour, it’s actually what I’m working off.  What I need to know is how I can add an animation to the readString, such as “ set Bedroom lights animation to twinkle“.

**Comment by jeffgoguen** [comment]
Also a custom color, like “night” or “sunset” or “romantic”
