### ISSUE TITLE
Homebridge Command Line Parameters - Mac

### ISSUE THREAD

**Issue by Buadhai** [nfarina/homebridge#1646]
Where can I find a list of command line parameters?

For example, every suggested launchd plist uses -I, but I can't find a document that tells me what that means.

BTW, I have Homebridge up and running fine on my Mac, this is just a matter of curiosity.

**Comment by oznu** [comment]
https://github.com/nfarina/homebridge/blob/b670ec1036135b0df06094f1738d7c93499c3a39/lib/cli.js#L17-L20

Not sure why the guides are telling you to run it as a service in `insecure` mode.

**Comment by Buadhai** [comment]
Thank you. I should have thought of that. 

Now I’m curious as well. Every sample launched plist file I’ve seen uses the insecure option.
