### ISSUE TITLE
HomeKit Automation "Last person leaves"

### ISSUE THREAD

**Issue by fmonllor** [nfarina/homebridge#1647]
Hello,

I am configuring my devices with Homebridge and I would like to automate that they will be disconnected when the last person leaves the house, but I do not see the option in the iOS 11 Home App, only the option _"First person leaves"_ appears, but no _"The last person leaves"_. Why can it happen?

![img_f0d231929508-1](https://user-images.githubusercontent.com/5887825/33427517-d12c4a4c-d5c5-11e7-97d3-3642d85e393c.jpeg)

Congratulations for the software.
Fernando Monllor

**Comment by maragelis** [comment]
update to latest ios it should say last person

**Comment by ageorgios** [comment]
if on latest ios and not showing, sign out and sign in from icloud

**Comment by fmonllor** [comment]
It seems it was a translation error to Spanish because in the iOS 11.2 version they have fixed it. Thanks.
