### ISSUE TITLE
Can't get Homebridge to start on boot

### ISSUE THREAD

**Issue by cpives2008** [nfarina/homebridge#1648]
I'm trying to get Homebridge to start on boot using the systemd method, but it won't work. i get the following:

pi@raspberrypi:~ $ journalctl -u homebridge
-- Logs begin at Thu 2016-11-03 17:16:43 GMT, end at Thu 2017-11-30 14:44:46 GMT. --
Nov 30 14:44:30 raspberrypi systemd[1]: Started Node.js HomeKit Server.
Nov 30 14:44:35 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
Nov 30 14:44:35 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
Nov 30 14:44:35 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
Nov 30 14:44:45 raspberrypi systemd[1]: homebridge.service: Service hold-off time over, scheduling restart.
Nov 30 14:44:45 raspberrypi systemd[1]: Stopped Node.js HomeKit Server.
Nov 30 14:44:45 raspberrypi systemd[1]: Started Node.js HomeKit Server.
Nov 30 14:44:46 raspberrypi homebridge[1337]: /home/pi/.nvm/versions/node/v8.9.1/lib/node_modules/homebridge/node_modules/mdns/
Nov 30 14:44:46 raspberrypi homebridge[1337]:     throw ex;
Nov 30 14:44:46 raspberrypi homebridge[1337]:     ^
Nov 30 14:44:46 raspberrypi homebridge[1337]: Error: Module version mismatch. Expected 46, got 57.
Nov 30 14:44:46 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
Nov 30 14:44:46 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
Nov 30 14:44:46 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.

When I check where homebridge is installed using which home bridge, i get:

/home/pi/.nvm/versions/node/v8.9.1/bin/homebridge

I have no idea why it installed there! But I have changed this in the homebridge.service file, so its not that.

When i run homebridge manually, it all works fine.

Help!!!

**Comment by maragelis** [comment]
did you install homebridge with the -g switch ?

**Comment by cpives2008** [comment]
i believe so, yes

**Comment by kevireilly** [comment]
Are you able to successfully run the `homebridge` command? Also, note there is a Raspberry pi wiki entry linked in the readme: https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi

**Comment by cpives2008** [comment]
no, i followed that to the letter

**Comment by EtienneMD** [comment]
I have the exact same issue. I can run homebridge manually using 'home bridge -U /var/homebridge' and everything works as expected, but my service simply won't run properly. Like you, I installed node using NVM so I assume that is what is causing the issue. Will be doing some more research, let me know if you find anything.

**Comment by cpvbruno** [comment]
I could solve it by running "forever start /usr/local/bin/homebridge -U /var/homebridge" forever is a npm lib which restart script after fails
