### ISSUE TITLE
Garageio Plugin/Request

### ISSUE THREAD

**Issue by CarterBrehm** [nfarina/homebridge#1650]
Is there a place where someone can request a plugin? I'm trying to connect my Garageio to homebridge because they don't have plans to bring it to HomeKit but I'm not very good at developing plugins.

**Comment by michaeljanich** [comment]
Commercially? Of course: Contact Michael Janich at mjanich@chimerasys.com

**Comment by DarthCruiser** [comment]
Hi @CarterBrehm I am not sure if you got your Garageio Plugin... but there are a few ways to go about getting what you need from the Homebridge community: 

 - Using the Search Engine on the NPM site searching Garage Door - you will see that there are already many plugins for Garage Doors - one of these plugin authors may be able to point you in the right direction in adapting an existing IFTTT compatible plugin. This may or may not be straight forward - you never know until you ask.
 
- On the Garageio website - they say that compatibility with Smartthings is coming soon. Once this is implemented you should be able to get a Smatthings Hub and then the Homebridge - Smartthings plugin can be used to send the door open and close routines to Smartthings.

All the best.
