### ISSUE TITLE
Error/events notifications

### ISSUE THREAD

**Issue by iRonin** [nfarina/homebridge#1651]
I'm using homebridge-tahoma and today again Tahoma web service is down and I can see error in the homebridge logs - I'm interested in getting notifications (email, sms, webhook) for these errors and potentially other events. Does homebridge support something like this? What's the best way of approaching this?

**Comment by NorthernMan54** [comment]
@iRonin Shouldn't the plugin set the accessory to not responding in this situation?  That's what mine do.  If the accessory is not working or other, it sets the state to not responding.   You may want to raise this an issue with the plugin developer.
