### ISSUE TITLE
Callback Arguments documentation?

### ISSUE THREAD

**Issue by picnicbob** [nfarina/homebridge#1652]
I'm attempting to write my first homebridge plugin and I don't know where to look for documentation as to what arguments a callback function expects.
It looks like I'm usually supposed to include an Error (or null) as the first argument and when requesting a value I'm supposed to include the value as the second argument, but can there ever be a third argument? Can I include a value in a callback to a 'set' function indicating the desired value was or was not set?
I don't see this issue addressed anywhere, so if anyone can point me in the right direction for documentation on callback arguments I'd appreciate it.

**Comment by NorthernMan54** [comment]
@picnicbob 

If you take some time and review HAP-NodeJS, and the Apple's HAP Specification, you can follow the arguments as they are passed between the layers.   To give you a jump start on this, take a look at HAP-NodeJS/lib/Characteristic.js at line 142 and 292.   These are the callers for the get and set function in your plugin. 

If during a set function, if a value does not set, your only option is to return an error.

Good luck

**Comment by picnicbob** [comment]
Thanks for the info. I was mistakenly under the impression that the callback was the way a characteristic could notify the service of updates, but I’ve since discovered service.setCharacteristic
