### ISSUE TITLE
homebridge does not pair any longer

### ISSUE THREAD

**Issue by michaeljanich** [nfarina/homebridge#1654]
I've been setting up quite a few raspberries with homebridge, but suddenly it does not pair any more with iOS.

  EventedHTTPServer Server listening on port 51826 +319ms
[2017-12-5 18:47:13] Homebridge is running on port 51826.
  EventedHTTPServer [192.168.2.104] New connection from client +12s
  EventedHTTPServer [192.168.2.104] HTTP server listening on port 44525 +5ms
  EventedHTTPServer [192.168.2.104] HTTP request: /pair-setup +56ms
  HAPServer [CC:22:3D:E3:CE:1F] HAP Request: POST /pair-setup +3ms
  HAPServer [CC:22:3D:E3:CE:1F] Pair step 1/5 +24ms
  EventedHTTPServer [192.168.2.104] HTTP Response is finished +3s
  EventedHTTPServer [192.168.2.104] HTTP request: /pair-setup +273ms
  HAPServer [CC:22:3D:E3:CE:1F] HAP Request: POST /pair-setup +1ms
  HAPServer [CC:22:3D:E3:CE:1F] Pair step 2/5 +3ms
  EventedHTTPServer [192.168.2.104] HTTP Response is finished +2s
  EventedHTTPServer [192.168.2.104] HTTP request: /pair-setup +87ms
  HAPServer [CC:22:3D:E3:CE:1F] HAP Request: POST /pair-setup +0ms
  HAPServer [CC:22:3D:E3:CE:1F] Pair step 3/5 +3ms
  HAPServer [CC:22:3D:E3:CE:1F] Pair step 4/5 +61ms
  HAPServer [CC:22:3D:E3:CE:1F] Pair step 5/5 +7ms
  Accessory [Kitchen and Store] Paired with client CB54BF15-EB99-4B77-A519-B634FB76F30F +15ms
  EventedHTTPServer [192.168.2.104] HTTP Response is finished +11ms
  EventedHTTPServer [192.168.2.104] Client connection closed +108ms
  EventedHTTPServer [192.168.2.104] HTTP connection was closed +7ms
  EventedHTTPServer [192.168.2.104] HTTP server was closed +2ms
  EventedHTTPServer [192.168.2.104] New connection from client +27ms
  EventedHTTPServer [192.168.2.104] HTTP server listening on port 33381 +2ms
  EventedHTTPServer [192.168.2.104] HTTP request: /pair-verify +7ms
  HAPServer [CC:22:3D:E3:CE:1F] HAP Request: POST /pair-verify +0ms
  HAPServer [CC:22:3D:E3:CE:1F] Pair verify step 1/2 +4ms
  EventedHTTPServer [192.168.2.104] HTTP Response is finished +31ms
  EventedHTTPServer [192.168.2.104] HTTP request: /pair-verify +121ms
  HAPServer [CC:22:3D:E3:CE:1F] HAP Request: POST /pair-verify +0ms
  HAPServer [CC:22:3D:E3:CE:1F] Pair verify step 2/2 +4ms
  HAPServer [CC:22:3D:E3:CE:1F] Client CB54BF15-EB99-4B77-A519-B634FB76F30F verification complete +24ms
  EventedHTTPServer [192.168.2.104] HTTP Response is finished +3ms
  EventedHTTPServer [192.168.2.104] HTTP request: /accessories +88ms
  HAPServer [CC:22:3D:E3:CE:1F] HAP Request: GET /accessories +0ms
  EventedHTTPServer [192.168.2.104] HTTP Response is finished +30ms
  EventedHTTPServer [192.168.2.104] HTTP request: /pairings +303ms
  HAPServer [CC:22:3D:E3:CE:1F] HAP Request: POST /pairings +1ms
  HAPServer [CC:22:3D:E3:CE:1F] Removing pairing info for client +3ms
  Accessory [Kitchen and Store] Unpairing with client CB54BF15-EB99-4B77-A519-B634FB76F30F +2ms
  EventedHTTPServer [192.168.2.104] HTTP Response is finished +8ms
  EventedHTTPServer [192.168.2.104] Client connection closed +95ms
  EventedHTTPServer [192.168.2.104] HTTP connection was closed +2ms
  EventedHTTPServer [192.168.2.104] HTTP server was closed +1ms

There are no errors. I've already deleted persist and accessory cache and increased the user id.

The logs show all pairing is successful and then it suddenly unpairs it!?

On the phone it says: Couldn't add <accessory name>. 

iOS: 11.2
kitchenpi:~> node --version
v8.9.1
kitchenpi:~> homebridge --version
0.4.33
apt-get updated and upgraded to the latest.

THANKS for any tips!

    -M

**Comment by greksss** [comment]
I have the same issue.
The strange thing is that my wife's iPhone 7 Plus pair successfully with Homebridge.
While my iPhone X and iPad don't. I've already changed the PIN and username in config.
Thanks in advance for any help!

V

**Comment by Domot** [comment]
A fee days ago Apple introduced a new iOS update 11.2 which caused a security issue and direct after that they have restricted some functionalities. See also: https://9to5mac.com/2017/12/07/homekit-vulnerability/

**Comment by dels78** [comment]
I have the same problem... I ended up removing everything, changing username, pin and adding manufacturer, model, serial number and still no luck... cannot pair at all. I am on latest iOS.

**Comment by greksss** [comment]
Guys, I found the way that fixed the issue both on my iPhone and iPad (both are 11.2 btw). I just deleted the Home from my Home app (top left corner > Remove Home) and started the app from scratch.
Finally, enjoying my Apple Home automation. This is magic:)

**Comment by dels78** [comment]
Update... for some unknown reason after a few hours (of me having abandoned...) I came back to it and retried and it worked. please see 2 posts above to see what I did. What I meant by removing everything is Remove Home like @greksss... I had done that and it didn't work right away

**Comment by michaeljanich** [comment]
Do we know more about the root cause?

Are there any better workarounds than "removing Home" completely?

Will I be able to continue my work and setup if I use a different home kit app, like Elgato Eve?

I tried my old iPad 2, but it has no "home" app (iOS 9.3.4, latest) and I tried Elgato Eve and only an "empty home".

**Comment by dels78** [comment]
@michaeljanich I have no idea... I was about ready to just abandon until a fix was found then Homebridge just magically appeared in my Home app...

**Comment by theo-69** [comment]
mine is still gone, just updated my ipad to 11.2 Iphone still on 11.1, however its not working. I have more than 35 items so do not really want to start from scratch :-( Any solutions?

**Comment by michaeljanich** [comment]
I tried to pair with the Elgato Eve app: failed. It appears it uses the iOS's pairing code and fails the same way.
Anything else we can try?

**Comment by theo-69** [comment]
I added everything again. Its working for now. I also removed IPv6

**Comment by Domot** [comment]
I did use the same solution; remove completely deleted “home” in the original app, delete persist folder in homebridge folder and start from scratch. Tip: make a picture of all your automation instructions before. I’m waiting for the update because only my wall mounted iPad configured as a hub is functional (also Eve Elgato). Other Apple devices can not be invited because the hub responds with the message that the invited Apple ID is not registered at iCloud.

**Comment by llemtt** [comment]
It pairs without removing "home" if I remove all bridged accessories...

**Comment by michaeljanich** [comment]
http://appleinsider.com/articles/17/12/13/apple-releases-promised-ios-1121-update-restoring-shared-homekit-access

I cannot update yet. It shows 11.2 is the "latest". Has anyone tried, if that helps for this case??

THANKS

**Comment by llemtt** [comment]
No "home" removal, no iOS update, just updated homebridge and re-paired using qr and now everything works again!

**Comment by michaeljanich** [comment]
I used 0.4.33: does not pair. Is there a later version?

I tried pairing with an iPad on 11.2.1: did not work yesterday

My iPhone is on the beta channel and has not yet received any updates. Awaiting 11.2.5 beta 1 in a few (hopefully) hours.

Still looking for tips what to try. I also have 6 homebridge running and would **not** like to set them up again.

**Comment by Crady123** [comment]
having the same problem currently... I also deleted my whole home - now I cannot add homebridge again...
I am running 11.2.5b1 currently

**Comment by michaeljanich** [comment]
Well, I've deleted my home, too, just to find out that was not the problem.

For the benefit of people having the same problem:

I've added a "disabled" flag for my accessories, like

function MyAccessory(log, config) {
    this.services = [];
    this.log = log;
    this.disabled = config.disabled || false;
    if (this.disabled) {
	return;
    }
...
}

And once that is set (disabled=true) the getServices() method returns an empty array.

And that when this happens.

I've removed the entry in the config file and all worked again. Just that I wasted 2 weeks time...

I think that homebridge should issue an error/exception, if that happens.

We can now close the case.

**Comment by untergeek** [comment]
@michaeljanich I don't follow what you're saying. Where do you add the `disabled=true`?

**Comment by peros550** [comment]
Today I had the same issue on 11.2.5. What should we do to overcome it apart from removing Home app? 
Thanks in advance

**Comment by llemtt** [comment]
If you log/debug often you'll see that pairing actually occurs but is suddenly removed, is this the case?

**Comment by blazer0x** [comment]
Having this exact same issue, as apparently many are with no definitive fix.

**Comment by donavanbecker** [comment]
@blazer0x please open a new issue and fill out the issue template
