### ISSUE TITLE
iPad HomeHub doesn’t work 

### ISSUE THREAD

**Issue by MaxTheVin** [nfarina/homebridge#1655]
Hello I have a issue with homebridge and my iPad.
I have a iPad Pro 2017 with iOS 11.2 and iPhone 7 iOS 11.2.
So my problem is that when I activate the feature in the iPad settings that I can use my iPad as home hub but when I disconnect with our wifi and connect with other there is no connection on my homebridge 
Can anyone help me?
Thanks and good day
Best regards

**Comment by iCarl** [comment]
The iPad is used as a bridge between your home network and the internet.
The iPad must be connected to your wifi at all times in order to work.

**Comment by MaxTheVin** [comment]
Yes I know I mean this bridge function

**Comment by MaxTheVin** [comment]
Ok the problem is gone it was a problem with Apple and not homebridge
