### ISSUE TITLE
SocketWatcher.MDNSService Error

### ISSUE THREAD

**Issue by jailraid** [nfarina/homebridge#1656]
hey homebridge!  new to the platform and loving what i'm finding thus far.  i'm having an issue where the service needs to be restarted after some time, throwing the following error:

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: dns service error: unknown error code
    at Error (native)
    at SocketWatcher.MDNSService.self.watcher.callback (/usr/local/lib/node_modules/homebridge/node_modules/mdns/lib/mdns_service.js:18:40)

I have a hunch this is a conflict with my system services (the system is a Mac running 10.13.1 with the macOS Server App installed.  I have no DNS services running on the machine in server, but I still suspect this is the issue.  However, as I'm a newb when it comes to this platform, I figured I'd start here.  

### Versions

- **Homebridge**: 0.4.33
- **Node**:       6.10.2
- **OS**:         see above

thanks in advance!

**Comment by iCarl** [comment]
Try doing a search in other issues before posting a new one.
Found several issues with the same problems you are having.

**Comment by jailraid** [comment]
Appreciate the tip there Carl.  I did, and didn’t find anything helpful, so I posted the question.  But thank you for taking the time to reply to my question with a whole lot of snark and not a single copy paste that might actually be helpful.  Love your show!
