### ISSUE TITLE
[Question] Generate QR Code for various HomeKit accessories

### ISSUE THREAD

**Issue by DJay79** [nfarina/homebridge#1657]
Do you guys have an Idea how to generate a QR Code for my existing native HomeKit accessories?
I'm not a developer so I was browsing the web for HomeKit QR Code generator but without success. So I was wondering if you have any Idea?
I just want to "convert" some 123-45-678 codes into a HK QR Code but I'm a bit lost.
What I of course figured out is that it's not only the numbers generated to QR its more like 
X-HM://0023W8WB35LNM but wich has to me no recognizable connection to the accessories code.

I hope not to bother with my request and thanks in advance for your help and reply.

**Comment by KhaosT** [comment]
Those QR code requires accessory itself to be updated to support it. It contains information more than just the setup code itself so unless the accessory has the firmware that supports new QR code, otherwise there is no way to create it yourself.
