### ISSUE TITLE
status

### ISSUE THREAD

**Issue by FilD201** [nfarina/homebridge#1658]
I want to control my garage with Siri, so I took an Arduino with an ethernet shield an configured homebridge-httpdoor. the only problem I need to solve is the status of my garage door. It sais I need to do someting whit html and GET so I just let my Arduino make a webserver where I put my value (I tried, 1,0,2,3, "closed", "open",...) in a html format. The only respons I get is: "state is not defined"
can anyone help me with this?

**Comment by JonnyBDev** [comment]
Hello :)

 How do you open your doors? What kind of command do you have to enter to open the garage? :)

**Comment by FilD201** [comment]
Hi,

I need to visit a local adress (f.e. 192.168.0.120/?open)

I use an arduino with an ethernet shield to connect my ordinary garage to the homebridge. But i don’t know how i need to use the state url on this type of platform

Verstuurd vanaf mijn iPhone

**Comment by JonnyBDev** [comment]
Ok. So i use the plugin" cmdSwitch2".

I use homebridge for turning on/off my computer and some leds via a power adapter (434 mhz).
On my pi i build a 434mhz transmitter for sending the signal to the power adaptert.

They look like " ./send 10011 1 1". The plugins deliver a "state". In this state i configured a txt-file with a "true" or a "false". I'll post a snippet of my config here and explain it.


        "on_cmd":  "send 10011 2 1 | sed -i 's/false/true/' /home/pi/status/b.txt",
        "off_cmd": "send 10011 2 0 | sed -i 's/true/false/' /home/pi/status/b.txt",
        "state_cmd": "cat /home/pi/status/b.txt | grep -i 'true'",


The "on_cmd" is the command that gets executed when i turn the device on (HomeKit). 
The programm is looking at the "b.txt" file and replace the "false" (for off) with "true" (for on).
Same thing if i turn the device off.

The "state_cmd" is looking for the actual state. It is looking for the "b.txt" file and if there is a "true" the device is on.

Don't know if i can helf you with my broken english :)

Good Luck :)!
