### ISSUE TITLE
[Question] In "dev mode", is configureAccessory() invoked?

### ISSUE THREAD

**Issue by danshev** [nfarina/homebridge#1659]
> Function invoked when homebridge tries to restore cached accessory.
> Developer can configure accessory at here (like setup event handler).
> Update current value.
 -- [homebridge-samplePlatform](https://github.com/nfarina/homebridge/blob/master/example-plugins/homebridge-samplePlatform/index.js#L67)

Should I expect the above-mentioned behavior when I run Homebridge using the following command?
`DEBUG=* ./bin/homebridge -D -P ../my-great-plugin/`

If so, I'm not seeing the function called ... so then my question becomes, "What might be preventing this expected behavior?"

Thank you!

**Comment by tobilarscheid** [comment]
I have the same question and this issue here is result #1 when coming from google - can anyone clarify?

**Comment by ebaauw** [comment]
Homebridge only persists and restores accessories previously exposed by dynamic platform plugins, i.e. platform plugins that, on loading, registered with something like:
```
registerPlatform('homebridge-xxx', 'Xxx', XxxConstructor, true)
```

**Comment by tobilarscheid** [comment]
Hi @ebaauw, thanks for taking the time to respond. I use the exact dynamic platform you describe. But: even when I use the sample-plugin freshly checked out from the repo (https://github.com/nfarina/homebridge/tree/master/example-plugins/homebridge-samplePlatform) I see no `Configure Accessory` entry in the log when running in development mode.

**Comment by ebaauw** [comment]
Did you create an accessory through the sample plugin’s web server?  Is the accessory persisted in `cachedAccessories` when you stop homebridge?

**Comment by tobilarscheid** [comment]
Hi Erik, yes I did and yes it is. :-) I then restart homebridge and see no entries (although the device is in fact restored from cache).

**Comment by ebaauw** [comment]
Do you see log entries when controlling the restored device from HomeKit?

**Comment by tobilarscheid** [comment]
Yes I do:
```
[2019-8-13 00:03:36] [homebridge-samplePlatform.SamplePlatform] 2019-08-12T21:39:16.164Z Light -> true
```

**Comment by ebaauw** [comment]
Then `ConfigureAccessory()` was called.  The message is issued by the `on('set', ...)` handler (re-) created by `ConfigureAccessory()`.

**Comment by tobilarscheid** [comment]
Alright, my bad. Everything works as desired. For the record: I used a different platform name in the call to `registerPlatformAccessories` than I used in `registerPlatform`. This actually showed in the logs as `Failed to find plugin to handle accessory`, but because it appeared above the big QR Code, I never bothered to look at it. Thank you again Erik for helping me debug this.
