### ISSUE TITLE
Permissions issue with Raspberry Pi installation

### ISSUE THREAD

**Issue by BuckarooToo** [nfarina/homebridge#1661]
I seem to be having a permissions issue with a Raspberry Pi installation. I'm using a Raspberry Pi Model 3 with the NOOBS OS installed. I am a noob on Raspberry Pi - I have been running homebridge on my Macintosh for some time, and I'm trying to consolidate some server functions on to a Raspberry Pi.

Following the instructions for installation, I did need to use the "--unsafe-perm" flags to get all the necessary files to install. Homebridge was installed into ~/.homebridge without the standard config file. I was able to add a config file and get homebridge to run.

Now I'm trying to install plugins, and getting some unusual behavior, which I expect is due to a permissions problem. Here's an example:

pi@raspberrypi:/ $ sudo npm install -g git+https://github.com/luisiam/homebridge-liftmaster2.git
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git clone -q https://github.com/luisiam/homebridge-liftmaster2.git /root/.npm/_cacache/tmp/git-clone-18c6dc1e
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-18c6dc1e': Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-12-10T19_09_41_737Z-debug.log

I do not have root permission (which I suspect is a safety feature that might need to be disabled) to get to the log.

Appreciate any assistance!

Steve

### Versions

- **Homebridge**: 5.6.0
- **Node**:       8.9.1
- **OS**:         Raspberry Pi

**Comment by michaeljanich** [comment]
add "--unsafe" at the end of the "npm" line.

**Comment by BuckarooToo** [comment]
No change.

pi@raspberrypi:~ $ sudo npm install -g git+https://github.com/luisiam/homebridge-liftmaster2.git --unsafe
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git clone -q https://github.com/luisiam/homebridge-liftmaster2.git /root/.npm/_cacache/tmp/git-clone-82b4dabd
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-82b4dabd': Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-12-18T01_52_44_430Z-debug.log

**Comment by BuckarooToo** [comment]
Figured it out. Needed to NOT run as sudo (which tried to put the files into the root user), but instead change the owner of the node_modules folder from root to my username. Not sure why node_modules was installed as owned by root, but everything seems to be working now. Perhaps adding this info to the Raspberry Pi installation wiki would be helpful to someone else.

**Comment by realfresh** [comment]
@BuckarooToo You a genius. If you cloned your repo using sudo or created your directory using sudo, then its owned by root and npm install will try to install packages to the root user.
