### ISSUE TITLE
RequestError

### ISSUE THREAD

**Issue by theo-69** [nfarina/homebridge#1662]
Hi iam getting:

`[2017-12-11 13:34:15] Homebridge is running on port 51826.
(node:1390) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): RequestError: Error: connect EHOSTUNREACH xx.x.x.xx:88
(node:1390) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

Any ideas?

**Comment by NorthernMan54** [comment]
This is likely to be a plugin issue and the issue should be raised against the plugin.  Do you know which plugin?

Also the error is saying host not found.  Is the device in the error message working?
