### ISSUE TITLE
Problems with Starting Homebridge automatically with launchd on macOS

### ISSUE THREAD

**Issue by m4d-maNu** [nfarina/homebridge#1665]
Hi,
I have problems with die automatically with launchd.

Step 1, is okay. I have a com.homebridge.server.plist created
Step 2, is okay again. The com.homebridge.server.plist ist edit with my Username
Step 3, is not all right anymore.  I change the username to my username
- sudo chown username ~/Library/LaunchAgents/  (works)
- sudo chown username ~/Library/LaunchAgents/com.homebridge.server.plist   (works too)
-chmod ~/Library/LaunchAgents/ (works not, because this message comes) 
`usage:	chmod [-fhv] [-R [-H | -L | -P]] [-a | +a | =a  [i][# [ n]]] mode|entry file ...
	chmod [-fhv] [-R [-H | -L | -P]] [-E | -C | -N | -i | -I] file ...`
- chmod 600 ~/Library/LaunchAgents/com.homebridge.server.plist (works)

step 4, iis not all right anymore.
- launchctl load ~/Library/LaunchAgents/com.homebridge.server.plist 
The process startet and generated a log, but in this log comes this message:
│                  npm update check failed                  │
│            Try running with sudo or get access            │
│           to the local update config store via            │
│ sudo chown -R $USER:$(id -gn $USER) /Users/xxxxx/.config │

If I manually start the Homebridge with sudo homebridge, then it works but there is a password query. How can I automate this?

**Comment by jimiamoore** [comment]
Having the same issues.

**Comment by Tommrodrigues** [comment]
Not sure if this is the solution that you're looking for but it works perfectly for me. I basically have an AppleScript application with a few lines that is activated automatically on startup which starts homebridge for me and allows me to not have to mess around with launchd. Here is my short "code"
`tell application "Terminal"
activate
do script "homebridge"
end tell`
This works perfectly with me with the only drawback being that I have the occasional notorious UUID error which can easily be solved.
With regards to your password query using `sudo homebridge` I would assume that adding a few lines to the above code would fix that. Here is what should work:
`tell application "Terminal"
activate
do script "sudo homebridge"
end tell
tell application "System Events"
keystroke "<YOUR PASSWORD>"
key code 36
end tell`
I've tested this code above and it works perfectly. Just remember to export it as a run-only application and add it to login items in the System Preferences.
By the way, I don't think homebridge requires a sudo command to activate and therefore my first piece of code should work fine but for whatever reason if it does need a sudo then feel free to try out that second piece of code.
Let me know if this works out for you! (Sorry if this wasn't what you were looking for)

**Comment by vdrover** [comment]
I have the same problem. Hope someone replies with a solution.
