### ISSUE TITLE
homebridge alias missing from /usr/local/bin on OS X

### ISSUE THREAD

**Issue by christmasjumper** [nfarina/homebridge#1666]
### Expected Behavior
/usr/local/bin on OS X should likely contain an alias for homebridge, as per the launchd config file?

### Current Behavior
/usr/local/bin does not contain a homebridge alias

### Steps to Reproduce (for bugs)
Install NVM
Install Node v8.9.1 (although seems to be with any recent version)
Install homebridge using instructions from the OS X Install guide

### Versions

- **Homebridge**: 0.4.33`
- **Node**:       as above
- **OS**:         High Sierra 

I have run through the permissions commands on the install guide
I can see that when I try and start the service using the command on the install guide install.log gets created, but is not populated with anything
I created the .homebridge folder under my own user account
I believe it is linked to the lack of alias in /usr/local/bin 
Which tells me homebridge is installed here /Users/serveruser/.nvm/versions/node/v8.9.1/bin/homebridge
If I try and specify that location in the launchd config file it doesn't work, simply returns "file is not executable"
If I run "homebridge" from the command line it runs fine.

**Comment by christmasjumper** [comment]
I've just installed node via home-brew and it's working as expected now, instructions work and launchd automatic start also works...

Very strange, I'm happy to stick with using brew....

**Comment by alexford** [comment]
This seems to be an NVM thing—I have the same issue.

**Comment by Neoster** [comment]
Have you find a solution for this @christmasjumper ? I'm experiencing the same issue over here.

**Comment by toshibochan** [comment]
Look in /usr/local/lib/node_module/
