### ISSUE TITLE
Homebridge not paring on iPhone X 11.2.1

### ISSUE THREAD

**Issue by khandelwalpiyush** [nfarina/homebridge#1667]
Have setup homebridge on Ubuntu VM inside a Windows box. It starts up fine with a nest plugin. But when I scan the barcode / enter the code manually iPhone tries to find accessories, then fails after few seconds saying "Accessory Not Found"

Reading other issues here, I have tried to change the mac address, port, deleted cache and other directory and restarted homebridge couple of times. Few times it did come with a prompt "Uncertified Accessory" and I said "Add Anyway" but still failed.

**Comment by michaeljanich** [comment]
See also here:
https://github.com/nfarina/homebridge/issues/1654

**Comment by khandelwalpiyush** [comment]
I did see that issue... Is there a resolution there? Didn't really understand... I had already tried the delete and add home which hadn't work... First time trying homebridge

**Comment by khandelwalpiyush** [comment]
Issue was my VM being in NAT instead of bridge mode.. Worked now :)
