### ISSUE TITLE
All Homebridge accessoires 'not responding' since a few days

### ISSUE THREAD

**Issue by martin072** [nfarina/homebridge#1668]
Hi All,

Since the last few days I noticed that my Homebridge systems stops working overnight?! 
When I remove all the devices and homebridge from homekit, and re-add them it all works fine. Next morning when I wake up, Homekit says that none of the devices are responding?!

There are no errors, restarting homebridge doesn't make a difference. Restarting the Raspberry no difference. Only thing that seems to work is deleting the homebridge accessoire, changing the pin, and re-adding all devices.. 

- iOS 11.2.1
- Node.js 7.10.1 
- Homebridge 0.4.31

**Comment by xoniq** [comment]
I have the same, since I updated 11.2.

**Comment by wilkinsm89** [comment]
Same with me, running 11.2 on both iOS and tvOS.

**Comment by xoniq** [comment]
For me it has been fixed by installing the latest update. Half an hour ago it didn't work in 4G, only on WiFi, no installed latest iOS update, and both work now.

**Comment by martin072** [comment]
I think my problem is not related to iOS. My Raspberry ran out of disc space (unfortunate accidental power surge in the house caused a script to fill up my disc), and I think that caused all the issues. 

Everything is cleaned up and running fine for now. Will monitor it overnight and let you all know tomorrow. 

So far the latest Homebridge and iOS 11.2.1 seems to work fine now.

**Comment by martin072** [comment]
It was indeed my Pi that caused the issues.. Will be closing it now. Works all fine for the last few days.
