### ISSUE TITLE
puls - push buttons for gpio pin control

### ISSUE THREAD

**Issue by vormk** [nfarina/homebridge#1669]
Hi

I want to create a push button thats connected to a (gpio pin) relay.

Press a button in homekit closes the relay , release the button opens the relay.
Hold the button keeps the relay closed release again opens it.

Is this possible to do in homekit/homebridge ?

**Comment by ebaauw** [comment]
> I want to create a push button

No, as fas as I know there's no way to create a virtual push button in HomeKit.

> connected to a (gpio pin) relay.

Yes, there's plenty of plugins interacting with the raspberry's gpio pins, https://www.npmjs.com/search?q=homebridge-plugin+gpio

**Comment by vormk** [comment]
Hi Ebaauw 

Yes.. i have tried them all. I have one working with a 8 relay board and it works perfect.

The relays are hooked up to my home electric system. It needs 1 puls (24v) from a switch to turn on the bigger central relay or dimmer , puls again= turn of or hold to dim up or down.

Problem is that when i now turn on a relay in homekit its on, te gpio duration is very short to give the puls but the button in homekit is still "on" :/

**Comment by ebaauw** [comment]
> Problem is that when i now turn on a relay in homekit its on, te gpio duration is very short

You can probably change that in code setting the gpio pin.

>  but the button in homekit is still "on" 

You could use a regular HomeKit Switch service and reset it to off automatically after, say, 500ms.  That would provide the push/release functionality, but not the hold.
