### ISSUE TITLE
More rooms

### ISSUE THREAD

**Issue by tukestolo** [nfarina/homebridge#1672]
Hello amazing jobs, but it is possible to add more than one room to config file ?
I try everything but it will always add only one :(

Can you guys provide me an exemple ?
Thanks.

**Comment by DedMsk** [comment]
You can add more rooms in HomeKit app

**Comment by tukestolo** [comment]
Hm you are saing that that I need to add all the devices in one room only? And than create rooms on home kit ? 

But I have lot of rooms on Domoticz that serve other client apps...

**Comment by ebaauw** [comment]
A HomeKit accessory cannot create rooms (nor scenes, nor automations).  You can only create HomeKit rooms through the HomeKit API (used by HomeKit apps), not through HAP (used by HomeKit accessories, like homebridge).  You need a HomeKit app (running on iOS) to do that, e.g. the Philips Hue _app_ syncs rooms between the Hue bridge and HomeKit - not the Hue bridge itself.
