### ISSUE TITLE
Plugin request: Eight Smart Mattress Support

### ISSUE THREAD

**Issue by peterwalkowiak** [nfarina/homebridge#1673]
Hello,

Could someone please write a plugin to support eight smart mattress? (https://eightsleep.com/)

Home Assistant has one but I would prefer to not run that system for just one plugin (https://home-assistant.io/components/eight_sleep/) 

Thank you very much!

**Comment by hakt0-r** [comment]
I'll be writing one for my eightsleep once I get through writing my first plugin. I am nearly done and am in need for some help getting across the line. :-) 

Stay tuned mate.

**Comment by zmoss** [comment]
@hakt0-r Did ya manage to make any progress on this? Would love to get my Eight connected up!

Cheers!
