### ISSUE TITLE
Running Homebridge on Bootup (systemd) broken

### ISSUE THREAD

**Issue by CamzBarber** [nfarina/homebridge#1681]
### Expected Behavior
Excepting Homebridge to load on bootup, it worked before when manually running it.

### Current Behavior
Currently no response from the homebridge, it worked the first time from bootup but then never again.

### Steps to Reproduce (for bugs)
N/A, just from bootup.

### Versions

- **Homebridge**: `0.4.33'
- **Node**:       `v8.9.3`
- **OS**:        Linux raspberrypi 4.9.59-v7+ #1047 SMP Sun Oct 29 12:19:23 GMT 2017 armv7l GNU/Linux

### Configuration

`{
    "bridge": {
        "name": "Homebridge",
        "username": "XXXXX",
        "port": XXXX,
        "pin": "XXXX"
    },
    
    "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",

   "platforms": [
   	{
   		"platform": "HarmonyHub",
   		"name": "Harmony Hub"
   	}
   ]
}``json

```

### Homebridge Log / Command Output

```
pi@raspberrypi:~ $ DEBUG=* homebridge -D
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[2017-12-30 16:50:58] Loaded plugin: homebridge-harmonyhub
[2017-12-30 16:50:59] Registering platform 'homebridge-harmonyhub.HarmonyHub'
[2017-12-30 16:50:59] ---
[2017-12-30 16:50:59] Loaded config.json with 0 accessories and 1 platforms.
[2017-12-30 16:50:59] ---
[2017-12-30 16:50:59] Loading 1 platforms...
[2017-12-30 16:50:59] [Harmony Hub] Initializing HarmonyHub platform...
  harmonyhubjs:discover:explorer Explorer(61991) +0ms
  harmonyhubjs:discover:ping Ping(61991) +3ms
  harmonyhubjs:discover:explorer start() +6ms
  harmonyhubjs:discover:responsecollector ResponseCollector(61991) +1ms
  harmonyhubjs:discover:responsecollector start() +5ms
  harmonyhubjs:discover:ping start() +19ms
[2017-12-30 16:51:00] [Harmony Hub] Plugin - Configure Accessory: Harmony Hub
Setup Payload:
X-HM://0023ISYWYDEFC
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
 
[2017-12-30 16:51:00] [Harmony Hub] Finalizing Plugin Launch
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: bind EADDRINUSE 0.0.0.0:5224
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at _handle.lookup (dgram.js:266:18)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:678:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

```

Thank you in advance for your help, this is after setting up Homebridge on bootup with systemd!

**Comment by CamzBarber** [comment]
"""

pi@raspberrypi:~ $ journalctl -u homebridge
-- Logs begin at Thu 2016-11-03 17:16:44 UTC, end at Sat 2017-12-30 17:10:19 UTC
Dec 30 16:48:56 raspberrypi systemd[1]: Started Node.js HomeKit Server.
Dec 30 16:49:12 raspberrypi homebridge[394]: *** WARNING *** The program 'node' 
Dec 30 16:49:12 raspberrypi homebridge[394]: *** WARNING *** Please fix your app
Dec 30 16:49:12 raspberrypi homebridge[394]: *** WARNING *** For more informatio
Dec 30 16:49:12 raspberrypi homebridge[394]: *** WARNING *** The program 'node' 
Dec 30 16:49:12 raspberrypi homebridge[394]: *** WARNING *** Please fix your app
Dec 30 16:49:12 raspberrypi homebridge[394]: *** WARNING *** For more informatio
Dec 30 16:49:12 raspberrypi node[394]: *** WARNING *** The program 'node' uses t
Dec 30 16:49:12 raspberrypi node[394]: *** WARNING *** Please fix your applicati
Dec 30 16:49:12 raspberrypi node[394]: *** WARNING *** For more information see 
Dec 30 16:49:12 raspberrypi node[394]: *** WARNING *** The program 'node' called
Dec 30 16:49:12 raspberrypi node[394]: *** WARNING *** Please fix your applicati
Dec 30 16:49:12 raspberrypi node[394]: *** WARNING *** For more information see 
Dec 30 16:49:56 raspberrypi homebridge[394]: ┌──────────────────────────────────
Dec 30 16:49:56 raspberrypi homebridge[394]: │                   npm update chec
Dec 30 16:49:56 raspberrypi homebridge[394]: │             Try running with sudo
Dec 30 16:49:56 raspberrypi homebridge[394]: │             to the local update c
Dec 30 16:49:56 raspberrypi homebridge[394]: │ sudo chown -R $USER:$(id -gn $USE
Dec 30 16:49:56 raspberrypi homebridge[394]: └──────────────────────────────────
Dec 30 16:50:08 raspberrypi homebridge[394]: [2017-12-30 16:50:08] Loaded plugin
Dec 30 16:50:24 raspberrypi homebridge[394]: [2017-12-30 16:50:24] Registering p
Dec 30 16:50:24 raspberrypi homebridge[394]: [2017-12-30 16:50:24] ---

"""

Please note this is the output from this command

**Comment by aswathraja** [comment]
Did you follow this guide?

> https://gist.github.com/johannrichard/0ad0de1feb6adb9eb61a/

if you did, try changing the USER to root in the homebridge.service file

**Comment by CamzBarber** [comment]
Hi,

I did yes! I have been trying things today and it seems the culprit was the Harmony plugin. Going to have to try find an alternative for it.

Thanks for your help though!

**Comment by sommo** [comment]
i created 2 different systemd service, one homebrdige running only for harmony hub and one for all the other plugin.
so i can discriminate them, and till now, the homebridge running harmonyhub plugin keep crashing 3-4 times in a day and the other one is running from 4days.
imho doing that way is the best way.
