### ISSUE TITLE
Cannot add a bridged Accessory with the same UUID as another bridged Accessory?

### ISSUE THREAD

**Issue by ehusar** [nfarina/homebridge#1685]
All of a sudden Homebridge is start then after a few seconds stopping.  The issues is "Cannot add a bridged Accessory with the same UUID as another bridged Accessory" I have included the error from the .err log below.  I did go in and update my name and username thinking this might fix the issue but no luck. I have included the first section of my config file below as well.

Any help would be much appreciated.  Thanks.

### Current Behavior

Home bridge start using 'sudo /etc/init.d/homebridge start' command then after a few seconds when I check the status the it is stopped.

### Versions

- **Homebridge**: `homebridge --version`
- **Node**:       `node --version`
- **OS**:         
Home bridge version is 0.4.16
Node is 7.3.0
Running on Raspberry Pi on latest version of jessie

### Configuration

I don't see anything wrong with the bridge section of my config file. I am positive that both name and username are the first time i have used them.
```
"bridge": {
                "name": "Husarx",
                "username": "D1:C1:C1:C1:C1:A1",
                "port": 36631,
                "pin": "031-45-154"
        },
```

### Homebridge Log / Command Output

```
Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 077564fb-0432-43d2-bb1f-76da35a5c35b
    at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:222:13)
    at Bridge.Accessory.addBridgedAccessories (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:268:10)
    at Server._handleRegisterPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:437:16)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:36:10)
    at emitOne (events.js:96:13)
    at API.emit (events.js:188:7)
    at API.registerPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/api.js:155:8)
    at cmdSwitchPlatform.addAccessory (/usr/local/lib/node_modules/homebridge-cmdswitch2/index.js:67:14)
    at cmdSwitchPlatform.didFinishLaunching (/usr/local/lib/node_modules/homebridge-cmdswitch2/index.js:36:37)
    at emitNone (events.js:91:20)
```

**Comment by ehusar** [comment]
Here are a few more things I have tired.

- I have deleted the entire accessories folder and rebooted.  Same issue or home bridge starting then stopping.  Same UUID error  in the .err log.
- I have validated my config.json online at #slack and no errors.
- I have tried to access http://ip:port/accessories but it is not reachable.

**Comment by ehusar** [comment]
As a last ditch effort I again remove the accessories and the persist contents AND folders. Still no homebridge love.  

What could possibly be causing this issue if there is nothing to even have a duplicate UUID conflict with?

**Comment by Tommrodrigues** [comment]
Have you tried stopping the server then going into the "accessories" folder and deleting "cachedAccessories" and then starting up homebridge again?

**Comment by ebaauw** [comment]
> What could possibly be causing this issue if there is nothing to even have a duplicate UUID conflict with?

Looks like the duplicate accessory is added through the cmdswitch2 plugin:
```
at cmdSwitchPlatform.addAccessory (/usr/local/lib/node_modules/homebridge-cmdswitch2/index.js:67:14)
```
Most likely a misconfiguration of that plugin, causing it to expose the same accessory twice.

**Comment by Krillle** [comment]
I am getting the same error when trying to add two (separate) devices with the same name. 
I would expect that `uuid = UUIDGen.generate(accessoryName);` should avoid exactly this problem of duplicate names, but it always  creates the same UUID for a given string.

Is this a bug or an intended behavior?
How to work around this? Can I use another UUID generator without problems?

**Comment by ebaauw** [comment]
That’s very much intented!  You want to use the same UUID between homebridge sessions, or HomeKit would see a new accessory, losing any assignments to HomeKit rooms, groups, scenes and automations.

You shouldn’t generate the UUID from something that’s user configured, like a name or ip address, but from something constant and guaranteed to be unique, like a serial number or mac address.

**Comment by ebaauw** [comment]
I depends on API version the plugin uses.  Newer (dynamic) platform plugins cache discovered accessories in ~/.homebridge/accessories.  Upon restart, homebridge restores the accessories from this cache calling `configureAccessory()` to tell the plugin.  For older (static) platform plugins homebridge doesn't cache anything.  The plugin needs to re-discover the accessories on each startup, and present them (or rather their delegate objects) to homebridge using `accessories()`.  Homebridge than (re-)generates the UUID (from `uuid_base`) (re-)creates the accessory.

**Comment by Krillle** [comment]
@ebaauw Thanks for your advice. I studied your homebridge-zp plugin and you create custom homekit characteristics. I would need such for my plugin too (tank levels and batteries). May I contact you on a private channel somewhere?

**Comment by ebaauw** [comment]
> So for the (dynamic) platform plugin I am writing, i can use a random UUID.

Technically you could, but I don’t think you should want to.  You need some unique id persisted in your accessory context anyways, to recognise, after restart, whether a discovered device was already exposed previously or whether it’s a new device.  Simply generate the UUID from that unique id.

You might also want to consider how to deal with stale devices (broken or no longer in your possession) or a corrupted or outdated cache.  It would be nice to be able to delete and rebuild the cache without having to redo your HomeKit configuration.

> May I contact you on a private channel somewhere?

I’m on the homebridge slack.

**Comment by Krillle** [comment]
> It would be nice to be able to delete and rebuild the cache without having to redo your HomeKit configuration. 
This means, when I reuse the same UUID generated from an identifier within the plugin, the HomeKit will recover/recognize the devices even after deleting  ~/.homebridge/accessories?

>I’m on the homebridge slack.
Ok, I will join there. Thanks for the hint.

**Comment by ebaauw** [comment]
> This means, when I use the same UUID generated from an identifier within the plugin, the HomeKit will recover/recognize the devices even after deleting ~/.homebridge/accessories?

Yes.  This is more or less what happens with static platform accessories.

> Who could add me?

Dunno.  I just clicked the link on the homebridge README, see https://github.com/nfarina/homebridge#community.

**Comment by ingria** [comment]
This error also happens if two accessories have the same name. For example, this config won't work:

```
        {
            "name": "Temperature",
            "type": "temperatureSensor",
            "accessory": "mqttthing",
            "topics": {
                "getCurrentTemperature": {
                    "topic": "zigbee2mqtt/Aqara_Sensor_01",
                    "apply": "return parseFloat(JSON.parse(message).temperature);"
                }
            }
        },
        {
            "name": Temperature",
            "type": "temperatureSensor",
            "accessory": "mqttthing",
            "topics": {
                "getCurrentTemperature": {
                    "topic": "zigbee2mqtt/Aqara_Sensor_02",
                    "apply": "return parseFloat(JSON.parse(message).temperature);"
                }
            }
        }
```
Not sure if this is a bug or a feature
If I change the name to unique value (e.g. Temperature 01), everything works fine.

**Comment by Krillle** [comment]
It's a feature to enable older (static) platform plugins which do not cache accessories to recognize them by their name. You need to name your devices unique.

> It depends on API version the plugin uses. Newer (dynamic) platform plugins cache discovered accessories in ~/.homebridge/accessories. Upon restart, homebridge restores the accessories from this cache calling `configureAccessory()` to tell the plugin. For older (static) platform plugins homebridge doesn't cache anything. The plugin needs to re-discover the accessories on each startup, and present them (or rather their delegate objects) to homebridge using `accessories()`. Homebridge than (re-)generates the UUID (from `uuid_base`) (re-)creates the accessory.
