### ISSUE TITLE
Accessories not responding

### ISSUE THREAD

**Issue by wilkinsm89** [nfarina/homebridge#1686]
Running Homebridge on a Debian VM and regularly facing 'Accessories not responding'. Homebridge logs report no issue and the problem will often be resolved shortly after without any changes required. 

Running iOS11 with the AppleTV on tvOS11 (ethernet) as the hub.

Have tried deleting the 'persist' & 'accessories' folders and even deleting and re-adding a new home to no avail.

Is there any additional debugging/diagnostics I can run to identify a possible network error?

Anyone else facing similar issues?

**Comment by wilkinsm89** [comment]
Managed to get additional logging and see the following whether the app is unreachable:

Thu, 04 Jan 2018 09:01:06 GMT EventedHTTPServer [::ffff:10.0.1.49] Client connection closed
Thu, 04 Jan 2018 09:01:06 GMT EventedHTTPServer [::ffff:10.0.1.49] Client connection closed
Thu, 04 Jan 2018 09:01:06 GMT EventedHTTPServer [::ffff:10.0.1.49] HTTP connection was closed
Thu, 04 Jan 2018 09:01:06 GMT EventedHTTPServer [::ffff:10.0.1.49] HTTP server was closed
Thu, 04 Jan 2018 09:01:06 GMT EventedHTTPServer [::ffff:10.0.1.49] HTTP connection was closed
Thu, 04 Jan 2018 09:01:06 GMT EventedHTTPServer [::ffff:10.0.1.49] HTTP server was closed

**Comment by bobfatherx** [comment]
Same problem here, running Homebridge on a FreeNAS jail (basically, FreeBSD) and on an Ubunti VM before that.

About 6 months ago my Homebridge started "not responding". Nuking my home in iOS didn't fix it, and neither did clearing out persist and accessories folder as you did. Also shuffling the MAC address, name, and PIN of the Homebridge install do nothing except let me re-add the Homebridge again, only for it to go "not responding" soon after.

When I run Homebridge it starts with 0 problems. About 50% of the time when trying to add a new Homebridge (after changing name, MAC, pin) I get a "device not supported" error, or something very similar. The other 50% of the time the Bridge will add successfully but the individual devices will go "not responding" anywhere from instantly to 2-3 minutes later.

**Comment by wilkinsm89** [comment]
Switching the device to an ethernet connection appears to have resolved the issue for now as I have not had any dropouts in the last 24 hours. Will update if that isn't the solution.
