### ISSUE TITLE
Link to Slack on Main ReadMe Fails

### ISSUE THREAD

**Issue by nickv2002** [nfarina/homebridge#1688]
In the [ReadMe](https://github.com/nfarina/homebridge/blob/master/README.md) there's a link to Slack at https://slackin-adpxqdnhge.now.sh/

Following that link just fails with a message "502 An Error Occurred In Your Deployment"

### Expected Behavior
Link to some kind of Slack login page.

### Current Behavior
502 error

### Steps to Reproduce (for bugs)
Follow Slack link

**Comment by AppleTechy** [comment]
Summoning @KhaosT  & @nfarina , Not sure which one of you is the owner of the Slack Team at the current moment.

**Comment by nfarina** [comment]
Darn, thought I fixed that ... will take a look

**Comment by nfarina** [comment]
Fixed again. Man, keeping this thing up is a pain!

**Comment by nfarina** [comment]
Thanks @nickv2002 for opening the issue btw!
