### ISSUE TITLE
Light Wave RF Heat Control Request

### ISSUE THREAD

**Issue by andygroves** [nfarina/homebridge#1689]
It is possible to add the LWRF heating device support please.

there are three device, radiator valve, stand alone thermostat and electric switch thermo stat, these device are gen1 one and are two way.

**Comment by bluntiless** [comment]
Hello andygroves, I to was looking for a solution to this. I currently use Mark Hornsby’s version of HAP-Nodejs and was able to implement this: https://cybermatters.info/2016/11/15/smart-home-project-homekit-and-lightwaverf-integration/

Have a look and see if you can get it working. I am able to change the temperature with Siri but have not got the home app to display the current temp. You have to add the TRV’s and Thermostat Control as separate accessories in your accessories folder. Let me know how you get on and good luck!
