### ISSUE TITLE
Refresh / Reload plugins during runtime?

### ISSUE THREAD

**Issue by jaal2001** [nfarina/homebridge#1690]
I'm using homebridge with the deconz plugin to control some non-homekit supported devices with Siri.
Works fine, as there are many helpful pages linked from here.
But there is one thing still unresolved for me:
If i add a new device to deconz, the device does not appear in homebridge.
When loading homebridge (or restarting), I can see the discovery of the already added devices:

Jan  6 09:03:40 raspberrypi homebridge[3610]: addDiscoveredLight
Jan  6 09:03:41 raspberrypi homebridge[3610]: addDiscoveredLight

But if I add a new device to deconz, the new device is not discovered until I restart homebridge.
Is there a trigger option available, that homebridge will discover or reload the plugins every n minutes?

Thanks
J

**Comment by xoniq** [comment]
I would like to see something like this too. For me with domoticz. If I add a device in domoticz it would be nice if it appears in some amount of time on my Home app too.

**Comment by KhaosT** [comment]
Homebridge allows plugin to dynamically add/remove accessories during runtime. Plugin developer need to use those APIs.
