### ISSUE TITLE
Update homebridge needs

### ISSUE THREAD

**Issue by sommo** [nfarina/homebridge#1697]
When we update the homebridge, we have to remove it from home app and readd it?
Right?

**Comment by theo-69** [comment]
wondering the same!

**Comment by NorthernMan54** [comment]
Most of the time updating homebridge does not requiring deleting and adding your devices again.  The updates around the iOS-11 launch were an exception.

**Comment by sommo** [comment]
Ok thank you, anyway reading error post in the last update i will wait
