### ISSUE TITLE
Unable to install libavahi-compat-libnssd-dev on Rpi3 with Hassbian

### ISSUE THREAD

**Issue by knowsnotmuch** [nfarina/homebridge#1699]
Hello - I am trying to follow this guide to install Homebridge on a Rpi3 with Hassbian. I get stuck at this point: 

```
sudo apt-get install libavahi-compat-libdnssd-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package libavahi-compat-libdnssd-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libavahi-compat-libdnssd-dev' has no installation candidate
```
Do I need to add any other source? Any pointers on what I should do? Thank you for your time and advice

**Comment by knowsnotmuch** [comment]
Never mind - I think it was just a messed up hassbian package status. 

I reinstalled hassbian from scratch and was able to install libavahi-compat-libdnssd-dev

**Comment by cpvbruno** [comment]
I have the same problem and already re-installed twice... anyone can help me?
