### ISSUE TITLE
Problem Authenticating with SmartThings

### ISSUE THREAD

**Issue by tonesto7** [nfarina/homebridge#17]
I have everything setup but I am receiving authentication error
     Starting HomeBridge server...
     Loading 1 platforms...
     [SmartThings] Initializing SmartThings platform...
     [SmartThings] Fetching SmartThings devices...
     [SmartThings] There was a problem authenticating with SmartThings.

I know the app-id and token are correct:
Here is my config.json:
    {
         "description": "This is an example configuration file with all supported devices. You can use this                         template for creating your own configuration file containing devices you actually own.",

    "platforms": [
        {
                "platform": "SmartThings",
                "name": "SmartThings",
                "appId" : "myStAppId",
		"accessToken" : "myStAccessToken"
        }
    ]
}

**Comment by bval** [comment]
I just ran into this myself and the issue is that the config.json block the SmartApp returns formats the keys with camelCase as:
```
"appId": "foo",
"accessToken": "bar"
```
whereas the node.js app is expecting underscore case as in `app_id`, `access_token`. Just change the config.json keys and you'll be good. I'll wrangle up a simple PR to fix that. I've also got some notes for @jnewland about his SmartApp assuming everyone has Hues. I'll send you something to make that optional. HTH. :beers:

**Comment by jnewland** [comment]
Should be resolved by https://github.com/jnewland/SmartThings/pull/1. Thanks @bval!

**Comment by tonesto7** [comment]
It is working now thanks

**Comment by timo55** [comment]
Hi, I also have this issue but app_id, access_token have the expected underscores... Any advice to get past what seems like the final hurdle would be much appreciated - I'm a newbie on a sharp learning curve!
I get exactly the same error message as the OP.
Thanks in advance!
config.json is as below:
{
        "bridge": {
                "name": "Homebridge",
                "username": "CC:22:3D:E3:CE:30",
                "port": 51826,
                "pin": "031-45-154"
        },

        "description": "JSON API",
        "platforms": [{
                "platform": "SmartThings",
                "name": "SmartThings",
                "app_id": "xxxxxxx",
                "access_token": "xxxxxxx"
        }]
}

@jnewland @nfarina
