### ISSUE TITLE
Help on how to Create An Accessory with 2 Services - Lock with Battery

### ISSUE THREAD

**Issue by jvmahon** [nfarina/homebridge#1700]
I am trying to understand how to create a homebridge accessory that has two services (i.e., a primary and secondary). Specifically, I'd like to create a homebridge accessory with a LockMechanism service as the primary and a Battery service as the secondary. I've been looking for an example homebridge plugin that similarly creates accessories with two Services but can't find one. Anybody have any they can suggest? Anybody know if adding multi-service accessories is even possible using homebridge?

My more specific goal is to figure out how to add a lock with a battery service using the homebridge-homeseer plugin. Locks added using that plugin currently lack a Battery service (in fact, I think all the accessories added by that plugin have only a single service). It should be possible to add a battery reference and battery threshold to the lock configuration line such that a battery service is created and added to the lock accessory if battery reference variables exist in the Lock defining line of the config.json file. 

As a further note, I have been experimenting with the Lock_Accessory.js accessory from HAP-NodeJS and was able to add a battery service to this template. For anyone interested, this modification can be found on my repository at [http://github.com/jvmahon/hap-nodejs](http://github.com/jvmahon/hap-nodejs)

**Comment by NorthernMan54** [comment]
In a platform plugin, use addService to add an additional Service.  Keep in mind that the Home app does not support some configurations of accessories, you may need to use Eve or other HomeKit clients with your own custom accessory.

ie

```
 var accessory = new Accessory(name, uuid, 10);

    self.log("Adding Reset Switch:");
    accessory.reachable = true;
    accessory.context.name = name;
    //        accessory.context.model = model;
    //        accessory.context.url = url;

    accessory.addService(Service.Switch, name)
      .getCharacteristic(Characteristic.On)
      .on('set', self.resetDevices.bind(self, accessory));

```

**Comment by jvmahon** [comment]
Thanks for the suggestion. Fortunately, I was able to confirm that LockMechanism along with Battery Service is a combination supported by the iOS 11 Home App.  

As far as getting the two services joined together as a single accessory, from what I can tell, it looks like the getServices() function in the Homebridge-Homseer plugin's index.js file does what you suggest - i.e.,  it builds an array of the desired services for an bridged accessory within the array 'services'. I think that the resulting array of services for the accessory is they used by Homebridge function Server.prototype_createAccessory function defined in Homebridge's lib/server.js file to actually create the Accessory. From what I can tell, the next step I have is to modify the getServices() function in homebridge-homeseer plugin to also add a BatteryService if a lock is being added.  At least that's the path I'm pursuing. Other thoughts welcome.

**Comment by ebaauw** [comment]
Note that that is for the (once) new dynamic platform accessories model, when you `registerPlatform('homebridge-yourplugin', 'YourName', YourPlatform, true)`.

With the old, static, model, when you `registerPlatform('homebridge-yourplugin', 'YourName', YourPlatform)`, you need to return a list of services from `YourAccessory.prototype.getServices()` for each YourAccessory object that you return from `YourPlatform.prototype.accesssories()`.

Apple's Home app handles multiple services per accessory just fine, as long as it knows the service.  It shows a tile per _service_,  __not__ per _accessory_, even though it labels the tiles accessories!  That's why the number of _Accessories_ for homebridge is smaller than the number of tiles shown when you press the number.  Note that Siri also deals with services, not with accessories.

The exceptions to "tile per service" are:
- No tiles for `AccessoryInformation` and `Battery` Services - these are shown under the details of each other service of the accessory;
- When the accessory contains only unknown services, it's shown as a _Not Supported_ tile;
- Stateless switches show one tile for the accessory, and a button per `StatelessProgrammableSwitch` service under the details;
- Note that Home doesn't know custom services, but also `Speaker`, even though this is defined by Apple.

Eve shows services in the _Rooms_ view.  When you detail a service, it shows all services for the associated accessory.  Under _Settings_, _Accessories_ it shows the accessories, with the services in the details under _Siri Names_.

**Comment by Nastras** [comment]
Hello, look here, with this plugin you can create a lock as a dummy. Maybe it will help you.

https://github.com/grover/homebridge-automation-switches/blob/master/docs/LockMechanism.md

**Comment by jvmahon** [comment]
Thanks to all who provided suggestions. I think I have my lock + battery accessory working now with the homeseer plugin. I'm testing to make sure, then I'll close out this comment and post it as a PR to the jrhubott/homeseer-homebridge plugin (no changes were needed to homebridge itself) (or I may post as a new npm package as it seems the homeseer-homebridge author may have gone inactive).

**Comment by jvmahon** [comment]
This has been posted as a PR to the homebridge-homeseer and, in the meantime, as a new npm package homebridge-homeseer-2018

**Comment by jdtsmith** [comment]
> Note that that is for the (once) new dynamic platform accessories model, when you `registerPlatform('homebridge-yourplugin', 'YourName', YourPlatform, true)`.
> 
> With the old, static, model, when you `registerPlatform('homebridge-yourplugin', 'YourName', YourPlatform)`, you need to return a list of services from `YourAccessory.prototype.getServices()` for each YourAccessory object that you return from `YourPlatform.prototype.accesssories()`.

Sorry to revive this old thread, but do you have any article or post about the differences between dynamic and non-dynamic platforms?  There is very little information as to what the differing behavior and call syntax is.

**Comment by ebaauw** [comment]
Sorry, I don’t know if it’s ever been written up, other than in the source code.

**Comment by chasenicholl** [comment]
Hi all,

I'd like to revive this question please. I've run into this exact problem.

When I create (used the plugin template) DynamicPlatformPlugin Accessory with both a LockMechanism and a Battery Service, only the latter initialized one is recognized in Apple Home. Though I can see both of their set and get handlers being called.

I can confirm, independently they both are added to Apple Home as expected.

Is there any documentation on creating a Platform Accessory with different Service types, like a LockMechanism and a Battery?

**Comment by NorthernMan54** [comment]
@chasenicholl As a sample take a look at https://github.com/NorthernMan54/homebridge-tasmota, I'm creating devices of various types depending on your Tasmota device configuration.

Please keep in mind that the Home App is pretty restricted on what services and characteristics can be included in the same accessory.  If a service does not have the particular characteristic listed as being included, it is unlikely to appear in the Home App.

**Comment by chasenicholl** [comment]
@NorthernMan54 Thanks! It would be wonderful if the Homebridge documentation had a list as to what Accessories (service + characteristics) can be combined.

My solution was simply to create 2 different platform accessory Classes. One for Battery and one for the Lock and its working totally fine. It honestly makes the code cleaner anyway to separate these concerns.

For anyone who finds this... in the `discoverDevices()` or whatever your Accessory initialization method is called I loop through a List of Accessory Classes, and then loop over the shared data in another nested loop.

```js
private accessoryClasses = [
   YourBatteryAccessory,
   YourLockAccessory,
];
// ... then in discoverDevices()

for (let i = 0, len = this.accessoryClasses.length; i < len; i++) {
  const accessoryClass = this.accessoryClasses[I];
  for (const device of sharedDevices) {
    //...create or load from cache blah blah blah
    new accessoryClass(this, accessory);
   //...etc
  }
}

```
