### ISSUE TITLE
Noob questions about homebridge on Pi2: access the Log

### ISSUE THREAD

**Issue by doodoovane** [nfarina/homebridge#1705]
Hi, 

Firstly sorry for the noob questions, I only started a week ago with the Pi and keep on learning commands with the terminal.

I've installed Homebridge 3 days ago, everything was fine until today. I came back home after the week end, all the accessories and the bridge itself was not responding anymore.

I've wanted the check on the log to see what happens but after closing the terminal windows, I can't find the command to show the Log anymore (what shows when I type: sudo homebridge server). 
What is the command to see it again?

Thank you for you help

P.S: I couldn't run the command 
_sudo homebridge server_ 
as it says 
_EADDRINUSE :::51826_
, even after
 _sudo killall homebridge_

**Comment by Dewsmen** [comment]
Hi, `tail -f /var/log/homebridge.err` (BTW check this part to autostart homebridge [https://github.com/nfarina/homebridge/wiki/Homebridge-autostart-at-boot-(init.d)-on-Ubuntu-(linux)](url) )
