### ISSUE TITLE
Accessories are working, but they're not triggering automation

### ISSUE THREAD

**Issue by rawrenced** [nfarina/homebridge#1710]
Hey guys, I've got an issue in regards to automation. All the lights (Yeelight) on my homebridge work fine and I'm able to turn scenes off and on no problem via my iPhone. With the lights, I've also got a set of sensors and switches (Aqara) which works fine when first installed. These include a switch, a motion sensor and door sensor. 

The problem I have is the switch and automation rules I have for sensors sometimes just fail. For example, I have a simple one which turns on the lights if the door is opened and turns off if the door is closed. The odd thing is, the sensors are working fine, they'll update the state of the door instantly, however it won't do anything to my lights. Everything works again once I restart homebridge though.

This happens probably 3 times a day? It's incredibly inconsistent. Sometimes it'll work all night, other times I'll have to reset like 3 times in 1 night.

Has anyone else had this problem or might know why it's happening so often? I can't reproduce the problem and the logs unfortunately don't capture anything when the sensors/buttons are triggered so there's no way to pinpoint when exactly they decide to give out. Homebridge is currently running on my RPI3 and everything is up to date.

Any help would be appreciated.

UPDATE: Ok they just crashed again but the logs are saying "already in device list!" and now it won't work

**Comment by ronaldheft** [comment]
Update to the latest version of HomeBridge. There was an issue with notifications that has been recently fixed.

**Comment by michaeljanich** [comment]
Make sure your Apple TV (or iPad) is on and working. After you "rename" some accessories or services you may need to redo the rules.

**Comment by rawrenced** [comment]
Thanks a lot @ronaldheft, looks like the update fixed it.
