### ISSUE TITLE
Config.json homebridge error on compilation

### ISSUE THREAD

**Issue by AlbertoZantedeschi** [nfarina/homebridge#1713]
Hi at all, I'm a new member.
I have a problem in compiling the config.json file below.
I was checking the file on https://jsonlint.com and it gave me the error Expecting 'STRING', got 'undefined' on line 18 ...rm": "eDomoticz",		"name”: ”Cancello”,“
----------------------^
Someone can check the file and correct the errors?
Thanks at all

{
 "bridge": {
 "name": "Homebridge",
 "username": "CC:21:3E:E4:DE:33",
 "port": 51826,
 "pin": "031-45-154"
 },
 "description": "Configuration file for (e)xtended Domoticz platform.",
 "platforms": [
 {
 "platform": "eDomoticz",
 "name": "eDomoticz",
 "server": "127.0.0.1",
 "port": "8080",
 "ssl": 0,
 "roomid": 0,
 "mqtt": 1
 },
 {
 "platform": "Camera-ffmpeg",
 “cameras”: [
 {
 “name”: ”Cancello”,
 “videoConfig”:{
 “source”:”-rtsp_transport tcp -i rtsp://192.168.1.31/unicast”,
 “stillImageSource”:”-i rtsp://192.168.1.31/unicast -vframes 1 -r 1″,
 “maxStreams”:2,
 “maxWidth”:1280,
 “maxHeight”:720,
 “maxFPS”:30
 }
 }
 ]
 }
]
},
 "accessories": [],
}

**Comment by aswathraja** [comment]
Here you go, do check and get back if u face any other problems. If u need to add any other platforms or accessories, you have to use normal double quotes ( " ) .

`{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:21:3E:E4:DE:33",
		"port": 51826,
		"pin": "031-45-154"
	},
	"description": "Configuration file for (e)xtended Domoticz platform.",
	"platforms": [{
			"platform": "eDomoticz",
			"name": "eDomoticz",
			"server": "127.0.0.1",
			"port": "8080",
			"ssl": 0,
			"roomid": 0,
			"mqtt": 1
		},
		{
			"platform": "Camera",
			"Cameras": [{
				"name": "Cancello",
				"videoConfig": {
					"source": "-rtsp_transport tcp - i rtsp: //192.168.1.31/unicast",
					"stillImageSource": "-i rtsp: //192.168.1.31/unicast -vframes 1 -r 1",
					"maxStreams": 2,
					"maxWidth": 1280,
					"maxHeight": 720,
					"maxFPS": 30
				}
			}]
		}
	],

	"accessories": []
}
`

**Comment by AlbertoZantedeschi** [comment]
Thank you aswathraja now works on homebridge.
But I have a second problem. Now I am unable to connect the camera to Home app (Homekit) on my iPhone. Someone can help me?

**Comment by jannnfe** [comment]
@AlbertoZantedeschi try a different name for your camera

**Comment by AlbertoZantedeschi** [comment]
@jannnfe @aswathraja I tried to change the name for the camera, but it does not work. When I open Home from the iPhone and try to add an accessory it can not locate the camera.
