### ISSUE TITLE
Homebridge runs for a several days, then stops working and keeps crashing after auto restart

### ISSUE THREAD

**Issue by jolenewa** [nfarina/homebridge#1721]
Folks,

I am trying to learn and have been having this issue for about a month. The first time it happened, I tried a reboot of the RPi 2 with Raspbian Stretch, and it did not help. On a whim, I ran sudo npm upgrade, deleted the bridge from iOS (I only have the WeMo Plugin at the moment) and re-paired. It worked again for several days, then stopped and will not restart by itself (Yes, it is running as a service). but now the same sequence no longer works. When everything works, I am able to reboot the Pi and Homebridge restarts without any hitches, so I assume my json config file is OK.

Running systemctl status homebridge does not give me any clues and to what could be happening. I cannot find any .err or .log files on the Pi, based on instructions on several posts here.

Here is the results I get when trying to get the status:

homebridge.service - Node.js HomeKit Server
   Loaded: loaded (/etc/systemd/system/homebridge.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Sat 2018-01-27 13:08:35 EST; 1s ago
  Process: 5417 ExecStart=/usr/bin/homebridge $HOMEBRIDGE_OPTS (code=exited, status=1/FAILURE)
 Main PID: 5417 (code=exited, status=1/FAILURE)
   CGroup: /system.slice/homebridge.service

Jan 27 13:08:35 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
Jan 27 13:08:35 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
Jan 27 13:08:35 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.

Using find / -name "homebridge.err" or the /log, yields no results. The Pi never loses connectivity to the network. My networki setup is simple, a single subnet and I am connecting via Ethernet at the moment. Deleting /var/homebridge/persist does not help.

I am still kind of a noob, although I am OK using most commands in Linux. Can anyone please try to help? None of the posts gave me any usable suggestions, no matter what I tried. I really would like to get it working without these apparent crashes.

The IP address is currently dynamic, but it has not changed since installation. Could this be related to the Pi momentarily disconnecting when trying to renew the IP address?

Thanks in advance.

**Comment by NorthernMan54** [comment]
Try this

sudo journalctl -f -u homebridge

This is display the log

**Comment by jolenewa** [comment]
Here is what I see when I display the log. Does it help?

Jan 27 13:18:23 raspberrypi homebridge[11041]: *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
Jan 27 13:18:23 raspberrypi nodejs[11041]: *** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
Jan 27 13:18:23 raspberrypi nodejs[11041]: *** WARNING *** Please fix your application to use the native API of Avahi!
Jan 27 13:18:23 raspberrypi nodejs[11041]: *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
Jan 27 13:18:23 raspberrypi nodejs[11041]: *** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
Jan 27 13:18:23 raspberrypi nodejs[11041]: *** WARNING *** Please fix your application to use the native API of Avahi!
Jan 27 13:18:23 raspberrypi nodejs[11041]: *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
Jan 27 13:18:28 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
Jan 27 13:18:28 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
Jan 27 13:18:28 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
Jan 27 13:18:38 raspberrypi systemd[1]: homebridge.service: Service hold-off time over, scheduling restart.
Jan 27 13:18:38 raspberrypi systemd[1]: Stopped Node.js HomeKit Server.
Jan 27 13:18:38 raspberrypi systemd[1]: Started Node.js HomeKit Server.
Jan 27 13:18:40 raspberrypi homebridge[11601]: *** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
Jan 27 13:18:40 raspberrypi homebridge[11601]: *** WARNING *** Please fix your application to use the native API of Avahi!
Jan 27 13:18:40 raspberrypi homebridge[11601]: *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
Jan 27 13:18:40 raspberrypi homebridge[11601]: *** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
Jan 27 13:18:40 raspberrypi homebridge[11601]: *** WARNING *** Please fix your application to use the native API of Avahi!
Jan 27 13:18:40 raspberrypi homebridge[11601]: *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>

**Comment by NorthernMan54** [comment]
Okay,  I think you need to stop the auto start and run homebridge from the command line

sudo systemctl stop homebridge

Then run it from the command line as the user you configured it to run as

Ie 

Homebridge

The console will then give you the errors

**Comment by jolenewa** [comment]
Thanks, I seem to be getting the same "cannot read username" error again, but I have not changed anything in the config.json file. Here is the log output:

[1/27/2018, 1:28:07 PM] Loaded plugin: homebridge-platform-wemo
[1/27/2018, 1:28:07 PM] Registering platform 'homebridge-platform-wemo.BelkinWeMo'
[1/27/2018, 1:28:07 PM] ---
/usr/lib/node_modules/homebridge/lib/server.js:212
  var username = config.bridge.username;
                              ^

TypeError: Cannot read property 'username' of undefined
    at Server._loadConfig (/usr/lib/node_modules/homebridge/lib/server.js:212:31)
    at new Server (/usr/lib/node_modules/homebridge/lib/server.js:57:38)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3

**Comment by jolenewa** [comment]
Here are the contents of config.json:

{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },

    "description": "Homebridge configuration file",

    "accessories": [],

    "platforms": [ 
        { 
        "platform": "BelkinWeMo", 
        "name": "WeMo Platform" 
        } 
    ]
}

**Comment by NorthernMan54** [comment]
Post your config.json, you likely have a typo or it is finding the wrong file

**Comment by jolenewa** [comment]
The config.json file is in /var/homebridge

**Comment by NorthernMan54** [comment]
Try

homebridge -U /var/homebridge

**Comment by NorthernMan54** [comment]
Or if you have .homebridge

homebridge -U /var/homebridge/.homebridge

**Comment by jolenewa** [comment]
Now I get a different error. Thanks for the help so far. I need to run an errand and do some research when I get back. There are two other config.json files and it looks like I am out of space in the root folder on the 16 GB card?

Here is the error:

/usr/lib/node_modules/homebridge/node_modules/mkdirp/index.js:90
                    throw err0;
                    ^

Error: ENOSPC: no space left on device, mkdir '/var/homebridge/persist'
    at Object.fs.mkdirSync (fs.js:895:18)
    at Function.sync (/usr/lib/node_modules/homebridge/node_modules/mkdirp/index.js:71:13)
    at LocalStorage.parseDirSync (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/node-persist/src/local-storage.js:642:20)
    at LocalStorage.parseDataDirSync (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/node-persist/src/local-storage.js:572:21)
    at LocalStorage.initSync (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/node-persist/src/local-storage.js:145:14)
    at Object.nodePersist.initSync (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/node-persist/src/node-persist.js:41:29)
    at Object.init (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/index.js:29:13)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:24:7)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:571:32)

**Comment by jolenewa** [comment]
Either way I think I will get a 32 GB card.

**Comment by NorthernMan54** [comment]
Try df -k

You have probably filled /var with error messages

**Comment by jolenewa** [comment]
/dev/root has zero space available. Can you give me clues as to which log files I can delete?

**Comment by jolenewa** [comment]
And where they are?

**Comment by NorthernMan54** [comment]
I think we should switch to a private chat on homebridge’s slack instance.  We are now well outside of a homebridge issue.

**Comment by jolenewa** [comment]
OK I am there as myself "Jorge Olenewa"
