### ISSUE TITLE
Homebridge Nest Temperature "Waaaaarming"? 

### ISSUE THREAD

**Issue by btk1011** [nfarina/homebridge#1722]
I just did a fresh install of Homebridge on a dedicated Raspberry Pi. I then installed the Nest plugin. All works fine, except if the heater is on, and I ask what temperature it is, Siri responds with "It's currently 71, but it's waaaaarming up to 73" and she sounds weird saying that. Any idea how I can correct that? 
![img_0637](https://user-images.githubusercontent.com/20198564/35475221-567cae68-0360-11e8-8fcd-e6e5fff3d575.png)

**Comment by KhaosT** [comment]
This is Siri’s response. Homebridge have no control over it. Please submit feedback to Apple.
