### ISSUE TITLE
Can't see camera RTSP (Xiaomi XiaoFang with hack) on Homekit via Homebridge

### ISSUE THREAD

**Issue by AlbertoZantedeschi** [nfarina/homebridge#1723]
Hello at all,
I've installed on my Ubuntu PC Homebridge and with Domoticz works well. Some days ago I tried to install Homebridge-Camera-ffmpeg and connect my camera Xiaofang with hack to Homekit but I can't see it. The camera works well with VLC but if I try to add to Home App, iPhone doesn't detect it. This is the configuration of config.json file:
{
"bridge": {
"name": "Homebridge",
"username": "CC:21:3E:E4:DE:33",
"port": 51826,
"pin": "031-45-154"
},
"description": "Configuration file for (e)xtended Domoticz platform.",
"platforms": [{
"platform": "eDomoticz",
"name": "eDomoticz",
"server": "127.0.0.1",
"port": "8080",
"ssl": 0,
"roomid": 0,
"mqtt": 1
},
{
"platform": "Camera-ffmpeg",
"Cameras": [{
"name": "Cancello",
"videoConfig": {
"source": "-rtsp_transport tcp - i rtsp: //192.168.1.31/unicast",
"stillImageSource": "-i rtsp: //192.168.1.31/unicast -vframes 1 -r 1",
"maxStreams": 2,
"maxWidth": 1280,
"maxHeight": 720,
"maxFPS": 30
}
}]
}
],

"accessories": []
}

Someone can help me to solve the problem?
Thank you.

**Comment by mrkernels** [comment]
I use the plugin 'homebridge-ip-camera' and have the ffmpeg installed as well, I use this config

{
    "platform": "Camera-IP",
    "cameras": [
        {
            "name": "Garage",
            "videoConfig": {
                "source": "-re -i rtsp://admin:password@192.168.99.119:554/Streaming/Channels/2",
                "stillImageSource": "-i rtsp://admin:password@192.168.99.119:554/Streaming/Channels/2",
                "maxStreams": 2,
                "maxWidth": 1280,
                "maxHeight": 720,
                "maxFPS": 15,
                "vcodec": "h264_omx"
            }

**Comment by shexbeer** [comment]
Indeed, i also did got problems while adding Xiaofang to homebridge.
This video helped me, because adding cameras to homekit are bit special 

https://www.youtube.com/watch?v=qJBO1kHuNRE

**Comment by AlbertoZantedeschi** [comment]
@mrkernels which admin and password do I have to write?
@shexbeer I saw the video and followed the guide of that user step by step but I can not see the camera at home. Guide link http://www.lagomsmartahem.se/guide/guide-fa-xiaomi-xiaofang-ip-kamera-till-homebridge/

**Comment by mrkernels** [comment]
Well that depends on your camera. Every camera ships with a default username and password. You will need to look up what's default for your model.

Also, try accessing and logging in to the camera using a web browser first to confirm that you have the right IP-address and username/password combo before adding them in your config.

It's also possible that the xiaomi camera doesn't need any login credentials which is scary...

**Comment by bencharlesrhys** [comment]
Default Xiaofang username is "root" Password is "ismart12". I've applied fang-hacks to the camera.

**Comment by niccolospa** [comment]
@AlbertoZantedeschi using homebridge-camera-ffmpeg or the other plugin your config should be like this:
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:22:E3:22:22",
        "port": 51826,
        "pin": "222-22-223",
        "manufacturer": "@miio",
        "model": "Homebridge",
        "serialNumber": "0.4.22"
    },


  "platforms": [{
      "platform":"Camera-ffmpeg",
      "cameras":[
      {
        "name":"Camera 1",
        "videoConfig":{
          "source":"-rtsp_transport tcp -i rtsp://192.168.1.8/unicast",
          "stillImageSource":"-i rtsp://192.168.1.8/unicast -vframes 1 -r 1",
          "maxStreams":2,
          "maxWidth":1280,
          "maxHeight":720,
          "maxFPS":15,
          "vcodec":"h264_omx"
        }
      }
    ] 
	}]


}
