### ISSUE TITLE
HomeKit App says accessories was already added and can't t add homebridge again

### ISSUE THREAD

**Issue by maartenvant** [nfarina/homebridge#1724]
Hi,

Hopefully people here can help me. I've added homebridge and some plugins. Was working perfectly. Only remote access wasn't working correctly (yes Apple TV 4 was connected in the home app and myself as admin user had right to access remotely) So I wanna to re-add homebridge. SO I removed it from the "home" app. Deleted "My Home" including from iCloud. Deleted and reinstalled the Home app and tried to add homebridge again with the QR code. 

Now the Home app says this accessories was already added so I need to reset and start over to be able to add it again. So Deleted "My Home" including from iCloud. Disabled Keychain, Deleted and reinstalled the Home app and tried to add homebridge again with the QR code. 

Same issue... changed the PIN... also no luck. It keeps complaining the homebridge was already added. 

Anybody had the same problem and might have an solution to solve this.

### Versions

- **Homebridge**: `0.4.37`
- **Node**:       `v6.10.2`
- **OS**:         <11.2.5>

**Comment by maartenvant** [comment]
Renamed "Homebridge" in the config file to "Homebridge2" and changed the password. 

Solved the issue...

**Comment by mreassassin** [comment]
renaming homebridge or changing pin did not do it for me.. any ideas?

**Comment by fredericpfisterer** [comment]
Adding my 2 cents here since I tried everything and what fix it was to simply restart my router :-)

**Comment by wildman199** [comment]
Changing the username helped. Thanks. I just changed the last digit from 0 to 1. Every time I have to remove the homebridge from HomeKit to add more devices, I just changed the last digit of the user name in the config.json.

**Comment by mafyata** [comment]
Why do you remove homebridge ? Just add new devices and restart.

**Comment by wildman199** [comment]
The ring alarm is always and new features and devices. The home bridge will not recognize any new devices being controlled by ring until the homebridge is removed and reconnected.

**Comment by wildman199** [comment]
In all there is 36 devices on my ring now

**Comment by dcuellar** [comment]
> Changing the username helped. Thanks. I just changed the last digit from 0 to 1. Every time I have to remove the homebridge from HomeKit to add more devices, I just changed the last digit of the user name in the config.json.

Changing the last digit on the username did the trick for me as well. Thanks!

**Comment by tusk4tusk** [comment]
> 
> 
> Changing the username helped. Thanks. I just changed the last digit from 0 to 1. Every time I have to remove the homebridge from HomeKit to add more devices, I just changed the last digit of the user name in the config.json.

Nice! Thanks for the assistance.

**Comment by Level-9** [comment]
Changing the username still helps if you encounter this issue.

**Comment by ricardopereira** [comment]
Changing the last digit on the username worked for me as well. Thank you everyone!
