### ISSUE TITLE
problem with appletv

### ISSUE THREAD

**Issue by ZoltXs** [nfarina/homebridge#1725]
I have installed homebridge in Mac Os X high sierra, and I have problem because it does not detect appletv as an accessory central for the connection from outside the network, has anyone had this problem ??? Can someone help me solve it?

**Comment by bluntiless** [comment]
Have you tried updating the ATV4 to the latest tvOS? This resolved the issue of no remote access to HomeKit for me.

**Comment by LeeStephane** [comment]
try this : https://www.howtoisolve.com/homepod-connect-to-apple-tv/
