### ISSUE TITLE
Homebridge SmartThings Platform + broadlink

### ISSUE THREAD

**Issue by raaffq** [nfarina/homebridge#1727]
Hello , guys Jim running raspberry with homebridge and smartthings plug-in just like to add other platform in broadlink , can I run both platform on same raspberry? It’s enough if I’ll change config file? Thanks

**Comment by NorthernMan54** [comment]
Yes you can run multiple plugins in one homebridge.  Just pay close attention to the config.json

**Comment by raaffq** [comment]
Thank you , by any chance can someone share config file with example of two plugins? how to combine them , thanks

**Comment by NorthernMan54** [comment]
See below

{
    "bridge": {
        "name": "Penny",
        "username": "CC:22:3D:E3:CD:33",
        "port": 51826,
        "pin": "031-45-154"
    },

    "description": "HomeBridge DHT Temp/Humidity Sensor",

    "platforms": [],

    "accessories": [{
        "accessory": "Dht",
        "name": "cputemp",
        "service": "Temperature"
    }, {
        "accessory": "Dht",
        "name": "Temp/Humidity Sensor",
        "service": "dht22"
    }]


}

**Comment by raaffq** [comment]
Ok sensor i see both sensors “Dht” same way if plugins are from different systems? Ex. Smartthings and nest or broadlink?

**Comment by NorthernMan54** [comment]
A different example

{
    "bridge": {
        "name": "Penny",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154",
        "ssdp": 1900
    },

    "description": "HomeBridge Status Control",

    "platforms": [{
            "platform": "Heyu",
            "name": "Heyu"
        }, {
            "platform": "mcuiot",
            "name": "mcuiot",
            "-Jy3fy4H-do",
            "aliases": {
                "NODE-2BA4CB": "Front Porch",
                "NODE-8F8FE": "Cold Cellar",
                "NODE-DC4492": "Office",
                "NODE-DC4492GD": "Garage Door"
                }
        }
    ],

    "accessories": [
    {
        "accessory": "Dht",
    "name": "Basement",
    "name_temperature": "Temperature",
    "name_humidity": "Humdity",
        "service": "dht22",
        "-Jy3fy4H-do"

    }]
}

**Comment by raaffq** [comment]
Ok Thats perfect ,

Can you be that good and combine this two codes: 


1)
http://www.mactechgenius.com/Files/Homebridge/Pi/config.json

2)
https://github.com/lprhodes/homebridge-broadlink-rm/blob/master/config-sample.json

This two different devices what I like to use in same config file .
Many thanks:)
