### ISSUE TITLE
remote access to Homebridge home kit devices worked forever, now failing

### ISSUE THREAD

**Issue by dbl4git** [nfarina/homebridge#1739]
### Expected Behavior

Both remote and local access to my Wemo and Nest devices via Homebridge has worked just fine for a very long time.
### Current Behavior

Recently, remote access to Homebridge devices started failing on a regular basis, while local access still works just fine.  HomeKit native devices (iHome, Koogeek, Chamberlain) all continue to work fine, both locally and remotely. I had an iPad (latest iOS), and two AppleTVs(4th Gen 64GB, latest tvOS) serving as Homekit hubs, and recently added a HomePod. This problem seems to have been begun around the time the AppleTV's auto-upgraded to the latest tvOS).  Homebridge is running on an iMac (Sierra 10.12.6), and produces no errors.
Over the course of trying to figure this out, I have tried removing various of the hubs from service, removing all the cached files on Homebridge and restarting, removing Homebridge from Home and re-adding, and hundreds of permutations of these changes.
Homebridge devices seemed to work intermittently remotely, but always locally. It appears, however, that in truth it was working (remotely) ONLY when the iPad was the hub and the rest (AppleTVs or HomePod) Standby or off/disabled.  Possibly a red herring given the bugginess of the HomePod, but it never thinks the Homebridge devices are responding (locally, obviously), even when they are working fine in the iOS Home App and the iPad is the primary Homekit Hub.
### Steps to Reproduce (for bugs)

I can reproduce reliably as follows:
Homebridge Wemo and Nest devices all responding (locally and remotely) fine with iPad as Homekit Hub. Turn off iPad and when the HomePod or AppleTV become the hub, remote access fails, while local access continues to work.
### Versions

- **Homebridge**: `homebridge --version`
0.4.38
- **Node**:       `node --version`
v6.9.4
- **OS**:         
Mac OS Sierra (10.12.6)
### Configuration

```json

```

### Homebridge Log / Command Output

```

```

**Comment by Matsuo3rd** [comment]
Same here with AppleTV 4 (latest tvOS) as bridge and Homebridge 0.4.38 running on Mac.

**Comment by benfysh** [comment]
I am getting similar issues since adding a HomePod to my setup. Remote access used to work all the time but now the Homebridge connected devices show as 'not responding' outside of the house when using 4g/LTE. Other HomeKit devices such as my hue lights work fine.

**Comment by kyc1338** [comment]
Same here, all homebridge connected devices show as "not responding" even on the same WIFI after I added HomePod to my setup.

**Comment by aschaper** [comment]
Just to add another data point: I was able to confirm that it does look like HomePod is the issue by disconnecting my phone from my WiFi network and actively using my Apple TV to make it the connected HomeKit hub. When the Apple TV is connected, all of my homebridge accessories work correctly but as soon as the HomePod becomes the connected hub, the accessories say "No Response".

Unfortunately I don't think there's a way to force Apple TV to always be the connected hub but I hope there's a solution for this problem.

**Comment by benfysh** [comment]
Another quirk that I have noticed is that the camera I have added to homebridge using [homebridge-camera-ffmpeg](https://github.com/KhaosT/homebridge-camera-ffmpeg#homebridge-camera-ffmpeg) continues to be visible remotely via 4g whilst all the other accessories show as 'not responding'.

**Comment by benfysh** [comment]
I have tried resetting homebridge via the server UI and now all homebridge connected devices are showing as ‘not responding’ even on my WiFi.

**Comment by nashlib** [comment]
I will add my woe to this list. 
My problem is very similar to above details. When the Apple TV 4 is the “main” hub and HomePod is the standby every thing works fine both locally and remotely. When the HomePod takes over as the primary hub I get intermittent “no response” for HomeBridge connected devices. But strangely the issue is not universal to all iOS devices. On my iPhoneX the remote access works fine. But on my other devices like iPad or iPad mini it fails. 

:(

**Comment by earlyshen** [comment]
I have the same issue here. 
- **HomeKit Hub**: `Apple TV 4K`
- **Homebridge**: `v0.4.32` running on Raspberry Pi 3 connected to router thru LAN
- **Homebridge devices**: TP-Link Switches/Outlets, Nest Thermostats, Cameras
  Work fine locally but don't work remotely (Homebridge no response)
- **Non homebridge devices**: August Lock, Hue
  Work fine both locally & remotely

I don't have a HomePod so it might not related to HomePod trying to take over.

**Comment by BenS89** [comment]
Same issue here. 

Homebridge devices are responding fine over LTE if an iPad acts as Homekit hub. When I disable the iPad as Homekit Hub and activate Apple TV 4K as primary hub, remote access fails for the Homebridge devices (HomeBridge certified devices like Hue or Eve are still working remotely)

Are there any solutions known?

**Comment by earlyshen** [comment]
I got mine worked. I found that I didn't change the default `username` & `pin` listed in `config-sample.jcon`
```
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
   ...
```
I follow the instruction in https://github.com/nfarina/homebridge#my-ios-app-cant-find-homebridge. Now it works for me both on LAN and on LTE 

This is what I did:
1. Remove Homebridge from Apple Home App
2. Stop Homebridge on raspberry pi
3. rm -rf ~/.homebridge/persist
4. Change "username" & "piin" in config.json to something else
5. Run Homebridge
6. Add Homebridge to Apple Home App

Hope that helps for some of you in this thread :)

**Comment by ur7x** [comment]
My Homebridge failed a few days ago too.  Was fine through the end of last year and then a week or so ago it just stopped.

I have tried everything above and nothing is working.

I can see my Apple TV's remotely but everything else is "Unavailable"

**Comment by PietsHost** [comment]
> 
> 
> My Homebridge failed a few days ago too. Was fine through the end of last year and then a week or so ago it just stopped.
> 
> I have tried everything above and nothing is working.
> 
> I can see my Apple TV's remotely but everything else is "Unavailable"

same here... any suggestions what we can do?

**Comment by ryanschmidt** [comment]
I’m having the same issue. Homebridge has been working remotely without issue for at least a year. I’ve not upgraded Apple TV recently or made any changes to Homebridge but as of this week I can no longer control homebridge devices remotely via Home app.
