### ISSUE TITLE
Adding Homebridge to multiple devices

### ISSUE THREAD

**Issue by OgreSwamp** [nfarina/homebridge#1742]
I'm trying to add Homebridge accessory to multiple iPhones (under different Apple IDs).

I can successfully add it to first iPhone but can't find to a second one (it can't find it).
If I remove `persist` directory I can add my Homebridge on either device but only to one of them. After I add it to one of my iPhones another can't find it. 

What should I do to troubleshoot this issue?

Both iPhones are running on iOS 11.2.5
I'm using latest Homebridge version (0.4.38) on RaspberryPi

**Comment by SkyJohn** [comment]
Sound like you're setting stuff up wrong.

You need to use the HomeKit hub device to invite the other Apple IDs to join and then all your settings will be shared between them, you don't add Homebridge to each device separately.

**Comment by xoniq** [comment]
You can only invite other people into using the HomeKit devices from within the Home app. That way you can share the single Homebridge instance with multiple people like the wife.

**Comment by saschaludwig** [comment]
I have the same issue here. And inviting is not a real option because then the 2nd device can not arrange rooms/favourites/devices. So how can I add the same device (homebridge) to multiple iPhones/iPads?

**Comment by Tomi88-tech** [comment]
Hi a homebridge want to add an iphone and an ipad how to solve this?

**Comment by Supereg** [comment]
@Tomi88-tech you need to turn on HomeKit in the iCloud settings. If both devices share the same Apple ID they will synchronize automatically. Otherwise you will need to share your home with the other Apple ID (like https://support.apple.com/en-us/HT208709)

**Comment by Tomi88-tech** [comment]
Hi and how do I share my home with another Apple ID

**Comment by Supereg** [comment]
I literally provided a well written Apple Support page.
