### ISSUE TITLE
WaterLevel not working

### ISSUE THREAD

**Issue by theo-69** [nfarina/homebridge#1744]
I am using the WaterLevel option in one of my plugins, however it show like a switch with Waterlevel in the details:

![img_1629](https://user-images.githubusercontent.com/28484958/36316952-25cdea54-1312-11e8-8c28-c047b9407ad2.PNG)

plus I am getting `service name WaterLevel unknown`

**Comment by SkyJohn** [comment]
You'll need to use something like the Elgato Eve app to create automations with the data.

Apple's Home app doesn't support every kind if device yet.
