### ISSUE TITLE
Can’t create automation

### ISSUE THREAD

**Issue by alexandrutatar** [nfarina/homebridge#1747]
In Apple Home app under the automation tab there is no button for create new automation, only the info about the Apple TV and Ipad hub. 
I’m new to Homebridge, am I doing something wrong? Also I can’t use geolocation ( location services are on)

**Comment by toshibochan** [comment]
You can upload pictures?

**Comment by alexandrutatar** [comment]
![a899ca00-138d-420c-afd2-90c4bfeb1550](https://user-images.githubusercontent.com/30413941/36349939-2bc884f6-1497-11e8-9646-0aaec6c1291c.png)
![Uploading 9434D5CA-FA08-4267-9003-3DDB1D790739.png…]()

**Comment by alexandrutatar** [comment]
![7250f01f-20d3-48c5-a9e7-3721cbaa8ef9](https://user-images.githubusercontent.com/30413941/36349962-78d3b13a-1497-11e8-996a-7c1e36f8255c.png)

**Comment by alexandrutatar** [comment]
![a437852b-d438-4cec-8bfd-d93d449e08e5](https://user-images.githubusercontent.com/30413941/36349994-f301b290-1497-11e8-9702-5a3f2bbea89b.png)

**Comment by toshibochan** [comment]
You need iPad Air and up or Apple TV 4 or 4K, or HomePod for do automation and access your HomeKit from outside.

**Comment by toshibochan** [comment]
Your iPad or Apple TV or HomePod have to be in your house in same Apple ID. If is in different Apple ID or get invited from the main Apple ID setup in your HomeKit.

**Comment by toshibochan** [comment]
you have Apple TV 4 or 4K?

**Comment by alexandrutatar** [comment]
No, i don’t have. I believed I can do the automation thing without ATv or Ipad...

To use geolocation I need Ipad or ATv?

**Comment by toshibochan** [comment]
You can’t! You need Apple TV 4 or 4K or iPad iOS 10 and above or HomePod

**Comment by alexandrutatar** [comment]
Thanks for help!
