### ISSUE TITLE
Readme.md

### ISSUE THREAD

**Issue by jagooch** [nfarina/homebridge#1748]
The readme.md file need some improvements. 

The avahi install instructions seem to be Debian-specific. That library does not exist on CentOS/RedHat , but I found one that works. 

On centos 7/rhel7, it needs avahi-compat-libdns_sd-devel, this will install it for you:
sudo yum install -y avahi-compat-libdns_sd-devel

Also, I don't have a sample file in my ~/.homebridge/ folder. Can you add the full path to `config-sample.json` to the readme instructions?

**Comment by AppleTechy** [comment]
This is an open source project. Feel free to open a PR to update the Readme. I personally am not running it on any RedHat based OS but it sounds like you are. :)
