### ISSUE TITLE
Logging homebridge events to database

### ISSUE THREAD

**Issue by sparkescreative** [nfarina/homebridge#1755]
Can anybody point me in the right direction for logging Homebridge events to a database.

I have a 3 Pi's running Homebridge and 12 NodeMCU ESP8266's doing various things around the place.

All of this gets logged to the daemon.log files. I would like to intercept the homebridge log to pull it into a data base. So the data is actually useful.

I can't be the first person to want this. 

Or has google not been my friend on this occasion and I've missed the obvious.

Any help would be greatly received.

**Comment by dezral** [comment]
i make homebridge use syslog (systemd), and then journalctl to views logs.. and then use syslog to put that logs in a database...

**Comment by shexbeer** [comment]
You're not the first :) Sadly homebridge is in that way just designed as a proxy. I did not find any advanced logging / export options.
So i just use a homeassistant instance together with influxdb to store my state changes , values.
After that you can do big data analysis or just make visualizations with grafana.
