### ISSUE TITLE
New functionality : AutoClose

### ISSUE THREAD

**Issue by xMadNet** [nfarina/homebridge#1757]
Hi,
Excellent work....

Most gate door Open and close automatically
Is it possible to add this in your        ###@###Dev.
Add Autoclose : Yes/No
Add AutoClose delay : 4000ms
Manage automaticallay this autoclose
Thanks,
Best Regards,
Xavier

**Comment by dezral** [comment]
there is a delay addon named delay i use in thies cases.. it's not a perfect solution but it works..
