### ISSUE TITLE
Skip Plug-In Load

### ISSUE THREAD

**Issue by GSanCap** [nfarina/homebridge#1760]
### Versions

- **Homebridge**: `homebridge --version`
- **Node**:       `node --version`
- **OS**:         

### Configuration

```json

```

### Homebridge Log / Command Output

```

```
How can i start a second instance of Homebridge but skiping some plugins? My problem is, in first case, the homebridge-yeelight plugin, that plugin start an UDP server listening on port USP 1982, i don´t wanna load this plugin in my second instance (development).
The plugin halt the 2nd Homebridge instance saying "Error: bind EADDRINUSE 0.0.0.0:1982" (as expected)

Thanks in advance

**Comment by ebaauw** [comment]
Move the plugin to another directory, and start your production instance using `homebridge -P `_dir_.  See `homebridge --help`.

**Comment by GSanCap** [comment]
You are right, Thank you!
