### ISSUE TITLE
Nest config issue

### ISSUE THREAD

**Issue by jsdorais** [nfarina/homebridge#1762]
### Versions

- **Homebridge**: `homebridge --version`
- **Node**:       `node --version`
- **OS**:         

### Configuration

```json

```

### Homebridge Log / Command Output

```

```

**Comment by jsdorais** [comment]
Running Homebridge and getting the following error trying to run my Nest plugin:

"Error: The requested accessory 'Nest' was not registered by any plugin."

I've got both homebridge and the homebridge-nest successfully installed.  I believe my issue is with the config.json file.  Here are the contents of it:

```
{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},

	"description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",

	"accessories": [{
		"accessory": "Nest",
		"name": "Nest"
	}],

	"platforms": [{
		"platform": "Nest",


		"clientId": "client id obtained by nest",
		"clientSecret": "client secret obtained by nest",
		"code": "correct code"
	}]
}

```
My thermostat's name is 'Nest'.  What should I be looking into at this point?

**Comment by aswathraja** [comment]
according to the sample config from the plugin, it doesn't include any accessory. You only need to add the platform.
