### ISSUE TITLE
Homebridge auto-start not working [RPi]

### ISSUE THREAD

**Issue by beniaminrychter** [nfarina/homebridge#1768]
Hi everyone!

I have a big problem with my homebridge auto start feature. Without any problems I can start my homebridge from terminal when I type `homebridge`. My iPhone Home.app is seeing everything, it's perfect. But when I want to start homebridge in background using `sudo systemctl start homebridge`, I've got result just like below on screenshot.

I've done all things with permissions, changing path to `usr/bin/homebridge` instead of `usr/local/bin/homebridge` but nothing is changing. 

Npm is updated. Thanks for helping guys!

![screen shot 2018-03-13 at 16 50 24](https://user-images.githubusercontent.com/27733472/37353177-122851f2-26df-11e8-9679-bf67904f8106.png)

**Comment by thefool** [comment]
I had the same issue and fixed it with these two commands:
`sudo mkdir /home/homebridge/`
`sudo chown -R homebridge:homebridge /home/homebridge/`
that should work, assuming you created a system user called homebridge for running the service.

I had some other issues after that with the hombridge-pilight plugin not being able to connect to pilight via websockets, which you might run into (you'll see "undefined" in the status output), but I'm not sure how I fixed them - today the problem just went away...

**Comment by beniaminrychter** [comment]
@thefool Thanks! That didn't helped, so I decided to install homebridge through docker: <https://github.com/oznu/docker-homebridge>. Now I don't have any issues at all, and brilliant web interface for all plugins, config files and stuff like that.
