### ISSUE TITLE
How to add other devices to homebridge such as smartthings, nest and dyson.

### ISSUE THREAD

**Issue by sjmarkham** [nfarina/homebridge#1778]
I had no problem getting my setup up and running on my raspberry pi and it interacts with smartthings just fine and controls all my smartthings devices.  I want to also add my nest and my dyson cool link fan.  I have seen how to add each one and there example config.json.  I can not figure out how to add all the devices into one config.json  Just need some help adding nest and dyson to this config file

Here is my current config.json

{
    "description": "JSON API",
    "platforms": [
        {
            "platform": "homebridge-smartthings.SmartThings",
            "name": "SmartThings",
            "app_url": "https://graph-na02-useast1.api.smartthings.com:443/api/smartapps/installations/",
            "app_id": "",
            "access_token": ""
        }
    ],
    "bridge": {
        "name": "Homebridge",
        "username": "AA:BB:CC:DD:EE:FF",
        "port": 51826,
        "pin": "123-45-678"
    }
}

**Comment by spacesuitdiver** [comment]
@sjmarkham this question is more relevant for the ST plugin repo, I used to be a contributor there but ST's unreliability has me using homebridge-homeassistant these days.
