### ISSUE TITLE
Pairing homebridge error

### ISSUE THREAD

**Issue by volschin** [nfarina/homebridge#178]
by trying to pair homebridge I get the following message

```
  EventedHTTPServer [2003:84:af4b:7900:1899:77d8:a605:897e] Client connection error: write EPIPE +337ms
```
I can put in the pin, but it never finishes pairing.

Anyone an idea?

**Comment by KhaosT** [comment]
It seems the socket between iOS and accessory get terminated ... Can you get the logs from iOS and see what's the reason they closed the socket?

**Comment by volschin** [comment]
I found, that I can pair without the fhem plattform shim. So the problem seem to be there.

**Comment by jmtatsch** [comment]
I guess I had the same problem a day ago. One of your devices is noncompliant and home kit thus unpairs. Try filtering by room to identify the culprit.

**Comment by snowdd1** [comment]
look at the http://ip:51826/accessories
If one of the value fields is ot of the bounds of the min/max values (or in case of fixed answer lists, none of the allowed) then homekit dislikes the bridge. Sometimes it even blacklists the bridge for some time. I had this a lot before https://github.com/KhaosT/HAP-NodeJS/commit/98ef550c8d6fd961741673d4b695a74dd0126eba a lot with target temperatures.

**Comment by nfarina** [comment]
Just pushed a HAP-NodeJS update to master.

**Comment by cflurin** [comment]
I'm not sure whether this may be the same reason, anyway adding the Characteristic.TargetHorizontalTiltAngle in a WindowCovering Accessory the pairing doesn't work. I just get these messages:
`````
...
HAPServer [CC:22:3D:E3:CE:35] Removing pairing info for client +9ms
Accessory [Homebridge] Unpairing with client B7B16E8A-6F47-4B82-843E-F217132F7FF9 +0ms
...
```

**Comment by KhaosT** [comment]
Can you post an accessory configuration file so I can try to reproduce this?

Best Wishes,
Tian Zhang

**Comment by cflurin** [comment]
@KhaosT:  I've uploaded "FhemWindowCovering.js" and "config-fhem-sample.json" [here] (https://github.com/cflurin/homebridge-shims)

**Comment by cflurin** [comment]
@KhaosT: good news! I've just updated my iPhone to iOS 9 > it works with iOS 9 :smile:
