### ISSUE TITLE
when run Homebridge , I found  "TimeoutOverflowWarning"

### ISSUE THREAD

**Issue by cndavy** [nfarina/homebridge#1781]
### Expected Behavior

homebridge  
iphone can found it ,but so many log in 1line /1HZ

### Versions

- **Homebridge**: `homebridge --version`  0.4.38

- **Node**:       `node --version` v9.8.0

- **OS**:         
Linux pi 4.9.80-v7+ #1098 SMP Fri Mar 9 19:11:42 GMT 2018 armv7l GNU/Linux
 /home/pi
└─┬ UNMET DEPENDENCY homebridge-wemo@0.0.2
  ├─┬ request@2.85.0
  │ ├── aws-sign2@0.7.0
  │ ├── aws4@1.6.0
  │ ├── caseless@0.12.0
  │ ├─┬ combined-stream@1.0.6
  │ │ └── delayed-stream@1.0.0
  │ ├── extend@3.0.1
  │ ├── forever-agent@0.6.1
  │ ├─┬ form-data@2.3.2
  │ │ ├── asynckit@0.4.0
  │ │ ├── combined-stream@1.0.6 deduped
  │ │ └── mime-types@2.1.18 deduped
  │ ├─┬ har-validator@5.0.3
  │ │ ├─┬ ajv@5.5.2
  │ │ │ ├── co@4.6.0
  │ │ │ ├── fast-deep-equal@1.1.0
  │ │ │ ├── fast-json-stable-stringify@2.0.0
  │ │ │ └── json-schema-traverse@0.3.1
  │ │ └── har-schema@2.0.0
  │ ├─┬ hawk@6.0.2
  │ │ ├─┬ boom@4.3.1
  │ │ │ └── hoek@4.2.1 deduped
  │ │ ├─┬ cryptiles@3.1.2
  │ │ │ └── boom@5.2.0 extraneous
  │ │ ├── hoek@4.2.1
  │ │ └─┬ sntp@2.1.0
  │ │   └── hoek@4.2.1 deduped
  │ ├─┬ http-signature@1.2.0
  │ │ ├── assert-plus@1.0.0
  │ │ ├─┬ jsprim@1.4.1
  │ │ │ ├── assert-plus@1.0.0 deduped
  │ │ │ ├── extsprintf@1.3.0
  │ │ │ ├── json-schema@0.2.3
  │ │ │ └─┬ verror@1.10.0
  │ │ │   ├── assert-plus@1.0.0 deduped
  │ │ │   ├── core-util-is@1.0.2
  │ │ │   └── extsprintf@1.3.0 deduped
  │ │ └─┬ sshpk@1.14.1
  │ │   ├── asn1@0.2.3
  │ │   ├── assert-plus@1.0.0 deduped
  │ │   ├─┬ bcrypt-pbkdf@1.0.1
  │ │   │ └── tweetnacl@0.14.5 deduped
  │ │   ├─┬ dashdash@1.14.1
  │ │   │ └── assert-plus@1.0.0 deduped
  │ │   ├─┬ ecc-jsbn@0.1.1
  │ │   │ └── jsbn@0.1.1 deduped
  │ │   ├─┬ getpass@0.1.7
  │ │   │ └── assert-plus@1.0.0 deduped
  │ │   ├── jsbn@0.1.1
  │ │   └── tweetnacl@0.14.5
  │ ├── is-typedarray@1.0.0
  │ ├── isstream@0.1.2
  │ ├── json-stringify-safe@5.0.1
  │ ├─┬ mime-types@2.1.18
  │ │ └── mime-db@1.33.0
  │ ├── oauth-sign@0.8.2
  │ ├── performance-now@2.1.0
  │ ├── qs@6.5.1
  │ ├── safe-buffer@5.1.1
  │ ├── stringstream@0.0.5
  │ ├─┬ tough-cookie@2.3.4
  │ │ └── punycode@1.4.1
  │ ├─┬ tunnel-agent@0.6.0
  │ │ └── safe-buffer@5.1.1 deduped
  │ └── uuid@3.2.1
  └─┬ wemo@0.2.1
    ├─┬ node-ssdp@2.9.1
    │ ├─┬ debug@2.6.9
    │ │ └── ms@2.0.0
    │ └── ip@1.1.5
    ├── request@2.85.0 deduped
    └─┬ xml2js@0.4.19
      ├── sax@1.2.4
      └── xmlbuilder@9.0.7

### Configuration

```json

{
    "bridge": {
        "name": "Homebridge",
        "username": "B8:27:EB:68:24:02",
        "port": 51826,
        "pin": "031-45-154"
    },

    "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",

    "accessories": [
        {
            "accessory": "WeMo",
            "name": "Coffee Maker"
        }
    ],
"platforms": [
        {
    "platform": "HomeAssistant",
    "name": "HomeAssistant",
    "host": "http://127.0.0.1:8123",
    "password": "passwd",
    "supported_types": ["automation", "binary_sensor", "climate", "cover", "device_tracker", "fan", "group", "input_boolean", "light", "lock", "media_player", "remote", "scene", "script", "sensor", "switch", "vacuum"],
    "default_visibility": "hidden",
    "logging": true,
    "verify_ssl": true
        }
        ,{
        "platform": "AqaraPlatform",
        "sid": ["1111111111"],

        "password": ["22222"]
        }

    ]


}


```

### Homebridge Log / Command Output

```
(node:4593) TimeoutOverflowWarning: Infinity does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:4593) TimeoutOverflowWarning: Infinity does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
```

**Comment by cndavy** [comment]
├─┬ homebridge@0.4.38
│ ├─┬ bignum@0.12.5
│ │ ├── nan@2.10.0
│ │ └─┬ node-pre-gyp@0.6.39
│ │   ├── detect-libc@1.0.3
│ │   ├─┬ hawk@3.1.3
│ │   │ ├─┬ boom@2.10.1
│ │   │ │ └── hoek@2.16.3 deduped
│ │   │ ├─┬ cryptiles@2.0.5
│ │   │ │ └── boom@2.10.1 deduped
│ │   │ ├── hoek@2.16.3
│ │   │ └─┬ sntp@1.0.9
│ │   │   └── hoek@2.16.3 deduped
│ │   ├─┬ mkdirp@0.5.1
│ │   │ └── minimist@0.0.8
│ │   ├─┬ nopt@4.0.1
│ │   │ ├── abbrev@1.1.1
│ │   │ └─┬ osenv@0.1.5
│ │   │   ├── os-homedir@1.0.2
│ │   │   └── os-tmpdir@1.0.2
│ │   ├─┬ npmlog@4.1.2
│ │   │ ├─┬ are-we-there-yet@1.1.4
│ │   │ │ ├── delegates@1.0.0
│ │   │ │ └── readable-stream@2.3.5 deduped
│ │   │ ├── console-control-strings@1.1.0
│ │   │ ├─┬ gauge@2.7.4
│ │   │ │ ├── aproba@1.2.0
│ │   │ │ ├── console-control-strings@1.1.0 deduped
│ │   │ │ ├── has-unicode@2.0.1
│ │   │ │ ├── object-assign@4.1.1
│ │   │ │ ├── signal-exit@3.0.2
│ │   │ │ ├─┬ string-width@1.0.2
│ │   │ │ │ ├── code-point-at@1.1.0
│ │   │ │ │ ├─┬ is-fullwidth-code-point@1.0.0
│ │   │ │ │ │ └── number-is-nan@1.0.1
│ │   │ │ │ └── strip-ansi@3.0.1 deduped
│ │   │ │ ├── strip-ansi@3.0.1 deduped
│ │   │ │ └─┬ wide-align@1.1.2
│ │   │ │   └── string-width@1.0.2 deduped
│ │   │ └── set-blocking@2.0.0
│ │   ├─┬ rc@1.2.6
│ │   │ ├── deep-extend@0.4.2
│ │   │ ├── ini@1.3.5
│ │   │ ├── minimist@1.2.0
│ │   │ └── strip-json-comments@2.0.1
│ │   ├─┬ request@2.81.0
│ │   │ ├── aws-sign2@0.6.0
│ │   │ ├── aws4@1.6.0
│ │   │ ├── caseless@0.12.0
│ │   │ ├─┬ combined-stream@1.0.6
│ │   │ │ └── delayed-stream@1.0.0
│ │   │ ├── extend@3.0.1
│ │   │ ├── forever-agent@0.6.1
│ │   │ ├─┬ form-data@2.1.4
│ │   │ │ ├── asynckit@0.4.0
│ │   │ │ ├── combined-stream@1.0.6 deduped
│ │   │ │ └── mime-types@2.1.18 deduped
│ │   │ ├─┬ har-validator@4.2.1
│ │   │ │ ├─┬ ajv@4.11.8
│ │   │ │ │ ├── co@4.6.0
│ │   │ │ │ └─┬ json-stable-stringify@1.0.1
│ │   │ │ │   └── jsonify@0.0.0
│ │   │ │ └── har-schema@1.0.5
│ │   │ ├── hawk@3.1.3 deduped
│ │   │ ├─┬ http-signature@1.1.1
│ │   │ │ ├── assert-plus@0.2.0
│ │   │ │ ├─┬ jsprim@1.4.1
│ │   │ │ │ ├── assert-plus@1.0.0
│ │   │ │ │ ├── extsprintf@1.3.0
│ │   │ │ │ ├── json-schema@0.2.3
│ │   │ │ │ └─┬ verror@1.10.0
│ │   │ │ │   ├── assert-plus@1.0.0
│ │   │ │ │   ├── core-util-is@1.0.2 deduped
│ │   │ │ │   └── extsprintf@1.3.0 deduped
│ │   │ │ └─┬ sshpk@1.14.1
│ │   │ │   ├── asn1@0.2.3
│ │   │ │   ├── assert-plus@1.0.0
│ │   │ │   ├─┬ bcrypt-pbkdf@1.0.1
│ │   │ │   │ └── tweetnacl@0.14.5 deduped
│ │   │ │   ├─┬ dashdash@1.14.1
│ │   │ │   │ └── assert-plus@1.0.0
│ │   │ │   ├─┬ ecc-jsbn@0.1.1
│ │   │ │   │ └── jsbn@0.1.1 deduped
│ │   │ │   ├─┬ getpass@0.1.7
│ │   │ │   │ └── assert-plus@1.0.0
│ │   │ │   ├── jsbn@0.1.1
│ │   │ │   └── tweetnacl@0.14.5
│ │   │ ├── is-typedarray@1.0.0
│ │   │ ├── isstream@0.1.2
│ │   │ ├── json-stringify-safe@5.0.1
│ │   │ ├─┬ mime-types@2.1.18
│ │   │ │ └── mime-db@1.33.0
│ │   │ ├── oauth-sign@0.8.2
│ │   │ ├── performance-now@0.2.0
│ │   │ ├── qs@6.4.0
│ │   │ ├── safe-buffer@5.1.1
│ │   │ ├── stringstream@0.0.5
│ │   │ ├─┬ tough-cookie@2.3.4
│ │   │ │ └── punycode@1.4.1
│ │   │ ├─┬ tunnel-agent@0.6.0
│ │   │ │ └── safe-buffer@5.1.1 deduped
│ │   │ └── uuid@3.2.1
│ │   ├─┬ rimraf@2.6.2
│ │   │ └─┬ glob@7.1.2
│ │   │   ├── fs.realpath@1.0.0
│ │   │   ├─┬ inflight@1.0.6
│ │   │   │ ├── once@1.4.0 deduped
│ │   │   │ └── wrappy@1.0.2 deduped
│ │   │   ├── inherits@2.0.3 deduped
│ │   │   ├─┬ minimatch@3.0.4
│ │   │   │ └─┬ brace-expansion@1.1.11
│ │   │   │   ├── balanced-match@1.0.0
│ │   │   │   └── concat-map@0.0.1
│ │   │   ├── once@1.4.0 deduped
│ │   │   └── path-is-absolute@1.0.1
│ │   ├── semver@5.5.0
│ │   ├─┬ tar@2.2.1
│ │   │ ├─┬ block-stream@0.0.9
│ │   │ │ └── inherits@2.0.3 deduped
│ │   │ ├─┬ fstream@1.0.11
│ │   │ │ ├── graceful-fs@4.1.11
│ │   │ │ ├── inherits@2.0.3 deduped
│ │   │ │ ├── mkdirp@0.5.1 deduped
│ │   │ │ └── rimraf@2.6.2 deduped
│ │   │ └── inherits@2.0.3
│ │   └─┬ tar-pack@3.4.1
│ │     ├── debug@2.6.9 deduped
│ │     ├── fstream@1.0.11 deduped
│ │     ├─┬ fstream-ignore@1.0.5
│ │     │ ├── fstream@1.0.11 deduped
│ │     │ ├── inherits@2.0.3 deduped
│ │     │ └── minimatch@3.0.4 deduped
│ │     ├─┬ once@1.4.0
│ │     │ └── wrappy@1.0.2
│ │     ├─┬ readable-stream@2.3.5
│ │     │ ├── core-util-is@1.0.2
│ │     │ ├── inherits@2.0.3 deduped
│ │     │ ├── isarray@1.0.0
│ │     │ ├── process-nextick-args@2.0.0
│ │     │ ├── safe-buffer@5.1.1 deduped
│ │     │ ├─┬ string_decoder@1.0.3
│ │     │ │ └── safe-buffer@5.1.1 deduped
│ │     │ └── util-deprecate@1.0.2
│ │     ├── rimraf@2.6.2 deduped
│ │     ├── tar@2.2.1 deduped
│ │     └── uid-number@0.0.6
│ ├─┬ chalk@1.1.3
│ │ ├── ansi-styles@2.2.1
│ │ ├── escape-string-regexp@1.0.5
│ │ ├─┬ has-ansi@2.0.0
│ │ │ └── ansi-regex@2.1.1
│ │ ├─┬ strip-ansi@3.0.1
│ │ │ └── ansi-regex@2.1.1 deduped
│ │ └── supports-color@2.0.0
│ ├─┬ commander@2.8.1
│ │ └── graceful-readlink@1.0.1
│ ├─┬ hap-nodejs@0.4.41
│ │ ├── buffer-shims@1.0.0
│ │ ├─┬ curve25519-n2@1.1.3
│ │ │ ├── bindings@1.2.1
│ │ │ └── nan@2.10.0 deduped
│ │ ├─┬ debug@2.6.9
│ │ │ └── ms@2.0.0
│ │ ├── decimal.js@7.5.1
│ │ ├─┬ ed25519@0.0.4
│ │ │ ├── bindings@1.2.1 deduped
│ │ │ └── nan@2.10.0 deduped
│ │ ├── fast-srp-hap@1.0.1
│ │ ├── ip@1.1.5
│ │ ├─┬ mdns@2.3.4
│ │ │ ├── bindings@1.2.1 deduped
│ │ │ └── nan@2.3.5
│ │ └─┬ node-persist@0.0.11
│ │   ├── mkdirp@0.5.1 deduped
│ │   └── q@1.1.2 deduped
│ ├─┬ node-persist@0.0.8
│ │ ├── mkdirp@0.3.5
│ │ └── q@1.1.2
│ ├── qrcode-terminal@0.11.0
│ └── semver@5.0.3
├── homebridge-aqara@0.1.13
├─┬ homebridge-broadlink-rm@3.2.20
│ ├─┬ broadlinkjs-rm@0.2.6
│ │ └── @types/node@7.0.56
│ ├─┬ chai@4.1.2
│ │ ├── assertion-error@1.1.0
│ │ ├── check-error@1.0.2
│ │ ├─┬ deep-eql@3.0.1
│ │ │ └── type-detect@4.0.8 deduped
│ │ ├── get-func-name@2.0.0
│ │ ├── pathval@1.1.0
│ │ └── type-detect@4.0.8
│ ├─┬ github-version-checker@1.2.0
│ │ ├─┬ chalk@1.1.3
│ │ │ ├── ansi-styles@2.2.1
│ │ │ ├── escape-string-regexp@1.0.5
│ │ │ ├─┬ has-ansi@2.0.0
│ │ │ │ └── ansi-regex@2.1.1
│ │ │ ├─┬ strip-ansi@3.0.1
│ │ │ │ └── ansi-regex@2.1.1 deduped
│ │ │ └── supports-color@2.0.0
│ │ ├── coffeescript@1.12.7
│ │ ├─┬ got@7.1.0
│ │ │ ├─┬ decompress-response@3.3.0
│ │ │ │ └── mimic-response@1.0.0
│ │ │ ├── duplexer3@0.1.4
│ │ │ ├── get-stream@3.0.0
│ │ │ ├── is-plain-obj@1.1.0
│ │ │ ├── is-retry-allowed@1.1.0
│ │ │ ├── is-stream@1.1.0
│ │ │ ├─┬ isurl@1.0.0
│ │ │ │ ├─┬ has-to-string-tag-x@1.4.1
│ │ │ │ │ └── has-symbol-support-x@1.4.2
│ │ │ │ └── is-object@1.0.1
│ │ │ ├── lowercase-keys@1.0.0
│ │ │ ├── p-cancelable@0.3.0
│ │ │ ├─┬ p-timeout@1.2.1
│ │ │ │ └── p-finally@1.0.0
│ │ │ ├── safe-buffer@5.1.1
│ │ │ ├── timed-out@4.0.1
│ │ │ ├─┬ url-parse-lax@1.0.0
│ │ │ │ └── prepend-http@1.0.4
│ │ │ └── url-to-options@1.0.1
│ │ └── semver@5.5.0
│ ├─┬ homebridge-platform-helper@1.0.5
│ │ ├─┬ node-persist@2.1.0
│ │ │ ├─┬ is-absolute@0.2.6
│ │ │ │ ├─┬ is-relative@0.2.1
│ │ │ │ │ └─┬ is-unc-path@0.1.2
│ │ │ │ │   └── unc-path-regex@0.1.2
│ │ │ │ └── is-windows@0.2.0
│ │ │ ├─┬ mkdirp@0.5.1
│ │ │ │ └── minimist@0.0.8
│ │ │ └── q@1.1.2 deduped
│ │ ├── semver@5.5.0 deduped
│ │ └── uuid@3.2.1 deduped
│ ├─┬ ping@0.2.2
│ │ ├── q@1.1.2
│ │ └── underscore@1.8.3
│ └── uuid@3.2.1
├─┬ homebridge-homeassistant@3.1.0
│ ├─┬ eventsource@0.2.3
│ │ └─┬ original@1.0.0
│ │   └─┬ url-parse@1.0.5
│ │     ├── querystringify@0.0.4
│ │     └── requires-port@1.0.0
│ └─┬ request@2.85.0
│   ├── aws-sign2@0.7.0
│   ├── aws4@1.6.0
│   ├── caseless@0.12.0
│   ├─┬ combined-stream@1.0.6
│   │ └── delayed-stream@1.0.0
│   ├── extend@3.0.1
│   ├── forever-agent@0.6.1
│   ├─┬ form-data@2.3.2
│   │ ├── asynckit@0.4.0
│   │ ├── combined-stream@1.0.6 deduped
│   │ └── mime-types@2.1.18 deduped
│   ├─┬ har-validator@5.0.3
│   │ ├─┬ ajv@5.5.2
│   │ │ ├── co@4.6.0
│   │ │ ├── fast-deep-equal@1.1.0
│   │ │ ├── fast-json-stable-stringify@2.0.0
│   │ │ └── json-schema-traverse@0.3.1
│   │ └── har-schema@2.0.0
│   ├─┬ hawk@6.0.2
│   │ ├─┬ boom@4.3.1
│   │ │ └── hoek@4.2.1 deduped
│   │ ├─┬ cryptiles@3.1.2
│   │ │ └─┬ boom@5.2.0
│   │ │   └── hoek@4.2.1 deduped
│   │ ├── hoek@4.2.1
│   │ └─┬ sntp@2.1.0
│   │   └── hoek@4.2.1 deduped
│   ├─┬ http-signature@1.2.0
│   │ ├── assert-plus@1.0.0
│   │ ├─┬ jsprim@1.4.1
│   │ │ ├── assert-plus@1.0.0 deduped
│   │ │ ├── extsprintf@1.3.0
│   │ │ ├── json-schema@0.2.3
│   │ │ └─┬ verror@1.10.0
│   │ │   ├── assert-plus@1.0.0 deduped
│   │ │   ├── core-util-is@1.0.2
│   │ │   └── extsprintf@1.3.0 deduped
│   │ └─┬ sshpk@1.14.1
│   │   ├── asn1@0.2.3
│   │   ├── assert-plus@1.0.0 deduped
│   │   ├─┬ bcrypt-pbkdf@1.0.1
│   │   │ └── tweetnacl@0.14.5 deduped
│   │   ├─┬ dashdash@1.14.1
│   │   │ └── assert-plus@1.0.0 deduped
│   │   ├─┬ ecc-jsbn@0.1.1
│   │   │ └── jsbn@0.1.1 deduped
│   │   ├─┬ getpass@0.1.7
│   │   │ └── assert-plus@1.0.0 deduped
│   │   ├── jsbn@0.1.1
│   │   └── tweetnacl@0.14.5
│   ├── is-typedarray@1.0.0
│   ├── isstream@0.1.2
│   ├── json-stringify-safe@5.0.1
│   ├─┬ mime-types@2.1.18
│   │ └── mime-db@1.33.0
│   ├── oauth-sign@0.8.2
│   ├── performance-now@2.1.0
│   ├── qs@6.5.1
│   ├── safe-buffer@5.1.1
│   ├── stringstream@0.0.5
│   ├─┬ tough-cookie@2.3.4
│   │ └── punycode@1.4.1
│   ├─┬ tunnel-agent@0.6.0
│   │ └── safe-buffer@5.1.1 deduped
│   └── uuid@3.2.1
├─┬ homebridge-miio@0.3.2
│ └─┬ miio@0.13.0
│   ├── appdirectory@0.1.0
│   ├─┬ chalk@1.1.3
│   │ ├── ansi-styles@2.2.1
│   │ ├── escape-string-regexp@1.0.5
│   │ ├─┬ has-ansi@2.0.0
│   │ │ └── ansi-regex@2.1.1
│   │ ├─┬ strip-ansi@3.0.1
│   │ │ └── ansi-regex@2.1.1 deduped
│   │ └── supports-color@2.0.0
│   ├─┬ debug@2.6.9
│   │ └── ms@2.0.0
│   ├── minimist@1.2.0
│   └─┬ mkdirp@0.5.1
│     └── minimist@0.0.8
├─┬ homebridge-openhab@0.1.31
│ ├─┬ request@2.85.0
│ │ ├── aws-sign2@0.7.0
│ │ ├── aws4@1.6.0
│ │ ├── caseless@0.12.0
│ │ ├─┬ combined-stream@1.0.6
│ │ │ └── delayed-stream@1.0.0
│ │ ├── extend@3.0.1
│ │ ├── forever-agent@0.6.1
│ │ ├─┬ form-data@2.3.2
│ │ │ ├── asynckit@0.4.0
│ │ │ ├── combined-stream@1.0.6 deduped
│ │ │ └── mime-types@2.1.18 deduped
│ │ ├─┬ har-validator@5.0.3
│ │ │ ├─┬ ajv@5.5.2
│ │ │ │ ├── co@4.6.0
│ │ │ │ ├── fast-deep-equal@1.1.0
│ │ │ │ ├── fast-json-stable-stringify@2.0.0
│ │ │ │ └── json-schema-traverse@0.3.1
│ │ │ └── har-schema@2.0.0
│ │ ├─┬ hawk@6.0.2
│ │ │ ├─┬ boom@4.3.1
│ │ │ │ └── hoek@4.2.1 deduped
│ │ │ ├─┬ cryptiles@3.1.2
│ │ │ │ └─┬ boom@5.2.0
│ │ │ │   └── hoek@4.2.1 deduped
│ │ │ ├── hoek@4.2.1
│ │ │ └─┬ sntp@2.1.0
│ │ │   └── hoek@4.2.1 deduped
│ │ ├─┬ http-signature@1.2.0
│ │ │ ├── assert-plus@1.0.0
│ │ │ ├─┬ jsprim@1.4.1
│ │ │ │ ├── assert-plus@1.0.0 deduped
│ │ │ │ ├── extsprintf@1.3.0
│ │ │ │ ├── json-schema@0.2.3
│ │ │ │ └─┬ verror@1.10.0
│ │ │ │   ├── assert-plus@1.0.0 deduped
│ │ │ │   ├── core-util-is@1.0.2
│ │ │ │   └── extsprintf@1.3.0 deduped
│ │ │ └─┬ sshpk@1.14.1
│ │ │   ├── asn1@0.2.3
│ │ │   ├── assert-plus@1.0.0 deduped
│ │ │   ├─┬ bcrypt-pbkdf@1.0.1
│ │ │   │ └── tweetnacl@0.14.5 deduped
│ │ │   ├─┬ dashdash@1.14.1
│ │ │   │ └── assert-plus@1.0.0 deduped
│ │ │   ├─┬ ecc-jsbn@0.1.1
│ │ │   │ └── jsbn@0.1.1 deduped
│ │ │   ├─┬ getpass@0.1.7
│ │ │   │ └── assert-plus@1.0.0 deduped
│ │ │   ├── jsbn@0.1.1
│ │ │   └── tweetnacl@0.14.5
│ │ ├── is-typedarray@1.0.0
│ │ ├── isstream@0.1.2
│ │ ├── json-stringify-safe@5.0.1
│ │ ├─┬ mime-types@2.1.18
│ │ │ └── mime-db@1.33.0
│ │ ├── oauth-sign@0.8.2
│ │ ├── performance-now@2.1.0
│ │ ├── qs@6.5.1
│ │ ├── safe-buffer@5.1.1
│ │ ├── stringstream@0.0.5
│ │ ├─┬ tough-cookie@2.3.4
│ │ │ └── punycode@1.4.1
│ │ ├─┬ tunnel-agent@0.6.0
│ │ │ └── safe-buffer@5.1.1 deduped
│ │ └── uuid@3.2.1
│ └─┬ ws@0.8.1
│   ├─┬ bufferutil@1.2.1
│   │ ├── bindings@1.2.1
│   │ └── nan@2.10.0
│   ├── options@0.0.6
│   ├── ultron@1.0.2
│   └─┬ utf-8-validate@1.2.2
│     ├── bindings@1.2.1 deduped
│     └── nan@2.4.0
├─┬ homebridge-platform-wemo@1.3.6
│ ├─┬ debug@3.1.0
│ │ └── ms@2.0.0
│ └─┬ wemo-client@0.15.0
│   ├─┬ debug@2.6.9
│   │ └── ms@2.0.0 deduped
│   ├── entities@1.1.1
│   ├── ip@1.1.5
│   ├─┬ node-ssdp@3.2.5
│   │ ├─┬ async@2.6.0
│   │ │ └── lodash@4.17.5
│   │ ├── bluebird@3.5.1
│   │ ├─┬ debug@2.6.9
│   │ │ └── ms@2.0.0 deduped
│   │ ├── extend@3.0.1
│   │ └── ip@1.1.5 deduped
│   ├─┬ xml2js@0.4.19
│   │ ├── sax@1.2.4
│   │ └── xmlbuilder@9.0.7
│   └── xmlbuilder@8.2.2
├─┬ homebridge-wemo@0.0.2
│ ├─┬ request@2.85.0
│ │ ├── aws-sign2@0.7.0
│ │ ├── aws4@1.6.0
│ │ ├── caseless@0.12.0
│ │ ├─┬ combined-stream@1.0.6
│ │ │ └── delayed-stream@1.0.0
│ │ ├── extend@3.0.1
│ │ ├── forever-agent@0.6.1
│ │ ├─┬ form-data@2.3.2
│ │ │ ├── asynckit@0.4.0
│ │ │ ├── combined-stream@1.0.6 deduped
│ │ │ └── mime-types@2.1.18 deduped
│ │ ├─┬ har-validator@5.0.3
│ │ │ ├─┬ ajv@5.5.2
│ │ │ │ ├── co@4.6.0
│ │ │ │ ├── fast-deep-equal@1.1.0
│ │ │ │ ├── fast-json-stable-stringify@2.0.0
│ │ │ │ └── json-schema-traverse@0.3.1
│ │ │ └── har-schema@2.0.0
│ │ ├─┬ hawk@6.0.2
│ │ │ ├─┬ boom@4.3.1
│ │ │ │ └── hoek@4.2.1 deduped
│ │ │ ├─┬ cryptiles@3.1.2
│ │ │ │ └─┬ boom@5.2.0
│ │ │ │   └── hoek@4.2.1 deduped
│ │ │ ├── hoek@4.2.1
│ │ │ └─┬ sntp@2.1.0
│ │ │   └── hoek@4.2.1 deduped
│ │ ├─┬ http-signature@1.2.0
│ │ │ ├── assert-plus@1.0.0
│ │ │ ├─┬ jsprim@1.4.1
│ │ │ │ ├── assert-plus@1.0.0 deduped
│ │ │ │ ├── extsprintf@1.3.0
│ │ │ │ ├── json-schema@0.2.3
│ │ │ │ └─┬ verror@1.10.0
│ │ │ │   ├── assert-plus@1.0.0 deduped
│ │ │ │   ├── core-util-is@1.0.2
│ │ │ │   └── extsprintf@1.3.0 deduped
│ │ │ └─┬ sshpk@1.14.1
│ │ │   ├── asn1@0.2.3
│ │ │   ├── assert-plus@1.0.0 deduped
│ │ │   ├─┬ bcrypt-pbkdf@1.0.1
│ │ │   │ └── tweetnacl@0.14.5 deduped
│ │ │   ├─┬ dashdash@1.14.1
│ │ │   │ └── assert-plus@1.0.0 deduped
│ │ │   ├─┬ ecc-jsbn@0.1.1
│ │ │   │ └── jsbn@0.1.1 deduped
│ │ │   ├─┬ getpass@0.1.7
│ │ │   │ └── assert-plus@1.0.0 deduped
│ │ │   ├── jsbn@0.1.1
│ │ │   └── tweetnacl@0.14.5
│ │ ├── is-typedarray@1.0.0
│ │ ├── isstream@0.1.2
│ │ ├── json-stringify-safe@5.0.1
│ │ ├─┬ mime-types@2.1.18
│ │ │ └── mime-db@1.33.0
│ │ ├── oauth-sign@0.8.2
│ │ ├── performance-now@2.1.0
│ │ ├── qs@6.5.1
│ │ ├── safe-buffer@5.1.1
│ │ ├── stringstream@0.0.5
│ │ ├─┬ tough-cookie@2.3.4
│ │ │ └── punycode@1.4.1
│ │ ├─┬ tunnel-agent@0.6.0
│ │ │ └── safe-buffer@5.1.1 deduped
│ │ └── uuid@3.2.1
│ └─┬ wemo@0.2.1
│   ├─┬ node-ssdp@2.9.1
│   │ ├─┬ debug@2.6.9
│   │ │ └── ms@2.0.0
│   │ └── ip@1.1.5
│   ├── request@2.85.0 deduped
│   └─┬ xml2js@0.4.19
│     ├── sax@1.2.4
│     └── xmlbuilder@9.0.7
├── homebridge-yeelight@0.0.18

**Comment by patrickmcc** [comment]
@cndavy Got the same situation here, found through output log and it said,

```
patrickmcc@patricks-macbook-pro [02:48:30] [/usr/local/lib/node_modules]
-> % uname -a
Darwin patricks-macbook-pro.patrickmcc.win 17.5.0 Darwin Kernel Version 17.5.0: Tue Mar 13 20:39:15 PDT 2018; root:xnu-4570.51.1~36/RELEASE_X86_64 x86_64 i386 MacBookPro13,2 Darwin
```
```
patrickmcc@patricks-macbook-pro [02:48:11] [/usr/local/lib/node_modules]
-> % homebridge --version
0.4.38
patrickmcc@patricks-macbook-pro [02:48:15] [/usr/local/lib/node_modules]
-> % node --version
v9.9.0
```
```
patrickmcc@patricks-macbook-pro [02:44:04] [/usr/local/lib/node_modules]
-> % ps aux | grep homebridge | grep -v grep
patrickmcc       98637  18.9  1.0  5224092 164128   ??  R     2:43AM   0:13.74 homebridge
```
```
patrickmcc@patricks-macbook-pro [02:44:08] [/usr/local/lib/node_modules]
-> % tail -n 10 ~/.homebridge/homebridge.log
(node:98637) TimeoutOverflowWarning: Infinity does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:98637) TimeoutOverflowWarning: Infinity does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:98637) TimeoutOverflowWarning: Infinity does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:98637) TimeoutOverflowWarning: Infinity does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:98637) TimeoutOverflowWarning: Infinity does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
```

**Comment by patrickmcc** [comment]
**Homebridge was installed at** _/usr/local/lib/node_modules/homebridge_

```
patrickmcc@patricks-macbook-pro [02:51:00] [/usr/local/lib/node_modules/homebridge]
-> % npm list
homebridge@0.4.38 /usr/local/lib/node_modules/homebridge
├─┬ chalk@1.1.3
│ ├── ansi-styles@2.2.1
│ ├── escape-string-regexp@1.0.5
│ ├─┬ has-ansi@2.0.0
│ │ └── ansi-regex@2.1.1
│ ├─┬ strip-ansi@3.0.1
│ │ └── ansi-regex@2.1.1 deduped
│ └── supports-color@2.0.0
├─┬ commander@2.8.1
│ └── graceful-readlink@1.0.1
├─┬ hap-nodejs@0.4.41
│ ├── buffer-shims@1.0.0
│ ├─┬ curve25519-n2@1.1.3
│ │ ├── bindings@1.2.1
│ │ └── nan@2.10.0
│ ├─┬ debug@2.6.9
│ │ └── ms@2.0.0
│ ├── decimal.js@7.5.1
│ ├─┬ ed25519@0.0.4
│ │ ├── bindings@1.2.1 deduped
│ │ └── nan@2.10.0 deduped
│ ├── fast-srp-hap@1.0.1
│ ├── ip@1.1.5
│ ├─┬ mdns@2.3.4
│ │ ├── bindings@1.2.1 deduped
│ │ └── nan@2.3.5
│ └─┬ node-persist@0.0.11
│   ├─┬ mkdirp@0.5.1
│   │ └── minimist@0.0.8
│   └── q@1.1.2 deduped
├─┬ node-persist@0.0.8
│ ├── mkdirp@0.3.5
│ └── q@1.1.2
├── qrcode-terminal@0.11.0
└── semver@5.0.3
```
