### ISSUE TITLE
2 Custom plugins -> logs data as the name of the first registered one

### ISSUE THREAD

**Issue by szlaskidaniel** [nfarina/homebridge#1782]
### Versions

- **Homebridge**: `0.4.38`
- **Node**:       `8.10.0`
- **OS**:        RassberryPi 3

I've created 2 Custom Plugins.
First one works ok. Log also properly.
When I've created second Custom Plugin (then the second one logs appear with description of the first one) - I know it's quite tongue twist here.

What I'm doing in the code is:
```
this.log = log;
self = this;
```
And then all logs are written as: self.log(stuff here).

Both plugins are built the same way.

Do you have idea what is happening? I guess I've done something wrong, but I've no idea what ...
```
[2018-3-21 17:02:45] [RiscoAlarm] New state detected: (1) -> AWAY_ARM. Notify !
[2018-3-21 17:04:02] [RiscoAlarm] login to Unifi...
[2018-3-21 17:04:02] [RiscoAlarm] Unifi request:  https://192.168.44.4:7443/api/2.0/login
[2018-3-21 17:04:02] [RiscoAlarm] Logged In
```
Below entry is wrong (it's from the second plugin),  should be [UnifiAlerts]:
```
[2018-3-21 17:04:02] [RiscoAlarm] Camera alerts enabled:  false
```

Thanks in advance.

**Comment by NorthernMan54** [comment]
Are you plugins sharing the same files, or packages?

Sounds like a shared variable issue between in memory instances.

**Comment by szlaskidaniel** [comment]
Both of them uses similar NPM packages like (cookie, request).
What I’ve learned that issue appear when I use self = this , looks like last loaded plugin is “the master” for this requests.

**Comment by NorthernMan54** [comment]
Have you looked at variable scoping?  Let versus var

**Comment by szlaskidaniel** [comment]
Hi, 

I didn't used let variables.

The code generally looks like:

```
function RiscoSecuritySystemAccessory(log, config) {
    

    this.log = log;
    this.name = config["name"];
    this.riscoUsername = config["riscoUsername"];
    this.riscoPassword = config["riscoPassword"];
    this.riscoPIN = config["riscoPIN"];
    this.polling = config["polling"] || false;
    this.pollInterval = config["pollInterval"] || 30000;

    self = this;
```

And then later in code:

``` 
RiscoSecuritySystemAccessory.prototype = {

    setTargetState: function (state, callback) {
        self("Setting state to %s", translateState(state));
```

This should be limited to the plugin, but looks like after I've used in plugin:

```     self = this; ```

Any other plugin, which will be configured later, and use above approach will overrite previous one.

**Comment by ebaauw** [comment]
Did you check that you’re not using the same name in config.json for both plugins?

**Comment by szlaskidaniel** [comment]
Yes, I’ve checked that. Names and versions are different.

**Comment by ebaauw** [comment]
Does it show the name of the plugin whose accessory is initialised first or the second?  Where do you declare `self`?

**Comment by szlaskidaniel** [comment]
I ‘ve included sample above. 
I didn’t yet committed second plugin to github, but you can check first one (Homebridge-risco-alarm) - second it similar in Homebridge part.

**Comment by ebaauw** [comment]
You’re not using strict mode and you don’t declare `self`, so its a property of the global object, which is shared by the plugins.  Basically, the second plugin re-assigns a shared variable.

**Comment by szlaskidaniel** [comment]
Could you help here and tell me how it should be declared then ?

**Comment by NorthernMan54** [comment]
Sent a pull request to your repository

Also, looking at your code, why are you even using self?

If it is to get access to the log object in your emitters, take a look at using bind something like this

emitter.on("err", function (err) {
            this.log("Polling failed, error was %s", err);
        }.bind(this));

**Comment by szlaskidaniel** [comment]
I see your point to "bind" or use local "self" variable.
What I can do to make it work with external *.js files? I've included additional file (service) to main plugin, and there this / self doesn't work now?

**Comment by NorthernMan54** [comment]
For sharing variables or state between modules/files their are a number of patterns.  And each developer has personal their preferences.

For myself, I would pass over any variables/state as part of a constructor or function.

Another alternative is to have the external file be the state and have it emit events etc as needed.

**Comment by szlaskidaniel** [comment]
Thanks for help here.
We Can close this case for now.
