### ISSUE TITLE
Control curtain wireless

### ISSUE THREAD

**Issue by filippocobelli** [nfarina/homebridge#1783]
### Versions

- **Homebridge**: `homebridge --version`
- **Node**:       `node --version`
- **OS**:         

### Configuration

```json

```

### Homebridge Log / Command Output

```

```

**Comment by filippocobelli** [comment]
I would like to control my curtain wireless using a gpio. Currently i’m Running homebridge on a raspberry pi 3. The raspberry in in another room and I can’t put it near the curtain(is an outdoor curtain) so I would like to use a wireless connection to control it but i can’t find the right gpio adapter and the extension...
Help will be appreciated
Thanks

**Comment by NorthernMan54** [comment]
@filippocobelli 

You are going to need to do some more research on this, like how are the curtains controlled IR or RF, and more.  Have you googled for something similar?

As an example, this is my plugin for controlling my fireplace which uses a RF remote for control.

https://www.instructables.com/id/Control-Your-Fireplace-With-HomeKit-and-Alexa/

**Comment by iCarl** [comment]
Check out https://github.com/lprhodes/homebridge-broadlink-rm
