### ISSUE TITLE
Trouble running two platforms together!

### ISSUE THREAD

**Issue by sftimeless** [nfarina/homebridge#1784]
Hello, I've successfully added Mi Robot Vacuum Platform to Homebridge alone, and Mi Air Purifier 2S alone, but for some weird reason, having them both together is causing some trouble that I'm not too familiar.

Pardon my noob-ness.

I'm getting this error through terminal
`SyntaxError: Unexpected end of JSON input`

> {
>     "bridge": {
>         "name": "Homebridge",
>         "username": "xxxxxxxxxxxxxx",
>         "port": xxxxxxxxxxxxxx,
>         "pin": "xxxxxxxxxxxxxx"
>     },
>     "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",
>     "accessories": [ ],
>     "platforms": [{
>         "platform": "MiRobotVacuumPlatform",
>         "deviceCfgs": [{
>             "type": "MiRobotVacuum2",
>             "ip": "xxxxxxxxxxxxxx",
>             "token": "xxxxxxxxxxxxxx",
>             "robotVacuumName": "Robot Vacuum 2",
>             "enablePauseToCharge": true,
>             "robotVacuumDisable": false
> }    , {
>             "platform": "MiAirPurifierPlatform",
>         "deviceCfgs": [{
>             "type": "MiAirPurifier2S",
>             "ip": "xxxxxxxxxxxxxx",
>             "token": "xxxxxxxxxxxxxx",
>             "airPurifierDisable": false,
>             "airPurifierName": "MiAirPurifier2S",
>             "silentModeSwitchDisable": false,
>             "silentModeSwitchName": "MiAirPurifier2S Silent Mode Switch",
>             "temperatureDisable": false,
>             "temperatureName": "MiAirPurifier2S Temperature",
>             "humidityDisable": false,
>             "humidityName": "MiAirPurifier2S Humidity",
>             "buzzerSwitchDisable": true,
>             "buzzerSwitchName": "MiAirPurifier2S Buzzer Switch",
>             "ledBulbDisable": true,
>             "ledBulbName": "MiAirPurifier2S LED Switch",
>             "airQualityDisable": false,
>             "airQualityName": "MiAirPurifier2S AirQuality"
>           }]
> 
>   }

**Comment by W0GER** [comment]
You're missing some array closures. Try the following

`
{
    "bridge": {
        "name": "Homebridge",
        "username": "xxxxxxxxxxxxxx",
        "port": 1,
        "pin": "xxxxxxxxxxxxxx"
    },
    "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",
    "accessories": [],
    "platforms": [{
            "platform": "MiRobotVacuumPlatform",
            "deviceCfgs": [{
                "type": "MiRobotVacuum2",
                "ip": "xxxxxxxxxxxxxx",
                "token": "xxxxxxxxxxxxxx",
                "robotVacuumName": "Robot Vacuum 2",
                "enablePauseToCharge": true,
                "robotVacuumDisable": false
            }]
        }, {
            "platform": "MiAirPurifierPlatform",
            "deviceCfgs": [{
                "type": "MiAirPurifier2S",
                "ip": "xxxxxxxxxxxxxx",
                "token": "xxxxxxxxxxxxxx",
                "airPurifierDisable": false,
                "airPurifierName": "MiAirPurifier2S",
                "silentModeSwitchDisable": false,
                "silentModeSwitchName": "MiAirPurifier2S Silent Mode Switch",
                "temperatureDisable": false,
                "temperatureName": "MiAirPurifier2S Temperature",
                "humidityDisable": false,
                "humidityName": "MiAirPurifier2S Humidity",
                "buzzerSwitchDisable": true,
                "buzzerSwitchName": "MiAirPurifier2S Buzzer Switch",
                "ledBulbDisable": true,
                "ledBulbName": "MiAirPurifier2S LED Switch",
                "airQualityDisable": false,
                "airQualityName": "MiAirPurifier2S AirQuality"
            }]
        }]
    }

`
