### ISSUE TITLE
Homekit recognizes Homebridge but not accessories

### ISSUE THREAD

**Issue by kiblereric** [nfarina/homebridge#1785]
I added homebridge and nest plugin to my Pi 3 B, was able to add homebridge to homekit with no errors, except instead of the nest thermostat showing as the accessory, I have included a screen shot of what does show. Ran debug, no discernible errors. Have tried this process 10+ times, installing and uninstalling nodejs, homebridge, nest plugin, even factory reset my Pi OS - all produces same result.   

![iphonescreenshot](https://user-images.githubusercontent.com/37812335/37926380-383e3a84-3105-11e8-85f4-8fb75cc85e72.jpg)

**Comment by DarthCruiser** [comment]
What do you get when you click - 'Next'?

**Comment by kiblereric** [comment]
**I am able to add home bridge to home kit -->**

![img_0527](https://user-images.githubusercontent.com/37812335/38218889-3ec6cf46-36a1-11e8-9fda-4c48b407234c.PNG)

**No issues here -->**

![img_0528](https://user-images.githubusercontent.com/37812335/38218888-3eac76dc-36a1-11e8-97ff-32df1d9aa9c9.PNG)

**Homebridge is recognized -->**

![img_0529](https://user-images.githubusercontent.com/37812335/38218886-3e81f06a-36a1-11e8-87ca-89eec120c28d.PNG)

**An accessory is recognized. This should say nest thermometer and show the appropriate icon.. but it doesn't**

![img_0530](https://user-images.githubusercontent.com/37812335/38218885-3e5e2626-36a1-11e8-8648-ba8bc37bc3a1.PNG)

**When I view accessories i see home bridge, but not the nest or any alias for it**

![img_0531](https://user-images.githubusercontent.com/37812335/38218884-3e3cadde-36a1-11e8-8fb9-fa095647b9cb.PNG)

**Click into home bridge -->**

![img_0532](https://user-images.githubusercontent.com/37812335/38218883-3e29dc72-36a1-11e8-8a65-bfa242eb2c30.PNG)

**Should list number of accessories associated with the bridge, but does not**

![img_0533](https://user-images.githubusercontent.com/37812335/38218882-3e032960-36a1-11e8-9286-449ba52ada46.PNG)

**Comment by jasehigh** [comment]
Having the same problem, did you resolve this issue?

**Comment by kiblereric** [comment]
@jasehigh no :/

**Comment by jasehigh** [comment]
I resolved the issue I was having.
In the config.json I only had a single platter defined, but wrapping this in:

`
"platforms": [{
}]
`

Enable the addition of accessories.

**Comment by kiblereric** [comment]
@jasehigh would you mind posting your json file (remove any confidential information) so that I can see how you formatted?

**Comment by jasehigh** [comment]
@kiblereric This is my config.json for homebridge-netatmo:

```
{
	"bridge": {
		"name": "netatmo",
		"username": "XX:XX:XX:XX:XX:XX",
		"port": XXXXX,
		"pin": "XXX-XX-XXX"
	},
	"platforms": [{
		"platform": "netatmo",
		"name": "Weather",
		"ttl": 5,
		"auth": {
			"client_id": "XXXXX",
			"client_secret": "XXXXX",
			"username": "XXXXX",
			"password": "XXXXX"
		}
	}]
}
```
