### ISSUE TITLE
Two platform of the same brand

### ISSUE THREAD

**Issue by lowrisk75** [nfarina/homebridge#1788]
I can't run two smartthings platform 
(I have one HUB V1 US and one HUB V2 UK.

"platforms": [
        {
            "platform": "SmartThings",
            "name": "SmartThings",
            "app_url": "https://graph-na04-useast2.api.smartthings.com:443/api/smartapps/installations/",
            "app_id": "XXXX",
            "access_token": "XXXXX"
        },
        {
            "platform": "SmartThings",
            "name": "SmartThings",
            "app_url": "https://graph-eu01-euwest1.api.smartthings.com:443/api/smartapps/installations/",
            "app_id": "YYYYYYY",
            "access_token": "YYYY"
        },

return : 
Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory:XXXXXXXXXXX
homebridge_1  |     at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:264:13)
homebridge_1  |     at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:377:24)
homebridge_1  |     at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:16:19
homebridge_1  |     at /homebridge/node_modules/homebridge-smartthings/index.js:121:4
homebridge_1  |     at /homebridge/node_modules/homebridge-smartthings/index.js:98:5
homebridge_1  |     at /homebridge/node_modules/homebridge-smartthings/lib/smartthingsapi.js:94:29
homebridge_1  |     at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-smartthings/lib/smartthingsapi.js:45:29)
homebridge_1  |     at emitNone (events.js:111:20)
homebridge_1  |     at IncomingMessage.emit (events.js:208:7)
homebridge_1  |     at endReadableNT (_stream_readable.js:1064:12)
homebridge_1  |     at _combinedTickCallback (internal/process/next_tick.js:138:11)
homebridge_1  |     at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by iCarl** [comment]
Change the name of the second "SmartThings" to "SmartThings2" or something else

**Comment by lowrisk75** [comment]
I tried this but have this issue

homebridge_1  | [2018-3-28 12:51:08] [SmartThings] Initializing platform accessory 'SmartSense Multi'...
homebridge_1  | [2018-3-28 12:51:08] [SmartThings] Initializing platform accessory 'Utility Door'...
homebridge_1  | 
homebridge_1  | /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:264
homebridge_1  |       throw new Error("Cannot add a bridged Accessory with the same UUID as another bridged Accessory: " + existing.UUID);
homebridge_1  |             ^
homebridge_1  | Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: xxxx-a5fa-4c4e-xxxx
homebridge_1  |     at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:264:13)
homebridge_1  |     at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:377:24)
homebridge_1  |     at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:16:19
homebridge_1  |     at /homebridge/node_modules/homebridge-smartthings/index.js:121:4
homebridge_1  |     at /homebridge/node_modules/homebridge-smartthings/index.js:98:5
homebridge_1  |     at /homebridge/node_modules/homebridge-smartthings/lib/smartthingsapi.js:94:29
homebridge_1  |     at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-smartthings/lib/smartthingsapi.js:45:29)
homebridge_1  |     at emitNone (events.js:111:20)
homebridge_1  |     at IncomingMessage.emit (events.js:208:7)
homebridge_1  |     at endReadableNT (_stream_readable.js:1064:12)
homebridge_1  |     at _combinedTickCallback (internal/process/next_tick.js:138:11)
homebridge_1  |     at process._tickCallback (internal/process/next_tick.js:180:9)
homebridge_1  | -U /homebridge -P /homebridge/node_modules

**Comment by lowrisk75** [comment]
I bought a new raspberry pi to run a another instance of Homekit, so I will be able to connect my second Smartthings Hub
