### ISSUE TITLE
How to add new devices to homebridge

### ISSUE THREAD

**Issue by sjmarkham** [nfarina/homebridge#1789]
I have homebridge running and it’s working great no issues with my smart things devices.   My question is how to get new devices to show up.  For example I added a new z wave switch.  It shows up in my json under my smart apps.  I need to know what steps do I need to do to get it to show up in HomeKit in the iOS app.  When I restart homebridge I see it gets the new device but still can’t figure out how to add to HomeKit unless I completely delete and start over.

**Comment by jresende7** [comment]
I have this problem to !!

**Comment by jblakeney82** [comment]
Hi did you ever figure out how to refresh homebridge in the home app to show the newly added Z-Wave devices?

**Comment by sjmarkham** [comment]
Reboot homebridge worked
