### ISSUE TITLE
Please explain how to create and edit the config.json

### ISSUE THREAD

**Issue by dmarkscouk** [nfarina/homebridge#1791]
Trying to get homebridge working with SmartThings but don't understand how to setup the config file..

I've installed homebridge without an issue. I've also installed homebridge-smartthings-routine-triggers. I've then installed homebridge-routine-triggers.groovy on the SmartThings API website and enabled oAuth.

On the raspberry pi, I don't have a config file and am unsure what to add to the example one. The instructions from the [plugin](https://www.npmjs.com/package/homebridge-smartthings-routine-triggers) say:
> You will need to fetch the accesory config to place in your homebridge config from the newly installed SmartApp and place it in your homebridge config.json file

However I don't understand how to do this.

Any help would be much appreciated.

Thanks,

David.

**Comment by cvccole** [comment]
Anyone ever help explain this?

**Comment by mafyata** [comment]
What is the problem ?
