### ISSUE TITLE
多个homebridge插件，配置文件config.json格式如何书写？

### ISSUE THREAD

**Issue by 18801054468** [nfarina/homebridge#1792]
本人菜鸟一枚，希望大神指点！

假如第一条：

"platforms": [
    {
      "platform": "config",
      "name": "Config",
      "port": 8080,
      "sudo": false
    }
]

第二条：

{
    "platform": "Server",
    "port"    : 8765,
    "name"    : "Homebridge Server",
    "log"     : "<PATH_TO_YOUR_LOG_FILE>",
    "restart" : "<COMMAND_TO_EXECUTE>"
}

第三条：
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:21:3E:E4:DE:33",
        "port": 51826,
        "pin": "031-45-154"
    },
    "description": "Configuration file for (e)xtended Domoticz platform.",
    "platforms": [
        {
            "platform": "eDomoticz",
            "name": "eDomoticz",
            "server": "127.0.0.1",
            "port": "8080",
            "ssl": 0,
            "roomid": 2,
            "mqtt": 1
        }
    ],
    "accessories": []
}

像这样的3条，我如何书写在同一个config.json文件里

**Comment by 18801054468** [comment]
Homebridge Config UI X插件   +  homebridge-edomoticz 插件+homebridge-server

**Comment by DarthCruiser** [comment]
我沒有安裝並運行它，但下面粘貼的JSON.conf文件的內容/結構應該是正確的。 我自己運行Homebridge服務器，所以使用我自己的JSON.conf文件並進行編輯以包含edomoticz。 以下已在JSONLint.com上進行了驗證。

我正在Debian Linux VM上運行Homebridge

{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:21:3E:E4:DE:33",
        "port": 51826,
        "pin": "031-45-154"
    },
    "platforms": [
        {
            "platform": "Server",
            "port": 8765,
            "name": "Homebridge Server",
            "log": "systemd",
            "restart": "sudo systemctl restart homebridge"
        },
        {
         "platform": "eDomoticz",
    "name": "eDomoticz",
    "server": "127.0.0.1",
    "port": "8080",
    "ssl": 0,
    "roomid": 0,
    "mqtt": 1,
    "excludedDevices": []
    }
    ],

          "accessories": []
        }
    ]
}

祝一切順利
