### ISSUE TITLE
Home couldn't connet to this accessory[update info]

### ISSUE THREAD

**Issue by Raccooon** [nfarina/homebridge#1794]
I do can find a near by homebridge
when I scan the picture or enter the code
It will start pairing and but can't finish
After minutes,Couldn't add homebridge
Try to run with Debugs mode
```
npm@5.6.0
node@v8.11.0
homebridge@0.4.38
```

```
{
        "bridge": {
                "name": "Homebridge",
                "username": "A1:36:ED:EF:AC:26",
                "port": 51826,
                "pin": "297-26-913"
        }
}

```
```
EventedHTTPServer [::ffff:192.168.1.160] New connection from client +16m
EventedHTTPServer [::ffff:192.168.1.160] HTTP server listening on port 34455 +6ms
EventedHTTPServer [::ffff:192.168.1.160] HTTP request: /pair-setup +30ms
HAPServer [A2:35:ED:EF:AC:26] HAP Request: POST /pair-setup +3ms
HAPServer [A2:35:ED:EF:AC:26] Pair step 1/5 +9ms
EventedHTTPServer [::ffff:192.168.1.160] HTTP Response is finished +3m
EventedHTTPServer [::ffff:192.168.1.160] Client connection error: This socket has been ended by the other party +16ms
EventedHTTPServer [::ffff:192.168.1.160] Client connection closed +4ms
EventedHTTPServer [::ffff:192.168.1.160] HTTP connection was closed +7ms
EventedHTTPServer [::ffff:192.168.1.160] HTTP server was closed +4ms
```
every time it hangs at
HAPServer [A2:35:ED:EF:AC:26] Pair step 1/5 +9ms
I have done delete home.app, rm -rf persist and acc..., change name and pin
Can you give me some advice

**Comment by Raccooon** [comment]
any one?

**Comment by Raccooon** [comment]
Really need help

**Comment by Raccooon** [comment]
really need help~~~~~~~

**Comment by Raccooon** [comment]
I am so hopeless can anyone help

**Comment by Raccooon** [comment]
Anyone?

**Comment by Lornis** [comment]
I just had the same problem and tried everything. What worked for me was "forgetting" my WIFI from my iPhone, then connecting to it again. Hope this works for you too.

**Comment by Raccooon** [comment]
Anyone can help？

**Comment by andyjkr** [comment]
homebridge is a piece of shit is they can't figure out how to save the QR. fuck homebridge and every asshole who has done work on it without solving such simple fucking things as this. go fuck yourself homebridge.

**Comment by drstil** [comment]
An additional information to this issue: The described trick did not work for me. But what helped was to reboot the WIFI router. Maybe you also add this to the official wiki?

Thank you!

**Comment by hiiragizawakun** [comment]
Hi all - I had an accessory not found issue as well after I nuked my raspberry pi (refresh a new image on an sd card) and tried to add homebridge to Home.

I did all the steps in:
https://github.com/homebridge/homebridge/wiki/Basic-Troubleshooting#home-couldnt-connect-to-this-accessory
https://github.com/homebridge/homebridge/wiki/Basic-Troubleshooting#reset-pairingaccessories

The issue still persists.

However, after waiting for 24 hours and trying to add accessory again, it works!

**Comment by Merco-Benitas** [comment]
> @Lornis This worked for me also. Adding this trick o the official wiki!

Port 51800 needs to be open on your NAS firewall

hi @vdrover. I had the same issue; time out on trying to add the Homebridge as an accessory to my homekit. After spending hours finding a solution, I noticed the firewall on my Synology NAS didn't have port 51800 open for my internal network. 
Maybe you want to add a note about the firewall port to the official wiki too.

I hope this helps

**Comment by Xthienphan** [comment]
> Tôi có thể tìm thấy một cầu nối gần nhà khi tôi quét ảnh hoặc nhập mã. Nó sẽ bắt đầu ghép nối nhưng không thể kết thúc Sau vài phút, Không thể thêm cầu nối chính Cố gắng chạy với chế độ Gỡ lỗi
> 
> ```
> npm@5.6.0
> node@v8.11.0
> homebridge@0.4.38
> ```
> 
> ```
> {
>         "bridge": {
>                 "name": "Homebridge",
>                 "username": "A1:36:ED:EF:AC:26",
>                 "port": 51826,
>                 "pin": "297-26-913"
>         }
> }
> ```
> 
> ```
> EventedHTTPServer [::ffff:192.168.1.160] New connection from client +16m
> EventedHTTPServer [::ffff:192.168.1.160] HTTP server listening on port 34455 +6ms
> EventedHTTPServer [::ffff:192.168.1.160] HTTP request: /pair-setup +30ms
> HAPServer [A2:35:ED:EF:AC:26] HAP Request: POST /pair-setup +3ms
> HAPServer [A2:35:ED:EF:AC:26] Pair step 1/5 +9ms
> EventedHTTPServer [::ffff:192.168.1.160] HTTP Response is finished +3m
> EventedHTTPServer [::ffff:192.168.1.160] Client connection error: This socket has been ended by the other party +16ms
> EventedHTTPServer [::ffff:192.168.1.160] Client connection closed +4ms
> EventedHTTPServer [::ffff:192.168.1.160] HTTP connection was closed +7ms
> EventedHTTPServer [::ffff:192.168.1.160] HTTP server was closed +4ms
> ```
> 
> mỗi lần nó bị treo ở HAPServer [A2:35:ED:EF:AC:26] Pair step 1/5 +9ms Mình làm xong xóa home.app, rm -rf và acc..., đổi tên và pin được không bạn cho tôi một vài lời khuyên
