### ISSUE TITLE
Homebridge not found in Homekit.... (wifi issue)

### ISSUE THREAD

**Issue by Unrender** [nfarina/homebridge#1797]
Hi,

I've been on this issue (unable to pair homebridge with HomeKit cause it is not found in this one) for 3 days. 
I've got an iPhone 7 with 11.3 iOS -> not found
My daughter's iPhone 5 with 11.3 iOS -> found without problem

I've just seen that she is on the 5.0 Ghz band and me on the 2.4 Ghz band...

So, I change my wifi band and now it works great....
Don't understand what is the matter with the other band.

So... if this can help someone.

Have a nice day ;)

**Comment by Raccooon** [comment]
I think you need to check your wifi
Does 2.4 and 5 in the same bridge?
Check with avahi-browse.
```
sudo apt-get update
sudo apt-get install avahi-utils
avahi-browse -at|fgrep _hap._tcp
```

**Comment by Unrender** [comment]
Not sure to understand what you have told :)
Here is the result of avahi-browse 👍 
`pi@raspberrypi:~ $ avahi-browse -at|fgrep _hap._tcp
+   eth0 IPv6 Healthy Home Coach                            _hap._tcp            local
+   eth0 IPv6 Homebridge                                    _hap._tcp            local
+   eth0 IPv4 Healthy Home Coach                            _hap._tcp            local
+   eth0 IPv4 Homebridge                                    _hap._tcp            local`

but don't know if it's good or not...
