### ISSUE TITLE
How to add multiple platforms and accessories got 1 working cannot add more

### ISSUE THREAD

**Issue by sjmarkham** [nfarina/homebridge#1798]
Help adding my dyson cool link to home kit.  I set it up been when homebridge reboots this is all that i see.
[2018-4-1 20:14:15] [DysonPlatform] Initializing DysonPlatform platform...
[2018-4-1 20:14:15] [DysonPlatform] Finished launching. Start to create accessory from config

This is my current config.json which smart things works without any problem.  I just cannot figure out how to add other devices and or accessories.

{
        "description": "JSON API",
        "platforms": [{
                        "platform": "homebridge-smartthings.SmartThings",
                        "name": "SmartThings",
                        "app_url": "",
                        "app_id": "",
                        "access_token": ""
                },
                {
                        "platform": "DysonPlatform",
                        "name": "DysonPlatform",
                        "ip": "******",
                        "displayName": "Dyson",
                        "serialNumber": "***************",
                        "password": "**********"
                }
        ],
        "bridge": {
                "name": "Homebridge",
                "username": "AA:BB:CC:DD:EE:FF",
                "port": 51826,
                "pin": "123-45-678"
        }
}

**Comment by jvmahon** [comment]
Often when you specify a "platform" (such as DysonPlatform), within the platform specification there is an "accessories" specification that further defines the accessories for that specific platform. SmartThings doesn't seem to require that, but it does seem to be how DysonPlatform works. This is shown in a bit more detail here: https://www.npmjs.com/package/homebridge-dyson-link . So I think you need to further specify each the Dyson accessories in the position I've shown below:

````
{
"description": "JSON API",
"platforms": [{
"platform": "homebridge-smartthings.SmartThings",
"name": "SmartThings",
"app_url": "",
"app_id": "",
"access_token": ""
},
{
"platform": "DysonPlatform",
"name": "DysonPlatform",
"ip": "******",
"displayName": "Dyson",
"serialNumber": "*****",
"password": ""

     "accessories": [
      {  Enter information for the first accessory here },
      { Enter information for the second DysonPlatform accessory here},
      { And so on for each additional DysonPlatform accessory },
      {Enter information for the lastDysonPlatform accessory here. No comma after last curly brace}
      ]

}
],
"bridge": {
"name": "Homebridge",
"username": "AA:BB:CC:DD:EE:FF",
"port": 51826,
"pin": "123-45-678"
}
}
````
