### ISSUE TITLE
Multiple homebridge http accessories

### ISSUE THREAD

**Issue by Bashface** [nfarina/homebridge#1799]
hi i have successfully set up i homebridge http accessory here is the Config.Json
[config.json.zip](https://github.com/nfarina/homebridge/files/1866801/config.json.zip)

i then wanted to add another accessory how do i do soo?

**Comment by jvmahon** [comment]
Put a comma after the curly brace that ends the first accessory, then set out the info. for each subsequent accessory in a new set of curly braces like so:

```
{
	"bridge": {
		"name": "HomeBridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},

	"description": "HomeBridge HTTP Status Control",

	"accessories": 
	[
		{
			"accessory": "Switcheroo",
			"type": "switch",
			"name": "Kitchen Light",
			"host": "http://192.168.1.50",
			"on": "/cm?cmnd=Power%20On",
			"off": "/cm?cmnd=Power%20Off"
		},
		{
			second accessory info. goes here!
		},
		{
			third accessory info. goes here!
		}
	]
}
```

Note that the last curly brace } should *not* be followed by a comma!

**Comment by Bashface** [comment]
Thanks I finally got it to work. You made my day
