### ISSUE TITLE
After switching router to NETGEAR R9000 homebridge devices show "no response" after a few minutes

### ISSUE THREAD

**Issue by amatrosovas** [nfarina/homebridge#1800]
When I connect my other router everything works as expected with no issues, as soon as I connect my NETGEAR R9000 after working for a minute or so devices become unresponsive. I've read that it might have something to do with multicast but not sure. Anyone had similar issue or know how to solve this?

**Comment by jarvismeier** [comment]
I have the same problem with my Netgear Orbi system.  I know they put out firmware fixes for an android chromecast MDNS flood issue.  I assume this has messed with Apple Homekit.
