### ISSUE TITLE
When I install HomeBridge,I have some problems😂

### ISSUE THREAD

**Issue by Sstefyuk2004** [nfarina/homebridge#1803]
dns_sd.cpp
  dns_service_browse.cpp
c:\users\sviatoslav\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083:
Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\dns_service_browse.cpp) [
C:\Users\Sviatoslav\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
c:\users\sviatoslav\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083:
Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\dns_sd.cpp) [C:\Users\Svi
atoslav\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  dns_service_enumerate_domains.cpp
  dns_service_get_addr_info.cpp
                                                                                         c:\users\sviatoslav\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083:
Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\dns_service_enumerate_dom
ains.cpp) [C:\Users\Sviatoslav\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxp
roj]
  dns_service_process_result.cpp
c:\users\sviatoslav\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083:
Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\dns_service_get_addr_info
.cpp) [C:\Users\Sviatoslav\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  dns_service_ref.cpp
c:\users\sviatoslav\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083:
Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\dns_service_process_resul
t.cpp) [C:\Users\Sviatoslav\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj
]
  dns_service_ref_deallocate.cpp
c:\users\sviatoslav\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083:
Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\dns_service_ref.cpp) [C:\
Users\Sviatoslav\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  dns_service_ref_sock_fd.cpp
c:\users\sviatoslav\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083:
Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\dns_service_ref_deallocat
e.cpp) [C:\Users\Sviatoslav\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj
]
  dns_service_register.cpp
c:\users\sviatoslav\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083:
Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\dns_service_ref_sock_fd.c
pp) [C:\Users\Sviatoslav\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  dns_service_resolve.cpp
c:\users\sviatoslav\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083:
Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\dns_service_register.cpp)
 [C:\Users\Sviatoslav\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
c:\users\sviatoslav\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083:
Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\dns_service_resolve.cpp)
[C:\Users\Sviatoslav\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  dns_service_update_record.cpp
  mdns_utils.cpp
c:\users\sviatoslav\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083:
Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\mdns_utils.cpp) [C:\Users
\Sviatoslav\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  network_interface.cpp
c:\users\sviatoslav\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083:
Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\dns_service_update_record
.cpp) [C:\Users\Sviatoslav\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  socket_watcher.cpp
c:\users\sviatoslav\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083:
Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\network_interface.cpp) [C
:\Users\Sviatoslav\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  txt_record_ref.cpp
c:\users\sviatoslav\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083:
Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\socket_watcher.cpp) [C:\U
sers\Sviatoslav\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  txt_record_create.cpp
c:\users\sviatoslav\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083:
Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\txt_record_ref.cpp) [C:\U
sers\Sviatoslav\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  txt_record_deallocate.cpp
c:\users\sviatoslav\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083:
Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\txt_record_create.cpp) [C
:\Users\Sviatoslav\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  txt_record_set_value.cpp
c:\users\sviatoslav\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083:
Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\txt_record_deallocate.cpp
) [C:\Users\Sviatoslav\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  txt_record_get_length.cpp
c:\users\sviatoslav\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083:
Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\txt_record_set_value.cpp)
 [C:\Users\Sviatoslav\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  txt_record_buffer_to_object.cpp
c:\users\sviatoslav\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083:
Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\txt_record_buffer_to_obje
ct.cpp) [C:\Users\Sviatoslav\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxpro
j]
c:\users\sviatoslav\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083:
Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\txt_record_get_length.cpp
) [C:\Users\Sviatoslav\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  win_delay_load_hook.cc
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Sviatoslav\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Sviatoslav\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\npm-lifecycle\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Sviatoslav\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mdns@2.3.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mdns@2.3.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Sviatoslav\AppData\Roaming\npm-cache\_logs\2018-04-03T17_53_20_613Z-debug.log  dns_sd.cpp
  dns_service_browse.cpp
c:\users\sviatoslav\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083:
Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\dns_service_browse.cpp) [
C:\Users\Sviatoslav\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
c:\users\sviatoslav\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083:
Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\dns_sd.cpp) [C:\Users\Svi
atoslav\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  dns_service_enumerate_domains.cpp
  dns_service_get_addr_info.cpp
                                                                                         c:\users\sviatoslav\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083:
Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\dns_service_enumerate_dom
ains.cpp) [C:\Users\Sviatoslav\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxp
roj]
  dns_service_process_result.cpp
c:\users\sviatoslav\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083:
Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\dns_service_get_addr_info
.cpp) [C:\Users\Sviatoslav\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  dns_service_ref.cpp
c:\users\sviatoslav\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083:
Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\dns_service_process_resul
t.cpp) [C:\Users\Sviatoslav\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj
]
  dns_service_ref_deallocate.cpp
c:\users\sviatoslav\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083:
Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\dns_service_ref.cpp) [C:\
Users\Sviatoslav\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  dns_service_ref_sock_fd.cpp
c:\users\sviatoslav\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083:
Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\dns_service_ref_deallocat
e.cpp) [C:\Users\Sviatoslav\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj
]
  dns_service_register.cpp
c:\users\sviatoslav\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083:
Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\dns_service_ref_sock_fd.c
pp) [C:\Users\Sviatoslav\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  dns_service_resolve.cpp
c:\users\sviatoslav\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083:
Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\dns_service_register.cpp)
 [C:\Users\Sviatoslav\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
c:\users\sviatoslav\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083:
Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\dns_service_resolve.cpp)
[C:\Users\Sviatoslav\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  dns_service_update_record.cpp
  mdns_utils.cpp
c:\users\sviatoslav\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083:
Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\mdns_utils.cpp) [C:\Users
\Sviatoslav\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  network_interface.cpp
c:\users\sviatoslav\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083:
Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\dns_service_update_record
.cpp) [C:\Users\Sviatoslav\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  socket_watcher.cpp
c:\users\sviatoslav\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083:
Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\network_interface.cpp) [C
:\Users\Sviatoslav\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  txt_record_ref.cpp
c:\users\sviatoslav\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083:
Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\socket_watcher.cpp) [C:\U
sers\Sviatoslav\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  txt_record_create.cpp
c:\users\sviatoslav\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083:
Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\txt_record_ref.cpp) [C:\U
sers\Sviatoslav\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  txt_record_deallocate.cpp
c:\users\sviatoslav\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083:
Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\txt_record_create.cpp) [C
:\Users\Sviatoslav\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  txt_record_set_value.cpp
c:\users\sviatoslav\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083:
Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\txt_record_deallocate.cpp
) [C:\Users\Sviatoslav\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  txt_record_get_length.cpp
c:\users\sviatoslav\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083:
Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\txt_record_set_value.cpp)
 [C:\Users\Sviatoslav\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  txt_record_buffer_to_object.cpp
c:\users\sviatoslav\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083:
Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\txt_record_buffer_to_obje
ct.cpp) [C:\Users\Sviatoslav\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxpro
j]
c:\users\sviatoslav\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083:
Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\src\txt_record_get_length.cpp
) [C:\Users\Sviatoslav\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  win_delay_load_hook.cc
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Sviatoslav\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Sviatoslav\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\npm-lifecycle\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Sviatoslav\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mdns@2.3.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mdns@2.3.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Sviatoslav\AppData\Roaming\npm-cache\_logs\2018-04-03T17_53_20_613Z-debug.log

**Comment by i3laze** [comment]
Looks like last Troubleshooting step from [Wiki](https://github.com/nfarina/homebridge/wiki/Install-HomeBridge-on-Windows-10-(new)). Please try it.
