### ISSUE TITLE
How to change the default values

### ISSUE THREAD

**Issue by cflurin** [nfarina/homebridge#181]
How can I change the default values of a Characteristic like minimumValue, maximumValue or stepValue?

**Comment by nfarina** [comment]
So if you're creating a custom characteristic with `new Characteristic(...)` then you can just assign those properties like `myCustomCharacteristic.minimumValue = 15` etc. I'm not sure if this is supported by Apple for their built-in Characteristics but you could try.

**Comment by cflurin** [comment]
With the HKA-Simulator when I add a characteristic like "Target Horizontal Tili Angle" I can change min Value, max Value and step Value. So I suppose it's supported by Apple. My Goal is to change the min Value from -90 to 0. I tried:
``` javascript
var FhemWindowCoveringService = new Service.WindowCovering();
var CurrentHorizontalTiltAngle = FhemWindowCoveringService
        .addCharacteristic(Characteristic.CurrentHorizontalTiltAngle)
...
CurrentHorizontalTiltAngle.minimumValue = 0;
```
but it doesn't work.

**Comment by nfarina** [comment]
You'll need to set the property on your particular instance of the characteristic, not the global class example:

```js
var FhemWindowCoveringService = new Service.WindowCovering();
var CurrentHorizontalTiltAngle = FhemWindowCoveringService
        .addCharacteristic(Characteristic.CurrentHorizontalTiltAngle)
...
FhemWindowCoveringService
        .getCharacteristic(Characteristic.CurrentHorizontalTiltAngle)
        .minimumValue = 0;
```

**Comment by nfarina** [comment]
[removed previous response because you are already doing that of course]

Your example looks like it should work... can you confirm it's not setting it properly by fetching `/accessories` locally?

**Comment by cflurin** [comment]
with:
```javascript
      var FhemWindowCoveringService = FhemWindowCoveringService
        .addCharacteristic(Characteristic.CurrentHorizontalTiltAngle)
        .on('get', this.getCurrentHorizontalTiltAngle.bind(this));
        
      FhemWindowCoveringService
        .getCharacteristic(Characteristic.CurrentHorizontalTiltAngle)
        .minimumValue = 0
        .maximumValue = 90
        .stepValue = 5;
```
I got:
```
["pr","ev"],"format":"int32","value":35,"description":"Current Horizontal Tilt Angle",
"unit":"arcdegrees","maxValue":90,"minValue":5,"minStep":1}
```
minValue should be 0 and not 5.

**Comment by nfarina** [comment]
Wow, I'm amazed that code actually runs - what's happening here is the statements after the initial assignment are ignored. Setting a property doesn't return the object like the `.get()` function does. What you want is:

```js
var tiltAngle = FhemWindowCoveringService.getCharacteristic(Characteristic.CurrentHorizontalTiltAngle);
tiltAngle.minimumValue = 0;
tiltAngle.maximumValue = 90;
tiltAngle.stepValue = 5;
```

**Comment by nfarina** [comment]
Maybe we should add jQuery-style setters to help with this - i.e. `.getCharacteristic(...).setMinimumValue(5).setMaximumValue(10)` etc.

**Comment by cflurin** [comment]
With:
```` javascript
      var CurrentTiltAngle = FhemWindowCoveringService.getCharacteristic(Characteristic.CurrentHorizontalTiltAngle);
      CurrentTiltAngle.minimumValue = 0;
      CurrentTiltAngle.maximumValue = 90;
      CurrentTiltAngle.stepValue = 5;
````
I got:
```
"Current Horizontal Tilt Angle","unit":"arcdegrees","maxValue":90,"minValue":0,"minStep":5}
```
but the AVE app ignore the settings.

**Comment by cflurin** [comment]
.setMinimumValue(0) ... will be great!    [like .setValue(x)]

**Comment by KhaosT** [comment]
@nfarina there is a issue with generating HomeKit types from Simulator's default metadata, int32 should be mapped to "int" otherwise HomeKit will think the metadata provided by server is invalid. Would you mind to change that in the HAP-NodeJS repo?

**Comment by nfarina** [comment]
Will do.

**Comment by nfarina** [comment]
Took a stab at both of these here: https://github.com/KhaosT/HAP-NodeJS/pull/135

**Comment by cflurin** [comment]
Wow, this is a huge work. Thanks. I'll install this version on my Test-RPI.

**Comment by cflurin** [comment]
@nfarina I think the package.json should be updated:
```
- "hap-nodejs": "git+https://github.com/KhaosT/HAP-NodeJS#0030b35856e04ee2b42f0d05839feaa5c44cbd1f",
+ "hap-nodejs": "git+https://github.com/KhaosT/HAP-NodeJS#4650e771f356a220868d873d16564a6be6603ff7",
```

**Comment by nfarina** [comment]
Oops, thanks!
