### ISSUE TITLE
Characteristic.TargetPosition take position when slider moving slow.

### ISSUE THREAD

**Issue by radebebek** [nfarina/homebridge#1813]
Dear,
My Plugin for blinds takes target position wrong when I moving slow slider.
I moved slider from 0% to 50% slow, but plugin take some position in middle (for example 20%).
Blinds start moving to 20%, in my Home App 50%
But when I exit application HOME and after that turn on application. Show Position in correct 20%.
Can you fix it. Maybe that homebridge wait some time (3 s) and after that take Target Position. 
Or need to be programing at the plugin level?

Rade

**Comment by NorthernMan54** [comment]
Unfortunately this is a plugin issue.
