### ISSUE TITLE
Home app on iPhone X can't connect to HomeBridge on Win10

### ISSUE THREAD

**Issue by imashwin** [nfarina/homebridge#1822]
### Expected Behavior

I can't seem to connect HomeBridge (running on Windows 10) on the Home app on my iPhone X. All devices are on the same network.

### Current Behavior

When I either scan the HomeKit barcode or enter the appropriate code, iPhone X's Home app can't seem to connect to Homebridge.

### Versions

- **Homebridge**: 0.4.38
- **Node**: v8.9.4
- **OS**: Windows 10 Pro

### Configuration

```json

{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:20",
        "port": 51826,
        "pin": "031-45-154"
    },
    "description": "Config file.",
    "accessories": [ ],
    "platforms": [
   	{
   		"platform": "Nest",
   		"clientId": "<client ID entered here>",
   		"clientSecret": "<client secret entered here>",
   		"code": "<code entered here>",
		"token": "<token entered here>"
   	}
   ]
}

```

### Homebridge Log / Command Output

```

```

**Comment by cubilon** [comment]
check windows firewall

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by imashwin** [comment]
Based on your comment, I went into Windows Firewall and specifically opened up the port. Restarted Homebridge, but the issue still persists. :(

**Comment by cubilon** [comment]
try stopping the firewall service, just to be sure

**Comment by imashwin** [comment]
I've stopped the firewall, but the issue persists.

**Comment by imashwin** [comment]
Hmm, I don't have any blocked (or unblocked) Node.js entries on my inbound rules.
