### ISSUE TITLE
Home app becomes unresponsive, log doesn't show any commands, but shows multiple error events.

### ISSUE THREAD

**Issue by Cooldude9210** [nfarina/homebridge#1827]
### Expected Behavior
Opening Home.app or Home from control center, scenes should turn on scenes from Harmony Hub plugin. Or, in the case of the shutdown scene, all devices should be set to OFF.
### Current Behavior
Scene fills circle ~75-80% of the way, stalls, then says "failed." Upon checking the logs, nothing has been reported since the last time the service was restarted, which happened due to errors listed below.
### Steps to Reproduce (for bugs)
Unsure how to reproduce, since it's variable how long homebridge will run without issues before needing to be reset.

### Versions

- **Homebridge**: 0.4.38
- **Node**: 6.10.2
- **OS**: macOS High Sierra 10.13.3

[EDIT 4/25 00:58 PST] Ran npm -g outdated, got a version of 3.10.10, updated to 6.0.0.
### Configuration
```
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": Not sure if this should be listed or not :/
    },

    "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",

    "accessories": [],

    "platforms": [
      {
        "platform": "HarmonyHub",
        "name": "Harmony Hub"
      }
    ]
}
```
### Homebridge Log / Command Output
Not sure how much to paste, since the errors are sometimes there and sometimes not. Also interesting to note is that no commands are ever logged; is that normal behavior? No logs are located at /var/log/homebridge.err or var/log/homebridge.log This log was found at ~/.homebridge/logfile.log
```
https://pastebin.com/aGgdUtEb
```

**Comment by avdz** [comment]
I'm seeing the same error. I think apple updated their homekit behaviour a little bit. Still looking into this.

**Comment by rposborne** [comment]
You may have better luck posting an issue over at https://github.com/KraigM/homebridge-harmonyhub/issues

As it looks like that error is within that module.
