### ISSUE TITLE
Home app refreshing sensor only when I open it

### ISSUE THREAD

**Issue by daniel4099** [nfarina/homebridge#1828]
Hi

I have node v 7.10.0
homebridge 0.4.20

When I set the motion sensor for any actions it will not work on background. I need to open home app and then it's show motion detected and execte action.

Please help

**Comment by skywalker1979** [comment]
You need to install mqtt and configure it in the homebridge configuration file if you have not done it..

**Comment by palasinio** [comment]
Can you explain this please?

**Comment by skywalker1979** [comment]
Not in much detail...you need to install mqtt...and put the appropriate settings in the configuration file of homebridge ...in the domoticz area...that way the update happens also in the background...and not only when you open the home app.

**Comment by skywalker1979** [comment]
Maybe take a look here...https://github.com/nfarina/homebridge/issues/742

**Comment by palasinio** [comment]
THE :)

**Comment by skywalker1979** [comment]
You are welcome! Working now?😊

**Comment by palasinio** [comment]
Sorry, I misunderstood something. I thought this could update Home in general.

**Comment by skywalker1979** [comment]
Yes I understood, and I gave you a hint to follow. Domoticz needs a way to tell HomeKit that sensors have been updated. That is way you need mqtt. Mqtt also needs to be configured  in domoticz and homebridge.
