### ISSUE TITLE
Xiaomi Hygrothermograph Homebridge doesn't work

### ISSUE THREAD

**Issue by AlbertoZantedeschi** [nfarina/homebridge#1829]
Hello everyone! I installed the homebridge plugin for xiaomi hygrothermograph (https://www.npmjs.com/package/homebridge-mi-hygrothermograph). To work it needs libbluetooth-dev (installation ok) and NOBLE (https://github.com/noble/noble), but I think I'm having trouble installing noble on my Ubuntu 16.04 and understand how to use it. This is the message that appears during the installation:

npm WARN checkPermissions Missing write access to /home/home/node_modules
/home/home
└── noble@1.9.1 

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: xpc-connection@~0.1.4 (node_modules/noble/node_modules/xpc-connection):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for xpc-connection@0.1.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"ia32"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: xpc-connection@~0.1.4 (node_modules/bleno/node_modules/xpc-connection):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for xpc-connection@0.1.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"ia32"})
npm WARN enoent ENOENT: no such file or directory, open '/home/home/package.json'
npm WARN home No description
npm WARN home No repository field.
npm WARN home No README data
npm WARN home No license field.
npm ERR! Linux 4.13.0-39-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "noble"
npm ERR! node v6.14.1
npm ERR! npm  v3.10.10
npm ERR! path /home/home/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/home/home/node_modules'
npm ERR!     at Error (native)
npm ERR!  { Error: EACCES: permission denied, access '/home/home/node_modules'
npm ERR!     at Error (native)
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/home/home/node_modules' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/home/npm-debug.log 

I configured config.json with the plugin settings and the accessories appear in Home App on iPhone, but, they do not respond .
{
 "bridge": {
 "name": "Homebridge",
 "username": "CC:21:3E:E4:DE:33",
 "port": 51826,
 "pin": "031-45-154"
 },
 "description": "Configuration file for (e)xtended Domoticz platform.",
 "platforms": [
 {
 "platform": "eDomoticz",
 "name": "eDomoticz",
 "server": "127.0.0.1",
 "port": "8080",
 "ssl": 0,
 "roomid": 0,
 "mqtt": 1
 },
{
"platform": "Camera-ffmpeg",
"cameras": [
{
"name": "Cancello",
"uploader": false,
"videoConfig": {
"source": "-rtsp_transport tcp -i rtsp://192.168.1.X/unicast",
"stillImageSource": "-i rtsp://192.168.1.X/unicast -frames 1 -r 1",
"maxStreams": 2,
"maxFPS": 10,
"maxWidth": 1280,
"maxHeight": 720,
"vcodec": "h264_omx"
}
}
]
}
],

 "accessories": [
 {
      "accessory": "Hygrotermograph",
      "name": "Temperature & Humidity",
      "address": "4c:65:a8:d3:de:47",
      "timeout": 10,
      "temperatureName": "Temperatura",
      "humidityName": "Umidità"
 }
]
}

Can someone help me?
Thank You in advance
Bye

**Comment by rposborne** [comment]
This is a linux permissions issue, not a homebridge one. 

Ensure that your logged in user has write access to the `node_modules` directory
