### ISSUE TITLE
NodeJS 10.0 incompatibility?

### ISSUE THREAD

**Issue by NiklasBr** [nfarina/homebridge#1830]
### Expected Behavior
Homebridge should start

### Current Behavior
Does not start, reports version incompatibility: "The module 'dns_sd_bindings.node'
was compiled against a different Node.js …"

### Steps to Reproduce (for bugs)
Update Node with Brew or similar method.

### Versions
- **Homebridge**: 0.4.38 (because `homebridge --version` throws an error, so I found it with: `cat /usr/local/lib/node_modules/homebridge/package.json | grep version`
- **Node**:       v10.0.0
- **OS**:         macOS 10.13.4 (17E202)

### Configuration
```json
{
    "bridge": {
        "name": "Homebridge",
        "username": "[hidden]",
        "port": 51826,
        "pin": "[hidden]"
    },
    "description": "",
    "accessories": [
    ],
    "platforms": [
        {
            "platform": "BelkinWeMo",
            "name": "WeMo Platform",
            "expected_accessories": "4",
            "timeout": "25",
            "homekit_safe": "1"
        }
    ]
}
```

### Homebridge Log / Command Output
```
Error: The module '/usr/local/lib/node_modules/homebridge/node_modules/mdns/build/Release/dns_sd_bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 59. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:707:18)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/mdns/lib/dns_sd.js:24:20)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
```

**Comment by mestery** [comment]
Same issue here.

**Comment by mestery** [comment]
Tried downgrading to a prior version of node via homebrew link/unlink and still hit the issue.

**Comment by ckd** [comment]
Some of homebridge's dependencies, such as mdns, themselves have dependencies that are incompatible with Node 10. You should be able to revert to Node 9.x and run `npm rebuild`

**Comment by NiklasBr** [comment]
I reverted back to:

```sh
$ node -v && npm -v
v8.11.1
5.6.0
$ homebridge 
/usr/local/lib/node_modules/homebridge/node_modules/mdns/lib/dns_sd.js:35
    throw ex;
    ^

Error: The module '/usr/local/lib/node_modules/homebridge/node_modules/mdns/build/Release/dns_sd_bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 59. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (module.js:681:18)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/mdns/lib/dns_sd.js:24:20)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
```

Homebridge still reports this error, though with still too late a version. I could have sworn I had it running on Node 9 previously.

**Comment by ckd** [comment]
Did you actually run `npm rebuild`?

**Comment by NiklasBr** [comment]
I did that after downgrading with:

 1. $ `brew switch node 8.11.1`
 2. $ `brew link --overwrite node`

See gist: https://gist.github.com/NiklasBr/faf3ce4bdd9844bf1387f1dacefaf71c

**Comment by palasinio** [comment]
Has someone Homebridge running with node.js 10?

**Comment by NiklasBr** [comment]
@palasinio I don't think so, [this issue](https://github.com/agnat/node_mdns/issues/215) suggests that Node.js version 10 is incompatible with the current version of the MDNS module.

**Comment by palasinio** [comment]
@NiklasBr: Thx for this information.

**Comment by camrun91** [comment]
It looks like the mdns module referenced above has been updated it is seen in the issue niklasBr posted.

**Comment by rposborne** [comment]
I have Homebridge running happily on node 10, I blew it away from node_modules and was able to reinstall. 

I had no luck with the rebuild command. 

Make sure you are running npm 6.0 or higher.

**Comment by NiklasBr** [comment]
@rposborne How did you get it to work?

I am running Node 10 and NPM 6, but still no luck after rebuilding: https://gist.github.com/NiklasBr/7af5c09c07f61e7c60a1642b9a37ef52

**Comment by rposborne** [comment]
It looks like your error is more along the lines of running it twice.   Are you loading it with launchtl (it looks like you are running on a mac)  

You might need to update the launch ctl script. But that would be surprising.

**Comment by rposborne** [comment]
@NiklasBr it also looks like the issue you ran up against has been fixed.

**Comment by NiklasBr** [comment]
I'll try to reinstall everything from scratch, anyway, here's the Launchctl info:

```sh
$ launchctl list | grep home
2459	1	com.homebridge.server
```
and
```sh
$ cat ~/Library/LaunchAgents/com.homebridge.server.plist 
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>RunAtLoad</key>
        <true/>
    <key>KeepAlive</key>
        <true/>
    <key>Label</key>
        <string>com.homebridge.server</string>
    <key>ProgramArguments</key>
        <array>
             <string>/usr/local/bin/homebridge</string>
             <string>-I</string>
        </array>
    <key>StandardOutPath</key>
        <string>/Users/niklas/.homebridge/logfile.log</string>
    <key>StandardErrorPath</key>
        <string>/Users/niklas/.homebridge/logfile.log</string>
    <key>EnvironmentVariables</key>
        <dict>
        <key>PATH</key>
            <string>/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
        <key>HOME</key>
            <string>/Users/niklas</string>
        </dict>
</dict>
</plist>
```

**Comment by rposborne** [comment]
Things to check,  remove older versions of node, just to be sure you are not referencing an unexpected path.  I run `brew cleanup` pretty often just to clear the cruft but be careful with that command.

Make sure you unload launchctrl  if you are manually starting homebridge. (or change the config.json port)  < I suspect this is the issue from the last error. Seeing your launchctrl is identical as mine.

**Comment by NiklasBr** [comment]
I blew it all away. Removed Node and NPM and Homebridge (except for the config file) and then re-installed everything and rebooted and now it is back working again with the following versions:

```sh
$ node -v && npm -v && homebridge --version
v10.0.0
5.6.0
0.4.42
```

Then I updated NPM to version 6 and it worked:

```sh
$ npm i npm -g
$ killall homebridge
$ node -v && npm -v && homebridge --version
v10.0.0
6.0.0
0.4.42
```

I'll close this issue now as the incompatibility is resolved. Thank you @rposborne

**Comment by rposborne** [comment]
@NiklasBr Glad I gave you the hope that it could be done :)
