### ISSUE TITLE
Is BatteryService unsupported in HomeKit?

### ISSUE THREAD

**Issue by dinmammas** [nfarina/homebridge#1831]
I found there's a battery service here;
https://github.com/KhaosT/HAP-NodeJS/blob/4df078d3482922fcc9edaa38d35c6fda63733df1/lib/gen/HomeKitTypes.js#L2730

And I tried building a plugin based on that here; https://github.com/dinmammas/homebridge-robonect

But the Home app says it's not supported. Is it unsupported, or have I made an error in my code?

**Comment by NorthernMan54** [comment]
I haven't tried battery service, but I have tried status low battery, and can confirm that it works okay.  Have you tried it with the Eve app?  Sometimes the Home app says that for services they don't support yet, like speaker.

https://github.com/NorthernMan54/homebridge-heyu/blob/master/index.js#L428

![image](https://user-images.githubusercontent.com/19808920/39400453-b7eeec02-4afe-11e8-83c5-14580fabe217.png)

**Comment by ebaauw** [comment]
I use the Battery service extensively in homebridge-hue.  You need to provide the three mandatory characteristics: Battery Level, Charging State, and Status Low Battery.  Most apps (Apple’s Home and Eve) don’t show the service, but they do show a battery symbol or level with the accessory.

**Comment by dinmammas** [comment]
I think I am doing things as I should?
`let batteryService = new Service.BatteryService("Batterinivå");
    batteryService
      .getCharacteristic(Characteristic.BatteryLevel)
        .on('get', this.getBatteryLevelCharacteristic.bind(this));
    batteryService
      .getCharacteristic(Characteristic.ChargingState)
        .on('get', this.getChargingStateCharacteristic.bind(this));
    batteryService
      .getCharacteristic(Characteristic.StatusLowBattery)
        .on('get', this.getLowBatteryCharacteristic.bind(this));`
Formatting gone awry above...

The thing is, I see it in the Home app, but not in Eve or Hesperus... Could someone look at my code and see if I made an error? This is my first attempt at anything node/Homebridge.

**Comment by ebaauw** [comment]
In Eve, the battery is shown on the accessory screen:
![img_0074](https://user-images.githubusercontent.com/22179355/39409672-a110196e-4beb-11e8-98a9-326b5ff9e7f3.png)

**Comment by dinmammas** [comment]
Ah. This is probably a brain fart on my end. I'm trying to use the battery service as an accessory... Is there a list of accessory types somewhere?

**Comment by dinmammas** [comment]
So, we can close this. Battery Service do not like to be treated as an accessory on it's own. I've now put both a HumiditySensor and a Switch in my plugin (link above), and both displays the battery/chargingstate etc perfectly.

**Comment by datjan** [comment]
> Ah. This is probably a brain fart on my end. I'm trying to use the battery service as an accessory... Is there a list of accessory types somewhere?

Maybe nice to know:
You can use service "BatteryService" with catergoy "Other". In this case you see a battery device in homekit.

![IMG_9336](https://github.com/homebridge/homebridge/assets/69371018/42517920-27f5-46ed-931b-292004e62361)
