### ISSUE TITLE
After update to 0.4.42 no response from devices - On a RPI with multiple network interfaces

### ISSUE THREAD

**Issue by NorthernMan54** [nfarina/homebridge#1843]
I went thru and performed an update to all my instances on homebridge, and everything worked fine until I updated one instance I have on a RPI with multiple network interfaces.  After updating I found that the Home app was showing no response for all devices from that instance of homebridge.

After digging into the issue, I found that the MDNS packets advertising homebridge were not visible on the local network.  As a workaround I installed the older version and it worked okay.

To install the older version I used

sudo npm install -g homebridge@0.4.38

**Comment by NorthernMan54** [comment]
@KhaosT After looking at the bonjour and multicast-dns code it appears to be broadcasting bonjour packets only on one interface on a RPI with multiple interfaces.   I was also able to workaround the issue by hard coding my preferred network interface in this line

https://github.com/mafintosh/multicast-dns/blob/master/index.js#L65

I think to fix this properly we will need to look at how MDNS was handling multiple network interfaces, and try and mimic the same behaviour with bonjour/multicast-dns.  One thing I did notice on my RPI was that IPTABLES started complaining about bonjour packets after the upgrade, which makes me suspect that MDNS may have defaulted to a different interface, or had different behaviour in this scenario.  I don't think MDNS was using my second interface.

Over the next few days I'm going to dig into this further, so expect a pull request at some point.  Likely in bonjour-hap.

PS Two thumbs up on the conversion to bonjour, all the rest of my setup and plugins worked perfectly, including my homebridge-alexa which I was the most worried about as it uses bonjour to discover homebridge instances.

**Comment by pponce** [comment]
I installed 0.4.42 and started receiving accessories not responding errors in the Apple home app.
Unfortunately rolling back to 0.4.38 didn’t fix things. Still getting the accessories not responding errors.

**Comment by pponce** [comment]
I had to remove homebridge accessory and re-add it to get things back in order for some reason.
I'm going to stick with 0.4.42 and just "sudo ifdown wlan0" for now. Seems to work well when i do that.

**Comment by rotx** [comment]
I have a related problem, but I'm running on macOS. Since 0.4.42, the Bonjour advertisement includes all IP addresses, including various VPN and VLAN interfaces. For some reason, the Home app tries to connect to an address that is outside the local LAN but accessories are unreachable because Home never receives SYNACK packets (I did the upgrade because the older mdns was not compatible with node v10).

@NorthernMan54 , what is the syntax for hard coding the interface?

**Comment by rotx** [comment]
@NorthernMan54 Yes you are correct. I read the release note history and apparently I got bit by the 0.4.41 problem. I restored accessories and persists folders from backup, re-upgraded to 0.4.42 and it's working again. So at least on macOS with multiple interfaces (I have about 10), the current code is working.

**Comment by ebaauw** [comment]
Yes, 
```
$ sudo npm -g un homebridge
$ sudo npm -g install homebridge@0.4.39 --unsafe-perm
```

**Comment by NorthernMan54** [comment]
@ebaauw @KhaosT 

I think the root of the issue I'm seeing is that MDNS was responding to requests on all network interfaces and bonjour-hap isn't.  After delving into this further I saw this

https://www.codeproject.com/Questions/524739/UDPplusbroadcastplusonplusmultipleplusethernetplus

Which leads me to suspect that this theory is accurate. Or was MDNS just responding to requests based on the network interface it saw a request/query come from.  Think I need more digging into this.

**Comment by riddik14** [comment]
Thanks u


Domenico

Il giorno 09 mag 2018, alle ore 04:56, Northern Man <notifications@github.com<mailto:notifications@github.com>> ha scritto:


@ebaauw<https://github.com/ebaauw> @KhaosT<https://github.com/KhaosT>

I think the root of the issue I'm seeing is that MDNS was responding to requests on all network interfaces and bonjour-hap isn't. After delving into this further I saw this

https://www.codeproject.com/Questions/524739/UDPplusbroadcastplusonplusmultipleplusethernetplus

Which leads me to suspect that this theory is accurate. Or was MDNS just responding to requests based on the network interface it saw a request/query come from. Think I need more digging into this.

**Comment by NorthernMan54** [comment]
That does not sound like this issue, as with this issue you always get no response and not after a while. What you have sounds like homebridge crashing for some reason, check your logs.

**Comment by peros550** [comment]
Hi thanks for your suggestion. Homebridge continues to work, I see the messages flow in real time as homebridge gets information from my accessories. Although my HTTP accessories respond with their value,  Home app shows them as "no response".  I will try to troubleshoot further by removing one by one my plugins-accessories. I wrote on this thread because I suspect there is something wrong with homebridge version as the issue occurred right after I updated to 0.4.42 and with no change on conf.json file.

**Comment by NorthernMan54** [comment]
Just a quick update, I'm continuing to look into this, and have yet to come with a workable solution that would work seamlessly for everyone.  I have tried a couple of different approaches, but each has failed in wider testing between my RPI's and Mac.  Stay tuned.

**Comment by KhaosT** [comment]
🙏

**Comment by niccolospa** [comment]
I’m having quite the same issue on Ubuntu 16.04 with 2 network interfaces active (eth and WLAN), so I downgraded Homebridge to 0.4.38, but I can control my accessories only if I’m connected to the default network interface, whereas if I’m connected to the other toggles buttons without effect

**Comment by NorthernMan54** [comment]
Okay, my current thinking is that this is related to older versions of NodeJS.  I had this issue on a RPI running NodeJS v7.10.1 and as part of the investigation I had upgraded to version v8.11.1.  Since upgrading I can no longer recreate the issue.  Looking at changes in NodeJS, there are significant changes with the code supporting UDP ( MDNS ) and it appears that they fixed the cause of this issue.

So unless anyone else has the same issue with a recent version of NodeJS, I'm going to close this.

**Comment by pponce** [comment]
I can confirm that things are working for me with v8.11.2.

**Comment by simont77** [comment]
I'm experiencing the same issue on macOS 10.13.5 and node 8.11.3. Latest homebridge version (0.4.44) does not show up, and I cannot even see any service with bonjour browser, 0.4.38 is ok and service _hap._tcp is present. I'm pretty convinced that I previously tested a >0.4.38 version, with no issue and node 8.10.xx. Any thought?
