### ISSUE TITLE
Suddenly: Error while installing/updating Homebridge

### ISSUE THREAD

**Issue by dehsgr** [nfarina/homebridge#1851]
Hi,

suddenly installing/upgrading homebridge is giving me the following error/output:

npm install -g --unsafe-perm homebridge
/usr/local/bin/homebridge -> /usr/local/lib/node_modules/homebridge/bin/homebridge

> curve25519-n@1.2.0 install /usr/local/lib/node_modules/homebridge/node_modules/curve25519-n
> node-gyp rebuild

make: Entering directory '/usr/local/lib/node_modules/homebridge/node_modules/curve25519-n/build'
  CXX(target) Release/obj.target/curve/node_curve.o
as: symbol lookup error: /usr/lib/libbfd-2.25-system.so: undefined symbol: bfd_plug)n_arch
curve.target.mk:93: recipe for target 'Release/obj.target/curve/node_curve.o' failed
make: *** [Release/obj.target/curve/node_curve.o] Error 1
make: Leaving directory '/usr/local/lib/node_modules/homebridge/node_modules/curve25519-n/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:225:12)
gyp ERR! System Linux 4.9.35-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/homebridge/node_modules/curve25519-n
gyp ERR! node -v v10.0.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! curve25519-n@1.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the curve25519-n@1.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-05-11T10_57_42_574Z-debug.log

I'm running on rasping jessie und my homebridge was running fine until current update. How can I get it back working? I think the error is related to build essentials and/or one of its dependencies. Am I right? Or do I misinterpret something?

Any directions what I can do would be highly appreciated.

Thank you!

**Comment by ebaauw** [comment]
After updating node (to another major version), uninstall homebridge and re-install it:
```
$ sudo npm -g un homebridge
$ sudo npm -g i homebridge --unsafe-perm
```

**Comment by dehsgr** [comment]
Hi @ebaauw,

thanks for your hints. Updating node and reinstalling results in the same error. Sth. breaks during update in that way that getting back to previous version doesn't work too. :-(

**Comment by ebaauw** [comment]
You need to _uninstall_ homebridge before re-installing it.  Somehow node-gyp rebuild fails on simply updating homebridge (installing homebridge over an existing installation).

**Comment by dehsgr** [comment]
I DID the uninstall. :-(

**Comment by ebaauw** [comment]
Bummer.  I'm afraid I don't have any other hints.

**Comment by dehsgr** [comment]
Nevertheless thanks for your help. Currently I'm restoring my Image from 2018-05-01 to get online again. I gave it a second chance but ran in the same error. So currently upgrading to latest homebridge is not possible to me. :'(

**Comment by TommyCardello** [comment]
Thanks! That worked for me.

I played with gulp yesterday, and today found out that homebridge stopped working.
Reinstalling showed the same error.

But performing **uninstall** THEN **install** fixed it.

Thx

**Comment by dehsgr** [comment]
Nothing helped than reinstalling from scratch. Strange issue, but now I‘m running again with latest homebridge version.

**Comment by tintoyuk** [comment]
Not to necro-post, but in case it helps others: i had the same issue as dehsgr and it turned out i was missing the —unssafe-perm switch. i.e. after updating node i had to run 
```
sudo npm uninstall -g homebridge 
sudo npm install -g —unsafe-perm homebridge
```
