### ISSUE TITLE
Homebridge isn't showing up!

### ISSUE THREAD

**Issue by mikesena** [nfarina/homebridge#1852]
Hi All,

I'm trying to get Homebridge running on my Raspberry Pi W.
I have had it running previously on Rasbian Jessie, but have reset my Pi on Stretch and it doesn't seem to work.
Homebridge itself starts up fine, and shows me the HomeKit code to scan / use.

Hunting around, I suspect the issue is to do with Avahi - I think it isn't publishing?

I've tried correcting nsswitch.conf, avahi's config, disabling ipv6...  I'd really appreciate some help getting this back up and running!

*nsswitch.conf*
```
hosts:          files mdns4_minimal [NOTFOUND=return] dns mdns4 mdns
```

*avahi*
```
[server]
#host-name=foo
#domain-name=local
#browse-domains=0pointer.de, zeroconf.org
use-ipv4=yes
use-ipv6=no
allow-interfaces=eth0,wlan0
#deny-interfaces=eth1
#check-response-ttl=no
#use-iff-running=no
#enable-dbus=yes
#disallow-other-stacks=no
#allow-point-to-point=no
#cache-entries-max=4096
#clients-max=4096
#objects-per-client-max=1024
#entries-per-entry-group-max=32
ratelimit-interval-usec=1000000
ratelimit-burst=1000

[wide-area]
enable-wide-area=yes

[publish]
#disable-publishing=no
#disable-user-service-publishing=no
#add-service-cookie=no
#publish-addresses=yes
publish-hinfo=no
publish-workstation=yes
#publish-domain=yes
#publish-dns-servers=192.168.50.1, 192.168.50.2
#publish-resolv-conf-dns-servers=yes
#publish-aaaa-on-ipv4=yes
#publish-a-on-ipv6=no

[reflector]
#enable-reflector=no
#reflect-ipv=no

[rlimits]
#rlimit-as=
rlimit-core=0
rlimit-data=4194304
rlimit-fsize=0
rlimit-nofile=768
rlimit-stack=4194304
rlimit-nproc=3
```

*homebridge configuration*
```
{
    "bridge": {
        "name": "Homebridge 2.0",
        "username": "CC:22:3D:E3:CE:32",
        "port": 51826,
        "pin": "031-45-156"
    },
    "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",
    "platforms": [
        {
            "platform": "BelkinWeMo",
            "name": "WeMo Platform"
        },
        {
            "platform": "Flic",
            "name": "Flic",
            "controllers": [
                {"host": "localhost", "port": 5551}
            ]
        }
    ],
    "accessories": []
}
```

*Log*
```
May 11 12:33:59 raspberrypi homebridge[425]: [2018-5-11 12:33:59] Loaded plugin: homebridge-flic
May 11 12:33:59 raspberrypi homebridge[425]: [2018-5-11 12:33:59] Registering platform 'homebridge-flic.Flic'
May 11 12:33:59 raspberrypi homebridge[425]: [2018-5-11 12:33:59] ---
May 11 12:34:02 raspberrypi homebridge[425]: [2018-5-11 12:34:02] Loaded plugin: homebridge-platform-wemo
May 11 12:34:02 raspberrypi homebridge[425]: [2018-5-11 12:34:02] Registering platform 'homebridge-platform-wemo.BelkinWeMo'
May 11 12:34:02 raspberrypi homebridge[425]: [2018-5-11 12:34:02] ---
May 11 12:34:02 raspberrypi homebridge[425]: [2018-5-11 12:34:02] Loaded config.json with 0 accessories and 2 platforms.
May 11 12:34:02 raspberrypi homebridge[425]: [2018-5-11 12:34:02] ---
May 11 12:34:02 raspberrypi homebridge[425]: [2018-5-11 12:34:02] Loading 2 platforms...
May 11 12:34:02 raspberrypi homebridge[425]: [2018-5-11 12:34:02] [WeMo Platform] Initializing BelkinWeMo platform...
May 11 12:34:02 raspberrypi homebridge[425]: [2018-5-11 12:34:02] [Flic] Initializing Flic platform...
May 11 12:34:02 raspberrypi homebridge[425]: [2018-5-11 12:34:02] Loading 0 accessories...
May 11 12:34:02 raspberrypi homebridge[425]: Setup Payload:
May 11 12:34:02 raspberrypi homebridge[425]: X-HM://0023ISYX03O26
May 11 12:34:02 raspberrypi homebridge[425]: Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
May 11 12:34:03 raspberrypi homebridge[425]: Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:
May 11 12:34:03 raspberrypi homebridge[425]:
May 11 12:34:03 raspberrypi homebridge[425]:     ┌────────────┐
May 11 12:34:03 raspberrypi homebridge[425]:     │ 031-45-156 │
May 11 12:34:03 raspberrypi homebridge[425]:     └────────────┘
May 11 12:34:03 raspberrypi homebridge[425]:
May 11 12:34:03 raspberrypi homebridge[425]: [2018-5-11 12:34:03] Homebridge is running on port 51826.
May 11 12:34:03 raspberrypi homebridge[425]: [2018-5-11 12:34:03] [Flic] Controller [localhost:5551] - Connected
May 11 12:34:05 raspberrypi homebridge[425]: [2018-5-11 12:34:05] [WeMo Platform] Online: Camille Lamp [94103EF6BF4360FA]
May 11 12:34:05 raspberrypi homebridge[425]: [2018-5-11 12:34:05] [WeMo Platform] Online: Michael Lamp [94103EF6BF43905C]
May 11 12:34:05 raspberrypi homebridge[425]: [2018-5-11 12:34:05] [WeMo Platform] Online: Living Room [1513857244]
May 11 12:34:05 raspberrypi homebridge[425]: [2018-5-11 12:34:05] [WeMo Platform] Offline: Dining Room [1512817675]
May 11 12:34:05 raspberrypi homebridge[425]: [2018-5-11 12:34:05] [WeMo Platform] Online: Dining Room [1513857260]
May 11 12:34:05 raspberrypi homebridge[425]: [2018-5-11 12:34:05] [WeMo Platform] Offline: Living Room [1500776415]
May 11 12:34:08 raspberrypi homebridge[425]: [2018-5-11 12:34:08] [WeMo Platform] Online: Living Room Lamp [94103EF6BF441FE4]
```

**Comment by theo-69** [comment]
try to delete persist and accessories and change username, pin and port and start homebridge again

**Comment by vinnyfiore** [comment]
I'm having the same exact issue. I was previously running Homebridge on a Pi Zero with no issues, but it updated and now I can't readd it. The log shows everything operating fine. I've tried @theo-69's steps, but still get the "Accessory not found" error in the app.

**Comment by mikesena** [comment]
@theo-69, I have tried that unfortunately.
I've also tried going back to Raspbian Jessie, and it doesn't work.

The commonality between them could still be package versions - in both cases I update Avahi, but I can't imagine that's the problem...

**Comment by AppleTechy** [comment]
I would also suggest using "Discover - DNS- SD Browser"  available on the IOS App store. Under the local domain something called `_hap.tcp_` should show up along with the name of your Homebridge Server's name.

**Comment by lemonkey** [comment]
My case was even stranger.  On this Raspberry Pi 3B+ running Raspbian Stretch, instead of the LAN identifying as eth0, it shows up as `enxb827eb3472a4`. Only after editing /etc/avahi/avahi-daemon.conf to explicitly include `enxb827eb3472a4,wlan0` did the homebridge instance show up under `avahi-browse -a` both locally and from my other Pis on the network.

**Comment by lemonkey** [comment]
Obviously when the CAT5 is connect it won't work since you need to be on the same network as the HomeKit Hub.

**Comment by mikesena** [comment]
Weird! Thanks for adding the tip to this ticket.

**Comment by lemonkey** [comment]
FYI, on the Raspberry Pi 3B+, like before, the ethernet adapter isn't a true ethernet device but it is implemented via USB (USB gigE + 3 x USB3), so you won't get GigE speeds.

To signal this interface up or down you just need to do `ifconfig <device name> up/down`.

Make sure to **not** include this device name in the avahi-daemon.conf "allow-interfaces" property.

**Comment by lemonkey** [comment]
Is there a way to specify which network device is used by homebridge? I currently get it to bind to wlan0 as long as my USB ethernet device is up.

**Comment by lemonkey** [comment]
I guess what I really want is a way to specify an IP address in addition to port in the config.json.

**Comment by lemonkey** [comment]
What's working for now in my case is to bring down the ethernet interface before starting up homebridge. Then once homebridge is broadcasting on wlan0, bringing up the ethernet interface is still ok and doesn't interfere.

**Comment by lemonkey** [comment]
My fault. I mistakenly thought avahi-daemon -r would also re-read avahi-daemon.conf, which it does not (see man page).

After force killing the daemon and restarting it with my conf changes which deny the ethernet interface, all is good when both wlan0 and the ethernet interfaces are up.

**Comment by RaspJ** [comment]
I changed the config file as well trying to force wlan connection. How do I force kill avahi-daemon? I tried sudo service avahi-daemon stop (then start again) and even a reboot but homebridge is still not showing up in Home on my iPhone. Can I see if homebridge is running on lan or wifi somehow?

Strange too that wifi isn't working without the ethernet cable connected.
