### ISSUE TITLE
Debugging Homebridge in VSCode

### ISSUE THREAD

**Issue by gamma** [nfarina/homebridge#1853]
hi, this is more of a question than a bug. I've seen a previous one about the dev env. VS Code seems reasonable but I'm stuck at the debug mode.

I can start and run the debugger and it will go through the whole thing until it is set up. But then the debug process stops. It might have something to do with the way how HAP runs the internal server ... or something else ...

I tried the VSCode debugger, `node --inspect` and so on.

How do you usually debug home bridge and its plugins? Is this even possible?

**Comment by jespertheend** [comment]
For anyone who is still looking for this. I managed to inspect homebridge by finding the binary location of homebridge, in my case this was `/opt/node/lib/node_modules/homebridge/bin`. Then running `node --inspect homebridge` with any necessary flags included, in my case `-D -I -U /var/lib/homebridge`. I usually have homebridge running in a service so make sure to stop that service first.
