### ISSUE TITLE
Error Install Harmony Plugin

### ISSUE THREAD

**Issue by gold2605** [nfarina/homebridge#1854]
Hello, I get the following error when installing the plugin. My Homebridge runs under the user homebridge and in unsafe mode. However, several installed plugins work correctly (Tado, Netatmo, homematic, config-ui-x, alexa, unifi). Why does not that work with harmony?

Error:

USER: homebridge
DIR: /usr/local/lib/node_modules
CMD: sudo -E -n npm --no-update-notifier install --unsafe-perm homebridge-marteksharmonyhub@latest

npm WARN deprecated node-xmpp-stanza@1.1.0: use @xmpp/xml package <https://www.npmjs.com/package/@xmpp/xml>
npm ERR! code 1
npm ERR! Command failed: /usr/bin/git clone --depth=1 -q -b cdata-for-ltx-parser https://github.com/swissmanu/ltx.git /home/homebridge/.npm/_cacache/tmp/git-clone-1016036f
npm ERR! /home/homebridge/.npm/_cacache/tmp/git-clone-1016036f/.git: Keine Berechtigung
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/homebridge/.npm/_logs/2018-05-12T11_32_58_586Z-debug.log

Command failed. Please review log for details

Log-Datei:

pi@raspberrypi:~ $ cat /home/homebridge/.npm/_logs/2018-05-12T11_32_58_586Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   '--no-update-notifier',
1 verbose cli   'install',
1 verbose cli   '--unsafe-perm',
1 verbose cli   'homebridge-marteksharmonyhub@latest' ]
2 info using npm@6.0.1
3 info using node@v8.8.1
4 verbose npm-session 1289a8a0da5eb871
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 304 https://registry.npmjs.org/homebridge-marteksharmonyhub 478ms (from cache)
8 silly pacote tag manifest for homebridge-marteksharmonyhub@latest fetched in 583ms
9 timing stage:loadCurrentTree Completed in 1463ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 1ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 8ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule homebridge-marteksharmonyhub@0.2.1 checking installable status
17 http fetch GET 304 https://registry.npmjs.org/bluebird 234ms (from cache)
18 silly pacote range manifest for bluebird@^3.3.4 fetched in 269ms
19 silly resolveWithNewModule bluebird@3.5.1 checking installable status
20 http fetch GET 304 https://registry.npmjs.org/harmonyhubjs-client 434ms (from cache)
21 http fetch GET 304 https://registry.npmjs.org/inherits 429ms (from cache)
22 http fetch GET 304 https://registry.npmjs.org/debug 441ms (from cache)
23 http fetch GET 304 https://registry.npmjs.org/harmonyhubjs-discover 448ms (from cache)
24 http fetch GET 304 https://registry.npmjs.org/queue 445ms (from cache)
25 http fetch GET 304 https://registry.npmjs.org/lodash 445ms (from cache)
26 silly pacote range manifest for harmonyhubjs-client@^1.1.6 fetched in 481ms
27 silly resolveWithNewModule harmonyhubjs-client@1.1.10 checking installable status
28 silly pacote range manifest for inherits@^2.0.1 fetched in 478ms
29 silly resolveWithNewModule inherits@2.0.3 checking installable status
30 silly pacote range manifest for debug@^2.2.0 fetched in 494ms
31 silly resolveWithNewModule debug@2.6.9 checking installable status
32 silly pacote range manifest for harmonyhubjs-discover@^1.0.2 fetched in 493ms
33 silly resolveWithNewModule harmonyhubjs-discover@1.1.1 checking installable status
34 silly pacote range manifest for queue@^3.1.0 fetched in 491ms
35 silly resolveWithNewModule queue@3.1.0 checking installable status
36 silly pacote range manifest for lodash@^4.6 fetched in 491ms
37 silly resolveWithNewModule lodash@4.17.10 checking installable status
38 http fetch GET 304 https://registry.npmjs.org/ms 63ms (from cache)
39 silly pacote version manifest for ms@2.0.0 fetched in 69ms
40 silly resolveWithNewModule ms@2.0.0 checking installable status
41 http fetch GET 304 https://registry.npmjs.org/node-xmpp-client 224ms (from cache)
42 http fetch GET 304 https://registry.npmjs.org/q 230ms (from cache)
43 silly pacote version manifest for node-xmpp-client@3.0.0 fetched in 250ms
44 silly resolveWithNewModule node-xmpp-client@3.0.0 checking installable status
45 silly pacote range manifest for q@^1.1.2 fetched in 249ms
46 silly resolveWithNewModule q@1.5.1 checking installable status
47 http fetch GET 304 https://registry.npmjs.org/node-xmpp-stanza 256ms (from cache)
48 http fetch GET 304 https://registry.npmjs.org/request 248ms (from cache)
49 silly pacote version manifest for node-xmpp-stanza@1.1.0 fetched in 277ms
50 warn deprecated node-xmpp-stanza@1.1.0: use @xmpp/xml package <https://www.npmjs.com/package/@xmpp/xml>
51 silly resolveWithNewModule node-xmpp-stanza@1.1.0 checking installable status
52 silly pacote range manifest for request@^2.48.0 fetched in 278ms
53 silly resolveWithNewModule request@2.85.0 checking installable status
54 silly fetchPackageMetaData error for ltx@git+https://github.com/swissmanu/ltx.git#cdata-for-ltx-parser Command failed: /usr/bin/git clone --depth=1 -q -b cdata-for-ltx-parser https://github.com/swissmanu/ltx.git /home/homebridge/.npm/_cacache/tmp/git-clone-1016036f
54 silly fetchPackageMetaData /home/homebridge/.npm/_cacache/tmp/git-clone-1016036f/.git: Keine Berechtigung
55 timing stage:rollbackFailedOptional Completed in 2ms
56 timing stage:runTopLevelLifecycles Completed in 3397ms
57 verbose stack Error: Command failed: /usr/bin/git clone --depth=1 -q -b cdata-for-ltx-parser https://github.com/swissmanu/ltx.git /home/homebridge/.npm/_cacache/tmp/git-clone-1016036f
57 verbose stack /home/homebridge/.npm/_cacache/tmp/git-clone-1016036f/.git: Keine Berechtigung
57 verbose stack
57 verbose stack     at ChildProcess.exithandler (child_process.js:272:12)
57 verbose stack     at emitTwo (events.js:125:13)
57 verbose stack     at ChildProcess.emit (events.js:213:7)
57 verbose stack     at maybeClose (internal/child_process.js:927:16)
57 verbose stack     at Socket.stream.socket.on (internal/child_process.js:348:11)
57 verbose stack     at emitOne (events.js:115:13)
57 verbose stack     at Socket.emit (events.js:210:7)
57 verbose stack     at Pipe._handle.close [as _onclose] (net.js:557:12)
58 verbose cwd /usr/local/lib/node_modules
59 verbose Linux 4.14.34-v7+
60 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "--no-update-notifier" "install" "--unsafe-perm" "homebridge-marteksharmonyhub@latest"
61 verbose node v8.8.1
62 verbose npm  v6.0.1
63 error code 1
64 error Command failed: /usr/bin/git clone --depth=1 -q -b cdata-for-ltx-parser https://github.com/swissmanu/ltx.git /home/homebridge/.npm/_cacache/tmp/git-clone-1016036f
64 error /home/homebridge/.npm/_cacache/tmp/git-clone-1016036f/.git: Keine Berechtigung
65 verbose exit [ 1, true ]

When trying to install via console, I get the following message:

pi@raspberrypi:~ $ sudo npm i homebridge-marteksharmonyhub
npm WARN deprecated node-xmpp-stanza@1.1.0: use @xmpp/xml package <https://www.npmjs.com/package/@xmpp/xml>
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git clone --depth=1 -q -b cdata-for-ltx-parser https://github.com/swissmanu/ltx.git /root/.npm/_cacache/tmp/git-clone-aced0a2a
npm ERR! fatal: Konnte führende Verzeichnisse von '/root/.npm/_cacache/tmp/git-clone-aced0a2a' nicht erstellen.: Keine Berechtigung
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-05-12T11_38_57_581Z-debug.log
pi@raspberrypi:~ $ 

Many thanks for the help....

**Comment by theo-69** [comment]
post this Problem @ [https://github.com/kraigm/homebridge-harmonyhub](url)
