### ISSUE TITLE
Start second instance with only one specific Plugin

### ISSUE THREAD

**Issue by theo-69** [nfarina/homebridge#1855]
Hi iam trying to start a second instance with only one specific plugin. However what ever i try its loading all plugins and that giving me ERROR.

tried `homebridge -U ~/.homebridge-aqara -P /home/pi/.homebridge-aqara/homebridge-mi-aqara`

but still loading all if i only use `homebridge -U ~/.homebridge-aqara` i am getting
`Error: bind EADDRINUSE 0.0.0.0:1982
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at _handle.lookup (dgram.js:215:18)
    at _combinedTickCallback (internal/process/next_tick.js:83:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3
`

**Comment by ebaauw** [comment]
homebridge always loads plugins from the default directory.  The `-P` flags specifies an _additional_ plugin or plugin directory.

The error means some-one already uses port 1982 - I suspect it's your other homebridge instance You need to change the `port` in `~/.homebridge-aqara/config.json`.  Don't forget also to change the `username` (mac address), as this is used in the Bonjour announcement to you iOS devices.

**Comment by theo-69** [comment]
@ebaauw thanks, did all that, seem to be a problem with one of the plugins. I was hoping to just load 1 plugin and not all. If i move all plugins can ich just call the folder or do i have to call a plugin path?

**Comment by Nastras** [comment]
#1864
