### ISSUE TITLE
Homebridge Not Starting as Expected

### ISSUE THREAD

**Issue by smerdonw** [nfarina/homebridge#1856]
I'm trying to setup homebridge on my MacBook Pro and get it working then setup on my Raspberry Pi. I'm following the instructions here (https://github.com/nfarina/homebridge) for Smartthings following these instructions (https://github.com/pdlove/homebridge-smartthings). I'm seeing the following when starting homebridge...
```
Loaded plugin: homebridge-smartthings
Registering platform 'homebridge-smartthings.SmartThings'
 ---
Loaded config.json with 0 accessories and 0 platforms.
```
followed by the code image and code and then
```
Homebridge is running on port 51826.
```
### Expected Behavior
As per the instructions, I would expect to see at least 1 platform as I put into the config-json. Also, as described I'm not seeing...
```
Loading 1 platforms...
Loading 0 accessories...
```
Also, I'm not seeing the following as per the smartthings setup...
```
[SmartThings] Direct Connect Is Listening On 192.168.0.49:8000
[SmartThings] SmartThings Hub Communication Established
```
### Versions
- **Homebridge**: 0.4.42
- **Node**: v8.11.1
- **OS**: macOD High Sierra 10.13.4

### Configuration
Note that I am inserting the app_id and access_token as per the instructions...
```config.json
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
	},

	"description": "Smartthings running on MacBook Pro.",

	"platform": "SmartThings",
	 "name": "SmartThings",
		 "app_url": "https://graph.api.smartthings.com:443/api/smartapps/installations/",
		 "app_id": "THIS-SHOULD-BE-YOUR-APPID",
		 "access_token": "THIS-SHOULD-BE-YOUR-TOKEN",
		 "polling_seconds": 3600,
		 "update_method": "direct",
		 "direct_ip": "192.168.0.45",
		 "direct_port": 8000,
		 "api_seconds": 30,
		 "excluded_capabilities": {
				 "SMARTTHINGS-DEVICE-ID-1" : [
						 "Switch",
						 "Temperature Measurement"
				 ]}
}
```

**Comment by theo-69** [comment]
Try this config:

`{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
	},

	"description": "Smartthings running on MacBook Pro.",
"accessories": [
        {
            "accessory": "WeMo",
            "name": "Coffee Maker"
        }
    ],

    "platforms": [
        {
           "platform": "SmartThings",
	 "name": "SmartThings",
		 "app_url": "https://graph.api.smartthings.com:443/api/smartapps/installations/",
		 "app_id": "THIS-SHOULD-BE-YOUR-APPID",
		 "access_token": "THIS-SHOULD-BE-YOUR-TOKEN",
		 "polling_seconds": 3600,
		 "update_method": "direct",
		 "direct_ip": "192.168.0.45",
		 "direct_port": 8000,
		 "api_seconds": 30,
		 "excluded_capabilities": {
				 "SMARTTHINGS-DEVICE-ID-1" : [
						 "Switch",
						 "Temperature Measurement"
				 ]}
    ]
}

**Comment by smerdonw** [comment]
Thanks, that gets me to part of what is expected from the Smartthings integration but not all the way. I think the rest is for the other forum.
