### ISSUE TITLE
Keeping Homebridge Running

### ISSUE THREAD

**Issue by HawkEye9034** [nfarina/homebridge#1857]
Hi There. I Have homebridge setup on my raspberry pi and ssh into it via a mac to execute it . However, If i quit terminal homebridge stops. If i leave terminal running then after a while it returns ssh lost: broken pipe and it stope homebridge. i have tried so many tutorials and none work . Please help!

**Comment by theo-69** [comment]
you have to autostart homebridge

`Start at boot
Install PM2 module:

sudo npm -g install pm2
Now when PM2 is installed, it should work starting Homebridge with the following command:

pm2 start homebridge
Check if Homebridge is running by:

pm2 list
Or for a more detailed description of the process:

pm2 show homebridge
In the detailed description the logs are shown, where you can check if everything went as intended. Or use the log function of PM2

pm2 logs homebridge
Of course you want Homebridge to autostart on boot. PM2 has a command making this easy:

pm2 startup
And this would give you a command to run, depending on your system setup. This is an example from a standard PI Jessie dist.

You have to run this command as root. Execute the following command:
sudo env PATH=$PATH:/usr/bin /usr/lib/node_modules/pm2/bin/pm2 startup systemd -u pi --hp /home/pi
It is important that you save the current PM2 process list, it is done by the following command:

pm2 save
After this you should be able to reboot, and hopefully you have working Homebridge-installation starting at boot.

sudo reboot`

**Comment by HawkEye9034** [comment]
Im useing ffmpeg, sonos zp, and sony bravia

Heres the config:
{
  "bridge": {
    "name": "HomeBridge",
    "username": "CC:22:3D:E3:CE:30",
    "port": 51826,
    "pin": "031-45-154"
  },
  "platforms": [
    {
      "platform": "Camera-ffmpeg",
      "name": "Camera",
      "cameras": [
        {
          "name": "OfficeCam",
          "videoConfig": {
            "source": "-f v4l2 -r 30 -s 1280x720 -i /dev/video0",
            "maxStreams": 2,
            "maxWidth": 1280,
            "maxHeight": 720,
            "maxFPS": 30,
            "vcodec": "h264_omx"
          }
        }
      ]
    },
    {
      "platform": "ZP",
      "service": "speaker",
      "brightness": true,
      "speakers": false
    },
    {
      "platform": "SonyBravia",
      "name": "Living Room TV",
      "ipadress": "xxxxxxxxx",
      "psk": "xxxxxxx"
    }
  ]
}

**Comment by aswathraja** [comment]
Did u try running homebridge as systemd daemon? 
https://gist.github.com/johannrichard/0ad0de1feb6adb9eb61a/

You can run the service as root too if any specific plugin requires it

**Comment by HawkEye9034** [comment]
tried that. nothing happens

**Comment by HawkEye9034** [comment]
@aswathraja ^^^

**Comment by aswathraja** [comment]
if you are running as the systemd as in the gist, use the  command :
`systemctl status homebridge`
or extensive logs by
`journalctl -a -u homebridge`

**Comment by HawkEye9034** [comment]
systemctl status homebridge returns this
● homebridge.service - Node.js HomeKit Server
   Loaded: loaded (/etc/systemd/system/homebridge.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Wed 2018-05-16 16:57:01 UTC; 8s ago
  Process: 3843 ExecStart=/usr/bin/homebridge $HOMEBRIDGE_OPTS (code=exited, status=203/EXEC)
 Main PID: 3843 (code=exited, status=203/EXEC)

May 16 16:57:01 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
lines 1-7/7 (END)

journalctl -a -u homebridge returns this: 
-- Logs begin at Wed 2018-05-16 08:49:59 UTC, end at Wed 2018-05-16 16:57:53 UTC. --
May 16 08:49:59 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
May 16 08:49:59 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
May 16 08:50:09 raspberrypi systemd[1]: homebridge.service: Service hold-off time over, scheduling restart
May 16 08:50:09 raspberrypi systemd[1]: Stopped Node.js HomeKit Server.
May 16 08:50:09 raspberrypi systemd[1]: Started Node.js HomeKit Server.
May 16 08:50:09 raspberrypi systemd[2759]: homebridge.service: Failed at step EXEC spawning /usr/bin/homeb
May 16 08:50:09 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=203/E
May 16 08:50:09 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
May 16 08:50:09 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
May 16 08:50:19 raspberrypi systemd[1]: homebridge.service: Service hold-off time over, scheduling restart
May 16 08:50:19 raspberrypi systemd[1]: Stopped Node.js HomeKit Server.
May 16 08:50:19 raspberrypi systemd[1]: Started Node.js HomeKit Server.
May 16 08:50:19 raspberrypi systemd[2783]: homebridge.service: Failed at step EXEC spawning /usr/bin/homeb
May 16 08:50:19 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=203/E
May 16 08:50:19 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
May 16 08:50:19 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
May 16 08:50:29 raspberrypi systemd[1]: homebridge.service: Service hold-off time over, scheduling restart
May 16 08:50:29 raspberrypi systemd[1]: Stopped Node.js HomeKit Server.
May 16 08:50:29 raspberrypi systemd[1]: Started Node.js HomeKit Server.
May 16 08:50:29 raspberrypi systemd[2812]: homebridge.service: Failed at step EXEC spawning /usr/bin/homeb
May 16 08:50:29 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=203/E
May 16 08:50:29 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
May 16 08:50:29 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
lines 2-24
May 16 08:49:59 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
May 16 08:49:59 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
May 16 08:50:09 raspberrypi systemd[1]: homebridge.service: Service hold-off time over, scheduling restart.
May 16 08:50:09 raspberrypi systemd[1]: Stopped Node.js HomeKit Server.
May 16 08:50:09 raspberrypi systemd[1]: Started Node.js HomeKit Server.
May 16 08:50:09 raspberrypi systemd[2759]: homebridge.service: Failed at step EXEC spawning /usr/bin/homebrid
May 16 08:50:09 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=203/EXEC
May 16 08:50:09 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
May 16 08:50:09 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
May 16 08:50:19 raspberrypi systemd[1]: homebridge.service: Service hold-off time over, scheduling restart.
May 16 08:50:19 raspberrypi systemd[1]: Stopped Node.js HomeKit Server.
May 16 08:50:19 raspberrypi systemd[1]: Started Node.js HomeKit Server.
May 16 08:50:19 raspberrypi systemd[2783]: homebridge.service: Failed at step EXEC spawning /usr/bin/homebrid
May 16 08:50:19 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=203/EXEC
May 16 08:50:19 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
May 16 08:50:19 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
May 16 08:50:29 raspberrypi systemd[1]: homebridge.service: Service hold-off time over, scheduling restart.
May 16 08:50:29 raspberrypi systemd[1]: Stopped Node.js HomeKit Server.
May 16 08:50:29 raspberrypi systemd[1]: Started Node.js HomeKit Server.
May 16 08:50:29 raspberrypi systemd[2812]: homebridge.service: Failed at step EXEC spawning /usr/bin/homebrid
May 16 08:50:29 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=203/EXEC
May 16 08:50:29 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
May 16 08:50:29 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
lines 2-24
May 16 08:49:59 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
May 16 08:49:59 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
May 16 08:50:09 raspberrypi systemd[1]: homebridge.service: Service hold-off time over, scheduling restart.
May 16 08:50:09 raspberrypi systemd[1]: Stopped Node.js HomeKit Server.
May 16 08:50:09 raspberrypi systemd[1]: Started Node.js HomeKit Server.
May 16 08:50:09 raspberrypi systemd[2759]: homebridge.service: Failed at step EXEC spawning /usr/bin/homebridge: No
May 16 08:50:09 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=203/EXEC
May 16 08:50:09 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
May 16 08:50:09 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
May 16 08:50:19 raspberrypi systemd[1]: homebridge.service: Service hold-off time over, scheduling restart.
May 16 08:50:19 raspberrypi systemd[1]: Stopped Node.js HomeKit Server.
May 16 08:50:19 raspberrypi systemd[1]: Started Node.js HomeKit Server.
May 16 08:50:19 raspberrypi systemd[2783]: homebridge.service: Failed at step EXEC spawning /usr/bin/homebridge: No
May 16 08:50:19 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=203/EXEC
May 16 08:50:19 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
May 16 08:50:19 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
May 16 08:50:29 raspberrypi systemd[1]: homebridge.service: Service hold-off time over, scheduling restart.
May 16 08:50:29 raspberrypi systemd[1]: Stopped Node.js HomeKit Server.
May 16 08:50:29 raspberrypi systemd[1]: Started Node.js HomeKit Server.
May 16 08:50:29 raspberrypi systemd[2812]: homebridge.service: Failed at step EXEC spawning /usr/bin/homebridge: No
May 16 08:50:29 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=203/EXEC
May 16 08:50:29 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
May 16 08:50:29 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
lines 2-24
May 16 08:49:59 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
May 16 08:49:59 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
May 16 08:50:09 raspberrypi systemd[1]: homebridge.service: Service hold-off time over, scheduling restart.
May 16 08:50:09 raspberrypi systemd[1]: Stopped Node.js HomeKit Server.
May 16 08:50:09 raspberrypi systemd[1]: Started Node.js HomeKit Server.
May 16 08:50:09 raspberrypi systemd[2759]: homebridge.service: Failed at step EXEC spawning /usr/bin/homebridge: No such
May 16 08:50:09 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=203/EXEC
May 16 08:50:09 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
May 16 08:50:09 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
May 16 08:50:19 raspberrypi systemd[1]: homebridge.service: Service hold-off time over, scheduling restart.
May 16 08:50:19 raspberrypi systemd[1]: Stopped Node.js HomeKit Server.
May 16 08:50:19 raspberrypi systemd[1]: Started Node.js HomeKit Server.
May 16 08:50:19 raspberrypi systemd[2783]: homebridge.service: Failed at step EXEC spawning /usr/bin/homebridge: No such
May 16 08:50:19 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=203/EXEC
May 16 08:50:19 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
May 16 08:50:19 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
May 16 08:50:29 raspberrypi systemd[1]: homebridge.service: Service hold-off time over, scheduling restart.
May 16 08:50:29 raspberrypi systemd[1]: Stopped Node.js HomeKit Server.
May 16 08:50:29 raspberrypi systemd[1]: Started Node.js HomeKit Server.
May 16 08:50:29 raspberrypi systemd[2812]: homebridge.service: Failed at step EXEC spawning /usr/bin/homebridge: No such
May 16 08:50:29 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=203/EXEC
May 16 08:50:29 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
May 16 08:50:29 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
lines 2-24
May 16 08:49:59 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
May 16 08:49:59 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
May 16 08:50:09 raspberrypi systemd[1]: homebridge.service: Service hold-off time over, scheduling restart.
May 16 08:50:09 raspberrypi systemd[1]: Stopped Node.js HomeKit Server.
May 16 08:50:09 raspberrypi systemd[1]: Started Node.js HomeKit Server.
May 16 08:50:09 raspberrypi systemd[2759]: homebridge.service: Failed at step EXEC spawning /usr/bin/homebridge: No such file o
May 16 08:50:09 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=203/EXEC
May 16 08:50:09 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
May 16 08:50:09 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
May 16 08:50:19 raspberrypi systemd[1]: homebridge.service: Service hold-off time over, scheduling restart.
May 16 08:50:19 raspberrypi systemd[1]: Stopped Node.js HomeKit Server.
May 16 08:50:19 raspberrypi systemd[1]: Started Node.js HomeKit Server.
May 16 08:50:19 raspberrypi systemd[2783]: homebridge.service: Failed at step EXEC spawning /usr/bin/homebridge: No such file o
May 16 08:50:19 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=203/EXEC
May 16 08:50:19 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
May 16 08:50:19 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
May 16 08:50:29 raspberrypi systemd[1]: homebridge.service: Service hold-off time over, scheduling restart.
May 16 08:50:29 raspberrypi systemd[1]: Stopped Node.js HomeKit Server.
May 16 08:50:29 raspberrypi systemd[1]: Started Node.js HomeKit Server.
May 16 08:50:29 raspberrypi systemd[2812]: homebridge.service: Failed at step EXEC spawning /usr/bin/homebridge: No such file o
May 16 08:50:29 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=203/EXEC
May 16 08:50:29 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
May 16 08:50:29 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
lines 2-24
May 16 08:49:59 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
May 16 08:49:59 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
May 16 08:50:09 raspberrypi systemd[1]: homebridge.service: Service hold-off time over, scheduling restart.
May 16 08:50:09 raspberrypi systemd[1]: Stopped Node.js HomeKit Server.
May 16 08:50:09 raspberrypi systemd[1]: Started Node.js HomeKit Server.
May 16 08:50:09 raspberrypi systemd[2759]: homebridge.service: Failed at step EXEC spawning /usr/bin/homebridge: No such file or d
May 16 08:50:09 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=203/EXEC
May 16 08:50:09 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
May 16 08:50:09 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
May 16 08:50:19 raspberrypi systemd[1]: homebridge.service: Service hold-off time over, scheduling restart.
May 16 08:50:19 raspberrypi systemd[1]: Stopped Node.js HomeKit Server.
May 16 08:50:19 raspberrypi systemd[1]: Started Node.js HomeKit Server.
May 16 08:50:19 raspberrypi systemd[2783]: homebridge.service: Failed at step EXEC spawning /usr/bin/homebridge: No such file or d
May 16 08:50:19 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=203/EXEC
May 16 08:50:19 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
May 16 08:50:19 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
May 16 08:50:29 raspberrypi systemd[1]: homebridge.service: Service hold-off time over, scheduling restart.
May 16 08:50:29 raspberrypi systemd[1]: Stopped Node.js HomeKit Server.
May 16 08:50:29 raspberrypi systemd[1]: Started Node.js HomeKit Server.
May 16 08:50:29 raspberrypi systemd[2812]: homebridge.service: Failed at step EXEC spawning /usr/bin/homebridge: No such file or d
May 16 08:50:29 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=203/EXEC
May 16 08:50:29 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
May 16 08:50:29 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
lines 2-24
May 16 08:49:59 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
May 16 08:49:59 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
May 16 08:50:09 raspberrypi systemd[1]: homebridge.service: Service hold-off time over, scheduling restart.
May 16 08:50:09 raspberrypi systemd[1]: Stopped Node.js HomeKit Server.
May 16 08:50:09 raspberrypi systemd[1]: Started Node.js HomeKit Server.
May 16 08:50:09 raspberrypi systemd[2759]: homebridge.service: Failed at step EXEC spawning /usr/bin/homebridge: No such file or di
May 16 08:50:09 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=203/EXEC
May 16 08:50:09 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
May 16 08:50:09 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
May 16 08:50:19 raspberrypi systemd[1]: homebridge.service: Service hold-off time over, scheduling restart.
May 16 08:50:19 raspberrypi systemd[1]: Stopped Node.js HomeKit Server.
May 16 08:50:19 raspberrypi systemd[1]: Started Node.js HomeKit Server.
May 16 08:50:19 raspberrypi systemd[2783]: homebridge.service: Failed at step EXEC spawning /usr/bin/homebridge: No such file or di
May 16 08:50:19 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=203/EXEC
May 16 08:50:19 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
May 16 08:50:19 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
May 16 08:50:29 raspberrypi systemd[1]: homebridge.service: Service hold-off time over, scheduling restart.
May 16 08:50:29 raspberrypi systemd[1]: Stopped Node.js HomeKit Server.
May 16 08:50:29 raspberrypi systemd[1]: Started Node.js HomeKit Server.
May 16 08:50:29 raspberrypi systemd[2812]: homebridge.service: Failed at step EXEC spawning /usr/bin/homebridge: No such file or di
May 16 08:50:29 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=203/EXEC
May 16 08:50:29 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
May 16 08:50:29 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
lines 2-24
May 16 08:49:59 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
May 16 08:49:59 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
May 16 08:50:09 raspberrypi systemd[1]: homebridge.service: Service hold-off time over, scheduling restart.
May 16 08:50:09 raspberrypi systemd[1]: Stopped Node.js HomeKit Server.
May 16 08:50:09 raspberrypi systemd[1]: Started Node.js HomeKit Server.
May 16 08:50:09 raspberrypi systemd[2759]: homebridge.service: Failed at step EXEC spawning /usr/bin/homebridge: No such file or dire
May 16 08:50:09 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=203/EXEC
May 16 08:50:09 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
May 16 08:50:09 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
May 16 08:50:19 raspberrypi systemd[1]: homebridge.service: Service hold-off time over, scheduling restart.
May 16 08:50:19 raspberrypi systemd[1]: Stopped Node.js HomeKit Server.
May 16 08:50:19 raspberrypi systemd[1]: Started Node.js HomeKit Server.
May 16 08:50:19 raspberrypi systemd[2783]: homebridge.service: Failed at step EXEC spawning /usr/bin/homebridge: No such file or dire
May 16 08:50:19 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=203/EXEC
May 16 08:50:19 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
May 16 08:50:19 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
May 16 08:50:29 raspberrypi systemd[1]: homebridge.service: Service hold-off time over, scheduling restart.
May 16 08:50:29 raspberrypi systemd[1]: Stopped Node.js HomeKit Server.
May 16 08:50:29 raspberrypi systemd[1]: Started Node.js HomeKit Server.
May 16 08:50:29 raspberrypi systemd[2812]: homebridge.service: Failed at step EXEC spawning /usr/bin/homebridge: No such file or dire
May 16 08:50:29 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=203/EXEC
May 16 08:50:29 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
May 16 08:50:29 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
lines 2-24
May 16 08:49:59 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
May 16 08:49:59 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
May 16 08:50:09 raspberrypi systemd[1]: homebridge.service: Service hold-off time over, scheduling restart.
May 16 08:50:09 raspberrypi systemd[1]: Stopped Node.js HomeKit Server.
May 16 08:50:09 raspberrypi systemd[1]: Started Node.js HomeKit Server.
May 16 08:50:09 raspberrypi systemd[2759]: homebridge.service: Failed at step EXEC spawning /usr/bin/homebridge: No such file or direc
May 16 08:50:09 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=203/EXEC
May 16 08:50:09 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
May 16 08:50:09 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
May 16 08:50:19 raspberrypi systemd[1]: homebridge.service: Service hold-off time over, scheduling restart.
May 16 08:50:19 raspberrypi systemd[1]: Stopped Node.js HomeKit Server.
May 16 08:50:19 raspberrypi systemd[1]: Started Node.js HomeKit Server.
May 16 08:50:19 raspberrypi systemd[2783]: homebridge.service: Failed at step EXEC spawning /usr/bin/homebridge: No such file or direc
May 16 08:50:19 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=203/EXEC
May 16 08:50:19 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
May 16 08:50:19 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
May 16 08:50:29 raspberrypi systemd[1]: homebridge.service: Service hold-off time over, scheduling restart.
May 16 08:50:29 raspberrypi systemd[1]: Stopped Node.js HomeKit Server.
May 16 08:50:29 raspberrypi systemd[1]: Started Node.js HomeKit Server.
May 16 08:50:29 raspberrypi systemd[2812]: homebridge.service: Failed at step EXEC spawning /usr/bin/homebridge: No such file or direc
May 16 08:50:29 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=203/EXEC
May 16 08:50:29 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
May 16 08:50:29 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
lines 2-24
May 16 08:49:59 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
May 16 08:49:59 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
May 16 08:50:09 raspberrypi systemd[1]: homebridge.service: Service hold-off time over, scheduling restart.
May 16 08:50:09 raspberrypi systemd[1]: Stopped Node.js HomeKit Server.
May 16 08:50:09 raspberrypi systemd[1]: Started Node.js HomeKit Server.
May 16 08:50:09 raspberrypi systemd[2759]: homebridge.service: Failed at step EXEC spawning /usr/bin/homebridge: No such file or directo
May 16 08:50:09 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=203/EXEC
May 16 08:50:09 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
May 16 08:50:09 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
May 16 08:50:19 raspberrypi systemd[1]: homebridge.service: Service hold-off time over, scheduling restart.
May 16 08:50:19 raspberrypi systemd[1]: Stopped Node.js HomeKit Server.
May 16 08:50:19 raspberrypi systemd[1]: Started Node.js HomeKit Server.
May 16 08:50:19 raspberrypi systemd[2783]: homebridge.service: Failed at step EXEC spawning /usr/bin/homebridge: No such file or directo
May 16 08:50:19 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=203/EXEC
May 16 08:50:19 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
May 16 08:50:19 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
May 16 08:50:29 raspberrypi systemd[1]: homebridge.service: Service hold-off time over, scheduling restart.
May 16 08:50:29 raspberrypi systemd[1]: Stopped Node.js HomeKit Server.
May 16 08:50:29 raspberrypi systemd[1]: Started Node.js HomeKit Server.
May 16 08:50:29 raspberrypi systemd[2812]: homebridge.service: Failed at step EXEC spawning /usr/bin/homebridge: No such file or directo
May 16 08:50:29 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=203/EXEC
May 16 08:50:29 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
May 16 08:50:29 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
lines 2-24
May 16 08:49:59 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
May 16 08:49:59 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
May 16 08:50:09 raspberrypi systemd[1]: homebridge.service: Service hold-off time over, scheduling restart.
May 16 08:50:09 raspberrypi systemd[1]: Stopped Node.js HomeKit Server.
May 16 08:50:09 raspberrypi systemd[1]: Started Node.js HomeKit Server.
May 16 08:50:09 raspberrypi systemd[2759]: homebridge.service: Failed at step EXEC spawning /usr/bin/homebridge: No such file or directory
May 16 08:50:09 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=203/EXEC
May 16 08:50:09 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
May 16 08:50:09 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
May 16 08:50:19 raspberrypi systemd[1]: homebridge.service: Service hold-off time over, scheduling restart.
May 16 08:50:19 raspberrypi systemd[1]: Stopped Node.js HomeKit Server.
May 16 08:50:19 raspberrypi systemd[1]: Started Node.js HomeKit Server.
May 16 08:50:19 raspberrypi systemd[2783]: homebridge.service: Failed at step EXEC spawning /usr/bin/homebridge: No such file or directory
May 16 08:50:19 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=203/EXEC
May 16 08:50:19 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
May 16 08:50:19 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
May 16 08:50:29 raspberrypi systemd[1]: homebridge.service: Service hold-off time over, scheduling restart.
May 16 08:50:29 raspberrypi systemd[1]: Stopped Node.js HomeKit Server.
May 16 08:50:29 raspberrypi systemd[1]: Started Node.js HomeKit Server.
May 16 08:50:29 raspberrypi systemd[2812]: homebridge.service: Failed at step EXEC spawning /usr/bin/homebridge: No such file or directory
May 16 08:50:29 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=203/EXEC
May 16 08:50:29 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
May 16 08:50:29 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
lines 2-24

**Comment by aswathraja** [comment]
i would guess you didnt install hombridge using `-g`. Your homebridge is not installed in the specified path of `usr/bin/homebridge` please check where your homebridge is installed using the command :

`which homebridge`

and change the path of the `ExecStart` in `homebridge.service` file which you would have copied to the path : `/etc/systemd/system/`

You might want to change the `User` to root as well if it still fails to keep the state running

**Comment by HawkEye9034** [comment]
`which homebridge` returns this: /usr/local/bin/homebridge
How do i do the rest?

**Comment by aswathraja** [comment]
Navigate to the folder using
` cd /etc/systemd/system/` 

Then type `sudo nano homebridge.service`

Then in the text editor screen change the`ExecStart` path to the correct path you found above

You can change the user too as I stated above in the same file, (if you didn’t create a new user for homebridge)

**Comment by HawkEye9034** [comment]
`journalctl -a -u homebridge` confirms it is now working but I get 'No Response' on my Home app.

**Comment by aswathraja** [comment]
Remove homebridge from ur home app and add it again as this a different instance of homebridge when the config.json is at /var/lib/homebridge/

**Comment by HawkEye9034** [comment]
now i removed it from the app it wont add it back

**Comment by aswathraja** [comment]
I had problems similar to this before but i am not really sure  if it would work
Possible Solutions : 1) Power Cycle my Pi (Plug out, and wait a few seconds and plug in back on)
2) Restart your phone and wait for home app to sync with all your devices on the apple id.

**Comment by todolit182** [comment]
FWIW, I setup daemontools for this (https://cr.yp.to/daemontools.html) a couple of years ago and haven't had a single problem yet.  Keeps it running and restarts, no matter the underlying reason.

**Comment by theheims2010** [comment]
Im not sure if you got it figured out but I was having the same connection issues with the HomeKit app on my phone. 

It appears that it would not allow it to reconnect after deleting it because you need to go back into the config.json and change the MAC address and the pin code. I changed the MAC, PIN Code and then from terminal I ran, “sudo shutdown -r now” and I waited and bit and then I was able to add it to my HomeKit on my phone again.
