### ISSUE TITLE
Error during FreeNAS 9.10 BSD Jail install

### ISSUE THREAD

**Issue by TonyTheTechie** [nfarina/homebridge#1858]
I have followed the installation instructions detailed in the FreeNAS 9.10 BSD Jail install until I got to the line - **npm install bignum** - in step 9

I then received the following error message: -

```
npm WARN npm npm does not support Node.js v10.1.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
npm ERR! code Z_DATA_ERROR
npm ERR! errno Z_DATA_ERROR
npm ERR! Invalid response body while trying to fetch https://registry.npmjs.org/nan: invalid distance too far back

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-05-14T04_38_27_408Z-debug.log
```

I thought Node.js v10.1.0 was the latest version. I don't see how I can upgrade to a newer version.

I have deleted the jail and tried again and it fails at the same stage again

### Versions

- **Homebridge**: Fails before that stage in the installation
- **Node**:       Node.js v10.1.0
- **OS**:         FreeNAS 9.10.2-U6

[2018-05-14T04_38_27_408Z-debug.log](https://github.com/nfarina/homebridge/files/1999396/2018-05-14T04_38_27_408Z-debug.log)

**Comment by nakosenk** [comment]
NPM v5.8 doesn't work with Node.js v10. Try upgrading to NPM v6 that should add support for it. https://github.com/npm/npm/issues/20433 has others having the same problem with NPM v5.6 and v5.8.
