### ISSUE TITLE
FreeNAS 11 Jail Installation

### ISSUE THREAD

**Issue by s1rc** [nfarina/homebridge#1860]
Following the install Wiki I cannot get past step 6.

### Steps to Reproduce (for bugs)
Follow Wiki at step 6: https://github.com/nfarina/homebridge/wiki/FreeNAS-11-Installation-using-a-Jail

### Versions

- **Homebridge**: `n/a`
- **Node**:       `v10.1.0`
- **OS**:         `FreeNAS 11`

### Homebridge Log / Command Output

```
npm ERR! code Z_DATA_ERROR
npm ERR! errno Z_DATA_ERROR
npm ERR! Invalid response body while trying to fetch https://registry.npmjs.org/homebridge: invalid distance too far back

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-05-16T14_04_19_853Z-debug.log
```

**Comment by TonyTheTechie** [comment]
This looks very similar to the error I am getting on the FreeNAS 9.10 installation
