### ISSUE TITLE
myQ Garage Door not showing up as an Device option.

### ISSUE THREAD

**Issue by rchoughton** [nfarina/homebridge#1861]
### Expected Behavior

I have installed the brbeaird/SmartThings_MyQ smart app that brings a Lift Master myQ garage door into smartthings. At one time it showed up, but with recent updates it does not show up as an option anymore

### Versions

- **Homebridge**: `homebridge --version` 0.4.33
- **Node**:       `node --version` v6.14.2
- **OS**:         
XXXXXXXX:~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
XXXXXXXX:~ $ uname -a
Linux XXXXXXXX 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l GNU/Linux

### Configuration

```json

```

### Homebridge Log / Command Output

```

```

**Comment by AppleTechy** [comment]
Please update the post with your configuration. Also based on your above description it sounds like it is a plugin issue not Homebridge's core. Please post the issue to the plugin's Github Repo.
