### ISSUE TITLE
Livolo plugin 

### ISSUE THREAD

**Issue by jungopro** [nfarina/homebridge#1862]
Hi
I was wondering if you have any knowledge of a livolo compatible plugin for homebridge? I couldn’t find one in npmjs...

Thanks
Omer

**Comment by maragelis** [comment]
livolo is 433mhz and not wifi if I am not mistaken. if i am correct you will need something like this
https://www.banggood.com/SONOFF-RF-Bridge-WiFi-433-MHz-Replacement-Smart-Home-Automation-Universal-Switch-p-1179900.html?rmmds=search

**Comment by jungopro** [comment]
Thanks
My HB is on R Pi. 
Can I add an RF USB to it and then connect HB to livolo?
What RF USB will be compatible? 
And if I get the adapter, what plugin do I need to connect HB to Livolo?

**Comment by maragelis** [comment]
You can use node-red  (already installed on pi) and mqtt, then all you need is any switch plugin that uses mqtt. I don’t know if any USB adapters, but you can create your own WiFi adapter using a wemos d1 and a cheap  433mhz receiver. Check out one of my projects.

**Comment by maragelis** [comment]
You could also go this route https://www.google.gr/amp/www.instructables.com/id/Super-Simple-Raspberry-Pi-433MHz-Home-Automation/%3famp_page=true

**Comment by perry-mitchell** [comment]
Has anyone had any luck here? Would love to use these switches..

**Comment by Kung-Foo-Kamel** [comment]
Just purchase a Broadlink RM Pro, perfect for all 433 stuff.

Personally I wouldnt bother, I purchased these switches, but I replacing them now, their hopless for home automation, due the remotes only have one button to toggle light state, you need seperate "on" and "off" in order for them to be useable.

The issue arrises if you remotely want to turn on the light, if its all ready on, then you would end up turning it off, these lights have no feedback to HB so you have no clue what state its in.

The cheapest touch switches on ebay work better than the Livolo ones, as they have seperate buttons for on, off, dim up and dim down.

I purchased both the large multi room remote and the mini 4 button remote, and the short answer is, sell it all off and purchase generic no-name switches instead.

Here is a link to a 433 switch that will work pretty good: http://r.ebay.com/ot5gLh

Here is a link to the RM Pro: http://r.ebay.com/2GDTA3

These links are for AU, but the items are available from different venders world wide, the RM Pro will make your Livolo switches operate with this plugin: https://github.com/lprhodes/homebridge-broadlink-rm#readme

Cheers

KFK
