### ISSUE TITLE
need help, problem with the installation of Homebridge on windows 7

### ISSUE THREAD

**Issue by Deniz1005** [nfarina/homebridge#1863]
### Current Behavior
in gitcmd:

`..\node_curve.cc(1): fatal error C1083: Cannot open inslude file: ' string.h ': No such file or directory [C:\User\Denis\\AppData\Roaming\npm\node_modules\homebridge\node_modules\curve25519-n\build\curve.vcxproj]`

in log:

3708 verbose rebuild bundle C:\Users\Denis\AppData\Roaming\npm\node_modules\homebridge\node_modules\curve25519-n
3709 info build C:\Users\Denis\AppData\Roaming\npm\node_modules\homebridge\node_modules\curve25519-n
3710 info lifecycle curve25519-n@1.4.0~preinstall: curve25519-n@1.4.0
3711 silly lifecycle curve25519-n@1.4.0~preinstall: no script for preinstall, continuing
3712 info linkStuff curve25519-n@1.4.0
3713 silly linkStuff curve25519-n@1.4.0 has C:\Users\Denis\AppData\Roaming\npm\node_modules\homebridge\node_modules as its parent node_modules
3714 verbose linkBins curve25519-n@1.4.0
3715 verbose linkMans curve25519-n@1.4.0
3716 verbose rebuildBundles curve25519-n@1.4.0
3717 info lifecycle curve25519-n@1.4.0~install: curve25519-n@1.4.0
3718 verbose lifecycle curve25519-n@1.4.0~install: unsafe-perm in lifecycle true
3719 verbose lifecycle curve25519-n@1.4.0~install: PATH: C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\Denis\AppData\Roaming\npm\node_modules\homebridge\node_modules\curve25519-n\node_modules\.bin;C:\Users\Denis\AppData\Roaming\npm\node_modules\homebridge\node_modules\.bin;C:\Users\Denis\AppData\Roaming\npm\node_modules\.bin;C:\Program Files (x86)\Git\cmd;C:\Python27\;C:\Python27\Scripts;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Git\cmd;C:\Users\Denis\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files (x86)\nodejs\;C:\Users\Denis\AppData\Roaming\npm
3720 verbose lifecycle curve25519-n@1.4.0~install: CWD: C:\Users\Denis\AppData\Roaming\npm\node_modules\homebridge\node_modules\curve25519-n
3721 silly lifecycle curve25519-n@1.4.0~install: Args: [ '/d /s /c', 'node-gyp rebuild' ]
3722 silly lifecycle curve25519-n@1.4.0~install: Returned: code: 1  signal: null
3723 info lifecycle curve25519-n@1.4.0~install: Failed to exec install script
3724 verbose unlock done using C:\Users\Denis\AppData\Roaming\npm-cache\_locks\staging-cb345d577d1b5977.lock for C:\Users\Denis\AppData\Roaming\npm\node_modules\.staging
3725 silly rollbackFailedOptional Starting
3726 silly rollbackFailedOptional Finishing
3727 silly runTopLevelLifecycles Starting
3728 silly runTopLevelLifecycles Finishing
3729 silly install printInstalled
3730 verbose stack Error: curve25519-n@1.4.0 install: `node-gyp rebuild`
3730 verbose stack Exit status 1
3730 verbose stack     at EventEmitter.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\lifecycle.js:233:16)
3730 verbose stack     at emitTwo (events.js:87:13)
3730 verbose stack     at EventEmitter.emit (events.js:172:7)
3730 verbose stack     at ChildProcess.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
3730 verbose stack     at emitTwo (events.js:87:13)
3730 verbose stack     at ChildProcess.emit (events.js:172:7)
3730 verbose stack     at maybeClose (internal/child_process.js:818:16)
3730 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
3731 verbose pkgid curve25519-n@1.4.0
3732 verbose cwd C:\Program Files (x86)\Git
3733 error Windows_NT 6.1.7601
3734 error argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "homebridge"
3735 error node v5.0.0
3736 error npm  v3.3.6
3737 error code ELIFECYCLE
3738 error curve25519-n@1.4.0 install: `node-gyp rebuild`
3738 error Exit status 1
3739 error Failed at the curve25519-n@1.4.0 install script 'node-gyp rebuild'.

### Versions

- **Homebridge**: `homebridge --version`
- **Node**:       `node v5.0.0`
- **OS**:       Windows 7 x64 SP1

Can someone show me how to solve this?

**Comment by i3laze** [comment]
Hi there.. Is your profile name nonLatin?
Is it C:\Users\Denis\ or actually is C:\Users\Денис\ ? 

Try this 
https://github.com/nodejs/node-gyp/issues/297#issuecomment-77996978
