### ISSUE TITLE
New option for Homebridge_OPTS

### ISSUE THREAD

**Issue by Nastras** [nfarina/homebridge#1864]
Hello everybody,
i have 24 Homebridge instances running as systemd service, one instance for each plugin.

What has always disturbed me and synonymous has reduced the system speed is that every instance starts all the plugins from global installed / usr / lib / node_modules.
By a note from another user, the solution became aware of the -P option to use. To test I have installed all the plugins local what a little more cumbersome the conventional way and started with the -P option.

Now each instance just launches the plugin it needs.
If I install the plugins globally in / usr / lib / node_modules I have a random access memory consumption when all 24 instances are started from 2.5GB.
With an installation of the plugins locally is that only each instance the plugin loads what it needs at 700 MB. Here is a huge performance difference especially for raspberry pi user.

My own hardware is an Intel nuc, because with the raspberry pi 3 the random access memory was no longer sufficient. On my raspberry pi 3 I could start a maximum of 10 instances. I think that many users use their Homebridge with multiple instances because the advantages are very big compared to the single instance.

I have also tried using the -P option to start the instances when the plugins are installed in / usr / lib / node_modules. Unfortunately all plugins will be loaded in every instance. I also received this message:

`skipping plugin found at '/ usr / lib / node_modules / homebridge-sun-position' since we already loaded the same plugin from '/ usr / lib / node_modules / homebridge-sun-position'.
`

Would not it be useful here to create maybe a new option -X for the (config option) in homebridge which still allows the plugins globally to be installed under / usr / lib / node_modules. This would allow for each instance only the plugin to start what is needed without reinstalling all plugins to local.

For the ever larger Homebridge setups of the users I think that it would be a great new feature.

Greeting Nastra

**Comment by Nastras** [comment]
#1855

**Comment by Nastras** [comment]
#1855

**Comment by theo-69** [comment]
Great Idea

**Comment by m4d-maNu** [comment]
Good idea, please intrigue in HB.

**Comment by SeydX** [comment]
Very nice idea, i have submitted a pull request to make that possible

https://github.com/nfarina/homebridge/pull/1866

**Comment by Heiliger85** [comment]
Great idea. I hope it will come in next version of Homebridge.

**Comment by NSCHI** [comment]
Great idea

**Comment by oznu** [comment]
I think this should be implemented in a backwards compatible way. That is, only disable loading the globally installed plugins if the `-X` flag is present. Otherwise I can see a lot of people having to make changes to their setups when it breaks upon upgrading - which would mean more issues raised here on GitHub by confused users.

Perhaps a naming the flag something like `--disable-global` might be more descriptive as well.

**Comment by oznu** [comment]
Disregard last comment, I actually looked at the proposed PR

**Comment by Nastras** [comment]
#1880 
solved!
