### ISSUE TITLE
Logo Proposal for HOMEBRIDGE

### ISSUE THREAD

**Issue by ggabogarcia** [nfarina/homebridge#1865]
Hello, I want to cooperate with the project, I read what it is and I found it really interesting, for this reason I decided to design a logo for this project. If you like it, let me know and I'll send you the files. Remember that you can suggest color changes. I hope you like it!

![home bridge](https://user-images.githubusercontent.com/35750428/40318671-05b9a294-5ceb-11e8-8e8b-259eb7e33e07.jpg)

**Comment by Nastras** [comment]
I like the Black and White logo 😉

Great Job 👍

**Comment by ascillato** [comment]
I also like the black and white :+1:

Great job!

**Comment by simont77** [comment]
Maybe I’m wrong, but I think it’s a single logo. In any case, I like it!

**Comment by simont77** [comment]
You should send them to @KhaosT or @nfarina, they are the admins. Let’s see what they think.

**Comment by simont77** [comment]
For the color, if not B&W I prefer yellow as the official Homekit logo

**Comment by NorthernMan54** [comment]
Last year @taitems on Slack had also created a couple of concepts as well

![image](https://user-images.githubusercontent.com/19808920/40334092-d4c5e24e-5d29-11e8-929b-4d691335c212.png)

And I have used this for my homebridge-alexa smart home skill

Do we need to vote or something to decide which one to use?

**Comment by ascillato** [comment]
I like your logo, but I like more the one from @ggabogarcia.

Vote for @ggabogarcia on black and white :+1:

**Comment by ggabogarcia** [comment]
They could use the logo in -Readme- provisionally.

**Comment by taitems** [comment]
I had been working on a web page with my version of the logo, which anyone can take over:

![image](https://user-images.githubusercontent.com/234593/40335494-4c9e4496-5da7-11e8-89b6-6f09c0e447c9.png)

A video of it in action with npm autocomplete search https://drive.google.com/open?id=1txeCorint_lCErpoddoCYitxeFMnQ7qU

And some of the experiments I was doing in Sketch:

![image](https://user-images.githubusercontent.com/234593/40335602-e062b45a-5da7-11e8-99f2-40557c01b2f0.png)

![image](https://user-images.githubusercontent.com/234593/40335610-f1599044-5da7-11e8-92da-3e0be11adee6.png)

![image](https://user-images.githubusercontent.com/234593/40335622-00c28dc4-5da8-11e8-96f3-3033becc663c.png)

There's no reason why ideas can't be combined, source code shared etc. I just had a baby and remembered that open source is a childless person's game haha.

**Comment by nfarina** [comment]
Thanks for chiming in and posting those @taitems - and congrats on your new baby!

Fun fact - I wrote 90% of Homebridge code while my newborn twins were between naps 😂

**Comment by simont77** [comment]
I really like the website layout from @taitems, but I prefer the logo from @ggabogarcia. @nfarina, is it possible to open a pool here or on slack?

**Comment by cubilon** [comment]
I like the yellow one, reminds me HomeKit

**Comment by ggabogarcia** [comment]
@taitems I think the idea of ​​combining the works is great, it's up to you, Mr. @nfarina, to accept my proposal.

**Comment by nfarina** [comment]
@ggabogarcia I love your logo, I'd be honored to make it the official mark. As for color, I agree. that yellow looks the most "natural" but only because it's mimicking Apple's branding for HomeKit, which I'm a bit wary of.

Let's go with B&W version for the README to start with if that's OK with you - if you can post the file somewhere then I can publish it.

@taitems Is your latest work accessible in Dropbox or similar?

**Comment by ggabogarcia** [comment]
@nfarina excellent news sir, let me upload all the files to Drive, and send you the link. Thank you very much.

**Comment by ggabogarcia** [comment]
@nfarina Ready sir, in this link you will find all the files, png, svg, eps and pdf, all in black and white as requested.
https://drive.google.com/drive/folders/1n5a5tfiGdbijm6s-In8zK_dakumwPb7F?usp=sharing

**Comment by ggabogarcia** [comment]
Remember that you can place the color you want, the blue that @taitems uses on the website is great.

**Comment by ggabogarcia** [comment]
![derechos](https://user-images.githubusercontent.com/35750428/40395535-2ca369e0-5dee-11e8-9824-4fdb575c50f1.jpg)

This work is licensed under a [Creative Commons Attribution 4.0 International License.](https://creativecommons.org/licenses/by/4.0/#)

Thank you so much for accepting my contribution

**Comment by NorthernMan54** [comment]
@ggabogarcia Are you okay with my using these with my homebridge-alexa skill, to identify this as part of the "homebridge" brand?   The icon would then appear in the Amazon Alexa Smart Home Skill, as part of the homebridge skill.

Also for everyone participating in this thread, if we want to setup an "official" homebridge website, I will gladly donate the Amazon AWS promotional credits I'm receiving from my "Homebridge" skill to fund the website on AWS.

This would also go along way with the effort that @AppleTechy is working on to create an official homebridge community using the homebridge GitHub and NPM org.

**Comment by ggabogarcia** [comment]
@NorthernMan54 I totally agree with that, I would feel really good in that they use it, it is my contribution for this project.

**Comment by AppleTechy** [comment]
Sorry if I am missing something. Can @nfarina or @northernman45 dm me on Slack or discord the new set of logos and what the plan now is. Reading on mobile so I probably am missing a lot of the conversation. Lol

**Comment by AppleTechy** [comment]
Edit:  I am all caught up. I think the black and white looks great for the readme but personally I am a fan of a more colorful logo.  Any one got an idea on that? Then could I get sent a folder for the colored one? If you merge a PR on the readme, I will go ahead and update all the accounts I have access to the new logo( Twitter, Github Org, Discord) :)

**Comment by ggabogarcia** [comment]
The color suggestions for Homebridge can also suggest color changes.

![home bridgej](https://user-images.githubusercontent.com/35750428/40440243-29f899aa-5e83-11e8-9f6e-898531f83347.png)

**Comment by ggabogarcia** [comment]
https://drive.google.com/drive/folders/1n5a5tfiGdbijm6s-In8zK_dakumwPb7F?usp=sharing
Files full color

**Comment by AppleTechy** [comment]
@nfarina @KhaosT @NorthernMan54 Anyone have a preference on a colored version of the logo to be used in conjunction with the black & white version?

**Comment by NorthernMan54** [comment]
No preference

**Comment by pdlove** [comment]
I think the greenish color is the most pleasant.

**Comment by nfarina** [comment]
I was hoping to get ahold of @taitems’s sketch files so I could attempt to combine the new mark with his existing style.

**Comment by taitems** [comment]
Let me attach these tomorrow, and you can have at it. The one I started building as a real front end site was a PSD though. Sketch was all the experiments and stuff as a familiarisation process.

**Comment by taitems** [comment]
[Google Drive link](https://drive.google.com/open?id=1PDKEdY-2cx1iz0o3XhrEEcOmb9hZYu2R) for Sketch File.

**Page 1** was logo play. The metaphor being homebridge makes two disparate systems talk the same language. Two disconnected signals making one functioning HomeKit.
![image](https://user-images.githubusercontent.com/234593/40609807-2d2c51a0-62b3-11e8-81a1-ce8872562a2a.png)

**Page 2** was all the layout experimentation. The metaphor here was "I dunno? I can't design without a creative brief".
![image](https://user-images.githubusercontent.com/234593/40609821-3b346008-62b3-11e8-8e49-132c510614ea.png)

As far as I can remember, all images come from Pexels and are therefore CC0.

**Comment by NorthernMan54** [comment]
@ggabogarcia Tks very much for you logo, I just published the new README with the logo.

**Comment by gozoinks** [comment]
@ggabogarcia The glyph is great. For what it's worth, "homebridge" seems like one word to me, and splitting the words in the logo seems to break that. Attaching an example with a simple monospaced font, which seems appropriate, given the nature of homebridge. For discussion.
![screen shot 2018-06-11 at 11 01 14 pm](https://user-images.githubusercontent.com/1703856/41269586-9927c4ca-6dcb-11e8-99b6-5d2a70ab4260.png)

**Comment by ggabogarcia** [comment]
Hello @gozoinks , sir, here are some examples that use the monospaced font you requested.

![examples](https://user-images.githubusercontent.com/35750428/41372042-cba922da-6f11-11e8-97ed-3a00ff411b97.png)

**Comment by nfarina** [comment]
@ggabogarcia I'd vote for the capital H in either horizontal or vertical format depending on context. I like it much better than the split-word version. Looks great!

**Comment by nfarina** [comment]
@taitems Could you send a link to your in-progress version of the website you mentioned above? I'd be happy to take over and try to bang it out this weekend.

**Comment by taitems** [comment]
@nfarina I can hopefully attach it tonight or over the weekend. just so you know, I was using it as a training exercise to evaluate the whole "you don't need jQuery/React/Angular etc" movement. I tried building it all in vanilla JS and knowing what I do now, I'd probably just use a react component for the autocomplete.

**Comment by nfarina** [comment]
@taitems Friendly reminder to send over the website (vanilla JS is right up my alley!) and also the fonts ("DIN2014") when you get a chance!

**Comment by AppleTechy** [comment]
@taitems Hmm for some reason Photoshop isn't automatically resolving the font. Is this the right one?[TypeKit link](https://typekit.com/fonts/din-2014/availability)

**Comment by taitems** [comment]
@AppleTechy That looks to be the one. It could be that I'm using an older Photoshop and CC version (2017) and it's created somewhat of a legacy font reference?

**Comment by nfarina** [comment]
Found the fonts, did some fiddling and put together a version of the logo that I think works well - combining the mark from @ggabogarcia and the color palette+logotype from @taitems. Result is on the README (and on the Slack team) Hope you guys like it. Website is still TODO 😛

**Comment by NorthernMan54** [comment]
I saw the change on Slack, and it looks great everyone

**Comment by nfarina** [comment]
New website is live. Thanks @taitems and hope you don't mind that I had to axe a couple features that I can tell you worked hard on 😢:

1) The autocomplete search box didn't always show the best results (and the UI was glitchy) - there's just no good API for searching npm (npmsearch is kind of a 3rd party hack thing). Instead I added a Search button which takes you to npm's official search page with your query pre-submitted.

2) Your amazing SVG animation where it floats up portions of the logo unfortunately doesn't have a good corollary with the new logo. I wanted to make the new logo "draw itself" but it's rendered using vector fills so it's not as straightforward as a stroke-dash-animation hack would be. I think the way to do it is with a separate stroke-based mask but I haven't tried this yet.

I'm going to close this issue now - I'm super happy with Homebridge's new branding and I hope you guys are as well!

**Comment by nfarina** [comment]
Nevermind the mask thing was easy so I added a logo animation as described.

**Comment by taitems** [comment]
@nfarina I don't mind at all, I think you've done a bloody good job considering! 

1) Yes, the autocomplete was flakey for me too, I think you made the right call. 
2) I noticed the effect, I think it works quite well

Finally, a minor tweak -- the white box sits hard against the bottom of the page, which looks like it ends very abruptly!

**Comment by nfarina** [comment]
Good point! Added a footer with some attribution credits. Feels more like a real site now 😛

**Comment by NorthernMan54** [comment]
README Logo

![homebridge](https://user-images.githubusercontent.com/19808920/58770949-bd9c7900-857f-11e9-8558-5dfaffddffda.png)

**Comment by Bi7** [comment]
👍🏽
