### ISSUE TITLE
question re homebridge.APIs

### ISSUE THREAD

**Issue by pi3dec** [nfarina/homebridge#1867]
Hello Guys, 
apologies for flooding into the issues thread, I've got few dev questions and would greatly appreciate if you could answer. Thanks!

1.  I am updating AccessoryInformation when it was already deployed to HomeBridge and reflected in the Home.app, if I do: Accessory.getService(Service.AccessoryInformation).setCharacteristic(Characteristic.Manufacturer, "smth") and then that.api.updatePlatformAccessories I don't get changes reflected in Home until after HomeBridge restarts. Any hints how to force update Hope.app data without restart?

2. when reachability is false, does it mean that all Homekit requests for getValue are taken from the accessories cache, and whenever I update it to true, I have to support Get/Set events for instantaneous values read/set form the Homekit apps?

3. Unlikely possible, but will give it a go, all new homebridge accessories are getting into the room where homebridge itself was assigned, could I have a way to push new accessories to the designated room?

Thanks again!

**Comment by NorthernMan54** [comment]
Question 1 - I don't know the answer to this, but I don't believe this is a valid use case.  Please check the Apple HAP-Spec

Question 2 - Reachability was deprecated a while back by Apple.  Take a look at this pull request, where updateValue was updated to create 'not responding' status.  https://github.com/KhaosT/HAP-NodeJS/pull/556

Question 3 - Nope, all new accessories go to the default room.

If you want to chat more, I'm frequently available on Slack
