### ISSUE TITLE
homebridge and Ubuntu Core

### ISSUE THREAD

**Issue by m0rt3nlund** [nfarina/homebridge#1868]
Hi!

I was wondering if there are any experience using Homebridge with Ubuntu Core and Snap?

I have managed to install homebridge using the Snap here: https://snapcraft.io/homebridge

But how should we install plugins in this environment? I cannot change anything due to the nature of Ubuntu Core as far as I know? Do I have to make ned snaps containing each Plugin or something like that?

Hope someone have any knowledge about this! :-)

Thank you,
Morten Lund

**Comment by ghazlewood** [comment]
`homebridge.npm-install homebridge-config-ui-x` appears to do it for me @m0rt3nlund:

```
root@audric:~# homebridge.npm-install homebridge-config-ui-x
HOMEBRIDGE_AUTO_UPDATE_NPM_MODULES=on (default value)
/var/snap/homebridge/common/bin/homebridge-config-ui-x -> /var/snap/homebridge/common/lib/node_modules/homebridge-config-ui-x/dist/bin/standalone.js

> node-pty@0.7.8 install /var/snap/homebridge/common/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty
> node scripts/install.js
```
