### ISSUE TITLE
minimalist-package.json 

### ISSUE THREAD

**Issue by cflurin** [nfarina/homebridge#187]
The Shim Family is growing, great. Otherwise installing HomeBridge on a RPi may be time-consuming. I reduced the dependencies to the minimum:
```javascript
{
  "name": "homebridge",
  "description": "HomeKit support for the impatient",
  "version": "0.1.1",
  "scripts": {
    "start": "DEBUG=* node app.js || true"
  },
  "repository": {
    "type": "git",
    "url": "git://github.com/nfarina/homebridge.git"
  },
  "license": "ISC",
  "dependencies": {
    "color": "0.10.x",
    "hap-nodejs": "git+https://github.com/KhaosT/HAP-NodeJS#0030b35856e04ee2b42f0d05839feaa5c44cbd1f",
    "mdns": "^2.2.4",
    "node-persist": "0.0.x",
    "q": "1.4.x",
    "request": "2.49.x",
    "xml2js": "0.4.x",
    "xmldoc": "0.1.x",
    "debug": "^2.2.0"
  }
}
```
Probably there are other dependencies we can delete.

**Comment by snowdd1** [comment]
Are we at the point to discuss the reduction of mandatory dependencies and installation of platforms and shims again? :smile: 
I wonder if @nfarina got any further with his provider-api branch, which I really did not understand yet.

My proposal is to install shims via npm upon finding references in config.json - no entry in config.json, no need for installation of the dependencies.

I have a working prototype at https://github.com/snowdd1/homebridge/tree/dynamic-platform which is able to install the homebridge-knx npm package based on package.json information. 
(And it is somewhat outdated as some PRs would overwrite my changes)

Sadly, we never came forward in the discussion.

I found the following ideas being mentioned:
- let the users install via npm themselves (I think that is what Nick is working on)
- install upon finding in config.json (my approach) - in the bright future have a web front end for that
In both cases, the [dependencies](https://github.com/snowdd1/homebridge/blob/dynamic-platform/package.json#L13) would shrink to
````json
  "dependencies": {
    "color": "0.10.x",
    "hap-nodejs": "git+https://github.com/KhaosT/HAP-NodeJS#6bf0f9eaaa2d87db8d1768114c61f4acbb095c41",
    "mdns": "^2.2.4",
    "node-persist": "0.0.x",
    "npmi": "1.0.1",
    "request": "2.49.x",
    "xml2js": "0.4.x",
    "xmldoc": "0.1.x"
  }
````
as all shim and platform dependencies are gone.
Building on a raspi2b takes <2 minutes, which I find is quite good for updating.

**Comment by cflurin** [comment]
@snowdd1
Honestly I'm working on other projects too, so I think we should patiently wait. IMHO I think stability and functionality have priority.

**Comment by cflurin** [comment]
@snowdd1 off topic: which Node version are using on your RPi 2?

**Comment by snowdd1** [comment]
Still on 0.12

**Comment by Kolbi** [comment]
I'm currently getting the issue: "No compatible version found: eibd@'^0.3.1'"

node -v v0.6.19
npm -v 1.1.4

on my Raspberry...

**Comment by cflurin** [comment]
@Kolbi You should update node to 0.12.6 but **do not install version 4.0.0**

**Comment by Kolbi** [comment]
@cflurin okay, just installed it via "sudo apt-get install node" on Raspbian..

**Comment by cflurin** [comment]
Which version is now installed?
node -v
npm -v

**Comment by SphtKr** [comment]
Another use case for figuring out modules and splitting up dependencies: I'd like to write a module for iTunes, to turn on and off playback and various AirPlay speakers (hello Apple, why isn't this already in HomeKit??). But to do that I'd have to introduce a dependency that would only compile on OS X...so, can't do that right now I don't think.

Not a huge priority, but another reason to figure out how to break the various platforms into their own modules.

**Comment by nfarina** [comment]
I'm currently working on porting just the "plugin" support from the `provider-api` branch as the web interface has a long way to go. For expediency, I'm planning on having the user manage their own plugins by installing npm packages like "homebridge-knx" etc. I think the web interface can definitely help the user do this for them as well, but this is the fastest way I can think of to start splitting things up.

**Comment by snowdd1** [comment]
Cool, what do the plugins have to do to work with the next homebridge?
Is there any required structure, any changes in exposed methods etc.?

**Comment by nfarina** [comment]
Goal is no change required besides adding package.json.

**Comment by snowdd1** [comment]
Even better! I am ready for testing, just tell me if you are. Currently the integrated version is still my master, I try to update the npm package version every now and then.

**Comment by Kolbi** [comment]
@cflurin I just installed node-v0.10.28 using this tutorial: http://pimatic.org/guide/getting-started/installation/

I created a little Shell-Skript for Raspberry: https://github.com/Kolbi/FHEM/blob/master/homebridge.sh

**Comment by cflurin** [comment]
I'm looking forward to the plugin feature. In the meantime following how-to might be of interest.
[Minimalist Homebridge](https://github.com/cflurin/homebridge-shims/wiki/Minimalist-Homebridge-on-a-Raspberry-Pi)
