### ISSUE TITLE
How to update Homebridge

### ISSUE THREAD

**Issue by dcaccount** [nfarina/homebridge#1870]
Hello,

I have installed Homebridge about two months ago with `sudo npm install -g --unsafe-perm homebridge`.

What is the safest way to check for updates and then to update it?

Thanks,
dan

**Comment by theo-69** [comment]
try `sudo npm install -g --unsafe-perm homebridge@latest`

**Comment by Nastras** [comment]
sudo npm outdated -g
lists all available npm updates installed on your system.

**Comment by dcaccount** [comment]
Thanks, is there any risk in updating?

**Comment by Nastras** [comment]
There is no risk, here you will only see available updates. You have to install with other commands.

**Comment by dcaccount** [comment]
Clear but if update one package or Homebridge, will I run any risk? 
I would not like to jeopardise what I have installed but I would like to keep the system updated

**Comment by Nastras** [comment]
There is always a risk with an update that goes wrong and does not work later. Make a backup before if you are not sure of your system.

**Comment by dcaccount** [comment]
Clear. So can you please advise the best way to update a package?

Is it “sudo npm install -g --unsafe-perm homebridge@latest” or is there another one?

Thanks!

**Comment by dcaccount** [comment]
Thanks, with the final “-g” after “@latest”?

**Comment by barquestdan** [comment]
I just pieced this together from a few different issues, so I figured I would throw my thoughts together (if only so I can reference it again in the future)

1 npm update -g
2 npm cache clean -f
3 sudo n stable
4 npm install -g -unsafe-perm homebridge@latest -g

**Comment by Calorion** [comment]
Is there a way to update all plugins at once? I'd really rather set up a cronjob to update everything at once; if everything's running smoothly, I often don't look at Homebridge for months.

**Comment by Calorion** [comment]
Bump. HOOBS can do this; can Homebridge?
