### ISSUE TITLE
Garage door triggered - what plugin to use?

### ISSUE THREAD

**Issue by dcaccount** [nfarina/homebridge#1872]
Hello,
I am looking for a simple plugin to be warned by Homekit only when the garage door is opening, not when it is closing.

I have a signal coming from the garage board that is 0 when the door is closed and 1 when it is not closed.

I have implemented it in Homekit using [https://github.com/rsg98/homebridge-gpio-wpi2](url) but I receive a notification not only when the garage door is opening but also when it is closed. I just would like to be warned only when it is opening.

How can I implement this?
Thanks,
dan

**Comment by ebaauw** [comment]
You cannot.  Notifications is a feature of the Home app; there’s nothing in the HAP (or even HomeKit) api to change them.
