### ISSUE TITLE
Error due to wrong version number on homebridge user

### ISSUE THREAD

**Issue by theGeorg** [nfarina/homebridge#1873]
### Expected Behavior

Homebridge should start without error. 

### Current Behavior

```
Error: Plugin /usr/local/lib/node_modules/homebridge-hue requires a HomeBridge version of ^0.4.42 which does not satisfy the current HomeBridge version of 0.4.38. You may need to upgrade your installation of HomeBridge.
```
Note that Version 0.4.42 is installed.

### Steps to Reproduce (for bugs)

Homebridge works normally when startet on "pi" user. The error message only appears on the "homebridge" user that was created for automated startup. (https://timleland.com/setup-homebridge-to-start-on-bootup/comment-page-1/)

### Versions

- **Homebridge**: 0.4.42
- **Node**:  9.4.0
- **OS**:  Raspbian GNU/Linux 9 (stretch)      

### Configuration

```json

```

### Homebridge Log / Command Output

```

```

**Comment by ebaauw** [comment]
Most likely, you installed homebridge twice.

Under user homebridge, what's the output of `which homebridge`?  Is that the same as under user pi?  And what did you specify for ExecStart in `/etc/systemd/system/homebridge.service`?

**Comment by theGeorg** [comment]
Ok I see. Changed what I specified under ExecStart and now it works. Thank you.
