### ISSUE TITLE
Difference between platform and plugin

### ISSUE THREAD

**Issue by dcaccount** [nfarina/homebridge#1874]
Hello,
I apologise for the easy question but being a newbie I have not realised the difference between platforms and accessory inside a config.json file.

Can anyone please advise?

I have noticed that some plugin require a platform to be specified, some others just accessories, why?

Can the coexist in the same config.json file?

Thnaks for clarifying, dan

**Comment by dcaccount** [comment]
So a platform is a group of accessory, have I understood correctly?

And then other “independent” accessories may coexists with platforms.

Is that correct?
Thanks,
Dan

**Comment by AppleTechy** [comment]
Platforms can be configured dynamically. Essentially it does the heavy lifting for you, you login to your Nest,Ecobee, etc, and a platform will handle the declaring of accessories and their characteristics and auto link commands. Accessories allow more granular control and require more setup. You will have to setup the device name, IP address of the device for each device you want to link. That make sense?

**Comment by mikekenyon99** [comment]
Hi, I too have this question - what is the difference?

Mike
