### ISSUE TITLE
iOS 11.4

### ISSUE THREAD

**Issue by dcaccount** [nfarina/homebridge#1876]
Hello,
Has anyone already tried IOS 11.4 with Homebridge?

Could there be any compatibility issue?

Thanks.
Dan

**Comment by Mattin** [comment]
After I updated all my devices, lights and switches works, but it seems that motion sensors stopped working.

**Comment by NorthernMan54** [comment]
Check your setup, I updated without issue and confirmed that motion sensors are working

**Comment by brentleeper** [comment]
There seems to be an issue with removing homebrige from HomeKit and then trying to re-add it. Upon scanning the QR code after Homebridge start up, the Home App gives an error: "Accessory already added - To add this accessory to your home, you'll need to reset it first" 

Changing the pin does not resolve the issue.

**Comment by fungilation** [comment]
Nothing to do with re-adding. After iOS 11.4, devices attached to Homebridge just stays offline even when I'm on same wifi. And deleting homebridge and re-adding, it says "Accessory not found".

Hopefully whatever broke in iOS 11.4 isn't too hidden on what broke homebridge?

**Comment by cubilon** [comment]
try this:
- remove homebridge from any iOS device
- disable HomeKit from iCloud settings in any device
- soft reset any device
- re-add HomeKit in iCloud settings
- change name, mac address and pin in your Homebridge config
- retry adding Homebridge on HomeKit

**Comment by brentleeper** [comment]
I followed the suggested steps. 

I did notice something new (to me). There is a directory called .AppleDouble in the .homebridge directory. 

Additionally, these steps allowed me to add all my devices and within HomeBridge I can see the log feedback printing statuses for many devices but in the Home app none of my devices are responding. The only thing that has changed is the upgrade to 11.4

**Comment by theo-69** [comment]
everything working gerat just the yeelight plugin broke, so any problems are more likely with individuelly plugins you use.

**Comment by cubilon** [comment]
so, my advice to @brentleeper is to reinstall each plugin he's using.

**Comment by dehsgr** [comment]
Hi all! Is it possible that you're sitting in EU, if your plugin is not working? If yes, you're the winner and currently not being able to use your yeelight at all. See https://www.stern.de/digital/online/dsgvo--die-absurden-folgen-des-datenschutz-gesetzes-7999562.html (German).

**Comment by theo-69** [comment]
@justme-1968 always trying to avoid it two, however was not even aware that these lamps need cloud. I only use them via plugin and not kill the cloud connection again.

**Comment by justme-1968** [comment]
it depends. the desk lamp is cloud only as it has no development mode. also the normal yeelight app will not work if you block outgoing connections for the lights. don't know if this is also the case for the lights with development mode.

anyway: enabling development is a hack and not a product feature. these cloud connected devices are just wrong.

**Comment by theo-69** [comment]
@justme-1968 thats not correct, there is a Development mode also for the desk lamp, otherwise it would not work with the homebridge plugin.

**Comment by theo-69** [comment]
well now it is, because mine is working 
![img_9093cc6c1dcb-1](https://user-images.githubusercontent.com/28484958/40730593-05f9cc48-63fd-11e8-8de6-3f395fa34bd3.jpeg)

**Comment by justme-1968** [comment]
this sounded like good news... unfortunately the required reset to reconnect the lamp with the app has bricked the lamp...

**Comment by macjeff** [comment]
I have been running 11.4 along with all the betas and not had a single issue.

**Comment by fungilation** [comment]
@cubilon, tried all these doesn't work. Still says "Accessory not found". My device/plugin is https://github.com/aschaper/homebridge-sesame. Did iOS 11.4 bring any change that would have broken it?

> - remove homebridge from any iOS device
> - disable HomeKit from iCloud settings in any device
> - soft reset any device
> - re-add HomeKit in iCloud settings
> - change name, mac address and pin in your Homebridge config
> - retry adding Homebridge on HomeKit

**Comment by theo-69** [comment]
@justme-1968 to bad, however I use mine with homebridge and developer model since March.

**Comment by cubilon** [comment]
>@cubilon, tried all these below as you suggested, doesn't work. Still says "Accessory not found". My device/plugin is https://github.com/aschaper/homebridge-sesame. Did iOS 11.4 bring any change that would have broken it? ...

- @fungilationare are you on Raspberry?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fungilation** [comment]
No. MacOS 10.13.4

**Comment by cubilon** [comment]
- just the same. redo the procedure, but before adding homebridge to home app, try removing persist and persist-plugin directories form homebridge directory and recreate them, then remove cachedAccessories from accessories directory.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fungilation** [comment]
Nope, same thing.

**Comment by cubilon** [comment]
I'm running out of options but the one to restore your iOS devices.

**Comment by dendeps** [comment]
Same problem. Can't find accessory on iOS 11.4. Still no solution on this?

**Comment by theo-69** [comment]
Its working with no problem here.

**Comment by charlesmkelley** [comment]
I was running into this issue, too, on 11.4 I recently upgraded to test iOS 12 beta 2 as well and it's still happening there as well. Have tried all the steps herein and nada.

**Comment by chriskmn** [comment]
do you see any "strange" behaviour when you start "journalctl -f -u homebridge" ? 

I am using homebridge in combination with FHEM and since iOS 11.4 there seems to be some issues with homebridge and siri and "connection lost" in FHEM. I still not know the reason for it :-( Updates between FHEM and homebridge don't work reliable and so on.

**Comment by gee4vee** [comment]
Stopped working for me as well after updating to latest Homebridge and updating to Node.js 8.x. Followed all the steps multiple times.

**Comment by chriskmn** [comment]
I downgraded to 4.43 and it works again. Using NPM 6.1.0 and nodejs 10.5.0.
