### ISSUE TITLE
homebridge logger enhancements

### ISSUE THREAD

**Issue by ebaauw** [nfarina/homebridge#1882]
### Current Behavior
I love the coloured log and error output of homebridge.  However, I'm typically running homebridge through `systemctl` on my Raspberry Pi and through `launchctl` on my mac server.  As these kind of setups redirect output to a file or to syslog, the colours get lost.  Also, as syslog already provides a timestamp, the timestamp output by homebridge seems redundant in that case.

### Suggested Behavior
I would like to be able to force colours in the output, regardless whether it's connected to a terminal, very much like homebridge-config-ui-x does.  I've been playing around with `chalk` and it seems that setting `chalk.enabled` to `true` and `chalk.level`  to `1` will do the trick.  When checking syslog with `journalctl -a`, the colours are displayed correctly.

I would like to be able to suppress the timestamps created by homebridge.

I don't think it's feasible for homebridge to detect how it's been launched, so I think the best way to achieve this is to introduce two additional command line options to homebridge: one to force colours, and one to suppress timestamps.

What are your views on this?  If you think this makes sense, I'll be happy to prepare a PR for this.

**Comment by NorthernMan54** [comment]
Sounds good

**Comment by NebzHB** [comment]
in the same idea, that would be nice to have a -no-qrcode parameter to hide the qr code in the logs
