### ISSUE TITLE
Since I upgraded the AppleTV tvOS homebridge doens't speek with Homekit at all

### ISSUE THREAD

**Issue by fchiari** [nfarina/homebridge#1883]
Hello everybody,
I'm new on this forum.
I installed in December '17 my Homebridge system. I modified some plugins and I configured 59 different accessories. Everithing was working fine until few days agowhen I updated my Apple TV. After that, all my accessories were not responding any more.
I tried several different options to have the system running again but with so success at all.

**The last I did is:**
A) Started again from scratch with my Raspberry PI 3 (latest version of Raspbian)
B) Installed the latest versions of everything, (eg. node, Homebridge, homebridge dependencies, ...)
C) I reset my Apple TV, disconnected my iphone/homekit from cloud and restored the network configuration
D) I deleted accessory and persistent folders of homebridge
E) I Changed Username, port and PIN
These are the softwaare versions I’m using:
   Apple TV tvOS 11.4 (15L577)
   iPhone 6 and 6s IOS 11.4 (15F79)
   Raspberry PI 3 PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)", NAME="Raspbian GNU/Linux"
        VERSION_ID="9", VERSION="9 (stretch)"
   node version: v8.11.2
   homebridge version: 0.4.42

**Result:**
Homebridge looks to work fine;
No error or waring in the homebridge log file at all, also using debug.
Homekit sees Homebridge in the Home app but it is not able to connect to it.
Attached: config.json used, homebridge.log, homebridge.err, some scrrenshots of the error received (in italian :( ).
I don’t see solution to my problem. May someone help me?
Many thanks in advance for your help.

[config.json.txt](https://github.com/nfarina/homebridge/files/2067026/config.json.txt)
[homebridge.log.txt](https://github.com/nfarina/homebridge/files/2067027/homebridge.log.txt)
[homebridge.err.txt](https://github.com/nfarina/homebridge/files/2067029/homebridge.err.txt)

![img_0255](https://user-images.githubusercontent.com/39841131/40901100-ed0f6e2e-67ce-11e8-8208-774d1f0b8f83.PNG)
![img_0256](https://user-images.githubusercontent.com/39841131/40901106-f3d6b94c-67ce-11e8-8d07-09235e99318b.PNG)
![img_0257](https://user-images.githubusercontent.com/39841131/40901109-f9b49438-67ce-11e8-8995-830cbe213f10.PNG)

**Comment by cubilon** [comment]
try changing "username" and "pin" fields.

**Comment by fchiari** [comment]
I tried to make it already several times but with no succes :(

**Comment by cubilon** [comment]
hmm
already tried reinstalling your iOS device(s)?

**Comment by cubilon** [comment]
just restore them using the full backup on itunes, way faster.

**Comment by ebaauw** [comment]
Before messing up you iOS devices, did you try running homebridge with no other accessories?  Your symptoms would suggest one of the accessories is showing an illegal characteristic value, which would be rejected by HomeKit.

**Comment by fchiari** [comment]
I used homebridge smoothly since six months ago. Nevertheless I also tried to reinstall from scratch my mobile and now ...... when I'm starting home anfter to be connected to icloud it starts to load accessories and scenes but I don't know really what. It should be totally clean.
Tomorrow I will try to contact Apple to clean my configuration, hopefully.
I'm really becaming crazy.
I will let you know.

**Comment by fchiari** [comment]
Hello, I did the following test:
1. I removed all the accessory from the config.json;
2. I removed all the plugin from the node_modules folder
3. I changed username and pin
4. I used another iphone installed on a different icloud (the phone of my friend) where home was never installed
5. The iphone has IOS 11.3.1
Same result, home see homebridge but it is not able to connect with it.
What can I do? In debug mode homebridge is not giving any further information.
Thanks for your support

**Comment by cubilon** [comment]
a network problem, maybe?

**Comment by ebaauw** [comment]
homebridge is shown as available device, so the iOS device sees the MDNS (Bonjour) announcement.  Using `DEBUG=* homebridge -D` you should be able to tell from the debug output whether the iOS device connects to the homebridge server.

**Comment by fchiari** [comment]
how can I read the log of the error?
I'm using "journalctl -f -au homebridge". Is this right?
Using this command I don't see any message in the log

**Comment by fchiari** [comment]
In addition I discovered that, trying to connect to homebridge with a telnet client I received the messages in the log file listed below. This means that Home is not trying at all any connection to homebridge, at least to the selected port.

giu 05 14:50:17 homebridge homebridge[10655]: Tue, 05 Jun 2018 12:50:17 GMT Even                          tedHTTPServer [::ffff:192.168.0.236] New connection from client
giu 05 14:50:17 homebridge homebridge[10655]: Tue, 05 Jun 2018 12:50:17 GMT Even                          tedHTTPServer [::ffff:192.168.0.236] HTTP server listening on port 38877
giu 05 14:50:22 homebridge homebridge[10655]: Tue, 05 Jun 2018 12:50:22 GMT Even                          tedHTTPServer [::ffff:192.168.0.236] HTTP connection was closed
giu 05 14:50:22 homebridge homebridge[10655]: Tue, 05 Jun 2018 12:50:22 GMT Even                          tedHTTPServer [::ffff:192.168.0.236] HTTP server was closed
giu 05 14:50:22 homebridge homebridge[10655]: Tue, 05 Jun 2018 12:50:22 GMT Even                          tedHTTPServer [::ffff:192.168.0.236] Client connection closed

**Comment by ebaauw** [comment]
Ok, using a Bonjour viewer or the `dns_sd` command, can you check that the MDNS announcement uses an ip address that is reachable by your iOS devices?  Does homebridge run on a system with multiple network interfaces?

**Comment by ebaauw** [comment]
On Raspberry:
```
$ sudo apt install avahi-tools
$ avahi-browse -r _hap._tcp.
```

**Comment by fchiari** [comment]
Hello everybody. SOLVED!!!!!!!!!!!!!!!!!!!!!!!!!!!
Thanks of your suggestions, including the last one (BTW it was apt install avahi-utils), Using these tools, I started to suspect network issues (as already suggested). I reboot the fiber optic modem and magically everithing is now working again. To many variables to keep under control.
At least now I have everything clean, correct and worning message free. Everithing up to date.
Conclusion is that withIOS 11.4 and Apple TV 11.4 the system works fine.

**Comment by fchiari** [comment]
Many thanks to @ebaauw and to @cubilon

**Comment by cubilon** [comment]
u welcome. happy u solved!

**Comment by ebaauw** [comment]
> BTW it was apt install avahi-utils

My bad.  I updated my comment for future reference.  Glad it now works.
