### ISSUE TITLE
How to implement Timer and Counter?

### ISSUE THREAD

**Issue by ctschach** [nfarina/homebridge#1888]
I need your help. What would be the right ServiceTypes to implement the "Last Open Timer" and the "Times Opened" counter?

![eve_door___window___evehome_com](https://user-images.githubusercontent.com/8994357/41107831-68cba234-6a73-11e8-9750-07da9c422ce4.jpg)

**Comment by simont77** [comment]
These are special Elgato charactistics. Have a look at fakegato wiki https://github.com/simont77/fakegato-history/wiki/Services-and-characteristics-for-Elgato-Eve-devices and the library from ebaauw https://github.com/ebaauw/homebridge-lib/blob/master/lib/EveHomeKitTypes.js

**Comment by ctschach** [comment]
Thanks and sorry for the late reply...
