### ISSUE TITLE
Plugin not responding over 4G

### ISSUE THREAD

**Issue by alucarddelta** [nfarina/homebridge#1891]
I have been using the Garadget plugin for a while, but a few months ago I noticed that my automation stopped working, shows as disabled.. After a little digging I also noticed that while outside of my home network, such as 4g or on a friends LAN, the device shows as "not responding". I have tried an update of both homebridge and the plugin as well as a clean install.

### Expected/Current Behavior
Below if an output of a reboot and action of the plugin. Between the reboot completion and the output of the "test" was a test over 4g. No output appeared, only over the wifi. The 4g output should be identical.

```
Jun 12 20:35:38 MasterServer2 homebridge[13657]: [12/6/2018, 8:35:38 PM] Homebridge is running on port 51826.
Jun 12 20:36:30 MasterServer2 homebridge[13657]: [12/6/2018, 8:36:30 PM] [Main Garage Door] Getting current state...
Jun 12 20:36:30 MasterServer2 homebridge[13657]: [12/6/2018, 8:36:30 PM] [Main Garage Door] Get ObstructionDetected...
Jun 12 20:36:30 MasterServer2 homebridge[13657]: [12/6/2018, 8:36:30 PM] [Main Garage Door] Getting current state...
Jun 12 20:36:31 MasterServer2 homebridge[13657]: [12/6/2018, 8:36:31 PM] [Main Garage Door] Door state is closed
Jun 12 20:36:31 MasterServer2 homebridge[13657]: [12/6/2018, 8:36:31 PM] [Main Garage Door] Door state is closed
Jun 12 20:36:32 MasterServer2 homebridge[13657]: [12/6/2018, 8:36:32 PM] [Main Garage Door] Access Key good...
```

### Versions

- **Homebridge**: `homebridge -V
0.4.43`
- **Node**:       `node --version
v4.3.2`
- **OS**:        Ubuntu VM on KVM/Unriad - 16.04.4 LTS - Auto starts using systemctl

### Configuration
``` {
"bridge": {
        "name": "Alucards Homebridge",
        "username": "####",
        "port": 51826,
        "pin": "####"
    },

"description": "Garadget as an accessory.",
"accessories": [
    {
        "accessory": "Garadget",
        "name": "Main Garage Door",
        "cloudURL": "https://api.particle.io/v1/devices/",
        "deviceID": "######",
        "access_token": "######",
        "bypass": "0",
        "args": "{STATE}"
    }
],
"platforms": [
    {
      #########
    }
  ]
}
```

**Comment by alucarddelta** [comment]
Link to issue report on the plugin git
[]https://github.com/xNinjasx/homebridge-garadget/issues/2

**Comment by Ti-Bo** [comment]
Same issue with home bridge-fibaro-hc2.
