### ISSUE TITLE
Not using dbus anymore?

### ISSUE THREAD

**Issue by cmsj** [nfarina/homebridge#1893]
### Expected Behavior
Previously homebridge would use dbus to talk to Avahi to publish its resources. I've not upgraded homebridge for a long time

### Current Behavior
It looks rather like homebridge (or its node dependencies) is spinning up a whole mDNS stack and is fighting with Avahi to listen on UDP:5353

### Steps to Reproduce (for bugs)
strace -Ff homebridge 2>&1 | grep dbus

### Versions
root@gnubert:/# homebridge --version
0.4.43
root@gnubert:/# node --version
v10.4.1

OS version: debian jessie via the `node:latest` docker images

**Comment by cmsj** [comment]
So I had avahi configured with `disallow-other-stacks=yes` which prevented Homebridge from even being able to bind to the socket, but with that removed, I'm just not seeing Homebridge from my iOS devices.

It's running in a container, which complicates things, but it has `--network=host` so it's interacting with the same network stack.

**Comment by KhaosT** [comment]
If you use bonjour browser on the iOS device, do you see anything?

**Comment by cmsj** [comment]
Oddly, I see "Apple Home Accessory Service (homekit)" with my homepod and appletv, but I don't see any of my native homekit devices (e.g. Philips Hue bridge) that are working fine. Perhaps the scanner I'm using is not showing everything.

Is there a `dns-sd` command that can show all of the devices?

**Comment by cmsj** [comment]
aha, `dns-sd -B _hap._tcp` which only finds the Hue, not HomeBridge. I'll poke around some more at the networking setup and make sure that the container is doing what I think it's doing.

**Comment by cmsj** [comment]
Ok, it's definitely something about the container - if I bring Homebridge up with the same config on a host, the accessories appear fine. Thanks for the pointers!

**Comment by cmsj** [comment]
It's bound to 0.0.0.0:5353, but it does choose a specific interface to bind to: https://github.com/mafintosh/multicast-dns/blob/9177a6024d10bad5d993a171b94a473640441643/index.js#L141

**Comment by NorthernMan54** [comment]
What version of node are you using?  I had a similar issue with the latest homebridge version and resolved it by updating my version 7 of nodejs to 8

**Comment by cmsj** [comment]
10.4.1

if I hack that `defaultInterface()` function to return the IP of my `bridge0` the devices appear correctly on my LAN.

I'm not currently able to think of any clever solutions here - there's no way to tell which network interface is "correct" from the code, so would it be possible to expose an option in node_mdns and homekit, to set the IP for the interface to bind to, which can be passed to `multicast-dns` as `opts.interface`?

**Comment by cmsj** [comment]
Not sure if you want to leave this open or not, but I've been able to workaround this by forcibly attaching the container to the correct host bridge interface.

**Comment by KhaosT** [comment]
Do you think having an option to provide an interface would help? Or is this really specific to this particular case?

**Comment by NorthernMan54** [comment]
My 2 cents on this

When I was investigating a similar issue in my setup, I found that when using nodejs 8.6.0+ bonjour/multicast-dns was broadcasting on all active interfaces.  So I’m thinking this is more related to the container config, rather than an actual issue.

**Comment by cmsj** [comment]
I think an option would be useful because multicast-dns just picks the first interface it finds in whatever order os.networkInterfaces() provides them.

I ran into it because my container was finding the docker0 bridge before my LAN bridge, which I can imagine happening in other interesting HomeLab networking setups.

**Comment by typcn** [comment]
multicast-dns is totally not working on my router( with complex network config, > 10+ interfaces, 5+vlans), using avahi-browse on localhost can't see the homebridge service
