### ISSUE TITLE
iOS 11.4 problem 

### ISSUE THREAD

**Issue by toshibochan** [nfarina/homebridge#1895]
After update to iOS 11.4 some divices keep turning ON or OFF when open home app or when do scenes. Anyone having this problem?

**Comment by PrzemyslawKlys** [comment]
I've setup new instance of homebridge with newest ios 11.4 and had no problems.

**Comment by toshibochan** [comment]
Hi @PrzemylawKlys you mean you reset You home and did from scratch?

**Comment by PrzemyslawKlys** [comment]
I mean I am new to homebridge and had no trouble to set it up on iOS 11.4

**Comment by chriskmn** [comment]
Hi, I experience the same problem. I am using FHEM and linked "dummys" from FHEM to homebride. The strange thing is, that some of those dummys are working fine and one ore two get sitched on "by itself". The dummys are set up the same way (devicetype switch etc).

The only thing I could find out is, that it might be related to siri....
