### ISSUE TITLE
config.json

### ISSUE THREAD

**Issue by oyamau** [nfarina/homebridge#1899]
Whenever I try to run my kit with TP-Link defaults (because I have a TP-Link plug) and it doesn't work. Please help!!

(code below I think 🖌 )

{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",
    "accessories": [ ],
    "platforms": [{
    "platform": "Hs100",
    "name": "TPLink"
]}

**Comment by roe1974** [comment]
Try:

{
"bridge": {
"name": "Homebridge",
"username": "CC:22:3D:E3:CE:30",
"port": 51826,
"pin": "031-45-154"
},
"accessories": [ ],
"platforms": [
{
"platform": "Hs100"
}
]
}
