### ISSUE TITLE
Automation screen in iOS home app just shows default

### ISSUE THREAD

**Issue by ryanseddon** [nfarina/homebridge#1902]
Home bridge works great and I have it running on my raspberry pi the home app works and is showing my thermostat and plug but when I go to the automation screen it gives me the default screen

### Expected Behavior
I should be able to add automation

### Current Behavior
it shows this screen 
![](https://i.imgur.com/Mq8RRZP.png)

### Versions

- **Homebridge**: `0.4.43`
- **Node**:       `8.11.3`
- **OS**:         `Raspbian GNU/Linux 9 (stretch)`

### Configuration

```json

```

### Homebridge Log / Command Output

```

```

**Comment by ebaauw** [comment]
As the screen says, you need a home hub for automations.  See also https://support.apple.com/en-us/HT207057.  There’s nothing homebridge can do to change that.

**Comment by ryanseddon** [comment]
![](http://gifimage.net/wp-content/uploads/2017/08/homer-bushes-gif-21.gif)
