### ISSUE TITLE
2-way communication?

### ISSUE THREAD

**Issue by JonyBCN** [nfarina/homebridge#1904]
I do not know if this is so, so apologize in advance.
  I do not know if the communication is 2 ways. I'm a Domoticz user and use Homebridge to interact with Siri.
  But, in the case of buying a BT device compatible with Homekit, domoticz would "see" it in some way or is communication in one direction?

**Comment by jarvismeier** [comment]
Communication is one way.  I have the same problem with smartthings.  To get around it I created virtual devices in smartthings and use HomeKit automation to turn on and off the virtual devices.

**Comment by JonyBCN** [comment]
Well, that hurts
creating virtual devices is a good compromise solution, but I think it's only valid with on / off switches
with more complex devices such as thermostats the thing can become tedious and problematic
