### ISSUE TITLE
Callback before homebridge exits

### ISSUE THREAD

**Issue by ebaauw** [nfarina/homebridge#1905]
[I created a new issue for the same topic, because I cannot re-open #984, which has been closed by the stale bot.]

As mentioned in #984, I've created an alternative plug-in for Sonos, https://github.com/ebaauw/homebridge-zp, that, like the Sonos app, subscribes to events from the speakers, to update volume and current track in real time. I would like to cancel these subscriptions before homebridge exits.

I need homebridge support to know when homebridge is about to exit:
- Trapping `process.on('exit', ...)` doesn't allow any more asynchronous I/O; and
- Trapping `process.on('SIGINT', ...)` seems to work on NodeJS v8, but in earlier versions it would overwrite homebridge's signal handling.

The implementation in homebridge is actually quite easy:
- Increase the timeout to `process.exit()` in `cli.js` to give plugins some more time to do their cleanup;
- After setting the timeout, issue `server._api.emit('shutdown')`.

@nfarina @KhaosT would this be the way to go? Shall I create a PR for this change?

**Comment by KhaosT** [comment]
Sounds good to me.

**Comment by nsayer** [comment]
Stupid question: how does a plugin writer register a callback for this shutdown event?

**Comment by NorthernMan54** [comment]
Added this to the docs - https://developers.homebridge.io/#/api/reference#apion

Follows same pattern as the didFinishLaunching event
