### ISSUE TITLE
Cannot install homebridge on Raspbian Stretch

### ISSUE THREAD

**Issue by giase82** [nfarina/homebridge#1909]
Hi All, 

I've got a strange issue, and wonder if somebody can help here.

I recently updated from Jessie to stretch on my Raspberry Pi 3. I now tried to install homebridge, but this one fails:

`sudo npm install -g --unsafe-perm homebridge
WARN engine curve25519-n@1.4.0: wanted: {"node":">=4.8.0"} (current: {"node":"4.3.2","npm":"2.14.12"})
-
> curve25519-n@1.4.0 install /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/curve25519-n
> node-gyp rebuild

make: Verzeichnis „/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/curve25519-n/build“ wird betreten
  CXX(target) Release/obj.target/curve/node_curve.o
In file included from /usr/include/string.h:25:0,
                 from ../node_curve.cc:1:
/usr/include/features.h:364:25: fatal error: sys/cdefs.h: Datei oder Verzeichnis nicht gefunden
 #  include <sys/cdefs.h>
                         ^
compilation terminated.`

It seems my build-toolchain is somehow broken. Has anybody seen something like this?

Thanks,
//giase

**Comment by Druuka** [comment]
If I'm reading the error correctly it looks like your versions of node and npm are old compared to what home bridge needs. I would suggest updating node and trying again.  I'm currently running on Raspberian Stretch.

**Comment by Apollon77** [comment]
And it seems that libc6 is somehow missing.  Google around for the missing .h file and try to find something there.
