### ISSUE TITLE
I already installed homebridge on my router, but it still doesn't work.

### ISSUE THREAD

**Issue by nccer** [nfarina/homebridge#1915]
I installed homebridge on wrt1900ac,and it gives the picture below.
<img width="557" alt="qq20180625-224857 2x" src="https://user-images.githubusercontent.com/9612358/41857381-fba31f88-78c9-11e8-8003-b4892ade266e.png">

### Expected Behavior

The ios device detected homebridge and connected at it.
### Current Behavior

I scaned QRcode,but nothing happen until timeout.
### Versions

- **Homebridge**:  0.4.44
- **Node**:       v4.4.5
- **OS**:         wrt1900acv2 lede 17.01.4
-**iOS**:        11.4
### Configuration

```json
{
"bridge": {
"name": "Homebridge",
"username": "CC:22:3D:E3:CE:30",
"port": 51826,
"pin": "121-81-983",
"manufacturer": "@nfarina",
"model": "Homebridge",
"serialNumber": "0.4.20"
}
}
```

### Homebridge Log / Command Output

```
Nothing.
```

**Comment by nccer** [comment]
Hey everyone.I installed another homebridge on my Mac,it works well.my phone can detect the homebridge immediately.But It still doesn't work on my router.I thought it may be something wrong with my router's OS.So I reinstalled  the lede . I only extroot and install homebridge on it.Still don't work.
How can I debug the homebridge.Does someone know what's wrong with my router?

**Comment by Lovingyourwork** [comment]
I'm having the same issue, built an old version of Homebridge ARMv7 from the oznu/homebridge image in docker. Used to work like a charm, but now doesn't register any services ( either with avahi or without ) and I can't get it to work at all. Built fresh from arm-debain, node 10 Homebridge 4.4 and still no dice, which is a shame as it was ace ;-(

**Comment by niktad** [comment]
i install homebridge on a Rasp Pi 3 and have the SAME PROBLEM !!! HELP !!! ;(
