### ISSUE TITLE
cannot integrate home bridge and blynk, unable to control device via homebridge. 

### ISSUE THREAD

**Issue by hamzam999** [nfarina/homebridge#1916]
![screen shot 2018-06-26 at 4 37 32 am](https://user-images.githubusercontent.com/40526398/41880306-ef67a938-78fa-11e8-9399-2044b33dda35.png)
![screen shot 2018-06-26 at 4 41 37 am](https://user-images.githubusercontent.com/40526398/41880346-3ad4f1b4-78fb-11e8-82b2-78b577b0c405.png)

As you can see the value of switches doesnot remain constant and i also cannot control my wifiswitch.
the wifiswitch is working fine with blynk app using both cloud and local server.

**Comment by hamzam999** [comment]
{
        "bridge": {
                "name": "hamza's Homebridge",
                "username": "C8:28:EB:14:31:37",
                "port": 51826,
                "pin": "033-45-158"
        },




        "platforms": [

                {
    "platform": "Server",
    "port"    : 8765,
    "name"    : "Homebridge Server",
    "log"     : "<PATH_TO_YOUR_LOG_FILE>",
    "restart" : "<sudo reboot>"
        },

                        {
                        "platform": "Blynk",
                        "name": "Blynk",
                        "server": "http://192.168.2.3",
                        "httpsPort": "8080",
                        "token": "29fd805a052044c4975bdaf0a8351714",
                        "dashboardName": "Blynk Switches",


                        "accessories": [{
                                        "name": "Switch 1",
                                        "widget": "Switch",
                                        "mode":"SWITCH",
                                        "caption": "Lamp 1",
                                        "pin": "D1"
                                },
                                {
                                        "name": "Switch 2",
                                        "widget": "Switch",
                                        "mode":"SWITCH",
                                        "caption": "lamp 2",
                                        "pin": "D2"
                                },
                                {
                                        "name": "Switch 3",
                                        "widget": "Switch",
                                        "mode":"SWITCH",
                                        "caption": "lamp 3",
                                        "pin": "D3"
				 },
				 {
                                        "name": "Switch 4",
                                        "widget": "Switch",
                                        "mode":"SWITCH",
                                        "caption": "lamp 4",
                                        "pin": "D4"
                                }
                        ]

                }
        ],
        "accessories": []
                                }

//this is my config.json file

**Comment by ilcato** [comment]
See the release notes and usage notes:

_Works on both cloud server and local server: for cloud server the Blynk App must be running in order to receive automatic update of the pin values (setting pins works also without the app runing); for local server put "allow.reading.widget.without.active.app=true" in server.properties in order to be able to receive automatic update of the pin values._
