### ISSUE TITLE
Homebridge is not working with my home router

### ISSUE THREAD

**Issue by huguitodb** [nfarina/homebridge#1918]
Hi, I have homebridge up and running on my raspberry pi. I set it up only with the dummy lightswitch plugin. When pairing it to my iphone it wont detect homebridge on my ZTE F660 Router. 
Wierdly, on my office router it works like a charm. Any Suggestions?

**Comment by jarvismeier** [comment]
Your router isn’t forwarding mDNS broadcasts properly.  You might need to enable igmp snooping/proxy.  It’s a router issue.

**Comment by justme-1968** [comment]
or for that matter disable it as some routers just get it wrong.

or reboot the router

or get a new one as some can't handle broadcasts correctly at all.

**Comment by huguitodb** [comment]
Hi, thanks for the feedback. I tried enabling and disabling both igmp proxy and snooping with no success, any other suggestions?

**Comment by jarvismeier** [comment]
Contact whomever supports your router for further diagnosis.  It’s possible the router blocks broadcasts from LAN to WLAN.

**Comment by jarvismeier** [comment]
Yes.  Broadcast traffic... more specifically mDNS/bonjour is being filtered.  If your router is supplied by your ISP then talk to them to get it properly configured.
