### ISSUE TITLE
uninstalled homebridge, now I can't get it to install again

### ISSUE THREAD

**Issue by mreassassin** [nfarina/homebridge#1919]
I uninstalled (had to manually delete some folders because I couldn't get a clean uninstall/remove) homebridge because it was giving me different results when running 'homebridge' vs 'sudo homebridge'.  now I can't get it to install again.

### Versions

pi@retropie:~ $ homebridge --version
-bash: homebridge: command not found
pi@retropie:~ $ node -v
v10.5.0
- **OS**:         Linux 4.9.35-v7+ armv7l GNU/Linux (raspberry pi 3) 

any help greatly appreciated.

thanks!

**Comment by lights0123** [comment]
What happens when you try to reinstall?

**Comment by mreassassin** [comment]
I ended up reformatting the sd card and was able to get it all back up and running. Thanks!

**Comment by ESLHemantSangle** [comment]
Hello,
@mreassassin how to uninstall homebridge can you tell me the steps?
Thanks

**Comment by KhaosT** [comment]
`npm uninstall -g homebridge`

**Comment by ESLHemantSangle** [comment]
@KhaosT Thank you very much
