### ISSUE TITLE
Cannot install libavahi-compat-libdnssd-dev

### ISSUE THREAD

**Issue by LIHHAO** [nfarina/homebridge#1921]
### Current Behavior

when I input 
```sudo apt-get install libavahi-compat-libdnssd-dev```

It shows error:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libavahi-compat-libdnssd-dev : Depends: libavahi-client-dev but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

### Versions

- **Homebridge**: `homebridge --version`
- **Node**:       `node --v8.11.3`
- **OS**:      Linux raspberrypi 4.14.50-v7+ #1122 SMP Tue Jun 19 12:26:26 BST 2018 armv7l GNU/Linux

and `g++ -v` show that:
`gcc version 6.3.0 20170516 (Raspbian 6.3.0-18+rpi1+deb9u1) `

**Comment by mloeschner** [comment]
Try to install `libavahi-client-dev` to met the dependencies. If that doesn't work, you should figure out why the dependency `libavahi-client-dev` cannot be installed. A good way is to use `aptitude` instead of `apt-get` because it offers ways to resolve the situation.

**Comment by dudusandi** [comment]
Try follow this 

https://github.com/nfarina/homebridge/wiki/Easy-Install-Raspberry-PI-(With-Start-with-boot)

**Comment by huangyafei** [comment]
@LIHHAO Have you found a solution?

**Comment by LIHHAO** [comment]
@huangyafei 
Apologize for my poor English.
It's caused by Internet connection error. I used VPN then it  installed.

**Comment by huangyafei** [comment]
@LIHHAO OH MY GFW...

THX!
