### ISSUE TITLE
Error: Service name is already in use on the network

### ISSUE THREAD

**Issue by stevemac00** [nfarina/homebridge#1923]
node --version => v10.5.0
homebridge --version =>0.4.44
avahi-daemon =>avahi-daemon 0.6.31
pfSense is also running avahi-daemon 0.6.31 to reflect across multiple subnets

Usage:
I'm working on a plugin and stop/starting Homebridge from CLI on a pi3b.
/usr/bin/homebridge --debug --plugin-path /home/homebridge/npm/
Everything works as it should except:

Problem:
Every time I stop with SIGINT and restart, I get:
`### events.js:167
      throw er; // Unhandled 'error' event
      ^`
`Error: Service name is already in use on the network
    at Registry._onProbeComplete (/usr/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Registry.js:106:27)`

This never happened on my old installation and I can't figure out what's changed. If I stop/start avahi-daemon on pfSense it will work again. So, this may not be a problem with Homebridge but that's the only time it manifests itself.

**Comment by shad0wca7** [comment]
I have this same issue (I'm using hass.io) - same setup as well (pfsense and avahi). Your fix 'fixes' things but Homebridge should be more resilient (e.g. other things will just append a (1..n) onto their name to avoid this issue)..

**Comment by ykorzikowski** [comment]
Make sure only one avahi is running on your network. I'm using OpenWRT and had 2 instances running on my network.

**Comment by SiGmAX666** [comment]
Thanks for that wise comment @ykorzikowski , that was my issue too.

**Comment by attinderseesdragons** [comment]
I am running into the same issue. I

**Comment by stevemac00** [comment]
Open avahi config file and set cache size to zero which will disable the cache.

**Comment by attinderseesdragons** [comment]
I am still getting same error.
I even uninstalled libavahi-compat-libdnssd-dev
