### ISSUE TITLE
homebridge not listed in avahi-browse

### ISSUE THREAD

**Issue by dennis82m** [nfarina/homebridge#1925]
I did a clean install and setup homebridge. Worked well.
After a while "no response" showed up on all devices. 
Removed the homebridge from home app. Changed pin and user. Can't be found anymore.

systemctl status homebridge
returns runnin

journalctl -u homebridge
does not show any faults

running netstat -na | grep 51826
first returned 
tcp6        0      0 0.0.0.0:51826           0.0.0.0:*               LISTEN

after adding ipv6.disabled to the bootline file it shows
tcp        0      0 0.0.0.0:51826           0.0.0.0:*               LISTEN    

avahi-browse returns
+  wlan0 IPv4 raspberrypi                                   Apple File Sharing   local

seems like homebridge is not "communication" with avahi ... 

EDIT:
doing a journalctl -u avahi-daemon reveals
*** WARNING: Detected another IPv4 mDNS stack running on this host. This makes mDNS unreliable and is...

set disallow-other-stacks in avahi-daemon.conf after force kill and restarting avahi-daemon, avahi-browse showed homebridge

reboot
homebridge is gone again
journalctl -u homebridge reveals
EADDRINUSE 0.0.0.0:5353

is there any way to get homebridge working?!

**Comment by Lovingyourwork** [comment]
I have exactly the same issue. Using the latest hombridge build, clean install on Armhf / (Raspberry Pi mk.3 ish) in docker, no avahi or mDNS service advertised with no errors.

Hope this gets resolved, was really liking Homebridge!

**Comment by OABsoftware** [comment]
Same for me...

**Comment by Trippersgarage** [comment]
Been getting the “no response” issue on my setup as well and I’m suspecting the same issue; no mdns service being advertised as far as I can tell. Ideas anyone?
