### ISSUE TITLE
Homebridge cannot connect on raspberry pi when ethernet & wifi connected

### ISSUE THREAD

**Issue by willyzha** [nfarina/homebridge#1928]
### Expected Behavior
I'm running homebridge on a raspberry pi 3 with a wifi bridge to ethernet. If I leave my ethernet port disconnected and only have wifi connected homebridge runs fine and I can add homebridge perfectly from homekit. In my previous install I had this setup working fine with a network bridge and homebridge on the raspberry pi.

### Current Behavior
After a clean install of Rasbian and homebridge if I connect a device to the ethernet port I am not able add homebridge from my device. If I disconnect the device on the ethernet port and I restart my homebridge instance I can detect homebridge from homekit. I also noticed that if I start homebridge before connecting the ethernet device homebridge can still communicate with homekit if I connect the ethernet device afterwards it will work for a few seconds before being unable to connect.

** Update **

I've since tested a done a clean install of rasbian without any network bridge setup. And it seems like the issue still occurs as long as I have a device connected to eth0. I suspect somehow once something is plugged into eth0 homebridge does not use the correct network adaptor somehow?

### Steps to Reproduce (for bugs)
1. Setup wifi to ethernet bridge on raspberry pi
2. Connect a device over ethernet
3. Start homebridge

### Versions

- **Homebridge**: 0.4.44
- **Node**:       v8.11.3
- **OS**:         Raspbian stretch Linux raspberrypi 4.14.52-v7+ #1123 SMP Wed Jun 27 17:35:49 BST 2018 armv7l GNU/Linux

### Configuration
Sample configuration with a single dummy switch for testing
```json
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    
    "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",

    "accessories": [
        {
          "accessory": "DummySwitch",
          "name": "My Switch 1"
        }   
    ],

    "platforms": [
    ]
}
```

### Homebridge Log / Command Output
There is no output after the standard homebridge start messages when ethernet device is connected

**Comment by willyzha** [comment]
Update. So narrowed down the problem. Something changed between homebridge version 0.4.38 and 0.4.39 causes an issue seen here. Looking at the commit history the only commit that I can see change anything is "Fix Node v10 support" made by @KhaosT on May 5th.

I don't quite understand what this commit does but maybe someone else can explain why the changes in that commit would cause this issue?

**Comment by tobielf** [comment]
I had the same issue recently, but I fixed it by upgrading the both Homebridge and HAP-NodeJS to the latest version.
