### ISSUE TITLE
Can't add accessory to Home app after updating my device to iOS 11.4.1

### ISSUE THREAD

**Issue by xiaohk** [nfarina/homebridge#1935]
### Current Behavior
Homebridge was working fine when my phone was on iOS 11.4, but all the accessories became unresponsible after updating to iOS 11.4.1.

### Have Tried
1. Deleted all accessories and tried to re-add them
2. Changed `username` and `pin` in `config.json`
3. Reinstalled Homebridge and step 2
4. Downgraded Homebridge to 0.4.33 and step 2

All above failed (Home app couldn't find accessories). However, my iPad with iOS 11.4 can reach homebridge all the time.

### Configuration
```json
{
    "bridge": {
        "name": "Homebridge",
        "username": "AA:BB:CC:DD:EE:11",
        "port": 51826,
        "pin": "123-45-111"
    }
}
```

**Comment by niktad** [comment]
Same problem and now i cant even add it...
https://github.com/nfarina/homebridge/issues/1915

**Comment by pierrenicolasr** [comment]
Same here as well. Had one iDevice showing unreachable devices ; I restarted everything (removed cache and persistent folder, changed pin and username)... None of my iDevices (11.4 and 11.4.1) can add homebridge again.

Tried in debug mode following wiki but nothing special shows up in logs, except maybe:
HAP Warning: Characteristic 00000010-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 0000008A-0000-1000-8000-0026BB765291. Adding anyway.

No error - but home is not able to find homebridge anymore. 
Anything I can provide to help finding a solution ?
thanks !

Seems also to be the same as https://github.com/nfarina/homebridge/issues/1937

**Comment by pewtertankard** [comment]
And same for me. All worked fine on my upgraded iOS 11.4.1 devices until I upgraded tvOS on my Apple TV (acting as Home Hub). At that point, all Homebridge devices were unresponsive.

Did full reinstall of Homebridge (running inside FreeNAS 11.1 jail: pkg update and upgrade, npm uninstall and then install of node-gyp, homebridge, homebridge-platform-wemo), changed username and pin.

No errors in the Homebridge log shown. When I try to remove and re-add the unresponsive Homebridge accessory, my iPhone just sits there with the spinning wheel... and then eventually gives up.

Any help at this point would be very welcome.

**Comment by Kimovitzh** [comment]
I can confirm this.

I've got iOS 12 on my iPhone and ATV 4K and can't add the bridge to homekit.

**Comment by pfinnegane** [comment]
Second confirm for iOS 12 dev & ATV.

**Comment by brideone** [comment]
I have the same problem. I even reinstalled macOS, homebridge and HomeKit app.

**Comment by brideone** [comment]
I don't know why but it was something related with my router configuration. I gave wifi connection to my mac from my iPhone and tried to add home bridge and it worked!!! Finally I restarted the router's default configuration and now all works again. Maybe you can try the same.

**Comment by Kimovitzh** [comment]
Restaring my router or my AP’s will not fix this.
My router runs PFsense and my WiFi network is Ubiquity. 
Maybe you have a Netgear router? - https://community.netgear.com/t5/Orbi/OrbiOS-2-1-4-Homekit/td-p/1565698

The problems started with iOS 12.
Since I’ve got a Apple TV 4K I can’t install previous iOS versions and i’m stuck with iOS 12.

What “fixed” it for me was using a old iPad running a old iOS, but that’s not a sustainable solution.

**Comment by openfirmware** [comment]
I started having issues with all the homebridge devices become unavailable via the Home app after updating to iOS 11.4.1 (iPhone 6S). I used control centre to disconnect and reconnect to my wi-fi and the homebridge connection started working again. I have an Asus wi-fi router which may involved.

**Comment by pewtertankard** [comment]
For completeness, I had all sorts of issues with using HomeKit on the latest main release iOS and tvOS. The Apple TV is acting as a Home Hub. What fixed that for me was performing a reset of the Apple TV (had to re-enter quite a few passwords but otherwise pretty seamless).

**Comment by iRayanKhan** [comment]
Do y'all mind checking out issue #1952

**Comment by sbehrends** [comment]
Having same issue running iOS 12. Tried reinstalling, change username, etc. Even tried adding Homebridge in an old iPad

**Comment by fsdsabel** [comment]
I struggled with not being able to readd my devices after I deleted them from home app. Deleted homebridge, reinstalled, debugged, switched versions and so on.
In the end I solved it by just **shutting down my iPad**. I used it as a hub. This may apply to people owning an Apple TV. Switching it off might help.

**Comment by eddyg** [comment]
FWIW, adding:

```
  "mdns": {
    "interface": "192.168.1.14"
  },
```

to `config.json` (where `192.168.1.14` is the IP address for the local interface on the server where Homebridge is running) solved the non-discoverability issue for me.

Before adding the above, `sudo lsof -nPp$(pgrep homebridge)` showed:

```
homebridg  5524 homebridge   11u  IPv4 5058551      0t0     UDP *:5353
```

with the `mdns` stanza, `lsof` shows:

```
homebridg 19539 homebridge   11u  IPv4 5148536      0t0     UDP 192.168.1.14:5353
```
