### ISSUE TITLE
Wich smart plug is supported?

### ISSUE THREAD

**Issue by alessandrocroci** [nfarina/homebridge#1936]
There is any kind of list of smart plug which is supported from homebridge?
on amazon.it I find this low expensive smart plug:
https://www.amazon.it/dp/B079D8Y2VW/
https://www.amazon.it/dp/B07CWQGP9C/
https://www.amazon.it/dp/B07B5WJD45/

i have also found this amazing smart switch:
https://www.amazon.it/dp/B071JB5LXR/

Anyone knows if any of this works on homebridge? there is an example?

thank you
Ciao!

**Comment by maragelis** [comment]
https://www.itead.cc/smart-home.html with https://github.com/arendst/Sonoff-Tasmota cheap and reliable

**Comment by alessandrocroci** [comment]
great! thank you.. 
yesterday i have bought the tp-link hs100 smart plug because I have find this plugin: https://www.npmjs.com/package/homebridge-tplink-smarthome
but I will try to buy also these that you say soon

**Comment by alessandrocroci** [comment]
if anyone has any other suggestions it's welcome

**Comment by alessandrocroci** [comment]
with tp-link hs100 and npm homebridge-tplink-smarthome everything worked in just a few minutes.. Wonderful!

now I was looking for some kind of relay that could be controlled via 8266... do u have any suggestion ?

**Comment by alessandrocroci** [comment]
great! sorry I'm a very newbie at this moment..
i have found this plugin: https://www.npmjs.com/package/homebridge-sonoff-basic-espeasy
I'm in doubt, the soldering etc.. isn't a problem... But i not understand why I have to reprogram it with the ESPEasy... Isn't the sonoff basic ready to use?
Wasn't it enough to make a plugin that identified it for use with homebridge? like the tp-link hs100

**Comment by maragelis** [comment]
Most vendors will not support homekit (license etc) so they build their own apps and services. That's what itead and tp-link do. Someone actually sat down and hacked the tp-link protocol so he can write the plug-in for homebridge. Itead on the other hand doesn't use a protocol that we can just write Plug-in for they use their own, so we have to hack the device, put our own firmware on it so we can write our plugins for homebridge. That what companies are not doing we are doing it for them.
