### ISSUE TITLE
Interfacing with Arduino ESP8266

### ISSUE THREAD

**Issue by djgalati** [nfarina/homebridge#1939]
Hello, I'm extremely new to the homebridge system and controlling accessories through it. I'm currently trying to interface my Raspberry Pi (running the homebridge server) with an Arduino with a ESP 8266 Microcontroller. I've tried setting up the Arduino as a server and as a client but im not sure which is the proper way to do it. I've attached my Config.json file below. Essentially I just need to know how to properly setup the Arduino code to be compatible with the http plugin also not sure if it would be easier to use a different plugin. . Any help is much appreciated! 

### Versions

- Homebridge: 0.4.44
- Node: 4.0.0
- OS: Rapsberry Pi 2 w/ raspian stretch

### Configuration

```json
{
   "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "123-45-678"
   },
   "description": "This is an example configuration for the Everything Homebridge plugin",
   "platforms":[],
   "accessories": [
        {
                "accessory": "HttpAccessory",
                "service": "Outlet",
                "name": "Left Outlet",
                "apiBaseUrl": "http://192.168.1.84:80/LeftOutlet",
                "apiSuffixUrl": "",
                "forceRefreshDelay": 0
        }
]
}
```

### Update
After looking around more I made use of the Arduino and made a web server from it, now im able to have both of the computers communicate. My current issue is that the homebridge-http-switch plugin wont accept my response from the Arduino server and I cant find any documentation on what the exact response is supposed to look like

**Comment by maragelis** [comment]
Take a look at this firmware for the esp8266 it has everything one needs. https://www.letscontrolit.com/wiki/index.php/ESPEasy
