### ISSUE TITLE
Temperature range of AC

### ISSUE THREAD

**Issue by lmendes28** [nfarina/homebridge#1941]
HomeKit shows me a temperature range from 0º to 30º, so its unresponsive util 18º.  Is it possible to show  only 18º to 25º? (config.json after the image)
![img_6479](https://user-images.githubusercontent.com/41343291/42837189-c04f2d80-89d3-11e8-99f7-7a92c4821cd7.PNG)
I created my config.json for my AC like this: 
{
         	"name": "AC",
	"type": "air-conditioner",
	"data": {
		"off": "3920",
		"temperature25": {
			"pseudo-mode": "cool",
			"data": "2938293"
		},
		"temperature24": {
			"pseudo-mode": "cool",
			"data": "23092"
		},
		"temperature23": {
			"pseudo-mode": "cool",
			"data": "20923"
		},
		"temperature22": {
			"pseudo-mode": "cool",
			"data": "39202"
		},
		"temperature21": {
			"pseudo-mode": "cool",
			"data": "20320-23"
		},
		"temperature20": {
			"pseudo-mode": "cool",
			"data": "3920392"
		},
		"temperature19": {
			"pseudo-mode": "cool",
			"data": "9222323"
		},
		"temperature18": {
			"pseudo-mode": "cool",
			"data": "0239203"
            }
          }
        },

**Comment by gaojie429** [comment]
I have same issue.
But it seem to be specification of Homekit itself.
I think it is because we can set only same range of temperature between all modes.
So we don't have any ways instead of integrate ranges of each mode.
