### ISSUE TITLE
Set fan speed percentage incrementally

### ISSUE THREAD

**Issue by benvallack** [nfarina/homebridge#1942]
I have a fan with IR remote that sets it from 1 to 10 but only using + or - buttons on the remote. Given HomeKit supports the percentage fan speed, is there a way to get it remember the current setting so asking for a percentage knows how many times to fire the + or - commands?

**Comment by lights0123** [comment]
Your plugin could store the current percentage in a variable, and calculate the difference from there. You could also just hit one of the buttons 9 times to make sure that it’s at a known value (hitting - 9 times will make sure that it’s at 1), then increment as needed.

**Comment by benvallack** [comment]
Ah interesting to know that the plugins can do that in theory. I've set it up at the moment to set it to lowest than go back back up for each level. Works quite well actually. Cheers.

**Comment by NorthernMan54** [comment]
Im doing what your asking here, but it is a bit clunky and easily gets out of whack.
