### ISSUE TITLE
Integrating Log level / verbose ?

### ISSUE THREAD

**Issue by chriskmn** [nfarina/homebridge#1943]
Hello folks,

as the homebridge logfile is the biggest one on my raspberry I‘m asking if it is possible to integrate something like a log level definition or verbose.

Or is there anything like that to tell homebridge how to log and to minimize log file size and with that the SD card wear ?

Thanks, Chris

**Comment by theccm** [comment]
this is not a direct answer, but if you look "big picture", you can try to set up overlay FS, I followed this link and it is working great. after that your SD card will be mounted in read only mode. 

https://www.domoticz.com/wiki/Setting_up_overlayFS_on_Raspberry_Pi

**Comment by djrobx** [comment]
Along these lines I think a better logging library that supports rolling log files / size limits would be helpful.   Homebridge has filled my router's drives with logging due to runaway repeating failures a couple times.
