### ISSUE TITLE
getPowerState

### ISSUE THREAD

**Issue by juliensantos87** [nfarina/homebridge#195]
I'm trying to add a new provider for MyHome platform.
It's starting to work but if the state change from somewhere else the state never change and I don't know how to call it and what to return.

for now I have this bind:

    lightbulbService
      .getCharacteristic(Characteristic.On)
      .on('get', this.getPowerState.bind(this))
      .on('set', this.setPowerState.bind(this)); 

when the getPowerState should be triggered what should be return ?

**Comment by justme-1968** [comment]
the get event is emitted if homekit asks for the value
the set event is emitted if the value is changed (by homekit)

if you receive a state change from somewhere else you have to call setValue on the characteristic to push it to homekit (and check in the set event handler that the change came from somewhere else and not from homekit)

check that you call the appropriate callbacks.

**Comment by juliensantos87** [comment]
@justme-1968 so it mean that the app i'm using for homekit (insteon+) is not asking for states?
Or maybe a missed a configuration because on the app, on the light I can see "LightBlub PowerState" to off.
There is something to configure for that?

**Comment by justme-1968** [comment]
i don't know about instead. try if it works with the legato eve ap. this one does ask for state updates and it supports many more devices.

**Comment by juliensantos87** [comment]
@justme-1968 By the way thank you it works.
