### ISSUE TITLE
Hide Password in config.json

### ISSUE THREAD

**Issue by ifunlisted** [nfarina/homebridge#1951]
I'm guessing this is a really simple question and I'm just blind to the answer.... Is there a way to hide passwords in the config.json? Maybe something similar to a secrets.yaml in a yaml situation?

**Comment by iRayanKhan** [comment]
Homebridge needs to read the password from the file so I don't get why you would want to hide it.

**Comment by acolomba** [comment]
+1 A secrets file is just good practice. For instance it would make it safe to version-control the main config file (and whatever additional configurations/scripts for plugins), and be sure to leave passwords out of the source repository.

**Comment by Garulf** [comment]
I'd love to be able to easily version control my setup for back up and not have to worry about exposing potential secrets.
