### ISSUE TITLE
Accessories Not Responding

### ISSUE THREAD

**Issue by tpitale** [nfarina/homebridge#1955]
### Expected Behavior

All accessories should be reachable, as they have been.

### Current Behavior

All accessories show up as "not responding".

### Steps to Reproduce (for bugs)

After performing a software upgrade to any component in a system (my mac running homebridge, the appletv, or the ios app) all accessories are unresponsive from the Home app. The mac is still running the same ip and port configuration.

What's frustrating is that I can bump the pin and user in `config.json` and then the accessories can be re-added. So, we know the connection is there.

I've read and attempted the steps in https://github.com/nfarina/homebridge#my-ios-app-cant-find-homebridge.

The homebridge instance connects to Nest and the Smarthings hub without issue.

Is the _only_ option to remove the existing homebridge accessory and re-add every time a software update happens?

I've had to do this at least twice previously. It may be that Apple is doing something stupid, but I'd love to know what is going on. Apple has to be "ignoring" accessories it already knows about because it sees that something has changed. But I can't fathom what that is after doing a software update.

### Versions

- **Homebridge**: 0.4.44
- **Node**: v7.7.4
- **OS**: Mojave 10.14 public beta 4

### Configuration

```json
{
  "bridge": {
    "name": "Homebridge",
    "username": "CC:22:3D:E3:CE:34",
    "port": 51826,
    "pin": "031-45-156"
  },
  "description": "",
  "accessories": [
  ],
  "platforms": [
    {
      "platform": "SmartThings",
      "name": "SmartThings",
      "app_url": "https://graph-na02-useast1.api.smartthings.com:443/api/smartapps/installations/",
      "app_id": "",
      "access_token": "",
      "polling_seconds": 3600,
      "update_method": "direct",
      "direct_ip": "",
      "direct_port": 51827
    },
    {
      "platform": "Nest",
      "clientId": "",
      "clientSecret": "",
      "token":"",
      "code": ""
    }
  ]
}
```

### Homebridge Log / Command Output

```
[8/2/2018, 8:32:57 AM] Loaded config.json with 0 accessories and 2 platforms.
[8/2/2018, 8:32:57 AM] ---
[8/2/2018, 8:32:58 AM] Loaded plugin: homebridge-nest-debounced
[8/2/2018, 8:32:58 AM] Registering platform 'homebridge-nest.Nest'
[8/2/2018, 8:32:58 AM] ---
[8/2/2018, 8:32:58 AM] Loaded plugin: homebridge-smartthings
[8/2/2018, 8:32:58 AM] Registering platform 'homebridge-smartthings.SmartThings'
[8/2/2018, 8:32:58 AM] ---
[8/2/2018, 8:32:58 AM] Loading 2 platforms...
[8/2/2018, 8:32:58 AM] [SmartThings] Initializing SmartThings platform...
[8/2/2018, 8:32:58 AM] [SmartThings] Fetching Smart Things devices.
[8/2/2018, 8:32:58 AM] [SmartThings] Refreshing All Device Data
[8/2/2018, 8:32:58 AM] [Nest] Initializing Nest platform...
[8/2/2018, 8:32:58 AM] [Nest] Fetching Nest devices.
```

**Comment by tpitale** [comment]
Is this a problem with the Home app, or is it a problem with HomeKit (using the AppleTV as a "hub")?

Should I use one of the other apps discussed here? Is it likely to fix this issue?
https://github.com/nfarina/homebridge/issues/520

**Comment by tpitale** [comment]
I don't think I was impacted by this: https://github.com/nfarina/homebridge/wiki/Migration-Guide
I didn't upgrade `homebridge` during this time.

**Comment by tpitale** [comment]
Seems possible related to #1948.

**Comment by kirichkov** [comment]
@tpitale What iOS version are you running?

I actually think this is in no way related to homebridge but "Apple is doing something stupid". Ever since I upgraded to iOS 11.4.1 I've been experiencing the same issue you describe. After I restart my iphone/ipad the connection is back on. If I click a bulb or a switch in the Home app, sometimes the connection is reestablished and my accessories are updated and responding. Closing and reopening the Home app leads again to "Accessory is not responding".

Why I think this is Apple and not homebridge - I observe the exact same behaviour using Home Assistant's native homekit integration, so Apple might have changed something in the protocol with 11.4.1. AFAIK there is the multiroom update in 11.4.1, or it might be upgraded HomeKit protocol due to Home App coming to macOS.

Can you try restarting your iOS device and see whether this reestablishes the connection? Perhaps it's the same issue.

**Comment by iRayanKhan** [comment]
I think it could be because you  are on mojave beta 4. When I was running dev beta 2 Node.js failed entirely.

**Comment by kirichkov** [comment]
@iRayanKhan I am running homebridge on a Raspberry Pi and still have the same issue. I don't think it's a problem with @tpitale's OS.

**Comment by HansVanEijsden** [comment]
I can confirm this issue: with (at least) the last 3 public betas of Mojave. The Home app finds all the HomeKit devices except HomeBridge: not HomeBridge itself and not the accessories.

**Comment by iRayanKhan** [comment]
It's working great for me on a Pi tbh it's worth getting a Pi their dirt chip on ebay mine had a 16gb micro sd card with it.

**Comment by Sytanek** [comment]
Just ran into this issue, occurred as soon as I restarted homebridge, has been working fine for works, and now can't access any devices.

**Comment by mhekim** [comment]
I had the same issue. Deleting the file inside the accessories folder , persist folder didn't solve my problem. I've rebooted it several time but it was not responding again. Deleting Installing the apple home kit app didn't solve my problem also. So I've removed the homebridge from apple home kit and add again. Now its working without any problem. I can control all my devices.
