### ISSUE TITLE
mDNS packets send to wrong interface

### ISSUE THREAD

**Issue by StoneMoe** [nfarina/homebridge#1957]
### Expected Behavior
When running homebridge on router, mDNS packets should send to local network interface (like eth1) rather than wan interface (like eth0)
So iDevices can add homebridge to homekit

### Current Behavior
All mDNS packets send to wan device
iPhone cannot find any accessory after scan qrcode

### Steps to Reproduce (for bugs)
On my router, i run these commands while homebridge is running:

`ifconfig` output
```
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.2  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::2e0:4dff:fe71:181  prefixlen 64  scopeid 0x20<link>
        ether 00:xx:xx:xx:xx:81  txqueuelen 1000  (Ethernet)


eth1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.42.1  netmask 255.255.254.0  broadcast 192.168.42.255
        inet6 fe80::2e1:4dff:fe71:17a  prefixlen 64  scopeid 0x20<link>
        ether 00:xx:xx:xx:xx:7a  txqueuelen 1000  (Ethernet)
```
(wan device: `eth0`, lan device: `eth1`)

`sudo tcpdump -n udp dst port 5353 -i eth0` output
```
listening on eth0, link-type EN10MB (Ethernet), capture size 262144 bytes
17:18:10.054717 IP 192.168.1.2.5353 > 224.0.0.251.5353: 0*- [0q] 7/0/0 PTR Homebridge-3B00._hap._tcp.local., SRV CC_XX_XX_XX_XX_XX.local.:51826 0 0, TXT "md=Homebridge" "pv=1.0" "id=CC:xx:xx:xx:xx:xx" "c#=2" "s#=1" "ff=0" "ci=2" "sf=1" "sh=o1M/HA==", A 192.168.1.2, AAAA fe80::2e0:4dff:fe71:181, A 192.168.42.1, AAAA fe80::2e1:4dff:fe71:17a (448)
.....
```

`sudo tcpdump -n udp dst port 5353 -i eth1` output
```
listening on eth1, link-type EN10MB (Ethernet), capture size 262144 bytes
<nothing here at all>
```

### Versions

- **Homebridge**: `0.4.44`
- **Node**:       `v8.11.3`
- **OS**:         `Debian 9, x86_64`

### Homebridge Log / Command Output
```
............qrcode and some plugin loaded output..........
[2018-8-4 17:02:37] [Homebridge Info] is listening on: http://192.168.1.2:9876
[2018-8-4 17:02:37] [Homebridge Info] is listening on: http://192.168.42.1:9876
[2018-8-4 17:02:37] Homebridge is running on port 51826.
```

**Comment by StoneMoe** [comment]
Looks like an OS related route issue, I'll close it.

**Comment by StoneMoe** [comment]
Use config `mdns.interface` can solve this issue by forcing multicast lib bind to specify interface.

example:
```
{
    "mdns": {"interface": "192.168.42.1" },  // here
    "bridge": {
        "name": "...",
        "username": "...",
        "port": ...,
        "pin": "..."
    },
    "description": "....",
    "accessories": [
....
    ],
    "platforms": [
....
}
```

**Comment by EvanPurkhiser** [comment]
I know this doesn't contribute to the conversation, but I really just wanted to say **_thank you_** @StoneMoe. I spent two hours trying to figure this out and had no idea of the existence of the `mdns` configuration.

**Comment by WimBre** [comment]
Hi,

I have tried to fix my pairing problems with homebridge by adding the mdns line in the config.json file (see below).

The JSON Validator found 2 errors:
1. Error:Strings should be wrapped in double quotes.[Code 17, Structure 10]
2. Error:Invalid character found at position 8.[Code 180, Structure 10]

What have i done wrong?

Config.json file:

{  
   "mdns":{  
      "interface":"192.168.178.25"
   },
   // here              <-RED MARKED IN VALIDATOR!
   "bridge":{        <-RED MARKED IN VALIDATOR!
      "name":"Homebridge",
      "username":"CC:22:3D:E3:CE:30",
      "port":51826,
      "pin":"031-45-154"
   },
   "description":"ORIGINEEL RASPBERRY PI",
   "accessories":[  
      {  
         "accessory":"Toon",
         "name":"TOON",
         "username":"...........",
         "password":"..............."
      }
   ]
}

**Comment by StoneMoe** [comment]
Hi, you can remove `// here` and try again, It’s just a comment.

From mobile device

**Comment by WimBre** [comment]
Thanks StoneMoe.

It didn't solve the pairing issue but homebridge is back in the air!

**Comment by WimBre** [comment]
FYI:



> Thanks StoneMoe.
> 
> It didn't solve the pairing issue but homebridge is back in the air!

I have solved my pairing issue with homebridge and homekit.

Homebridge is running on a raspberry pi and on the raspberry pi a firewall has been activated.

Because I had problems with pairing, I deactivated the firewall and then the pairing worked fine.

Because I wanted to activate the firewall, I gave access to the port through which homebridge is running and after I reactivated the firewall everything works fine!

**Comment by i3laze** [comment]
Spent extra 5 minutes, cause didn't notice that:
   "mdns" block goes above/near "bridge"

   Placed "mdns" inside "bridge" block by mistake :)

P.S. Homebridge log output says **nothing** about this setting in effect, but it does work!

**Comment by hepcat72** [comment]
> Use config `mdns.interface`

Could someone please tell me where I can file the file `mdns.interface ` referenced above?

**Comment by hepcat72** [comment]
For anyone else finding themselves here and trying these tips and it's not working... check your logs. I was getting "no response" errors from Siri, couldn't control any device from the home app, couldn't re-add the homebridge to the home app, and none of the usual fixes worked either: remove persist, remove accessories, change the name, turn onn/off airplane mode, restart the Pi & my phone... I even tried the dumptcp suggestion and saw homebridge traffic on the expected ports... Well, my homebridge-liftmaster2 plugin was crashing homebridge a dozen times a minute due to a bad response from the chamberlain remote server that the plugin doesn't handle. My logs had bloated with multiple errors per second and pm2 was working overtime to restart homebridge continually.

**Comment by TheGingerDan** [comment]
via the Homebridge ui in the CONFIG area I added the code suggested:
for "hostip" I put the IP of my NAS server which is runnung Homebridge via Docker.

{
    "mdns": {
        "interface": "hostip"
    },
    "bridge": {
        "name": "Homebridge AA5B",
        "username": "0E:BC:46:51:AA:5B",
        "port": 51712,
        "pin": "031-45-154"
    },
    "accessories": [
        {

When I add this to the config, I get this error:  Error: bind EADDRNOTAVAIL HostIP:5353
    at dgram.js:334:20
    at processTicksAndRejections (internal/process/task_queues.js:82:21)

If I remove the interface command, homebridge runs again but I cannot add it to the Home app on iOS.

**Comment by angus2064** [comment]
> via the Homebridge ui in the CONFIG area I added the code suggested:
> for "hostip" I put the IP of my NAS server which is runnung Homebridge via Docker.
> 
> {
> "mdns": {
> "interface": "hostip"
> },
> "bridge": {
> "name": "Homebridge AA5B",
> "username": "0E:BC:46:51:AA:5B",
> "port": 51712,
> "pin": "031-45-154"
> },
> "accessories": [
> {
> 
> When I add this to the config, I get this error: Error: bind EADDRNOTAVAIL HostIP:5353
> at dgram.js:334:20
> at processTicksAndRejections (internal/process/task_queues.js:82:21)
> 
> If I remove the interface command, homebridge runs again but I cannot add it to the Home app on iOS. I also don't understand why it shows port 5353.

I have the same problem, someone can help me please ?

**Comment by StoneMoe** [comment]
> > via the Homebridge ui in the CONFIG area I added the code suggested:
> > for "hostip" I put the IP of my NAS server which is runnung Homebridge via Docker.
> > ...
> > When I add this to the config, I get this error: Error: bind EADDRNOTAVAIL HostIP:5353
> > If I remove the interface command, homebridge runs again but I cannot add it to the Home app on iOS. I also don't understand why it shows port 5353.

@angus2064 @TheGingerDan 

Docker container has its own network namespace, which means homebridge cannot get your real IP when running in a container. so you got EADDRNOTAVAIL(Error ADDRess NOT AVAILable).

[Use "host" network mode](https://docs.docker.com/network/host/) for the container which you ran homebridge may fix this issue.

**Comment by angus2064** [comment]
Thank you for your help !!

For those having the same issue using Docker, when you intsall the container for the first time, in network section you need to check the box "use the same network than Docker host".

**Comment by sealedge** [comment]
Thanks for the great help @StoneMoe and others.
I'm running MacOS with homebridge. I cannot get homekit to find it via my iPhone 12.
I have tried all of the suggestions here and added the mdns code as instructed. HB runs fine. Here's my config file.

Your assistance is GREATLY appreciated.

{
    "mdns": {
        "interface": "192.168.1.19"
    },
    "bridge": {
        "name": "Homebridge 64AB",
        "username": "0E:77:BE:95:C6:33",
        "port": 51849,
        "pin": "264-53-439",
        "advertiser": "bonjour-hap",
        "bind": [
            "en1",
            "awdl0",
            "utun0",
            "utun1",
            "utun2"
        ]
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        },
        {
            "name": "Ledge",
            "user": "******",
            "pass": "******",
            "host": "192.168.1.2",
            "port": "25105",
            "model": "2245",
            "refresh": "false",
            "server_port": "3000",
            "keepAlive": "false",
            "devices": [
                {
                    "name": "Nursery",
                    "deviceID": "5738FC",
                    "dimmable": "true",
                    "deviceType": "dimmer"
                }
            ],
            "platform": "InsteonLocal"
        }
    ]
}
