### ISSUE TITLE
best method of having HomeKit server autostart in ubuntu?

### ISSUE THREAD

**Issue by tommyd75** [nfarina/homebridge#196]
Does anyone have the best method for having the server autostart as soon as the server in booted up?

**Comment by nfarina** [comment]
Check [this section](https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi#running-homebridge-on-bootup) of the Wiki (instructions for Raspberry Pi but should work on most Linux systems I believe)
