### ISSUE TITLE
iOS cannot find the homebridge device

### ISSUE THREAD

**Issue by AlexHuebi** [nfarina/homebridge#1960]
### Expected Behavior
iOS (iPad on 11.3.1 & iPhone on 12pb5) should find the Homebridge as a Homekit device 

### Current Behavior
iOS (iPad on 11.3.1 & iPhone on 12pb5) does not see the Homebridge as a Homekit device and/or cannot find it either

### Steps to Reproduce (for bugs)
Install Homekit as described, modify config.json, launch, error

### Versions
- **Homebridge**: 0.4.44
- **Node**:      6.3.0 (also didnt work with 5.10.0 or 5.6.0)
- **OS**:         Rasbian Jessie w/ Kernel ver 4.9.35-v7+ 
- **System**:   Raspberry 3B 

### Configuration

```json
{
   "bridge": {
      "name": "Homebridge",
      "username": "B8:27:EB:41:2A:25",
      "port": 51826,
      "pin": "031-45-154"
   },

   "description": "RGB TestLED ",

   "accessories": [{
      "accessory": "HTTP-RGB",
      "name": "RGB LED",

      "switch": {
         "status": "http://10.0.0.37:80/status",
         "powerOn": "http://10.0.0.37:80/on",
         "powerOff": "http://10.0.0.37:80/off"
      },

      "color": {
         "status": "http://10.0.0.37:80/color",
         "url": "http://10.0.0.37:80/set/%s"
      },

      "brightness": {
         "status": "http://10.0.0.37:80/bright",
         "url": "http://10.0.0.37:80/set/%s"
      }
   }],

   "platforms": []

}
```

### Homebridge Log / Command Output

```

```

NOTE: 
Installed also "homebridge-better-http-rgb" but the error was existing before

**Comment by iRayanKhan** [comment]
Have you tried adding it with the default config?

**Comment by AlexHuebi** [comment]
Yes. But with that, homebridge even refuses to start.
``
pi@rpi-Alex:/ $ homebridge
[2018-8-9 14:47:42] Loaded config.json with 1 accessories and 1 platforms.
[2018-8-9 14:47:42] ---
[2018-8-9 14:47:42] Loaded plugin: homebridge-httptemperaturehumidity
[2018-8-9 14:47:42] Registering accessory 'homebridge-httptemperaturehumidity.HttpTemphum'
[2018-8-9 14:47:42] ---
[2018-8-9 14:47:42] Loading 1 platforms...
/usr/lib/node_modules/homebridge/lib/api.js:122
      throw new Error("The requested platform '" + name + "' was not registered by any plugin.");
      ^

Error: The requested platform 'PhilipsHue' was not registered by any plugin.
    at API.platform (/usr/lib/node_modules/homebridge/lib/api.js:122:13)
    at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:315:45)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:85:36)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:43:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
``
I got the config sample from here: 
https://github.com/nfarina/homebridge/blob/master/config-sample.json

**Comment by iRayanKhan** [comment]
I had this error too I wiped my Pi and then it fixed it self. Goodluck

**Comment by iRayanKhan** [comment]
I see your using Rapsbarian Jessie I tried Lite try that and do it headless or not depends on you.

**Comment by gerrit-goed** [comment]
Are you connected through LAN? I had the same issue, and fixed it by unplugging the lan cable and run homebridge on the wifi interface of the PI..

**Comment by AlexHuebi** [comment]
A small update for you guys.. (thanks to @iRayanKhan for the tipp) I did reinstall my RasbPI OS and is now running Debian Stretch. And with that I could get this thing to work.

@gerrit-goed wifi would not have been any option because the supposed place is in the cellar.

**Comment by iRayanKhan** [comment]
@AlexHuebi to close this thread there should be an option that says close or comment and close.
