### ISSUE TITLE
How to keep HomeBridge accessories after reboot?

### ISSUE THREAD

**Issue by iRayanKhan** [nfarina/homebridge#1961]
### Expected Behavior
Occasionally I have to reboot my Rpi 3 model B for various reasons and I understand you have to delete the Persist folder and the accessories folder other wise you get the UUID error. I was wondering if there is a way to keep the accessories from HomeBridge in the home app rather then having to re-add them as I plan to add 45 more HomeBridge accessories. 

### Current Behavior
Rebooting the host requires me to re-add homebridge to the Home App
Wish you only have to delete the persist folder and homebridge would work like a normal bridge and restart after being connected to power.

### Steps to Reproduce (for bugs)
Reboot the host and restart homebridge you get an error for bridged accessories with a UUID error. Then it requires me to remove BOTH the accessories and persist folders not just the persist folder.

### Versions

- **Homebridge**: `Latest`
- **Node**:       `Latest`
- **OS**:         Rapsbarian Lite (latest) on an iPhone 7 running iOS 12 Developer Beta 6.

**Comment by ebaauw** [comment]
> I understand you have to delete the Persist folder and the accessories folder 

The persist folder keeps information from homebridge itself, notably to which HomeKit clients it has been paired.  Deleting the persist folder is like a factory reset of homebridge.  This will remove the bridge and all accessories from your HomeKit configuration.  **Don't do this**, unless your HomeKit configuration is completely broken, and you cannot remove homebridge.

> other wise you get the UUID error.

The accessories folder is where dynamic platform plugins persist previously created accessories.  Deleting the accessories folder shouldn't be necessary.   If you get a _Cannot add bridged accessory with the same UUID_ error, that can only be remedied by deleting the accessories folder, one of your plugins is broken.  Try to identify which one, and raise an issue there.

**Comment by iRayanKhan** [comment]
The plugin is Lift-master-2 let me test some stuff.

**Comment by iRayanKhan** [comment]
Thank you, I rebooted the host and only deleted the accessories folder and now it stays.
