### ISSUE TITLE
Really slow reaction with more than 1 light

### ISSUE THREAD

**Issue by Julius971** [nfarina/homebridge#1963]
If i add a single light (HTTP_RGB) to the homebridge everything works just fine.
But if i add a second one of the same kind everything becomes slow and the homebridge takes minutes to complete a task like changing color. Its also noticable in the long "updating" times of the lamps in the home app.

### Versions

homebridge: 0.4.38
node: 8.9.4
os: windows server 2016

**Comment by Julius971** [comment]
also in 0.4.44

**Comment by NorthernMan54** [comment]
Please open this issue under the plugin you are using.  In almost all cases Slowness is a direct result of the plugin design and implementation.
