### ISSUE TITLE
How to add new accessories

### ISSUE THREAD

**Issue by iRayanKhan** [nfarina/homebridge#1968]
Hello everyone,
Small question.
I have 2 Garages already setup with HomeBridge and I'm planning to add 47 more. If I want to add more accessories I know that I have to edit the config, but when I restart homebridge will it automatically add the accessories or do I have to re-add homebridge entirely? 

Thank you!

**Comment by xoniq** [comment]
For me, when a plugin serves new devices, and I restart homebridge, the new devices are added. So i would say yes. Try it, it should work that way.

**Comment by iRayanKhan** [comment]
Ok thanks!
