### ISSUE TITLE
Can't control Xfinity Home system

### ISSUE THREAD

**Issue by fitzage** [nfarina/homebridge#197]
I've set things up, and when I start homebridge it's definitely connecting to my Xfinity security system and gets the status as disarmed.

However, I can't figure out any Siri commands that actually work to control it. Also, in the Insteon+ app, there doesn't seem to be any commands associated with the Xfinity Home device.

If I try something like "set security system to away mode" or "turn on away mode" or anything of that nature, I get "cannot find that scene".

**Comment by nfarina** [comment]
Yes, unfortunately I haven't figured out the magical phrases, if any, that will cause Siri to control security systems. Maybe they haven't activated this yet?

In the meantime I use it myself personally by assigning it to the built-in scenes - "I'm Leaving", "I'm Home", "Good night", etc.

Also, glad to hear someone else is getting some use out of this! It was a lot of work to rewrite it against their new API :)

**Comment by KhaosT** [comment]
I believe Siri currently doesn't support most of new profiles Apple introduced in iOS 9, I'd suggest you follow Nick's suggestion to setup a scene so you can control those systems with Siri :)

**Comment by fitzage** [comment]
The Insteon app doesn't show me any scenes, and when I try to set one up that includes the security system, it doesn't give me any control over the security system. What am I missing?

**Comment by fitzage** [comment]
In fact, if I try adding the security system to a scene and then go back, it shows no devices in the scene.

**Comment by KhaosT** [comment]
@fitzage Insteon+ hasn't been updated to support new profiles for iOS 9, I'd suggest to try Elgato Eve app?

**Comment by fitzage** [comment]
Ah, that would explain it. I will try that.

**Comment by fitzage** [comment]
Works like a charm. Thanks.
