### ISSUE TITLE
How to edit config for multiple plugins.

### ISSUE THREAD

**Issue by iRayanKhan** [nfarina/homebridge#1970]
Hey everyone quick question:
I want to add another plugin and I was wondering how to merge these 2 configs to best merge it;
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    "description": "Homebridge",
    "accessories": [],
    "platforms": [
        {
            "platform": "LiftMaster2",
            "username": "blank@gmail.com",
            "password": "YeahNo"
        }
    ]
}

//Stuff I want to add

 "platforms": [
    {
      "platform": "Envisalink",
      "host": "192.168.0.XXX",
      "deviceType": "DSC",
      "password": "---envisalink password (default is user)---",
      "pin": "---panel pin for disarming---",
      "suppressZoneAccessories": false,
      "suppressClockReset": false,
      "partitions": [
        {
          "name": "Alarm"
        }
      ],
      "zones": [
        {
          "name": "Front Door",
          "type": "door",
          "partition": 1
        },
        {
          "name": "Master Bedroom Door",
          "type": "door",
          "partition": 1
        },
        {
          "name": "Downstairs Windows",
          "type": "window",
          "partition": 1
        },
        {
          "name": "Basement Leak",
          "type": "leak",
          "partition": 1
        },
        {
          "name": "Upstairs Smoke",
          "type": "smoke",
          "partition": 1
        },
        {
          "name": "Living Room Motion",
          "type": "motion",
          "partition": 1
        }
      ],
      "userPrograms": [
        {
          "name": "Basement Smoke",
          "type": "smoke",
          "partition": 1
        }
      ]
    }
  ]

**Comment by W0GER** [comment]
platforms: [ ] indicates an array; array elements are separated by commas. So after your LiftMaster2 object, add a comma, then the next object. I validated the following at https://jsonformatter.curiousconcept.com/


```
{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},
	"description": "Homebridge",
	"accessories": [],
	"platforms": [{
			"platform": "LiftMaster2",
			"username": "blank@gmail.com",
			"password": "YeahNo"
		}, {
			"platform": "Envisalink",
			"host": "192.168.0.XXX",
			"deviceType": "DSC",
			"password": "---envisalink password (default is user)---",
			"pin": "---panel pin for disarming---",
			"suppressZoneAccessories": false,
			"suppressClockReset": false,
			"partitions": [{
					"name": "Alarm"
				}
			],
			"zones": [{
					"name": "Front Door",
					"type": "door",
					"partition": 1
				}, {
					"name": "Master Bedroom Door",
					"type": "door",
					"partition": 1
				}, {
					"name": "Downstairs Windows",
					"type": "window",
					"partition": 1
				}, {
					"name": "Basement Leak",
					"type": "leak",
					"partition": 1
				}, {
					"name": "Upstairs Smoke",
					"type": "smoke",
					"partition": 1
				}, {
					"name": "Living Room Motion",
					"type": "motion",
					"partition": 1
				}
			],
			"userPrograms": [{
					"name": "Basement Smoke",
					"type": "smoke",
					"partition": 1
				}
			]
		}

	]
}

```

**Comment by iRayanKhan** [comment]
Thank you will try this out rn.

**Comment by iRayanKhan** [comment]
I did this it worked I installed the plugin and it says it wasn't registered by any plugin Im assuming because I haven't filled out the envisalink config?

**Comment by iRayanKhan** [comment]
Fixed. Thanks!
