### ISSUE TITLE
Host Name Conflict

### ISSUE THREAD

**Issue by OliB73** [nfarina/homebridge#1971]
I do not get any response from any plug in, as I face a host name conflict.

### Expected Behavior
Homebridge should run, the plug in should register and the data should be shown in HomeKit

### Current Behavior
Homebridge runs, plugs ins are register and shown in HomeKit, but no data is transmitted. 
Log shows Host Name Conflict

### Steps to Reproduce (for bugs)
just restart the container

### Versions

- **Homebridge**: `homebridge --version` 0.4.44
- **Node**:       `node --version` v.8.11.3
- **OS**:            DSM 6.2-23739 Update 2

### Configuration
{
    "bridge": {
        "name": "Homebridge",
        "username": "DADADADAD",
        "port": 51826,
        "pin": "031-45-154"
    },

    "description": "This is an example configuration file. You can use this as a template for creating your own configuration file containing devices you actually own.",

    "accessories": [
    ],

    "platforms": [

        {
          "platform": "DysonPlatform",
          "name": "DysonPlatform",
          "email": "BBB",
          "password": "CCC",
          "country": "DE",
          "accessories": [
            {
            "ip": "EEE",
            "displayName": "PureCool",
            "serialNumber": "DDD"
          }
            ]
       },

       {
       "platform": "Netatmo",
       "name": "Netatmo Platform",
       "auth": {
         "client_id": "AAA",
         "client_secret": "ZZZ",
         "username": "YYY",
         "password": "XXX"
       }
     }
   ]

}

### Homebridge Log / Command Output

```

Host name conflict, retrying with DSM216-1865                                                                                    
Registering new address record for 172.17.0.1 on docker0.IPv4.                                                                   
Registering new address record for 2a04:4540:6d00:8000:211:32ff:fe55:3323 on ovs_eth0.*.                                         
Registering new address record for 192.168.188.29 on ovs_eth0.IPv4.                                                              
^[cWithdrawing address record for 172.17.0.1 on docker0.                                                                         
Withdrawing address record for 192.168.188.29 on ovs_eth0.                                                                       
Host name conflict, retrying with DSM216-1866                                                                                    
Registering new address record for 172.17.0.1 on docker0.IPv4.                                                                   
Registering new address record for 2a04:4540:6d00:8000:211:32ff:fe55:3323 on ovs_eth0.*.                                         
Registering new address record for 192.168.188.29 on ovs_eth0.IPv4. 

```

**Comment by brideone** [comment]
Your username is malformed, It must be a Mac address like:
`"username": "CC:22:3D:E3:CE:34",`
