### ISSUE TITLE
Is it possible to embed HomeBridge with a native app on tvOS

### ISSUE THREAD

**Issue by seivan** [nfarina/homebridge#1974]
I am wondering if its possible to embed `HomeBridge` with a native app on `tvOS` as an alternative to having a `Raspberry Pi` hardware. Since my `AppleTV` is always running, it could just run the `Homebridge` app - but I'm not sure if I've missed something crucial here. 

It is possible to execute `JS` with `tvOS`, just no web-view to render the `DOM` - but not sure if there are other obstacles.

**Comment by Partizan7676** [comment]
as i know some guys from Russia work on that. https://itunes.apple.com/app/apple-store/id1329662539?mt=8

**Comment by aptonline** [comment]
This would not work as it would A) need to be running in the background, which isn’t possible on tvOS, and B) I don’t think it could run the required frameworks. 

It really would be simple and straight forward to run it on a Rasyberry Pi (even a pi zero w) with minimal effort. I have mine running a docker.

**Comment by seivan** [comment]
Cool, thanks for the feedback. The background portion isn't a big concern, as I don't mind it running as a dashboard. That being said, maybe the required frameworks might be an issue.
