### ISSUE TITLE
Possible issue with tvOS 12 Public Beta 7 and Homebridge...

### ISSUE THREAD

**Issue by jsworks** [nfarina/homebridge#1975]
I'm currently running the latest version of Homebridge, using an AppleTV as a Home hub. I've been using tvOS 12 Public Beta for a few weeks, which has already seen a couple of updates. Up until today, everything has been working as it always has done.

So, I'm at work and open my Home app and see that all the Homebridge accessories are reporting "no response". When I get home and my phone joins my wifi network, all the accessories in the Home app are responding again, but the most my rules (which are mostly based on the status of homebridge plugins) do not fire.

As far as I knew, nothing had changed on my system between last night (when I know it was working) to this evening. That is, until I realised that my AppleTV had updated itself to the latest public beta 7, which was released about 24 hours ago. I tried restarting the AppleTV and restarting Homebridge, but the rules still do not fire. Switching off my wifi, the homebridge accessories in the Home app again show "no response".

Rather than try the usual method of changing the pin/username, I switched the Home hub to be my iPad (which is running iOS 11) and now everything is working again as it was. Having seen a similar issue reported in iOS 11 betas, I figured I'd wait to see if the next public beta of tvOS fixes things.

Anyway, hopefully this is not a permanent issue and it might be something specific to my setup, but I thought I'd let others know.

**Comment by Jozarco** [comment]
The same for me with tvOS 11 from 4 months ago. I have to restore complety the apple tv for recover the system. En 2 ó 3 weeks fail again. I'm afraid its a problem with some ruler made with an app diferente from Home but I am not sure. Now I'm using HomePod as hub without problems the last two weeks.

**Comment by soska12** [comment]
I'm using tvOS beta since the first or second one but everything is working fine for me. I'm using iOS 12 beta on my iPhone and iPad as well.

**Comment by rajkowski** [comment]
Came here looking for issues with the tvOS 12 release. Homebridge status says Updating... then No response for homebridge accessories only. I haven’t figured out anything useful. Thanks for the tip using an iOS 11 iPad.

**Comment by jsworks** [comment]
Well, I found out that if I go the account settings on the Apple TV (pick your iCloud account), "disconnect" from HomeKit, reboot the Apple TV and then "reconnect", connectivity is restored. Seems like procedure "refreshes" something on the Apple TV.

Hope that helps someone...

**Comment by rajkowski** [comment]
@jsworks I tried that... Homebridge responds to turn on/off lights for about a minute then all the Homebridge devices (contact closure/lights/garage) report as Updating/No Response again. 

One weird side effect though is that even with the No Response accessories, the contact closure push notifications still occur, and the video cameras update too.

I'm going to look into the plug-ins.

**Comment by rajkowski** [comment]
Good news – I worked through the plug-ins and found one hanging on an ip for a device that changed. I can also confirm tvOS 12.0.1 and macOS 10.14 are working well.
