### ISSUE TITLE
send hombridges nodes to mqtt or node-red  to be able to control and get status from mqtt or node-red directly

### ISSUE THREAD

**Issue by MattL0** [nfarina/homebridge#1978]
Hi,
 Since there is a lot of development in homebridge plugins...
 I would like to extract nodes from homebridge ( not homekit) and get the status and control them from node-red or mqtt . I would then,in the end, add the nodes to my homeseer setup.

That's sound like a good project ? nah? haha

**Comment by NorthernMan54** [comment]
That sounds like a great idea!  I would love for node-red to have access to all my homebridge devices, then I could build some awesome automations in node-red and.

**Comment by NorthernMan54** [comment]
6 months later, and I have this Alpha version ready to go.

https://github.com/NorthernMan54/HAP-NodeRed
