### ISSUE TITLE
No response for a few minutes

### ISSUE THREAD

**Issue by philipans** [nfarina/homebridge#1979]
Home App shows "no response" on all devices randomly. After a few minutes the connection is back and all is working well again without doing anything.
This happens around three times a day and it's really annoying.

### Setup

**Homebridge:** 
is running on a virtual machine (Ubuntu 18.04) [current version]

**Plugins:** 
Fibaro-HC2 [current version]

**Device:** 
- iPhone X [with iOS 11.4.1]
- iPhone 6s [with iOS 11.4.1]
- iPad 5 [with iOs 11.4.1]
- HomePod [with 11.4.1] 

### Already checked during the problem occurs:
homebridge - **connected to network**
Fibaro HC2 - **connected to network**
iPhone X - **connected to network**

ping: homebridge <-> iPhone **successful**
ping: homebridge <-> Fibaro HC2 **successful**

This isn't a new problem. Even before I switched to iOS 11 with the Apple devices I had these problems.
Has anyone else the same problem?

**Comment by skywalker1979** [comment]
yes...i do....i'm in the process of trying to find out what it is right now....or at least i've been trying in the last month....let's try to share what we have in common:

2 homebridges for 2 different users on 2 different raspberrys.
one of them has pi-hole... (wich i just 5 minutes ago deactivated...)
unifi access points and 2 tp-link powerlines.
mikrotik router
1 esp8266 connected to the wifi wich sends data to domoticz for temperature....
couple of android box for tv.

can't think of anything else worth mentioning.

**Comment by skywalker1979** [comment]
ok....i noticed that pi-hole should have nothing to do with this problem.
at this very moment i'm testing homebridge by starting it in a screen session, instead of starting it with the systemd system.
like this it seems to be working for longer....at least until now i have not seen the problem again. I will keep it going for a few more hours and write back.

**Comment by skywalker1979** [comment]
i've just added a mikrotik router as access point....and it's been working stable for the last 3 hours....

**Comment by iRayanKhan** [comment]
When I attempted to run it on a linux based VM it failed all the time for me. I bit the bullet and bought a pi3 model B for $25 on ebay (it even came with an 16gb sd card!) I hope you can find a fast and easy fix, but I just got a Pi and it fixed my issue.
