### ISSUE TITLE
can't install through npm

### ISSUE THREAD

**Issue by flamner** [nfarina/homebridge#1982]
When I try to install package

`sudo npm install -g --unsafe-perm homebridge`

I got an error: 

`request to https://registry.npmjs.org/homebridge failed, reason: Hostname/IP doesn't match certificate's altnames: "Host: registry.npmjs.org. is not in the cert's altnames: DNS:a.sni.fastly.net, DNS:a.sni.global-ssl.fastly.net"`

**Comment by W0GER** [comment]
I'm able to get valid JSON back from `https://registry.npmjs.org/homebridge` and the SSL validates. 

It seems that your infrastructure is attempting to hit fastly.net which appears to be a Internet Caching provider. I'd check to see if you can bypass fastly.net.
