### ISSUE TITLE
Plugins: How to set/clear error indicator in Homebridge Accessories

### ISSUE THREAD

**Issue by jdtsmith** [nfarina/homebridge#1983]
I'm working on a homebridge plugin that polls a somewhat flakey http server using `request.`  As a result of this flakiness, a number of errors occur, primarily `ESOCKETTIMEDOUT` (slow to respond) and `EHOSTUNREACH` (unit cycles its own power).  

In the polling callback, I'm using `updateValue` on the `On` characteristic.  Unfortunately neither `updateValue` nor `setValue` have separate `error` arguments.  It does seem you can them pass an `Error` object as the new value itself, and this indeed induces an error indicator in the interface:

![img_392e437e772f-1](https://user-images.githubusercontent.com/93749/44949416-ab2dbd00-adfe-11e8-8bd6-9add93fca481.jpeg)

Eventually the server starts responding again, and polling requests go through.  Subsequent `update/setValue` calls with normal values _do not_, however, clear the circled exclamation point in the Home app.  Everything works, but the error indicator remains.  Even restarting homebridge does nothing to clear it.

So my question is, in homebridge, how do you set and clear the error indicator on an accessory?  The behavior I'm trying to achieve is that the error status indicator is present only when the server is experiencing issues (to encourage the user to wait for them to clear before interacting again). 

Here's the current polling method:

```js
    pollPowerState: function() {
        clearTimeout(this.pollingTimeOut);

	this.getPowerState(
	    (error,value) => {
		if (debug) {
		    if(error) {
			this.log("Error polling state: ",error)
		    } else {
			this.log("Got Power State: ",value?"On":"Off");
		    }
		}
		this.switchService.getCharacteristic(Characteristic.On).
		    updateValue(error || value);
	    });

	this.pollingTimeOut = setTimeout(
            this.pollPowerState.bind(this),
            this.interval * 1000);
    },
```

**Comment by NorthernMan54** [comment]
I’m not 100% sure, but I thought that the behaviour of home app when it has a “not responding” device was to refresh when changing room’s and read the characteristic.  I’m away from my setup for a few days so I can’t check right now.

Another tip, run homebridge in DEBUG mode to watch the requests going back and forth so you can see what’s happening.

**Comment by ebaauw** [comment]
> I thought that the behaviour of home app when it has a “not responding” device was to refresh when changing room’s and read the characteristic.

Yes, when changing rooms (or when changing between _Home_ and _Rooms_ view), Home refreshes (re-reads) the services displayed.  Also when all are reachable.  It just doesn't update the status when you leave the app untouched.

**Comment by jdtsmith** [comment]
I see.  Strange that an `update` with an Error will _set_ the error status, but an update without an Error does not clear it.  Is that your experience as well?

Thanks for the thoughts.

**Comment by NorthernMan54** [comment]
This behaviour is due to limitations in the HomeKit event interface.   The Event interface only support’s value updates and not status/error updates.  So to clear the error status you need to trigger a get characteristics, and the easiest way to do that is to change rooms.
