### ISSUE TITLE
Multiple Platforms

### ISSUE THREAD

**Issue by iRayanKhan** [nfarina/homebridge#1984]
Hello everyone, I need a small bit of help please.
I am trying to add 2 Platforms into my config and I have some trouble here are the 2 things I would like merged thanks!

{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    "description": "Homebridge",
    "accessories": [],
    "platforms": [
        {
            "platform": "LiftMaster2",
            "username": ***@***com",
            "password": "*************"
        }
    ]
}
And to be merged with:
{
  "platform": "Camera-IP",
  "cameras": [
    {
      "name": "Name of the camera eg. GARAGE",
      "videoConfig": {
      	"source": "-re -i rtsp://10.0.19.10:554/Streaming/Channels/101",
      	"stillImageSource": "-i http://10.0.19.10/Streaming/channels/101/picture",
      	"maxStreams": 2,
      	"maxWidth": 1280,
      	"maxHeight": 720,
      	"maxFPS": 30
      }
    }
  ]
}
Thanks!

**Comment by iRayanKhan** [comment]
Here it is in PasteBin https://pastebin.com/mEPt23hK

**Comment by QuinnDD** [comment]
{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},
	"description": "Homebridge",
	"accessories": [],
	"platforms": [{
		"platform": "LiftMaster2",
		"username": "blah@blah",
		"password": "OOOF"
	}, {
		"platform": "Camera-IP",
		"cameras": [{
			"name": "Name of the camera eg. GARAGE",
			"videoConfig": {
				"source": "-re -i rtsp://10.0.19.10:554/Streaming/Channels/101",
				"stillImageSource": "-i http://10.0.19.10/Streaming/channels/101/picture",
				"maxStreams": 2,
				"maxWidth": 1280,
				"maxHeight": 720,
				"maxFPS": 30
			}
		}]
	}]
}




This should be working. You can check if your json file is valid. With the online jsonlint validator.

**Comment by iRayanKhan** [comment]
Cheers will try it out once I get my rtsp url.
