### ISSUE TITLE
Homekit connection error over multiple network hops

### ISSUE THREAD

**Issue by roguetradder** [nfarina/homebridge#1985]
### Expected Behavior

I have homebridge running on a Raspberry PI 3 B+. Started using homebridge.service. The install is working fine, however:
The RPI is connected directly to the wireless router via ethernet (wireless on the RPI is disabled) that router operates as the DHCP server and connects to the internet. I also have a 24 port switch in the basement that is connected to the router and various Wireless Access points through the house all via gigabit ethernet. All devices are on the same subnet. The IOS device seamlessly transfers to the strongest signal as it moves around the house. Previously I had homebridge running on a Mac mini plugged into the same port on the router and had no issues.
### Current Behavior

If the IOS device is connecting wirelessly directly to the Router where the RPI is plugged in, I have no issues. If I move to a different location and the IOS device connects to the network via any other Wireless access points, Homekit shows the homebridge accessories as being “Not Responding” (red). They eventually come back online after around 30 seconds. It feels to me that avahi (as apposed to Bonjour running on the Mac Mini) is not broadcasting over various hops in the network.
### Steps to Reproduce (for bugs)

I have moved the RPI to plug in directly to switch in the basement, to which all access points connect via ethernet and everything works with out the error. 
### Versions

- **Homebridge**: `homebridge --version 0.4.44`
- **Node**:       `node --version v10.9.0`
- **iOS**:         `11.4.1` 
- **Avahi Install**:  `sudo apt-get install libavahi-compat-libdnssd-dev`

### Configuration

```json

```

### Homebridge Log / Command Output

```

```

**Comment by iRayanKhan** [comment]
On the iOS device navigate to Settings > Wi-Fi > Select the SEID or Network name and hit "Auto connect or something like that" and disable it for all networks, but leave it on for the Net Work you want it to connect to. Also you can avoid this issue with a HomeHub.
A HomeHub can be the following:
-iPad running iOS 10.1 or later
-HomePod running iOS 11.2.5 or later
-AppleTV runnning tvOS 10.1 or later.

**Comment by roguetradder** [comment]
@iRayanKhan The iOS devices already auto connects to all Wifi access point and roam between access point seamlessly. This is not a connection issue. There are 2 Apple TV 4K's on the network, they are both operating as HomeHubs. 
This more likely a avahi broadcast issue IMO.

**Comment by ebaauw** [comment]
Did you turn off IGMP snooping on your router and access points?

**Comment by roguetradder** [comment]
@ebaauw the router and access points do not support IGMP, so no need to turn off.

**Comment by ebaauw** [comment]
Are you sure they don’t support IGMP snooping, or they don’t support turning it off (like my Fritz!Box, see #1801).

**Comment by roguetradder** [comment]
@ebaauw . Correct, it can not be disabled, so not an issue.

**Comment by marklife** [comment]
I have a similar setup and was having the exact same problem. In my config.json I had not changed the username from the default value - when I changed it to the actual MAC address of my raspberry pi, it fixed the problem, the home app worked everywhere. Hopefully that might help you too.
