### ISSUE TITLE
Catch plugin errors so that they don't crash homebridge

### ISSUE THREAD

**Issue by iRonin** [nfarina/homebridge#1988]
Would it be possible to catch plugin errors  so that they don't crash homebridge?
Mine has been currently plagued with https://github.com/nfarina/homebridge-sonos/issues/55 and it just keeps restarting instead of ignoring the accessory.

**Comment by NorthernMan54** [comment]
Not the answer you want, but for me I run a second instance of homebridge and just have the misbehaving plugins installed there.  So when it crashes Homebridge my main plugins keep running.  Also autostart via systemd will automatically restart after crashes.  For running a second instance, if google it, you should be able to find instructions
