### ISSUE TITLE
Error "Segmentation fault (core dumped)" when pairing with HomeBridge

### ISSUE THREAD

**Issue by crxdelsol** [nfarina/homebridge#199]
I have set up HomeBridge recently, already got the '**Segmentation fault**' error, today I tried again, after updating using '**npm update**'.
Still got the same error.

This is what terminal shows:

>   Accessory [Homebridge] Creating new AccessoryInfo for our HAP server +0ms
  Accessory [Homebridge] Creating new IdentifierCache +3ms
  EventedHTTPServer Server listening on port 51826 +11ms
  EventedHTTPServer [192.168.178.22] New connection from client +35s
  EventedHTTPServer [192.168.178.22] HTTP server listening on port 54826 +1ms
  EventedHTTPServer [192.168.178.22] HTTP request: /pair-setup +4ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-setup +1ms
  HAPServer [CC:22:3D:E3:CE:30] Pair step 1/5 +2ms
  EventedHTTPServer [192.168.178.22] HTTP Repsonse is finished +12ms
  EventedHTTPServer [192.168.178.22] HTTP request: /pair-setup +15s
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-setup +0ms
  HAPServer [CC:22:3D:E3:CE:30] Pair step 2/5 +1ms
  EventedHTTPServer [192.168.178.22] HTTP Repsonse is finished +13ms
  EventedHTTPServer [192.168.178.22] HTTP request: /pair-setup +96ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-setup +0ms
  HAPServer [CC:22:3D:E3:CE:30] Pair step 3/5 +1ms
  HAPServer [CC:22:3D:E3:CE:30] Pair step 4/5 +27ms
  HAPServer [CC:22:3D:E3:CE:30] Pair step 5/5 +2ms
  Accessory [Homebridge] Paired with client 528BC1C7-9E21-478D-9565-9AB658275B1E +4ms
  EventedHTTPServer [192.168.178.22] HTTP Repsonse is finished +6ms
  EventedHTTPServer [192.168.178.22] Client connection closed +42ms
  EventedHTTPServer [192.168.178.22] HTTP connection was closed +1ms
  EventedHTTPServer [192.168.178.22] HTTP server was closed +1ms
  EventedHTTPServer [192.168.178.22] New connection from client +14ms
  EventedHTTPServer [192.168.178.22] HTTP server listening on port 54826 +0ms
  EventedHTTPServer [192.168.178.22] HTTP request: /pair-verify +2ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +1ms
  HAPServer [CC:22:3D:E3:CE:30] Pair verify step 1/2 +1ms
**Segmentation fault (core dumped)**

**Comment by nfarina** [comment]
If you have recently updated to NodeJS 4.0, make sure you are running the latest version from master branch, and try deleting your `node_modules` folder and running `npm install` again to make sure everything is recompiled.

**Comment by crxdelsol** [comment]
I will try that.
Let you know seen when it's done.

**Comment by crxdelsol** [comment]
I removed the **node_modules** folder, and tried **npm install**, getting this at the end:

>npm ERR! Linux 3.13.0-32-generic
npm ERR! argv "/home/xbmc/.nvm/versions/node/v4.0.0/bin/node" "/home/xbmc/.nvm/versions/node/v4.0.0/bin/npm" "install"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE
>
npm ERR! curve25519@1.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the curve25519@1.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the curve25519 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls curve25519
npm ERR! There is likely additional logging output above.
>
npm ERR! Please include the following file with any support request:
npm ERR!     /home/xbmc/homebridge/npm-debug.log
