### ISSUE TITLE
SSH Client

### ISSUE THREAD

**Issue by iRayanKhan** [nfarina/homebridge#1990]
Hey y'all,
This isn't fully related to HomeBridge, but I run it off my Rpi 3B and Putty keeps closing the ssh connects (even with null packets sending and tcp on) this started happening to me for the past 3 days before that I'd have no issue. It'd tell me "Software caused connection abort". Is there a better ssh client or is windows just being stupid?

**Comment by Harwood** [comment]
Putty has historically been quite good. You could give [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10) a try as an alternative. 

However, to narrow down what is exactly what causing is your issue try running ssh with verbose `-v` to get a more detailed log.

**Comment by iRayanKhan** [comment]
Issue fixed, Windows just needed an update. This is why I prefer macOS but I take my MacBook to school.
