### ISSUE TITLE
Unable to install homebridge

### ISSUE THREAD

**Issue by D33ZE** [nfarina/homebridge#1992]
This is what happened when I entered "sudo npm install -g --unsafe-perm homebridge"
<img width="662" alt="screenshot 2018-09-11 at 6 53 55 pm" src="https://user-images.githubusercontent.com/31156954/45355859-260f8880-b5f4-11e8-996f-b8d9cce667a9.png">

**Comment by matass** [comment]
Your node version seems to be old. Try to update node

**Comment by D33ZE** [comment]
My version is v6.10.2

**Comment by denisinla** [comment]
Latest Node version is 10.10.0, with LTS being 8.12.0. You're definitely running an outdated version of Node.

**Comment by D33ZE** [comment]
How am I supposed to upgrade Node?

**Comment by D33ZE** [comment]
Thanks so much. It worked after I installed the latest version (10.10.0)

<img width="596" alt="screenshot 2018-09-12 at 5 02 26 pm" src="https://user-images.githubusercontent.com/31156954/45414327-a645f480-b6ad-11e8-8f46-cb6873ad87b3.png">

**Comment by denisinla** [comment]
@D33ZE you should probably close this issue since it was resolved.

Cheers!
