### ISSUE TITLE
Unable to update

### ISSUE THREAD

**Issue by TerrorSource** [nfarina/homebridge#1994]
Hi. I'm unable to update HomeBridge.

### Steps to Reproduce (for bugs)
Trying to update HomeBridge from 0.4.44 to 0.4.45 does not work via de webinterface of homebridge-config-ui-x v3.8.8. Update remains available after reloading.
Tried via CMD but does not work either, see output below.

### Homebridge Log / Command Output
```
pi@raspberrypi:~ $ sudo npm --no-update-notifier install --unsafe-perm homebridge@latest
npm WARN saveError ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN pi No description
npm WARN pi No repository field.
npm WARN pi No README data
npm WARN pi No license field.

+ homebridge@0.4.45
```

**Comment by brideone** [comment]
try sudo npm --no-update-notifier install -g --unsafe-perm homebridge@latest

**Comment by TerrorSource** [comment]
Fixed! Thanks @brideone 

pi@raspberrypi:~ $ sudo npm --no-update-notifier install -g --unsafe-perm homebridge@latest
/usr/local/bin/homebridge -> /usr/local/lib/node_modules/homebridge/bin/homebridge
+ homebridge@0.4.45
updated 1 package in 13.115s
