### ISSUE TITLE
installed node via nvm, but homebridge fails to start as a systemd service

### ISSUE THREAD

**Issue by FrothyDog** [nfarina/homebridge#1996]
The homebridge-harmonyhub plugin would not install globally so instead I tried installing node using nvm. It worked great. I was able to install homebridge and all plugins without needing root. I can invoke homebridge just fine from the command line, but when starting as a service it fails with this message -

homebridge[5072]: /usr/bin/env: ‘node’: No such file or directory

I have no idea where to begin with this one.

**Comment by ebaauw** [comment]
Looks like your service cannot find the `node` executable.  Make sure to set PATH correctly in the service definition and that you start homebridge under the correct user, with the correct HOME.
