### ISSUE TITLE
IOS home stuck on add Homebridge

### ISSUE THREAD

**Issue by alfienero** [nfarina/homebridge#1997]
Dear all,

I installed homebridge (0.4.45) on a Windows 7 machine following the tutorials. Homebridge is apparently running since it gives me back the QRCode.

As I try to pair with iphone or Ipad it says that homebridge is impossible to find. So I cancelled the persist folder and changed in the json the name, the macaddress, the pin and the port, rerun homebridge and both iphone and ipad are able to see Homebridge with QR code or PIN. As I click on the iphone (11.4.1 IOS) or ipad (11.4.3) to add it and confirm that is reliable even if not supported, it keeps trying to add and finally says that is not possible to add Homebridge both on iphone/ipad. Then I'm not able to see Homebridge again unless I do all over again the persist cancel and json modifications.

Any suggestions?

**Comment by iRayanKhan** [comment]
Can you paste your config here and into pastebin. Also ensure you are on the Same Wi-Fi network and Wi-Fi band (2.4g // 5g) as Homebridge.

**Comment by alfienero** [comment]
Thanks for your reply! The network is the same and only 2.4g is activated

Config was a downloaded standard one modified in name, macaddress, pin and port.

{
     "bridge": {
        "name": "GHomebri",
        "username": "CC:22:3D:E3:CE:99",
        "port": 51827,
        "pin": "031-45-135"
    },
    
    "description": "HomeBridge HTTP Status Control",

    "accessories": [ {
	        "accessory": "Http",
                "name": "Alfresco Lamp",
			"switchHandling": "realtime",
				"http_method": "GET",
				"on_url":      "http://localhost/controller/1700/ON",
				"off_url":     "http://localhost/controller/1700/OFF",
				"status_url":  "http://localhost/status/100059",				
			"service": "Light",
				"brightnessHandling": "yes",
				"brightness_url":     "http://localhost/controller/1707/%b",
				"brightnesslvl_url":  "http://localhost/status/100054"			
									    
       } 
    ]
}

**Comment by alfienero** [comment]
Update: I succedeed in pairing Homebridge in Home deleting the config.json.

Now I don't know which config.json I should use to start, any advice?

**Comment by alfienero** [comment]
Update 2: I used again a standard json, but doing this after pairing make it works. I also added a plugin to control the Xiaomi Vacuum Roborock and modified the config.json and I'm able to see it on Home!!! Thanks to everybody that worked on this stunning project!!!

Now I have to understand how to make Homebridge work when I'm not connected with my iphone in the same wifi in which Homebridge is.

**Comment by alfienero** [comment]
My windows is connected on wifi. I solved canceling the config.json, pairing and adding again a config.json, maybe it could work also for you

**Comment by mars7397** [comment]
i have some issue. but i use the homebridge on win10. 
It's be working.  But I cant find the homebridge on Iphone(home).
