### ISSUE TITLE
Home app on iPad not updated with new values from sensor. 

### ISSUE THREAD

**Issue by deadlyknapsack** [nfarina/homebridge#1999]
For a sensor - a Mi Flower - I am receiving humidity, fertility and temperature values on a specific interval. In this case every 10 seconds, for testing purposes. However, the Home app is not receiving these values, unless I manually tap somewhere in the Home app or when I open Home app on a second device (for example my iPhone). It seems to be that other values (although not thoroughly tested) get updated in the Home app with some kind of interval.

### Expected Behavior
I expected polled values to show in the Home app on a regular interval. Not necessarily the same interval als the plugin, but at least automated and without intervention. 

### Current Behavior
The logging of Homebridge shows the values coming in every 10 seconds. However, the Home app is not updated. Not even after 30 minutes. The moment I touch the app or a secondary device, the values get refreshed.

### Steps to Reproduce (for bugs)
Have Home app open on iPad or iPhone, have Homebridge open in terminal and not interfere.

### Versions

- **Homebridge**: 0.4.44
- **Node**:       v8.11.1
- **OS**:         Raspian

Edit: I did raise an issue with the creator of the plugin, but as this feels like a Homebridge vs Home app thing, I wanted to post it here as well.

**Comment by TKSondergaard** [comment]
I'm having the exact same problem with the "homebridge-gpio-device" plugin. The second i launch the Home App everything is updated. Including notifications.
