### ISSUE TITLE
Wink door lock?

### ISSUE THREAD

**Issue by fitzage** [nfarina/homebridge#200]
I have a door lock connected to my Wink hub. Does wink disallow access to these in the API or something? I understand if that's the case and wouldn't be surprised. Would be nice to be able to lock my door as part of my good night scene, but…

**Comment by pdlove** [comment]
I'm getting ready to look into what it will take to add Wink's categories of "Locks", "Binary Switch", "Thermostat" and "Garage Door Openers". I may not make very quick progress. If anyone else is already working on these, let me know and I'll just wait.

**Comment by KraigM** [comment]
Should be there now after my additions in #331

**Comment by AppleTechy** [comment]
Ok so I am all my devices going through Wink but most of the time it is faster to turn on the light or close the Garage door through the official app for that connected product. If I want to load my garage doors through the liftmaster plugin is there any way to stop/remove them from the Wink Plugin? Would it still be faster for me to control them from their official app or will it not make a difference now with the homebridge running will both services signal the device in similar timeframe?

**Comment by KraigM** [comment]
@AppleTechy assuming you are using the new plugin system, post this on the wink plugin repo

**Comment by AppleTechy** [comment]
@KraigM  can you post a link to the new plugin system... I don't know exactly what you mean by "new" plugin system but I assume I am using it I just don't know where u want me to post. Thanks!

**Comment by KraigM** [comment]
@AppleTechy https://github.com/nfarina/homebridge lol

**Comment by KraigM** [comment]
Wink Plugin: https://github.com/KraigM/homebridge-wink

**Comment by AppleTechy** [comment]
kraigm/homebridge-wink
