### ISSUE TITLE
Accesories "No Answer" on Ipad hub ios11.4.1 after a period on time

### ISSUE THREAD

**Issue by pplanteg** [nfarina/homebridge#2005]
### Expected Behavior
Ipad is the hub for my homebridge accessories so i can access from outside home.
My accessories are my light controlled by Sonoff device (with Tasmota) homebridge.
AND a Schlage Bolt (homekit compatible) for the door.

### Current Behavior
Since I've updated my ipad to IOS 11.4.1, all my homebridge devices becomme unreachable (in french "Pas de Reponse" so "No answer") after a variable period of time.
BUT the schalge bolt is still ok.
It's affect only the homebrige accessories.

to recover my homebridge accessories control from the ipad, I must quit home app on the Ipad (swap it up the screen), TURN OFF THE WIFI on ipad and then turn it up and relaunch home app.

I have to do it several time per day, and obviously when I'm out my home I can not do it...;)

### Steps to Reproduce (for bugs)
Just wait less than one hour for ipad to loss connection with homebrige accessories.

### Versions

- **Homebridge**: `0.4.45`
- **Node**:       `v8.9.4
`
- **OS**:         RPI 3B Raspbian GNU/Linux 9 (stretch)

### Configuration
{
  "accessories" : [
    {
      "accessory" : "BME280",
      "name_temperature" : "Temperature",
      "name_humidity" : "Humidity",
      "options" : {
        "i2cBusNo" : 1,
        "i2cAddress" : "0x76"
      },
      "name" : "Sensor"
    },
    {
      "accessory" : "MagicHome",
      "purewhite" : false,
      "name" : "Aquarium",
      "ip" : "192.168.1.148",
      "setup" : "RGBW"
    },
    {
      "accessory" : "MagicHome",
      "purewhite" : false,
      "name" : "Bureau",
      "ip" : "192.168.1.135",
      "setup" : "RGBW"
    },
    {
      "activityParameter" : "Online",
      "activityTopic" : "tele/Garage/LWT",
      "startCmd" : "cmnd/Garage/TelePeriod",
      "onValue" : "ON",
      "switchType" : "bulb",
      "offValue" : "OFF",
      "startParameter" : "60",
      "url" : "mqtt://raspberrypi",
      "password" : "Password",
      "topics" : {
        "stateGet" : "tele/Garage/STATE",
        "statusGet" : "stat/Garage/RESULT",
        "statusSet" : "cmnd/Garage/POWER"
      },
      "manufacturer" : "ITEAD",
      "username" : "sonoff",
      "serialNumberMAC" : "MAC OR SERIAL NUMBER OR EMPTY",
      "accessory" : "mqtt-switch-tasmota",
      "model" : "Sonoff",
      "name" : "Garage"
    },
  ],
  "bridge" : {
    "username" : "CD:22:3D:E3:CE:69",
    "name" : "Homebridge",
    "pin" : "031-45-348",
    "port" : 51826
  },
  "platforms" : [
    {
      "port" : "1883",
      "password" : "bar",
      "topic_prefix" : "homebridge",
      "qos" : 1,
      "platform" : "mqtt",
      "username" : "foo",
      "topic_type" : "multiple",
      "name" : "mqtt",
      "url" : "mqtt://192.168.1.104"
    }
  ]
}
### Homebridge Log / Command Output

LOG AT THE TIME OFF IPAD SHOWING THE "UNREACHABLE" message (192.168.1.128 is the Ipad)

Wed, 19 Sep 2018 11:54:25 GMT Accessory [Homebridge] Registering Characteristic "Current Relative Humidity" for events
Wed, 19 Sep 2018 11:54:25 GMT EventedHTTPServer [::ffff:192.168.1.128] HTTP Response is finished
Wed, 19 Sep 2018 11:54:26 GMT EventedHTTPServer [::ffff:192.168.1.128] HTTP request: /characteristics
Wed, 19 Sep 2018 11:54:26 GMT HAPServer [CD:22:3D:E3:CE:69] HAP Request: PUT /characteristics
Wed, 19 Sep 2018 11:54:26 GMT Accessory [Homebridge] Processing characteristic set: [{"aid":9,"iid":10,"ev":true},{"aid":9,"iid":11,"ev":true}]
Wed, 19 Sep 2018 11:54:26 GMT Accessory [Homebridge] Registering Characteristic "On" for events
Wed, 19 Sep 2018 11:54:26 GMT Accessory [Homebridge] Registering Characteristic "Status Active" for events
Wed, 19 Sep 2018 11:54:26 GMT EventedHTTPServer [::ffff:192.168.1.128] HTTP Response is finished
Wed, 19 Sep 2018 11:54:26 GMT EventedHTTPServer [::ffff:192.168.1.128] HTTP request: /characteristics
Wed, 19 Sep 2018 11:54:26 GMT HAPServer [CD:22:3D:E3:CE:69] HAP Request: PUT /characteristics
Wed, 19 Sep 2018 11:54:26 GMT Accessory [Homebridge] Processing characteristic set: [{"aid":7,"iid":10,"ev":true},{"aid":7,"iid":11,"ev":true}]
Wed, 19 Sep 2018 11:54:26 GMT Accessory [Homebridge] Registering Characteristic "On" for events
Wed, 19 Sep 2018 11:54:26 GMT Accessory [Homebridge] Registering Characteristic "Status Active" for events
Wed, 19 Sep 2018 11:54:26 GMT EventedHTTPServer [::ffff:192.168.1.128] HTTP Response is finished
Wed, 19 Sep 2018 11:54:26 GMT EventedHTTPServer [::ffff:192.168.1.128] HTTP request: /characteristics
Wed, 19 Sep 2018 11:54:26 GMT HAPServer [CD:22:3D:E3:CE:69] HAP Request: PUT /characteristics
Wed, 19 Sep 2018 11:54:26 GMT Accessory [Homebridge] Processing characteristic set: [{"aid":22,"iid":10,"ev":true},{"aid":22,"iid":11,"ev":true}]
Wed, 19 Sep 2018 11:54:26 GMT Accessory [Homebridge] Registering Characteristic "On" for events
Wed, 19 Sep 2018 11:54:26 GMT Accessory [Homebridge] Registering Characteristic "Status Active" for events
Wed, 19 Sep 2018 11:54:26 GMT EventedHTTPServer [::ffff:192.168.1.128] HTTP Response is finished
Wed, 19 Sep 2018 11:54:26 GMT EventedHTTPServer [::ffff:192.168.1.128] HTTP request: /characteristics?id=16.10,14.10,19.10,18.10,12.10,20.10,13.10,6.10,8.10,23.10,5.10,17.10,11.10,4.11,4.12,4.10,4.13,10.10,22.10,3.10,15.10,2.10,9.10,7.10
Wed, 19 Sep 2018 11:54:26 GMT HAPServer [CD:22:3D:E3:CE:69] HAP Request: GET /characteristics?id=16.10,14.10,19.10,18.10,12.10,20.10,13.10,6.10,8.10,23.10,5.10,17.10,11.10,4.11,4.12,4.10,4.13,10.10,22.10,3.10,15.10,2.10,9.10,7.10
Wed, 19 Sep 2018 11:54:26 GMT Accessory [Homebridge] Getting value for Characteristic "On"
Wed, 19 Sep 2018 11:54:26 GMT Accessory [Homebridge] Got Characteristic "On" value: false
Wed, 19 Sep 2018 11:54:26 GMT Accessory [Homebridge] Getting value for Characteristic "On"
Wed, 19 Sep 2018 11:54:26 GMT Accessory [Homebridge] Got Characteristic "On" value: false
Wed, 19 Sep 2018 11:54:26 GMT Accessory [Homebridge] Getting value for Characteristic "On"
Wed, 19 Sep 2018 11:54:26 GMT Accessory [Homebridge] Got Characteristic "On" value: false
Wed, 19 Sep 2018 11:54:26 GMT Accessory [Homebridge] Getting value for Characteristic "On"
Wed, 19 Sep 2018 11:54:26 GMT Accessory [Homebridge] Got Characteristic "On" value: false
Wed, 19 Sep 2018 11:54:26 GMT Accessory [Homebridge] Getting value for Characteristic "On"
Wed, 19 Sep 2018 11:54:26 GMT Accessory [Homebridge] Got Characteristic "On" value: false
Wed, 19 Sep 2018 11:54:26 GMT Accessory [Homebridge] Getting value for Characteristic "Current Temperature"
Wed, 19 Sep 2018 11:54:26 GMT Accessory [Homebridge] Got Characteristic "Current Temperature" value: 22.6
Wed, 19 Sep 2018 11:54:26 GMT Accessory [Homebridge] Getting value for Characteristic "On"
Wed, 19 Sep 2018 11:54:26 GMT Accessory [Homebridge] Got Characteristic "On" value: false
Wed, 19 Sep 2018 11:54:26 GMT Accessory [Homebridge] Getting value for Characteristic "On"
Wed, 19 Sep 2018 11:54:26 GMT Accessory [Homebridge] Got Characteristic "On" value: false
Wed, 19 Sep 2018 11:54:26 GMT Accessory [Homebridge] Getting value for Characteristic "On"
Wed, 19 Sep 2018 11:54:26 GMT Accessory [Homebridge] Got Characteristic "On" value: false
Wed, 19 Sep 2018 11:54:26 GMT Accessory [Homebridge] Getting value for Characteristic "On"
Wed, 19 Sep 2018 11:54:26 GMT Accessory [Homebridge] Got Characteristic "On" value: false
Wed, 19 Sep 2018 11:54:26 GMT Accessory [Homebridge] Getting value for Characteristic "On"
Wed, 19 Sep 2018 11:54:26 GMT Accessory [Homebridge] Got Characteristic "On" value: false
Wed, 19 Sep 2018 11:54:26 GMT Accessory [Homebridge] Getting value for Characteristic "On"
Wed, 19 Sep 2018 11:54:26 GMT Accessory [Homebridge] Got Characteristic "On" value: false
Wed, 19 Sep 2018 11:54:26 GMT Accessory [Homebridge] Getting value for Characteristic "On"
Wed, 19 Sep 2018 11:54:26 GMT Accessory [Homebridge] Got Characteristic "On" value: false
Wed, 19 Sep 2018 11:54:26 GMT Accessory [Homebridge] Getting value for Characteristic "Hue"
Wed, 19 Sep 2018 11:54:26 GMT Accessory [Homebridge] Got Characteristic "Hue" value: 255
Wed, 19 Sep 2018 11:54:26 GMT Accessory [Homebridge] Getting value for Characteristic "Saturation"
Wed, 19 Sep 2018 11:54:26 GMT Accessory [Homebridge] Got Characteristic "Saturation" value: 100
Wed, 19 Sep 2018 11:54:26 GMT Accessory [Homebridge] Getting value for Characteristic "On"
Wed, 19 Sep 2018 11:54:26 GMT Accessory [Homebridge] Getting value for Characteristic "Brightness"
Wed, 19 Sep 2018 11:54:26 GMT Accessory [Homebridge] Got Characteristic "Brightness" value: 100
Wed, 19 Sep 2018 11:54:26 GMT Accessory [Homebridge] Getting value for Characteristic "On"
Wed, 19 Sep 2018 11:54:26 GMT Accessory [Homebridge] Got Characteristic "On" value: false
Wed, 19 Sep 2018 11:54:26 GMT Accessory [Homebridge] Getting value for Characteristic "On"
Wed, 19 Sep 2018 11:54:26 GMT Accessory [Homebridge] Got Characteristic "On" value: false
Wed, 19 Sep 2018 11:54:26 GMT Accessory [Homebridge] Getting value for Characteristic "On"
Wed, 19 Sep 2018 11:54:26 GMT Accessory [Homebridge] Getting value for Characteristic "On"
Wed, 19 Sep 2018 11:54:26 GMT Accessory [Homebridge] Got Characteristic "On" value: false
Wed, 19 Sep 2018 11:54:26 GMT Accessory [Homebridge] Getting value for Characteristic "Current Temperature"
Wed, 19 Sep 2018 11:54:26 GMT Accessory [Homebridge] Getting value for Characteristic "On"
Wed, 19 Sep 2018 11:54:26 GMT Accessory [Homebridge] Got Characteristic "On" value: false
Wed, 19 Sep 2018 11:54:26 GMT Accessory [Homebridge] Getting value for Characteristic "On"
Wed, 19 Sep 2018 11:54:26 GMT Accessory [Homebridge] Got Characteristic "On" value: false
Wed, 19 Sep 2018 11:54:26 GMT Accessory [Homebridge] Got Characteristic "Current Temperature" value: 24
Wed, 19 Sep 2018 11:54:26 GMT Accessory [Homebridge] Got Characteristic "On" value: true
Wed, 19 Sep 2018 11:54:26 GMT Accessory [Homebridge] Got Characteristic "On" value: true
Wed, 19 Sep 2018 11:54:26 GMT EventedHTTPServer [::ffff:192.168.1.128] HTTP Response is finished
Wed, 19 Sep 2018 11:55:06 GMT EventedHTTPServer [::ffff:192.168.1.72] Sending HTTP event 'keepalive' with data: {"characteristics":[]}
Wed, 19 Sep 2018 11:55:06 GMT EventedHTTPServer [::ffff:192.168.1.128] Sending HTTP event 'keepalive' with data: {"characteristics":[]}
Wed, 19 Sep 2018 11:55:06 GMT EventedHTTPServer [::ffff:192.168.1.127] Sending HTTP event 'keepalive' with data: {"characteristics":[]}
Wed, 19 Sep 2018 11:55:06 GMT BME280 Polling BME280
Wed, 19 Sep 2018 11:55:08 GMT EventedHTTPServer [::ffff:192.168.1.127] Client connection closed
Wed, 19 Sep 2018 11:55:08 GMT EventedHTTPServer [::ffff:192.168.1.127] HTTP connection was closed
Wed, 19 Sep 2018 11:55:08 GMT EventedHTTPServer [::ffff:192.168.1.127] HTTP server was closed

**Comment by skywalker1979** [comment]
are you on unifi access points?

**Comment by pplanteg** [comment]
Everything back to normal since iOS 12 update on iPad witch is being use as hub
