### ISSUE TITLE
Problem with conexion 

### ISSUE THREAD

**Issue by ZoltXs** [nfarina/homebridge#2009]
Hello, I have a problem, I currently have Homebridge running on Mac OsX, all right, but I would like Homebridge to run on raspberry. I made homebridge in raspberry but when I add the accessories to Homebridge raspberry, everything gives me error, I can not run, I use the same file but change port number, PIN, username and name. I don't understand the reason for the mistake. I tried to restore factory router and nothing, someone could help me??
Thanks

**Comment by rcmoraes** [comment]
Same Problem Here
