### ISSUE TITLE
How to avoid homebridge from dying

### ISSUE THREAD

**Issue by sansari1959** [nfarina/homebridge#2011]
Hi,

I've been running homebridge on my Mac mini for weeks. Never once did it die on me. I just switched to a Raspberry Pi and overnight the processor died. What can I do to avoid that, and has anyone had similar behavior?

One important detail. I started homebridge as a background process through a terminal window from another machine. The terminal window closed after a while. Could that be the cause? If so, could the remedy be to start a homebridge process directly on the Raspberry Pi itself in background mode? Obviously that's what I did on my Mac mini.

**Comment by sansari1959** [comment]
Answering my own question: Will a nohup command to run homebridge in the background permanently remedy the problem?

**Comment by sansari1959** [comment]
Just to say, that the nohup did not help. Homebridge stopped responding minutes after I started it. Others seem to have had the same issue a couple of months ago with no conclusion on the standard Raspian image. Has anyone encountered similar behavior recently?

**Comment by timanrebel** [comment]
I setup a systemd service: https://gist.github.com/johannrichard/0ad0de1feb6adb9eb61a/ and that seems to work well..

**Comment by sansari1959** [comment]
Not quite what I was looking for, although extremely useful.

It's not thet the Raspberry Pi crashed, it's the Homebridge process that appears to have crashed.

**Comment by iRayanKhan** [comment]
Paste your config, make sure to Redact any personal info.
Also are you ssh'ing into your pi? If so make sure your client for SSH sends "Null" packets to your Pi because some ISP's will close the connection to prevent "spam" and such. Also ensure port 22 isn't blocked (Or the ssh port you are using).
