### ISSUE TITLE
Request/Advice: Sprinklers

### ISSUE THREAD

**Issue by iRayanKhan** [nfarina/homebridge#2012]
Hello Everyone,

I have been using HomeBridge for the past 3 months and it's bloody brilliant.

I have recently wanted to connect sprinklers to HomeKit and I have found very little on Youtube and Google of HomeKit sprinklers (I heard of Ranchio, but haven't found a plugin). The videos I have seen are involving electrical work or using "HomeKit Switches" instead of valve type = 1 (or 2 idk which 1 is faucet.) If anyone could point me in the right direction to plugins with sprinklers that'd be great! 
(I Also have no Wi-Fi/Smart Sprinklers so I can buy hardware down the road.)

**Comment by troystanway** [comment]
Hi!
I'm using a OpenSprinkler PI hat for another raspberry pi to control upto 8 zones.
At the moment I'm using php scripts and a Hombridge http plugin to expose standard switches to control them.
I'm looking to develop a specific plugin for OpenSprinkler to use the correct sprinkler accessory type, something that will be quite a challenge for myself.
If your interested to learn more, I could show you the current configuration I use, but it does require an OpenSprinker.

**Comment by iRayanKhan** [comment]
Thanks for reply! I now see there are native sprinklers on the market and my current system isn't capable of any Wi-Fi BLE connections. Closed: Resolved
