### ISSUE TITLE
Triggering NON Homebridge / Official HomeKit Devices via the Command Line (via a Mac)

### ISSUE THREAD

**Issue by twentyNoise** [nfarina/homebridge#2017]
Hi,

Is there a way / or a plugin to trigger HomeKit accessories that are NOT connected to HomeBridge, but officially supported by HomeKit (and in my current HomeKit setup) via the command line?

If there is no way official support for this with Homebridge, would this be possible by writing a specific Homebridge Plugin?

I have the need to integrate powering on / off switches into my setup via scripting (so backup routines, work routines are all automated). Currently I am using the "Type to Siri" function in Mojave to send Siri commands - but ultimately this is not the most reliable way to trigger devices, nor is it the fastest.

Thanks!

**Comment by ebaauw** [comment]
> Is there a way / or a plugin to trigger HomeKit accessories that are NOT connected to HomeBridge, but officially supported by HomeKit (and in my current HomeKit setup) via the command line?

No.  You can only access HomeKit accessories through the HomeKit API from iOS devices.  In other words: you need and iOS HomeKit app.

> would this be possible by writing a specific Homebridge Plugin?

No.

> I have the need to integrate powering on / off switches into my setup

You can use HomeKit automations to set an action to "any" HomeKit accessory, triggered by "any other" HomeKit accessory.  You need a home hub for this to work, though, see https://support.apple.com/en-us/HT207057.

**Comment by twentyNoise** [comment]
> > Is there a way / or a plugin to trigger HomeKit accessories that are NOT connected to HomeBridge, but officially supported by HomeKit (and in my current HomeKit setup) via the command line?
> 
> No. You can only access HomeKit accessories through the HomeKit API from iOS devices. In other words: you need and iOS HomeKit app.
> 
> > would this be possible by writing a specific Homebridge Plugin?
> 
> No.
> 
> > I have the need to integrate powering on / off switches into my setup
> 
> You can use HomeKit automations to set an action to "any" HomeKit accessory, triggered by "any other" HomeKit accessory. You need a home hub for this to work, though, see https://support.apple.com/en-us/HT207057.

Thanks ebaauw.

Right, the HomeKit API for iOS, that makes sense.

The next easiest solution is "Type to Siri" in Mojave, or better still, Apple released a Siri SDK for Mojave, so HomeKit control is possible with both of these solutions - albeit a bit slower.

I do have plenty of HomeKit automations but basically I need a way for a bash script to turn off a HomeKit switch (Hard Disk) after a backup occurs. Or turn off a switch to a Mac once it has been shutdown, in order to trigger the remote cold boot function. Again, for the time being I guess "Type to Siri" will have to do.

The other option would be to buy an unsupported WIFI switch that can be added to HomeBridge, and then trigger that switch via a script / command line.

Thanks for the info.

**Comment by iRayanKhan** [comment]
@ebaauw You mind checking out: https://github.com/KhaosT/homebridge-camera-ffmpeg/issues/213

**Comment by ebaauw** [comment]
> I need a way for a bash script to turn off a HomeKit switch (Hard Disk) after a backup occurs.

I would use a CLIPGenericFlag on my Hue bridge, or deCONZ gateway, exposed to HomeKit by homebridge-hue, as a switch.  I'd set the flag from a macOS bash script (or any other system) using `ph put` (even `curl` will do).  See https://github.com/ebaauw/homebridge-hue/wiki/Getting-Started#24-clip-sensors.

I suppose any homebridge plugin exposing a dummy switch and providing a way to control it from a bash script (or REST API) would do the trick here.  I'm afraid I don't know any others, though.

> Or turn off a switch to a Mac once it has been shutdown, in order to trigger the remote cold boot function. Again, for the time being I guess "Type to Siri" will have to do.

That's a fun one: how to detect that the mac has shutdown?  You could use a smart plug that reports the current consumption, or run a script on another mac (or Raspberry) that `ping`s the mac (although it wouldn't know the difference between shut down and a network detach, or issue something from the mac, just before shut down.

**Comment by ebaauw** [comment]
> You mind checking out: KhaosT/homebridge-camera-ffmpeg#213

I have no clue about that one; I don't have any homebridge cameras.

**Comment by twentyNoise** [comment]
> I would use a CLIPGenericFlag on my Hue bridge, or deCONZ gateway, exposed to HomeKit by homebridge-hue, as a switch. I'd set the flag from a macOS bash script (or any other system) using `ph put` (even `curl` will do). See https://github.com/ebaauw/homebridge-hue/wiki/Getting-Started#24-clip-sensors.
> 

Noted! Thanks!

> > Or turn off a switch to a Mac once it has been shutdown, in order to trigger the remote cold boot function. Again, for the time being I guess "Type to Siri" will have to do.
> 
> That's a fun one: how to detect that the mac has shutdown? You could use a smart plug that reports the current consumption, or run a script on another mac (or Raspberry) that `ping`s the mac (although it wouldn't know the difference between shut down and a network detach, or issue something from the mac, just before shut down.

Exactly, right now I have the Mac Pro triggering a Macro on a Mac Mini that pings the Mac Pro and once it fails it pauses for 20 seconds to be sure the Mac is off and then the Mac Mini has Siri turn off the device. What would be best here is if the Macro could get access to the iDevices Switch power consumption and once the power draw is less than a specified amount - turn the switch off. But that's probably unnecessary, though this would be a great automation trigger for them to add to their iOS app - this goes for all switches.

For the time being it all works well - but we'll have to see about longevity and again, how reliable Type to Siri will be (so far so good with the help of Keyboard Maestro). The other issue is that I don't have any way to get 'feedback' from Siri if she can't connect to the switch etc. I was thinking there has to be logs somewhere for Siri but I'll have to do more research into that.

Thanks again for all the ideas!

**Comment by henrik** [comment]
[HomeControl Menu for HomeKit](https://apps.apple.com/gb/app/homecontrol-menu-for-homekit/id1547121417?mt=12) can do this – it lets you trigger HomeKit devices via a URL scheme.
