### ISSUE TITLE
package.json dependencies

### ISSUE THREAD

**Issue by cflurin** [nfarina/homebridge#202]
@nfarina:
Is there a reason, why you've defined a commit-ish suffix for the hap-nodejs dependency?
The default is Master and should install the latest version.

**Comment by snowdd1** [comment]
When HAP-nodeJS changes, Nick wants to make sure that homebridge is capable of the changes. So he adds each tested commit point.

**Comment by cflurin** [comment]
@snowdd1: This is a reason, otherwise I've seen users getting troubles, because the homebridge package.json wasn't updated and the "old" HAP-NodeJS was installed instead of the new one.

**Comment by nfarina** [comment]
If HAP-NodeJS were in npm with semver, then we could automatically get bug fixes by requiring "^1.3.x" or similar - but since it's a git dependency, we don't know when it may change in a way that breaks homebridge. So we need to pin it to the last specific version that is "verified good".

**Comment by cflurin** [comment]
I've read about publishing on npm, it seems to be easy. Let see what the future will bring.

**Comment by snowdd1** [comment]
@KhaosT is there a reason why it's not?
