### ISSUE TITLE
No response in Rooms, but Correct Status in Favorites

### ISSUE THREAD

**Issue by anupchavda1** [nfarina/homebridge#2020]
Strange issue, whereby when i use the Home Control Centre "Favourites" my Homebridged appliances report the correct status, but when i go into the actual Home App, everything indicates "updating" for about 60 seconds and then reverts to "Not Responding".

I've done a fresh install on Ubuntu Mate 18.04 and a seperate install on a Rpi using the directions here. i'm using an Apple Airport Extreme tied with BT Home Disk Mesh Wifi.

Any ideas about what i can investigate to get this to work correctly? I keep seeing reference to mdns and bonjour but not sure how to correct these.

Thanks

**Comment by iRayanKhan** [comment]
This happens to me but it eventually fixes it self. Are they on the Same Wi-Fi network and band? Also is there any HomeHubs?

**Comment by anupchavda1** [comment]
Resolved by rebuilding my entire implementation. now works extremely well.
