### ISSUE TITLE
Homebridge MQTT not updating state

### ISSUE THREAD

**Issue by Kepete** [nfarina/homebridge#2021]
I have setup different sensors and switches with MQTT. At first it worked great, the status of the switch is instantly updated over MQTT if the switch is used manually.
But now I have discovered that after a while it will not update the status anymore. I can still toggle the switch, turn it on and off, but manual switch toggling won't change the status in Homa app. 
It works after every homebridge restart for few hours and then status updates stop. 
I also have a temperature plugin, same problem there. Temperature readings are sent over MQTT. After a while it just won't update the temperature and show still the sensor as online. 

It is not a plugin problem(what I was thinking about first) because different plugins have the same issue. 

All MQTT messages are sent, I can confirm it from the MQTT broker side. 

### Versions

- **Homebridge**: 0.4.38
- **Node**:       8.9.4
- **OS**:           Raspbian GNU/Linux 9 (stretch)

### Configuration

```json
{
            "accessory": "mqtt-switch-tasmota",
            "switchType": "lightbulb",
            "name": "Test",
            "url": "mqtt://1.1.1.1",
            "username": "usr",
            "password": "pswd",
            "topics": {
                "statusGet": "stat/sonoff_test/POWER2",
                "statusSet": "cmnd/sonoff_test/POWER2",
                "stateGet": "tele/sonoff_test/STATE"
            },
            "onValue": "ON",
            "offValue": "OFF",
            "activityTopic": "tele/sonoff_test/LWT",
            "activityParameter": "Online",
            "startCmd": "cmnd/sonoff_test/TelePeriod",
            "startParameter": "60",
            "manufacturer": "ITEAD",
            "model": "Sonoff",
            "serialNumberMAC": "sonoff"
        },        
        {
            "accessory": "mqtt-temperature-tasmota",
            "name": "Test2",
            "url": "mqtt://1.1.1.1",
            "username": "usr",
            "password": "pswd",
            "topic": "tele/sonoff_test2/SENSOR",
            "activityTopic": "tele/sonoff_test2/LWT",
            "activityParameter": "Online",
            "startCmd": "cmnd/sonoff_test2/TelePeriod",
            "startParameter": "60",
            "sensorPropertyName": "DS18B20",
            "manufacturer": "ITEAD",
            "model": "Sonoff TH",
            "serialNumberMAC": "sonoff_test2"
        },
```

### Homebridge Log / Command Output

Couldn't find the log file at /var/log/homebridge.log
Will update it when I find the logs. 

```

```

**Comment by aleksandrsivanovs** [comment]
for me the same problems occur using  mqtt plugins for temperature and humidity:
https://github.com/mcchots/homebridge-mqtt-temperature
https://github.com/mcchots/homebridge-mqtt-humidity

at some point it just sticks to some old values and does not update to the new values
only restart of homebridge helps.

**Comment by Kepete** [comment]
At first I also thought it would be a plugin problem. But as we are all using different plugins it seems more like a homebridge problem now. 
Could I know what version of homebridge/node/OS are you running ?

**Comment by bartoszwas** [comment]
I got the same problem. 

Homebridge running on latest Mac OS Sierra (10.12). After some time, usually 2-3 days Homebridge stops updating statuses. All of them, I got three Sonoff T1 switches 2 with DS18B20, and two sonoff basic with DS18B20 latest Tasmota installed. Stuff is sending values via mqqt but Homebridge is not updating till reboot.

**Comment by mcchots** [comment]
Until now I have not seen this issue. However today I noticed incorrect readings on one of my sensors.
I don't think this is an issue with mqtt but with homebridge itself.  

This is my log:
<pre><code>
[10/12/2018, 3:18:17 PM] [Freezer Three] Sending MQTT.Temperature: 22
[10/12/2018, 3:18:32 PM] [Freezer One] Sending MQTT.Temperature: 23
[10/12/2018, 3:18:32 PM] [Freezer Two] Sending MQTT.Temperature: 25
[10/12/2018, 3:18:32 PM] [Freezer Three] Sending MQTT.Temperature: 22
  EventedHTTPServer [::ffff:192.168.1.103] HTTP request: /characteristics?id=2.10,4.10,3.10 +41s
  HAPServer [CD:E2:3E:A3:CE:3A] HAP Request: GET /characteristics?id=2.10,4.10,3.10 +0ms
  Accessory [Work Bridge] Getting value for Characteristic "Current Temperature" +2ms
[10/12/2018, 3:18:36 PM] [Freezer One] Get Temperature Called: 23
  Accessory [Work Bridge] Got Characteristic "Current Temperature" value: 23 +2ms
  Accessory [Work Bridge] Getting value for Characteristic "Current Temperature" +0ms
<b>[10/12/2018, 3:18:36 PM] [Freezer Three] Get Temperature Called: 22
  Accessory [Work Bridge] Got Characteristic "Current Temperature" value: 20 +2ms</b>
  Accessory [Work Bridge] Getting value for Characteristic "Current Temperature" +0ms
[10/12/2018, 3:18:36 PM] [Freezer Two] Get Temperature Called: 25
  Accessory [Work Bridge] Got Characteristic "Current Temperature" value: 25 +2ms
  EventedHTTPServer [::ffff:192.168.1.103] HTTP Response is finished +1ms
[10/12/2018, 3:18:47 PM] [Freezer One] Sending MQTT.Temperature: 23
[10/12/2018, 3:18:47 PM] [Freezer Two] Sending MQTT.Temperature: 25
[10/12/2018, 3:18:47 PM] [Freezer Three] Sending MQTT.Temperature: 22
</code></pre>

According to this, the plugin is sending the correct temperature, but homebridge has a different value.
What's really weird is I have restarted homebridge, the PC and re-added the bridge on iOS and get the same value of 20 all the time, but only for the one sensor.

**Comment by AMTNate** [comment]
Are you using a local MQTT server or a something like cloudMQTT? I'm having the same problem, and I'm wondering if its because I'm using cloudMQTT.

**Comment by AMTNate** [comment]
Update: I switched from CloudMQTT to Mosquitto and I haven’t had any problems with the state not updating since then.

**Comment by Kepete** [comment]
I have been using Mosquitto all the time. Furthermore, for me the broker is sending the messages correctly so it should be a broker issue.

**Comment by Kepete** [comment]
There are a lot more people experiencing the problem.
Still not sure if a plugin, broker or homebridge issue, but seems more like homebridge.

https://github.com/MacWyznawca/homebridge-mqtt-switch-tasmota/issues/49#

**Comment by bartoszwas** [comment]
For me it seems to be homebridge too... For me it happens every time i restart the router. Homebridge works for few minutes and its stuck. MQTT (Mosquitto) works fine.

My server is hackintosh on Sierra and I've made a simple Mac OS app in Swift that is checking lan connection every 20 seconds, when lan is down it waits till gets up and restarts the Homebridge. Im testing it for few days and for now homebridge works fine, but I have done many restarts through this time.

**Comment by NorthernMan54** [comment]
Is the IP address of your machine changing as part of this?

Am thinking that a changing IP address may contribute to this

**Comment by Kepete** [comment]
I haven't noticed that it is related to router down time. But I will investigate that. 
Also in my setup I have static IP mapped to the homebridge machine.

**Comment by bartoszwas** [comment]
Mine homebridge machine is static IP too. I suppose one more thing- an mDNS but I haven't check that. I was planning too turn off mDNS in all Sonoffs but for now i will leave that on.

**Comment by bartoszwas** [comment]
Today it got stuck anyway.

I wonder is there any other plugin for sonoffs?
Sonoff’s github page says there’s a mqttthing plugin but i can’t get it work... 😐

**Comment by nfarina** [comment]
Sounds like a tricky issue to diagnose. I looked at the source of `mqtt-switch-tasmota` and it looks pretty straightforward - basically a bridge between the `mqtt` module and Homebridge. I would probably be most suspicious of HomeKit's connection with Homebridge. Do you have an Apple TV that is serving as the bridge?

**Comment by NorthernMan54** [comment]
@Kepete As nick indicated, maybe you can do some digging to get to the bottom of this, as there are a lot of moving parts in the setup, and getting to the actual component would be useful

Home App <===> Apple TV <===> HomeBridge <===> Plugin <===> MQTT <===> Device

The logs from homebridge in DEBUG mode give a lot of details of the communications both up and downstream, looking at those when the problems occur should give some clues into which component is challenging.  From my experience, with a good running setup, homebridge and the upstream components are rock solid, and majority of the problems are from the plugin down to the actual device.

**Comment by NorthernMan54** [comment]
Looking at the log, the last entry appears to be a successful request from your .31 device to update status on numerous devices.   Did that display correctly on that device?

```
Sun, 06 Jan 2019 13:20:25 GMT EventedHTTPServer [::ffff:192.168.88.31] HTTP request: /characteristics?id=57.10,56.10,32.10,2.10,4.10,51.10,41.10,55.10,22.10,42.10,31.10,54.10
Sun, 06 Jan 2019 13:20:25 GMT HAPServer [CC:33:3D:E3:CE:30] HAP Request: GET /characteristics?id=57.10,56.10,32.10,2.10,4.10,51.10,41.10,55.10,22.10,42.10,31.10,54.10
Sun, 06 Jan 2019 13:20:25 GMT Accessory [Homebridge] Getting value for Characteristic "Current Temperature"
Sun, 06 Jan 2019 13:20:25 GMT Accessory [Homebridge] Got Characteristic "Current Temperature" value: 20.1
Sun, 06 Jan 2019 13:20:25 GMT Accessory [Homebridge] Getting value for Characteristic "Current Temperature"
Sun, 06 Jan 2019 13:20:25 GMT Accessory [Homebridge] Got Characteristic "Current Temperature" value: 47.6
Sun, 06 Jan 2019 13:20:25 GMT Accessory [Homebridge] Getting value for Characteristic "On"
Sun, 06 Jan 2019 13:20:25 GMT Accessory [Homebridge] Got Characteristic "On" value: false
Sun, 06 Jan 2019 13:20:25 GMT Accessory [Homebridge] Getting value for Characteristic "On"
Sun, 06 Jan 2019 13:20:25 GMT Accessory [Homebridge] Got Characteristic "On" value: false
Sun, 06 Jan 2019 13:20:25 GMT Accessory [Homebridge] Getting value for Characteristic "On"
Sun, 06 Jan 2019 13:20:25 GMT Accessory [Homebridge] Got Characteristic "On" value: false
Sun, 06 Jan 2019 13:20:25 GMT Accessory [Homebridge] Getting value for Characteristic "On"
Sun, 06 Jan 2019 13:20:25 GMT Accessory [Homebridge] Got Characteristic "On" value: false
Sun, 06 Jan 2019 13:20:25 GMT Accessory [Homebridge] Getting value for Characteristic "On"
Sun, 06 Jan 2019 13:20:25 GMT Accessory [Homebridge] Got Characteristic "On" value: false
Sun, 06 Jan 2019 13:20:25 GMT Accessory [Homebridge] Getting value for Characteristic "Current Temperature"
Sun, 06 Jan 2019 13:20:25 GMT Accessory [Homebridge] Got Characteristic "Current Temperature" value: 20.4
Sun, 06 Jan 2019 13:20:25 GMT Accessory [Homebridge] Getting value for Characteristic "Motion Detected"
Sun, 06 Jan 2019 13:20:25 GMT Accessory [Homebridge] Got Characteristic "Motion Detected" value: false
Sun, 06 Jan 2019 13:20:25 GMT Accessory [Homebridge] Getting value for Characteristic "On"
Sun, 06 Jan 2019 13:20:25 GMT Accessory [Homebridge] Got Characteristic "On" value: false
Sun, 06 Jan 2019 13:20:25 GMT Accessory [Homebridge] Getting value for Characteristic "On"
Sun, 06 Jan 2019 13:20:25 GMT Accessory [Homebridge] Got Characteristic "On" value: false
Sun, 06 Jan 2019 13:20:25 GMT Accessory [Homebridge] Getting value for Characteristic "Current Temperature"
Sun, 06 Jan 2019 13:20:25 GMT Accessory [Homebridge] Got Characteristic "Current Temperature" value: -3.2
Sun, 06 Jan 2019 13:20:25 GMT EventedHTTPServer [::ffff:192.168.88.31] HTTP Response is finished
```

**Comment by bartoszwas** [comment]
They were different and i think nothing happend in log when i turned on a switch. For now i restarted homebridge do it’s working fine for now.

**Comment by NorthernMan54** [comment]
There may be 2 different things going one here, one being homebridge to the home app, and the second being homebridge to your device.  Please keep that in mind.

**Comment by bartoszwas** [comment]
I did some research today and every time I reset the router homebridge gets stuck dunno why.

homebridge is running on macOS Sierra, node 11.1.0, npm 6.4.1, homebridge 0.4.45
Here's todays log and my config. I rebooted router on 14:52:20.

[config.zip](https://github.com/nfarina/homebridge/files/2733196/config.zip)
[log070118.log.zip](https://github.com/nfarina/homebridge/files/2733197/log070118.log.zip)

**Comment by NorthernMan54** [comment]
What is not in the log file are anything from the plugin itself, which makes this a bit harder.

If you look at these messages, and in particular the Sending HTTP event, you can see events being sent to both of your devices.

Please try the following

1. Ensure that everything is working
2. Turn on/off your switch at the device
3. You should see 'Sending HTTP event' lines for this ( this is homebridge sending the event to the Home App)
4. Turn on/off your device via the home app
5. You should see 'Sending HTTP event' lines for this
6. Reboot your router
7. Repeat the above steps ( both via the home app and switch )

Based on what I have seen, it appears that the device to plugin communications are failing after the router reboot, which would be a plugin problem.

**Comment by bartoszwas** [comment]
I've done what you asked for. Heres log. Router rebooted at 13:55.
First turned on and off on my Sonoff then iPhone, reboot and again turned on and off on Sonoff and iPhone. 

[log090118.log.zip](https://github.com/nfarina/homebridge/files/2741165/log090118.log.zip)

**Comment by NorthernMan54** [comment]
If you look at just the line's with "Sending HTTP event '2.10'", that is homebridge sending the device change events to the Home App.

And what is not visible in the logs is the plugin sending the device change events after the reboot.  This would be an issue with the plugin and the communications with the device and not homebridge.  Please open an issue with the plugin itself.

Homebridge sending events is working okay after the reboot, but the plugin is not telling homebridge about the events.  In the flow below the issue is between the plugin and the device

Home App <===> Apple TV <===> HomeBridge <===> Plugin <===> MQTT <===> Device

**Comment by bartoszwas** [comment]
Yes it looks like it's plugin problem. I installed mqttthing plugin and it seems to working after reboot but I haven't much time to test it. Too bad it doesn't support Sonoff temperature JSON status...

Sonoff-temperature plugin support is dead I think...

Thanks a lot for help and Your time :) I will do more long time tests.

**Comment by Kepete** [comment]
Thank you both @bartoszwas and @NorthernMan54 for troubleshooting it. Valuable information. 
Mqttthings now also supports LWT as it is the way to go seems. Only need to add the possibility to extract temperature readings from JSON.

**Comment by NorthernMan54** [comment]
Glad to hear everyone
