### ISSUE TITLE
Homematic IP Siren (HmIP-ASIR) & Water Sensor HmIP-SWD

### ISSUE THREAD

**Issue by adrianoje** [nfarina/homebridge#2024]
Dear all,

thanks a lot to the brilliant hombridge plugin I was able to add all of my HomematicIP devices via my CCU3 and Hoembridge to Homekit!

What I can´t manage is to manual add the Homematic IP siren (HmIP-ASIR) and the Homematic Water sensor (HmIP-SWD) to the config.json. I´ve treif to add them to different secitons (outlets, etc. below without success)

Purpose is to get it into Homekit as a "Sensor" to receive push notification if a alarm is triggered or my water sensors are flooded. :-)

I´ve added some variables and programs which are working fine for an alarm, butwith that i can´t setup push notoifications on my iOS device (sensor required)

Here´s my current config, any idea? Highly appreciating any idea and support! Thanks!

"name": "HomeMatic CCU",

"ccu_ip": "192.168.178.xxx",

"enable_hmip":"true",

"filter_device": [],

"filter_channel": [],

"outlets": [],

"doors": [],

"windows": [],

"programs": [],

"accessories": [],

"subsection": "Homekit",

"variables": ["Anwesenheit", "Automatikfunktionen", "Alarmanlage"]

}]

Teilen

**Comment by adrianoje** [comment]
Any idea or tip? Would be highly appreciated - I can´t figure out how to do it 👎 :-)

**Comment by iRayanKhan** [comment]
Submit this to the plugins repo they will be able to help
