### ISSUE TITLE
SyntaxError: missing ) after argument list

### ISSUE THREAD

**Issue by nitingrathod** [nfarina/homebridge#2025]
Hi There,
I've followed all the said steps from your blog at "https://github.com/nfarina/homebridge/wiki/Install-Homebridge-on-Windows-(old)".
the change I did was, I used all most updated versions. everything seems fine until the last step to starting server with the command "node homebridge" as you mentioned.

### Versions
1 - Git-2.19.1-32-bit
2 - Visual Studio Community 2017
3 - python-3.7.0
4 - Win32OpenSSL-1_0_2p
5 - node-v10.11.0-x86
6 - Bonjour for Developers 3.0.0.10 downloaded from the alternate location you provided
7 - getopt.h & getopt.c. same files from your download path
8 - unistd.h. Version of Patcher

Followed the installation sequence as mentioned but on D drive.

### Homebridge Log / Command Output
--------------------------------------------------------------------------------------------------------
1. I dont know if this is an serious error or can live with it. still copying it for better understanding of my issue. see below
---------------------------------------------------------------------------------------------------------
C:\Users\TRUPTI\AppData\Roaming\npm>npm install -g homebridge
C:\Users\TRUPTI\AppData\Roaming\npm\homebridge -> C:\Users\TRUPTI\AppData\Roamin
g\npm\node_modules\homebridge\bin\homebridge

> curve25519-n@1.4.0 install C:\Users\TRUPTI\AppData\Roaming\npm\node_modules\ho
mebridge\node_modules\curve25519-n
> node-gyp rebuild

C:\Users\TRUPTI\AppData\Roaming\npm\node_modules\homebridge\node_modules\curve25
519-n>if not defined npm_config_node_gyp (node "D:\Program Files\nodejs\node_mod
ules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bi
n\node-gyp.js" rebuild )  else (node "D:\Program Files\nodejs\node_modules\npm\n
ode_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (D:\Program Files\nodejs\node_mo
dules\npm\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (D:\Program Files\nodejs\node_mod
ules\npm\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at D:\Program Files\nodejs\node_modules\npm\node_modules\grac
eful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:154:21)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\TRUPTI\AppData\Roaming\npm\node_modules\homebridge\node_mo
dules\curve25519-n
gyp ERR! node -v v10.11.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! curve25519-n@1.4.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the curve25519-n@1.4.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\TRUPTI\AppData\Roaming\npm-cache\_logs\2018-10-06T21_00_48
_539Z-debug.log

---------------------------------------------------------------------------------------------
2. the next command "3 - Console command: npm install -g homebridge-http" went without errors.
I was happy thinking things are not that bad with me. then I tried the next thing. 
node homebridge. it never went thru. I'm stuck at the last thing. not sure what is wrong I'm doing.
-----------------------------------------------------------------------------------------------
C:\Users\TRUPTI\AppData\Roaming\npm>node homebridge
C:\Users\TRUPTI\AppData\Roaming\npm\homebridge:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^
SyntaxError: missing ) after argument list
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:279:19)
-->

**Comment by Apollon77** [comment]
For your first error it says exactly what Is missing. Google would help you. 
Install windows nodejs build tools ...

**Comment by nitingrathod** [comment]
thanks Apollon77 for your quick response. I'm working as you suggested. Will keep you posted.

Just a question. if you look at the steps I followed from the blog I followed, what exactly you think I missed? Or the blogger missed this step?
