### ISSUE TITLE
iOS 12.1 and Homebridge 

### ISSUE THREAD

**Issue by mgawley4** [nfarina/homebridge#2028]
Is anyone using Homebridge successfully on iOS 12.1 beta? I can see Homebridge in my Home app, but I cannot add it. “Home couldn’t connect to this accessory.”
Homebridge did work on iOS 11 for me and I didn’t change any of my configuration when I upgraded to iOS 12.1 beta. 

**UPDATE**:  It seems to be a problem with my RPi. Installed Homebridge on my iMac and it's working as it should.

**Comment by iRayanKhan** [comment]
It works for me on 12.1 Dev Beta 2. 
Is the Pi on Ethernet or Wi-Fi? If so ensure it is on the same network (Bands matter too [2.4/5])

**Comment by llluis** [comment]
It's working for me on 12.1 Public Beta 3 from yesterday.
Pi on the wired network.
(and it's a "Dino" Pi, arm6, the first one from 2012)

**Comment by ukd1** [comment]
dup of #2036 or vice versa?
