### ISSUE TITLE
homebridge installed on MacOS not working after update to 0.4.39 depend of HW config

### ISSUE THREAD

**Issue by FredWst** [nfarina/homebridge#2032]
Hi,

In my case config is Mojave with internet sharing homebridge installed on.
Update after 0.4.38 does not work.
Main differences between those two builds is node_modules.
in 0.4.38 it use mdns.
since 0.4.39 it use bonjour-hap.

In case of installing homebridge on a Mac connecting to this server it works up to last build.

Fred

**Comment by FredWst** [comment]
Sorry, seems to be same issue as #1843

**Comment by iRayanKhan** [comment]
Close then.

**Comment by FredWst** [comment]
No, there is a real issue when using with 2 Ethernets/wifi  connection.
Should it be possible to add option in config.json to tell homebridge to listen on en0 en1 bridge ...?

Fred

**Comment by FredWst** [comment]
After many test I can say that this bug is not in Homebridge.
At the moment I just can say that, hap is not shown in Bonjour Browser when using 0.4.45 rev.
Trouble is either in hap-nodes or bonjour-hap.
now searching how to get debug log of those 2 modules.

**Comment by FredWst** [comment]
So after some investigations.
The issu is in hap-nodejs. it can't create hap. alone.
if I run homebridge 0.4.38 on one Mac and run Homebridge 0.4.45 on another one, it works

So closed
