### ISSUE TITLE
Cannot login to web

### ISSUE THREAD

**Issue by Trippersgarage** [nfarina/homebridge#2033]
Hi. I can't seem to log in to home bridge via my web browser. I have home bridge on a Raspberry 3 running libreelec and it installed fine, runs great etc. Issue is that I cannot seem to log in via my web browser anymore, I was previously able to do this (I had changed the password before and it worked fine). Note, I am NOT getting a "invalid username and password" error; I input my username and password, click login and the page seems to just reload itself. 

Any ideas?

**Comment by FredWst** [comment]
Hi,

Try to clear browser cache.

**Comment by Trippersgarage** [comment]
Tried that. Didn’t work. Tried different browsers as well. Didn’t work either. :(

**Comment by Trippersgarage** [comment]
Did a fresh install and everything is back the way it should be. Thank you.
