### ISSUE TITLE
Change accesory state from file system?

### ISSUE THREAD

**Issue by iandronowicz** [nfarina/homebridge#2034]
Is there a way to change the satus of a homebridge accessory directly from the file system? I understand that the accessories states are persisted on reboot so they are stored somwhere in the fs...

**Comment by ebaauw** [comment]
> Is there a way to change the satus of a homebridge accessory directly from the file system?

Not while homebridge is running.

> I understand that the accessories states are persisted on reboot so they are stored somwhere in the fs...

In `~/.homebridge/accessories/cachedAccessories` (this is a JSON file).  Afaik this file is only read by homebridge on startup.  Note that only accessories created by a dynamic platform plugin are cached here.  If you have static platform plugins or accessory plugins, you're out of luck.  Make sure to shutdown homebridge before editing the file (or your edits will be overwritten when homebridge exits).

**Comment by flobernd** [comment]
@ebaauw Can you please explain me the difference between a static and a dynamic platform? I saw the parameter of `registerPlatform` but could not find any useful information about that so far.

**Comment by NorthernMan54** [comment]
Think of it this way

Static - in your configuration file you define each device 

Dynamic - the plugin discovers each device and adds in real time

**Comment by flobernd** [comment]
Thanks @NorthernMan54! So dynamic is originally intended for plugins that simulate a bridge? Just seems like pretty much every plugin around using the dynamic mode anyways ^^

**Comment by ebaauw** [comment]
> Static - in your configuration file you define each device
> Dynamic - the plugin discovers each device and adds in real time

That's the difference between accessory plugins and (dynamic) platform plugins.  The difference between static platform plugins and dynamic platform plugins is whether the accessories exposed through the plugin are determined statically, at startup time, or dynamically, at runtime.

For static platform plugins, homebridge calls `accessories()` before starting its server to receive a list of accessory delegates.  It creates an accessory for each delegate, calling `getServices()` for the list of services.  After that, the server is started, and the list of accessories is fixed.

For dynamic platform plugins, homebridge persists the accessories and restores them, before starting its server.  It calls `configureAccessory()` for each restored accessory.  After starting its server, it emits `didFinishLaunching`, after which the plugin might add or remove accessories by calling (`un`)`registerPlatformAccessories()`.

**Comment by flobernd** [comment]
Thanks for that explanation :)
