### ISSUE TITLE
Z-wave sensor connected via Hubitat reporting open falsely in homebridge

### ISSUE THREAD

**Issue by spud** [nfarina/homebridge#2042]
I have a Z-wave Ecolink Door/Window sensor on a window, connected to a Hubitat hub.

The Hubitat correctly reports the window as CLOSED. After installing Homebridge and connecting it to Hubitat with homebridge-hubitat-tonesto7, the sensor reported as closed in Homebridge as well. At some point, an hour or so later, Homebridge reported the window as OPEN. I went upstairs and checked the window. Closed, as expected.

I opened the window, and shut it again. Homebridge acknowledged that the window is now closed. A few hours later, it reported open again. (To be clear, this window is never opened by anyone regularly). Hubitat, at every point, correctly notes that the window sensor is in a closed state.

Any reason why Homebridge and Hubitat are getting two different readings from the sensor? 

I'm not quite sure where to address this issue, so I'm trying here first! What debugging can I try? Logs to watch?

### Versions
- **Homebridge**: 0.4.45
- **Node**:       v10.12.0
- **OS**:         Raspberry pi, armv7l, running Raspian (Linux raspberrypi 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l GNU/Linux)

### Homebridge Log / Command Output
Just a simple log of the event, but no indication why it was triggered, when the contact hasn't changed.

Oct 20 09:48:46 raspberrypi homebridge[783]: [10/20/2018, 9:48:46 AM] [Hubitat] Change Event: (Library Window) [CONTACT] is open
Oct 20 09:48:51 raspberrypi homebridge[783]: [10/20/2018, 9:48:51 AM] [Hubitat] Change Event: (Library Window) [CONTACT] is closed

**Comment by pdlove** [comment]
This is a fairly known bug in the homebridge-smartthings project and so I'm not surprised it's affecting hubitat as well. SmartThings and I think the derived Hubitat send a strange value for the attribute "contact" when it's not open. I never was able to resolve this in my code because I didn't have a contact sensor on my platform.

**Comment by spud** [comment]
Hey — Great to hear…I’ll bring it up with the (super-responsive) Habitat people, and see if we can get to the bottom of this!

Cheers,
spud.
