### ISSUE TITLE
How to Homebridge at WAN?

### ISSUE THREAD

**Issue by brendanlim1995** [nfarina/homebridge#2046]
I had succeeded to control my controller using iPhone 7(IOS 12) by using Raspberry at home. But I can't control my controller when I went outside.

 Is there any way to control my device when I am away?

Here are my system's information:
> pi@raspberrypi:~ $ node --version
> v8.1.3
> pi@raspberrypi:~$ uname -a
> Linux raspberrypi 4.14.34+ #1110 Mon Apr 16 14:51:42 BST 2018 armv6l GNU/Linux

**Comment by bartoszwas** [comment]
Only if you have Apple TV or iPad. In TV it’s by default, on iPad you have to turn it on in options. But i don’t recommend using iPad for it, when it goes to sleep homekit is sometimes unavailable. 

MAYBE VPN could help but i don’t think so...

**Comment by ebaauw** [comment]
> MAYBE VPN could help but i don’t think so...

You would need to have a bridging VPN.  Bonjour doesn't work over a routing VPN, so your accessories cannot be found over a routing VPN.  I'm not aware of any bridging VPN clients on iOS - typically this is setup between routers.

**Comment by brendanlim1995** [comment]
Thanks!
I will try it on an Apple TV later.
