### ISSUE TITLE
Invitation problem Slack

### ISSUE THREAD

**Issue by nikosillo** [nfarina/homebridge#2049]
Hello
Hello ... this is not exactly a Homebridge problem ...
I'm trying to request an invitation to your Slack, and there must be some problem because it gives an error. I have tried in different browsers and with different email accounts, I enter the email, I mark the check box, I hit the send button, and it is marked in red with the message "Object object" and nothing else happens

**Comment by Marco1097** [comment]
Same here

**Comment by filippocobelli** [comment]
Same here

**Comment by AppleTechy** [comment]
Hmm thanks for pointing this out. @nfarina , Can you investigate? I am also getting the same "object object error" after pressing "Get my invite button". Response seems to the Post 
```{"msg":{"code":"EAI_AGAIN","errno":"EAI_AGAIN","syscall":"getaddrinfo","hostname":"www.google.com","host":"www.google.com","port":443}}```

**Comment by nfarina** [comment]
Sorry for the delay! Investigating…
