### ISSUE TITLE
Get around Garage door automation Run requirements

### ISSUE THREAD

**Issue by akac** [nfarina/homebridge#2050]
I’m using the MyQ plugins to allow HomeKit to control my garage doors and I enjoy using the automation to automatically open or close it when I get home. 

However I’d like to automatically CLOSE garage doors when I (or a specific child of mine) leave without requiring direct action to run the Home automation via notification. I’ve provided feedback to Apple that locking/closing a HK device should be allowed automatically. 

So is there a way to alias the Garage doors to another type that doesn’t require user action simply for the purpose of automation?

**Comment by iRayanKhan** [comment]
Geofence it? Make it when xx or everyone leaves this area do this scene which closes it. Why not see home bridge-dummy it adds a fake switch and you can make it do multiple things in the home app.
