### ISSUE TITLE
how to open two homebridge or more？

### ISSUE THREAD

**Issue by songzh96** [nfarina/homebridge#2054]
I want open two or more homebridge。how to make it on raspberry。

respect

**Comment by ebaauw** [comment]
Use `-U` when starting homebridge to specify a different directory (than `~/.homebridge`).  Make sure you specify a different `name`, `username`, and `port` in config.json.  If you want to automate the startup, create a new service as well.

Here's my setup for the first homebridge instance:
```
$ cat .homebridge/config.json
{
  "bridge": {
    "name": "pi2",
    "username": "CC:22:3D:E3:CD:31",
    "port": 51827,
    "pin": "987-65-432"
  },
  "plugins": [
    "homebridge-p1",
    "homebridge-ws",
    "homebridge-zp"
  ],
  "platforms": [
    {
      "platform": "P1"
    },
    {
      "platform": "WS",
      "name": "Weather",
      "apikey": "xxxxxxxxxxxxxxxx",
      "locations": ["AMS"],
      "timeout": 15
    },
    {
      "platform": "ZP",
      "name": "Sonos",
      "speakers": true,
      "searchTimeout": 15
    }
  ]
}
$ cat /etc/default/homebridge
# Command line parameters for homebridge.
HOMEBRIDGE_OPTS="-CT"

# Log HAP requests between HomeKit and homebridge.
# DEBUG=*
$ cat /etc/systemd/system/homebridge.service 
[Unit]
Description=homebridge
After=syslog.target network-online.target

[Service]
Type=simple
User=pi
EnvironmentFile=/etc/default/homebridge
ExecStart=/usr/bin/homebridge $HOMEBRIDGE_OPTS
Restart=on-failure
RestartSec=10
KillMode=process

[Install]
WantedBy=multi-user.target
```
And here's the setup for the second instance:
```
$ cat .homebridge-hue/config.json
{
  "bridge": {
    "name": "pi2 hue",
    "username": "CC:22:3D:E3:CD:30",
    "port": 51826,
    "pin": "987-65-432"
  },
  "plugins": [
    "homebridge-hue"
  ],
  "platforms": [
    {
      "platform": "Hue",
      "host": "127.0.0.1",
      "users": {
	"00212EFFFFxxxxxx": "xxxxxxxxxx"
      },
      "sensors": true,
      "hueDimmerRepeat": true,
      "hueMotionTemperatureHistory": true,
      "lowBattery": 10,
      "lights": true,
      "groups": false,
      "schedules": true,
      "heartrate": 5
    }
  ]
}
$ cat /etc/default/homebridge-hue 
# Command line parameters for homebridge.
HOMEBRIDGE_OPTS="-CDT -U /home/pi/.homebridge-hue"

# Log HAP requests between HomeKit and homebridge.
# DEBUG=*
$ cat /etc/systemd/system/homebridge-hue.service 
[Unit]
Description=homebridge-hue
After=syslog.target network-online.target

[Service]
Type=simple
User=pi
EnvironmentFile=/etc/default/homebridge-hue
ExecStart=/usr/bin/homebridge $HOMEBRIDGE_OPTS
Restart=on-failure
RestartSec=10
KillMode=process

[Install]
WantedBy=multi-user.target
```

Both services are running happily in parallel:
```
$ sudo systemctl status home*
● homebridge-hue.service - homebridge-hue
   Loaded: loaded (/etc/systemd/system/homebridge-hue.service; enabled; vendor preset: e
   Active: active (running) since Sat 2018-11-03 18:27:28 CET; 16h ago
 Main PID: 20502 (homebridge)
   CGroup: /system.slice/homebridge-hue.service
           └─20502 homebridge

Nov 04 11:09:26 pi2 homebridge[20502]: [Hue] pi2: gateway request 48056: ok
Nov 04 11:09:27 pi2 homebridge[20502]: [Hue] Plug: state changed event
Nov 04 11:09:31 pi2 homebridge[20502]: [Hue] pi2: gateway request 48057: get /config
Nov 04 11:09:31 pi2 homebridge[20502]: [Hue] pi2: gateway request 48057: ok
Nov 04 11:09:31 pi2 homebridge[20502]: [Hue] pi2: gateway request 48058: get /sensors
Nov 04 11:09:31 pi2 homebridge[20502]: [Hue] pi2: gateway request 48058: ok
Nov 04 11:09:31 pi2 homebridge[20502]: [Hue] pi2: gateway request 48059: get /lights
Nov 04 11:09:31 pi2 homebridge[20502]: [Hue] pi2: gateway request 48059: ok
Nov 04 11:09:31 pi2 homebridge[20502]: [Hue] pi2: gateway request 48060: get /schedules
Nov 04 11:09:31 pi2 homebridge[20502]: [Hue] pi2: gateway request 48060: ok

● homebridge.service - homebridge
   Loaded: loaded (/etc/systemd/system/homebridge.service; enabled; vendor preset: enabl
   Active: active (running) since Fri 2018-10-26 00:44:25 CEST; 1 weeks 2 days ago
 Main PID: 12904 (homebridge)
   CGroup: /system.slice/homebridge.service
           └─12904 homebridge

Nov 04 11:08:48 pi2 homebridge[12904]: [P1] Electricity: set homekit current consumption
Nov 04 11:08:48 pi2 homebridge[12904]: [P1] Electricity: set homekit voltage from 231 V 
Nov 04 11:08:58 pi2 homebridge[12904]: [P1] Electricity: set homekit total consumption f
Nov 04 11:08:58 pi2 homebridge[12904]: [P1] Electricity: set homekit current consumption
Nov 04 11:09:08 pi2 homebridge[12904]: [P1] Electricity: set homekit total consumption f
Nov 04 11:09:08 pi2 homebridge[12904]: [P1] Electricity: set homekit current consumption
Nov 04 11:09:18 pi2 homebridge[12904]: [P1] Electricity: set homekit total consumption f
Nov 04 11:09:18 pi2 homebridge[12904]: [P1] Electricity: set homekit current consumption
Nov 04 11:09:28 pi2 homebridge[12904]: [P1] Electricity: set homekit total consumption f
Nov 04 11:09:28 pi2 homebridge[12904]: [P1] Electricity: set homekit current consumption
```

**Comment by songzh96** [comment]
thank you for your answer。

> Use `-U` when starting homebridge to specify a different directory (than `~/.homebridge`). Make sure you specify a different `name`, `username`, and `port` in config.json. If you want to automate the startup, create a new service as well.
> 
> Here's my setup for the first homebridge instance:
> 
> ```
> $ cat .homebridge/config.json
> {
>   "bridge": {
>     "name": "pi2",
>     "username": "CC:22:3D:E3:CD:31",
>     "port": 51827,
>     "pin": "987-65-432"
>   },
>   "plugins": [
>     "homebridge-p1",
>     "homebridge-ws",
>     "homebridge-zp"
>   ],
>   "platforms": [
>     {
>       "platform": "P1"
>     },
>     {
>       "platform": "WS",
>       "name": "Weather",
>       "apikey": "xxxxxxxxxxxxxxxx",
>       "locations": ["AMS"],
>       "timeout": 15
>     },
>     {
>       "platform": "ZP",
>       "name": "Sonos",
>       "speakers": true,
>       "searchTimeout": 15
>     }
>   ]
> }
> $ cat /etc/default/homebridge
> # Command line parameters for homebridge.
> HOMEBRIDGE_OPTS="-CT"
> 
> # Log HAP requests between HomeKit and homebridge.
> # DEBUG=*
> $ cat /etc/systemd/system/homebridge.service 
> [Unit]
> Description=homebridge
> After=syslog.target network-online.target
> 
> [Service]
> Type=simple
> User=pi
> EnvironmentFile=/etc/default/homebridge
> ExecStart=/usr/bin/homebridge $HOMEBRIDGE_OPTS
> Restart=on-failure
> RestartSec=10
> KillMode=process
> 
> [Install]
> WantedBy=multi-user.target
> ```
> And here's the setup for the second instance:
> 
> ```
> $ cat .homebridge-hue/config.json
> {
>   "bridge": {
>     "name": "pi2 hue",
>     "username": "CC:22:3D:E3:CD:30",
>     "port": 51826,
>     "pin": "987-65-432"
>   },
>   "plugins": [
>     "homebridge-hue"
>   ],
>   "platforms": [
>     {
>       "platform": "Hue",
>       "host": "127.0.0.1",
>       "users": {
> 	"00212EFFFFxxxxxx": "xxxxxxxxxx"
>       },
>       "sensors": true,
>       "hueDimmerRepeat": true,
>       "hueMotionTemperatureHistory": true,
>       "lowBattery": 10,
>       "lights": true,
>       "groups": false,
>       "schedules": true,
>       "heartrate": 5
>     }
>   ]
> }
> $ cat /etc/default/homebridge-hue 
> # Command line parameters for homebridge.
> HOMEBRIDGE_OPTS="-CDT -U /home/pi/.homebridge-hue"
> 
> # Log HAP requests between HomeKit and homebridge.
> # DEBUG=*
> $ cat /etc/systemd/system/homebridge-hue.service 
> [Unit]
> Description=homebridge-hue
> After=syslog.target network-online.target
> 
> [Service]
> Type=simple
> User=pi
> EnvironmentFile=/etc/default/homebridge-hue
> ExecStart=/usr/bin/homebridge $HOMEBRIDGE_OPTS
> Restart=on-failure
> RestartSec=10
> KillMode=process
> 
> [Install]
> WantedBy=multi-user.target
> ```
> Both services are running happily in parallel:
> 
> ```
> $ sudo systemctl status home*
> ● homebridge-hue.service - homebridge-hue
>    Loaded: loaded (/etc/systemd/system/homebridge-hue.service; enabled; vendor preset: e
>    Active: active (running) since Sat 2018-11-03 18:27:28 CET; 16h ago
>  Main PID: 20502 (homebridge)
>    CGroup: /system.slice/homebridge-hue.service
>            └─20502 homebridge
> 
> Nov 04 11:09:26 pi2 homebridge[20502]: [Hue] pi2: gateway request 48056: ok
> Nov 04 11:09:27 pi2 homebridge[20502]: [Hue] Plug: state changed event
> Nov 04 11:09:31 pi2 homebridge[20502]: [Hue] pi2: gateway request 48057: get /config
> Nov 04 11:09:31 pi2 homebridge[20502]: [Hue] pi2: gateway request 48057: ok
> Nov 04 11:09:31 pi2 homebridge[20502]: [Hue] pi2: gateway request 48058: get /sensors
> Nov 04 11:09:31 pi2 homebridge[20502]: [Hue] pi2: gateway request 48058: ok
> Nov 04 11:09:31 pi2 homebridge[20502]: [Hue] pi2: gateway request 48059: get /lights
> Nov 04 11:09:31 pi2 homebridge[20502]: [Hue] pi2: gateway request 48059: ok
> Nov 04 11:09:31 pi2 homebridge[20502]: [Hue] pi2: gateway request 48060: get /schedules
> Nov 04 11:09:31 pi2 homebridge[20502]: [Hue] pi2: gateway request 48060: ok
> 
> ● homebridge.service - homebridge
>    Loaded: loaded (/etc/systemd/system/homebridge.service; enabled; vendor preset: enabl
>    Active: active (running) since Fri 2018-10-26 00:44:25 CEST; 1 weeks 2 days ago
>  Main PID: 12904 (homebridge)
>    CGroup: /system.slice/homebridge.service
>            └─12904 homebridge
> 
> Nov 04 11:08:48 pi2 homebridge[12904]: [P1] Electricity: set homekit current consumption
> Nov 04 11:08:48 pi2 homebridge[12904]: [P1] Electricity: set homekit voltage from 231 V 
> Nov 04 11:08:58 pi2 homebridge[12904]: [P1] Electricity: set homekit total consumption f
> Nov 04 11:08:58 pi2 homebridge[12904]: [P1] Electricity: set homekit current consumption
> Nov 04 11:09:08 pi2 homebridge[12904]: [P1] Electricity: set homekit total consumption f
> Nov 04 11:09:08 pi2 homebridge[12904]: [P1] Electricity: set homekit current consumption
> Nov 04 11:09:18 pi2 homebridge[12904]: [P1] Electricity: set homekit total consumption f
> Nov 04 11:09:18 pi2 homebridge[12904]: [P1] Electricity: set homekit current consumption
> Nov 04 11:09:28 pi2 homebridge[12904]: [P1] Electricity: set homekit total consumption f
> Nov 04 11:09:28 pi2 homebridge[12904]: [P1] Electricity: set homekit current consumption
> ```

thank you for your answer。

best wishes
