### ISSUE TITLE
Image snapshot returned HTTP client error

### ISSUE THREAD

**Issue by aphex3k** [nfarina/homebridge#2057]
I did [open an Issue in the repository of the plugin](https://github.com/KhaosT/homebridge-camera-ffmpeg/issues/223) I'm trying to configure, however, I wonder if the problem I'm experiencing is rather platform agnostic and homebridge related instead.

I'm running iOS 12.1 on an iPhone X (not sure if this matters).

### Expected Behavior
I have a camera accessory added to homebridge and streaming video works just fine. But homebridge never triggers my _handleSnapshotRequest_ method. I can see the error mentioned in [homebridge-camera-ffmpeg/issues/223](https://github.com/KhaosT/homebridge-camera-ffmpeg/issues/223) in my console App. My hunch is that this might have to do with the **EventedHTTPServer** or **HAPServer** failing early and not forwarding the snapshot request to the plugin to begin with.

Is there any better way to debug homebridge besides launching it with Debug options enabled?

    DEBUG=* homebridge -D -P

### Versions

- **Homebridge**: 0.4.45
- **Node**:       v10.11.0
- **OS**:         macOS Mohave

### Console.app Log
```
Image snapshot returned HTTP client error: Error Domain=HMErrorDomain Code=58 "Failed with OSStatus code 200405 (Method Not Allowed)" UserInfo={NSLocalizedDescription=Failed with OSStatus code 200405 (Method Not Allowed), NSUnderlyingError=0x100bbaff0 {Error Domain=NSOSStatusErrorDomain Code=200405 "Method Not Allowed" UserInfo={NSLocalizedDescription=Method Not Allowed}}}

[<redacted>] Accessory sent Error Domain=HMErrorDomain Code=58 "Failed with OSStatus code 200405 (Method Not Allowed)" UserInfo={NSLocalizedDescription=Failed with OSStatus code 200405 (Method Not Allowed), NSUnderlyingError=0x100bbaff0 {Error Domain=NSOSStatusErrorDomain Code=200405 "Method Not Allowed" UserInfo={NSLocalizedDescription=Method Not Allowed}}} for snapshot request of resolution HMDVideoResolutionType480x270
```

**Comment by aphex3k** [comment]
Please disregard, it was not a homebridge issue. I merely had a mistake in my camera control...

**Comment by nikonratm** [comment]
@aphex3k Any insight into what your issue was? Not sure issue is the same but I cant get `handleSnapshotRequest` to trigger in my plugin either...
