### ISSUE TITLE
Accessories not responding in Home App - auto refresh?!

### ISSUE THREAD

**Issue by henkhb** [nfarina/homebridge#2058]
Apple home app shows "not responding" in the overview section when opened. 

### Expected Behavior
After opening the app you should see an overview of the favorite devices and their current state.

### Current Behavior
The home app shows only the state of the native homeKit devices. Homebridge connected devices show "not connected / not responding" error. When changing rooms (or when changing between Home and Rooms view), Home refreshes (re-reads) the services displayed. Also when all are reachable. It just doesn't update the status when you leave the app untouched.

### Steps to Reproduce (for bugs)
This behavior appears most time the home app is opened. But not all the time. 

### Versions

- **Homebridge**: 0.4.45, running in Docker on Synology
- **Node**:       v10.13.0
- **OS**:        12.1

**Comment by henkhb** [comment]
I got this reply from oznu, thanks for that ... 

<This is usually caused by a poorly coded plugin not responding with what HomeKit expects, so <HomeKit just gives up on the entire bridge.
<I'll close this one as it's really a duplicate of your other issue, and it's more appropriate for the <Homebridge repo. You could also try asking in the Homebridge Slack group.

I have these Plugins running. Which is known for causing this kind of trouble?
To make clear: Homebridge works great. Just annoyed by the need of switching rooms to get the connection / refresh. 

Homebridge plugin for Philips Hue and deCONZ
Alexa Skill frontend for Homebridge
Configuration UI plugin for Homebridge
Dummy switches for Homebridge:
homebridge-fritz-platform
Homebridge plugin for IFTTT Maker Channel
Xiaomi Mi air purifier plugin for Homebridge.
Plugin for using the smart intercom system nello.io in homebridge.
Nest plugin for homebridge
Netatmo plugin for homebridge:
Sonos plugin for homebridge:
homebridge-sonybravia-platform
Synology Diskstation support for Homebridge:

**Comment by NorthernMan54** [comment]
Are you running one instance of homebridge, or several?  In my setup, I’m running several instances so the impact from problematic plugins is limited.

From your list, I can say that the Alexa Skill wouldn’t cause this, as it doesn’t create a device

**Comment by henkhb** [comment]
It’s only one instance running in Docker. 

I just found out that iit seems to connect better via LTE. 

So maybe it’s a networking issue with my WiFi? Have to monitor this for some time. 

The Synology also runs Bonjour fit time machine. But what I read so far, this is no issue anymore. 

There is something that seems to block the first connect from home app.

**Comment by Kohle81** [comment]
Hello, I also have the problem that an instance in HomeKit is suddenly unreachable. I can not detect an error message in the log. I'm on node 11.0, npm 6.4.1 and homebridge 0.4.45.

I am using this plugins:

├── homebridge-automation-switches@3.2.1
├── homebridge-calendar@0.3.6
├── homebridge-callmonitor@0.0.3
├── homebridge-cmdtrigger@0.3.1
├── homebridge-harmonyhub@0.3.0-alpha.2
├── homebridge-hue@11.0
├── homebridge-ifttt@0.3.0
├── homebridge-mi-aqara@0.7.3
├── homebridge-mi-gateway-security@0.1.1
├── homebridge-omxplayer@2.2.2
├── homebridge-people@0.6.2
├── homebridge-rademacher-homepilot@0.0.4
├── homebridge-tado-thermostat-plugin@3.2.3
├── homebridge-vorwerk@0.2.0
├── miio@0.14.1

**Comment by henkhb** [comment]
Solution: homebridge-netatmo was causing all my trouble.
It makes the Home App showing "no response" erros. Without this plugin the system works really smooth. 

So be aware of that when using this plugin.  The eveatmo plugin is a good alternative and runs without issues.

**Comment by netRunner0** [comment]
Well, let's say this is a plugin. I ran the broken Homebridge with a completely empty configuration file, and it still remains inaccessible to the Home program. Only resetting and adding everything by new helps!

This is an obvious problem to be solved. Since after resetting it is necessary to reconfigure all automations.

**Comment by gcappucc** [comment]
Had the same issue. Resolved by removing the Roomba plugin. So it seems that also for me was a plugin affecting the entire bridge.
