### ISSUE TITLE
Siri commands?

### ISSUE THREAD

**Issue by dreameruk** [nfarina/homebridge#206]
Has anyone written a list of accepted terms by Siri, managed to get 'my touch home' app connected but finding a command that doesn't open the actual app and is ran as a command is very hit and miss.

Perhaps a page on the wiki would work well? Soon as got mine working can add what I have.

In the meantime interested in sonos, hue, nest & wemo.

Many thanks guys!

**Comment by desvdp** [comment]
@dreameruk Actually Siri doesn't have anything to do with the app (or any app). Think of homekit as a headless layer inside iOS. The apps are merely "another" way to interact with the homekit system.  One thing Siri can't do is adding/configuring devices: for this you actually will need an app... but any app will do. 
For a list of commands: google is your friend, eg first hit http://9to5mac.com/2015/06/25/apple-homekit-siri-commands/

**Comment by dreameruk** [comment]
Thanks for the explanation, shame apple is not more helpful with HomeKit yet, for example custom phrases or teaching it how you speak. I know iOS 9 brought a little voice learning but not much.

**Comment by fitzage** [comment]
I still can't figure out a way to have Siri arm and disarm the alarm without putting it in a scene.

**Comment by desvdp** [comment]
Have you tried naming it something siri doesn't already know (alarm is your wakeup clock ... radio is itunes). For example name your alarm "deflector shield" and just say "turn on the defector shield"

**Comment by KhaosT** [comment]
Here is a list of commands that Siri supported… there might be more but Apple only says these. http://www.apple.com/ios/siri/

**Comment by fitzage** [comment]
My alarm is called "security system". Hard to confuse that.

**Comment by justme-1968** [comment]
radio can be used as a device name if you use it in combination with a room. so turin on the radio in the bathroom works. unfortunately device names must be unique. so you can habe only one radio.

**Comment by YoungxHelsinki** [comment]
So is the following app BS? The app is called "Remote S" for Tesla cars and you can voice control your car with custom commands like "Start the car" or "Open the roof".

![https://www.youtube.com/watch?v=Ke6q1cKrmew](https://www.youtube.com/watch?v=Ke6q1cKrmew)

**Comment by tommyd75** [comment]
@fitzage Did you ever figurer out to have Siri turn on the Security System to Home or Away?
I have tried renaming my accessory but I have had no luck, unless I create a scene.

**Comment by fitzage** [comment]
No, only by creating a scene.

**Comment by apwelsh** [comment]
I enable / disable the security in my house using a virtual switch on my smartthings hub.  I export the switch to siri.  When the switch is on, smartthings arms, when it is off, smartthings disarms.  I called the swith (in homekit) Alarm.  Then i say, hey siri turn on alarm. Or Hey siri turn off alarm.
