### ISSUE TITLE
Stateless switch without hub

### ISSUE THREAD

**Issue by eisenheim94** [nfarina/homebridge#2064]
Is there any way to create stateless switch without hub (ATV or iPad)? Or something similar to turn on/off devices that can't tell current state? I don't like solution with fake switch (that turn's off button automatically after turning on).

**Comment by ebaauw** [comment]
You can create the stateless switch alright, it just won’t do anything without a Home Hub.

I think what you want is a write-only characteristic, like _Identify_ that can be set from a HomeKit app, but not read (as there’s no value to report).  I’ve had mixed results with these (e.g. the _Stop_ for the _Window Covering_ service).  Still need to dive into the details.

**Comment by eisenheim94** [comment]
@ebaauw thanks. Which accessory/service type you use for _Identify_ ?
