### ISSUE TITLE
Homebridge Wont Wake

### ISSUE THREAD

**Issue by erpeters3** [nfarina/homebridge#2069]
### Expected Behavior

Homebridge devices should be always available and responsive. 
### Current Behavior

Homebridge devices don’t respond unless I wake and log into my Mac OS X Mojave iMac. Once I log in I see homebridge is still running and with no errors. Going back to Home soo shows all is working as expected. Mojave set to never sleep and even tried running Amphetamine to stay alive. Homebridge is running on the Mac account which is different than the Homekit owner but this always worked before Mojave and iOS 12. 
### Versions

- **Homebridge**: `homebridge --version`
- **Node**:       `node --version`
- **OS**:         

### Configuration

```json

```

### Homebridge Log / Command Output

```

```

**Comment by erpeters3** [comment]
I think I may have resolved the source.  I forgot i had installed McAfee on the iMac running HB. If anyone can recommend specific firewall policies to enable wake on lan I’d appreciate it. It works once awake but cannot seem to wake the iMac through the McAfee firewall.

**Comment by iRayanKhan** [comment]
I solved my issue by just buying a pi. It costed me $35 for the latest model (B+) and came with a micro SD card.
