### ISSUE TITLE
Harmony Hub Devices?

### ISSUE THREAD

**Issue by Torsten85** [nfarina/homebridge#207]
Hey,
I see that the devices part of the harmony platform is currently commented out. In fact there is no function called "hub.getDevices()" but it looks like those devices are under "hub.getAvailableCommands()". 

Is it planned to reimplement the device list? Would be great!

I've a IR controlled ceiling fan and I dream of a world where I can simply shout "Siri, turn on the living room fan!" 😄

**Comment by AppleTechy** [comment]
@nfarina

**Comment by virtubob** [comment]
I am wondering this as well. I have an electric fireplace I would love to be able to control.

**Comment by KraigM** [comment]
This plugin has been separated out and someone else has requested this as well. Please comment and add any additional info to the new item. https://github.com/KraigM/homebridge-harmonyhub/issues/9

@nfarina go ahead and close this
