### ISSUE TITLE
Control the mdns behaviour of multicasting / advertising

### ISSUE THREAD

**Issue by muellra** [nfarina/homebridge#2072]
Are there in the mdns library configuration settings available to control the amount and timeframes of the mdns multicasting / advertising?

I'm a bit confused why my homebride sends about 4 or more multicast resquests per minute to the entire network. (tcpdump checked)

Are these multicasts needed by any devices who are already paired with my homebrigde?

Since HAP-NodeJS moved from dbus and avahi away the configurations in the avahi-daemon config are useless.

e.g. these...
[publish]
disable-publishing=yes
disable-user-service-publishing=yes

[server]
ratelimit-interval-usec=0
ratelimit-burst=0

**Comment by NorthernMan54** [comment]
This is not very well documented and may not have the feature you are looking for but, please review issue #1957 for details on how to configure the mDNS package.  And the options are documented here

https://github.com/mafintosh/multicast-dns#mdns--multicastdnsoptions

**Comment by NorthernMan54** [comment]
In my test environment I just added a debug line around that if statement and can confirm that parameter passing works as designed, but for the feature itself I can't confirm if it works or not.

If that feature is a required feature for your self, you could try opening an issue with multicast-dns, and see if they will take it on as an enhancement.

**Comment by muellra** [comment]
OK, i think I've found the problem. It's not in the multicast-dns package. It's in the a forked implementation bonjour-hap that is used by hap-nodejs:

https://github.com/KhaosT/bonjour/blob/master/lib/Service.js

Filepath in my Installation:
/usr/lib/node_modules/hap-nodejs/node_modules/bonjour-hap/lib
"gitHead": "2db14fae2cb66886f920d78710d902f4fe535a20"
bonjour-hap@^3.5.1

@KhaosT I'm not able to create an Issue in your fork of the bonjour project. So I'm give it a try here...

1. The announcements never stops, because, the variable "this.delay=1000" is overwritten every time the  "announce: function ()" is getting called by the "onAnnounceComplete: function ()".
This variable should be defined in the constructor "var Service = function (opts) {..."

2. It would be great if the 2 Paramaters in that file would be configurable. 
var REANNOUNCE_MAX_MS = 60 * 60 * 1000
var REANNOUNCE_FACTOR = 3

So the currently never ending "PTR Homebridge-..." mdns announcements should be stopping after a while.
