### ISSUE TITLE
Automation on Home APP

### ISSUE THREAD

**Issue by erokoder** [nfarina/homebridge#2073]
This is maybe not an issue, but I need information about how works automation on ios APP.
I have motion sensor and lights. So when somebody entrances in Garage, sensor motion automatic turn on lights, and after 5 minutes turn off automation. 

Expect Behavior: When John entrances in Garage, lights on for 5 minutes. John leaves the garage after 2 minutes and Mary entrances in Garage. But timer doesn't reset from zero. 
- I want that every time when the sensor detects a move that automation reset a timer for lights ON. 

This is implemented on home kit, or this is situation about homebridge?

**Comment by NorthernMan54** [comment]
This is not homebridge, but part of the Apple supplied ecosystem for HomeKit.
