### ISSUE TITLE
.json issues. Will not validate

### ISSUE THREAD

**Issue by 1gilly1** [nfarina/homebridge#2075]
Absolutley new to programming, have so far been managing ok, up untill this json file. 

I have used a few exapmples and searched for similar issues on here and the net and to no avail. 

{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},
	"accessories": [{
			"accessory": "Button",
			"name": "Test",
			"pinUp": 6,
			"pinDown": 12
		},
		{
			"accessory": "Blinds",
			"name": "Garage Door",
			"pinUp": 6,
			"pinDown": 12,
			"durationUp": 500,
			"durationDown": 500
		}
	]

I cannot see the issue with the bottom line on here, however it will not validate on the jsonlint website, regardless of where I put the bracket. 
as such Homebridge will not launch. 
Homebridge installed and running prior to the .json, all other installs went well. 

This is draining the life out of me....  any help would be greatly appreciated and Im under no illusions that the issue lies between the keyboard and the seat.

**Comment by ebaauw** [comment]
There’s a missing } at the end.

**Comment by 1gilly1** [comment]
Thanks for the quick responce ebbaauw but I had tried that to no avail, 

Error: Parse error on line 22:
...ionDown": 500		}	]
---------------------^
Expecting '}', ',', got 'EOF'

I cannot add or move any }] to get this to validate

**Comment by NorthernMan54** [comment]
Try it again, Erik was correct

{
  "bridge": {
    "name": "Homebridge",
    "username": "CC:22:3D:E3:CE:30",
    "port": 51826,
    "pin": "031-45-154"
  },
  "accessories": [{
      "accessory": "Button",
      "name": "Test",
      "pinUp": 6,
      "pinDown": 12
    },
    {
      "accessory": "Blinds",
      "name": "Garage Door",
      "pinUp": 6,
      "pinDown": 12,
      "durationUp": 500,
      "durationDown": 500
    }
  ]
}

**Comment by 1gilly1** [comment]
See the edit from about 6 seconds after my reply 😉
