### ISSUE TITLE
devices temporary not responsive

### ISSUE THREAD

**Issue by aski71** [nfarina/homebridge#2077]
### Expected Behavior
When opening "Home" on an iOS device, the devices should refresh.
When telling Siri to activate a scene, she should activate and acknowledge.

### Current Behavior
When I open "Home" on an iOS device I see the status "47 devices do not respond". When I tap on the status, the devices are being refreshed and it works fine again.
When I tell Siri to activate a scene, the scene is activated but Siri says: "Your scene does not work."
Or Siri says: "I don't get a response from your device." Even though the device did what it was supposed to do.

### Steps to Reproduce (for bugs)
See above. This is reproducible in 9 of 10 cases.

### Versions
- **Homebridge**:  0.4.45
- **Node**:       v6.15.0
- **OS**:        Ubuntu 16.04.5 LTS (GNU/Linux 4.4.0-139-generic x86_64)

### Configuration

```
{
    "bridge": {
        "name": "Homie",
        "username": "52:54:00:77:82:E9",
        "port": 51826,
        "pin": "....."
    },
 
    "platforms": [
        {
            "platform": "FHEM",
            "name": "FHEM",
            "server": "127.0.0.1",
            "port": "8083",
            "filter": "room=HomekitActors"
        },
	{
	    "platform": "FHEM",
	    "name": "FHEM",
	    "server": "127.0.0.1",
	    "port": "8083",
	    "filter": "room=HomekitSensors"
	},
        {
            "platform": "FHEM",
            "name": "FHEM",
            "server": "127.0.0.1",
            "port": "8083",
            "filter": "room=HomekitMedia"
        },
        {
            "platform": "FHEM",
            "name": "FHEM",
            "server": "127.0.0.1",
            "port": "8083",
            "filter": "room=HomekitLights"
        }
     ],
 
    "accessories": []
}

```

### Homebridge Log / Command Output

```
nothing to paste here
```

Thanks for help!

**Comment by aski71** [comment]
Can anyone help? 
I deleted my Homebridge from "Home" app, deleted the accessories and persist folder, restarted homebridge and reinstalled the Homebridge within "Home". Now the behaviour actually is worse to the extent that it's completely unusable. :-(
I urgently need help! Thanks!

**Comment by aski71** [comment]
It only sort of works on the iPad where I added homebridge to Home app. On all my other iOS device it does not work at all. "No device is responding."

**Comment by matevzg** [comment]
I'm seeing that too in the last couple of days. Also, Siri will not respond appropriately in most cases. Every time, on the first try, she would respond with 'Hmm, I couldn't get a response from your devices at this time.' On a second try, it succeeds.

Investigating further.

**Comment by Skjaar** [comment]
I have a problem with my plugin that is similar to what you are describing. My guess is that when HomeBridge is refreshing device status it sends out the same number of requests as there are devices in your config.json file. This will cause several of the request to fail since the device can't handle several requests at the same time. Leaving HomeBridge waiting for an answer and can't update the device status.
This is my guess anyway. Don't know if there is a way to handle this. Anyone who can confirm or shed some more light into the matter?

**Comment by matevzg** [comment]
The issue went away for me by updating to latest version (hap-nodejs, homebridge, homebridge-knx) and a restart. Not sure what it was. :/

**Comment by Skjaar** [comment]
I updated to homebridge@0.4.45 and it solved it. As soon as I opened Home.app everything was as it should. Correct status for each device.

**Comment by Skjaar** [comment]
Updated to homebridge@0.4.45 and it seems to handle it better than before. Need to do some more testing to se if it solves it. Thx for the tip.

**Comment by aski71** [comment]
I already had the latest version.

In my case it seems the Home config somehow got corrupted on some of the iOS devices.

The following steps completely resets the Home config and makes sure it is loaded onto your iOS. devices from scratch:
1) uninvited everyone who is part of your Home config on your master iOS device and disconnect all connected AppleTVs.
2) delete your homebridge connection from Home app on your master iOS device so your home app is clean.
3) IMPORTANT: Log off your iCloud ID on every iOS device telling it to remove local data. (This does not erase your data in the iCloud.)
4) Stop the homebridge service on your server, delete the „persist“ and „accessories“ folder.
5) Restart the homebridge service. (This will create „persist“ and „accessories“ again.
6) login your iCloud ID on your master iOS device.
7) add your homebridge to Home app on your master iOS device and configure.
8) relogin your iCloud ID on all your other devices and reconnect AppleTVs.

You could start by just performing 3) 6) 7) 8).
If that doesn‘t help, try 1) 2) 3) 6) 7) 8).
As last resort: Do it all the way.

I had to do it all the way. No more issues ever since.
