### ISSUE TITLE
How to encourage Home app to update, when `updateValue` doesn't do it?

### ISSUE THREAD

**Issue by jdtsmith** [nfarina/homebridge#2078]
Hacking on a `WidowCovering`-based plugin, and am unable to get the Home app to notice at the end of a move when I `updateValue`.  Home compares `TargetPosition` to `CurrentPosition`, and reports e.g. "Opening..." if they are unequal.  And the end of my e.g. open move, I call:

```js
    this._windowCovering
	.getCharacteristic(Characteristic.CurrentPosition)
	.updateValue(value);
```

(and similarly with `Characteristic.PositionState`, although apparently the Home app ignores that).   I have a `getTargetPosition`, but obviously can't set it (as that's how the Home app controls me!).  In any case, this does not alert the Home app that the move is over... the "Opening..." remains. 

### Expected Behavior

I expect the Home app to be alerted when the `updateValue()` is called, and to clear (e.g.) "Opening...".

### Current Behavior

"Opening..." persists far beyond the end of the move.  At some much later time (minutes), Home decides on its own to request those values:

```
  EventedHTTPServer [::ffff:192.168.0.12] HTTP request: /characteristics?id=2.16,2.17 +5s
  HAPServer [CC:22:3E:E3:CE:91] HAP Request: GET /characteristics?id=2.16,2.17 +3ms
  Accessory [HomebridgeEdgeScreen] Getting value for Characteristic "Current Position" +20ms
[12/4/2018, 3:06:23 AM] [Screen] Returning position: 0
  Accessory [HomebridgeEdgeScreen] Got Characteristic "Current Position" value: 0 +16ms
  Accessory [HomebridgeEdgeScreen] Getting value for Characteristic "Target Position" +4ms
  Accessory [HomebridgeEdgeScreen] Got Characteristic "Target Position" value: 0 +5ms
```

and at that point, presumably noticing Current and Target positions agree, clears the "Opening..." and spinning circle.  

The question is, how can I cause this to happen on demand, when my move completes?

### Steps to Reproduce (for bugs)

n/a

### Versions

- **Homebridge**: 0.4.45
- **Node**: v11.2.0
- **OS**:  macOS10.14 

### Configuration

```json

```

### Homebridge Log / Command Output

```

```

**Comment by NorthernMan54** [comment]
As an example, here is my working garage door plugin that uses update value.

https://github.com/NorthernMan54/homebridge-wssensor/blob/70fa641287c53363096a687bc76c6ead390b0e97/ws.js#L200

That particular section of code gets called whenever it receives an event message from my nodemcu connected to the door.

**Comment by jdtsmith** [comment]
Thanks.  It seems `updateValue` does the trick for you, although it doesn't for me.  I have made some progress.  By paring down a `WindowCovering` accessory to its working bare minimum (no stuck on "Opening..."), I've found log items that I'm missing in my plugin:

```
  Accessory [HomebridgeEdgeScreen] Registering Characteristic "Current Position" for events +4ms
  Accessory [HomebridgeEdgeScreen] Registering Characteristic "Target Position" for events +3ms
  Accessory [HomebridgeEdgeScreen] Registering Characteristic "Position State" for events +3ms
```

After the fake move and subsequent `updateValue`'s in my small test code, you find log items like:

```
EventedHTTPServer [::ffff:192.168.0.12] Sending HTTP event '4.12' with data: {"characteristics":[{"aid":4,"iid":12,"value":1}]} +14ms
EventedHTTPServer [::ffff:192.168.0.12] Sending HTTP event '4.10' with data: {"characteristics":[{"aid":4,"iid":10,"value":100}]} +14ms
```
and more.  I.e. the HAP server actively pushing out the update events (presumably to the position state and current positions) back to the clients (including my Home app).  I don't get any lines like these in the platform-based `WindowCovering` I'm working on.  So that explains why no events are generated for external consumption.  I just don't know why.  The same ` new Service.WindowCovering(this.name);` call is in both. 

Does your code enable characteristics' events in some manner?

**Comment by jdtsmith** [comment]
OK, I narrowed it down further.  My non-working platform code creates and returns 3 services as an array:

```
  createServices() {
    return [
      this.getAccessoryInformationService(),
      this.getBridgingStateService(),
      this.getWindowCoveringService()
    ];
  }
```

If I provide all 3 as an array in `getServices`, the events on the relevant characteristics are _not registered_.  If, however, I _only_ return the `WindowCovering` service, the events are registered and the problem is solved.  What's odd is, the other services are trivial:

```
  getAccessoryInformationService() {
    return new Service.AccessoryInformation()
      .setCharacteristic(Characteristic.Name, this.name)
      .setCharacteristic(Characteristic.Manufacturer, 'TMP')
      .setCharacteristic(Characteristic.Model, `Model ${this.config.model}`)
      .setCharacteristic(Characteristic.SerialNumber, '100')
      .setCharacteristic(Characteristic.FirmwareRevision, this.version)
      .setCharacteristic(Characteristic.HardwareRevision, this.version);
  }

  getBridgingStateService() {
    this._bridgingStateService = new Service.BridgingState()
      .setCharacteristic(Characteristic.Reachable, false)
      .setCharacteristic(Characteristic.LinkQuality, 4)
      .setCharacteristic(Characteristic.AccessoryIdentifier, this.name)
      .setCharacteristic(Characteristic.Category, Accessory.Categories.WINDOW_COVERING);

    return this._bridgingStateService;
  }
```
Not sure why they'd block event registration.

**Comment by NorthernMan54** [comment]
When your returning 3 as part of getServices do they all get properly created in the Home App? That would stop events being registered.

I’m wondering if the service is being created properly.

**Comment by jdtsmith** [comment]
How can I tell if they are?  I don’t think accessory info and bridging state have any interface visible in the Home app. I can return 2 services, just not `BridgingState`.

**Comment by NorthernMan54** [comment]
Sorry missed that, you don’t return a bridging service

One tool I use is this with homebridge started with -I, it dumps the whole HAP object that gets passed to HomeKit.  Allows easy troubleshooting of device config problems.

curl -X PUT http://127.0.01:51826/accessories --header "Content-Type:Application/json" --header "authorization: 031-45-154"

**Comment by jdtsmith** [comment]
That's a cool trick, thanks.  Interestingly, when I run it with and without returning the bridging service included, the only change looks pretty innocuous.  So this seems to be a deeper bug when a bridging service is returned.  

```json
--- hapdump.json	2018-12-04 22:26:36.000000000 -0500
+++ hapdump_nobridging.js	2018-12-04 22:31:56.000000000 -0500
@@ -263,63 +263,6 @@
           ],
           "primary": false,
           "hidden": false
-        },
-        {
-          "iid": 35,
-          "type": "00000062-0000-1000-8000-0026BB765291",
-          "characteristics": [
-            {
-              "iid": 36,
-              "type": "00000063-0000-1000-8000-0026BB765291",
-              "perms": [
-                "pr",
-                "ev"
-              ],
-              "format": "bool",
-              "value": false,
-              "description": "Reachable"
-            },
-            {
-              "iid": 37,
-              "type": "0000009C-0000-1000-8000-0026BB765291",
-              "perms": [
-                "pr",
-                "ev"
-              ],
-              "format": "uint8",
-              "value": 4,
-              "description": "Link Quality",
-              "maxValue": 4,
-              "minValue": 1,
-              "minStep": 1
-            },
-            {
-              "iid": 38,
-              "type": "00000057-0000-1000-8000-0026BB765291",
-              "perms": [
-                "pr"
-              ],
-              "format": "string",
-              "value": "Theater Screen",
-              "description": "Accessory Identifier"
-            },
-            {
-              "iid": 39,
-              "type": "000000A3-0000-1000-8000-0026BB765291",
-              "perms": [
-                "pr",
-                "ev"
-              ],
-              "format": "uint16",
-              "value": 14,
-              "description": "Category",
-              "maxValue": 16,
-              "minValue": 1,
-              "minStep": 1
-            }
-          ],
-          "primary": false,
-          "hidden": false
         }
       ]
     }
```

**Comment by ebaauw** [comment]
Why not simply remove the _Bridging State_ service?  Afaik, Apple removed it back in iOS 10, see 
https://github.com/KhaosT/HAP-NodeJS/blob/9eaea6df40811ccc71664a1ab0c13736e759dac7/lib/gen/HomeKitTypes-Bridge.js#L132

**Comment by jdtsmith** [comment]
That was indeed my solution, but since the Service still exists, and does not produce an error when created or returned from `getServices`, it seems like a subtle bug lurking in Homebridge or HAP.  Maybe a “this service has been removed and may cause issues” warning would be appropriate?

Also, from what I’ve read, there is no reliable way to signal a disconnected device other than waiting for a `get` and calling back with an error.  Any other method?

**Comment by ebaauw** [comment]
> Also, from what I’ve read, there is no reliable way to signal a disconnected device other than waiting for a get and calling back with an error. Any other method?

I use _Status Fault_ to indicate when a device is unreachable.  Not supported by Apple's Home app, but works wonderfully in Eve.  The problem I have with using an error value is that the state seems to stick, until you view another room, or switch from the _Rooms_ view to the _Home_ view.

**Comment by NorthernMan54** [comment]
@jdtsmith As @ebaauw has indicated there are no 100% fool proof methods of having homebridge tell the Home app that a device is not responding or available.  I had spent a fair bit of time reviewing the Apple HAP Spec document, looking for this, and it is a gap in their device API model for Bridge's.  They do have a robust model between the Apple cloud and Homebridge ( Native Device ), but it is lacking for bridges fronting other devices.  For myself, I use the updateValue error method mentioned by Erik, and live with the user experience warts as I use the Home App primarily ( Actually I use Alexa about 90% of the time ).

The updateValue method was documented here.

https://github.com/KhaosT/HAP-NodeJS/pull/556

**Comment by jdtsmith** [comment]
Thanks both.  I've discovered the unfortunate "stickiness" of the error (!) state as well.  I think I'll try `StatusFault` and see how that goes; perhaps Home will start supporting it at some point.  Are `Characteristic.StatusFault` and `Accessory.prototype.updateReachability` related? The latter seems [deprecated](https://github.com/KhaosT/HAP-NodeJS/blob/9eaea6df40811ccc71664a1ab0c13736e759dac7/lib/Accessory.js#L248).

**Comment by ebaauw** [comment]
No, they’re not related.  And yes, the updateReachability no longer works as it used to update the corresponding characteristic in the bridging state service.

**Comment by iRayanKhan** [comment]
There is a plugin for windows if you want to fork it: homebridge-windowskel
