### ISSUE TITLE
Cannot read property '0' of undefined - When using ISY platform

### ISSUE THREAD

**Issue by rodtoll** [nfarina/homebridge#208]
Receiving error 'Cannot read property '0' of undefined - When using ISY platform.

Configuration:
ISY-994i
Firmware: Insteon_UD994 v4.2.21
Running on Mac OS Yosemite

Console output:
Loading 1 platforms...
[ISY] Initializing ISY platform...
[ISY] Fetching ISY Devices.
Loading 0 accessories...

TypeError: Cannot read property '0' of undefined
    at /Users/rodtoll/github/homebridge/platforms/ISY.js:70:45
    at Array.forEach (native)
    at /Users/rodtoll/github/homebridge/platforms/ISY.js:57:35
    at Parser.<anonymous> (/Users/rodtoll/github/homebridge/node_modules/xml2js/lib/xml2js.js:462:18)
    at Parser.emit (events.js:95:17)
    at Object.onclosetag (/Users/rodtoll/github/homebridge/node_modules/xml2js/lib/xml2js.js:423:26)
    at emit (/Users/rodtoll/github/homebridge/node_modules/xml2js/node_modules/sax/lib/sax.js:625:33)
    at emitNode (/Users/rodtoll/github/homebridge/node_modules/xml2js/node_modules/sax/lib/sax.js:630:3)
    at closeTag (/Users/rodtoll/github/homebridge/node_modules/xml2js/node_modules/sax/lib/sax.js:874:5)
    at Object.write (/Users/rodtoll/github/homebridge/node_modules/xml2js/node_modules/sax/lib/sax.js:1314:29)
    at Parser.exports.Parser.Parser.parseString (/Users/rodtoll/github/homebridge/node_modules/xml2js/lib/xml2js.js:481:31)

Config (host, password replaced with placeholders):
{
    "bridge": {
        "name": "Home",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },

    "description": "Main House.",

    "platforms": [
        {
            "platform": "ISY",
            "name": "ISY",
            "host": "<<ADDRESS>>",
            "port": "80",
            "username": "admin",
            "password": "<<PASSWORD>>"
        }
    ],

    "accessories": [
    ]
}

Looks like a parsing error (ISY returning something unexpected) in platforms/ISY.js. Adding a try catch around the call to the constructor on the ISYAccessory bypasses the issue.

I have a very large Insteon network with a wide variety of devices. I can share my nodes.xml file privately if it helps address the issue.

**Comment by rodtoll** [comment]
The device which is causing the parse error are my Wave repeaters. (I am using the wave module). They do not have uom element and can be safely ignored. type element in these items are 4.15.1.0. Here is the offending node elements:

<node flag="128">
<address>ZW003_1</address>
<name>ZW 003 Repeater</name>
<family>4</family>
<parent type="3">46017</parent>
<type>4.15.1.0</type>
<enabled>true</enabled>
<deviceClass>0</deviceClass>
<wattage>0</wattage>
<dcPeriod>0</dcPeriod>
<pnode>ZW003_1</pnode>
<sgid>1</sgid>
<devtype>
<gen>4.15.1</gen>
<mfg>134.4.37</mfg>
<cat>129</cat>
</devtype>
</node>
<node flag="128">
<address>ZW004_1</address>
<name>ZW 004 Repeater</name>
<family>4</family>
<parent type="3">46017</parent>
<type>4.15.1.0</type>
<enabled>true</enabled>
<deviceClass>0</deviceClass>
<wattage>0</wattage>
<dcPeriod>0</dcPeriod>
<pnode>ZW004_1</pnode>
<sgid>1</sgid>
<devtype>
<gen>4.15.1</gen>
<mfg>134.4.37</mfg>
<cat>129</cat>
</devtype>
</node>

**Comment by AppleTechy** [comment]
Have you been able to resolve this issue?

**Comment by rodtoll** [comment]
Thanks for following up. I ended up working around the problem by building a new isy library and homebridge plugin. Homebridge-isy-js. It handles the offending devices and others.

**Comment by AppleTechy** [comment]
@rodtoll alright then. Going to close the issue then since you got it all sorted out.
