### ISSUE TITLE
Windows install not writing logs

### ISSUE THREAD

**Issue by 400HPMustang** [nfarina/homebridge#2081]
The homebridge install is written for Linux and seems to support a path for writing log files on a Linux installation of the software. I cannot seem to find how to specify log location other than in a config file and that does not seem to do anything. 

### Versions
- **Homebridge**: `Version 0.4.45`
- **Node**:       `v8.9.4`
- **OS**:         Windows 10 Home Version 1803

### Configuration
``{
    "bridge": {
        "name": "XXXXXXX Homebridge",
        "username": "XX:XX:XX::XX:XX:XX",
        "port": 53052,
        "pin": "031-45-154",
	"log": "C:/Users/XXX/.homebridge/Output.log"
    },`
`

**Comment by 400HPMustang** [comment]
Still having this problem. Despite specifying a log path in my config, my homebridge will not write logs to a file. I can only output to the screen when I launch homebridge from powershell. 

Can I get a little help here? Please?

**Comment by ScottGA** [comment]
I'm having the same issue.  My iOS and MacOS Home apps are getting stuck in the "No Responses" state, but I can't really debug anything since I can't find the Homeseer error logs.  Please help.

Thanks!
