### ISSUE TITLE
Plugin Request: DITRA-HEAT-E-WIFI

### ISSUE THREAD

**Issue by jpaquino3** [nfarina/homebridge#2086]
Hey all! 

I’m having a heated tile floor installed in my bathroom and was wondering if there was any way to add the Schluter Ditra WiFi Theromostat to my HomeKit setup. Thanks!

**Comment by cbuds** [comment]
Second the request. Installing these thermostats in my basement.

**Comment by majkelospl** [comment]
hi, it would be fantastic to make that plugin, for example on HA it is here: https://www.home-assistant.io/integrations/schluter/
Any possible to translate that plugin to HB?

**Comment by patmanh** [comment]
+1 would love to use this plugin - the HA plugin @majkelospl linked to looks to be powered by https://github.com/prairieapps/py-schluter (python API for Schluter DITRA-HEAT Thermostats)... maybe that helps too?

don't have time right now to write it myself, but maybe in the future 😢

**Comment by cavsee** [comment]
Curious if anyone has tried the above API for use with homekit or HB?

Here's the related repo from @majkelospl https://github.com/home-assistant/core/tree/dev/homeassistant/components/schluter

and @patmanh also posted what seems to be similar, so feels like we just need someone to give a shot who is more savvy than I am :)
