### ISSUE TITLE
Issue with installing plugins npm package.json

### ISSUE THREAD

**Issue by Alezx22** [nfarina/homebridge#2087]
When i try to install a plugin with the command npm every time it give me an error regarding a package.json not found and npm WARN enoent ENOENT. I have tried using the command npm init but it doen't fix nothing beacuse if i try to launch homebridge it doen't recognise the plugin installed. How can i solve this issue? this happened to me with the latest version of raspian, because when i installed homerbidge 5 months ago on another rapsberry i didn't have this kind of error.
Thanks

**Comment by rvs007** [comment]
I'm running into the same issue.  I'm trying to install a homebridge plugin and I am running 'sudo npm i homebridge-pluginname' and it's returning a bunch of warnings with first three being:

npm WARN saveError ENOENT: no such file or directory, open '/home/pi/package.json'
npm notice created a lockfile as package-lock.json.  You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/package.json'
...

Any help?

**Comment by Hussamfhaily** [comment]
I get such error while I try to update the homebridge
