### ISSUE TITLE
Shows as non-compliant on iOS9.0.1 on iPhone 6S Plus

### ISSUE THREAD

**Issue by rodtoll** [nfarina/homebridge#209]
Unable to add devices (or the bridge) from ISY from iOS9.0.1. 

Setup:
iPhone 6S Plus 
iOS 9.0.1
MobiLinc Home (Reproduced on MyTouchHome)
Mac OS X Running Yosemite (Node host)

Steps:
1. Run HomeBridge on Mac OS X
2. Go into a room, click to add Accessory
2. Select the bridge (it appears in the list). Select to Add
3. Get a warning message abut the accessory not being compliant (see IMG_0005)
![img_0005](https://cloud.githubusercontent.com/assets/3971139/10124079/02ac53d4-6500-11e5-9d0d-1a62e91a6632.PNG)
4. Receive error message about accessory being out of compliance (see IMG_0006)
![img_0006](https://cloud.githubusercontent.com/assets/3971139/10124081/02c8e88c-6500-11e5-8502-2261b9b56a8d.PNG)
5. Console output is below..

> homebridge@0.1.1 start /Users/rodtoll/github/homebridge
> DEBUG=* node app.js || true

Starting HomeBridge server...
_____________________________________________________________________
IMPORTANT: Homebridge is in the middle of some big changes.
           Read more about it here:
           https://github.com/nfarina/homebridge/wiki/Migration-Guide
_____________________________________________________________________

Loading 1 platforms...
[ISY] Initializing ISY platform...
[ISY] Fetching ISY Devices.
Loading 0 accessories...
[ISY] Initializing platform accessory 'ApplianceLink.F0'...
[ISY] Initializing platform accessory 'Back Door.Off.To.Lock'...
[ISY] Initializing platform accessory 'Back Door.On.To.Lock'...
[ISY] Initializing platform accessory 'Back Gate Unused'...
[ISY] Initializing platform accessory 'Back Ground Motion Light'...
[ISY] Initializing platform accessory 'Basement Door Switch'...
[ISY] Initializing platform accessory 'Basement Motion LIght'...
[ISY] Initializing platform accessory 'Basement Motion Sensor-Dusk.D'...
[ISY] Initializing platform accessory 'Basement Motion Sensor-Low Ba'...
[ISY] Initializing platform accessory 'Basement Motion Sensor-Sensor'...
[ISY] Initializing platform accessory 'Basement Rec Room Back Door'...
[ISY] Initializing platform accessory 'Basement Rec Room Inner Wall'...
[ISY] Initializing platform accessory 'Basement Stairs Bottom'...
[ISY] Initializing platform accessory 'Basement Stairs Top - Main'...
[ISY] Initializing platform accessory 'Bedroom Keypad.All On'...
[ISY] Initializing platform accessory 'Bedroom Keypad.Fireplace'...
[ISY] Initializing platform accessory 'Bedroom Keypad.Garage Status'...
[ISY] Initializing platform accessory 'Bedroom Keypad.Night'...
[ISY] Initializing platform accessory 'Bedroom Keypad.Night Hallway'...
[ISY] Initializing platform accessory 'Bedroom Keypad.Romance'...
[ISY] Initializing platform accessory 'Bedroom RemoteLinc'...
[ISY] Initializing platform accessory 'Bedroom RemoteLinc - 2'...
[ISY] Initializing platform accessory 'Bedroom RemoteLinc - 3'...
[ISY] Initializing platform accessory 'Bedroom RemoteLinc - 4'...
[ISY] Initializing platform accessory 'Bedroom RemoteLinc - 5'...
[ISY] Initializing platform accessory 'Bedroom RemoteLinc - 6'...
[ISY] Initializing platform accessory 'Bedroom RemoteLinc - 7'...
[ISY] Initializing platform accessory 'Bedroom RemoteLinc - 8'...
[ISY] Initializing platform accessory 'Bedroom.Side Gate'...
[ISY] Initializing platform accessory 'Butlers Pantry'...
[ISY] Initializing platform accessory 'Deck Door Lock'...
[ISY] Initializing platform accessory 'Deck Keypad.AlarmOn'...
[ISY] Initializing platform accessory 'Deck Keypad.Fireplace'...
[ISY] Initializing platform accessory 'Deck Keypad.Garage'...
[ISY] Initializing platform accessory 'Deck Keypad.Home'...
[ISY] Initializing platform accessory 'Deck Keypad.Night'...
[ISY] Initializing platform accessory 'Deck Keypad.Outside Lights'...
[ISY] Initializing platform accessory 'Deck Keypad.Side Gate'...
[ISY] Initializing platform accessory 'Deck Keypad.Sophia'...
[ISY] Initializing platform accessory 'Deck Motion Light'...
[ISY] Initializing platform accessory 'Dinning Room Inner Wall'...
[ISY] Initializing platform accessory 'Dinning Room Outer Wall - Mai'...
[ISY] Initializing platform accessory 'Doorbell Sensor'...
[ISY] Initializing platform accessory 'Doorbell-Relay'...
[ISY] Initializing platform accessory 'Front Door Lock'...
[ISY] Initializing platform accessory 'Front Door.1'...
[ISY] Initializing platform accessory 'Front Hall Front Door'...
[ISY] Initializing platform accessory 'Front Hall Main Hall - Main'...
[ISY] Initializing platform accessory 'Front Keypad.Away'...
[ISY] Initializing platform accessory 'Front Keypad.Decorations'...
[ISY] Initializing platform accessory 'Front Keypad.Home'...
[ISY] Initializing platform accessory 'Front Keypad.Night'...
[ISY] Initializing platform accessory 'Garage Keypad.Alarm'...
[ISY] Initializing platform accessory 'Garage Keypad.ArrriveHome'...
[ISY] Initializing platform accessory 'Garage Keypad.Away'...
[ISY] Initializing platform accessory 'Garage Keypad.Garage'...
[ISY] Initializing platform accessory 'Garage Keypad.Gate'...
[ISY] Initializing platform accessory 'Garage Keypad.Hallway'...
[ISY] Initializing platform accessory 'Garage Keypad.Home'...
[ISY] Initializing platform accessory 'Garage Keypad.Night'...
[ISY] Initializing platform accessory 'Garage Light'...
[ISY] Initializing platform accessory 'Garage Sensor-Sensor'...
[ISY] Initializing platform accessory 'Garage Sensor-Unused Relay'...
[ISY] Initializing platform accessory 'Girls Inner'...
[ISY] Initializing platform accessory 'Girls Outer'...
[ISY] Initializing platform accessory 'Kitchen Alcove'...
[ISY] Initializing platform accessory 'Kitchen Island'...
[ISY] Initializing platform accessory 'Kitchen Main'...
[ISY] Initializing platform accessory 'Kitchen Motion Sensor-Dusk.Da'...
[ISY] Initializing platform accessory 'Kitchen Motion Sensor-Low Bat'...
[ISY] Initializing platform accessory 'Kitchen Motion Sensor-Sensor'...
[ISY] Initializing platform accessory 'Kitchen Table'...
[ISY] Initializing platform accessory 'Living Room Lamplinc'...
[ISY] Initializing platform accessory 'Living Room Switch'...
[ISY] Initializing platform accessory 'Main Floor Bathroom'...
[ISY] Initializing platform accessory 'Main Floor Closet'...
[ISY] Initializing platform accessory 'Main Floor Closet Sensor'...
[ISY] Initializing platform accessory 'Main Floor Fireplace'...
[ISY] Initializing platform accessory 'Main Floor Hall Front Hall'...
[ISY] Initializing platform accessory 'Main Floor Hall Kitchen'...
[ISY] Initializing platform accessory 'Main Floor Hall Office'...
[ISY] Initializing platform accessory 'Main Floor TV Room'...
[ISY] Initializing platform accessory 'Main Floor TV Room Lamplinc'...
[ISY] Initializing platform accessory 'Main TV Room Motion'...
[ISY] Initializing platform accessory 'Main TV Room Motion-Light'...
[ISY] Initializing platform accessory 'Main TV Room Motion-Low Bat'...
[ISY] Initializing platform accessory 'Master Bathroom'...
[ISY] Initializing platform accessory 'Master Bedroom Fireplace'...
[ISY] Initializing platform accessory 'Master Bedroom LampLinc'...
[ISY] Initializing platform accessory 'Master Bedroom.1'...
[ISY] Initializing platform accessory 'Office Keypad.B'...
[ISY] Initializing platform accessory 'Office Keypad.C'...
[ISY] Initializing platform accessory 'Office Keypad.D'...
[ISY] Initializing platform accessory 'Office Keypad.E'...
[ISY] Initializing platform accessory 'Office Keypad.F'...
[ISY] Initializing platform accessory 'Office Keypad.G'...
[ISY] Initializing platform accessory 'Office Keypad.H'...
[ISY] Initializing platform accessory 'Office Keypad.Main'...
[ISY] Initializing platform accessory 'Outside Plug Left of Garage'...
[ISY] Initializing platform accessory 'Outside Plug Left of Porch'...
[ISY] Initializing platform accessory 'Outside Plug Right Side'...
[ISY] Initializing platform accessory 'Pantry Light'...
[ISY] Initializing platform accessory 'Play Room'...
[ISY] Initializing platform accessory 'Play Room Motion-Dusk.Dawn'...
[ISY] Initializing platform accessory 'Play Room Motion-Low Bat'...
[ISY] Initializing platform accessory 'Play Room Motion-Sensor'...
[ISY] Initializing platform accessory 'Rod Office Motion'...
[ISY] Initializing platform accessory 'Rod Office Motion-Light'...
[ISY] Initializing platform accessory 'Rod Office Motion-Low Bat'...
[ISY] Initializing platform accessory 'Sam Fan-Light'...
[ISY] Initializing platform accessory 'Sam Fan-Motor'...
[ISY] Initializing platform accessory 'Sam Keypad.A'...
[ISY] Initializing platform accessory 'Sam Keypad.B'...
[ISY] Initializing platform accessory 'Sam Keypad.C'...
[ISY] Initializing platform accessory 'Sam Keypad.D'...
[ISY] Initializing platform accessory 'Sam Keypad.Light'...
[ISY] Initializing platform accessory 'Sarah Fan-Light'...
[ISY] Initializing platform accessory 'Sarah Fan-Motor'...
[ISY] Initializing platform accessory 'Sarah Keypad-A'...
[ISY] Initializing platform accessory 'Sarah Keypad-B'...
[ISY] Initializing platform accessory 'Sarah Keypad-C'...
[ISY] Initializing platform accessory 'Sarah Keypad-D'...
[ISY] Initializing platform accessory 'Sarah Keypad-Main'...
[ISY] Initializing platform accessory 'Server Room'...
[ISY] Initializing platform accessory 'Server Room Door Sensor'...
[ISY] Initializing platform accessory 'Side Gate Unused'...
[ISY] Initializing platform accessory 'Sophia Fan-Light'...
[ISY] Initializing platform accessory 'Sophia Fan-Motor'...
[ISY] Initializing platform accessory 'Sophia Keypad.A'...
[ISY] Initializing platform accessory 'Sophia Keypad.B'...
[ISY] Initializing platform accessory 'Sophia Keypad.C'...
[ISY] Initializing platform accessory 'Sophia Keypad.D'...
[ISY] Initializing platform accessory 'Sophia Keypad.Light'...
[ISY] Initializing platform accessory 'Stairs Scones'...
[ISY] Initializing platform accessory 'Upstairs Hall By Bath'...
[ISY] Initializing platform accessory 'Upstairs Hall By Bath - Main'...
[ISY] Initializing platform accessory 'Upstairs Hall By Laundry'...
[ISY] Initializing platform accessory 'Upstairs Hall By Master'...
[ISY] Initializing platform accessory 'Upstairs Stairs By Bath - Mai'...
[ISY] Initializing platform accessory 'Upstairs Stairs Main Floor'...
[ISY] Initializing platform accessory 'Upstairs Stairs Top Left'...
Scan this code with your HomeKit App on your iOS device:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
  EventedHTTPServer Server listening on port 51826 +0ms
  EventedHTTPServer [10.0.1.247] New connection from client +19s
  EventedHTTPServer [10.0.1.247] HTTP server listening on port 54826 +0ms
  EventedHTTPServer [10.0.1.247] HTTP request: /pair-setup +2ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-setup +0ms
  HAPServer [CC:22:3D:E3:CE:30] Pair step 1/5 +1ms
  EventedHTTPServer [10.0.1.247] HTTP Repsonse is finished +10ms
  EventedHTTPServer [10.0.1.247] HTTP request: /pair-setup +10s
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-setup +0ms
  HAPServer [CC:22:3D:E3:CE:30] Pair step 2/5 +1ms
  EventedHTTPServer [10.0.1.247] HTTP Repsonse is finished +7ms
  EventedHTTPServer [10.0.1.247] HTTP request: /pair-setup +8ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-setup +0ms
  HAPServer [CC:22:3D:E3:CE:30] Pair step 3/5 +0ms
  HAPServer [CC:22:3D:E3:CE:30] Pair step 4/5 +3ms
  HAPServer [CC:22:3D:E3:CE:30] Pair step 5/5 +1ms
  Accessory [TollHome] Paired with client B8164B5E-1256-40CB-81C6-A0F1A80A5ED4 +1ms
  EventedHTTPServer [10.0.1.247] HTTP Repsonse is finished +1ms
  EventedHTTPServer [10.0.1.247] Client connection closed +14ms
  EventedHTTPServer [10.0.1.247] HTTP connection was closed +0ms
  EventedHTTPServer [10.0.1.247] HTTP server was closed +0ms
  EventedHTTPServer [10.0.1.247] New connection from client +4ms
  EventedHTTPServer [10.0.1.247] HTTP server listening on port 54826 +0ms
  EventedHTTPServer [10.0.1.247] HTTP request: /pair-verify +1ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +0ms
  HAPServer [CC:22:3D:E3:CE:30] Pair verify step 1/2 +1ms
  EventedHTTPServer [10.0.1.247] HTTP Repsonse is finished +1ms
  EventedHTTPServer [10.0.1.247] HTTP request: /pair-verify +79ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +0ms
  HAPServer [CC:22:3D:E3:CE:30] Pair verify step 2/2 +1ms
  HAPServer [CC:22:3D:E3:CE:30] Client B8164B5E-1256-40CB-81C6-A0F1A80A5ED4 verification complete +2ms
  EventedHTTPServer [10.0.1.247] HTTP Repsonse is finished +0ms
  EventedHTTPServer [10.0.1.247] HTTP request: /accessories +6ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: GET /accessories +0ms
  EventedHTTPServer [10.0.1.247] HTTP Repsonse is finished +13ms
  EventedHTTPServer [10.0.1.247] HTTP request: /pairings +735ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pairings +0ms
  HAPServer [CC:22:3D:E3:CE:30] Removing pairing info for client +0ms
  Accessory [TollHome] Unpairing with client B8164B5E-1256-40CB-81C6-A0F1A80A5ED4 +0ms
  EventedHTTPServer [10.0.1.247] HTTP Repsonse is finished +1ms
  EventedHTTPServer [10.0.1.247] Client connection closed +13ms
  EventedHTTPServer [10.0.1.247] HTTP connection was closed +1ms
  EventedHTTPServer [10.0.1.247] HTTP server was closed +0ms

**Comment by KhaosT** [comment]
@rodtoll normally this occurred when accessory platform returns an unexpected value for some service/characteristic. Can you start the server and on your computer, post the results from http://127.0.0.1:51826/accessories so we can figure out what exactly goes wrong?

**Comment by rodtoll** [comment]
Ok. I've got the file as JSON but it will not let me paste it into the comment (too long), or attach as a JSON, TXT, PDF or DOCX (I tried all of those). The error message is "Something went really wrong, and we can't process that file. Try again". And trying again doesn't work. Reproduces in Chrome and Safari.

**Comment by KhaosT** [comment]
@rodtoll you can use this and post the link here http://pastebin.com/

**Comment by rodtoll** [comment]
Here you go:
http://pastebin.com/ZM6Hsrve

**Comment by KhaosT** [comment]
@rodtoll OK... the problem is ... HomeKit only allows bridge accessory to bridge 100 accessories and you got 142 accessories in total. Based on the naming, it seems most of the "accessory" are bridged scenes, I'd suggest you to merge some of those (to reduce the total number to under 100) or try to split all those accessories to two bridges.

@nfarina Do you think we should guard the upper limit of bridged accessories and show a warning?

**Comment by rodtoll** [comment]
@KhaosT Got it. I will reduce the number of scenes. Seems like for robustness an error message if 100 is exceeded would be good. I like the idea of automatically creating a second bridge though.

I have a fairly complex and extensive system but I won't be the last one. :)

**Comment by nfarina** [comment]
@KhaosT yes if this is a hard limit then we should definitely throw an Error when attempting to add more than 100 accessories to a bridge.

**Comment by KhaosT** [comment]
@nfarina it's a hard limit in iOS. For iOS 8 and iOS 9, each accessory can have 100 services, each service can have 100 characteristics and each bridge accessory can have 99 bridged accessories (100 total)

**Comment by rodtoll** [comment]
I have reduced the number of my devices down to 60. It is still failing unfortunately. Same symptoms. 

Here is the results from http://127.0.0.1:51826/accessories:
http://pastebin.com/ZAaye0ny

I made sure to reset my HomeKit configuration and remove the local persist directory to make sure nothing was holding over from the old config. 

I added code to skip the devices I didn't need (some of the sensors, relays, etc..) and that appears in the console output in the skipping section. I checked the accessories JSON and it only has the 60 devices.  

Here is the console output:

> homebridge@0.1.1 start /Users/rodtoll/github/homebridge
> DEBUG=* node app.js || true

Starting HomeBridge server...
_____________________________________________________________________
IMPORTANT: Homebridge is in the middle of some big changes.
           Read more about it here:
           https://github.com/nfarina/homebridge/wiki/Migration-Guide
_____________________________________________________________________

Loading 1 platforms...
[ISY] Initializing ISY platform...
[ISY] Fetching ISY Devices.
Loading 0 accessories...
Skipping motion device: Main Floor Closet Sensor
Skipping unused device: Side Gate Unused
Skipping motion device: Server Room Door Sensor
Skipping unused device: Back Gate Unused
Skipping motion device: Main TV Room Motion
Skipping motion device: Main TV Room Motion-Light
Skipping motion device: Main TV Room Motion-Low Bat
Skipping motion device: Play Room Motion-Sensor
Skipping motion device: Play Room Motion-Dusk.Dawn
Skipping motion device: Play Room Motion-Low Bat
Skipping motion device: Rod Office Motion
Skipping motion device: Rod Office Motion-Light
Skipping motion device: Rod Office Motion-Low Bat
Skipping motion device: Deck Motion Light
Skipping motion device: Basement Motion LIght
Skipping motion device: Garage Sensor-Sensor
Skipping motion device: Garage Sensor-Unused Relay
Skipping unused device: Garage Door Opener-Unused Sen
Skipping motion device: Garage Door-Relay
Skipping motion device: Doorbell Sensor
Skipping motion device: Doorbell-Relay
Skipping device non button 1 device: Bedroom Keypad.Night
Skipping device non button 1 device: Bedroom Keypad.Garage Status
Skipping device non button 1 device: Bedroom Keypad.Romance
Skipping device non button 1 device: Bedroom Keypad.Fireplace
Skipping device non button 1 device: Bedroom Keypad.Night Hallway
Skipping device non button 1 device: Bedroom Keypad.All On
Skipping device non button 1 device: Front Keypad.Away
Skipping device non button 1 device: Front Keypad.Night
Skipping device non button 1 device: Front Keypad.Decorations
Skipping device non button 1 device: Front Keypad.Home
Skipping device non button 1 device: Deck Keypad.Outside Lights
Skipping device non button 1 device: Deck Keypad.AlarmOn
Skipping device non button 1 device: Deck Keypad.Night
Skipping device non button 1 device: Deck Keypad.Fireplace
Skipping device non button 1 device: Deck Keypad.Sophia
Skipping device non button 1 device: Deck Keypad.Home
Skipping device non button 1 device: Deck Keypad.Side Gate
Skipping device non button 1 device: Deck Keypad.Garage
Skipping motion device: Back Ground Motion Light
Skipping remote device: Bedroom RemoteLinc
Skipping remote device: Bedroom RemoteLinc - 2
Skipping remote device: Bedroom RemoteLinc - 3
Skipping remote device: Bedroom RemoteLinc - 4
Skipping remote device: Bedroom RemoteLinc - 5
Skipping remote device: Bedroom RemoteLinc - 6
Skipping remote device: Bedroom RemoteLinc - 7
Skipping remote device: Bedroom RemoteLinc - 8
Skipping device non button 1 device: Sophia Keypad.Light
Skipping device non button 1 device: Sophia Keypad.A
Skipping device non button 1 device: Sophia Keypad.B
Skipping device non button 1 device: Sophia Keypad.C
Skipping device non button 1 device: Sophia Keypad.D
Skipping device non button 1 device: Sarah Keypad-Main
Skipping device non button 1 device: Sarah Keypad-A
Skipping device non button 1 device: Sarah Keypad-B
Skipping device non button 1 device: Sarah Keypad-C
Skipping device non button 1 device: Sarah Keypad-D
Skipping device non button 1 device: Sam Keypad.Light
Skipping device non button 1 device: Sam Keypad.A
Skipping device non button 1 device: Sam Keypad.B
Skipping device non button 1 device: Sam Keypad.C
Skipping device non button 1 device: Sam Keypad.D
Skipping motion device: Basement Motion Sensor-Sensor
Skipping motion device: Basement Motion Sensor-Dusk.D
Skipping motion device: Basement Motion Sensor-Low Ba
Skipping motion device: Kitchen Motion Sensor-Sensor
Skipping motion device: Kitchen Motion Sensor-Dusk.Da
Skipping motion device: Kitchen Motion Sensor-Low Bat
Skipping device non button 1 device: Garage Keypad.Hallway
Skipping device non button 1 device: Garage Keypad.Away
Skipping device non button 1 device: Garage Keypad.ArrriveHome
Skipping device non button 1 device: Garage Keypad.Night
Skipping device non button 1 device: Garage Keypad.Alarm
Skipping device non button 1 device: Garage Keypad.Home
Skipping device non button 1 device: Garage Keypad.Gate
Skipping device non button 1 device: Garage Keypad.Garage
Skipping device non button 1 device: Office Keypad.Main
Skipping device non button 1 device: Office Keypad.B
Skipping device non button 1 device: Office Keypad.C
Skipping device non button 1 device: Office Keypad.D
Skipping device non button 1 device: Office Keypad.E
Skipping device non button 1 device: Office Keypad.F
Skipping device non button 1 device: Office Keypad.G
Skipping device non button 1 device: Office Keypad.H
Loaded 60 devices
[ISY] Initializing platform accessory 'ApplianceLink.F0'...
[ISY] Initializing platform accessory 'Back Door.Off.To.Lock'...
[ISY] Initializing platform accessory 'Back Door.On.To.Lock'...
[ISY] Initializing platform accessory 'Basement Door Switch'...
[ISY] Initializing platform accessory 'Basement Rec Room Back Door'...
[ISY] Initializing platform accessory 'Basement Rec Room Inner Wall'...
[ISY] Initializing platform accessory 'Basement Stairs Bottom'...
[ISY] Initializing platform accessory 'Basement Stairs Top - Main'...
[ISY] Initializing platform accessory 'Bedroom.Side Gate'...
[ISY] Initializing platform accessory 'Butlers Pantry'...
[ISY] Initializing platform accessory 'Deck Door Lock'...
[ISY] Initializing platform accessory 'Dinning Room Inner Wall'...
[ISY] Initializing platform accessory 'Dinning Room Outer Wall - Mai'...
[ISY] Initializing platform accessory 'Front Door Lock'...
[ISY] Initializing platform accessory 'Front Door.1'...
[ISY] Initializing platform accessory 'Front Hall Front Door'...
[ISY] Initializing platform accessory 'Front Hall Main Hall - Main'...
[ISY] Initializing platform accessory 'Garage Light'...
[ISY] Initializing platform accessory 'Girls Inner'...
[ISY] Initializing platform accessory 'Girls Outer'...
[ISY] Initializing platform accessory 'Kitchen Alcove'...
[ISY] Initializing platform accessory 'Kitchen Island'...
[ISY] Initializing platform accessory 'Kitchen Main'...
[ISY] Initializing platform accessory 'Kitchen Table'...
[ISY] Initializing platform accessory 'Living Room Lamplinc'...
[ISY] Initializing platform accessory 'Living Room Switch'...
[ISY] Initializing platform accessory 'Main Floor Bathroom'...
[ISY] Initializing platform accessory 'Main Floor Closet'...
[ISY] Initializing platform accessory 'Main Floor Fireplace'...
[ISY] Initializing platform accessory 'Main Floor Hall Front Hall'...
[ISY] Initializing platform accessory 'Main Floor Hall Kitchen'...
[ISY] Initializing platform accessory 'Main Floor Hall Office'...
[ISY] Initializing platform accessory 'Main Floor TV Room'...
[ISY] Initializing platform accessory 'Main Floor TV Room Lamplinc'...
[ISY] Initializing platform accessory 'Master Bathroom'...
[ISY] Initializing platform accessory 'Master Bedroom Fireplace'...
[ISY] Initializing platform accessory 'Master Bedroom LampLinc'...
[ISY] Initializing platform accessory 'Master Bedroom.1'...
[ISY] Initializing platform accessory 'Outside Plug Left of Garage'...
[ISY] Initializing platform accessory 'Outside Plug Left of Porch'...
[ISY] Initializing platform accessory 'Outside Plug Right Side'...
[ISY] Initializing platform accessory 'Pantry Light'...
[ISY] Initializing platform accessory 'Play Room'...
[ISY] Initializing platform accessory 'Sam Fan-Light'...
[ISY] Initializing platform accessory 'Sam Fan-Motor'...
[ISY] Initializing platform accessory 'Sarah Fan-Light'...
[ISY] Initializing platform accessory 'Sarah Fan-Motor'...
[ISY] Initializing platform accessory 'Server Room'...
[ISY] Initializing platform accessory 'Sophia Fan-Light'...
[ISY] Initializing platform accessory 'Sophia Fan-Motor'...
[ISY] Initializing platform accessory 'Stairs Scones'...
[ISY] Initializing platform accessory 'Upstairs Hall By Bath'...
[ISY] Initializing platform accessory 'Upstairs Hall By Bath - Main'...
[ISY] Initializing platform accessory 'Upstairs Hall By Laundry'...
[ISY] Initializing platform accessory 'Upstairs Hall By Master'...
[ISY] Initializing platform accessory 'Upstairs Stairs By Bath - Mai'...
[ISY] Initializing platform accessory 'Upstairs Stairs Main Floor'...
[ISY] Initializing platform accessory 'Upstairs Stairs Top Left'...
Scan this code with your HomeKit App on your iOS device:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
  Accessory [TollHome] Creating new AccessoryInfo for our HAP server +0ms
  Accessory [TollHome] Creating new IdentifierCache +3ms
  EventedHTTPServer Server listening on port 51826 +15ms
  EventedHTTPServer [10.0.1.247] New connection from client +24s
  EventedHTTPServer [10.0.1.247] HTTP server listening on port 54826 +0ms
  EventedHTTPServer [10.0.1.247] HTTP request: /pair-setup +2ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-setup +0ms
  HAPServer [CC:22:3D:E3:CE:30] Pair step 1/5 +1ms
  EventedHTTPServer [10.0.1.247] HTTP Repsonse is finished +9ms
  EventedHTTPServer [10.0.1.247] HTTP request: /pair-setup +8s
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-setup +0ms
  HAPServer [CC:22:3D:E3:CE:30] Pair step 2/5 +0ms
  EventedHTTPServer [10.0.1.247] HTTP Repsonse is finished +9ms
  EventedHTTPServer [10.0.1.247] HTTP request: /pair-setup +114ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-setup +0ms
  HAPServer [CC:22:3D:E3:CE:30] Pair step 3/5 +0ms
  HAPServer [CC:22:3D:E3:CE:30] Pair step 4/5 +4ms
  HAPServer [CC:22:3D:E3:CE:30] Pair step 5/5 +0ms
  Accessory [TollHome] Paired with client EA6FE169-03EC-4E31-BE96-9C2CD0D14C73 +2ms
  EventedHTTPServer [10.0.1.247] HTTP Repsonse is finished +1ms
  EventedHTTPServer [10.0.1.247] Client connection closed +23ms
  EventedHTTPServer [10.0.1.247] HTTP connection was closed +1ms
  EventedHTTPServer [10.0.1.247] HTTP server was closed +0ms
  EventedHTTPServer [10.0.1.247] New connection from client +44ms
  EventedHTTPServer [10.0.1.247] HTTP server listening on port 54826 +1ms
  EventedHTTPServer [10.0.1.247] HTTP request: /pair-verify +1ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +0ms
  HAPServer [CC:22:3D:E3:CE:30] Pair verify step 1/2 +1ms
  EventedHTTPServer [10.0.1.247] HTTP Repsonse is finished +1ms
  EventedHTTPServer [10.0.1.247] HTTP request: /pair-verify +42ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +0ms
  HAPServer [CC:22:3D:E3:CE:30] Pair verify step 2/2 +1ms
  HAPServer [CC:22:3D:E3:CE:30] Client EA6FE169-03EC-4E31-BE96-9C2CD0D14C73 verification complete +0ms
  EventedHTTPServer [10.0.1.247] HTTP Repsonse is finished +0ms
  EventedHTTPServer [10.0.1.247] HTTP request: /accessories +6ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: GET /accessories +0ms
  EventedHTTPServer [10.0.1.247] HTTP Repsonse is finished +11ms
  EventedHTTPServer [10.0.1.247] HTTP request: /pairings +414ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pairings +0ms
  HAPServer [CC:22:3D:E3:CE:30] Removing pairing info for client +1ms
  Accessory [TollHome] Unpairing with client EA6FE169-03EC-4E31-BE96-9C2CD0D14C73 +0ms
  EventedHTTPServer [10.0.1.247] HTTP Repsonse is finished +1ms
  EventedHTTPServer [10.0.1.247] Client connection closed +14ms
  EventedHTTPServer [10.0.1.247] HTTP connection was closed +1ms
  EventedHTTPServer [10.0.1.247] HTTP server was closed +0ms

**Comment by KhaosT** [comment]
```js
{
   "iid":7,
   "type":"00000049-0000-1000-8000-0026BB765291",
   "characteristics":[
      {
         "iid":8,
         "type":"00000023-0000-1000-8000-0026BB765291",
         "perms":[
            "pr"
         ],
         "format":"string",
         "value":"Deck Door Lock",
         "description":"Name"
      }
   ]
}
```
For Switch service, power characteristic is mandatory and it is missing from here.

**Comment by rodtoll** [comment]
It is working now. This did the trick 

BTW, the issue up above is caused by a ZWave door lock. The new ISY devices can support ZWave and when they do they don't have the same shape as the regular Insteon nodes. For future reference this is what one of the lock nodes looks like:

````
<node flag="128">
<address>ZW005_1</address>
<name>Deck Door Lock</name>
<family>4</family>
<parent type="3">42035</parent>
<type>4.64.3.0</type>
<enabled>true</enabled>
<deviceClass>0</deviceClass>
<wattage>0</wattage>
<dcPeriod>0</dcPeriod>
<pnode>ZW005_1</pnode>
<sgid>1</sgid>
<devtype>
<gen>4.64.3</gen>
<mfg>297.2.0</mfg>
<cat>111</cat>
<model>5</model>
</devtype>
<property id="ST" value="0" formatted="Unlocked" uom="11"/>
</node>
````

**Comment by leoneleone** [comment]
@rodtoll  can you please detail the steps you took to fix the issue?

I'm running into the same problem with an ISY Zwave lock already part of my ISY setup.
When I try to add my "homebridge" as an accessory using an app, after entering the correct HomeKit setup code, I get "Adding Accessory Failed" error on my iOS device. 

How can I fix this? 
Thanks 😊

**Comment by rodtoll** [comment]
Hi @leoneleone . I had three problems:

1. ISY.js expects all devices it exposes to have a uom value in their expected list of values. See controlcharacteristics definition which has the list. uom="11", like a ZWave lock has is not one of those expected values. 
2. To command a ZWave lock the commands are different from light switches. You need to use a SECMD/<State you want> instead of DON/DOF command. 
3. There were some nodes in my ISY network which crashed the new ISYAccessory call in ISY.js.  

To address (3) I put a try catch around the new ISYAccessory. To address (1) and (2) I had it skip my door lock. In ISYPlatform.prototype, in accessories, I added this line after var enabled = obj.enabled[0]:

''''
if(obj.type[0] == '4.64.3.0') {
    enabled = false;
}
''''

This tells the loop parsing nodes to skip the lock node. So you get to add your other items but don't get a door lock.

The real fix is to detect the zWave lock type and construct a lock node instead of a light switch and handle it in the code.
