### ISSUE TITLE
No Access Over Internet

### ISSUE THREAD

**Issue by platini76** [nfarina/homebridge#2096]
Hello,
I have no access over internet to my homebridge.
I have an apple tv configured on the same network...
is this a bug or mine issue?
thanks for help to all!

**Comment by ebaauw** [comment]
Make sure to login with the same iCloud login on your AppleTV as on your iPhone.

**Comment by platini76** [comment]
I discover now that it was a problem of conflict with another homebridge on the same lan... maybe it is solved. thanks!
