### ISSUE TITLE
Two or more network interfaces make homebridge unstable

### ISSUE THREAD

**Issue by DRazumovskiy** [nfarina/homebridge#2098]
I'm running homebridge on Raspberry Pi which has 2 network interfaces enabled as shown on simple diagram below:

**Home WiFi** 192.168.30.x------wlan0-**Rapsberry**-eth0------**HomeAutomation** 192.168.220.x

I noticed that after some period time when I do not use an Home App it takes quite a long time for it to connect to homebridge. I did a research and found out that the problem is in how homebridge announces itself using **bonjour** mDNS service. Using a Bonjour Viewer I found out that 2 IP addresses were advertised for Homebridge service: 192.168.220.1, 192.168.35.150 (in this exact order). First IP is not accessible from Home WiFi because it belongs to another isolated network for home automation device. Incorrect IP address specification caused spontaneous unavailability of homebridge service.

### Expected Behavior
I would expect that only manually configured interfaces are announced in bonjour service

### Current Behavior
Homebridge relies on **[HAP-NodeJS](https://github.com/KhaosT/HAP-NodeJS)** which in turns uses **[bonjur](https://github.com/watson/bonjour)** for advertising a bonjour service. Current realization of bonjour service does not allow specification of an interfaces, and actually all available external network 
interfaces are advertised in bonjour service as can be seen in the code below (_Service.js_):

```
 _records: function () {
    var records = [this._rrPtr(), this._rrSrv(), this._rrTxt()]

    var interfaces = os.networkInterfaces()
    for (var ifaceID in interfaces) {
      var iface = interfaces[ifaceID]
      for (var i = 0; i < iface.length; i++) {
        var address = iface[i]
        if (address.internal) { continue }

        records.push(
                    address.family === 'IPv4'
                    ? this._rrA(address.address)
                    : this._rrAaaa(address.address))
      }
    }
    return records
  },
```

There is a [pull request](https://github.com/watson/bonjour/pull/28) from **Feb 2017** which enables manual specification of interfaces, but project seems a bit abandoned and I really doubt that this pull request will ever be merged.

Unfortunately, an option in homebridge configuration that controls mdns interfaces cannot resolve the issue with wrongly advertised IPs. This option only instructs bonjour service to listen on a specific interface, but has nothing to do with IP addresses advertised in the response.

### Workarounds
I've found 2 quite "dirty" workarounds for this issue.
**Workaround 1**
1. Install Bonjour Explorer on any device
2. Write down all parameters listed for Homebridge service
3. Disable mDNS service in homebridge by setting "interface":
```json
{
    "mdns": {
        "interface": "127.0.0.1"
}
```
4. In avahi services configuration folder create a new service definition as following:
```
<service-group>

  <name replace-wildcards="yes">Homekit on %h</name>

  <service>
    <type>_hap._tcp</type>
    <domain-name>local</domain-name>
    <host-name>xxxxxxxxx.local</host-name>
    <port>NNNNN</port>
    <txt-record>pv=1.0</txt-record>
    <txt-record>sh=XYZXYZ</txt-record>
    <txt-record>ff=0</txt-record>
    <txt-record>ci=2</txt-record>
    <txt-record>id=XX:XX:XX:XX:XX:XX</txt-record>
    <txt-record>md=YYYYYYYYYYY</txt-record>
    <txt-record>c#=NN</txt-record>
    <txt-record>s#=1</txt-record>
  </service>
</service-group>
```

**Workaround 2 (currently in use)**
Locally patch code of /usr/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Service.js

1. Comment a part related to interfaces discovery
2. Hard code an IP address that you wish to use for service advertising:
```
  _records: function () {
    var records = [this._rrPtr(), this._rrSrv(), this._rrTxt()]

/* CUSTOM 2018-12-29
    var interfaces = os.networkInterfaces()
    for (var ifaceID in interfaces) {
      var iface = interfaces[ifaceID]
      for (var i = 0; i < iface.length; i++) {
        var address = iface[i]
        if (address.internal) { continue }

        records.push(
                    address.family === 'IPv4'
                    ? this._rrA(address.address)
                    : this._rrAaaa(address.address))
      }
    }
*/
    records.push(this._rrA('192.168.30.150'));
// CUSTOM 2018-12-29 //

    return records
  },
```

### Versions
- **Homebridge**: 0.4.45
- **Node**:       v8.15.0
- **OS**:         4.14.79-v7+ armv7l

### Configuration
```json
{
    "mdns": {
        "interface": "192.168.30.150"
}
```

**Comment by NorthernMan54** [comment]
I had thought that this issue was resolved with this change back on June 25th?

https://github.com/nfarina/homebridge/commit/aea4684526f1675cb15f4d034b73fd222795dcdc

Unfortunately this is not a documented feature

**Comment by langovoi** [comment]
I have some problem, but both workarounds don't work for me.
First workaround allow to find bridge, but I got error "Couldn't add Homebridgre-XXXX"

**Comment by gonzalezcalleja** [comment]
I have the same issue that @langovoi, with v0.4.50

Using "mans" in config.json isn't enough for me, I have a bond interface (bond0) for my lan and a lot of interfaces for docker, etc .. 

The only solution that I found was fixing only one IP address on bonjour-hap (Services.js):

`  
_records: function () {
    var records = [this._rrPtr(), this._rrSrv(), this._rrTxt()]

/*    var interfaces = os.networkInterfaces()
    for (var ifaceID in interfaces) {
      var iface = interfaces[ifaceID]
      for (var i = 0; i < iface.length; i++) {
        var address = iface[i]
        if (address.internal) { continue }

        records.push(
                    address.family === 'IPv4'
                    ? this._rrA(address.address)
                    : this._rrAaaa(address.address))
      }
    }*/
    records.push(this._rrA('192.168.1.101'));
    return records
  },
`

Without comment the discovery interfaces part, doesn't work. 

I think that could be useful add a "interface(s)" setup in config.json for set the interface(s) for bonjour services.
