### ISSUE TITLE
[Feature] Phillips hue shim

### ISSUE THREAD

**Issue by stephenyeargin** [nfarina/homebridge#21]
There is a fairly robust [node module](https://github.com/peter-murray/node-hue-api) that, if I'm reading this all correctly, could be used in creating a shim. I did a [refactor](https://github.com/kingbin/hubot-philipshue/pull/8) on a Hubot module recently to use that one, so I may be able to take a look at this one.

**Comment by nfarina** [comment]
I would love this personally, I have a couple Hue lights at home but just haven't gotten around to writing the shim. Also it kept seeming like they were on the verge of supporting HomeKit natively, but apparently not!

**Comment by stephenyeargin** [comment]
Looks like it may require some lower-level work in the HAP-NodeJS library? This is mentioned in the wiki as a fork that built-in Hue support.

https://github.com/KhaosT/HAP-NodeJS/compare/master...renssies:master

**Comment by nfarina** [comment]
I don't think anything would be required of `HAP-NodeJS` - the fork you pointed to does include Hue support but it's built on top of "standard" HAP-NodeJS and could probably be ported easily to HomeBridge.

**Comment by jhurliman** [comment]
+1 for this

**Comment by stephenyeargin** [comment]
Some WIP stuff:

- Add `"node-hue-api": "^1.0.5",` to `package.json`
- https://gist.github.com/stephenyeargin/80da50e53fcd5c241f6c

So far:

```
Stephens-Air:homebridge (master) stephen$ npm run start

> homebridge@0.0.0 start /Users/stephen/Sites/homebridge
> node app.js

Starting HomeBridge server...
Loading 1 platforms...
[Phillips Hue] Initializing PhilipsHue platform...
[Phillips Hue] Fetching Philips Hue lights...
Loading 0 accessories...
[Phillips Hue] Initializing device with name undefined...
/Users/stephen/Sites/homebridge/node_modules/node-hue-api/node_modules/q/q.js:126
                    throw e;
                          ^
TypeError: Cannot read property 'lights' of null
    at /Users/stephen/Sites/homebridge/platforms/PhilipsHue.js:200:15
    at resolveError (/Users/stephen/Sites/homebridge/node_modules/node-hue-api/hue-api/utils.js:40:13)
    at _rejected (/Users/stephen/Sites/homebridge/node_modules/node-hue-api/node_modules/q/q.js:797:24)
    at /Users/stephen/Sites/homebridge/node_modules/node-hue-api/node_modules/q/q.js:823:30
    at Promise.when (/Users/stephen/Sites/homebridge/node_modules/node-hue-api/node_modules/q/q.js:1035:31)
    at Promise.promise.promiseDispatch (/Users/stephen/Sites/homebridge/node_modules/node-hue-api/node_modules/q/q.js:741:41)
    at /Users/stephen/Sites/homebridge/node_modules/node-hue-api/node_modules/q/q.js:557:44
    at flush (/Users/stephen/Sites/homebridge/node_modules/node-hue-api/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:355:11)

npm ERR! Darwin 14.3.0
npm ERR! argv "/opt/boxen/nodenv/versions/v0.12.4/bin/node" "/opt/boxen/nodenv/versions/v0.12.4/bin/npm" "run" "start"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE
npm ERR! homebridge@0.0.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the homebridge@0.0.0 start script 'node app.js'.
npm ERR! This is most likely a problem with the homebridge package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls homebridge
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/stephen/Sites/homebridge/npm-debug.log
```

**Comment by nfarina** [comment]
Cool! It's a good start.

Would it be possible for the shim to "autodiscover" the Hue bridge instead of requiring that you figure out its IP?

**Comment by stephenyeargin** [comment]
Not as sure about that one. The [one thing](https://github.com/kingbin/hubot-philipshue) I've worked with have required you to at least have the IP address.

**Comment by nfarina** [comment]
Looks like the underlying lib does have a `locateBridges()` or `nupnpSearch()`: https://github.com/peter-murray/node-hue-api

**Comment by stephenyeargin** [comment]
Cool. That's something that can definitely be added, but I'd like to see if I can get it working with a manual configuration first. I've opened #28 if you or anybody gets a chance to look into why it doesn't quite work. At this point, I'm just brute-force trying to get it to work. :smile:
