### ISSUE TITLE
Manual homebridge restart loop

### ISSUE THREAD

**Issue by vzlgdu** [nfarina/homebridge#2100]
My homebridge configuration, works fine after every server reboot, but if I stop homebridge manually using the commands: "**sudo systemctl stop homebridge**", it goes in a loop of start and stop:

- standard startup messages
- Got SIGTERM, shutting down Homebridge...
- homebridge.service: Main process exited, code=exited, status=143/n/a
- Stopped Node.js HomeKit Server.
- homebridge.service: Unit entered failed state.
- homebridge.service: Failed with result 'exit-code'.
- Started Node.js HomeKit Server.

after this last message the loop starts again...
If i reboot the server, everything works fine.
Do you have any suggest?
Thanks

**Comment by tbelcher** [comment]
Did you have any luck with this?   I'm also getting the exit status 143 error.....

Thanks,

Tim
