### ISSUE TITLE
OpenVPN and Homebridge

### ISSUE THREAD

**Issue by Baeda73** [nfarina/homebridge#2101]
When OpenVPN and its interfaces / settings is started before homebridge, homebridge does not bind to any network interface and is not reachable.

### Expected Behavior

I expect homebridge to start and bind to the network interfaces independent of OpenVPN.

### Current Behavior

see above

### Steps to Reproduce (for bugs)

see above

Output if homebridge is started before Openvpn
netstat -an | grep 51826
tcp        0      0 0.0.0.0:51826           0.0.0.0:*               LISTEN   

no output if openvpn is started before, no binding to any interface, not reachable.

### Versions

- **Homebridge**: `homebridge --version`
0.4.45
- **Node**:       `node --version`
v8.11.1

- **OS**:         
Raspberry Pi on Debian 9.6

**Comment by mrpharderwijk** [comment]
I think this is a duplicate of #1192 and #2162
