### ISSUE TITLE
LG SmartThinq Homebridge Integration

### ISSUE THREAD

**Issue by grapestech** [nfarina/homebridge#2102]
Hello !

Have anyone tested or worked on integrating LG Smartthinq devices (air conditioners, washing machines, fridges) via homebridge?

I know there's a reversed engineered API library called wideq https://github.com/sampsyo/wideq that connects to the devices. 

Thanks.

**Comment by kaiatkins** [comment]
I added a bounty for it

https://www.bountysource.com/issues/68328887-lg-smartthinq-homebridge-integration

I need it for my LG Air Conditioner

Hopefully people can kick in to get it done :)

**Comment by jcapayne** [comment]
I added bounty too. For washing machine I hope :)

**Comment by kafeg** [comment]
I added bounty too, for LG AC.

**Comment by carlittoer** [comment]
Hi ! Apparently someone wrote this for the AC: https://github.com/beele/HomebridgeLgSmartThinqAirco

I tried it and it works.

Cheers.

**Comment by kafeg** [comment]
Great, thank you!

**Comment by rashmendis** [comment]
https://www.npmjs.com/package/homebridge-lg-airco

**Comment by ssut** [comment]
Hi, I'm working on porting wideq to node.js: see https://github.com/ssut/wideq-js to follow along. As far as I can see it will not be a hard task so it will not take long time to complete. I think this work can help improve the homebridge ecosystems, and also reduce the overhead incurred by spawning a python process.

**Comment by rashmendis** [comment]
@ssut nice. let us know when you are done. btw any of you guys know to change the min and max temperature? [ current min - 18 and max - 26 ]

**Comment by K2i4n6g8** [comment]
@carlittoer
The id in the config file reverse to ?
the model number ?
Or the name in the app ?

**Comment by carlittoer** [comment]
Hi,

You obtain this id from executing the command mentioned in the installation instructions. 

Cheers.

**Comment by u20p17** [comment]
Hi,
are there any news regarding this topoc? I would like to integrate my washing maschine to homebridge.

Cheers
