### ISSUE TITLE
[Discussion] NEW! TV and DoorBells

### ISSUE THREAD

**Issue by iRayanKhan** [nfarina/homebridge#2104]
Hello everyone I have big news!

As you may or may not have heard, a TV accessory is going to be available for HomeKit starting in the spring. So far Samsung, Vizio, and LG are the first 3 companies to announce this. The Tv will have its own icon and support AirPlay2. 

Why is this a discussion and what does this have to do with doorbells?'

Well with CES we have seen 2 new HomeKit doorbells (not released yet) and with this the DoorBell accessory should soon work with HomeKit without it being "Not supported by Home App".

And with tv's HomeBridge plugins can now be a TV icon instead of a switch.

Now this is a discussion and there are some points I want to make.

AirPlay 2 won't be available to HomeBridge Tv's unless someone cracks AirPlay 2 Protocol. 
Also we are unsure if Tv's can be directly added with HomeBridge because it may be like the speaker service which again needs AirPlay 2. But someone has made it where a Speaker Accessory can be added with HomeBridge.

I would love to see what people have to say about this.

**Comment by ebaauw** [comment]
Apple’s Home app only supports the Speaker service in a Video Doorbell accessory.  Other HomeKit apps typically support it alright.  The support for Airplay2 speakers and TVs in Apple’s Home app and in Siri has nothing to do with the Speaker service or even the HomeKit Accessory Protocol (HAP) that homebridge and other HomeKit accessories use.  If/when Airplay2 will be reverse engineered, any software implementation of that wll run independently from homebridge.

**Comment by KhaosT** [comment]
@ebaauw From Apple's website, it looks like there might actually have a HAP TV profile in addition to normal AirPlay 2 thing for controlling other stuff... We'll see if that's going to be the case or not 😅

**Comment by iRayanKhan** [comment]
@khaosT that’s great news since I can replace the switch accessory that is used to turn the tv on, with the Tv accessory.

**Comment by SoulOnFire** [comment]
KhosT already make a commit with the basic TV support

https://github.com/KhaosT/HAP-NodeJS/pull/638

**Comment by Supereg** [comment]
Regarding the latest changes, how exactly does the TelevisionSpeaker Service work. Is it like the Doorbell speaker and can only be used with Television Service?

**Comment by Supereg** [comment]
If Samsung has some http API endpoints 

> If someone release a plugin for Samsung 2016 TVs with Tizen, I think I would die of happiness. I've been waiting for this for a looooooooooooooooooooooooooooong time.

If Samsung has some API endpoints to control the TV that would be no problem. However as far as I know Samsung TVs doesn't have this. Or does anyone have other information?

A way more hacky way would be building your own IR Remote you can control with Homebridge. Doable but not the cleanest way, especially chasing input channel would be weird.

**Comment by NorthernMan54** [comment]
If you have a LG TV they have a RS232 port on the back that you can use to control it.  The manual even included the protocol ( At least mine does ).

**Comment by greensouth** [comment]
> > If someone release a plugin for Samsung 2016 TVs with Tizen, I think I would die of happiness. I've been waiting for this for a looooooooooooooooooooooooooooong time.
> 
> If Samsung has some API endpoints to control the TV that would be no problem. However as far as I know Samsung TVs doesn't have this. Or does anyone have other information?
> 
> A way more hacky way would be building your own IR Remote which you could control with Homebridge. Doable but not the cleanest way, especially chasing input channel would be weird.

Well, there are a few Homebridge plugins for sending commands to Tizen TV's, but you have to assign actions as switches.

**Comment by KhaosT** [comment]
@Supereg Yeah the speaker service requires a valid TV service bundled in accessory to get UI under Remote app.

**Comment by Supereg** [comment]
@KhaosT ah, so the service doesn’t show up in home but is rather used to make the remote in control center working?

**Comment by ebaauw** [comment]
Are the new services and characteristics also visible in Apple's Home app?  Can you include them in HomeKit scenes and automations?  Does Apple's Remote app adjust itself according to the valid values for _Remote Key_?  Anxiously awaiting the first _public_ beta of 12.2, so I can see for myself...

I'll be happy to make homebridge-zp expose the Sonos speakers using _TV_ and _Television Volume_ services, if we don't lose the ability to include them automations.

**Comment by iRayanKhan** [comment]
@Supereg @ebaauw They show in the home app yes, so do Speakers. 

@ebaauw I can give you my developer beta copy I have a dev account.

**Comment by KhaosT** [comment]
@ebaauw Yes, most of characteristics are accessible by normal HomeKit API. It's possible to add things to action set and automations. I haven't tried to change available values, but I assume so since there are checks for supported buttons.

**Comment by ebaauw** [comment]
Been experimenting exposing my Sonos speakers using the Television service.  On iOS 12.2 public beta 1, the Home app shows a TV for each of my five zones, as expected.  I can turn them on or off, select the input, change the input names.  Nice.

In the Remote widget, next to my AppleTV, only on of the homebridge TVs shows (which one seems random).  I do get the corresponding remote key values (up, down, left, right, centre, play/pause, back, exit, i).  The TV is not visible in the AppleTV Remote app.

I cannot find a way to control the volume, even though I expose a TelevisionSpeaker service.  Not sure whether I'm looking in the right place on my iPhone, or whether I'm missing something in the service.  Any hints are highly appreciated.

**Comment by KhaosT** [comment]
@ebaauw right now the only way to control volume is using physical volume buttons on iOS device while in Remote widget.

**Comment by iRayanKhan** [comment]
Closed:
Inactive thread & everyone seems to know what they are doing or want to do now.
