### ISSUE TITLE
Homebridge extract current state output

### ISSUE THREAD

**Issue by NK74** [nfarina/homebridge#2106]
Hello,

I'm using Homebridge on a Rpi 3 and precisely a Xiaomi Mijia Bluetooth Temperature (with this plugin : https://github.com/hannseman/homebridge-mi-hygrothermograph/ )

And my question today : I would like to know if it's possible to extract the current sensor state/data (temperature, and state) form Homebridge log ? I want to send this data into a Grafana or monitoring tool.

Thanks
NK

**Comment by iRayanKhan** [comment]
There may be a plugin for this or just have the ~~~ -D ~~~ debug  flag for that plugin

**Comment by NK74** [comment]
Hello Rayan,

I talk about all the state/sensor and log from Homebridge itself not my plugin.

Do you have an idea?

Thanks
