### ISSUE TITLE
Problems with RP 2 and Homebridge

### ISSUE THREAD

**Issue by frizby66** [nfarina/homebridge#211]
Know this is not a forum, but have been struggling for two days trying to get Homebridge running.

1) Can I leave RP running wheezy or should I update to Jessie (have tried both)?
2) Readme says I should use 0.12 nodejs but I get and error saying a dependency is looking for 0.10. Should I ignore?
3) Have tried various combinations, but when I try and run Homebridge I get the following error:-

> homebridge@0.1.1 start /home/pi/homebridge
> DEBUG=\* node app.js || true

module.js:338
    throw err;
          ^
Error: Cannot find module '../build/Release/dns_sd_bindings'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/pi/homebridge/node_modules/mdns/lib/dns_sd.js:32:22)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

Any suggestions?

**Comment by cflurin** [comment]
It works with wheezy. How to install on RPi: [here](https://github.com/cflurin/homebridge-shims/wiki/Minimalist-Homebridge-on-a-Raspberry-Pi)

**Comment by frizby66** [comment]
Thanks, will try tonight.

**Comment by flynhawaiian** [comment]
I'm still having this problem as above, even following these different directions on a pi 2 b.  It installed fine on my pi B+ about 3 months ago but this new version seems to be having issues.  Any other thoughts?

**Comment by neonightmare** [comment]
Got also an Error on my Pi2:

pi@raspberrypi ~/homebridge $ npm run start

> homebridge@0.1.1 start /home/pi/homebridge
> DEBUG=* node app.js || true

module.js:338
    throw err;
    ^

Error: Cannot find module 'HAP-NodeJS'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/pi/homebridge/app.js:4:11)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
pi@raspberrypi ~/homebridge $

**Comment by cflurin** [comment]
Additional specifications would be useful, like:
```sh
uname -a
nove -v
gcc --version
````
Is it a new installation or an update?

**Comment by flynhawaiian** [comment]
I'm doing a brand new install.  I tried using the wheezy image, now going to do the noobs image and see if that makes a difference?

Are we supposed to be using 4.0.0 or 0.10.0?  Just trying to ensure.

**Comment by cflurin** [comment]
I testet node 4.0.0 and node 4.1.1 it works removing some dependencies, take a look at the link above.
Otherwise you also can install node 0.12.x >>> Readme!
```sh
Note: You'll need to have NodeJS version 0.12.x or better installed for required submodule HAP-NodeJS to load.
```

**Comment by flynhawaiian** [comment]
So this time should I install 0.12 or 4.1.1?

**Comment by cflurin** [comment]
@flynhawaiian my favor is node 4.1.1, it up to you.
Keep in mind that doing an upgrade later will install the latest node version anyway.

**Comment by flynhawaiian** [comment]
Okay interesting when I try to do gcc -version i get:
gcc (Debian 4.6.3-14+rpi1) 4.6.3

Then I do a sudo apt-get install gcc-4.8 g++4.8

It says unable to locate package g++4.8

**Comment by cflurin** [comment]
uname -a ?

**Comment by flynhawaiian** [comment]
After the gcc and gcc++ update to 4.8 it still states:

gcc (Debian 4.6.3-14+rpi1) 4.6.3

uname -a:
linux raspberrypi 3.18.11-v7+ #781 present ...

**Comment by frizby66** [comment]
Same here…

gcc (Debian 4.6.3-14+rpi1) 4.6.3

After doing update

**Comment by flynhawaiian** [comment]
updating the firmware to see if that fixes the issue.

**Comment by cflurin** [comment]
```sh
sudo apt-get update
sudo apt-get upgrade
````
and reboot the RPi

**Comment by cflurin** [comment]
@frizby66 reboot the RPi

**Comment by flynhawaiian** [comment]
firmware update rebooted.  Did the gcc --version: came up with debian 4.6.3

then did the sudo apt-get install gcc-4.8 gcc++4.8
"g++-4,8 is already the newest version
gcc-4.8 is already the newest version"

gcc --version:
"gcc (Debian 4.6.3-14+rpi1) 4.6.3"

**Comment by cflurin** [comment]
do this additionally:
```sh
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.6 20
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.6 20
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50
```

**Comment by frizby66** [comment]
Reboot and still the same!

Is it a permission issue, should I be doing Sudo su first?

Am logged in as pi

**Comment by cflurin** [comment]
@frizby66 try the additional update-alternatives above

**Comment by flynhawaiian** [comment]
say 4.8.2 now :)

**Comment by cflurin** [comment]
Great! I'll update the wiki.

**Comment by flynhawaiian** [comment]
seems like HAP-NodeJS install is missing in instructions

**Comment by frizby66** [comment]
That appeared to work

pi@raspberrypi ~ $ gcc --version                                                gcc (Raspbian 4.8.2-21~rpi3rpi1) 4.8.2
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by cflurin** [comment]
@flynhawaiian I'm not sure I understand you. Sure is HAP-NodeJs needed.

**Comment by flynhawaiian** [comment]
It's missing in the instructions unless it's auto included in the home bridge install?

**Comment by cflurin** [comment]
@flynhawaiian I see, "npm install" will do the job.
Please, post your package.json before you start install.

**Comment by flynhawaiian** [comment]
{
  "name": "homebridge",
  "description": "HomeKit support for the impatient",
  "version": "0.1.1",
  "scripts": {
    "start": "DEBUG=* node app.js || true"
  },
  "repository": {
    "type": "git",
    "url": "git://github.com/nfarina/homebridge.git"
  },
  "license": "ISC",
  "dependencies": {
    "ad2usb": "git+https://github.com/alistairg/node-ad2usb.git#local",
    "carwingsjs": "0.0.x",
    "chokidar": "^1.0.5",
    "color": "0.10.x",
    "eibd": "^0.3.1",
    "elkington": "kevinohara80/elkington",
    "hap-nodejs": "git+https://github.com/KhaosT/HAP-NodeJS#4650e771f356a220868d873d16564a6be6603ff7",
"lifx-api": "^1.0.1",
    "lifx": "git+https://github.com/magicmonkey/lifxjs.git",
    "mdns": "^2.2.4",
    "node-icontrol": "^0.1.4",
    "node-milight-promise": "0.0.x",
    "node-persist": "0.0.x",
    "q": "1.4.x",
    "tough-cookie": "^2.0.0",
    "request": "2.49.x",
    "sonos": "0.8.x",
    "telldus-live": "0.2.x",
    "teslams": "1.0.1",
    "unofficial-nest-api": "git+https://github.com/hachidorii/unofficial_nodejs_nest.git#d8d48edc952b049ff6320ef99afa7b2f04cdee98",
   "xml2js": "0.4.x",
    "xmldoc": "0.1.x",
    "komponist" : "0.1.0",
    "yamaha-nodejs": "0.4.x",
    "debug": "^2.2.0"
  }
}

**Comment by cflurin** [comment]
@flynhawaiian Do you really need all the packages? However this should work anyway.

**Comment by flynhawaiian** [comment]
I'm using it for smart things so I'm not sure I even need any packages?

**Comment by cflurin** [comment]
@flynhawaiian Ok, did you install Avahi? If yes then you can start "npm install"

**Comment by flynhawaiian** [comment]
yes.

**Comment by frizby66** [comment]
I want to try with:-

Nest
Sonos
Philips Hue

What should I leave in?

**Comment by cflurin** [comment]
@frizby66 I don't know exactly what the packages need. Just remove the minimum:
```sh
"harmonyhubjs-client": "^1.1.4",
"harmonyhubjs-discover": "git+https://github.com/swissmanu/harmonyhubjs-discover.git",
```

**Comment by frizby66** [comment]
Best to remove or comment out?

**Comment by cflurin** [comment]
@frizby66 you have to remove them.

**Comment by flynhawaiian** [comment]
seems like it's installing fine this time.  Need a few more minutes and I'll let you know.  Seems like that Gcc and g++ were the main issue.

**Comment by frizby66** [comment]
Got some errors…

Near the start:-

npm WARN engine ad2usb@1.0.3: wanted: {"node":"~0.10.0"} (current: {"node":"4.0.                                                              0","npm":"2.14.2"})
npm WARN optional dep failed, continuing fsevents@1.0.0

Then towards the end:-

In file included from ../lib/kerberos.cc:1:0:
../lib/kerberos.h:5:27: fatal error: gssapi/gssapi.h: No such file or directory
 #include <gssapi/gssapi.h>
                           ^
compilation terminated.
kerberos.target.mk:92: recipe for target 'Release/obj.target/kerberos/lib/kerberos.o' failed
make: *** [Release/obj.target/kerberos/lib/kerberos.o] Error 1
make: Leaving directory '/home/pi/homebridge/node_modules/teslams/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.1.7-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/homebridge/node_modules/teslams/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok
unofficial-nest-api@0.1.4 node_modules/unofficial-nest-api

Thoughts?

**Comment by cflurin** [comment]
Are  you in the homebridge folder?

Did you:
```sh
npm install
```
or
```sh
sudo npm install
```

**Comment by frizby66** [comment]
npm install

**Comment by frizby66** [comment]
in homebridge directory

**Comment by cflurin** [comment]
@frizby66 "npm install" is Ok, hmm just now I don't know the reason.
Please post your package.json and uname -a

**Comment by flynhawaiian** [comment]
works.  Problem is it still says use native api of avahi (sp?)

**Comment by cflurin** [comment]
@flynhawaiian That is Ok, ignore the messages.

**Comment by frizby66** [comment]
pi@raspberrypi ~/homebridge $ uname -a
Linux raspberrypi 4.1.7-v7+ #817 SMP PREEMPT Sat Sep 19 15:32:00 BST 2015 armv7l GNU/Linux

{
  "name": "homebridge",
  "description": "HomeKit support for the impatient",
  "version": "0.1.1",
  "scripts": {
    "start": "DEBUG=* node app.js || true"
  },
  "repository": {
    "type": "git",
    "url": "git://github.com/nfarina/homebridge.git"
  },
  "license": "ISC",
  "dependencies": {
    "ad2usb": "git+https://github.com/alistairg/node-ad2usb.git#local",
    "carwingsjs": "0.0.x",
    "chokidar": "^1.0.5",
    "color": "0.10.x",
    "eibd": "^0.3.1",
    "elkington": "kevinohara80/elkington",
    "hap-nodejs": "git+https://github.com/KhaosT/HAP-NodeJS#4650e771f356a220868d873d16564a6be6603ff7",
    "lifx-api": "^1.0.1",
    "lifx": "git+https://github.com/magicmonkey/lifxjs.git",
    "mdns": "^2.2.4",
    "node-hue-api": "^1.0.5",
    "node-icontrol": "^0.1.4",
    "node-milight-promise": "0.0.x",
    "node-persist": "0.0.x",
    "q": "1.4.x",
    "tough-cookie": "^2.0.0",
    "request": "2.49.x",
    "sonos": "0.8.x",
    "telldus-live": "0.2.x",
    "teslams": "1.0.1",
    "unofficial-nest-api": "git+https://github.com/hachidorii/unofficial_nodejs_nest.git#d8d48edc952b049ff6320ef99afa7b2f04cdee98",
    "wemo": "0.2.x",
    "wink-js": "0.0.5",
    "xml2js": "0.4.x",
    "xmldoc": "0.1.x",
    "komponist" : "0.1.0",
    "yamaha-nodejs": "0.4.x",
    "debug": "^2.2.0"
  }
}

**Comment by frizby66** [comment]
Also, when I run npm run start I get this:-

> homebridge@0.1.1 start /home/pi/homebridge
> DEBUG=* node app.js || true

*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
Starting HomeBridge server...
_____________________________________________________________________
IMPORTANT: Homebridge is in the middle of some big changes.
           Read more about it here:
           https://github.com/nfarina/homebridge/wiki/Migration-Guide
_____________________________________________________________________

**Comment by cflurin** [comment]
@frizby66 remove 
```sh
    "teslams": "1.0.1",
```
in package.json
und run
```sh
npm install
````
again

**Comment by frizby66** [comment]
Running…

**Comment by frizby66** [comment]
No errors on build, but when I download the fake files I get this error:-

pi@raspberrypi ~/homebridge $ npm run start

> homebridge@0.1.1 start /home/pi/homebridge
> DEBUG=* node app.js || true

*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
Starting HomeBridge server...
_____________________________________________________________________
IMPORTANT: Homebridge is in the middle of some big changes.
           Read more about it here:
           https://github.com/nfarina/homebridge/wiki/Migration-Guide
_____________________________________________________________________

There was a problem reading your config.json file.
Please try pasting your config.json file here to validate it: http://jsonlint.com

/home/pi/homebridge/app.js:43
  throw err;
  ^

SyntaxError: Unexpected token <
    at Object.parse (native)
    at Object.<anonymous> (/home/pi/homebridge/app.js:37:17)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3

**Comment by cflurin** [comment]
Ok, I need a cup of coffee :coffee:

**Comment by cflurin** [comment]
@frizby66 check your config.json [here]( http://jsonlint.com)

**Comment by frizby66** [comment]
Progress…managed to get the fake files to work perfectly (least I think i did).

Using mytouchHome app I could add Fake-Homebridge and add a fake_accessory (outlet).

Progress!

Just need to try and get my real stuff to talk.

In the Hue settings, it asks for a username. Not sure if this means my hue account name or the name of the Hue bridge or something else?

**Comment by cflurin** [comment]
... I don't know much about the packages like Hue, try or have a look at the documentation.

**Comment by frizby66** [comment]
When I try validating the sample json I get errors…is this right?

Parse error on line 119:
...vice.",            //"requiredDeviceId"
----------------------^
Expecting 'STRING'

**Comment by frizby66** [comment]
Looks like it is running…built the json file and validated each part.

When you run with Hue is generates a username which you put in the config file and it works. Just need to try and sort Nest. Looks like the accessory details are built around US Nest system which are different from UK (we don’t have Air Con, only heat).

Thanks for the help, will keep you updated on progress :-)

**Comment by frizby66** [comment]
Got most things working, but the system see’s my Nest as a long serial number “oooooo4A-00000-10000….” any ideas how to change that to something more sensible?

Not sure where it is getting that details from!

**Comment by neonightmare** [comment]
@cflurin 
THX, gcc was the reason.. works now on my Raspi2..

--> will try now EIBD & Yamaha

**Comment by frizby66** [comment]
Got everything working and then tried to install the load on boot. Got no errors but wouldn't load on boot and now something very strange is happening. Removed the load on boot script and when I run npm run start from command prompt, everything loads but the home bridge is not visible within MyTouchHome (it was before). Have tried npm install again and also tried npm cache clear and still can't see it. This is what I see:-
pi@raspberrypi ~/homebridge $ npm run start

> homebridge@0.1.1 start /home/pi/homebridge
> DEBUG=* node app.js || true

*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
Starting HomeBridge server...
_____________________________________________________________________
IMPORTANT: Homebridge is in the middle of some big changes.
           Read more about it here:
           https://github.com/nfarina/homebridge/wiki/Migration-Guide
_____________________________________________________________________

Loading 3 platforms...
[Nest] Initializing Nest platform...
[Nest] Fetching Nest devices.
[Phillips Hue] Initializing PhilipsHue platform...
[Phillips Hue] Fetching Philips Hue lights...
[Phillips Hue] Attempting to discover Philips Hue bridge with meethue.com...
[Sonos] Initializing Sonos platform...
[Sonos] Fetching Sonos devices.
Loading 0 accessories...
[Sonos] Found device at 192.168.1.205
[Sonos] Found device at 192.168.1.190
[Sonos] Found device at 192.168.1.163
[Sonos] Found playable device - Living Room
[Sonos] Ignoring playable device with duplicate room name - Living Room
[Sonos] Found playable device - Bedroom
[Sonos] Found device at 192.168.1.180
[Sonos] Found device at 192.168.1.233
[Sonos] Found device at 192.168.1.234
[Sonos] Found device at 192.168.1.111
[Sonos] Found device at 192.168.1.119
[Sonos] Ignoring playable device with duplicate room name - Living Room
[Sonos] Ignoring playable device with duplicate room name - Bedroom
[Sonos] Found playable device - Kitchen
[Sonos] Found playable device - BRIDGE
[Phillips Hue] Philips Hue bridges found:
        192.168.1.126 - 001788fffe14395f
[Phillips Hue] Save the Philips Hue bridge ip address 192.168.1.126 to your config to skip discovery.
[Phillips Hue] Initializing platform accessory 'Bedroom'...
[Phillips Hue] Initializing platform accessory 'Living Room'...
[Nest] Initializing platform accessory ''...
[Sonos] Initializing platform accessory 'Living Room Sonos'...
[Sonos] Initializing platform accessory 'Bedroom Sonos'...
[Sonos] Initializing platform accessory 'Kitchen Sonos'...
[Sonos] Initializing platform accessory 'BRIDGE Sonos'...
Scan this code with your HomeKit App on your iOS device:

    ┌────────────┐
    │ 031-45-154 │
    └────────────┘

  EventedHTTPServer Server listening on port 51826 +0ms

**Comment by frizby66** [comment]
Solved: Deleted cache files in "persist" directory.

**Comment by dreameruk** [comment]
I have exactly the same issue above ^ all worked, made load on boot and now phone cannot see homebridge, which files did you delete and did you stop loading on boot to resolve?

Thanks,

**Comment by frizby66** [comment]
Hi Dreameruk,

I removed into PI and found a folder called “persists” or similar and deleted the two cache files in there. Ran again and everything worked fine.

**Comment by dreameruk** [comment]
Thanks will give it a try tonight

**Comment by frizby66** [comment]
BTW folder your looking for is inside homebridge folder.

**Comment by dreameruk** [comment]
Thanks!

If anyone knows the exact path it would be great, did not think Homebridge had a cache?

**Comment by frizby66** [comment]
/home/pi/homebridge/persist

Delete the two files in here. Run the install again and it should work.

**Comment by cflurin** [comment]
You don't need to run install again! just "npm run start". But following solution will do the job:

Change config.json
```javascript
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
```
to an other Name and username

```javascript
    "bridge": {
        "name": "Homebridge-02",
        "username": "CC:22:3D:E3:CE:31",
        "port": 51826,
        "pin": "031-45-154"
    },
```

and run homebridge again.

EVE will find the new Homebridge-02.

**Comment by snowdd1** [comment]
It's not really a cache. Homebridge (in fact it's hap-nodjs behind) need to store the uuids and the pairing status of each accessory (with homebridge it's only the bridge itself).
If the bridge is stored as already paired, you will not find it in "add accessory" in your HomeKit app. If it has vanished, it was usually because somehow an incompliant value has been sent to the HomeKit framework, say you've got an thermostat that is returning negative Degrees Celsius despite Apple assumed only values above freezing point. The actual a hap-nodejs should guard against such incompliant values, do you have updated to the latest version of homebridge and did a `npm update` ?

**Comment by dreameruk** [comment]
@frizby66 Thanks, will delete them

@cflurin Thanks will also do this.

Just to check, I have set my Pi to load Homebridge on boot (as per instructions on Wiki), I assume I do not need to run anything else? Is there a way to see the output/debug when loading on boot?

Thanks for all the help!

**Comment by ekwarg** [comment]
@frizby66  how did you get the real stuff to talk?

**Comment by rhearob** [comment]
I don't know if you are still having problems, but FWIW - I had the devils time getting Homebridge to install and run on wheezy.  It took some time, but I updated everything to Jesse and bam everything worked beautifully.  I am on Pi B+.  

It works great with my Yamaha receiver and with he MyQ garage door.  I am struggling with getting the ZWayServer plug in to work.  I think it may have more to do with trying to secure the Z-Way than anything else.

**Comment by Slepperpon** [comment]
Dad working till power surge took out rpi have new one but just cant get it to work
here is what i have
pi@raspberrypi ~/homebridge $ npm run start
npm ERR! Linux 4.1.7-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.12

npm ERR! missing script: start
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/homebridge/npm-debug.log
pi@raspberrypi ~/homebridge $ node -v
v5.0.0
pi@raspberrypi ~/homebridge $ npm -v
u3.3.12
pi@raspberrypi ~/homebridge $ uname -a
Linux raspberrypi 4.1.7-v7+ #817 SMP PREEMPT Sat Sep 19 15:32:00 BST 2015 armv7l GNU/Linux
pi@raspberrypi ~/homebridge $ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/arm-linux-gnueabihf/4.9/lto-wrapper
Target: arm-linux-gnueabihf
Configured with: ../src/configure -v --with-pkgversion='Raspbian 4.9.2-10' --with-bugurl=file:///usr/share/doc/gcc-4.9/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.9 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.9 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libitm --disable-libquadmath --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.9-armhf/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.9-armhf --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.9-armhf --with-arch-directory=arm --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-sjlj-exceptions --with-arch=armv6 --with-fpu=vfp --with-float=hard --enable-checking=release --build=arm-linux-gnueabihf --host=arm-linux-gnueabihf --target=arm-linux-gnueabihf
Thread model: posix
gcc version 4.9.2 (Raspbian 4.9.2-10)

**Comment by Hogster** [comment]
I have tried verahomebridgekit (working) and Homebridge (not working).

When running Homebridge I could find the bridge but no devices. I decided to remove and reinstall homebridge. Now I cant find the bridge. From the start I could not find verahomebridekit either but found the persist folder and voila! Now I don't seem to find the same folder for Homebridge.

Homebridge seems to be installed on "/usr/local/lib/node_modules/homebridge" but there is no persist folder. I'm I looking at the wrong place, I did not have a "/home/pi/homebridge/persist" folder.

Sorry for probably stupid issue, but I'm in the learning curve of RPI etc.... BTW great work!

**Comment by xtech86** [comment]
Hi Guys,

I'm really struggling with the legacy plugins. PI2 fresh OS install. Running:

sudo npm install -g homebridge-legacy-plugins

results in:

`└─┬ homebridge-legacy-plugins@0.2.0 
  ├── ad2usb@1.0.5  (git+https://github.com/alistairg/node-ad2usb.git#0e08d434e648a7e38d50ffffa55ff1d90eaedcf3)
  ├── elkington@0.1.0  (git://github.com/kevinohara80/elkington.git#80bc9cc77faeee2a8ce22c0c12a2c73023044131)
  ├─┬ komponist@0.1.0
  │ └─┬ shoe@0.0.4
  │   └── sockjs-client@0.0.0-unreleasable  (git://github.com/substack/sockjs-client.git#40d48d06b4dba884416bf88a051f76ca3c8ffcae)
  └── lifx@0.3.1  (git+https://github.com/magicmonkey/lifxjs.git#cfb4814d447d119a4db410274499d8ee77f66d96)

npm WARN optional Skipping failed optional dependency /homebridge-legacy-plugins/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14`

Any suggestions? Can't seem to find away around it.

**Comment by AppleTechy** [comment]
@tonypartridge Why are you trying to use Legacy Plugins? Most legacy plugins have more modern versions written, or need new modern version written
