### ISSUE TITLE
Trouble Pairing Apple TV to Homebridge

### ISSUE THREAD

**Issue by Crox77** [nfarina/homebridge#2113]
Hi I have been following this Guide to Add Apple TV Theatre Mode to My Homebridge and have been following this Guide https://github.com/edc1591/homebridge-theater-mode/blob/master/README.md

All seems to install fine until I try to Pair the Apple TV 4K Box when I type appletv pair it is then followed by this error message: 
 
/usr/local/lib/node_modules/node-appletv/node_modules/bindings/bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /usr/local/lib/node_modules/node-appletv/node_modules/ed25519/build/ed25519.node
 → /usr/local/lib/node_modules/node-appletv/node_modules/ed25519/build/Debug/ed25519.node
 → /usr/local/lib/node_modules/node-appletv/node_modules/ed25519/build/Release/ed25519.node
 → /usr/local/lib/node_modules/node-appletv/node_modules/ed25519/out/Debug/ed25519.node
 → /usr/local/lib/node_modules/node-appletv/node_modules/ed25519/Debug/ed25519.node
 → /usr/local/lib/node_modules/node-appletv/node_modules/ed25519/out/Release/ed25519.node
 → /usr/local/lib/node_modules/node-appletv/node_modules/ed25519/Release/ed25519.node
 → /usr/local/lib/node_modules/node-appletv/node_modules/ed25519/build/default/ed25519.node
 → /usr/local/lib/node_modules/node-appletv/node_modules/ed25519/compiled/10.15.0/darwin/x64/ed25519.node
    at bindings (/usr/local/lib/node_modules/node-appletv/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/node-appletv/node_modules/ed25519/index.js:1:99)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)

Anybody have any ideas?

As I said yesterday I am very new to this and none of that makes sense and I can not find what it means by "Can not find Bindings File"

Thank You 
Paul

**Comment by Crox77** [comment]
So ive tried reinstalling the Thetre mode plugin and I get this error message

npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-theater-mode
npm ERR! path /usr/local/lib/node_modules/homebridge-theater-mode
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules/homebridge-theater-mode'
npm ERR!  { [Error: EACCES: permission denied, access '/usr/local/lib/node_modules/homebridge-theater-mode']
npm ERR!   stack:
npm ERR!    'Error: EACCES: permission denied, access \'/usr/local/lib/node_modules/homebridge-theater-mode\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules/homebridge-theater-mode' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Crox-iMac/.npm/_logs/2019-01-18T19_09_05_904Z-debug.log


Any help guys please?

**Comment by iRayanKhan** [comment]
Put this issue on that plugin. Try ``` sudo npm i -g homebridge-theatre-mode --unsafe-perm ```
