### ISSUE TITLE
Restarting homebridge causes HomeKit to forget rooms and names

### ISSUE THREAD

**Issue by mikesalz** [nfarina/homebridge#2119]
I have seen other similar threads, but no solutions or workarounds.  When I restart homebridge or the host machine, all homebridge devices forget their room assignments and revert back to their original names (I give customized names within HomeKit).

**Comment by KhaosT** [comment]
Can you share you setup so I can figure out why this is happening? How are you running homebridge, and what's the version of OS you are using?

**Comment by mikesalz** [comment]
Thanks for the reply.  Homebridge is running on a Synology NAS - version DSM 6.2.1-23824 Update 4.  Let me know what else you might need for debugging, and I'll be happy to share.  Thanks!

**Comment by KhaosT** [comment]
On Synology, using a Docker? If so, can you point me to the Docker file you use? I think it might be related to that not persisting related configuration files...

**Comment by mikesalz** [comment]
Correct, I am using a Docker.  I used the instructions from this page: https://github.com/oznu/docker-homebridge/wiki/Homebridge-on-Synology

Was that helpful, or are you looking for specific json files?  I'm fairly new to Synology, linux, and homebridge, so please forgive my ignorance if I ask dumb questions!

**Comment by mikesalz** [comment]
@KhaosT I ended up deciding to delete the container, delete the image, and then completely uninstall docker. Possibly overkill.  But when I reinstalled everything, it seems to be working.  I think I just mucked something up somewhere when adding stuff, changing stuff, and deleting stuff.  Everything seems good now, so I'm happy.  Thanks again for all of your help!

**Comment by KhaosT** [comment]
Good to know :)
