### ISSUE TITLE
Multiple Lightbulb services not compliant

### ISSUE THREAD

**Issue by SphtKr** [nfarina/homebridge#212]
So I'm trying to bridge one of these Aeon labs RGB+W+W bulbs, so it has a RGB control, a main dimmer, and a "Cold White" and a "Soft White" dimmer. I've added subtype parameters to the service constructor call, so I get past the error message telling me to do that. But I can't add the bridge to any app (out of compliance), and looking at the `/accessories` output, I don't see the subtype parameter coming out anywhere...should it? It seems that just looking at the JSON there's no distinction between the two services...should there be?

I'm only adding one of the white dimmers so far, and ignore the duplication of the hue/saturation characteristics, I'll fix that later (unless this is the problem...?).

    {
    "accessories": [
        {
            "aid": 1,
            "services": [
                {
                    "iid": 1,
                    "type": "0000003E-0000-1000-8000-0026BB765291",
                    "characteristics": [
                        {
                            "iid": 2,
                            "type": "00000014-0000-1000-8000-0026BB765291",
                            "perms": [
                                "pw"
                            ],
                            "format": "bool",
                            "description": "Identify"
                        },
                        {
                            "iid": 3,
                            "type": "00000020-0000-1000-8000-0026BB765291",
                            "perms": [
                                "pr"
                            ],
                            "format": "string",
                            "value": "Default-Manufacturer",
                            "description": "Manufacturer"
                        },
                        {
                            "iid": 4,
                            "type": "00000021-0000-1000-8000-0026BB765291",
                            "perms": [
                                "pr"
                            ],
                            "format": "string",
                            "value": "Default-Model",
                            "description": "Model"
                        },
                        {
                            "iid": 5,
                            "type": "00000023-0000-1000-8000-0026BB765291",
                            "perms": [
                                "pr"
                            ],
                            "format": "string",
                            "value": "HomebridgeZ",
                            "description": "Name"
                        },
                        {
                            "iid": 6,
                            "type": "00000030-0000-1000-8000-0026BB765291",
                            "perms": [
                                "pr"
                            ],
                            "format": "string",
                            "value": "Default-SerialNumber",
                            "description": "Serial Number"
                        }
                    ]
                }
            ]
        },
        {
            "aid": 2,
            "services": [
                {
                    "iid": 1,
                    "type": "0000003E-0000-1000-8000-0026BB765291",
                    "characteristics": [
                        {
                            "iid": 2,
                            "type": "00000014-0000-1000-8000-0026BB765291",
                            "perms": [
                                "pw"
                            ],
                            "format": "bool",
                            "description": "Identify"
                        },
                        {
                            "iid": 3,
                            "type": "00000020-0000-1000-8000-0026BB765291",
                            "perms": [
                                "pr"
                            ],
                            "format": "string",
                            "value": "Z-Wave.me",
                            "description": "Manufacturer"
                        },
                        {
                            "iid": 4,
                            "type": "00000021-0000-1000-8000-0026BB765291",
                            "perms": [
                                "pr"
                            ],
                            "format": "string",
                            "value": "Virtual Device (VDev version 1)",
                            "description": "Model"
                        },
                        {
                            "iid": 5,
                            "type": "00000023-0000-1000-8000-0026BB765291",
                            "perms": [
                                "pr"
                            ],
                            "format": "string",
                            "value": "Dimmer 18-0 Aeon Labs",
                            "description": "Name"
                        },
                        {
                            "iid": 6,
                            "type": "00000030-0000-1000-8000-0026BB765291",
                            "perms": [
                                "pr"
                            ],
                            "format": "string",
                            "value": "VDev--1503061047",
                            "description": "Serial Number"
                        }
                    ]
                },
                {
                    "iid": 7,
                    "type": "00000043-0000-1000-8000-0026BB765291",
                    "characteristics": [
                        {
                            "iid": 8,
                            "type": "00000023-0000-1000-8000-0026BB765291",
                            "perms": [
                                "pr"
                            ],
                            "format": "string",
                            "value": "Dimmer 18-0 Aeon Labs",
                            "description": "Name"
                        },
                        {
                            "iid": 9,
                            "type": "00000025-0000-1000-8000-0026BB765291",
                            "perms": [
                                "pr",
                                "pw",
                                "ev"
                            ],
                            "format": "bool",
                            "value": false,
                            "description": "On"
                        },
                        {
                            "iid": 10,
                            "type": "00000008-0000-1000-8000-0026BB765291",
                            "perms": [
                                "pr",
                                "pw",
                                "ev"
                            ],
                            "format": "int",
                            "value": 2,
                            "description": "Brightness",
                            "unit": "percentage",
                            "maxValue": 100,
                            "minValue": 0,
                            "minStep": 1
                        },
                        {
                            "iid": 11,
                            "type": "00000013-0000-1000-8000-0026BB765291",
                            "perms": [
                                "pr",
                                "pw",
                                "ev"
                            ],
                            "format": "float",
                            "description": "Hue",
                            "unit": "arcdegrees",
                            "maxValue": 360,
                            "minValue": 0,
                            "minStep": 1
                        },
                        {
                            "iid": 12,
                            "type": "0000002F-0000-1000-8000-0026BB765291",
                            "perms": [
                                "pr",
                                "pw",
                                "ev"
                            ],
                            "format": "float",
                            "description": "Saturation",
                            "unit": "percentage",
                            "maxValue": 100,
                            "minValue": 0,
                            "minStep": 1
                        }
                    ]
                },
                {
                    "iid": 13,
                    "type": "00000043-0000-1000-8000-0026BB765291",
                    "characteristics": [
                        {
                            "iid": 14,
                            "type": "00000023-0000-1000-8000-0026BB765291",
                            "perms": [
                                "pr"
                            ],
                            "format": "string",
                            "value": "Soft White 18-0-51-0 Aeon Labs",
                            "description": "Name"
                        },
                        {
                            "iid": 15,
                            "type": "00000025-0000-1000-8000-0026BB765291",
                            "perms": [
                                "pr",
                                "pw",
                                "ev"
                            ],
                            "format": "bool",
                            "value": true,
                            "description": "On"
                        },
                        {
                            "iid": 16,
                            "type": "00000008-0000-1000-8000-0026BB765291",
                            "perms": [
                                "pr",
                                "pw",
                                "ev"
                            ],
                            "format": "int",
                            "value": 2,
                            "description": "Brightness",
                            "unit": "percentage",
                            "maxValue": 100,
                            "minValue": 0,
                            "minStep": 1
                        },
                        {
                            "iid": 17,
                            "type": "00000013-0000-1000-8000-0026BB765291",
                            "perms": [
                                "pr",
                                "pw",
                                "ev"
                            ],
                            "format": "float",
                            "description": "Hue",
                            "unit": "arcdegrees",
                            "maxValue": 360,
                            "minValue": 0,
                            "minStep": 1
                        },
                        {
                            "iid": 18,
                            "type": "0000002F-0000-1000-8000-0026BB765291",
                            "perms": [
                                "pr",
                                "pw",
                                "ev"
                            ],
                            "format": "float",
                            "description": "Saturation",
                            "unit": "percentage",
                            "maxValue": 100,
                            "minValue": 0,
                            "minStep": 1
                        }
                    ]
                }
            ]
        }
    ]
    }

**Comment by KhaosT** [comment]
It seems your "Hue" and "Saturation" characteristics missing "value"

**Comment by cflurin** [comment]
@SphtKr I'm experimenting with the AEON LED Bulb ZE098-C55. Did you manage do include the Bulb without configurations warnings. It partially works but  e.g. SwitchColor returns an error:
````
Node 3:0 CC SwitchColor: Unknown command 0x05
[2015-09-29 10:24:46.355] [E] [zway] Error returned from _zway_cc_call_handler(zway, command, controller->id, 0, data[4], &data[5]): Not implemented by the library (-3)
```

**Comment by SphtKr** [comment]
Doh! You're right...the bulb happened to be set to a shade of gray/white which takes a different code path that had a bug (h and s were undefined). Working fine now, sorry!
