### ISSUE TITLE
Delete Persist and Accessories results in "No response"

### ISSUE THREAD

**Issue by Kepete** [nfarina/homebridge#2121]
### Expected Behavior

I have some old accessorise that have been removed from config.json but still appear as not responding on Home app. Usually to fix this I delete the persist folder with 10 files and accessories folders with one file, restart Homebridge and everything works fine. 
 

### Current Behavior

I delete the folders and after this homebridge start fine but shows for everything in Home app "No response".  But it is running nicely. And creates new files int the persist folder. This time only 8 files instead of 10. Accessorise folder looks the same

### Steps to Reproduce (for bugs)

Delete persist and accessories folder, restart homebridge, "No response" in home app.
But the deleted folders back, everything works again.  

### Versions

- **Homebridge**: `0.4.38`
- **Node**:       `v8.9.4`
- **OS**:         Raspbian GNU/Linux 9 (stretch)
### Configuration

```json

```

### Homebridge Log / Command Output

```

```

The only difference that comes into my mind about why it worked before is and not now is that I have since started using homebridge as a systemctl service. But eventhought when I stop the service and try it as usual with homebridge command the same thing happens.

**Comment by ebaauw** [comment]
This is by design: the `persist` directory contains the pairing info.  Deleting it is like factory resetting homebridge - you need to delete it from HomeKit and pair it again.

**Comment by Kepete** [comment]
What would be a walkaround for this? Would not want to add all my family again to a new home always when a accessory is left in Home app eventhought when deleted from config.json. 

Also, I have done it before without issues. What is the problem now?

**Comment by Kepete** [comment]
@ebaauw  Sorry I misread your comment a bit. But deleting the accessories directory does not clean up the old accessories sadly.

**Comment by iRayanKhan** [comment]
Do the following:
``` cd .homebridge/ ```
``` sudo rm -r Persist/ ```
``` sudo rm -r Accessories/```
Then remove the bridge from HomeKit in the Home App.
Use the same home you already have and restart Homebridge *AFTER* removing the Persist and Accessories folder *including* the bridge. 
After doing this Start HomeBridge and then add the Bridge accessory to the same home. No need to re-invite again.

**Comment by JoeWoodward** [comment]
Is there no way we could try to auto correct the corrupt files? It’s really frustrating having to keep doing this

**Comment by mriksman** [comment]
Agreed. I tried the -R option. Logs said it cleaned up the accessory. But it still appeared on my phone. So I deleted the cachedAccessories - and left the persist folder alone. 
Everything now shows No Response.
There HAS to be a better way?

**Comment by bday1978** [comment]
having similar issues, whats the fix? I want to be able to delete old accessories without deleting Persist folder. so I don`t have to setup everything from scratch again.

**Comment by mriksman** [comment]
At the moment, I'm opening cachedAccessories in Notepad++ with the JSON Viewer plugin, and then finding the accessory I want to delete. It's fiddly, but it works.

**Comment by ebaauw** [comment]
See #2428
