### ISSUE TITLE
Error: EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by mikesalz** [nfarina/homebridge#2122]
I am new top homebridge, and recently installed it on a Synology Diskstation using a docker.  It was working fine until I stopped and restarted the container.  Now homebridge is stuck in an endless error loop.  This happened earlier today, and I removed the container, the image, and even uninstalled docker.  I reinstalled everything, and it worked fine for hours until I stopped and restarted the service again.  Any idea what is going on?

![image](https://user-images.githubusercontent.com/46855061/51447638-24ff0e00-1cee-11e9-864d-d2c6acd12dd5.png)

**Comment by mikesalz** [comment]
Thanks for nothing

**Comment by emeidi** [comment]
Homebridge crashes shortly after starting with this error message when there is a subfolder within the `persist` folder. Deleting the subfolder solves the issue.

Kudos to @kevinkub for figuring this out: [homebridge-aedes/issues/2](https://github.com/kevinkub/homebridge-aedes/issues/2#issuecomment-772843085)

Suggestion: Homebridge should spit out a warning, ignore the subfolder, and continue to work as expected.
