### ISSUE TITLE
Config.JSON Problem

### ISSUE THREAD

**Issue by Crox77** [nfarina/homebridge#2123]
Hi can somebody please tell me what is wrong with this JSON Please?

{
"platforms": [{
"platform": "Camera-IP",
"cameras": [{
"name": "Name of the camera eg. GARAGE",
"videoConfig": {
"source": "-re -i rtsp://10.0.19.10:554/Streaming/Channels/101",
"stillImageSource": "-i http://10.0.19.10/Streaming/channels/101/picture",
"maxStreams": 2,
"maxWidth": 1280,
"maxHeight": 720,
"maxFPS": 30
}
}]
}

Thank You Paul

**Comment by KhaosT** [comment]
https://jsonlint.com/ is your friend.

```
{
	"platforms": [{
		"platform": "Camera-IP",
		"cameras": [{
			"name": "Name of the camera eg. GARAGE",
			"videoConfig": {
				"source": "-re -i rtsp://10.0.19.10:554/Streaming/Channels/101",
				"stillImageSource": "-i http://10.0.19.10/Streaming/channels/101/picture",
				"maxStreams": 2,
				"maxWidth": 1280,
				"maxHeight": 720,
				"maxFPS": 30
			}
		}]
	}]
}
```

**Comment by Crox77** [comment]
Thank You For that, so know I've added all my other items to the JSON I still keep getting errors from that address you gave me and I can not work it out

{
	"bridge": {
		"name": "Homebridge2",
		"username": "CC:22:3D:E3:CE:31",
		"port": 51826,
		"pin": "031-45-153"
	},
	"platforms": [{
			"platform": "Camera-IP",
			"cameras": [{
					"name": "Name of the camera eg. GARAGE",
					"videoConfig": {
						"source": "-re -i rtsp://10.0.19.10:554/Streaming/Channels/101",
						"stillImageSource": "-i http://10.0.19.10/Streaming/channels/101/picture",
						"maxStreams": 2,
						"maxWidth": 1280,
						"maxHeight": 720,
						"maxFPS": 30
					},
					"accessories": [{
							"accessory": "HiveThermostat",
							"name": "Hive Thermostat",
							"username": "88888888888",
							"password": "88888888"
						},
						{
							"accessory": "SkyQ",
							"name": "Sky Q Lounge",
							"ipAddress": "192.168.0.11"
						},
						{
							"accessory": "SkyQ",
							"name": "Sky Q Bedroom",
							"ipAddress": "192.168.0.23"
						},
						{
							"accessory": "SamsungTV",
							"name": "Samsung TV",
							"ip": "192.168.0.5",
							"mac": "70:2a:d5:8a:ab:af",
							"type": "power"
						}
					}]
			}]
	}
