### ISSUE TITLE
"getaddrinfo ENOTFOUND null null:80" when calling ESP8266-HTTP-IR-Blaster via Homebridge/Homekit

### ISSUE THREAD

**Issue by scoover** [nfarina/homebridge#2125]
I'm working through [NorthernMan54's tutorial](https://github.com/NorthernMan54/homebridge-HTTP-IRBlaster) to leverage Homebridge & Homekit to control our fireplace using the [ESP8266-HTTP-IR-Blaster project](https://github.com/mdhiggins/ESP8266-HTTP-IR-Blaster).

I can successfully talk directly to the HTTP-IR-Blaster using this endpoint:
`http://192.168.1.16:667/json?simple=1&pass=100&plain=[{%22type%22:%22raw%22,%22out%22:1,%22data%22:[200,700,700,200,700,200,700,200,200,700,700,200,200,700,200,700,200,700,700,200,200,700,700,200,700,200,700,200,200,700,200,700,200,700,700,200,700,200,200,700,200,700,700,200,700,200],%22khz%22:500,%22pulse%22:10,%22pdelay%22:30}]`
(The IR Blaster responds with a "**Success, code sent**" message and I can see the transmission in the ESP8266-HTTP-IR-Blaster's log.)

What isn't working is when I try to make the request to the IR Blaster through Homekit/Homebridge...

(I originally [posted this issue](https://github.com/mdhiggins/ESP8266-HTTP-IR-Blaster/issues/243) to ESP8266-HTTP-IR-Blaster, but the IR Blaster seems to be working via direct HTTP requests. It feels like the problem is my configuration mapping the Homebridge-Homekit request properly to the IR Blaster instance.)

I'm running Homebridge and have paired the service with my iPhone. The fireplace accessory that I've created in the config file shows up on my iPhone. When I click the icon in Homekit to run the "turn on" command, the icon spins and then I get these messages in the Homebridge log:
`[1/22/2019, 9:57:00 PM] [Fireplace] Turning Fireplace to true`
<... then, later...>
`[1/22/2019, 9:57:28 PM] [Fireplace] IR Blast failed: getaddrinfo ENOTFOUND null null:80`

My Homebridge config.json file (which mirrors [NorthernMan54's config.json](https://github.com/NorthernMan54/homebridge-HTTP-IRBlaster/blob/master/sample-fireplace.json)) follows:
```
{
  "bridge": {
    "name": "Homebridge",
    "username": "00:3E:E1:BF:02:2E",
    "pin": "031-45-154"
  },
  "description": "HomeBridge HTTP Status Control",
  "accessories": [
    {
      "accessory": "http-irblaster",
      "name": "Fireplace",
      "url": "http://192.168.1.16:667/json?pass=100&simple=1",
      "on_busy": 28000,
      "off_busy": 5000,
      "up_busy": 600,
      "down_busy": 600,
      "start": 100,
      "steps": 10,
      "rdelay": 600,
      "off_data": [
        {
          "type": "raw",
          "out": 1,
          "khz": 500,
          "data": [200, 700, 700, 200, 700, 200, 700, 200, 200, 700, 700, 200, 200, 700, 200, 700, 200, 700, 700, 200, 200, 700, 700, 200, 700, 200, 700, 200, 200, 700, 200, 700, 200, 700, 700, 200, 700, 200, 200, 700, 700, 200, 700, 200, 700, 200],
          "pulse": 10,
          "pdelay": 30
        }
      ],
      "on_data": [
        {
          "type": "raw",
          "out": 1,
          "data": [200, 700, 700, 200, 700, 200, 700, 200, 200, 700, 700, 200, 200, 700, 200, 700, 200, 700, 700, 200, 200, 700, 700, 200, 700, 200, 700, 200, 200, 700, 200, 700, 200, 700, 700, 200, 700, 200, 200, 700, 200, 700, 700, 200, 700, 200],
          "khz": 500,
          "pulse": 10,
          "pdelay": 30
        }
      ],
      "up_data": [
        {
          "type": "raw",
          "out": 1,
          "data": [200, 700, 700, 200, 700, 200, 700, 200, 200, 700, 700, 200, 200, 700, 200, 700, 200, 700, 700, 200, 200, 700, 700, 200, 700, 200, 700, 200, 200, 700, 200, 700, 200, 700, 700, 200, 700, 200, 700, 200, 200, 700, 700, 200, 700, 200],
          "khz": 500,
          "pulse": 10,
          "pdelay": 30
        }
      ],
      "down_data": [
        {
          "type": "raw",
          "out": 1,
          "data": [200, 700, 700, 200, 700, 200, 700, 200, 200, 700, 700, 200, 200, 700, 200, 700, 200, 700, 700, 200, 200, 700, 700, 200, 700, 200, 700, 200, 200, 700, 200, 700, 200, 700, 200, 700, 200, 700, 200, 700, 200, 700, 200, 700, 200, 700],
          "khz": 500,
          "pulse": 10,
          "pdelay": 30
        }
      ]
    }
  ],
  "platforms": []
}
```

I'm running Homebridge version 0.4.45 and node version v11.7.0 on a 2013 Mac Pro (Mojave 10.14.2).

Any ideas on why I'm getting the `getaddrinfo ENOTFOUND null null:80` error?

Your help is appreciated. Thanks,
scoover

P.S. I'm also getting this warning from Homebridge on startup. Is there an easy way to make it go away?
`(node:848) [DEP0118] DeprecationWarning: The provided hostname "undefined" is not a valid hostname, and is supported in the dns module solely for compatibility.`

**Comment by NorthernMan54** [comment]
Hi,

Can you open this issue against my plugin, I will answer you there.

Sean

**Comment by scoover** [comment]
Will do. 

That would be my third post (IR Blaster + homebridge + your plugin)… which I’m guessing isn’t the best.
Should I delete the other issues?

Randy

**Comment by NorthernMan54** [comment]
Sorry about the third post, but am trying to reduce the number of issues raised against homebridge when the problem is with a plugin.

I took a quick look, and it appears the sample-config.json is outdated and doesn’t reflect the current code base. If you look at the README, it is current.

Majour difference is I switched from the URL config option to irblaster.  Which is the devices hostname.  Hence the dns error and enotfound error

**Comment by scoover** [comment]
Are you saying that I delete the "url" keyword and set "irBlaster" to the hostname that I assigned the the blaster wifi setup process? e.g.:
  "irBlaster": "fireplace",


...and then the passcode I setup would go right below that like this?
"irBlaster": "fireplace",
"pass":"100",

Where does the port number go? Is it part of the irBlaster definition? e.g.
"irBlaster": "fireplace.local:667"

What amount the minimal output you had used in previous examples "simple=1"?
Any other changes required to config.json?

Three other questions:
You suggested a 23cm wire for the antenna.... I can just hang a long wire off the end of the TX pcb?
Do you know if the remotes are paired to the fireplace inserts? Or if your codes should work on all inserts with the same remote FCC ID?
As for Github hygiene... would you still like me to repost this to your GitHub project? Should I close it on the other ones (even with no responses)?

Sorry for so many questions; really appreciate your help! 
It's a super cool project and I can't wait to get it working.
Randy
