### ISSUE TITLE
Question: (i)Beacons? 

### ISSUE THREAD

**Issue by desvdp** [nfarina/homebridge#213]
Hi, has anyone figured out if it's possible to throw iBeacons in the mix. I.e. if I enter a room an event is triggered. Looking at the app I only see "GPS" location based events...

**Comment by KhaosT** [comment]
It's possible to setup an event trigger with iBeacon but so far there is no app allows you to do that.

**Comment by robertvorthman** [comment]
This app will allow you to trigger scenes when you get enter or exit the range of an iBeacon.

http://myhome-app.com/
