### ISSUE TITLE
[Request] Homebridge-Sharp

### ISSUE THREAD

**Issue by iRayanKhan** [nfarina/homebridge#2133]
Hello everyone, with the recent addition of TV's in HomeKit I have added most of my TV's. I have one tv in particular that doesn't run common OS's. 

# Info for this request:

Documentation: https://github.com/benburkhart1/sharp-aquos-remote-control

All I really want is just to be able to see if the TV is on or Off in HomeKit. Hdmi inputs are an extra. 

Thanks!

**Comment by galzil** [comment]
I've been looking at it as well for the past week,
Never wrote a plugin before, but thinking about giving it a try.
Hopefully someone more knowledgeable will try as well

**Comment by iRayanKhan** [comment]
@galzil I'll be willing to help out and test it.. Maybe I can tweak an existing tv plugin and see from there...

**Comment by toshibochan** [comment]
I’m using this and work for ON OFF only
https://github.com/reecedantin/homebridge-sharptv

**Comment by iRayanKhan** [comment]
@toshibochan Thank you for this! I will see if the plugin will work with my TV and if it does I will expose it as a TV accessory. 
https://github.com/iRayanKhan/homebridge-sharptv

**Comment by toshibochan** [comment]
That’s great!
You going to update to show as tv accessory?

**Comment by iRayanKhan** [comment]
@toshibochan I am going to attempt to, but TV's are still a little weird in my house with 1/3 of them consistently working with HomeKit. If you are willing to test the plugin that'd be amazing once it's finished.

**Comment by toshibochan** [comment]
let me know when is ready to test

**Comment by leimonio** [comment]
@toshibochan what Sharp TV model have you managed to connect as a switch? I'm getting a connection refuded error message and wonder if my config is right. How can I find the correct IP and port of the TV?

**Comment by mafyata** [comment]
Ask in plugin’s github. Here is for homebridge , not for specific plugin.
