### ISSUE TITLE
MaxListenersExceededWarning

### ISSUE THREAD

**Issue by marcodesantis71** [nfarina/homebridge#2135]
HI All,

when I start Homebridge I see this message:

"MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 didFinishLaunching listeners added. Use emitter.setMaxListeners() to increase limit"

I've not a problem to use all my plugin, but I don't know why I receive this error.

Homebridge running on Ubuntu 16.

**Comment by NorthernMan54** [comment]
Sounds like a plugin issue, can you share the detailed error message ( did it include the calling stack ).

The listener for didfinishlaunching is part of plugin API and not homebridge.

**Comment by marcodesantis71** [comment]
> Sounds like a plugin issue, can you share the detailed error message ( did it include the calling stack ).
> 
> The listener for didfinishlaunching is part of plugin API and not homebridge.

Hi,

I attached a standard output when Homebridge start.

Do you want I start Homebridge in debug mode?
[log.txt](https://github.com/nfarina/homebridge/files/2813440/log.txt)

**Comment by NorthernMan54** [comment]
I take back my comment about it possibly being a plugin issue, as I'm thinking it may be related to the sheer number of plugins in a single homebridge instance.   Based on the log, you have 13 Platform plugins so I suspect that is causing the message.

After quickly looking at the NodeJS code around the message, it appears to be just a warning, and can be ignored.

https://github.com/nodejs/node/blob/d022cb1bdd20f10483cbe988a950548df2dfd48c/lib/events.js#L192

But having 13 plugins in one instance could be a stability concern, and I would recommend creating multiple homebridge instances, with a couple in each.  Even my favorite plugin homebridge-alexa will work with multiple instances.

**Comment by marcodesantis71** [comment]
HI,

I have created a new instance and moved the plugin.
Now it works without warning

**Comment by NorthernMan54** [comment]
Awesome
