### ISSUE TITLE
Raspberry Pi install

### ISSUE THREAD

**Issue by adekka** [nfarina/homebridge#214]
I followed the instruction at the wiki for running homebridge on a Raspberry Pi. I stumble upon error(s). I googled for a solution but nothing helped so far. This is what the error message says:

> homebridge@0.1.1 start /home/pi/node_modules/homebridge
> DEBUG=* node app.js || true

module.js:338
    throw err;
          ^
Error: Cannot find module '../build/Release/dns_sd_bindings'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/pi/node_modules/homebridge/node_modules/HAP-NodeJS/node_modules/mdns/lib/dns_sd.js:32:22)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

**Comment by KhaosT** [comment]
@adekka it failed to find mdns module. Please may sure you installed the project correctly.

**Comment by cflurin** [comment]
@adekka 
```

 I googled for a solution but nothing helped so far.
```
did you see Issue #211 ?

**Comment by nzhome** [comment]
maybe you missed this step in the homebridge installation instructions readme?

Install Avahi

This is required by the mdns package in HAP-NodeJS library.

sudo apt-get install libavahi-compat-libdnssd-dev

**Comment by juliensantos87** [comment]
@adekka I install the old version http://node-arm.herokuapp.com/node_archive_armhf.deb

you can follow this link and change node_latest by node_archive in the url.
https://gist.github.com/elvisimprsntr/f23c76587d48be0ec4b9

**Comment by adekka** [comment]
@nzhome @juliensantos87 I did follow the instructions. Guess I'm missing out on something. The instructions of the wiki just doesn't do it for me. Did a mix of the suggestions..

installing npm gives me this error:
npm WARN engine ad2usb@1.0.3: wanted: {"node":"~0.10.0"} (current: {"node":"4.0.0","npm":"2.14.2"})

**Comment by adekka** [comment]
guess that this is the actual issue that i'm experiencing..

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/4.0.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/pi/homebridge/node_modules/HAP-NodeJS/node_modules/curve25519/.node-gyp"

**Comment by cflurin** [comment]
@adekka this [instruction](https://github.com/cflurin/homebridge-shims/wiki/Minimalist-Homebridge-on-a-Raspberry-Pi) works for me with Wheezy, Jessie, RPi B and RPI 2. At least one dozen people used it successfully.

**Comment by adekka** [comment]
@cflurin that's exactly what puzzles me..

**Comment by cflurin** [comment]
@adekka Let's see what's wrong. Post
```sh
uname -a
gcc --version
node -v
```
and package.json

**Comment by adekka** [comment]
@cflurin 
Linux raspberrypi 4.1.7+ #817 PREEMPT Sat Sep 19 15:25:36 BST 2015 armv6l GNU/Linux
gcc (Raspbian 4.8.2-21~rpi3rpi1) 4.8.2
v4.1.1

**Comment by cflurin** [comment]
Did you run
 ```sh
npm install
```
without errors?

are all modules installed?

```sh
cd homebridge
ls node_moules
```

**Comment by adekka** [comment]
No, got these errors:
npm WARN engine ad2usb@1.0.3: wanted: {"node":"~0.10.0"} (current: {"node":"4.1.                                                                                                                     1","npm":"2.14.4"})

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/4.1.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/pi/homebridge/node_modules/HAP-NodeJS/node_modules/curve25519/.node-gyp"
npm WARN prefer global node-gyp@3.0.3 should be installed with -g
npm WARN unmet dependency /home/pi/homebridge/node_modules/node-hue-api requires xml2js@'~0.2.2' but will load
npm WARN unmet dependency /home/pi/homebridge/node_modules/xml2js,
npm WARN unmet dependency which is version 0.4.12
npm WARN unmet dependency /home/pi/homebridge/node_modules/node-hue-api requires q@'~1.0.0' but will load
npm WARN unmet dependency /home/pi/homebridge/node_modules/q,
npm WARN unmet dependency which is version 1.4.1
npm WARN unmet dependency /home/pi/homebridge/node_modules/sonos requires debug@'~0.7.2' but will load
npm WARN unmet dependency /home/pi/homebridge/node_modules/debug,
npm WARN unmet dependency which is version 2.2.0
npm WARN unmet dependency /home/pi/homebridge/node_modules/sonos requires xml2js@'~0.2.8' but will load
npm WARN unmet dependency /home/pi/homebridge/node_modules/xml2js,
npm WARN unmet dependency which is version 0.4.12
npm WARN unmet dependency /home/pi/homebridge/node_modules/sonos requires request@'~2.27.0' but will load
npm WARN unmet dependency /home/pi/homebridge/node_modules/request,
npm WARN unmet dependency which is version 2.49.0

But less errors then before :)

**Comment by adekka** [comment]
Did this: 
> cd node_modules/mdns
> node-gyp BUILDTYPE=Release rebuild

And got a step further. However, still struggling with this:

> homebridge@0.1.1 start /home/pi/homebridge
> DEBUG=* node app.js || true

*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
Starting HomeBridge server...
_____________________________________________________________________
IMPORTANT: Homebridge is in the middle of some big changes.
           Read more about it here:
           https://github.com/nfarina/homebridge/wiki/Migration-Guide
_____________________________________________________________________

Loading 2 platforms...
module.js:338
    throw err;
    ^

Error: Cannot find module './search'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/pi/homebridge/node_modules/node-hue-api/hue-api/bridge-discovery.js:5:16)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

**Comment by snowdd1** [comment]
You must be root for npm install. 
Otherwise you will run into indeterminable trouble, as you already might be.

**Comment by adekka** [comment]
the thing is, i'm root :s

**Comment by cflurin** [comment]
@adekka I'd rename homebridge to e.g homebridge-backup and install homebridge again.

```sh
git clone https://github.com/nfarina/homebridge.git
and so on
```

@snowdd1 you don't have to be root!

**Comment by snowdd1** [comment]
That's what I said. 
You **must not** be root ( or sudo for that matter)

Npm blocks some features as a security measure.

**Comment by snowdd1** [comment]
I just saw I wrote "you must be root" instead of of "mustn't be root" 
Sorry for the confusion.

**Comment by cflurin** [comment]
@snowdd1 I know it's Friday :smile:

**Comment by snowdd1** [comment]
No, thank god it's Friday....

**Comment by nzhome** [comment]
if you don't need "node-hue-api": "^1.0.5",

remove it from your package.json and install again.  seems that you have dropped some required files in the hue folder somehow. or the build of hue-api is broken out there.

**Comment by adekka** [comment]
i'm getting lucky!


Loading 2 platforms...
[Phillips Hue] Initializing PhilipsHue platform...
[Phillips Hue] Fetching Philips Hue lights...
[Phillips Hue] Attempting to discover Philips Hue bridge with meethue.com...
[Sonos] Initializing Sonos platform...
[Sonos] Fetching Sonos devices.
Loading 1 accessories...
module.js:338
    throw err;
    ^

Error: Cannot find module './accessories/undefined.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at loadAccessories (/home/pi/homebridge/app.js:79:31)
    at startup (/home/pi/homebridge/app.js:60:29)
    at Object.<anonymous> (/home/pi/homebridge/app.js:223:1)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)

**Comment by adekka** [comment]
It works. Thanks for the help!

**Comment by cflurin** [comment]
@adekka Did you install homebridge again? What was the reason for fail before?

**Comment by adekka** [comment]
I installed homebridge again. But before I dit that, i had to to solve this error: Error: Cannot find module '../build/Release/dns_sd_bindings'

by doing this:

> npm install -g node-gyp
> cd node_modules/mdns
> node-gyp BUILDTYPE=Release rebuild

After that I had to install some NPM modules, but the thing above did the trick in combination with the new install of homebridge.

**Comment by cflurin** [comment]
Ok, this was probably an issue with your Installation. I didn't encountered such troubles.
