### ISSUE TITLE
No pairing between iOS and HomeBridge on Mac

### ISSUE THREAD

**Issue by Mini-Stef** [nfarina/homebridge#2140]
I know there are a few issues already, but none of them have a solution for me.

I just installed HomeBridge 0.4.46, on my Mac with mac OS Mojave 10.14.2.
No plugin.

```
config.json
{
    "bridge": {
        "name": "My Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-156"
    }
}

```
I also tried by replacing that Mac number with the Mac number of the Macintosh I'm running.
(by the way, what's the Mac number to put, the host machine one or this number above ?)

Paring attempts with an iPhone with iOS 12.1.2 and an iPad with iOS 12.1.1 all failed, using the QR code or using the 8 digit code.

I remember that the NPM installation of homebridge gave a bunch of "deprecated" warnings ("ToObject" is deprecated).

I am on the same WiFi network.

As the documentation is "light" and there is no error message in any way, I'm a bit stuck.

**Comment by NorthernMan54** [comment]
You likely need a plugin installed before it will work

**Comment by Mini-Stef** [comment]
Well, the HomeBridge page (https://github.com/nfarina/homebridge) says :
"Homebridge will complain if you don't have any Plugins installed, since it will essentially be useless, although you can still "pair" with it."
