### ISSUE TITLE
Wiped my Pi to start fresh and now get unregistered platform errors on all plugins

### ISSUE THREAD

**Issue by gadgetfreak98** [nfarina/homebridge#2142]
Hi.  I had my Raspberry Pi working previously with about 6 plugins, but one that I couldn't install successfully required an updated version of Node and the update ended up killing my setup.  So I decided to start anew with a fresh Raspbian installation, crossing my fingers that my carefully built config.json file would work fine once I was back up and running.

I got homebridge reinstalled fine with no plugins.  I then went ahead and reinstalled all my prior plugins and put my config.json file back into the .homebridge folder.  However, when I run homebridge, virtually all my plugins throw up:  

"throw new Error("The requested platform '" + name + "' was not registered by any plugin.");" errors.

I removed the first two plugins that threw up that error, but they were super simple ones before...  harmony-hub-platform and tplinksmarthome.  Then a nest one threw up the same error, so my issue seems to be more pervasive.

Is there any suggestion about why this might be happening with a fresh install?  I suppose I will whittle my way back to a single plug in and see if anything works at all.  Are there cache issues?  Thanks for any advice!

**Comment by gadgetfreak98** [comment]
Just to follow up.  I am down to Logi Circle Controls plugin, which loaded fine.  I think tried to reinstall TPlink, but again got the error noted above and Homebridge failed to load.

**Comment by aswathraja** [comment]
Please follow the template for reporting an issue.

Please give the steps to reproduce, config.json file contents

A few common trouble shooting tips :

1. Can you check your node_modules folder in both local and global environments? 

You should have the plugins that you are trying to add in your config.json file in the node_modules folder. 

Some plugins need to be installed in the global environment with the “-g” in your npm install command and obviously run as “sudo”.

2. Run your npm install command with “—unsafe-perm” flag to ignore any permission warning
3. Can you please clean your “node_modules” folder?


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
