### ISSUE TITLE
Request: Mipow Playbulb Plugin with instructions

### ISSUE THREAD

**Issue by dapperdan75** [nfarina/homebridge#2143]
I am looking for a plugin for the Mipow Playbulb smart candles. I found a reference to one via google but clicking the link tells me it no longer exists. 

I am incredibly new to Raspberry Pi and any sort of programming (though I’ve managed to successfully install homebridge and some other plugins!) so would appreciate any helpful instructions. 

My sincerest apologies if this post has broken any etiquette, has been posted in the wrong place, etc. I have carried out an extensive search and cannot find this elsewhere but if a solution does already exist, please point me in the right direction. 

Many thanks 😊

**Comment by iRayanKhan** [comment]
Try this out:
https://github.com/mecrip/homebridge-playbulb

**Comment by dapperdan75** [comment]
Thank you for the link.  Can you tell me how to install it on my rPi?  I am
a complete newbie and am struggling to work it out.  Somehow, I have
managed to install homebridge and it is running correctly.

Many thanks

**Comment by dapperdan75** [comment]
> Try this out:
> https://github.com/mecrip/homebridge-playbulb

Thank you for the link.  Can you tell me how to install it on my rPi?  I am a complete newbie and am struggling to work it out.  Somehow, I have managed to install homebridge and it is running correctly.

Many thanks
