### ISSUE TITLE
Hombridge restart on failure with systemd ... but only 3times

### ISSUE THREAD

**Issue by roe1974** [nfarina/homebridge#2146]
i start homebridge with systemd
it restarts on failure ... that works all.
today i had a problem with a plugin, and hombridge restarted 6times ..... that causes a problem in another plugin (Duty Cycle of Homematic)
How can i manage it, that Hombridge will only restart 3times ... and then stop ?

Richard

**Comment by iRayanKhan** [comment]
@roe1974 You would need to make a script that detects how many times systemd has crashed the HomeBridge instance. I use PM2 as if it is an error in HomeBridge it will stop trying to re-run. Whereas, is it crashes, it will auto restart.
