### ISSUE TITLE
cached accessories file is empty ... only [] ????

### ISSUE THREAD

**Issue by roe1974** [nfarina/homebridge#2149]
My cahed Accessories file is empty ?!?!?
There is only a "[]" inside....is this normal ?

Richard

**Comment by F4stFr3ddy** [comment]
Does it cause an issue for you?

**Comment by ebaauw** [comment]
`cachedAccessories` is used to persist accessories exposed by dynamic platform plugins across homebridge restarts.  If you only use accessory and/or static platform plugins, it’s empty.  These types of plugins re-create the accessories when homebridge starts.

**Comment by roe1974** [comment]
ok thx :)
