### ISSUE TITLE
No more commands after connection timeout on harmony

### ISSUE THREAD

**Issue by Hans-S** [nfarina/homebridge#215]
Hello, I started using homebridge after I discovered it through the Fibaro forum. Works with Fibaro nicely! I also added the logitech harmony platform, but have an issue with that that I can't figure out. It looks like the way this is setup is that a connection is made to the hub on platform initialisation, and that it is assumed that this connection will stay up forever. But in my case, it doesn't. There's a timeout somewhere, so after 60 seconds the connection is dropped. And no commands can be sent anymore. Any suggestion here? Login to the hub at every Homekit command maybe?

**Comment by justme-1968** [comment]
the shim has to send a keep alive ping every second so that the hub will not close the connection.

**Comment by Hans-S** [comment]
Do you mean like a getCurrentActivity request every second? Or a TCP ping?

**Comment by justme-1968** [comment]
there is a special xmpp ping message that is used. this should be implemented in the node harmony node lib. but i don't know anything about this lib.

i'm using this:
```
<iq type='get' id='ping-$id'><ping xmlns='urn:xmpp:ping'/></iq>
```
in my harmony module for fhem.

**Comment by Hans-S** [comment]
Ok, great. I have no clue how I've done it, but I kind of hardcoded a ping like you described. Will see what if it's still alive tomorrow. And still wonder what happens when my Mac loses it's network connection. Anyway, thanks a gain, close it up! ;)

**Comment by MackesG** [comment]
Hello, ich have the same issue. Please tell me how you implement the code. Is it still alive with ping? :-) thanks.

**Comment by KraigM** [comment]
That fork plus other enhancements have been merged in as part of #299.  See if that works for you guys

**Comment by Hans-S** [comment]
Have it up and running now, will let you know if it stays alive ;)

**Comment by Hans-S** [comment]
I can happily report that the 60 second timeout is solved in this version! Thanks!

One thing though, not sure if I should put that here. Sometimes, a timeout occurs on the connection. I guess that cannot be helped. My setup ran for days, and then came to a halt due to a tcp timeout. I changed the code in hub.js to this:

        var xmppClient = new Client({
                        jid: 'guest@x.com/gatorade'
                        , password: 'guest'
                        , host: hubhost
                        , port: hubport
                        , disallowTLS: true
                        , reconnect : true
                });

This way, after the tcp timeout, it reconnects and still works. Oh, it's about that last line, reconnect true.

If you would like this in a separate issue let me know. Anyway, this one's closed as far as I'm concerned. Great work, thanks again!
