### ISSUE TITLE
Cannot install HomeBridge on High Sierra

### ISSUE THREAD

**Issue by sparky672** [nfarina/homebridge#2150]
I found a similar topic with a resolution involving over-riding directory permissions, but that did not work for me.   **Yes, I am using `sudo` as you can see below.**

### Versions
- **Homebridge**:  trying to install latest version - failing
- **Node**:       10.15.1
- **OS**:         Mac OS 10.13.6 (High Sierra)

### Steps to Reproduce

**Terminal Command**:  `sudo npm install -g homebridge`

**Output**:

```
/usr/local/bin/homebridge -> /usr/local/lib/node_modules/homebridge/bin/homebridge

> curve25519-n@1.4.0 install /usr/local/lib/node_modules/homebridge/node_modules/curve25519-n
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/homebridge/node_modules/curve25519-n/build'
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/homebridge/node_modules/curve25519-n
gyp ERR! node -v v10.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! curve25519-n@1.4.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the curve25519-n@1.4.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

So then after researching this problem, I tried the permissions over-ride...

**Terminal Command**:  `sudo npm install -g --unsafe-perm homebridge`

**Output**:

```
/usr/local/bin/homebridge -> /usr/local/lib/node_modules/homebridge/bin/homebridge

> curve25519-n@1.4.0 install /usr/local/lib/node_modules/homebridge/node_modules/curve25519-n
> node-gyp rebuild

  CXX(target) Release/obj.target/curve/node_curve.o
clang: error: no such file or directory: 'HD/Users/username/.node-gyp/10.15.1/include/node'
clang: error: no such file or directory: 'HD/Users/username/.node-gyp/10.15.1/src'
clang: error: no such file or directory: 'HD/Users/username/.node-gyp/10.15.1/deps/openssl/config'
clang: error: no such file or directory: 'HD/Users/username/.node-gyp/10.15.1/deps/openssl/openssl/include'
clang: error: no such file or directory: 'HD/Users/username/.node-gyp/10.15.1/deps/uv/include'
clang: error: no such file or directory: 'HD/Users/username/.node-gyp/10.15.1/deps/zlib'
clang: error: no such file or directory: 'HD/Users/username/.node-gyp/10.15.1/deps/v8/include'
make: *** [Release/obj.target/curve/node_curve.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/homebridge/node_modules/curve25519-n
gyp ERR! node -v v10.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! curve25519-n@1.4.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the curve25519-n@1.4.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Note that the path in the "no such file or directory" error message is nonsensical.  My drive is called "Macintosh HD" and yet the path in the error message just starts with "HD".

Would love to know the secret to getting this installed properly.  Thank you.

**Comment by iRayanKhan** [comment]
Try ```sudo npm I -g homebridge --unsafe-perm```

**Comment by sparky672** [comment]
> Try `sudo npm I -g homebridge --unsafe-perm`

Thank you for your response, no errors this time, however nothing was installed either...

**Output**:

```
Usage: npm <command>

where <command> is one of:
    access, adduser, audit, bin, bugs, c, cache, ci, cit,
    completion, config, create, ddp, dedupe, deprecate,
    dist-tag, docs, doctor, edit, explore, get, help,
    help-search, hook, i, init, install, install-test, it, link,
    list, ln, login, logout, ls, outdated, owner, pack, ping,
    prefix, profile, prune, publish, rb, rebuild, repo, restart,
    root, run, run-script, s, se, search, set, shrinkwrap, star,
    stars, start, stop, t, team, test, token, tst, un,
    uninstall, unpublish, unstar, up, update, v, version, view,
    whoami

npm <command> -h  quick help on <command>
npm -l            display full usage info
npm help <term>   search for help on <term>
npm help npm      involved overview

Specify configs in the ini-formatted file:
    /Volumes/Macintosh HD/Users/username/.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@6.4.1 /usr/local/lib/node_modules/npm
```

**Comment by iRayanKhan** [comment]
Did you specify a path?
``` cd desktop ```
or wherever you want it to install.

**Comment by sparky672** [comment]
> Did you specify a path?
> `cd desktop`
> or wherever you want it to install.

I just want it installed where it's supposed to be installed.  

Following the directions, it says nothing about specifying a path.  Can you help me figure this out?  Thank you.

**Comment by ebaauw** [comment]
`I` is not an `npm` command.  Use `sudo npm i -g homebridge --unsafe-perm`.

**Comment by sparky672** [comment]
> sudo npm i -g homebridge --unsafe-perm

Thank you for the response.  However, still not working...

**OUTPUT**:

Mac-Pro:~ username $ sudo npm i -g homebridge --unsafe-perm
Password:
/usr/local/bin/homebridge -> /usr/local/lib/node_modules/homebridge/bin/homebridge

> curve25519-n@1.4.0 install /usr/local/lib/node_modules/homebridge/node_modules/curve25519-n
> node-gyp rebuild

  CXX(target) Release/obj.target/curve/node_curve.o
clang: error: no such file or directory: 'HD/Users/username/.node-gyp/10.15.1/include/node'
clang: error: no such file or directory: 'HD/Users/username/.node-gyp/10.15.1/src'
clang: error: no such file or directory: 'HD/Users/username/.node-gyp/10.15.1/deps/openssl/config'
clang: error: no such file or directory: 'HD/Users/username/.node-gyp/10.15.1/deps/openssl/openssl/include'
clang: error: no such file or directory: 'HD/Users/username/.node-gyp/10.15.1/deps/uv/include'
clang: error: no such file or directory: 'HD/Users/username/.node-gyp/10.15.1/deps/zlib'
clang: error: no such file or directory: 'HD/Users/username/.node-gyp/10.15.1/deps/v8/include'
make: *** [Release/obj.target/curve/node_curve.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/homebridge/node_modules/curve25519-n
gyp ERR! node -v v10.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! curve25519-n@1.4.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the curve25519-n@1.4.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by sparky672** [comment]
Please anyone?

**Comment by sparky672** [comment]
Updated NodeJS to v11.10.0 and same issue as above.
