### ISSUE TITLE
There was a problem reading your config.json file.

### ISSUE THREAD

**Issue by selmholt** [nfarina/homebridge#2151]
Hi. 

I have setup Homebridge, but i am getting the following error in the log:

0|homebrid |     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
0|homebrid | [2/10/2019, 8:41:15 AM] There was a problem reading your config.json file.
0|homebrid | [2/10/2019, 8:41:15 AM] Please try pasting your config.json file here to validate it: http://jsonlint.com
0|homebrid | [2/10/2019, 8:41:15 AM]
0|homebrid | SyntaxError: Unexpected token < in JSON at position 428
0|homebrid |     at JSON.parse (<anonymous>)
0|homebrid |     at Server._loadConfig (/usr/lib/node_modules/homebridge/lib/server.js:208:19)
0|homebrid |     at new Server (/usr/lib/node_modules/homebridge/lib/server.js:56:38)
0|homebrid |     at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:30:16)
0|homebrid |     at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
0|homebrid |     at Module._compile (internal/modules/cjs/loader.js:689:30)
0|homebrid |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
0|homebrid |     at Module.load (internal/modules/cjs/loader.js:599:32)
0|homebrid |     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
0|homebrid |     at Function.Module._load (internal/modules/cjs/loader.js:530:3)

My Config.json looks like this and does validate on https://jsonlint.com/:

{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:21:3E:E4:DE:33",
        "port": 51826,
        "pin": "031-45-154"
    },
    "description": "Configuration file for (e)xtended Domoticz platform.",
    "platforms": [
        {
            "platform": "eDomoticz",
            "name": "eDomoticz",
            "server": "192.168.1.5",
            "port": "8080",
            "ssl": 0,
            "roomid": 2,
            "mqtt": 0
        }
    ],
    "accessories": []
}

**Comment by iRayanKhan** [comment]
Are you sure it's saved as ```config.json``` and there isn't a missing character in the file name. Also make sure it is in the same file as your ```.homebridge``` folder.

**Comment by selmholt** [comment]
> Are you sure it's saved as `config.json` and there isn't a missing character in the file name. Also make sure it is in the same file as your `.homebridge` folder.

Hi. Changes the IP in the config from localhost to the static IP, that looks like it solved it. 
That for answering.
