### ISSUE TITLE
Warning: Attempt to call disposable callback twice.

### ISSUE THREAD

**Issue by roe1974** [nfarina/homebridge#2155]
i had today this entry in my log without connex to a plugin... what does this mean ?

`Feb 13 07:30:23 homebridge-raspi homebridge[446]: Warning: Attempt to call disposable callback twice.
Feb 13 07:30:23 homebridge-raspi homebridge[446]: Warning: Attempt to call disposable callback twice.
`

**Comment by iRayanKhan** [comment]
Please paste you config and a link to the plugin you are trying to use.

**Comment by roe1974** [comment]
i use the same plugins since about 1 year ... nothing changed or added ....
today i got this message for the first time ... i can not identify which plugin caused this log entry :(

**Comment by NorthernMan54** [comment]
Just looking at your log snippet I would have assumed homebridge-raspi

If you look at the source code for the plugin you may be able to confirm

**Comment by roe1974** [comment]
"homebridge-raspi" is the name of the raspi itself ;-)
