### ISSUE TITLE
Cant start Homebridge with insecure mode on pm2

### ISSUE THREAD

**Issue by gaojie429** [nfarina/homebridge#2157]
When I run `pm2 start homebridge -I`
I get ``error: unknown option '-I'``
Any solution ?

**Comment by NorthernMan54** [comment]
@gaojie429 The place to ask this question would be the pm2 support forums or google.  But if you do find the answer, could you update the wiki page that mentions pm2. [Wiki Link](https://github.com/nfarina/homebridge/wiki/Easy-Install-Raspberry-PI-(With-Start-with-boot))

And as your using my homebridge-alexa, it you let me know I will update my README as well

**Comment by gaojie429** [comment]
Of course!
When I found the answer, I will update the Wiki and let you know that.
Sorry for asking to wrong place.

**Comment by gitgayhub** [comment]
you should use -- to pass arguments to apps
so your command will be like this
`pm2 start homebridge -- -I`

**Comment by micro23xd** [comment]
> you should use -- to pass arguments to apps
> so your command will be like this
> `pm2 start homebridge -- -I`

This works for me! 
Make sure to delete homebridge from pm2 before you run this if you had homebridge in the pm2 list already. `pm2 show homebridge` should show `-I` as script args if executed correctly.
