### ISSUE TITLE
The plugin homebridge-yeelight works good, but siri reply error.

### ISSUE THREAD

**Issue by doxingyun** [nfarina/homebridge#2167]
I can use "home" app on the iOS to control my yeelight device, but every time when I say "hey siri, turn on the light" the lights are really light on, and then siri always say back "there is something wrong, try it later"

**Comment by doxingyun** [comment]
Always read back wrong.

**Comment by honghaoz** [comment]
I'm having the same problem.

**Comment by doxingyun** [comment]
Anyeone have the same problem?

**Comment by honghaoz** [comment]
@doxingyun One Interesting thing is not all of my lights are having this issue. I'm using `TplinkSmarthome`.
