### ISSUE TITLE
Homebridge won't start

### ISSUE THREAD

**Issue by samsonrosen** [nfarina/homebridge#2170]
Hi! 

Last night I rebooted my Pi and now it won't start. It's been working fine before this (freshly built yesterday)

```
Mar 04 07:44:47 raspberrypi systemd[1]: Started Node.js HomeKit Server.
Mar 04 07:44:48 raspberrypi homebridge[656]: module.js:550
Mar 04 07:44:48 raspberrypi homebridge[656]:     throw err;
Mar 04 07:44:48 raspberrypi homebridge[656]:     ^
Mar 04 07:44:48 raspberrypi homebridge[656]: Error: Cannot find module 'debug'
Mar 04 07:44:48 raspberrypi homebridge[656]:     at Function.Module._resolveFilename (module.js:548:15)
Mar 04 07:44:48 raspberrypi homebridge[656]:     at Function.Module._load (module.js:475:25)
Mar 04 07:44:48 raspberrypi homebridge[656]:     at Module.require (module.js:597:17)
Mar 04 07:44:48 raspberrypi homebridge[656]:     at require (internal/module.js:11:18)
Mar 04 07:44:48 raspberrypi homebridge[656]:     at Object.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.
Mar 04 07:44:48 raspberrypi homebridge[656]:     at Module._compile (module.js:653:30)
Mar 04 07:44:48 raspberrypi homebridge[656]:     at Object.Module._extensions..js (module.js:664:10)
Mar 04 07:44:48 raspberrypi homebridge[656]:     at Module.load (module.js:566:32)
Mar 04 07:44:48 raspberrypi homebridge[656]:     at tryModuleLoad (module.js:506:12)
Mar 04 07:44:48 raspberrypi homebridge[656]:     at Function.Module._load (module.js:498:3)
Mar 04 07:44:48 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
Mar 04 07:44:48 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
Mar 04 07:44:48 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
Mar 04 07:44:58 raspberrypi systemd[1]: homebridge.service: Service hold-off time over, scheduling restart.
Mar 04 07:44:58 raspberrypi systemd[1]: Stopped Node.js HomeKit Server.
Mar 04 07:44:58 raspberrypi systemd[1]: Started Node.js HomeKit Server.
Mar 04 07:44:58 raspberrypi homebridge[663]: module.js:550
Mar 04 07:44:58 raspberrypi homebridge[663]:     throw err;
Mar 04 07:44:58 raspberrypi homebridge[663]:     ^
Mar 04 07:44:58 raspberrypi homebridge[663]: Error: Cannot find module 'debug'
Mar 04 07:44:58 raspberrypi homebridge[663]:     at Function.Module._resolveFilename (module.js:548:15)
Mar 04 07:44:58 raspberrypi homebridge[663]:     at Function.Module._load (module.js:475:25)
Mar 04 07:44:58 raspberrypi homebridge[663]:     at Module.require (module.js:597:17)
Mar 04 07:44:58 raspberrypi homebridge[663]:     at require (internal/module.js:11:18)
Mar 04 07:44:58 raspberrypi homebridge[663]:     at Object.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.
Mar 04 07:44:58 raspberrypi homebridge[663]:     at Module._compile (module.js:653:30)
Mar 04 07:44:58 raspberrypi homebridge[663]:     at Object.Module._extensions..js (module.js:664:10)
Mar 04 07:44:58 raspberrypi homebridge[663]:     at Module.load (module.js:566:32)
Mar 04 07:44:58 raspberrypi homebridge[663]:     at tryModuleLoad (module.js:506:12)
Mar 04 07:44:58 raspberrypi homebridge[663]:     at Function.Module._load (module.js:498:3)
Mar 04 07:44:58 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
Mar 04 07:44:58 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
Mar 04 07:44:58 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
Mar 04 07:45:08 raspberrypi systemd[1]: homebridge.service: Service hold-off time over, scheduling restart.
Mar 04 07:45:08 raspberrypi systemd[1]: Stopped Node.js HomeKit Server.
Mar 04 07:45:09 raspberrypi systemd[1]: Started Node.js HomeKit Server.
Mar 04 07:45:09 raspberrypi homebridge[670]: module.js:550
Mar 04 07:45:09 raspberrypi homebridge[670]:     throw err;
Mar 04 07:45:09 raspberrypi homebridge[670]:     ^
Mar 04 07:45:09 raspberrypi homebridge[670]: Error: Cannot find module 'debug'
Mar 04 07:45:09 raspberrypi homebridge[670]:     at Function.Module._resolveFilename (module.js:548:15)
Mar 04 07:45:09 raspberrypi homebridge[670]:     at Function.Module._load (module.js:475:25)
Mar 04 07:45:09 raspberrypi homebridge[670]:     at Module.require (module.js:597:17)
Mar 04 07:45:09 raspberrypi homebridge[670]:     at require (internal/module.js:11:18)
Mar 04 07:45:09 raspberrypi homebridge[670]:     at Object.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.
Mar 04 07:45:09 raspberrypi homebridge[670]:     at Module._compile (module.js:653:30)
Mar 04 07:45:09 raspberrypi homebridge[670]:     at Object.Module._extensions..js (module.js:664:10)
Mar 04 07:45:09 raspberrypi homebridge[670]:     at Module.load (module.js:566:32)
Mar 04 07:45:09 raspberrypi homebridge[670]:     at tryModuleLoad (module.js:506:12)
Mar 04 07:45:09 raspberrypi homebridge[670]:     at Function.Module._load (module.js:498:3)
Mar 04 07:45:09 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
Mar 04 07:45:09 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
Mar 04 07:45:09 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
Mar 04 07:45:16 raspberrypi sudo[643]: pam_unix(sudo:session): session closed for user root
Mar 04 07:45:18 raspberrypi sudo[680]:       pi : TTY=pts/0 ; PWD=/home/pi ; USER=root ; COMMAND=/usr/bin/sudo
Mar 04 07:45:18 raspberrypi sudo[680]: pam_unix(sudo:session): session opened for user root by pi(uid=0)
Mar 04 07:45:18 raspberrypi sudo[680]: pam_unix(sudo:session): session closed for user root
Mar 04 07:45:19 raspberrypi systemd[1]: homebridge.service: Service hold-off time over, scheduling restart.
Mar 04 07:45:19 raspberrypi systemd[1]: Stopped Node.js HomeKit Server.
Mar 04 07:45:19 raspberrypi systemd[1]: Started Node.js HomeKit Server.
Mar 04 07:45:20 raspberrypi homebridge[688]: module.js:550
Mar 04 07:45:20 raspberrypi homebridge[688]:     throw err;
Mar 04 07:45:20 raspberrypi homebridge[688]:     ^
Mar 04 07:45:20 raspberrypi homebridge[688]: Error: Cannot find module 'debug'
Mar 04 07:45:20 raspberrypi homebridge[688]:     at Function.Module._resolveFilename (module.js:548:15)
Mar 04 07:45:20 raspberrypi homebridge[688]:     at Function.Module._load (module.js:475:25)
Mar 04 07:45:20 raspberrypi homebridge[688]:     at Module.require (module.js:597:17)
Mar 04 07:45:20 raspberrypi homebridge[688]:     at require (internal/module.js:11:18)
Mar 04 07:45:20 raspberrypi homebridge[688]:     at Object.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.
Mar 04 07:45:20 raspberrypi homebridge[688]:     at Module._compile (module.js:653:30)
Mar 04 07:45:20 raspberrypi homebridge[688]:     at Object.Module._extensions..js (module.js:664:10)
Mar 04 07:45:20 raspberrypi homebridge[688]:     at Module.load (module.js:566:32)
Mar 04 07:45:20 raspberrypi homebridge[688]:     at tryModuleLoad (module.js:506:12)
Mar 04 07:45:20 raspberrypi homebridge[688]:     at Function.Module._load (module.js:498:3)
Mar 04 07:45:20 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
Mar 04 07:45:20 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
Mar 04 07:45:20 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
Mar 04 07:45:24 raspberrypi sudo[695]:       pi : TTY=pts/0 ; PWD=/home/pi ; USER=root ; COMMAND=/bin/journalctl
Mar 04 07:45:24 raspberrypi sudo[695]: pam_unix(sudo:session): session opened for user root by pi(uid=0)
```

**Comment by NorthernMan54** [comment]
Looking at the log, the module debug is missing try installing homebridge again

**Comment by samsonrosen** [comment]
> Looking at the log, the module debug is missing try installing homebridge again
> […](#)
> Sent from my iPad
> On Mar 4, 2019, at 3:47 AM, samsonrosen ***@***.***> wrote: Hi! Last night I rebooted my Pi and now it won't start. It's been working fine before this (freshly built yesterday) Mar 04 07:44:47 raspberrypi systemd[1]: Started Node.js HomeKit Server. Mar 04 07:44:48 raspberrypi homebridge[656]: module.js:550 Mar 04 07:44:48 raspberrypi homebridge[656]: throw err; Mar 04 07:44:48 raspberrypi homebridge[656]: ^ Mar 04 07:44:48 raspberrypi homebridge[656]: Error: Cannot find module 'debug' Mar 04 07:44:48 raspberrypi homebridge[656]: at Function.Module._resolveFilename (module.js:548:15) Mar 04 07:44:48 raspberrypi homebridge[656]: at Function.Module._load (module.js:475:25) Mar 04 07:44:48 raspberrypi homebridge[656]: at Module.require (module.js:597:17) Mar 04 07:44:48 raspberrypi homebridge[656]: at require (internal/module.js:11:18) Mar 04 07:44:48 raspberrypi homebridge[656]: at Object.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory. Mar 04 07:44:48 raspberrypi homebridge[656]: at Module._compile (module.js:653:30) Mar 04 07:44:48 raspberrypi homebridge[656]: at Object.Module._extensions..js (module.js:664:10) Mar 04 07:44:48 raspberrypi homebridge[656]: at Module.load (module.js:566:32) Mar 04 07:44:48 raspberrypi homebridge[656]: at tryModuleLoad (module.js:506:12) Mar 04 07:44:48 raspberrypi homebridge[656]: at Function.Module._load (module.js:498:3) Mar 04 07:44:48 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE Mar 04 07:44:48 raspberrypi systemd[1]: homebridge.service: Unit entered failed state. Mar 04 07:44:48 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'. Mar 04 07:44:58 raspberrypi systemd[1]: homebridge.service: Service hold-off time over, scheduling restart. Mar 04 07:44:58 raspberrypi systemd[1]: Stopped Node.js HomeKit Server. Mar 04 07:44:58 raspberrypi systemd[1]: Started Node.js HomeKit Server. Mar 04 07:44:58 raspberrypi homebridge[663]: module.js:550 Mar 04 07:44:58 raspberrypi homebridge[663]: throw err; Mar 04 07:44:58 raspberrypi homebridge[663]: ^ Mar 04 07:44:58 raspberrypi homebridge[663]: Error: Cannot find module 'debug' Mar 04 07:44:58 raspberrypi homebridge[663]: at Function.Module._resolveFilename (module.js:548:15) Mar 04 07:44:58 raspberrypi homebridge[663]: at Function.Module._load (module.js:475:25) Mar 04 07:44:58 raspberrypi homebridge[663]: at Module.require (module.js:597:17) Mar 04 07:44:58 raspberrypi homebridge[663]: at require (internal/module.js:11:18) Mar 04 07:44:58 raspberrypi homebridge[663]: at Object.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory. Mar 04 07:44:58 raspberrypi homebridge[663]: at Module._compile (module.js:653:30) Mar 04 07:44:58 raspberrypi homebridge[663]: at Object.Module._extensions..js (module.js:664:10) Mar 04 07:44:58 raspberrypi homebridge[663]: at Module.load (module.js:566:32) Mar 04 07:44:58 raspberrypi homebridge[663]: at tryModuleLoad (module.js:506:12) Mar 04 07:44:58 raspberrypi homebridge[663]: at Function.Module._load (module.js:498:3) Mar 04 07:44:58 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE Mar 04 07:44:58 raspberrypi systemd[1]: homebridge.service: Unit entered failed state. Mar 04 07:44:58 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'. Mar 04 07:45:08 raspberrypi systemd[1]: homebridge.service: Service hold-off time over, scheduling restart. Mar 04 07:45:08 raspberrypi systemd[1]: Stopped Node.js HomeKit Server. Mar 04 07:45:09 raspberrypi systemd[1]: Started Node.js HomeKit Server. Mar 04 07:45:09 raspberrypi homebridge[670]: module.js:550 Mar 04 07:45:09 raspberrypi homebridge[670]: throw err; Mar 04 07:45:09 raspberrypi homebridge[670]: ^ Mar 04 07:45:09 raspberrypi homebridge[670]: Error: Cannot find module 'debug' Mar 04 07:45:09 raspberrypi homebridge[670]: at Function.Module._resolveFilename (module.js:548:15) Mar 04 07:45:09 raspberrypi homebridge[670]: at Function.Module._load (module.js:475:25) Mar 04 07:45:09 raspberrypi homebridge[670]: at Module.require (module.js:597:17) Mar 04 07:45:09 raspberrypi homebridge[670]: at require (internal/module.js:11:18) Mar 04 07:45:09 raspberrypi homebridge[670]: at Object.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory. Mar 04 07:45:09 raspberrypi homebridge[670]: at Module._compile (module.js:653:30) Mar 04 07:45:09 raspberrypi homebridge[670]: at Object.Module._extensions..js (module.js:664:10) Mar 04 07:45:09 raspberrypi homebridge[670]: at Module.load (module.js:566:32) Mar 04 07:45:09 raspberrypi homebridge[670]: at tryModuleLoad (module.js:506:12) Mar 04 07:45:09 raspberrypi homebridge[670]: at Function.Module._load (module.js:498:3) Mar 04 07:45:09 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE Mar 04 07:45:09 raspberrypi systemd[1]: homebridge.service: Unit entered failed state. Mar 04 07:45:09 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'. Mar 04 07:45:16 raspberrypi sudo[643]: pam_unix(sudo:session): session closed for user root Mar 04 07:45:18 raspberrypi sudo[680]: pi : TTY=pts/0 ; PWD=/home/pi ; USER=root ; COMMAND=/usr/bin/sudo Mar 04 07:45:18 raspberrypi sudo[680]: pam_unix(sudo:session): session opened for user root by pi(uid=0) Mar 04 07:45:18 raspberrypi sudo[680]: pam_unix(sudo:session): session closed for user root Mar 04 07:45:19 raspberrypi systemd[1]: homebridge.service: Service hold-off time over, scheduling restart. Mar 04 07:45:19 raspberrypi systemd[1]: Stopped Node.js HomeKit Server. Mar 04 07:45:19 raspberrypi systemd[1]: Started Node.js HomeKit Server. Mar 04 07:45:20 raspberrypi homebridge[688]: module.js:550 Mar 04 07:45:20 raspberrypi homebridge[688]: throw err; Mar 04 07:45:20 raspberrypi homebridge[688]: ^ Mar 04 07:45:20 raspberrypi homebridge[688]: Error: Cannot find module 'debug' Mar 04 07:45:20 raspberrypi homebridge[688]: at Function.Module._resolveFilename (module.js:548:15) Mar 04 07:45:20 raspberrypi homebridge[688]: at Function.Module._load (module.js:475:25) Mar 04 07:45:20 raspberrypi homebridge[688]: at Module.require (module.js:597:17) Mar 04 07:45:20 raspberrypi homebridge[688]: at require (internal/module.js:11:18) Mar 04 07:45:20 raspberrypi homebridge[688]: at Object.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory. Mar 04 07:45:20 raspberrypi homebridge[688]: at Module._compile (module.js:653:30) Mar 04 07:45:20 raspberrypi homebridge[688]: at Object.Module._extensions..js (module.js:664:10) Mar 04 07:45:20 raspberrypi homebridge[688]: at Module.load (module.js:566:32) Mar 04 07:45:20 raspberrypi homebridge[688]: at tryModuleLoad (module.js:506:12) Mar 04 07:45:20 raspberrypi homebridge[688]: at Function.Module._load (module.js:498:3) Mar 04 07:45:20 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE Mar 04 07:45:20 raspberrypi systemd[1]: homebridge.service: Unit entered failed state. Mar 04 07:45:20 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'. Mar 04 07:45:24 raspberrypi sudo[695]: pi : TTY=pts/0 ; PWD=/home/pi ; USER=root ; COMMAND=/bin/journalctl Mar 04 07:45:24 raspberrypi sudo[695]: pam_unix(sudo:session): session opened for user root by pi(uid=0) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

Thank you! I will try this when I get home later. Is this most level of detail I can get with logging? I've recently moved over from using Mac OS to a Pi using SystemD and am having trouble wrapping my head around where I can get this information.

I use your Alexa plugin which is fantastic.

**Comment by NorthernMan54** [comment]
The other log I use is DEBUG, which is good for seeing what is happening between HomeKit and homebridge.

You can get a DEBUG log by starting homebridge like this

DEBUG=* homebridge -I

The -I is for my Alexa plugin

**Comment by samsonrosen** [comment]
Brilliant I will try this later on with DEBUG to see if it reveals more as well. I think I spotted you can add this to the homebridge.service. It's currently got homebridge -I -U so I will add Debug.

Thanks again. Spent way too many hours getting this right! The pi is headless so when it goes horribly wrong I've been using an image I created in terminal on Mac OS with a card reader. I freshly restored it yesterday so I don't know why it's not working but I will find out tonight.

**Comment by NorthernMan54** [comment]
If you headless have you enabled ssh, so you can ssh in from a macOS terminal

**Comment by samsonrosen** [comment]
Yeah I'm using ssh! Super weird.. so I ran the install command and got this:

```
pi@raspberrypi:~ $ sudo npm install -g --unsafe-perm homebridge
module.js:550
    throw err;
    ^

Error: Cannot find module './internal/streams/stream'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_readable.js:50:14)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
```

I tried this command but to no avail. Do I need to do a fresh install again?

```
pi@raspberrypi:~ $ sudo rm -rf node_modules
pi@raspberrypi:~ $ sudo npm install
module.js:550
    throw err;
    ^

Error: Cannot find module './internal/streams/stream'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_readable.js:50:14)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)

```

**Comment by NorthernMan54** [comment]
If you have the latest nodejs and npm, you should just need to re-install homebridge

**Comment by samsonrosen** [comment]
I managed to successfully reinstall using the --reinstall flag. I kind of restarted the installation process from the install guide. I'm now getting slightly different errors with debug enabled:

```
Mar 06 08:14:06 raspberrypi systemd[1]: homebridge.service: Service hold-off time over, scheduling restart.
Mar 06 08:14:06 raspberrypi systemd[1]: Stopped Node.js HomeKit Server.
Mar 06 08:14:06 raspberrypi systemd[1]: Started Node.js HomeKit Server.
Mar 06 08:14:07 raspberrypi homebridge[22107]: /usr/lib/node_modules/homebridge/node_modules/ansi-styles/index.js:1
Mar 06 08:14:07 raspberrypi homebridge[22107]: (function (exports, require, module, __filename, __dirname) {
Mar 06 08:14:07 raspberrypi homebridge[22107]:                                                               
Mar 06 08:14:07 raspberrypi homebridge[22107]: SyntaxError: Invalid or unexpected token
Mar 06 08:14:07 raspberrypi homebridge[22107]:     at createScript (vm.js:80:10)
Mar 06 08:14:07 raspberrypi homebridge[22107]:     at Object.runInThisContext (vm.js:139:10)
Mar 06 08:14:07 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
Mar 06 08:14:07 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
Mar 06 08:14:07 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
Mar 06 08:14:17 raspberrypi systemd[1]: homebridge.service: Service hold-off time over, scheduling restart.
```

**Comment by NorthernMan54** [comment]
This is very wacky looking, what version on npm and nodejs do you have? Ie

npm -v
node -v

**Comment by samsonrosen** [comment]
```
pi@raspberrypi:~ $ node -v
v8.15.1
pi@raspberrypi:~ $ npm -v
6.4.1
pi@raspberrypi:~ $ 
```

**Comment by samsonrosen** [comment]
I think it might have been down to a rogue config file being weird tbh. Sorry to have dragged you into it! Thanks again for all your help. I think it's all back up now!!
