### ISSUE TITLE
Disable Plugin Option

### ISSUE THREAD

**Issue by 400HPMustang** [nfarina/homebridge#2171]
Expected behavior: The ability to disable an installed plugin in Homebridge without having to uninstall it and remove its config entry and to reinstall the plugin to re-enable it. 

Current behavior: All plugins installed attempt to load on launch, with config entries where required. Removing a config entry for an installed plugin will result in homebridge not running. Removing a plugin while leaving the config entry also results in homebridge not running.

**Comment by phenomeus** [comment]
like this? https://github.com/nfarina/homebridge/issues/2120

**Comment by 400HPMustang** [comment]
Nope. Not like that at all. I am just asking for the ability to switch plugins off and on without removing them and reinstalling them.

**Comment by ebaauw** [comment]
> The ability to disable an installed plugin in Homebridge without having to uninstall it 

It's already there: use the `"plugins"` key in config.json to whitelist which plugins should be loaded.  See #1880.
