### ISSUE TITLE
HomeKit (Siri) doesn't seem to see anything anymore

### ISSUE THREAD

**Issue by maddox** [nfarina/homebridge#218]
I've developed the WEIRDEST problem. Suddenly out of no where, Siri can't identify ANY of my accessories.

I didn't really change anything, the Home HomeKit app can add and control all my devices just fine, but Siri refuses to understand anything. 

If I ask for a device by name to be turned on/off, it doesn't understand. If I ask for a whole room to be turned off, it doesn't understand. If I ask for a whole room's lights to be turned off "hey siri, turn off the family room lights" it gets confused and asks if I want ALL of my lights turned off.

So it's like it sees my devices, but can't figure out how to control them appropriately.

I've done everything down to resetting all my HomeKit settings. Has anyone else seen anything like this before?

**Comment by KhaosT** [comment]
@maddox What's the Siri's response when you ask "Turn on the lights" and what's the iOS release you're using?

**Comment by maddox** [comment]
> what's the iOS release you're using
I'm on 9.0 (Haven't updated my 6s yet :grin:). 

> What's the Siri's response when you ask "Turn on the lights"

I already wiped my accessories.

Good news though. After doing another wipe, I couldn't add a Home anymore. It kept telling me "cloud sync is in progress". Even a reboot didn't fix this. The only thing that fixed it was:

* Turn off keychain syncing
* reset HomeKit
* Turn keychain syncing back on

After that, I was able to add a Home again, and my devices. And siri is responding correctly now.

So...¯\_(ツ)_/¯

**Comment by KhaosT** [comment]
That's strange... I guess there are something wrong with HomeKit which cause Siri failed to sync all the home information with its server.

**Comment by maddox** [comment]
It could turn EVERYTHING on/off when I asked though. So it could do SOMETHING.

**Comment by snowdd1** [comment]
>it gets confused and asks if I want ALL of my lights turned off.

Does it really asks that? With me, it always turns all lights on/off if it doesn't understand the room name. Which has a very low WAF I can tell.

**Comment by KhaosT** [comment]
@snowdd1 I believe that's a new Siri feature in iOS 9, when Siri is not confident enough about your command, it will ask like this. 
![img_2621](https://cloud.githubusercontent.com/assets/1725664/10214718/a35ea22e-67cf-11e5-9cee-9898bbd3183a.jpg)

**Comment by snowdd1** [comment]
Never had that. Always got a "your lamps are turned off" and sudden darkness in the house :(

**Comment by KhaosT** [comment]
@snowdd1 yeah, Siri should never ever try to turn off everything without asking...

**Comment by snowdd1** [comment]
Which ios9 do you have? 01 or 02?

**Comment by nzhome** [comment]
even in ios 8.1.4  I get "would you like to turn all the lights off?'   it only does it when I screw up what I say, otherwise it just shuts them all off instantly.  its a Siri cloud thing, not an ios9 thing.

**Comment by nzhome** [comment]
but it is quite a new Siri thing this month, because I didn't get it before.

**Comment by snowdd1** [comment]
This month? October?

**Comment by nzhome** [comment]
September. (3 days ago)
