### ISSUE TITLE
Add this issue to Common Issues / My iOS App Can't Find Homebridge

### ISSUE THREAD

**Issue by hepcat72** [nfarina/homebridge#2180]
### Pre Steps

I was resuming the setup of homebridge on my raspberry pi and was unable to get my phone to detect homebridge running (without error) on my pi.  I had previously added it as an accessory.  I decided to reset the accessory by removing it from the home app and re-adding it.  I scanned the QR, but it kept timing out, saying it couldn't be detected.  I tried both suggested solutions for "My iOS App Can't Find Homebridge" in the README.  Neither worked.  I deleted the persist directory and stopped and started homebridge.  I also changed the username in the json and stopped/started. I figured out a solution (albeit a temporary one).  It's related to other bonjour issues I've been having described [here](url
https://alwayswithyouwhatcannotbedone.wordpress.com/2019/03/10/temporary-fix-for-an-iphone-that-cannot-access-local-addresses/).  All you have to do is turn on & off airplane mode to empty your DNS cache. Then when you try to add the homebridge accessory, it gets detected right away!

### Expected Behavior

Add a note about the airplane mode trick described above to resolve a "My iOS App Can't Find Homebridge" issue.

### Current Behavior

There's currently no listed resolution in the README when a user encounters this issue.

### Steps to Reproduce (for bugs)

If your iOS device has trouble resolving .local domain names, detecting airport express-connected speakers, or other bonjour-advertised services, I have a hunch that you will likely also encounter this issue with adding homebridge to the home app. I don't know how to reproduce it other than that.

### Versions

- **Homebridge**: 0.4.46
- **Node**:       v11.12.0
- **OS**:         iOS 11.4.1

### Homebridge Log / Command Output

no errors

**Comment by iRayanKhan** [comment]
Make a PR of this.

**Comment by hepcat72** [comment]
Done.

https://github.com/nfarina/homebridge/pull/2186

**Comment by hepcat72** [comment]
Merged
