### ISSUE TITLE
Second pi for sensors

### ISSUE THREAD

**Issue by mikekenyon99** [nfarina/homebridge#2183]
Hi,

Is it possible to have Homebridge running on a Pi in my study with other devices attached then have a pi in my garage with sensors attached? The garage pi would then send data to the Homebridge/Pi?

Mike

**Comment by NorthernMan54** [comment]
Yes you can,  HomeKit supports having multiple homebridge’s.

Another option is use an esp8266 to send sensor data to your raspberrypi.  In my setup I built these

https://github.com/NorthernMan54/homebridge-mcuiot

**Comment by mikekenyon99** [comment]
Thanks 😀👍
