### ISSUE TITLE
Basic TV Support idea

### ISSUE THREAD

**Issue by marcelkordek** [nfarina/homebridge#2184]
Hi @nfarina, @KhaosT,

Thank you for the implementation the Basic TV support.

Due to the limitation of Apple regarding Homekit TV's (only 1 TV per bridge), only one TV will be displayed in the remote overview in the control center. In the Home App, however, all TV's are displayed. I don't think this will change in the Final 12.2.

Would it be possible to create the TV service similar to the IP camera's?
So every TV has to be paired separately.

Thus several TV's should be operated per Homebridge instance and displayed in the control center, or do I have a mistake in thinking?

Does anyone have any suggestions for this?

Thank you
Greetings

**Comment by KhaosT** [comment]
Added a new [API](https://github.com/nfarina/homebridge/blob/master/lib/api.js#L104) to publish separate accessory for this case.

**Comment by nicoduj** [comment]
@KhaosT Thank you for that ! Can’t wait to try :) 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by marcelkordek** [comment]
Wow this was fast 👌 Thank you

**Comment by nicoduj** [comment]
@KhaosT : I don't really get why you add a second method that is exactly the same (except its name) than publishCameraAccessories . 

If I correctly understand, we need to use this method instead of registering the accessory the normal way (through registerPlatformAccessories) ? If the accessory is cached, we have to do nothing right ?

thank you and sorry if my questions seems dumb, just trying to understand before putting this in place in my harmony plugin.

**Comment by KhaosT** [comment]
@nicoduj because it reflects a different purpose. For backwards compatibility reason, we can't just rename `publishCameraAccessories` to `publishExternalAccessories`. External accessories are not cached by homebridge, it's up to plugins to decide what to do there. Normally, as long as services and characteristics are stable, developer should be able to just create a new instance every time `didFinishLaunching` event happens.

**Comment by nicoduj** [comment]
>@nicoduj because it reflects a different purpose. For backwards compatibility reason, we can't just rename `publishCameraAccessories` to `publishExternalAccessories`. External accessories are not cached by homebridge, it's up to plugins to decide what to do there. Normally, as long as services and characteristics are stable, developer should be able to just create a new instance every time `didFinishLaunching` event happens.

@KhaosT thank you for explanations, makes sense even if I would have tried to avoid duplicate code maybe to keep an A with codeFactor, but I am still not a pro in JavaScript :) thanks again for your work on this also :) 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by justme-1968** [comment]
thanks for the publishExternalAccessories function. unfortunately it looks like it is tied to the 'new' platform api? 

is there a way to geht it working with the old style accessories() type of platform plugin?

**Comment by KhaosT** [comment]
@justme-1968 Yeah the current design expects that, since it's not necessarily a good idea for homebridge to just dig into the services returned by accessory plugin and "randomly" push it as a separate accessory to HomeKit. Adopting the new API for platform plugin shouldn't be too tricky I think...

**Comment by justme-1968** [comment]
@KhaosT it would be great if you could get it working :)

**Comment by NorthernMan54** [comment]
@justme-1968 @KhaosT I'm still playing with this, but here is a working example of having multiple TV's created from a single platform plugin using the new API.  (Tks very much ). This is for my multi zone Yamaha receiver that I had been using "Fans" with before.

https://github.com/NorthernMan54/homebridge-yamaha-home/tree/TV

When I'm complete, I'm likely to publish this as homebridge-yamaha-tv ( Need to keep the existing plugin for people still using it. ) so this branch may disappear at some point.

Besides my base Yamaha code base being a bit clumsy, the only really clunky but was getting access to the AccessoryInformation object, as I like to populate it with the implementation details.  As I couldn't figure out the platformAccessory getServiceByUUIDAndSubType function to grab the AccessoryInformation service, I brut forced it with

```
var informationService = this.accessory.services[0];
```
