### ISSUE TITLE
Can't add new accessories - get No Response

### ISSUE THREAD

**Issue by cantchooseaname8** [nfarina/homebridge#2185]
Whenever I update my config.json file with a new accessory, homebridge returns No Response for all of my devices. If I go back and delete the newly added accessory, it goes back to working as normal. I essentially can't make any new changes to my config.json file without it breaking homebridge.

For example, one of the packages that I have is DummySwitch. I already have four switches installed and working perfectly. If I install a fifth switch, all of my homebridge devices return with No Response.

I included both my working config.json file and the one that doesn't work after trying to add another DummySwitch. Any ideas what might be causing this? I'm completely confused at this point.

Any help would be greatly appreciated!!! Thanks.

### Versions

- **Homebridge**: 0.4.46
- **Node**:       8.2.1
- **OS**:  12.2       

### Configuration

```json
Working json:
{
	"bridge": {
		"name": "homebridge",
		"username": "******",
		"pin": "******",
		"port": 43757
	},

	"accessories": [{
		"accessory": "DummySwitch",
		"name": "My Switch 1"
	},
			{
		"accessory": "DummySwitch",
		"name": "My Switch 2"
	},
			{
		"accessory": "DummySwitch",
		"name": "My Switch 3"
	},
			{
		"accessory": "DummySwitch",
		"name": "My Switch 4"
	}
],

	"platforms": [{
		"platform": "RingAlarm",
		"email": "******",
		"password": "******",
		"alarmOnEntryDelay": true
	}]
}


Not working json:
{
	"bridge": {
		"name": "homebridge",
		"username": "******",
		"pin": "******",
		"port": 43757
	},

	"accessories": [{
		"accessory": "DummySwitch",
		"name": "My Switch 1"
	},
			{
		"accessory": "DummySwitch",
		"name": "My Switch 2"
	},
			{
		"accessory": "DummySwitch",
		"name": "My Switch 3"
	},
			{
		"accessory": "DummySwitch",
		"name": "My Switch 4"
	},
			{
		"accessory": "DummySwitch",
		"name": "My Switch 5"
	}
],

	"platforms": [{
		"platform": "RingAlarm",
		"email": "******",
		"password": "******",
		"alarmOnEntryDelay": true
	}]
}
```

**Comment by hmook** [comment]
Same issue here. Unfortunately a removal and reset of homebridge didn’t have the hoped outcome.

**Comment by cantchooseaname8** [comment]
> Same issue here. Unfortunately a removal and reset of homebridge didn’t have the hoped outcome.

Glad it's not just me. Maybe it's a bug and someone else can chime in.

**Comment by NorthernMan54** [comment]
Homebridge is very verbose with its logging, and will show why this is happening in its cryptic way.   Sharing a log may help.

PS Homebridge is exceptionally stable

**Comment by cantchooseaname8** [comment]
> Homebridge is very verbose with its logging, and will show why this is happening in its cryptic way. Sharing a log may help. PS Homebridge is exceptionally stable
> […](#)

Any chance you can help me locate the logs? I'm running homebridge as a service for the autostart capabilities. I ran a search on my pi for anything with homebridge.log in the name but couldn't find anything. Any idea where I can find the logs?

**Comment by cantchooseaname8** [comment]
I was able to get the logs. Here is what I'm getting after trying to add the webos tv accessory. It happens with any accessory that I add, not just this one. If you have any suggestions, it would be very much appreciated.


Mar 25 17:17:31 raspberrypi systemd[1]: homebridge.service: Service hold-off time over, scheduling restart.
Mar 25 17:17:31 raspberrypi systemd[1]: Stopped Node.js HomeKit Server.
Mar 25 17:17:31 raspberrypi systemd[1]: Started Node.js HomeKit Server.
Mar 25 17:17:37 raspberrypi homebridge[606]: [2019-3-25 17:17:37] Loaded config.json with 5 accessories and 1 platforms.
Mar 25 17:17:37 raspberrypi homebridge[606]: [2019-3-25 17:17:37] ---
Mar 25 17:17:37 raspberrypi homebridge[606]: [2019-3-25 17:17:37] Loaded plugin: homebridge-dummy
Mar 25 17:17:37 raspberrypi homebridge[606]: [2019-3-25 17:17:37] Registering accessory 'homebridge-dummy.DummySwitch'
Mar 25 17:17:37 raspberrypi homebridge[606]: [2019-3-25 17:17:37] ---
Mar 25 17:17:37 raspberrypi homebridge[606]: [2019-3-25 17:17:37] Plugin /usr/local/lib/node_modules/homebridge-ring-alarm requires Node version of >=8.3.0 which does not satisfy the current Node version of v8.2.1. You may need to upgrade your installation of Node.
Mar 25 17:17:37 raspberrypi homebridge[606]: [2019-3-25 17:17:37] Loaded plugin: homebridge-ring-alarm
Mar 25 17:17:38 raspberrypi homebridge[606]: [2019-3-25 17:17:37] Registering platform 'homebridge-ring-alarm.RingAlarm'
Mar 25 17:17:38 raspberrypi homebridge[606]: [2019-3-25 17:17:38] ---
Mar 25 17:17:38 raspberrypi homebridge[606]: [2019-3-25 17:17:38] Loaded plugin: homebridge-webos-tv
Mar 25 17:17:38 raspberrypi homebridge[606]: [2019-3-25 17:17:38] Registering accessory 'homebridge-webos-tv.webostv'
Mar 25 17:17:38 raspberrypi homebridge[606]: [2019-3-25 17:17:38] ---
Mar 25 17:17:38 raspberrypi homebridge[606]: [2019-3-25 17:17:38] Loading 1 platforms...
Mar 25 17:17:38 raspberrypi homebridge[606]: [2019-3-25 17:17:38] [RingAlarm] Initializing RingAlarm platform...
Mar 25 17:17:38 raspberrypi homebridge[606]: [2019-3-25 17:17:38] Loading 5 accessories...
Mar 25 17:17:38 raspberrypi homebridge[606]: [2019-3-25 17:17:38] [My Switch 1] Initializing DummySwitch accessory...
Mar 25 17:17:38 raspberrypi homebridge[606]: [2019-3-25 17:17:38] [My Switch 2] Initializing DummySwitch accessory...
Mar 25 17:17:38 raspberrypi homebridge[606]: [2019-3-25 17:17:38] [My Switch 3] Initializing DummySwitch accessory...
Mar 25 17:17:38 raspberrypi homebridge[606]: [2019-3-25 17:17:38] [My Switch 4] Initializing DummySwitch accessory...
Mar 25 17:17:38 raspberrypi homebridge[606]: [2019-3-25 17:17:38] [LG TV] Initializing webostv accessory...
Mar 25 17:17:38 raspberrypi homebridge[606]: path.js:28
Mar 25 17:17:38 raspberrypi homebridge[606]:     throw new TypeError('Path must be a string. Received ' + inspect(path));
Mar 25 17:17:38 raspberrypi homebridge[606]:     ^
Mar 25 17:17:38 raspberrypi homebridge[606]: TypeError: Path must be a string. Received undefined
Mar 25 17:17:38 raspberrypi homebridge[606]:     at assertPath (path.js:28:11)
Mar 25 17:17:38 raspberrypi homebridge[606]:     at join (path.js:1232:7)
Mar 25 17:17:38 raspberrypi homebridge[606]:     at module.exports (/usr/local/lib/node_modules/homebridge-webos-tv/node_modules/persist-path/index.js:19:22)
Mar 25 17:17:38 raspberrypi homebridge[606]:     at new webosTvAccessory (/usr/local/lib/node_modules/homebridge-webos-tv/index.js:33:43)
Mar 25 17:17:38 raspberrypi homebridge[606]:     at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:297:29)
Mar 25 17:17:38 raspberrypi homebridge[606]:     at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:87:38)
Mar 25 17:17:38 raspberrypi homebridge[606]:     at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:45:10)
Mar 25 17:17:38 raspberrypi homebridge[606]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
Mar 25 17:17:38 raspberrypi homebridge[606]:     at Module._compile (module.js:569:30)
Mar 25 17:17:38 raspberrypi homebridge[606]:     at Object.Module._extensions..js (module.js:580:10)
Mar 25 17:17:38 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
Mar 25 17:17:38 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
Mar 25 17:17:38 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.

**Comment by NorthernMan54** [comment]
Error is here

Mar 25 17:17:38 raspberrypi homebridge[606]: throw new TypeError('Path must be a string. Received ' + inspect(path));
Mar 25 17:17:38 raspberrypi homebridge[606]: ^
Mar 25 17:17:38 raspberrypi homebridge[606]: TypeError: Path must be a string. Received undefined
Mar 25 17:17:38 raspberrypi homebridge[606]: at assertPath (path.js:28:11)
Mar 25 17:17:38 raspberrypi homebridge[606]: at join (path.js:1232:7)
Mar 25 17:17:38 raspberrypi homebridge[606]: at module.exports (/usr/local/lib/node_modules/homebridge-webos-tv/node_modules/persist-path/index.js:19:22)
Mar 25 17:17:38 raspberrypi homebridge[606]: at new webosTvAccessory 

The log shows the homebridge-webos-tv plugin, but your config.json is missing it.

**Comment by cantchooseaname8** [comment]
> Error is here
> 
> Mar 25 17:17:38 raspberrypi homebridge[606]: throw new TypeError('Path must be a string. Received ' + inspect(path));
> Mar 25 17:17:38 raspberrypi homebridge[606]: ^
> Mar 25 17:17:38 raspberrypi homebridge[606]: TypeError: Path must be a string. Received undefined
> Mar 25 17:17:38 raspberrypi homebridge[606]: at assertPath (path.js:28:11)
> Mar 25 17:17:38 raspberrypi homebridge[606]: at join (path.js:1232:7)
> Mar 25 17:17:38 raspberrypi homebridge[606]: at module.exports (/usr/local/lib/node_modules/homebridge-webos-tv/node_modules/persist-path/index.js:19:22)
> Mar 25 17:17:38 raspberrypi homebridge[606]: at new webosTvAccessory
> 
> The log shows the homebridge-webos-tv plugin, but your config.json is missing it.

Thanks for the quick reply. Any idea why it wouldn't be reading my config.json correctly? Here is what I have in that file (I added "***" to cover a few things). I've also tried it with adding additional DummySwitch and I get the same thing. It's listed in the config.json, so I'm not sure why I'm getting that error.

{
	"bridge": {
		"name": "homebridge",
		"username": "***",
		"pin": "***",
		"port": 43757
	},

	"accessories": [{
		"accessory": "DummySwitch",
		"name": "My Switch 1"
	},
			{
		"accessory": "DummySwitch",
		"name": "My Switch 2"
	},
			{
		"accessory": "DummySwitch",
		"name": "My Switch 3"
	},
			{
		"accessory": "DummySwitch",
		"name": "My Switch 4"
	},
  {
	"accessory": "webostv",
	"name": "LG TV",
	"ip": "192.168.1.252",
	"mac": "E4:3E:D7:AD:25:3B",
	"keyFile": "/home/pi/.homebridge/lgtvKeyFile",
	"pollingInterval": 10,
	"tvService": true,
	"inputs": [{
		"appId": "com.webos.app.hdmi1",
		"name": "Apple TV"
	}],
	"volumeControl": false,
	"channelControl": false,
	"mediaControl": false
}
],

	"platforms": [{
		"platform": "RingAlarm",
		"email": "***",
		"password": "***!",
		"alarmOnEntryDelay": true
	}]
}

**Comment by NorthernMan54** [comment]
This is really a question for homebridge-webs-tv and not homebridge itself.

Looking at the log, it is complaining about this line of code

Mar 25 17:17:38 raspberrypi homebridge[606]: at new webosTvAccessory (/usr/local/lib/node_modules/homebridge-webos-tv/index.js:33:43)

https://github.com/merdok/homebridge-webos-tv/blob/d59afe22e9e5709e703dc9d68d885b3684b74c22/index.js#L33

Which appears to be related to the 'prefsDir' config option.

I would recommend moving this issue to homebridge-webs-tv

**Comment by cantchooseaname8** [comment]
> This is really a question for homebridge-webs-tv and not homebridge itself.
> 
> Looking at the log, it is complaining about this line of code
> 
> Mar 25 17:17:38 raspberrypi homebridge[606]: at new webosTvAccessory (/usr/local/lib/node_modules/homebridge-webos-tv/index.js:33:43)
> 
> https://github.com/merdok/homebridge-webos-tv/blob/d59afe22e9e5709e703dc9d68d885b3684b74c22/index.js#L33
> 
> Which appears to be related to the 'prefsDir' config option.
> 
> I would recommend moving this issue to homebridge-webs-tv

Even I remove the webos tv and just add another DummySwitch, I still get errors. It does it with everything. Here is the log for just adding an additional DummySwitch. Does this provide any other insights?

Mar 25 19:18:43 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
Mar 25 19:18:43 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
Mar 25 19:18:53 raspberrypi systemd[1]: homebridge.service: Service hold-off time over, scheduling restart.
Mar 25 19:18:53 raspberrypi systemd[1]: Stopped Node.js HomeKit Server.
Mar 25 19:18:53 raspberrypi systemd[1]: Started Node.js HomeKit Server.
Mar 25 19:18:59 raspberrypi homebridge[6678]: [2019-3-25 19:18:59] There was a problem reading your config.json file.
Mar 25 19:18:59 raspberrypi homebridge[6678]: [2019-3-25 19:18:59] Please try pasting your config.json file here to validate it: http://jsonlint.com
Mar 25 19:18:59 raspberrypi homebridge[6678]: [2019-3-25 19:18:59]
Mar 25 19:18:59 raspberrypi homebridge[6678]: /usr/local/lib/node_modules/homebridge/lib/server.js:214Mar 25 19:18:59 raspberrypi homebridge[6678]:     throw err;
Mar 25 19:18:59 raspberrypi homebridge[6678]:     ^Mar 25 19:18:59 raspberrypi homebridge[6678]: SyntaxError: Unexpected token } in JSON at position 445
Mar 25 19:18:59 raspberrypi homebridge[6678]:     at JSON.parse (<anonymous>)
Mar 25 19:18:59 raspberrypi homebridge[6678]:     at Server._loadConfig (/usr/local/lib/node_modules/homebridge/lib/server.js:208:19)
Mar 25 19:18:59 raspberrypi homebridge[6678]:     at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:56:38)
Mar 25 19:18:59 raspberrypi homebridge[6678]:     at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:30:16)
Mar 25 19:18:59 raspberrypi homebridge[6678]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
Mar 25 19:18:59 raspberrypi homebridge[6678]:     at Module._compile (module.js:569:30)
Mar 25 19:18:59 raspberrypi homebridge[6678]:     at Object.Module._extensions..js (module.js:580:10)
Mar 25 19:18:59 raspberrypi homebridge[6678]:     at Module.load (module.js:503:32)
Mar 25 19:18:59 raspberrypi homebridge[6678]:     at tryModuleLoad (module.js:466:12)
Mar 25 19:18:59 raspberrypi homebridge[6678]:     at Function.Module._load (module.js:458:3)
Mar 25 19:18:59 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE

**Comment by NorthernMan54** [comment]
Typo in config.json

Mar 25 19:18:59 raspberrypi homebridge[6678]: [2019-3-25 19:18:59] There was a problem reading your config.json file.
Mar 25 19:18:59 raspberrypi homebridge[6678]: [2019-3-25 19:18:59] Please try pasting your config.json file here to validate it: http://jsonlint.com

**Comment by hmook** [comment]
I’ve tried serval things but still not able to resolve this issue even with a fresh raspberry pi and a new install it won’t give me responsive devices.

**Comment by dewoert** [comment]
Looking at the log:

Plugin /usr/local/lib/node_modules/homebridge-ring-alarm **requires Node version of >=8.3.0** which does not satisfy the **current Node version of v8.2.1**. You may need to upgrade your installation of Node.

**Comment by shawn-digitalpoint** [comment]
Same issue... started with iOS 12.2.  Anecdotal, but on the surface it’s the same thing with a Rachio 3 (I have about 50 real/certified HomeKit devices).  The only 2 things I have issues with after iOS 12.2 is Homebridge and Rachio 3.  Yesterday I reset Homebridge and Rachio back to factory and readded then as new accessories.  Today, they are again the only things giving “No Reponse”.

Seems like a bug in new HomeKit maybe somewhere?  Rachio is a “certified” device and it’s doing the same thing.  All other devices have been fine.

**Comment by henkhb** [comment]
Same here, stopped working after installing homebridge-bravia-tvos. Uninstalled it but Homebridge and all installed devices show "no response"! Need help please. :(

**Comment by kot-925** [comment]
The same story, yesterday added a new accessory and everything stopped working, then returned everything back and still accessories do not respond. Today installed completely, still the accessories don't answer
