### ISSUE TITLE
dev/root 100% and no access to homebridge

### ISSUE THREAD

**Issue by discjockeyr** [nfarina/homebridge#2191]
Hi,
After several months of use the homebbridge on PI with apple homekit it stops responding and i found that the pi memory is full. PI is used only for homebridge to control my cbus lighting with homekit. It seems that each time when i select to do something it write something somewhere so after several months it full the memory. I know that my sd card is only 8gb but i had about 3gb emty when i set it up. Can i clear any cache or temp folder? is there any specific folder that all commands are stored?
thanks in advance

Filesystem      Size  Used Avail Use% Mounted on
/dev/root       5.6G  5.4G     0 100% /
devtmpfs        458M     0  458M   0% /dev
tmpfs           462M     0  462M   0% /dev/shm
tmpfs           462M   12M  450M   3% /run
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           462M     0  462M   0% /sys/fs/cgroup
/dev/mmcblk0p6   65M   22M   43M  34% /boot
tmpfs            93M     0   93M   0% /run/user/109
tmpfs            93M     0   93M   0% /run/user/1000

**Comment by KhaosT** [comment]
Can you share how are you running homebridge? Depends on the setup, the log might live in system journal, a log file, or some random place...

**Comment by discjockeyr** [comment]
> Can you share how are you running homebridge? Depends on the setup, the log might live in system journal, a log file, or some random place...

hmmm... homebridge is running as systemctl if this is what you mean. can i find somewhere a log or a config file to help you understant better?
thanks

**Comment by KhaosT** [comment]
You can try https://unix.stackexchange.com/questions/139513/how-to-clear-journalctl

Or if you can link me the systemd unit file I can take a look too.

**Comment by discjockeyr** [comment]
KhaosT thanks again for your reply. Unfortunately i am not familiar enough with linux. i have follow several instractions to set it up so i am trying to understant what you are trying to explain me.
Fro the link i did not manage to find any solution.
When you said to sent you the systemd unit file you mean the file that i found on /lib/systemd/systemd ?

**Comment by KhaosT** [comment]
Try run `journalctl --vacuum-time=2d` in terminal I mean.

Do you remember which instruction you end up using for start homebridge on boot?

**Comment by discjockeyr** [comment]
Below are the commands that i end up to run the service
systemctl daemon-reload
systemctl enable homebridge
systemctl start homebridge

**Comment by KhaosT** [comment]
@discjockeyr with that `journalctl` command should work... have you tried that?

**Comment by discjockeyr** [comment]
Vacuuming done, freed 0B of archived journals from /run/log/journal/fe0d289b0919                                     413d970ec4768e111cd8.

but the root is still at 100%

**Comment by KhaosT** [comment]
@discjockeyr Let's try `sudo du -a / 2>/dev/null | sort -n -r | head -n 20` to find the biggest file then...

**Comment by discjockeyr** [comment]
this is what i get

sort: write failed: /tmp/sortHFIJU5: No space left on device

**Comment by KhaosT** [comment]
Okay ... let's try `rm -rf /var/cache/apt/archives` and then run the `sudo du -a / 2>/dev/null | sort -n -r | head -n 20`

**Comment by discjockeyr** [comment]
still no space left error

**Comment by KhaosT** [comment]
😞 That's annoying... two things you can try I guess
First one:
```
cd /
sudo du -cks *
```
and then manually find the biggest folder and recursively run it.

Second one:
```
sudo du / 2>/dev/null
and then copy the result to your computer, then run "sort -n -r | head -n 20" manually
```

**Comment by discjockeyr** [comment]
6928    bin
22498   boot
46528   cgate
0       dev
5824    etc
913116  home
188552  lib
16      lost+found
16      media
4       mnt
989000  opt
du: cannot access 'proc/5364/task/5364/fd/3': No such file or directory
du: cannot access 'proc/5364/task/5364/fdinfo/3': No such file or directory
du: cannot access 'proc/5364/fd/3': No such file or directory
du: cannot access 'proc/5364/fdinfo/3': No such file or directory
0       proc
20984   root
du: cannot access 'run/user/109/gvfs': Permission denied
47728   run
7520    sbin
972     ser2sock
4       srv
0       sys
72      tmp
2928112 usr
417240  var
5595114 total

**Comment by KhaosT** [comment]
Looks like something in `/usr` is really big...
I figured out a way to run the sort with not enough space. You can run this from your computer, it should pipe the result back (file list), and then sort on your computer so we wont run into issue like no space...

`ssh pi@YOUR_RASPBERRYPI_ip "sudo du -a / 2>/dev/null" | sort -nr | head -40`

**Comment by discjockeyr** [comment]
KhaosT i apreciate too much your help and thank you.
from where i can run this command? whitout connect to putty?

**Comment by KhaosT** [comment]
Ah... you are using windows... Any chance you have [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10) configured?

If not, I don't have a good solution for you other than manually try running
```
sudo du -cks /home/*
sudo du -cks /opt/*
sudo du -cks /usr/*
sudo du -cks /var/*
```
on raspberry pi and see why those folders are so big...

**Comment by discjockeyr** [comment]
ok KhaosT 

i will try it again with sudo commands as i am on windows and not have subsystem for linux.... i will try ti find out what are those big files and let you know. thanks very very much for your time and help.

**Comment by afharo** [comment]
Hi @discjockeyr,
From https://github.com/nfarina/homebridge/wiki/Basic-Troubleshooting#examine-logs-for-errors, it looks like the log files should be automatically created in these paths:
```
/var/log/homebridge.log
/var/log/homebridge.err
```
If you are only running homebridge in your pi, I'd say the log has gone over your space.
Can you check the size of those 2 files by running
```
sudo ls -lh /var/log/homebridge.*
```
If they are around the GBs size, you might be able to truncate them by simply running:
```
sudo su
:> /var/log/homebridge.log
:> /var/log/homebridge.err
```

**Comment by discjockeyr** [comment]
hi afharo,

i don't know if this is normal but i cannot find those 2 files in pi
Seems that my homebridge is not in the specific folder, but if i serach any of those 2 files i found nothing.
Something strange it happens. It was working now for some months and now gets fu;;. is clear that all the commands are stored somewhere and full up the pi.

**Comment by afharo** [comment]
Oh! Weird!! 
Then I’d check /tmp and /var/log should you can remove anything to clear some space and try with the commands @KhaosT suggested

**Comment by discjockeyr** [comment]
hi guys,

After several reseach in the internet i found the following command " sudo ncdu -x / " and it shows me the folders that are too huge. i have delete several files this morning and i have reduse the size of the disc at 86%. I will test the following days if it increase again the size after the use of the homebridge with homekit and cbus. I know that 86% is also too many but i am not sure if i delete the files that keeping the log data as i don't found log folders.

**Comment by discjockeyr** [comment]
ok, i found finally that there is var/log folder. i don't know why i don't see it before. this folder size is increased each time i sent a command thru homekit to my cbus network. the folder did not contains homebridge.log file but the followinf files. the 3 first files are increased each time i sent a commacd.
Is there a way to autoclean the folder?

--- /var/log ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
                         /..
    1.2 MiB [##########]  syslog
    1.2 MiB [######### ]  daemon.log.2.gz
    1.1 MiB [########  ]  daemon.log
  140.0 KiB [#         ]  kern.log
  112.0 KiB [          ]  messages
   20.0 KiB [          ] /lightdm
   12.0 KiB [          ]  wtmp
   12.0 KiB [          ]  auth.log
    8.0 KiB [          ]  Xorg.0.log.old
    8.0 KiB [          ]  Xorg.0.log
    4.0 KiB [          ]  debug
    4.0 KiB [          ]  boot.log
    4.0 KiB [          ]  user.log
    0.0   B [          ]  btmp
