### ISSUE TITLE
Dynamic Platform [TV]

### ISSUE THREAD

**Issue by SeydX** [nfarina/homebridge#2192]
Hi guys, I have a little problem.  

I have created a plugin for my Bravia TV (dynamic platform).  Whenever I add 'new' inputs, they are first displayed as unknown accessories in HomeKit.

Only after quitting and restarting the apple Home app, they are displayed as 'inputs'.

Is that normal?  or a mistake in the code?

Here my plugin (currently in beta branch):

https://github.com/SeydX/homebridge-bravia-tvos/tree/beta?files=1

**Comment by SeydX** [comment]
Below you can see what i mean with "adding new inputs and they are exposed as unknown accessory"

![prob_homekit](https://user-images.githubusercontent.com/34152761/55670290-de4b9980-5882-11e9-9acc-f17224ac7f87.gif)

**Comment by KhaosT** [comment]
Yeah please try the new publish external accessory API. There are some issues with how home app handles new bridged accessory.

**Comment by SeydX** [comment]
Tried it already, the same issue after a restart AND it seems with the publish external api the accessories are not cached(?)

After every restart the plugin exposes the tv again to HomeKit

I have just replaced the line with publish external api

https://github.com/SeydX/homebridge-bravia-tvos/blob/43579278ea140cf340dd0e0f7e2739dfad5d07d8/src/platform.js#L113

**Comment by KhaosT** [comment]
Yeah it’s not cached as plugin can have more control over it.

Interesting that pairing fresh still have this issue… I don’t have a good suggestion then…

**Comment by SeydX** [comment]
Everytime i call ‚addService‘ it appears always as an unknown accessory till restarting home app...

@KhaosT

Is it maybe possible to avoid addService and push it directly as linkedService and tell HomeKit just to refresh the accessory?

**Comment by KhaosT** [comment]
do you have sample code I can take a look?

**Comment by SeydX** [comment]
@KhaosT 

do you mean from my plugin?

Here i am adding the new inputs as new service

https://github.com/SeydX/homebridge-bravia-tvos/blob/43579278ea140cf340dd0e0f7e2739dfad5d07d8/src/accessory.js#L600

and after than as linkedService

https://github.com/SeydX/homebridge-bravia-tvos/blob/43579278ea140cf340dd0e0f7e2739dfad5d07d8/src/accessory.js#L669

Or you mean from the idea above? If yes, i dont have a sample code for this, was just an idea if it is possible to do it so as described above :/

**Comment by SeydX** [comment]
The inputs are again displayed as unknown accessories.  I have not changed anything, no new inputs, etc, the plugin is running for hours ... This time brings a restart of the home app nothing ... only after restarting Homebridge disappear this again ...

(They are also displayed as inputs on the tv accessory)

![463DAAE0-5A60-4703-9194-2037B738D95D](https://user-images.githubusercontent.com/34152761/55679618-f49f3700-590e-11e9-8660-9587cfab3486.png)

**Comment by SeydX** [comment]
And im using the external publish Api atm for testing (not visible on github)

**Comment by KhaosT** [comment]
@SeydX in your new code, did you call publish accessory before or after adding the services?

**Comment by SeydX** [comment]
@KhaosT 

Before adding the service, as with the previous versions

**Comment by KhaosT** [comment]
@SeydX You need to setup the full accessory before publishing it in this case, otherwise HomeKit will nuke all the old services, and then re-discover them again, causing the issue.

**Comment by SeydX** [comment]
@KhaosT 

Have comepletely rewritten the code to ‚publish External API‘ with creating the whole accessory first (with all detected inputs etc) before publishing. Same issue...

After adding new inputs in config and restarting homebridge, the accessory will be created new again, after accessory is done it will publish it... after publishing, the new inputs appears as unknown accessories... need to force quit and restart home app again

It seems that homebridge first looks at the services array of main accessory (not linkedServices) and expose them to HomeKit (at this stage, the services listed in the linkedServices array from the TV service is ignored), after force quitting and restarting home app, it only shows the linked services as inputs. Maybe it is detecting later the linkedService ?

**Comment by SeydX** [comment]
@KhaosT

One question, do i need to call ‚publishExternalApi‘ everytime i restart homebridge?

I have following problem:
After publishing a new accessory, i set new characteristics like ConfiguredName etc...

With the publishPlatformAccessory, i only need to set it once, atm with publishExternalApi i set it everytime with restarting homebridge. 

The problem with configuredName is, after restarting, the name of the TV in Apple Home app is reset to the name in config.json again. 

Is there a possibility to get the already published accessory (with publishExternalApi) because they are not cached.. ?

**Comment by KhaosT** [comment]
@SeydX Publish external accessory requires developer to manage the accessory itself, so you need to call it every time when homebridge launches. Developer is also responsible of persisting additional data in this case.
