### ISSUE TITLE
Homebridge verliert geräte

### ISSUE THREAD

**Issue by fighterzg6** [nfarina/homebridge#2193]
hallo, 

nach dem update auf Version 0.4.48 tritt ein merkwürdiges Phänomen auf. 
es erscheinen alle geräte im standartraum! nach einer zeit "welche variiert" verschwinden alle geräte! irgend wann kommen sie wieder und verschwinden wieder! auch wenn ich die geräte räumen zuordne verschwinden diese aus den räumen und wenn sie wieder kommen befinden sie sich wieder alle in den Standart räumen! auch ein downgrade oder sogar HomeKit und Homebridge zurücksetzen hat nix gebracht!!!!

**Comment by luissimoes** [comment]
I have exactly the same problem.... .... creating an issue in English with this and will make reference to this issue ok?
