### ISSUE TITLE
Homebridge lässt sich nicht mit Homekit koppeln

### ISSUE THREAD

**Issue by reinerweber** [nfarina/homebridge#2195]
Seit über einem Jahr läuft mein Raspberry Pi erfolgreich mit Homebridge und den Plugins von Devolo und Fritzbox. Seit vorgestern habe ich massive Probleme. Alle Geräte wurden in der Home-App als nicht verfügbar gekennzeichnet. Die Hue-Lampen, welche direkt an Homekit angebunden sind, funktionierten noch. Diverse Reboots und Zurücksetzen der Homebridge brachten kein Erfolg. Ich habe das Haus in Homekit komplett gelöscht. Ich kann, obwohl die Homebridge sauber läuft, nicht mehr aufnehmen. Ich habe den User und den Code manuell in der config geändert. Ohne Erfolg. Hat jemand eine Idee bzw. gibt es ein generelles Problem? Zeitlich passt der Ausfall zum Rollout von IOS 12.2 und den damit verbundenen neuen Features im Homekit. 
Folgende Aktivitäten im Nachgang:

- komplette Neuinstallation Homebridge -> Ohne Erfolg
- Deaktivierung IPV6 -> ohne Erfolg

Vielen Dank für ein Feedback.

**Comment by NewFolk** [comment]
Same here.
2 Iphone at the home
1. My main (no aTV 4 or other hub)  iOS 12 -  **Not responding**
2. My wife iPhone iOS 12.0 - **All Ok**
3. My Macbook (same apple ID to my iphone) 10.14.4 -  **All Ok**

 homebridge@0.4.49

**Comment by NewFolk** [comment]
Full remove Home from HomeKit and clear persist and accessories in homebridge helped me.

**Comment by janis-ax** [comment]
@reinerweber Bekommst du eine Fehlermeldung, wenn ja welche?
