### ISSUE TITLE
Can't run on nodejs v10 and upper

### ISSUE THREAD

**Issue by mafyata** [nfarina/homebridge#2202]
Help !!! Homebridge was working good with nodejs 8.x .   I want to update nodejs , but then I can't start homebridge.

pi@raspberrypi:~ $ homebridge -I
/usr/local/lib/node_modules/hap-nodejs/node_modules/bindings/bindings.js:91
throw e
^

Error: The module '/usr/local/lib/node_modules/hap-nodejs/node_modules/ed25519-hap/build/Release/ed25519.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 67. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
at Object.Module._extensions..node (internal/modules/cjs/loader.js:857:18)
at Module.load (internal/modules/cjs/loader.js:685:32)
at Function.Module._load (internal/modules/cjs/loader.js:620:12)
at Module.require (internal/modules/cjs/loader.js:723:19)
at require (internal/modules/cjs/helpers.js:14:16)
at bindings (/usr/local/lib/node_modules/hap-nodejs/node_modules/bindings/bindings.js:84:48)
at Object.<anonymous> (/usr/local/lib/node_modules/hap-nodejs/node_modules/ed25519-hap/index.js:1:37)
at Module._compile (internal/modules/cjs/loader.js:816:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
at Module.load (internal/modules/cjs/loader.js:685:32)
pi@raspberrypi:~ $

**Comment by Sarcas666** [comment]
I am having the same problem. I upgraded node since I wanted to use the Homebridge-Hue plugin which needs 10.x.x.
I tried rebuilding, reinstalling, removing, cursing and sacrificing a chicken. I'm hoping to find a solution here before offering my firstborn.

**Comment by NorthernMan54** [comment]
If you read the error message posted above it tells you what to do!  That and a bit of googling and you should be fine.

**Comment by mafyata** [comment]
I rebuilded , updated npm , but can’t run again.

**Comment by DJay-X** [comment]
@mafyata 
Try
`cd /usr/local/lib/node_modules/`
`sudo npm rebuild --unsafe-perm`

**Comment by Sarcas666** [comment]
I removed every trace I could find of Homebridge (it turned out it was installed on two different places)and node (there were various versions) and reinstalled following the procedure exactly. It is running now on Node 10.15.3 LTS. I am not 100% sure, but I think using nvm (node version manager) solved the problem at the end. Good luck.
https://github.com/creationix/nvm

**Comment by camrun91** [comment]
> I removed every trace I could find of Homebridge (it turned out it was installed on two different places)and node (there were various versions) and reinstalled following the procedure exactly. It is running now on Node 10.15.3 LTS. I am not 100% sure, but I think using nvm (node version manager) solved the problem at the end. Good luck.
> https://github.com/creationix/nvm

This is actually exctly what happened to me I had two versions of each one as non sudo and one as sudo this caused me a lot of headache.

**Comment by KhaosT** [comment]
Try again with v0.4.49 :)

**Comment by roy-pa** [comment]
> @mafyata
> Try
> `cd /usr/local/lib/node_modules/`
> `sudo npm rebuild --unsafe-perm`

it worked in my case 

> @mafyata
> Try
> `cd /usr/local/lib/node_modules/`
> `sudo npm rebuild --unsafe-perm`

it worked in my case !

**Comment by roy-pa** [comment]
> @mafyata
> Try
> `cd /usr/local/lib/node_modules/`
> `sudo npm rebuild --unsafe-perm`

it worked..Great thanks

**Comment by mafyata** [comment]
I i made new sd card i manually installed everything. Now everything is ok.
