### ISSUE TITLE
Cannot install Homebridge on Mac OS Mojave

### ISSUE THREAD

**Issue by sether82** [nfarina/homebridge#2203]
(Sorry if I posted this in the wrong place!)

Followed instructions at https://github.com/nfarina/homebridge/wiki/Install-Homebridge-on-macOS

Everything worked fine until command "npm -g install homebridge --unsafe-perm" gave the following error:

npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
npm ERR! path /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!  { [Error: EACCES: permission denied, access '/usr/local/lib/node_modules']
npm ERR!   stack:
npm ERR!    'Error: EACCES: permission denied, access \'/usr/local/lib/node_modules\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

This is all greek to me. Any help would be appreciated.

**Comment by HDJulie** [comment]
I had a similar problem. I had to manually delete the directories.
