### ISSUE TITLE
Node.js 12.0.0 Cannot Compile

### ISSUE THREAD

**Issue by walksonair** [nfarina/homebridge#2204]
Just had to downgrade node back to v11.14 (last release) as Homebridge would not compile under v12. FYI for those who may run the NPM update like I do...

FYI I use Homebrew to install NPM@11 and it worked on my MacOS Mojave...

**Comment by Krocko** [comment]
Same for me on a Raspberry Pi.

**Comment by KhaosT** [comment]
#2205 should fix the issue with v0.4.49.
