### ISSUE TITLE
Different locations of config.json

### ISSUE THREAD

**Issue by nixmeer** [nfarina/homebridge#2210]
Hello

where is the config.json supposed to be located? I have seen different tutorials placing it in different locations:

```
/var/homebridge/config.json
~/.homebridge/config.json
/root/.homebridge/config.json
```

I placed it in `~/.homebridge/config.json` but Homebridge won't start since it misses the config.json in `/root/.homebridge`. homebridge was installed by the default user `pi` using the standard flags `-g` and `--unsafe-perm` and executed by the same user.
 
Is there a benefit of any location? What is the default location? How do I change the location where homebridge is looking for it?

Thanks in advance!

**Comment by mafyata** [comment]
Is homebridge starting with linux boot or you manually start homebridge after boot ?

**Comment by nixmeer** [comment]
On the new raspberry, I tried to start it manually. If that works as aspected, I'd like to use systemd services

**Comment by mafyata** [comment]
Config.json must be in pi/.homebridge

**Comment by nixmeer** [comment]
that is where I placed it! As mentioned above, homebridge misses /root/.homebridge/config.json and I wonder why.

**Comment by nixmeer** [comment]
Again: the file is placed exactly where you said it should be placed. However, I can't start homebridge because it says it can not find /root/.homebridge/config.json

**Comment by mafyata** [comment]
Look at the picture!!! Home/pi/.homebridge/config.json

**Comment by nixmeer** [comment]
This is where I placed it: `~/.homebridge/config.json` 
Still homebridge can't find it, and it seems as if it was looking for it some where else. 

The config.json file has previously been used on another pi so I assume it is readable

**Comment by mafyata** [comment]
So , try to search config.json file from tools-search

**Comment by mafyata** [comment]
Shift+Ctrl+F

**Comment by nixmeer** [comment]
ok, I found the problem. Homebridge has had no persmissions for the `.homebridge` directory.

However, I'd still like to know why some people place it somewhere else

**Comment by mafyata** [comment]
Mine was at home/pi/.homebridge
When I make it to start when linux boot , homebridge is copied in new location. I don’t know why , but the old location is there , not deleted , just copied to the new location where linux start it automatically when boot. If you do start with boot , you must copy config.json to the new location. After that  in your phone/tablet you must delete homebridge hub and add again.

**Comment by nixmeer** [comment]
ok it is working now (using systemd service) so I will close this issue. Still I'd like to know if there is any benefit.
