### ISSUE TITLE
problem with homebridge 0.4.49

### ISSUE THREAD

**Issue by harrykausl** [nfarina/homebridge#2211]
I have running homebridge in combination with domoticz on my raspberry since 3 years. I also use homebridge-edomaticz plugin and mqtt. Currently I use homebrdige 0.4.47. When I update to the actual version 0.4.49 homebridge stops immediatly after starting . In the logfile I see SIGTERM, shutting down homebridge. When I go back to 0.4.47 (with yn old image of my pi) everything runs ok. Has anyone a idea? Thanks

**Comment by ebaauw** [comment]
Probably an uncaught exception.  What's the lines before the SIGTERM?

**Comment by harrykausl** [comment]
There are 3 devices startet, then mqtt startet and then comes the sigterm. I went back to a image with 0.4.47, all worked. Then I updatetd homebridge again and the same error.

**Comment by KhaosT** [comment]
Can you post the log here? I’d like to fix it for sure 🙏

**Comment by harrykausl** [comment]
this is the log

[5/4/2019, 8:13:10 PM] Homebridge is running on port 51826.
[5/4/2019, 8:13:10 PM] [Domoticz] Helligkeit Esszimmer
[5/4/2019, 8:13:10 PM] [Domoticz] Temperatur Esszimmer
[5/4/2019, 8:13:10 PM] [Domoticz] Thermostat Schlafzimmer Temperatur
[5/4/2019, 8:13:11 PM] [Domoticz] Successfully connected to MQTT broker.
[5/4/2019, 8:14:57 PM] Got SIGTERM, shutting down Homebridge...

**Comment by harrykausl** [comment]
@KhaosT 
Did you find anything in the log?

**Comment by harrykausl** [comment]
Today I tried 0.4.50, same problem
