### ISSUE TITLE
Lost TVs from third party apps

### ISSUE THREAD

**Issue by 2nm** [nfarina/homebridge#2212]
Since the official release of 12.2 the TV state and controls don’t show up in third party apps.  Do you know what’s happened, I use the LG webos but the dev says he hasn’t changed that side of things, I’m using 12.2 and 12.3 and neither show up.  Wondering if something changed between iOS and homebridge?  Have you noticed it?

**Comment by ebaauw** [comment]
Yes, I see the same.  TV accessories were visible to other HomeKit apps in the early iOS 12.2 betas.  They are not visible in later iOS 12.2 betas, in released iOS 12.2, and in iOS 12.3 betas.

I've yet to try a non-bridged TV accessory, but I don't hold high hopes.
