### ISSUE TITLE
ERROR: Dropped event message, rate too high.

### ISSUE THREAD

**Issue by sherazan** [nfarina/homebridge#2213]
Hi I'm receiving this message:

ERROR: Dropped event message, rate too high.

homebridge 0.4.49

Do you have suggest?

Thanks

### Versions

- **Homebridge**: `homebridge --version`
- **Node**:       `node --version`
- **OS**:         

### Configuration

```json

```

### Homebridge Log / Command Output

```

```

**Comment by NorthernMan54** [comment]
Is this homebridge-Alexa?

It will emit this if it sees too many events in a short period of time.

**Comment by sherazan** [comment]
Yes it is. I would understand the origin of this messages...

> Il giorno 5 mag 2019, alle ore 17:50, Northern Man <notifications@github.com> ha scritto:
> 
> Is this homebridge-Alexa?
> 
> It will emit this if it sees too many events in a short period of time.
>

**Comment by NorthernMan54** [comment]
There is a limit on the amazon side, and the error is letting you know it dropped messages.  Am thinking that this should be a warning instead and include homebridge-Alexa in the name.

**Comment by sherazan** [comment]
The complete message is:

mag 05 13:54:22 homebridgea homebridge[10824]: ERROR: Dropped event message, rate too high.

It include the server name “homebridgea” and the HB istance name “homebridgea”.

It’s good if you think that it should be a warning.

I would only understand if it is possible understand the origin of this messages.




> Il giorno 5 mag 2019, alle ore 18:01, Northern Man <notifications@github.com> ha scritto:
> 
> There is a limit on the amazon side, and the error is letting you know it dropped messages. Am thinking that this should be a warning instead and include homebridge-Alexa in the name.
>

**Comment by NorthernMan54** [comment]
In DEBUG mode it will log all event messages, and you should be able to see if a sensor is sending too many.

**Comment by sherazan** [comment]
Thanks. I will do...

> Il giorno 5 mag 2019, alle ore 18:46, Northern Man <notifications@github.com> ha scritto:
> 
> In DEBUG mode it will log all event messages, and you should be able to see if a sensor is sending too many. 
> 
> Sent from my iPad
>

**Comment by NorthernMan54** [comment]
Going to close this, if you have any more questions please raise an issue on homebridge-alexa
