### ISSUE TITLE
Homebridge on Pi via Ethernet

### ISSUE THREAD

**Issue by Yatinbaluja** [nfarina/homebridge#2216]
Hi All,

I'm running Homebridge on raspberry pi model 3 b+ via Ethernet where raspberry pi is working as a WiFi hotspot and the Homekit is connected to the WiFi produced by raspberry pi hostapd mode and I'm using ESP32 to control the LED and the ESP32 is also connected to the same WiFi network as produced by raspberry pi but I'm not able to add Accessory on the Homekit.

Any suggestions how can I sort this problem where Homebridge is running on Ethernet and Homekit is on WiFi.

Regards,
Yatin Baluja

**Comment by ebaauw** [comment]
Make sure homebridge announces itself (using Bonjour) over the WiFi interface, see https://github.com/nfarina/homebridge/issues/2098.
