### ISSUE TITLE
Nothing is responding after months of being perfectly stable

### ISSUE THREAD

**Issue by ifeign** [nfarina/homebridge#2220]
I'm at a loss. My Homebridge set up is just dead. I'm able to add all my accessories etc to homekit but nothing responds. I troubleshooted all the normal ways (deleting persist folder, removing and re adding the bridge, updating my raspberry pi, changing the pairing code and id). I took more extreme steps: I downgraded my router firmware because the problem started shortly after the router got updated, I downgraded several versions below the previous release. Still nothing. Next I did a clean install of raspbian and Homebridge, still the same situation. I can add accessories but not use them. The only thing I haven't tried is completely deleting my home and redoing everything, but my native Homekit accessories work just fine. There's also the option of doing a different install method, currently I used oznu's docker script to install Homebridge, I might just try a manual installation the next time I have the energy to try again.

I'm running the latest Homebridge, latest iOS/tvOS version, but this happened before I updated those devices yesterday. My router is a Netgear Orbi

Any suggestions welcome, I'm losing my mind trying to solve this.

**Comment by mafyata** [comment]
I use homebridge by nfarina on my raspberry with raspbian os. 
I used instructions from this video:
https://youtu.be/2RnDp5Eg1RE
Yesterday I updated my iphone and my ipad which I use as a hub and everything is working fine. 
May be your problem is some of your plugin if you install new plugin before the crash.

**Comment by ifeign** [comment]
Thanks for the reply. I haven't added anything new. I just experienced something weird though. After completely deleting my home and recreating it, I was able to add Homebridge and control one accessory exactly one time. When I tried to turn the accessory off again it was too late, everything was back to "no response"

**Comment by mafyata** [comment]
Try to reset the accessory.

**Comment by ifeign** [comment]
Reset it how? I completely wiped my raspberry pi and deleted my entire HomeKit setup and tried again with no difference

**Comment by mafyata** [comment]
Not raspberry . Reset your device - sonoff , hue or what you have.

**Comment by jetison** [comment]
> Thanks for the reply. I haven't added anything new. I just experienced something weird though. After completely deleting my home and recreating it, I was able to add Homebridge and control one accessory exactly one time. When I tried to turn the accessory off again it was too late, everything was back to "no response"
> 
> My logs show nothing wrong, however I will try adding my accessories one at a time.

I'm experiencing the same issue. Accessories not responding. Been having this issue since iOS 12.2.
Resetting and re-adding only gets them to work for a few moments only.

**Comment by ifeign** [comment]
> Not raspberry . Reset your device - sonoff , hue or what you have.

I get where you're coming from but how likely is it that six different devices from multiple manufacturers are the problem? It's most definitely Homebridge or my router.

**Comment by ifeign** [comment]
> > Thanks for the reply. I haven't added anything new. I just experienced something weird though. After completely deleting my home and recreating it, I was able to add Homebridge and control one accessory exactly one time. When I tried to turn the accessory off again it was too late, everything was back to "no response"
> > My logs show nothing wrong, however I will try adding my accessories one at a time.
> 
> I'm experiencing the same issue. Accessories not responding. Been having this issue since iOS 12.2.
> Resetting and re-adding only gets them to work for a few moments only.

Damn, what have you done to try and fix it? I'm about ready to switch to Home Assistant if this persists..

**Comment by jetison** [comment]
> > > Thanks for the reply. I haven't added anything new. I just experienced something weird though. After completely deleting my home and recreating it, I was able to add Homebridge and control one accessory exactly one time. When I tried to turn the accessory off again it was too late, everything was back to "no response"
> > > My logs show nothing wrong, however I will try adding my accessories one at a time.
> > 
> > 
> > I'm experiencing the same issue. Accessories not responding. Been having this issue since iOS 12.2.
> > Resetting and re-adding only gets them to work for a few moments only.
> 
> Damn, what have you done to try and fix it? I'm about ready to switch to Home Assistant if this persists..

Reset Homebridge (changed username, pin, port), deleted Home and recreated it, deleted persist folder. After adding back Homebridge to Home, it works just one time and goes straight to "not responding".

**Comment by ifeign** [comment]
> > > > Thanks for the reply. I haven't added anything new. I just experienced something weird though. After completely deleting my home and recreating it, I was able to add Homebridge and control one accessory exactly one time. When I tried to turn the accessory off again it was too late, everything was back to "no response"
> > > > My logs show nothing wrong, however I will try adding my accessories one at a time.
> > > 
> > > 
> > > I'm experiencing the same issue. Accessories not responding. Been having this issue since iOS 12.2.
> > > Resetting and re-adding only gets them to work for a few moments only.
> > 
> > 
> > Damn, what have you done to try and fix it? I'm about ready to switch to Home Assistant if this persists..
> 
> Reset Homebridge (changed username, pin, port), deleted Home and recreated it, deleted persist folder. After adding back Homebridge to Home, it works just one time and goes straight to "not responding".

Sounds like we're in a similar situation... Out of curiosity, what router are you using?

**Comment by nenadmilano** [comment]
> > > > > Thanks for the reply. I haven't added anything new. I just experienced something weird though. After completely deleting my home and recreating it, I was able to add Homebridge and control one accessory exactly one time. When I tried to turn the accessory off again it was too late, everything was back to "no response"
> > > > > My logs show nothing wrong, however I will try adding my accessories one at a time.
> > > > 
> > > > 
> > > > I'm experiencing the same issue. Accessories not responding. Been having this issue since iOS 12.2.
> > > > Resetting and re-adding only gets them to work for a few moments only.
> > > 
> > > 
> > > Damn, what have you done to try and fix it? I'm about ready to switch to Home Assistant if this persists..
> > 
> > 
> > Reset Homebridge (changed username, pin, port), deleted Home and recreated it, deleted persist folder. After adding back Homebridge to Home, it works just one time and goes straight to "not responding".
> 
> Sounds like we're in a similar situation... Out of curiosity, what router are you using?

I've got a similar issue. Homebridge reset + removal from Home App works for one minute, afterwards all accessories go back to "No Response". I have it installed on a Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-50-generic x86_64) Virtual Machine on a ESXi.

As a router i use a Unifi Security Gateway 3P

npm-version
{ npm: '6.9.0',
  ares: '1.14.0',
  cldr: '32.0.1',
  http_parser: '2.7.1',
  icu: '60.2',
  modules: '57',
  nghttp2: '1.30.0',
  node: '8.10.0',
  openssl: '1.0.2n',
  tz: '2017c',
  unicode: '10.0',
  uv: '1.18.0',
  v8: '6.2.414.50',
  zlib: '1.2.11' }

Homebridge Version 0.4.49

**Comment by h2zero** [comment]
I just tried this out with Domoticz tonight on a raspberry pi, same issues going on. It works fine for a couple mins then no accessories responding. I'm not sure where to start troubleshooting this, I've done the same as others above, deleting presist etc folders and redoing the linking with the same result.

version 0.4.49

**Comment by ifeign** [comment]
I figured out my issue. I had to factory reset my Dyson fan, somehow it got messed up when my router firmware upgraded. Reset, reconnected it, everything is back to normal. I had to delete persist, accessories and change the pin etc but after that it was fine.

To get to this point I started homebridge with only one plugin at a time, I suggest you try the same.

**Comment by mafyata** [comment]
There is nothing to do except reset your iphone/ipad to default settings. You can try other method. Delete homebridge hub from your ios device and add it in new device.
