### ISSUE TITLE
About use typescript coding plugin template

### ISSUE THREAD

**Issue by songzh96** [nfarina/homebridge#2221]
who can provide the simple Tutorial.
the homebridge-tesla plugin, I don't understand this process too much.

It may be that I am too dishy.

best regrads~

**Comment by songzh96** [comment]
https://github.com/songzh96/homebridge-lightbulb-ts-demo

**Comment by mafyata** [comment]
What is this plugin?

**Comment by songzh96** [comment]
> What is this plugin?

A plugin written in typescript that communicates via a socket. This plugin is mainly to tell you how to write a homebridge plugin with typescript.
