### ISSUE TITLE
Mozilla IoT (Web Things API) plugin request

### ISSUE THREAD

**Issue by arstulke** [nfarina/homebridge#2224]
A plugin for controlling and interacting with devices over the [Web Things API](https://iot.mozilla.org/wot/) would be open up new possibilities. The [Mozilla IoT Gateway](https://github.com/mozilla-iot/gateway) is a reference implementation of the Web Things API.

**Comment by fcm1982** [comment]
Will be really fantastic, if there will be an possibility. Actually there is only the HomeKit device adapter which doesn't work as the Pin from homebridge is not acceppted.
