### ISSUE TITLE
homekit Fan controls

### ISSUE THREAD

**Issue by JangoBritt** [nfarina/homebridge#2227]
Hi developers, I'm trying to weigh in on a plugin for the Ewelink/Sonoff Cloud plugin

https://github.com/howanghk/homebridge-ewelink/

I am in particular wondering about Fan controls within HomeKit. I'm not sure how to register an accessory as a fan that you could increase the Fan speed, like the Hunter Fan controls in HomeKit.

The Sonoff iFan02 has 4 channels on the device API, which are used to configure Light, Fan on/off (Low), Med, and High.

At the moment, that is presented as 4 different switches, but I'd prefer to re-code the plugin to present it as a light switch, and a fan with a slider control.

Would appreciate any assistance with how I can do this.

**Comment by ebaauw** [comment]
Create a single accessory, with a _Lightbulb_ service for the light and a _Fanv2_ service for the Fan.  The _Fanv2_ includes characteristics for _Rotation Speed_, etc, see https://github.com/KhaosT/HAP-NodeJS/blob/d0f92c202e312717829b76c3803c86aa04fa8dc0/lib/gen/HomeKitTypes.js#L2905.

**Comment by JangoBritt** [comment]
Thanks!
