### ISSUE TITLE
Error: Cannot Bridge more than 149 Accessories

### ISSUE THREAD

**Issue by DJay-X** [nfarina/homebridge#2228]
Hey guys.  Hi @nfarina  Today I was facing a problem I didn't know it ever would happens to me. ;)
I run Homebridge the classic way without instances, just on a Pi3B+.
System is running for many months now without any problems.
Now I found in the Log after I reboot the Pi `Error: Cannot Bridge more than 149 Accessories`and homebridge did't start.
Checking on Apple Home App - after I removed a Plugin and by this some accessories - I still have 147 Devices on Homebridge. Homebridge is running with this amount of devices again perfect. 

Does this mean Homebridge is restricted to 149 accessories with intention and I can't get around this? 
Hope anybody can help and give me some background info to higher the 149 accessories.

Thanks in advance for the time you are investing. Happy to learn.  :)

**Comment by NorthernMan54** [comment]
This is a HomeKit limitation and not homebridge. Homebridge is just letting you know.

To workaround the issue, split your setup into multiple instances of homebridge.

**Comment by DJay-X** [comment]
Thanks @NorthernMan54 I probably have to do this and get myself informed how do setup instances. As I understand I can keep the existing homebridge with my 147 accessories and just add a new instance and use new plugins/devices there. 
By the way thanks for your homebridge-alexa . ;)

**Comment by DJay-X** [comment]
Created a 2nd-Instance and that fixed my problem with `Error: Cannot Bridge more than 149 Accessories.` setting up new devices now on the 2nd-Instance.
For help and instruction in German language can be found here.
https://forum.smartapfel.de/forum/thread/910-homebridge-instanzen-anlegen/

Translation here: https://translate.google.com/translate?sl=auto&tl=en&u=https%3A%2F%2Fforum.smartapfel.de%2Fforum%2Fthread%2F910-homebridge-instanzen-anlegen%2F

**Comment by JurgenLB** [comment]
You could try a 'child bridge'
