### ISSUE TITLE
[News] Router Support + Airplay automations

### ISSUE THREAD

**Issue by iRayanKhan** [nfarina/homebridge#2230]
Hello everyone,
Apple has just shown at WWDC19 that routers can now support HomeKit. Now it seems like a firewall on a router, but maybe the characteristics  can be added like band strength etc not much details on this. 
Other news:
Cameras can now use iCloud.

Airplay 2 speakers now work in automations. 

Use this issue as a thread about this topic.
I hope this helps any devs wanting to add things.

**Comment by linusnyren** [comment]
The HomeKit secure video function would be awesome if incorporated to HomeKit!
Guess we got to wait and see how video sending mechanisms work. Hoping for a simple rtsp stream but I can’t be that easy...

**Comment by KhaosT** [comment]
I'll probably look more into secure video recording. The router support is ... annoying, since it's TLV heavy, and it doesn't really make sense to me having iOS/HomeKit to manage your network...

**Comment by bdruth** [comment]
TLV?

**Comment by sofakng** [comment]
I'm also very interested in HomeKit Secure Video and I'd love to see it implemented into HomeBridge.  Thanks for all your hardwork @KhaosT!

**Comment by dibble9012** [comment]
It looks like HomeKit Secure Video will be available as a firmware update on cameras (not requiring extra hardware) which should make it so HomeBridge can be updated to support it.

"Netatmo
We are very excited to be working with Apple to provide Netatmo users the best smart-home experience and the most advanced technologies that protect user privacy and security. The Netatmo Smart Video Doorbell will be compatible with HomeKit Secure Video at its launch and a free, automatic firmware update will add HomeKit Secure Video compatibility to new and existing Netatmo Smart Indoor Cameras and Smart Outdoor Cameras later this year. Netatmo users can experience HomeKit Secure Video through the Apple Home app on iPhone and iPad with select iCloud storage plans."

**Comment by iRayanKhan** [comment]
Closed: I think everyone gets the point now, can't wait to see the implementations!
