### ISSUE TITLE
Erroneous error msg regarding node version mismatch for plug-in

### ISSUE THREAD

**Issue by RMCob** [nfarina/homebridge#2231]
The following warning is generated when homebridge starts:

[6/3/2019, 4:43:26 PM] Plugin /usr/lib/node_modules/homebridge-bravia-tvos requires Node version of ^8.9.1 which does not satisfy the current Node version of v12.3.1. You may need to upgrade your installation of Node.

 I have the latest versions of Homebridge and the tvos plug-in. Everything seems to be working properly. Just the bogus warning message....

Thanks!

**Comment by mediter** [comment]
installed v10.15.3, requires ^8.9.1, but the following warning appears in log

```
Plugin /usr/local/lib/node_modules/homebridge-camera-ui requires Node version of ^8.9.1 which does not satisfy the current Node version of v10.15.3. You may need to upgrade your installation of Node.
```

**Comment by mafyata** [comment]
node -v
This will show you current installed node version.
