### ISSUE TITLE
libc++abi.dylib: terminating with uncaught exception

### ISSUE THREAD

**Issue by mbial** [nfarina/homebridge#2233]
So I was trying to configure FFMPEG to work with my video doorbell (Doorbird)...I reinstalled Homebrew, FFMPEG, and everything seemed to be working until my next Homebridge restart, now I get the error below.

I have attempted to reinstall my Homebridge plugins and npm rebuild.  Any suggestions?

Running:
Homebridge: 0.4.50
Node: 12.4.0
MacOS Mojave 10.14.5

### Homebridge Log / Command Output

```
homebridge(1069,0x10bb6d5c0) malloc: can't allocate region
*** mach_vm_map(size=180146304411033600) failed (error code=3)
homebridge(1069,0x10bb6d5c0) malloc: *** set a breakpoint in malloc_error_break to debug
libc++abi.dylib: terminating with uncaught exception of type std::bad_alloc: std::bad_alloc
Abort trap: 6
```

**Comment by mbial** [comment]
Found the problem!! I had accidentally managed to install a second, newer version of Node. Once I set the correct version, everything is back!

**Comment by mafyata** [comment]
How did you set the correct version?
