### ISSUE TITLE
Thermostat/HeaterCooler: possible to hide cool/auto modes?

### ISSUE THREAD

**Issue by maisun** [nfarina/homebridge#2239]
Hi,
Looks like by default a Thermostat will have four modes:
1) Off
2) Heat
3) Cool
4) Auto
If I have a device which only support heating, is there a way to disable other modes? Or even disable the modes selection possibility? Thank you

**Comment by Partizan7676** [comment]
ask plugin author

**Comment by tobekas** [comment]
Yes, you just have to change the property `characteristic.props.validValues` for tote TargetState characteristic.

**Comment by maisun** [comment]
> Yes, you just have to change the property `characteristic.props.validValues` for tote TargetState characteristic.

Hi I tried that and can restrict values to what I need, works great except for a minor thing. For Heater/Cooler with auto mode I can't seem to find a way to remove "OFF" option. So if I allow 0=AUTO, 1=HEAT and 2=COOL, it will show 3=OFF even though the value is not allowed. But the interesting thing is, if I only allow 1 and 2, then both 0 and 3 are invisible. Guess some minor bug somewhere, no big deal though.

**Comment by tobekas** [comment]
For Apple‘s newer services, like HeaterCooler, HumidifierDehumdiifier, AirPurifier, Valve, Fanv2,... they completely removed the OFF option from the target states (like in Thermostat) and use an additional characteristic „Active“ for this.
I think the OFF option in the user interface (Home App) relates to this characteristic and therefore cannot be restricted by validValues for ***TargetState.
The accessory should always have a chance to be switched off. I wonder why OFF disappears, if you allow only Cool and Heat. I have not seen this yet

**Comment by maisun** [comment]
> For Apple‘s newer services, like HeaterCooler, HumidifierDehumdiifier, AirPurifier, Valve, Fanv2,... they completely removed the OFF option from the target states (like in Thermostat) and use an additional characteristic „Active“ for this.
> I think the OFF option in the user interface (Home App) relates to this characteristic and therefore cannot be restricted by validValues for ***TargetState.
> The accessory should always have a chance to be switched off. I wonder why OFF disappears, if you allow only Cool and Heat. I have not seen this yet

My understanding is active shows the current state of the device (if it’s running). For thermostat I leave only one target state HEAT, and in Homekit “modes” menu is completely gone (because only one option). For Heater/cooler if I only keep HEAT and COOL options, I get a switch in Homekit. So I believe target state is still the way to control the options.

**Comment by tobekas** [comment]
Characteristic „Active“ is very similar to „On“. Definitely from the Homekit framework view, for HeaterCooler you have to use both „TargetHeaterCoolerState“ (which does **not** include OFF) and „Active“ (which can be ACTIVE or INACTIVE. From the Home App view, it seems like OFF is a fourth mode, but in fact, if you select mode to OFF, „Active“ is set to INACTIVE and the target mode is not touched. The advantage is, that you can turn on/off the device directly from the room view and the last target mode is retained.
If you only allow one target state, there will be switch. If you allow only Heat and Cool, there will also be an OFF field.

**Comment by Tommrodrigues** [comment]
You have to add the `maxValue` to `.setProps` like below:

```js
this.service.getCharacteristic(Characteristic.TargetHeatingCoolingState)
      .setProps({
        maxValue: Characteristic.TargetHeatingCoolingState.HEAT
      })
```

Take a look at my [homebridge-web-boiler](https://github.com/Tommrodrigues/homebridge-web-boiler/blob/master/index.js) plugin if you want a full example.

**Comment by maisun** [comment]
> You have to add the `maxValue` to `.setProps` like below:
> 
> ```js
> this.service.getCharacteristic(Characteristic.TargetHeatingCoolingState)
>       .setProps({
>         maxValue: Characteristic.TargetHeatingCoolingState.HEAT
>       })
> ```
> 
> Take a look at my [homebridge-web-boiler](https://github.com/Tommrodrigues/homebridge-web-boiler/blob/master/index.js) plugin if you want a full example.

Thank you! Tried that without luck. For Thermostat the trick works, but not for Heater/Cooler for some reason.

**Comment by tobekas** [comment]
As I said before, you can not make „OFF“ disappear for HeaterCooler, because it is linked to the required Characteristic.Active and is not/never part of TargetState. It‘s only about how the UI of the Home App is designed. Try Eve App for comparison.

**Comment by maisun** [comment]
> As I said before, you can not make „OFF“ disappear for HeaterCooler, because it is linked to the required Characteristic.Active and is not/never part of TargetState. It‘s only about how the UI of the Home App is designed. Try Eve App for comparison.

Hi thank you I fully understand what you're saying, but as I stated earlier on I can hide the OFF button if I only allow 1=HEAT and 2=COOL, so it must be possible.

**Comment by tobekas** [comment]
I also tried 
`maxValue: 1,
minValue: 0,
validValues: [0,1],`
and with this you can select HEAT, COOL and OFF in Apples Home App. In Eve you can choose between Heat and Cool and have a separate On/Off switch. This reflects the underlying characteristics logic better...

**Comment by maisun** [comment]
> I also tried
> `maxValue: 1, minValue: 0, validValues: [0,1],`
> and with this you can select HEAT, COOL and OFF in Apples Home App. In Eve you can choose between Heat and Cool and have a separate On/Off switch. This reflects the underlying characteristics logic better...

Try validValues: [1,2] or validValues: [1]

**Comment by maisun** [comment]
Ok, only way is to disallow value 0 for Active:
        primaryService.getCharacteristic(this.Characteristic.Active).setProps({
            maxValue: 1,
            minValue: 1,
            validValues: [1]
        });
It works differently from Thermostat which I can hide the OFF button completely:
