### ISSUE TITLE
Yamaha RX-V2067 won't recognized

### ISSUE THREAD

**Issue by neonightmare** [nfarina/homebridge#224]
Hi, got my Rpi2 with KNX, HTTP and Yamaha working. But my RX-V2067 won't be  detected... any suggestions?
--> RX-V2067 / RX-A2000 Firmware Update Version 3.65
--> Network Stand-By is activated, Connection with IOS-App works

config.json:
```
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    "description": "This is an example configuration file for KNX platform shim",
    "hint": "Always paste into jsonlint.com validation page before starting your homebridge, saves a lot of frustration",
    "hint2": "Replace all group addresses by current addresses of your installation, these are arbitrary examples!",
    "hint3": "For valid services and their characteristics have a look at the knxdevice.md file in folder accessories!",
    "platforms":
    [

            {
               "platform": "YamahaAVR",
               "play_volume": -48,
               "setMainInputTo": "Tuner"
             },
             {
            "platform": "KNX",
            "name": "KNX",
            "knxd_ip": "127.0.0.1",
            "knxd_port": 6720,
            "accessories": [
                {
                    "accessory_type": "knxdevice",
                    "description": "sample device with multiple services. Multiple services of different types are widely supported",
                    "name": "Werkstatt",
                    "services": [
                            {
                            "type": "Lightbulb",
                            "name": "Werkstatt Raum",
                            "On": {
                                "Set": "1/1/1"
                                  }
                            },
                            {
                            "type": "Lightbulb",
                            "name": "Werkstatt Fenster",
                            "On": {
                                "Set": "1/1/2"
                                  }
                            },
                            {
                            "type": "Thermostat",
                            "description": "iOS8 Thermostat type, supports CurrentTemperature, TargetTemperature, CurrentHeatingCoolingState ",
                            "name": "Raumtemperatur",
                            "CurrentTemperature": {
                                "Listen": "1/1/10"
                                },
                            "TargetTemperature": {
                                "Set": "1/1/11"
                                },
                            "CurrentHeatingCoolingState": {
                                "Listen": "1/1/12"
                                }
                            },
                            {
                            "type": "TemperatureSensor",
                            "name": "ArduinoTemperatur",
                            "CurrentTemperature": {
                                "Listen": "2/0/0"
                                }
                            }
                      ]
                  }


            ]
          }
      ],

       "accessories": [
         {
   "accessory": "Http",
   "name": "Relais 1",
   "on_url": "http://192.168.1.178/?button1on",
   "off_url": "http://192.168.1.178/?button1off",
   "http_method": "POST"
        }

   ]
}
```
Logfile on start:
```
Loading 2 platforms...
  [undefined] Initializing YamahaAVR platform...
  [undefined] Getting Yamaha AVR devices.
  [KNX] Initializing KNX platform...
  [KNX] Fetching KNX devices.
  [KNX] parsing acc 0 of 1
  [KNX] push new universal device Werkstatt
  [KNX] Accessory constructor called
  [KNX] created Werkstatt universal accessory
  [KNX] returning 1 accessories
  [KNX] Initializing platform accessory 'Werkstatt'...
  [KNX] Preparing Services: 3
  [KNX] Preparing Service: 0 of type Lightbulb
  [KNX] Lightbulb on/off characteristic enabled
  [KNX] knx registering BOOLEAN 1/1/1
  [KNX] Issuing read requests on the KNX bus...
  [KNX] Preparing Service: 1 of type Lightbulb
  [KNX] Lightbulb on/off characteristic enabled
  [KNX] knx registering BOOLEAN 1/1/2
  [KNX] Issuing read requests on the KNX bus...
  [KNX] Preparing Service: 2 of type Thermostat
  [KNX] Thermostat CurrentTemperature characteristic enabled
  [KNX] knx registering FLOAT ,1/1/10
  [KNX] Issuing read requests on the KNX bus...
  >>> knxd groupsocketlisten starting <<<
  [KNX] knx request sent for 1/1/1
  [KNX] knx request sent for 1/1/2
  [KNX] knx request sent for 1/1/10
  [undefined] Waited 30 seconds, stopping discovery.
  [undefined] Discovery finished, found 0 Yamaha AVR devices.
```

thx Neo

**Comment by SphtKr** [comment]
Hmm...well, there are a few possibilities. Could be a Bonjour problem or could be it's just taking too long.

First, try adding a `discovery_timeout` entry to your config, go for 120 seconds or something to make sure that's not the problem:

            {
               "platform": "YamahaAVR",
               "play_volume": -48,
               "setMainInputTo": "Tuner",
               "discovery_timeout": 120
             },

If that still doesn't work, I'm curious if your RPi can see the Bonjour broadcasts of the AVR. Run this:

    pi@longsword ~ $ avahi-browse _http._tcp
    +   eth0 IPv4 Main Speakers                                 Web Site             local
    +   eth0 IPv4 HP LaserJet M1536dnf MFP (61865D)             Web Site             local
    +   eth0 IPv4 Game Room                                     Web Site             local

If you don't have `avahi-browse`, you may need to `sudo apt-get install avahi-utils` first. See if your AVR shows up in that list from your RPi. If not, Bonjour broadcast isn't working between the AVR and the RPi, which is more common than you might think.

**Comment by neonightmare** [comment]
Hi, I've tested the discovery_timout, nothing recognized

Seems to be a problem with Bonjour, only the printer was detected:
```
pi@raspberrypi ~ $ avahi-browse _http._tcp
-bash: avahi-browse: Kommando nicht gefunden.
pi@raspberrypi ~ $ sudo apt-get install avahi-utils
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
Die folgenden NEUEN Pakete werden installiert:
  avahi-utils
0 aktualisiert, 1 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
Es müssen 55.8 kB an Archiven heruntergeladen werden.
Nach dieser Operation werden 142 kB Plattenplatz zusätzlich benutzt.
Holen: 1 http://mirrordirector.raspbian.org/raspbian/ wheezy/main avahi-utils armhf 0.6.31-2 [55.8 kB]
Es wurden 55.8 kB in 0 s geholt (144 kB/s).
Vormals nicht ausgewähltes Paket avahi-utils wird gewählt.
(Lese Datenbank ... 80097 Dateien und Verzeichnisse sind derzeit installiert.)
Entpacken von avahi-utils (aus .../avahi-utils_0.6.31-2_armhf.deb) ...
Trigger für man-db werden verarbeitet ...
avahi-utils (0.6.31-2) wird eingerichtet ...
pi@raspberrypi ~ $ avahi-browse _http._tcp
+   eth0 IPv4 HP LaserJet M1120n MFP                        Web-Angebot          local


^CGot SIGINT, quitting.
pi@raspberrypi ~ $ avahi-browse _http._tcp
+   eth0 IPv4 HP LaserJet M1120n MFP                        Web-Angebot          local
^CGot SIGINT, quitting.
pi@raspberrypi ~ $
```
A restart (supply off) of the Yamaha was also useless..

any suggestions to get the Bonjour between Yamaha and RPI2 to work?
thx Neo

**Comment by snowdd1** [comment]
@neonightmare  
-  are you sure the broadcast functionality in your receiver is turned on?
-  what Kind of Network infrastructure elements do you have between the Yamaha and the PI? Access Points, Switches, hubs etc. How is the PI connected to the Network?

**Comment by SphtKr** [comment]
I also may add the ability to specify an IP...the app has the ability to do so specifically for this reason. 

But yes, the interesting question is that what is different network wise between your AVR and RPi vs. between your AVR and your phone/app...I assume by the way that the app automatically discovers the AVR and you didn't have to specify its IP there?

**Comment by neonightmare** [comment]
Hi there
Checked:
-> Network StandBy is on
-> on iPhone deleted recognized IP from AVR -> new search -> found and OK

my network

modem/router (WLAN1) -> cisco-switch SLM2024 -> LAN to AVR
                                                                -> LAN to RPi
                                                               -> LAN to Airport Express "WLAN2"

Iphone/Ipad is connected via WLAN1 and WLAN2 working both (detection and use of App)
I am trying now to upgrade the firmware on my switch...

thx so far, any other suggestions?

**Comment by SphtKr** [comment]
Okay, odd. I double-checked and your model is on the compatibility list for the app I'm using, so I'm assuming you're running the same app, and therefore assuming all the protocols are the same. A lot of assuming, but not having the same AVR model I have little choice. What I can be certain of is that if the RPi doesn't see a bonjour broadcast from it then the current code will do nothing. 

If, in fact, the protocols are the same, I can add a manual IP option and it should work. I can take a crack at that in the next day or two, it should be pretty easy. Can you try a branch when I commit one, or do you need it in master? (That is, how comfortable are you with git?)

**Comment by neonightmare** [comment]
Hi, thx for the explanation... I can try a branch (I suppose i can learn this) git i use for my Arduino projects...

**Comment by SphtKr** [comment]
Okay, can you try [this branch I just published](https://github.com/SphtKr/homebridge/tree/yamahaavr-manual-ip)? You can use the "Download ZIP" button to the right, I think, if that's easier. In your `config.json`, add something like this:

            "platform": "YamahaAVR",
            "play_volume": -35,
            "setMainInputTo": "AirPlay",
            "manual_addresses": {
                "Yamaha": "192.168.1.67"
            }
 
The key is the name and the address is an IP or theoretically a DNS name. Give that a shot and see if it finds your device.

**Comment by neonightmare** [comment]
Cool, AVR detected and working! 

@SphtKr Big THX

**Comment by SphtKr** [comment]
Great, I'll submit a pull request and get it into the main codebase! Thanks!
