### ISSUE TITLE
Type Error crashes home bridge on start.

### ISSUE THREAD

**Issue by iRayanKhan** [nfarina/homebridge#2240]
Hello, I just got a new Pi and am only trying to put homebridge-camera-ffmpeg on it with no success.

I get this error with my config (posted below)
# Error
pi@raspberrypi:~/.homebridge $ homebridge
[2019-6-18 10:16:11] Loaded config.json with 1 accessories and 1 platforms.
[2019-6-18 10:16:11] ---
[2019-6-18 10:16:13] Loaded plugin: homebridge-camera-ffmpeg
[2019-6-18 10:16:13] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
[2019-6-18 10:16:13] ---
[2019-6-18 10:16:13] Loading 1 platforms...
[2019-6-18 10:16:13] [Camera-ffmpeg] Initializing Camera-ffmpeg platform...
[2019-6-18 10:16:13] Loading 1 accessories...
[2019-6-18 10:16:13] TypeError: Cannot read property 'indexOf' of undefined
    at API.accessory (/usr/local/lib/node_modules/homebridge/lib/api.js:50:12)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:297:42)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:91:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
[2019-6-18 10:16:13] Got SIGTERM, shutting down Homebridge...

# Config
~~~
{
        "bridge": {
                "name": "Homebridge",
                "username": "CC:22:3D:E3:CE:30",
                "port": 51826,
                "pin": "031-45-154"
        },

        "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you$
        "ports": {
                "start": 52100,
                "end": 52150,
                "comment": "This section is used to control the range of ports that separate accessory (like camera or television) should be bind to."
        },
        "accessories": [{

        }],

        "platforms": [{
                "platform": "Camera-ffmpeg",
                "cameras": [{
                        "name": "Camera Name",
                        "videoConfig": {
                                "source": "-re -i rtsp://myfancy_rtsp_stream",
                                "maxStreams": 2,
                                "maxWidth": 1280,
                                "maxHeight": 720,
                                "maxFPS": 30
                        }
                }]
        }]
}
~~~

**Comment by mafyata** [comment]
There is a problem with your config.json
Check it at config.json

**Comment by mafyata** [comment]
I checked it. Just delete:
 "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you$

**Comment by iRayanKhan** [comment]
@mafyata Thanks for the reply. This did not end up working for me.. 
I also tried a config from my other home bridge setups and they also fail on this machine, I will try to wipe the Pi and start again and hope it was just a install error.

**Comment by mafyata** [comment]
If you want I can send you txt file with comands for installing homebridge , nodejs and set it to start with system startup. Just copy/paste commands.

**Comment by iRayanKhan** [comment]
Yes please. Could you also link a FFMPEG install guide for Homebridge-Camera-FFMPEG

**Comment by mafyata** [comment]
Which OS are you using ? With Desktop or no ?

**Comment by iRayanKhan** [comment]
Stretch Lite (No Desktop) I just got home bridge installed and found the FFMpeg install guide so I'm doin that currently.

**Comment by mafyata** [comment]
###sudo apt-get install curl - if curl command don't work
sudo su
curl -sL https://deb.nodesource.com/setup_10.x | bash -
sudo apt-get install -y nodejs
node -v
apt-get install libavahi-compat-libdnssd-dev
npm install -g --unsafe-perm homebridge

**Comment by mafyata** [comment]
This is for installing nodejs 10.16.0 and homebridge.

**Comment by iRayanKhan** [comment]
Cheers, gonna try it out :D

**Comment by mafyata** [comment]
after that you must create config.json

**Comment by mafyata** [comment]
cat >/var/lib/homebridge/config.json <<EOL
{
    "bridge": {
        "name": "Homebridge",
        "username": "CB:22:3D:E2:CE:31",
        "port": 51826,
        "pin": "033-44-254"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8080,
            "auth": "form",
            "theme": "teal",
            "restart": "sudo -n systemctl restart homebridge",
            "tempUnits": "c",
            "sudo": true,
            "log": {
                "method": "systemd"
            },
            "platform": "config"
        }
    ]
}
EOL

**Comment by mafyata** [comment]
Change parameters for your config

**Comment by iRayanKhan** [comment]
@mafyata Thanks so much for the help I got it all working!
