### ISSUE TITLE
Can not read property username

### ISSUE THREAD

**Issue by Steffenni** [nfarina/homebridge#2245]
![image](https://user-images.githubusercontent.com/32431895/59975781-2d6cb500-95bc-11e9-8243-13b8ca0b45fc.jpg)

What to do?

**Comment by ebaauw** [comment]
Fix your config.json

**Comment by Steffenni** [comment]
I dont know how. I am all new in this. 
I tested the Config.json on jsonlint.com and it Said it was ok?

**Comment by aswathraja** [comment]
Can you please post your config.json file?
  

  
  

  
  
>

**Comment by Steffenni** [comment]
{
	"accessories": [{
		"accessory": "webostv",
		"name": "Tv stue",
		"ip": "",
		"mac": "",
		"keyFile": "/home/pi/.homebridge/lgtvKeyFile",
		"pollingInterval": 10,
		"inputs": [{
				"appId": "com.webos.app.livetv",
				"name": "Live TV"
			},
			{
				"appId": "com.webos.app.hdmi1",
				"name": "Apple tv"
			},
			{
				"appId": "com.webos.app.hdmi4",
				"name": "Playstation"
			}
		],
		"showInputButtons": true,
		"volumeControl": "buttons",
		"channelControl": false,
		"mediaControl": false,
		"channelButtons": [3, 5, 7, 8],
		"notificationButtons": [
			"Motion detected - living room",
			"Motion detected - kitchen"
		],
		"remoteControlButtons": [
			"HOME",
			"LIST",
			"EXIT"
		],
		"soundOutputButtons": [
			"tv_speaker",
			"external_optical",
			"headphone"
		],
		"remoteSequenceButtons": [{
				"sequence": ["HOME", "RIGHT", "RIGHT", "RIGHT", "ENTER"],
				"name": "screen_share_seq"
			},
			{
				"sequence": ["VOLUMEUP", "VOLUMEDOWN", "MUTE", "MUTE"],
				"name": "volume_seq",
				"interval": 1000
			}
		]
	}]
}

**Comment by Steffenni** [comment]
I have IP adress and mac dress of course, just deleted it in this post.

**Comment by ebaauw** [comment]
The `"bridge"` part is missing.  See [`config-sample.json`](https://github.com/nfarina/homebridge/blob/master/config-sample.json).

**Comment by Steffenni** [comment]
So the first 7 lines?

**Comment by mafyata** [comment]
{
  "bridge": {
    "name": "Homebridge",
    "username": "CC:22:3D:E3:CE:30",
    "port": 51826,
    "pin": "031-45-154"
  },
  This is missing and there must be the problem.

**Comment by mafyata** [comment]
For example :
![290A20C1-466F-450B-81B1-7D5951CE9078](https://user-images.githubusercontent.com/48009267/59976562-d9b79700-95ce-11e9-9bb7-ac39b3727f2d.jpeg)

**Comment by aswathraja** [comment]
Please replace the confidential credentials needed  below. 
{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},
	"accessories": [{
		"accessory": "webostv",
		"name": "Tv stue",
		"ip": "",
		"mac": "",
		"keyFile": "/home/pi/.homebridge/lgtvKeyFile",
		"pollingInterval": 10,
		"inputs": [{
				"appId": "com.webos.app.livetv",
				"name": "Live TV"
			},
			{
				"appId": "com.webos.app.hdmi1",
				"name": "Apple tv"
			},
			{
				"appId": "com.webos.app.hdmi4",
				"name": "Playstation"
			}
		],
		"showInputButtons": true,
		"volumeControl": "buttons",
		"channelControl": false,
		"mediaControl": false,
		"channelButtons": [3, 5, 7, 8],
		"notificationButtons": [
			"Motion detected - living room",
			"Motion detected - kitchen"
		],
		"remoteControlButtons": [
			"HOME",
			"LIST",
			"EXIT"
		],
		"soundOutputButtons": [
			"tv_speaker",
			"external_optical",
			"headphone"
		],
		"remoteSequenceButtons": [{
				"sequence": ["HOME", "RIGHT", "RIGHT", "RIGHT", "ENTER"],
				"name": "screen_share_seq"
			},
			{
				"sequence": ["VOLUMEUP", "VOLUMEDOWN", "MUTE", "MUTE"],
				"name": "volume_seq",
				"interval": 1000
			}
		]
	}]
}

**Comment by Steffenni** [comment]
Thank you. That works.
