### ISSUE TITLE
Will Homebridge run better on beefier hardware?

### ISSUE THREAD

**Issue by Yardco** [nfarina/homebridge#2246]
I'm currently running homebridge on a RaspberryPi 3B and am wondering if switching to something more powerful will have a positive effect on performance? 

Im noticing for example when opening a camera feed (provided by the homebridge-camera-ffmpeg plugin) that starting the feed takes about 5/10 seconds whereas when using the VLC app, the feed starts almost instantly. 

Will behavior like this improve when switching from a raspberry pi to something beefier?

**Comment by mafyata** [comment]
Today released raspberry pi 4B with 4GB ram.

**Comment by Yardco** [comment]
Im not specifically revering to the newly released raspi 4, but to more powerful hardware in general.
