### ISSUE TITLE
Can you improve the documentation?

### ISSUE THREAD

**Issue by a-x-** [nfarina/homebridge#2247]
Hey,
Thank you for a good product!

Can you make clearer some details in the documentation?

For example

What user should write to accessories config for example?

Is `accessories.*.accessory` for some standard names user should copy from?
Is `accessories.*.name` should be uniq for single homebridge instance?
What are platforms, though? ;)

Add please link to wiki to readme. You know, Many of repos has empty Wiki enabled by default.

**Comment by a-x-** [comment]
Also, can you create homebridge-awesome with featured plugins in categories and with basic plugins?

**Comment by a-x-** [comment]
I understand now, that accessories.*.accessory should be taken from some plugin config
e.g. GPIODevice from homebridge-gpio-device

but I'm WTFing here every time I getting started with homebridge again

**Comment by mafyata** [comment]
No , he can’t create homebridge-awesome ......
Homebridge is like os,windows,linux. Plugins are like programs. You install programs on your computer which you need, so and the plugins, everyone install plugins that need. Owner of homebridge program is not writing plugins, everyone who want can write plugin for homebridge.
I think you can understand me.

**Comment by a-x-** [comment]
Apple features good programs in its App Store

**Comment by shamasis** [comment]
I second this. I’ve been trying to build a lot of home bridge plugins. My only source of documentation is reading other plugins. I’m not asking about simple how-to. I’m looking for simple lists ... what are the characteristics available, what are the services, etc. Guess, it’s time to read homebridge code to find that. 😞

**Comment by shamasis** [comment]
Also ... for those lists https://github.com/KhaosT/HAP-NodeJS code is the best source.
