### ISSUE TITLE
Home Bridge - Got SIGTERM, shutting down Homebridge

### ISSUE THREAD

**Issue by eugeneshortall** [nfarina/homebridge#2248]
### Versions

- **Homebridge**: `homebridge --version`
- **Node**:       `node --version`
- **OS**:         

### Configuration

```json

```

### Homebridge Log / Command Output

```

```

**Comment by eugeneshortall** [comment]
Using Mac Mojave
I Know nothing about programming, for Terminal I copy text given by those kinds persons who take the time to explain to idiots like me what to do. I have previous experience with X10 and Isteon in the USA. Now in europe and need to set up a system in a large house and have decided on WiFi with the occasional rf Bridge (Sonoff + others) where necessary.
I now need to find a MAC based interface so that i can programme and set scenes.
I have installed Home Bridge as described elsewhere on this site and it appears to have installed correctly although I am getting what look like error messages and finally a logout. 
"Got Sigterm, shutting down Homebridge..."

I have researched this message but can not find anything that appears to relate to my system.
I am currently using Apple TV4K Homekit as a HUB. Tried Pi but despite every effort, it was way beyond my limited comprehension.

Can some kind person please advise me what I can do to make this stable as I hope it will allow communication between the Homekit etc.

Thanks,

Eugene
[Terminal Print.pdf](https://github.com/nfarina/homebridge/files/3329852/Terminal.Print.pdf)

**Comment by MulderDSM** [comment]
I am now receiving this same error.
