### ISSUE TITLE
Plugin Request: Aladdin Connect Garage Door

### ISSUE THREAD

**Issue by Jborn4christ** [nfarina/homebridge#2252]
Would love to see a plugin that works for Aladdin Connect Genie garage doors now that they’ve opened up their api. The one that is available does not work, and the dev is useless from a support standpoint. I’d $$ for a working one with clear instructions.

**Comment by iAnatoly** [comment]
Try this one: https://www.npmjs.com/package/homebridge-aladdin-connect-garage-door , I am using it myself.

**Comment by Jborn4christ** [comment]
Yep. Got it working.
