### ISSUE TITLE
Question: How do I report accessory not responding?

### ISSUE THREAD

**Issue by dinmammas** [nfarina/homebridge#2256]
Hello!

I have a plugin that relies on a JSON service on robotic lawnmowers. As a lawnmower is sometimes out of range, I need a way to report "not responding" to Homebridge/Homekit, as I'd prefer not just reporting default values.

Is there a way?

Best,
David

**Comment by NorthernMan54** [comment]
Take a read of this

https://github.com/KhaosT/HAP-NodeJS/pull/556

**Comment by dinmammas** [comment]
Thank you! Very helpful. <3
