### ISSUE TITLE
Confusion over accessory registration

### ISSUE THREAD

**Issue by RMCob** [nfarina/homebridge#2257]
According to /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/README.md,
the accessories defined in /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/accessories are automatically loaded when hap-nodejs is started. My assumption was that I could simply add:
    "accessories": [
         {
            "accessory": "Airconditioner_accessory",
            "name": "FAKE AC"
         }
     ]
and it would show up. Instead I got the error msg that "Airconditioner_accessory" was not registered by any plugin. My reason for wanting to use this particular version of air conditioner accessory as a starting point is that its the only one I've seen so far that had controls for on/off, mode, temperature, AND fan speed.

Any pointers to documentation explaining how to 'register' this accessory would be greatly appreciated. Thanks!

**Comment by iRayanKhan** [comment]
Hello, 
HomeBridge reads the ```accessory``` characteristic from a plugin. You would need to make a plugin called "Airconditioner_accessory" to accomplish this.
