### ISSUE TITLE
Multiple Homebridge instances with PM2

### ISSUE THREAD

**Issue by sebasanblas** [nfarina/homebridge#2258]
Hi! I've been using homebridge successfully using PM2 to auto start. Now I wanted to use multiple homebridges and apply pm2 as well. Would someone be so kind as to tell me how to do this process? I've been looking but I don't know which homebridge files to duplicate or how to use pm2 with a second bridge. I appreciate any help.

**Comment by knaackville** [comment]
I've been trying to do this as well for the past few days.  I've created a homebridge.config.js in /home/pi  and have been trying to run pm2 start homebridge.config.js.  PM2 will start things and say they're "online", but essentially restarts them continuously.   Each folder in the "args" section has its own config.json file for each plugin, specifically only whitelisting that plugin.  Each individual instance works on its own running "homebridge -U /home/pi/.homebridge/XXXXX" perfectly either individually or in different terminal windows.  

Homebridge.config.js file:

'module.exports = {
  "apps": [
    {
      "script": "/usr/lib/node_modules/homebridge/bin/homebridge",
      "name": "Homebridge-Alarm",
      "args": [ "-U /home/pi/.homebridge/alarmdotcom" ]
    },
    {
      "script": "/usr/lib/node_modules/homebridge/bin/homebridge",
      "name": "Homebridge-HomeSeer",
      "args": [ "-U /home/pi/.homebridge/homeseer" ]
    },
    {
      "script": "/usr/lib/node_modules/homebridge/bin/homebridge",
      "name": "Homebridge-DysonFan",
      "args": [ "-U /home/pi/.homebridge/dysonfan" ]
    }
  ]
}
'

The log file shows the following:

`  Usage: ProcessContainerFork [options]

  Options:

    -h, --help                      output usage information
    -V, --version                   output the version number
    -C, --color                     force color in logging
    -D, --debug                     turn on debug level logging
    -I, --insecure                  allow unauthenticated requests (for easier hacking)
    -P, --plugin-path [path]        look for plugins installed at [path] as well as the default locations ([path] can also point to a single plugin)
    -Q, --no-qrcode                 do not issue QRcode in logging
    -R, --remove-orphans            remove cached accessories for which plugin is not loaded
    -T, --no-timestamp              do not issue timestamps in logging
    -U, --user-storage-path [path]  look for homebridge user files at [path] instead of the default location (~/.homebridge)

It seems like each argument isn't being sent on to homebridge, but I'm relatively new to setting up multiple instances.  Anyone have any thoughts?

**Comment by sebasanblas** [comment]
I did it! Let me write it like I did and I'll soon write it here!

**Comment by knaackville** [comment]
I was able to get this to work as well, in an easier fashion than my earlier post.  I made each instance have a new folder in the /home/pi/Desktop/Homebridge directory with individual config.json files.  The key for those config files is whitelisting the plugins you want to use in each instance (plugins section in the config), along with having a different name, username, and port for each instance as well.  An example is below for the node-alarm-dot-com plugin.

Then to run it in pm2, I ran the following command:
pm2 start homebridge --name Homebridge-Alarmdotcom -- -U ./.homebridge/alarmdotcom

Just repeat for each instance that you need, changing the name and location of the config file.  Hope that helps someone in the future!

Sample config to whitelist the plugins for each instance.
`{
	"bridge": {
		"name": "Homebridge Alarmdotcom",
		"username": "BC:44:3D:E3:3E:12",
		"port": 51829,
		"pin": "987-65-432"
	},
	"description": "Homebridge config stuff",
	"plugins": [
		"homebridge-node-alarm-dot-com"
	],
	"platforms": [
		{
			"platform": "Alarmdotcom",
			"name": "Security System",
			"username": "XXXXXXXXXXX",
			"password": "XXXXXXXXXXX",
			"armingModes": {
				"away": {
					"noEntryDelay": false,
					"silentArming": false
				},
				"night": {
					"noEntryDelay": false,
					"silentArming": false
				},
				"stay": {
					"noEntryDelay": false,
					"silentArming": false
				}
			},
			"logLevel": 3
		}
	]
}
