### ISSUE TITLE
incorrect ranges can corrupt homekit database and disable homebridge accessories

### ISSUE THREAD

**Issue by karlg100** [nfarina/homebridge#2261]
### Pre Steps
define a homebridge plugin device such as temperature device. then set the Max temp below the Min temp using SetProps().

### Expected Behavior
Ignore the device, throw an error, otherwise do not register the device with these values with homekit and foobar the database.  Perhaps mark this plugin/device as no responsive.

### Current Behavior
Blindly accepts invalid values.  upon start of homebridge, all your homebridge accessories will become "no response" and there is no recovery -  Removing the offending plugin's config.json section and restarting homebridge, devices still not responsive.  

Removing the offending plugin all together and restart, devices still not responsive.  

Even removing the bridge device does not allow it to be reregistered with the same username, the user name must be changed in the config.json.

Only resolution is to remove the homebridge device in the Home app, change the username in the config.json, add it as a new device and reconfigure ALL your scenes, rules, automation.

### Steps to Reproduce (for bugs)

```
service = new Service.TemperatureSensor(this.name);
service
      .getCharacteristic(Characteristic.CurrentTemperature)
      .setProps({
        minValue: -256,
        maxValue: -512 // you are screwed if you start with this value!
      })
      .on('get', this.getDefaultValue.bind(this));
```

if these values are taken from user input, or otherwise checked, user can foobar themselves.

### Versions

- **Homebridge**: 0.4.50
- **Node**:       v8.11.1
- **OS**:         Raspbian GNU/Linux 9.9 (stretch)

**Comment by KhaosT** [comment]
I feel this is more of a plugin implementation error. If the plugin decided to accept arbitrary user input values, it's up to the plugin to validate those values. If you believe otherwise, please file an issue at https://github.com/KhaosT/HAP-NodeJS/ for the underlying HAP library.

**Comment by karlg100** [comment]
While I do agree, I do feel otherwise.  This is a pretty bad corruption bug that likely the root issue should be addressed by apple, but given this is a 3rd party app, at least in the HAP library, something should be done to prevent a plugin from creating a denial of service.
