### ISSUE TITLE
config.json

### ISSUE THREAD

**Issue by eugeneshortall** [nfarina/homebridge#2265]
I am a total newbie at this and have spent days trying to figure it out. I have sonoff devices working through eWelink, I want to use them with Apple Home as a trial. I have set up Homebridge but cannot get the Config.json file to work. I have used https://jsonlint.com/ to validate the file, adding sections one at a time. I found several errors on the samples publish on the web but have now got to the stage of adding the platforms when get error 
"Error: Parse error on line 19:
...d be bind to."	}	"platforms": [{		"p--------------------^ Expecting 'EOF', '}', ',', ']', got 'STRING'"

I have pasted the eWelink paltfom info as per the publish instructions.

Please help, what is wrong with my file.

Thanks in advance,
Eugene

CONFIG.JSON FILE
_______________________________________________________________________________________________

{
  "mdns": {"interface": "192.168.1.34"},

  
  "bridge": {
    "name": "Homebridge",
    "username": "B8:09:8A:CD:85:19",
    "port": 51826,
    "pin": "123-12-123"
},

"description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",
  "ports": {
    "start": 52100,
    "end": 52300,
    "comment": "This section is used to control the range of ports that separate accessory (like camera or television) should be bind to."
}

"platforms": [
        {
        "platform" : "eWeLink",
            "name" : "eWeLink",
            "email" : "XXXXXXXXXXXl@gmail.com",
            "password" : "XXXXXXXX",
            "imei" : "0D1A1B1D-848D-45B5-8D47-EB0DFFA8BF86"
        }
    ]

"accessories": [
    {
          "accessory": "Relay",
          "name": "CASCADE",
          "ip_address": "192.168.1.67"
        },
        {
          "accessory": "Relay"
          "name": "Sonoff",
          "name": "LIONS",
          "hostname": "192.168.1.26"
          }
        ]
  ]

**Comment by davipt** [comment]
`{
  "mdns": {
    "interface": "192.168.1.34"
  },
  "bridge": {
    "name": "Homebridge",
    "username": "B8:09:8A:CD:85:19",
    "port": 51826,
    "pin": "123-12-123"
  },
  "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",
  "ports": {
    "start": 52100,
    "end": 52300,
    "comment": "This section is used to control the range of ports that separate accessory (like camera or television) should be bind to."
  },
  "platforms": [
    {
      "platform": "eWeLink",
      "name": "eWeLink",
      "email": "XXXXXXXXXXXl@gmail.com",
      "password": "XXXXXXXX",
      "imei": "0D1A1B1D-848D-45B5-8D47-EB0DFFA8BF86"
    }
  ],
  "accessories": [
    {
      "accessory": "Relay",
      "name": "CASCADE",
      "ip_address": "192.168.1.67"
    },
    {
      "accessory": "Relay",
      "name": "LIONS",
      "hostname": "192.168.1.26"
    }
  ]
}
`

You were missing some commas, and the proper "}" at the end.

Grab the "jq" binary file from https://stedolan.github.io/jq/download/

**Comment by eugeneshortall** [comment]
Thank you so much for your help, I still have not recognised what was missing but it loaded. 

I really need to find a consultant, someone I can pay, to help me set up systems in my house. It is a very large stone build, we have 17 access points and I have decided the only thing that will work is WiFi.

Once again many thanks,

R,

Eugene


Chateau de la Dorée
Route du Noble Jouée
Esvres sur Indre
37320 FRANCE

M +33 (0) 6 70 16 80 48

Email: eugene.shortall@gmail.com

On 22 Jul 2019, at 15:29, Bruno D. Rodrigues <notifications@github.com> wrote:

{ "mdns": { "interface": "192.168.1.34" }, "bridge": { "name": "Homebridge", "username": "B8:09:8A:CD:85:19", "port": 51826, "pin": "123-12-123" }, "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.", "ports": { "start": 52100, "end": 52300, "comment": "This section is used to control the range of ports that separate accessory (like camera or television) should be bind to." }, "platforms": [ { "platform": "eWeLink", "name": "eWeLink", "email": "XXXXXXXXXXXl@gmail.com", "password": "XXXXXXXX", "imei": "0D1A1B1D-848D-45B5-8D47-EB0DFFA8BF86" } ], "accessories": [ { "accessory": "Relay", "name": "CASCADE", "ip_address": "192.168.1.67" }, { "accessory": "Relay", "name": "LIONS", "hostname": "192.168.1.26" } ] }

You were missing some commas, and the proper "}" at the end.

Grab the "jq" binary file from https://stedolan.github.io/jq/download/ <https://stedolan.github.io/jq/download/>

**Comment by mafyata** [comment]
For sonoff devices I am using ravencore firmware. It is working with homekit , no need of homebridge.
