### ISSUE TITLE
Homebridge no response after idling for a few hours

### ISSUE THREAD

**Issue by halfcherry** [nfarina/homebridge#2267]
My setup:
Apple TV as hub
Homebridge running in Synology docker
Only Fibaro HC2 and web UI plugin

I've gone through pretty much every topic related to "homebridge no response", but mine seems a bit different.

My homebridge and all it's accessories only becomes "no response" after idling(no action or trigger) for a couple of hours, but once I turn on a light with Fibaro app or trigger a scene(setup in Fibaro HC2) by Fibaro motion sensor, all Homebridge accessories become alive. There is nothing out of ordinary in the log, the only activities between last trigger and "no response" are the motion sensor updating Lux level and temperature around every 20 minutes depending on the weather. 
Based on my observations, it seems like something in the middle fell asleep while idling, what could it be? How do I pin point it? Or could it be something else?

**Comment by dpyy** [comment]
Do you have a mac? I have a similar thing but loading the home app in the mac wakes it up

**Comment by halfcherry** [comment]
I don't have a mac unfortunately. But after tinkering with lots of options in my Ubiquiti Gateway which made no difference, I switched back to my old Asus AC68u, it's been running fine for the past 12 hours. We shall see how long this can last and I will report back.

**Comment by dpyy** [comment]
Did you always have this problem or did it recently come up? Mine only started last week

**Comment by halfcherry** [comment]
I had it setup 6 months ago but never really used it much, during the occasional use, I never had any problem. Last months I replaced my Asus router with Unifi USG, and 3 days ago, I started experimenting a variety of smart home devices which is why I started noticing this probelm. But since I plugged my old Asus router back, it's been running withou issue for nearly 24 hours.
According to logs, my issue was when HB  first starts, Home hub(in my case Apple TV 4) establishes a connection with other iOS devices on HB port. As time goes on, that socket goes stale for some reason I haven't figured out, hence no response. Most likely it's something to do with router settings. I changed a bunch of setting both via the Ubiquiti controller and ssh but didn't work.
