### ISSUE TITLE
Stuck in updating at random times but if I open home app from mac it unlocks it

### ISSUE THREAD

**Issue by dpyy** [nfarina/homebridge#2268]
I have the most weird issue with homebridge. 

I've been running the same config for over a year everything works great. But started last week, the accessories started freezing at "updating" at random times. Then for some reason if I open the home app on the mac, it unfreezes it. Then all the iOS devices can see it again. 

But after a while, it would freeze again. 

I checked the logs, theres nothing. 

How do I troubleshoot this?

Running latest version of macOS and homebridge.

**Comment by royale56** [comment]
I’m having a similar issue when my accessories are showing as “updating” in the home app but when I go to control any homebridge accessory via my HomePod it works perfectly. 

I notice that some of the accessories will occasionally connect in the home app but as soon as I try to turn it on/off etc it will go back to updating. The HomePod seems to work every time though. 

No errors or any issues in terminal.

**Comment by afharo** [comment]
Is your mac going to sleep? If so, you can try https://apps.apple.com/us/app/amphetamine/id937984704?mt=12 to avoid your mac from going to sleep
