### ISSUE TITLE
SmartThings shades, fans, and locks

### ISSUE THREAD

**Issue by A5HRAJ** [nfarina/homebridge#227]
Window shades and fan controllers both show up in HomeBridge as dimmable lights, and locks don't show up at all. Does anyone know how to implement support for these device types in the SmartThings shim? HomeKit supports all of them in iOS 9.

**Comment by humac** [comment]
I'd like to see the smartthings plugin updated to expose more device types as well. Garage doors, shades, locks, contact sensors, pretty much anything that HomeKit supports that is connected via ST would be awesome.  Only if my dev skills were better I'd try to tackle this.  Maybe I'll give it a shot if someone doesn't come along and doit faster and better :)

**Comment by webxl** [comment]
And thermostats! Looks like adding some of this https://github.com/luigifreitas/homebridge-http-thermostat/blob/master/index.js (in a smartthings manner) to https://github.com/nfarina/homebridge-legacy-plugins/blob/master/platforms/SmartThings.js should do it. I'm trying it right now

**Comment by pdlove** [comment]
By February, I expect to write a complete smartthings platform plugin similar to what I'm doing now to finish out the wink plugin. I'm going to likely create the repository this weekend. The only ones I currently see under "homebridge-smartthings" are woefully inadequate. Is anyone else interested in a more complete plugin for this platform?

**Comment by foxxyben** [comment]
I will be more than happy to help test and provide feedback for a smartthings plugin. My coding skills are woefully inadequate, but I will do what I can there as well.

**Comment by humac** [comment]
@pdlove I would definitely like to see a more complete plugin.  Also a lot of the iOS users in the SmartThings community would welcome this as well i bet.

**Comment by miabilabs** [comment]
@pdlove I'd like to 3rd the desire for a more complete SmartThings plugin. I signed up for github just to tell you! And agreed, the SmartThings community would welcome it as well. Please let me know if I can help test, provide feedback or do whatever you need. Do you need your shoes shined?

**Comment by humac** [comment]
@pdlove sign me up if you need a beta tester :)

**Comment by pdlove** [comment]
Give me a couple of weeks. I'm really disappointed with the API interface for Smart Things, but I think I can accomplish this to work well and be complete. I've created a git hub repository called homebridge-smartthings. There are some others called that, but they're not current or anywhere near complete.

**Comment by rickysmartthings** [comment]
Likewise, I'd love to test this out. I'm using the legacy plugin now, which works, but having everything appropriately categorized would be fantastic.

**Comment by miabilabs** [comment]
Another thing I've noticed is that the eve app does not accurately report the brightness of your devices. Mine are all pinned to 0% regardless of if they're on or not. 

Not sure if this can be addressed in the plugin or if it's a limitation of homebridge itself. 

This would be a nice to have. It's a minor annoyance and frankly I'm not in the Eve app often. It's all Siri.

**Comment by pdlove** [comment]
When you have your lights at full brightness, does it change to 1%?
If so then the current plugin is passing 0.5 instead of 50 for 50%.
I had this issue initially when I worked on the homebridge-wink and can definitely overcome it.

**Comment by miabilabs** [comment]
They just all stay at 0% regardless. 

It may also be the fact that the smartapp generating the json out of Smartthings is categorizing everything as "switches". 

I suppose that smartapp will need to be updated as well to take advantage of a new plugin.

**Comment by humac** [comment]
Yeah i've noticed anything registered as a dimmable device doesn't actually dim. You see the setLevel command get sent buck nothing happens.

**Comment by miabilabs** [comment]
This may be a general Homekit question, but I'm curious if it's possible to ask Siri what the current temperature is at a specific thermostat or temp sensor? This would be a cool feature to have, particularly within the Smartthings plugin, because many of us are using generic zwave thermostats (a CT100 for example) that aren't nearly as smart as the Nest or Ecobee3.

So the use case is:
*Hey Siri, What is the temperature at the downstairs thermostat?
or 
Hey Siri, What is the current temperature in the family room?*

So ultimately you can say:
*Hey Siri, raise the temperature to 73 degrees.*

**Comment by rickybloomfield** [comment]
Yes, as long as you can assign the device to a particular room or zone, you can query for the temperature of that room or zone. Works great.

**Comment by miabilabs** [comment]
That's great to hear. Thanks!

**Comment by pdlove** [comment]
I have the first versions of my plugin uploaded. To my knowledge it doesn't have support for Shades or fans. I'll be adding Thermostat Support tonight as well as instructions on how to give me what I need to enable support for devices I don't have. I plan to test and expand it until this coming weekend and then publish to npm. https://github.com/pdlove/homebridge-smartthings

**Comment by rickybloomfield** [comment]
Thanks! I tried to install the JSON Complete API SmartApp, but when I tap publish and try to tap on it within the SmartThings iOS app, the progress indicator spins for half a second, and then nothing happens - I've never seen a SmartApp do that before. Have you seen this?

**Comment by pdlove** [comment]
It looks like I missed a step on the installation instructions. I'm fixing that now. Take a look in about 10 minutes.

**Comment by rickybloomfield** [comment]
Ah, OAuth?

**Comment by Wildcat1** [comment]
Can this support smart vents as well ? These general operate on open/close (on/off), amount of open/close (0 to 100%) report back temp, pressure etc. Thanks

**Comment by AppleTechy** [comment]
@wildcat1 What smart vent do you have? I had been looking into buying one a
while back but now have forgotten all the names of them. :)

**Comment by Wildcat1** [comment]
Keen Smart Vents

**Comment by AppleTechy** [comment]
@wildcat1 Do you like the vent? And I assume you live in AZ due to your
username have you seen improvements in efficiency with the high temp during
the day and low temps at night?

**Comment by Wildcat1** [comment]
Lots of nuance, some quirks and bugs right now. Some efficiency gains but not great yet as not true zoning capability due to limitations in the HW. Great for convenience though and from a comfort in room perspective

**Comment by Wildcat1** [comment]
@pdlove Your new JSON COMPLETE is frickin awesome !!! I cannot say enough good things about this. Installed in replacement of the other excellent JSON smart app which was working very well to this point. This JSON complete of yours take it to another level. Vents although still pulling over as dimmers now can be controlled fully (the only thing I noticed did not show up was pressure reading), temp sensors and motions are pulled through with full info as is the Nest. The net of this is that all of these can be fully triggered using HomeKit apps, trigger on temp sensor reaching a certain level etc. Absolutely phenomenal work here, thank you and now going to work on some nested triggers in HomeKit thanks again to this SmartApp !

**Comment by Wildcat1** [comment]
@pdlove After further testing, I do have one problem I am seeing with the Nest. Specifically until using your smart app I was using the homebridge-nest config by KraigM. That nest integration is still included in my JSON config and uses the dev api. It is bringing the Nest over and allowing full control into HomeKit that way however a lot of the functions like showing current humidity occupant and being able to trigger does not work in that implementation in my testing. However when adding Nest into ST using the device handler created by dianoga 7, I see all the functions and triggerable (word of the week;)) there but it will not actually control that Nest instance in HomeKit, any thoughts on that ? To recap I see 2 instances of Nest in HomeKit now (1 from KraigM implementation and 1 from dianoga7, KraigM allows control in app, dianoga7 handler is not currently).

Hope that makes sense and thanks to all named in this post for their amazing work and contribution to this.

**Comment by Wildcat1** [comment]
@pdlove seeing an issue with latest release where when I toggle a device off in HomeKit, it resets itself back to on and therefore is not a true reflection of device state. In this case trying this on smart vents that show up with on/off and dimmer control for amount of open or close. I reinstalled homebridge, reinstalled your latest 043 release both from NPM, reset keychain and still see this issue. Was not having this problem in your older (041?) release. Any ideas ?

**Comment by Wildcat1** [comment]
@pdlove / All
Seeing a new issue pop up and was wondering if others have seen something similar or had any ideas on how to fix:

error at req:  { [Error: connect EHOSTUNREACH 107.20.201.51:443 - Local (**removed by me from this thread**)]
  code: 'EHOSTUNREACH',
  errno: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '107.20.201.51',
  port: 443 }

**then I also see this**

error at req:  { [Error: getaddrinfo ENOTFOUND graph.api.smartthings.com graph.api.smartthings.com:443]
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'graph.api.smartthings.com',
  host: 'graph.api.smartthings.com',
  port: '443' }

I see this happen after x number of hours of running and at that time is when I also lose access to the SmartThings devices in HomeKit (running through Homebridge). Restart Homebridge and everything works again but wondering what is causing the issues above.

Any help, as always is greatly appreciated

Thanks

WC

**Comment by pdlove** [comment]
The concerning thing to me is that you have to restart homebridge to get it to work again. We have some similar issues posted in the homebridge-smartthings GitHub. I invite you to join there. I'm a bit delayed right now due to IOS 9.3 difficulties, but am still actively attempting to reproduce and resolve issues.

**Comment by Wildcat1** [comment]
@pdlove thanks for the reply. Yes I'm testing on 9.3 and 10.11.4 beta 5 as well. It certainly is strange because Homebridge won't last even 24 hours before I start seeing those issues and although I still am able to access my Nest through it (through the KraigM port) everything else disappears that was brought in via the JSON complete API. It never recovers from the errors I posted until I stop the script and start fresh, then it runs fine again for a few hours before hitting the same problem. Thanks for your help with this, much appreciate the time and effort you have put into this
