### ISSUE TITLE
Plugin Request - Honeywell Home Thermostats

### ISSUE THREAD

**Issue by donavanbecker** [nfarina/homebridge#2270]
Anyone know of a plugin that works with Honeywell home thermostats?

**Comment by d0n4v4nb3ck3r** [comment]
https://developer.honeywell.com

**Comment by iRayanKhan** [comment]
https://github.com/NorthernMan54/homebridge-tcc

**Comment by d0n4v4nb3ck3r** [comment]
that plugin doesn't work for Honeywell-Home Thermostats
