### ISSUE TITLE
Don't have a config.json yet homebridge still starts and runs plugin fine

### ISSUE THREAD

**Issue by dhniels** [nfarina/homebridge#2272]
From the root of the system i ran a find command for config.json and it didnt find anything. In the readme, it says homebridge CANNOT start without a config.json. However, If I run the homebridge command, it starts, says Homebridge is running on port 33055, and loads my homebridge-tp-link-smarthome plugin. Additionally, everything shows up and works as expected in the Home app on my iphone. However, the homebridge-nest plugin doesn't seem to load, as none of those register in my Home app (assuming because theres no config.json - even though the tp-link stuff worked.) 

How is this possible? I'm super confused how homebridge is starting, running, and registering my TP-Link devices with the respective plugin, even though there is no config.json to be found??

(I Installed homebridge, homebridge-nest, and homebridge-tp-link-smarthome with npm install -g)

**Comment by Staubgeborener** [comment]
> How is this possible? 

Simply can't. There has to be a config.json file, even if you use homebridge i.e. with docker. 
How did you search for this? Maybe post your command here.

`$ find / -name "config.json"` maybe also `find / -name "config*.json"`
Use this in your root-folder **/**. 

After a period of using homebridge, i found my config.json in different folders:
`/home/username/homebridge/config/config.json`
`/home/username/**.homebridge**/config/config.json` (keep in mind, that this is a hidden directory)
also fóund some time a homebridge folder in `/var/` or `/var/lib/`.
