### ISSUE TITLE
Mac keeps going to sleep please help

### ISSUE THREAD

**Issue by dpyy** [nfarina/homebridge#2273]
I used to have homebridge running for 3 years just fine. 

But 2 weeks ago, homebridge seems to sleep when idle. The devices goes "updating" until I wake up the mac. 

So to troubleshoot this, I have a brand new homebridge installation, brand new home in Homekit, brand new config file. Brand new macOS. But the problem won't go away. 

I already did sudo systemsetup -setcomputersleep Never

Doesn't help. 

How to fix this?

**Comment by gchokov** [comment]
Install a small app called Caffeine - http://lightheadsw.com/caffeine/
Your mac won't sleep, guaranteed.

**Comment by dpyy** [comment]
It's not the mac per se thats sleeping. 

If I use the 'home' app on macOS, it will wake homebridge

If I go to the computer and load a browser, it will wake homebridge

If I access the homebridge-config-ui-x webpage, it wakes homebridge

I don't understand whats going on

**Comment by davipt** [comment]
Could it be that the latest macOS version is now applying "App Nap" also to command line tools like nodejs? Have you updated macOS over these two weeks, maybe to the latest 10.14.6? Want to try to disable App Nap on your system to see if it solves the issue (search on google), and then maybe consider some way to disable app nap just for the nodejs command?

**Comment by dpyy** [comment]
I've since (for testing) moved homebridge to linux in a vm inside the mac. Maybe the "app nap" is also napping the vm?

**Comment by mafyata** [comment]
Why don’t you buy one cheap Raspberry pi

**Comment by dpyy** [comment]
But I already run homebridge from linux, what would be the difference?

**Comment by davipt** [comment]
> I've since (for testing) moved homebridge to linux in a vm inside the mac. Maybe the "app nap" is also napping the vm?

That would make sense. Lookup for the application that runs your VM, open the info of the app, and check the "Prevent App Nap". See e.g. https://www.lifewire.com/control-how-mac-applications-use-app-nap-2260788

Full mac Apps can be controlled one by one, with this on the GUI, or via command line.

What was confusing me was if macOS could also app nap terminal apps like nodejs… it's not unexpected, but as a beta tester, I can't confirm or deny if that will happen (translation: it's broken to the point that I'm pretty sure it won't happen, and it would make no sense to push that into a stable version of Mojave)

**Comment by afharo** [comment]
Have you tried with an app like: https://apps.apple.com/us/app/amphetamine/id937984704?mt=12

This will allow you to control if you don't want your mac to go to sleep. Or you allow the screen to go off, but the mac to keep running, etc.
