### ISSUE TITLE
Feature request: show firmware/plugin updates in homekit

### ISSUE THREAD

**Issue by ifeign** [nfarina/homebridge#2274]
Many native Homekit devices inform you when a firmware update is needed with an orange exclamation point on the accessory's tile, some even let you update within the Home app. Would it be possible to implement something like this with Homebridge? I don't expect in-Home updates would work but notifications probably could work for outdated Homebridge or plugin versions.
![E96EAEE8-96EA-4BD0-8EC7-5653E67781F0](https://user-images.githubusercontent.com/32289760/62012179-af11ae80-b137-11e9-919f-5d099e74a297.jpeg)

**Comment by KhaosT** [comment]
Apple maintains [a list of accessory firmware](https://configuration.apple.com/configurations/internetservices/HomeKit/v1/ManufacturerDatabase.plist). Home app uses that to show this notice. There is no way for Homebridge to trigger this.

**Comment by Dids** [comment]
@KhaosT As this is an old issue and I'm not sure if this warrants opening a new one, do you happen to know if the situation regarding firmware update notifications is still the same?

As a hobbyist, I've found it rather hard to keep up with all the API changes in HomeKit, so I'm never quite sure what's available now vs. years ago vs. in Homebridge/node-hap.
