### ISSUE TITLE
Home App Accessories Unavailable But Homebridge Still Running Fine In Console

### ISSUE THREAD

**Issue by Jborn4christ** [nfarina/homebridge#2277]
So, Homebridge is running fine and continuing to poll and get responses from devices in the console, but in the Home app on my iphone (ios 13 beta 6) every hour or few hours the accessories will show unavailable. Not really any rhyme or reason as to why or when they go unavailable. I'm thinking it's related to the ios beta update I installed, as it seems to correspond with that timeline, and there have been no additioanl environmental changes to the homebridge system. ANyone else having this?

**Comment by Jborn4christ** [comment]
Update
So thought it may have to do with how the hub is handling connections, so I updated the Apple TV to the latest beta as well. Will provide feedback tomorrow.

**Comment by tbelcher** [comment]
Similar issues for me. Running iOS 13 developer beta on my phone and I can only see the bridged accessories on my lan. I’ve tried both the latest official release of tvOS along with the beta on my Apple TV hub but experience the same issue.

**Comment by Jborn4christ** [comment]
My problem happens on lan and remotely. And the weird part is Homebridge is running in terminal just fine.

**Comment by Jborn4christ** [comment]
Update—
It has to be homebridge related. My two HomeKit outlets work even when all homebridge devices are unavailable.
