### ISSUE TITLE
Can someone help a lost man?

### ISSUE THREAD

**Issue by Haorak** [nfarina/homebridge#2278]
### Pre Steps
Hello,
I am trying to make homebridge work. I did a bunch of stuff going trough some pages on this github, I gotta say it's pretty hard to find what you need. Anyways i hope i get cen some help here.

Here's what i am trying to do :
- Make homebridge work (add it to homekit)
- Add 2 tuya smart plug
### Where I'm at

I have a raspberry pi b+ running raspian. 
I did all the steps to install homebridge and also the autoboot steps, but when i type
systemctl status homebridge
i get this : 
root@raspberrypi:/home/pi/.homebridge# systemctl status homebridge
● homebridge.service - Node.js HomeKit Server
   Loaded: loaded (/etc/systemd/system/homebridge.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Thu 2019-08-01 23:39:40 EDT; 2s ago
  Process: 2253 ExecStart=/usr/local/bin/homebridge $HOMEBRIDGE_OPTS (code=exited, status=217/USER)
 Main PID: 2253 (code=exited, status=217/USER)

That's issue # 1 id say. 
Issue # 2
If i type homebridge
(to start homebridge i guess) I get  :
root@raspberrypi:/home/pi/.homebridge# homebridge
npm WARN npm npm does not support Node.js v10.15.2
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
[2019-08-01, 11:13:52 p.m.] config.json (/root/.homebridge/config.json) not found.
[2019-08-01, 11:13:53 p.m.] Loaded plugin: homebridge-tuya-web
[2019-08-01, 11:13:53 p.m.] Registering platform 'homebridge-tuya-web.TuyaWebPlatform'
[2019-08-01, 11:13:53 p.m.] ---
Load homebridge-tuya-web.TuyaWebPlatform
[2019-08-01, 11:13:53 p.m.] [homebridge-tuya-web.TuyaWebPlatform] No config found, disabling plugin.
Setup Payload:
X-HM://0023ISYWYN9B6

It says that i don't have a config.json file even though i see one when i go into the path. 

I am kinda lost to what to tackle first and i feel like i should restart from scratch but i don't know how and i'd rather try to fix it instead.

Thank you!

### Versions

- **Homebridge**: `homebridge --version`
npm WARN npm npm does not support Node.js v10.15.2
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
0.4.50
- **Node**:       `node --version`
v10.15.2
- **OS**:         
Raspian on pi b+

### Configuration

```json
{
  "bridge": {
    "name": "Homebridge",
    "username": "CC:22:3D:E3:CE:30",
    "port": 51826,
    "pin": "031-45-154"
  },

  "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",
  "ports": {
    "start": 52100,
    "end": 52150,
    "comment": "This section is used to control the range of ports that separate accessory (like camera or television) should be bind to."
  },
  "accessories": [
    {
      "accessory": "WeMo",
      "name": "Coffee Maker"
    }
  ],

  "platforms": [
    {
  "platform": "TuyaWebPlatform",
  "name": "TuyaWebPlatform",
  "options":
    {
      "username": "XXXXX@hotmail.com",
      "password": "XXXXX",
      "countryCode": "1",
      "platform": "tuya",
      "pollingInterval": 10

   }
  ]
}
```

### Homebridge Log / Command Output

```

```

**Comment by ebaauw** [comment]
You don’t want to start homebridge as user `root`.  Use `pi` instead.

I’m not sure about the `npm` warnings.  You might want to double-check how many versions of `node` and `npm` you have installed.  Update `npm`, normally through
```
$ sudo npm -g i npm
```

**Comment by Haorak** [comment]
@ebaauw Thank you for the response! I will try that when i get back home! Do you know if this will fix the fact that homebridge does not see my config.json file?

**Comment by onefish2** [comment]
@Haorak, Do not run as root. Log in as the user pi to do your normal work. Use the sudo command to do root level things. Start with that. Root is a separate super user from pi and its a totally different set of environment settings. If this does not make sense to you then Google these terms.

**Comment by Haorak** [comment]
Thank you very much! It actually did work without being on root. I now have a working .json file aswell. Howerver still have issue with the autoboot function and my tuya-web-plugin (which i have an open item in that github). I am focusing on the plugins for now and will try the autoboot debugging later on. Thank you both for your responses!
