### ISSUE TITLE
Mac Home Assistant asking for Username & Password

### ISSUE THREAD

**Issue by eugeneshortall** [nfarina/homebridge#2279]
I have eventually got Home Assistant installed and open on my Imac.
But now it is asking for Username & Password.
I followed advice found on web,
Deleted files: cloud, onboarding, auth_provider.homeassistant, auth

Still asking for username & Password

Can i find this info in a config or other file.

Thanks,

Eugene

**Comment by iRayanKhan** [comment]
Hello, this is HomeBridge, Home Assistant is something different. Please refer to the HA forums regarding your issue.
