### ISSUE TITLE
Invitee share cameras not working 

### ISSUE THREAD

**Issue by CVHvisuals** [nfarina/homebridge#2282]
My invitee share is not seeing the cameras outside the home network. All other devices are working and updating, except the camera feeds for my invitee. I have tried on both wifi and cellular outside the home network with the same result. 
When inside the home network, the streams work. 
I am able to see the cameras on my devices inside and outside the network( Home owner ).  
I am using ffmpeg for rtsp camera streams. 
Thanks in advance for any suggestions.

**Comment by iRayanKhan** [comment]
I have an issue being investigated by Apple Engineers where certain people sharing the Home as an invitee can't control or see cameras remotely. If there's any update I'll let you know.

**Comment by dezral** [comment]
Same problem here but also with owner access.. homekit is slow and i have rebooted it all now.

Could it be the lastet  tvos Update with an issue?

**Comment by CVHvisuals** [comment]
i have tried all os versions from 12 to 13. all devices match on OS. The devices are controllable and updated on the invitee device, yet the the cameras for the invitee do not work outside the home network.

**Comment by CVHvisuals** [comment]
any update to this issue?

**Comment by CVHvisuals** [comment]
Solved! The latest release now has the option to toggle share camera streams.

**Comment by patelhiren** [comment]
@CVHvisuals I am trying to solve the same problem where my invitees cannot see shared camera outside the home network. You mentioned latest release has an option to toggle share camera streams. I cannot seem to find that option. Can you tell me where this option is?

**Comment by CVHvisuals** [comment]
The option is under the invitee name. Camera stream

**Comment by patelhiren** [comment]
Hmm. I don’t seem to be able to find it there. I am running latest tvOS and iOS. Is this in the beta builds?

**Comment by CVHvisuals** [comment]
I am in beta, but it was in the Final release also.

**Comment by patelhiren** [comment]
Thanks. I will have to see why it’s not showing up for me.

**Comment by CVHvisuals** [comment]
If you open the Home app on iOS, click the house in the upper left corner, then the invitee name/picture. There should be a “Cameras” section with “Stream Only”, or “Stream and View Recordings”.

**Comment by patelhiren** [comment]
Here is what I see for my invitee. May be that only shows if I am using a certified accessory? I am using hombridge-camera-ffmpeg.

![IMG_75A30355469F-1](https://user-images.githubusercontent.com/172098/67165762-f6829200-f356-11e9-9846-ba1a64e2926c.jpeg)

**Comment by CVHvisuals** [comment]
thats odd. I am also using Homebridge-camera-ffmpeg

**Comment by patelhiren** [comment]
Looks like I had to update my Apple TV to tvOS 13.2 beta. Once I did that the options to share camera showed up.
