### ISSUE TITLE
new installation error

### ISSUE THREAD

**Issue by thales-man** [nfarina/homebridge#2290]
### Versions

- **Homebridge**: `homebridge --version`
- **Node**:       `node --version`
- **OS**:         

### Configuration

```json

```

### Homebridge Log / Command Output

```

```

**Comment by thales-man** [comment]
oops, started the process hit return and it committed without any details...

new install of Homebridge using node 12.9
getting this error:

pi@pi-home:~ $ sudo npm install -g -unsafe -perm homebridge
(node:3618) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 drain listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
/usr/local/bin/homebridge -> /usr/local/lib/node_modules/homebridge/bin/homebridge
+ homebridge@0.4.50
added 37 packages from 27 contributors in 6.114s

**Comment by mafyata** [comment]
Try with node v10. I think 10.16.x was the last.

**Comment by thales-man** [comment]
the LTS version is 10.16.3; but the devs should still be aware there is an issue. this is a bug; I've repeated the installation process and it happens every time.

**Comment by ebaauw** [comment]
Read the instructions: it’s a single parameter `--unsafe-perm`.

**Comment by thales-man** [comment]
nice of you to point that out, so politely...

**Comment by thales-man** [comment]
and it's still happening....

**Comment by thales-man** [comment]
the problem isn’t reported with the LTS version (10.16.3); that isn't the same as "doesn't occur". but I'm happier with the outcome.
