### ISSUE TITLE
Removing and adding again a device in Home app.

### ISSUE THREAD

**Issue by kerwinf** [nfarina/homebridge#2291]
I removed an accessory, a camera, from the home app which was using my homebridge. Trying to add the camera back to the home app has been unsuccessful. It is never found again. The only solution, so far, is to remove homebridge and all its accessories, change the identity/pin of my homebridge, add it and all its accessories back and then redo all their settings, scenes and automations. Is there any way to “reset” homebridge so that an accessory can be removed and then found again in the home app?

**Comment by Samfox2** [comment]
Should work if you change the camera name.

**Comment by kerwinf** [comment]
Excellent! I thought I tried that once but, after another attempt it worked! Thank you!
