### ISSUE TITLE
Glass Break Sensors Support

### ISSUE THREAD

**Issue by mrjackyliang** [nfarina/homebridge#2292]
I've been learning how to develop a security system plugin for my ADT Pulse system for Homebridge, and I've bumped into an issue where HAP doesn't seem to have Glass Break/Tamper sensors in support.

My guess would be to leverage the contact sensors like a glass sensor, since all of these accessories (except the security system) is read only mode.

Any ideas on implimenting this feature, or any workarounds available? Thanks!

**Comment by codyc1515** [comment]
You could theoretically use a Contact Sensor.

**Comment by mrjackyliang** [comment]
I did, but I switched it to a motion sensor instead. It kind of works, but the experience is a bit weird.
