### ISSUE TITLE
help me understand how to add platform to config.json - all the time an error

### ISSUE THREAD

**Issue by macguru341** [nfarina/homebridge#2297]
Hello
i have 2 major issues and i hope you guys help me fix them :
1. i want to edit the config.json form adding platforms but i'm getting all the time an error : 

{
    "bridge": {
        "name": "Raspberry",
        "username": "E3:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    
    "platforms": [
        {
            "platform": "config",
            "name": "Config",
            "port": 8080,
            "sudo": true,
            "restart": "sudo -n systemctl restart homebridge",
            "temp": "/sys/class/thermal/thermal_zone0/temp",
            "log": {
                "method": "systemd",
                "service": "homebridge"
            }
            ,
            {
              "platform": "HarmonyHubWebSocket",
                 "name": "HubName",
                 "hubIP": "192.168.1.XX",
                 "TVAccessory" : false,
                  "switchAccessories" : true
            }
            ,
            {
               "platform": "SensiboSky",
              "name": "Sensibo",
                "apiKey": "YOUR_SENSIBO_API_ID"
        }
        }
    ],
    
    "accessories": []
}

The JASONline website that can validate the file says the error is in line 19 :
Error: Parse error on line 19:
..."homebridge"		},		{			"platform": "Ha
---------------------^
Expecting 'STRING', got '{'

what could be the problem ?

thanks you guys

**Comment by mafyata** [comment]
{
"bridge": {
"name": "Raspberry",
"username": "E3:22:3D:E3:CE:30",
"port": 51826,
"pin": "031-45-154"
},

"platforms": [
    {
        "platform": "config",
        "name": "Config",
        "port": 8080,
        "sudo": true,
        "restart": "sudo -n systemctl restart homebridge",
        "temp": "/sys/class/thermal/thermal_zone0/temp",
        "log": {
            "method": "systemd",
            "service": "homebridge"
}
        },
        {
        "platform": "SensiboSky",
        "name": "Sensibo",
        "apiKey": "YOUR_SENSIBO_API_ID"
    }
]
}

**Comment by mafyata** [comment]
This is valid json

**Comment by macguru341** [comment]
Thanks a lot for your help

**Comment by mafyata** [comment]
Is it working now?

**Comment by macguru341** [comment]
Yep, fixed it
