### ISSUE TITLE
iOS 9 - No devices detected, no changes in HAP status regarding existing devices 

### ISSUE THREAD

**Issue by acseven** [nfarina/homebridge#23]
Hi,

Has anyone tried this under iOS 9? I'm using an adaptation of homebridge to micasaverde Vera (this one https://github.com/Hackworth/VeraHomeKitBridge) and while it worked fine with iOS 8.x (I added some scenes and was controlling those with Siri), now it doesn't detect any device and the HAP server status doesn't show any change.

I even tried removing one of them to see if it would pop back up, but to no avail, it wasn't detected.

Do you have any idea of what I can try here?

**Comment by maddox** [comment]
The project that homebridge sits on top of had to make some adjustments for iOS 9. You can see that commit here: https://github.com/KhaosT/HAP-NodeJS/commit/19a4bee7d82674ac0051706687def1e3570c2b68 with an explanation [here](https://github.com/KhaosT/HAP-NodeJS/issues/69#issuecomment-110261466).

So maybe VeraHomeKitBridge needs to make some of the same kind of adjustments.

**Comment by maddox** [comment]
Also, heh, to actually answer your question: yes, homebridge works with iOS 9. But only after some changes and having to remove all devices and re-add them.

**Comment by acseven** [comment]
Ok, thank you for that info, I appreciate it.
