### ISSUE TITLE
Hello! Can I install homebridge on Hyper-V virtual machine?

### ISSUE THREAD

**Issue by xosadmin** [nfarina/homebridge#2308]
Hello! I don't have Raspberry Pi, but I have a machine that can install Hyper-V virtualization. Can I install homebridge on Hyper-V virtual machine with Debian or CentOS system?

**Comment by buenyamin-olgun** [comment]
Yes, should work fine if your networking settings are properly set.

**Comment by xosadmin** [comment]
> Yes, should work fine if your networking settings are properly set.

Thank you! I've updated my gateway firmware to the latest version. I found that gateway id is changed to 8-digit numbers, nor mac address. Should I still copy gateway mac address to be my SID?

**Comment by buenyamin-olgun** [comment]
Didn't get your question - about which gateway firmware / id are you talking about? For which specific component?

**Comment by xosadmin** [comment]
> Didn't get your question - about which gateway firmware / id are you talking about? For which specific component?

Sorry, I got it wrong.
