### ISSUE TITLE
Nest platform name is ''

### ISSUE THREAD

**Issue by ethansinjin** [nfarina/homebridge#231]
When running Homebridge with Nest enabled, it successfully connects to the Nest API.
However, the following is displayed:
```
[Nest] Initializing platform accessory ''...
```
The Nest shows up on iOS, but with a really long name, similar to 0000004A-0000-0000-0000.....

My nest is named. I'm not sure why this is happening

**Comment by ethansinjin** [comment]
It seems that my thermostat is not correctly returning its name to Homebridge via the Nest API. I'm not sure if this is a bug in the API, a problem with Nest 3rd Generation devices, or a problem in the dependency Homebridge is using.

In order to personally resolve this, I added a check in Nest.js: NestThermostatAccessory().
If the name given is "" or null, I'm just using the name "Nest".

I can submit a pull request tomorrow.

**Comment by deejc-uk** [comment]
hi,
I have a nest 2nd Gen and also get this issue, how can i get rid of it ?

**Comment by deejc-uk** [comment]
can anyone give me a hint as to what i have to put into Nest.js ?
I am upto date with this software but still do not see this issue resolved.

**Comment by ethansinjin** [comment]
I submitted a pull request to fix this issue, pending approval.

**Comment by ethansinjin** [comment]
Approved

**Comment by deejc-uk** [comment]
working perfectly, thanks

**Comment by snijjar** [comment]
I installed homebridge last night and installed the nest plugin and everything is working except the name of my device  when I ask Siri to change my temp on my nest she says changing temp on Nesta84444545144... I don't understand what needs to be done in order to change the name just to Nest  Forgive me I am new to all this

**Comment by jdwhite** [comment]
I'd also like the answer to this, and also the following.  I'm using the MyTouchHome iOS app.  Despite homebridge and the iOS app both showing my temperature units set to Fahrenheit, both homebridge and MyTouchHome show Celsius:

[Nest] Current heating for Nest02A..... is: 0
[Nest] Target heating for Nest02A..... is: 1
[Nest] Current temperature for Nest02A..... is: 21.94  <== not fahrenheit
[Nest] Target temperature for Nest02A..... is: 18.968  <== not fahrenheit
[Nest] Tempature unit for Nest02A..... is: Fahrenheit
[Nest] Away for Nest02A..... is: false
[Nest] Current humidity for Nest02A..... is: 47

**Comment by KraigM** [comment]
@jdwhite your question should prob be in HomeBridge-Nest repo. 

This is the second time today that I have been asked this so I will prob change how this was done. They changed the name to ensure it was unique but it's kind of ugly and confuses people who haven't seen the code. 

I'm pretty sure that you just need to change the label on the device (not the home) in the nest app.  Open nest app > home > thermostat > settings cog in right corner > where > label.

But I'm likely going to change the code to find alternatives (like room, home name, etc)before resorting to device id.

**Comment by KraigM** [comment]
I just created an [enhancement item](https://github.com/KraigM/homebridge-nest/issues/10) and also opened up a discussion in #slack

**Comment by jdwhite** [comment]
Changing the label did the trick for me.  Before I was just using the location label "Living Room".  Now I added a label, "Nest" so it now shows "Living Room (Nest)" -- which I can live with -- and now Siri just says "Nest" rather than "nest zero two a thirty two thousand four hundred and thirty one etc, etc."  Better.
