### ISSUE TITLE
Having Problems setting up the .json file

### ISSUE THREAD

**Issue by olebesendahl** [nfarina/homebridge#2311]
Hi,

sorry this is the first thing I'm trying in this way. I have made it till opening the nano /Users.. etc. But then when typing in the Content of the json file I just cant figure out what to press/type to save the file. In my instruction it says to write ^X and then Y and then Enter. But if I do this, nothing happens. 

Is "^" a shortcut for sth?

Thanks for your help! Really appreciate that!

**Comment by iRayanKhan** [comment]
It's CRTL X and CTRL Y

**Comment by olebesendahl** [comment]
great thanks for the quick help.  Worked all good.

But another question: whats the username and the pin? Where do I get them from? Sorry really lost here.

**Comment by iRayanKhan** [comment]
Leave them the way they are.
