### ISSUE TITLE
Log registration in homebridge.log

### ISSUE THREAD

**Issue by dcaccount** [nfarina/homebridge#2315]
Hello,
I have noticed that some plugins configured as accessories register the change of a status in the homebridge.log file, some other do not.

Is there a way to tell Homebridge to register in the log file every status change of each accessory in the config.json file?

Please help, thanks, Dan

**Comment by NorthernMan54** [comment]
Try running in DEBUG mode, it will log all the communications to the Home App, which would include status updates.  Not exactly what your looking for but close.

**Comment by codyc1515** [comment]
Without changing the plug-in, doing the above is your best bet.
