### ISSUE TITLE
Module startup order

### ISSUE THREAD

**Issue by ahartman** [nfarina/homebridge#2319]
Powerful stuff, very valuable, keep up the good work.

I run homebridge-daily-sensors and homebridge-ikea-tradfri-gateway.
When starting up the daily-sensors module sends a double press to a defined switch to initialise. However, the tradfri-gateway is not yet fully started up up, so the double press goes nowhere.

Is there any way to determine the order of module startup and to make one module wait until another one is fully up and running?

Please find my config.json attached for information as as a log of homebridge startup.

Regards, ahartman, belgium
[config-json.txt](https://github.com/nfarina/homebridge/files/3657911/config-json.txt)
[homebridge-startup.txt](https://github.com/nfarina/homebridge/files/3657912/homebridge-startup.txt)

**Comment by NorthernMan54** [comment]
For my setup I split my accessories into multiple homebridge instances and used systemd to start them in a defined order.

Homebridge doesn’t offer this feature

**Comment by ahartman** [comment]
Thank you for the excellent suggestion.
However, it would be good if Homebridge itself offered 'before' and 'after' directives as well to avoid the complexity of multiple instances.

**Comment by ahartman** [comment]
Thank you for the excellent suggestion.
However, it would be good if Homebridge itself offered 'before' and 'after' directives as well to avoid the complexity of multiple instances.

Closing now
