### ISSUE TITLE
Mac OSX. only localhost 

### ISSUE THREAD

**Issue by djwouter12** [nfarina/homebridge#232]
Hello i try to run home brige on my mac. its runs perfect!

but i can only acces with 127.0.0.1. only local... 

how can get acces in my network. 

my router is the apple airport express

**Comment by snowdd1** [comment]
Sorry I didn't get that. What are you trying to do?
You should be able to see it from your iOS HomeKit app, like Elgato EVE or Insteon+; and not from other PCs.

**Comment by spock888** [comment]
Do a netstat -an from the command prompt and grep for 51826 and see if it is binding on 127.0.0.1?

**Comment by djwouter12** [comment]
I don"t see homebridge on my iOS divices or apps,

So i try i can connect by web browser so i enterd 

127.0.0.1:51826 And in the terminal he connects
I have tryd the same thing on an other pc

10.0.1.17:51826 in my browser.. "The page not found" 

I thik that Some firewall it blocks .. But the firewall is disabled

**Comment by spock888** [comment]
Run a tcpdump on your Mac terminal window and see if requests are making it to port 51826 on 10.0.1.17. You should be able to see requests and responses to/from Homebridge server.

**Comment by AppleTechy** [comment]
Due to no updates in the past 2 years I am going to close the issue. If the issue is still occurs please reach out on Slack or create a new issue
