### ISSUE TITLE
pm2 cannot find homebridge

### ISSUE THREAD

**Issue by hunhejj** [nfarina/homebridge#2335]
I set up `pm2` following [this guide](https://github.com/nfarina/homebridge/wiki/Easy-Install-Raspberry-PI-(With-Start-with-boot)) as it seemed like the most convenient way for auto-startup. However if I run `pm2 start homebridge` I get the following error logs in pm2:
```
0|homebridge  | { Error: Cannot find module '/home/pi/homebridge'
0|homebridge  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
0|homebridge  |     at Function.Module._load (internal/modules/cjs/loader.js:507:25)
0|homebridge  |     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:27:21)
0|homebridge  |     at Module._compile (internal/modules/cjs/loader.js:689:30)
0|homebridge  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
0|homebridge  |     at Module.load (internal/modules/cjs/loader.js:599:32)
0|homebridge  |     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
0|homebridge  |     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
0|homebridge  |     at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
0|homebridge  |     at startup (internal/bootstrap/node.js:283:19) code: 'MODULE_NOT_FOUND' }
PM2           | App [homebridge:0] exited with code [1] via signal [SIGINT]
PM2           | App [homebridge:0] starting in -fork mode-
PM2           | App [homebridge:0] online
```
And this is repeating all the time.
 
I can start homebridge just normal when running `$ homebridge` simply from a terminal.

**Comment by dxdc** [comment]
What is the output of `pm2 list`? You can also check your pm2 log files `pm2 log`. That being said, it's not very obvious if it has something to do with your pm2 initialization or your homebridge set up.

I would venture that there is some wrong set up in `config.json` or a bad module that got installed. What do you see as the output of this:

`ls -lAF ~/".pm2/modules"`

There should be no modules in there, other than `pm2-logrotate` if you installed that.

**Comment by hunhejj** [comment]
Output of `pm2 list`:
```
│ 0  │ homebridge         │ fork     │ 3    │ online   │ 0%       │ 19.9mb   │
```

`pm2 log` does not really reveal anything more than the above. `/home/pi/.pm2/pm2.log` has these lines repeatingly:
```
/home/pi/.pm2/pm2.log last 15 lines:
PM2        | 2019-10-21T10:03:27: PM2 log: App [homebridge:0] exited with code [                                           1] via signal [SIGINT]
PM2        | 2019-10-21T10:03:27: PM2 log: App [homebridge:0] starting in -fork                                            mode-
PM2        | 2019-10-21T10:03:27: PM2 log: App [homebridge:0] online
PM2        | 2019-10-21T10:03:29: PM2 log: App [homebridge:0] exited with code [                                           1] via signal [SIGINT]
PM2        | 2019-10-21T10:03:29: PM2 log: App [homebridge:0] starting in -fork                                            mode-
PM2        | 2019-10-21T10:03:29: PM2 log: App [homebridge:0] online
PM2        | 2019-10-21T10:03:31: PM2 log: App [homebridge:0] exited with code [                                           1] via signal [SIGINT]
```
whileas `/home/pi/.pm2/logs/homebridge-error.log` repeats the following:
```
0|homebridge  | { Error: Cannot find module '/home/pi/homebridge'
0|homebridge  |     at Function.Module._resolveFilename (internal/modules/cjs/lo                                           ader.js:581:15)
0|homebridge  |     at Function.Module._load (internal/modules/cjs/loader.js:507                                           :25)
0|homebridge  |     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/P                                           rocessContainerFork.js:27:21)
0|homebridge  |     at Module._compile (internal/modules/cjs/loader.js:689:30)
0|homebridge  |     at Object.Module._extensions..js (internal/modules/cjs/loade                                           r.js:700:10)
0|homebridge  |     at Module.load (internal/modules/cjs/loader.js:599:32)
0|homebridge  |     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
0|homebridge  |     at Function.Module._load (internal/modules/cjs/loader.js:530                                           :3)
0|homebridge  |     at Function.Module.runMain (internal/modules/cjs/loader.js:7                                           42:12)
0|homebridge  |     at startup (internal/bootstrap/node.js:283:19) code: 'MODULE                                           _NOT_FOUND' }
PM2           | App [homebridge:0] exited with code [1] via signal [SIGINT]
PM2           | App [homebridge:0] starting in -fork mode-
PM2           | App [homebridge:0] online
```

The error message is technically true, i.e. there is no `/home/pi/homebridge` module indeed, because I installed homebridge globally. However if I run `homebridge` simply from the terminal in `/home/pi/`, then it runs correctly. I don't think there is anything wrong with my `config.json` because as I mentioned earlier it runs correctly when started manually. 


There are no modules in `ls -lAF ~/".pm2/modules"`

**Comment by dxdc** [comment]
@hunhejj looks like pm2 is (probably) working fine, and `homebridge` is crashing, so pm2 keeps restarting it. Maybe a path issue or permissions issue?

try typing:

```sh
cd ~
pm2 delete all
pm2 start homebridge
```

same result?

**Comment by hunhejj** [comment]
Same result.

But I just realized that you are probably right that it might be a permission issue. I forgot, that I wrote a plugin, that is in `/home/pi/homebridge/homebridge-my-plugin`, that I installed with `npm install -g /home/pi/homebridge/homebridge-my-plugin/`. As far as I remember this creates a symlink only. What permission should the original directory have so homebridge started with `pm2` could access it?

**Comment by dxdc** [comment]
Remove that plugin and see if your problem goes away. That is probably your issue.

Read the section under `Plugin Development` and the use of `-P`.
https://github.com/nfarina/homebridge/blob/master/README.md

**Comment by hunhejj** [comment]
Removed the plugin, but I still get the same error. (Also removed all accessories from `config.json`)

**Comment by dxdc** [comment]
Removing it from config.json won't help, homebridge looks for plugins on startup. You need to remove the symlink in your /usr/lib/node_modules folder that you created.

If that doesn't work, it just sounds like an installation or permissions issue. You installed pm2 globally and not locally? 

`sudo npm install -g pm2`

**Comment by hunhejj** [comment]
I only have `pm2` and `homebridge` in `/usr/lib/node_modules` (both of them are installed globally). No symlink, clean `config.json`.

**Comment by hunhejj** [comment]
I removed the directory `/home/pi/homebridge` and suddenly I was able to start homebridge with `pm2`. What makes me wonder is that the same error still shows up 3 times in the logs whenever I start the service (`Error: Cannot find module '/home/pi/homebridge'`), but still homebridge starts.

**Comment by hunhejj** [comment]
Thank you very much for your help @dxdc !
