### ISSUE TITLE
Any chance this will work with Android Home Kit (Brillo?)

### ISSUE THREAD

**Issue by spock888** [nfarina/homebridge#234]
Curious if I can get this working on an Android phone running Marshmallow and control stuff by saying "OK Google" :-)

**Comment by maddox** [comment]
This is specifically for the HomeKit protocol. I'm sure there are other ways to map speech to do things on Android. Check out Tasker. People seem to be doing a lot of cool things with that.

**Comment by spock888** [comment]
Thanks for the quick response. I already have homebridge running and works great with my iPhone. My son has an android phone and wanted to see if I can reuse some of the stuff. Thanks for comfirming.

**Comment by anubhavmajumder** [comment]
Hello.
You can install any distro of linux as a secondary OS using this on your android. [https://github.com/meefik/linuxdeploy](https://github.com/meefik/linuxdeploy)

After that setup homebridge as usual. https://github.com/nfarina/homebridge
And plugins from here. https://www.npmjs.com/search?q=homebridge-plugin

Cheers!
