### ISSUE TITLE
Cannot completely close blinds

### ISSUE THREAD

**Issue by odrobnik** [nfarina/homebridge#2340]
### Expected Behavior

With blinds open, when tapping on a blinds button in Home, I expect the blinds to go fully down.

### Current Behavior

The go fully down, but then go slightly back to turn the slats horizontal. Sometimes they show as 1% status.

### Versions

- **Homebridge**: `0.4.50`
- **Node**:       `v12.12.0`
- **OS**:         macOS 10.15 on 2018 Mac Mini

**Comment by NorthernMan54** [comment]
This is a plugin issue and not a homebridge disuse, please close this and open an issue against the plugin
