### ISSUE TITLE
Update MacOS Catalina --> Launchd not working

### ISSUE THREAD

**Issue by beatpaul** [nfarina/homebridge#2341]
Hi!
I had 6 Instances of homebridge running on MacOS Mojave starting up automatically with launchd without any issue (thx to @ebaauw !).
After Updating to MacOS Catalina i still can run the homebridge instances manually at cmd but the LaunchAgents with launchd do not work any more :(
- do I have to reinstall Node, Npm, Homebridge e.g ?
- did any path change in Catalina ?

Would be geat if someone has an idea!

thx, Paul

**Comment by ddorato** [comment]
I am also having the same issue.

**Comment by beatpaul** [comment]
Is there any other way to start homebridge instances as a service than launchd / launchctr ?

Would be great if someone could help :)

**Comment by TaylorBruce** [comment]
@beatpaul - You could use PM2 to manage it. I used to do it this way before and it worked very well.

Now I run it in docker on a RPI, and that is even easier.

**Comment by beatpaul** [comment]
@TaylorBruce Thx for advice!
I will try it and report

**Comment by beatpaul** [comment]
@TaylorBruce : PM2 worked great! to daemonize all homebridge instances! (and i didn't have to reinstall anything --> what was very comfortable :)

THX!
