### ISSUE TITLE
Accessory Not Found

### ISSUE THREAD

**Issue by dhpeter** [nfarina/homebridge#2350]
### Expected Behavior
When homebridge is running on rPI, accessory would add via homekit when scanning the QR Code

### Current Behavior
When scanning the QR Code, end result is accessory not found.

### Versions

- **Homebridge**: 0.4.50
- **Node**:      10.16.3
 

### Configuration

```json

```

### Homebridge Log / Command Output

```

```
I have an ATT fiber modem/gateway, google wifi connected from that. The rPI is connected to the google mesh and has an IP.

If i connect the rPI and iphone to ATT wifi, it works, however, this isn't the configuration i want. I want to use the mesh system as everything is on it. 

I have tried restarting PI, deleted persist/accessories. entered mdsn settings in config.json (with rPI IP, connected to google wifi)

I have completely updated and reinstalled homebridge and modules.

I feel this is some double NAT issue, but i do not know how to bypass it. It used to work until last week or so.

**Comment by mafyata** [comment]
Many people have problem with homebridge + google wifi

**Comment by mafyata** [comment]
Use nodejs 10.16.x

**Comment by dhpeter** [comment]
Thank you, I will definitely try this tonight. I have been using this setup for a while now, it’s possible when I upgraded the framework while trying to use homebridge-nest it broke it. It WAS around that time I noticed it stopped working, however, it did work with that at one point.

**Comment by dhpeter** [comment]
@mafyata , downgrading to 10.16.3 did not change the behavior.

**Comment by dhpeter** [comment]
This has to do with google wifi's update in Q3 2019. If homebridge server is not connected to primary NAT device it will not work. Connect to primary NAT or disconnect other bridges to work.

**Comment by JamesToohey** [comment]
@dhpeter for what it's worth, my homebridge is a Pi connected to a non-primary Google Wifi node and works fine. Google Wifi is up to date - maybe they resolved it?
