### ISSUE TITLE
Connecting from Remote

### ISSUE THREAD

**Issue by nyxs** [nfarina/homebridge#2352]
### Expected Behavior

Controlling the devices outside of the Wi-Fi, using the hub.

### Current Behavior

Can't control devices remotely. They're not responding outside the internal network.
The accessories I have that connected directly to HomeKit are working great.

### Steps to Reproduce (for bugs)

1. Create new Home
2. Add Apple TV/iPad/Homepod as hub
3. Install Homebridge and configure all your devices in the config.json file
4. Run Homebridge and add the accessories to your Home.
5. Turn off Wi-Fi and you won't be able to control the Homebridge devices.

### Versions

- **Homebridge**: `0.4.50`
- **Node**:       `v12.4.0`
- **OS**:         `Raspbian Buster`

Should I open some ports in my router?

Thanks

**Comment by nyxs** [comment]
Found the solution!
I use pfsense as my router at home. I made segmentation and put the Apple TV on one segment, but the rbpi was on another segment. When I connected to the rbpi's segment, I got everything up and running. But when I connected to the Apple TV's segment, I saw all the bridges up (I have both Home Assistant and Homebridge), but nothing worked (Not Responding accessories).

### Solution
Simply connected the Apple TV to the rbpi's segment and everything works great, even over cellular.

**Comment by ebaauw** [comment]
HomeKit clients use Bonjour (multicast-DNS) to locate HomeKit accessories.  This protocol is not routable, so even if the HAP HTTP server can be reached, it won't be found.  The HomeKit client (i.c. your AppleTV for remote access) and the HomeKit accessory (i.c. the server running homebridge) need to be in the same subnet.

**Comment by dkrizic** [comment]
Hi @nyxs and @ebaauw. The protocol is fully routable, but the mDNS will be broadcasted only in the the same network. For pfSense (and other systems like Linux): Install and configure Avahi. It will forward those broadcasts to other segments so they are visible. The broadcasted messages are being forwarded to other segments, in result all devices in all segments are visible to each other.

![image](https://user-images.githubusercontent.com/1181349/68528067-75cc0b80-02ee-11ea-9e2e-6ad7115da2b9.png)

BTW: Additionally there is something called Wide-Area-Bonjour that allows to propagate Bonjour services even thru the whole internet using some DNS entries. This is a very powerful protocol.

**Comment by nyxs** [comment]
@dkrizic 
Thank you for the info!
Just install Avahi, set everything up like you did, connected the ATV to the original subnet, and still doesn't work.

**Comment by dkrizic** [comment]
There is a tool called iNet Network Scanner that is available for the Mac and iOS. It shows you all devices that are visible from the network. Here for example is the Apple TV

![image](https://user-images.githubusercontent.com/1181349/68528304-35ba5800-02f1-11ea-9070-97718fd72d66.png)

and here my HomeKit (HAP) devices:

![image](https://user-images.githubusercontent.com/1181349/68528310-4f5b9f80-02f1-11ea-86f9-a0981d5c9c7f.png)

Some of them are in other segments. Ensure that Avahi is configured on and select all interfaces of all segments that should see each other. Verify using iNet.

**Comment by ebaauw** [comment]
> The protocol is fully routable, but the mDNS will be broadcasted only in the the same network.

mDNS is not routable.  It uses multicast, not broadcast.  The multicast address is local subnet only.

> It will forward those broadcasts to other segments so they are visible. The broadcasted messages are being forwarded to other segments, in result all devices in all segments are visible to each other.

Cool!  I didn’t know pfSense.  Do you know if it can also reflect UPnP multicasts?

Note that pSense doesn’t forward the multicast packets.  It “reflects” them, i.e. it creates a new multicast packet with the same content on the other subnet.  In OSI terms, it’s a level-7 application gateway, not a level-3 router.

> BTW: Additionally there is something called Wide-Area-Bonjour that allows to propagate Bonjour services even thru the whole internet using some DNS entries. This is a very powerful protocol.

Apple used that for the (now discontinued) Back-to-My-Mac service.  In my experience this was kinda hit and miss, but when it worked it was great.  I haven’t seen any other applications of Wide-Area-Bonjour.

**Comment by dkrizic** [comment]
You are right, the protocol itself (multicast) is not routed, but what I wanted to say is that as soon as they are found the devices communicate even in different networks.

pfSense is a very powerful firewall that I use for various things (segments, security, VPN, Avahi, Reverse Proxy, DNS, DHCP, Guest network, UPNP, NAT, Port forwards, a.s.o.). Here is the configuration screen for UPnP:

![image](https://user-images.githubusercontent.com/1181349/68528404-972ef680-02f2-11ea-8e1a-9ce3242847a4.png)

and here the status:

![image](https://user-images.githubusercontent.com/1181349/68528411-aca42080-02f2-11ea-903b-df97d4568f67.png)

**Comment by ebaauw** [comment]
Did you ever try to use pfSense to reflect mDNS between a VPN and your local network?

**Comment by dkrizic** [comment]
No, I did not try that, but my experience is: If it does not work on pfSense, it does not work anywhere.

**Comment by ebaauw** [comment]
> You are right, the protocol itself (multicast) is not routed, but what I wanted to say is that as soon as they are found the devices communicate even in different networks.

Yes, HAP is basically HTTP.

> Here is the configuration screen for UPnP:

Thanks.  This looks like ”only” the NAT functionality of UPnP.  I’m particularly interested in device discovery (ssdp:alive and ssdp:discover messages), as used by e.g. Sonos.

What hardware are you running pfSense on?

**Comment by dkrizic** [comment]
I run it on a PC-Engines APU2 (APU2C4 or so). I have multiple of those for various tasks (mostly Kubernetes). Two fit in a 19" rack. Extremely reliable hardware. One old instance (Alex) runs since ten years.
