### ISSUE TITLE
How to implement and provide custom plugins?

### ISSUE THREAD

**Issue by knalli** [nfarina/homebridge#236]
Please see this as a general advice, also for others.

How does the project consider handling custom plugins (say: accessories) not built-in in repo? If I read [app.js correctly](https://github.com/nfarina/homebridge/blob/feca9fbf0d9418ea742bdf58aa9a71ef1b79776e/app.js#L79), it will load only from `./accessories/*.js`. I guess an `accessory` with value `../../MyCustomAccessory` will work, but that's probably not intended?!

Meanwhile, I'm not hiding my work: I've played with the stuff last weekend (thank you for the project, it is wonderful!) and I've made a prototype adapter for pilight [here](https://gist.github.com/knalli/201eea71130136db2ca0) based on its ws api. Would do you like to add this kind of adapter?

**Comment by cflurin** [comment]
Take al look at #151

**Comment by knalli** [comment]
Okay, this is being solved by the new plugin architecture.
