### ISSUE TITLE
Updated accessory information becomes reset to original

### ISSUE THREAD

**Issue by mrjackyliang** [nfarina/homebridge#2365]
### Pre Steps
Have a plugin update a plugin accessory information.

### Expected Behavior

The updated accessory information should stay.

### Current Behavior

The updated accessory information resets after a period of time.

### Versions

- **Homebridge**: `v0.4.50`
- **Node**:       `v12.13.1`
- **OS**:         oznu/docker-homebridge

**Comment by stibbzy** [comment]
Hello. I have this same issue. Were you Able to figure out what was going on? Cheers.
