### ISSUE TITLE
Multiple instances

### ISSUE THREAD

**Issue by Vulpecula-nl** [nfarina/homebridge#2370]
I'm getting the following message with every restart of my homebridge service. Can someone tell me which one I have to remove and with which command that can be done? Thanks

```
[Config] Multiple Instances Of Homebridge Found Installed
[Config] /usr/lib/node_modules/homebridge
[Config] /usr/local/lib/node_modules/homebridge
```

**Comment by mafyata** [comment]
I use: usr/local/lib/node_modules/homebridge

**Comment by maxrad-nobrain** [comment]
I have the same "problem", meaning having same two instances. I think I accidentally added the 2nd one, which I didn't meant to do. Can someone confirm which is the right one to keep? 
Can someone please also let me know how to uninstall/remove the instance I don't need anymore, i.e. how to uninstall an instance in a specific folder? Thanks!

**Comment by Vulpecula-nl** [comment]
I have remove one by uninstalling the local instance. I don’t know the command anymore. But it was quiet simple
