### ISSUE TITLE
Unable to install Broadlink Plugin

### ISSUE THREAD

**Issue by rafayez** [nfarina/homebridge#2395]
Hi all,

I've been using homebridge with the broad link plugin for 2 or 3 years now with no issues that weren't fixable. Until recently i bumped into an issue where homebridge will just refuse to run hitting me with a bunch of errors. So i decided to reinstall the plugin to resolve the issue, for doing so, i removed broadlink plugin using the command " npm remove -g homebridge-broadlink-rm " and then tried to re-install by using the command " npm install -g homebridge-broadlink-rm " , but sadly it kept on failing and logged the following errors one the log file :

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli 'C:\Program Files\nodejs\node.exe',
1 verbose cli 'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli 'install',
1 verbose cli '-g',
1 verbose cli 'homebridge-broadlink-rm'
1 verbose cli ]
2 info using npm@6.9.0
3 info using node@v12.3.1
4 verbose npm-session b94767d920bfce97
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 304 https://registry.npmjs.org/homebridge-broadlink-rm 1443ms (from cache)
8 silly pacote tag manifest for homebridge-broadlink-rm@latest fetched in 1578ms
9 timing stage:loadCurrentTree Completed in 1679ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 2ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 14ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule homebridge-broadlink-rm@3.6.22 checking installable status
17 silly fetchPackageMetaData error for homebridge-platform-helper@github:lprhodes/homebridge-platform-helper#feature/typescript Error while executing:
17 silly fetchPackageMetaData undefined ls-remote -h -t ssh://git@github.com/lprhodes/homebridge-platform-helper.git
17 silly fetchPackageMetaData
17 silly fetchPackageMetaData
17 silly fetchPackageMetaData spawn git ENOENT
18 http fetch GET 304 https://registry.npmjs.org/github-version-checker 1387ms (from cache)
19 silly pacote range manifest for github-version-checker@^1.2.0 fetched in 1404ms
20 silly resolveWithNewModule github-version-checker@1.2.0 checking installable status
21 http fetch GET 304 https://registry.npmjs.org/broadlinkjs-rm 2759ms (from cache)
22 http fetch GET 304 https://registry.npmjs.org/uuid 2563ms (from cache)
23 http fetch GET 304 https://registry.npmjs.org/find-key 2769ms (from cache)
24 http fetch GET 304 https://registry.npmjs.org/chai 2774ms (from cache)
25 http fetch GET 304 https://registry.npmjs.org/ping 2582ms (from cache)
26 http fetch GET 304 https://registry.npmjs.org/net-ping 2675ms (from cache)
27 silly pacote range manifest for uuid@^3.3.3 fetched in 2677ms
28 silly resolveWithNewModule uuid@3.4.0 checking installable status
29 silly pacote range manifest for find-key@^2.0.1 fetched in 2887ms
30 silly resolveWithNewModule find-key@2.1.3 checking installable status
31 silly pacote range manifest for chai@^4.2.0 fetched in 2897ms
32 silly resolveWithNewModule chai@4.2.0 checking installable status
33 silly pacote range manifest for broadlinkjs-rm@^0.7.6 fetched in 2910ms
34 silly resolveWithNewModule broadlinkjs-rm@0.7.6 checking installable status
35 silly pacote range manifest for ping@^0.2.2 fetched in 2706ms
36 silly resolveWithNewModule ping@0.2.2 checking installable status
37 silly pacote range manifest for net-ping@^1.2.3 fetched in 2741ms
38 silly resolveWithNewModule net-ping@1.2.3 checking installable status
39 timing stage:rollbackFailedOptional Completed in 3ms
40 timing stage:runTopLevelLifecycles Completed in 4703ms
41 verbose stack Error: spawn git ENOENT
41 verbose stack at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
41 verbose stack at onErrorNT (internal/child_process.js:456:16)
41 verbose stack at processTicksAndRejections (internal/process/task_queues.js:84:9)
42 verbose cwd C:\Users\Server\Desktop
43 verbose Windows_NT 10.0.18362
44 verbose argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "homebridge-broadlink-rm"
45 verbose node v12.3.1
46 verbose npm v6.9.0
47 error path git
48 error code ENOENT
49 error errno ENOENT
50 error syscall spawn git
51 error enoent Error while executing:
51 error enoent undefined ls-remote -h -t ssh://git@github.com/lprhodes/homebridge-platform-helper.git
51 error enoent
51 error enoent
51 error enoent spawn git ENOENT
52 error enoent This is related to npm not being able to find a file.
53 verbose exit [ 1, true ]

Can someone please help me with my issue, as i've tried almost everything that i could think of but none of the worked. Removed Homebridge, Node.js and reinstalled them but still nothing seemed to resolve the issue.

Thank you in advance for your help, much appreciated.
Rafay

**Comment by oznu** [comment]
https://github.com/lprhodes/homebridge-broadlink-rm/issues/544

**Comment by rafayez** [comment]
Thank you oznu for your help, following your link resolved my initial issue, but sadly i was confronted with another issue that i'm unable to resolve at all. Please have a look below :

C:\WINDOWS\system32>homebridge -U c:\users\server\.homebridge
[1/24/2020, 9:45:07 PM] Loaded config.json with 1 accessories and 4 platforms.
[1/24/2020, 9:45:07 PM] ---
[1/24/2020, 9:45:08 PM] Loaded plugin: homebridge-automation-switches
[1/24/2020, 9:45:08 PM] Registering platform 'homebridge-switches.AutomationSwitches'
[1/24/2020, 9:45:08 PM] ---
[1/24/2020, 9:45:09 PM] ====================
[1/24/2020, 9:45:09 PM] ERROR LOADING PLUGIN homebridge-broadlink-rm:
[1/24/2020, 9:45:09 PM] Error: Cannot find module 'hap-nodejs'
Require stack:
- C:\Users\Server\AppData\Roaming\npm\node_modules\homebridge-broadlink-rm\node_modules\homebridge-platform-helper\dist\accessory.js
- C:\Users\Server\AppData\Roaming\npm\node_modules\homebridge-broadlink-rm\node_modules\homebridge-platform-helper\dist\index.js
- C:\Users\Server\AppData\Roaming\npm\node_modules\homebridge-broadlink-rm\platform.js
- C:\Users\Server\AppData\Roaming\npm\node_modules\homebridge-broadlink-rm\index.js
- C:\Users\Server\AppData\Roaming\npm\node_modules\homebridge\lib\plugin.js
- C:\Users\Server\AppData\Roaming\npm\node_modules\homebridge\lib\server.js
- C:\Users\Server\AppData\Roaming\npm\node_modules\homebridge\lib\cli.js
- C:\Users\Server\AppData\Roaming\npm\node_modules\homebridge\bin\homebridge
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\Server\AppData\Roaming\npm\node_modules\homebridge-broadlink-rm\node_modules\homebridge-platform-helper\dist\accessory.js:13:22)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
[1/24/2020, 9:45:09 PM] ====================


Tried reinstalling Node and npm, broadlink plugin, removed and re-installed homebridge. I tried almost anything that i can dream of, but none of them worked.

I've highly appreciated once again any help resolving the over issue.
Thank you in advance for your help.
Rafik

**Comment by rafayez** [comment]
can someone please assist me with my above mentioned issue. Here are some more troubleshooting data, maybe it can help.

C:\Users\Server\AppData\Roaming\npm\node_modules\homebridge-broadlink-rm\node_modules\raw-socket>if not defined npm_config_node_gyp (node "C:\Users\Server\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Server\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  raw.cc
  win_delay_load_hook.cc
c:\users\server\appdata\roaming\npm\node_modules\homebridge-broadlink-rm\node_modules\raw-socket\src\raw.cc(723): warning C4018: '>': signed/unsigned mismatch [C:\Users\Server\AppData\Roaming\npm\node_modul
es\homebridge-broadlink-rm\node_modules\raw-socket\build\raw.vcxproj]
     Creating library C:\Users\Server\AppData\Roaming\npm\node_modules\homebridge-broadlink-rm\node_modules\raw-socket\build\Release\raw.lib and object C:\Users\Server\AppData\Roaming\npm\node_modules\homeb
  ridge-broadlink-rm\node_modules\raw-socket\build\Release\raw.exp
  raw.vcxproj -> C:\Users\Server\AppData\Roaming\npm\node_modules\homebridge-broadlink-rm\node_modules\raw-socket\build\Release\\raw.node
+ homebridge-broadlink-rm@3.6.22
added 135 packages from 122 contributors in 74.292s

**Comment by rafayez** [comment]
npm install -g hap-nodejs 

fixed my issue.
