### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by tocks53** [nfarina/homebridge#24]
hello, sorry, but you close my issue ans my problem is again here.

beber@beber-Portable:~/homebridge$ sudo npm run start

> homebridge@0.0.0 start /home/beber/homebridge
> node app.js

Starting HomeBridge server...
*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>

/home/beber/homebridge/lib/HAP-NodeJS/node_modules/ed25519/node_modules/bindings/bindings.js:83
        throw e
              ^
Error: Symbol ed25519_module not found.
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at bindings (/home/beber/homebridge/lib/HAP-NodeJS/node_modules/ed25519/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/home/beber/homebridge/lib/HAP-NodeJS/node_modules/ed25519/index.js:1:99)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

npm ERR! homebridge@0.0.0 start: `node app.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the homebridge@0.0.0 start script.
npm ERR! This is most likely a problem with the homebridge package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls homebridge
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.19.0-20-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "run" "start"
npm ERR! cwd /home/beber/homebridge
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/beber/homebridge/npm-debug.log
npm ERR! not ok code 0
beber@beber-Portable:~/homebridge$

**Comment by tocks53** [comment]
its ok for me

npm install <name of module>

Sorry close the issue please

**Comment by maddox** [comment]
@tocks53 thanks for reporting back. 

You'll have to close it, since you opened it.

Thanks!

**Comment by tocks53** [comment]
When close a ticket ?

**Comment by nfarina** [comment]
Hi @tocks53 you can close an issue by clicking the "Close" button on this page. I'll close this one for you though.
