### ISSUE TITLE
Router Accessory support

### ISSUE THREAD

**Issue by iRayanKhan** [nfarina/homebridge#2403]
Recently with iOS 13.3.1, Eero's have started showing up as a nearby accessory to add to HomeKit, does HAP-JS support the router accessory yet? I understand it is TLV heavy, I just wanted to see what we can get out of it, and see if it's possible to use a HomeKit router as a HomeKit hub.

**Comment by KhaosT** [comment]
I'm not sure it make sense for us to ever implement router support? HomeKit's Router support includes two things, managed network for HomeKit accessories, and firewall isolation for certified accessories. If you have network equipment supporting those features, you probably already using those features... If your network equipment doesn't support those features, there is no sensible way to fake those...

And given your homebridge instance need to talk to those accessories via local network or via internet, enforcing a strict firewall rules will only break things...

HomeKit Router does not support being a HomeKit Hub.

**Comment by alexindigo** [comment]
@KhaosT How about some informational things, like router's stats?

**Comment by iRayanKhan** [comment]
Dang I was thinking too Homebridge may break with HKSR, but I wonder if flashing accessories with HomeKit software (non certified ofc), would still work.

**Comment by KhaosT** [comment]
@alexindigo it's pretty limiting, only includes things like whether your internet is connected or not... https://github.com/KhaosT/HAP-NodeJS/blob/master/src/lib/gen/HomeKit.ts#L4581

**Comment by alexindigo** [comment]
I see. Thanks for the link.

PS. This is golden :)

```
      case Formats.DATA:
        return null; // who knows!
      case Formats.TLV8:
        return null; // who knows!
```

**Comment by alexindigo** [comment]
Btw, what is `TLV`?

**Comment by KhaosT** [comment]
@alexindigo https://en.wikipedia.org/wiki/Type-length-value

**Comment by iRayanKhan** [comment]
@KhaosT Is there anything that could bypass the firewall to allow for only a Pi to talk to these devices? I am planning on getting an eero, but if it breaks stuff then I guess I may try to put the homebridge stuff on a separate router.
