### ISSUE TITLE
State of home bridge accessory will not update in HomeKit app.

### ISSUE THREAD

**Issue by rixmix123** [nfarina/homebridge#2420]
Hello, 

I am seeing an issue that when using a Smartthings accessory with homebridge, HomeKit can control the accessory no problem, but if the switch for example is turned off manually, HomeKit will not update the state of the device. For example, the SmartThings/homebridge accessory can turn the light off no problem. But when turning the light off manually from the physical location, homekit/homebridge will still say the light is in the "on" status or vise versa. Sorry if this is a duplicate issue, but I could not find the issue anywhere. Also I have ran home bridge on a Mac and raspberry PI and I have had the same issue. I also am not sure if this would only apply to smart things accessories, but that is all I am currently running.

**Comment by NorthernMan54** [comment]
This is not a homebridge issue but an issue with the smarthings plugin.  Please Close this and raise as an issue against the plugin
