### ISSUE TITLE
Help setting up homebridge!

### ISSUE THREAD

**Issue by cubstitan95** [nfarina/homebridge#2436]
Hello! I’m new to this coding and scripting thing and I’m attempting to set up homebridge. I followed all the steps and instructions all the way to the part where I have to edit the config.json file and add Homebridge Config UI X. The instructions recommend using notepad++. The problem is every time I paste the code into config.json under platforms it’s not formatting it correctly And ends up not validating. I’ve included two pictures below. The first One of what it’s supposed to look like according to the instructions and the second is what I have. Please help! Thanks in advance! 
![09E5DEC5-ACB3-473F-BE6E-1378D337EB3A](https://user-images.githubusercontent.com/61809107/76031129-b20a2400-5efc-11ea-9979-b46d67c88673.png)
![70387DD3-E7F3-49BD-B4B4-8745F0FF383D](https://user-images.githubusercontent.com/61809107/76031155-c3ebc700-5efc-11ea-81aa-7e6ff6b5aee6.jpeg)

**Comment by joberembt** [comment]
You've got an extra comma after the "port" :8080 and an extra }  - remove
them and it should be good.

--JOsh

**Comment by cubstitan95** [comment]
It worked! But now I have another problem. I’m in the administrator command prompt and for some reason when I try to launch homebridge I’m getting an error message.
![image](https://user-images.githubusercontent.com/61809107/76110811-cd306e80-5fa4-11ea-9750-ddd915022767.jpg)

**Comment by mgbowman** [comment]
The `username` field in the config.json needs to be in the format `AA:BB:CC:DD:EE:FF`
