### ISSUE TITLE
Server crashes when entering the pin on the phone

### ISSUE THREAD

**Issue by postbreak** [nfarina/homebridge#244]
I finally managed to get this installed with all the dependencies and I'm running into an issue. I get homebridge running, my iPhone sees the homebridge, but when I tap on it to add the device homebridge server stops with the following error. I really don't know how to debug this one.

I looked through the submitted issues and didn't see this one listed, I'm new to Github so if I missed it I'm sorry. 

iPhone 6s, Elgato Eve, trying the lockitron accessory.

Loading 1 platforms...
[undefined] Initializing YamahaAVR platform...
[undefined] Getting Yamaha AVR devices.
Loading 1 accessories...
[Front Door] Initializing Lockitron accessory...
[undefined] Waited 30 seconds, stopping discovery.
[undefined] Discovery finished, found 0 Yamaha AVR devices.
Scan this code with your HomeKit App on your iOS device:

```
┌────────────┐     
│ 031-45-154 │     
└────────────┘     
```

  EventedHTTPServer Server listening on port 51826 +0ms
  EventedHTTPServer [192.168.29.127] New connection from client +8s
  EventedHTTPServer [192.168.29.127] HTTP server listening on port 54826 +0ms
  EventedHTTPServer [192.168.29.127] HTTP request: /pair-verify +2ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +1ms
  HAPServer [CC:22:3D:E3:CE:30] Pair verify step 1/2 +1ms

TypeError: Object #<Object> has no method 'makeSecretKey'
    at Object.generateCurve25519SecretKey (/home/ryan/homebridge/node_modules/HAP-NodeJS/lib/util/encryption.js:33:14)
    at HAPServer._handlePairVerifyStepOne (/home/ryan/homebridge/node_modules/HAP-NodeJS/lib/HAPServer.js:440:30)
    at HAPServer._handlePairVerify (/home/ryan/homebridge/node_modules/HAP-NodeJS/lib/HAPServer.js:429:10)
    at HAPServer.<anonymous> (/home/ryan/homebridge/node_modules/HAP-NodeJS/lib/HAPServer.js:172:39)
    at IncomingMessage.EventEmitter.emit (events.js:92:17)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)

**Comment by AppleTechy** [comment]
Please update and try with the latest version of Homebridge. If the issue still occurs, please hop onto Slack or create a new issue
