### ISSUE TITLE
Wemo Light

### ISSUE THREAD

**Issue by ttgolf** [nfarina/homebridge#246]
Looks like the code was updated a few days ago to support Wemo light bulbs.  Just tried it yesterday without any success.  Homebridge can't find any light accessories.  Anyone has similar issue?

**Comment by kenderson** [comment]
Same issue here. +1 for support on this!

Some of the ground work may be  done here: https://gist.github.com/hardillb/1279241bb886ee28c05b

**Comment by nfarina** [comment]
Hey guys, sorry for the fake out - I did add support for "Light" type but that just makes a HomeKit Lightbulb out of a WeMo switch. I don't own any actual WeMo bulbs so I'm not sure how they work.

**Comment by ttgolf** [comment]
Looks like someone will have to build a "platform" for this since Wemo bridge (Wemo Link) is involved.  I have not programmed anything for a while.  Will look into it.  Also hope someone can help.

**Comment by kenderson** [comment]
@ttgolf - Although I'm not super technical, I'm in for helping whereever possible.

**Comment by syncmac** [comment]
I would also love the addition for the Wemo Link bulbs! Being able to tell Siri to turn them on or dim them would be awesome. You guys are great, thank you all!!

**Comment by ntollemache** [comment]
Hi all,

I'd also like this feature. Am happy to work on it, anyone else like to contribute?

**Comment by ttgolf** [comment]
Let me know what u need. I just don't have time to get this started. Hope you can help out the community

**Comment by kenderson** [comment]
Hi All! I'm just checking in here - let me know if anyone has made any progress or wants to get started!

**Comment by rudders** [comment]
I'm having a hack at it currently and could provide some clues. I'm porting homebridge-wemo to use wemo-client instead go node-wemo which doesn't support enddevices. Got stuck in the foibles of async callbacks (i.e I disappeared up my own code oriface) Happy to share....

**Comment by rudders** [comment]
Have a look at this https://github.com/rudders/homebridge-wemo2 - the WeMoAccessory.prototype.search is a cluster .... javascript is not my native language.....

**Comment by rudders** [comment]
So I've discovered an unfortunate reality with the WEMO lights. They are not visible to the PNP SSDP discovery process if the lights are off. This means that based on the current architecture of the plugin if the light/bulb is off when homebridge initiates the module the lights will never be found. I'm going to make wemo2 module take hard coded ids to circumvent this issue for now to get it to work and then look to make a command live the gist @nfarina mentioned above which I had also found.

**Comment by IMNotMax** [comment]
You certainly can close this issue, the homebridge-platform-wemo created by @rudders works like a charm !

**Comment by rudders** [comment]
I'm not 100% happy with Link discovery so am looking for ways to make it more robust. Sometimes requires a few restarts of Homebridge to find them I've found.

**Comment by AppleTechy** [comment]
rudders/homebridge-platform-wemo#17
I am going to close this issue and any new comments please be made at the one above.

**Comment by bradbiss** [comment]
Absolutely loving the homebridge functionality using the WeMo plugs. Good Work @nfarina 

I too have the Wemo Link with 2 x Lightbulbs in a group. Being able to control these using siri would be amazing. Power options would be fantastic, adjusting the brightness would be immense

Any update on when you may be getting into this? if at all.

Thanks again

**Comment by rudders** [comment]
@bradbiss - is you question specifically about controlling a group's brightness or individual bulb's brightness?

**Comment by bradbiss** [comment]
@rudders hello! 

It was about not just getting homebridge to see the wemo link but being able to control 'wemo app' specific settings. Such as brightness and dimming. 

At the moment my homebridge will only 'see' the wemo plugs I have on the LAN. 

Tried all sorts of different names for the wemo link and it's connected bulbs (there are two currently) in my config file to no avail. 

Running sudo homebridge in terminal identifies my plugs but will not find the wemo link and/or their respective bulbs. I get a timeout message when attempting to identify after running the program. 

I've hunted high and low for a wemo link plugin which doesn't seem to be available as of yet. I do appreciate you guys are doing this in your own time. 

I'm over the moon already at getting my wemo devices working with HomeKit 'non native' made possible by homebridge. Don't really want to get any Phillips hue bulbs as I already have WeMo's

So in answer to your question - getting homebridge to see my wemo link and my grouped bulbs, in addition to being able to control brightness with Siri would be fantastic. 

Brad

**Comment by rudders** [comment]
Are you using Homebridge-platform-wemo plugin? Homebridge-wemo does not support link/bulb.

Can you post the log from starting Homebridge please.

**Comment by rudders** [comment]
https://github.com/rudders/homebridge-platform-wemo

**Comment by bradbiss** [comment]
Hi Rudders,

apologies for delay in getting back to you. Been a little busy.

Installed platform-wemo. Works an absolute treat, Thanks very much for your help.

Kind Regards

Brad
