### ISSUE TITLE
Adding homebridge into iOS (Eve) fails after input of code

### ISSUE THREAD

**Issue by neonightmare** [nfarina/homebridge#247]
Hi, i made an update with git pull to the newest version. Homebridge-server runs. I deleted /persist and changed the name and username already. I can see the homebridge on iOS and can start the coupling. After input of the key the error message occurs  „Hinzufügen fehlgeschlagen Verbindung mit Zubehör nicht möglich“  an after this, the homebridge disappears in the search/App,

 ```
pi@raspberrypi ~/homebridge $ npm run start
  
  > homebridge@0.1.1 start /home/pi/homebridge
  > DEBUG=* node app.js || true
  
  *** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
  *** WARNING *** Please fix your application to use the native API of Avahi!
  *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
  *** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
  *** WARNING *** Please fix your application to use the native API of Avahi!
  *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
  Starting HomeBridge server...
  _____________________________________________________________________
  IMPORTANT: Homebridge is in the middle of some big changes.
             Read more about it here:
             https://github.com/nfarina/homebridge/wiki/Migration-Guide
  _____________________________________________________________________
  
  Loading 2 platforms...
  [undefined] Initializing YamahaAVR platform...
  [undefined] Getting Yamaha AVR devices.
  [KNX] Initializing KNX platform...
  [KNX] Fetching KNX devices.
  [KNX] parsing acc 0 of 1
  [KNX] push new universal device Werkstatt
  [KNX] Accessory constructor called
  [KNX] created Werkstatt universal accessory
  [KNX] returning 1 accessories
  [KNX] Initializing platform accessory 'Werkstatt'...
  [KNX] Preparing Services: 5
  [KNX] Preparing Service: 0 of type Lightbulb
  [KNX] [Werkstatt]:Lightbulb on/off characteristic enabled
  [KNX] knx registering BOOLEAN 0/0/1
  [KNX] [Werkstatt]:[On]: Issuing read requests on the KNX bus...
  [KNX] [knxdevice:knxread] preparing knx request for 0/0/1
  [KNX] Preparing Service: 1 of type Lightbulb
  [KNX] [Werkstatt]:Lightbulb on/off characteristic enabled
  [KNX] knx registering BOOLEAN 0/0/2
  [KNX] [Werkstatt]:[On]: Issuing read requests on the KNX bus...
  [KNX] [knxdevice:knxread] preparing knx request for 0/0/2
  [KNX] Preparing Service: 2 of type Thermostat
  [KNX] [Werkstatt]:Thermostat CurrentTemperature characteristic enabled
  [KNX] [Werkstatt]:[Current Temperature]:knx registering FLOAT ,0/0/6
  [KNX] [Werkstatt]:[Current Temperature]: Issuing read requests on the KNX bus...
  [KNX] [knxdevice:knxread] preparing knx request for 0/0/6
  [KNX] [Werkstatt]:Thermostat TargetTemperature characteristic enabled
  [KNX] [Werkstatt]:[Target Temperature]:knx registering FLOAT 0/0/7
  [KNX] [Werkstatt]:[Target Temperature]: Issuing read requests on the KNX bus...
  [KNX] [knxdevice:knxread] preparing knx request for 0/0/7
  [KNX] [Werkstatt]:Thermostat CurrentHeatingCoolingState characteristic enabled
  [KNX] [Werkstatt]:[Current Heating Cooling State]:knx registering HVAC ,0/0/8
  [KNX] [Werkstatt]:[Current Heating Cooling State]: Issuing read requests on the KNX bus...
  [KNX] [knxdevice:knxread] preparing knx request for 0/0/8
  [KNX] Preparing Service: 3 of type TemperatureSensor
  [KNX] [Werkstatt]:TemperatureSensor CurrentTemperature characteristic enabled
  [KNX] [Werkstatt]:[Current Temperature]:knx registering FLOAT ,2/0/0
  [KNX] [Werkstatt]:[Current Temperature]: Issuing read requests on the KNX bus...
  [KNX] [knxdevice:knxread] preparing knx request for 2/0/0
  [KNX] Preparing Service: 4 of type TemperatureSensor
  [KNX] [Werkstatt]:TemperatureSensor CurrentTemperature characteristic enabled
  [KNX] [Werkstatt]:[Current Temperature]:knx registering FLOAT ,2/0/1
  [KNX] [Werkstatt]:[Current Temperature]: Issuing read requests on the KNX bus...
  [KNX] [knxdevice:knxread] preparing knx request for 2/0/1
  >>> knxd groupsocketlisten starting <<<
  Loading 2 accessories...
  [Relais 1] Initializing Http accessory...
  [Relais 2] Initializing Http accessory...
  [KNX] [knxdevice:knxread] knx request sent for 0/0/1
  [KNX] [knxdevice:knxread] knx request sent for 0/0/2
  [KNX] [knxdevice:knxread] knx request sent for 0/0/6
  [KNX] [knxdevice:knxread] knx request sent for 0/0/7
  [KNX] [knxdevice:knxread] knx request sent for 0/0/8
  [KNX] [knxdevice:knxread] knx request sent for 2/0/0
  [KNX] [knxdevice:knxread] knx request sent for 2/0/1
  [KNX] [Werkstatt]: Received value from bus:0 for 0/0/1 from 1.1.1 of type DPT1 for On
  [undefined] Found Yamaha RX-V2067 - 0BF249F3, "Yamaha"
  [undefined] Waited 30 seconds, stopping discovery.
  [undefined] Discovery finished, found 1 Yamaha AVR devices.
  [undefined] Initializing platform accessory 'Yamaha'...
  Scan this code with your HomeKit App on your iOS device:
  
      ┌────────────┐     
      │ 031-45-154 │     
      └────────────┘     
  
    Accessory [Homebridge-04] Creating new AccessoryInfo for our HAP server +0ms
    Accessory [Homebridge-04] Creating new IdentifierCache +43ms
    EventedHTTPServer Server listening on port 51826 +160ms
    YamahaAVR Got volume percent of 22% +1s
    EventedHTTPServer [192.168.1.106] New connection from client +44s
    EventedHTTPServer [192.168.1.106] HTTP server listening on port 54826 +7ms
    EventedHTTPServer [192.168.1.106] HTTP request: /pair-setup +26ms
    HAPServer [CC:22:3D:E3:CE:38] HAP Request: POST /pair-setup +2ms
    HAPServer [CC:22:3D:E3:CE:38] Pair step 1/5 +11ms
    EventedHTTPServer [192.168.1.106] HTTP Repsonse is finished +235ms
    EventedHTTPServer [192.168.1.106] HTTP request: /pair-setup +13s
    HAPServer [CC:22:3D:E3:CE:38] HAP Request: POST /pair-setup +1ms
    HAPServer [CC:22:3D:E3:CE:38] Pair step 2/5 +5ms
    EventedHTTPServer [192.168.1.106] HTTP Repsonse is finished +231ms
    EventedHTTPServer [192.168.1.106] HTTP request: /pair-setup +59ms
    HAPServer [CC:22:3D:E3:CE:38] HAP Request: POST /pair-setup +0ms
    HAPServer [CC:22:3D:E3:CE:38] Pair step 3/5 +4ms
    HAPServer [CC:22:3D:E3:CE:38] Pair step 4/5 +57ms
    HAPServer [CC:22:3D:E3:CE:38] Pair step 5/5 +11ms
    Accessory [Homebridge-04] Paired with client 159F473E-85D6-467A-89F6-768696505202 +19ms
    EventedHTTPServer [192.168.1.106] HTTP Repsonse is finished +39ms
    EventedHTTPServer [192.168.1.106] Client connection closed +134ms
    EventedHTTPServer [192.168.1.106] New connection from client +16ms
    EventedHTTPServer [192.168.1.106] HTTP server listening on port 54827 +2ms
    EventedHTTPServer [192.168.1.106] HTTP connection was closed +9ms
    EventedHTTPServer [192.168.1.106] HTTP server was closed +4ms
    EventedHTTPServer [192.168.1.106] HTTP request: /pair-verify +8ms
    HAPServer [CC:22:3D:E3:CE:38] HAP Request: POST /pair-verify +3ms
    HAPServer [CC:22:3D:E3:CE:38] Pair verify step 1/2 +11ms
    EventedHTTPServer [192.168.1.106] HTTP Repsonse is finished +33ms
    EventedHTTPServer [192.168.1.106] HTTP request: /pair-verify +22ms
    HAPServer [CC:22:3D:E3:CE:38] HAP Request: POST /pair-verify +2ms
    HAPServer [CC:22:3D:E3:CE:38] Pair verify step 2/2 +5ms
    HAPServer [CC:22:3D:E3:CE:38] Client 159F473E-85D6-467A-89F6-768696505202 verification complete +16ms
    EventedHTTPServer [192.168.1.106] HTTP Repsonse is finished +4ms
    EventedHTTPServer [192.168.1.106] HTTP request: /accessories +19ms
    HAPServer [CC:22:3D:E3:CE:38] HAP Request: GET /accessories +1ms
    EventedHTTPServer [192.168.1.106] HTTP Repsonse is finished +22ms
    EventedHTTPServer [192.168.1.106] Client connection closed +152ms
    EventedHTTPServer [192.168.1.106] HTTP connection was closed +3ms
    EventedHTTPServer [192.168.1.106] HTTP server was closed +2ms
```

any idea? thx neo

**Comment by KhaosT** [comment]
Normally this is caused by one or more characteristics are out of bounds which made iOS to think accessory is misbehaving. Please make sure all characteristics are within the valid value range.

**Comment by neonightmare** [comment]
OK, thx for the hint, the problem was the manual IP for the platform Yamaha, seems there is still a problem based on (closed) issue #224.

@SphtKr  // my test was probably not complete...

**Comment by SphtKr** [comment]
Okay, interesting...it could be that another change on master created a problem for YamahaAVR. I'll check out the latest and test it here. Can you attach the contents of `http://your-rpi:51826/accessories` or at least the YamahaAVR accessory part of it?

**Comment by neonightmare** [comment]
Hi, here the file as u wished:
```
{"accessories":[{"aid":1,"services":[{"iid":1,"type":"0000003E-0000-1000-8000-0026BB765291","characteristics":[{"iid":2,"type":"00000014-0000-1000-8000-0026BB765291","perms":["pw"],"format":"bool","description":"Identify"},{"iid":3,"type":"00000020-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Default-Manufacturer","description":"Manufacturer"},{"iid":4,"type":"00000021-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Default-Model","description":"Model"},{"iid":5,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Homebridge","description":"Name"},{"iid":6,"type":"00000030-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Default-SerialNumber","description":"Serial Number"}]}]},{"aid":2,"services":[{"iid":1,"type":"0000003E-0000-1000-8000-0026BB765291","characteristics":[{"iid":2,"type":"00000014-0000-1000-8000-0026BB765291","perms":["pw"],"format":"bool","description":"Identify"},{"iid":3,"type":"00000020-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Opensource Community","description":"Manufacturer"},{"iid":4,"type":"00000021-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"KNX Universal Device","description":"Model"},{"iid":5,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Werkstatt","description":"Name"},{"iid":6,"type":"00000030-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Version 1.1.4","description":"Serial Number"}]},{"iid":7,"type":"00000043-0000-1000-8000-0026BB765291","characteristics":[{"iid":8,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Werkstatt Deckenlicht","description":"Name"},{"iid":9,"type":"00000025-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"bool","value":0,"description":"On"}]},{"iid":10,"type":"00000043-0000-1000-8000-0026BB765291","characteristics":[{"iid":11,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Werkstatt Werkbanklicht","description":"Name"},{"iid":12,"type":"00000025-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"bool","value":0,"description":"On"}]},{"iid":13,"type":"0000004A-0000-1000-8000-0026BB765291","characteristics":[{"iid":14,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Raumtemperatur","description":"Name"},{"iid":15,"type":"0000000F-0000-1000-8000-0026BB765291","perms":["pr","ev"],"format":"uint8","value":0,"description":"Current Heating Cooling State"},{"iid":16,"type":"00000033-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"uint8","value":0,"description":"Target Heating Cooling State"},{"iid":17,"type":"00000011-0000-1000-8000-0026BB765291","perms":["pr","ev"],"format":"float","value":0,"description":"Current Temperature","unit":"celsius","maxValue":60,"minValue":-40,"minStep":0.1},{"iid":18,"type":"00000035-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"float","value":10,"description":"Target Temperature","unit":"celsius","maxValue":40,"minValue":0,"minStep":0.1},{"iid":19,"type":"00000036-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"uint8","value":0,"description":"Temperature Display Units"}]},{"iid":20,"type":"0000008A-0000-1000-8000-0026BB765291","characteristics":[{"iid":21,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Arduino Temperatur","description":"Name"},{"iid":22,"type":"00000011-0000-1000-8000-0026BB765291","perms":["pr","ev"],"format":"float","value":0,"description":"Current Temperature","unit":"celsius","maxValue":60,"minValue":-40,"minStep":0.1}]},{"iid":23,"type":"0000008A-0000-1000-8000-0026BB765291","characteristics":[{"iid":24,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Arduino Feuchte","description":"Name"},{"iid":25,"type":"00000011-0000-1000-8000-0026BB765291","perms":["pr","ev"],"format":"float","value":0,"description":"Current Temperature","unit":"celsius","maxValue":60,"minValue":-40,"minStep":0.1}]}]},{"aid":3,"services":[{"iid":1,"type":"0000003E-0000-1000-8000-0026BB765291","characteristics":[{"iid":2,"type":"00000014-0000-1000-8000-0026BB765291","perms":["pw"],"format":"bool","description":"Identify"},{"iid":3,"type":"00000020-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"HTTP Manufacturer","description":"Manufacturer"},{"iid":4,"type":"00000021-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"HTTP Model","description":"Model"},{"iid":5,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Relais 1","description":"Name"},{"iid":6,"type":"00000030-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"HTTP Serial Number","description":"Serial Number"}]},{"iid":7,"type":"00000043-0000-1000-8000-0026BB765291","characteristics":[{"iid":8,"type":"00000025-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"bool","value":0,"description":"On"},{"iid":9,"type":"00000008-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"int","value":0,"description":"Brightness","unit":"percentage","maxValue":100,"minValue":0,"minStep":1}]}]},{"aid":4,"services":[{"iid":1,"type":"0000003E-0000-1000-8000-0026BB765291","characteristics":[{"iid":2,"type":"00000014-0000-1000-8000-0026BB765291","perms":["pw"],"format":"bool","description":"Identify"},{"iid":3,"type":"00000020-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"HTTP Manufacturer","description":"Manufacturer"},{"iid":4,"type":"00000021-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"HTTP Model","description":"Model"},{"iid":5,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Relais 2","description":"Name"},{"iid":6,"type":"00000030-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"HTTP Serial Number","description":"Serial Number"}]},{"iid":7,"type":"00000043-0000-1000-8000-0026BB765291","characteristics":[{"iid":8,"type":"00000025-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"bool","value":0,"description":"On"},{"iid":9,"type":"00000008-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"int","value":0,"description":"Brightness","unit":"percentage","maxValue":100,"minValue":0,"minStep":1}]}]}]}
```

**Comment by SphtKr** [comment]
@neonightmare The link there isn't working for me...is it correct?

So I updated to master and ran it here. Erm...I see the problem but I don't know why. In the custom Service/Characteristic `AudioVolume` I added, there is no value, which causes compliance to fail...but there's no value because `format` is `null`, even though my characteristic specifies `format` as `uint8`...and therefore (I'm inferring) `getDefaultValue()` fails, because it relies on `format`... @nfarina , any idea why my `format` property in my custom Characteristic isn't making it through?

**Comment by SphtKr** [comment]
OH...my...significant API change. That'll teach me to merge master and test before committing (I'm fuzzy on standard procedure for when to merge master manually). I'll look at this in the morning, but I'm sure I can fix it quickly.

**Comment by neonightmare** [comment]
here the content, link is broken, sorry;

{"accessories":[{"aid":1,"services":[{"iid":1,"type":"0000003E-0000-1000-8000-0026BB765291","characteristics":[{"iid":2,"type":"00000014-0000-1000-8000-0026BB765291","perms":["pw"],"format":"bool","description":"Identify"},{"iid":3,"type":"00000020-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Default-Manufacturer","description":"Manufacturer"},{"iid":4,"type":"00000021-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Default-Model","description":"Model"},{"iid":5,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Homebridge","description":"Name"},{"iid":6,"type":"00000030-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Default-SerialNumber","description":"Serial Number"}]}]},{"aid":2,"services":[{"iid":1,"type":"0000003E-0000-1000-8000-0026BB765291","characteristics":[{"iid":2,"type":"00000014-0000-1000-8000-0026BB765291","perms":["pw"],"format":"bool","description":"Identify"},{"iid":3,"type":"00000020-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Opensource Community","description":"Manufacturer"},{"iid":4,"type":"00000021-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"KNX Universal Device","description":"Model"},{"iid":5,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Werkstatt","description":"Name"},{"iid":6,"type":"00000030-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Version 1.1.4","description":"Serial Number"}]},{"iid":7,"type":"00000043-0000-1000-8000-0026BB765291","characteristics":[{"iid":8,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Werkstatt Deckenlicht","description":"Name"},{"iid":9,"type":"00000025-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"bool","value":0,"description":"On"}]},{"iid":10,"type":"00000043-0000-1000-8000-0026BB765291","characteristics":[{"iid":11,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Werkstatt Werkbanklicht","description":"Name"},{"iid":12,"type":"00000025-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"bool","value":0,"description":"On"}]},{"iid":13,"type":"0000004A-0000-1000-8000-0026BB765291","characteristics":[{"iid":14,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Raumtemperatur","description":"Name"},{"iid":15,"type":"0000000F-0000-1000-8000-0026BB765291","perms":["pr","ev"],"format":"uint8","value":0,"description":"Current Heating Cooling State"},{"iid":16,"type":"00000033-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"uint8","value":0,"description":"Target Heating Cooling State"},{"iid":17,"type":"00000011-0000-1000-8000-0026BB765291","perms":["pr","ev"],"format":"float","value":0,"description":"Current Temperature","unit":"celsius","maxValue":60,"minValue":-40,"minStep":0.1},{"iid":18,"type":"00000035-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"float","value":10,"description":"Target Temperature","unit":"celsius","maxValue":40,"minValue":0,"minStep":0.1},{"iid":19,"type":"00000036-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"uint8","value":0,"description":"Temperature Display Units"}]},{"iid":20,"type":"0000008A-0000-1000-8000-0026BB765291","characteristics":[{"iid":21,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Arduino Temperatur","description":"Name"},{"iid":22,"type":"00000011-0000-1000-8000-0026BB765291","perms":["pr","ev"],"format":"float","value":0,"description":"Current Temperature","unit":"celsius","maxValue":60,"minValue":-40,"minStep":0.1}]},{"iid":23,"type":"0000008A-0000-1000-8000-0026BB765291","characteristics":[{"iid":24,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Arduino Feuchte","description":"Name"},{"iid":25,"type":"00000011-0000-1000-8000-0026BB765291","perms":["pr","ev"],"format":"float","value":0,"description":"Current Temperature","unit":"celsius","maxValue":60,"minValue":-40,"minStep":0.1}]}]},{"aid":3,"services":[{"iid":1,"type":"0000003E-0000-1000-8000-0026BB765291","characteristics":[{"iid":2,"type":"00000014-0000-1000-8000-0026BB765291","perms":["pw"],"format":"bool","description":"Identify"},{"iid":3,"type":"00000020-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"HTTP Manufacturer","description":"Manufacturer"},{"iid":4,"type":"00000021-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"HTTP Model","description":"Model"},{"iid":5,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Relais 1","description":"Name"},{"iid":6,"type":"00000030-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"HTTP Serial Number","description":"Serial Number"}]},{"iid":7,"type":"00000043-0000-1000-8000-0026BB765291","characteristics":[{"iid":8,"type":"00000025-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"bool","value":0,"description":"On"},{"iid":9,"type":"00000008-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"int","value":0,"description":"Brightness","unit":"percentage","maxValue":100,"minValue":0,"minStep":1}]}]},{"aid":4,"services":[{"iid":1,"type":"0000003E-0000-1000-8000-0026BB765291","characteristics":[{"iid":2,"type":"00000014-0000-1000-8000-0026BB765291","perms":["pw"],"format":"bool","description":"Identify"},{"iid":3,"type":"00000020-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"HTTP Manufacturer","description":"Manufacturer"},{"iid":4,"type":"00000021-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"HTTP Model","description":"Model"},{"iid":5,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Relais 2","description":"Name"},{"iid":6,"type":"00000030-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"HTTP Serial Number","description":"Serial Number"}]},{"iid":7,"type":"00000043-0000-1000-8000-0026BB765291","characteristics":[{"iid":8,"type":"00000025-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"bool","value":0,"description":"On"},{"iid":9,"type":"00000008-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"int","value":0,"description":"Brightness","unit":"percentage","maxValue":100,"minValue":0,"minStep":1}]}]}]}
