### ISSUE TITLE
Did anyone found the right procedure to install HomeBridge on Windows ?

### ISSUE THREAD

**Issue by stipus** [nfarina/homebridge#250]
I installed Homebridge on a Mac without any problem, but I want to move it to an always-on windows server.

So far I tried:
- install python 2.7.10
- install Visual Studio Express 2013
- install GIT
- install Bonjour SDK for Windows
- install open-ssl that was needed for one of the packages
- install Node.js
- install Homebridge

But pm install still fails !

We (as a group of HomeSeer users on the homeseer forum) have been trying for several days without any success !

Any idea ?

**Comment by jmvanbuskirk** [comment]
I'd like to know this too. I can successfully install after cloning, but when I try to run it fails.

**Comment by firewlf** [comment]
I too would like to know about this. Stipus - I have been following what you have been doing on the homeseer forum, good stuff!!  Just now need to get it working on windows. ha! :)

**Comment by stipus** [comment]
To reduce dependencies, I have been trying to remove all platforms except PhilipsHue and HomeSeer, then I removed most dependencies from homebridge/package.json
Unfortunately, the Windows computer on which I tried this is an old Windows 2003 server with Visual Studio 2010, and I got errors stating I needed a C++11 compiler for some modules...
Still stuck....

**Comment by malosaa** [comment]
im stuck also on this , 
i installed all from above , and buildtools , and updated everything etc, 

this is the message where im stuck :


npm ERR! curve25519@1.1.0 install: `node-gyp rebuild` 
npm ERR! Exit status 1 
npm ERR! 
npm ERR! Failed at the curve25519@1.1.0 install script. 
npm ERR! This is most likely a problem with the curve25519 package, 
npm ERR! not with npm itself. 
npm ERR! Tell the author that this fails on your system: 
npm ERR!     node-gyp rebuild 
npm ERR! You can get their info via: 
npm ERR!     npm owner ls curve25519 
npm ERR! There is likely additional logging output above. 
npm ERR! System Windows_NT 6.1.7601 
npm ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej 
s\\node_modules\\npm\\bin\\npm-cli.js" "install" 
npm ERR! cwd C:\Users\Home Security System\Desktop\homebridge 
npm ERR! node -v v4.2.1 
npm ERR! npm -v 1.4.28 
npm ERR! code ELIFECYCLE 
npm ERR! not ok code 0

**Comment by stipus** [comment]
As far as I know, one of the HomeSeer board user successfully compiled homebridge on a win32 computer. He wrote he is going to create a ZIP, so that everyone can install the compiled version.
On my side, I have been trying for hours with no success.

**Comment by malosaa** [comment]
ah , isee willems is gonna release it , but i dont know if its x64 or x86 , we will see

**Comment by iDVB** [comment]
Has anyone gotten this working on Windows? I've followed the directions to the letter. 
I'm running Windows 10 64bit and have installed all things 32bit, except for Bonjour as that did not seem to give me an option.

I'm getting the error when I `npm install -g homebridge` ...
```
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\Win32\PlatformToolsets\v140\Toolset.targets(34,5): 
error MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution".
```

**Comment by iDVB** [comment]
- UPDATE - 
Figured it out...needed to open Visual Studio and install the Windows SDK 8.1 by trying to start a new C++ project.

**Comment by prbreezy** [comment]
We should update the tutorial and say at the step : 
Step 3: Configuration Visual Studio
1 - Open Visual Studio Community and create a C++ Project to install "dev environment"

And add "Verify that the The Windows SDK version 8.1 is selected"

Link: https://github.com/nfarina/homebridge/wiki/Install-homebridge-on-Windows

This is just a suggestion..
