### ISSUE TITLE
Harmony Causes Failure to Start

### ISSUE THREAD

**Issue by lessphiling** [nfarina/homebridge#255]
Hello-

When I have Harmony in my config file homebridge won't start, if I remove it, it starts just fine. Below is the output I'm getting.

> homebridge@0.1.1 start /home/phil/homebridge
> DEBUG=* node app.js || true

*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
Starting HomeBridge server...
_____________________________________________________________________
IMPORTANT: Homebridge is in the middle of some big changes.
           Read more about it here:
           https://github.com/nfarina/homebridge/wiki/Migration-Guide
_____________________________________________________________________

Loading 2 platforms...
[Nest] Initializing Nest platform...
[Nest] Fetching Nest devices.
  node-stringprep Cannot load StringPrep-0.7.2 bindings (using fallback). You may need to `npm install node-stringprep` +0ms
  node-stringprep Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (/home/phil/homebridge/node_modules/harmonyhubjs-client/node_modules/node-xmpp-client/node_modules/node-xmpp-core/node_modules/node-stringprep/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/home/phil/homebridge/node_modules/harmonyhubjs-client/node_modules/node-xmpp-client/node_modules/node-xmpp-core/node_modules/node-stringprep/index.js:10:39)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32) +2ms
  node-stringprep Cannot load StringPrep-0.7.2 bindings (using fallback). You may need to `npm install node-stringprep` +0ms
  node-stringprep Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (/home/phil/homebridge/node_modules/harmonyhubjs-client/node_modules/node-xmpp-core/node_modules/node-stringprep/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/home/phil/homebridge/node_modules/harmonyhubjs-client/node_modules/node-xmpp-core/node_modules/node-stringprep/index.js:10:39)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32) +0ms
[Living Room Harmony Hub] Initializing LogitechHarmony platform...
[Living Room Harmony Hub] Searching for Logitech Harmony remote hubs...
  harmonyhubjs:discover:explorer Explorer(61991) +0ms
  harmonyhubjs:discover:ping Ping(61991) +2ms
  harmonyhubjs:discover:explorer start() +0ms
  harmonyhubjs:discover:responsecollector ResponseCollector(61991) +1ms
  harmonyhubjs:discover:responsecollector start() +0ms
  harmonyhubjs:discover:ping start() +17ms
Loading 1 accessories...
[Patio Lights] Initializing WeMo accessory...
[Patio Lights] Searching for WeMo device with exact name 'Patio Lights'...
  harmonyhubjs:discover:ping emit() +1s
  harmonyhubjs:discover:responsecollector handle new connection +591ms
  harmonyhubjs:discover:responsecollector received data chunk +4ms
  harmonyhubjs:discover:responsecollector connection closed. emitting data. +1ms
  harmonyhubjs:discover:explorer discovered new hub Living Room Harmony Hub +1ms
[Living Room Harmony Hub] Found Logitech Harmony remote hub: 10.0.1.26
  harmonyhubjs:discover:explorer stop() +0ms
  harmonyhubjs:discover:ping stop() +0ms
  harmonyhubjs:discover:responsecollector stop() +0ms
[Living Room Harmony Hub] Connecting to Logitech Harmony remote hub...
  harmonyhubjs:client:login login on hub 10.0.1.26 +1ms
  harmonyhubjs:client:login:hub perform hub login +0ms
  harmonyhubjs:client:login:hub retrieve identity by logging in as guest +0ms
  node-stringprep Operation does not exist +5s nodeprep [TypeError: Cannot read property 'StringPrep' of undefined]
  node-stringprep Operation does not exist +1ms resourceprep [TypeError: Cannot read property 'StringPrep' of undefined]
  node-stringprep Operation does not exist +0ms nameprep [TypeError: Cannot read property 'StringPrep' of undefined]
  xmpp:client:session start socket connection +0ms
  xmpp:connection setup socket +0ms
  xmpp:connection use lazy socket +1ms
  xmpp:connection setup stream +1ms
  xmpp:connection send: <stream:stream xmlns="jabber:client" xmlns:stream="http://etherx.jabber.org/streams" version="1.0" to="x.com"> +7ms
  xmpp:connection receive: <?xml version='1.0' encoding='iso-8859-1'?><stream:stream from='x.com' id='0d2b5891' version='1.0' xmlns='jabber:client' xmlns:stream='http://etherx.jabber.org/streams'><stream:features><mechanisms xmlns='urn:ietf:params:xml:ns:xmpp-sasl'><mechanism>PLAIN</mechanism></mechanisms></stream:features> +17ms
  node-stringprep Operation does not exist +31ms nodeprep [TypeError: Cannot read property 'StringPrep' of undefined]
  node-stringprep Operation does not exist +0ms nameprep [TypeError: Cannot read property 'StringPrep' of undefined]
  xmpp:connection send: <auth xmlns="urn:ietf:params:xml:ns:xmpp-sasl" mechanism="PLAIN">Z3Vlc3RAeC5jb20AZ3Vlc3QAZ3Vlc3Q=</auth> +3ms
  xmpp:connection receive: <success xmlns='urn:ietf:params:xml:ns:xmpp-sasl'/> +16ms
  xmpp:connection send: <stream:stream xmlns="jabber:client" xmlns:stream="http://etherx.jabber.org/streams" version="1.0" to="x.com"> +1ms
  xmpp:connection receive: <stream:stream from='x.com' id='0d2b5891' version='1.0' xmlns='jabber:client' xmlns:stream='http://etherx.jabber.org/streams'><stream:features><bind xmlns='urn:ietf:params:xml:ns:xmpp-bind'/><session xmlns='urn:ietf:params:xml:nx:xmpp-session'/></stream:features> +13ms
  xmpp:connection send: <bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"><resource>gatorade</resource></bind> +1ms
  xmpp:connection receive: <iq id='bind' type='result'><bind xmlns='urn:ietf:params:xml:ns:xmpp-bind'><jid>1111/gatorade</jid></bind></iq> +9ms
  node-stringprep Operation does not exist +40ms resourceprep [TypeError: Cannot read property 'StringPrep' of undefined]
  node-stringprep Operation does not exist +1ms nameprep [TypeError: Cannot read property 'StringPrep' of undefined]
  harmonyhubjs:client:login:hub XMPP client connected +74ms
  xmpp:connection send: <iq type="get" id="898703" from="guest"><oa xmlns="connect.logitech.com" mime="vnd.logitech.connect/vnd.logitech.pair">method=pair:name=harmonyjs#iOS6.0.1#iPhone</oa></iq> +2ms
  xmpp:connection receive: <iq/> +12ms
  harmonyhubjs:client:login:hub received XMPP stanza: <iq xmlns:stream="http://etherx.jabber.org/streams"/> +13ms
  xmpp:connection receive: <iq id="898703" to="guest" type="get"><oa xmlns='connect.logitech.com' mime='vnd.logitech.connect/vnd.logitech.pair' errorcode='200' errorstring='OK'><![CDATA[serverIdentity=734df069-67bb-4e40-9041-ff95052667c8:hubId=97:identity=734df069-67bb-4e40-9041-ff95052667c8:status=succeeded:protocolVersion={XMPP="1.0", HTTP="1.0", RF="1.0", WEBSOCKET="1.0"}:hubProfiles={Harmony="2.0"}:productId=Pimento:friendlyName=Living Room Harmony Hub]]></oa></iq> +185ms
  harmonyhubjs:client:login:hub received XMPP stanza: <iq id="898703" to="guest" type="get" xmlns:stream="http://etherx.jabber.org/streams"><oa xmlns="connect.logitech.com" mime="vnd.logitech.connect/vnd.logitech.pair" errorcode="200" errorstring="OK"/></iq> +187ms
/home/phil/homebridge/node_modules/harmonyhubjs-client/lib/login/hub.js:63
			if(response.identity && response.identity !== undefined) {
			           ^
TypeError: Cannot read property 'identity' of undefined
    at Client.<anonymous> (/home/phil/homebridge/node_modules/harmonyhubjs-client/lib/login/hub.js:63:15)
    at Client.emit (events.js:107:17)
    at Client.onStanza (/home/phil/homebridge/node_modules/harmonyhubjs-client/node_modules/node-xmpp-client/index.js:224:14)
    at Connection.emit (events.js:107:17)
    at Connection.onStanza (/home/phil/homebridge/node_modules/harmonyhubjs-client/node_modules/node-xmpp-client/node_modules/node-xmpp-core/lib/Connection.js:370:14)
    at StreamParser.<anonymous> (/home/phil/homebridge/node_modules/harmonyhubjs-client/node_modules/node-xmpp-client/node_modules/node-xmpp-core/lib/Connection.js:226:14)
    at StreamParser.emit (events.js:107:17)
    at SaxLtx.<anonymous> (/home/phil/homebridge/node_modules/harmonyhubjs-client/node_modules/node-xmpp-client/node_modules/node-xmpp-core/lib/StreamParser.js:59:22)
    at SaxLtx.emit (events.js:107:17)
    at SaxLtx._handleTagOpening (/home/phil/homebridge/node_modules/harmonyhubjs-client/node_modules/node-xmpp-client/node_modules/node-xmpp-core/node_modules/ltx/lib/parsers/ltx.js:30:18)

**Comment by patrickbusch** [comment]
same here

**Comment by patrickbusch** [comment]
https://github.com/nfarina/homebridge/issues/185#issuecomment-141369530

helped to get it recognized, but I cannot use it because of an error that follows later

**Comment by lessphiling** [comment]
I'm new to this so I'm still not sure what to do, any progress on this?

**Comment by fitzage** [comment]
It's hopefully fixed in #299. Hoping that will get merged in soon.

**Comment by lessphiling** [comment]
Is there a way to know when it's merged?

**Comment by fitzage** [comment]
If you're "following" the repo on github, you should get an email when a pull request is merged in. Along with lots of other emails.

**Comment by KraigM** [comment]
Just merged.  Hope it helps
