### ISSUE TITLE
Install on OSX Yosemite gives Config.Json error

### ISSUE THREAD

**Issue by sirshorty** [nfarina/homebridge#263]
Seem to be having issues starting the HomeBridge server.

I've used the sample config.json file and it still doesn't work, I've also tried stripping out the config to the bare basics (one accessory) 

npm run start

> homebridge@0.1.1 start /Users/HomeServer/homebridge
> DEBUG=* node app.js || true

Starting HomeBridge server...
_____________________________________________________________________
IMPORTANT: Homebridge is in the middle of some big changes.
           Read more about it here:
           https://github.com/nfarina/homebridge/wiki/Migration-Guide
_____________________________________________________________________

There was a problem reading your config.json file.
Please try pasting your config.json file here to validate it: http://jsonlint.com

/Users/HomeServer/homebridge/app.js:43
  throw err;
  ^

SyntaxError: Unexpected token ]
    at Object.parse (native)
    at Object.<anonymous> (/Users/HomeServer/homebridge/app.js:37:17)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3

My config.json file:
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    
    "description": "This is an example configuration file with all supported devices. You can use this as a template for creating your own configuration file containing devices you actually own.",

    "platforms": [
        {
            "platform" : "Nest",
            "name" : "Nest",
            "username" : "username",
            "password" : "password"
        },
        {
            "platform" : "TelldusLive",
            "name" : "Telldus Live!",
            "public_key" : "telldus public key",
            "private_key" : "telldus private key",
            "token" : "telldus token",
            "token_secret" : "telldus token secret"
        },
        {
            "platform" : "Telldus",
            "name" : "Telldus"
        },
        {
            "platform": "Wink",
            "name": "Wink",
            "client_id": "YOUR_WINK_API_CLIENT_ID",
            "client_secret": "YOUR_WINK_API_CLIENT_SECRET",
            "username": "your@email.com",
            "password": "WINK_PASSWORD"
        },
        {
            "platform": "SmartThings",
            "name": "SmartThings",
            "app_id": "JSON SmartApp Id",
            "access_token": "JSON SmartApp AccessToken"
        },
        {
            "platform": "Domoticz",
            "name": "Domoticz",
            "server": "127.0.0.1",
            "port": "8080",
            "roomid": 0,
            "loadscenes": 1
        },
        {
            "platform": "PhilipsHue",
            "name": "Phillips Hue",
            "username": ""
        },
        {
            "platform": "ISY",
            "name": "ISY",
            "host": "192.168.1.20",
            "port": "8000",
            "username": "username",
            "password": "password"
        },
        {
            "platform": "LogitechHarmony",
            "name": "Living Room Harmony Hub"
        },
        {
            "platform": "Sonos",
            "name": "Sonos",
            "play_volume": 25
        },
        {
            "platform": "YamahaAVR",
            "play_volume": -35,
            "setMainInputTo": "AirPlay" 
        },
        {
            "platform": "ZWayServer",
            "url": "http://192.168.1.10:8083/",
            "login": "zwayusername",
            "password": "zwayuserpassword",
            "poll_interval": 2,
            "split_services": false
        },
        {
            "platform": "MiLight",
            "name": "MiLight",
            "ip_address": "255.255.255.255",
            "port": 8899,
            "type": "rgbw",
            "delay": 30,
            "repeat": 3,
            "zones":["Kitchen Lamp","Bedroom Lamp","Living Room Lamp","Hallway Lamp"]
        },
        {
             "platform": "HomeAssistant",
             "name": "HomeAssistant",
             "host": "http://192.168.1.10:8123",
             "password": "XXXXX",
             "supported_types": ["light", "switch", "media_player", "scene"]
        },
        {
            "platform": "LIFx",
            "name": "LIFx",
            "access_token": "XXXXXXXX generate at https://cloud.lifx.com/settings"
        }
    ],

    "accessories": [
                {
            "accessory": "Http",
            "name": "Hall Light",
            "on_url": "http://localhost/api/halllightOn.php",
            "off_url": "http://localhost/api/halllightOff.php",
            "http_method": "POST"

        },

    ]
}

**Comment by stipus** [comment]
1) You should remove all platforms you don't need.
2) Just looking at your file, you have a wrong comma after the first Http accessory

**Comment by tolgraven** [comment]
3) It says right there in the error message, "Please try pasting your config.json file here to validate it: http://jsonlint.com"
Always follow such instructions before opening issues on github

**Comment by dgarozzo** [comment]
I like the idea of the config-sample.json file, however, it should be made much more clear that you can not simply take that file and rename it to config.json and expect it to work. It would be much clearer if there was a working config.json that contains no platforms or accessories, or maybe just one generic one, so Homebridge can at least start up without error.

**Comment by sirshorty** [comment]
Sorry about that - realised that when editing it in Text Edit on Mac it caused the formatting to go all over the place. 
All working now - cheers!
