### ISSUE TITLE
Error With 'DEBUG=* node app.js | | true'

### ISSUE THREAD

**Issue by mdod** [nfarina/homebridge#264]
Here is the error log I got when I tried to run: "npm run start".  The first error listed was with  'DEBUG=* node app.js | | true' from what I can see.  I'm sorry if there is a really simple fix to this.  Thank you for your help.

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start' ]
2 info using npm@2.14.4
3 info using node@v4.1.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart homebridge@0.1.1
6 info start homebridge@0.1.1
7 verbose unsafe-perm in lifecycle true
8 info homebridge@0.1.1 Failed to exec start script
9 verbose stack Error: homebridge@0.1.1 start: `DEBUG=* node app.js || true`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:818:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid homebridge@0.1.1
11 verbose cwd C:\Users\Guest\Documents\GitHub\homebridge
12 error Windows_NT 10.0.10240
13 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
14 error node v4.1.2
15 error npm  v2.14.4
16 error code ELIFECYCLE
17 error homebridge@0.1.1 start: `DEBUG=* node app.js || true`
17 error Exit status 1
18 error Failed at the homebridge@0.1.1 start script 'DEBUG=* node app.js || true'.
18 error This is most likely a problem with the homebridge package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     DEBUG=* node app.js || true
18 error You can get their info via:
18 error     npm owner ls homebridge
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by jmvanbuskirk** [comment]
I'm having the exact same problem, also trying to run on Windows.

**Comment by PatcherMustermann** [comment]
Hello  mdod and jmvanbuskirk.
Look here: https://github.com/nfarina/homebridge/issues/270

Greeting
Patcher
