### ISSUE TITLE
Much errors on x64 Windows 7

### ISSUE THREAD

**Issue by malosaa** [nfarina/homebridge#267]
i dont know what depency's is missing but i installed everything it needed .

need help please 

C:\Users\Home Security System\Desktop\homebridge\node_modules\HAP-NodeJS\node_mo 
dules\srp\node_modules\bignum>node "C:\Program Files\nodejs\node_modules\npm\bin 
\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" configure build 
(node) child_process: options.customFds option is deprecated. Use options.stdio 
instead. 
Building the projects in this solution one at a time. To enable parallel build, 
please add the "/m" switch. 
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.Cpp.Platform.t 
argets(44,5): error MSB8020: The builds tools for v120 (Platform Toolset = 'v12 
0') cannot be found. To build using the v120 build tools, either click the Proj 
ect menu or right-click the solution, and then select "Update VC++ Projects..." 
. Install v120 to build using the v120 build tools. [C:\Users\Home Security Sys 
tem\Desktop\homebridge\node_modules\HAP-NodeJS\node_modules\srp\node_modules\bi 
gnum\build\bignum.vcxproj] 
gyp ERR! build error 
gyp ERR! stack Error: `msbuild` failed with exit code: 1 
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\ 
npm\node_modules\node-gyp\lib\build.js:267:23) 
gyp ERR! stack     at emitTwo (events.js:87:13) 
gyp ERR! stack     at ChildProcess.emit (events.js:172:7) 
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces 
s.js:200:12) 
gyp ERR! System Windows_NT 6.1.7601 
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodej 
s\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "configure" "bui 
ld" 
gyp ERR! cwd C:\Users\Home Security System\Desktop\homebridge\node_modules\HAP-N 
odeJS\node_modules\srp\node_modules\bignum 
gyp ERR! node -v v4.2.1 
gyp ERR! node-gyp -v v1.0.1 
gyp ERR! not ok 

> mdns@2.2.10 install C:\Users\Home Security System\Desktop\homebridge\node_modu 
> les\HAP-NodeJS\node_modules\mdns 
> node-gyp rebuild 

C:\Users\Home Security System\Desktop\homebridge\node_modules\HAP-NodeJS\node_mo 
dules\mdns>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\... 
.\node_modules\node-gyp\bin\node-gyp.js" rebuild 
(node) child_process: options.customFds option is deprecated. Use options.stdio 
instead. 
Building the projects in this solution one at a time. To enable parallel build, 
please add the "/m" switch. 
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.Cpp.Platform.t 
argets(44,5): error MSB8020: The builds tools for v120 (Platform Toolset = 'v12 
0') cannot be found. To build using the v120 build tools, either click the Proj 
ect menu or right-click the solution, and then select "Update VC++ Projects..." 
. Install v120 to build using the v120 build tools. [C:\Users\Home Security Sys 
tem\Desktop\homebridge\node_modules\HAP-NodeJS\node_modules\mdns\build\dns_sd_b 
indings.vcxproj] 
gyp ERR! build error 
gyp ERR! stack Error: `msbuild` failed with exit code: 1 
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\ 
npm\node_modules\node-gyp\lib\build.js:267:23) 
gyp ERR! stack     at emitTwo (events.js:87:13) 
gyp ERR! stack     at ChildProcess.emit (events.js:172:7) 
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces 
s.js:200:12) 
gyp ERR! System Windows_NT 6.1.7601 
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodej 
s\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild" 
gyp ERR! cwd C:\Users\Home Security System\Desktop\homebridge\node_modules\HAP-N 
odeJS\node_modules\mdns 
gyp ERR! node -v v4.2.1 
gyp ERR! node-gyp -v v1.0.1 
gyp ERR! not ok 

> ed25519@0.0.3 install C:\Users\Home Security System\Desktop\homebridge\node_mo 
> dules\HAP-NodeJS\node_modules\ed25519 
> node-gyp rebuild 

C:\Users\Home Security System\Desktop\homebridge\node_modules\HAP-NodeJS\node_mo 
dules\ed25519>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\. 
...\node_modules\node-gyp\bin\node-gyp.js" rebuild 
(node) child_process: options.customFds option is deprecated. Use options.stdio 
instead. 
Building the projects in this solution one at a time. To enable parallel build, 
please add the "/m" switch. 
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.Cpp.Platform.t 
argets(44,5): error MSB8020: The builds tools for v120 (Platform Toolset = 'v12 
0') cannot be found. To build using the v120 build tools, either click the Proj 
ect menu or right-click the solution, and then select "Update VC++ Projects..." 
. Install v120 to build using the v120 build tools. [C:\Users\Home Security Sys 
tem\Desktop\homebridge\node_modules\HAP-NodeJS\node_modules\ed25519\build\ed255 
19.vcxproj] 
gyp ERR! build error 
gyp ERR! stack Error: `msbuild` failed with exit code: 1 
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\ 
npm\node_modules\node-gyp\lib\build.js:267:23) 
gyp ERR! stack     at emitTwo (events.js:87:13) 
gyp ERR! stack     at ChildProcess.emit (events.js:172:7) 
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces 
s.js:200:12) 
gyp ERR! System Windows_NT 6.1.7601 
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodej 
s\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild" 
gyp ERR! cwd C:\Users\Home Security System\Desktop\homebridge\node_modules\HAP-N 
odeJS\node_modules\ed25519 
gyp ERR! node -v v4.2.1 
gyp ERR! node-gyp -v v1.0.1 
gyp ERR! not ok 

npm ERR! curve25519@1.1.0 install: `node-gyp rebuild` 
npm ERR! Exit status 1 
npm ERR! 
npm ERR! Failed at the curve25519@1.1.0 install script. 
npm ERR! This is most likely a problem with the curve25519 package, 
npm ERR! not with npm itself. 
npm ERR! Tell the author that this fails on your system: 
npm ERR!     node-gyp rebuild 
npm ERR! You can get their info via: 
npm ERR!     npm owner ls curve25519 
npm ERR! There is likely additional logging output above. 
npm ERR! System Windows_NT 6.1.7601 
npm ERR! command "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodej 
s\node_modules\npm\bin\npm-cli.js" "install" 
npm ERR! cwd C:\Users\Home Security System\Desktop\homebridge 
npm ERR! node -v v4.2.1 
npm ERR! npm -v 1.4.28 
npm ERR! code ELIFECYCLE 
npm ERR! not ok code 0 

C:\Users\Home Security System\Desktop\homebridge>

**Comment by PatcherMustermann** [comment]
Hello  malosaa.
Look here: https://github.com/nfarina/homebridge/issues/270

Greeting
Patcher

**Comment by malosaa** [comment]
dont work...

**Comment by PatcherMustermann** [comment]
Your answer is not exactly formulated in detail

**Comment by malosaa** [comment]
Hi patcher 

i did everything from the tutorial , and it dont work.... it has to many errors ...
not only me but other people aswell ...

**Comment by PatcherMustermann** [comment]
The complete software modules i have installed with 32bit. You too? 
What error messages do you have?

**Comment by nzhome** [comment]
I have it installed on windows7 32bit and windows7 64bit.. works fine here.

**Comment by malosaa** [comment]
Patcher , i installed x64, and no luck


nzhome , what did u do ? 
many people are trying but no luck

kind regards

**Comment by PatcherMustermann** [comment]
@nzhome: Have you installed after my instructions?

@malosaa: I have a Windows 7 64 bit and the programs I installed with 32bit

**Comment by malosaa** [comment]
ok in installed again all in 32bit 

get this error its the only one 

C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.t
argets(57,5): error MSB8020: The build tools for v120 (Platform Toolset = 'v120
') cannot be found. To build using the v120 build tools, please install v120 bu
ild tools.  Alternatively, you may upgrade to the current Visual Studio tools b
y selecting the Project menu or right-click the solution, and then selecting "R
etarget solution". [C:\Users\Home Security System\Desktop\homebridge\node_modul
es\HAP-NodeJS\node_modules\ed25519\build\ed25519.vcxproj]

**Comment by malosaa** [comment]
i did this 

set VCTargetsPath=C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120

and get this error 

C:\Users\Home Security System\Desktop\homebridge\node_modules\HAP-NodeJS\node_m
odules\ed25519\build\ed25519.vcxproj(20,3): error MSB4019: The imported project
 "C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Default.
props" was not found. Confirm that the path in the <Import> declaration is corr
ect, and that the file exists on disk.

**Comment by malosaa** [comment]
someone created a zipfile for us , you can close the topic

**Comment by boikedamhuis** [comment]
@malosaa Where can I download the *zip file?

**Comment by rcoletti116** [comment]
I'm curious what the resolution to this was. I get the same errors when I try to install. I'm running a 64-bit system, but have installed all the 32-bit versioned software. I followed the install instructions exactly. I see Malosaa mentioned a zip file resolved this issue. Any help is appreciated.

**Comment by malosaa** [comment]
i use a homeseer version , i dont know if u need that version 

http://board.homeseer.com/showpost.php?p=1207987&postcount=402

but i dont use it anymore 

kind regards

**Comment by Bart274** [comment]
if you use the zip file, how can you add more plugins?

**Comment by PatcherMustermann** [comment]
I have update the description for install Homebridge on Windows. WilliamHF have changes the "unistd.h" file, after problems by install Homebridge.

Link: https://github.com/nfarina/homebridge/wiki/Install-Homebridge-on-Windows:-New-version-(with-Plugin)

Greeting
Patcher

**Comment by Bart274** [comment]
it says ctype.h and stddef.h are also missing :s

**Comment by Bart274** [comment]
it finally worked, Visual studio wasn't installed right and I needed to install OpenSSL64 instead of OpenSSL32

**Comment by PatcherMustermann** [comment]
What version of way have you installed?

**Comment by rcoletti116** [comment]
I don't use Homeseer, but I tried installing the Homeseer version Malosaa provided anyway and something still is not right. None of my errors change.

@PatcherMustermann you said you updated the steps of the install. Should I overwrite the old unistd.h with your new version or use the William HF version?

@Bart274 I'm curious how you finally got it working. Did you completely reinstall Visual Studio (if so, what version) and for OpenSSL, did you just install Win32 OpenSSL-64bit?

**Comment by PatcherMustermann** [comment]
@rcoletti116: I'm used my version of "unistd.h". 

My test systems: 
- Windows 7 64Bit
- Windows 10 64Bit

**Comment by rcoletti116** [comment]
I can't seem to get this installed on my machine. 

I seem to have many errors, but the fatal error every attempt is 
'Failed at the mdns@2.2.11 install script. 'node-gyp' rebuild'.

I guess I will wait for proper installation package as is alluded to in roadmap?

**Comment by GreenTurtwig** [comment]
I can't get it installed either :-/
```Failed at the curve25519@1.1.0 install script 'node-gyp rebuild'.```

**Comment by Bart274** [comment]
Try installing openssl64 when following the guide, that worked for me ;)

**Comment by GreenTurtwig** [comment]
I definitely did if you mean selecting the 64bit version on the site. Reinstalled but same error. :-(

**Comment by cswelin** [comment]
I had a similar issue on FreeBSD and ended up being my npm version was out of date.

**Comment by ShadowGraves** [comment]
Just finished getting passed the "npm install -g homebridge" cmd.

following the tutorial, 

1.) opening new vs project to install dev stuff was a little vague, as VS has a lot of unrelated options and checkboxes to muddling things up at that stage,

2.) also had to install openssl-win64 (as the error msg in the log was failing to open "openssl-win64" while I had the 32-bit install. Could the author please update the tutorial to mention that the 64-bit install is a common fix for a relatively vague problem? Hopefully this could save someone else hours. :smile:
