### ISSUE TITLE
HTTP response from owner Software

### ISSUE THREAD

**Issue by PatcherMustermann** [nfarina/homebridge#269]
Hello everybody,
sorry for my bad English. I have a problem with the answer to HTTP commands.

Here is my configuration (config.json):
```
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    
    "description": "This is an example configuration file with all supported devices. You can use this as a template for creating your own configuration file containing devices you actually own.",

    "platforms": [
    ],

    "accessories": [
        {
            "accessory": "Http",
            "name": "Kuechen Lampe 1",
            "on_url": "http://10.0.0.215:3030/devices/23222/on",
            "off_url": "http://10.0.0.215:3030/devices/23222/off",
            "brightness_url": "http://10.0.0.215:3030/devices/23222/brightness/%b",
            "http_method": "POST"
        },
        {
            "accessory": "Http",
            "name": "Wohnzimmer Lampe 1",
            "on_url": "http://10.0.0.215:3030/devices/23223/on",
            "off_url": "http://10.0.0.215:3030/devices/23223/off",
            "brightness_url": "http://10.0.0.215:3030/devices/23223/brightness/%b",
            "http_method": "POST"
        }
    ]
}
```
When I turn on the lamp "Wohnzimmerlampe 1" I get the following answer in my own software:
```
POST /devices/23223/on HTTP/1.1
host: 10.0.0.215:3030
content-length: 0
Connection: close
```

When I turn off the lamp "Wohnzimmerlampe 1" I get the following answer in my own software:
```
POST /devices/23223/off HTTP/1.1
host: 10.0.0.215:3030
content-length: 0
Connection: close
```

I've tested the following answer with no success:
```
HTTP/1.1 200 OK
```

Hence my question: How should a response appearance (in my Software) for HTTP commands?

Many thanks!

**Comment by maddox** [comment]
Does your endpoint expect a GET instead of a POST?

**Comment by PatcherMustermann** [comment]
I have a own Software and i must make the answer self over TCP commands.

**Comment by PatcherMustermann** [comment]
Now i found the Answer:

  String   = HTTP/1.1 " & '200 OK +CRLF
  String &= Server: Apache +CRLF
  String &= Connection: close +CRLF
  String &= Content-Lenght: X-LENGHT: +CRLF
  String &= Content-Type: text/html +CRLF +CRLF
  String &= X-DATA
  String &= +CRLF +CRLF

Legend:
CRLF = Carriage return & line feed
X-LENGHT = Lenght from X-DATA
X-DATA = Data send to homebridge
