### ISSUE TITLE
Vera with others in config.json

### ISSUE THREAD

**Issue by Dax333** [nfarina/homebridge#271]
Vera works when your config file is this:
{
  "VeraIP": "10.0.1.153",
  "PIN": "031-45-154",
  "GarageDoors":[
    "Garage Door",
    "Second Garage Door"
  ]
}

How do I get it to work with this type of config:

{
    "bridge": {
        "name": "Homebridge-vera",
        "username": "CC:22:3D:E3:CE:35",
        "port": 51826,
        "pin": "031-45-154"
    },
    "platforms": [
        {
        "VeraIP": "10.0.1.151",
        "PIN": "031-45-154",
        "GarageDoors":[
            "Garage Door",
            "Second Garage Door"
            ]
        },
                {
               "platform": "YamahaAVR",
               "play_volume": -35,
               "setMainInputTo": "AirPlay" 
               }

```
]
```

}

If I try something like the second I get:

Error: Cannot find module './platforms/undefined.js'

**Comment by stipus** [comment]
You did close the platform list [ ] just before declaring the second platform.

**Comment by Dax333** [comment]
I thought the close bracket is completing the garage door segment.  "GarageDoors":[
"Garage Door",
"Second Garage Door"
]

**Comment by Be2daErtin** [comment]
Hi, I wrote a plugin for the Vera
