### ISSUE TITLE
how to use homebridge with knx

### ISSUE THREAD

**Issue by gjniewenhuijse** [nfarina/homebridge#272]
I have homebridge running on a PI and a KNX system with an KNX IP gateway at 192.168.0.100 port 3671.

How to configure the config.json to use the KNX IP Gateway, i use the following, but it doesn't work:
"knxd_ip": "192.168.0.100", 
"knxd_port": 3671, 

Or is there another way to use my KNX IP Gateway with homebridge?

**Comment by snowdd1** [comment]
You need an knxd running on a computer in your network. You cannot connect to a KNX IP gateway directly. 
See https://github.com/knxd

**Comment by gjniewenhuijse** [comment]
I can't get KNXD running on my PI

 My raspberry:
 Distributor ID: Raspbian
 Description: Raspbian GNU/Linux 8.0 (jessie)
 Release: 8.0
 Codename: jessie

systemctl status knxd.service gives:
 â knxd.service - KNX Daemon
 Loaded: loaded (/lib/systemd/system/knxd.service; disabled)
 Active: activating (auto-restart) (Result: exit-code) since Thu 2015-11-05 09:32:17 UTC; 6s ago
 Process: 21931 ExecStart=/usr/bin/knxd $KNXD_OPTS (code=exited, status=1/FAILURE)
 Main PID: 21931 (code=exited, status=1/FAILURE)

Nov 05 09:32:17 homekit systemd[1]: Unit knxd.service entered failed state.

In /etc/init.d/knxd is changed the following lines:
 DAEMON=/usr/bin/knxd
 DAEMON_ARGS="-c -D -R -T -f9 -S ipt:127.0.0.1 -b ipt:192.168.2.16"
 start-stop-daemon --start --quiet --pidfile $PIDFILE -c $DAEMONUSER --e$ || return 1
 start-stop-daemon --start --quiet --pidfile $PIDFILE -c $DAEMONUSER --e$ -d -p $PIDFILE DAEMON_ARGS || return 2

How to get KNXD working on my PI, or has someone a working image with knxd and homebridge that i can download?

**Comment by nfarina** [comment]
Did you try the [new knx plugin](https://github.com/snowdd1/homebridge-knx)?

**Comment by snowdd1** [comment]
Hi @gjniewenhuijse 
please raise questions for the KNXD or EIBD daemon in the knxd community: https://github.com/knxd/knxd
Installation can become a bit tricky, depending on OS and version. Once the daemon is running and talking to your knx bus, I am happy to help with the homebridge shim/plugin!
