### ISSUE TITLE
Can't use with multiple nest thermostats

### ISSUE THREAD

**Issue by joegrace13** [nfarina/homebridge#280]
With one platform defined:

 {
            "platform" : "Nest",
            "name" : "Nest",
            "username" : "un",
            "password" : "pw"
        }

I get this error:

[Nest] Initializing platform accessory 'Nest'...
[Nest] Initializing platform accessory 'Nest'...

/root/homebridge/node_modules/HAP-NodeJS/lib/Accessory.js:164
      throw new Error("Cannot add a bridged Accessory with the same UUID as an

What can I do to add both of my thermostats?

Tied defining it this way as well with no dice:

 {
            "platform" : "Nest",
            "name" : "Nest1",
            "username" : "un",
            "password" : "pw"
        }
 {
            "platform" : "Nest",
            "name" : "Nes2",
            "username" : "un",
            "password" : "pw"
        }

**Comment by alindeman** [comment]
Try giving each device a different 'label' in the https://home.nest.com application

**Comment by joegrace13** [comment]
You sir are a godsend. Thank you, that worked. I only had them labeled with the location field.
