### ISSUE TITLE
Nest platform does not represent away

### ISSUE THREAD

**Issue by luc-ass** [nfarina/homebridge#281]
Hi,

the Nest platform does not represent "away" or "auto away". They both make it look like the heating is turned off, wich is in fact the case but not the state of the device.

example: 
<img height="300" alt="web-interface" src="https://cloud.githubusercontent.com/assets/3263257/10558107/2bdafca0-74c4-11e5-9a3c-73b363c85813.png"><img height="300" alt="Insteon+ via Homebridge" src="https://cloud.githubusercontent.com/assets/3263257/10558108/316dfa82-74c4-11e5-9748-490e2271a117.jpg">

see how the state of Nest is on "Heat" while the app (Insteon+) does not represent this setting. Also the temperature (which is about 16 °C) is not reflected...

Also, the actual humidity do not represent what is shown on the device and inside the Nest app. Any ideas what could be causing this?

**Comment by pedroserano** [comment]
I second support for adding "home" and "away" status if possible! It looks like the unofficial-nest-api code that homekit uses actually supports setting home and away, as well as the fan mode, but it doesn't look like the accessories/nest.js in homekit adds this functionality. Is this a relatively easy addition to make?

**Comment by fcarucci** [comment]
I can control Nest home/away and fan through my ruby scripts, I can try to give it a go for homebridge.

**Comment by luc-ass** [comment]
moved this to https://github.com/KraigM/homebridge-nest/issues/2
