### ISSUE TITLE
problems with starting Homebridge

### ISSUE THREAD

**Issue by dborup** [nfarina/homebridge#288]
Hi all!.

I just bought a WeMo switch for my coffeemachine, and would love to make it work with Siri.

So I installed homebridge on my OS X. but I get some errors:

Denniss-MacBook-Pro:homebridge dborup$ npm run start

> homebridge@0.1.1 start /Users/dborup/homebridge
> DEBUG=* node app.js || true

Starting HomeBridge server...
_____________________________________________________________________
IMPORTANT: Homebridge is in the middle of some big changes.
           Read more about it here:
           https://github.com/nfarina/homebridge/wiki/Migration-Guide
_____________________________________________________________________

Loading 1 platforms...
[Phillips Hue] Initializing PhilipsHue platform...
[Phillips Hue] Fetching Philips Hue lights...
[Phillips Hue] Attempting to discover Philips Hue bridge with meethue.com...
Loading 1 accessories...
[Coffee Maker] Initializing WeMo accessory...
[Coffee Maker] Searching for WeMo device with exact name 'Kaffemaskinen'...
[Phillips Hue] Philips Hue bridges found:
	10.0.1.2 - 001788fffe112d79
[Phillips Hue] Save the Philips Hue bridge ip address 10.0.1.2 to your config to skip discovery.
[Phillips Hue] Initializing platform accessory 'Soveværelse'...
[Phillips Hue] Initializing platform accessory 'Stue'...
[Phillips Hue] Initializing platform accessory 'Stue'...
/Users/dborup/homebridge/node_modules/node-hue-api/node_modules/q/q.js:126
                    throw e;
                    ^

Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 2600c775-7c21-4fe7-85cc-204eea50646d
    at Bridge.Accessory.addBridgedAccessory (/Users/dborup/homebridge/node_modules/hap-nodejs/lib/Accessory.js:164:13)
    at /Users/dborup/homebridge/app.js:135:18
    at /Users/dborup/homebridge/node_modules/hap-nodejs/lib/util/once.js:15:19
    at /Users/dborup/homebridge/platforms/PhilipsHue.js:125:9
    at resolveValue (/Users/dborup/homebridge/node_modules/node-hue-api/hue-api/utils.js:34:13)
    at _fulfilled (/Users/dborup/homebridge/node_modules/node-hue-api/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/dborup/homebridge/node_modules/node-hue-api/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/Users/dborup/homebridge/node_modules/node-hue-api/node_modules/q/q.js:749:13)
    at /Users/dborup/homebridge/node_modules/node-hue-api/node_modules/q/q.js:557:44
    at flush (/Users/dborup/homebridge/node_modules/node-hue-api/node_modules/q/q.js:108:17)

**Comment by dborup** [comment]
I got it to work, it was the duplicate HUE light bulb :)
 
AWESOME :p

**Comment by nfarina** [comment]
Glad you got it working!
