### ISSUE TITLE
yamaha on/off working, best way to setup other commands

### ISSUE THREAD

**Issue by solidstudio** [nfarina/homebridge#291]
any advice, i would like something like 'turn on living room speakers and play radio' or if thats not possible 'turn on living room speakers radio'.

Thanks

**Comment by solidstudio** [comment]
happy to right the code for yamaha-nodejs just need advice on getting a handle on the command. Would i need to setup multiple switches? Ideally i would like a on command that does multiple things, lights/music etc.

**Comment by SphtKr** [comment]
Hi, yes, this is something I'd like to do, but it's tricky. See the discussion in #265 for some information.

At the moment, doing this with Siri doesn't seem possible--Siri seems to only understand Apple's built-in Characteristics (not custom ones), and there are no built-in Characteristics for audio control. But it should be possible to make them controllable via an app, somewhat. For instance, a write-only boolean characteristic for "skip forward" could show up as a Switch that you could trigger...it might be possible to have a "playing" Characteristic that was "on" if playing and "off" if paused. It might also be possible to publish a Characteristic for, say, FM frequency, but it's up to the iOS apps to be able to make sense of Characteristics that aren't standard. The latest updates to apps and iOS (9.0.2) seem to be able to handle this to some degree.

However, I should mention that you can at least set the default play source via `config.json`, just replace `AirPlay` with `Tuner` (I think...or whatever your AVR calls the radio), and it should start up the radio by default when you turn it on.

And also, even if you could control the AVR's source with Siri, I don't think she understands "do this, and then do that"--you'd have to make it two commands, for what it's worth.

Another

**Comment by SphtKr** [comment]
Oh, right, there's another complication, and that's sequencing. Say you add a Characteristic for Radio Preset (1-9, or whatever...assuming it even works). If you wanted to have a Scene that turned on the AVR, set the mode to Radio, and chose preset 3, it wouldn't work: the AVR has to be in the right state to receive certain commands, and the scene settings would all probably be sent at the same time, or at least in an undefined order. So the AVR would ignore or error on the "set preset \#3" command if it got that before the "set input Tuner" command was finished. So that makes it tough too, or at least it requires some thought.

**Comment by solidstudio** [comment]
Ok got it working using the http accessory and yamaha-nodejs :) 

Basically you just create a simple http server to handle on/off requests and use yamaha-nodejs for the rest.

**Comment by solidstudio** [comment]
I now say 'siri set the chillout scene' and that scene has a http accessory that calls my custom server which in turn uses yamaha-nodejs to set the input to net radio and select one of my presets.

**Comment by Dax333** [comment]
solidstudio:   Are you using this https://github.com/PSeitz/yamaha-nodejs?  
Could you share some config examples of how you are doing this?  Also with Eve I've found I don't even need to even need to say "set the" anymore, Just "Hey siri, Chillout".

**Comment by AppleTechy** [comment]
Please create a new issue on the GitHub page on which the Yamaha plugin is hosted if there are still any questions.
