### ISSUE TITLE
[Feature] Support Nest

### ISSUE THREAD

**Issue by nfarina** [nfarina/homebridge#30]
Possibly via this "unofficial" API (as getting access to the official API is quite onerous): https://github.com/johnwyles/node-nest-api

**Comment by hachidorii** [comment]
I have preliminary work for a Nest platform started. I'll submit a pull request later.

**Comment by Danimal4326** [comment]
What about adding via the Wink platform?  This should allow any Wink-compatible thermostat to work as well..

**Comment by nfarina** [comment]
Would you have to own a Wink hardware bridge of some kind?

**Comment by Danimal4326** [comment]
Unfortunately yes.  But for someone with a Wink hub, any compatible thermostat would automatically work w/ Homebridge.  A similar case cam be made for SmartThings, or any 'platform' that supports thermostats.
