### ISSUE TITLE
Using multiple iOS devices

### ISSUE THREAD

**Issue by ttgolf** [nfarina/homebridge#300]
Everything is working well with the iPhone I used to setup homebridge.  I am having problem getting my other iOS devices to connect.  I thought as long as these devices are signed in using the same iCloud ID with keychain turned on, they should all work.  Can anyone help?

**Comment by KhaosT** [comment]
@ttgolf yeah, it should work... So on the other devices, are you not seeing the accessories?

**Comment by ttgolf** [comment]
No I don't see any accessories.  I can't even see the homekit menu under Settings/General.  When I open MyTouchHome on the other devices it just show blank.  I know iPhone I used to setup the system is syncing with iCloud because AppleTV sync is working (outside of home network).  I just don't know why it won't work with my other devices.  I have tried delink keychain and reset my iCloud account multiple times on my other iOS devices.  Still can't get them to work.

**Comment by KhaosT** [comment]
@ttgolf not sure why it's not working... did you enabled iCloud Drive?

**Comment by ttgolf** [comment]
Yes iCloud Drive is enable.  I am seeing any accessories in my iPad.  But I know it works if I invite my wife.  I just can't get more than one device using my ID.

**Comment by KhaosT** [comment]
That's super strange... what happens if you created another home on the other device and add a few rooms to it? Does the new home synced to other devices?

**Comment by ttgolf** [comment]
No. Just added a new home in my iPad but it's not showing up on my iPhone.  Both iPhone and iPad are using the same iCloud ID with iCloud Keychain and Drive on.  It makes no sense :-1:

**Comment by SphtKr** [comment]
For argument's sake, do other apps sync iCloud Drive files correctly? E.g. pages or Keynote? Does a document created on one device appear on the other(s)? Answer's probably yes, but worth asking.

Oh, and...

> I can't even see the homekit menu under Settings/General.

Are you running iOS 9 on everything? That's not there on iOS 8 I don't think.

**Comment by KhaosT** [comment]
Yeah, HomeKit settings will only show up on Settings if there is a home on device. In his case, because the home didn't sync across devices, it's normal that HomeKit didn't show up in settings.

**Comment by MSchmidt** [comment]
Also to note: HomeKit requires iCloud Keychain to be active. Don't think iCloud Drive is involved.

**Comment by AppleTechy** [comment]
Where you able to resolve your issue?

**Comment by eyv** [comment]
I have iCloud Keychain disabled. HomeKit works fine.

**Comment by AppleTechy** [comment]
@eyv its a matter of whether or not you can successfully share your homekit home with someone else

**Comment by eyv** [comment]
@AppleTechy see my updated comment.

**Comment by AppleTechy** [comment]
@eyv sounds solid

**Comment by AppleTechy** [comment]
@eyv This issue is old so my guess is it has been fixed but just want to confirm before I close it up as a courtesy

**Comment by OceansCrashing** [comment]
I'm having a similar issue here;  When I add HomeKit on my iPhone, it's available and syncs over to my other IOS devices no problem, and everything works.  However, when I try to add the same HomeKit on someone else's IOS device, the HomeBridge isn't detected.  If I stop the service and change the username in config.json, I can then add the HomeBridge on that person's IOS device.  But then mine stops working obviously.  I tried adding them both at the same time, but one always fails.  It's like it's only accepting a connection from a single account.  I'm running HomeBridge on a raspberry pi, in case that's relevant.

**Comment by KhaosT** [comment]
Due to the security reason, HomeKit only allows one user to pair with the accessory directly. For other users, you'll have to share your home in HomeKit with them.

**Comment by OceansCrashing** [comment]
Thanks for the reply, I realized this shortly after I posted, and you're absolutely right.  Went to settings->home kit->(home name) and invited, works great.  Siri controls my TV, LED strip, and lights around the house now.  And everyone in the house benefits from the setup. This is great!

**Comment by jplongo** [comment]
I found this just a little weird from Apple. 
Sharing Home work well on both my and my girlfriend iPhone, but the weird thing is that she can't change anything from the shared Home. 
Ex : We have two door garage in our house. I've set notifications for both doors. But if she only want notification for left door (where her car is), she can't...
That the missing parts from Apple 👎

**Comment by ipaqmaster** [comment]
Hi,

Same issue here. homebridge running on a CentOS 7 host.

Controlling the lights via a http request works instantly with Chrome/wget/curl/my homebridge setup and I can pair my iPhone. But as discussed I cant pair multiple devices. 

I can invite the involved people and their iPhones/iCloud accounts from the Apple Home interface but any iDevice which is isn't logged into my iCloud account says 'Unavailable'  and iOS suggests setting up an 'Apple TV (4th Generation)' for remote access which does not make sense while connected to our WiFi.

An unfortunate case; I was very close to having everybody on the home control train.

**Comment by OceansCrashing** [comment]
I have this working with 4 devices on two different iCloud devices. Nothing special needed.

**Comment by toshibochan** [comment]
@jplongo on the home app you can set her to allow edit.

**Comment by jplongo** [comment]
Yep I’ve seen this switch. But I think the main problem with Apple choice is that we can’t have custom Home by Phone. If she change something in home I have the same change on mine. That it’s not what I want. 
Ex: I’m using Raspberry CPU temps with homebridge to check my pi temps. She don’t need to know that and she certainly remove this elements from favorite to clean her display. 
If she do that temps widget hangs on my home too.

**Comment by NorthernMan54** [comment]
Ymmv for this

For my kids, I run a second instance of homebridge, so they can manage things the way they want to, and have there own automations.  But there are a lot of limitations with this approach, as you need a second ‘homehub’ for remote access, and your devices need to be okay with multiple homebridge’s.   For my kids control is just local, as I don't have a second Apple TV for them.

**Comment by jplongo** [comment]
Smart, itdon't correspond to my usage, but thanks for sharing. It can be helpfull

**Comment by toshibochan** [comment]
@NorthernMan54 You can add same device in other homebridge?

**Comment by NorthernMan54** [comment]
In my case I was able to control the same device from 2 instances of homebridge, but being able to do this depends on the plugin.  A bit of trial and error may be in order here, as everyone’s setup is different.
