### ISSUE TITLE
HTTP with this options -> Thermostat with switch "ON" / "OFF" , get Temperature and set Temperature

### ISSUE THREAD

**Issue by PatcherMustermann** [nfarina/homebridge#302]
Today i had time for playing with homebridge. Now it's running with http commands. What missing by http files is the thermostat with switch "ON" / "OFF" , get Temperature and set Temperature. Is here a User there have a http-file with this options? I looked the HomeMaticThermo.js, but i not understand this :(. 

Thank for your help.

**Comment by iRaven** [comment]
Hi, 
the mapping of the homekit datatypes matter. Homekit knows heating, cooling, auto and off as an integer value 0..3. In my tests all these modes had to be defined for getting a working accesory.
Homematic knows Auto Mode, Manu Mode (Off in my settings) as boolean and control mode as integer. I mapped auto and heating to auto(homematic) and other homekit states to off (114-118). The homematic states kind of depend on each other.
So if you only want On / Off states you should map the homekit types to your Solution in an own shim. The Homematic.. Functions are designed for the structure of the homematic xml-api (calls, responses handled with substr). Not the professional way but working :)

**Comment by luc-ass** [comment]
My idea was to do this over IFTTT. The beauty would be, that there is a whole lot of thermostats already supported by IFTTT, plus you can optionally pass up to 3 variables i.e. temperature values.

The http would go to: 
<code>https://maker.ifttt.com/trigger/{event}/with/key/{secret}</code> 
event could be <code>livingroom_set_temp</code>
and pass a json:
<code>{ "value1" : "something", "value2" : "goes", "value3" : "here" }</code>

config.json could even contain the essential information like secret, and event

**Comment by PatcherMustermann** [comment]
Sorry for the late answer. I have my own "http thermostat" created from the source "HomeMatic Thermo". Thanks for the help!

Greeting Patcher

**Comment by luc-ass** [comment]
do you mind publishing it?

**Comment by PatcherMustermann** [comment]
@luc-ass: What for a Version of Homebridge have you installed?
-> Old = Without Plugins
-> New = With Plugins
