### ISSUE TITLE
Raspberry Pi Sensor Hat and how to read temperature with Siri.

### ISSUE THREAD

**Issue by marcopifferi** [nfarina/homebridge#304]
Hello,

I just created a new accessory that is able to read temperature and humidity from the Raspberry Pi
where Homebridge is installed and the data is reported correctly to homekit : I am able to see it 
from any app working on homekit but I am not able to query that via SIRI. Mi impression is there is a configuration structure that does not like Siri: something like the hub -> temperature.

Any idea what could be wrong ?

best
Marco

**Comment by SphtKr** [comment]
How are you asking Siri? She's very...particular. If this is your only temperature device, if you just ask, "what is the temperature at Home?" Does it work?

If not, please post the contents of `http://serverip:51826/accessories` from your bridge and we'll have a look.

**Comment by Samfox2** [comment]
Hi, as I'm trying to do the same, could you please post your accessory file here? It would be very helpful.

**Comment by marcopifferi** [comment]
"what is the temperature at Home?" is not working.

Here is the config file : https://gist.github.com/marcopifferi/a636c7e39ae14da8a488

**Comment by Samfox2** [comment]
Got it, if I ask "how warm is it in basement" it is working for me.

**Comment by marcopifferi** [comment]
The problem was that I was asking for temperature in the house. That is not working.
Asking for temperature in the specific room works fine.
Definitely not an homebridge issue.
