### ISSUE TITLE
Tellstick Net or Duo?

### ISSUE THREAD

**Issue by ekwarg** [nfarina/homebridge#306]
@nfarina @johngson  Thanks a lot for that, will get to it during the autumn break. Please pardon my question if this sounds obvious but I am a noob. Just wondering if you can use Tellstick Net and Duo regardless or is it working better with one? What would you recommend?

My config is homebridge installed on raspbian.

Also wondering if there is a need to specify specific Siri commands (like it used to be the case on Siriproxy) or will she just pick up on anything related to the Telldus Live installation?

**Comment by theodorton** [comment]
I worked on the Telldus platform implementation. I believe you would use "Telldus" with the Duo, and "TelldusLive" with Net.

**Comment by ekwarg** [comment]
Thanks a lot! have installed homebridge, tellstick net is running with telldus live but can't get to have siri controlling the thing. I have mytouchhomeapp and see my "fake-homebridge" and "fake-accessory" but can't add any device.

Do you have any advice?
