### ISSUE TITLE
[usability] Access over the internet

### ISSUE THREAD

**Issue by mihailescu2m** [nfarina/homebridge#307]
Homekit currently works with ios devices that are connected to the wifi network. It does not work over 3G/Internet. For some accessories this is annoying - for example, you want to use Siri to open the garage door, but it will not work since you are probably outside and not connected to the wifi.
The solution is to use the new Apple TV, or the yet unannounced bluetooth range extenders.

However, since accessories are actually discovered via avahi/bonjour, configuring your network for wide-area bonjour should expose homebridge functionality over the Internet.

I was curious if anyone tried this already. I only installed homebridge yesterday - thanks to all contributors for this excellent piece of work! - and will try in the next couple of days wide-area bonjour myself.

**Comment by KhaosT** [comment]
@mihailescu2m Remote Access also works for Apple TV 3rd Generation. Given that HomeKit on iOS is explicitly scanning .local domain, I'm not sure Wide-Area Bonjour will work in this case...

**Comment by lukeredpath** [comment]
As above, you can use the current Apple TV for this. It should just work. Does for me.

**Comment by jmvanbuskirk** [comment]
I can't seem to get Homebridge working over LTE either. Works fine at home but not over cellular. I have a third generation Apple TV on the same network and they're both using the same iCloud account. I have signed in and out on the Apple TV and have restarted both the phone and Apple TV. I've also reset HomeKit settings. I'm using Windows to host my Homebridge. Could that be the cause of the issue?

Regards,

Josh

**Comment by KhaosT** [comment]
@jmvanbuskirk As long as Homebridge works with iOS device, Remote Access should work for you... If it doesn't, it's really hard to debug this...

**Comment by fitzage** [comment]
Yeah, it doesn't work for me either, and I haven't found a decent way to figure out why.

**Comment by jmvanbuskirk** [comment]
Could it have anything to do with the devices I have setup? I have wemo and
hue presently in my config file.

**Comment by KhaosT** [comment]
@fitzage @jmvanbuskirk so far the only thing I can suggest is to follow the procedural I described [here](https://github.com/nfarina/homebridge/issues/256#issuecomment-148499883)... Also if you enabled 2FA on your account, there might have some other issues.

**Comment by keloin** [comment]
@KhaosT What is 2FA? Thanks!

**Comment by AppleTechy** [comment]
If you disable 2 part Authentication it should fix your issue. issue #462

**Comment by jaydisc** [comment]
I have this issue too. I have WeMo stuff going through Homebridge via "WeMo Platform", and Hue stuff connecting directly. I can control all the Hue stuff remotely, but all the WeMo switches say "No Response". I have an Apple TV 4 on my LAN.
