### ISSUE TITLE
Cant start the Server on Raspberry Pi 2

### ISSUE THREAD

**Issue by RBEGamer** [nfarina/homebridge#31]
Hello, i can't start the server on myRPI.. this is the error-message 

pi@smarthomeserver:~/homebridge$ sudo npm run start

> homebridge@0.0.0 start /home/pi/homebridge
> node app.js

Starting HomeBridge server...
module.js:338
    throw err;
          ^
Error: Cannot find module '../build/Release/dns_sd_bindings'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/pi/homebridge/lib/HAP-NodeJS/node_modules/mdns/lib/dns_sd.js:32:22)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

npm ERR! Linux 3.18.0-20-rpi2
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "start"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE
npm ERR! homebridge@0.0.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the homebridge@0.0.0 start script 'node app.js'.
npm ERR! This is most likely a problem with the homebridge package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls homebridge
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/homebridge/npm-debug.log
pi@smarthomeserver:~/homebridge$ 

have anybody a hint for me ?

**Comment by nfarina** [comment]
This looks like an issue with one of [HAP-NodeJS's](https://github.com/KhaosT/HAP-NodeJS) dependencies. Have you run `npm install` from the `lib/HAP-NodeJS` directory? (see the homebridge README)

**Comment by rayzorben** [comment]
Make sure that you install build-essential and libavahi-compat-libdnssd-dev first before trying to run an npm install.

If you get in a stuck state, I followed the solution here and then did an npm install on HAP-NodeJS and got it working: https://github.com/stephen/nodetunes/issues/28

**Comment by eprompc** [comment]
I'm on raspberry too.

~/homebridge $ npm run start

> homebridge@0.0.0 start /home/eprom/homebridge
> node app.js

Starting HomeBridge server...
Couldn't find a config.json file in the same directory as app.js. Look at config-sample.json for examples of how to format your config.js and add your home accessories.

npm ERR! Linux 3.18.11+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
npm ERR! node v0.12.6
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE
npm ERR! homebridge@0.0.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the homebridge@0.0.0 start script 'node app.js'.
npm ERR! This is most likely a problem with the homebridge package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls homebridge
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/eprom/homebridge/npm-debug.log

**Comment by Kosta-Github** [comment]
You read what was dumped into the console, right?

`Couldn't find a config.json file in the same directory as app.js. Look at config-sample.json for examples of how to format your config.js and add your home accessories.`

see also line: https://github.com/nfarina/homebridge/blob/master/app.js#L13

**Comment by eprompc** [comment]
Ok, all is working, but when run instead app in iphone for add Wemo Switch, it ask for a key.... What key?
Thanks u very much

**Comment by eprompc** [comment]
Ok. Solved. Thanks

**Comment by flynhawaiian** [comment]
I had the same problem as the origional poster.  I got around it by just simply running node app.js in the homebridge directory.

**Comment by nfarina** [comment]
Finally got my RPi 2 and it was really easy to set up and run. I wrote some instructions here: https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi

**Comment by toshibochan** [comment]
Please anyone can make YouTube how to install HomeBridged on raspberry pi! Please
