### ISSUE TITLE
Nest kicks me out of the Nest app when using 3rd-party API

### ISSUE THREAD

**Issue by luc-ass** [nfarina/homebridge#311]
Hey, anyone else experiencing this? I integrated Nest (for a vacation home) into Homebridge but now it kicks everyone out of the app so they need to log in again before using it. Any solution to this problem?

**Comment by jumpkick** [comment]
I've experienced the same thing, it's not a homebridge specific problem...

**Comment by luc-ass** [comment]
anywhere where this is discussed properly?

**Comment by deejc-uk** [comment]
i added my nest in IFTTT and it also kicked me out of every other device and app using the api, it would not allow me back in until i had changed the password (changed it back to what is was originally) and then everything was OK.

**Comment by KraigM** [comment]
I had an issue with it but it was fixed when I restarted my Nest.

**Comment by luc-ass** [comment]
As this seems to be a known issue I close this discussion. Pleas comment if you find some place else that this problem is discussed....
