### ISSUE TITLE
Frequently crashing

### ISSUE THREAD

**Issue by lukeredpath** [nfarina/homebridge#312]
Homebridge has been pretty stable for me until over the past week or so, it has started crashing frequently. I need to restart it at least once a day. 

I can't figure out what is causing this. I'm using the Domoticz and Nest shims. 

This is the console output (I run Homebridge in a screen session):

```
  EventedHTTPServer [::ffff:192.168.1.85] HTTP server was closed +0ms
  EventedHTTPServer [::ffff:192.168.1.85] New connection from client +3m
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1156:14)
    at listen (net.js:1182:10)
    at Server.listen (net.js:1267:5)
    at new EventedHTTPServerConnection (/opt/homebridge/node_modules/hap-nodejs/lib/util/eventedht
tp.js:125:20)
     at EventedHTTPServer._onConnection (/opt/homebridge/node_modules/hap-nodejs/lib/util/eventedh
ttp.js:79:20)
      at Server.emit (events.js:107:17)
      at TCP.onconnection (net.js:1330:8)
```

Any ideas?

**Comment by KhaosT** [comment]
It appears that hap server is trying to bind a port which is already in use... For now I'd suggest you to modify the start port to a higher number to solve this (if this happens a lot)
In the future, hap server needs to be smart on which port it should use.

**Comment by lukeredpath** [comment]
Is there a reason this doesn't happen immediately? If I can find out what port it's conflicting with I might be able to change that.

**Comment by KhaosT** [comment]
@lukeredpath right now hap server will create a new instance of internal server for every session, that's why it won't happen immediately until iOS device connected to accessory.
