### ISSUE TITLE
WARNING *** Please fix your application to use the native API of Avahi!

### ISSUE THREAD

**Issue by Paul1989** [nfarina/homebridge#32]
Hi,

I'm getting the following error when trying to run this on a Pi 2:

> homebridge@0.0.0 start /home/pi/homebridge
> node app.js

Starting HomeBridge server...
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>

Node version is v0.12.1 and NPM is 2.5.1. My installation steps are:

sudo apt-get install libavahi-compat-libdnssd-dev (I get a MDNS related error without these packages)
wget http://node-arm.herokuapp.com/node_latest_armhf.deb
sudo dpkg -i node_latest_armhf.deb
git clone https://github.com/nfarina/homebridge.git
cd homebridge
git submodule init
git submodule update
npm install
cd lib/HAP-NodeJS
npm install

I have created a config.json based on the sample output but when I run npm run start I get the above error. Does anyone have any ideas?

Many thanks in advance.

**Comment by Paul1989** [comment]
Turns out you can ignore these errors. The reason why I thought you couldn't was because I wasn't getting anything after them but that was due to an error in my config. I have closed this issue.

**Comment by nfarina** [comment]
Yes you are correct, it's unfortunate but can be ignored.
