### ISSUE TITLE
ISY-JS add support for Insteon Motion Sensor

### ISSUE THREAD

**Issue by leoneleone** [nfarina/homebridge#321]
I'm not sure Insteon Morion Sensors are supported under isy-js.js platform. I have motion sensors as part of my Isy setup but they do not show up in Homebridge as devices/accessories.

Can someone please add support for motion sensors? 

Thanks

**Comment by rodtoll** [comment]
@leoneleone I've added support for Insteon motion sensors to both the underlying isy-js library and the homebridge extension. If you get the latest homebridge and install the homebridge-isy-js extension the software will support the motion sensors. You can see instructions here: https://github.com/rodtoll/homebridge-isy-js.

**Comment by nfarina** [comment]
Closing for now; @leoneleone if you're having issues with this plugin then feel free to reopen the issue at https://github.com/rodtoll/homebridge-isy-js :)
