### ISSUE TITLE
Crashing on "Error: read ECONNRESET"

### ISSUE THREAD

**Issue by schubert** [nfarina/homebridge#323]
```
 harmonyhubjs:client:harmonyclient handleStanza(<iq id="842906" type="get" xmlns:stream="http://etherx.jabber.org/streams"><oa xmlns="connect.logitech.com" mime="vnd.logitech.harmony/vnd.logitech.harmony.engine?getCurrentActivity" errorcode="200" errorstring="OK">result=15310342</oa></iq>) +20ms
  harmonyhubjs:client:harmonyclient received response stanza for queued response handler +0ms
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: read ECONNRESET
    at exports._errnoException (util.js:746:11)
    at TCP.onread (net.js:559:26)
```

This started happening after I re-enabled harmony support after recent fixes. Looks like on a connection reset it should catch and reconnect instead of just dying? Looks like it dies after running for a few hours. I've got a Harmony Hub, Sonos and Nest. When just using Sonos and Nest it continues to run.

I'll see if i can patch if I have time but figured I'd put the issue in in case others encounter it as well.

**Comment by askme233** [comment]
Did this get resolved?  I now have the same issue, but do not use Harmony

**Comment by schubert** [comment]
It doesn't look like this issue exists with the new harmony plugin (vs. the legacy one which might still have this issue).

If you're seeing this with another platform or accessory, please provide more details.

**Comment by askme233** [comment]
I rebuilt with latest versions and all is well. Not sure what the culprit was.
