### ISSUE TITLE
Problem with Netatmo homebridge module - CO2 / Air Quality

### ISSUE THREAD

**Issue by szerglyiphone** [nfarina/homebridge#328]
Hi,

I'm having an issue with using a CO2 sensor with the Netatmo homebridge module.

I have installed the HomeBridge server on a Raspberry Pi and the Insteon Plus app on my iPhone. I have set up a temperature, a humidity and a CO2 level sensor in my bedroom, and I've added each of them. The iOS app recognizes them as well; in fact, it displays 4 devices, the 4th one being an additional "air quality" sensor (which I think is the same as the CO2 level meter).

(logs)

    [Netatmo Weather] refreshing device 70:ee:50:02:dd:c2 (Inside)
    [Netatmo Weather] refreshing module 02:00:00:02:e4:fc (Outside)
    [Netatmo Weather] refreshing module 05:00:00:00:92:2a (Csapadekmero)
    [Netatmo Weather] Adding accessory for device 70:ee:50:02:dd:c2 (Inside)
    [Netatmo Weather] Adding accessory for module 02:00:00:02:e4:fc (Outside)
    [Netatmo Weather] Adding accessory for module 05:00:00:00:92:2a (Csapadekmero)

When I query the temperature and the humidity ("Hey Siri! What's the temperature [/humidity] in the bedroom?"), it works just fine, and I get a response.

(logs)

    Accessory [Homebridge] Registering Characteristic "Current Temperature" for events +0ms 
    Accessory [Homebridge] Registering Characteristic "Humidity" for events +1ms
    Accessory [Homebridge] Registering Characteristic "CO2 detected" for events +0ms
    Accessory [Homebridge] Registering Characteristic "CO2 level " for events +1ms
    Accessory [Homebridge] Registering Characteristic "Current Air Quality" for events +0ms

When I ask Siri for either the "air quality" or "CO2", neither one works; Siri replies "I wasn't able to find any devices in the bedroom this time". When I look at the log produced by the homebridge server, I can't see any activity; apparently, the app doesn't even seem to be able to communicate with the server. (See attached screenshots.)

![photo 1 3](https://cloud.githubusercontent.com/assets/15326344/10732773/e1c7a58e-7bfb-11e5-80ad-96e9a8169ca3.png)
![photo 2 2](https://cloud.githubusercontent.com/assets/15326344/10732774/e1f37182-7bfb-11e5-96b9-ded219b2602e.png)

I presume this is not necessarily (not only) a problem with homebridge's Netatmo module; could you provide any insight as to what the cause of the issue might be and how I could resolve it?

Thanks and regards,
Szergely

**Comment by planetk** [comment]
Hi,

you're right, The air quality right now is just a characteristic based on CO2 level.
(in steps of 500ppm). I'm planning to add some more sophisticated stuff based on humidity and Temperature in future (like netatmo app). When doing so, I will check about the issue with siri. It might be because the name of the service is not unique. Possibly using something like "<Name of Device> Air" as service name might help.
It will take me a few days until I can check that.
Kind regards
PlanetK

**Comment by KhaosT** [comment]
@szerglyiphone if I remember correctly, Siri on iOS currently don't understand most of new services added in iOS 9.

**Comment by szerglyiphone** [comment]
Hello Planetk!

Thank you for your fast answer! If you need any help for testing just tell me :)

**Comment by planetk** [comment]
Hi,

ok, today I was able to continue my work on the netatmo module. I'll do some more test and than write an PR.

There are good news and bad news as well.

Bad news is: KhaosT is completely right. iOS 9 does not integrate the new Characteristics in siri up to now. So there is no way for me to help with that. Possibly there is a chance by defining a scene. But I haven't tried.

Good news is: I did a complete rewrite of the module, using the new API. This is much more readable for me being a JavaScript novice. And I did integrate support for atmospheric pressure and noise level.

**Comment by szerglyiphone** [comment]
Hey Planetk!

I upgraded the latest version, and yes its now better, can you tell me some Siri-command please? I don't know exacly how I asking the noise level or atmospheric pressure.

Thank you!

**Comment by dobsiin** [comment]
Based on some research i guess siri is not able to tell you the noise level or atmospheric pressure. I hope they deliver some new siri commands with further updates.

https://help.elgato.com/customer/en/portal/articles/2069686-die-eve-app-und-siri-geräte-steuern-und-werte-abfragen-per-sprachbefehl?b_id=360
