### ISSUE TITLE
Using Domoticz does not show current state

### ISSUE THREAD

**Issue by deejc-uk** [nfarina/homebridge#329]
i am using the domoticz platform and it works well, except it does not reflect the current state of the devices as known to domoticz.
i run some events / scenes in domoticz that turn devices on and off and the Eve app does not know about these devices states.
i just pulled current but it still seems the same.

**Comment by PatchworkBoy** [comment]
Not an issue with homebridge. Using the homebridge-edomoticz plugin will give you accurate reflection of Domoticz states (in super speedy realtime if you use the MQTT-integration branch).

Issue can be closed.
