### ISSUE TITLE
Homebridge won't start

### ISSUE THREAD

**Issue by rudyv** [nfarina/homebridge#33]
Hi, 
I upgraded my nodejs to 0.12.1 and then installed everything. Unfortunately the server doesn't start with following details in the logfile.

pi@raspberrypi ~/homebridge $ npm run start

> homebridge@0.0.0 start /home/pi/homebridge
> node app.js

Starting HomeBridge server...
/home/pi/homebridge/lib/HAP-NodeJS/node_modules/mdns/lib/dns_sd.js:35
    throw ex;
          ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/pi/homebridge/lib/HAP-NodeJS/node_modules/mdns/lib/dns_sd.js:24:20)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

npm ERR! Linux 3.12.21+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
npm ERR! node v0.12.1
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! homebridge@0.0.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the homebridge@0.0.0 start script 'node app.js'.
npm ERR! This is most likely a problem with the homebridge package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls homebridge
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/homebridge/npm-debug.log

The content of the npm-debug.log file is
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'start' ]
2 info using npm@2.5.1
3 info using node@v0.12.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart homebridge@0.0.0
6 info start homebridge@0.0.0
7 verbose unsafe-perm in lifecycle true
8 info homebridge@0.0.0 Failed to exec start script
9 verbose stack Error: homebridge@0.0.0 start: `node app.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/ut
ils/lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/ut
ils/spawn.js:14:12)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1008:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
10 verbose pkgid homebridge@0.0.0
11 verbose cwd /home/pi/homebridge
12 error Linux 3.12.21+
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
14 error node v0.12.1
15 error npm  v2.5.1
16 error code ELIFECYCLE
17 error homebridge@0.0.0 start: `node app.js`
17 error Exit status 1
18 error Failed at the homebridge@0.0.0 start script 'node app.js'.
18 error This is most likely a problem with the homebridge package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node app.js
18 error You can get their info via:
18 error     npm owner ls homebridge
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

Any suggestion ?
Thanks
Rudy

**Comment by nfarina** [comment]
Hi, this looks similar to issue #31. Can you try the suggestion at the bottom there?

**Comment by rudyv** [comment]
Hi Nick,
I had a look at it and run the install again, also in lib/HAP-NodeJS directory. it didn't solve the issue.
I'll also try to upgrade npm, maybe that is the issue, I'll let you know

KR,
Rudy

**Comment by nfarina** [comment]
OK thanks. You might try running the `HAP-NodeJS` server by itself (as it looks like the issue is somewhere in one of their dependencies) and posting an issue to that project if it doesn't work!

**Comment by rudyv** [comment]
Hi Nick, I installed everything on a new image and got it to work. So we can close this item.
I'm sorry for the inconvenience caused.
Rudy

**Comment by rudyv** [comment]
closed

**Comment by nfarina** [comment]
Ah OK, well glad you got it working!
