### ISSUE TITLE
Denon Remote integration

### ISSUE THREAD

**Issue by SmoothMC** [nfarina/homebridge#330]
Is there a way to integrate a control module for Denon AVR

for commands like
"Volume Up, Down Mute On Off etc."

There is a way to do that via telnet or http

like this
http://[ip]/goform/formiPhoneAppDirect.xml?MUON             = Mute On
http://[ip]/goform/formiPhoneAppDirect.xml?MUOFF           = Mute Off
http://[ip]/goform/formiPhoneAppDirect.xml?MVUP              = Volume Up 0,5 dB
http://[ip]/goform/formiPhoneAppDirect.xml?MVDOWN       = Volume Down 0,5 dB
http://[ip]/goform/formiPhoneAppDirect.xml?MV80              = Direkt Volume MV00 - MV98

regards Micha

**Comment by luc-ass** [comment]
I have a Marantz reciever (which uses the same protocol) and am planing to write a shim. I'll have a look at the Yamaha shim. Shal we work together on this one?

There is a node-api for marantz but I didn't have the time to try it out yet.

Any suggestions on what to do first?

**Comment by luc-ass** [comment]
I made some progress. The receiver can indeed be called be called via http. Cool!

On and off works like a charm. I'll have you know when you can test it out :)

**Comment by SmoothMC** [comment]
with my AVR i use the same for Volume Up, Down Mute On OFF
I have Scenes for "Ton aus" "Ton ein" "Lauter" "Leiser" :P
but a module would be nice.
At the moment every entry is a new device in a app like "Eve" ;)

**Comment by luxus** [comment]
i can try it with my marantz 7010 if you need support

**Comment by SmoothMC** [comment]
that would be great :)
commands to change Source and turn On, OFF Power would be nice as well ;)

regards

**Comment by luc-ass** [comment]
My priority list for now is:
- Power ON/OFF,
- Mute ON/OFF,
- Volume UP/DOWN including "Set Volume to %",
- Input

**Comment by luc-ass** [comment]
OK, I managed to build robust On/Off controls. Next step would be to integrate "audio specific" functions but since those can not be called by Siri I wonder how much use they would be? What do you think?

**Comment by luxus** [comment]
Take care! 100% volume will be much more painful then 100% light :)

**Comment by tilledminds** [comment]
luc-ass,

How is the integration coming along? 

Thanks

**Comment by luc-ass** [comment]
Up until now I am kind of stuck with power controls.  The thing is that  I would like to add multiple services to one device and mulch one device per service. The Insteon+ app  does represent those values but only lets me change power state.

Any ideas on how to add additional on/off switches or  percentage values to existing devices?

**Comment by tilledminds** [comment]
I have it working with my Marantz (same protocol as Denon) for power on/off via the HTTP shim and was hoping to override Brightness as a way to control volume (I just want mute on and off really), but so far no luck getting it to work.

**Comment by luc-ass** [comment]
If you really want to do like this you need to expose your receiver as a lightbulb. That will be really annoying as it would respond to "turn all the lights off".

**Comment by tilledminds** [comment]
Ha - that's an excellent point!

**Comment by luc-ass** [comment]
Yesterday I got to Play with the HomeKit Simulator and added additional On/Off Characteristic aswell as a 100% Characteristics. The EVE-App understands those. I'll try more today.

**Comment by alfista2600** [comment]
I have a denon x4000 that I control with SimpleControl mostly. I'd be happy to help test some of the homebridge code if you need testers...

**Comment by luc-ass** [comment]
Just wanted to show you this: 
![img_1318](https://cloud.githubusercontent.com/assets/3263257/10950687/40acd198-8339-11e5-8d6f-ee2d30a87f2b.jpg)

... and point you to my repo luc-ass/homebridge-marantzavr
I think that will be the best place to discuss anything else....

**Comment by luc-ass** [comment]
I also opened #homebridge-marantzavr on nfarina's homebridgeteam.slack.com

**Comment by tilledminds** [comment]
Very nice!

**Comment by luc-ass** [comment]
As I created a seperate repo I suggesting to this discussion and move it to http://github.com/luc-ass/homebridge-marantzavr

**Comment by alfista2600** [comment]
Lucas - thanks for including me. Work has gotten very busy so I haven’t had time to engage, but I hope to over the weekend. This is my first real use of github as well so lots to learn.

Thanks,

Jason
