### ISSUE TITLE
Official Versions through GitHub releases/tags?

### ISSUE THREAD

**Issue by ankushg** [nfarina/homebridge#339]
Are there any plans to use releases/tags instead of relying on the master version always being up to date? I generally don't touch my homebridge box too often, and know I'm always going to be at least a few commits out of date.

Having official releases for major feature additions/changes as opposed to just always cloning master would be a great way for people to have a more maintainable update cycle, and would allow people to do things like subscribe to an RSS feed for new releases/updates as well!

**Comment by nfarina** [comment]
The current plan is to distribute via `npm install -g`. See #293 for more on the proposed upcoming changes.
