### ISSUE TITLE
[Feature] Particle support

### ISSUE THREAD

**Issue by rudyv** [nfarina/homebridge#34]
Hi,

Can somebody have a look at the Particle, formerly know as Spark.
A microcontroller that is cloud enabled and even a channel in IFTTT.

The way a function is called is through a REST API.

For Example:

POST /v1/devices/{DEVICE_ID}/{FUNCTION}

# EXAMPLE REQUEST
curl https://api.particle.io/v1/devices/0123456789abcdef01234567/brew \
     -d access_token=1234123412341234123412341234123412341234 \
     -d "args=202,230"

First you have the URL of the cloud service
then a version: in this case v1
A device ID
and then the function called, brew in this case
then also the access token needs to be passed and some arguments.

As I'm not an experienced programmer I wonder if someone could make an "accessory" for this ?

I guess the whole particle community would be pleased with this extension.
Thanks
Rudy

**Comment by maddox** [comment]
You could easily just use teh `HTTP` accessory for this. It's a generic accessory designed to make HTTP requests. You simply create devices with the `config.json` and define what the URL to be requested is, and the requests will just be made.

You can see how to set up an accessory with the `HTTP` accessory in the sample `config.json` - https://github.com/nfarina/homebridge/blob/master/config-sample.json#L85-L92

You can learn more about how this works on the [pull request](https://github.com/nfarina/homebridge/pull/26) that implemented it.

**Comment by maddox** [comment]
Hmm, the `POST` arguments would cause trouble with this though. You should try to see if you can append them to the URL like query parameters and see if it works:

```
curl -d "" https://api.particle.io/v1/devices/0123456789abcdef01234567/brew?access_token=1234123412341234123412341234123412341234&args=202,230
```

**Comment by rudyv** [comment]
Thanks for the hint Jon, I'll give it a try.

KR,

**Comment by rudyv** [comment]
Hi Jon,
Unfortunately not, I also posted a question in the Particle community to see what comes out, we'll get it to work.

Thanks,
Rudy

**Comment by maddox** [comment]
I found a js module for particle.io - https://www.npmjs.com/package/particle-io

But I'm not sure exactly how these devices would map to HomeKit devices. If you're just looking for on/off then it could work just fine. Using this library, an accessory could be created for adding devices.

**Comment by nikita-leonov** [comment]
I did it pretty quick with Http accessory, it still required some modifications in it, but it works — https://vimeo.com/132413806

I think we can easily develop Spark accessory as well as Spark platform, however I am little bit worried about platforms & accessories architecture in general. May require some refactoring as well.

**Comment by nfarina** [comment]
Particle looks awesome. I wonder what the best way to "support" it officially would be though - it seems that normal users would be adding accessories that just happen to have Particle inside as an implementation detail. I don't know that adding a "Particle" accessory makes a ton of sense if it's a circuit board ... unless there's an easy way for a hobbyist-type person to buy a Particle thing and hook it up to a switch.

**Comment by nikita-leonov** [comment]
Particle is one of the easiest way to hack with hardware as it has build in wifi and cloud integration based on node.js. It is easy to wire things to the particle as well. 
Homebridge is the easiest way to hack with HomeKit. Since it targeting "intrepid hackers only" as well as may require some knowledge about RaspberryPi etc I thought it would make sense to marry Particle & Homebridge. There are a lot of hobbies that wants this. 

My plan was following: 
* Implement generic HTTP accessory that not limited to light characteristics but allows registering any HomeKit characteristics, assign URLs and data payloads to them.
* Implement Particle HomeKit library that allows to register handlers for HomeKit services and characteristics.
* Implement Particle accessory on a top of generic HTTP accessory that will work with Particle HomeKit API exposed through Particle Cloud platform.
* Implement Particle platform that able to discover Particle accessories through Particle cloud platform.

I do not know how long it will take, but it something that I would be interesting to play with. @nfarina do you think it makes sense and could be a part of Homebridge?

**Comment by nfarina** [comment]
If done well, then absolutely this sounds awesome. In terms of generic HTTP accessory, we had a discussion about that in #36. I think an ideal HTTP accessory would function like a published "REST API" - like, you can implement any kind of HomeKit accessory on "the other side" as long as you implement the correct API hooks.

**Comment by nikita-leonov** [comment]
I am working on this as we speak, but I decided to approach in a more generic way by providing HttpAccessory, HttpService and HttpCharacteristic. This three classes should allow to integrate any device API by defining only requests configurations.

**Comment by nikita-leonov** [comment]
As I got a bunch of requests I step a side from implementation of common base for HTTP Accessories and documented a process of particle.io integration — https://github.com/nikita-leonov/particleio-homekit

@rudyv this should give you a base for your experiments and not delay while I am implementing better platform for integration of HTTP accessories.

**Comment by rudyv** [comment]
@nikita-leonov thanks for the code. I had to make some modifications to the hue simulator. It runs now nice on a Photon.
I also downloaded the latest version of homebridge and I'm now puzzled about the location of ParticleAccessory.js ??? 
@nfarina in which directory should this additional accessory be placed ? I now have it in ~/homebridge/accessories and unfortunately the homebridge is not starting up :(

**Comment by nikita-leonov** [comment]
@rudyv It should be in accessories folder ParticleAccessory.js, you also need to be sure that you have proper config.json in place.

**Comment by rudyv** [comment]
@nikita-leonov i did that and ubfortunately with The latest version of homebridge I always get an error when I try to run it.
I'll send the details later

**Comment by nikita-leonov** [comment]
@rudyv It seems home bridge evolving fast, this is good :) No worries, I will update my code sample today at evening. I do not expect a lot of changes.

**Comment by nikita-leonov** [comment]
@rudyv I fixed my sample. Apparently home bridge started to instal HAP through NPM, but not manually and it broke some paths. Now it works well. Also, if you have any further issues with that sample, please create issues in dedicated place, meanwhile lets keep this issue for official support of particle.io by home bridge.

**Comment by rudyv** [comment]
@nikita-leonov I got it to work with the Insteon+ app, thanks a lot for the changes you made.
The only thing I wonder is: what are the Siri commands to control the Particle to react ?
Most likely it is also because of being not a native English speaker I'm afraid.
So if you can give me a hint on that I would appreciate 
KR
Rudy

**Comment by rudyv** [comment]
@nikita-leonov It works now, thanks for the update, that made the trick :)
The only question I have left is about the Siri commands to use to control the Particle. Unfortunately I'm not a native English speaker and that doesn't help when using Siri ...
So if you can give me a few hints here ?

And it was not my intention to close the topic, that was an accident.
Sorry for the trouble.

KR,
Rudy
