### ISSUE TITLE
How does "StatusLowBattery" work?

### ISSUE THREAD

**Issue by Samfox2** [nfarina/homebridge#341]
Hi,
I am writing a shim for reading values out of my DomotoGa platform.
At the current state it can read temperature and humidity from combined sensors.
As the sensors are battery powered would like to add a low battery warning.
I can read out the power level and decide, whether it is low (=1) or ok (=0) but nothing is displayed in my eve app.
Could anybody please have a look at my shim and tell me what`s wrong with it?
https://github.com/Samfox2/homebridge-domotiga

Here is what I did in short form:

       temperatureService
                .getCharacteristic(Characteristic.CurrentTemperature)
                .on('get', this.getCurrentTemperature.bind(this));

        temperatureService
                .addCharacteristic(new Characteristic.StatusLowBattery())
                .on('get', this.getLowBatteryStatus.bind(this));

        return [informationService, temperatureService, humidityService];

**Comment by KhaosT** [comment]
@Samfox2 battery service is a new service added in iOS 9. It's up to app to decide what to display when this characteristic is low and currently there is no app actually supports displaying this characteristic in a meaningful way.

**Comment by Samfox2** [comment]
Ok, that's the reason... Thanks!

**Comment by justme-1968** [comment]
i can see the battery level indicators in eve with my fhem shim.

ps: why do you use two services to display temperature und humidity? i think it is much more convenient to display both characteristics in the same service.

**Comment by Samfox2** [comment]
@justmee-1968: thanks for your answer. Never thougth about an combination of the 2 services, did it now, thanks for the hint.
StatusLowBattery still not shown in my eve app, maybe BatteryLevel is also needed?

**Comment by Samfox2** [comment]
Added (fake) BatteryLevel now but still no indication in eve app.
Could you please have a look at my shim?
https://github.com/Samfox2/homebridge/blob/master/accessories/DomotigaTempHygroMeter.js

**Comment by justme-1968** [comment]
at the first glance i don't see a problem. i'm using only Characteristic.StatusLowBattery in the FHEM shim: https://github.com/justme-1968/homebridge/blob/master/platforms/FHEM.js

**Comment by justme-1968** [comment]
here is what the result looks like (in german):
![img_1346](https://cloud.githubusercontent.com/assets/4605251/10853740/f4e7a436-7f37-11e5-828f-db935b44c77d.png)

**Comment by Samfox2** [comment]
Ok, tried it also with a contact sensor - unfortunatelly with the same result:
Contact is working but battery state not :-(
Is it possible that I you have newer dependencies that do support additional characteristics?
When I use another app, e.g. Insteon, I can see an empty field at the sensors that appears as soon as I activate the battery state mapping. So maybe the code is ok (what I think) but it is cannot handle the missing characteristics?

**Comment by Samfox2** [comment]
another idea, are you using an iOS beta version?

**Comment by justme-1968** [comment]
currently just the regular 9.1 version.

**Comment by Samfox2** [comment]
Update: Just added a fake eve room service with custom eve uuid and now the battery status appeared in eve app. Seems like it is hardcoded in the app and only working for a few services.

**Comment by justme-1968** [comment]
i'm having it working with the normal contact and temperature sensor services. and some of the fhem users have it working with other devices also.

**Comment by Samfox2** [comment]
Got it! It was really strange mistake... When I defined the different services I left the "service name" empty. However if that's the case, eve app cannot handle the battery and lowbattery characteristics. Changed that now and both battery and statuslowbattery are visualized in eve app for all my accessories :-)
