### ISSUE TITLE
Raspberry Pi Doc

### ISSUE THREAD

**Issue by niallel** [nfarina/homebridge#344]
Hi,

One thing I noticed when running **npm install** after following the instructions some of the build fails because the kerberos dev stuff isn't installed.
The docs just need to say to run 
**sudo apt-get install libkrb5-dev**
before running **npm install**

Fantastic project by the way, you've done a great job, love it.

cheers,

**Comment by nfarina** [comment]
Ah gotcha - thanks for the report! Would you mind updating the Wiki page with that?

**Comment by niallel** [comment]
Thanks, I just did, never realised I could.

thanks again,
