### ISSUE TITLE
Can Homebridge use tag Homebridge.Service.Type:Lightbulb to report a swtich as a lightbuld

### ISSUE THREAD

**Issue by mories76** [nfarina/homebridge#362]
Is it possible to use tags to change the type form switch to lightbulb ?
I use some zwave switches to control lights, and it would be nice to make Homekit respond to a command like: turn off the lights.

I used the tags Homebridge.Service.Type:Lightbulb, and Homebridge.IsPrimary.
But this doesn't seem too work.

Regards,
Maurice

**Comment by mories76** [comment]
I have found a solutions.

I changed ZWayServer.js and modfied the getVDevDevices function

//// before ///

case "switchBinary":
                services.push(new Service.Switch(vdev.metrics.title, vdev.id));
                break;

//// after ///

case "switchBinary":
                if(this.platform.getTagValue(vdev, "Service.Type") === "Lightbulb"){
		    services.push(new Service.Lightbulb(vdev.metrics.title, vdev.id));
		}else{
		    services.push(new Service.Switch(vdev.metrics.title, vdev.id));
		}
                break;

@nfarina : is it possible to include this change ? Thx

**Comment by nfarina** [comment]
Hello, I don't know anything about this platform - @SphtKr is the one that did most of the work so you'll have to ask him.

**Comment by SphtKr** [comment]
Hey there, sorry, just had some things taking up my time. Yes, we can do that, looks like your suggested change is probably about right. Just got to get back and finish a half-done pull request and work on the plugin version :-).

**Comment by luxus** [comment]
@SphtKr any updates? :D

**Comment by SphtKr** [comment]
The fix above is already in homebridge-zway/master...it will never auto-close because the homebridge-zway repo is a fork of nfarina/homebridge. This issue should be manually closed.
