### ISSUE TITLE
Any ideas regarding Service.powerConsumption?

### ISSUE THREAD

**Issue by luc-ass** [nfarina/homebridge#364]
Hi,

I noticed that "elgato eve power" can not only switch on/off but also report back how much power was consumed. Any ideas how this service works?

**Comment by justme-1968** [comment]
probably a custom characteristc (as quite a few other of elgatos stuff).

it should be visible with homkit apps from apple or KhaosT. 

if anyone finds out more please post here: https://github.com/KhaosT/HAP-NodeJS/issues/155
