### ISSUE TITLE
npm run start error

### ISSUE THREAD

**Issue by cali0028** [nfarina/homebridge#369]
been trying this for the last two days but keep getting the following error 

root@devpi:/home/pi/homebridge# node -v
v5.0.0
root@devpi:/home/pi/homebridge# gcc --version
gcc (Raspbian 4.8.2-21~rpi3rpi1) 4.8.2

not sure what else i need to provide as versions go. but below is the error i keep getting every time. 

root@devpi:/home/pi/homebridge# npm run start

> homebridge@0.1.1 start /home/pi/homebridge
> DEBUG=* node app.js || true

*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
module.js:339
    throw err;
    ^

Error: Cannot find module './build/Release/bignum'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at new require (module.js:385:17)
    at Object.<anonymous> (/home/pi/homebridge/node_modules/hap-nodejs/node_modules/srp/node_modules/bignum/index.js:4:14)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
root@devpi:/home/pi/homebridge#

**Comment by kemathy** [comment]
Hi, 
And if you try to reinstall after having installed the bignum module with a "npm install bignum" ?
It may works :-/ (or maybe I'm totally out of subject :-) )

Kevin

**Comment by cali0028** [comment]
I tried running npm install bignum as root just to make sure but didn't work. Only thing I can think of is I am using the A+ not the B or B+...But I don't think hardware has anything to do it with. I am totally lost.

**Comment by cali0028** [comment]
see there are some updates going on home bridge. closing this and going to try the new updated/revised from the main...

**Comment by ronnyandre** [comment]
Still an issue with latest version of Homebridge. Although I'm using and older version of Node for Raspberry Pi Model B.
