### ISSUE TITLE
Wink Client ID/passkey

### ISSUE THREAD

**Issue by keloin** [nfarina/homebridge#371]
Hi everyone,

Quick question - how do you get a client ID for Wink? 
I went quickly thru http://docs.wink.apiary.io, but could not find anything. 
I might just be blind, don't know.
So, please help! :-)

Thanks in advance! 
Sergey.

**Comment by AppleTechy** [comment]
You have to contact wink at questions@wink.com or call them. They will then send you an email asking what is the name of your application, give a description, and any related links. The guy I talked to said about after a week they will contact you back with your id. I just contacted them today will let you know about anything else that comes up in getting the ID. Good Luck, Apple T.
