### ISSUE TITLE
Triggering events based on other events

### ISSUE THREAD

**Issue by fitzage** [nfarina/homebridge#373]
This isn't really an issue so much as it is a question. I have devices connected to homebridge where that's the only way they can speak to each other.

Is there a way to do things like "whenever this harmony activity is activated, set the living room lights to 50%"? Or do I just need to create scenes for things like that?

**Comment by KhaosT** [comment]
If your accessory supports notification, you can setup an event trigger (HomeKit enhancement in iOS 9) on iOS and achieve the behavior you described.

**Comment by fitzage** [comment]
Hmmm…do I need an iOS app that supports the triggers to set that up or something?

**Comment by KhaosT** [comment]
Yep, right now I believe there are only two apps support adding event trigger to HomeKit. First one is Apple's sample app HMCatalog and the second one is [Home](https://appsto.re/us/WRAx7.i).

**Comment by fitzage** [comment]
Cool, thanks.
