### ISSUE TITLE
Plugin author mailing list and notifications

### ISSUE THREAD

**Issue by rodtoll** [nfarina/homebridge#377]
I think it's a great idea to spin the platforms out into separate repositories -- it keeps the core clean and enables plugin authors to handle issues without polluting your core codebase. 

Is it possible to have a mailing list or forum for those of us who are building plugins so we can keep up to date on changes which impact platform? I would like to keep isy-js up to date but I find it difficult to keep checking back looking for changes. You're moving fast and I'd like to keep up. :)

**Comment by nfarina** [comment]
So we have a Slack channel that we could use more; I just added that to the README. We could create an "announcements" channel that people could sign up for email notifications on - or do you think an email group is also needed?

**Comment by nfarina** [comment]
Let's try using Slack for now - I made the #general channel readonly, so you can sign up for email notifications there and chat about stuff in the #plugins channel.
