### ISSUE TITLE
Custom config location

### ISSUE THREAD

**Issue by fitzage** [nfarina/homebridge#378]
I'd love the ability to set a custom config location at runtime with a flag. It would seem that would make it super easy for me to set up a `launchd` script. Right now if I add the new global homebridge to launchd, it can't find the config directory.

**Comment by nfarina** [comment]
Good point - although I think it would have to be for the "storage directory" as a whole which includes config and "persist" files.

**Comment by fitzage** [comment]
Yeah, makes sense. Make it so. :-)

**Comment by nfarina** [comment]
Note that this command line parameter was changed to `-U` or `--user-storage-path` to be consistent with the API naming for plugins.
