### ISSUE TITLE
Never get prompt to enter PIN

### ISSUE THREAD

**Issue by salimyzadeh** [nfarina/homebridge#38]
I have installed Domoticz on my pi and am able to access it from the web and have created a dummy device and test lights on the site
latest commit of homekit is also installed on the pi and the config file is set up to point to local address and port 8080

I can see the devices in the insteon+ app however after selecting the device, I never get a pop up to enter the pin and eventually the device times out and i get the following printed to the console

[Domoticz] There was a problem connecting to Domoticz.
An Error Occured on HAP side connection, { [Error: connect ETIMEDOUT] code: 'ETIMEDOUT', errno: 'ETIMEDOUT', syscall: 'connect' }
Server Disconnected

**Comment by nfarina** [comment]
I think @joepv will have to comment here ... I'm not very familiar with this system.

**Comment by joepv** [comment]
@salimyzadeh: the PIN is only asked when adding a device. This looks like a configuration issue. Is the Domoticz server running on the same host? If not use the correct IP/PORT and not 127.0.0.1 (localhost).

**Comment by salimyzadeh** [comment]
Yes it's running on the same host and port 8080

I then tried to run directly through HAP-NodeJS using command "node core.js" and removed the persist directory and reset the phone configuration but get the same error. I can see the sample devices in the insteon+ app and after tapping "Add anyway," I never get a prompt for the pin
the console shows the following:
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=node
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister
Parsing accessory: Fan_accessory.js
Parsing accessory: GarageDoorOpener_accessory.js
Parsing accessory: Light_accessory.js
Parsing accessory: Lock_accessory.js
Parsing accessory: Thermostat_accessory.js
HAP-NodeJS starting...
Cannot find secret key, creating One...
TCP server accepting connection on port: 51826
HAP Server is listening
Cannot find secret key, creating One...
TCP server accepting connection on port: 51828
HAP Server is listening
Cannot find secret key, creating One...
TCP server accepting connection on port: 51832
HAP Server is listening
Cannot find secret key, creating One...
TCP server accepting connection on port: 51838
HAP Server is listening
Cannot find secret key, creating One...
TCP server accepting connection on port: 51846
HAP Server is listening
New Session 49202
Client Disconnected
An Error Occured on HAP side connection, { [Error: connect ETIMEDOUT] code: 'ETIMEDOUT', errno: 'ETIMEDOUT', syscall: 'connect' }
Server Disconnected

**Comment by nfarina** [comment]
So just HAP-NodeJS by itself doesn't work with the "sample" accessories? If so, I might post this issue on that repo.

**Comment by joepv** [comment]
To test please remove all your accessories from the config en run only the Domoticz platform shim.
Also remove the key file in the homebrigde folder for the devices to get a fresh start pairing everything.

**Comment by madmod** [comment]
You might also want to try resetting HomeKit on your device under Privacy > HomeKit or try a different device if you have one.  Are you running the latest (public release) of iOS?

**Comment by salimyzadeh** [comment]
after starting from scratch i now have everything working
looks like best way to install node is:
apt-get update
apt-get install git-core libnss-mdns libavahi-compat-libdnssd-dev -y
wget http://node-arm.herokuapp.com/node_latest_armhf.deb
dpkg -i node_latest_armhf.deb

thanks

**Comment by nfarina** [comment]
Good to know - I'll add this to the wiki.

**Comment by nfarina** [comment]
What OS are you running on your pi? And are those the complete instructions?

**Comment by salimyzadeh** [comment]
I'm running the latest version of rasbian and yes those are the complete instruction. I then followed the instruction listed in the readme
