### ISSUE TITLE
Running Homebridge on Bootup on RPI

### ISSUE THREAD

**Issue by cali0028** [nfarina/homebridge#383]
Not sure if the wiki needs to be updated...i've tried and followed the settings and the auto start on pi reboot is not working. 

I am guessing the install location has been changed from /home/pi/homebridge? 

thanks.

**Comment by luc-ass** [comment]
I think it moved to /usr/local/bin/homebridge

Have a look there...

**Comment by cali0028** [comment]
okay updated the /etc/init.d/hombridge to point to /usr/local/bin/homebridge and then ran command "sudo /etc/init.d/homebridge start" but it didn't start it

**Comment by luc-ass** [comment]
did you cd into that folder and check if it is in there?

**Comment by luc-ass** [comment]
oh! Sorry... my fault...
the folder is /usr/local/lib/
check if it is there anyway!

**Comment by cali0028** [comment]
No it's under /usr/local/bin/. homebridge is not under /usr/local/lib.

**Comment by luc-ass** [comment]
hmm... perhaps you join http://homebridgeteam.slack.com

**Comment by luxus** [comment]
It's not a solution. But perhaps a alternative

I use pm2 for starting on boot up
http://www.domoticz.com/forum/viewtopic.php?f=36&t=6864&start=200#p51609

**Comment by cali0028** [comment]
@luxus Thanks. Tired to follow your inst. and when I run "pm2 start app.js --name HomeBridge" I get error "[PM2][ERROR] script not found : /home/pi/app.js". 

I think the error is with app.js

tired npm install -g app.js but I don't think that would solve the problem. 

@nfarina Nick any thoughts or help? 

thanks

**Comment by luxus** [comment]
Looks like you not running it from the homebridge root folder

**Comment by mishakim** [comment]
I'm having the same problem trying to follow the instructions on the wiki. I updated the script so that dir='/usr/local/bin" since that's where homebridge is. The homebridge.err log has two errors, that it can't find module '/home/pi/app.js' and /usr/local/bin/app.js'

**Comment by cali0028** [comment]
Finally figured this out..just need someone to test and confirm...

First the issue: The forever service was never installed. Not sure if it's being installed when home bridge is installed.  

Fix: Install forever as follows:

1. npm install -g forever
2. npm install -g forever-service
3. Follow the inst. on the wiki on how to do the run on boot except change this part
         dir="/usr/local/bin/"
         cmd="homebridge"
         user="root"  
4. sudo /etc/init.d/homebridge start (If this command works then you are golden)
5. And reboot and it should work. Well atleast it worked for me! 

Let me know if this works for anyone else. 

Thanks

**Comment by mishakim** [comment]
Yep, that worked, homebridge came up for both a manual start and on reboot. Had some confusion because I'd been running it from my home directory, and it was looking for the config.json in /root/.homebridge, and once that was fixed the iOS thought it was a new accessory, but that was easy to straighten out

**Comment by cali0028** [comment]
@mishakim Thanks for confirming. @nfarina I guess at this point the wiki needs to be updated on how to do this.

**Comment by petkoe** [comment]
@cali0028 @nfarina  Hi if line 3 the user is "root" it di not work for me in a raspberry just run it as "raspberry"

**Comment by cali0028** [comment]
@petkoe did you create a new user as raspberry?

**Comment by petkoe** [comment]
cups theres is something wrong, my standard user is "pi" with the standard password. It is correct in "init.d". I need no "sudo" to run homebridge on the pi. So it seems both versions work ok

**Comment by AppleTechy** [comment]
@nfarina Has this already been fixed in the wiki?
