### ISSUE TITLE
HELP:  Cannot get Z-Way Server to connect

### ISSUE THREAD

**Issue by rhearob** [nfarina/homebridge#386]
I am getting the following error when I execute Homebridge and connect to the Z-Way Server:

/usr/local/lib/node_modules/homebridge-legacy-plugins/platforms/ZWayServer.js:43
            if(response.statusCode == 401){
                       ^

TypeError: Cannot read property 'statusCode' of undefined
    at Request._callback (/usr/local/lib/node_modules/homebridge-legacy-plugins/platforms/ZWayServer.js:43:24)
    at self.callback (/usr/local/lib/node_modules/homebridge-legacy-plugins/node_modules/request/request.js:373:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Request.onRequestError (/usr/local/lib/node_modules/homebridge-legacy-plugins/node_modules/request/request.js:971:8)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at TLSSocket.socketErrorListener (_http_client.js:259:9)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)

I am assuming I am getting this error because the HTTP request is failing for some reason and as a result Request in undefined.  I have Z-way installed behind the NGINX running as a reverse router and a SSL cert.  For the time being with testing I have turned of httpaccess for additional security.

Here is the result of /ZAutomation/api/v1/devices on port 8085 of my z-way server.

{"data":{"structureChanged":true,"updateTime":1446959828,"devices":[{"creatorId":11,"deviceType":"toggleButton","h":557861321,"hasHistory":false,"id":"LightScene_11","location":0,"metrics":{"level":"on","icon":"","title":"Morning"},"permanently_hidden":false,"tags":[],"visibility":true,"updateTime":1446954699},{"creatorId":13,"deviceType":"switchBinary","h":2095255578,"hasHistory":false,"id":"HTTP_Device_switchBinary_13","location":6,"metrics":{"icon":"switch","title":"Overhead Lamp","level":"off"},"permanently_hidden":false,"tags":[],"visibility":true,"updateTime":1446954700},{"creatorId":14,"deviceType":"switchBinary","h":2095255579,"hasHistory":false,"id":"HTTP_Device_switchBinary_14","location":7,"metrics":{"icon":"switch","title":"Thomas Office","level":"off"},"permanently_hidden":false,"tags":[],"visibility":true,"updateTime":1446954700},{"creatorId":15,"deviceType":"switchBinary","h":2095255580,"hasHistory":false,"id":"HTTP_Device_switchBinary_15","location":3,"metrics":{"icon":"switch","title":"Back Porch Light","level":"on"},"permanently_hidden":false,"tags":[],"visibility":true,"updateTime":1446954700},{"creatorId":16,"deviceType":"switchBinary","h":2095255581,"hasHistory":false,"id":"HTTP_Device_switchBinary_16","location":3,"metrics":{"icon":"switch","title":"Side Yard Flood","level":"on"},"permanently_hidden":false,"tags":[],"visibility":true,"updateTime":1446954700},{"creatorId":17,"deviceType":"switchBinary","h":2095255582,"hasHistory":false,"id":"HTTP_Device_switchBinary_17","location":3,"metrics":{"icon":"switch","title":"Carport","level":"on"},"permanently_hidden":false,"tags":[],"visibility":true,"updateTime":1446954700},{"creatorId":8,"deviceType":"battery","h":-592588977,"hasHistory":false,"id":"BatteryPolling_8","location":0,"metrics":{"probeTitle":"Battery","scaleTitle":"%","title":"Battery digest 8","level":80},"permanently_hidden":false,"tags":[],"visibility":true,"updateTime":1446954704},{"creatorId":1,"deviceType":"switchBinary","h":1078449915,"hasHistory":false,"id":"ZWayVDev_zway_2-0-37","location":1,"metrics":{"icon":"switch","title":"Sink","level":"off"},"permanently_hidden":false,"tags":[],"visibility":true,"updateTime":1446954703},{"creatorId":1,"deviceType":"switchBinary","h":1135708217,"hasHistory":false,"id":"ZWayVDev_zway_4-0-37","location":1,"metrics":{"icon":"switch","title":"Overhead","level":"off"},"permanently_hidden":false,"tags":[],"visibility":true,"updateTime":1446954703},{"creatorId":1,"deviceType":"switchBinary","h":1164337368,"hasHistory":false,"id":"ZWayVDev_zway_5-0-37","location":2,"metrics":{"icon":"switch","title":"Outlet","level":"on"},"permanently_hidden":false,"tags":[],"visibility":true,"updateTime":1446954703},{"creatorId":1,"deviceType":"switchBinary","h":1192966519,"hasHistory":false,"id":"ZWayVDev_zway_6-0-37","location":4,"metrics":{"icon":"switch","title":"Foyer","level":"off"},"permanently_hidden":false,"tags":[],"visibility":true,"updateTime":1446957903},{"creatorId":1,"deviceType":"switchBinary","h":1221595670,"hasHistory":false,"id":"ZWayVDev_zway_7-0-37","location":3,"metrics":{"icon":"switch","title":"Garage","level":"on"},"permanently_hidden":false,"tags":[],"visibility":true,"updateTime":1446954704},{"creatorId":1,"deviceType":"switchBinary","h":1250224821,"hasHistory":false,"id":"ZWayVDev_zway_8-0-37","location":"3","metrics":{"icon":"switch","title":"Front Door","level":"on"},"permanently_hidden":false,"tags":[],"visibility":true,"updateTime":1446954704},{"creatorId":1,"deviceType":"doorlock","h":-1646206616,"hasHistory":false,"id":"ZWayVDev_zway_13-0-98","location":"1","metrics":{"level":"open","icon":"door","title":"Door Lock"},"permanently_hidden":false,"tags":[],"visibility":true,"updateTime":1446954704},{"creatorId":1,"deviceType":"battery","h":507194638,"hasHistory":false,"id":"ZWayVDev_zway_13-0-128","location":0,"metrics":{"probeTitle":"Battery","scaleTitle":"%","level":80,"icon":"battery","title":"Battery 13-0"},"permanently_hidden":false,"tags":[],"visibility":true,"updateTime":1446954704},{"creatorId":1,"deviceType":"switchBinary","h":-1617577652,"hasHistory":false,"id":"ZWayVDev_zway_14-0-37","location":5,"metrics":{"icon":"switch","title":"Thomas Bedside","level":"off"},"permanently_hidden":false,"tags":[],"visibility":true,"updateTime":1446954705},{"creatorId":1,"deviceType":"switchBinary","h":-1588948501,"hasHistory":false,"id":"ZWayVDev_zway_15-0-37","location":5,"metrics":{"icon":"switch","title":"Robert Bedside","level":"off"},"permanently_hidden":false,"tags":[],"visibility":true,"updateTime":1446954705},{"creatorId":1,"deviceType":"switchBinary","h":-1560319350,"hasHistory":false,"id":"ZWayVDev_zway_16-0-37","location":1,"metrics":{"icon":"switch","title":"Entry","level":"off"},"permanently_hidden":false,"tags":[],"visibility":true,"updateTime":1446954705}]},"code":200,"message":"200 OK","error":null}

Here is the platform section for z-way out of my config.son file:

```
     {
        "platform": "ZWayServer",
        "url": "https://192.168.0.248:8085/",
        "login": "home",
        "password": "bridge",
        "poll_interval": 2,
        "split_services": false,
        "opt_in": false
    }
```

The user in z-way is a normal user, not an admin and not a local user.  I have tried all variations on the root url including 127.0.0.1, localhost, etc.  If I use HTTP instead of https I do not get the error, but I do get a time out.  I imagine this is just because the server is not answering without the secure connection.

also here is the result of name -a  (I am running on a ras pi B+ with Raspbian jesse

Linux ae35.rheahometn.com 4.1.7+ #817 PREEMPT Sat Sep 19 15:25:36 BST 2015 armv6l GNU/Linux

and node -v
v4.2.1

If I take the Z-Way server out of my config.son file Homebridge connects to other HTTP services just fine.  The only issue it has is with the Z-Way Server.

Please Help!  I have been hammering away at this for almost two days now and can't find anything.  So far I am loving home bridge so much more than the crappy home kit implementation in Z-Way itself and am excited to get my family set up completely.

EDIT:  I should Mention that I am running Razberry/Z-Way Server 2.1.1

**Comment by rhearob** [comment]
OK, So I made the following updates to the ZWayServer.js to trap the undefined response.  I do not get the error when I run homebridge.  The problem, however, is that it now even though homebridge execute, it times out when trying to connect to Z-Way.  No devices are discovered and loaded.

When I execute the logon from the command line with CURL, I do get a response immediately (Homebridge and Z-Way are running on the same pi).

This is the CURL I am using:

curl --insecure -i -H "Accept: application/json" -H "Content-Type: application/json" -X POST -d '{"form": true, "login": "XXXXXX", "password": "XXXXXX", "keepme": false, "default_ui": 1}' 'https://XXXXXXX:XXXXXXX@192.168.0.248:8085/ZAutomation/api/v1/login' -c cookie.txt

and the lines from config.son

         {
            "platform": "ZWayServer",
            "url": "https://XXXXXXX:XXXXXXX@192.168.0.248:8085/",
            "login": "XXXXXXX",
            "password": "XXXXXXX",
            "poll_interval": 2,
            "split_services": false
        },

ZWayServerPlatform.prototype = {

    zwayRequest: function(opts){
        var that = this;
        var deferred = Q.defer();

        opts.jar = true;//this.jar;
        opts.json = true;
        opts.headers = {
            "Cookie": "ZWAYSession=" + this.sessionId
        };

        request(opts, function(error, response, body){
            if(response === undefined || response.statusCode != 200){
                debug("Authenticating...");
                request({
                    method: "POST",
                    url: that.url + 'ZAutomation/api/v1/login',
                    body: { //JSON.stringify({
                        "form": true,
                        "login": that.login,
                        "password": that.password,
                        "keepme": false,
                        "default_ui": 1
                        "keepme": false,
                        "default_ui": 1
                    },
                    headers: {
                        "Accept": "application/json",
                        "Content-Type": "application/json"
                    },
                    json: true,
                    jar: true//that.jar
                }, function(error, response, body){
                    if(response != undefined && response.statusCode == 200){
                        that.sessionId = body.data.sid;
                        opts.headers["Cookie"] = "ZWAYSession=" + that.sessionId;
                        debug("Authenticated. Resubmitting original request...");
                        request(opts, function(error, response, body){
                            if(response.statusCode == 200){
                                deferred.resolve(body);
                            } else {
                                deferred.reject(response);
                            }
                        });
                    } else {
                        deferred.reject(response);
                    }
                });
            } else if(response != undefined && response.statusCode == 200) {
                deferred.resolve(body);
            } else {
                deferred.reject(response);
            }
        });
        return deferred.promise;
    }

Any ideas why I might be getting a timeout?

**Comment by rhearob** [comment]
One More Update:  

When I comment out all of my NGINX SSL and delete my IPTABELS Firewall rules this works on port 8083.

**Comment by SphtKr** [comment]
Hello @rhearob , Did you get this working? I'm finally back and am working on a module version of the platform. My guess would be that the underlying `request` module is rejecting or failing to connect because of a self-signed certificate--which I infer because you're using the ` --insecure` flag in your `curl` command.

In short, that is expected behavior. Though I can see the use case for allowing it. There are two options:

1. Make your self-signed cert trusted by the underlying OS where Homebridge is running, which hopefully will allow the `request` module to trust the cert (and probably wouldn't have to use the `curl --insecure` flag, either)

2. I can add a config parameter that would let you specify the filename of your (public) certificate file, which would be passed through to `request` so that it would allow the connection.

3. Reconfigure your NGINX proxy to not use SSL (or to be bypassed entirely) for local network requests

Since I'm assuming that your Homebridge installation and your ZWay server instance are on the same network, I'd recommend option no. 3. There's substantially less reason to mess with SSL-enabling on your local network (lots of reasons to do it if you're hitting your ZWay server from the internet!). Unless you're on a dorm/shared network, or running wifi unsecured or something, you already have pretty substantive layers of protection surrounding your local network traffic. Option no. 1 is also probably the quickest way to get it going. This should be pretty easy to Google how to do, depending on the OS your Homebridge is running on.

If you're still stuck, please open an issue on the [new plugin repo](https://github.com/SphtKr/homebridge-zway).
