### ISSUE TITLE
fhem shim 

### ISSUE THREAD

**Issue by justme-1968** [nfarina/homebridge#388]
i have ported the fhem shim to the new plugin api. so the version from homebridge-legacy-plugins should probably be removed.

it is here: https://github.com/justme-1968/homebridge-fhem and can be installed with 
```
npm install -g https://github.com/justme-1968/homebridge-fhem.git
```

there will probably no version from the npm web site as i do not intend to have a public e-mail adress somewhere and also there is already a version from cflurin with the same name.

**Comment by cflurin** [comment]
@nfarina, @justme-1968: I've changed my Plugin name to homebridge-punt.

**Comment by nfarina** [comment]
@justme-1968 OK done thanks.
