### ISSUE TITLE
Have to reset config and reload on startup

### ISSUE THREAD

**Issue by Be2daErtin** [nfarina/homebridge#389]
Hi,

I'm writing a plugin for Vera. Everything works fine up to the point where I restart homebridge. (Due to changes made in my code)
Upon restart, all devices on the iOs app are grayed out. I then have to reset homkit config on the phone and delete the persist folder.

Is this normal behavior or something that the plugin should cater for?

**Comment by Apollon77** [comment]
I have this effect sometimes also after certail time, and yes, most likely after a restart ...

**Comment by Samfox2** [comment]
I remember there was an "issue" if reported values are not in the correct min/max interval (e.g. humidity = 500). Then the configuration was blocked by homekit and had to be deleted. Maybe that`S the case?

**Comment by snowdd1** [comment]
I see two possible causes:
- The "incomplient value" issue @Samfox2 described above. I had this behaviour that reported a 0 as target temperature which was out of bounds of 10..40 °C that were default for temperature sensor. This might apply also for all "fixed list" value types, such as current or target heating/cooling modes, garage door status, etc. Sometimes the invalid values are simply ignored, sometimes the whole bridge gets blacklisted (and the devices greyed out). Err, and step values might be a cause also, if the characteristic is defined as "[0.100] step 2" you must not set a value of 3; also values of 21.00000002 sometimes lead to an immediate "dislike" of the bridge.
- unique device IDs: Have you made sure that with each start of homebridge your devices get the same user names? If you are using uuid_base, you must not change that value between restarts. So if you are simply enumerating your devices (sorry, I have no clue about Vera!), you are having trouble if the are discovered in changing order.

Regards

**Comment by amitgandhinz** [comment]
okay, i did the nuclear option, and uninstalled homebridge and all plugins.  Then I npm installed everything again, and changed both the bridge name and bridge username values to something i havent used before.  

The device was immediately discovered and appears to be working.

**Comment by mul891** [comment]
I'm also experiencing the same problem: HomeBridge accessories not being discovered after a while. Also tried restarting both iOS and host pc, removing configuration, removing persist but to no avail. How can the bridge name and username be changed? How do you reverse the npm install process?

**Comment by amitgandhinz** [comment]
@mul891 

# Uninstall Homebridge
$ sudo npm uninstall homebridge

# uninstall platforms
$ sudo npm uninstall -g homebridge-nest
$ sudo npm uninstall -g homebridge-sonos
...

# delete persists folder
rm -rf .homebridge/persist/

# reinstall everything as per the README instructions
# edit your ~/.homebridge/config.json file, giving your bridge a unique name and username.
