### ISSUE TITLE
Stability (connection) Homebridge

### ISSUE THREAD

**Issue by PatcherMustermann** [nfarina/homebridge#391]
Hello everybody,
I have problems with the stability of the home bridge. If my iPhone loses the connection of wi-fi (for example, standby, flight mode, and so on ...) then can no reconnect the Homebridge after reconnect wi-fi. If I restart the Home Bridge, then everything is okay again.

I've been using netstart checked the connection and see that the connection from the Home Bridge to my iPhone still exists although the iPhone is no longer in the wi-fi. After about 5 minutes I see over netstart that the Home Bridge disconnected the conecction to the iPhone. A new connection with no restart the homebridge is not possible.

I'm think, that the homebridge have no correct check the lost connection from the iDevice. 

Has one an idea how I can get the problem under control?

Only for information: 
- The problem I have with the old and the new version of homebridge
- I have install the homebridge on Windows 7

Thank you for your help!

Greeting Patcher

**Comment by KhaosT** [comment]
"I've been using netstart checked the connection and see that the connection from the Home Bridge to my iPhone still exists although the iPhone is no longer in the wi-fi. After about 5 minutes I see over netstart that the Home Bridge disconnected the conecction to the iPhone." this is expected behavior. However, with some routers and Bonjour on Windows, sometime iOS device will not be able to rediscover the homebridge after it comes back to WiFi environment... Restarting homebridge will force homebridge to re-initiate a Bonjour advertisement which will let iOS rediscover the bridge. I'm not sure if there are any fixes to this problem through.

**Comment by PatcherMustermann** [comment]
@KhaosT: Thanks for your answer. I have installed on my test environment also iTunes. Could it be that iTunes gives me trouble (because the iTunes Bonjour Service)?

Greeting Patcher

**Comment by askme233** [comment]
Looking to solve a similar problem, I found the Bonjour Browser app (free) valuable to see the details of what was being advertised and when (from the iOS side).  It shows you what iOS sees in terms of available Bonjour connections.

I never found my problem as when I rebuilt from the latest versions, my issues went away.  I can confirm that I can disconnect iOS from my network (e.g. standby) and when I reconnect, the Homebridge connection is re-established.

**Comment by PatcherMustermann** [comment]
@askme233: I have testet the connection over the app "Bonjour Browser". After the Wi-Fi connection is lost to the iPhone the app "Bonjour browser" shows no longer the HomeBridge. Nevertheless, many thanks!

@KhaosT: I read a lot of posts, where the problem is also on Raspberry Pi (Linux).

@All: What is the best TCP-Port for the homebridge?

**Comment by askme233** [comment]
I have both a Windows and Linux VM version of Homebridge. I assume you mean that the Bonjour connection no longer shows after wifi connection is broken and then re-established as is clearly would not be there without a Wifi connection.

**Comment by PatcherMustermann** [comment]
@askme233: First, sorry for my bad english.

 I assume you mean that the Bonjour connection no longer shows after wifi connection is broken and then re-established as is clearly would not be there without a Wifi connection. 
--> That's what I wanted to tell

**Comment by PatcherMustermann** [comment]
I have yesterday testing the Homebridge of a other System with new installt Windows 10 Sytems without connection problems. I think it was a problem from my Testmachine. Thanks for your help!

Greeting
Patcher
