### ISSUE TITLE
Siri 'Not Finding' WeMo Switches

### ISSUE THREAD

**Issue by barryjarvis** [nfarina/homebridge#392]
I have tonight added a second WeMo switch to Homebridge, which is recognised within HomeKit Apps on iOS (Insteon+ App) and i can toggle manually etc.

When i say to Siri "Turn on the Lamp in the lounge" however, it turns the switch on, but the Siri response is "Sorry, i couldn't find any lights in the lounge".

It works flawlessly with my other WeMo switch in the dining room (again acting as a lamp within HomeKit), but this Siri doesn't seem to like this second switch, despite actually triggering the action.

Any known issues with multiple WeMo switches?

**Comment by rudders** [comment]
Make sure the WeMo device type is set as a Light Bulb in Insteon.

**Comment by kicketster** [comment]
@barryjarvis may I know how you connect WeMo with HomeKit and Insteon+?

**Comment by kicketster** [comment]
@rudders ^^^
