### ISSUE TITLE
.homebridge folder was created after first start of homebridge but not after the installation

### ISSUE THREAD

**Issue by NetRat88** [nfarina/homebridge#394]
The ./homebridge folder under /home/pi on a raspberry pi version B is not automatically created after installation of homebridge with "npm install -g homebridge"
The folder was created after the first start of homebridge.

**Comment by nfarina** [comment]
Homebridge shouldn't be creating that folder by itself at all (and it's impossible to do it when `npm install`'d) - it should only let you know where it expects to find it.

**Comment by NetRat88** [comment]
This was fast!
Good to know! Thanks

**Comment by cflurin** [comment]
@nfarina: I just tried on a RPi 2. Starting homebridge the first time creates the folder .homebridge if it doesn't exist.

**Comment by NetRat88** [comment]
Exactly! I thought its a bug and it should be created after the installation. ;-)

**Comment by nfarina** [comment]
Oh you know what - The `persist` package is creating it. So running homebridge will create the directory if it doesn't exist.

**Comment by NetRat88** [comment]
Good to know! Thanks and keep it up, great tool nfarina!

**Comment by cflurin** [comment]
Just now I don't see a solution, this is also the case for the  `.homebridge/plugins folder`.
A note in README may be helpful.
