### ISSUE TITLE
Installing dynamic accessories

### ISSUE THREAD

**Issue by oddwires** [nfarina/homebridge#396]
Hi,

I have a homemade system, providing a web-app gui to control power sockets around my house through a 433MHz radio link. I've been successfully using the previous version of Homebridge with it.
This meant I could use either the web app, or any of the Homekit apps, or Siri to control devices.

Previously I have used two stages to integrate Homebridge to my system...
1) Create a number of custom accessory files and store them in ~/Downloads/homebridge/accessories
2) Create a corresponding json.config and store it in ~/Downloads/homebridge
All the files were created programmatically by the web-app. Then I'd restart app.js, and everything was great.

So now I've installed the latest version of Homebridge using the npm installer, but can’t get my head around the changes to the accessories installation. My accessories aren’t static, as they are created on the fly through my web app, so I don’t want to install them as an npm module.

I’m fairly sure I've got the Homebridge install working ok, and I've picked up the detail about config.json now residing in ~/.homebridge.

I've tried dropping the accessories into the same directory as the config.json, but when I start Homebridge, I get an error....

`No plugins found. See the README for information on installing plugins.
Loaded config.json with 6 accessories and 0 platforms.`

`Loading 0 platforms...
Loading 6 accessories...
/usr/local/lib/node_modules/homebridge/lib/api.js:47
      throw new Error("The requested accessory '" + name + "' was not registered by any plugin.");
      ^`

`Error: The requested accessory 'Blue' was not registered by any plugin.
    at API.accessory (/usr/local/lib/node_modules/homebridge/lib/api.js:47:13)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:155:42)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:36:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:23:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)`

So where should the accessory files go ? and do I need to register them ? and how do I register them ?

( Thanks in advance for any help – really great project )

**Comment by snowdd1** [comment]
Hi @oddwires ,
so many questions!

1. Where to put your accessories: You may keep the folder as it was. See [/lib/cli.js](https://github.com/nfarina/homebridge/blob/master/lib/cli.js) for the command line option to point homebridge to your folder:
     `-P`, `--plugin-path [path] ` 'look for plugins installed at [path] as well as the default locations ([path] can also point to a single plugin)'
     `-U`, `--user-storage-path [path]`  'look for homebridge user files at [path] instead of the default location (~/.homebridge)'
     `-D`, `--debug`, 'turn on debug level logging'
( @nfarina : is there a reason that's not mentioned in the readme?)

2. How to register accessories: You might think of making your accessory-generator a platform, instead of generating single accessory files. However, both is possible. At the bottom of the readme is a section called [writing plugins](https://github.com/nfarina/homebridge#writing-plugins). Consider reading that and looking into the given examples.

Regards

**Comment by oddwires** [comment]
Hi @snowdd1, 

1. Command line parameters !!! ...................Brilliant. I never thought of that.
2. It Sounds like registering the accessories isn't anything more demanding than creating the plugin file. So I've probably got that sorted already. But I'll also look into creating a platform.

I'll give it another go at the weekend.

Thanks for the pointers.

**Comment by oddwires** [comment]
Sorry guys - I never did manage to get this working. I'm not sure using npm to install the accessories is what I am after for my system, so I'm moving my code back to use the HAP-NodeJS repository.

But thanks for the help - and keep up the good work   :)

**Comment by LwsBtlr** [comment]
When I startup home bridge I get "Registering platform 'homebridge-myq.MyQ'" but then I get "The requested accessory 'MyQ' was not registered by any plugin." There seems to be little ample documentation how to setup these various sorts of devices.

**Comment by AppleTechy** [comment]
Use the LiftMaster plugin it has been developed more and will continue to
be developed. And to install the plugin run "npm install -g
homebridge-LiftMaster" then edit you config.json to fit the LiftMaster
plugin and delete the portion related to the MYQ plugin.

**Comment by lbutlr** [comment]
Hello,

I was wondering how I was mentioned in this post? My github username is
mentioned in this line: On Friday, February 12, 2016, @lbutlr.

I am not familiar with this product, maybe this was done in error?

Logan

**Comment by AppleTechy** [comment]
Your account posted an issue on homebridge with how to load the
homebridge-MYQ plugin. Was this an accident or was this by mistake? Just
want to clarify if you actually had a question about homebridge or not.

**Comment by lbutlr** [comment]
weird. I haven't used github in 8 months...

**Comment by AppleTechy** [comment]
Sorry for any complication that this might have caused you. For some reason
something got screwed up on Github and for some reason it emailed you not
@LwsBtlr who had posted the orginal issue I was responding to

**Comment by AppleTechy** [comment]
@LwsBtlr Can you check my above comments as a possible solution for your issue.

**Comment by lbutlr** [comment]
No worries, I'm glad someone else wasn't in my account. Good luck on the
project!

**Comment by LwsBtlr** [comment]
Sorry, my "name" is set to my twitter handle, @lbutlr.

Thanks for the point on using the LiftMaster plugins instead, but I get `Registry returned 404 for GET on https://registry.npmjs.org/homebridge-LiftMaster` when I try to install that. I also tried chamberlain

**Comment by AppleTechy** [comment]
@LwsBtlr Try the the exact command I posted here. It might not have liked the capitals "npm install -g homebridge-liftmaster " let me know if that worked

**Comment by LwsBtlr** [comment]
Thanks, no caps did work. Now it's setup and launches, but if I issue a command it dies with a SecurityToken error, so off to investigate that. The docs say I should only need deviceID with multiple openers, which I don't have. Still, progress!

**Comment by AppleTechy** [comment]
@LwsBtlr Can you now move your issue over to the GitHub page for the
LiftMaster plugin and make a new issue with the exact error it is giving
you.

**Comment by LwsBtlr** [comment]
OK, I setup a new issue on the lift master page, but I think there' not a lot of traffic over there.

[https://github.com/nfarina/homebridge-liftmaster/issues/13](url)
