### ISSUE TITLE
Logfile

### ISSUE THREAD

**Issue by ak0815** [nfarina/homebridge#399]
Hello,

according to the guide here
https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi

is described that with

tail -f /var/log/homebridge.log

can look at the log file. This directory but is no logfile.
How can I activate it?

Thanks
Andy

**Comment by csawall** [comment]
Are you running it manually from the command line or starting it with the init.d script?  I believe it is the init.d script that sets up the logging output of the program.  It's not within the app itself.

**Comment by radinsky** [comment]
I running with DEBUG=* homebridge -D but no /var/log/homebridge.log created indeed.

**Comment by snowdd1** [comment]
Did you start from command line or via systemd service file? In case of the latter you need to access the log with `sudo journalctl`

**Comment by radinsky** [comment]
I start from command line

**Comment by snowdd1** [comment]
Are you sure your output will not simply appear in the terminal ? If you just start it the standard out and standard error targets are the console. So no file gets created.  
You might want to route them to the file by appending `&>/var/log/homebridge.log` to your command.

**Comment by radinsky** [comment]
Yes, that makes sense
