### ISSUE TITLE
Unlicensed accessories

### ISSUE THREAD

**Issue by PatcherMustermann** [nfarina/homebridge#400]
Why does the EVE App Homebridge as unlicensed accessories? 
Is there possibly a way to change this?

Greeting
Patcher

**Comment by nfarina** [comment]
This cannot be changed, unfortunately, without Apple "approving" Homebridge as a licensed accessory, which they would never do :)

**Comment by PatcherMustermann** [comment]
@farina: Okay I understand. 

How to recognize Apple an unlicensed accessories? 
- Harware: As an example -> MAC address 
- Software: As an example -> Specific key
- Hardware and Software 

This is only for my understanding -> I want no to do anything illegal.

Greeting
Patcher

**Comment by nfarina** [comment]
I believe Apple must sign your HomeKit identifier with their private signing key. @KhaosT may know more :)

**Comment by KhaosT** [comment]
@PatcherMustermann It's "unauthorized" not unlicensed... The way iOS checks that is by a flag and by perform an extra step in Pair-Setup with MFi chip to confirm the accessory has a MFi chip inside.

**Comment by PatcherMustermann** [comment]
@nfarina and @KhaosT: Thank you for the fast answer! 

Greeting
Patcher
