### ISSUE TITLE
Nest showing wrong temp conversion 

### ISSUE THREAD

**Issue by julianfez** [nfarina/homebridge#401]
Nest showing wrong temp conversion i have my thermostat in F but in homekit shows the temp in C 
And i check the logs and detect F but convert to C

[Nest] Update to Device: 02AA01AC35140AKU type: device   │
homebridge-0 [Nest] Tempature unit for Thermostat is: Fahrenheit      │
homebridge-0 [Nest] Current temperature for Thermostat is: 21.93      │
homebridge-0 [Nest] Current heating for Thermostat is: 1              │
homebridge-0 [Nest] Current humidity for Thermostat is: 50            │
homebridge-0 [Nest] Target heating for Thermostat is: 1               │
homebridge-0 [Nest] Target temperature for Thermostat is: 22.222222222]

**Comment by KraigM** [comment]
Go ahead an close this and move to https://github.com/KraigM/homebridge-nest
