### ISSUE TITLE
New wiki : Homebridge on Windows

### ISSUE THREAD

**Issue by WilliamHF** [nfarina/homebridge#402]
I'm going to give it a try later on, but just wondering if the wiki on Homebridge for Windows environment is being updated by someone already?
Would like to install the latest version with modules and was double checking my prerequisites, as I have a working nodeJS environment I wanted to minimise disruption...

Regards,

**Comment by PatcherMustermann** [comment]
I have created the Wiki. I think I can update the wiki later. But I've tested so far only on a system.

Greeting
Patcher

**Comment by PatcherMustermann** [comment]
I have make a description for install the new Homebridge on WIndows:

-> https://github.com/nfarina/homebridge/wiki/Install-homebridge-on-Windows----New-version-%28with-Plugin%29

Greeting
Patcher

**Comment by PatcherMustermann** [comment]
...close please this issues!

**Comment by WilliamHF** [comment]
Many thanks Patcher !

**Comment by PatcherMustermann** [comment]
@WilliamHF: Running the Homebridge after my instruction?

Greeting
Patcher

**Comment by WilliamHF** [comment]
Hi, Had an issue while trying yesterday, must be due to my existing nodejs install in an older version, have to figure out how to make them coexist. I'll give it another try tonight and let you know ;)

**Comment by WilliamHF** [comment]
Hi Patcher,

After a couple tries and some tweaking with VC 2015 + node-gyp it finally worked !!
I just had to remove the 4 blank #include in your unistd.h that were crashing the build

Works like a charm now. 

Thanks for the walkthrough!

Will

**Comment by PatcherMustermann** [comment]
@WilliamHF : Thank you for your answer. Have you changed only the "unistd.h"? Can your "unistd.h" publish? 

Greeting
Patcher

**Comment by PatcherMustermann** [comment]
@WilliamHF: I have your and my Version of  "unistd.h" implemented in the Wiki. Thank you for your Version!
