### ISSUE TITLE
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/4.2.2"

### ISSUE THREAD

**Issue by deennoo** [nfarina/homebridge#405]
Hello,

Trying get home bridge on i386 device
uname -a
Linux localhost 3.10.20-ga0b64e7-dirty #1 SMP PREEMPT Mon Sep 22 12:17:58 CST 2014 i686 GNU/Linux

gcc -v
gcc version 4.7.2 (Debian 4.7.2-5)

node -v
v.4.2.2

npm -v
2.14.7

Got this error when run : sudo npm install -g homebridge 

of course npm run start says : 

npm ERR! Linux 3.10.20-ga0b64e7-dirty
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "start"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7

npm ERR! missing script: start
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /home/android/homebridge/npm-debug.log

How to solve please

**Comment by PJCzx** [comment]
Are you on a mac ? Could be a Xcode agreement thing. Otherwise, I got once this message it was due to Node version (Node Version Manager NVM can help on this)

Best

**Comment by deennoo** [comment]
M'y config is a bit spécial...I'm using a linux emulator on an Android device intel proc, for an home automation with domoticz.It run wheezy i386 version.Will check NVMEnvoyé depuis mon mobile Huawei-------- Message original --------Objet : Re: [homebridge] gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/4.2.2" (#405)De : Pierre-Julien Cazaux À : nfarina/homebridge Cc : deennoo Are you on a mac ? Could be a Xcode agreement thing. Otherwise, I got once this message it was due to Node version (Node Version Manager NVM can help on this)

Best

**Comment by deennoo** [comment]
got a small succes here : NVM allow me to compil and run homebridge.

Now homebridge asking for config.json, great ! but homebridge directory is /home/android/.nvm/homebridge

i can"t acces to .nvm...can't see it on dir cmd

**Comment by vogelboy** [comment]
This same permission error is causing me problems as well. I am on a Raspberry Pi and have tried installing on both Jessie and Wheezy (making sure to use the correct compiler as stated in the Wiki), got the same errors with multiple versions of Node, and tried installing on my Mac as well - all give the same errors and after install am unable to run- i get a command not found error. I tried issuing the install command twice, the second time I got the config.son file not found error, however after placing a config.json file in the directory that was listed, I got a completely different error (this was using a config file that I had working on an old install). 

Anyone have any ideas what is going on?

**Comment by achingbrain** [comment]
Have you tried installing homebridge with the `--unsafe-perm` option?  e.g.

```
sudo npm install -g --unsafe-perm homebridge
```

If npm detects it is running as root it drops to a non-privileged user which then doesn't have permissions to write to `/root/.node-gyp`.  The `--unsafe-perm` option stops it from changing user.

nvm doesn't have this problem when not using sudo because it stores everything under the current users' home directory.

**Comment by vogelboy** [comment]
Aching- This worked for me!! Thanks :+1:

**Comment by jcwcheng** [comment]
<code>
sudo npm install -g --unsafe-perm homebridge
</code>

Thx to achingbrain, it worked for me, too!

**Comment by sivann-tw** [comment]
I was trying to install noblejs modules. This really works for me and my RasPi2 man! Thanks.

**Comment by mareeb** [comment]
Please run "sudo /opt/node/bin/npm install (Instead of npm install)"

Where /opt/node/bin/npm is the complete path of binary. This will resolved your issue.
