### ISSUE TITLE
Control raspberry pins pi

### ISSUE THREAD

**Issue by arr00** [nfarina/homebridge#406]
How would I be able to control pins on the raspberry pi. Which plugins should I use and how would I go about turning on and off pins.

**Comment by PJCzx** [comment]
Depending on what you are trying to do, you can Base your work on a new lightbulb implementation and use raspi-gpio plug-in ?

Pierre-Julien Cazaux,
Envoyé depuis mon mobile.

**Comment by PaulFl** [comment]
I'm very interested in doing this, did you figure out how to do it?
Otherwise, where can I find the raspi-gpio plugin?
Thanks
Paul F.

**Comment by IMNotMax** [comment]
You can also use the homebridge-ssh to control scripts controlling your GPIO.
I'm working on controlling an arduino through my network using scripts, without any programming knowledge... I'm going to have fun :)

**Comment by PaulFl** [comment]
Thanks you!
 I did not know about this plugin but it looks perfect for what I want to do
