### ISSUE TITLE
getting HTTP Accessory to work with Particle

### ISSUE THREAD

**Issue by EMCSizl** [nfarina/homebridge#409]
looking for any pointers on how I can use the generic HTTP Accessory to POST API calls to  particle 

I can do this from the command line with the following
 curl -X POST https://api.particle.io/v1/devices/deviceID/power?access_token=TOKEN -d  "value=on"

and this works, but I cannot get it working from homebridge.  my  config.json looks like the below. I have tried a couple of different combinations.  Even tried modifying index.js based on what was done in ParticleAccessory.js.

any help appreciated

```
        "accessory": "Http",
        "name": "Coffee Machine",
        "on_url":  "https://api.particle.io/v1/devices/<deviceID>/power?access_token=<TOKEN?",
        "on_body": "{\"value=on\"}",
        "sendimmediately": "",
        "username": "",
        "password": "",
        "http_method": "POST"
```

**Comment by rudders** [comment]
Have you looked in the log to see what response you get - the homekit-http should log the response from the server for you - on success and failure!

**Comment by EMCSizl** [comment]
Yes I did try that.. I ran Homebridge from the command line and looked at the output.  I could see a return code coming back from my Particle indicating  my argument was not being passed correctly.  For reasons I cannot work out, the simple string of "on" was not being parsed in the particle...  since I am new at this, It surely has to be user error...

anyway I recoded my particle to simplify the  functions, so all that is required is for  homebridge to call the function, and that all works correctly.

I would really love to know how to get arguments across correctly if you have anytips

thanks

**Comment by temeyers** [comment]
was there any update to this ? 

okay so here is the commands i need to commit on or off using curl for my living room lamp however i changed my access token so it wont work for everyone to see i changed one digit to break it

however in config.json there is a on_body and an off_body and thats where i am stuck as you can see ... the homebridge fires up and siri works also my appletv saw the homebridge and made it available on and off of wifi which is great news in itself... can you help me out with the on_body and off_body please ! i have tried everything i can think off for 2 days !

This is the curl command i use turn on my lamp: ​
curl https://api.particle.io/v1/devices/53ff6d066667574813461267/digitalwrite?access_token=7458609c672644bb8d29780fbe60a71f3ce26293 -d params=D2,HIGH

this is the curl command i use to turn off my lamp
curl https://api.particle.io/v1/devices/53ff6d066667574813461267/digitalwrite?access_token=7458609c672644bb8d29780fbe60a71f3ce26293 -d params=D2,LOW

this is just part of the accessories section of my config.json aparently part of the copy and paste has been cut off however my URL part i think is correct 

accessories": [
{
"accessory": "Http",
"name": "Kitchen Lamp",
"on_url": "https://api.particle.io/v1/devices/53ff6$
"on_body": "{\"D2, HIGH\"}",
"off_url": "https://api.particle.io/v1/devices/53ff$
"off_body": "{\"D2, LOW\"}",
"brightness_url": "https://192.168.1.22:3030/device$
"username": "",
"password": "",
"sendimmediately": "",

**Comment by EMCSizl** [comment]
Hey there , I worked out how to call the particle functions.  I could even see the return code coming back from my photon.  For reasons I have not yet worked out, the string I was passing never matched any of the tests in my code, and I would fall out the bottom of the function with no action. So I simply split my functions in 2.  on() and of(). All I have to do is hit the function and it will trigger.  

my config file looks like this
"accessories": [
        {
            "accessory": "Http",
            "name": "Power",
            "on_url":  "https://api.particle.io/v1/devices/<DeviceID1234>/On?access_token=<AccessToken1234>",
            "on_body": "{arg=on}",
            "on_url":  "https://api.particle.io/v1/devices/<DeviceID1234>/Off?access_token=<AccessToken1234>",
            "off_body": "{arg=off}",
            "sendimmediately": "",
            "username": "",
            "password": "",
            "http_method": "POST "

I tried many combinations but nothing would work.  have not had time to chase this up.  At the moment my particle functions ignore any arguments, so it does not matter what you put there.

particle.function() expects a strings as input and always returns an integer... so this make is hard to figure out what is going on for a newbie like me... anyway when I get more time.

**Comment by EMCSizl** [comment]
BTW, once working, the integration of HomeBridge and Homekit/Siri is pretty cool... 

thanks to the guys who put in so much effort to keep this rolling...

**Comment by temeyers** [comment]
you sir are on to something here ... however can you post your particle code so i can try and copy you from start to finish

**Comment by EMCSizl** [comment]
Hey the last post didn't come through properly.. so here is the config.json entry I am using for Homebridge-Http.

"accessories": [
        {
            "accessory": "Http",
            "name": "Coffee Machine",
            "on_url":  "https://api.particle.io/v1/devices/12345/powerOn?access_token=12345",
            "on_body": "{arg=on}",
            "off_url": "https://api.particle.io/v1/devices/12345/powerOff?access_token=12345",
            "off_body": "{arg=off}",
            "sendimmediately": "",
            "username": "",
            "password": "",
            "http_method": "POST 


all you need is a couple of very simple particle functions that set your pins accordingly... ignoring any arguments until someone (maybe me) can figure out why the  arguments are not passed correctly.




/ -----------------------------------
// Controlling my coffee machine over the internet via a remote control power socket
// -----------------------------------

// I have two optocouplers connected to A5 and A0. 
// A5 creates the circuit in the remote to switch on the power.
// AO creates the circuit in the remote to switch off the power.

int ledOn = A5;
int ledOff = A0;


// register our Spark function and initialise

void setup()
{

   pinMode(ledOn, OUTPUT);
   pinMode(ledOff, OUTPUT);

   // declare a Particle.function so that we can turn the power on and off from the cloud.
   Particle.function("powerOn",PowerOn);
   Particle.function("powerOff",PowerOff);

 
   // For good measure, let's also make sure both LEDs are off when we start:
   digitalWrite(ledOn, LOW);
   digitalWrite(ledOff, LOW);


}


void loop()
{

}



int PowerOn(String command) {
 

   
        digitalWrite(ledOn,HIGH);
        delay(500);
        digitalWrite(ledOn,LOW);
        return 1;
    
}


int PowerOff(String command) {


        digitalWrite(ledOff,HIGH);
        delay(500);
        digitalWrite(ledOff,LOW);
        return 0;
    
}
