### ISSUE TITLE
[Brainstorm] Platform discovery and installation

### ISSUE THREAD

**Issue by madmod** [nfarina/homebridge#41]
Certain platforms like Philips Hue require a non-trivial setup process to require secret keys. (See #40)  To simplify this process we might consider a secondary persistent store for platforms and accessories or a interface to save changes to it's entry in the config.json. (Not great but nice to have a central place for all config that the user can read.)  Alternatively giving each accessory and platform it's own sub folder (possibly as a separate node module like yeoman and node-red) would allow them to store persistent caches independently of other modules and have the side benefit of reducing core dependencies. Having separate node modules would also make contributing to the project easier because we could avoid merge conflicts with package.json, but add effort required to discover new modules.  Separate repos would fragment this small project too much and increase complexity managing conflicts with Siri's keywords.  I propose that we create a separate repo for "bridges" that are npm modules with a common prefix.  That way you could run `npm i homebridge-philips-hue` or whatever and we would still have a central place to manage issues.  It would also remove the issue of conflicts in package.json.  An example of a project using this pattern is tomahawk.

**Comment by nfarina** [comment]
The first thing I'd like to figure out is how to support accessories without having to "bundle" them with HomeBridge - especially requiring users to `npm install` a lot of accessory-specific deps that they will likely not need.

I like the idea of separate npm modules for each accessory/platform, especially if others could make their own npm modules in their own repos without having to PR into HomeBridge every time. We could allow for "discovering" modules by simply searching npm for anything starting with `homebridge-`. If their search allows us to be that specific?

**Comment by nfarina** [comment]
Also I'd like to avoid having to create some common core module that all accessory modules must include. Right now accessories have to include at least `types.js` to build the giant JSON services structure. It would be nice to allow devs to just create simple JS classes that are expected to implement certain endpoints.

**Comment by madmod** [comment]
Yeah a higher level API would be a nice addition to the project. 

Gulp [has a module](https://github.com/gulpjs/plugins) for finding plugins that we could fork as the basis for a github.io site once we get to that point. I'm looking into how we can load any modules in the node_modules directory that have a `homebridge` tag in the package.json. That way `npm i` would be all that is needed to add plugins. We might also want to consider a web interface for configuration. That could open up a lot of potential functionality and make the project more accessible.

**Comment by madmod** [comment]
We could even use the [npmi package](https://github.com/maxleiko/npmi) to allow one click installation of new modules from a web interface. If we did chose to make a web interface I think that we should limit it's scope to simplifying configuration only. Home automation UI can be an endless project and there are already good solutions to that problem, including HomeKit (soon).

**Comment by nfarina** [comment]
Yes totally agreed about the web UI and scope of such. I've been thinking about a simple one-page UI with "cards" for the modules you've installed, and badges for "Update available".

We might want to deliver HAP-NodeJS itself as a module of sorts - instead of requiring folks to deal with submodules and an extra npm install. And we could deliver the initial HomeBridge state as a simple download with node_modules pre-packaged - so that all you need to do is download and run the server, then access the web UI.

**Comment by madmod** [comment]
If we could make this a module also we could have a separate project that bundles it in a [nw.js](https://github.com/nwjs/nw.js) or [electron](https://github.com/atom/electron) executable. Having this project be more approachable for non developers will put more pressure on Apple and manufacturers to build more HomeKit devices. Anything controlled with Siri makes headlines. :laughing:

I have been reading some of the yeoman source code and [this](https://github.com/yeoman/environment/blob/master/lib/resolver.js) looks similar to what we would need for loading `homebridge-` modules. There is also a great example of searching for and installing plugin modules programmatically in the [yo package here](https://github.com/yeoman/yo/blob/master/lib/routes/install.js).

**Comment by nfarina** [comment]
I think `npmi` looks very promising as a programmatic interface to installing HomeBridge "plugins." Although `npm` makes a bunch of noise about how it's not supposed to be used programmatically, only through the cli, it's probably not a big deal.

Ultimately bundling it in an "application package" might be the most user-friendly option as you say. But we could get something pretty nice by just having users "npm install -g homebridge" and going from there.

I would love to have plugins installed in the user's homedir somewhere, similar to Atom - maybe `~/.homebridge/plugins`. But it looks like npm is dead-set on _always_ installing to a folder named `node_modules`, so it might have to be `~/.homebridge/plugins/node_modules` which is not ideal but maybe workable for now.

**Comment by snowdd1** [comment]
> Although npm makes a bunch of noise about how it's not supposed to be used programmatically, only through the cli, it's probably not a big deal.

Did you notice they have the API published at https://docs.npmjs.com/api/npm ?
Which are the functions npmi is using.

**Comment by snowdd1** [comment]
I have roughly coded a first attempt. If you're interested have a look at my branch `dynamic-platform` and the repo `homebridge-knx` which is a packaged platform shim (basically the same as you merged it).
It is still failing to run because of two installed instances of HAP-NodeJS, and consecutive failure to match the classes.

**Comment by snowdd1** [comment]
So, about an hour later I debugged it to a running state.
It does not support single accessories any more, only platforms NPM packages.

**Comment by nfarina** [comment]
You might take a look at the in-progress [provider API](https://github.com/nfarina/homebridge/tree/provider-api) branch - it has a working implementation of loading "Plugins" (a.k.a. shims) from separately-installed npm modules. The trick to avoid multiple HAP-NodeJS instances is to use `peerDependencies`. And the main homebridge app has some code for dynamic discovery of compatible installed npm modules.

**Comment by snowdd1** [comment]
> And the main homebridge app has some code for dynamic discovery of compatible installed npm modules

Nick, can you give me a hint :copyright: ?

But if you can spare the time have a look at https://github.com/snowdd1/homebridge/blob/dynamic-platform/app.js#L98 (loadPlatforms()) if we're talking of different topics.

**Comment by snowdd1** [comment]
> The trick to avoid multiple HAP-NodeJS instances

And by the way, as homebridge-knx module is supposed to run only within an installed homebridge it can rely on the existence of HAP-NodeJS in a defined way, I simply didn't mention the dependency but did a 
````javascript
var Service = require("../../HAP-NodeJS").Service;
var Characteristic = require("../../HAP-NodeJS").Characteristic;
````
in https://github.com/snowdd1/homebridge-knx/blob/master/lib/knxdevice.js#L6 and following. And it does work fine, just needs some seconds longer to load, as it tries to load the 'latest' version, so it has to do a lookup at npm registry.

If you think my ideas are completely off, please say so!
I'd like to support the development, but you can assign the topics; we do not need to invent the wheels multiple times.

**Comment by snowdd1** [comment]
@nfarina : I tried with `peerDependencies` but failed with *hap-nodejs* as it has no npm registry. I need to refer to the *HomeKitTypes.js* in the accessories creation process. npmi installs my shim, but fails with the postprocessing of hap-nodejs, because it cannot check if it is already installed.
However, it runs fine the second start attempt, when it doesn't have to install *homebridge-knx* any more. In your [example](https://github.com/nfarina/homebridge/blob/provider-api/example-plugins/homebridge-lockitron/package.json) I even did not see a reference to *hap-nodejs*.

I still didn't the automatic installer in the *provider-api* branch.
Maybe I got you wrong - don't you want to install the modules dynamically? Do you want the user to use npm himself and only discover the installed modules? So many questions!
