### ISSUE TITLE
Read States API

### ISSUE THREAD

**Issue by bp529** [nfarina/homebridge#411]
Where is the Homebridge API documented? I've been trying to dissect built plugins to determine what functions or callbacks are needed to request read states from a device, i.e. brightness level, on/off. The author of the HTTP shim was exploring adding this to the plugin, but decided it was better off to write your own plugin, which I agree with. However, I can't find any documentation on requesting and updating read states. I have control over the URL which can be called and the data that is returned by the URL call. Thank you!

**Comment by nfarina** [comment]
For the underlying "HomeKit" API, see: https://github.com/KhaosT/HAP-NodeJS#api

**Comment by bp529** [comment]
Thank you this helped a lot. I am able to read boolean states for switches. I am running into trouble with how to call a 'getBrightness' function and write that to the characteristic. 

The following is my function:

getBrightness: function(callback) {
		var url = this.brightness_lvl

		
		this.log("Getting Brightness");
		this.httpRequest(url, "", this.http_brightness_method, this.username, this.password, this.sendimmediately, function(error, response, body) {
			if (error) {
				this.log('Getting brightness failed!', error);
				callback(error);
			} else {
				var level =  parseInt(body, 10);
				this.log('HTTP get Brightness succeeded! The Current Level is: '+level);
				
				callback(null, level);
			}
		}.bind(this));
	}


For the Services:

lightbulbService
	.addCharacteristic(new Characteristic.Brightness())
		.on('set', this.setBrightness.bind(this))
                .value = this.getBrightness.bind(this);


If I manually set a value it will populate ( .value = 55)

**Comment by mklips0** [comment]
@bp529 Try this instead: 

```
lightbulbService
.addCharacteristic(new Characteristic.Brightness())
.on('set', this.setBrightness.bind(this))
.on('get', this.getBrightness.bind(this));
```
