### ISSUE TITLE
 Error 'null' logging in: {"ReturnCode":"217"...

### ISSUE THREAD

**Issue by jojo3632** [nfarina/homebridge#414]
Hi,

I'm trying to get homebridge running to control my liftmaster garage door.
I was able to install homebridge. I'm able to launch homebridge, I can add the devide to the Insteon I downloaded. When I run homebridge, here is what I see:

*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
Loaded plugin: homebridge-liftmaster
Registering accessory 'homebridge-liftmaster.LiftMaster'
---
Loaded config.json with 1 accessories and 0 platforms.
---
Loading 1 accessories...
[Garage Door] Initializing LiftMaster accessory...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:

    ┌────────────┐
    │ 031-45-154 │
    └────────────┘

Homebridge is running on port 51826.
[Garage Door] Error 'null' logging in: {"ReturnCode":"217","ErrorMessage":"Error processing request (217)","CorrelationId":"e1c904f0-a8ae-4ec2-92e9-5424245db3c2"}

But as soon  as I try to operate the door via the app or Siri, I get this error:

[Garage Door] Error 'null' logging in: {"ReturnCode":"217","ErrorMessage":"Error processing request (217)","CorrelationId":"e1c904f0-a8ae-4ec2-92e9-5424245db3c2"}

Can you help?
Jojojo3632

**Comment by nfarina** [comment]
Please reopen this issue in https://github.com/nfarina/homebridge-liftmaster

**Comment by jojo3632** [comment]
Hi Nick,

Done. 

J.
