### ISSUE TITLE
There was a problem reading your config.json file

### ISSUE THREAD

**Issue by rockthemike** [nfarina/homebridge#415]
Hey all!

I've been working to get this set up and I realize I'm in a bit over my head. When I run homebridge in terminal on my Mac I get the below error. It sees my plug ins but can't read my config file. I pasted the contents into the website it recommends which tells me the json is valid . Any guidance would be great and Im sorry if this is in the wrong place!

config.json:

{

    "bridge": {

        "name": "Homebridge",

        "username": "CC:22:3D:E3:CE:30",

        "port": 51826,

        "pin": "031-45-154"

    },

"platforms": [
	{
		"platform": "Nest",
		"name": "Nest",
		"username" : "xxxxx@xx.com",
		"password" : "xxxxx"
	}
],

"accessories": [
    {
        "accessory": "WeMo",
        "name": "Tree",
        "description": "This shim supports Belkin WeMo devices on the same network as this server. You can create duplicate entries for this device and change the 'name' attribute to reflect what device is plugged into the WeMo, for instance 'Air Conditioner' or 'Coffee Maker'. This name will be used by Siri. Make sure to update the 'wemo_name' attribute with the EXACT name of the device in the WeMo app itself. This can be the same value as 'name' but it doesn't have to be.",
        "wemo_name": "Tree"
    }
]
}

terminal error: 
Loaded plugin: homebridge-indigo
Registering platform 'homebridge-indigo.Indigo'
---
Loaded plugin: homebridge-nest
Registering platform 'homebridge-nest.Nest'
---
Loaded plugin: homebridge-wemo
Registering accessory 'homebridge-wemo.WeMo'
---
There was a problem reading your config.json file.
Please try pasting your config.json file here to validate it: http://jsonlint.com

/opt/local/lib/node_modules/homebridge/lib/server.js:124
    throw err;
    ^

SyntaxError: Unexpected token \
    at Object.parse (native)
    at Server._loadConfig (/opt/local/lib/node_modules/homebridge/lib/server.js:118:19)
    at new Server (/opt/local/lib/node_modules/homebridge/lib/server.js:25:23)
    at module.exports (/opt/local/lib/node_modules/homebridge/lib/cli.js:23:3)
    at Object.<anonymous> (/opt/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)

**Comment by nfarina** [comment]
That is strange - I'm able to load the config.json as you pasted it just fine. Are you on Windows?

**Comment by rockthemike** [comment]
Hi Nick!

I'm on Mac. I think I followed all the steps including installing Xcode and command line tools. The only thing I ran into was during the installation of homebridge it placed the items into a deep directory instead of /homebridge because root didn't have access to create. Other than placing the files there, the installation seemed fine. 

Michael Barnett

**Comment by crespino-com** [comment]
I had a similar issue. Are you using a certain text editor to modify the file? I ran into this when I was trying to copy and paste from the text editor on my Raspberry Pi. If I manually created the config.json file with nano it worked fine. I think that some copy and paste can insert hidden characters that are messing with the parser. That is all I could think would be causing the problem.

**Comment by rockthemike** [comment]
I'm using TextEdit on the Mac and everything in that file was a copy and paste and then some minor edits.  I'll report back after trying again. Thanks for the advice so far.

**Comment by nfarina** [comment]
I would be very suspicious of TextEdit. Try using a "pure text" editor like atom.io to create a brand new file.

**Comment by KraigM** [comment]
With TextEdit you have to choose the option "Make Plain Text".  

Personally I'm a fan of [Sublime Text](https://www.sublimetext.com) myself

**Comment by rockthemike** [comment]
You guys are awesome! Terminal is now running home bridge successfully. It's been up and running for about 10 minutes but none of the iOS apps seem to find home bridge. How long does it normally take for the iPhone to see home bridge once its set up?

**Comment by rockthemike** [comment]
Quitting terminal and relaunching it seemed to fix it. Thank you all so much for your help

**Comment by nfarina** [comment]
Awesome, glad you got it working!

**Comment by bhushangahire** [comment]
`{
	"platforms": [{
		
	}]
}`

It needs to be included in {}
