### ISSUE TITLE
Install fails on osx 10.11.2 El Capitan

### ISSUE THREAD

**Issue by pacific707** [nfarina/homebridge#416]
/usr/local/bin/homebridge -> /usr/local/lib/node_modules/homebridge/bin/homebridge

> mdns@2.2.10 install /usr/local/lib/node_modules/homebridge/node_modules/mdns
> node-gyp rebuild

/usr/local/lib/node_modules/npm/bin/node-gyp-bin/node-gyp: line 3: node: command not found
/usr/local/lib
└── (empty)

npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "homebridge"
npm ERR! node v4.2.3
npm ERR! npm  v3.5.1
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! mdns@2.2.10 install: `node-gyp rebuild`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the mdns@2.2.10 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mdns package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mdns
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mdns
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/admin/Desktop/npm-debug.log
npm ERR! code 1

any help would be great

**Comment by oehokie** [comment]
@pacific707 did you ever solve this?  I'm running into the same issue trying to install in a docker container

**Comment by AppleTechy** [comment]
issue #456
