### ISSUE TITLE
Paradox Alarms bridge?

### ISSUE THREAD

**Issue by jroux1** [nfarina/homebridge#418]
Hi, does anybody know if a bridge from Paradox alarms http://www.paradox.com will be attempted? It has an IP Module IP150 that talks to the alarm systems, the model MG5000 and MG5050, from which such a bridge to homebrige could be built?

**Comment by Tertiush** [comment]
Hi, not sure if this will help:

https://github.com/Tertiush/ParadoxIP150

**Comment by jroux1** [comment]
Great! Installed it last night, was able to get MQTT messages from the IP150 - alarm events. Thank you Teriush ! Looking forward to how this project will progress.

**Comment by MnrGreg** [comment]
Hi @jroux1, check out https://github.com/mnrgreg/homebridge-paradox-security-system

This Homebridge plugin will monitor the ParadoxIP150v2 status from the mqtt queue and convert it to Homebridge/HomeKit signals.

Let me know how it goes for you.
