### ISSUE TITLE
Node JS Version - Homebridge and Pimatic

### ISSUE THREAD

**Issue by benbeton** [nfarina/homebridge#419]
Hi,

I'm running Homebridge on my Pi (with  Node JS 4.0) 
Additional I wan't to use pimatic on the same device, pimatic  (needs  NodeJS 0.10.24) https://github.com/pimatic/pimatic

Would it be possible to run Homebridge and Pimatic with the same Node JS version? If yes which version of Node JS ?

I tried to run Homebridge with 0.10.24, it does not work, and pimatic will not run with Node JS 4.0 :(
 
Would be possible to run 2 NodeJS versions on the same machine, with a "path to" for each off the apps ?!

I'm not that experienced using Node JS, would be great if someone can help

regards

**Comment by snizzleorg** [comment]
i had success using the dockerized version: 

https://github.com/patrickbusch/homebridge-docker

i got docker running with this:

https://github.com/umiddelb/armhf/wiki/Get-Docker-up-and-running-on-the-RaspberryPi-(ARMv6)-in-four-steps-(Wheezy)

**Comment by benbeton** [comment]
thanks, sounds like a good plan, did you updated to jessy?

**Comment by snizzleorg** [comment]
I already was running jessie....

**Comment by benbeton** [comment]
ok, I set up a new jessy installation, docker is installed, how to install homebridge? 

git clone repo 
.> run homebridge-pi.sh build? 

is it that easy?

**Comment by snizzleorg** [comment]
yes. thats what I did. You have to change the docker file to include your plugins (and maybe remove the harmony hub plugin) 

I also had to do the following:

```
sudo sysctl net.ipv4.conf.docker0.forwarding=1
sudo systemctl restart docker.service
```

before running ```home bridge-pi.sh build```otherwise the images would not have network. Not sure if this has to be done everytime the system boots or not. (Probably the best would be to start with the hyperion image instead of raspbian http://blog.hypriot.com/downloads/)

**Comment by snizzleorg** [comment]
@benbeton Did you have to do this:

```
sudo sysctl net.ipv4.conf.docker0.forwarding=1
sudo systemctl restart docker.service
```

or did it work w/o?

**Comment by benbeton** [comment]
not needed while creating the container
