### ISSUE TITLE
Philips Hue rate limiting

### ISSUE THREAD

**Issue by madmod** [nfarina/homebridge#42]
The Philips Hue bridge only allows a certain number of requests each second. When I change a scene it is sending an API call for each characteristic of each bulb. A possible solution to this might be to group characteristic changes for each bulb into a single call. I'm trying to figure out a good way to cache characteristic changes by bulb for a few ms before sending them to the bridge. I am working on a PR but don't have a lot of time today so it may have to wait until tomorrow.

**Comment by alistairg** [comment]
I can't wait for this PR! :)

Are you also considering supporting Hue Groups?

**Comment by madmod** [comment]
I will try to get around to this today or tomorrow. 

I'm not sure what would be required to represent Hue groups in HomeKit. I think the easiest solution would be to manually create zones in the insteon+ app. If there is some way push zones to HomeKit I will look into adding it.

It would also be great if Hue scenes could be synced to HomeKit scenes somehow. I think this would require some more structure around the setup process to allow for merging scenes from platforms to existing HomeKit scenes.

**Comment by alistairg** [comment]
I think the challenge is that Hue sees scenes / groups as “devices” as far as HomeKit is concerned. HomeKit’s scenes / zones are just logical groupings of accessories, services, and characteristics. 

We’d likely need to create a “group device” for each of up to 16 groups in Hue and map them back to HomeKit...

**Comment by madmod** [comment]
I think you're right that we would need to create a "group device" right now. I'm not sure that is something we should do because it isn't the HomeKit way of doing things. A better solution to that problem might be an iOS app to import groups/scenes into HomeKit from homebridge platforms through some kind of API.

**Comment by Tom2Drake** [comment]
Is there any way to create a workaround that implement a delay between the command communication the the hue bridge? This may will "solve" the issue. When i try to turn off all my 14 Hue devices at once with siri, 3 of them didn't change the state.

**Comment by nfarina** [comment]
Does the hue API allow for a single "batch" of changes at once? I can think of two solutions to this problem:

  1. New HAP-NodeJS API for handling "batch set" of characteristic changes
  2. New helper function to wait until next runloop and accumulate changes ourself

**Comment by Tom2Drake** [comment]
Well, regarding the API i just found olny the follwing:

"How many commands you can send per second?

You can send commands to the lights too fast. If you stay roughly around 10 commands per second to the /lights resource as maximum you should be fine. For /groups commands you should keep to a maximum of 1 per second."

**Comment by Tom2Drake** [comment]
The new workaround works great, expect one thing. All lights turn off or on successfully but Siri gives a negative feedback very often. Like: "This time i was note able to reach your lights. But in fact, all lights reacting.
