### ISSUE TITLE
How can I promote a stable run of Homebridge?

### ISSUE THREAD

**Issue by Joey-1970** [nfarina/homebridge#420]
Hello!

Homebridge is a very fantastic programm and many thanks for sharing!

I install it on a Raspberry Pi (1), and sometimes it runs very stable - but only for a few hours...

The Homebridge-Server runs, but not connections possible, deleting Homekit-Settings on the iPhone and the persists-file in the directory sometimes help to start up again. (...and do all settings in insteon+ again..)

Sometimes it works only in WLAN, sometimes even with the Apple TV-Box. For me it is not recognizable where is the mistake in the system.

Can someone explain me, maybe what I should avoid? What can I do, to have a stable run?

Joey

**Comment by sh-run** [comment]
Hello Homebridge Community. 

I also run Homebrige on a RPI (v2) and have the same problem. When i delete the HomeKit config and change the Bridge Name and username than it works. After a view Hours it Stopps  working. I think i have tried this about 20 Times. I also installed it on OS X for testing and Same failure. 

When i Scan the bonjour i See the raspi with HAP. 

I think the failure occures when i  leave my wifi and when i come back it is Borken. 

Maybe somebody hast an idea,becouse i Love Homebridge and Sant to use it

Regards Stefan

**Comment by jw59** [comment]
I'm running on an RPi 2 with the OpenHAB and Liftmaster plugins and have no issues with it crashing or losing connections.   May want to try removing plugins one at a time and see if its a particular plugin that's causing your issue?

**Comment by Joey-1970** [comment]
Hello Community,

I now try to run Homebridge on a Raspberry Pi and on Windows, with only one lightBulb and temperature to test - but after a viewe hours I must restart server, delete configure in iOS, sometimes restart iPhone and start allover again.
I have no idea, where is the problem. Sometimes I have nothing change on configuration, I came back home, it works and only a view minutes laters it will not work...

Joachim

**Comment by sh-run** [comment]
I only use the Fibaro HC2 Plugin. I can reproduce the failure, when i disconnect my iPhone 6s from Wifi and connect it back, it lose the connection. I use the Elgato Eve app. 

Which type of phone and app do you use Joey-1970?

**Comment by Joey-1970** [comment]
iPhone 6s and my son a iPhone 6....

I try different App (Eve, Insteon+, MyTouchHome), but it works only for a few hours, sometimes with a connection over AppleTV, sometimes not, sometimes after reconnect Wifi, but mostly not...

Joachim

**Comment by sh-run** [comment]
Which plugins do you use?

**Comment by Joey-1970** [comment]
...only homebridge-symcon...

Joachim

**Comment by Batoon69** [comment]
Hi guys, same issue for me. I use homebridge+plugin fibaro HC2 on a mac mini. On my iphone 6s, I use the app Eve. Everything works great but after some hours, homekit lose the connection with homebridge. The server homebridge still seems to work but is not "joinable" anymore. In this situation, the only way is to delete homekit database, to delete the files in the "persist" folder and to re-pair everything. Of course I need to re-define all my rooms and scenes! I'm looking forward to reading some clues about this issue.  Happy christmas.

**Comment by gomba777** [comment]
Same problem for me. I run homebridge on RPI2 with the HC2 plugin. It works for +-1 hour or several siri calls and the it loosed connection between iphone 6s (using EVE) and homebridge. Only way to restore is deleting the files in persist, restarting homebridge and removing homebridge from homekit and start again. 
I get the following warning:
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>

Or different kind of errors:
Error: listen EADDRINUSE 0.0.0.0:51826
or
Error: dns service error: name conflict
or
Error: dns service error: unknown

for the rest, when it works, it works really well : :+1: 
thank you for making this possible!

**Comment by aebgit** [comment]
Hi all,

merry christmas to all of you and many thanks to nfarina for that great project!

I had similar problems on my raspberry. 
After disabling power-save for the WiFi-adapter homebridge runs absolutely stable.

I currently cannot check my personal configuration, but here is described what do do: https://www.raspberrypi.org/forums/viewtopic.php?t=51543&p=397663

> It is possible to set the 8192cu power management parameter to off by generating the 8192cu.conf file with command sudo nano /etc/modprobe.d/8192cu.conf and adding the lines
> # Disable power management
> options 8192cu rtw_power_mgnt=0

Viele Grüße,
Andreas

**Comment by gomba777** [comment]
Hi Aebgit,
Thank you for you suggestion but I am using it on wired network. No wifi. 
Best,

**Comment by Batoon69** [comment]
No wifi for me neither. But thank you for the tip Aebgit.

**Comment by Batoon69** [comment]
Hi  Gomba777. Sounds like we have the same issue. Any idea?

**Comment by Joey-1970** [comment]
...your are not alone! ;-)
I have installed the homebridge on Raspberry Pi and on Windows - same problems on both systems.
(both on wired network).
There are more people with this problems in germen communities:
http://forum.fhem.de/index.php?topic=32652.0;nowap
https://www.symcon.de/forum/threads/27949-Apple-HomeKit-Anbindung-an-IPS-auf-Basis-der-HomeBridge-von-nfarina

Joachim

**Comment by Batoon69** [comment]
Unfortunately, I do not read german. Have they found the root cause or any solution?

**Comment by Joey-1970** [comment]
No, unfortunately not...

If they did it, I would post it here..;-)

But I hope, I get hier some information to promote the stable run. The power management is one of them, unfortunately I didn't use wifi...

**Comment by ericbenjaminjr** [comment]
+1 on this issues

**Comment by igorpanjan** [comment]
Works like a charm for couple of minutes or sometimes hours. I am using RPi 2, Model B, wired connection, homebridge-http module.

**Comment by ilcato** [comment]
@igorpanjan, Wheezy or Jessie ?

**Comment by igorpanjan** [comment]
Wheezy

**Comment by ilcato** [comment]
I'm on Jessie without this kind of problem. Also which version of node.js?

**Comment by sh-run** [comment]
I´m on jessie too and have the problem. i tried both and the problem occours. 

pi@raspi:~ $ node -v
v4.0.0

Regards Stegan

**Comment by Joey-1970** [comment]
...I'm on Jessie to - but with this problems...:-(

Joachim

**Comment by igorpanjan** [comment]
@ilcato Node is v4.2.4. 

@all Is there anyone else with same experience as ilcato? I do not want to commit to upgrading until I'm shore :)

**Comment by ilcato** [comment]
I'm on node 4.2.2 and Jessie. Works for days (I upgrade frequently the plugins so I often need to reboot) without problem. Run with forever.

**Comment by Joey-1970** [comment]
...jessie with node.js-version 4.2.1...

How can I update to this 4.2.2 version?

Joachim

**Comment by ilcato** [comment]
I normally do on PI2 (there are more recent version of node):
wget https://nodejs.org/dist/v4.2.2/node-v4.2.2-linux-armv7l.tar.gz 
tar -xvf node-v4.2.2-linux-armv7l.tar.gz 
cd node-v4.2.2-linux-armv7l

**Comment by Joey-1970** [comment]
Hello ilcato,

thank you for this, but what must I do next?

Joachim

**Comment by ilcato** [comment]
Execute the commands on the PI shell

**Comment by Joey-1970** [comment]
...I execute the three commands you posted, but what I must I do next after the last command "cd node-v4.2.2-linux-armv7l"?
Soemthing like "install"?

Joachim

**Comment by ilcato** [comment]
just updated the message. last step was missing

**Comment by Joey-1970** [comment]
...so my Homebridge don't start after update...

Must I change something else?

Joachim

**Comment by ilcato** [comment]
Did you stopped homebridge before sudo cp -R * /usr/local/ ?

**Comment by Joey-1970** [comment]
Yes, now the answer is always "segmentation fault" ("Speicherzugriffsfehler" in german). I think something wents wrong...

Joachim

**Comment by ilcato** [comment]
If you execute node -v it shows the right number?

**Comment by Joey-1970** [comment]
..the answer ist "segmentation fault"...

**Comment by ilcato** [comment]
which version of raspberry do you have?

**Comment by Joey-1970** [comment]
...a Raspberry Pi B, but I fear the SD-Card is damaged... :-(

**Comment by ilcato** [comment]
No, the instruction were for a PI 2. This is the equivalent for a Model A, B, B+:

wget https://nodejs.org/dist/v4.2.2/node-v4.2.2-linux-armv6l.tar.gz 
tar -xvf node-v4.2.2-linux-armv6l.tar.gz 
cd node-v4.2.2-linux-armv6l
sudo cp -R * /usr/local/

**Comment by Joey-1970** [comment]
Super!!!

v4.2.2 - and Homebridge run again - hope it will be a stable run! ;-))

Many thanks!

Joachim

**Comment by igorpanjan** [comment]
I have just tested the homebridge on Jessie and node v4.2.4 and the problems are the same as before. 

It is interesting, that if I leave the mobile apps like Eve or Insteon+ running (just tapping on the screen so that the phone doesn't lock the screen) everything works fine for a long time. When I stop using the mobile app and lock the phone for couple of minutes and then get back to the app, the connection to homebridge server crashes. 

I have one another culprit here, that is bugging me. My RPi has a wired connection to my secondary router that works like wireless bridge to my primary router (I didn't want to lay to many cables at home) and maybe that is also one variable in this issue.

**Comment by jw59** [comment]
Is everyone with these troubles running the latest iOS on ALL their devices?  I had a bunch general HomeKit issues that appeared like Homebridge was acting up.  However once I updated all my iDevices updated to 9.2 and reset both HomeKit and HomeBridge, everything has been super stable.

**Comment by ilcato** [comment]
jw59 is right, I experience some problems after updating to some iOS beta a specific device I used for testing purposes and not he others. Other users also had problem with Apple TV connecting to the same iCloud account. @igorpanjan do you have an Apple TV?

**Comment by Joey-1970** [comment]
...I have iOS 9.2 on the devices...

After updating yesterday to node 4.2.2 there is again "Unable to access device" in this morning. Restart of the homebridge doesn't work...

Joachim

**Comment by igorpanjan** [comment]
@ilcato No I don't, I am using iPhone 6, iOS 9.2.

But I think I solved my issue. I've plugged RPi into my primary router and everything works stable now. If I start a mobile app after some time, it immediately connects to RPi homebridge server.

**Comment by nizaga** [comment]
Hi, i have the same issue. I run homebridge on RPI2. It works sometimes and then I lose connection between iphone 6s (using EVE) and homebridge. And the way to restore is deleting the files in persist, restarting homebridge and removing homebridge from homekit and start again (and sometime does not even work). I have tried to update to 4.2.2 but it does not work...

**Comment by nizaga** [comment]
Hello, i found my issue!!!

Take a look at: https://github.com/cflurin/homebridge-shims/wiki/Minimalist-Homebridge-on-a-Raspberry-Pi

FAQ 2: The Homekit app (e.g. EVE) doesn't find Homebridge Homebridge not displayed? There might be an issue with your LAN/WLAN Layout. Try a simple Layout without Switches/Repeaters. A Wifi-Dongle instead of the Ethernet cable might help.

I did try to install avahi-utlis but Homebridge  was not displayed.

So.. i installed Discovery - Bonjour Browser on my iphone and i connected the RPI via Wifi-Dongle instead of the Ethernet cable and IT WORKS!!!!

Still don't know why avahi-browse -t _http._tcp was not displaying homebridge while the browser does...

So.. i have a network issue at home (in fact, i have several PLCs, Router, switch,,,,)

Regards,

Nacho

**Comment by Batoon69** [comment]
Hi all,
Unbelievable ! I've just installed "Discovery - Bonjour Browser" on my iPhone then relaunch home bridge and it worked ! No need to delete all and re-install everything. Thanks Nizaga. Let's see now if it's stable. Just for memory, my homebridge is installed on a mac mini. For the other ones who had the same problem, does it work for you too ?

**Comment by Joey-1970** [comment]
Hello again,

there must be something else going wrong...

I now installed the Discovery - Bonjour Browser too and there you see immediately the Homebridge, but in Insteon+ or other apps the connections is "Unable to Access Device"...

I don't think that this failure is caused by the network. If the Bonjour Browser see the homebridge, why the Homekit-Apps can't do???

Joachim

**Comment by Batoon69** [comment]
Joey, have you relaunched homebridge after installation of Discovery-Bonjour ?

**Comment by Joey-1970** [comment]
Yes, stop, start, "Unable to Access Device"...:-(

**Comment by Batoon69** [comment]
Have you tried to open HAP/Homebridge on your iOS device in "Discovery-Bonjour" ? You should have something like that :
![img_1765](https://cloud.githubusercontent.com/assets/13831334/12043069/66b03ef2-ae81-11e5-88af-9f25dfe8b8c7.PNG)

**Comment by Joey-1970** [comment]
...here is nearly the same (other IP, but also c#=2, other id (but is the id from the config.json)...

**Comment by Batoon69** [comment]
Very strange. I still do not understand how installing this app, helped me to get back the connection...

**Comment by Joey-1970** [comment]
...accident? ;-)

**Comment by Batoon69** [comment]
Still working since yesterday (13 hours ago). I will check if it keeps on working if I leave home (then leaving the wifi net).

**Comment by nizaga** [comment]
hi... this is getting interesting... i cheked the Discovery-Bonjour" and i see 2 IPs from the SAME raspberry......

I installed my RPI using the 2015-11-21-raspbian-jessie image, via LAN. Then i added the wireless adapter, removed ALL references in the interfaces.

If i search for the IP i all the files get the following:

var/log/syslog:Dec 30 06:59:20 raspberrypi avahi-daemon[432]: Registering new address record for 192.168.1.148 on wlan0.IPv4.

which makes a reference to the Install Avahi (this is required by the mdns package in HAP-NodeJS library)

Someone know why the Avahi is creating a new ip adress???

Thanks!!!

Nacho

**Comment by nizaga** [comment]
interesing... further reading...Install Avahi - This is required by the mdns package in HAP-NodeJS library. The daemon is creating the second IP... i have not tried to disable the daemon, i did kill the second IP using:  ip address del 192.168.1.148 dev wlan0

Anyone knows if having 2 ips on the same raspberry might cause an issue? (i see this two ips in the discovery Bonjour app.

Any issues to disable the deamon? I might test it...

Sorry, i am not a network expert :(

Thanks again!

**Comment by Batoon69** [comment]
Still working after leaving the wifi net for one hour and coming back home. Worked also when I was outside through the apple tv4.

**Comment by rooi** [comment]
I had a similar problem while running homebridge on my mac mini, while HAP-Nodejs was much more stable. It seems to be fixed by changing homebridge's hap-nodejs dependency from v0.0.3 to the latest v0.0.7 in the package.json. Homebridge is running stable on my mac mini, but I'm not sure it will work on other devices of course.

**Comment by Joey-1970** [comment]
Hello rooi,

how did I know which version I have? And how can I possibly update this?

Joachim

**Comment by rooi** [comment]
I just forked it and changed it in the package.json file.
After that installed the forked version e.g npm install git://....

**Comment by nachtsheim** [comment]
@rooi please make a pull request for your change

**Comment by Joey-1970** [comment]
Hello nachtsheim,

how can I update from 0.0.3 to 0.0.7? Please tell me step-by-step...

Joachim

**Comment by IMNotMax** [comment]
`sudo npm update -g homebridge` I think :)

**Comment by rudders** [comment]
Homebridge still dependent on 0.0.3 so will have to wait for @nfarina to update before this approach works.

**Comment by cflurin** [comment]
Hi, I forked homebridge and changed hap-nodejs to 0.07.
You can temporarily install it this way:
```
sudo npm install -g https://github.com/cflurin/homebridge
```

@nfarina: I'll remove my fork as soon you've update homebridge.

**Comment by nfarina** [comment]
@rudders Just bumped it to 0.0.7 and republished homebridge.

**Comment by bwired-nl** [comment]
thanks! whats the best update command?

**Comment by nfarina** [comment]
Try `sudo npm update -g homebridge`

**Comment by bwired-nl** [comment]
worked! and all still working perfect on my rasp :)

**Comment by nizaga** [comment]
hi, my homebridge is running stable, however, i get sometimes the following error (below)

Is the fix in hap-nodejs to 0.07. related to this issue? I have not upgraded yet....

Thanks!

Nacho

Thu, 07 Jan 2016 00:40:40 GMT EventedHTTPServer [::ffff:127.0.0.1] New connection from client
events.js:142
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::54826
 Error: listen EADDRINUSE :::54826
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at Server._listen2 (net.js:1238:14)
    at listen (net.js:1274:10)
    at Server.listen (net.js:1370:5)
    at new EventedHTTPServerConnection (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:125:20)
    at EventedHTTPServer._onConnection (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:79:20)
    at emitOne (events.js:78:13)
    at Server.emit (events.js:170:7) 

Is the fix in hap-nodejs to 0.07. related to this issue? I have not upgraded yet....

Thanks!

Nacho

**Comment by nizaga** [comment]
just to make sure i understand what is going on.... if i run sudo npm update -g homebridge i will upgrade to hap-nodejs to 0.07?

**Comment by rudders** [comment]
Firstly I'd strongly suggest upgrading but your error looks like something already has that port locked. Like a background instance of Homebridge for instance.

**Comment by nizaga** [comment]
hi, just running the command: sudo npm update -g homebridge?

My confusion was the comment: @nfarina: I'll remove my fork as soon you've updated homebridge.

Does it mean the current homebridge will install node 0.0.7 or it is just the fork for testing purposes?

Nacho

**Comment by rudders** [comment]
latest homebridge has latest (0.0.7) HAP-Nodes. `sudo npm install -g homebridge` might be worth a try depending on your platform and config.

**Comment by cflurin** [comment]
@nizaga: The fork is removed.
Follow the regular install/update instruction:
```
sudo npm update -g homebridge
```

**Comment by Joey-1970** [comment]
...the important question:
Is it now more stable then before???

Joachim

**Comment by bwired-nl** [comment]
Im running homebridge on a rasp pi without any problems for a month now.
Alo Using http plugin, no stability problems at all. Yesterday i did the HAP-nodes upgrade and also running fine until now.

**Comment by nizaga** [comment]
ok, thanks, i will upgrade and let you know, i am quite sure i don't have a background instance of Homebridge... i have set monit to check the process and restart if it fails and i got this error last night...

Nacho

Related to my issue, Error: listen EADDRINUSE :::54826
  Error: listen EADDRINUSE :::54826
     at Object.exports._errnoException (util.js:856:11)
     at exports._exceptionWithHostPort (util.js:879:20)
     at Server._listen2 (net.js:1238:14)
     at listen (net.js:1274:10)
     at Server.listen (net.js:1370:5)
     at new EventedHTTPServerConnection
(/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:125:20)
     at EventedHTTPServer._onConnection
(/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:79:20)
     at emitOne (events.js:78:13)
     at Server.emit (events.js:170:7)
     at TCP.onconnection (net.js:1434:8)

**Comment by rudders** [comment]
try the following to see what's going on. it will give you some process id's to investigate to see who's got your port.

`lsof | grep 54826`

**Comment by nizaga** [comment]
i understand i need to run this comand just after the process fails, right? i mean i have monit to re-start the process as soon as it fails, so i should disable this otherwise i will not find out the process running the port, right? thanks!

**Comment by rudders** [comment]
Perhaps you could share what happens earlier in the log files for a clue - it looks like homebridge is trying to start up and is finding the port otherwise engaged by another app. running the command will show you what's got it at that point - are you sure monic isn't trying to rescan unnecessarily?

**Comment by mavis46** [comment]
I am on a rasp2. I have updated homebridge and downdated node to 4.2.2 but I am still having problems with my things being 'unreachable' in Eve. Homebridge appears to be running (I get the message Homebridge running on port 51826.) I have installed Discovery-Bonjour and when first installed HAP showed  but now it only shows sometimes and if it does, when I click into it it just says 'scanning'.

Like a few people on here I am a newbie (and quite proud that I have got everything set up eventually.). What would be good but not sure if this website is the best place for it would be a walkthrough with links to the latest code to get various projects up and running. I have set up Homebridge to run SmartThings with Siri but have run into various problems using out of date versions (or too new versions of node).

ps by having these problems I am learning fast! So there is some positive from it.

**Comment by gijoecool** [comment]
Yesterday I updated hap-nodejs' node-persist to the latest GitHub version and moved my raspberry pi to be hardwired to the main router. This appears to have fixed the problem where homebridge stops working after a short amount of time.

**Comment by nfarina** [comment]
@gijoecool How was your RPi connected before?

**Comment by gijoecool** [comment]
It was connected (wired) to an AirPort Extreme that extends the network of another AirPort Extreme (wireless) that's wired to my Verizon FiOS Quantum Gateway router. The Verizon router controls IP address allocation. The Raspberry Pi has a static IP.

**Comment by Joey-1970** [comment]
...since the update to 0.0.7 it runs much more stable as before!

Joachim

**Comment by mavis46** [comment]
Last night I hardwired my Pi to my router and it is still working 12 hours later. I did have a static IP address but it is now showing as another IP address.

When I say working, I mean Eve does not show as unreachable against my things and I can see HAP in Discovery. In Terminal on my Pi I can see the commands going through (with Siri and with Eve) but the Window Plug (with lamp attached) does not actually come on or go off. If I use the ST app then it does work. My Sonos (set up as a ST accessory and not a Homebridge plugin) does work with Siri and Eve. SmartThings are having problems so it may just be down to this.

Once I am sure it is working properly then I think that I will prepare and set up a new SD card to tidy up my versions of software.

**Comment by dermotos** [comment]
+1 I'm also getting this issue. Works fine, then disappears. After resetting the homekit database on my phone, homebridge will only appear if I delete the persist folder.

**Comment by cflurin** [comment]
I'm running homebridge on a Mac mini and a RPi 2. Both are running for weeks. My devices are connected via Wifi. On the RPI I also disabled the power management for the Wifi adapter, this was often the reason for HomeKit reporting "accessory unreachable". More details [here] (https://github.com/cflurin/homebridge-punt/wiki/Running-Homebridge-on-a-Raspberry-Pi)

**Comment by hummer5** [comment]
I am trying to run the homebridge on RPI-B. My issue is that i have a homebridge running to control the control4, i think at the port 51826. Is it still possible for me to run this homebridge, if yes then how to? I appreciate all the help.

**Comment by waxlabo** [comment]
I am currently having an unstable connection with Homebridge also for my Nest Thermostat.  The strange thing is I run a separate Homebridge for MyQ Garage opener and that one keeps it's connection very well.

**Comment by moosebert** [comment]
Same issue in a way I think.  Homebridge remains stable and useable for well over 12hrs+.  However, whenever the service or Pi it runs on is restarted iOS devices can no longer find it unless it's removed from the homekit database and added again.

**Comment by moosebert** [comment]
In the logs I see these from various iOS devices trying to update:
```Jul 29 19:49:19 services homebridge[344]: Sat, 30 Jul 2016 02:49:19 GMT HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify
Jul 29 19:49:19 services homebridge[344]: Sat, 30 Jul 2016 02:49:19 GMT EventedHTTPServer [::ffff:192.168.1.127] HTTP Response is finished
Jul 29 19:49:19 services homebridge[344]: Sat, 30 Jul 2016 02:49:19 GMT EventedHTTPServer [::ffff:192.168.1.127] Client connection closed
Jul 29 19:49:19 services homebridge[344]: Sat, 30 Jul 2016 02:49:19 GMT EventedHTTPServer [::ffff:192.168.1.127] HTTP connection was closed
Jul 29 19:49:19 services homebridge[344]: Sat, 30 Jul 2016 02:49:19 GMT EventedHTTPServer [::ffff:192.168.1.127] HTTP server was closed
