### ISSUE TITLE
Module version mismatch

### ISSUE THREAD

**Issue by Jborn4christ** [nfarina/homebridge#421]
Not sure how to resolve. Please assist.

Jeremys-Mac-mini:homebridge jeremychambers$ homebridge
/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/mdns/lib/dns_sd.js:35
    throw ex;
    ^

Error: Module version mismatch. Expected 46, got 14.
    at Error (native)
    at Object.Module._extensions..node (module.js:460:18)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/mdns/lib/dns_sd.js:24:20)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)

**Comment by KhaosT** [comment]
If you recently updated your nodejs version, please recompile the modules

**Comment by Jborn4christ** [comment]
I'm not really familiar with node, or compiling, so what commands should I use for that.

**Comment by KhaosT** [comment]
You can try ``npm rebuild``

**Comment by Jborn4christ** [comment]
And actually I think I got that, but I now I'm getting a "Segmentation fault:11"

**Comment by KhaosT** [comment]
Can you tell which module causes the seg fault? My guess is one or more modules failed to get recompiled correctly.

**Comment by Jborn4christ** [comment]
Just emailed you

**Comment by Jborn4christ** [comment]
This is all I get...
"Jeremys-Mac-mini:homebridge jeremychambers$ homebridge
Segmentation fault: 11"

**Comment by KhaosT** [comment]
Can you post result of ``npm version``?

**Comment by Jborn4christ** [comment]
Jeremys-Mac-mini:homebridge jeremychambers$ npm version
{ homebridge: '0.2.11',
  npm: '2.14.2',
  ares: '1.10.1-DEV',
  http_parser: '2.5.0',
  modules: '46',
  node: '4.0.0',
  openssl: '1.0.2d',
  uv: '1.7.3',
  v8: '4.5.103.30',
  zlib: '1.2.8' }

**Comment by KhaosT** [comment]
Huh, have you try to remove homebridge and reinstall it?
``sudo npm rm -g homebridge`` and ``sudo npm install -g homebridge``

**Comment by Jborn4christ** [comment]
Do i need to have Xcode installed? I notice references to it.

**Comment by Jborn4christ** [comment]
Here is the result:

Jeremys-Mac-mini:homebridge jeremychambers$ sudo npm install -g homebridge
/
> curve25519@1.1.0 install /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/curve25519
> node-gyp rebuild

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  CXX(target) Release/obj.target/curve/node_curve.o
  SOLINK_MODULE(target) Release/curve.node

> ed25519@0.0.3 install /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/ed25519
> node-gyp rebuild

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  CC(target) Release/obj.target/ed25519/src/ed25519/keypair.o
  CC(target) Release/obj.target/ed25519/src/ed25519/sign.o
  CC(target) Release/obj.target/ed25519/src/ed25519/open.o
  CC(target) Release/obj.target/ed25519/src/ed25519/crypto_verify_32.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_double_scalarmult.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_frombytes.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_scalarmult_base.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_precomp_0.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_p2_0.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_p2_dbl.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_p3_0.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_p3_dbl.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_p3_to_p2.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_p3_to_cached.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_p3_tobytes.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_madd.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_add.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_msub.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_sub.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_p1p1_to_p3.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_p1p1_to_p2.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_tobytes.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_0.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_1.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_cmov.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_copy.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_neg.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_add.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_sub.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_mul.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_sq.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_sq2.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_invert.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_tobytes.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_isnegative.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_isnonzero.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_frombytes.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_pow22523.o
  CC(target) Release/obj.target/ed25519/src/ed25519/sc_reduce.o
  CC(target) Release/obj.target/ed25519/src/ed25519/sc_muladd.o
  CXX(target) Release/obj.target/ed25519/src/ed25519.o
  SOLINK_MODULE(target) Release/ed25519.node

> mdns@2.2.11 install /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/mdns
> node-gyp rebuild

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_browse.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_enumerate_domains.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_get_addr_info.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_process_result.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_ref.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_ref_deallocate.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_ref_sock_fd.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_register.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_resolve.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/mdns_utils.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/network_interface.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/socket_watcher.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_ref.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_create.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_deallocate.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_set_value.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_get_length.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_buffer_to_object.o
  SOLINK_MODULE(target) Release/dns_sd_bindings.node

> bignum@0.11.0 install /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/srp/node_modules/bignum
> node-gyp configure build

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  CXX(target) Release/obj.target/bignum/bignum.o
  SOLINK_MODULE(target) Release/bignum.node
/usr/local/bin/homebridge -> /usr/local/lib/node_modules/homebridge/bin/homebridge
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/npm-registry-client/node_modules/npm-package-arg requires semver@'4' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/semver,
npm WARN unmet dependency which is version 5.0.1
homebridge@0.2.11 /usr/local/lib/node_modules/homebridge
├── semver@5.0.3
├── commander@2.8.1 (graceful-readlink@1.0.1)
├── chalk@1.1.1 (escape-string-regexp@1.0.3, ansi-styles@2.1.0, supports-color@2.0.0, has-ansi@2.0.0, strip-ansi@3.0.0)
└── hap-nodejs@0.0.3 (debug@2.2.0, node-persist@0.0.3, curve25519@1.1.0, ed25519@0.0.3, mdns@2.2.11, srp@0.2.0)

**Comment by KhaosT** [comment]
Yeah, build tools need xcode. You can run ``xcode-select --install`` to install the required parts.

**Comment by KhaosT** [comment]
OK, it seems Apple changed that in later release, now Xcode is required for xcodebuild... You have to install Xcode from App Store.

**Comment by Jborn4christ** [comment]
Homebridge is running on port 51826.
events.js:141
      throw er; // Unhandled 'error' event
      ^

Actually, looks like I am almost there...

This is after it gets my wink up and running, and provides my code...


Error: dns service error: unknown
    at Error (native)
    at Advertisement.on_service_registered (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/mdns/lib/advertisement.js:42:24)
    at SocketWatcher.MDNSService.self.watcher.callback (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/mdns/lib/mdns_service.js:18:40)

**Comment by KhaosT** [comment]
This is running on OS X? Can you try rebooting your Mac and run the homebridge?

**Comment by Jborn4christ** [comment]
Appears to be running. But trying to use Eve to connect it isn't finding it...

**Comment by KhaosT** [comment]
Can you try running [Bonjour Browser](http://www.tildesoft.com/) on your Mac and see if it can find .hap service?

**Comment by Jborn4christ** [comment]
![screen shot 2015-12-13 at 9 31 18 pm](https://cloud.githubusercontent.com/assets/3494551/11771617/de181c7e-a1e0-11e5-9ac0-f6f8bf00d7a7.png)

**Comment by Jborn4christ** [comment]
Appears to be

**Comment by KhaosT** [comment]
@Jborn4christ yeah, it seems running fine. Next step, can you try to run [iNet](https://itunes.apple.com/us/app/inet-network-scanner/id340793353?mt=8) on your iOS device and see if iOS device can see that service?

**Comment by Jborn4christ** [comment]
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
Homebridge is running on port 51826.
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: dns service error: unknown
    at Error (native)
    at Advertisement.on_service_registered (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/mdns/lib/advertisement.js:42:24)
    at SocketWatcher.MDNSService.self.watcher.callback (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/mdns/lib/mdns_service.js:18:40)

**Comment by KhaosT** [comment]
it should already works, try to run homebridge again and see what happens there?

BTW, can you tell what's the OS X version you're running on? it seems you're experiencing lots of issue with mDNS...

**Comment by Jborn4christ** [comment]
10.10

**Comment by Jborn4christ** [comment]
To run Homebridge, just type home bridge, correct?

**Comment by KhaosT** [comment]
yes

**Comment by KhaosT** [comment]
is it 10.10.4 or later or just 10.10? If it's 10.10, I assume it's discoveryd causing some strange issues and updating to 10.10.4 or later should fix that.

**Comment by Jborn4christ** [comment]
Updating now to 10.10.5

**Comment by Jborn4christ** [comment]
Also can't find any integration notes for the legit on wall switches. The wink hub light bulbs are showing good, but not two switches.

**Comment by Jborn4christ** [comment]
Do those get added as accessories?

**Comment by KhaosT** [comment]
For those, you'll need ask the creator of Wink plugin, I'm not sure.

**Comment by Jborn4christ** [comment]
Ok, cool. I go tit working, not the wall switches yet, but nest and lights. Thanks for your help. You guys are brilliant.

**Comment by KhaosT** [comment]
:)

**Comment by herious1989** [comment]
@Jborn4christ Ho did you fix this https://github.com/nfarina/homebridge/issues/421#issuecomment-164328966 error?
