### ISSUE TITLE
Cannot start homebridge at all

### ISSUE THREAD

**Issue by andrelind** [nfarina/homebridge#422]
When trying to startup homebridge to run agains my Z-Way Server this is all that happens
```
~ $ homebridge
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
No plugins found. See the README for information on installing plugins.
Loaded config.json with 0 accessories and 1 platforms.
---
Loading 1 platforms...
/usr/local/lib/node_modules/homebridge/lib/api.js:88
      throw new Error("The requested platform '" + name + "' was not registered by any plugin.");
      ^

Error: The requested platform 'ZWayServer' was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:88:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:185:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:35:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:23:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
```

My config file:
```
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "100-20-300"
    },

    "description": "My awesome description",

    "platforms": [
        {
           "platform": "ZWayServer",
           "url": "http://localhost:8083/",
           "login": "mylogin",
           "password": "mypassword"
        }
    ]
}
```

**Comment by kenderson** [comment]
@andrelind What was the solution to your issue above?

**Comment by rudders** [comment]
@kenderson - I think he'd forgotten to install the plugin by the look of the log.

**Comment by kenderson** [comment]
@rudders Appreciate the tip here! I just updated both the core homebridge code as well as your homebridge-platform-wemo code, and end up the same error as above when I attempt to fire it up for the first time. It seems perhaps related to the same issue that folks were seeing about a month ago? https://github.com/nfarina/homebridge-sonos/issues/10

**Comment by rudders** [comment]
But your config mentions zway? Have you installed the zway plugin?

**Comment by rudders** [comment]
This error in particular points to Homebridge being unable to find any plugins 

No plugins found. See the README for information on installing plugi

**Comment by kenderson** [comment]
@rudders Below is a full snapshot of what I get. A couple notes;

1. The legacy stuff loads, but I don't use it. I'm not sure how to dump it.
2. My config file is only referencing the homebridge-platform-wemo plugin

Any guidance is welcome and appreciated!

```
Kens-iMac:~ kenhenderson$ homebridge
Loaded plugin: homebridge-legacy-plugins
Registering accessory 'homebridge-legacy-plugins.AD2USB'
Registering accessory 'homebridge-legacy-plugins.Carwings'
Registering accessory 'homebridge-legacy-plugins.ELKM1'
Registering accessory 'homebridge-legacy-plugins.FileSensor'
Registering accessory 'homebridge-legacy-plugins.GenericRS232Device'
Registering accessory 'homebridge-legacy-plugins.HomeMatic'
Registering accessory 'homebridge-legacy-plugins.HomeMaticThermo'
Registering accessory 'homebridge-legacy-plugins.HomeMaticWindow'
Registering accessory 'homebridge-legacy-plugins.HttpGarageDoorOpener'
Registering accessory 'homebridge-legacy-plugins.HttpHygrometer'
Registering accessory 'homebridge-legacy-plugins.HttpThermometer'
Registering accessory 'homebridge-legacy-plugins.Tesla'
Registering accessory 'homebridge-legacy-plugins.X10'
Registering accessory 'homebridge-legacy-plugins.mpdclient'
Registering platform 'homebridge-legacy-plugins.Domoticz'
Registering platform 'homebridge-legacy-plugins.HomeAssistant'
Registering platform 'homebridge-legacy-plugins.HomeSeer'
Registering platform 'homebridge-legacy-plugins.ISY'
Registering platform 'homebridge-legacy-plugins.LIFx'
Registering platform 'homebridge-legacy-plugins.SmartThings'
Registering platform 'homebridge-legacy-plugins.TelldusLive'
Registering platform 'homebridge-legacy-plugins.ZWayServer'
---
Loaded plugin: homebridge-nest
Registering platform 'homebridge-nest.Nest'
---
Loaded plugin: homebridge-wemo
Registering accessory 'homebridge-wemo.WeMo'
---
Loaded config.json with 0 accessories and 1 platforms.
---
Loading 1 platforms...
/usr/local/lib/node_modules/homebridge/lib/api.js:88
      throw new Error("The requested platform '" + name + "' was not registered by any plugin.");
      ^

Error: The requested platform 'BelkinWeMo' was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:88:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:194:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:35:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:23:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3
```

**Comment by rudders** [comment]
Could you post your config.json also please

**Comment by rudders** [comment]
BelkinWemo is the platform from Homebridge-platform-wemo you appear to be loading Homebridge-wemo.

**Comment by rudders** [comment]
Oh and assuming you use npm to install the legacy logins then `npm uninstall -g homebridge-legacy-plugis` should work.

**Comment by kenderson** [comment]
@rudders Legacy Plugins uninstalled - thank you!
```
{
	"bridge": {
		"name": "Homebridge",
		"username": "$$$$",
		"port": $$$,
		"pin": "$$$-$$-$$$"
	},

	"description": "This is an example configuration file with all supported devices. You can use this as a template for creating your own configuration file containing devices you actually own.",

	"platforms": [
		{
			"platform": "BelkinWeMo",
			"name": "WeMo Platform",
			"expected_accessories" : "0",
			"timeout" : "25",
			"no_motion_timer": "60",
			"homekit_safe" : "1"
		}
	]
}
```

**Comment by rudders** [comment]
You need to install Homebridge-platform-wemo. And uninstall homebridge-wemo if your not using it, which is recommend not to.

**Comment by kenderson** [comment]
Got it - uninstalling homebridge-wemo was the ticket. Thank you @rudders!

**Comment by kenderson** [comment]
@rudders Last question and then I'll stop bothering you :-) Do you envision supporting Wemo Maker with the Wemo Platform? If so, any thoughts on a timeline? For some reason, I thought I had read that you folded into a recent release.

**Comment by AppleTechy** [comment]
@Kenderson  There is a beta build that is being worked on to support the
Wemo coffee maker. I don't know any of the other details as I don't have
the coffee maker. For me info your going to have to talk to @rudders

**Comment by rudders** [comment]
I have recently acquired a Maker to play with but as far as I understand it is a very flexible device and would need specific configuration in config.json to interpret what the actual use case is for the device. I'll probably look at doing a separate plugin for it if I proceed at all. s for the coffee maker - I'm not inclined to acquire one so unless someone wants to lend me one (in Sydney Australia) we may need to find someone with one and the requisite skills that is willing to update the plugin and submit a PR.

**Comment by AppleTechy** [comment]
Lol. My response was terribly inadequate. Sorry for confusing you. Plus I
was totally wrong, so ignore my earlier post :)

**Comment by timswf** [comment]
H both - thank you for this guide - I wonder of you can help with my installation? I've been able to get to the register with homekit code screen without a config file - but when I add the config I get errors. Sorry if I've posted this in the wrong place - am v new to this and my Pi!

Here's my config file

    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "123-45-678"
    },
    "description:: "test"
    "platforms": [{
        "platform": "BelkinWeMo",
        "name": "WeMo Platform",
        "expected_accessories": "3",
        "timeout": "25",
        "homekit_safe": "1"
    }]

and the error I get is

/usr/local/lib/node_modules/homebridge/lib/server.js:176
    throw err;
    ^

SyntaxError: Unexpected token t in JSON at position 167
    at Object.parse (native)
    at Server._loadConfig (/usr/local/lib/node_modules/homebridge/lib/server.js:170:19)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:44:23)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)

**Comment by abataille** [comment]
You have :: in the description tag. Try jsonlint.com

**Comment by timswf** [comment]
Thanks for checking.. now have more errors.. think will go for a fresh start and try installing again with fresh config!

**Comment by timswf** [comment]
Hi v many thanks again - wiped the Pi and installed all again and got the config right and working - thank you! Best regards Tim
