### ISSUE TITLE
Z-wave Switches/Outlets

### ISSUE THREAD

**Issue by Jborn4christ** [nfarina/homebridge#423]
Has anyone gotten z-wave switches or outlets to work through a wink hub? They obviously show up in wink app, but not in Homebridge. Just curious.

**Comment by AppleTechy** [comment]
There should be an update pushed out by the end of the week by @pdlove or @KraigM which will bring support for both

**Comment by Jborn4christ** [comment]
Awesome news

"Live your life as if it were a work of art."
-Abraham Joshua Heschel

**Comment by AppleTechy** [comment]
kraigm/homebridge-wink#5

**Comment by AppleTechy** [comment]
close #423

**Comment by AppleTechy** [comment]
close

**Comment by AppleTechy** [comment]
duplicate of Kraigm/homebridge-wink#5

**Comment by AppleTechy** [comment]
duplicate
