### ISSUE TITLE
Remove and re-add homebridge in HomeKit after ne package and edit config.json

### ISSUE THREAD

**Issue by DJay1** [nfarina/homebridge#426]
Hi there..
Is it correct that everytime I install a new package and change the config.json I have to remove the Homebridge Device completely on my iOS and re-add it?

At the moment I'm experience this. Homebridge does not work after a new package and edit config.json only after I removed it completely from the iOS and re-add it search for new device, enter code etc.
At this way of course all my scenes are empty after this I have to configure all new. 
Or am I doing something wrong? 
Thanks in advance for your help and reply.

**Comment by nfarina** [comment]
This is not expected - I've added and removed accessories many times and all that should be required is restarting the Homebridge server.

**Comment by AppleTechy** [comment]
@DJay1 You need to end homebridge process and restart it everytime after you edit your config and or install a new package. Also make sure you are running the newest version of homebridge for the less to limit the variables that could be causing the issue if you are still experiencing it.
