### ISSUE TITLE
Howto multiple platforms/accessories?

### ISSUE THREAD

**Issue by joystick666** [nfarina/homebridge#428]
Hi all,
I am somehow stuck here.
I have homebridge Running with Fibaro Plugin, an also installed Hue Platform and Sonos Accessorie.
However, if i setup Both (Fibaro and Hue) in config json, either Fibaro Or hue is working (the Last in the Config) .
Same with sonos, more than one speaker will nötig work.

I think there is some error/misunderstanding in the config file, so could someone post a Sample file With more than one platform?

Cheers 
Joystick

**Comment by DJay1** [comment]
Recently I had the same challenge. I'm new to this all and I had some problem with this { } [ ], things. ;)
Maybe this config.json helps.
[config.json.txt](https://github.com/nfarina/homebridge/files/67218/config.json.txt)

**Comment by rafaelsantander** [comment]
I have the same issue. Is there any documentation on how to append multiple platforms &/or accessories @nfarina? thanks!

**Comment by nfarina** [comment]
@joystick666 Sounds like you may be writing the `platforms: [...]` block multiple times. Take a look at @DJay1's link, that looks more correct to me.

**Comment by rafaelsantander** [comment]
I had the same problem @joystick666. I was missing a `,` between the platform and accessory definition. post your json and I'll take a look. remove your creds before posting.

**Comment by scubidu24** [comment]
Hi Guys

I have been trying for hours now :( Could someone please have a look at my config to make it work? Many thanks in Advance!

{
	"bridge": {
		"name": "Homebridge",
		"username": "X",
		"port": X,
		"pin": "X"

	},



	"platforms": [{
		"platform": "eveatmo",
		"name": "eveatmo platform",
		"extra_co2_sensor": false,
		"ttl": 540,
		"auth": {
			"client_id": "X",
			"client_secret": "x",
			"username": "X",
			"password": "X"
		},
		{
			"platform": "HarmonyHub",
			"name": "Harmony Hub"
		}
	}]
}

**Comment by scubidu24** [comment]
Hi Guys

I have been trying for hours now :( Could someone please have a look at my config to make it work? Many thanks in Advance!

{
"bridge": {
"name": "Homebridge",
"username": "X",
"port": X,
"pin": "X"

},



"platforms": [{
	"platform": "eveatmo",
	"name": "eveatmo platform",
	"extra_co2_sensor": false,
	"ttl": 540,
	"auth": {
		"client_id": "X",
		"client_secret": "x",
		"username": "X",
		"password": "X"
	},
	{
		"platform": "HarmonyHub",
		"name": "Harmony Hub"
	}
}]
}

**Comment by shotgoto** [comment]
I think your Harmony Hub is still inside the eveatmo platform. If you rewrite your code this way, you can tell:

Yours:
```
{
    "bridge":
    {
        "name": "Homebridge",
        "username": "X",
        "port": X,
        "pin": "X"
    },

    "platforms":
    [
        {
            "platform": "eveatmo",
            "name": "eveatmo platform",
            "extra_co2_sensor": false,
            "ttl": 540,
            "auth":
            {
                "client_id": "X",
                "client_secret": "x",
                "username": "X",
                "password": "X"
            },

            {
                "platform": "HarmonyHub",
                "name": "Harmony Hub"
            }
        }
    ]
}
```
My suggestion:
```
{
    "bridge":
    {
        "name": "Homebridge",
        "username": "X",
        "port": X,
        "pin": "X"
    },

    "platforms":
    [
        {
            "platform": "eveatmo",
            "name": "eveatmo platform",
            "extra_co2_sensor": false,
            "ttl": 540,
            "auth":
            {
                "client_id": "X",
                "client_secret": "x",
                "username": "X",
                "password": "X"
            }
        },
        {
            "platform": "HarmonyHub",
            "name": "Harmony Hub"
        }
    ]
}
```
