### ISSUE TITLE
running homebridge with forever (on mac osx)

### ISSUE THREAD

**Issue by r1tchy** [nfarina/homebridge#430]
Hey guys, I'm confused on how to run the globally installed homebridge (/.homebridge) with forever?

any help on that ? tnx

**Comment by IMNotMax** [comment]
On OS X it's easy.
On the Users Pref pane, choose the automatic start panel. Just Add Homebridge to this panel.
The path of the bin file is "/usr/local/bin/homebridge" 
Just clic on the + sign, copy paste the path and you're done.

Every time your mac boots, the homebrige will be launched.
The only "issue" is the terminal windows will appear.

If you really want home bridge to run a background without terminal window, i'm writing a .plist and an install bash

**Comment by r1tchy** [comment]
tnx your reply helped me with the path of the bin file..

in case anybody lands here while searching how to run homebridge with forever in mac osx terminal:

to install forever:
npm install forever -g

to run homebridge with forever:
cd /usr/local/bin/
forever start homebridge

now you can close terminal window and homebridge is still running..
(if homebridge is configured correctly.. you can always check the forever logs)


if you want it to run on boot, you can make automator run a shell script with those 2 commands, save it, and then just as IMNotMax said:

On the Users Pref pane, choose the automatic start panel.
Just clic on the + sign, and point to the automator file you created..

please reply with any remarks ! tnx

**Comment by IMNotMax** [comment]
LoL I did not understood your question :)
english is not my native language, and I have to improve it :+1:

**Comment by r1tchy** [comment]
😬
