### ISSUE TITLE
installation not working on OSMC raspberry

### ISSUE THREAD

**Issue by sdecaux** [nfarina/homebridge#431]
I am trying to install on a raspberry with a OSMC distribution (new version of raspbmc).
It is not as straightforward as I hoped.

I did followed the wiki page https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi and managed to install the correct version of g++ (`g++ -v` returns "gcc version 4.9.2 (Raspbian 4.9.2-10)") and nodeJS (`node -v` returns "v4.0.0"). I also installed Avahi and updated all packages.

First try of `sudo npm install -g homebridge` failed with [ErrorLog1.txt](https://github.com/nfarina/homebridge/files/67946/ErrorLog1.txt), complaining of "git" not found, so I installed also git with `apt-get install git-core`. The install then goes further, but still fails -> [ErrorLog2.txt](https://github.com/nfarina/homebridge/files/67947/ErrorLog2.txt) that is harder to explain : "Command failed: git config --get remote.origin.url" and "Error: not found: make".

Help!

**Comment by trusk89** [comment]
apt-get install make. I had the same problem.

**Comment by sdecaux** [comment]
Thanks! In the meantime I managed through `apt-get install build-essential` that I suppose includes "make" :)

So I suppose it should be added in the wiki `apt-get install git-core make`

**Comment by trusk89** [comment]
Kinda depends on what you are running. The wiki is written for raspbian, which includes build-essentials. I had to manually install it as I am running it on osmc, which in turn is based on a strippe down version of debian.

**Comment by sdecaux** [comment]
Yes. I added it to the wiki anyway, could save some hours to some poor OSMC owners ;)
