### ISSUE TITLE
Siri don't want to close the light

### ISSUE THREAD

**Issue by thib5** [nfarina/homebridge#432]
Hi, I set up everything and when I said "siri turn on the light" she answer : ok light is on then i said close the light and she answer me i can't find any light for now...

**Comment by PatcherMustermann** [comment]
https://github.com/nfarina/homebridge/wiki/Siri-commands

**Comment by AppleTechy** [comment]
What app are you using? If you are using Insteon+ go to home/tap the little list icon in the right corner/edit devices/The light you are trying to control/ then it should have an option on that next screen to choose if it is a lightbulb,fan, or etc. Where you able to resolve your issue?
