### ISSUE TITLE
Running on Windows

### ISSUE THREAD

**Issue by Joey-1970** [nfarina/homebridge#433]
Hello!

How can I start on bootup in Windows?
How start, stop, restart and control status?

Joachim

**Comment by PatcherMustermann** [comment]
@Joey-1970: You can create a start skript over a bacht file. I have write a tool to start Homebridge "invisible" on windows. 

What do you mean by: How to start, stop, restart and control status?

Greeting
Patcher

**Comment by Joey-1970** [comment]
Hello Patcher,
thanks for your reply. May you show me your startscript?

I want to get regularly control the state (running/not running) of the homebridge from another application (like 'sudo /etc/init.d/homebridge status' on Raspberry Pi).
And - if this possible - check the log or error messages (like 'tail -f /var/log/homebridge.log' on Raspberry Pi).

Joachim

**Comment by PatcherMustermann** [comment]
Here ist my batch (start.bat) file:

echo off
cd C:\Users\xxx\AppData\Roaming\npm\node_modules\homebridge\bin
cls
node homebridge


You are from Germany?

Greeting
Patcher

**Comment by Joey-1970** [comment]
Hello Patcher,

thanks for your script, it is very helpful. I try to install it on my system.

Yes, I am from Germany. Why?

Joachim

**Comment by PatcherMustermann** [comment]
Hello Joachim,
i come from Germany and thy name is typically German ;)

If you want, I can tell you later yet another way of booting Homebridge?!

Greeting
Patcher

**Comment by Joey-1970** [comment]
Hello Patcher,

this would be very nice!

Joachim

**Comment by PatcherMustermann** [comment]
Hello Joachim,
sorry, today I had no time. I think I have time tomorrow night.

Greeting
Patcher

**Comment by Joey-1970** [comment]
Hello Patcher,

maybe this Link will help us to take (a little) control of the homebridge?
https://www.npmjs.com/package/node-windows

Joachim

**Comment by PatcherMustermann** [comment]
Hello Joachim,
sorry for my late answer. I have write a new version of my program to start homebridge on Windows.

You can download it from the Annex.

I hope it match your requirements?!

Greeting
Patcher

[shb.zip](https://github.com/nfarina/homebridge/files/73122/shb.zip)

**Comment by Joey-1970** [comment]
Many, many thanks!!!

Unfortunely I haven't the time to test it. A question before I do it: Can I start and stop up over command line too? I need to control from another application... ;-)

Joachim

**Comment by PatcherMustermann** [comment]
Hello Joachim,
Currently you can not. What do you imagine that? About TCP or Shell?

Greeting
Patcher

**Comment by Joey-1970** [comment]
Hello Patcher,

I think that is equal for me. The Homebridge runs on the same WHS 2011 as my smart-home-application (IP-Symcon).
So I think I can go both ways.

Joachim

**Comment by PatcherMustermann** [comment]
Hello Joachim,
now i have make a new version with TCP-control and Tray-control. You can download it from the Annex. Please read the "_Readme.txt" for details.

I hope it match your requirements?!

Greeting
Patcher

Download: [shb.zip](https://github.com/nfarina/homebridge/files/74400/shb.zip)

**Comment by Joey-1970** [comment]
Hello Patcher,

many thanks for your commitment!!!!! I will test  it tomorow... ;-))

There is a interesting discussion on issue #420 ...

Joachim

**Comment by Joey-1970** [comment]
...I could't wait until tomorow - look very nice!!!

Joachim

**Comment by PatcherMustermann** [comment]
Hello Joachim,
I think you can now close this issues - or?

Greeting
Patcher

**Comment by Joey-1970** [comment]
Hello Patcher,

yes, thank you very much for support!

Joachim
