### ISSUE TITLE
How do I use homebridge to execute script on the RPi

### ISSUE THREAD

**Issue by casper-gh** [nfarina/homebridge#434]
Is it possible to execute some bash or php scripts using homebridge? What does the config.json look like?

**Comment by IMNotMax** [comment]
I think you can use the [ssh plugin](https://www.npmjs.com/package/homebridge-ssh) to execute scripts.

**Comment by herious1989** [comment]
@IMNotMax On my server I use putty ppk key to access (yes, I installed putty ssh on a linux to talk with other server), I don't know if this plugin would work, is there any plugin that can send http post to an endpoint I set up on my server?

**Comment by IMNotMax** [comment]
Homebridge-http :)

**Comment by IMNotMax** [comment]
See the plugins via the npmjs homebridge page
