### ISSUE TITLE
Unable to run Homebridge on Bootup Raspberry Pi

### ISSUE THREAD

**Issue by casper-gh** [nfarina/homebridge#435]
I followed the instruction [https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi] to set up auto start on boot.

When I type `sudo /etc/init.d/homebridge start`, it just doesn't do anything

**Comment by trusk89** [comment]
If it's a bash script you should run it with ./ so it becomes

sudo /etc/init.d/./homebridge start

And don't forget to make it executable with

chmod a+x homebridge

**Comment by herious1989** [comment]
Still does not work for me. The only way to start is `homebridge` from anywhere, but I want it to start on boot

**Comment by hofster** [comment]
Probably your init script is incomplete. See “Running Homebridge on Bootup“ in the wiki (https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi#running-homebridge-on-bootup).
Use the init script template or raw template file AND then modify the top of the file as mentioned in the wiki.

Here is mine:
—
#!/bin/sh
### BEGIN INIT INFO
# Provides: homebridge
# Required-Start:    $network $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

dir="/home/pi"
cmd="DEBUG=* /usr/local/bin/homebridge"
user="pi"

name=`basename $0`
pid_file="/var/run/$name.pid"
stdout_log="/var/log/$name.log"
stderr_log="/var/log/$name.err"

get_pid() {
    cat "$pid_file"
}

is_running() {
    [ -f "$pid_file" ] && ps `get_pid` > /dev/null 2>&1
}

case "$1" in
    start)
    if is_running; then
        echo "Already started"
    else
        echo "Starting $name"
        cd "$dir"
        if [ -z "$user" ]; then
            sudo $cmd >> "$stdout_log" 2>> "$stderr_log" &
        else
            sudo -u "$user" $cmd >> "$stdout_log" 2>> "$stderr_log" &
        fi
        echo $! > "$pid_file"
        if ! is_running; then
            echo "Unable to start, see $stdout_log and $stderr_log"
            exit 1
        fi
    fi
    ;;
    stop)
    if is_running; then
        echo -n "Stopping $name.."
        kill `get_pid`
        for i in {1..10}
        do
            if ! is_running; then
                break
            fi

            echo -n "."
            sleep 1
        done
        echo

        if is_running; then
            echo "Not stopped; may still be shutting down or shutdown may have failed"
            exit 1
        else
            echo "Stopped"
            if [ -f "$pid_file" ]; then
                rm "$pid_file"
            fi
        fi
    else
        echo "Not running"
    fi
    ;;
    restart)
    $0 stop
    if is_running; then
	echo "Unable to stop, will not attempt to start"
        exit 1
    fi
    $0 start
    ;;
    status)
    if is_running; then
        echo "Running"
    else
        echo "Stopped"
        exit 1
    fi
    ;;
    *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0
—

 <https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi#running-homebridge-on-bootup>

**Comment by herious1989** [comment]
Thanks, works good

**Comment by herious1989** [comment]
For some reason when I reformatted the drive and restore from backup, it won't start on boot anymore, error and log showed these:

    pi@raspberrypi-2:~ $ tail -f /var/log/homebridge.log
    Registering platform 'homebridge-legacy-plugins.TelldusLive'
    Registering platform 'homebridge-legacy-plugins.ZWayServer'
    ---
    Loaded config.json with 0 accessories and 1 platforms.
    ---
    Loading 1 platforms...
    [SmartThings] Initializing SmartThings platform...
    Loading legacy platform SmartThings
    [SmartThings] Fetching SmartThings devices...
    [SmartThings] There was a problem authenticating with SmartThings.

    pi@raspberrypi-2:~ $ tail -f /var/log/homebridge.err
    *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
    *** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
    *** WARNING *** Please fix your application to use the native API of Avahi!
    *** WARNING *** For more information see <http://0pointer.de/avahi-compat?    s=libdns_sd&e=node&f=DNSServiceRegister>
    *** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
    *** WARNING *** Please fix your application to use the native API of Avahi!
    *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
    *** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
    *** WARNING *** Please fix your application to use the native API of Avahi!
    *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>

It starts fine if I run `sudo /etc/init.d/homebridge start`

No idea what happened

**Comment by herious1989** [comment]
anyone has same issue?

**Comment by devbobo** [comment]
Personally, I prefer to run Homebridge with forever.

Here's my script in `/etc/init.d/homebridge`
```
#!/bin/sh

case "$1" in
    start)
        su - pi -c "forever start  --spinSleepTime 5000 --sourceDir=/usr/local/bin homebridge" 
        ;;
    stop)
        su - pi -c "forever stopall"
        forever stopall
        ;;
    restart)
        su - pi -c "forever restartall"
        forever restartall
        ;;
    status)
        su - pi -c "forever list"
        forever list
        ;;
esac

exit 0
```

**Comment by AppleTechy** [comment]
issue #383

**Comment by herious1989** [comment]
I actually found out this error cause homebridge fails to start on boot. Like I said, It works when I start from /etc/init.d/homebridge start|stop|status

https://github.com/nfarina/homebridge/issues/460

**Comment by rudders** [comment]
Have you run sudo update-rc.d /etc/init.d/....

**Comment by herious1989** [comment]
I did

**Comment by cmcarver** [comment]
I had a similar issue and found my disk space was 0.  Once I freed up space I had to reboot and it auto-launched

**Comment by timleland** [comment]
Here is my guide in setting up Homebridge on Raspberry Pi to start on boot up and restart on errors. Hope it help!
https://timleland.com/setup-homebridge-to-start-on-bootup/

**Comment by frodeaux** [comment]
@timleland I am using the same setup for auto start and it works well.  I notice you use RFswitches as well.  Are you controlling them from homebridge?  If so what plugin are you using?  I have run into problems using any plugin that requires wiringpi and using the systemd auto start method.  I assume its permissions issue where wiring pi is not being run as root.  Any advice on how to get that working?

**Comment by timleland** [comment]
@frodeaux If you follow my [guide](https://timleland.com/wireless-power-outlets/) on setting up the rf outlets, you can call the codesend program directly from homebridge using [cmdswitch2](https://www.npmjs.com/package/homebridge-cmdswitch2).

**Comment by Maikeximu** [comment]
Just a quick tip, on latest Node, Homebridge is not located on /usr/local/lib but in /usr/lib. Just change the line `cmd="DEBUG=* /usr/local/bin/homebridge"` into `cmd="DEBUG=* /usr/bin/homebridge"` and it works like a charm

**Comment by MrNPP** [comment]
@timleland Thanks for your step-by-step guide, worked perfectly (I also had to remove 'local' from one of the steps. 
You've provided far better instructions than in the Wiki, perfect for people like myself you a new to coding etc but want to leverage the benefits of Homebridge.
Thanks!

**Comment by timleland** [comment]
@MrNPP thanks! Glad it helped.

**Comment by b8ka** [comment]
> Just a quick tip, on latest Node, Homebridge is not located on /usr/local/lib but in /usr/lib. Just change the line cmd="DEBUG=* /usr/local/bin/homebridge" into cmd="DEBUG=* /usr/bin/homebridge" and it works like a charm

@Maikeximu - that actually help! Thanks!

**Comment by LucLisette** [comment]
Hey, I am new with almost no experiance and my english is bad. Do not know if I am in the right topic?
My RBPi 3 is running stretch. I can not get homebridge to run.
this is what I get. Can someone help please.

pi@raspberrypi:~ $ sudo systemctl status homebridge.service -l
● homebridge.service - HomeBridge Service
   Loaded: loaded (/lib/systemd/system/homebridge.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sat 2018-02-17 12:14:01 CET; 8min ago
 Main PID: 25566 (code=exited, status=1/FAILURE)

feb 17 12:13:59 raspberrypi node[25566]: *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
feb 17 12:13:59 raspberrypi node[25566]: *** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supp
feb 17 12:13:59 raspberrypi node[25566]: *** WARNING *** Please fix your application to use the native API of Avahi!
feb 17 12:13:59 raspberrypi node[25566]: *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSSer
feb 17 12:14:01 raspberrypi homebridge[25566]: [2018-2-17 12:14:01] Loaded plugin: homebridge-gpio-relay
feb 17 12:14:01 raspberrypi homebridge[25566]: [2018-2-17 12:14:01] Registering accessory 'homebridge-gpio-relay.relay'
feb 17 12:14:01 raspberrypi homebridge[25566]: [2018-2-17 12:14:01] ---
feb 17 12:14:01 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
feb 17 12:14:01 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
feb 17 12:14:01 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
lines 1-15/15 (END)

**Comment by AppleEducate** [comment]
> Personally, I prefer to run Homebridge with forever.

> 
> Here's my script in /etc/init.d/homebridge
> 
> #!/bin/sh
> 
> case "$1" in
>     start)
>         su - pi -c "forever start  --spinSleepTime 5000 --sourceDir=/usr/local/bin homebridge" 
>         ;;
>     stop)
>         su - pi -c "forever stopall"
>         forever stopall
>         ;;
>     restart)
>         su - pi -c "forever restartall"
>         forever restartall
>         ;;
>     status)
>         su - pi -c "forever list"
>         forever list
>         ;;
> esac
> 
> exit 0

@devbobo  How can you check the status if logged in via SSH using this script on bootup?
