### ISSUE TITLE
no directory homebridge in home/pi on a raspberry Pi 2 ?

### ISSUE THREAD

**Issue by chris2div** [nfarina/homebridge#436]
Hello,
I have install a raspberry Pi2 with the last RaspBian with Jessie.
I have gcc v4.9.2, node v4.2.4, and Avahi.
After sudo apt-update, sudo apt-get update, ans sudo reboot, I install HomeBridge with sudo npm install -g homebridge. All it's ok, Homebridge is OK (message   Couldn't find a config.json file at '/home/pi/.homebridge/config.json).
But...  the problem is I don't have any directory homebridge. I search this directory but nothing :-(
Could you help me please ?
Thank you very mych an happy christmas !
Chris

**Comment by IMNotMax** [comment]
The directory is hidden. It's your_home_dir/.homebridge. 
Try to use a Terminal to see it. 

Usually after installing homebridge you have to follow these steps:
First, You have to install plugins (see npmjs.com and search for homebridge). 
Then create a directory in ~/ (it's your home directory) name .homebridge/ (and don't forget the dot if it's not created (weird !)
Now you can create, copy/paste a config.json

Then launch homebridge
