### ISSUE TITLE
Multiple Accessories Issue

### ISSUE THREAD

**Issue by syncome** [nfarina/homebridge#437]
I have two accessories defined in one config.json. I have issues when loading config.json.

Would someone please tell whether this's a bug, or a wrong written config.json?

Thank you.

The server gives the following error:

---
## Loaded config.json with 2 accessories and 0 platforms.

Loading 0 platforms...
Loading 2 accessories...
[Bedroom Lamp] Initializing Http accessory...
[Bedroom Lamp] getServices
[Aircon Sleep Mode] Initializing Http accessory...
[Aircon Sleep Mode] getServices
/usr/local/lib/node_modules/homebridge/lib/server.js:228
  if (!(services[0] instanceof Service)) {
                ^

TypeError: Cannot read property '0' of undefined
    at Server._createAccessory (/usr/local/lib/node_modules/homebridge/lib/server.js:228:17)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:167:26)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:36:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:23:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)

Config.json file:::::::::::::::::::::::::::::::::::::::
{
    "bridge": {
        "name": "HomebridgePI",
        "port": 51826,
        "pin": "031-45-156",
        "username": "xx:22:3D:E3:CE:31"
    },

```
"description": "SmallK",

"platforms": [],

"accessories": [{
    "accessory": "Http",
    "name": "Bedroom Lamp",
    "on_url": "",
    "on_body": "{\"state\":\"On\"}",
    "off_url": "",
    "off_body": "{\"state\":\"Off\"}",
    "brightness_url": "",
    "username": "xxxx",
    "password": "xxxx",
    "clientid": "xxxx",
    "clientSecret": "xxxx",
    "user_id": "xxxx",
    "smallK_id": "xxxx",
    "remoteType": "1",
    "sendimmediately": "",
    "http_method": "POST",
    "http_brightness_method": "POST",
    "service": "Switch",
    "brightnessHandling": "no"
}, {
    "accessory": "Http2”,
    "name": "Aircon Sleep Mode",
    "on_url": "xxx",
    "on_body": "xxxx",
    "off_url": "xxx",
    "off_body": "xxxx",
    "brightness_url": "",
    "username": "xxxx",
    "password": "xxx",
    "clientid": "xxx",
    "clientSecret": "xxx",
    "user_id": "xxx",
    "smallK_id": "xxx",
    "remoteType": "1",
    "sendimmediately": "",
    "http_method": "POST",
    "http_brightness_method": "POST",
    "service": "Aircon",
    "brightnessHandling": "no"
}]
```

}

**Comment by IMNotMax** [comment]
To check the syntax you can add '''json before and just ''' after your copy-paste. 
The preview will highlight in red if a problem is detected

**Comment by IMNotMax** [comment]
see:

```json
{
"bridge": {
"name": "HomebridgePI",
"port": 51826,
"pin": "031-45-156",
"username": "xx:22:3D:E3:CE:31"
},

"description": "SmallK",

"platforms": [],

"accessories": [{
    "accessory": "Http",
    "name": "Bedroom Lamp",
    "on_url": "",
    "on_body": "{\"state\":\"On\"}",
    "off_url": "",
    "off_body": "{\"state\":\"Off\"}",
    "brightness_url": "",
    "username": "xxxx",
    "password": "xxxx",
    "clientid": "xxxx",
    "clientSecret": "xxxx",
    "user_id": "xxxx",
    "smallK_id": "xxxx",
    "remoteType": "1",
    "sendimmediately": "",
    "http_method": "POST",
    "http_brightness_method": "POST",
    "service": "Switch",
    "brightnessHandling": "no"
}, {
    "accessory": "Http2”,
    "name": "Aircon Sleep Mode",
    "on_url": "xxx",
    "on_body": "xxxx",
    "off_url": "xxx",
    "off_body": "xxxx",
    "brightness_url": "",
    "username": "xxxx",
    "password": "xxx",
    "clientid": "xxx",
    "clientSecret": "xxx",
    "user_id": "xxx",
    "smallK_id": "xxx",
    "remoteType": "1",
    "sendimmediately": "",
    "http_method": "POST",
    "http_brightness_method": "POST",
    "service": "Aircon",
    "brightnessHandling": "no"
}]
}

```

**Comment by IMNotMax** [comment]
And above all, your second accessories must be http and not http2... this instruction call the plugin... you use the plugin http :) there is no http2 plugin

**Comment by syncome** [comment]
Hi @IMNotMax , thanks for replying :)

I've checked my original JSON file and it's correct.

And I've also changed Http2 to Http, but homebridge threw the same error:


if (!(services[0] instanceof Service)) {
                ^

TypeError: Cannot read property '0' of undefined
    at Server._createAccessory (/usr/local/lib/node_modules/homebridge/lib/server.js:228:17)

**Comment by IMNotMax** [comment]
Try to delete the second accessory. I think there are s a problem with this one.
