### ISSUE TITLE
Connection Reset interacting with Hue

### ISSUE THREAD

**Issue by alistairg** [nfarina/homebridge#44]
I'm getting this odd error interacting with the two Hue hubs in my home. Both hubs are running the latest firmware, and both happily went through the initial linking / user generation process.

Any thoughts? :|

```
[Media Room Hue] Initializing PhilipsHue platform...
[Media Room Hue] Fetching Philips Hue lights from 172.16.1.23, user <Removed>...
Loading 0 accessories...
/Users/alistair/Dropbox/Development/Node/homebridge/node_modules/node-hue-api/node_modules/q/q.js:126
                    throw e;
                          ^
Error: connect ECONNRESET
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)
```

**Comment by alistairg** [comment]
OK - I tracked this one down. It's rate-limiting on the hub. I've got a lot of bulbs (~40 on each hub). After returning the status for the first 16 bulbs, the hub kills the connection - which causes the error above.

IIRC you can return the state for all bulbs in a single call, and then iterate.... will look to changing that, and doing a PR.

**Comment by madmod** [comment]
I have a PR in progress for this if you can wait a day.

**Comment by alistairg** [comment]
Absolutely. Thanks! :)

**Comment by maddox** [comment]
> IIRC you can return the state for all bulbs in a single call, and then iterate.... will look to changing that, and doing a PR.

I'd love to see how we can implement this in an Async world and one in which HomeKit asks individually. Wink also can fetch everything at once. In fact, the lib being used doesn't even use an individual endpoint, it just grabs everything and cherry picks the device, lol.

While API limits aren't an issue, it just feels gross.

I just wasn't sure about how to really mange this outside of just cacheing and ACCIDENTALLY returning from the cache because of latent requests, lol.

**Comment by madmod** [comment]
I have a plan for grouping requests for changing scenes but it will take a while to do it right. For getting the state of all bulbs node-hue-api has a `fullState()` call that is expensive but less expensive than getting the state of all 40 bulbs individually.

**Comment by madmod** [comment]
Also for the rate limiting I am using the excellent [bottleneck](https://github.com/SGrondin/bottleneck) module if someone else is working an a PR for this.
