### ISSUE TITLE
homebridge.log and homebridge.err in Windows?

### ISSUE THREAD

**Issue by Joey-1970** [nfarina/homebridge#443]
Hello!

Is in Windows a homebridge.log and homebridge.err like on a Raspberry Pi?

If the answer is yes, where can I find it?

Joachim

**Comment by bittles** [comment]
Also having this issue, anyone know an answer?

**Comment by snowdd1** [comment]
I don't use it on windows, but google showed this article on redirecting stdout and stderr in windows: https://support.microsoft.com/de-de/help/110930/redirecting-error-messages-from-command-prompt-stderr-stdout

**Comment by i3laze** [comment]
Any support out there?

Where does Windows version put logs?

**Comment by 420Dope** [comment]
Same issue. Canˋt find any logs on windows.
