### ISSUE TITLE
ECONNRESET

### ISSUE THREAD

**Issue by NiackBuster** [nfarina/homebridge#444]
Hello !

May you have an idea about tis error I get all the time ((4-6 times a day) withou reason (i think) ?
![error](https://cloud.githubusercontent.com/assets/15909780/12011834/9d56dfea-acdf-11e5-8e87-cfbbe648e7d0.png)

thanks for help !

**Comment by KhaosT** [comment]
it looks like a plugin issue. The plugin developer didn't handle the case that tcp socket get closed during reading...

**Comment by NiackBuster** [comment]
Ok !
I Check with him! Thank you

Have à Nice evening !


Le dimanche 27 décembre 2015, Khaos Tian <notifications@github.com> a
écrit :
