### ISSUE TITLE
TypeError: Cannot read property 'username' of undefined

### ISSUE THREAD

**Issue by Xtropy74** [nfarina/homebridge#445]
I just upgraded homebridge on my Ubuntu server and now it will not start. The plugins register ok but something with the bridge username is crashing it.

Here are the logs:

*snip*
Registering platform 'homebridge-legacy-plugins.YamahaAVR'
Registering platform 'homebridge-legacy-plugins.ZWayServer'
---
Loaded plugin: homebridge-nest
Registering platform 'homebridge-nest.Nest'
---
Loaded plugin: homebridge-wemo
Registering accessory 'homebridge-wemo.WeMo'
---

/usr/local/lib/node_modules/homebridge/lib/server.js:129
  var username = config.bridge.username;
                              ^
TypeError: Cannot read property 'username' of undefined
    at Server._loadConfig (/usr/local/lib/node_modules/homebridge/lib/server.js:129:31)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:25:23)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:23:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)

**Comment by Xtropy74** [comment]
Of note, I am using SmartThings with homebridge. Looks like the recent commit for "checking for valid username" is the issue. If I roll back to the older server.js, everything works fine. In the JSON API being used for Smartthings via config.json, there is no "username" field, only platform, name, app_id and access_token

**Comment by rudders** [comment]
Perhaps sharing your config.json would assist in tracking don the problem.

**Comment by Xtropy74** [comment]
Sure thing, here it is:

{
    "description": "JSON API",
    "platforms": [
        {
            "platform": "SmartThings",
            "name": "SmartThings",
            "app_id": "590a32ce-69c2-40fc-a516-XXXXXXXXXXXXXXXXXXXX",
            "access_token": "74ac6a07-e63e-43f9-9ee4-XXXXXXXXXXXXXXXXX"
        },
        {
                "platform": "Nest",
                "name": "Nest",
                "username" : "xXXXXX@xxxxxxxxxx.com",
                "password" : "xxxxxxxxx"
        }
    ],
"accessories": [
    {
      "accessory": "LiftMaster",
      "name": "Garage Door",
      "username": "xXXXXX@xxxxxxxxxx.com",
      "password": "xxxxxxxxx"
    }
  ]
}

**Comment by rudders** [comment]
You seem to be missing the bridge section altogether. Here is the sample-config.jsom from Homebridge.

```javascript  
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    
    "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",

    "accessories": [
        {
            "accessory": "WeMo",
            "name": "Coffee Maker"
        }
    ],

    "platforms": [
        {
            "platform" : "PhilipsHue",
            "name" : "Hue"
        }
    ]
}```

**Comment by Xtropy74** [comment]
That fixed it, thanks rudders! Can't believe I was missing that....

**Comment by keerthivasangoplakrishnan** [comment]
while compilation there is no error but iam getting run time error give me suloution how to solve the issue. **TypeError:  http://localhost/projectdir/app/login.component.html:5:68 caused by: Cannot read property 'username' of undefined**

**Comment by ghazel** [comment]
Homebridge has default config values, but specifying a config.json makes it not use those values, resulting in this error. https://github.com/nfarina/homebridge/blob/84b4733ac75aba9e7c19d36be282cd8162077860/lib/server.js#L198
