### ISSUE TITLE
Homeridge stopped working

### ISSUE THREAD

**Issue by Slepperpon** [nfarina/homebridge#447]
Worked for weeks then stopped responding on raspberry says it's running deleted from iOS then tried re adding and will not show up when searching for homeridge.

**Comment by gl-lamhnguyen** [comment]
In config.json file, change name and mac address to something else. I usually add a number to the name and change last digit/char of the mac address:

        "name": "Homebridge2",
        "username": "CC:22:3D:E3:CE:33",

**Comment by Slepperpon** [comment]
Tried that did not work so after deleting homekit from all ios devices and still not working i rebooted Apple tv and then it was visible and is now working thanks for the fast response.

Date: Wed, 30 Dec 2015 09:23:32 -0800

**Comment by devbobo** [comment]
you need to run...
```
rm -rf /home/pi/.homebridge/persist
```
and then restart homebridge
