### ISSUE TITLE
Bonjour error

### ISSUE THREAD

**Issue by bazcurtis** [nfarina/homebridge#449]
Hi,

I am very new to this, but have managed to get Homebridge installed on a Debian v8 Fusion VM.

When I try and run it, I get the below. Is this something I have done wrong? Is this just a warning and it should work?

**\* WARNING **\* The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
**\* WARNING **\* Please fix your application to use the native API of Avahi!
**\* WARNING **\* For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs
**\* WARNING **\* The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
**\* WARNING **\* Please fix your application to use the native API of Avahi!
**\* WARNING **\* For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister

Thanks for writing Homebridge, I think it is going to be a lot of fun to use.

Best wishes

Michael

**Comment by rickysmartthings** [comment]
Did you figure this out? I'm seeing the same thing.

**Comment by rudders** [comment]
This is an expected error that can be safely ignored.

**Comment by rickysmartthings** [comment]
Interesting. My server is up and running and behavior is a little strange. Using the SmartThings plug-in, my z-wave devices are not working, but my Zigbee devices are working fine (server is a Raspberry Pi 2). When I ran the server from my Mac, everything worked just fine ...

**Comment by rudders** [comment]
Have you tried `homebridge -D` to get some debug output? Works fine on RPi - have you looked at the Wiki for RPi install assistance  https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi and/or come join our Slack team and check out the install_support channel https://homebridgeteam.slack.com/messages/install_support/

**Comment by rickysmartthings** [comment]
It's working now. I think it may have been an alpha/beta version of Node I was running. I backed up to 4.2.4. Thanks!

**Comment by rudders** [comment]
Homebridge README.md has been updated to help users on the future.

**Comment by mavis46** [comment]
@rickysmartthings how did you downgrade your node version. I am running 5.4.1 and would like to try and downgrade to see if things work?

**Comment by cflurin** [comment]
@mavis46: I'm running node v5.4.1 on a RPi 2, Jessie without any issues. Take a look on homebridge-punt > wiki > troubleshooting.

**Comment by IMNotMax** [comment]
Follow the URL, you'll find the versions you need.

```txt
Raspberry Pi 2 Model B 
wget https://nodejs.org/dist/latest-v5.x/node-v5.4.0-linux-armv7l.tar.gz 
tar -xvf node-v5.4.0-linux-armv7l.tar.gz 
cd node-v5.4.0-linux-armv7l

sudo cp -R * /usr/local/

node -v

```

**Comment by mavis46** [comment]
So this will install the latest working version of node automatically or do I need to specifically state the version I want?

I am going to start from scratch (again!!) only this time I am going to follow the wiki on installing homebridge in a Pi. Then instead of adding SmartThings (and the associated config) I will try a different plugin and see if I can get things working.

**Comment by msnelling** [comment]
I've just tried the following versions of Node from https://nodejs.org/dist/ to try and resolve this issue but with no luck.
7.1.0
6.9.1
5.12.0
4.6.2

**Comment by aarocka** [comment]
I too am having this issue. I can't run homebridge and also get this error #309. I am also running it in a docker container inside a hyper-v vm running ubuntu.

**Comment by David-Noble-at-work** [comment]
Is this issue a problem? I see some evidence on this thread that it is. Homebridge generates some warning messages just like--for example--cupsd. See https://ubuntuforums.org/showthread.php?t=862068. You'll see this which makes sense:

> cups, and other packages, are designed to be cross platform using the mDNSResolver library which is released as free software by Apple.

>Avahi, which is not cross platform but is better integrated with Gnome, has built a crude compatibility layer to allow mDNSResolver apps to work with it, but it's developers have decided to pressure applications using Apple's API by printing a warning to their user's logs.

>The proper fix is to remove the offending code from Avahi's warn.c in Ubuntu.

Hence--if this is in fact the case--this issue should be address by the Avahi maintainers.

So back to my central question: Is this issue a problem for homebridge or can it be safely ignored?

To this question I'll add: Is Ubuntu the OS to run if you're installing homebridge?

**Comment by cerniuk** [comment]
Suspect the Bonjour errors to be related to the RBPi HomeBridge being invisible to HomeKit when  auto-starting up.
