### ISSUE TITLE
Plugin request: MQTT plugin

### ISSUE THREAD

**Issue by Bart274** [nfarina/homebridge#453]
Hi,

Can someone please write an MQTT plugin for homebridge? Something like homekit2mqtt https://github.com/hobbyquaker/homekit2mqtt
Now I use the IFTTT plugin to send an event to my Maker Channel and that same Maker Channel sends an according request to my local MQTT broker, so I want to bypass the IFTTT part and send that request directly to my local MQTT broker.

Thanks in advance!

Bart

**Comment by bwired-nl** [comment]
+++

**Comment by ilcato** [comment]
Working on it. Stay tuned.

**Comment by Bart274** [comment]
Alright, thanks a lot! Really looking forward to it! :)

**Comment by desvdp** [comment]
Is this architecturally sound? Please correct me if I'm wrong but fundamentally Homekit is a M2M "protocol", so is MQTT. I understand you're looking for Homebridge2MQTT, but MQTT2HomeBridge is not that far away, right?

Currently I like the really clean approach of HomeBridge: please make sure this effort doesn't end up in yet another OpenHAP alike system. 
If we do need another OpenHAP (I'm not saying we don't ;-) ... as I'm not a big fan of Java anymore ), it might make more sense to create a system where the M2M protocols become plugins as well with access to all platform plugins, just because there will be other requests like this one (XMPP, (Web)Sockets, ... )

Not intended to be negative, just trying to generalise the GOOD idea of having other mechanisms to communicate with the devices... just because there's other stuff, not just iOS.

**Comment by ilcato** [comment]
It make sense for me: homebridge allows communication between HomeKit and other home automation system and other similar stuff (call it IoT and/or M2M). So if you have something managed through an MQTT broker it sounds useful for me to have it accessible through HomeKit and in particular through Siri (there's no other simpler way on the iOs platform to achieve this objective).

My main use case for having an MQTT plugin is to allow an MQTT client device to trigger an HomeKit Programmable Switch and from there an HomeKit scene. I will describe the scenario in a better way once implemented (I still have some architectural doubt in the end to end implementation).

**Comment by Bart274** [comment]
I want it because I use home-assistant.io and I have several mqtt switches, for turning services on my pc on or off and for other stuff as well.
I want to be able to control these switches without having to take my iphone or ipad, open home-assistant and flip a switch.
Now I use the IFTTT plugin to make the request, but if I can use mqtt directly it will shorten the response time a lot. :)
Also since it's an mqtt switch, the app I use for homebridge (mytouchhome) should also be able to read the current state of the switch so it would be updated if my switches were flipped in home-assistant by myself or because of my automated rules...

**Comment by tvillingett** [comment]
I have tried using the homekit2mqtt server for heating/thermostat service, and that works on its own.
Is there anyone that got it to work with more than one server on the same machine?
Although right now I cannot get it to run on the RPi, I would rather not have more than one instance of a homekit server on the same raspberry.
In short I would also like MQTT support for homebridge :)

**Comment by Bart274** [comment]
I have the same feeling, I already installed homebridge for my wemo switch, I don't want to install another server if it could be implemented in this one :)

**Comment by ilcato** [comment]
@Bart274, @tvillingett, how do you use MQTT "devices" ? Is the homekit2mqtt approach (the way in which the devices are define, config files, ...) right for you?

**Comment by Bart274** [comment]
I only have mqtt switches at this moment, so for me I only need to be able to configure the topic of the switch, the payload for the off and for the on state and whether or not the message should be retained.

**Comment by tvillingett** [comment]
I would like to have support for alarm and garageport, in addition to the ones used in config below.
But I would like to have support for comments (which is not standard in json), so you can easier comment a boilerplate reference config, and also  comment out the functions not used for a certain accessory (for example dimming or blocked garageport, if you don't have hardware for that, or while testing out partially functioning hardware).

For me a compact config file with easy to follow comments would be nice.
The plugin also needs to support callback so when mqtt arrives it updates directly in homekit, and not only when asked for new value. Because it seems like Elgato EVE can reload the status of the garage, but Insteon+ waits for an incoming Homekit change of the value.

```json
{
  "vp//Värmepump Rum": {
    "service": "Thermostat",
    "name": "Golvvärme",
    "topic": {
      "setTargetTemperature": "vp/set/rumstemp börvärde/SETPOINT",
      "statusTargetTemperature": "vp/status/rumstemp börvärde/SETPOINT",
      "statusCurrentTemperature": "vp/status/rumstemp ärvärde/TEMPERATURE"
    },
    "payload": {

    },
    "config": {
      "TemperatureDisplayUnits": 0
    },
    "manufacturer": "Comfortzone",
    "model": "CE50"
  },
  "vv//Värmepump VV": {
    "service": "Thermostat",
    "name": "Varmvatten",
    "topic": {
      "setTargetTemperature": "vv/set/vvtemp börvärde/SETPOINT",
      "statusTargetTemperature": "vv/status/vvtemp börvärde/SETPOINT",
      "statusCurrentTemperature": "vv/status/vvtemp ärvärde/TEMPERATURE"
    },
    "payload": {

    },
    "config": {
      "TemperatureDisplayUnits": 0
    },
    "manufacturer": "Comfortzone",
    "model": "CE50"
  }
    ,
    "mk//MK Ytterdörr": {
    "service" : "ContactSensor",
    "name" : "Ytterdörr",
    "topic": {
      "statusContactSensorState": "mk/status/Ytterdorr/STATUS"
    },
    "payload": {
        "onContactDetected" : "door closed"
    },
    "manufacturer": "Siemens",
    "model":        "MK 240"
  }
    ,
    "mk//MK Groventré": {
    "service" : "ContactSensor",
    "name" : "Groventré",
    "topic": {
      "statusContactSensorState": "mk/status/Groventré/STATUS"
    },
    "payload": {
        "onContactDetected" : "door closed"
    },
    "manufacturer": "Siemens",
    "model":        "MK 240"
  }
    ,
    "mk//MK Altan": {
    "service" : "ContactSensor",
    "name" : "Altan",
    "topic": {
      "statusContactSensorState": "mk/status/Altan/STATUS"
    },
    "payload": {
        "onContactDetected" : "door closed"
    },
    "manufacturer": "Siemens",
    "model":        "MK 240"
  }
}
```

**Comment by bwired-nl** [comment]
I now use the HTTP plugin which sends commands and status of my devices to a small nodejs HTTP server. This nodejs HTTP server sends commands and receives status of my devices via MQTT.
so i have the current status of my devices to send to the homebridge and I can execute commands from the homebdrige via Mqtt. So i think the mqtt Plugin should be able to send and receive....
The only thing i have to do is listen to the MQTT stream :-)

btw: i see a lot of people having troubles installing the homebridge on a rasp. I have installed it multiple times and working like a charm for many week now.. Im very happy with this.

**Comment by maddox** [comment]
> want it because I use home-assistant.io and I have several mqtt switches, for turning services on my pc on or off and for other stuff as well.

Why don't you use the Home Assistant platform directly in Homebridge? It bridges all of your lights, switches, media players, and scenes directly to HomeKit. By using this you don't have to do anything, all of your stuff from HA comes right over. This keeps all your config and logic in a single place (HA) and just exposes your accessories over to HomeKit allowing you to use Siri to control it.

More info here: https://github.com/nfarina/homebridge-legacy-plugins/blob/master/platforms/HomeAssistant.js

**Comment by Bart274** [comment]
I didn't knew that existed! Thanks for the tip! I'll try it! 😊

**Comment by maddox** [comment]
@Bart274 I've been needing to blog about it on http://home-assistant.io for ages :( my bad.

This is going to get me moving and finally do it!

**Comment by Bart274** [comment]
I will definitely read it and try it later this week! :)

**Comment by Bart274** [comment]
@maddox I just configured my homeassistant plugin, it has found my media players and switches :) Now I'll have to wait until I get home to see them in MyTouchHome. :)
When I add a new switch or when a new Media Players is added to HomeAssistant through discovery, will I have to restart Homebridge or will it add new accessoires on the fly?

**Comment by maddox** [comment]
> When I add a new switch or when a new Media Players is added to HomeAssistant through discovery, will I have to restart Homebridge or will it add new accessoires on the fly?

You will.

I need to add some kind of re-discoverablity function to it so it checks every minute or something. I've been out of the Homebridge game for a bit so I'm not sure if that's baked in for accessories or not. 

I'll look at what I can do since this annoys me as well :smile:

**Comment by Bart274** [comment]
Take your time :)
It seems I reactivated your interest for this project again? :p

Date: Wed, 6 Jan 2016 07:42:50 -0800

**Comment by ivory9334** [comment]
@ilcato
I use MQTT to trigger lights, door lock with nfc card reader, humidity/temp sensor, and shutters. soon, some electric plugs too. 
The protocole used to connect to the broker is websocket to update the webapp.
all of it is homemade.

have you any update ?

**Comment by ilcato** [comment]
Working on it. Low priority :-)

**Comment by ilcato** [comment]
@ivory9334 I just published a first draft of an HomeKit Switch accessory plugin that maps to MQTT broker topics. It works for me, try if it is right for you and send me feedbacks:

https://github.com/ilcato/homebridge-mqttswitch

**Comment by bwired-nl** [comment]
thank! will check

**Comment by ivory9334** [comment]
@Ilcato 
Thanks! I'll check that later. GG

**Comment by tvillingett** [comment]
I have tested it, and works fine! Good work! :sweat_smile:
I have both tested inputting changes from EVE (Elgato) and force-updating the state from node-red. It is no percepted delay at all when force updating the value, very nice.

Now we need to do the garage door opener, contact sensor, thermostat, thermometer and alarm :stuck_out_tongue_closed_eyes:
There is a clean implementation for the garage that could be used as a start here:
https://github.com/benlamonica/homebridge-rasppi-gpio-garagedoor.git
It should be changed for simpler implementation, since MQTT won't need polling.

**Comment by ivory9334** [comment]
@ilcato 
looks fine but I've some issues with my broker. https://www.github.com/mcollina/mosca only support node v0.12.
mqttswitch require node v4. 
is there any way to retro support node v0.12?
tks

**Comment by bwired-nl** [comment]
who has a fully filled working sample json?

**Comment by ilcato** [comment]
https://github.com/ilcato/homebridge-mqttswitch/blob/master/config.json
works after inserting right params...

**Comment by ilcato** [comment]
@ivory9334 you can fork the project and change in package.json the node param.

**Comment by bwired-nl** [comment]
who has a fully filled working sample config.json?
so not the example from the code, but filled with params

**Comment by ilcato** [comment]
Credentials removed...
{
    "bridge": {
        "name": "HomebridgeMAC",
        "username": "CC:22:3D:E3:CE:33",
        "port": 51826,
        "pin": "031-45-154"
    },
    "description": "This is an example configuration file. You can use this as a template for creating your own configuration file.",
    "platforms": [
    ],
    "accessories": [
        {
                        "accessory": "mqttswitch",
                        "name": "TestButton1",
                        "url": "wss://m20.cloudmqtt.com:32794/",
                        "username": "xxx",
                        "password": "xxx",
                        "caption": "Button1",
                        "topics": {
                                "statusGet":    "/ac/test/statusGet/Button1",
                                "statusSet":    "/ac/test/statusSet/Button1"
                        }
        }

    ]
}

**Comment by bwired-nl** [comment]
thanks, i have this now, but im not receiving any mqtt topics
Homebridge is starting OK with the plugin
any tips?

{
		"accessory": "mqttswitch",
		"name": "TestButton1",
		"url": "10.0.0.47:1883",
		"username": "",
		"password": "",
		"caption": "Button1",
		"topics": {
			"statusGet": "/Button1",
			"statusSet": "/Button1"
			}
		},

**Comment by ilcato** [comment]
put in url:
mqtt://10.0.0.47:1883

**Comment by bwired-nl** [comment]
mhhh strange, still nothing
I using mosquitto as mqtt server
this is what i see in homebridge when i control the button from the app
looks like the plugin is not reached, put in extra logging in the index.js

 EventedHTTPServer [10.0.0.103] HTTP request: /characteristics +24s
  HAPServer [CD:23:3D:E3:CE:01] HAP Request: PUT /characteristics +1ms
  Accessory [HomebridgeBwired] Processing characteristic set: {"characteristics":[{"aid":9,"iid":9,"value":true}]} +14ms
  Accessory [HomebridgeBwired] Setting Characteristic "On" to value true +1ms
  EventedHTTPServer [10.0.0.103] Muting event '9.9' notification for this connection since it originated here. +1ms
  EventedHTTPServer [10.0.0.103] HTTP Repsonse is finished +2ms

**Comment by tvillingett** [comment]
I made a first version of garageport opener for mqtt also:
https://github.com/tvillingett/homebridge-mqttgaragedoor.git

**Comment by cflurin** [comment]
Hi, recently I realised some stuff with node-red. node-red not only supports MQTT but also several intersting APIs. Yuo can connect homebridge with node-red via websocket. I've published a plugin for this purpose: [homebridge-websocket](https://github.com/cflurin/homebridge-websocket). Here you'll find an  example for MQTT: https://github.com/cflurin/collection

**Comment by TeraJaQ** [comment]
Any news?
I've got good result using HAP-nodeJS and pyton script...but i've see with homebridge there is more plug-in...or i'm lost anything?

**Comment by cflurin** [comment]
Hi,
I've published a new Plugin: [homebridge-mqtt](https://www.npmjs.com/package/homebridge-mqtt).
Your feedback is welcome > https://github.com/cflurin/homebridge-mqtt/issues

**Comment by johnypony3** [comment]
@cflurin looking over the [homebridge-mqtt](https://www.npmjs.com/package/homebridge-mqtt) plugin, this looks good! It's not quite clear what it does though 😄 . I was expecting for homebridge to emit actions to mqtt it doesnt do that. I then thought that it would listen to a mqtt topic but it doesnt seem to do be doing that either. What does it do?

**Comment by cflurin** [comment]
@johnypony3: 
Take a look at the wiki: https://github.com/cflurin/homebridge-mqtt/wiki

Please open an issue on https://github.com/cflurin/homebridge-mqtt if you don't understand the documentation. Your question may be also usefull for other homebridge-mqtt users.
