### ISSUE TITLE
SmartThings [Wanting to support Schlage Connect & Linear Garage Door Opener]

### ISSUE THREAD

**Issue by JStyleT** [nfarina/homebridge#454]
Hello,

I'm hoping someone could provide some insight or assistance into helping develop support for the Schlage Connect Lock and the Linear Garage Door Opener. 

I recently installed HomeBridge but it appears it only supports lights and switches at the moment, lacking support for doors locks, garage door openers and other accessories within SmartThings.

I also recently installed a new Schlage Sense Lock with excitement over convenience in the fact that you can manage users codes from an app, view access history as well as have direct integration with Homekit.  However with all that said I found that you lose a lot of functionality because it's no longer supporting z-wave (only bluetooth) and certain routines that would have normally say unlocked the door when arriving home or automatically locking the door after 5 minutes but only if it detects the door is shut using an open close sensor do not work (this can only be achieved with SmartThings as Homekit does not offer these options).

I really appreciate everyone's effort on this project and although it may only be working with the lights and switches as of now it's still really awesome..  :)

**Comment by jclarke0000** [comment]
Likely the state of the SmartThings plugin is the limitation here.  I have a wink  hub and I am able to control my Schlage Connect lock using HomeBridge with the HomeBridge-wink plugin.

Suggest posting a feature request to the dev for the SmartThings plugin.
