### ISSUE TITLE
Better plugin Error Handling

### ISSUE THREAD

**Issue by fahrvergnuugen** [nfarina/homebridge#455]
Plugins are great, but the large number of plugin authors results in different levels of code quality being loaded into the homebridge service. This is greatly affecting the reliability of the homebridge service because poor code in a plugin can result in the entire process crashing.

At least once every couple of days I have to restart my homebridge service because of an uncaught exception (often because of a re-used `callback`) or a "syntax error" because a webserver somewhere sent an unexpected result that a plugin didn't know how to handle.

I'm not a nodeJS expert, but I'm hoping there is some practical way to isolate the plugins or at least provide developers with a pattern they can follow for properly handling exceptions.

**Comment by KhaosT** [comment]
@nfarina it seems most of people encounters crashes from plugins, do you think it's necessary for homebridge to use ``process.on('uncaughtException')`` by default?

**Comment by nfarina** [comment]
I wonder if it's possible to run plugins in separate Node processes? Without changing the API of course. The process could start with a plugin-bootstrapping layer and the "API Object" could be modified to act as a proxy that communicates with the main homebridge process via some IPC channel.

Or we could handle uncaught exceptions... Just need to be sure that's not causing nasty issues like memory leaks. I seem to remember reading about how it's a bad idea...

**Comment by devbobo** [comment]
@fahrvergnuugen a workaround for this, would be to run Homebridge using forever, I know it's a bit of a bandaid, but it would solve the issue if you having to manually restart your homebridge service.

**Comment by sdecaux** [comment]
Yes, Homebridge should be able to put up with hanged plugins.
I have [an issue with Harmony plugin](https://github.com/KraigM/homebridge-harmonyhub/issues/4) that prevents homebridge from starting if harmony hub is shut down. The plugin never manages to initialize and it blocks all homebridge launch. There should be a timeout setting.
