### ISSUE TITLE
npm ERR! Failed at the ed25519@0.0.3 install script 'node-gyp rebuild' Mac 10.11.2

### ISSUE THREAD

**Issue by MoocowJay** [nfarina/homebridge#456]
I've tried and tried to fix this error with no success. Can anyone help? THANKS!

> bignum@0.11.0 install /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/srp/node_modules/bignum
> node-gyp configure build

gyp WARN EACCES user "root" does not have permission to access the dev dir "/Users/Jay/.node-gyp/4.2.4"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/srp/node_modules/bignum/.node-gyp"
  CXX(target) Release/obj.target/bignum/bignum.o
  SOLINK_MODULE(target) Release/bignum.node
npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "homebridge"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE

npm ERR! ed25519@0.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ed25519@0.0.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the ed25519 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls ed25519
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/lib/npm-debug.log

**Comment by AppleTechy** [comment]
try sudo install.....

**Comment by IMNotMax** [comment]
Did you install the libavahi-compat-libdnssd-dev package on Linux ?

https://github.com/nfarina/homebridge#installation

**Comment by AppleTechy** [comment]
issue #416
