### ISSUE TITLE
uses port: 54826 when paring, but configured for 54827

### ISSUE THREAD

**Issue by tvillingett** [nfarina/homebridge#458]
I changed the config.json to use 54827, since I'm already running one server already on the same machine, and that works ok, until I try to pair, and then i uses 54826 anyway:
It initialized and started running, but when I try to add accessory it stops:

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::54826
    at Object.exports._errnoException (util.js:837:11)
    at exports._exceptionWithHostPort (util.js:860:20)
    at Server._listen2 (net.js:1231:14)
    at listen (net.js:1267:10)
    at Server.listen (net.js:1363:5)
    at new EventedHTTPServerConnection (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:125:20)
    at EventedHTTPServer._onConnection (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:79:20)
    at emitOne (events.js:77:13)
    at Server.emit (events.js:169:7)
    at TCP.onconnection (net.js:1427:8)
```

Is this a bug, or is all pairing made with port 54826?

**Comment by tvillingett** [comment]
I made a workaround and setup so no server uses the 54826, so it can be free for any use of the pairing on the same machine for other Homekit instances.

**Comment by ni-hao-1** [comment]
Are you running two homebridge instances using different ports... Does that mean that you can only pair one device to a running homebridge. I want to use Siri on my iPad but also on my iPhone. Can you explain what and how you did it?

**Comment by tvillingett** [comment]
Yes, I was trying to use two servers on the same mahcine. I could not get it to run at the same time, but I'm not sure why. One was homebridge and the other homekit2mqtt, both of them was using the same lib form the HAP-NodeJS

**Comment by nriley** [comment]
I'm only running one copy (which is configured for port 51826) but it seems to be wanting to listen on another port which is in use.

```
02/07 22:28:40 events.js:141
02/07 22:28:40       throw er; // Unhandled 'error' event
02/07 22:28:40       ^
02/07 22:28:40 
02/07 22:28:40 Error: listen EADDRINUSE :::54829
02/07 22:28:40     at Object.exports._errnoException (util.js:870:11)
02/07 22:28:40     at exports._exceptionWithHostPort (util.js:893:20)
02/07 22:28:40     at Server._listen2 (net.js:1237:14)
02/07 22:28:40     at listen (net.js:1273:10)
02/07 22:28:40     at Server.listen (net.js:1369:5)
02/07 22:28:40     at new EventedHTTPServerConnection (/Users/nicholas/Documents/Development/homebridge/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:125:20)
02/07 22:28:40     at EventedHTTPServer._onConnection (/Users/nicholas/Documents/Development/homebridge/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:79:20)
02/07 22:28:40     at emitOne (events.js:77:13)
02/07 22:28:40     at Server.emit (events.js:169:7)
02/07 22:28:40     at TCP.onconnection (net.js:1433:8)
```

I'm pretty sure there is only one copy of homebridge or anything similar on my machine.  Same issue or any ideas?

**Comment by ni-hao-1** [comment]
Here running perfect now, but in your log I see it is trying to listen to 54829, which is already in use...

Verstuurd vanaf mijn iPad 4

**Comment by ni-hao-1** [comment]
Btw where is homebridge running, I mean what maxhine and which OS

Verstuurd vanaf mijn iPad 4

**Comment by snowdd1** [comment]
Might that be a plugin that tries to open that port?
Which plugins do you use?

**Comment by snowdd1** [comment]
Sorry, was confused.
A file search for 54826 shows that this is a default start port the internal HTTP server of hap-nodejs.
It's hard-coded in the `PortAllocator` and though it says [here](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/util/eventedhttp.js#L107) *grab the next open port* (which I think should be the next **free** port) it does not check whether this port is taken by any other process.

**Comment by nriley** [comment]
Thanks, that's helpful; that looks like a bad assumption.  I guess I should file a bug on hap-nodejs then.

**Comment by ni-hao-1** [comment]
As asked before, what system do ya have...
And do you also have a windows pc or mac so I can login and have a look at your homebridge files by using TeamViewer while you are watching. I do not like to be unattended i  someone else his/her system

Verstuurd vanaf mijn iPad 4

**Comment by nriley** [comment]
Thanks for the offer of help but I just changed the port number for now and homebridge is running reliably again.  Got some bigger fish to fry this weekend :-)

**Comment by ni-hao-1** [comment]
Great reading its working properly

Verstuurd vanaf mijn iPad 4
