### ISSUE TITLE
Problem Authenticating with Smartthings

### ISSUE THREAD

**Issue by timo55** [nfarina/homebridge#459]
Hi, similarly to issue listed as closed here: https://github.com/nfarina/homebridge/issues/17#issuecomment-168808027

The difference with the above issue is the underscores are in place in the app_id / access_token lines.
I'd appreciate any help here, no search online has found any other solution to try (I'm quite new to this!).
Using Raspbian on pi 2.
I have all set up and looks fine until the following:

Starting HomeBridge server...
Loading 1 platforms...
[SmartThings] Initializing SmartThings platform...
[SmartThings] Fetching SmartThings devices...
[SmartThings] There was a problem authenticating with SmartThings.

The app-id and token are correct.
Here is my config.json:

{
"bridge": {
"name": "Homebridge",
"username": "CC:22:3D:E3:CE:30",
"port": 51826,
"pin": "031-45-154"
},

```
"description": "JSON API",
"platforms": [{
        "platform": "SmartThings",
        "name": "SmartThings",
        "app_id": "xxxxxxx",
        "access_token": "xxxxxxx"
}]
```

}

Many thanks!

T

**Comment by herious1989** [comment]
Did you have this issue when RPi reboot? I also had this issue but only at boot. It starts fine when I run it manually after RPi finishes booting.

**Comment by timo55** [comment]
Hi, yes the problem still happens after reboot- I tried reinstalling from scratch after reboot as well, no joy - same problem persists...

**Comment by herious1989** [comment]
I'm interested in the fix as well, but did you try to install this? `homebridge-legacy-plugins`

`sudo npm install -g homebridge-legacy-plugins`

**Comment by timo55** [comment]
Hi, yes I’ve installed this - as far as I can tell it installed ok.

**Comment by mavis46** [comment]
Have you got 2 JSON APIs created in the SmartThings App?

**Comment by timo55** [comment]
I did have without realising but I have since deleted and still the same issue (prior to posting the issue)...

**Comment by raspman** [comment]
Having the same issues..it was working fine, but now, after a re-boot, I am getting this

**Comment by herious1989** [comment]
@raspman If you manually start it after the machine finishes the boot, is there any error?

**Comment by raspman** [comment]
Well, if I delete the Smart app, re-provision it by updated the new information to place in json.config, I can it to work if I keep tinkering with it (by typing homebridge) and running it.  If I try to get it to run in the background or reboot the pi, it seems to go back to having an authentication error.  Yesterday I had it working awesome (simulating a power outage by reseting the pi) and it went right back up, including the hap showing up via the "Discovery" app I used to make sure it is running properly....

**Comment by herious1989** [comment]
@raspman I think typing `homebridge` or start it in background manually (not automatically after boot) has the same effect and homebridge will run without error. But for me I only have issue when Pi reboots, if you can, try to hook up a monitor to the Pi and monitor when Pi reboots, see if any error comes up. For me I got this error https://github.com/nfarina/homebridge/issues/460 and it comes from homebridge. This is the reason why homebridge logs says authentication error

**Comment by raspman** [comment]
Interesting.  I have a headless set-up, so I'll wait a bit and see what happens.  Right now, I can't even get homebridge to run manually :)  I'm not sure if it has anything to do with Smartthings having some network issues right now our not..

**Comment by timo55** [comment]
Glad you're having a bit more success @raspman, I've still not got it to run once without the authentication error - have tried the above steps you mentioned (deleted smart app, re-installed it etc), rebooted the smart hub and pi, typed homebridge but same result - runs until auth :(

**Comment by raspman** [comment]
I can get it to run by typing homebridge, however, trying to run it again after reboot gives me an authentication error.  Also, I cannot figure out a way to run this in the background without keeping a terminal window open.  No idea what the problem is..

**Comment by raspman** [comment]
I think I might have figured out what the issue is on my end.  It seems, from trial and error, that homebridge loads without the authentication error as long as it is run via root (even on a reboot.)  Now, I just need to figure out how to get it to load via the root on boot up or a reboot...I can see there is an error message when I restart my pi saying "Failed to start.  See systemctl status homebridge.service"  I assume this is because I used a few methods to get it to auto load at boot up, but then deleted some files when it didn't work.

**Comment by herious1989** [comment]
@raspman I know the wiki for run homebridge on startup has a new method (systemctl), but I don't think that's the issue (at least in my case). You're right that homebridge won't start if you run it from different account in RPi (happened to me before). Let me know if you can make it start on reboot

**Comment by raspman** [comment]
Now I have to figure out how to program it (properly) to do that :). I need guidance.......obviously the way I had it set up it wasn't booting from root.

**Comment by raspman** [comment]
Btw, I'm getting an error on boot about abosystemctl homebridge. I'm sure that has to do with me removing part of the script or something?

**Comment by raspman** [comment]
Sorry, typo. An error regarding systemctl homebridge.

**Comment by pdlove** [comment]
It is still a couple of weeks out, but I am working on a refreshed and more complete smartthings plugin.

**Comment by realdannys** [comment]
@pdlove thats great news, any chance it'll poll for updates from SmartThings, its pretty useless when Homebridge won't keep in sync with changes SmartThings has made to switches.

**Comment by mavis46** [comment]
I have just done a clean install often having everything up and running (but a very messy install). I am now stuck with the authenticating message. I installed the latest version of node v5.4.1. Could this be the problem? And if so, how do I downgrade?

**Comment by AppleTechy** [comment]
Has the authentication problem been solved?

**Comment by raspman** [comment]
My resolution is run via the sudo command.  However, I cannot program my Raspberry Pi to reload 'homebridge' via sudo on boot-up.

**Comment by mavis46** [comment]
If I run homebridge just by typing the command 'homebridge' then I get the authenticating error. If I run 'sudo homebridge' then I get  an error saying config.json is not at /root/.homebridge/config.json.

**Comment by raspman** [comment]
Did you try moving config.json to /root/.homebridge/ ?

**Comment by herious1989** [comment]
For me it's vice versa, I got auth error if i run sudo homebridge. and no error if on homebridge

**Comment by mavis46** [comment]
Just tried and I get auth error with both root and normal user

**Comment by realdannys** [comment]
I had to roll back my entire install from TimeMachine to January 7th. Updates in HomeBridge appear to have broken it (and other things) 

Updating HomeBridge is something I avoid now, i've done it twice and its broken everything that was working perfectly - so if its working well for you, like mine is now and you don't need any new plugins or features I advise just leaving it and not updating until something stops working.

**Comment by mavis46** [comment]
I have solved the auth error. Second time around I forgot to amend the SmartThings.js file for the UK - see below. Hence why it worked on my first install but didn't work on the second as I followed  a different set of instructions.

Now we need to make some changes to the smartthings.js file for the UK/EU servers:
cd /usr/local/lib/node_modules/homebridge-legacy-plugins/platforms
nano SmartThings.js
Find the following URL in the file:
https://graph.api.smartthings.com
and replace it with:
https://graph-eu01-euwest1.api.smartthings.com
In my version of the file, there was only one instance of this. Ctrl-O and Enter to save the file,

**Comment by timo55** [comment]
Hi, unfortunately I already had the UK server address amended & auth error still occurs - glad it works for you now tho!

Tim

**Comment by raspman** [comment]
Unfortunately, I cannot (again) get it to authenticate, even when using the sudo command.  I am not sure, again, if this has anything to do with the recent ST updates?  I had a few devices that I had to re-provision.  When I did so, I lost homebridge access and went to re-start it.  Once I did that, I could not get it to authenticate again (re-installed the Smartapp, etc..)
