### ISSUE TITLE
UnRegister Accessory from Platform Plugin

### ISSUE THREAD

**Issue by pdlove** [nfarina/homebridge#461]
I'm working on the Wink Platform Plugin for homebridge and want to remove/unpublish accessories  that have lost their connection with the Wink Hub without restarting homebridge.
Does anyone know if there is currently a way to do this?

**Comment by AppleTechy** [comment]
Try talking to @devbobo If I am understanding what you are wanting to do he is doing something similar for the WeMo plugin he is working on.

**Comment by pdlove** [comment]
This is Discussion #237
