### ISSUE TITLE
Remote access over Internet (one more time)

### ISSUE THREAD

**Issue by toffimeister** [nfarina/homebridge#462]
Hi,

I am still having problems getting remote access to work via Apple TV. I am loggin into iCloud with the same account on iOS and Apple TV. Homebridge is working fine. I have looked at #412 as well as #256 and have tried multiple times to reset Homekit on iOS, logged out of iCloud on Apple TV (3rd generation) with tvOS 8.3 and rebooted, deleted homebridge persist directory, etc. 

Below is my homebridge log file output (I have deleted the caching messages from the devices). Is there any hint in what is going wrong?

In addition I tried to look at the log files of my Apple TV via Xcode, but I get an error message from Xcode that the tvOS version I am using is unsupported. i thought from the other issues #412 and #256 that this should be possible with 3rd generation ATV, but it seems that this is not the case (maybe anymore?). Can somebody confirm?

Any ideas/help?

  Accessory [Homebridge] Creating new AccessoryInfo for our HAP server +0ms
  Accessory [Homebridge] Creating new IdentifierCache +34ms
Homebridge is running on port 51826.
  EventedHTTPServer Server listening on port 51826 +100ms
  EventedHTTPServer [192.168.178.47] New connection from client +20s
  EventedHTTPServer [192.168.178.47] HTTP server listening on port 54826 +8ms
  EventedHTTPServer [192.168.178.47] HTTP request: /pair-setup +43ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-setup +3ms
  HAPServer [CC:22:3D:E3:CE:30] Pair step 1/5 +10ms
  EventedHTTPServer [192.168.178.47] HTTP Repsonse is finished +211ms
  EventedHTTPServer [192.168.178.47] HTTP request: /pair-setup +18s
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-setup +2ms
  HAPServer [CC:22:3D:E3:CE:30] Pair step 2/5 +6ms
  EventedHTTPServer [192.168.178.47] HTTP Repsonse is finished +203ms
  EventedHTTPServer [192.168.178.47] HTTP request: /pair-setup +34ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-setup +1ms
  HAPServer [CC:22:3D:E3:CE:30] Pair step 3/5 +3ms
  HAPServer [CC:22:3D:E3:CE:30] Pair step 4/5 +70ms
  HAPServer [CC:22:3D:E3:CE:30] Pair step 5/5 +7ms
  Accessory [Homebridge] Paired with client 3A...32 +17ms
  EventedHTTPServer [192.168.178.47] HTTP Repsonse is finished +28ms
  EventedHTTPServer [192.168.178.47] Client connection closed +89ms
  EventedHTTPServer [192.168.178.47] New connection from client +16ms
  EventedHTTPServer [192.168.178.47] HTTP server listening on port 54827 +2ms
  EventedHTTPServer [192.168.178.47] HTTP connection was closed +11ms
  EventedHTTPServer [192.168.178.47] HTTP server was closed +3ms
  EventedHTTPServer [192.168.178.47] HTTP request: /pair-verify +8ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +2ms
  HAPServer [CC:22:3D:E3:CE:30] Pair verify step 1/2 +5ms
  EventedHTTPServer [192.168.178.47] HTTP Repsonse is finished +27ms
  EventedHTTPServer [192.168.178.47] HTTP request: /pair-verify +23ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +1ms
  HAPServer [CC:22:3D:E3:CE:30] Pair verify step 2/2 +5ms
  HAPServer [CC:22:3D:E3:CE:30] Client 3A..32 verification complete +8ms
  EventedHTTPServer [192.168.178.47] HTTP Repsonse is finished +16ms
  EventedHTTPServer [192.168.178.47] HTTP request: /accessories +19ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: GET /accessories +1ms
  EventedHTTPServer [192.168.178.47] HTTP Repsonse is finished +29ms
  EventedHTTPServer [192.168.178.63] New connection from client +8m
  EventedHTTPServer [192.168.178.63] HTTP server listening on port 54826 +2ms
  EventedHTTPServer [192.168.178.63] HTTP request: /pair-verify +14ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +1ms
  HAPServer [CC:22:3D:E3:CE:30] Pair verify step 1/2 +2ms
  EventedHTTPServer [192.168.178.63] HTTP Repsonse is finished +32ms
  EventedHTTPServer [192.168.178.63] Client connection closed +24ms
  EventedHTTPServer [192.168.178.63] HTTP connection was closed +3ms
  EventedHTTPServer [192.168.178.63] HTTP server was closed +2ms
  EventedHTTPServer [192.168.178.47] Sending HTTP event 'keepalive' with data: {"characteristics":[]} +2m
  EventedHTTPServer [192.168.178.63] New connection from client +33s
  EventedHTTPServer [192.168.178.63] HTTP server listening on port 54826 +1ms
  EventedHTTPServer [192.168.178.63] HTTP request: /pair-verify +7ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +0ms
  HAPServer [CC:22:3D:E3:CE:30] Pair verify step 1/2 +7ms
  EventedHTTPServer [192.168.178.63] HTTP Repsonse is finished +29ms
  EventedHTTPServer [192.168.178.63] Client connection closed +23ms
  EventedHTTPServer [192.168.178.63] HTTP connection was closed +3ms
  EventedHTTPServer [192.168.178.63] HTTP server was closed +1ms
  EventedHTTPServer [192.168.178.63] New connection from client +54s
  EventedHTTPServer [192.168.178.63] HTTP server listening on port 54826 +2ms
  EventedHTTPServer [192.168.178.63] HTTP request: /pair-verify +6ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +1ms
  HAPServer [CC:22:3D:E3:CE:30] Pair verify step 1/2 +4ms
  EventedHTTPServer [192.168.178.63] HTTP Repsonse is finished +29ms
  EventedHTTPServer [192.168.178.63] Client connection closed +22ms
  EventedHTTPServer [192.168.178.63] HTTP connection was closed +6ms
  EventedHTTPServer [192.168.178.63] HTTP server was closed +1ms
  EventedHTTPServer [192.168.178.63] New connection from client +2m
  EventedHTTPServer [192.168.178.63] HTTP server listening on port 54826 +2ms
  EventedHTTPServer [192.168.178.63] HTTP request: /pair-verify +5ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +2ms
  HAPServer [CC:22:3D:E3:CE:30] Pair verify step 1/2 +2ms
  EventedHTTPServer [192.168.178.63] HTTP Repsonse is finished +28ms
  EventedHTTPServer [192.168.178.63] Client connection closed +25ms
  EventedHTTPServer [192.168.178.63] HTTP connection was closed +3ms
  EventedHTTPServer [192.168.178.63] HTTP server was closed +1ms
  EventedHTTPServer [192.168.178.47] Sending HTTP event 'keepalive' with data: {"characteristics":[]} +6m
  EventedHTTPServer [192.168.178.63] New connection from client +1m
  EventedHTTPServer [192.168.178.63] HTTP server listening on port 54826 +1ms
  EventedHTTPServer [192.168.178.63] HTTP request: /pair-verify +8ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +1ms
  HAPServer [CC:22:3D:E3:CE:30] Pair verify step 1/2 +2ms
  EventedHTTPServer [192.168.178.63] HTTP Repsonse is finished +30ms
  EventedHTTPServer [192.168.178.63] Client connection closed +28ms
  EventedHTTPServer [192.168.178.63] HTTP connection was closed +3ms
  EventedHTTPServer [192.168.178.63] HTTP server was closed +3ms
  EventedHTTPServer [192.168.178.63] New connection from client +47s
  EventedHTTPServer [192.168.178.63] HTTP server listening on port 54826 +5ms
  EventedHTTPServer [192.168.178.63] HTTP request: /pair-verify +8ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +1ms
  HAPServer [CC:22:3D:E3:CE:30] Pair verify step 1/2 +2ms
  EventedHTTPServer [192.168.178.63] HTTP Repsonse is finished +32ms
  EventedHTTPServer [192.168.178.63] Client connection closed +17ms
  EventedHTTPServer [192.168.178.63] HTTP connection was closed +2ms
  EventedHTTPServer [192.168.178.63] HTTP server was closed +1ms
  EventedHTTPServer [192.168.178.63] New connection from client +41s
  EventedHTTPServer [192.168.178.63] HTTP server listening on port 54826 +2ms
  EventedHTTPServer [192.168.178.63] HTTP request: /pair-verify +6ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +5ms
  HAPServer [CC:22:3D:E3:CE:30] Pair verify step 1/2 +2ms
  EventedHTTPServer [192.168.178.63] HTTP Repsonse is finished +30ms
  EventedHTTPServer [192.168.178.63] Client connection closed +18ms
  EventedHTTPServer [192.168.178.63] HTTP connection was closed +2ms
  EventedHTTPServer [192.168.178.63] HTTP server was closed +1ms
  EventedHTTPServer [192.168.178.63] New connection from client +4m
  EventedHTTPServer [192.168.178.63] HTTP server listening on port 54826 +3ms
  EventedHTTPServer [192.168.178.63] HTTP request: /pair-verify +16ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +3ms
  HAPServer [CC:22:3D:E3:CE:30] Pair verify step 1/2 +3ms
  EventedHTTPServer [192.168.178.63] HTTP Repsonse is finished +30ms
  EventedHTTPServer [192.168.178.63] Client connection closed +137ms
  EventedHTTPServer [192.168.178.63] HTTP connection was closed +2ms
  EventedHTTPServer [192.168.178.63] HTTP server was closed +1ms
  EventedHTTPServer [192.168.178.63] New connection from client +3m
  EventedHTTPServer [192.168.178.63] HTTP server listening on port 54826 +1ms
  EventedHTTPServer [192.168.178.63] HTTP request: /pair-verify +13ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +1ms
  HAPServer [CC:22:3D:E3:CE:30] Pair verify step 1/2 +3ms
  EventedHTTPServer [192.168.178.63] HTTP Repsonse is finished +30ms
  EventedHTTPServer [192.168.178.63] Client connection closed +19ms
  EventedHTTPServer [192.168.178.63] HTTP connection was closed +2ms
  EventedHTTPServer [192.168.178.63] HTTP server was closed +2ms
  EventedHTTPServer [192.168.178.47] Sending HTTP event 'keepalive' with data: {"characteristics":[]} +42s
  EventedHTTPServer [192.168.178.63] New connection from client +10m
  EventedHTTPServer [192.168.178.63] HTTP server listening on port 54826 +1ms
  EventedHTTPServer [192.168.178.63] HTTP request: /pair-verify +6ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +1ms
  HAPServer [CC:22:3D:E3:CE:30] Pair verify step 1/2 +5ms
  EventedHTTPServer [192.168.178.63] HTTP Repsonse is finished +30ms
  EventedHTTPServer [192.168.178.63] Client connection closed +29ms
  EventedHTTPServer [192.168.178.63] HTTP connection was closed +3ms
  EventedHTTPServer [192.168.178.63] HTTP server was closed +1ms
  EventedHTTPServer [192.168.178.47] Sending HTTP event 'keepalive' with data: {"characteristics":[]} +24s
  EventedHTTPServer [192.168.178.63] New connection from client +2m
  EventedHTTPServer [192.168.178.63] HTTP server listening on port 54826 +23ms
  EventedHTTPServer [192.168.178.63] HTTP request: /pair-verify +8ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +1ms
  HAPServer [CC:22:3D:E3:CE:30] Pair verify step 1/2 +2ms
  EventedHTTPServer [192.168.178.63] HTTP Repsonse is finished +25ms
  EventedHTTPServer [192.168.178.63] Client connection closed +14ms
  EventedHTTPServer [192.168.178.63] HTTP connection was closed +2ms
  EventedHTTPServer [192.168.178.63] HTTP server was closed +0ms
  EventedHTTPServer [192.168.178.63] New connection from client +2m
  EventedHTTPServer [192.168.178.63] HTTP server listening on port 54826 +2ms
  EventedHTTPServer [192.168.178.63] HTTP request: /pair-verify +7ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +1ms
  HAPServer [CC:22:3D:E3:CE:30] Pair verify step 1/2 +2ms
  EventedHTTPServer [192.168.178.63] HTTP Repsonse is finished +32ms
  EventedHTTPServer [192.168.178.63] Client connection closed +62ms
  EventedHTTPServer [192.168.178.63] HTTP connection was closed +5ms
  EventedHTTPServer [192.168.178.63] HTTP server was closed +2ms
  EventedHTTPServer [192.168.178.47] Sending HTTP event 'keepalive' with data: {"characteristics":[]} +6m
  EventedHTTPServer [192.168.178.63] New connection from client +3m
  EventedHTTPServer [192.168.178.63] HTTP server listening on port 54826 +1ms
  EventedHTTPServer [192.168.178.63] HTTP request: /pair-verify +6ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +1ms
  HAPServer [CC:22:3D:E3:CE:30] Pair verify step 1/2 +3ms
  EventedHTTPServer [192.168.178.63] HTTP Repsonse is finished +53ms
  EventedHTTPServer [192.168.178.63] Client connection closed +20ms
  EventedHTTPServer [192.168.178.63] HTTP connection was closed +9ms
  EventedHTTPServer [192.168.178.63] HTTP server was closed +1ms
  EventedHTTPServer [192.168.178.63] New connection from client +10s
  EventedHTTPServer [192.168.178.63] HTTP server listening on port 54826 +1ms
  EventedHTTPServer [192.168.178.63] HTTP request: /pair-verify +5ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +1ms
  HAPServer [CC:22:3D:E3:CE:30] Pair verify step 1/2 +1ms
  EventedHTTPServer [192.168.178.63] HTTP Repsonse is finished +21ms
  EventedHTTPServer [192.168.178.63] Client connection closed +12ms
  EventedHTTPServer [192.168.178.63] HTTP connection was closed +1ms
  EventedHTTPServer [192.168.178.63] HTTP server was closed +1ms
  EventedHTTPServer [192.168.178.63] New connection from client +3m
  EventedHTTPServer [192.168.178.63] HTTP server listening on port 54826 +1ms
  EventedHTTPServer [192.168.178.63] HTTP request: /pair-verify +5ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +1ms
  HAPServer [CC:22:3D:E3:CE:30] Pair verify step 1/2 +2ms
  EventedHTTPServer [192.168.178.63] HTTP Repsonse is finished +29ms
  EventedHTTPServer [192.168.178.63] Client connection closed +16ms
  EventedHTTPServer [192.168.178.63] HTTP connection was closed +2ms
  EventedHTTPServer [192.168.178.63] HTTP server was closed +2ms
  EventedHTTPServer [192.168.178.47] Sending HTTP event 'keepalive' with data: {"characteristics":[]} +4m
  EventedHTTPServer [192.168.178.63] New connection from client +7m
  EventedHTTPServer [192.168.178.63] HTTP server listening on port 54826 +1ms
  EventedHTTPServer [192.168.178.63] HTTP request: /pair-verify +7ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +1ms
  HAPServer [CC:22:3D:E3:CE:30] Pair verify step 1/2 +2ms
  EventedHTTPServer [192.168.178.63] HTTP Repsonse is finished +29ms
  EventedHTTPServer [192.168.178.63] Client connection closed +23ms
  EventedHTTPServer [192.168.178.63] HTTP connection was closed +2ms
  EventedHTTPServer [192.168.178.63] HTTP server was closed +1ms
  EventedHTTPServer [192.168.178.63] New connection from client +31s
  EventedHTTPServer [192.168.178.63] HTTP server listening on port 54826 +4ms
  EventedHTTPServer [192.168.178.63] HTTP request: /pair-verify +6ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +1ms
  HAPServer [CC:22:3D:E3:CE:30] Pair verify step 1/2 +2ms
  EventedHTTPServer [192.168.178.63] HTTP Repsonse is finished +43ms
  EventedHTTPServer [192.168.178.63] Client connection closed +57ms
  EventedHTTPServer [192.168.178.63] HTTP connection was closed +2ms
  EventedHTTPServer [192.168.178.63] HTTP server was closed +0ms
  2016-01-06 20:35:47 caching: HM_308EBA_Clima-measured-temp: 20.9 as number
  EventedHTTPServer [192.168.178.47] Sending HTTP event 'keepalive' with data: {"characteristics":[]} +3m
  EventedHTTPServer [192.168.178.63] New connection from client +39s
  EventedHTTPServer [192.168.178.63] HTTP server listening on port 54826 +2ms
  EventedHTTPServer [192.168.178.63] HTTP request: /pair-verify +4ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +1ms
  HAPServer [CC:22:3D:E3:CE:30] Pair verify step 1/2 +2ms
  EventedHTTPServer [192.168.178.63] HTTP Repsonse is finished +19ms
  EventedHTTPServer [192.168.178.63] Client connection closed +28ms
  EventedHTTPServer [192.168.178.63] HTTP connection was closed +2ms
  EventedHTTPServer [192.168.178.63] HTTP server was closed +1ms
  EventedHTTPServer [192.168.178.63] New connection from client +6m
  EventedHTTPServer [192.168.178.63] HTTP server listening on port 54826 +2ms
  EventedHTTPServer [192.168.178.63] HTTP request: /pair-verify +11ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +1ms
  HAPServer [CC:22:3D:E3:CE:30] Pair verify step 1/2 +2ms
  EventedHTTPServer [192.168.178.63] HTTP Repsonse is finished +29ms
  EventedHTTPServer [192.168.178.63] Client connection closed +16ms
  EventedHTTPServer [192.168.178.63] HTTP connection was closed +2ms
  EventedHTTPServer [192.168.178.63] HTTP server was closed +1ms
  EventedHTTPServer [192.168.178.63] New connection from client +41s
  EventedHTTPServer [192.168.178.63] HTTP server listening on port 54826 +2ms
  EventedHTTPServer [192.168.178.63] HTTP request: /pair-verify +6ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +1ms
  HAPServer [CC:22:3D:E3:CE:30] Pair verify step 1/2 +2ms
  EventedHTTPServer [192.168.178.63] HTTP Repsonse is finished +33ms
  EventedHTTPServer [192.168.178.63] Client connection closed +31ms
  EventedHTTPServer [192.168.178.63] HTTP connection was closed +2ms
  EventedHTTPServer [192.168.178.63] HTTP server was closed +1ms
  EventedHTTPServer [192.168.178.63] New connection from client +2m
  EventedHTTPServer [192.168.178.63] HTTP server listening on port 54826 +2ms
  EventedHTTPServer [192.168.178.63] HTTP request: /pair-verify +6ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +1ms
  HAPServer [CC:22:3D:E3:CE:30] Pair verify step 1/2 +1ms
  EventedHTTPServer [192.168.178.63] HTTP Repsonse is finished +30ms
  EventedHTTPServer [192.168.178.63] Client connection closed +18ms
  EventedHTTPServer [192.168.178.63] HTTP connection was closed +3ms
  EventedHTTPServer [192.168.178.63] HTTP server was closed +1ms
  EventedHTTPServer [192.168.178.47] Sending HTTP event 'keepalive' with data: {"characteristics":[]} +4s
  EventedHTTPServer [192.168.178.63] New connection from client +12s
  EventedHTTPServer [192.168.178.63] HTTP server listening on port 54826 +1ms
  EventedHTTPServer [192.168.178.63] HTTP request: /pair-verify +6ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +1ms
  HAPServer [CC:22:3D:E3:CE:30] Pair verify step 1/2 +2ms
  EventedHTTPServer [192.168.178.63] HTTP Repsonse is finished +29ms
  EventedHTTPServer [192.168.178.63] Client connection closed +15ms
  EventedHTTPServer [192.168.178.63] HTTP connection was closed +7ms
  EventedHTTPServer [192.168.178.63] HTTP server was closed +1ms

**Comment by KhaosT** [comment]
@toffimeister what's your Apple TV's IP Address? is it 192.168.178.63?

**Comment by toffimeister** [comment]
AppleTV is 192.168.178.58, the 192.168.178.63 belongs to my wife's iPhone, with who I shared an older Homekit library before I did the remote access testing.

**Comment by KhaosT** [comment]
@toffimeister alright... based on the log, it seems iOS didn't even try to setup remote access with accessory (no /pairings) for Apple TV. This is normally happened when Apple TV failed to register Identity Service. If your iCloud account has 2-step verification enabled, you may want to try turning it off and repeat the process again. If not, there is no reliable workaround and Apple TV 4 (with tvOS 9.0 or later) might be the only solution.

**Comment by toffimeister** [comment]
I do have 2-step verification enabled. Will turn it off and try again and report.

**Comment by toffimeister** [comment]
Thank You! Turning off 2-step verification did the trick. Just for completeness, here is the log after I turned off 2-step verification:

192.168.178.47 is my iPhone with Homekit pairing
192.168.178.63 is my wife's iPhone (Homekit shared to)
192.168.178.58 is my AppleTV

  Accessory [Homebridge] Creating new AccessoryInfo for our HAP server +0ms
  Accessory [Homebridge] Creating new IdentifierCache +37ms
Homebridge is running on port 51826.
  EventedHTTPServer Server listening on port 51826 +100ms
  EventedHTTPServer [192.168.178.47] New connection from client +6m
  EventedHTTPServer [192.168.178.47] HTTP server listening on port 54826 +9ms
  EventedHTTPServer [192.168.178.47] HTTP request: /pair-setup +7s
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-setup +2ms
  HAPServer [CC:22:3D:E3:CE:30] Pair step 1/5 +8ms
  EventedHTTPServer [192.168.178.47] HTTP Repsonse is finished +250ms
  EventedHTTPServer [192.168.178.47] HTTP request: /pair-setup +14s
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-setup +1ms
  HAPServer [CC:22:3D:E3:CE:30] Pair step 2/5 +5ms
  EventedHTTPServer [192.168.178.47] HTTP Repsonse is finished +204ms
  EventedHTTPServer [192.168.178.47] HTTP request: /pair-setup +58ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-setup +1ms
  HAPServer [CC:22:3D:E3:CE:30] Pair step 3/5 +3ms
  HAPServer [CC:22:3D:E3:CE:30] Pair step 4/5 +43ms
  HAPServer [CC:22:3D:E3:CE:30] Pair step 5/5 +7ms
  Accessory [Homebridge] Paired with client DA..C9 +15ms
  EventedHTTPServer [192.168.178.47] HTTP Repsonse is finished +23ms
  EventedHTTPServer [192.168.178.47] Client connection closed +125ms
  EventedHTTPServer [192.168.178.47] HTTP connection was closed +8ms
  EventedHTTPServer [192.168.178.47] HTTP server was closed +3ms
  EventedHTTPServer [192.168.178.47] New connection from client +970ms
  EventedHTTPServer [192.168.178.47] HTTP server listening on port 54826 +3ms
  EventedHTTPServer [192.168.178.47] HTTP request: /pair-verify +15ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +2ms
  HAPServer [CC:22:3D:E3:CE:30] Pair verify step 1/2 +6ms
  EventedHTTPServer [192.168.178.47] HTTP Repsonse is finished +47ms
  EventedHTTPServer [192.168.178.63] New connection from client +15ms
  EventedHTTPServer [192.168.178.63] HTTP server listening on port 54827 +2ms
  EventedHTTPServer [192.168.178.63] HTTP request: /pair-verify +10ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +1ms
  HAPServer [CC:22:3D:E3:CE:30] Pair verify step 1/2 +2ms
  EventedHTTPServer [192.168.178.63] HTTP Repsonse is finished +25ms
  EventedHTTPServer [192.168.178.47] HTTP request: /pair-verify +10ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +1ms
  HAPServer [CC:22:3D:E3:CE:30] Pair verify step 2/2 +4ms
  HAPServer [CC:22:3D:E3:CE:30] Client DA..C9 verification complete +14ms
  EventedHTTPServer [192.168.178.47] HTTP Repsonse is finished +4ms
  EventedHTTPServer [192.168.178.63] Client connection closed +8ms
  EventedHTTPServer [192.168.178.63] HTTP connection was closed +2ms
  EventedHTTPServer [192.168.178.63] HTTP server was closed +1ms
  EventedHTTPServer [192.168.178.47] HTTP request: /accessories +8ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: GET /accessories +1ms
  EventedHTTPServer [192.168.178.47] HTTP Repsonse is finished +25ms
  EventedHTTPServer [192.168.178.47] HTTP request: /pairings +3s
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pairings +1ms
  HAPServer [CC:22:3D:E3:CE:30] Adding pairing info for client +5ms
  Accessory [Homebridge] Paired with client 56..8F +4ms
  EventedHTTPServer [192.168.178.47] HTTP Repsonse is finished +19ms
  EventedHTTPServer [192.168.178.58] New connection from client +13s
  EventedHTTPServer [192.168.178.58] HTTP server listening on port 54827 +1ms
  EventedHTTPServer [192.168.178.58] HTTP request: /pair-verify +7ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +1ms
  HAPServer [CC:22:3D:E3:CE:30] Pair verify step 1/2 +2ms
  EventedHTTPServer [192.168.178.58] HTTP Repsonse is finished +28ms
  EventedHTTPServer [192.168.178.58] HTTP request: /pair-verify +46ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +0ms
  HAPServer [CC:22:3D:E3:CE:30] Pair verify step 2/2 +3ms
  HAPServer [CC:22:3D:E3:CE:30] Client 56..8F verification complete +7ms
  EventedHTTPServer [192.168.178.58] HTTP Repsonse is finished +4ms
  EventedHTTPServer [192.168.178.58] HTTP request: /accessories +14ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: GET /accessories +1ms
  EventedHTTPServer [192.168.178.58] HTTP Repsonse is finished +22ms

**Comment by KhaosT** [comment]
Nice to know. In the cellular network, it may takes a while for iOS to setup the remote session so if it doesn't work, maybe just wait a while and try again.

**Comment by toffimeister** [comment]
It actually works quite reliably already...
