### ISSUE TITLE
Issues with homebridge in Raspberry Pi.

### ISSUE THREAD

**Issue by kaszito** [nfarina/homebridge#463]
Hi, I'm having some issues with homebridge installed in RPI. 
I have installed homebridge in Raspberry PI 2 model B with this configuration:

pi@raspi ~ $ uname -a
Linux raspi 4.1.13-v7+ #826 SMP PREEMPT Fri Nov 13 20:19:03 GMT 2015 armv7l GNU/Linux
pi@raspi ~ $ node -v
v5.3.0
pi@raspi ~ $ npm -v
2.14.7

First issue is related to accessories. I have all my accessories duplicated in Eve app.
Sometimes one of the duplicated accessory works fine, other is inaccessible.

Another issue I am having is that often my accessories are not available. 

I tried deactivating keychain from my iPhone 6S  icloud account, deleting files from /home/pi/.homebridge/persist/, deleting homebridge from Eve app, but always issues come back.
I also tried changing my homebridge username.

Could someone help me with this issues? 

Thanks in advance!

**Comment by matthijs2704** [comment]
Could you check your `config.json`. I think that's where the issue is. Could you post the file?

**Comment by kaszito** [comment]
Thanks so much matthijs2704. 

Made a new config.json more lighter, with only 3 accessories and seems to be working like a charm!
I'm going to add new accessories one by one and testing before add the next.

Regards!

**Comment by jnovack** [comment]
If you change the device name or type in the config.json you could possible get a duplicate (and/or old) device in your application.
