### ISSUE TITLE
Unable to access Homebridge 

### ISSUE THREAD

**Issue by kohlsalem** [nfarina/homebridge#464]
Hi, 

I freshly installed HB on a Raspberry2B, 
* Either on Raspbian or OSMC
* Either via WLAN or Cable
* Either on Node 4.0.0 or 4.2.4 or latest
* Either with homebridge-milight or homebridge-fakebulb
* Using gcc version 4.9.2 and latest IOS on Ipad 3

i changed
* username
* pin

left ports etc standard.

I resetted homekit several times, ensured keychain and drive is enabled (it always was) but i ALWAYS get the same behaviour:

After configuring "Home" on the Ipad on Eve or MyTouchHome i always can see the Homebridge, it takes a couple of seconds, than i can scan the pin - and fall immediately back on the screen showing the homebridge.

After hours of google and tryouts i loose a bit ideas. 

Since i was trying to keep setup as standard as possible, i really do not know how to proceed. 

Any Idea what the issue could be?

Best
Michael

**Comment by rudders** [comment]
have you tried manually entering the PIN?
![1447643544_thumb](https://cloud.githubusercontent.com/assets/104969/12231992/a4f855a4-b8af-11e5-8f90-3057b080d884.png)

**Comment by kohlsalem** [comment]
Dear Rudders, 

i move 100 karma points to your life account!

T H A N K S

Indeed i tried 100 different things, but always scanned with the iPad cam from the macbook monitor.

I never guessed that after the beep something went wrong.

Best
Michael

**Comment by rudders** [comment]
Thanks dude - glad it got you going! Remember being stumped on that one myself for a bit!
