### ISSUE TITLE
Persist accessory internal value

### ISSUE THREAD

**Issue by KameHouseGit** [nfarina/homebridge#466]
Hi all!

I'm trying to simulate the state of a device type one-way.
For example, a one-way light X10 device, you may set a brightness value, but you can not ask what their brightness value. I'm trying to simulate this.

When I tell Siri to adjust the light to 50% I want to keep the value '50' in a variable accessory, so that when asked by value, Homebridge answer '50'.

The initial value of the variable is 0.
Adjust the brightness to 50, but when asked what the value Siri, she answers 0.

Can I save the value of the variable somewhere? Does the accessory object disappears from memory and Homebridge created whenever you need it?

Thanks for everything
Greetings!

**Comment by nfarina** [comment]
The "value" of a characteristic like Brightness is stored inside the Characteristic instance inside the Service you construct in `getServices()`. If you don't listen for the `get` event yourself, Homebridge will automatically cache the last value that was set by the user (or by you calling `setValue`) and should return that to Siri when she asks.

**Comment by KameHouseGit** [comment]
Hello again!
Thank you very much for the help. I've made good progress. But even I have two questions:

The first: 
When I stop listening to the event GET, like you said, if I adjust the brightness to 50% and then ask Siri, she responds 50%. Well!
If I ask Siri about power status, she responds ON. Well!
But if I adjust the brightness to 0% and then ask Siri about state power, she continues to respond me ON.
Brightness "0%" should save the state power OFF? and brightness higher than 0% should save power status ON?

The second:
The problem I have now in the blinds.
If I stop listening to the event GET to the characteristic "CurrentPosition" and ask Siri, she answers me not find the devices.
I guess it's because "CurrentPosition" only has the GET event.
Blinds receive requests through the ON event of the characteristic "TargetPosition". But if I ask Siri she responds through "CurrentPosition".
Is there any way to get the value that comes from "SET TargerPosition" is stored in "CurrentPosition" and it work without removing the GET event?

Many many thank you very much for everything!
