### ISSUE TITLE
No pairing with homebridge

### ISSUE THREAD

**Issue by ni-hao-1** [nfarina/homebridge#468]
Running Homebridge (0.2.15) at Ubuntu server (14.04.3 LTS). Homebridge starts but MyTouchHome and Eve app do not pair with homebridge. Using Philips Hue as accessoire. I see Homebridge connects with the bridge, because it initializes the PhilipsHue Platform Plugin Version (0.0.2) and fetches all my Philips Hue Lights (more than 10). I did reset the homekit config at iPad, changed the username in the bridge part of config.json, also changed the bridge name. But nothing helps. Installed versions:

 npm version
{ npm: '3.3.12',
  ares: '1.10.1-DEV',
  http_parser: '2.6.0',
  icu: '56.1',
  modules: '47',
  node: '5.3.0',
  openssl: '1.0.2e',
  uv: '1.8.0',
  v8: '4.6.85.31',
  zlib: '1.2.8' }

Finally I deleted both apps at my iPad, reboot and installed again. Unfortunately.
Strange is that I never has been asked to enter the code for pairing. What to do?

**Comment by rudders** [comment]
What do you specifically mean by this statement *Homebridge starts but MyTouchHome and Eve app do not pair with homebridge* - Can you see the Homebridge Accessory? When you enter in the ID what happens?

**Comment by ni-hao-1** [comment]
When I start homebridge at my ubuntu server everything seems to be ok. At the end I see the pin used for pairing and the port. Hiwever when I start one of the apps at my iPad. It does not ask me for the pin so they do not pair

**Comment by rudders** [comment]
So you try to "add and accessory" under a home and can't see Homebridge?

**Comment by ni-hao-1** [comment]
As written before in the apps I am not asked to enter the pin so It does nit find anything, no accessoires

**Comment by rudders** [comment]
Have you walked through this process?
http://www.insteon.com/support-knowledgebase/2015/5/4/adding-a-homekit-compatible-device

**Comment by ni-hao-1** [comment]
Yes but no pin question

**Comment by rudders** [comment]
It doesn't ask you to scan a pin after you select your Homebridge?? That's odd? You can select your Homebridge can't you?

**Comment by ni-hao-1** [comment]
No I cann't

**Comment by ni-hao-1** [comment]
No I can't

**Comment by rudders** [comment]
Can you try Bonjour Browser on a mac and see if the hap service is visible?
<img width="472" alt="bonjour_browser" src="https://cloud.githubusercontent.com/assets/104969/12364175/515768fc-bc21-11e5-9cf8-b27f01248623.png">

**Comment by tonesto7** [comment]
Is anyone else having issues pairing on an iOS 9.3 beta1 device?  I can see the 'HAP' under bonjour browser

**Comment by pdlove** [comment]
On my 9.3 beta 1 phone, it pairs just fine but only the hub accessory is passed to Homekit.
I'm going to start investigating tonight unless someone figures it out before then.

**Comment by KhaosT** [comment]
@pdlove in iOS 9.3, HomeKit handles bridged accessory differently. When one or more bridged accessories are out of compliance (normally because the value is invalid), it just discard the accessory that has problem, but the bridge will be there.

**Comment by pdlove** [comment]
Thanks. I'll take a look and see what's wrong with it. Thanks for the info.

**Comment by pdlove** [comment]
Thank you. I got mine sorted out. No problems with 9.3 beta now.
It looks like there is a new mandatory Characteristic on BridgingState which I was testing on one device in my library. It's a new Characteristic as well that wasn't in the file.
There may be other Services I'm not using with mandatory Characteristics. 
Will there be a process that can be used to update HomeKitTypes.js in HAP-NodeJS when the time comes? I would assume Apple has it backwards compatible so that it will still work with older versions of IOS after adding the new mandatory characteristic.

**Comment by KhaosT** [comment]
Apple didn't publish the BridgingState service so technically they can do what ever they wanted to change the service… I already made the changes to support iOS 9.3 in this branch (https://github.com/KhaosT/HAP-NodeJS/tree/bridgeUpdate), you can check the commit history and adopt the new behavior.

**Comment by ni-hao-1** [comment]
Finally I got it working, which means the apps do pair now with the bridge and reacts on speach cmds. What I did was a complete reinstall of most of the software (npm, nodejs, homebridge, etc), including changing to an older kernel. Than I tried again with new installed apps on my iPad and it was working. Then changed back to the newer kernel, reboot ubuntu and still working. What intrigues me is, what the cause was of the malfunction, but I changed so many things that I can not find out anymore. So, now other things to develop here, like using Siri and homebridge at two devices (iPad and iPhone) and start homebridge at boot as a service etc,

**Comment by AppleTechy** [comment]
@KhaosT Does the current version of Homebridge work with HomeKit on iOS 9.3?

**Comment by KhaosT** [comment]
@AppleTechy as long as the current plugin doesn't use Service.BridgingState then they're fine.

**Comment by PjRossi** [comment]
I am a noob. I have been using homebridge for a while. It's great! However, after 9.3 all my accessories disappeared. I have no idea what service.bridgingstate means, and that is probably why I don't know how to fix it. I tried resetting homekit with iOS, deleting the persist file, and changing the port. The plugins I have been using are Nest, smartthings, and IFTTT. Any suggesstions?

**Comment by KhaosT** [comment]
Please update homebridge to 0.3.0 or later

**Comment by PjRossi** [comment]
I tried updating it. Unless I am updating it wrong which could be a possibility. I have it running on startup using systemd. The command to update I use is, sudo npm update -g home bridge

**Comment by PjRossi** [comment]
Thanks! I tried updating it again and it worked. Not sure what happened. Must have done it wrong the first time.
