### ISSUE TITLE
Unable to make ed25519 while installing homebridge

### ISSUE THREAD

**Issue by velocer** [nfarina/homebridge#469]
I tried different versions auf gcc,g++ and nodeJS.

admin@smarthome:~/homebridge$ uname -a
Linux smarthome.local 4.1.15-v7+ #830 SMP Tue Dec 15 17:02:45 GMT 2015 armv7l GNU/Linux

admin@smarthome:~/homebridge$ gcc --version gcc (Raspbian 4.8.4-1) 4.8.4 Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Package.json
{
"name": "homebridge",
"description": "HomeKit support for the impatient$"version": "0.2.15",
"scripts": {
"dev": "DEBUG=* ./bin/homebridge -D -P example-$},
"author": {
"name": "Nick Farina"
},
"repository": {
"type": "git",
"url": "git://github.com/nfarina/homebridge.git"},
"bugs": {
"url": "http://github.com/nfarina/homebridge/is$},
"licenses": [
{
"type": "ISC",
"url": "http://github.com/nfarina/homebridge/$}
],
"bin": {
"homebridge": "bin/homebridge"
  },
  "engines": {
    "node": ">=0.12.0"
},
"preferGlobal": true,
"dependencies": {
"chalk": "^1.1.1",
"commander": "2.8.1",
"hap-nodejs": "0.0.7",
"semver": "5.0.3"
}
}

make: Entering directory `/home/admin/homebridge/node_modules/hap-nodejs/node_modules/ed25519/build'
  CC(target) Release/obj.target/ed25519/src/ed25519/keypair.o
make: cc: Command not found
make: *** [Release/obj.target/ed25519/src/ed25519/keypair.o] Error 127
make: Leaving directory `/home/admin/homebridge/node_modules/hap-nodejs/node_modules/ed25519/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.1.15-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/admin/homebridge/node_modules/hap-nodejs/node_modules/ed25519
gyp ERR! node -v v4.1.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Linux 4.1.15-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE

npm ERR! ed25519@0.0.3 install: `node-gyp rebuild` npm ERR! Exit status 1 npm ERR! 
npm ERR! Failed at the ed25519@0.0.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the ed25519 package, npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls ed25519
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/admin/homebridge/npm-debug.log

**Comment by rudders** [comment]
How are you installing the compile? 

Have you read the wiki on Raspberry https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi#install-c14-raspbian-wheezy-only? 

Which OS have you got on your Raspberry? Wheezy or Jessie?

`cat /etc/*-release`

Nothing will work till `cc` is found.

**Comment by KhaosT** [comment]
Please install build-essential

**Comment by velocer** [comment]
> How are you installing the compile?

I tried "sudo npm install -g homebridge" first
Later I tried to clone, edit package.json und "nmp install"

> Have you read the wiki on Raspberry https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi#install-c14-raspbian-wheezy-only?
Sure, strictly followed all instructions

> Which OS have you got on your Raspberry? Wheezy or Jessie?

Wheezy, but followed instructions under "https://solarianprogrammer.com/2015/01/13/raspberry-pi-raspbian-install-gcc-compile-cpp-14-programs/" to install 4.9 compiler. 4.9 did not work, therefore I aslo tried 4.8

admin@smarthome:/usr/smarthome$ cat /etc/*-release
PRETTY_NAME="Raspbian GNU/Linux 7 (wheezy)"
NAME="Raspbian GNU/Linux"
VERSION_ID="7"
VERSION="7 (wheezy)"
ID=raspbian
ID_LIKE=debian
ANSI_COLOR="1;31"
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

> Please install build-essential

Tried it, did not help.

**Comment by rudders** [comment]
What does `which cc` return?
What versions of `node -v` and `npm -v`?

**Comment by velocer** [comment]
> What does which cc return?

/usr/bin/cc

> What versions of node -v and npm -v?

admin@smarthome:/usr/smarthome$ node -v
v4.1.1


admin@smarthome:/usr/smarthome$ npm -v
2.14.4


I also tried node 4.0.0 and latest Version

**Comment by rudders** [comment]
You've tried sudo too I assume? `sudo npm install -g ...`

**Comment by velocer** [comment]
Sure.

**Comment by rudders** [comment]
Then it's beyond my pay grade sorry @velocer .
Looks like you've installed into /home/admin - maybe a priivilidge issue?
if cd `cd /home/admin/homebridge/node_modules/hap-nodejs/node_modules/ed25519/build` and then `make` what happens

**Comment by velocer** [comment]
Directory doesn't exist. Maybe really an access problem. Found those warnings:

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/4.1.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/curve25519/.node-gyp"

**Comment by snowdd1** [comment]
I read about the EACCESS warning some time ago in https://github.com/nodejs/node-gyp/issues/454#issuecomment-134140378 
It's related to installing globally and using root as user.

**Comment by velocer** [comment]
Thanks Raoul. Installing homebridge with "--unsafe-perm" while using gcc/g++ 4.8 finally did it.
