### ISSUE TITLE
Characteristic information not updating in iOS apps

### ISSUE THREAD

**Issue by mmworm** [nfarina/homebridge#470]
So I have a working setup with a rpi as the bridge (I am having problems with losing the bridge in the app but I am investigating how my openwrt router is handling lan -> wifi multicast packets to solve that). I have one accessory that is a SoC (particle.io) that reacts to a custom udp based api to open my a garage door. Siri works, the output in my putty window when running homebridge looks good. [homebridge] garage is ..... Shows properly in log output (my config and plugin are based on the legacy garage door plugin) but the state characteristic field in the iOS apps never change to reflect the current returned state in the log. And clues?  Sorry about the lack of links above. On my phone.

**Comment by rudders** [comment]
That's up to the plugin to do - can you detail your plugin use and config.json please.

**Comment by mmworm** [comment]
it is literally a modification of the legacy plugin from
https://github.com/nfarina/homebridge-legacy-plugins/blob/master/accessories/HttpGarageDoorOpener.js
I just changed the on close and open calls from an HTTP request to my custom API and I added a call to a function that checks the status of the device via udp in on get status
I know if is working according to the homebridge as I get this, see screenshot:
![homebridge](https://cloud.githubusercontent.com/assets/14791868/12374234/9bf1fdd0-bc5a-11e5-83ad-8ffcfb66d472.png)
but the ios app doesn't seem to get the same info
(the other log stuff is just the udp call/response debugging)

index.js:

    var garage = require("./lib/udpgarage.js");

    module.exports = function (homebridge) {
        Service = homebridge.hap.Service;
        Characteristic = homebridge.hap.Characteristic;
        homebridge.registerAccessory('homebridge-particlegaragedooropener', 'ParticleGarageDoorOpener', ParticleGarageDoorOpener);
    }
    function ParticleGarageDoorOpener(log, config) {
      this.log = log;
      this.particleAddress = config.local_address;
      this.garageDoorStatus = Characteristic.CurrentDoorState.STOPPED;
      this.garageDoorTStatus = Characteristic.TargetDoorState.STOPPED;
    }

    ParticleGarageDoorOpener.prototype = {
       close: function (callback) {
        this.garageDoorStatus = Characteristic.CurrentDoorState.CLOSING;
        this.garageDoorTStatus = Characteristic.TargetDoorState.CLOSED;
        this.log("Door is", this.getCurrentDoorStateReadable());
        garage.garageAction("close", this.particleAddress);
	setTimeout(function(){
		this.garageDoorStatus = this.garageDoorTStatus;
    }, 4000);
	callback();
    },

    open: function (callback) {
        this.garageDoorStatus = Characteristic.CurrentDoorState.OPENING;
	this.garageDoorTStatus = Characteristic.TargetDoorState.OPEN;
        this.log("Door is", this.getCurrentDoorStateReadable());
        garage.garageAction("open", this.particleAddress);
	setTimeout(function(){
		this.garageDoorStatus = this.garageDoorTStatus;
	}, 4000);
	callback();
    },

    identify: function() {
        console.log("Identify the Door!");
    },
  
    getServices: function () {
        this.garageDoorOpenerService = new Service.GarageDoorOpener();
    
        this.garageDoorOpenerService
          .getCharacteristic(Characteristic.CurrentDoorState)
          .on('get', this.getCurrentDoorState.bind(this));

        this.garageDoorOpenerService
          .getCharacteristic(Characteristic.TargetDoorState)
          .on('set', this.setTargetDoorState.bind(this));

    /*
    garageDoorOpenerService
    .getCharacteristic(Characteristic.ObstructionDetected)
    .on('get', this.getObstructionDetected.bind(this))
    .on('set', this.setObstructionDetected.bind(this));
    */

    var informationService = new Service.AccessoryInformation();
    informationService
      .setCharacteristic(Characteristic.Manufacturer, "mmWorm")
      .setCharacteristic(Characteristic.Model, "Particle Garage Door Opener")
      .setCharacteristic(Characteristic.SerialNumber, "1");

    return [informationService, this.garageDoorOpenerService];
    },

     getCurrentDoorStateReadable: function () {
        var textState = "";
        switch (this.garageDoorStatus) {
          case 0: textState = "OPEN"; break;
          case 1: textState = "CLOSED"; break;
          case 2: textState = "OPENING"; break;
          case 3: textState = "CLOSING"; break;
          case 4: textState = "STOPPED"; break;
          default: this.log("Unhandled CurrentDoorState");
        }
        return textState;
      },
  
     getCurrentDoorState: function(callback) {
	   
	this.garageDoorStatus = garage.getStatus();
	
	this.log("The door is now", this.getCurrentDoorStateReadable() ,"("+ this.garageDoorStatus + ")");

	var error = null;
	var returnValue = this.state;

	callback(null, returnValue);
      },

    setTargetDoorState: function(value, callback) {
      if(value === Characteristic.TargetDoorState.OPEN) {
		this.open(callback);
      } else {
		this.close(callback);
      }; 
    }
    };

config.json:

     {
        "bridge": {
            "name": "Homebridge",
            "username": currentusername,
            "port": 51826,
            "pin": "031-45-154"
        },

     "description": "This is an example configuration file with one fake accesso$

    "accessories": [
        {
            "accessory": "ParticleGarageDoorOpener",
            "name": "Garage Door",
            "local_address": addressofphoton        
        }
       ]
    }

**Comment by rudders** [comment]
I'm on my phone so can't really attempt to look seriously but it looks like it should work okay to me so maybe someone who's used this plugin might have some clues.

**Comment by mmworm** [comment]
I figured it out
line 7 of the getCurrentDoorState method sets the return value:
var returnValue = this.state;

it should set the return value to:
var returnValue = this.garageDoorStatus;

I guess it is a typo in the legacy plugin
