### ISSUE TITLE
terminates with Error: socket hang up in q.js:126 #4

### ISSUE THREAD

**Issue by gjniewenhuijse** [nfarina/homebridge#471]
I know this is a hue plugin error, but maybe its general. Same hue connect details with the same plugin on another raspberry pi works great. I installed a new pi and now i get at homebridge startup:

/usr/local/lib/node_modules/homebridge-philipshue/node_modules/node-hue-api/node_modules/q/q.js:126
throw e;
^

Error: socket hang up
at createHangUpError (_http_client.js:203:15)
at Socket.socketOnEnd (_http_client.js:288:23)
at emitNone (events.js:72:20)
at Socket.emit (events.js:166:7)
at endReadableNT (_stream_readable.js:903:12)
at doNTCallback2 (node.js:439:9)
at process._tickCallback (node.js:353:17)

Maybe something todo with node version or another bug?

**Comment by Connor-Knabe** [comment]
Which version of Node are you using? This is happening to me on Node 5.4 but not on Node 4.0.

**Comment by gjniewenhuijse** [comment]
npm -v
2.14.7

node -v
v4.2.1

**Comment by Connor-Knabe** [comment]
What kind of Pi are you using? I've noticed that it seems to be happening on my Pi Zero but not on my Pi 2, I wonder if it's related to the hardware.

**Comment by gjniewenhuijse** [comment]
I have a Model B Revision 2.0 with Mounting holes 512MB 
-----------------------------------------

pi@homekit ~ $ cat /proc/cpuinfo
processor       : 0
model name      : ARMv6-compatible processor rev 7 (v6l)
BogoMIPS        : 2.00
Features        : half thumb fastmult vfp edsp java tls
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xb76
CPU revision    : 7

Hardware        : BCM2708
Revision        : 000e
Serial          : 0000000045ff1c5e

http://www.raspberrypi-spy.co.uk/2012/09/checking-your-raspberry-pi-board-version/

**Comment by Connor-Knabe** [comment]
I may have found a solution for this.

For the node-hue-api you need to have error handling like this:

```
var displayError = function(err) {
    console.error(err);
};
api.setLightState(8, hueState)
    .then()
    .fail(displayError)
    .done();
```
