### ISSUE TITLE
Unable to get homebridge to auto start on boot-up via sudo homebridge

### ISSUE THREAD

**Issue by raspman** [nfarina/homebridge#472]
When I go into terminal and type 'sudo homebridge' it works perfectly.  When I use the various methods to get it to automatically load on boot-up, it won't work (authentication error.)  I never get this error as long as I run the 'sudo homebridge' command via terminal.  I've tried various methods, including PM2, to get this to auto load, but it won't work properly.  Thanks

**Comment by damianromanowski** [comment]
Stick it into /etc/rc.local without the sudo.

**Comment by IMNotMax** [comment]
rc.local is a good idea :)

In the other hand to have logs and error messages, you can have a /etc/init.d/homebridge file (see this excellent example [here](https://github.com/rudders/homebridge-platform-wemo/issues/21#issuecomment-171865742) ) and just follow instructions [here](https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi#running-homebridge-on-bootup-initd) to initialise correctly the file (chmod and update-rc.d) 

(FYI I change the chmod of /var/log/ to give access in RW to all the users, Brutal but no real consequences :)

**Comment by timleland** [comment]
Here is my guide in setting up Homebridge on Raspberry Pi to start on boot up and restart on errors. Hope it help!
https://timleland.com/setup-homebridge-to-start-on-bootup/
