### ISSUE TITLE
config file with 2 or more plugins

### ISSUE THREAD

**Issue by miabilabs** [nfarina/homebridge#475]
Sorry if this is a completely beginner question. I couldn't find the answer anywhere, so maybe it is or I'm missing it...

I'm trying to write my config.json file for use with the legacy plugins plugin and the Sonos plugin. More specifically I'm using Smartthings and would like to support Sonos via homebridge.  My config.json looks like the below, but this is throwing up errors in homebridge. Am I doing this correctly or at least on the right path? I think I might have too many brackets?  Thanks!

{
"bridge": {
"name": "Homebridge",
"username": "F9:52:A8:42:7B:70",
"port": 39320,
"pin": "123-45-678"
},
"description": "JSON API",
        "platforms": [
            {
                "platform": "SmartThings",
                "name": "SmartThings",
                "app_id": "02522b-8b93-45c9-96e8-70fcb63430dbc",
                "access_token": "bbfsas402d-2828-4663-962d-79a13e63317d"
            }
        ]
{
  "accessories": [
    {
      "accessory": "Sonos",
      "name": "Kitchen Speakers",
      "room": "Kitchen"
    }
    {
      "name": "Living Room Speakers",
      "room": "Living Room"
    }
 ]
}

**Comment by MrCoBalt** [comment]
Yeah, I found this could be better documented too and I ran into the same thing integrating like four plugins together in my config.

http://jsonlint.com is definitely your friend here though. I ran your config through it and it needed a `]` or two removed, and some `,` added:
```json
{
	"bridge": {
		"name": "Homebridge",
		"username": "D0:52:A8:00:7B:70",
		"port": 39500,
		"pin": "031-45-154"
	},
	"description": "JSON API",

	"platforms": [{
		"platform": "SmartThings",
		"name": "SmartThings",
		"app_id": "0110f22b-8b93-45c9-96e8-70fcb9c90dbc",
		"access_token": "bb55402d-2828-4430-962d-79a13e6e717d"
	}],
	"accessories": [{
		"accessory": "Sonos",
		"name": "Kitchen Speakers",
		"room": "Kitchen"
	}, {
		"name": "Living Room Speakers",
		"room": "Living Room"
	}]
}
```

**Comment by damianromanowski** [comment]
Looks like you're missing a few commas, as well as a missing `accessory` decleration for your living room speakers:

    {
        "bridge": {
            "name": "Homebridge",
            "username": "D0:52:A8:00:7B:70",
            "port": 39500,
            "pin": "031-45-154"
        },
        "description": "JSON API",
        "platforms": [
            {
                "platform": "SmartThings",
                "name": "SmartThings",
                "app_id": "0110f22b-8b93-45c9-96e8-70fcb9c90dbc",
                "access_token": "bb55402d-2828-4430-962d-79a13e6e717d"
            }
        ],
        "accessories": [
            {
                "accessory": "Sonos",
                "name": "Kitchen Speakers",
                "room": "Kitchen"
            },
            {
                "accessory": "Sonos",
                "name": "Living Room Speakers",
                "room": "Living Room"
            }
        ]
    }

**Comment by MrCoBalt** [comment]
Ah good catch Damian, I didn't notice that missing accessory declaration.

In case anybody cares here is an example of my working config with a few different platforms (sub-configs taken straight from their respective read-me basically):

```json
{
	"bridge": {
		"name": "Your Homebridge",
		"username": "CC:22:3D:E3:CE:20",
		"port": 51826,
		"pin": "123-45-678 "
	},

	"description": "HomeKit Bridge",

	"platforms": [{
		"platform": "BelkinWeMo",
		"name": "WeMo Platform",
		"expected_accessories": "10",
		"timeout": "30",
		"no_motion_timer": "60",
		"homekit_safe": "1"
	}, {
		"platform": "HarmonyHub",
		"name": "Living Room Harmony Hub",
		"ip_address": "192.168.1.50 "
	}, {
		"platform": "Nest",

		"token": "**MUST FILL IN, READ-ME VERY IMPORTANT HERE",

		"clientId": "**NEED DEV API**",
		"clientSecret": "**NEED DEV API**",
		"code": "**NEED DEV API**"
	}, {
		"platform": "IFTTT",
		"name": "IFTTT",
		"makerkey": "**NEED TO ACTIVATE MAKER CHANNEL**",
		"accessories": [{
			"name": "IFTT Test Accessory 1",
			"buttons": [{
				"caption": "A1-1",
				"triggerOn": "T1-1On",
				"triggerOff": "T1-1Off"
			}, {
				"caption": "A1-2",
				"triggerOn": "T1-2On",
				"triggerOff": "T1-2Off"
			}, {
				"caption": "A1-3",
				"trigger": "T1-3"
			}, {
				"caption": "A1-4",
				"trigger": "T1-4"
			}]
		}, {
			"name": "IFTTT Test Accessory 2",
			"buttons": [{
				"caption": "A2-1",
				"trigger": "T2-1"
			}, {
				"caption": "A2-2",
				"trigger": "T2-2"
			}, {
				"caption": "A2-3",
				"trigger": "T2-3"
			}, {
				"caption": "A2-4",
				"trigger": "T2-4"
			}]
		}]
	}]
}
```

**Comment by miabilabs** [comment]
Thanks so much guys! I appreciate the help and that example config.json should be helpful for a lot of folks MrCoBalt.

Also, I got a little trigger happy... would you guys mind changing the values of my config file in this thread? :) I meant to change them before posting but forgot. 

Thanks again.

**Comment by damianromanowski** [comment]
@miabilabs Updated values to match.

**Comment by AppleTechy** [comment]
Is it ok with you if I go ahead and close this than now that you have figured out what your issue was?

**Comment by miabilabs** [comment]
yep we can close it.

**Comment by Pltnorwich** [comment]
hi guys,
I'm using the Json checker online but its defeating me, i had it working with my todo thermostat an wave door lock, but i wanted to add additional accessory,
A lot of the time it says "Duplicate" Ive looked online at and tried to copy but its not helping. Where am i going wrong when trying to add the 2 accessories?

{
	"bridge": {
		"name": "Homebridge",
		"username": "xx:xx:xx:xx:xx:xx",
		"port": 51826,
		"pin": "xxx-xx-xxx"
	},

	"description": "Thermostat",

	"accessories": [{
			"accessory": "TADO",
			"name": "Tado",
			"homeID": "xxxxx",
			"username": "philxxxx@xxx",
			"password": "Mxx-xx-xxxxx"
		}, {
			"accessory": "Danalock",
			"name": "Danalock",
			"address": "xx:xx:xx:xx:xx:xx",
			"name": "Front Door"
			"type": "LockMechanism",
			"UUID": "xxxx-xxx-xxx-xxx-xxxx",
			"characteristics": [{
					"type": "LockTargetState",
					"UUID": "xxxx-xxx-xxx-xxx-xxxx",

					"type": "LockCurrentState",
					"UUID": "xxxx-xxx-xxx-xxx-xxxx",




					"platforms": [{
						"platform": "ZWayServer",
						"url": "http://192.xxx.1.xxx:8083/",
						"login": "xx",
						"password": "xxxxx"

					}]
				}
			}]
	}

It worked with Way, tado, and homebridge, so its just the correct {[, somewhere when using multiple accessories.

Thanks

Phil

**Comment by biffdog** [comment]
I am trying to add Lifx, Dyson and nest plugins but I am finding it quite difficult so could anyone help correct my work?


{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "053-73-874"
    },

   "accessories": [
  {
    "accessory": "dyson-coollink",
    "name": "Purifier Cool Tower",
    "ip": "10.0.1.x",
    "username": "...",
    "password": "..."
  }
],    
    "platforms": [
        {
            "platform" : "LifxLan",
            "name" : "LIFX"
        }
{
   		"platform": "Nest",
   		
   		"token" : "c.5ABsTpo88k5yfNIxZlh...",
   		
   		"clientId": "developer client id",
   		"clientSecret": "developer client secret.",
   		"code": "Pin Code",
   		
   		"username" : "username",
   		"password" : "password"
   	}
   ],

**Comment by Pltnorwich** [comment]
@biffdog, I think it probably has to do with your square bracket position, look at mine above how it was laid out.
Also use this website http://jsonlint.com.

what i did was write a separate json file for each item and checked on the above website, then all I had to do was add one item at a time, ( so 2 items on a json file......) and just work out what was needed to add additional item  ]},........in right places.

**Comment by EdwinJS** [comment]
# Hi @biffdog,

So exactly like what @Pltnorwich said, you had 3 errors that I have fixed it but I also made the errors clear for better understanding of where you went wrong. The errors have been bolded for your ease.

Here is your fixed code:

{
"bridge": {
"name": "Homebridge",
"username": "CC:22:3D:E3:CE:30",
"port": 51826,
"pin": "053-73-874"
},

"accessories": [
{
"accessory": "dyson-coollink",
"name": "Purifier Cool Tower",
"ip": "10.0.1.x",
"username": "...",
"password": "..."
}
],
"platforms": [
{
"platform" : "LifxLan",
"name" : "LIFX"

## },
{
"platform": "Nest",

	"token" : "c.5ABsTpo88k5yfNIxZlh...",
	
	"clientId": "developer client id",
	"clientSecret": "developer client secret.",
	"code": "Pin Code",
	
	"username" : "username",
	"password" : "password"
}
## ]
## }

**Comment by RickHOZ** [comment]
Hi All,

I am having a similar problem with the above, I have bee=n going through it in jsonlint but still seem to be making a mistake somewhere because of the accessories.

Would appreciate anyone with experience casting their eyes over it for me. I have only had the issue since I added the new plugin for BroadlinkRM as I have the CBUS and ELKM1 workign well but i want to be able to control the AV equipemnt now.

Cheers. R

{
   "bridge":{
      "name":"Samara",
      "username":"CC:22:3D:E3:CE:30",
      "port":51826,
      "pin":"031-45-154"
   },
   "description":"My home HomeKit API configuration file",
   "platforms":[
      {
         "platform":"ElkM1",
         "name":"ElkM1",
         "elkAddress":"192.168.1.2",
         "elkPort":"2101",
         "area":"1",
         "keypadCode":"3733",
         "zoneTypes":{
           "4":"motion",
           "5":"motion",
           "7":"motion",
           "8":"motion",
           "9":"motion",
           "10":"motion",
           "11":"motion",
           "12":"motion",
           "14":"motion",
           "15":"motion",
           "16":"motion",
           "17":"motion",
           "18":"motion",
           "19":"motion",
           "20":"motion",
           "21":"motion",
           "22":"motion",
           "23":"motion",
           "24":"motion",
           "25":"motion",
           "26":"motion",
           "28":"motion",
           "29":"motion"
         },
         "garageDoors":[
            {
               "stateZone":"5",
               "openOutput":"11",
               "closeOutput":"11",
               "name":"Garage door"
            }
         ]
      },
      {
        "platform":"BroadlinkRM",
"name":"Broadlink RM",
"hideScanFrequencyButton": false,
"hideLearnButton": false,
"accessories":[
  {
    "name":"Auto-off Switch",
    "type":"switch",
    "disableAutomaticOff": false,
    "onDuration": 5,
    "data":{
      "on":"2600500000012...",
      "off":"2600500000012..."
    }
  },
  {
    "name":"TV On/Off",
    "type":"switch",
    "data":{
      "on":"2600500000012...",
      "off":"2600500000012..."
    }
  },
  {
    "name":"Channel Up",
    "type":"switch-repeat",
    "sendCount":1,
    "data":"2600500000012..."
  },
  {
    "name":"Channel Down",
    "type":"switch-repeat",
    "sendCount":1,
    "data":"2600500000012..."
  },
  {
    "name":"Volume Up",
    "type":"switch-repeat",
    "sendCount":5,
    "interval":0.3,
    "data":"2600500000012..."
  },
  {
    "name":"Volume Down",
    "type":"switch-repeat",
    "sendCount":5,
    "interval":0.3,
    "data":"2600500000012..."
  },
  {
    "name":"Entertainment",
    "type":"switch-multi",
    "interval":0.5,
    "data": [
      "2600500000012...",
      "2600500000012...",
      "2600500000012..."
    ]
  },
  {
    "name":"Entertainment 2",
    "type":"switch-multi-repeat",
    "interval":2,
    "data": [
      {
        "data": "2600500000012...",
        "sendCount": 2,
        "interval": 0.3,
        "pause": 10
      },
      {
        "data": "2600500000012...",
        "sendCount": 2,
        "interval": 5
      }
   ]
},
{
         "platform":"homebridge-cbus.CBus",
         "name":"CBus",
         "client_ip_address":"127.0.0.1",
         "client_controlport":20023,
         "client_cbusname":"SAMARA",
         "client_network":254,
         "client_application":56,
         "client_debug":true,
         "platform_export":"/Users/SamaraServer/.homebridge/samara_platform.json",
         "accessories":[
            {"type":"light","id":11,"name":"Office lights"},
            {"type":"light","id":12,"name":"Office Store"},
            {"type":"light","id":74,"name":"AirCon Office"},
            {"type":"light","id":13,"name":"Office Toilet"},
            {"type":"dimmer","id":18,"name":"Office Hall"},
            {"type":"light","id":50,"name":"Office Toilet Exhaust Fan"},
            {"type":"dimmer","id":1,"name":"Master Bedroom"},
            {"type":"light","id":75,"name":"Master Bedroom AirCon"},
            {"type":"light","id":2,"name":"Master Bedroom Feature"},
            {"type":"dimmer","id":3,"name":"Master Bedroom Ensuite"},
            {"type":"light","id":4,"name":"Master Bedroom Ensuite Mirror"},
            {"type":"dimmer","id":5,"name":"Master Bedroom Toilet"},
            {"type":"light","id":6,"name":"Master Bedroom Wardrobe"},
            {"type":"light","id":48,"name":"Master Bathroom Fan"},
            {"type":"light","id":49,"name":"Master Toilet fan"},
            {"type":"dimmer","id":7,"name":"Retreat"},
            {"type":"dimmer","id":8,"name":"Retreat Cove"},
            {"type":"dimmer","id":9,"name":"Retreat Stairs"},
            {"type":"light","id":76,"name":"AirCon Retreat"},
            {"type":"light","id":145,"name":"Retreat Feature"},
            {"type":"dimmer","id":15,"name":"Media Room"},
            {"type":"dimmer","id":16,"name":"Media Cove"},
            {"type":"light","id":73,"name":"AirCon Media"},
            {"type":"dimmer","id":21,"name":"Kitchen"},
            {"type":"light","id":22,"name":"Kitchen Benches"},
            {"type":"light","id":71,"name":"AirCon Kitchen"},
            {"type":"light","id":86,"name":"Kitchen Bulkhead"},
            {"type":"light","id":23,"name":"Scullery"},
            {"type":"dimmer","id":24,"name":"Dining Room"},
            {"type":"light","id":10,"name":"House Features"},
            {"type":"dimmer","id":26,"name":"Lounge"},
            {"type":"light","id":72,"name":"AirCon Lounge"},
            {"type":"light","id":85,"name":"Fireplace"},
            {"type":"dimmer","id":40,"name":"Sala Treatment Room"},
            {"type":"dimmer","id":38,"name":"Sala"},
            {"type":"light","id":39,"name":"Sala Feature"  },
            {"type":"light","id":56,"name":"Sala Bathroom Exhaust Fan"},
            {"type":"light","id":35,"name":"Laundry"},
            {"type":"light","id":36,"name":"Laundry Store"},
            {"type":"light","id":37,"name":"Laundry Clothesline"},
            {"type":"dimmer","id":19,"name":"Laundry Hall"},
            {"type":"light","id":110,"name":"Externals Rear and Clothesline"},
            {"type":"light","id":45,"name":"Pool Pump Room"},
            {"type":"light","id":46,"name":"Wine Cellar"},
            {"type":"light","id":67,"name":"Fountain"},
            {"type":"light","id":68,"name":"Garden Lighting"},
            {"type":"light","id":69,"name":"Green Garden Lights"},
            {"type":"light","id":58,"name":"Pond Light"},
            {"type":"light","id":57,"name":"Pond Pump"},
            {"type":"light","id":70,"name":"Pool Lights"},
            {"type":"light","id":43,"name":"Deck Pool"},
            {"type":"light","id":60,"name":"Pool Pump"},
            {"type":"light","id":61,"name":"Pool Spa Pump"},
            {"type":"dimmer","id":28,"name":"Bridge Suite"},
            {"type":"dimmer","id":29,"name":"Bridge Suite Ensuite"},
            {"type":"light","id":30,"name":"Bridge Suite Ensuite Mirror"},
            {"type":"light","id":77,"name":"Bridge Suite AirCon"},
            {"type":"light","id":44,"name":"Bridge Suite Deck"},
            {"type":"light","id":53,"name":"Bridge Suite Ensuite Exhaust Fan"},
            {"type":"light","id":66,"name":"Bridge Suite AV Features"},
            {"type":"dimmer","id":31,"name":"Kingfisher Bed"},
            {"type":"light","id":78,"name":"Kingfisher Bed AirCon"},
            {"type":"dimmer","id":32,"name":"Kingfisher lounge"},
            {"type":"light","id":79,"name":"Kingfisher Lounge AirCon"},
            {"type":"dimmer","id":33,"name":"Bathroom Kingfisher"},
            {"type":"light","id":54,"name":"Bathroom Exhaust Fan Kingfisher"},
            {"type":"dimmer","id":34,"name":"Kingfisher Toilet"},
            {"type":"light","id":55,"name":"Kingfisher Toilet Exhaust Fan"},
            {"type":"dimmer","id":20,"name":"Guest Hall"},
            {"type":"light","id":47,"name":"Portico"},
            {"type":"switch","id":80,"name":"Front Door Open","activeDuration":"5s"},
            {"type":"light","id":87,"name":"Chandelier"},
            {"type":"light","id":25,"name":"Foyer"},
            {"type":"switch","id":105,"name":"Front Gate Open","activeDuration":"100ms"},
            {"type":"switch","id":103,"name":"Garage Door Open","activeDuration":"100ms"},
            {"type":"light","id":14,"name":"Garage"},
            {"type":"light","id":52,"name":"Solar Hot Water Boost"},
            {"type":"shutter","id":64, "name": "Master Bedroom Curtains", "invert": "true"},
            {"type":"shutter","id":63, "name": "Master Bedroom Net", "invert": "true"}
         ]
      }
   ],
   "accessories":[

   ]
}

**Comment by johnsills1** [comment]
No } at the end of Broadlink

**Comment by johnsills1** [comment]
Need some help with the following:

Trying to add another Accessory and keep having my Nest and Plex stop working when I add the Denon portion. I will put in bold what I'm having trouble adding


{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    "description": "This is an example configuration file. You can use this as a template for creating your own configuration file containing devices you actually own.",
    "accessories": [
    {"accessory": "Plex",
      "name": "Plex",
      "plex_token": "NxcraQQdgDFnxAR4CWs7",
      "filter": [{
            "user": "johnsills1",
            "player": "Living Room" }]
    },
      **_{"accessory": "DenonAVR",
          "name": "Denon Basement",
          "ip": "192.168.1.89",
          "defaultInput": "Game",
          "defaultVolume": 35,
          "minVolume": 10,
          "maxVolume": 75,
          "doPolling": true,
          "pollingInterval": 60
    }_**
       ]
    ,
    "platforms": [
        {
            "platform": "Nest",
            "token": "c.c6kmAMvmPL45fxOObYnqB8V...",
            "clientId": "client id",
            "clientSecret": "secret",
            "code": "code",
            "username": "username",
            "password": "password"
        }
    ]
}
