### ISSUE TITLE
Simple UI for managing / customizing plugins

### ISSUE THREAD

**Issue by epheterson** [nfarina/homebridge#477]
While the CLI / config file system is functional, it's not the most approachable. It'd be nice to track a longer-term UI to streamline the process of using HomeBridge.

**Comment by KhaosT** [comment]
@epheterson surprise to see you here 😄It's on the roadmap for a while but everyone is kinda busy right now so that will probably arrive later :)

**Comment by epheterson** [comment]
Didn't know you were on here either! Looking forward to it as the customization requires you go back to each plugin's documentation instead of being intuitively discoverable.

**Comment by cflurin** [comment]
I'm working on it at first for my plugin (homebridge-punt). It will be similar to the already implemented simulator.

**Comment by nfarina** [comment]
It's something I'd love to have as well. I started working on this a while ago in the `provider-API` branch, but it has a ways to go.

**Comment by KraigM** [comment]
Im actually working on something along those lines right now.  I have it so you can load your config and installed plugins, make modifications to the config, and save the config, all from anywhere on the network (secured by the access key, i.e. "174-33-129")

**Comment by epheterson** [comment]
To be clear, when I suggested UI, I did not mean in-browser UI, or UI to edit the config file via text. Although that's a step, an ideal solution would be more akin to the UI to discover / install / customize plugins for browsers such-as Firefox or Chrome. 

I'd love to play with any half-baked solutions any of you have made!

**Comment by bugs181** [comment]
I suppose what you're really looking for then is a sort of UI for `npm` that looks for the `homebridge-` prefix and then uses the `package.json` file. Inside that, you can have a `screenshotUrl` property that displays a screenshot, an install button, and perhaps some sort of social/rating platform. It all seems kind of elaborate but I think it could work.

**Comment by epheterson** [comment]
Hey, that's really half of the puzzle. The other half is actual configuration of the plugin. For example, if I download the homebridge-cmd plugin, a UI to visually convey to the user that one accessory will exist, with whichever title, running whichever commands when the boolean goes to each state. Then a (+) button to add an additional toggle / accessory and configure it. 

I'd like for this to be more approachable for people who may never want to open a text editor, copy/paste lines to the correct section, modify and verify syntax before relaunching homebridge.

**Comment by bugs181** [comment]
It would involve a little more thought on making an extensive configuration panel, with text fields, switches, checkboxes, and buttons. I'm not sure who would be responsible for making those options and the commands that would need to follow. Everything else can be done using the `package.json` - tests, installation, etc. Gulp task comes to mind here for the backend of the UI. One way of doing that could be a community dropdown that shows you a variety of pre-configurations, with the options of changing those fields.. That would at least get you a small database running of easy to install plugins.

I really like the idea of this so I may take a swing at if I get more time. If someone starts this project, be sure to chime in here so that I can follow and help contribute to it.

**Comment by epheterson** [comment]
The best way to do it would be for the creator of each plugin to also provide prototypes within the plugin that this new service can use. As a fallback, we could use community-sourced prototypes and lastly, when neither exist, give the user a text box within UI and a link to the plugin's npm page to help the user out, where that textbox's contents would be automatically added to the appropriate place in the config file.

**Comment by justme-1968** [comment]
the idea is great but keep in mind that this can get arbitrarily complex.

i have just changed the FHEM plugin to be completely user configurable. all mappings from fhem device to homekit service, fhem reading to homekit characteristic and and all mappings of the values and commands used in both directions are configurable. the only thing missing is the creation of custom characteristics which will be added later.

all this is currently done by setting a few strings on the fhem side. text is not the friendliest interface but very flexible.

doing this with a gui on the homebridge side would look great and help novice users but might hinder more experienced users.

**Comment by epheterson** [comment]
It makes sense that advanced users can fall back to text entry instead of the UI to use features that were never implemented in the UI. in these cases they could do a majority of the configuration in UI, then open some box to edit the config manually. 

We'll have to consider how to go back to UI once a manual change has been made. Are you restricted from returning to UI without starting over? Does the UI change overwrite any manual change? Is the UI getting its info from the config doc or elsewhere, because if so what happens when the UI comes across text it doesn't know how to display? All need to be answered, but I'm sure we can figure something out!

**Comment by KraigM** [comment]
I currently have a Mac app that can download the configuration, download what plugins are installed and what platforms/accessories they support, edit the configuration (with some amount of aid, right now each platform/accessory can only be edited raw but it at least separates them all), and upload the config back to homebridge (currently you have to restart home bridge manually for it to take effect).  

Im working on getting it to update/install plugins now.  I have it mostly done; it can get a list of plugins that are available (from npm) and attempts to install, but I'm missing args or something because its installing all the dependencies next to each other instead of in the hierarchy (so it fails to load).

If you guys are interested, I can post what I have so far.  Its a little rough but I think its a start.

**Comment by epheterson** [comment]
I'd like to give it a spin!

**Comment by snowdd1** [comment]
@KraigM Did you use the npmi package for the npm install?

**Comment by KraigM** [comment]
@snowdd1 Oooo... Nope, I just used npm as a dependency.  npmi might be the solution to my prob Thanks!

I'm going to try to clean up a few things today and then release an alpha version for those interested.

**Comment by KraigM** [comment]
Sorry for the delay.  I have release an prerelease version of the app I'm working on.  Its VERY early so be for warned :smile: 

To install:

1. Install the plugin: `npm install -g homebridge-controllerlink`

2. Download the app: [HomeBridgeController-0.1.0.dmg](https://github.com/KraigM/HomeBridgeController/releases/download/app-0.1.0/HomeBridgeController-0.1.0.dmg)

3. Configure the connection by using the pin code from you homebridge (preferences should open automatically and can be opened at anytime using the preferences menu option or `cmd + ,`)

**Comment by epheterson** [comment]
Hmm...?
Feb  5 01:37:37 Erics-iMac taskgated-helper[81396] <Error>: Disallowing com.enferra.HomeBridgeController.Mac[pid 81395] because no provisioning profiles found
Feb  5 01:37:37 Erics-iMac HomeBridgeController[81395] <Warning>: ### Failed to load Addressbook class CNContactNameFormatter

I enter the correct PIN but it doesn't dismiss, and never stops the spinner.

**Comment by KraigM** [comment]
So it does open and ask you for the pin?

**Comment by KraigM** [comment]
Not sure what that task gate helper error is stopping. I'm going to try setting it up fresh on another Mac tonight to trouble shoot any issues with using another machine. 

Can you see if the link is up and running? If it is it should show up on bonjour browser as "hbctrllink".

**Comment by KraigM** [comment]
As Im installing this I realize I missed a crucial step above:

2.5. Add the HomeBridgeControllerLink platform to your current config.json
```
        {
            "platform" : "HomeBridgeControllerLink"
        }
```

**Comment by humac** [comment]
@KraigM I also have it just sitting at the spinner after I enter the PIN.  I did include the platform statement in my config.json as well.

**Comment by KraigM** [comment]
@humac Can you run [bonjour browser](http://www.macupdate.com/app/mac/13388/bonjour-browser) on that same machine and make sure that it shows up, please :smile:

**Comment by KraigM** [comment]
There might still be something wrong with how I built it thats not allowing you guys to use it.  I signed it but the profile error makes me think there is something wrong with how I signed it.  But I wanted to rule out the link not actually being on or not broadcasting

**Comment by KraigM** [comment]
On bonjour browser it will display as `_hbctrllink._tcp.`

**Comment by humac** [comment]
@KraigM Yep bonjour browser sees it

**Comment by KraigM** [comment]
@humac I think I may have figured out the issue.  My control for reading the pin code was looking for numbers, however when it went back into a string, I forgot to pad the numbers.  So if you were using the default pin code (031-45-154) my app was generating the security token with (31-45-154) which is completely different when it comes to encryption/hashing/etc :smile: 

I uploaded a new version of the app [HomeBridgeController 0.1.1](https://github.com/KraigM/HomeBridgeController/releases/download/app-0.1.1/HomeBridgeController-0.1.1.dmg).  See if that fixes it for you. You will have to reconfigure your pin, but you only need to open the prefs and hit save and it will fix it.

**Comment by KraigM** [comment]
Ok I am releasing version 0.2.0 of the app.  It requires at least version 0.2.2 of the plugin.  Feel free to report any issues or feature requests to the [GitHub repo](https://github.com/KraigM/HomeBridgeController).  Hope you guys enjoy

### Whats New (in addition to what was in 0.1):

- _Several_ fixes

- Installing and updating of plugins (just like the config updates, right now new installs/updates require manual restart of homebridge to take effect)

- App update system to simplify future releases



### Installation
[App Download](https://s3.amazonaws.com/enferra-homebridgecontroller-release/HomeBridgeController/HomeBridgeController.dmg)

Plugin Install:
`npm install -g homebridge-controllerlink`

And don't forget to add the plugin as a platform on your config.json



### What I plan to add next:

- Better documentation on installation and setup

- Rebuild the connection system to better indicate found homebridge's and availability (not just an unending spinner with no clue why)

- Cleanup UI

- Update HomeBridge itself

- Full meta information about plugins and available plugins

- Properly load new available plugins.  Right now it requires an update to refresh the list of plugins, do to the fact that npm search involves a complete local index of _all the things_ on npm (no I'm not even joking, they download meta data on every single package on the npm registry).  To start, I might just throw a JSON file on S3 that I update, but if anyone else has any better ideas I would love to hear it.


### After That
I have some ideas beyond that but I leave it to you guys to ask for what you want or suggest more:

- Get it on the Mac App Store

- Apply updates without a manual restart (via automated restart, plugin 2.0, docker, or all the above or others)

- iOS app that is able to preform most, if not all, the same functionality. (this one should be fairly easy, I wrote it cross platform so I only need to add a few things to get it on iOS and even Windows if people want)

- Full installation of HomeBridge via the app

- Dynamically built UI for editing plugin settings. Possibly even making it so plugin developers can define metadata for their own editors as part of their npm package.

**Comment by epheterson** [comment]
Whoa! It works! This is cool, thanks so much :)

I never thought to update my plugins before, it's nice that this prompts me and lets me to so effortlessly.

Especially looking forward to : 
- Full installation of HomeBridge via the app (including ability to stop/start/view status)
- Dynamically built UI for editing plugin settings. ~~Possibly~~ even making it so plugin developers can define metadata for their own editors as part of their npm package.

**Comment by AppleTechy** [comment]
I would love to see an automated restart with it. It would also be great if
it packaged the entire install of homebridge in it but I doubt you could
get that then into the Mac App Store, but if you that would streamline the
process of the installation process most likely drawing more people to
actually use the app. Thanks for the hard work!

**Comment by KraigM** [comment]
My theory is given Xcode was able to install command line tools, we might be able to do something similar.  Pretty sure SourceTree managed to do that when they were on the App Store.  

That or it could be a separate install package that you can download. 

Also we might be able to embed it right in the app (like source tree did).

**Comment by nfarina** [comment]
@KraigM This is amazing!

**Comment by humac** [comment]
@KraigM FYI it's working for me now...  Well as far as I can tell it's now connecting, haven't had a chance to play around with the app yet but so far so good.

**Comment by KraigM** [comment]
## Release 0.3.0

### Additions
+ [[#14]](https://github.com/KraigM/HomeBridgeController/issues/14)	Added the ability to update homebridge itself
+ [[#17]](https://github.com/KraigM/HomeBridgeController/issues/17)	Enhanced Locating/Selecting/Connecting to HomeBridge
+ [[#3]](https://github.com/KraigM/HomeBridgeController/issues/3)	All raw settings views now have enhanced controls including features like syntax highlighting, syntax checking, and more
+ [[#13]](https://github.com/KraigM/HomeBridgeController/issues/13)	Properly includes newly released plugins in available plugins to install
+ [[#2]](https://github.com/KraigM/HomeBridgeController/issues/2)	Installed plugins are filtered from the list of available plugins to be installed
+ [[#15]](https://github.com/KraigM/HomeBridgeController/issues/15)	Now displays the description and link to the homepage of the plugins

**Comment by ShamanPrime** [comment]
Great work!

In Raspberry Pi 3 (latest Raspbian) I had to use the "--unsafe-perm" flag for global npm installation.
Otherwise you get the same error as during the homebridge installation (i.e.: gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/5.5.0").
