### ISSUE TITLE
Custom commands for HomeKit

### ISSUE THREAD

**Issue by iPh1ps99** [nfarina/homebridge#48]
Hey,

Is it possible that you can insert your own commands that aren't related to HomeKit but for Siri with this library?

**Comment by nfarina** [comment]
There's nothing stopping you from adding "Accessories" that aren't actually accessories. However the language to use them may be awkward, as Siri only knows phrases related to controlling a small set of connected-home devices. So "Turn on the XYZ" for instance.

**Comment by iPh1ps99** [comment]
Ok thank you, how can I close this issue?

**Comment by iPh1ps99** [comment]
Thank you!
