### ISSUE TITLE
Negative Float Values 

### ISSUE THREAD

**Issue by Joey-1970** [nfarina/homebridge#480]
Hello!

I have a problem to get negativ values of float-variables. In this case I want to get the temperature from outside and at this time it is negativ. (In the app I see only 0 to 100)

Is this a problem of homebridge or off the plugin (homebridge-symcon)?

Joachim

**Comment by KhaosT** [comment]
@Joey-1970 the plugin needs to override the characteristic.props.minValue in this case.

**Comment by Joey-1970** [comment]
Hello KhoasT,
thanks for your answer.
May you explain me how to do this? (maybe a example?)
And in witch place?
Joachim

**Comment by KhaosT** [comment]
Something like
```js
service.getCharacteristic(hapCharacteristic).setProps({minValue: -10});
```
should be added to [here](https://github.com/w-andre/homebridge-symcon/blob/master/SymconAccessory.js#L279) depends on the characteristic type.

**Comment by Joey-1970** [comment]
Hello KhoasT,

I try and try but I don't get a negative feedback in the app (..is not my code...)
I hope the author will do it... ;-)

Thank you for your help!

Joachim

**Comment by cflurin** [comment]
@Joey-1970: it works! I've implemented it in homebridge-punt. The settings can be defined in config-punt.json.
You can test it yourself, just install [homebridge-punt] (https://github.com/cflurin/homebridge-punt) and run the build-in simulator.

**Comment by Joey-1970** [comment]
Sorry, I'm not able to do something like this in the code of homebridge-symcon. I see what you mean, but I don't no how do this in homebridge-symcon... (https://github.com/w-andre/homebridge-symcon/blob/master/SymconAccessory.js)
I must wait for the author of this code or on someone who can tell me exactly what I ust change in this code... :-(

Joachim

**Comment by KhaosT** [comment]
@Joey-1970 in that case, I'd suggest you file an enhancement request in that repo. I'll close this issue for now.
