### ISSUE TITLE
Temperature below 0 degree celsius

### ISSUE THREAD

**Issue by xfjx** [nfarina/homebridge#481]
Is it possible to display values below 0 degree for temperature? I created a plugin which fetches weather information form weather underground but I am having problems with negative values.

Thank you very much!

**Comment by KhaosT** [comment]
@xfjx check this https://github.com/nfarina/homebridge/issues/480#issuecomment-173656196

**Comment by xfjx** [comment]
@KhaosT Thank you very much! It works!
