### ISSUE TITLE
Yamaha AVR - other zones possible?

### ISSUE THREAD

**Issue by ficklma1** [nfarina/homebridge#485]
The Yamaha-JS works well for main zone, but are there any properties to turn on/off other zones?  i.e. zone2 or zone3.  Also the respective volumes for those zones?

**Comment by ficklma1** [comment]
I was able to modify the code to use for Zone_2 instead of Main_zone.  I'm going to attempt to put both of these in the code.

**Comment by NovaGL** [comment]
Just fyi @ficklma1 I have do a pull request in december to allow multiple zones for node_yamaha it just hasn't been looked at.

**Comment by KraigM** [comment]
You really should discuss anything the  homebridge-Yamaha repo

**Comment by AppleTechy** [comment]
Please move this to the homebridge-Yamaha repo
