### ISSUE TITLE
do I need 2 homebridge instances?

### ISSUE THREAD

**Issue by ni-hao-1** [nfarina/homebridge#486]
I use homebridge at a ubuntu server. I have Eve installed at my iPhone. Working ok. Now I want also to use Eve at my iPad (using the same bridge), but it does not (re)act on siri commands. Do I need to have 2 homebridge instances running at ubuntu server and if so, howto setup?

**Comment by nfarina** [comment]
Are you signed into the same iCloud account on both iOS devices?

**Comment by ni-hao-1** [comment]
No I am not, besides later (when it functionates at my iPad and iPhone) I want to have it working also at the device of my wife

**Comment by nfarina** [comment]
HomeKit sharing is done through iCloud accounts and sharing. If you want to share with a separate account, you'll need to go to HomeKit in the Settings app and "invite user".

**Comment by ni-hao-1** [comment]
Ah good tip, It is working now at all devices

**Comment by nfarina** [comment]
Awesome!
