### ISSUE TITLE
Colorpicker support

### ISSUE THREAD

**Issue by nbittmann** [nfarina/homebridge#487]
Is there any change of getting support for a colorpicker item?

Thanks

**Comment by damianromanowski** [comment]
@nbittmann Please elaborate..

**Comment by nbittmann** [comment]
Currently if you have a site map in openhab with a so called colorpicker item it will be ignored however I just noticed it might be better to post this to the actual openhab plugin ?

**Comment by damianromanowski** [comment]
@nbittmann It sounds like a plugin issue. I'd post to issues @ [homebridge-openhab](https://github.com/tommasomarchionni/homebridge-openHAB/issues) first.

Perhaps related to tommasomarchionni/homebridge-openHAB#12
