### ISSUE TITLE
Triggers

### ISSUE THREAD

**Issue by chrislongden** [nfarina/homebridge#489]
I currently have homebridge setup with the wemo-platform plugin and it's working great. I've setup a trigger based on a wemo motion plug to turn on my lights in the living room between sunset and sunrise.

However, the wemo-platform forces a crash if it cannot detect a set number of devices that you expect it to find (so homekit doesn't removed them and therefore remove triggers and settings for them devices). 

To counter this I have a crob job set to run every 5 minutes checking if homebridge is running and if not then to start it up, which works fine for what I need.

The issue I'm having is that the triggers stop working completely and I have to open the "Home" app on my phone, goto triggers and disable then re-enable them so kick them back in.

Would this be an issue with homebridge and/or is there a way to forcefully enable the triggers from the Pi. Maybe setting up another cron job?

**Comment by nfarina** [comment]
I feel like I've encountered "randomly disabled" triggers as well. So you're saying that simply restarting homebridge will cause triggers to stop working even when homebridge starts back up?

**Comment by chrislongden** [comment]
That's what appears to be happening and I presume it's homebridge as I would guess the wemo-platform plugin pings a message to homebridge regarding triggers.

Exactly what happened is, I just got in from work and lights didn't turn on from the motion sensor so I didn't touch homebridge or anything, just went and disabled then re-enabled the triggers from the "Home" app, which showed them as "Enabled" initially, then walked in front of sensor and the light come on.

**Comment by chrislongden** [comment]
Just a note: Previously when getting this issue I'd normally reboot my raspberry pi but that didn't seem to do the trick so ended up deleting the homekit configuration on my phone and starting over only for it to happen again, so just tried to stated turn them off and on again.

**Comment by KhaosT** [comment]
```
Exactly what happened is, I just got in from work and lights didn't turn on from the motion sensor so I didn't touch homebridge or anything, just went and disabled then re-enabled the triggers from the "Home" app, which showed them as "Enabled" initially, then walked in front of sensor and the light come on.
```
So when this happens, the state of the trigger is still "enabled" before you turn it off?

**Comment by chrislongden** [comment]
Correct.

Triggers don't work but in the "Home" app they are displayed as "Disable Trigger", tap that and changes to "Enable Trigger" tap again to turn on.

**Comment by KhaosT** [comment]
That can either count as a HomeKit bug or the accessory misbehave... It's a known issue that when accessory closed the connection (in this case, crashed) and re-connected, HomeKit on iOS may not re-enroll the notifications for characteristic events since local state of the accessory still think all those notifications are enrolled.

**Comment by chrislongden** [comment]
I've just done a test by killing homebridge and then running it again, triggers still work. Followed up with a reboot of the system, homebridge is running and triggers are working so I guess just every now and again that this is going to happen. Generally seems like once a day.

Is there anyway to force the triggers off and on again from on pi that you know of?

**Comment by KhaosT** [comment]
not really, triggers is protected by HomeKit on iOS and only user can change that ... Is it possible for you to enable the advanced logging for homebridge and next time when this happens, post the log at here? I just want to make sure we're not missing any problem ^^

**Comment by chrislongden** [comment]
Yeah I've just removed the massive .log and .err files so start from scratch and hopefully will see something in the next 24 hours.

**Comment by KhaosT** [comment]
Thanks :)

**Comment by chrislongden** [comment]
They have randomly stopped working again so here are the log files.

[homebridge_err.txt](https://github.com/nfarina/homebridge/files/105745/homebridge_err.txt)
[homebridge_log.txt](https://github.com/nfarina/homebridge/files/105746/homebridge_log.txt)

**Comment by chrislongden** [comment]
After I got these logs I deleted them, Istopped homebridge and start it up again. Then I tried the motion sensor and nothing, so I used the app to disable and re-enable the triggers, then tested and they worked. Here are the logs from that.

[homebridge_err.txt](https://github.com/nfarina/homebridge/files/105751/homebridge_err.txt)
[homebridge_log.txt](https://github.com/nfarina/homebridge/files/105752/homebridge_log.txt)

**Comment by KhaosT** [comment]
@chrislongden can you tell which IP address belongs to iPhone (the one with trigger?)

**Comment by chrislongden** [comment]
The one that ends .207

**Comment by KhaosT** [comment]
@chrislongden and can you post the content from http://homebridge-ip:51826/accessories? And which accessory did you set to turn on/off (preferably a screenshot from "Home" that shows condition)?

**Comment by chrislongden** [comment]
Accessories:
[accessories.txt](https://github.com/nfarina/homebridge/files/105780/accessories.txt)

Screenshots of triggers and scenes:

![2016-01-26 22 25 36](https://cloud.githubusercontent.com/assets/1384877/12597258/19d9648a-c47c-11e5-9c3f-6dbfc7f63b86.png)
![2016-01-26 22 25 28](https://cloud.githubusercontent.com/assets/1384877/12597259/19dcfec4-c47c-11e5-9a49-73fbe3230226.png)

![2016-01-26 22 25 51](https://cloud.githubusercontent.com/assets/1384877/12597263/1f74cfba-c47c-11e5-999f-14588e4ee506.png)
![2016-01-26 22 25 46](https://cloud.githubusercontent.com/assets/1384877/12597262/1f726216-c47c-11e5-9388-ecd18cfe49bb.png)

**Comment by chrislongden** [comment]
One trigger is always and the other is only after sunset.

**Comment by chrislongden** [comment]
Just had a look at the "Home" app on my ipad. It does list all devices, rooms, scenes etc but it doesn't show the triggers I have setup, do you think that this may be an issue, specially if im not present in the house with my iphone?

**Comment by KhaosT** [comment]
Triggers will not be synced across your devices (otherwise it may be executed multiple times). If you have an Apple TV and the Remote Access is working then it shouldn’t be a problem.

Best Wishes,
Tian

**Comment by chrislongden** [comment]
Yeah I have an Apple TV 4 so that's fine then.

**Comment by KhaosT** [comment]
From the log it it seems when iOS reconnects to the bridge, it always subscribes notifications for trigger characteristics. Maybe it's a bug in HomeKit for scheduling trigger event handler then...
