### ISSUE TITLE
Startup Issue

### ISSUE THREAD

**Issue by steve772** [nfarina/homebridge#49]
I am getting the following error:

Starting HomeBridge server...
Couldn't find a config.json file in the same directory as app.js. Look at config-sample.json for examples of how to format your config.js and add your home accessories.

npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "start"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE
npm ERR! homebridge@0.0.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the homebridge@0.0.0 start script 'node app.js'.
npm ERR! This is most likely a problem with the homebridge package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls homebridge
npm ERR! There is likely additional logging output above.

I am using the config-sample.json file and renamed it to config.json locally.  The file is in fact in the same directory as app.js.  Any suggestions?

![screen shot 2015-06-30 at 10 58 31 am](https://cloud.githubusercontent.com/assets/13118694/8434033/0ce6a252-1f17-11e5-91e6-e577219266ef.png)

**Comment by madmod** [comment]
Make sure that you are in the homebridge directory when running the app?

**Comment by steve772** [comment]
I definitely am...

**Comment by nfarina** [comment]
Are you positive that the file is named "config.json" exactly and that there isn't an additional "hidden" file extension as Finder likes to do sometimes?

**Comment by madmod** [comment]
Run the following command in that directory and paste the output in `test.log` here. Remove any passwords or API keys from the file also. This will give us some more info on what the problem might be.

```bash
echo "r=require;l=console.log;d=__dirname;p=r('path').join(d,'config.json');l(d);l(p);f=r('fs');l(f.readFileSync(p).toString());l(f.existsSync(p));" | node > test.log; ls -al >> test.log
```

**Comment by steve772** [comment]
Tried doing that but am having permission issues:

Last login: Tue Jun 30 21:21:04 on ttys000
Home:~ Steve$ cd homebridge
Home:homebridge Steve$ ls
LICENSE			config-sample.json	npm-debug.log
README.md		homebridge		package.json
accessories		lib			platforms
app.js			node_modules
Home:homebridge Steve$ sudo npm run start

> homebridge@0.0.0 start /Users/Steve/homebridge
> node app.js

Starting HomeBridge server...
Couldn't find a config.json file in the same directory as app.js. Look at config-sample.json for examples of how to format your config.js and add your home accessories.

npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "start"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE
npm ERR! homebridge@0.0.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the homebridge@0.0.0 start script 'node app.js'.
npm ERR! This is most likely a problem with the homebridge package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls homebridge
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Steve/homebridge/npm-debug.log
Home:homebridge Steve$ sudo echo "r=require;l=console.log;d=__dirname;p=r('path').join(d,'config.json');l(d);l(p);f=r('fs');l(f.readFileSync(p).toString());l(f.existsSync(p));" | node > test.log; ls -al >> test.log
-bash: test.log: Permission denied
-bash: test.log: Permission denied
Home:homebridge Steve$

**Comment by nfarina** [comment]
In your "ls" output I don't see config.json listed?

**Comment by nfarina** [comment]
It looks like your terminal is in ~/homebridge and your Finder window is in ~/Github/homebridge. Perhaps you copied the directory?

**Comment by madmod** [comment]
I'm not sure why that would need sudo permissions to write something to the hombridge directory. Run the following command in that directory and post it here.

```bash
sudo sh -c "echo \"r=require;l=console.log;d=__dirname;p=r('path').join(d,'config.json');l(d);l(p);f=r('fs');l(f.readFileSync(p).toString());l(f.existsSync(p));\" | node > test.log; ls -al >> test.log"
```

Also try running `sudo chmod -R 750 ~/homebridge; chown -R steve ~/homebridge` then run the last command I gave you. (Replace the `~/hombridge` with `~/Github/homebridge` if it is there instead.) Also if `npm install` doesn't work without sudo then your npm/node permissions are incorrect and you should try to reinstall them.

**Comment by steve772** [comment]
Thanks will give it a try this weekend

**Comment by steve772** [comment]
I definitely had an issue with two folders with hombridge as you pointed out so I am using the ~/homebridge folder.  I placed the config.json file there and ran npm run start.  The new error returned is posted below.  I then ran the test log command as instructed and have attached that as well.  Thanks for your help and sorry for the delay in getting back to you.

Home:homebridge Steve$ npm start run

> homebridge@0.0.0 start /Users/Steve/homebridge
> node app.js "run"

Starting HomeBridge server...
undefined:10
            "username": “steve772@rochester.rr.com",
                        ^
SyntaxError: Unexpected token “
    at Object.parse (native)
    at Object.<anonymous> (/Users/Steve/homebridge/app.js:21:19)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "start" "run"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE
npm ERR! homebridge@0.0.0 start: `node app.js "run"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the homebridge@0.0.0 start script 'node app.js "run"'.
npm ERR! This is most likely a problem with the homebridge package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js "run"
npm ERR! You can get their info via:
npm ERR!     npm owner ls homebridge
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Steve/homebridge/npm-debug.log


Test Log Results:

.
config.json
{
    "description": "This is an example configuration file with all supported devices. You can use this as a template for creating your own configuration file containing devices you actually own.",

    "platforms": [
        {
            "platform": "Wink",
            "name": "Wink",
            "client_id": "YOUR_WINK_API_CLIENT_ID",
            "client_secret": "YOUR_WINK_API_CLIENT_SECRET",
            "username": “steve772@rochester.rr.com",
            "password": “”
        },
        {
            "platform": "SmartThings",
            "name": "SmartThings",
            "app_id": "JSON SmartApp Id",
            "access_token": "JSON SmartApp AccessToken"
        },
        {
            "platform": "Domoticz",
            "name": "Domoticz",
            "server": "127.0.0.1",
            "port": "8005"
        },
        {
            "platform": "PhilipsHue",
            "name": "Phillips Hue",
            "username": ""
        },
        {
            "platform": "ISY",
            "name": "ISY",
            "host": "192.168.1.20",
            "port": "8000",
            "username": "username",
            "password": "password"
        }
    ],

    "accessories": [
        {
            "accessory": "WeMo",
            "name": "Coffee Maker",
            "description": "This shim supports Belkin WeMo devices on the same network as this server. You can create duplicate entries for this device and change the 'name' attribute to reflect what device is plugged into the WeMo, for instance 'Air Conditioner' or 'Coffee Maker'. This name will be used by Siri. Make sure to update the 'wemo_name' attribute with the EXACT name of the device in the WeMo app itself. This can be the same value as 'name' but it doesn't have to be.",
            "wemo_name": "CoffeeMaker"
        },
        {
            "accessory": "LiftMaster",
            "name": "Garage Door",
            "description": "This shim supports LiftMaster garage door openers that are already internet-connected to the 'MyQ' service.",
            "username": “”,
            "password" : “”
        },
        {
            "accessory": "Sonos",
            "name": "Speakers",
            "description": "This shim supports Sonos devices on the same network as this server. It acts as a simple switch that calls play() or pause() on the Sonos, so it's only useful for pausing and resuming tracks or radio stations that are already in the queue. When 'play_volume' is nonzero, the volume will be reset to that value when it turns the Sonos on.",
            "play_volume": 25
        },
        {
            "accessory": "Lockitron",
            "name": "Front Door",
            "description": "This shim supports Lockitron locks. It uses the Lockitron cloud API, so the Lockitron must be 'awake' for locking and unlocking to actually happen. You can wake up Lockitron after issuing an lock/unlock command by knocking on the door.",
            "lock_id": "your-lock-id",
            "api_token" : "your-lockitron-api-access-token"
        },
        {
            "accessory": "Carwings",
            "name": "Leaf",
            "description": "This shim supports controlling climate control on Nissan cars with Carwings. Note that Carwings is super slow and it may take up to 5 minutes for your command to be processed by the Carwings system.",
            "username": "your-carwings-username",
            "password" : "your-carwings-password"
        },
        {
            "accessory": "XfinityHome",
            "name": "Xfinity Home",
            "description": "This shim supports the 'Xfinity Home' security system. Unfortunately I don't know how to generate the 'dsig' property, so you'll need to figure yours out by running the Xfinity Home app on your iOS device while connected to a proxy server like Charles. If you didn't understand any of that, sorry! I welcome any suggestions for how to figure out dsig automatically.",
            "email": "your-comcast-email@example.com",
            "password": "your-comcast-password",
            "dsig": "your-digital-signature",
            "pin": "your-security-system-pin-code"
        },
         {
            "accessory": "HomeMatic",
            "name": "Light",
            "description": "Control HomeMatic devices (The XMP-API addon for the CCU is required)",
            "ccu_id": "The XMP-API id of your HomeMatic device",
            "ccu_ip": "The IP-Adress of your HomeMatic CCU device"
        },
        {
            "accessory": "X10",
            "name": "Lamp",
            "ip_address": "localhost:3000",
            "device_id": "E1",
            "protocol": "pl",
            "can_dim": true
        },
        {
            "accessory": "Http",
            "name": "Kitchen Lamp",
            "on_url": "https://192.168.1.22:3030/devices/23222/on",
            "off_url": "https://192.168.1.22:3030/devices/23222/off",
            "brightness_url": "https://192.168.1.22:3030/devices/23222/brightness/%b",
            "http_method": "POST"
        },{
            "accessory": "ELKM1",
            "name": "Security System",
            "description": "Allows basic control of Elk M1 security system. You can use 1 of 3 arm modes: Away, Stay, Night. If you need to access all 3, create 3 accessories with different names.",
            "zone": "1",
            "host": "192.168.1.10",
            "port": "2101",
            "pin": "1234",
            "arm": "Away"
        }
    ]
}
true
total 160
drwx---rwx  20 root   501    680 Jul  6 07:05 .
drwxr-xr-x@ 57 Steve  501   1938 Jul  6 07:04 ..
-rwx--xrw-@  1 root   501   6148 Jul  6 07:02 .DS_Store
drwx---rwx  15 root   501    510 Jul  6 06:59 .git
-rwx--xrw-   1 root   501    127 Jun 30 08:56 .gitignore
-rwx--xrw-   1 root   501    100 Jun 30 08:56 .gitmodules
-rwx--xrw-   1 root   501  10172 Jul  6 07:01 LICENSE
-rwx--xrw-   1 root   501   9127 Jul  6 07:01 README.md
drwx---rwx  12 root   501    408 Jul  6 07:01 accessories
-rwx--xrw-   1 root   501   7755 Jun 30 10:05 app.js
-rwx--xrw-   1 root   501   5096 Jun 30 08:56 config-sample.json
-rwx--xrw-@  1 root   501   5508 Jun 30 10:30 config.json
drwx---rwx  14 root   501    476 Jul  6 06:59 homebridge
drwx---rwx   4 root   501    136 Jul  6 06:59 lib
drwx---rwx  12 root   501    408 Jul  6 06:59 node_modules
-rw-r--r--   1 Steve  501   1661 Jul  6 07:04 npm-debug.log
-rwx--xrw-   1 root   501    536 Jul  6 07:01 package.json
drwx---rwx   2 root   501     68 Jul  6 07:01 persist
drwx---rwx   7 root   501    238 Jul  6 07:01 platforms
-rw-r--r--   1 root   501   5528 Jul  6 07:05 test.log

**Comment by nfarina** [comment]
What text editor are you using to edit your `config.json` file? It looks like you may be using something like Word because I'm noticing some "Smart Quote" characters:

![screen shot 2015-07-06 at 7 36 39 am](https://cloud.githubusercontent.com/assets/117280/8524743/e312a846-23b1-11e5-9500-a005e3a3609a.png)

These won't work in JSON files - the quotes should all look "straight" like the ones around the word "Wink".

Try using a "pure text" editor like Sublime Text or Atom.

**Comment by steve772** [comment]
I will try that. I used text edit.

**Comment by madmod** [comment]
It also looks like you have non standard quotes in the lift master section of config.json.

**Comment by steve772** [comment]
ok all set...thanks for all of your help!

**Comment by jaysettle** [comment]
Hope this is still open. I can get homebridge to show up in numerous iphone apps like Insteon, iDevices, myHome+ and Eve however I never see the accessories. I have taken care to create and edit the config.json file in atom and notepad++ due to the earlier comments but still no accessories.

I've installed node with homebridge and homebridge-particle plugin on mac osx with success on seeing the homebridge server only - no accessories.

So then I tried the raspberry pi with node and homebridge and the homebridge-http plugin and still success with seeing the homebridge server but no accessories. 

I'm using homebridge version 0.3.4 and iOS version 9.3.2. I've tried rebooting all devices and servers, I'm running homebridge from within /usr/local/lib/node_modules/homebridge. I'm using a raspberry pi version 2 with a particle photon.
https://store.particle.io/

After running homebridge I see:
![image](https://cloud.githubusercontent.com/assets/603364/16753625/5a6e729a-47b9-11e6-99fa-9c834944aa55.png)

My config.json file:
![image](https://cloud.githubusercontent.com/assets/603364/16753622/3ddd560a-47b9-11e6-8310-f9b51f9b04dd.png)

**Comment by jaysettle** [comment]
I figured it out looking at issue #641. The config.json I created should end up in /home/pi/.homebridge
![image](https://cloud.githubusercontent.com/assets/603364/16782727/e0054006-484e-11e6-8ae1-0eea271ab20d.png)

Sorry for hijacking a closed thread!
