### ISSUE TITLE
Bug with lockitron plugin example

### ISSUE THREAD

**Issue by fahrvergnuugen** [nfarina/homebridge#490]
I used the lockitron plugin example as a template to create my own. I kept getting a seemingly random homebridge crash with a fatal error:

```bash
/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:11
      throw new Error("This callback function has already been called by someone else; it can only be called one time.");
      ^
```
I took me a while to figure this out, but the reason is because the example I copied binds the "get" event twice! The culprit is [line 25 of example-plugins/homebridge-lockitron/index.js](https://github.com/nfarina/homebridge/blob/master/example-plugins/homebridge-lockitron/index.js#L25):

```javascript
 this.service
    .getCharacteristic(Characteristic.LockCurrentState)
    .on('get', this.getState.bind(this));
  
  this.service
    .getCharacteristic(Characteristic.LockTargetState)
    .on('get', this.getState.bind(this))
    .on('set', this.setState.bind(this));
}
```

I suggest removing line 25 to prevent some other poor soul from repeating my mistake :)

**Comment by snowdd1** [comment]
Sorry, I don't grok it. I read two characteristics (current and target) and two distinct events (get and set). 
Can you elaborate a little further what the culprit is supposed to be?

**Comment by fahrvergnuugen** [comment]
@snowdd1 You are right, I totally missed that they are different characteristics until you just pointed it out!
