### ISSUE TITLE
I tried everything and I give up

### ISSUE THREAD

**Issue by ro8in** [nfarina/homebridge#492]
There is just no way I can get this running on my raspberry pi. I got NodeJS 4.2.6 running and I can't find any way to downgrade to 0.12.9.. With NodeJS 4.2.6 there is no way of getting it to work or even run the npm install command. I just receive error after error..

Is there someone who can tell me how to dowgrade to a NodeJS version that works or how to get this working with NodeJS 4.2.6 ??

**Comment by KhaosT** [comment]
@ro8in what's the error you get? homebridge should work with nodejs 0.12.0 and higher. I tested both 4.2.6 and 5.5.0....

**Comment by julianfez** [comment]
To delete node try
sudo rm -rf /usr/local/bin/npm /usr/local/share/man/man1/node* /usr/local/lib/dtrace/node.d ~/.npm ~/.node-gyp /opt/local/bin/node opt/local/include/node /opt/local/lib/node_modules

**Comment by ro8in** [comment]
Ok so I got 0.12.6 working now and I run npm install it does allot of things and seems to finish without error.. But then its as if it didn't do anything. When i run npm run start it just gives me an error that there is no script called start

**Comment by ro8in** [comment]
If I run now again npm install in the homebridge folder it finishes really fast and just gives me the following warning

npm WARN package.json homebridge@0.2.16 No license field.

**Comment by ro8in** [comment]
Here is the complete output of "npm install"

`pi@raspberrypi ~/homebridge $ npm install
npm WARN package.json homebridge@0.2.16 No license field.
|
> curve25519@1.1.0 install /home/pi/homebridge/node_modules/hap-nodejs/node_modules/curve25519
> node-gyp rebuild

make: Entering directory '/home/pi/homebridge/node_modules/hap-nodejs/node_modules/curve25519/build'
  CXX(target) Release/obj.target/curve/node_curve.o
  SOLINK_MODULE(target) Release/obj.target/curve.node
  COPY Release/curve.node
make: Leaving directory '/home/pi/homebridge/node_modules/hap-nodejs/node_modules/curve25519/build'

> bignum@0.11.0 install /home/pi/homebridge/node_modules/hap-nodejs/node_modules/srp/node_modules/bignum
> node-gyp configure build

make: Entering directory '/home/pi/homebridge/node_modules/hap-nodejs/node_modules/srp/node_modules/bignum/build'
  CXX(target) Release/obj.target/bignum/bignum.o
  SOLINK_MODULE(target) Release/obj.target/bignum.node
  COPY Release/bignum.node
make: Leaving directory '/home/pi/homebridge/node_modules/hap-nodejs/node_modules/srp/node_modules/bignum/build'

> ed25519@0.0.3 install /home/pi/homebridge/node_modules/hap-nodejs/node_modules/ed25519
> node-gyp rebuild

make: Entering directory '/home/pi/homebridge/node_modules/hap-nodejs/node_modules/ed25519/build'
  CC(target) Release/obj.target/ed25519/src/ed25519/keypair.o
  CC(target) Release/obj.target/ed25519/src/ed25519/sign.o
  CC(target) Release/obj.target/ed25519/src/ed25519/open.o
  CC(target) Release/obj.target/ed25519/src/ed25519/crypto_verify_32.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_double_scalarmult.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_frombytes.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_scalarmult_base.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_precomp_0.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_p2_0.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_p2_dbl.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_p3_0.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_p3_dbl.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_p3_to_p2.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_p3_to_cached.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_p3_tobytes.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_madd.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_add.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_msub.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_sub.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_p1p1_to_p3.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_p1p1_to_p2.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_tobytes.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_0.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_1.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_cmov.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_copy.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_neg.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_add.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_sub.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_mul.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_sq.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_sq2.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_invert.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_tobytes.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_isnegative.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_isnonzero.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_frombytes.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_pow22523.o
  CC(target) Release/obj.target/ed25519/src/ed25519/sc_reduce.o
  CC(target) Release/obj.target/ed25519/src/ed25519/sc_muladd.o
  CXX(target) Release/obj.target/ed25519/src/ed25519.o
  SOLINK_MODULE(target) Release/obj.target/ed25519.node
  COPY Release/ed25519.node
make: Leaving directory '/home/pi/homebridge/node_modules/hap-nodejs/node_modules/ed25519/build'

> mdns@2.2.11 install /home/pi/homebridge/node_modules/hap-nodejs/node_modules/mdns
> node-gyp rebuild

make: Entering directory '/home/pi/homebridge/node_modules/hap-nodejs/node_modules/mdns/build'
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_browse.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_enumerate_domains.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_get_addr_info.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_process_result.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_ref.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_ref_deallocate.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_ref_sock_fd.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_register.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_resolve.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_update_record.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/mdns_utils.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/network_interface.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/socket_watcher.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_ref.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_create.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_deallocate.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_set_value.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_get_length.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_buffer_to_object.o
  SOLINK_MODULE(target) Release/obj.target/dns_sd_bindings.node
  COPY Release/dns_sd_bindings.node
make: Leaving directory '/home/pi/homebridge/node_modules/hap-nodejs/node_modules/mdns/build'
semver@5.0.3 node_modules/semver

commander@2.8.1 node_modules/commander
└── graceful-readlink@1.0.1

chalk@1.1.1 node_modules/chalk
├── escape-string-regexp@1.0.4
├── supports-color@2.0.0
├── ansi-styles@2.1.0
├── strip-ansi@3.0.0 (ansi-regex@2.0.0)
└── has-ansi@2.0.0 (ansi-regex@2.0.0)

hap-nodejs@0.1.1 node_modules/hap-nodejs
├── debug@2.2.0 (ms@0.7.1)
├── node-persist@0.0.6 (mkdirp@0.3.5, q@1.1.2)
├── curve25519@1.1.0 (bindings@1.2.1, nan@2.2.0)
├── srp@0.2.0 (bignum@0.11.0)
├── ed25519@0.0.3 (bindings@1.2.1, nan@2.2.0)
└── mdns@2.2.11 (bindings@1.2.1, nan@2.1.0)`

**Comment by ro8in** [comment]
And then if I ls in the homebridge folder i see only the following files

pi@raspberrypi ~/homebridge $ ls -l
total 48
drwxr-xr-x 2 pi pi  4096 Jan 28 19:36 bin
-rw-r--r-- 1 pi pi   599 Jan 28 19:36 config-sample.json
drwxr-xr-x 3 pi pi  4096 Jan 28 19:36 example-plugins
drwxr-xr-x 2 pi pi  4096 Jan 28 19:36 lib
-rw-r--r-- 1 pi pi 10172 Jan 28 19:36 LICENSE
drwxr-xr-x 7 pi pi  4096 Jan 28 19:36 node_modules
-rw-r--r-- 1 pi pi   774 Jan 28 19:36 package.json
-rw-r--r-- 1 pi pi 10318 Jan 28 19:36 README.md

**Comment by damianromanowski** [comment]
Try doing a global install: `npm install -g homebridge` and running `DEBUG=* homebridge -D` in your home dir `~/`

**Comment by ro8in** [comment]
I actually managed to get it running by just typing the command homebridge.. Why is every tutorial saying npm start run in the same folder?? Are those outdated or so?

**Comment by KhaosT** [comment]
@ro8in which tutorial are you referring to?

**Comment by ro8in** [comment]
For example this one

https://www.domoticz.com/wiki/Homekit_Siri

**Comment by damianromanowski** [comment]
We should create some _official_ steps in the wiki. That may alleviate the amount of install issues that open up.

**Comment by snizzleorg** [comment]
I think the easiest way to get it running is through docker:

https://github.com/patrickbusch/homebridge-docker

all the node stuff etc is working in this docker image

**Comment by ro8in** [comment]
I completely agree. Im ussually pretty good at this. I can get most stuff running without reading even half the manual.. I got over 15 years of linux expirience and this was the first time in years i was pulling my hairs out and took my personal walk of shame to ask for help on the forums..
But to be honest most atleast domoticz related homebridge install tutorials mention exactly the same way, use npm run start to start it up.. I would love to help to write this on the wiki, but in all honesty I did so many things today im not sure now anymore what was good and not..

**Comment by ro8in** [comment]
Haven't checked tho but not sure if theres docker available on raspbian yet..

**Comment by snizzleorg** [comment]
it is. I have it running on mine. http://blog.hypriot.com/getting-started-with-docker-on-your-arm-device/
