### ISSUE TITLE
Homebridge Nest Username Invalid

### ISSUE THREAD

**Issue by mazmaximus** [nfarina/homebridge#496]
I'm brand new to Homebridge.  I've followed the instructions to the letter but this is the error I'm getting...

Loaded plugin: homebridge-nest
Registering platform 'homebridge-nest.Nest'
/usr/local/lib/node_modules/homebridge/lib/server.js:132
      throw new Error('Not a valid username: ' + username + '. Must be 6 pairs of colon-' +
      ^
Error: Not a valid username: undefined. Must be 6 pairs of colon-separated hexadecimal chars (A-F 0-9), like a MAC address.
    at Server._loadConfig (/usr/local/lib/node_modules/homebridge/lib/server.js:132:13)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:25:23)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:23:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

This is the config file I've used...

	"bridge": {
		"name": "Homebridge",
		"pin": "987-65-432"
	},

	"platforms": [{
		"platform": "Nest",
		"username": "*****@***.com",
        "password": "*********"
	}]
}

Any idea why this isn't working?

**Comment by KraigM** [comment]
You are missing the username in the bridge config.  See the README.

**Comment by KraigM** [comment]
https://github.com/nfarina/homebridge/blob/master/config-sample.json

**Comment by mazmaximus** [comment]
Thanks for the reply, but where do I get the username?  Is it exactly like the example you provided?  Same question about the port?

**Comment by KraigM** [comment]
Its nothing specific.  You can just use the default.  Its just how HomeKit identifies that particular homebridge instance from other HomeKit devices

**Comment by KraigM** [comment]
I think the port is defaulted, but same as username, you can set it to what you want.  Its which port HomeBridge will run on on your machine.

**Comment by mazmaximus** [comment]
Great, that totally worked! Any idea why its displaying my temp is Celsius?

**Comment by KraigM** [comment]
What is your Nest set to (Im assuming F but just checking :stuck_out_tongue_winking_eye:) and what app are you using on iOS?

**Comment by mazmaximus** [comment]
No luck getting Homebridge running.  Well I take that back, I'm just sure if it's running.  I've tried to check Bonjour Browser but don't see Homebridge listed anywhere.  I'm trying to get my iPhone to see the server and it's just not.  I've tried the fixes of clearing the IOS homekit files and resetting my device but both of the homekit programs I've bought, ('Devices' and 'Home') have failed.

Also when I run the "homebridge" command in the Terminal I'm getting this error...

...
Fetching Nest devices.
[Error: You did not specify {'token'} or {'clientId','clientSecret','code'}, one set of which is required for the new API]
Falling back to legacy API.

Could this be why I'm not getting it running? If so any idea how to fix this?

**Comment by damianromanowski** [comment]
Follow the steps here to make use of the [new api](https://github.com/kraigm/homebridge-nest#how-to-setup-new-api)

**Comment by kapilmalhotra** [comment]
Tried following the API steps but not able to connect Nest in Homebridge iOS app.

My config.json looks like below:

{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    
    "description": "sample desc"

    "platforms": [
        {
            "platform" : "Nest",
            "name" : "Nest",
            "username": "myemailid@email.com",
        	"password": "myNestdotcompassword",
            "clientId" : "1234567890",
            "clientSecret" : "1234567890xyz",
            "code" : "validcodefromauthenticationurl",
            "token" : "c.FM.................."
        }
    ]
}


When i run homebridge i see this in console:

$ homebridge
[3/12/2017, 2:43:33 PM] Loaded plugin: homebridge-nest
[3/12/2017, 2:43:33 PM] Registering platform 'homebridge-nest.Nest'
[3/12/2017, 2:43:33 PM] ---
[3/12/2017, 2:43:33 PM] Loaded config.json with 0 accessories and 1 platforms.
[3/12/2017, 2:43:33 PM] ---
[3/12/2017, 2:43:33 PM] Loading 1 platforms...
[3/12/2017, 2:43:33 PM] [Nest] Initializing Nest platform...
[3/12/2017, 2:43:33 PM] [Nest] Fetching Nest devices.
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[3/12/2017, 2:43:36 PM] Homebridge is running on port 51826.


on my phone i am doing below:
1. Edit > Create New Room 
2. Tap on Homebridge > Add Anyway > Enter Code Manually > 03145154
3. Keeps spinning and then at the end gives error message that it could not add my device.

Please let me know if I am doing something wrong here.
