### ISSUE TITLE
cant get it to work on windows 10

### ISSUE THREAD

**Issue by notdave1** [nfarina/homebridge#498]
followed directions from https://github.com/nfarina/homebridge/wiki/Install-Homebridge-on-Windows:-New-version-(with-Plugin)

I used the sample-config.json file. I just removed the sample- from the title
heres my output

Loaded plugin: homebridge-http
Registering accessory 'homebridge-httpstatus.Http'
---
Loaded plugin: homebridge-wol
Registering accessory 'homebridge-wol.Computer'
---
There was a problem reading your config.json file.
Please try pasting your config.json file here to validate it: http://jsonlint.co
m

C:\Users\daveh\AppData\Roaming\npm\node_modules\homebridge\lib\server.js:124
    throw err;
    ^

SyntaxError: Unexpected token

    at Object.parse (native)
    at Server._loadConfig (C:\Users\daveh\AppData\Roaming\npm\node_modules\homeb
ridge\lib\server.js:118:19)
    at new Server (C:\Users\daveh\AppData\Roaming\npm\node_modules\homebridge\li
b\server.js:25:23)
    at module.exports (C:\Users\daveh\AppData\Roaming\npm\node_modules\homebridg
e\lib\cli.js:23:3)
    at Object.<anonymous> (C:\Users\daveh\AppData\Roaming\npm\node_modules\homeb
ridge\bin\homebridge:17:22)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)

# don't know what I am doing wrong

heres my config 

{
     "bridge": {
        "name": "HomeBridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    
    "description": "HomeBridge HTTP Status Control",

    "accessories": [ {
		"accessory": "Http",
		"name": "Alfresco Lamp",
		"switchHandling": "yes",
		"http_method": "GET",
		"on_url":      "http://localhost/controller/1700/ON",
		"off_url":     "http://localhost/controller/1700/OFF",
		"status_url":  "http://localhost/status/100059",
		"service": "Light",
		"brightnessHandling": "yes",
		"brightness_url":     "http://localhost/controller/1707/%b",
		"brightnesslvl_url":  "http://localhost/status/100054",
		"username" : "",
		"password" : "",
		"sendimmediately": "","
									    
       } 
    ]
}

**Comment by KhaosT** [comment]
``    "sendimmediately": "","`` < there is an extra " at the end.

**Comment by notdave1** [comment]
i get the same error

C:\Users\daveh\AppData\Roaming\npm\node_modules\homebridge\bin>node homebridge
Loaded plugin: homebridge-http
Registering accessory 'homebridge-httpstatus.Http'
---
Loaded plugin: homebridge-wol
Registering accessory 'homebridge-wol.Computer'
---
There was a problem reading your config.json file.
Please try pasting your config.json file here to validate it: http://jsonlint.co
m

C:\Users\daveh\AppData\Roaming\npm\node_modules\homebridge\lib\server.js:124
    throw err;
    ^

SyntaxError: Unexpected token }
    at Object.parse (native)
    at Server._loadConfig (C:\Users\daveh\AppData\Roaming\npm\node_modules\homeb
ridge\lib\server.js:118:19)
    at new Server (C:\Users\daveh\AppData\Roaming\npm\node_modules\homebridge\li
b\server.js:25:23)
    at module.exports (C:\Users\daveh\AppData\Roaming\npm\node_modules\homebridg
e\lib\cli.js:23:3)
    at Object.<anonymous> (C:\Users\daveh\AppData\Roaming\npm\node_modules\homeb
ridge\bin\homebridge:17:22)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)

C:\Users\daveh\AppData\Roaming\npm\node_modules\homebridge\bin>

removed the extra " like you said

{
     "bridge": {
        "name": "HomeBridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },

    "description": "HomeBridge HTTP Status Control",

    "accessories": [ {
		"accessory": "Http",
		"name": "Alfresco Lamp",
		"switchHandling": "yes",
		"http_method": "GET",
		"on_url":      "http://localhost/controller/1700/ON",
		"off_url":     "http://localhost/controller/1700/OFF",
		"status_url":  "http://localhost/status/100059",
		"service": "Light",
		"brightnessHandling": "yes",
		"brightness_url":     "http://localhost/controller/1707/%b",
		"brightnesslvl_url":  "http://localhost/status/100054",
		"username" : "",
		"password" : "",
		"sendimmediately": "",

       }
    ]
}

**Comment by KhaosT** [comment]
Try this?
```json
{
	"bridge": {
		"name": "HomeBridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},

	"description": "HomeBridge HTTP Status Control",

	"accessories": [{
		"accessory": "Http",
		"name": "Alfresco Lamp",
		"switchHandling": "yes",
		"http_method": "GET",
		"on_url": "http://localhost/controller/1700/ON",
		"off_url": "http://localhost/controller/1700/OFF",
		"status_url": "http://localhost/status/100059",
		"service": "Light",
		"brightnessHandling": "yes",
		"brightness_url": "http://localhost/controller/1707/%b",
		"brightnesslvl_url": "http://localhost/status/100054",
		"username": "",
		"password": "",
		"sendimmediately": ""
	}]
}
```

**Comment by notdave1** [comment]
SUCCESS!
C:\Windows\system32>cd C:\Users\daveh\AppData\Roaming\npm\node_modules\homebridg
e\bin

C:\Users\daveh\AppData\Roaming\npm\node_modules\homebridge\bin>node homebridge
Loaded plugin: homebridge-http
Registering accessory 'homebridge-httpstatus.Http'
---
Loaded plugin: homebridge-wol
Registering accessory 'homebridge-wol.Computer'
---
Loaded config.json with 1 accessories and 0 platforms.
---
Loading 1 accessories...
[Alfresco Lamp] Initializing Http accessory...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:


    ┌────────────┐
    │ 031-45-154 │
    └────────────┘

Homebridge is running on port 51826.

thank you so much!

what was I doing wrong?

**Comment by damianromanowski** [comment]
Your config had a trailing comma after `"sendimmediately": ""*,*`

**Comment by notdave1** [comment]
Thank you both for helping me out. I have no programming background so I had no idea how to read the config file. Now that homebridge is functioning I am attempting to pair it with domoticz. I have an Aeon wall plug in that is coming in the mail which I want to control my lamp so I am excited to try and set it up. I will report back just in case someone is interested
