### ISSUE TITLE
Siri Name (eg: via Eve App)

### ISSUE THREAD

**Issue by PatchworkBoy** [nfarina/homebridge#499]
Morning guys - I’ve hunted thru the whole bridged mode migration posts in the wiki etc and wandered through all the issues here but not found this mentioned.

Prior to the homebridge migration to bridged by default, some apps (notably the Elgato Eve app) permitted you to define a Siri Name per accessory which was separate to the defined accessory name. In bridged mode, this option vanishes and accessory names are static.

Is this inherent to running as a bridge? Is there any way to get this functionality back, or does that require NOT running bridged by default & if so, how does one not run in bridged mode? Omitting the bridge object from config.json simply results in an error referring to username not being set.

Reason for asking? Some folks are reverting back to older versions of homebridge pre-the bridging mode thang just to get this feature back, and going back to per accessory detection.

**Comment by KhaosT** [comment]
"Siri Name" exposed in most of apps is refers to Service name in HomeKit. The app should always allow you to change the service name no matter if it's bridged or not. I check the Eve app and under Settings > Accessories I can still change the bridged accessory's Siri Name there.

**Comment by PatchworkBoy** [comment]
Hmmm - I & others cannot. Can you spot anything in my code that would be stopping this?? https://github.com/patchworkboy/homebridge-eDomoticz

**Comment by PatchworkBoy** [comment]
S’ok - hint was enough - this.name not being passed to new Service instance - all fixed!
