### ISSUE TITLE
Stimm for HTTPREQUEST ?

### ISSUE THREAD

**Issue by petkoe** [nfarina/homebridge#5]
Hi, is it possible to do a shimm for a httprequest? 

Peter

**Comment by tommyd75** [comment]
Here's what I used. 


  sType: types.LIGHTBULB_STYPE, 
    characteristics: [{
    	cType: types.NAME_CTYPE,
    	onUpdate: null,
    	perms: ["pr"],
		format: "string",
		initialValue: "Kitchen Light",
		supportEvents: false,
		supportBonjour: false,
		manfDescription: "Bla",
		designedMaxLength: 255   
    },{
        cType: types.POWER_STATE_CTYPE,
    	
               onUpdate: function(value)
{
    target = "off";
    if (value === true) {
        target = "on";
    }
    request("http://192.168.1.1/kitchen"+target);
},

**Comment by nfarina** [comment]
It would be great to have this as an official "accessory"! Where you could set the target URL in the `config.json`.

**Comment by tocks53** [comment]
Hello,
I also want to launch a http.

You can add an example in the config.json

thank you

**Comment by nfarina** [comment]
Closed by #26!
