### ISSUE TITLE
dns service error

### ISSUE THREAD

**Issue by m0rph13** [nfarina/homebridge#501]
Dear sir,
First of all, thank you for an awesome project! I had lots of fun using it with Z-way on my Raspberry PI.
This weekend I decided to try out Domoticz , so I fetched the image (domoticz-raspberrypi-sdcard-3530) and set it all up according to instructions.
When It was time to enable homebridge I ran into some unexpeced problems though:

> [Domoticz] Initializing Domoticz platform...
> [Domoticz] Fetching Domoticz lights and switches...
> Loading 0 accessories...
> [Domoticz] Initializing device with name Hörnlampa...
> [Domoticz] Loaded services for Hörnlampa
> Cannot find secret key, creating One...
> /home/pi/homebridge/lib/HAP-NodeJS/node_modules/mdns/lib/advertisement.js:56
>   dns_sd.DNSServiceRegister(self.serviceRef, flags, ifaceIdx, name,
>          ^
> Error: dns service error: unknown
>     at Error (native)
>     at new Advertisement (/home/pi/homebridge/lib/HAP-NodeJS/node_modules/mdns/lib/advertisement.js:56:10)
>     at Object.create [as createAdvertisement] (/home/pi/homebridge/lib/HAP-NodeJS/node_modules/mdns/lib/advertisement.js:64:10)
>     at Object.startAdvertising (/home/pi/homebridge/lib/HAP-NodeJS/Advertiser.js:7:28)
>     at Object.publishAccessory (/home/pi/homebridge/lib/HAP-NodeJS/Accessory.js:10:29)
>     at createHAPServer (/home/pi/homebridge/app.js:167:15)
>     at /home/pi/homebridge/app.js:92:17
>     at Request._callback (/home/pi/homebridge/platforms/Domoticz.js:68:6)
>     at Request.self.callback (/home/pi/homebridge/node_modules/request/request.js:373:22)
>     at Request.emit (events.js:110:17)

> The debug says:
> 0 info it worked if it ends with ok
> 1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'start' ]
> 2 info using npm@2.5.1
> 3 info using node@v0.12.1
> 4 verbose run-script [ 'prestart', 'start', 'poststart' ]
> 5 info prestart homebridge@0.0.0
> 6 info start homebridge@0.0.0
> 7 verbose unsafe-perm in lifecycle true
> 8 info homebridge@0.0.0 Failed to exec start script
> 9 verbose stack Error: homebridge@0.0.0 start: `node app.js`
> 9 verbose stack Exit status 1
> 9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
> 9 verbose stack     at EventEmitter.emit (events.js:110:17)
> 9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:14:12)
> 9 verbose stack     at ChildProcess.emit (events.js:110:17)
> 9 verbose stack     at maybeClose (child_process.js:1008:16)
> 9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
> 10 verbose pkgid homebridge@0.0.0
> 11 verbose cwd /home/pi/homebridge
> 12 error Linux 4.1.13-v7+
> 13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
> 14 error node v0.12.1
> 15 error npm  v2.5.1
> 16 error code ELIFECYCLE
> 17 error homebridge@0.0.0 start: `node app.js`
> 17 error Exit status 1
> 18 error Failed at the homebridge@0.0.0 start script 'node app.js'.
> 18 error This is most likely a problem with the homebridge package,
> 18 error not with npm itself.
> 18 error Tell the author that this fails on your system:
> 18 error     node app.js
> 18 error You can get their info via:
> 18 error     npm owner ls homebridge
> 18 error There is likely additional logging output above.
> 19 verbose exit [ 1, true ]

Is it node_mdns that is acting up? Seen it before?

**Comment by rudders** [comment]
Have you installed avahi?
Check out that section in the wiki Page.
https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi

**Comment by m0rph13** [comment]
Thank you Rudders!
No, the issue seems to have been that the homebride distribution with Domoticz was very, very old. I'll just remove it and install standard homebride with the new shiny Domoticz plugin :)
