### ISSUE TITLE
Run homebridge on VM?

### ISSUE THREAD

**Issue by DumbAsABrick** [nfarina/homebridge#503]
Is it possible to run this on an Ubuntu Server v.15 VM? (Specifically using Oracle VM Virtualbox.)

I've installed it twice over, I get no errors, it says that it's running, but my phone can't for the life of it find the homebridge! Nothing I do gets it to work.

Can you help? I'm kind of stupid when it comes to Linux, but if you can tell me what to do to get log files, I'll post them up here.

Thanks.

**Comment by AppleTechy** [comment]
What os are you running the VM on? Mac or Windows? And yes you should be
able to get it running. Did you install the libavahi-compat-libdnssd-dev
package? And where you able to successfully install homebridge and its
config file?

**Comment by KhaosT** [comment]
Since it's in the VM, please make sure your VM forward the multicast packets to the actual network (instead of the one shared between VM and host)

**Comment by AppleTechy** [comment]
@khaosT I found that on Mac VMWare The Wemo plugin doesn't work as it
doesn't forward the UPnDP that is needed for it to work. Not sure why you
wouldn't just install on your base OS on the computer...?

**Comment by DumbAsABrick** [comment]
Thanks for the quick replies!

> What os are you running the VM on? Mac or Windows?

I'm running the VM on Win 7 64-bit. 

>Did you install the libavahi-compat-libdnssd-dev
package?

Affirmative!

>And where you able to successfully install homebridge and its
config file?

I'm able to get it all running, edited the config file, and it says:

![image](https://cloud.githubusercontent.com/assets/16998722/12709373/251d0440-c860-11e5-8821-3c51cf0a66f0.png)

I edited the file based on this article: https://c4drivers.wordpress.com/2015/10/28/homekit-for-control4/

And here's what my config.json looks like:

![image](https://cloud.githubusercontent.com/assets/16998722/12709389/5c6d4946-c860-11e5-8109-aeba88f2f85b.png)

**Comment by KhaosT** [comment]
It looks alright, what's the IP address of the VM? (ifconfig)

**Comment by DumbAsABrick** [comment]
IP is 192.168.0.10.

**Comment by KhaosT** [comment]
and on iOS device can you access http://192.168.0.10:51826/accessories?

**Comment by DumbAsABrick** [comment]
Nope! Can't get to it via my iPhone.

**Comment by KhaosT** [comment]
If so, you may want to check your network... make sure other devices on your network can access your VM.

**Comment by DumbAsABrick** [comment]
OK! Thank you for your help! That narrowed it down quite a bit. 

Got it fixed! The issue was that I had set the network settings in the VM Manager, but not for the Virtualbox program itself. D'oh! Now it has no issue at all connecting to the homebridge (using the bridged connection).

**Comment by KhaosT** [comment]
:) Glad to know you were able to solve the problem.
I'll close the issue for now.

**Comment by gielk** [comment]
Is it possible that u share your vmware machine ? because i can not get it working.
