### ISSUE TITLE
Question Regarding door/Window Sensors

### ISSUE THREAD

**Issue by jndizoglio** [nfarina/homebridge#504]
I have a home server running ubuntu and homebridge. It works flawlessly! I currently have homebridge linked to my nests, and my harmony hub and my smarthings hub V2. (homebridge-legacy-plugins....homebridge-nest....homebridge-harmonyhub) also running ("hello homebridge" and "JSON api"  smart apps on smarthings) I am currently able to use siri to control my nests, harmony hub and wave lights. I was wondering if there was a way to support my Z-wave Door/Window Sensors in homekit? I do not see them pop up as a device. I understand there are three options in home kit for these sensors ("door" "window" and "contact sensor") Is there any homebridge-plugin that will allow home kit to see my door/window sensors in homekit?

**Comment by pdlove** [comment]
I just uploaded the change for that to my platform plugin: https://github.com/pdlove/homebridge-smartthings/
It still needs more testing before I make a release of it, but I'm expanding all of the smartthings types I can.

**Comment by jndizoglio** [comment]
pdlove, you are a god! I will test this out as soon as I get home. Good luck to your upcoming npm release! If you need help beta testing anything definitely PM me and I can help!

**Comment by pdlove** [comment]
Quick warning... You MUST install my JSON smart app as opposed to the old one. Mine is much more complete and is not compatible.

**Comment by jndizoglio** [comment]
That makes complete sense! (Looking at the old JSON API code it only supports switches and hues) I'll be testing you JSON-COMPLETE-API tonight...Thanks again!

**Comment by jndizoglio** [comment]
That makes complete sense! (Looking at the old JSON API code it only supports switches and hues) I'll be testing your JSON-COMPLETE-API tonight...Thanks again!

**Comment by orctrial** [comment]
Any updates on this? I am in the same situation- want to monitor and get status updates on zwave door sensors that I have running with Openremote controller. 

Lights and switches seems to work great with homebridge and Home app
