### ISSUE TITLE
How to pass a value with Siri? (setting iTunes / media player volume)

### ISSUE THREAD

**Issue by oa-** [nfarina/homebridge#505]
How do I pass a value to homebridge so a plugin can process it?

In my case the volume of a media player (iTunes) needs to be adjusted.

Ideally it should work like this:
"Set the volume of the iTunes to 50"
which then sets the volume slider to 50 %.

I have installed dansays/homebridge-applescript, but I can only turn a (virtual) device on or off.

**Comment by dermotos** [comment]
It would need to be a device type that supports dimming. Best one would probably be a dimmable bulb. You can set their brightness via Siri. Take a look at the homebridge philips hue plugin to see how dimmable bulbs are implemented.

**Comment by sean256** [comment]
You can expose a characteristic named volume but siri refuses to interact with it while most homekit apps will display a slider with the name volume and allow you to interact with it. Kind of a bummer.

A work around is to what @dermotos suggested, use the dimmer. But you might feel stupid asking Siri to set the brightness of iTunes lol.

**Comment by maddox** [comment]
> A work around is to what @dermotos suggested, use the dimmer. But you might feel stupid asking Siri to set the brightness of iTunes lol.

Also, Siri will consider it a light, so if you ask it to "Turn on the Family Room lights" it'll turn that media player on too.

**Comment by robertvorthman** [comment]
I can control the volume of my stereo telling Siri "set stereo volume brightness to 50%" because my stereo is exposed as a light bulb with a brightness characteristic.  Using this plugin:

https://www.npmjs.com/package/homebridge-marantz-volume

The same could be done for iTunes, the only downside is you have to use the word brightness in your Siri commands.
