### ISSUE TITLE
Question: Trigger On Temperature

### ISSUE THREAD

**Issue by desvdp** [nfarina/homebridge#507]
Hi All,

I'm facing this silly issue: I created a custom TemperatureSensor accessory (one that monitors the internal temperature of the Raspberry Pi it's running on). The accessory itself runs fine. Problem is I'd like to create a Trigger based on this (i.e. to turn on a warning light or a fan ... ) .

Pretty much it boils down to a service like this:

```
  this.service = new Service.TemperatureSensor(this.name);
  this.service
    .getCharacteristic(Characteristic.CurrentTemperature)
    .on('get', this.getState.bind(this));
```

Does anyone know why the Temperature characteristic doens't show up in when creating a new "Event Trigger" using an app like MyTouchHome. 

In specific I'd like to figure out if:
A- you can't trigger on temperatures (maybe it's a feature that you can set a trigger on CurrentTemperature?)
B- the MyTouchHome app can't configure triggers based on temperature, I need another app
C- I forgot to set a property of the characteristic
D- None of the above

Thanks !

**Comment by KhaosT** [comment]
@desvdp I'm not sure what's wrong with MyTouchHome, you should be able to create event trigger with a read-only characteristic.

**Comment by desvdp** [comment]
@KhaosT I'm not even sure it's a MyTouchHome issue: I have a strong feeling the Event Trigger from is one ove these forms that is common to all apps (one that is provided by Apple themselves) 

Funny enough setting a Trigger on one of the values of my Hue Lamps works fine (also via homebridge)

**Comment by KhaosT** [comment]
@desvdp my guess is MyTouchHome uses the same interface for main UI and trigger creation which doesn't allow you select read-only characteristic. I'd suggest you try a different app (like the "Home" or Apple's HMCatalog)
