### ISSUE TITLE
Question: Workarounds available for having 100+ accessories?

### ISSUE THREAD

**Issue by odelma** [nfarina/homebridge#509]
Hi,

Until yesterday I was still running the old version of Homebridge ( = version without plugins) but finally decided to update. Update itself went quite smoothly (on Raspberry Pi 2), but then I wasn't able to add Homebridge as an accessory to iOS Eve app. It just said "adding the accessory has failed" after inputting the pin code.

Then I found out that there's a limit of 100 accessories per bridge and as the new plugins were also able to handle sensors that were not showing up in Homekit before, I guess it went over the 100 accessory limit. After removing one platform I was then finally able to add Homebridge to Eve. I also found the following statement:

> _Apple’s specs will also allow bridges to connect to other bridges, and each can connect up to 100 accessories, according to Apple’s specs._
> http://9to5mac.com/2015/01/22/apple-details-homekit-compatibility-with-competing-home-automation-platforms/

This raised the question, whether there are any current workarounds available to connect to 100+ accessories with Homebridge? And/or would it be worth investigating if the configuration could be developed so that there could be one master bridge ("Homebridge") and the same way as there are now platforms and accessories under it, there could also be other bridges (with their own platforms and accessories)? If I understand the above quote correctly, it would then allow over 100 accessories under Homebridge. Though I'm not sure would this be doable without some major changes - or is it just impossible altogether...:)

**Comment by KhaosT** [comment]
I'd suggest plugin developer to bundle as many services into a single accessory as they can. Right now most plugins use a 1:1 mapping between physical accessory and HomeKit accessory. Ideally the ratio can be 1:100. Since service is the first class citizen in HomeKit and Siri only cares about service, this won't break the Siri support and we can have about 9,801 devices bridged to HomeKit in the extreme case (HomeKit will probably crash before you reach this limit 😅).

**Comment by justme-1968** [comment]
but this would not allow to have individual reachable states for each device as the reachable characteristic is in a bridging service which is valid for the whole accessory.

**Comment by odelma** [comment]
Interesting - I'll have to check with the developers of the plugins that I use whether they see this as a feasible option. In most cases I think the reachability is tied to the platform so probably the above mentioned would not be a huge problem. Or then I'm missing certain scenarios here (wouldn't be a too big of a surprise :smiley: )...

**Comment by justme-1968** [comment]
i think in most cases the reachability is tied to a device. one hue bulb in many, one sonos player in many, ...

just think of the bridge as bridging :) a whole home automation setup.

**Comment by odelma** [comment]
Yes, I see the point now. I was thinking it from the viewpoint of e.g. Domoticz and Telldus platforms which I currently use. If the platform is reachable, then (in most cases) all devices that can be controlled with the platform are also reachable. But it's very true that in reality this is necessarily not the case...

**Comment by desvdp** [comment]
Hi @KhaosT your answer about "bundling services" intrigues me. Some background: I'm in the "process" of defining a platform for a quite old home automation platform (Nikobus)... really the protocol is quite archaic ... RS232 ;-) . The reason your answer got my attention is that each button in this home automation has it's own address. I was planning to expose each each of them as an accessory in such I can control other things using the buttons of the home automation system by using homekit triggers/events. Unfortunately, as most "wall plates" have at least 4 to 8 buttons, I'll reach the magic number 100 quite easily...

Now, if I understand your comment correctly you're suggesting I should be able to define a "wall plate" as an accessory and then define 8 separate "switch services" as part of that one accessory. Is this a correct assumption? And if so, do you believe current homekit apps would be able to deal with this? 

Thanks for your insights.

**Comment by KhaosT** [comment]
@desvdp Yes, if that's the case, defining a "wall plate" accessory with 8 "switch services" would be the preferable solution. Most of HomeKit apps (Eve, Home ...) support displaying multiple (same) services from a single accessory so it should be fine ^^

**Comment by SteliosMakrinos** [comment]
Would it be possible to enhance homebridge to allow for the configuration of multiple bridges in the config.json file?  That way you can expose more than 1 bridge and specify which plugins belong to each bridge.

**Comment by beorn** [comment]
This may be a "stale" issue, but it's not less an issue, especially when bridging into entire new smarthome ecosystems, e.g., a z-wave smarthome.  I'd be great to see homebridge create multiple bridges by accessory type or some hashing of ids or something like that.
