### ISSUE TITLE
HAP-NodeJS as npm vs submodule

### ISSUE THREAD

**Issue by jason0x43** [nfarina/homebridge#51]
Any particular reason you're including HAP-NodeJS as a submodule rather than an npm dependency? Including it as an npm dependency would simplify the installation process a bit.

**Comment by nfarina** [comment]
Unfortunately HAP-NodeJS is not in npm. Although I support we could make a mirror of it...

**Comment by jason0x43** [comment]
You can just use a git commit as your package reference in the `package.json`. To pin it to the commit you're currently using, it'd be:

```js
"dependencies": {
    ...
    "HAP-NodeJS": "git://github.com/KhaosT/HAP-NodeJS#b130842"
}
```

**Comment by Kosta-Github** [comment]
+1

**Comment by nfarina** [comment]
Wow, TIL! Had no idea. Let me play with this...

**Comment by madmod** [comment]
+1

Also someone who knows HAP-NodeJS should look into submitting a PR with instructions to the owners for submitting to npm. That way we can have a more stable versioned platform to build on.
