### ISSUE TITLE
Multiple iDevices connected to the same iCloud account ?

### ISSUE THREAD

**Issue by devbobo** [nfarina/homebridge#514]
This has worked in the past, but I'm having all sorts of problems getting it to work now.

I have multiple iDevices signed into the same iCloud account, but I can only control HomeKit devices with the iDevice that I configured the homebridge on. All the HomeKit config appears correctly on the other iDevices but device states show as `N/A`.

When I use Eve on the iDevices that aren't working, it says there is a `HomeKit reported a communication failure. Please try again.` and homebridge shows the following....
```
on, 08 Feb 2016 09:32:31 GMT EventedHTTPServer [172.16.1.61] New connection from client
Mon, 08 Feb 2016 09:32:31 GMT EventedHTTPServer [172.16.1.61] HTTP server listening on port 54826
Mon, 08 Feb 2016 09:32:31 GMT EventedHTTPServer [172.16.1.61] HTTP request: /pair-verify
Mon, 08 Feb 2016 09:32:31 GMT HAPServer [B8:27:EB:20:90:E3] HAP Request: POST /pair-verify
Mon, 08 Feb 2016 09:32:31 GMT HAPServer [B8:27:EB:20:90:E3] Pair verify step 1/2
Mon, 08 Feb 2016 09:32:31 GMT EventedHTTPServer [172.16.1.61] HTTP Repsonse is finished
Mon, 08 Feb 2016 09:32:31 GMT EventedHTTPServer [172.16.1.61] HTTP request: /pair-verify
Mon, 08 Feb 2016 09:32:31 GMT HAPServer [B8:27:EB:20:90:E3] HAP Request: POST /pair-verify
Mon, 08 Feb 2016 09:32:31 GMT HAPServer [B8:27:EB:20:90:E3] Pair verify step 2/2
Mon, 08 Feb 2016 09:32:31 GMT HAPServer [B8:27:EB:20:90:E3] Client FBFFC7C1-F5AF-468C-A2BA-C5032BC0FAE9 attempting to verify, but we are not paired; rejecting client
Mon, 08 Feb 2016 09:32:31 GMT EventedHTTPServer [172.16.1.61] HTTP Repsonse is finished
Mon, 08 Feb 2016 09:32:31 GMT EventedHTTPServer [172.16.1.61] Client connection closed
Mon, 08 Feb 2016 09:32:31 GMT EventedHTTPServer [172.16.1.61] HTTP connection was closed
Mon, 08 Feb 2016 09:32:31 GMT EventedHTTPServer [172.16.1.61] HTTP server was closed
```

Any ideas how to resolve this ?

**Comment by tonesto7** [comment]
How are you getting the connection debug output?  I've been wanting to try and debug why my appleTv 3 is not pairing correctly to allow for remote access on my iPhone

**Comment by devbobo** [comment]
@tonesto7 I'm running `DEBUG=* homebridge`

**Comment by KhaosT** [comment]
Based on the log, it looks like HomeKit failed to add the public key for this iOS device. Is the iOS device you're talking about a shared user to the home?

**Comment by devbobo** [comment]
@KhaosT no, not a shared user...the primary account under which the home was created, just a different device

**Comment by devbobo** [comment]
Is there a way to resolve this, other than resetting the HomeKit config and starting again ?

**Comment by KhaosT** [comment]
@devbobo so does home configuration sync works on that iOS device?

**Comment by devbobo** [comment]
I believe it does, as I said in the original post... This has all worked previously....not quite sure why it's failing now.

**Comment by devbobo** [comment]
@KhaosT I should mention that I also have an Eve Room in my HomeKit config and this iDevice (not working with homebridge) appears to be getting device updates just fine.

**Comment by KhaosT** [comment]
@devbobo huh... that's interesting. Maybe try removing homebridge from all iOS devices, change homebridge's username to something else and pair again?

**Comment by devbobo** [comment]
Closing this issue as reconfiguring the HomeKit db seemed to resolve it.
