### ISSUE TITLE
Homebridge stops working after pairing

### ISSUE THREAD

**Issue by tengelmeier** [nfarina/homebridge#516]
Hi, 

I'm trying to get a local Mac install of homebridge to work. 
Final goal is to find out why zway-server vanishes from HomeKit. 
Currently I have 
- installed home bridge
- configured a FakeBulb as accessory
- started the server with DEBUG set on the command line
- paired an iPhone after resetting HomeKit data

It paired, returned an error in the client app and then vanished from the list of new devices to pair (and also the list of paired devices)

How should I proceed to troubleshoot? Are there any request logs? An wiki where I can see how the protocol works?

		$ DEBUG=* /usr/local/bin/homebridge
		Loaded plugin: homebridge-fakebulb
		Registering accessory 'homebridge-fakebulb.FakeBulb'
		---
		Loaded config.json with 1 accessories and 0 platforms.
		---
		Loading 1 accessories...
		[Test lamp] Initializing FakeBulb accessory...
		[Test lamp] Starting a fake bulb device with name 'Lamp1'...
		Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
					   
			┌────────────┐     
			│ [deleted] │     
			└────────────┘     
					   
		  Accessory [Homebridge] Creating new AccessoryInfo for our HAP server +0ms
		  Accessory [Homebridge] Creating new IdentifierCache +5ms
		Homebridge is running on port 51826.
		  EventedHTTPServer Server listening on port 51826 +12ms
		  EventedHTTPServer [::ffff:192.168.-----] New connection from client +4m
		  EventedHTTPServer [::ffff:192.168.-----] HTTP server listening on port 54826 +4ms
		  EventedHTTPServer [::ffff:192.168.-----] HTTP request: /pair-setup +14ms
		  HAPServer [CC:22:3D:-----] HAP Request: POST /pair-setup +1ms
		  HAPServer [CC:22:3D:-----] Pair step 1/5 +4ms
		  EventedHTTPServer [::ffff:192.168.-----] HTTP Repsonse is finished +24ms
		  EventedHTTPServer [::ffff:192.168.-----] HTTP request: /pair-setup +13s
		  HAPServer [CC:22:3D:-----] HAP Request: POST /pair-setup +1ms
		  HAPServer [CC:22:3D:-----] Pair step 2/5 +1ms
		  EventedHTTPServer [::ffff:192.168.-----] HTTP Repsonse is finished +13ms
		  EventedHTTPServer [::ffff:192.168.-----] HTTP request: /pair-setup +12ms
		  HAPServer [CC:22:3D:-----] HAP Request: POST /pair-setup +0ms
		  HAPServer [CC:22:3D:-----] Pair step 3/5 +1ms
		  HAPServer [CC:22:3D:-----] Pair step 4/5 +9ms
		  HAPServer [CC:22:3D:-----] Pair step 5/5 +1ms
		  Accessory [Homebridge] Paired with client 6321FB21-D074-4ABF-A08A-54EAC84841BF +2ms
		  EventedHTTPServer [::ffff:192.168.-----] HTTP Repsonse is finished +3ms
		  EventedHTTPServer [::ffff:192.168.-----] Client connection closed +39ms
		  EventedHTTPServer [::ffff:192.168.-----] HTTP connection was closed +2ms
		  EventedHTTPServer [::ffff:192.168.-----] HTTP server was closed +0ms

**Comment by KhaosT** [comment]
Is that all the logs you got? Look at the logs, it looks pair succeeded but iOS never tries to access accessory attribute database.

**Comment by tengelmeier** [comment]
Yes.. After that the homekit bridge is blacklisted by iOS. Seeing it and repairing was only possible after changing the *username* in config.son

**Comment by KhaosT** [comment]
That's strange... If this happens in the future, can you pull the device log from iOS device?

**Comment by tengelmeier** [comment]
Xcode -> console.log?

**Comment by KhaosT** [comment]
Xcode > Window > Devices > Your iOS Device > Console

**Comment by tengelmeier** [comment]
OK. I'll grab it next time.. Looks like I have only seven minutes of messages cached there..

**Comment by johnschult** [comment]
I have the same situation (I think). I am paired with homebridge using HMCatalog and everything work fine the first time I have Siri do something. After that, the Homebridge and the one accessory I have are grayed out in HMCatalog. I have to clean up and re-pair to get it to ever work again.
