### ISSUE TITLE
Can't start homebridge

### ISSUE THREAD

**Issue by perevers** [nfarina/homebridge#519]
Hi. Have tried searching for an answer to my problem, but without luck,
I have homebridge installed, but i cant seem to start it, every time i try by writing: homebridge i get the same error:
`pi@raspberrypi:~ $ homebridge
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
module.js:341
    throw err;
    ^

Error: Cannot find module './build/Release/bignum'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at new require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/bignum/index.js:4:14)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
pi@raspberrypi:~ $ `

I know the first section dosn't matter, but the last part i dont know how to get by.

node -v: 5.5.0
npm -v: 3.3.12

If you need any other info, please write.

btw im pretty new at this rPI and coding, så pls write any code or suggestens simple :)

Per

**Comment by rudders** [comment]
Have you done this?

sudo apt-get install libavahi-compat-libdnssd-dev

From these instructions.

https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi

**Comment by perevers** [comment]
Hi Have installed that.
But i formated the SD card and startet from scratch. and now i can start homebridge. So problem is solved.
I do however have a problem with my config.json file.
Maybe someone can tell what is wrong with it:
`{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},


	"accessories": [{
		"accessory": "Sonos",
		"name": "Køkken Højtaler",
		"room": "Køkken"
	}],

	"platforms": [{
		"platform": "PhilipsHue",
		"name": "Philips Hue",
		“ip_address”: “192.168 .0 .27”,
		“username”: “”,
		“excludephilips”: false
	}]
}`

JSONLint.com gives this error:
`Error: Parse error on line 18:
...": "Philips Hue",		“ip_address”: “192.1
----------------------^
Expecting 'STRING', got 'undefined'`

**Comment by AppleTechy** [comment]
It appears that you have extra spaces in your IP address. Shoukd look like "
ip_address”: "192.168.0.27"

**Comment by perevers** [comment]
I dont have extra space. Jsonlint.com makes those extra spaces when i press the validate button

**Comment by leoneleone** [comment]
@perevers 
the homebridge README explains your problem. Please read it again carefully.

**Comment by StallionV** [comment]
The double quotes that you are using are different.
The quotes used on the Philips hue Line are valid where as he ones on the error line are considered special chars in parsing.
Try replacing them with the ones from Philips hue line

**Comment by perevers** [comment]
Leoneleone: can't find anyrhing in the readme about my problem. Only the first half of my problem which I know does not matter. 

StallionV:
Thx a lot. It works now. Until next time I decide to try and put some new lines in it 😀

**Comment by perevers** [comment]
BTW problem solved so I will close this thread
