### ISSUE TITLE
Install homebridge on linux

### ISSUE THREAD

**Issue by prbreezy** [nfarina/homebridge#521]
Hi,

My config:
- Linux debian wheezy
- 1GB
- 10GB

I'm trying to get homebridge running on my linux server to be able to install later the VeraPluging but at the first steps I face an issue and I actually dont fully understand the issue.

here my steps and the error message.

Steps:
**# Updates and Common installs:**
apt-get update
apt-get install curl git 
apt-get install libavahi-compat-libdnssd-dev -y

**#installation of node JS & NPM**
curl --silent --location https://rpm.nodesource.com/setup_5.x | bash -
apt-get install nodejs

#Miss dependencies 
apt-get dist-upgrade

#Install HomeKitBridge
npm install -g homebridge

After the last command I get the error message below:

> root@homebridge:~/.node-gyp# npm install -g homebridge
/usr/bin/homebridge -> /usr/lib/node_modules/homebridge/bin/homebridge
mdns@2.2.11 install /usr/lib/node_modules/homebridge/node_modules/mdns
node-gyp rebuild
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/5.6.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/homebridge/node_modules/mdns/.node-gyp"
gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:78:19)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:87:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:98:16
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Linux 3.2.0-4-686-pae
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/homebridge/node_modules/mdns
gyp ERR! node -v v5.6.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok
/usr/lib
└── (empty)
npm ERR! Linux 3.2.0-4-686-pae
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "homebridge"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! mdns@2.2.11 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mdns@2.2.11 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mdns package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mdns
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mdns
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /root/.node-gyp/npm-debug.log
npm ERR! code 1
root@homebridge:~/.node-gyp#

I try to run this: npm install -g node-gyp but no luck :-1: 

Is anyone be able to help on this? and was able ot install on linux ? and how ?

**Comment by AppleTechy** [comment]
Try ignoring the error and try running homebridge. Does it return with an
error saying command not found?

**Comment by prbreezy** [comment]
Okay I found this sample : https://github.com/nfarina/homebridge/blob/master/config-sample.json

But he tell me I need to configure hue blabla bla.. How I ca nget a basic basic homebridge config.json just to get it running...?

**Comment by AppleTechy** [comment]
Use the sample-config.som but delete everything except the Bridge part.
Plus you have to delete the comma after the ending } of the bridge section.
Let me know if that works. As I have never actually used a config like that
but theoretically it should work

**Comment by prbreezy** [comment]
Still not be able to I would like to install on my raspberry Pi I will create another topic.
