### ISSUE TITLE
Switch service 'get' only gets called with Siri

### ISSUE THREAD

**Issue by sean256** [nfarina/homebridge#523]
This seems odd and I don't know if it's apple designed or a way homebridge is exposing services.

When I create a **Switch** service and view the 'device' in any homkit app it will always show off and the log I have in the getter never fires. However if I create a **Lightbulb** service with exactly the same code elsewhere, homekit will ask homebridge for the state every time I view the 'device' in the app.

Interestingly if I ask Siri if the device is on, it will call the getter in both cases. THEN it will show the correct state in the app.

```
var testService = new Service.Switch(this.name);
testService
        .getCharacteristic(Characteristic.On)
        .on('get', this.getPowerOn.bind(this))
        .on('set', this.setPowerOn.bind(this));

VS

var testService = new Service.Lightbulb(this.name);
testService
        .getCharacteristic(Characteristic.On)
        .on('get', this.getPowerOn.bind(this))
        .on('set', this.setPowerOn.bind(this));
```

**Comment by maxclaey** [comment]
I noticed the same issue with a LockMechanism: the getter only fires when using Siri while the app always shows to lock to be unlocked.
