### ISSUE TITLE
Please help, dns service error?

### ISSUE THREAD

**Issue by khorn73** [nfarina/homebridge#527]
As soon as the HomeKit number to scan shows up it produces the following error and the device won't show up in any of my HomeKit apps:

Homebridge is running on port 51826.
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: dns service error: unknown
    at Error (native)
    at Advertisement.on_service_registered (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/mdns/lib/advertisement.js:42:24)
    at SocketWatcher.MDNSService.self.watcher.callback (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/mdns/lib/mdns_service.js:18:40)

**Comment by rudders** [comment]
Have you installed avahi?

https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi#install-avahi

**Comment by khorn73** [comment]
I apologize I should have mentioned this in my first post, but I'm trying to run this on a Mac running on Yosemite. I maybe mistaken as I'm very new to all of this, but I'm not sure you can run Avahi on Mac OS X? I would think bonjour should be running? I'll try to do some research on this. Thanks for the suggestion.

**Comment by KhaosT** [comment]
@khorn73 if you're using Yosemite, please make sure you're running 10.10.4 or later... I knew a few people had this issue with discoveryd.

**Comment by khorn73** [comment]
Thanks, KhaosT, I'll take a look on which version I'm on and report back.

**Comment by khorn73** [comment]
It looks like I'm running 10.10.2 and it'll let me update to 10.10.5 so I'll give that a try and let you guys know if this fixes the problem.

**Comment by khorn73** [comment]
The update worked! Thank you so much! Now I can control and organize my MyQ and Harmony remote using HomeKit.
