### ISSUE TITLE
Open Door works, close not

### ISSUE THREAD

**Issue by gjniewenhuijse** [nfarina/homebridge#529]
I added a (KNX) door opener, with the dutch name Hek (gate).

When i say: Doe het hek open (open the gate), it works
 When i say: Doe het hek dicht (close the gate), it doesn't work and siri says: can't find devices

I have the same device for my garage deur (door) and this works great.

Here my device:
 { "accessory_type": "knxdevice", "description": "sample garage door opener", "name": "Hek", "services": [ { "type": "GarageDoorOpener", "name": "Hek", "CurrentDoorState": { "Listen": ["5/0/3"] }, "TargetDoorState": { "Set": "5/0/2" } } ] }

**Comment by rudders** [comment]
This will be a Siri issue. Suggest you rename it and see how that goes.

**Comment by rudders** [comment]
There is also a siricommands channel in the slack community you could try for help. 

https://homebridge-slackin.herokuapp.com/

**Comment by AppleTechy** [comment]
Is it ok it I close this issue? My best guess is there is some issue with the naming as @rudders suggested above or there is a bug with siri that would then need to be reported to Apple.

**Comment by gjniewenhuijse** [comment]
Ok, i try to contact apple support
