### ISSUE TITLE
Should be Accessory getServices be asynchronous? 

### ISSUE THREAD

**Issue by nikita-leonov** [nfarina/homebridge#53]
Should getServices be asynchronous to support services discovery? As for by providing this interface we assume that list of services and characteristics is static which could be not always true.

**Comment by nfarina** [comment]
Yes I believe it should be, especially to match the `accessories` call in Platforms. Perhaps there could create a new method `services` that passes along an async callback and `app.js` could prefer that before calling `getServices` synchronously.

**Comment by nikita-leonov** [comment]
Here is a list of things that asynchronous on iOS — https://developer.apple.com/library/ios/documentation/HomeKit/Reference/HMAccessoryDelegate_Protocol/index.html

I think this behaviors should be implemented in a such way between bridge and devices as well.

**Comment by nfarina** [comment]
That would be awesome - it's more a question for @KhaosT over at [HAP-NodeJS](https://github.com/KhaosT/HAP-NodeJS) though. I'm not sure what that library supports in terms of proactively notifying HomeKit about accessory state.

**Comment by KhaosT** [comment]
@nfarina to support -[HMAccessoryDelegate accessoryDidUpdateServices:], you'll need to modify Advertiser.js, every time you want to force iOS device to fetch new services, you have to increase the "c#" number and update the TXT Record. Too bad that I can't make any changes right now, feel free to send PR to that repo :)

**Comment by nfarina** [comment]
Closing this for now - `getServices` must be synchronous right now in order to serve `/accessories` efficiently.

**Comment by wurmr** [comment]
Has there been any thought to revisit this issue? It seems to me that having getServices be async is the only way to allow a accessory to do discovery of unknown services on startup.

But it is entirely possible I'm missing something.

**Comment by snowdd1** [comment]
@wurmr  
Hi, since API 2 is out (~ March 2016) there is the possibility to make platforms dynamic, so they can add devices right after startup, or whenever they are discovered. But the platform must take care of accessories that are gone, too. Search for dynamic in the issues, there are several of them.
