### ISSUE TITLE
Two accessories with same name

### ISSUE THREAD

**Issue by aprentis** [nfarina/homebridge#530]
At home i have curtains in two different rooms. They`re connected to homebridge via http accessory. 
But it does not work, when i want to type same names for this devices in config.json. 

How should i configure homebridge to say "Siri close the curtains in the living room" and "close the curtains in the dining room"?

**Comment by rudders** [comment]
ave you tried calling one of the "living room curtains" and the other "dining room curtains"? I'm not sure the verb open and close works - you may need to say on/off. Alternatively create "Scenes" that you can activate - "living room bright", "living room dark" kind of thing.

**Comment by rudders** [comment]
There is also a siricommands channel in the slack community you could try for help.

https://homebridge-slackin.herokuapp.com/
