### ISSUE TITLE
config.json help for multiple Sonos speakers

### ISSUE THREAD

**Issue by bartbrueck** [nfarina/homebridge#533]
Sorry if this has been covered.  I cant figure out how to add more than one sonos speaker. the one I currently have in my config works. Any direction is greatly appreciated.
![screen shot 2016-02-17 at 3 53 04 pm](https://cloud.githubusercontent.com/assets/17304506/13128931/628ad43e-d58e-11e5-86d6-54cf699b7b5a.png)

screen shot of my config is attached.

**Comment by rudders** [comment]
Like this
```
"accessories" : [
  {
    "accessory": "Sonos",
    "name": "Kitchen Speakers",
    "room": "Kitchen"
  }, 
  {
    "accessory": "Sonos",
    "name": "Garden Speakers",
    "room": "Garden"
  }, 
  {
    "accessory": "Sonos",
    "name": "Lounge Speakers",
    "room": "Lounge"
  }
]
```
