### ISSUE TITLE
Error installing Homebridge on Raspberry Pi windows 10 iot

### ISSUE THREAD

**Issue by NAVEEDAHAMMAD** [nfarina/homebridge#534]
C:\NAVEED\NodejsWebApp1\NodejsWebApp1>npm install -g homebridge
C:\Users\naveed\AppData\Roaming\npm\homebridge -> C:\Users\naveed\AppData\Roaming\npm\node_modules\homebridge\bin\homebridge

> mdns@2.2.11 install C:\Users\naveed\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns
> node-gyp rebuild

C:\Users\naveed\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  dns_sd.cpp
  dns_service_browse.cpp
  dns_service_enumerate_domains.cpp
  dns_service_get_addr_info.cpp
  dns_service_process_result.cpp
  dns_service_ref.cpp
  dns_service_ref_deallocate.cpp
  dns_service_ref_sock_fd.cpp
c:\users\naveed\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\s
rc\dns_service_browse.cpp) [C:\Users\naveed\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
c:\users\naveed\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\s
rc\dns_service_process_result.cpp) [C:\Users\naveed\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  dns_service_register.cpp
c:\users\naveed\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\s
rc\dns_service_enumerate_domains.cpp) [C:\Users\naveed\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  dns_service_resolve.cpp
c:\users\naveed\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\s
rc\dns_sd.cpp) [C:\Users\naveed\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
c:\users\naveed\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\s
rc\dns_service_get_addr_info.cpp) [C:\Users\naveed\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  dns_service_update_record.cpp
c:\users\naveed\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\s
rc\dns_service_ref.cpp) [C:\Users\naveed\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  mdns_utils.cpp
  network_interface.cpp
c:\users\naveed\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\s
rc\dns_service_ref_deallocate.cpp) [C:\Users\naveed\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  socket_watcher.cpp
  txt_record_ref.cpp
c:\users\naveed\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\s
rc\dns_service_ref_sock_fd.cpp) [C:\Users\naveed\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  txt_record_create.cpp
c:\users\naveed\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\s
rc\dns_service_resolve.cpp) [C:\Users\naveed\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
c:\users\naveed\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\s
rc\dns_service_update_record.cpp) [C:\Users\naveed\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
c:\users\naveed\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\s
rc\dns_service_register.cpp) [C:\Users\naveed\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  txt_record_deallocate.cpp
  txt_record_set_value.cpp
  txt_record_get_length.cpp
c:\users\naveed\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\s
rc\txt_record_create.cpp) [C:\Users\naveed\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
c:\users\naveed\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\s
rc\network_interface.cpp) [C:\Users\naveed\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
c:\users\naveed\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\s
rc\mdns_utils.cpp) [C:\Users\naveed\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  txt_record_buffer_to_object.cpp
c:\users\naveed\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\s
rc\txt_record_ref.cpp) [C:\Users\naveed\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
c:\users\naveed\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\s
rc\socket_watcher.cpp) [C:\Users\naveed\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
c:\users\naveed\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\s
rc\txt_record_get_length.cpp) [C:\Users\naveed\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
c:\users\naveed\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\s
rc\txt_record_deallocate.cpp) [C:\Users\naveed\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
c:\users\naveed\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\s
rc\txt_record_set_value.cpp) [C:\Users\naveed\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
c:\users\naveed\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns\src\mdns.hpp(32): fatal error C1083: Cannot open include file: 'dns_sd.h': No such file or directory (compiling source file ..\s
rc\txt_record_buffer_to_object.cpp) [C:\Users\naveed\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\naveed\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns
gyp ERR! node -v v5.6.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok
C:\Users\naveed\AppData\Roaming\npm
`-- (empty)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "homebridge"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE

npm ERR! mdns@2.2.11 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mdns@2.2.11 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mdns package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mdns
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mdns
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\NAVEED\TECHINICAL\NODEJS\NodejsWebApp1\NodejsWebApp1\npm-debug.log

**Comment by NAVEEDAHAMMAD** [comment]
Followed the below link and resolved. Tx
https://github.com/nfarina/homebridge/wiki/Install-Homebridge-on-Windows:-New-version-(with-Plugin).

**Comment by PatcherMustermann** [comment]
New Link: https://github.com/nfarina/homebridge/wiki/Install-Homebridge-on-Windows
