### ISSUE TITLE
Timestamp in log files

### ISSUE THREAD

**Issue by keloin** [nfarina/homebridge#537]
Is it possible to add a timestamp to console.log / .error functions?
Would be really helpful! 

Thanks!

**Comment by DerEisvogel** [comment]
Hey keloin,

I had the same thinking a few weeks ago. Therefore I created a tiny plugin which adds a locale timestamp to the console output of homebridge. I have just published it for others to use.

You should be able to install it using the following command:
`sudo install -g homebridge--log`

Looking forward to your feedback, as this is the first time I have ever published something on GitHub let alone for npm.

Best Regards,
Eisvogel.

**Comment by desvdp** [comment]
Hi @keloin,
IF you're on Linux (e.g. RaspberryPi) you might want to consider switching to system.d  (see the excellent write-up [here](https://gist.github.com/johannrichard/0ad0de1feb6adb9eb61a/) )
When doing so you'll get the time stamps for free in the journal plus to other nifty features ... see the link.

Best regards
