### ISSUE TITLE
Pre-set device room and siri name?

### ISSUE THREAD

**Issue by nicknewlin14** [nfarina/homebridge#538]
Is there a way to, in the config.json file, pre-configure accessory/device room and siri name?

I'm loading a netatmo and wink hub with a few devices throughout my home that I'd like to assign to different rooms. I can do this manually in a homekit management app after I've added the bridge, but it would be great if this could be specified in the config.json file so it is set up automatically when the bridge loads into my homekit setup (as opposed to all of the devices under the bridge being assigned to the room I place the bridge in, with default names).

Is this already possible and I just can't find documentation for it, or would this be a new feature request?

I also want to say that homebridge is great. I ordered a raspberry pi and can't wait to get a more permanent instance of homebridge running on it (versus my laptop where it is running for now). Hopefully by the middle of next week I'll have a permanent, stable homebridge device running to integrate my wink, netatmo and future devices into HomeKit so I can control them all with scenes and triggers. Thank you for writing and maintaining this great tool.

Thanks!

**Comment by justme-1968** [comment]
there is no way to do this on the homebridge side. at least not as long there is no special purpose companion app that will receive a hint from homebridge and create the room.

**Comment by nicknewlin14** [comment]
The rooms already exist in homekit. I've got actual HomeKit devices set up, many more than I have Homebridge devices. I'm just using Homebridge to bridge some leviton dimmers via a Wink hub, a netatmo and hopefully a Sonos device or two soon.

**Comment by justme-1968** [comment]
the same goes for assigning devices to rooms. this is only possibly by using the homekit api which is only possible from an app on the iOS device.

**Comment by danshev** [comment]
Is there a way to retrieve a HKRoom's `uniqueIdentifier`?
