### ISSUE TITLE
getting homebridge 0.2.13 when I install instead of newest version

### ISSUE THREAD

**Issue by thomasbruce** [nfarina/homebridge#539]
Hi

I'm trying to use the "vera" plugin with homebridge. After a fresh install of homebridge and home bridge-vera I get an error that says I'm using homebridge 0.2.13 instead of the news that is 0.2.18. The vera plugin needs the newest version of homebridge :(

I'm on a raspberry pi 2 with newest jessie and new to linux. I've tried "sudo npm install -g homebridge’", "sudo npm update -g homebridge" and "sudo npm upgrade -g homebridge" to try to update to the newest version of homebridge but with no luck :(

Hope someone can help me!

Thanks

Thomas

**Comment by AppleTechy** [comment]
Are you trying to get the newest version of Homebridge or the "Vera" Plugin? If homebridge run `sudo npm update -g homebridge` and if you want Vera run ` sudo npm update -g homebridge`. In either cases depending on how you originally installed you can remove the sudo and if you would prefer you could try replacing `install` with `update` as npm can sometimes be a pain and not actually download the update unless you for it to install.
