### ISSUE TITLE
libavahi-compat-libdnssd-dev not installing on Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by iDVB** [nfarina/homebridge#540]
I keep getting errors saying its dependences are not being installed
When I dive down in the deps I get to ​**libdbus-1-dev**​ which looks like it's trying to install a newer version that it wants

```
The following packages have unmet dependencies:
 libdbus-1-dev : Depends: libdbus-1-3 (= 1.6.18-0ubuntu4) but 1.6.18-0ubuntu4.2 is to be installed
E: Unable to correct problems, you have held broken packages.
```

I've googled the hell out of this and still can't seem to find out how to fix.

**Comment by maragelis** [comment]
sudo apt-get install aptitude 
Then after install 
sudo aptitude install libavahi-compat-libdnssd-dev
