### ISSUE TITLE
Issue iOS 9.3 beta 4

### ISSUE THREAD

**Issue by julianfez** [nfarina/homebridge#541]
I just have installed today the las beta iOS 9.3 beta 4 on my phone and all my devices attached to the bridge has gone , only show apple compatible like the HUE , Ihome and eve . The devices like nest harmony zway netatmo  and some that used to have with domoticz it's not longer showing. Just appear the bridge , I spend the day trying to restart and factory reset and never show up , just in the devices that I haven't upgraded I guess it's the update of the iOS 9.3 beta 4 or someone have the same issue?

**Comment by JotWee** [comment]
have the same issue

**Comment by PhiltorX** [comment]
Ditto

**Comment by desvdp** [comment]
Hi @JotWee @PhiltorX @julianfez 
might be a long shot, but when you said "just appear the bridge" : do you mean you're seeing the bridge itself, but none of the accessories? If so: you might want to check on issue #163 (the posts from the last two days) ... at least the behavior is the same them, changing the port fixed it there... 
Like I said: maybe a long shot ...

**Comment by AppleTechy** [comment]
@khaost discovered they had slightly modified some characteristics in that
update. The was a a new hapnodjs beta release for 0.2.19 that fixes the
issue. For 9.3 B4. But won't be fully added into the main version until 9.3
has the characterstics finalized in the the OS.

**Comment by JotWee** [comment]
which characteristics have been modified and how?

**Comment by KhaosT** [comment]
Service.BridgingState, they changed the mandatory characteristics required by the service.

Please update your homebridge (npm -g update homebridge) and then all accessories should come back automatically.

**Comment by JotWee** [comment]
Thank you very much, you guys are great!

**Comment by JotWee** [comment]
hm, i removed home bridge from my home, did the update - now I cannot re-add it.

**Comment by KhaosT** [comment]
Oops, I assume you shutdown the homebridge before removing it from home? If that's the case, you'll have to update your homebridge's username in config.json

**Comment by JotWee** [comment]
You are right, thank you very much, everything works again 😊 

Von meinem iPhone gesendet

**Comment by PhiltorX** [comment]
Thanks! It's working again, :)

**Comment by julianfez** [comment]
I dont know what its the problem i  started over with everything and when I tried to pair and set the PIN 03145154 with the ipad also i did a factory restore with ios 9.2. i got a message that it cant add the bridge , but when i try to pair with my iphone 6s ios 9.3 beta 4 works fine . So give up and have working on my phone o won't spend more time to figure out what's going on with the ipad

**Comment by straccio** [comment]
I have 9.3 beta 5 with homebridge fully updated, and after some time all devices goes offline only bridge seems to be online.

**Comment by codetwice** [comment]
Got this error when updating my iPhone to 9.3. 
Solved it by updating homebridge to its latest version.
