### ISSUE TITLE
No Log with autostart (systemd) - (raspberry A - jessy)

### ISSUE THREAD

**Issue by thezepter** [nfarina/homebridge#543]
Hi there !
My Problem with my raspberry A (jessy) & homebridge autostart:

If i start Homebridge manually all fine ! Ok.. i think, now it´s time for autostart. ;-)

If i use your Wiki description for autostart with systemd. In 1st step it´s seem to be work fine. The process starts correctly, but the homebridge devices show no reaction. 

![dienst](https://cloud.githubusercontent.com/assets/2700279/13348326/0d135abc-dc73-11e5-9b5d-58bf0593f2fc.PNG)

sudo systemctl -l status homebridge

![error_log](https://cloud.githubusercontent.com/assets/2700279/13352151/a9b2fdc4-dc8b-11e5-9bd1-c4b4769de224.PNG)

I think it has something todo with the persistence directory not being copied from the original .homebridge folder.

Any idea ?!

Thanks !!!

**Comment by thezepter** [comment]
I´ve found a solution !!!

I copied the "persist" directory to the new directory /var/homebridge

sudo cp -r ~/homebridge/persist /var/homebridge

Works fine !

**Comment by PatcherMustermann** [comment]
Please close this issues...
