### ISSUE TITLE
No accessories visible on iOS

### ISSUE THREAD

**Issue by SunnyPanda1347** [nfarina/homebridge#545]
I've installed Homebridge on Windows 10 64-bit, and it runs correctly, there are no errors on Windows, and I can pair it normally with iOS (I'm using HomeKit Catalog), but then none of my accessories appear like they do when I run the server on Mac.

This also happened when I tried to run Homebridge on my Raspberry Pi.

**Comment by ljcl** [comment]
I'm experiencing this too, only using `homekit-philipshue` in my setup.

**Comment by SunnyPanda1347** [comment]
Updating to the iOS 9.3 beta fixed it!

**Comment by 128keaton** [comment]
I am having this issue. I was able to see it once, but now with a custom config, I am unable to see it.
