### ISSUE TITLE
IOS Error - Device does not conform to Homekit specifications

### ISSUE THREAD

**Issue by cwall88** [nfarina/homebridge#550]
I am attempting to run Homebridge on a Raspberry Pi 2 running the latest Jessie distribution. However, I am constantly met with an error reading "Device does not conform to Homekit specifications" when attempting to add Homebridge to both Insteon+ and MyTouchHome. I can get Homebridge to add when there is no platform or accessory in config.json, but after adding something, the error surfaces. That said, everything appears to load correctly on the Homebridge side. (For example, homebridge-nest pulls current temp, etc. and homebridge-harmonyhub pulls relevant actions.)

 After entirely too much time and effort, I need some help. So far, I have tried:
- Changing name, device ID, and passcode in config.json
- Clearing Homebridge config on IOS device.
- NodeJS versions 3, 4, and 5.
- Several different plug-ins.
- Multiple fresh installs of Jessie.

At this point, I'm lost. I don't know what else to try. Error logs aren't turning up anything useful. Any help would be appreciated. Thanks.

**Comment by RecognitionDesigns** [comment]
what version iOS are you on?
I had the same issues, I ended up installing the latest public beta 9.3 and everything works now!

**Comment by cwall88** [comment]
My iPhone (primary test device) is currently on 9.2.1. I do have an iPad on the 9.3 beta, so I will see if I can get any traction on that front. I'll report back.

**Comment by KhaosT** [comment]
That's really strange... what's the homebridge version you're using? The new bridging state service shouldn't break iOS 9.2.1...

**Comment by RecognitionDesigns** [comment]
How do you find out what the Homebridge version?
(Total noob to this!)

**Comment by cwall88** [comment]
I believe that I have been using 2.18 (or whatever a git clone is giving me), but I just burned down yet another attempt, so I will report back when I can verify.

**Comment by cwall88** [comment]
I'm happy to report a bit of good news. I reinstalled Homebridge (v3.0) and added a couple of plugins. AdditionalIy, I updated my iPad to the new 9.3 Beta 5 and everything seems to be working. However, 9.2.1 still won't work with it.

**Comment by KhaosT** [comment]
@cwall88 I just tested homebridge 0.3.0 with iOS 9.2.1 and it's working fine... Is it possible for you to pull the logs from iOS device console and post at here?

**Comment by cwall88** [comment]
In a particularly strange twist, it's actually working now. It appears that iCloud synced the Homekit profile between, so now the iPhone on 9.2.1 can see and interact with the devices.

**Comment by toshibochan** [comment]
need help. just install homebridge on PI2.
install homebridge, and homebridge-nest
before edit config.joson i just start homebridge for look where to add config.json, but no give me error and just start but no accessories(nest) show in my iPhone to add. where to add config.json?
i add to ~/.homebridge but not work.
