### ISSUE TITLE
Empty service.optionalCharacteristic []

### ISSUE THREAD

**Issue by cflurin** [nfarina/homebridge#552]
@KhaosT: The service.optionalCharacteristics [] is empty when homebridge loads from the cachedAccessories.

```
var service = accessory.getService(Service.Lightbulb);
this.log.debug("optionalCharacteristics %s", service.optionalCharacteristics.length);
```
service.optionalCharacteristics.length = 0.

**Comment by KhaosT** [comment]
@cflurin I didn't cache the optional characteristics since when cached accessory get restored in the next session, plugin should already configured all required characteristics. Is there a reason that you need to have optionalCharacteristics available after accessory restoration?

**Comment by cflurin** [comment]
I used the optionalCharacterics to configure the accessories (allocate, setProps etc.)
https://github.com/cflurin/homebridge-punt/blob/master/lib/accessory.js#L157

But I've to investigate, maybe there is another solution.

**Comment by KhaosT** [comment]
@cflurin if you accessed those optional characteristics before caching, it should be in characteristics after restoration.

**Comment by cflurin** [comment]
No, they aren't. When I start homebridge the first time (no cachedAccessories) then I use `addService` and the optionalCharacteristics are available but stopping and starting homebridge again will restore from  the cachedAccessories and I use `getService`. This way the optionalCharacterists [] ist empty, therefore I'm not able to configure the accessory optionalCharacteristics.

**Comment by cflurin** [comment]
... Please wait I'll check that again.

**Comment by KhaosT** [comment]
@cflurin please make sure you accessed those optional characteristics before you call registerAccessory

**Comment by cflurin** [comment]
Ok, the optionalCharacteristics are in characteristics. But adding/changing optionalCharacteristics to an accessory will be hard to manage.

```sh
[{
	"displayName": "Name",
	"UUID": "00000023-0000-1000-8000-0026BB765291",
	"iid": null,
	"value": "led_bulb",
	"props": {
		"format": "string",
		"unit": null,
		"minValue": null,
		"maxValue": null,
		"minStep": null,
		"perms": ["pr"]
	},
	"_events": {}
}, {
	"displayName": "On",
	"UUID": "00000025-0000-1000-8000-0026BB765291",
	"iid": null,
	"value": true,
	"props": {
		"format": "bool",
		"unit": null,
		"minValue": null,
		"maxValue": null,
		"minStep": null,
		"perms": ["pr", "pw", "ev"]
	},
	"_events": {}
}, {
	"displayName": "Brightness",
	"UUID": "00000008-0000-1000-8000-0026BB765291",
	"iid": null,
	"value": 63,
	"props": {
		"format": "int",
		"unit": "percentage",
		"minValue": 0,
		"maxValue": 100,
		"minStep": 1,
		"perms": ["pr", "pw", "ev"]
	},
	"_events": {}
}, {
	"displayName": "Hue",
	"UUID": "00000013-0000-1000-8000-0026BB765291",
	"iid": null,
	"value": 356,
	"props": {
		"format": "float",
		"unit": "arcdegrees",
		"minValue": 0,
		"maxValue": 360,
		"minStep": 1,
		"perms": ["pr", "pw", "ev"]
	},
	"_events": {}
}, {
	"displayName": "Saturation",
	"UUID": "0000002F-0000-1000-8000-0026BB765291",
	"iid": null,
	"value": 98,
	"props": {
		"format": "float",
		"unit": "percentage",
		"minValue": 0,
		"maxValue": 100,
		"minStep": 1,
		"perms": ["pr", "pw", "ev"]
	},
	"_events": {}
}]
```

**Comment by KhaosT** [comment]
@cflurin why? you shouldn't care about whether or not a characteristic is optional after you set it up...

**Comment by cflurin** [comment]
@KhaosT: Let say I remove a characteristic in my configuration (homebridge-punt.json) this will not be modified as it did with the old homebridge version.

**Comment by KhaosT** [comment]
on Service object, there is now a "removeCharacteristic()" you can use to remove the characteristic if you want...

**Comment by cflurin** [comment]
@KhaosT Ok, I've to modify my plugin and test all use cases (add, remove characteristics).

**Comment by KhaosT** [comment]
@cflurin your use case is kinda like the 1% ... normally an accessory shouldn't modify services/characteristics after being published...

**Comment by cflurin** [comment]
@KhaosT: just now there is a simple solution:
the user can stop homebridge, delete cachedCharacteristics and start again :smile:
