### ISSUE TITLE
Adding Homebridge to Home fails after Removal

### ISSUE THREAD

**Issue by searls** [nfarina/homebridge#558]
Initially, I was able to add Homebridge as a HomeKit accessory via Apple's HMCatalog sample code project, but as I added platforms & accessories to Homebridge & restarted the server they never appeared.  To resolve this, I removed Homebridge from my Home and attempted to re-add it.

Steps I took:
- Change the homebridge username address
- Change the HomeKit PIN number
- Remove the `~/.homebridge/persist/` directory
- Restarted `homebridge`

Now, when I add Homebridge via HMCatalog, I see this after I enter the PIN:

![img_0100](https://cloud.githubusercontent.com/assets/79303/13556223/4c062246-e3a2-11e5-8f7b-182124e4addb.PNG)

When I try to add Homebridge via Insteon+, I see this after I enter the PIN:

![img_0101](https://cloud.githubusercontent.com/assets/79303/13556231/73164956-e3a2-11e5-900d-b9867460e9b2.PNG)

Any advice?

**Comment by searls** [comment]
Related: https://github.com/nfarina/homebridge/issues/429

**Comment by searls** [comment]
Update: I suspect the root cause is hidden in one of my installed plugins. If I remove `homebridge-liftmaster` and `homebridge-nest` from my `.homebridge/config.json` the device can be added successfully via the iOS apps. However, if I re-add either to my `config.json` and restart homebridge, the iOS apps will report they cannot connect to the Homebridge accessory.

Nothing is logged to STDOUT/STDERR in this case.

```
~ $ node -v
v4.3.1
 ~ $ npm -v
2.1.11
```

**Comment by KhaosT** [comment]
If you can isolate the problem to a specific plugin, I'd suggest you to contact plugin developer for further assistance.

**Comment by AppleTechy** [comment]
Huh. My guess is it Nest as Kraigm updated the plugin 9 days ago. Try
removing that one and adding the LiftMaster back into ur config and try
running.

**Comment by searls** [comment]
If I add only LiftMaster or only Nest, I get the error.
