### ISSUE TITLE
homekit triggers

### ISSUE THREAD

**Issue by armins2k** [nfarina/homebridge#559]
Hi ,
is it a normal behavior that setup triggers like a specific air quality value or a state of a switch only trigger after I open a homekit app like Eve, Home and the data gets refreshed? 
I'm having this problem with different scenes where I want a specific action to happen after a certain value is reached (like netatmo data or homematic blinds change).
Tried a fresh install of homebridge on a Raspberry Pi but same thing.

Thanks for enlighten me ;)

**Comment by torange** [comment]
I have the same problem.. I have only tested it using netatmo CO2 levels as an event trigger to activate a light, but the netatmo data does not seem to update in the device's HomeKit data until a HomeKit app is opened, so the event is never triggered.
