### ISSUE TITLE
Devices from zway are not in homekit apps

### ISSUE THREAD

**Issue by stephandue** [nfarina/homebridge#560]
Hi,
I run zway and homebridge on a Paspberry Pi2. When I start the homebridge everything seems fine but my Smarhome App´s like "Eve" or "myHome" just see the homebridge no zway or any devices from there. I only installed a danalock in zway which works fine from there.

Here´s what I get when I run homebridge:

`pi@raspberrypi ~ $ homebridge
**\* WARNING **\* The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
**\* WARNING **\* Please fix your application to use the native API of Avahi!
**\* WARNING **\* For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=node
**\* WARNING **\* The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
**\* WARNING **\* Please fix your application to use the native API of Avahi!
**\* WARNING **\* For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister
Loaded plugin: homebridge-legacy-plugins
Registering accessory 'homebridge-legacy-plugins.AD2USB'
Registering accessory 'homebridge-legacy-plugins.Carwings'
Registering accessory 'homebridge-legacy-plugins.ELKM1'
Registering accessory 'homebridge-legacy-plugins.FileSensor'
Registering accessory 'homebridge-legacy-plugins.GenericRS232Device'
Registering accessory 'homebridge-legacy-plugins.HomeMatic'
Registering accessory 'homebridge-legacy-plugins.HomeMaticThermo'
Registering accessory 'homebridge-legacy-plugins.HomeMaticWindow'
Registering accessory 'homebridge-legacy-plugins.HttpGarageDoorOpener'
Registering accessory 'homebridge-legacy-plugins.HttpHygrometer'
Registering accessory 'homebridge-legacy-plugins.HttpThermometer'
Registering accessory 'homebridge-legacy-plugins.Tesla'
Registering accessory 'homebridge-legacy-plugins.X10'
Registering accessory 'homebridge-legacy-plugins.mpdclient'
Registering platform 'homebridge-legacy-plugins.Domoticz'
Registering platform 'homebridge-legacy-plugins.HomeAssistant'
Registering platform 'homebridge-legacy-plugins.HomeSeer'
Registering platform 'homebridge-legacy-plugins.ISY'
Registering platform 'homebridge-legacy-plugins.LIFx'
Registering platform 'homebridge-legacy-plugins.SmartThings'
Registering platform 'homebridge-legacy-plugins.TelldusLive'
## Registering platform 'homebridge-legacy-plugins.ZWayServer'

Loaded plugin: homebridge-zway
Registering accessory 'homebridge-zway.ZWayServer'
## Registering platform 'homebridge-zway.ZWayServer'

Scan this code with your HomeKit App on your iOS device to pair with Homebridge:

```
┌────────────┐     
│ 031-45-154 │     
└────────────┘     
```

Homebridge is running on port 51826.`

And here´s my json.config:
`{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },

```
"description": "",

"accessories": [
],

"platforms": [
    {
    "platform": "ZWayServer",
    "url": "http://192.168.178.26:8083/",
    "login": "admin",
    "password": "raspberry"
    }
]
```

}`

Many Thanks
Stephan

**Comment by AppleTechy** [comment]
What version of ios are you using? If you're using 9.3 beta you must update to the newest version of Homebridge(3.1). I would also suggest uninstall the legacy plugins and installing just the zway plugin which will be more developed if that's the only plugin you are using out of the legacy plugins. Here is the [Link to the Github page](https://github.com/SphtKr/homebridge-zway)
