### ISSUE TITLE
persist file location

### ISSUE THREAD

**Issue by farberm** [nfarina/homebridge#563]
Where is the persis cache fie location on OSX. Cannot find homebridge and need to delete files? Cannot seem to locate. Please be specific

**Comment by mactr0n** [comment]
Try this: https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/mdfind.1.html

**Comment by rudders** [comment]
Same as all platforms ~/.homebridge/persist
i.e .homebridge in the users home folder.
Mac OS X hides folders and files that start with a "." So user terminal.

cd ~/.homebridge
rm -rf persist
