### ISSUE TITLE
config.json not loaded

### ISSUE THREAD

**Issue by Cavas17** [nfarina/homebridge#564]
Hi,

I have an issue with iOS Eve app. I can add the homebridge accessory but it appear like this and my accessories (SonyTV and Xbox) not appear.

![img_0255](https://cloud.githubusercontent.com/assets/17765433/13671533/b52c7e60-e6d0-11e5-9340-272da216f911.jpg)

When I run Homebridge, I don't see the sentence "Loaded config.json with x accessories and x platforms."

![capture d ecran 2016-03-10 a 14 50 28](https://cloud.githubusercontent.com/assets/17765433/13671624/3e54df02-e6d1-11e5-832b-de65cb562acb.png)

And if I try to delete the config.json of the homebridge folder, no error message. It seem that hombridge doesn't load the config.json file.
I don't understand... anyone can help me please ?

This is my config.json file : 

![capture d ecran 2016-03-10 a 14 51 34](https://cloud.githubusercontent.com/assets/17765433/13671665/7930d220-e6d1-11e5-8241-75ccb3e5cedc.png)

PS : Sorry for my broken English, I'm a French user.
Thanks

**Comment by KhaosT** [comment]
I believe you placed the config.json at the wrong place. By default it should be placed at ~/.homebridge

**Comment by KhaosT** [comment]
Homebridge itself is at the right place. Can you do a ``ls -al ~/`` and see if there is a .homebridge folder?

Best Wishes,
Tian

**Comment by KhaosT** [comment]
You can see there is a .homebridge folder there, now try ``ls -al ~/.homebridge`` and see if your config.json is actually at the right place.

Best Wishes,
Tian

**Comment by Cavas17** [comment]
All right !!! It works !!!

![img_0256](https://cloud.githubusercontent.com/assets/17765433/13679568/b08b4750-e6f4-11e5-9f54-f154f23987c3.jpg)

Thanks a lot for your help !!!

In order to learn, what the command "ls -al" do ?

**Comment by AppleTechy** [comment]
It lists all directories even if they are hidden

**Comment by Cavas17** [comment]
Okay, thanks a lot for help.

**Comment by readeral** [comment]
I had this issue too - is there any way that it could be a 'common error' in the readme.md?

**Comment by rcorbari** [comment]
What's that terminal app with the black window?

**Comment by Cavas17** [comment]
The app is Atom.
