### ISSUE TITLE
Samsung TV

### ISSUE THREAD

**Issue by matthijsotterloo** [nfarina/homebridge#568]
Hi!

I'm using the Samsung TV plugin to control my TV.
When I ask siri: "Turn the living room TV off" it says: "Okay, the living room tv is turned off", but the TV is still on and in the console I get this error: 

`Samsung Remote Client: disconnected from 192.168.178.14:55000`

Anyone knows how to fix it? I tried to run a standalone version of the samsung tv remote (so not within homebridge) and that seems to work fine... Seems like it's sending a wrong action to the TV? Where can this be edited?

Thanks!

Matthijs

**Comment by damianromanowski** [comment]
@matthijsotterloo The 'error' is not really an error, more of an information message. It seems that the command was sent successfully, just not executed internally.

If you have already paired the TV with nodejs, try editing [index.js line 80](https://github.com/CONNCTED/homebridge-samsungtv/blob/master/index.js#L80) and change `KEY_POWER` to `KEY_POWEROFF`.

Not all Samsung TV's use the same codes.
