### ISSUE TITLE
Lockitron Doesn't Work

### ISSUE THREAD

**Issue by eggyacid** [nfarina/homebridge#569]
I have installed homebridge, installed the plug in and I think I've created config file correctly. When I run homebridge in terminal, I get that it's all working and I can see it in my iOS app. However, whenever I trigger lock/unlock/status. It fails for authentication error. What am I missing?  Can someone share their config file?  Am I missing something in the js?  Sorry, totally new to this and I've searched everywhere. 

Thanks.

**Comment by AppleTechy** [comment]
Please move your issue to nfarina/homebridge-lockitron
