### ISSUE TITLE
Higher level API

### ISSUE THREAD

**Issue by madmod** [nfarina/homebridge#57]
I think we should consider adding some more abstraction on top of HAP-NodeJS for ease of development. I think [this project](https://github.com/Torsten85/node-homekit) could be a good starting point for design. Using chaining with getters, setters, and event emitters would greatly reduce the amount of code required to create an accessory. It also reduces the HomeKit specific knowledge required for a new developer to start contributing to the project. We might also want to consider some higher level accessory base classes such as Light, Switch, Lock, Door, Alarm, Sensor, etc. which provide defaults and create characteristics based on what parts of the interface the developer chooses to implement. 

Here is an example of a potential interface using EventEmitters with callbacks. The underlying API would create permissions, cTypes, and other HomeKit specific attributes for HAP-NodeJS based on the event listeners that are implemented.

```javascript
var accessory = new Accessory('First Garage Liftmaster');

var safetyLight = new Accessory.Light('Overhead Light');
accessory.addService(safetyLight);

safetyLight
    .on('setPowerOn', function (callback) {
        // Liftmaster API call for turning light on
    })
    .on('setPowerOff', function () {
        // Liftmaster API call for turning light off
    });

var backlight = new Accessory.Light('Information Display Backlight');
accessory.addService(backlight);

backlight
    .on('setPowerOn', function () {
        // Liftmaster API call for turning light on
    })
    .on('setPowerOff', function () {
        // Liftmaster API call for turning light off
    });

var securityLock = new Accessory.Lock(
    'Control Panel Lock',
    // We could add accessory type specific options such as Apple's auto lock feature like this
    {
        autoLock: true,
        lockTimeout: 10000
    }
);

accessory.addService(securityLock);

securityLock
    // Auto lock also calls this to simplify the interface
    .on('setLocked', function (isLocked, done) {
        // Fake Liftmaster API call for locking garage controls
        liftmasterApi.setControlLock(isLocked, function (err) {
            done(err);
        });
    })
    .on('getLocked', function (done) {
        // Fake Liftmaster API call for getting lock state of garage controls
        var isLocked = liftmasterApi.getControlLock(function (err, locked) {
            // Node js style callback with err, result
            done(null, isLocked);
        });
    });

// Example fake Liftmaster API event callback for updating a read-only characteristic
liftmasterApi
    .obstructionDetected(function () {
        securityLock.emit('obstructionDetected');
    });

// Run this when any discovery and setup is done to start the server
accessory.publish();
```

**Comment by nfarina** [comment]
This is a great idea. I'm an OO guy personally so am wondering if these can be classes instead of top-level objects, but regardless I think we really need something like this.

(Also I added this to the new [roadmap](https://github.com/nfarina/homebridge/wiki/Roadmap))

**Comment by madmod** [comment]
I'm not sure if EventEmitters are the right pattern for this, but it seemed to be the closest fit because `emit` allows us implement calls anywhere inside of callbacks from third party API libraries without needing `this = that` everywhere. If we use a standard naming scheme for the events such as `obstructionDetected` for an event notification to homebridge and `getObstructionDetected` for when the third party API requires polling and can't send event notifications like webhooks. (more on this below) Using this one to many pattern may increase complexity in the core however because of the potential for multiple listeners that could call a callback multiple times.

An alternative to EventEmitters might be a "fill in the blanks" class prototype, however I think that assigning functions to a class you didn't define can be awkward unless we use setters which may require the developer to have more homebridge specific knowledge.

I've heard great things about streams providing a simple interface but haven't wrapped my head around them yet. It seems that a two way asynchronous communication that can be used inside of third party callbacks is what we need. The ability for accessories to push events to homebridge and respond to events from homebridge. Also we may need the ability for homebridge to periodically poll for changes depending on how HomeKit triggers work (Does HAP send requests periodically or expect notification on a change?) and wether the third party API sends event notifications (AD2USB) or only has status requests. (Philips Hue)

Here are the three main "info events" I see:
- HomeKit wants to know the lights current power state when it is connected after being offline (`initialValue`?)
- HomeKit (probably Siri) wants to know the lights current power state on demand (`onRead`)
- HomeKit either wants to be notified when the light is on or will poll homebridge periodically so it can fire a trigger (I'm not sure which. Can someone explain this? Is this related to `eventEnabled` and `supportEvents`?)

All of these should use the same accessory code to return the light state regardless of wether it is requested by homebridge or the third party API sends homebridge a change event. Some third party APIs may only support requesting state or events but not both. I think homebridge should provide a way to periodically poll for state or to save the current state given to it by an event, then provide that state information to HomeKit as it requires.

**Comment by madmod** [comment]
@nfarina I see that you have started building this in the [provider-api branch](https://github.com/nfarina/homebridge/tree/provider-api). I haven't used ES6 yet but it looks exciting! Let me know how I can contribute to the project. I will probably have some time tomorrow and I can Skype if you want more efficient communication.

**Comment by nfarina** [comment]
Hey I was going to follow up about your API proposal - on further reflection I think your code up top is pretty much ideal. The provider-api branch has a bunch of interesting ideas in it but it's getting a little in the weeds in terms of a ground-up redesign. I created a [public Slack for HomeBridge](http://homebridge-slackin.herokuapp.com) if you'd like to chat more.
