### ISSUE TITLE
Homebridge instability

### ISSUE THREAD

**Issue by leoneleone** [nfarina/homebridge#570]
My Homebridge devices keep resetting themselves within HomeKit. I lose all the orginisation I've done. And now the Scenes I had made are empty and I cannot add any actions to those scenes, any changes I make won't stick, even with the "I'm home" and "I'm leaving" scenes. 

This is definitely a result of using Homebridge. Theo my solution is forever HomeKit configuration and start again. I've done that 3 times already in the past week. 

This is a serious issue in my opinion. 

Something must be going on i can't put my finger on.

**Comment by rudders** [comment]
What platform are you using? Not a docker or VM by any chance. What else can you tell us about your environment and configuration? When do the resets occur etc?

**Comment by leoneleone** [comment]
Raspberry Pi 2 - wheezy, init.d boot up script
Running the latest version of Homebridge from GitHub. All my plugins at updated as well. 

All seems fine at first. After leaving everything running, sometimes some devices disappear from my HomeKit config. I believe they aren't added to persist folder for some reason, they disappear completely and not just appear greyed out in iOS app. 

My init.d script utilises "forever" to keep Homebridge running if errors occur. I think some platforms/accessories don't initialize correctly after a restart of Homebridge. 

But why aren't already added accessories not persisting in Homebridge?

**Comment by KhaosT** [comment]
HomeKit will unpair (aka lose) accessory when it think the accessory's behavior is out of compliance. In the case of homebridge, this normally occurs when one or more plugin returned invalid value for characteristic reads. Ideally if all plugin developers enforce the value it returns for characteristic is valid, this should never happen. For now I'd suggest you try to isolate the plugin that causes the problem and contact plugin developer to address the problem.

**Comment by leoneleone** [comment]
Thanks for the info. 
The plugins causing the problems are:
Homebridge-nest
Homebridge-harmonyhub
Homebridge-smartthings

I'll contact the developers as you advise.

**Comment by pdlove** [comment]
@leoneleone try running it without homebridge-smartthings. I am having some instability that I am actively working to resolve. You can see more discussion of this in the issues on that github page.

**Comment by leoneleone** [comment]
Does that also explain why the HomeKit scenes I had the unstable accessories in are now unusable? The scenes appear empty and I cannot add actions to them. Of course deleting and re-adding the scene solves the problem, but not when my "I'm leaving" and "I'm home" scenes are involved. As you know, they cannot be deleted.

**Comment by leoneleone** [comment]
@pdlove
Thanks for letting me know.

**Comment by KhaosT** [comment]
@leoneleone There is a bug in HomeKit's framework side deserialization process, when the accessory is gone but homed failed to clean up the associated actions in action set, application will get an empty array for actions in the action set. There are some changes in iOS 9.3 might fix the problem. If it doesn't you'll have to reset HomeKit to get built-in action set to work again.

**Comment by leoneleone** [comment]
I'm on iOS 9.3 beta 7
The problem still exists in the latest beta build. 
Hopefully the plugin developers can sort this out.

**Comment by leoneleone** [comment]
Homebridge has completely disappeared from my HomeKit config now. Left the house and all seemed stable (minus the problematic plugins). Came home to fine Homebridge isn't part of my HomeKit config anymore. The HAP server is still running though. 

Are you sure the issue is purely plugin specific?

**Comment by leoneleone** [comment]
Do you think downgrading Homebridge to a version earlier than 3.0 would solve the problem for now? At least until developers fix their plugins...?

**Comment by KraigM** [comment]
@leoneleone So the homebridge hub is disappearing from HomeKit?  Do you ever have the plugin devices disappear but other ones including the homebridge hub are still there?

**Comment by leoneleone** [comment]
Yes, other plugins (accessories) seem to persist. I've managed to narrow down my problematic/disappearing plugins to list in an earlier comment.
 If my Homebridge config.json includes problematic plugins or accessories, Homebridge will eventually get kicked off my HomeKit config. Removing the problematic plugins "solved" that.

**Comment by KraigM** [comment]
@leoneleone Do you have any other platforms other then the three above?

**Comment by leoneleone** [comment]
No. All my other plugins are fine. The accessories seem stable

**Comment by roybotic** [comment]
Every homebridge device is gone today. Eve sees Homebridge, but none of the devices show up (SmartThings, Nest, etc). Eve is doing fine with the Hue Bridge-based devices. I updated to 9.3 last night. Maybe that's it? I hope Apple didn't 'fix' something that was allowing 'uncertified' accessories like homebridge.

**Comment by KhaosT** [comment]
@roybotic for your case, please upgrade homebridge to 0.3.0 or later.

**Comment by roybotic** [comment]
Thanks @KhaosT! Now at 0.3.2 and all is working again. Forgive me for not researching better before posting my question; found the other posts for this error just now.

**Comment by leoneleone** [comment]
@KhaosT 
The disappearing homebridge has starting happening again after updating to iOS 10.3 beta 7 and trying to add Homebridge as an Accessory. Everything is added, but then HomeKit deletes it from the setup after a few minute.

Any ideas? 
I suspect it's a compliance issue which can easily be fixed.

**Comment by KhaosT** [comment]
Can you provide log from iOS device? Mine works fine on 10.3

**Comment by leoneleone** [comment]
@KhaosT 
After some trouble shooting I realise that it was a problem with my instance of homebridge. Renaming homebridge and deleting the persist folder solved my issue. 

Closing this again. 

Thanks
