### ISSUE TITLE
timestamp

### ISSUE THREAD

**Issue by cflurin** [nfarina/homebridge#572]
I've just updated homebridge on my RPi. My terminal background is black and therefore the timestamp isn't visible.

Removing chalk.black() for the timestamp should work for all terminals:

logger.js:
```
-  msg = chalk.black("[" + date.toLocaleString() + "]") + " " + msg;
+  msg = "[" + date.toLocaleString() + "]" + " " + msg;
```

**Comment by KhaosT** [comment]
fixed with 620c847
