### ISSUE TITLE
Home bridge with iOS 9.3 - No accessories

### ISSUE THREAD

**Issue by Cardo1** [nfarina/homebridge#577]
Just updated to 9.3 and unfortunately all my Homebridge accessories have vanished (they appear to have disappeared for pre 9.3 devices, also).  I can see the Homebridge accessory itself, but none of the bridged accessories.

**Comment by KhaosT** [comment]
Please make sure you updated homebridge to 0.3.0 or later

**Comment by Cardo1** [comment]
Thanks for the response.  For some reason, npm update -g doesn't seem to be working.  Doing a npm install homebridge -g sorted it out.
Thanks again.
