### ISSUE TITLE
Slow Remote Connection

### ISSUE THREAD

**Issue by frodeaux** [nfarina/homebridge#578]
First off, this is a wonderful project, thank you for the hard work !

I notice that it takes a good bit of time for me to connect to my devices when away from my home. I use an AppleTV4 with iCloud enabled as the remote hub and I am using a RPi vB as for home bridge.  Executing commands via siri when away from the home often returns a " Sorry I can not connect to that device at this time " reply. Using the Home App on an iOS device often takes a minute or more to get the status of my devices and display them when I am away from the home.  What I am wondering is if this is something normal with HomeKit, or if its an issue caused by either the RPi, HomeBridge or a particular HomeBridge plugin that I may be using.

**Comment by luc-ass** [comment]
I have noticed this aswell. My experience is that the initial call sometimes causes a timeout while consecutive calls work fine. Quite strange...

**Comment by frodeaux** [comment]
I am just wondering what the bottleneck is, or if its just a Home Kit thing in general.

**Comment by pdlove** [comment]
I believe the bottleneck is the polling interval to iCloud.
I experience this also with native HomeKit devices.

**Comment by maddox** [comment]
iCloud slow? :trollface:

**Comment by aaronjedwards** [comment]
I have noticed the same issue. Has anyone by chance had better luck with a remote connection? Unlike pdlove I have fast response times with native HomeKit devices, but only without homebridge running.

**Comment by chado99** [comment]
Has anyone found anything that helps. I found in having the same issue. I have a RPI3 and with an Apple Watch this setup is almost unusable as it takes forever to get a status. I don't recall it being so bad until recently

**Comment by klaasjoerg** [comment]
I am using RPI3, ATV4, AppleWatch and am not experiencing such delay / performance problems. Just switched wifi on my iphone off and told siri on my watch to switch on/off some lights. Was just a matter of 2-3 seconds with IOS10 and watchOS3 until it was executed - and back again. So doesn't seem to be generic problems.

**Comment by chado99** [comment]
Thanks, klaasjoerg. I'm going to experiment more. 

Can you tell me on your Apple Watch if you go to the Home app, do your devices regularly updated? I've observed even when my phone Home App seems generally updated but my watch almost always say "no response". 

Finally, I too have an ATV4. What is the significance of this being on the network? Since I don't have any official homekit devices, does it do anything related to HomeKit?

Thanks, Chad

**Comment by klaasjoerg** [comment]
Well ATV4 (or a ipad) simply allows to "bridge" your devices via icloud while you're not at home. Without you wouldn't have homekit access to your home-devices at all.
Btw I just tried  once again a little bit with the applewatch:

a.) I am not really using the "Homekit"-App on AppleWatch often. I prefer using it for speaking siri-commands instead. I have to many devices and it's not really comfortable (or fast enough) anymore then.

b.) I also have to to wait until the devices status are refreshed on the watch. While beeing refreshed, the Homekit-Watch-App kind of "freezes".

c.) I remember as well, that sometimes (1 out of 10 or so) that my apple watch isn't able to execute a siri command e.g. "Switch Light xy on" and just answers with an error messages like "devices do not respond" or "couldnt execute" or so. In the same moment I simply try to use the iphone-App which works immediately then. So this is probably a apple issue between Watch and iphone and has in my opinion nothing to do with homebridge itself.  Maybe even a problem when Siri isn't able to make a connection to Apple it sometimes results in similar effect without using homekit or so.

So all in all:
1. Siri via AppleWatch works fine for me, when just recalling scenes or single devices (without using the watch-app itself).

2. The Watch-Homekit-App is indeed kind of "freezing" until it has refreshed all status. Thats one reason why I am not really using it. The other reasons are, that it simply takes longer to start, than simply calling a siri command and is not really giving a good overview when having more than 8 devices....
