### ISSUE TITLE
iOS 9.3 Breaks Homebridge

### ISSUE THREAD

**Issue by n3rxstech** [nfarina/homebridge#580]
I have had homebridge running on my Raspberry Pi 2 for a few months now and everything worked fine. I upgraded to iOS 9.3 this week and now nothing works. My homebridge is still running, all devices are loaded but iPhone only sees homebridge itself, no devices at all. I have reset iPhone many times, re-set up iCloud account, nothing seems to work. Anyone else run into this?

**Comment by maddox** [comment]
Upgrade your homebridge to 0.3 to get it to work with iOS 9.3. Changes in iOS 9.3 require this.

**Comment by n3rxstech** [comment]
how do I check my version? I ran update commnad I found online but didn't seem to work.

**Comment by maddox** [comment]
Check out more here: https://github.com/nfarina/homebridge/issues/577

**Comment by n3rxstech** [comment]
Thanks Maddox!
