### ISSUE TITLE
Rasping Jessie / Clean install

### ISSUE THREAD

**Issue by chado99** [nfarina/homebridge#582]
everything installs fine but when run I get the following message:

`
pi@raspberrypi:~ $ homebridge
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[3/23/2016, 10:37:11 PM] No plugins found. See the README for information on installing plugins.
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:`

the only errors I saw during install was the periodic:
`gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/5.9.1"
gyp WARN EACCES attempting to reinstall`

**Comment by snowdd1** [comment]
Maybe the README should be changed to include the trick...

https://github.com/nfarina/homebridge/issues/405#issuecomment-164803485
