### ISSUE TITLE
Find Homebridge but no Accessories

### ISSUE THREAD

**Issue by startraider** [nfarina/homebridge#583]
Hey Guys,

I paired my iOS Device with the Homebridge, which is installed on a Raspberry Pi, one week ago everything works fine. But now it pairs with the Homebridge and don't display any accessoire in the eve app. Does anyone have the same Problem maybe it depends on iOS 9.3 or the newest Version off the eve elegato app.
Maybe someone can help. Thanks a lot.

Heres my Log on starting the Homebridge, the iPad finds the Homebridge!
`Loading 0 platforms...
Loading 8 accessories...
[Temperature Sensor] Initializing DS18B20 accessory...
[Zimmertemperatur] Initializing DS18B20 accessory...
[Sofalampe] Initializing CMD accessory...
[Bettlampe] Initializing CMD accessory...
[Schreibtischlampe] Initializing CMD accessory...
[Stehlampe] Initializing CMD accessory...
[Alles] Initializing CMD accessory...
[Fernseher] Initializing CMD accessory...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
Homebridge is running on port 51826.`

**Comment by PeteLawrence** [comment]
Upgrade homebridge to 0.3.0 or greater.

**Comment by startraider** [comment]
Thanks for the answer, my version is 0.3.2.

`pi@raspberrypi ~ $ npm view homebridge version
0.3.2`

Already the newest i think.

**Comment by PeteLawrence** [comment]
Try ```sudo npm install -g homebridge```

**Comment by startraider** [comment]
Thanks a lot, this works. You made my day!
