### ISSUE TITLE
Accessories not showing up in homekit

### ISSUE THREAD

**Issue by sleepyarmistice** [nfarina/homebridge#584]
I have Homebridge running on Raspbian 4.1, but it has recently started acting weird. The bridge shows up in my HomeKit app, but that's about it. Last time I was looking, all of my accessories were there, but now only the bridge shows up. I've tried restarting Homebridge and removing and adding it again, but that hasn't changed anything. Has anyone else experienced anything like this?

**Comment by Slepperpon** [comment]
Have the same problem started over no matter what i do homebridge is the only thing that shows up

**Comment by pdlove** [comment]
@sleepyarmistice This is typically caused by one of the plug-ins. Which plug-ins are you using?

**Comment by sleepyarmistice** [comment]
I have the Nest, Wemo, Harmony Hub, and Netatmo Weather Station plugins installed, but none of these have changed since I first set it up.  Is there a reason they would suddenly start malfunctioning?

**Comment by Slepperpon** [comment]
harmony nest and smartthings   tried only smartthings still same problem. I just changed jason config to run smartthings only same problem

Date: Thu, 24 Mar 2016 10:14:05 -0700

**Comment by hrzsolt** [comment]
Same problem with me. Homebridge worked so far. Now: detected, added but no accessories are present. Could be the new ios update causing the issue?

**Comment by KhaosT** [comment]
Did you guys recently updated to iOS 9.3? If so, please make sure you update homebridge to 0.3.0 or later.

**Comment by hrzsolt** [comment]
Yes, IOS 9.3 here. Homebridge already on 0.3.2. Then reinstalled. And then a complete Homekit reset (PIA). No success.

**Comment by Slepperpon** [comment]
ios 9.3 and homebridge 3.2 does not work just shows homebridge no accessories

**Comment by KhaosT** [comment]
Huh interesting, can any of you post logs from iOS when pair finished?

**Comment by hrzsolt** [comment]
Happy to help - how to/where to find the log?

**Comment by KhaosT** [comment]
If you have Xcode on your computer, please open Windows > Devices > Select your iOS Device > on the lower left corner, there is a expand to show device log

**Comment by hrzsolt** [comment]
Looking after the logs in xcode, could not find anything interesting. No sign of relevant log...

**Comment by Slepperpon** [comment]
Tried wife's phone it has not been updated and error message said this device does not conform with homekit privileges when tiring to add homebridge

**Comment by u2jrmw** [comment]
My liftmaster accessory has vanished without a trace since I update to 9.3... Has Apple killed Homebridge? That would totally suck.

**Comment by u2jrmw** [comment]
I updated Homebridge and all seems well now...

**Comment by u2jrmw** [comment]
My Apple Watch seems unable to control the garage door. Every other device works fine, but Watch won't find it with identical Siri commands. It is able to control my HUE bulbs through Siri still. Very weird.

**Comment by sleepyarmistice** [comment]
Updating Homebridge did it for me too. Can't believe I didn't think of that myself! ¯\_(ツ)_/¯

**Comment by hrzsolt** [comment]
Completely rebuilt (reinstalled) Homebridge 0.3.2, no success... :/

**Comment by u2jrmw** [comment]
Full reset of my Watch fixed that so probably not Homebridge specific.

**Comment by Bazrat24** [comment]
I too just upgraded to 0.3.2 and everything started working again. I thought I was already on the latest version but running 'homebridge --version' revealed otherwise!!!

**Comment by fahrvergnuugen** [comment]
I have the same problem. Latest homebridge and ios 9.3. Only way to fix it is to delete the persist folder, restart homebridge and then re-pair with iOS. 

It seems to do it when I leave the house then return. I'm going to try disabling remote access and see if it makes any difference.

**Comment by pdlove** [comment]
@fahrvergnuugen do you have an Apple TV? I was seeing the same thing happening for me due to data type issues on older versions of homebridge-smartthings. The Apple TV would maintain everything with remote access but the moment my phone returned to the network, it would drop all accessories.
What plugins are you using?

**Comment by fahrvergnuugen** [comment]
This is still happening every couple of days. I think I've ruled out remote access yesterday - it worked fine on wifi one minute and then the next minute all my accessories disappeared.

**Comment by Ma-580** [comment]
I had the problem. It was caused by the config.json being in the wrong place but no error message had been shown.

**Comment by Mirzel** [comment]
From my side its the same problem, I can connect with EVE, so homebridge is working but there are no accessories loaded. Its also visible in the starting precedure log. Accessories loaded (0)
I set up system and Iphone 2 weeks before, so it´s up to date.

I am using the homematic plug in over CCU2 with a extra "Gewerk" (Folder) Siri..
Actual I have for testing two Jalousieactors "HomeMatic 076799" and one 8x receiver/relaisactor "HomeMatic Komplettbausatz 8-Kanal-Empfangsmodul".
In another discussion they wrote it could be a problem with the given informations by the moduls (Accessories) to homebridge. My problem is, I have no mac so I can´t read it out. Also I can´t found some format discription or what I can do or test....
It would be great if someone has an idea, cause in moment Iam at the end of the road..

**Comment by fahrvergnuugen** [comment]
My issue was caused by a faulty plugin. The plugin was returning an invalid state value for a switch. Seemingly randomly HomeKit would lose all accessories. 

I disabled my plugins one at a time to narrow it down. And then patched the plugin once I found the offending code. 

This actually seems like a bug in HomeKit to me, as an accessory should not be able to corrupt the database of your devise.

**Comment by Mirzel** [comment]
What are you meaning with disable plugin? Remove it? How?
But, I have never seen any accessories. I changed the contents inside CCU2 Folder "Siri" also, to crosscheck the devices.
The problem with the lost connection is also on my side. But I am still in prototyping workflow, so I delete the persist folder and go on...

**Comment by loewal** [comment]
Running Homebridge on Cubietruck ARMBIAN Ubuntu 16.04.1 LTS 3.4.112-sun7i and iPhone on IOS10.
Had the same problems.
- stopped Homebridge: /etc/init.d/homebridge stop
- deleted the persist-directory in Homebridge
- installed the latest plugins: Homebridge-fakebulb and Homebridge-wemo
- restarted Homebridge: /etc/init.d/homebridge start
After a few minutes.....YES!!! my stuff reappeared!!!

**Comment by loewal** [comment]
Forgot to mention: Siri on iPhone finds my "Schakelaar" (Switch).
Happyyyyyy...

**Comment by islesailor** [comment]
Help
Have homebridge running on raspberry pi 3. Platform for TP-Link devices loaded.
[6/1/2017, 5:59:24 PM] Loading 1 platforms...
[6/1/2017, 5:59:24 PM] Initializing Hs100 platform...
Homebridge paired with Homekit. Lamps show up as discovered accessories. Button shows
lamp off, tap button it shows lamp in, BUT the lamp doesn't turn on. No devices respond
to accessories buttons. Lamps work with Kasa app.
config.json
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    
    "description": "This is my configuration file with  one  platform. ",

    "accessories": [
     
    ],

    "platforms": [
        {
            "platform" : "Hs100"
        }
    ]
}
homebridge start up
pi@raspberrypi:~ $ homebridge
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[6/1/2017, 6:16:58 PM] Loaded plugin: homebridge-hs100
[6/1/2017, 6:16:58 PM] Registering platform 'homebridge-hs100.Hs100'
[6/1/2017, 6:16:58 PM] ---
[6/1/2017, 6:16:58 PM] Loaded config.json with 0 accessories and 1 platforms.
[6/1/2017, 6:16:58 PM] ---
[6/1/2017, 6:16:58 PM] Loading 1 platforms...
[6/1/2017, 6:16:58 PM] Initializing Hs100 platform...
[6/1/2017, 6:16:58 PM] Loading 0 accessories...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[6/1/2017, 6:16:58 PM] Homebridge is running on port 51826.
[6/1/2017, 6:16:58 PM] New Plug Online: Pool Light [80062C1E178AC54C5ABEEDF386825AF718391623]
[6/1/2017, 6:16:58 PM] Configuring: Pool Light
[6/1/2017, 6:16:58 PM] New Plug Online: Bedroom Lamp [8012563B520079154E0AFCFAC99D1F61187F0DCA]
[6/1/2017, 6:16:58 PM] Configuring: Bedroom Lamp
[6/1/2017, 6:16:58 PM] New Plug Online: Den Lamp [8012F954590F11D1FCD81541016B2AC4187045A2]
[6/1/2017, 6:16:58 PM] Configuring: Den Lamp

**Comment by DaMojoh** [comment]
My iPad Pro M2 shows most of the devices, but my iphone and iPad Pro A-chip does not. Is that relavent in this discussion, maybe, maybe not. I'll have to check my Macs as well.
