### ISSUE TITLE
HttpMulti and blinds

### ISSUE THREAD

**Issue by pvandenbulcke** [nfarina/homebridge#585]
Hello,
I am not able to make the blinds work with the HttpMulti.js plugin.
It works for DOOR LOCK and GARAGEDOOR types but does not for blinds.
I don't understand why blinds appear to be so difficult.

I have made my own home automation system, which can be controlled by simple HTTP calls to an internal server. So controlling the blinds should in theory be a snap with this plugin.

This is my config.json section relating to blinds:

{

"accessory": "HttpMulti",
"name": "Living blinds",
"description": "Blinds",
"up_url": "http://192.168.0.10:50001/ihomegateway.py?cmd=13%205%20U",
"down_url": "http://192.168.0.10:50001/ihomegateway.py?cmd=13%205%20D",
"open_url": "http://192.168.0.10:50001/ihomegateway.py?cmd=13%205%20U",
"close_url": "http://192.168.0.10:50001/ihomegateway.py?cmd=13%205%20D",
"deviceType" : "blind",
"http_method": "GET",
"model": "HttpBlinds",
"serviceName": "Living Blinds",
"serialNum": "1234"
},

When I ask Siri : "Close Living Blinds"
I get the answer : Sorry, I wasn't able to find any shades at this time.....

This has been driving me nuts....have spend hours and hours on this and can't find a solution.

I'm using the "MyHome" app to test homekit.
It recognizes the blinds and indicates a slider (for percentage), which effectively triggers the up_url.
However in my case this isn't valid....since I cannot control the %, it is just go up or go down.
But that should not be relevant to the Siri message. Siri simply doesn't recognize any blinds connected.

Any idea?

**Comment by Zorgonaute84** [comment]
Same issue here... Do you find the solution or another plugin which working with blinds ?

**Comment by mik79** [comment]
Hello, same Problem here  :-(
