### ISSUE TITLE
Moved homebridge from raspberrypi to Debian 8 - but ios cannot find homebridge

### ISSUE THREAD

**Issue by xena68** [nfarina/homebridge#587]
I've been running homebridge successfully on a raspberry pi for months.  I just installed Debian 8 on a AMD64 box and installed homebridge, copied over my json.config file, and installed the http accessory.

Homebridge starts up fine on Debian, but my iOS devices (running eve) cannot find it. I deleted both persist directories and changed the username in the config file, but still no luck.

Any suggestions?

**Comment by pdlove** [comment]
When you move it, you really should copy over the persist folder as it contains the pairing information for the phone. As it is, you need to reset HomeKit on the phone and delete the persist folders one more time.

**Comment by xena68** [comment]
Thank you.  That fixed it.  Unfortunately, I lost all of my scenes in Eve on my iPhone, but at least all of the accessories are still there.  Thanks

**Comment by defatpm** [comment]
Where are the persist folders located? Complete newb question, I know.

**Comment by cmera** [comment]
xena68 - try disabling ipv6 in avahi .. 

<code> sed -i '/^use-ipv6=/s/=.*/=no/' avahi-daemon.conf  /etc/avahi/avahi-daemon.conf</code>
