### ISSUE TITLE
Harmony Hub activities not showing up in Homekit

### ISSUE THREAD

**Issue by Rhoeffner** [nfarina/homebridge#588]
I'll admit I am a complete noob at this but I cannot get my harmony hub integration to work. I have homebridge installed on mac and am using the elgato eve app for homekit. The plugin gets loaded but the activities are not found =

Ryans-MacBook-Pro-4:~ Home$ npm update -g homebridge-harmonyhub
Ryans-MacBook-Pro-4:~ Home$ homebridge
[3/27/2016, 6:52:03 PM] Loaded plugin: homebridge-harmonyhub
[3/27/2016, 6:52:03 PM] Registering platform 'homebridge-harmonyhub.HarmonyHub'
[3/27/2016, 6:52:03 PM] ---
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[3/27/2016, 6:52:03 PM] Homebridge is running on port 51826.

**Comment by KraigM** [comment]
Did you configure homebridge to use harmony hub?

**Comment by Rhoeffner** [comment]
My config.json that is saved in my /homebridge directory is: 

{
"bridge": {
"name": "Homebridge",
"username": "CC:22:3D:E3:CE:35",
"port": 51826,
"pin": "2486"
},

"platforms": [{
    "platform": "HarmonyHub",
    "name": "Bedroom Harmony Hub"
}]

}

**Comment by Rhoeffner** [comment]
Nevermind I figured it out. Had the file saved in /homebridge not /.homebridge. Cheers
