### ISSUE TITLE
Too stupid to know what this issue is please help

### ISSUE THREAD

**Issue by maxtheeverything7** [nfarina/homebridge#591]
![image](https://cloud.githubusercontent.com/assets/18165953/14140639/40b1bf6e-f648-11e5-8e42-6558f78865a7.jpg)
Please. help

**Comment by maxtheeverything7** [comment]
The only problem is that i dont know where to put the directory persist
![image](https://cloud.githubusercontent.com/assets/18165953/14140670/7ad0a8ea-f648-11e5-88f6-999f22d52e19.jpg)

**Comment by maxtheeverything7** [comment]
this is where i put it

**Comment by bprskalo** [comment]
as shown on your screen in the message the folder MUST be in /home/pi/.homebridge/ 

this is very important. on your screen of your folders is a file shown withe the name .homebridge. Please rename this file .


so you have o create a folder in your pi home folder called .homebridge

in this the config.json should be placed (default location for the configuration file) and then the PERSIST and Accessories folder will be created in there.

**Comment by maxtheeverything7** [comment]
ok thankyou that fixed it
