### ISSUE TITLE
Question about Remote access

### ISSUE THREAD

**Issue by jcbriones** [nfarina/homebridge#592]
Hello everyone,

I've read a lot of Issues already regarding this one but it still doesn't work for me. First of all, I have my 2-step verification enabled on my iCloud account and I do have an Apple TV 4 running latest iOS 9.2 and iOS 9.3 on all my iDevices. It works fine when I reset everything (including Apple HomeKit DB) and reconnecting the Homebridge back. But when my internet IP address change, it won't work anymore. It's probably not updating my new IP address on the iCloud servers? I don't want to keep on resetting everything when my IP change. Also, how #462 print out the logs from the Apple TV? I might able to go check that what's happening.

Is there workaround with the 2-step verification enabled? I haven't tried turning it off though.

**Comment by kaosrq** [comment]
Turn off 2-step authentication worked for me with third-generation Apple TV. It was not necessary to disable the suspend apple tv.

**Comment by roycepope** [comment]
Oh is this still an issue? It's still unclear to me if I should be able to control my LIFX bulbs remotely. I have other official HomeKit compatible switches that work remotely but when I try to turn on my LIFX bulbs (Added through this repo) I always get "No Response" in the Home App. When I am on my home WiFi it works flawlessly.
