### ISSUE TITLE
SIGINT/SIGTERM unavailable to native plug-ins?

### ISSUE THREAD

**Issue by mlaurijsse** [nfarina/homebridge#595]
Hi, 

I'm writing a homebridge plugin, which is depending on a native C++ add-on ([homebrigde-fidelio](https://github.com/mlaurijsse/homebridge-fidelio) -> [alsa-monitor-node](https://github.com/mlaurijsse/alsa-monitor-node)). After sending the SIGINT or SIGTERM signal to homebridge when using this plug-in, homebridge does not shutdown. I'm new to native add-ons in NodeJS, so any help is much appreciated. Below is what I've found so far.

Alsa-monitor-node is listening to some alsa events using poll(). When trying to shutdown homebridge, alsa-monitor-node hangs at poll(). After the event we're listening for is fired, homebridge shuts down. When testing alsa-monitor-node on it's own, it shuts down correctly. When using homebridge, SIGINT and SIGTERM are not received by the plug-in/add-on. Testing the add-on stand-alone, poll() receives these signals, returns and the add-on shuts down properly.

Looking at `cli.js` this part seems to capture these signals: 

```
var signals = { 'SIGINT': 2, 'SIGTERM': 15 };
  Object.keys(signals).forEach(function (signal) {
    process.on(signal, function () {
      log.info("Got %s, shutting down Homebridge...", signal);

      // Save cached accessories to persist storage.
      server._updateCachedAccessories();

      process.exit(128 + signals[signal]);
    });
  });
```

Indeed, after commenting this section, homebridge will shutdown correctly. However, this is not a structural solution.

Towards a solution:
1. Is it possible to modifiy `cli.js` so that native add-on's still receive SIGINT/SIGTERM
2. Is there a way (e.g. an event) my plug-in can listen to, to detect a shutdown and in turn send a SIGINT/SIGTERM to the native code?

For completeness: I'm running homebridge v0.3.2 with node v5.9.1 on a Raspberry Pi3 running Raspbian Jessie.

With kind regards,

Marcel

**Comment by normen** [comment]
+1 on this issue, this seems to be a problem with the homebridge-platform-rcswitch plugin as well, removing the mentioned lines allows homebridge to shut down again. It also seems to lock up because the plugin is polling the RC receiver in the background.

**Comment by itavero** [comment]
Seems related to mlaurijsse/homebridge-rflink#4.
Has anyone looked into this?
