### ISSUE TITLE
plugin for Haiku SenseME ceiling fan?

### ISSUE THREAD

**Issue by tokamac** [nfarina/homebridge#596]
Sorry for the inconvenience if this is not the right place to post feature requests, but I didn't find any specific topic for it.

Would it be possible for someone to create a homebridge plugin to control the Haiku ceiling fan with SenseME technology (from the company Big Ass Fans)?

https://www.haikuhome.com

This would not be a fresh start because such a plugin for the Indigo Domotics home automation system already exists: 
https://github.com/bpennypacker/SenseME-Indigo-Plugin

**Comment by pedroserano** [comment]
https://github.com/sean9keenan/homebridge-bigAssFans
