### ISSUE TITLE
lib/HAP-NodeJS change?

### ISSUE THREAD

**Issue by mbnn** [nfarina/homebridge#60]
Hello there,

Maybe im being blind but your documentation says:
cd lib/HAP-NodeJS and then npm install
but when i do a fresh copy of the latest git after npm install i dont see any subdir called lib
the HAP-NodeJS seems to be in the node-modules directory for me?

Any idea?

**Comment by nfarina** [comment]
Sorry, a bit of README rot there. You can ignore that, I'll remove it shortly.

**Comment by mbnn** [comment]
Cool, any idea about me not getting forever working?
Go to the homebridge directory

npm install forever
cd homebridge
forever start app.js

When i do that i get:  forever start app.js
-bash: forever: command not found

**Comment by nfarina** [comment]
Oh where are you getting that command from? You should be able to run the server with `npm run start`

**Comment by mbnn** [comment]
Yes, thats here: https://www.domoticz.com/wiki/Homekit_Siri
I guess to run it in the background and auto start it when the PI2 reboots? :) Or is there a better way?

**Comment by madmod** [comment]
You need to run `npm install -g forever` to run it as a shell command. I would also run `npm rm forever` to remove the unnecessary local copy installed with your last command.

**Comment by mbnn** [comment]
Yep, just found out about that and that worked :) Thx!
Also created a .sh init.d script for it to auto start at startup :)

**Comment by madmod** [comment]
I wasn't able to find an obvious way to notify the wiki moderators of the error. If anyone knows how to contact them or already has a forum account it would be nice to inform them of this correction.

**Comment by nfarina** [comment]
Oh hah, I didn't realize we were talking about a totally different website here :) So yes, this is a problem with that wiki. Hopefully they'll fix it soon! Closing this for now.
