### ISSUE TITLE
Random Disconnects (Maybe socket.io closing socket issue??)

### ISSUE THREAD

**Issue by EmnaX** [nfarina/homebridge#604]
Hello,

First off, HomeBridge is amazing when it's working! I love being able to talk to my phone and make things happen. Thanks for all your hard work HomeBridge Team!

I have run into an issue in which HomeBridge stops working after a while. HomeBridge seems to work great as soon as I start it but after a random amount of time (seems to be between 15 min - 60 min), I no longer get a good response from Siri on my iPhone. HomeBridge doesn't crash or anything but it just doesn't seem to work with Siri on my iPhone anymore. Restarting the HomeBridge service fixes the issue.

Setup:
Ubuntu 15.10 VM created just for this HomeBridge install.
node -v: v5.10.1
HomeBridge Version: 0.3.3

Ubuntu IP: 10.0.0.42
Apple TV 4th Gen IP: 10.0.0.43
My iPhone IP: 10.0.1.101

I am guessing that the problem is related to the following to lines from my log:

Apr 10 13:48:47 kit homebridge[7619]: Sun, 10 Apr 2016 17:48:47 GMT socket.io:client client close with reason ping timeout
Apr 10 13:48:47 kit homebridge[7619]: Sun, 10 Apr 2016 17:48:47 GMT socket.io:socket closing socket - reason ping timeout

After those two lines, I can't get a good response back from Siri.

I have posted my log over at pastebin [http://pastebin.com/wrx00AXm](http://pastebin.com/wrx00AXm). I have put a few comments in showing two instances when I was able to get a good response back from Siri and then last, when Siri couldn't find out what the status was of my garage door.

Any help would be appreciated.

A few other notes that might help:
I have three networks at home:
10.0.0.0/24 <-- Has the Ubuntu server
10.0.1.0/24 <-- Has my iPhone
10.0.2.0/24 <-- Has my internet of things devices

I am using Avahi on my pfSense router to allow the Bongour service to show up on all three networks. The three networks go through the router to communicate with each other. I am using a 4 port NIC.

Cheers

Edit: Added my config files:
cat /etc/systemd/system/homebridge.service 

```
[Unit]
Description=Node.js HomeKit Server 
After=syslog.target network-online.target

[Service]
Type=simple
User=user
EnvironmentFile=/etc/default/homebridge
ExecStart=/usr/bin/homebridge $HOMEBRIDGE_OPTS
Restart=on-failure
RestartSec=10
KillMode=process

[Install]
WantedBy=multi-user.target
```

cat /etc/default/homebridge 

```
# Defaults / Configuration options for home bridge
# The following settings tells homebridge where to find the config.json file and where to persist the data (i.e. pairing and others)
HOMEBRIDGE_OPTS=-U /var/homebridge

# If you uncomment the following line, homebridge will log more 
# You can display this via systemd's journalctl: journalctl -f -u home bridge
DEBUG=*
```

cat /var/homebridge/config.json 

```
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51823,
        "pin": "856-22-123"
    },
    "platforms": [
        {
            "platform": "HomeBridgeControllerLink"
        },
        {
            "platform": "MyQ",
            "name": "Garage Door",
            "MyQApplicationId": "*****",
            "UserAgent": "Chamberlain/2793 (iPhone; iOS 9.3; Scale/2.00)",
            "BrandId": "2",
            "culture": "en",
            "username": "*****",
            "password": "*****",
            "loglevel": "0"
        },
        {
            "platform": "netatmo",
            "name": "netatmo weather",
            "ttl": 5,
            "auth": {
                "client_id": "*****",
                "client_secret": "*****",
                "username": "*****",
                "password": "*****"
            }
        }
    ]
}
```

**Comment by ericcirone** [comment]
I am getting the same issue. Homebridge is not broadcasting over my network sometime between 15 - 60 min. In previous versions it was working great.

**Comment by ericcirone** [comment]
EventedHTTPServer [::ffff:10.0.1.11] Sending HTTP event 'keepalive' with data: {"characteristics":[]} +7m
  EventedHTTPServer [::ffff:10.0.1.11] Sending HTTP event 'keepalive' with data: {"characteristics":[]} +10m
[4/30/2016, 11:26:22 PM] [Nest] Current temperature for Downstairs Thermostat is: 68 F
[4/30/2016, 11:26:23 PM] [Nest] Current temperature for Upstairs Thermostat is: 68 F
  EventedHTTPServer [::ffff:10.0.1.11] Sending HTTP event 'keepalive' with data: {"characteristics":[]} +10m
[4/30/2016, 11:38:13 PM] [Nest] Current humidity for Downstairs Thermostat is: 30%
  EventedHTTPServer [::ffff:10.0.1.11] Sending HTTP event 'keepalive' with data: {"characteristics":[]} +10m
  EventedHTTPServer [::ffff:10.0.1.11] Sending HTTP event 'keepalive' with data: {"characteristics":[]} +10m
  EventedHTTPServer [::ffff:10.0.1.11] Sending HTTP event 'keepalive' with data: {"characteristics":[]} +10m
  EventedHTTPServer [::ffff:10.0.1.11] Sending HTTP event 'keepalive' with data: {"characteristics":[]} +10m
  EventedHTTPServer [::ffff:10.0.1.11] Client connection closed +6m
  EventedHTTPServer [::ffff:10.0.1.11] HTTP connection was closed +1ms
  EventedHTTPServer [::ffff:10.0.1.11] HTTP server was closed +0ms

**Comment by gijoecool** [comment]
FWIW, I am having a similar issue. Perhaps the same issue...

@ericcirone, where do you see those logs?

**Comment by nbwallace** [comment]
I am also seeing homebridge losing communication.

**Comment by nbwallace** [comment]
In the log I'm seeing errors like:

raspberrypi avahi-daemon[471] Invalid response packet from host 192.168.0.xxx

where xxx is 119 or 120

**Comment by Tiger519** [comment]
@EmnaX Did you ever find a solution to this? I'm having the same problem running from a windows build.

**Comment by EmnaX** [comment]
Hi @Tiger159,
I never found out what was causing the issue. What I did to solve it was just use the pre-packaged image for the Raspberry Pi.... Not ideal but at least I got it working.
