### ISSUE TITLE
Add more then one bridge

### ISSUE THREAD

**Issue by gjniewenhuijse** [nfarina/homebridge#606]
Is it possible to add more then one bridge?

So i can add the bridge to a different home.

**Comment by toshibochan** [comment]
I think you can add to you iOS devices but homebridge can't be installed on the same computer. You can install in different computers and change the address.
I have 2 raspberry pi and both have homebridge running.

**Comment by KhaosT** [comment]
You can try to run two homebridge instances with different config file with flag ``-U``.

**Comment by edelmaca** [comment]
Sorry for waking up such an old thread, but I want to run two instances of HomeBridge on one pi. Can you give an example how to run it with that command and two different config files? I'm very greatfull for any advice to do that.

**Comment by KhaosT** [comment]
``homebridge -U storage_path`` put config.json in the storage_path of your choice
