### ISSUE TITLE
Can't pair -- Can't see HomeBridge in Bonjour Browser

### ISSUE THREAD

**Issue by earlthesquirrel** [nfarina/homebridge#607]
I can't get the Home.app to pair with my home bridge set up.
I had things working on an earlier Raspberry Pi, but had to reset to ground zero because of some other issues.

But got a new Pi 3, latest OS.
iPhone latest OS patches 

Home kit says it's started.  Wink plugin seems to be pulling info just fine (according to log)
But can't get the App to connect via add accessory.

Read other issue and got Bonjour Browser.  It fires up fine, and sees the Openhab config running on the box fine remotely.  But nothing for HomeBridge.

Thoughts?
![image](https://cloud.githubusercontent.com/assets/4523243/14550097/d3b93038-0293-11e6-84a3-7a16c6e43d58.png)

**Comment by earlthesquirrel** [comment]
Some more details : Homebridge 0.3.3, IOS 9.3.1
Raspberry Pi : uname -a says :  Linux raspberrypi 4.4.7-v7+ #876 SMP Tue Apr 12 22:28:41 BST 2016 armv7l GNU/Linux

**Comment by KhaosT** [comment]
What's the error output you get on the iOS side?

**Comment by earlthesquirrel** [comment]
Just did an apt-get autoremove to clean out stuff it was complaining about (I believe after Node install)
Re-ran apt-get for packages : 

sudo apt-get install libavahi-compat-libdnssd-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libavahi-compat-libdnssd-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.

So that says it's all there, no?

**Comment by earlthesquirrel** [comment]
Only result on iOS side is spinning icon when it's trying to get Accessories.

**Comment by KhaosT** [comment]
"when it's trying to get Accessories" like searching but nothing shows up or it shows up but when tap on it it just keeps loading?

**Comment by earlthesquirrel** [comment]
Only error in homebridge.err is : 
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in t
he Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>

**Comment by earlthesquirrel** [comment]
When I got to Accessories, click the +, it says "Searching" with the circle busy icon.
Never comes back.

**Comment by KhaosT** [comment]
Then it's a bonjour issue. Can you try to connect your raspberry pi to your router using wire connection and try running homebridge again and see if you can see homebridge? Or try opening a personal hotspot on your iOS device and let raspberry pi join that access point and see if homebridge can be find by Home.app?

**Comment by earlthesquirrel** [comment]
Ok this is interesting.

Doing netstat -na | grep 51826 (port for Homebridge) and it says : 

netstat -na | grep 51826
tcp6       0      0 :::51826                :::*                    LISTEN 

That says tcp v6, right?   Could that be the issue?

**Comment by earlthesquirrel** [comment]
Raspberry Pi 3 is connected to local ethernet via hard-wire.

**Comment by earlthesquirrel** [comment]
Just added ipv6.disable=1 to /boot/cmdline.txt to turn off V6.

A restart and that turned off V6.

Then had to manually shutdown and restart homebridge after it booted.  

That got hap_tcp showing up in Bonjour Browser.

**Comment by earlthesquirrel** [comment]
And vola!  Now I can add that.

Might be something to add to notes...

**Comment by KhaosT** [comment]
Interesting, not really sure why IPv6 would affect bonjour, so can you pair with iOS device now?

**Comment by earlthesquirrel** [comment]
Yup, all connected and can see Wink, WUnderground, Openhab, etc.

All happy now.  Thanks!

**Comment by cmera** [comment]
In case anyone with a RasPi is still seeing this issue, I was able to resolve this by disabling ipv6 in avahi-daemon. 

sed -i '/^use-ipv6=/s/=.*/=no/' avahi-daemon.conf /etc/avahi/avahi-daemon.conf 

a reboot of the raspi and all is working.

**Comment by bartdorsey** [comment]
Someone should add this to the raspberry pi instructions.

**Comment by jvanthof** [comment]
Aaaargh! After I "added ipv6.disable=1 to /boot/cmdline.txt to turn off V6" and rebooted the Pi, the Home app was able to see the HomeBridge, but would take forever to actually add it and eventually failed.

Then I stepped out for a few hours and when I came back, the Home app wouldn't find the HomeBridge anymore! D'OH!!!

Then I tried "sed -i '/^use-ipv6=/s/=.*/=no/' avahi-daemon.conf /etc/avahi/avahi-daemon.conf" (after I actually manually changed that line in the avahi-daemon.conf...) and rebooted the Pi again.... But alas... still no luck... HomeBridge cannot be seen by the Home app.

Yes, I'm on the same WIFi (and actually physically 1m away from the Pi with my iPhone), and I have deleted the /persist and /accessories folders and restarted HomeBridge multiple times...

The Bonjour Discovery app also doesn't seem to find the HomeBridge, or anything like it now... :-S

What am I gonna do now?!?

**Comment by ooii** [comment]
Hi,

I have reset my homekit install because of issues with automation when home app is closed, despite the fact that I have an ATV4 acting as a hub.
Since then, I cannot see homebridge when I want to add accessories. Wired behavior: I see cameras exposed by homebridge through the `Camera-ffmpeg` plugin.

I used Bonjour Browser and it detects my Philips Hue bridge and the cameras exposed by homebridge but not this latter. Any idea?
PS: I disabled IPv6 in `avahi`.

**Comment by ooii** [comment]
After a night of thinking, homebridge has finally decided to show up this morning.

**Comment by LTMNO** [comment]
What did the trick for me was having both things on wifi.. my Pi was on ethernet... when i put it on wifi, it all worked.  I was able to see everything.

**Comment by josser** [comment]
Hi! Getting almost same but a bit different issue:
avahi-browse -av
  wlan1 IPv6 josser-hb                                     _hap._tcp            local
+  wlan0 IPv6 josser-hb                                     _hap._tcp            local
+ eth1.2 IPv6 josser-hb                                     _hap._tcp            local
+ br-lan IPv6 josser-hb                                     _hap._tcp            local
+   eth0 IPv6 josser-hb                                     _hap._tcp            local
+   eth1 IPv6 josser-hb                                     _hap._tcp            local
But
 netstat -an | grep 3000
tcp        0      0 :::3000                 :::*                    LISTEN      
So, it looks like service is advertised only by ipv6 but actually listen only on ipv4. Can somebody confirm my guess? 
And if yes, do you have any advices how to fix this?

**Comment by erikbelusic** [comment]
i just struggled with this for days and finally solved it with https://github.com/nfarina/homebridge/issues/607#issuecomment-210268844

now can we get the docker updated? i preferred running docker on unraid over running a pi

**Comment by lemonkey** [comment]
How can you force homebridge to use wlan0 instead of USB ethernet? No matter what I do via avahi-daemon.conf to not allow the ethernet device, homebridge ends up broadcasting via bonjour on the ethernet device instead of wlan0.

**Comment by lemonkey** [comment]
Nevermind -- had to force kill avahi-daemon and restart it to read the updates to avahi-daemon.conf which deny the ethernet interface.
