### ISSUE TITLE
Home bridge with multiple plug-ins

### ISSUE THREAD

**Issue by eggyacid** [nfarina/homebridge#614]
I finally got Homebridge to work with Lockitron.. mostly working fine except for Secure/Unsecure is reversed.  
now I want to attempt to get a second plug in "LiftMaster" to work with homebridge as well... Do i just copy index.js package.json and add to to the existing file?  or do I need to create a new file for each plug in?  is there a way to setup a folder so I can separate each plug in with their own index.js and package.json?  Sorry, very new at all this and just looking for help.

**Comment by luc-ass** [comment]
Plugins install in separate folders. Homebridge initializes them by calling the folder homebridge-<pluginname>. You the specify the settings in the config.json.

Installation process is described in most of the readme files oft the plugins.

**Comment by jer78** [comment]
Use the instructions (usually the command line) to install new plugins. As was mentioned, they will install into their own directories. 

As for the config.json file, you use the same one for every plug-in. Just copy paste the parameters into your exisiting config file.

**Comment by eggyacid** [comment]
I have copy and pasted the parameters to the existing config.json file inside .homebridge but can't get it to start up anymore.  It works if I only had one aka lockitron in it.  am I missing something in my config.json file?

{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },

    "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",


    "accessories": [
      {
          "accessory": "Lockitron",
          "name": "Door",
          "lock_id": "xxxxxxxxxx",
          "api_token" : "xxxxxxxxxx"
      }

     {
          "accessory": "LiftMaster",
          "name": "Garage",
          "username": "xxxxxxxxxx@mac.com",
          "password": "xxxxxxxxxx"
      }

                    ]
    }


}

**Comment by jer78** [comment]
Its a formatting issue. Try using jsonlint.com to validate it. The following should work for you...

{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},

	"description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",


	"accessories": [{
			"accessory": "Lockitron",
			"name": "Door",
			"lock_id": "xxxxxxxxxx",
			"api_token": "xxxxxxxxxx"
		},

		{
			"accessory": "LiftMaster",
			"name": "Garage",
			"username": "xxxxxxxxxx@mac.com",
			"password": "xxxxxxxxxx"
		}

	]
}

**Comment by eggyacid** [comment]
Thank you, thank you, thank you... i think i finally got it working, there was an extra } in there from copy and paste.

**Comment by jer78** [comment]
No problem. Glad everything is working now!

**Comment by DannyJim** [comment]
Hi all, please I need your help, I have a device sonoff with tasmota software added to homebridge + mosquitto broker, the one accesory work fine but the problem is when add new device, both work at the same time. That is, when i activate the one, the other devices same turn on.
I change the ports and assign one for each device but the last port is not recognized for the configuration file in the mosquitto broker.
How I can separate devices to work independently?
Attach the config.json file and the configuration in the mosquito broker file.
[config.json.txt](https://github.com/nfarina/homebridge/files/1850271/config.json.txt)

[mosquitto.conf.txt](https://github.com/nfarina/homebridge/files/1850274/mosquitto.conf.txt)
