### ISSUE TITLE
Early tests with node v6.0-LTS?

### ISSUE THREAD

**Issue by luc-ass** [nfarina/homebridge#615]
Hey there. Did someone try running homebridge with node v6.0? Support for 0.10 and 0.12 will be killed in about a year and v4.0 about a year later.

**Comment by IComplainInComments** [comment]
I'm trying to get it to install now, but it fails to even compile mdns... Honestly I have no clue on how to fix it.

**Comment by luc-ass** [comment]
Perhaps we'll just wait until the official release in autumn.
