### ISSUE TITLE
Managing cached accessories in dynamic platform

### ISSUE THREAD

**Issue by hinzundcode** [nfarina/homebridge#619]
Do you have some best practices for adding accessories in a dynamic platform? At the moment I query my API and add accessories using registerPlatformAccessories in my platform constructor, but this fails on the second start since homebridge loads and configures them automatically (and I get duplicate accessories/UUIDs). Can I determine in the platform constructor if the cache already contains my accessories?

**Comment by KhaosT** [comment]
@hinzundcode If you check the ``samplePlatform`` you will see the plugin [registered event](https://github.com/nfarina/homebridge/blob/master/example-plugins/homebridge-samplePlatform/index.js#L60) ``didFinishLaunching`` and then start adding new accessories.

Before homebridge send out event ``didFinishLaunching``, it will invoke [configureAccessory](https://github.com/nfarina/homebridge/blob/master/example-plugins/homebridge-samplePlatform/index.js#L70) method on the plugin instance with the cached plugin, you should configure the given accessory and save it somewhere so you you this accessory already exist in homebridge and there is no need to add again.

**Comment by hinzundcode** [comment]
awesome, thanks!

**Comment by bgottsch** [comment]
Hi,

I am trying to create a dynamic platform which fetches once on home bridge startup all available devices from a specific server. To identify these devices they have a unique ID assigned to them.

How would the logic inside the plugin work for it to fetch all devices, check if they already exists, remove the ones that don't exist on the server but exists on homebridge, and add devices that exist on the server but don't exist on homebridge.

How can I check in the didFinishLaunching the devices that already exist?

Thanks,
Beno
