### ISSUE TITLE
Running homebridge via launchd no longer works

### ISSUE THREAD

**Issue by reflektion84** [nfarina/homebridge#621]
Had no problem initially running homebridge as either a user agent or global daemon via launchd.  I can still open via terminal no problem, however, when trying to run via launchd I get the following error:

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn osascript ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:968:3

**Comment by coliflower** [comment]
Hi,

I have the same Error: spawn osascript ENOENT after I edited the config.json …

Are there already some hints how to solve, please ?

**Comment by emeshuris** [comment]
Hi,
Most likely your config file is not valid. Inline search for a validator or
post here

**Comment by coliflower** [comment]
Hi,
maybe but I tested them …

`{
    "bridge": {
        "name": "Homebridge",
        "username": "11:22:33:44:55:66",
        "port": 51826,
        "pin": "031-45-154"
    },
    
    "description": "This is a configuration file.",

    "accessories": [
    ],

    "platforms": [
        {
            "platform" : "iTunes"
        }
    ]
}
`

**Comment by emeshuris** [comment]
Yeah that looks fine, how about logs?

Homebridge logs to two places:

1. /var/log/homebridge.log
2. /var/log/homebridge.err

I suggest you look in them to see if anything jumps out at you.

**PROTIP**: unix has the `tail` command, it makes it really nice to see logs in real time.

Assuming you have homebridge running, from that server run one of the following commands to see what is getting logged live.

```
tail -f /var/log/homebridge.log
tail -f /var/log/homebridge.err
```

**Comment by nzhome** [comment]
i had the same problem, turned out the software was looking elsewhere for the config.json, I thought all software looked in the app folder first.  I guess I am used to windows software too much.
I found out because I changed the PIN number to end in 155, and homebridge still reported the default one.

**Comment by coliflower** [comment]
@johnypony3 
there are no log inside the „folders“ therefore „tail“ is not possible, either :-(

**Comment by coliflower** [comment]
@nzhome 
thank you, that solved a problem with my installation on my MBP, now my App (EVE) „sees“ homebridge and is able to connect (with the new PIN + USER).

I will also try to do it with a installation on my debian …
