### ISSUE TITLE
HomeKit no longer paired

### ISSUE THREAD

**Issue by sethhere04** [nfarina/homebridge#622]
HomeKit just stopped working. Accessories say they are not reachable. I deleted the persist folder and reset HomeKit. Restarted homebridge but HomeKit can't find the bridge. Running on raspberry pi 2.

**Comment by PatcherMustermann** [comment]
Change the username in the config.json

**Comment by sethhere04** [comment]
Can it be just anything?

**Comment by JonathanH5** [comment]
The name seems to be a MAC address, so you should follow some patterns: https://de.m.wikipedia.org/wiki/MAC-Adresse

**Comment by EMCSizl** [comment]
Same issue here. Tried changing the username but still no joy.
