### ISSUE TITLE
home bridge does not recognise limitlessled plugin

### ISSUE THREAD

**Issue by neeshu7** [nfarina/homebridge#623]
i have installed homebridge on raspberry pi globally.
Now I am trying to install limitlessled plugin by using "sudo npm install -g limitlessled"  command but I keep getting the message "No Plugins installed".  I do not get any error message.

To test further I installed i installed lockitron plugin with the help of sudo npm install -g homebridge-lockitron command. 
When I run home homebridge I do find homebridge-lockitron plugin loaded but not limitlessled.

any help would be greatly appreciated.

**Comment by jer78** [comment]
Im not familiar with limitlessled but at first glance it doesn't look like its a Homebridge plugin. I could be wrong. 

Have you tried this one instead? https://www.npmjs.com/package/homebridge-milight

**Comment by neeshu7** [comment]
I installed mlight and it did show up when i start homebridge.
But before I used to see homebridge on iphone through app Insteon+ but after I installed might homebridge does not show up in iPhone. 
it is really strange.
