### ISSUE TITLE
Homebridge Not Accessible Off Network

### ISSUE THREAD

**Issue by kevinstillson** [nfarina/homebridge#624]
I know there has been discussion about accessing HomeKit outside of a home network, but my problem is only with Homebridge.  My other HomeKit accessories work outside of my network, but my Homebridge accessories are unreachable.  Any tips on troubleshooting this without completely resetting my HomeKit configuration?

**Comment by DerEisvogel** [comment]
Have you got an Apple TV in your network? There are some accessories, which are accessible from anywhere, but Homebridge requires an Apple TV bound to your Apple-ID.

**Comment by kevinstillson** [comment]
Yes, I have an Apple TV 4 on the network logged into the same iCloud
address as my phone and mac.  Other HomeKit compatible accessories do work
outside of the network (Phillips Hue and iHome plug) but Homebridge is not.

**Comment by DerEisvogel** [comment]
Are you using Eve? When pressing on the little error triangle in Eve it gives you an error message.
Have you tried signing out and back in again on your Apple TV?

**Comment by kevinstillson** [comment]
In the Eve app the error triangle says "The accessory cannot be reached at
the moment. Make sure Wi-Fi and Bluetooth are enabled and try again.  You
may also try moving closer to the accessory."

I did log out and back in on the ATV a few days ago, but will try again
when I am home.

**Comment by kevinstillson** [comment]
I logged out of iCloud on the Apple TV then restarted the Apple TV and
logged back in.  I also rebooted my modem and router.  All HomeKit and
Homebridge accessories seem to be working off network now.  Thanks for the
help.

**Comment by toshibochan** [comment]
today i have same problem. i have 2 raspberry pi and 2 homebridge, one work from outside and other not. the reason was one is connect to my living room Apple TV and other in my bedroom Apple TV . this morning i disconnect my bedroom Apple TV and one homebridge stop working from outside.

**Comment by toshibochan** [comment]
Take long time to homebridge to connect to my living room appletv but now is working!

**Comment by rafacampoamor** [comment]
Same problem here! Any news on this?

**Comment by andrewgribben** [comment]
I thought this used to work, but after a reinstall of the Pi it does not work. At home everything is fine and the Apple TV is always on.
