### ISSUE TITLE
Homebridge-Wink not communicating

### ISSUE THREAD

**Issue by Gamer106** [nfarina/homebridge#625]
For the last 24 hours or so, there seems to be an issue with Wink communicating with Homebridge. I can't seem to get the devices to respond, but if I run Homebridge maually, I can see that it only updates the devices that I turn off/on in the Wink app, rather than a full refresh ever x seconds. This just happened recently. I'm looking at the log of the actively-running homebridge, and it is showing that it's receiving the commands and setting things to True or False, but it's not happening. Anyone else having this issue?

**Comment by jwl17330536** [comment]
Yes, but it has been going on for longer than the past couple of days.  I can no longer even see my locks.   Furthermore when locks are enabled in the group then my yamaha receiver won't show up.  As you said, I'm also not able to turn any lights on or off.  I can see their state, but can't change.  Same seems true for my Nest thermostats.

I've been working on homebrige-wink, but after seeing this post I think it might here here instead!

**Comment by Gamer106** [comment]
I finally figured it out. I guess my personal API keys expired. I went back to the generic Android app one and it's working again. Try that!

**Comment by jwl17330536** [comment]
Yeah, I have API credentials from Wink and I verified with them that they were still valid and working.

**Comment by Gamer106** [comment]
Oh ok, I'd recommend renaming config.json and making a copy and using the android API as a test as its least invasive, I didn't even contact Wink. I guess I could've haha

**Comment by treeiler** [comment]
@jwl17330536 Have you figured out what went wrong. I am having the same issue. I can see all of my devices but I cannot toggle their power. 

@Gamer106 any suggestions?

**Comment by jwl17330536** [comment]
I went through each and every version of homebridge and all with the same results. Wink fails while all other modules work. 

iOS has been updated. Wink firmware I don't think has, but the app has been as you pointed out.

**Comment by Gamer106** [comment]
config.json

 "client_id": "quirky_wink_android_app",
 "client_secret": "e749124ad386a5a35c0ab55

**Comment by treeiler** [comment]
@Gamer106 

That didn't work, I got an authentication error. I think that client secret is unique to your account. 

@jwl17330536 

I agree with the idea that the wink module has not been updated. Oh well, there hasn't been any development in the module at all this year. 


Im going to try out using IFTTT to toggle shortcuts. Its very complicated but if no one uses the Wink app and only home kit, it may work. Im also trying to integrate the Homeassistant.io server. Ill update this thread with any updates.

**Comment by Gamer106** [comment]
@treeiler that is a generic API that all android Wink apps use, it should work. If you got an authentication error, make sure you copy/paste it, and put the " at the end, which I did not do in that post :o.

**Comment by jwl17330536** [comment]
The home-assistant module worked last time I tried, but doesn't have all the functionality that wink did. For example, Nest, locks, garage door, and sensors.  I pulled it out in favor of the wink module for that reason.

**Comment by jclarke0000** [comment]
I was having this problem too.  Changing to the generic Android API key worked for me.

**Comment by pdlove** [comment]
@treelier We completely rebuilt the wink module back in January.
Is everyone using homebridge-wink or the one that used to be in the legacy plugin?

**Comment by jwl17330536** [comment]
Homebridge-wink here.

**Comment by pdlove** [comment]
I just plugged my wink hub back in to test and it's successfully controlling my lutron lights from home kit.
The client secret and client id are tied together, but they aren't specific to the user's account.
It is also working with this pair:
            "client_id": "quirky_wink_android_app",
            "client_secret": "e749124ad386a5a35c0ab554a4f2c045",

If the client secret is wrong, you shouldn't get any devices pop up.
I also just finished updating everything with npm and see no change. Everything works as it should.
When I do it from HMCatalog on the iPhone, I notice that when I turn it off it turns back on immediately according to the phone and then turns off after 30-45 seconds, but the light functions within a couple of seconds.

**Comment by treeiler** [comment]
@Gamer106 and @pdlove 

I tried the client id and secret @pdlove provided. All is working now. Although there seems to be a much longer delay than there used to be. It was almost instant and now sadly it is not. Oh well I will live with it. 

For now I'm going to run both Homebridge and HomeAssistant side by side. I love the siri integration with homebridge, I use it daily on my apple watch and in my car for my garage. But, sadly, I cannot view my IP cams from home kit, come on apple! Oh well.

**Comment by Gamer106** [comment]
@treeiler @jclarke0000 that's great news! So it seems to be tied to the individual's API, unsure as to why but that's 3 resolved by changing to the generic Android app API. I'll close this issue out in 24 hours if that took care of it.

**Comment by jclarke0000** [comment]
I've sent a note to Wink support inquiring about the status of my API key.  I'll report back here when I hear a response.

**Comment by jwl17330536** [comment]
Changing to the generic android api credentials worked for me.  I’m super happy to back in business, but very annoyed that was the problem!  I spent 8+ hours yesterday trying everything BUT that.  I did ask Wink if my credentials were still valid and they confirmed that they were…. They might have changed some permissions to all of our API accounts.

**Comment by jclarke0000** [comment]
The Wink support rep is asking me for an example of a cURL request that is failing.  Is anyone seeing such a failure?  I don't recall seeing errors in the log file, although I can check tonight.

**Comment by inator** [comment]
+1 on the same issue with my personal api credentials.  Reverting to the quirky_wink_android_app fixed for now, but looks like we'll need to figure out where the personal API is broken.  I'm willing to pair with someone on this.  Ping inator in the Homebridge Wink channel if interested.

**Comment by benw525** [comment]
I spent a few hours working on this yesterday. Going back to the android API fixed it for me as well.

Is it possible that Wink has disabled a lot of developer APIs?

**Comment by jwl17330536** [comment]
Don't think they disabled them completely. They told me that mine was still active. I bet they changed permissions.

**Comment by pdlove** [comment]
Can someone email me your nonworking API key?  I would like to try it out with my login information and see if any errors are reported back.  My email address is pdlovelace@gmail.com

**Comment by jwl17330536** [comment]
I emailed you what I have.

**Comment by pdlove** [comment]
@jwl17330536 I can confirm it broke my implementation. I'll take a look and see why Wink is returning something so drastically different. Thanks for the example bad key.

**Comment by chado99** [comment]
Had same issue, used the android key listed above from @pdlove and all is well again. Comeon Wink!

**Comment by pdlove** [comment]
Can someone ask Wink if your key is API Version 2 specific? That's the only think I can think that might be an issue.
My key works fine, but I requested version 1 when I got it.

**Comment by chado99** [comment]
I just emailed, will let this thread know what they reply. Though, I assume t's V2 specific, when I looked at the email they sent my key with it had this indicating v2 "While we don't provide developer support, the answers for everything you need can be found in the API documentation: http://docs.winkapiv2.apiary.io/"

**Comment by pdlove** [comment]
Mine says this: "The documentation for the API can be found at:
http://docs.wink.apiary.io/"
So that really does indicate it is the issue.
V2 is quite a bit different, so you need to try and get a V1 key. If that isn't possible, let me know and I'll evaluate if I can potentially update the code... I just don't know when that would be or how long it would take as work has me really tied up this month.

**Comment by chado99** [comment]
got a response: "Those credentials are API 2 specific.  That is the only version we create keys for." BAM.

**Comment by pdlove** [comment]
K. I'll start looking into what it will take to use API 2 for the calls and work on the tweak.
At the very least, the old Android keys still work for now.

**Comment by pdlove** [comment]
I'm convinced that they broke the version 2 API. It no longer supplies anything in the desired_state object and that is causing the issue. everything I've seen looks like the desired state should work in v2 like it did in v1. I'll request a v2 key and see if I can get support.

**Comment by chado99** [comment]
Sounds reasonable. I have been using it for at least a month on my existing version two key and then as others have said it just stopped working

**Comment by jclarke0000** [comment]
Just heard back from Wink support and I can confirm my API key is a V2 key.

**Comment by Gamer106** [comment]
Alight, update. Receiving a message that my certificate has expired while using the generic API we've posted throughout this thread. I will try again with my personal Client/client secret and see if I get the same result.

**Comment by pdlove** [comment]
I am redoing the plugin to work with API version 2. I'm on vacation this week, so it will probably be 3 weeks.

**Comment by benw525** [comment]
Thanks pdlove!

**Comment by treeiler** [comment]
Pdlove,

Could u possibly look into adding support for devices like the wink relay or tapt. I would love to use the physical buttons as a trigger for HomeKit devices.

**Comment by Gamer106** [comment]
Oh excellent, because my API isn't working 😭

**Comment by tekuonline** [comment]
@pdlove any updates on V2 yet?

**Comment by GaryFDes** [comment]
Yah, any update?  I got a brand new id from Wink last week but noticed that my Lutron devices were not working.  I replace the new cliend id/secret with the android app credentials and they are now working.

If you need help then please just ask.  I might be able to help.

**Comment by tomboates** [comment]
@pdlove Also interested in an update as my keys don't seem to work.

**Comment by drgonz0** [comment]
Has this gone anywhere?  Still using the Generic V1 app, but at times I find response slow.  Not sure if that's over-use of the generic API ID.  Any chance this will become deactivated?
