### ISSUE TITLE
SIRI commands - other languages (german)

### ISSUE THREAD

**Issue by zackdvd** [nfarina/homebridge#626]
Hey,
don't think this is an homebridge issue, but i don't know where i should this post to...
Any help is welcome!

I've a strange behaviour with voice commands to siri in german. My setup:

> "accessories": [
>         {
>             "accessory": "CMD",
>             "name": "Lampe",
>             "on_cmd": "sudo codesend 83029",
>             "off_cmd": "sudo codesend 83028"
>         },
>         {
>             "accessory": "CMD",
>             "name": "Verstärker",
>             "on_cmd": "sudo codesend 21589",
>             "off_cmd": "sudo codesend 21588"
>         }
>     ]

So i've two identical accessouries, only the name is different (Lampe = lamp, Verstärker=amplifier).

This works
"Lampe ein" (lamp on)  --> OK
"Schalte die Lampe ein" (turn the light on) --> OK

Now the problem with "verstärker:
Most of the time, Siri does a websearch on that:
"Verstärker ein" --> Siri does a websearch.
Also other words like _einschalten_, _anschalten_ or _an_, same result.
They all work with _lampe_.

And now even more strange:
_"schalte den verstärker ein"_ (turn on the amplifier) works and after a few commands it stops working. The spelling and understanding from siri were the same.

Any ideas??? It is not related to the umlaut ä, also tried different names. Only "Lampe" works...
Lampe2 also do not work (i can't find Lampe 2).

Thank you!

**Comment by PatcherMustermann** [comment]
Hallo zackdvdch,
ich könnte mir vorstellen, das es Probleme mit den Umlauten "äöü" gibt. Daher vermute ich, das es gehen könnte, wenn du die Befehle anlegst wie man sie spricht. 

Beispiel:
Verstärker = Versterker 

Gruß
Patcher

**Comment by luc-ass** [comment]
I have the same problem. "Verstärker" is not always recognized by Siri as a HomeKit device. I tried "Lautsprecher" but I did not like it... ended up creating Scenes that would do the job (i.e. set the living room to XBOX)...

**Comment by zackdvd** [comment]
The strange thing is "not always recognized"...  Same here.



Siri answers: I don't understand
![img_0224](https://cloud.githubusercontent.com/assets/19238490/15097454/edc4cfa6-151b-11e6-9b81-becc29ec5d7b.jpg)

answer: I did not found no devices
![img_0225](https://cloud.githubusercontent.com/assets/19238490/15097455/ede95092-151b-11e6-94bb-cd3bec83a277.jpg)

This worked
![img_0226](https://cloud.githubusercontent.com/assets/19238490/15097456/edeb3c7c-151b-11e6-9832-4e3fac39e979.jpg)
But Siri answers with "ausgeschaltet", which "she" doesn't understand in the first picture...

It's really hard to understand why Lampe is OK and Verstärker not (always).

I'll play around with some different names..

**Comment by developer2013** [comment]
Hallo Leute, 

ich habe das selbe Problem mit meinem Sonos System, wie kann ich hier die Siri Kommandos so ändern, dass Sonos abspielt bzw. pausiert? 

Grüße Carsten

**Comment by justme-1968** [comment]
if siri does not recognize a device name as a homekit device it often helps to add the name of the room or the name of the home.

**Comment by zackdvd** [comment]
A workaround is to create scenes like "Verstärker an" and "Verstärker aus". This works for me.

Maybe one can add this here:
https://github.com/nfarina/homebridge/wiki/Siri-commands

**Comment by developer2013** [comment]
@zackdvd Danke Dir ein bzw. ausschalten geht jetzt endlich. Super Tipp von dir.

**Comment by developer2013** [comment]
kann man auch das Volumen einstellen per Siri?

**Comment by developer2013** [comment]
@zackdvd du musst dir eine LIFX LED Birne holen, ich habe nun eine und kann das Licht direkt über Siri steuern, ist echt genial. Du kannst es auch direkt mit % Werten dimmen, bin total begeistert.

**Comment by zackdvd** [comment]
Since iOS 10.1 it now seems to work without problems. No scenes needed any more.
