### ISSUE TITLE
2 small questions

### ISSUE THREAD

**Issue by modsfabio** [nfarina/homebridge#629]
Edit: Only 1 :)

I installed homebridge on my RaspberryPi. Everything is working fine with Siri and Elgato Eve App..
I can only use it in my own Wifi, since I don't hve an Apple TV..
1. Is there any other option to access the homebridge remotely? Maybe there is something like an iCloud-Connector for the Raspberry?

Thanks guys! This is awesome!

**Comment by modsfabio** [comment]
No Idea? At least for number 2...

**Comment by craigsheath** [comment]
There's a controller app available here that might be suitable.

https://github.com/kraigm/homebridgecontroller

No idea about #1 I'm afraid

**Comment by modsfabio** [comment]
This controller does not include external access... only in the same network :(
Anyone else has an idea?

**Comment by Ricardo1980** [comment]
👍

**Comment by dsaaltink** [comment]
You need a Apple TV 3 or later that is signed in to iCloud with the same iCloud I'd of your phone. If you google on HomeKit remote you will find it. Be patent it cost me a day to get it working.

**Comment by robertvorthman** [comment]
Not sure if you guys already heard that iOS 10 beta allows an iPad to be used as a HomeKit hub which would allow remote access to homebridge.
