### ISSUE TITLE
MyQ Causing Hang

### ISSUE THREAD

**Issue by kevinstillson** [nfarina/homebridge#630]
MyQ Garage Opener is causing an issue with my HomeBridge setup.  It launches and works a couple of times, then when trying later it hangs at:

[MyQ] getDeviceAttribute: making callback

Then nothing else in Homebridge works until I restart.

Any ideas what the issue could be here?

Thank you!

Kevin

**Comment by nimustan** [comment]
Same issue here. Restarting Homebridge will temporarily fix the issue. Garage door will open but hang on closing.

**Comment by kevinstillson** [comment]
I have still not found a fix to this issue.  Anyone else?

**Comment by AppleTechy** [comment]
Use the LiftMaster plugin! The MyQ plugin is no longer being developed....
