### ISSUE TITLE
Default hard coded config settings

### ISSUE THREAD

**Issue by shamiraf** [nfarina/homebridge#631]
Hi,

I've installed homebridge on a raspberry pi and the homebridge works fine except for an issue with defaulting the config to the hardcoded config on the server.js file.

I have placed a valid config.json on the /homebridge folder (pretty much edited and renamed the sample json file) and the server doesn't seem to be using this file. Is the file in the correct location or is there a different folder for it? The config currently got 1 wemo accessory and with a modified port number but when the server is executed, it always defaults to the default port with no accessories getting loaded.

Appreciate any help.

**Comment by modsfabio** [comment]
On my PI the folder was **/home/pi/.homebridge**

**Comment by shamiraf** [comment]
I've got the config file in the same place but it's not getting picked up
and used when the server is started.

On Wednesday, 11 May 2016, modsfabio <notifications@github.com> wrote:

> On my PI the folder was */home/pi/.homebridge*
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/nfarina/homebridge/issues/631#issuecomment-218373159>
>


-- 
________
Regards,

Shamira

**Comment by modsfabio** [comment]
Correct user with all needed permissions?
I'm new to this, too.. But for me it worked from the beginning with the config at this place

**Comment by shamiraf** [comment]
No idea, tried running as both Pi and root users and still running on
default config.

On Wednesday, 11 May 2016, modsfabio <notifications@github.com> wrote:

> Correct user with all needed permissions?
> I'm new to this, too.. But for me it worked from the beginning with the
> config at this place
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/nfarina/homebridge/issues/631#issuecomment-218403133>
>


-- 
________
Regards,

Shamira

**Comment by modsfabio** [comment]
Maybe this helps..
https://github.com/tommasomarchionni/homebridge-openHAB/issues/19

**Comment by shamiraf** [comment]
Thanks, I've tried all things and finally found that homebridge got
installed under /home/Pi/homebridge instead of /home/Pi/.homebridge which
the server was looking for. Everything is working fine now.

On Wednesday, 11 May 2016, modsfabio <notifications@github.com> wrote:

> Maybe this helps..
> tommasomarchionni/homebridge-openHAB#19
> <https://github.com/tommasomarchionni/homebridge-openHAB/issues/19>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/nfarina/homebridge/issues/631#issuecomment-218404244>
>


-- 
________
Regards,

Shamira
