### ISSUE TITLE
Device Polling in Plugins

### ISSUE THREAD

**Issue by Be2daErtin** [nfarina/homebridge#632]
Hi,

I'm creating my plugin. But I noticed that if the homekit app is running and I switch a device, the status on the app does not update for that device. Could it be that I have to create a polling function in the plugin to push a new value every X seconds or was the app suppose to poll?

Does anyone know how real homekit devices will work?

Regards,
Bertin

**Comment by DerEisvogel** [comment]
Are invoking the callback function in your event listener?

**Comment by Be2daErtin** [comment]
I added this for each device type:

`setInterval(function() {
          lightbulbService.getCharacteristic(Characteristic.On).getValue()
   }, 5000);`

But it is killing my http requests.

So now thinking of adding some form of polling function to my platform that will do one request and then update all devices.
