### ISSUE TITLE
Plugin Request - curl data from MyDLink Baby Cam DCS-825L

### ISSUE THREAD

**Issue by JangoBritt** [nfarina/homebridge#637]
So I've got this D-Link DCS-825L Baby Cam that has a temperature sensor on it. I've been digging around trying to figure out how to get the Temperature out of it, and I think I've found the right file.

on the device, there's a script called http://[Device IP]/eng/web_event.cgi which, when run returns the below:

```
motion_detected_1=off
mdv1=0
pir=off
gp_input_0=off
gp_input_1=off
gp_input_2=off
gp_input_3=off
storage_full_sd=off
storage_failure_sd=off
in_recording=off
audio_detected=off
gp_output_0=off
gp_output_1=off
gp_output_2=off
gp_output_3=off
pan_pos=0.000000
tilt_pos=0.000000
zoom_mag=0.000000
focus_step=0
irled=off
playing_music=off
music_repeated=off
night_led=off
camera_name=<redacted>
speaker_occupied=off
mic_muted=off
td=normal

tdC=23
tdF=73

tdC=23
tdF=73

tdC=23
tdF=73

tdC=23
tdF=73

tdC=23
tdF=73
```

The temperature result keeps repeating over and over for as long as the script is running.

Now I'm not great at coding, but I'm sure there must be a way to pull this out into a Thermometer reading that can be input into HomeBridge... Any ideas? There must be some way to CURL this output?

**Comment by JangoBritt** [comment]
Well.. so I sort of answered my own question:

curl -u admin:<redacted> -m 1 http://<ipaddress>/eng/web_event.cgi | grep 'tdC=' | sed -n -e 's/^tdC=//p'

The -m is to -max-time the curl command to 1 second, which catches the first temp report

the grep finds the term tdC= from the whole string
the sed removes the search parameter "tdC=" and just returns the value after it.

returns a very simple "23"

Thank you very much!

Now... how to get this into an accessory?

**Comment by jer78** [comment]
I haven't tried this, but there are some plug-ins for readable HTTP that may do the trick. 

Here's one for thermostats, but it doesn't look like there's very good instructions. You'll have to dig around the code to see what parameters it needs...
https://www.npmjs.com/package/homebridge-http-thermostat

I'm guessing it's going to be similar to something like this one (this one is just to get an on/off characteristic):
https://www.npmjs.com/package/homebridge-readablehttp

**Comment by jer78** [comment]
Also, if you're in the market for a thermostat, I love my Ecobee3 and definitely recommend them. You can add remote sensors to it and put them in any room. It responds to "What is the temperature in <sensor name>?". It's much more reliable that HomeBridge too. Just another option.

**Comment by mefynn** [comment]
did anyone dig any deeper into this topic?
