### ISSUE TITLE
Is Spanish supported?

### ISSUE THREAD

**Issue by Ricardo1980** [nfarina/homebridge#639]
In this document I see many languages but I don't see Spanish
https://github.com/nfarina/homebridge/wiki/Siri-commands

Is Spanish supported? Is it supported automatically because Siri supports it?
Thanks.

**Comment by KhaosT** [comment]
If Siri supports Spanish, HomeKit commands should work automatically.

**Comment by Ricardo1980** [comment]
Yes, now it works. I don't know the reason.

The Philips Hue app, when you change the name of your room or light, it appears an exclamation icon saying that a resynchronisation with Siri is necessary. You press a button and then everything works.

That is my question, maybe homebridge also needs some kind of synchronisation with Siri. Am I right? Am I missing something?

Thanks a lot.
