### ISSUE TITLE
"There was a problem reading your config.json file." Wondering if anybody could help? 

### ISSUE THREAD

**Issue by MXPelez** [nfarina/homebridge#641]
Hi, I'm trying to setup Homebridge and am encountering issues, seemingly with the config.json file. Here is my config.json file:

> {
>     "bridge": {
>         "name": "Homebridge",
>         "username": "CC:22:3D:E3:CE:30",
>         "port": 51826,
>         "pin": "031-45-154"
>     },
>     
>     "description": "Config file for Xbox.",
> 
>     "accessories": [
>         {
>             "accessory": "Xbox",
>   		"name": "Xbox",
>   		"ipAddress": "192.168.0.20",
>   		"liveId": "FD0086CA6C9AF4A6"
>         }
>     ]
> }

Here is what Terminal is returning when I run Homebridge:

![2016-05-22-143042_1920x1080_scrot](https://cloud.githubusercontent.com/assets/19516752/15455240/89aec07c-2046-11e6-8d87-95caaaeb0954.png)

**Comment by simonrb2000** [comment]
Hi

Have you copied and pasted your config file into the website it suggests? Sometimes it's the " that are wrong.

Sent from my iPhone

On 22 May 2016, at 17:57, MXPelez <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, I'm trying to setup Homebridge and am encountering issues, seemingly with the config.json file. Here is my config.json file:

{
"bridge": {
"name": "Homebridge",
"username": "CC:22:3D:E3:CE:30",
"port": 51826,
"pin": "031-45-154"
},

"description": "Config file for Xbox.",

"accessories": [
    {
        "accessory": "Xbox",
    "name": "Xbox",
    "ipAddress": "192.168.0.20",
    "liveId": "FD0086CA6C9AF4A6"
    }
]


}

Here is what Terminal is returning when I run Homebridge:

[2016-05-22-143042_1920x1080_scrot]<https://cloud.githubusercontent.com/assets/19516752/15455240/89aec07c-2046-11e6-8d87-95caaaeb0954.png>

-

**Comment by MXPelez** [comment]
@simonrb2000 I have, it validated. I have read that sometimes the " is where it can be going wrong but it doesn't seem to be that in this case.

**Comment by jer78** [comment]
What txt editor are you using? I found on a Mac that using the default text editor always gave me problems as it put different ASCII characters than what it needed. I now use Text Wrangler on OS X and it works great so I'd try dumping whatever text editor you are using and download something else and give it a try.

The following validated for me:

`{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},

	"description": "Config file for Xbox.",

	"accessories": [{
		"accessory": "Xbox",
		"name": "Xbox",
		"ipAddress": "192.168.0.20",
		"liveId": "FD0086CA6C9AF4A6"
	}]
}`

**Comment by Ricardo1980** [comment]
I use Sublime Text 2 under MAC and no problems.

**Comment by MXPelez** [comment]
@jer78 sorry, I completely forgot to add I'm running on a Raspberry Pi.

**Comment by MXPelez** [comment]
Still haven't managed to resolve the issue. Can anybody help?

**Comment by toshibochan** [comment]
Delete "description" line

**Comment by MXPelez** [comment]
@toshibochan I deleted it, unfortunately the problem is still there

**Comment by toshibochan** [comment]
Go to www.jsonlint.com
Copy your config.json and look if correct!

**Comment by toshibochan** [comment]
Copy config.json and past to website

**Comment by MXPelez** [comment]
It is all validating successfully. Strange.

**Comment by toshibochan** [comment]
Oh! Where your config.json is locate?
Have to be in to /home/pi/.homebridge
cd /home/pi/.homebridge

**Comment by MXPelez** [comment]
My config.json is located at /usr/local/lib/node_modules/homebridge

**Comment by toshibochan** [comment]
Not there! Have to add to
/home/pi/.homebridge

**Comment by MXPelez** [comment]
Right! This is where the problem seems to be.
In /home/pi/ there is no .homebridge
Have I installed in the wrong place?

**Comment by toshibochan** [comment]
Try
cd ~/.homebridge
Or
cd /home/pi/.homebridge

**Comment by toshibochan** [comment]
Use terminal

**Comment by MXPelez** [comment]
Right okay, done that through terminal, appears it is actually there. So, what's the next step?

**Comment by toshibochan** [comment]
nano config.json
Copy you config and past and save

**Comment by toshibochan** [comment]
Work?

**Comment by MXPelez** [comment]
No luck :( There were already contents inside, tried replacing it and running home bridge again but it still produces the error.

**Comment by MXPelez** [comment]
Seems at this point starting over from a clean install may be the best option.

**Comment by toshibochan** [comment]
cd /home/pi/.homebridge
ls
What have inside?

**Comment by MXPelez** [comment]
accessories config.json pm-debug.log persist

**Comment by toshibochan** [comment]
You did
nano config.json and paste you config?

**Comment by MXPelez** [comment]
I did yeah, but when I attempted to run homebridge, it returned the same error message

**Comment by MXPelez** [comment]
Oh wait, I've done it. There was a validation error in the original file that I was copying from! It is working now

**Comment by MXPelez** [comment]
Thank-you so much for your help

**Comment by toshibochan** [comment]
Nice! I glad is working now!

**Comment by MXPelez** [comment]
@toshibochan  It's all working, but can I just ask 1 more thing, when I close terminal, I can no longer control my devices with the app on my iPhone. Do I need to configure home bridge to run in the background on my Pi or something?

**Comment by toshibochan** [comment]
Look this guys exemple:
"running at startup"
http://www.kramnameloc.com/homebridge-pi-switch
Make file:
sudo nano /etc/init.d/homebridge
Copy and past the he's second script and save
Next:
sudo chmod 755 /etc/init.d/homebridge
Next:
sudo update-rc.d homebridge defaults
Next restart the pi

**Comment by MXPelez** [comment]
@toshibochan once again thanks for you help. You've been great! 👍

**Comment by toshibochan** [comment]
Work? You welcome! I'm not developed and don't know anything about code! So people help me and I help when I can!

**Comment by MXPelez** [comment]
@toshibochan well I appreciate it a lot! You've been a big help.

**Comment by dhruvsahni** [comment]
Found the answer for all the issues....
You need to look for ./homebidge folder and then look as config.json file
I was looking at /usr/local/lib/node_modules/homebridge  all the time
