### ISSUE TITLE
Unstable platform?

### ISSUE THREAD

**Issue by JangoBritt** [nfarina/homebridge#643]
So I have homebridge installed on a Mac Mini, which is always on. I find that any time I have to restart the homebridge, whether due to restarting the machine, adding plugins, or plain old app crash, either my iPhone won't rediscover the appliance, or it does, but commands won't run, or I have to re-add the appliance (reconfiguring all my rooms & scenes)

Is Homebridge more stable on other platforms? Is it worth going out and buying something like a rPi just to get a stable Homebridge?

I'm currently running plugins HarmonyHub, and IFTTT, and planning to add LightWaveRF as soon as the module is ready for the new portal style. 

Any help greatly appreciated. 

-Adam

**Comment by jer78** [comment]
That's odd. I use a Mac Mini and it never loses the devices from HomeKit. They are just unavailable until I restart homebridge. I find my homebridge crashes with the HarmonyHub plugin. The developer is working on a fix.

**Comment by tannebil** [comment]
My Mac Mini has been rock solid as well. Homebridge is running as an OS X guest in Parallels.

**Comment by JangoBritt** [comment]
Tannebil, how come you use parallels? Why not just run it on the primary OS

Jer78, it might be harmony that's crashing it occasionally then... Still doesn't explain the times when I have to change the userid to get it to show up on the phone. 

How long does it usually take to appear after booting the Homebridge? I find that if I leave it and come back, it has often turned up.

**Comment by tannebil** [comment]
I use a VM because I wanted to be free to install and change software without putting my primary system at risk. In addition, it's easy to make a copy of the system before making a change and rolling back if things go sideways. I used a Ubuntu VM at first but decided I didn't want to spread my efforts across both OS X (which I'm quite familiar with) and Linux (where I'm barely literate).

**Comment by jer78** [comment]
The accessories show up immediately after I restart homebridge. It sounds like there's something wrong with your persist folder. I'd try deleting italong with the accessories folder. Once you restart homebridge it should recreate those folders. See if that solves it

**Comment by JangoBritt** [comment]
Looks like the HarmonyHub upgrade resolved this
