### ISSUE TITLE
MyQ Validatewithculture.

### ISSUE THREAD

**Issue by Mpfk** [nfarina/homebridge#644]
I was able to launch home bridge a few times, but now when I attempt to launch, it just ends at [MyQ] validatewithculture: exception in response validatewithculture: Unexpected toped u

I was able to launch it before without encountering any issue, and the config file is perfectly fine. Whats going on?

Thanks!

**Comment by jcostom** [comment]
Can't speak to that particular module, but I can say that homebridge-platform-myq works like a champ.  I struggled with the homebridge-myq in exactly the same way you're describing.

Maybe some hints in the code there: https://github.com/rainlake/homebridge-platform-myq

**Comment by nimustan** [comment]
When I run my-q it works for the first minute then does not work anymore. I have to shut homebridge down then launch it again to it to work for the next minute.

**Comment by AppleTechy** [comment]
Create an issue on the Plugin Github page please. Also you should run the homebridge-liftmaster plugin as it will still work with Chamberlain an is further developed and tested
