### ISSUE TITLE
Error Installing on Windows 10

### ISSUE THREAD

**Issue by bittles** [nfarina/homebridge#647]
Following the instructions for new version (with plugin), I get an error when installing homebridge, but homebridge-http installs fine.

Code:
1387 error Command failed: git -c core.longpaths=true clone --template=C:\Users\Nick\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/KhaosT/node-curve25519.git C:\Users\Nick\AppData\Roaming\npm-cache\_git-remotes\git-github-com-KhaosT-node-curve25519-git-750fb09d
1387 error Cloning into bare repository 'C:\Users\Nick\AppData\Roaming\npm-cache\_git-remotes\git-github-com-KhaosT-node-curve25519-git-750fb09d'...

Any help?

**Comment by bittles** [comment]
It's also throwing the same errors for node-srp and ed25519.

**Comment by bittles** [comment]
Installed dependency packages one by one.  bignum and srp were the biggest trouble makers, srp is unable to be installed by npm.  git clone and npm link were my work arounds.

**Comment by PatcherMustermann** [comment]
I had the same problem on my new system. There seems to be a problem of Node.JS 4.x.x.. I have updated the installtion instructions. To which i have yet elemeniert other bugs at the installtion instructions.

=> https://github.com/nfarina/homebridge/wiki/Install-Homebridge-on-Windows

Greeting
Patcher
