### ISSUE TITLE
What environment do you use to develop plugins

### ISSUE THREAD

**Issue by Ricardo1980** [nfarina/homebridge#648]
Hello!
I would like to try to develop a plugin.
What IDE do you use to create the javascript files in a MAC?
How do you debug it? (only adding a flag and reading the console maybe?)
Any related advice is welcome.
Thanks.

**Comment by apwelsh** [comment]
I use Microsoft visual studio code. It's built on top of Atom.io

I have not written any plug-ins yet, so my experience is not exactly to be considered professional. I have, however, done substantial  amounts of development for react, JavaScript, node.js,  and my personal preference for all of these which leverage all the same technologies as the plug-ins, is Micrsoft VS code

**Comment by Ricardo1980** [comment]
Thanks! Years ago I used VS in Windows, but now I only have a MAC. What do people use nowadays to develop javascript in MAC? 
Anything else I should know?
I guess the development flow is write the .js file, stop hombridge, copy the plugin (not clear this step), run homebridge and see if the plugin works. Is that right? Thanks.

**Comment by pdlove** [comment]
I use Visual Studio Code on my Mac and it works beautifully. It is a totally different environment than traditional visual studio. I'm also using SourceTree to manage my github. It works tons better than github desktop.

**Comment by Ricardo1980** [comment]
@pdlove  I had no idea about that. I try it right now, thanks.
About the working flow, how do you do it exactly? (homebridge plugin)

**Comment by Ricardo1980** [comment]
I started playing with Visual Studio Code for Mac is it is really nice.
I see there is even a debugger.
Is it possible to debug the plugin created for homebridge using that env?
Thanks.

**Comment by Ricardo1980** [comment]
I got it, using VSC it is super easy to develop plugins in my mac. Thanks. I close this.
