### ISSUE TITLE
Thermostat celsius conversion

### ISSUE THREAD

**Issue by fordracerguy** [nfarina/homebridge#65]
I am creating an accessory for my Radio Thermostat CT50. It has its own API. The unit talks in Fahrenheit, but it seems that Siri likes to talk in Celsius after viewing this thread https://github.com/KhaosT/HAP-NodeJS/issues/29

The problem is that when I say "Set the temperature to 85", Siri sends in 29 celsius instead of 29.4444, which then gets converted to 84.2F. This is just one example.

Is this a bug with Siri/HomeKit? Is it a bug with HAP? Or is it a bug with the Insteon+ app? I have traced the issue into node_modules/HAP-NodeJS/Server.js this.accessoryController.processCharacteristicsValueWrite(data, request.socket.remotePort); but cannot debug data to see if the phone is at fault or not.

![siri homekit](https://cloud.githubusercontent.com/assets/3803591/8638486/d2e4b49a-2871-11e5-88d8-3f12ae4ff8ef.png)

**Comment by nfarina** [comment]
So the only way to know for sure is to debug the call that you found. I would try dumping the raw data submitted by Siri here:

![](http://d.pr/i/18LaS+)

And see what exactly Siri is sending. If it's 29, then it would point to a bug in HomeKit.

**Comment by fordracerguy** [comment]
I can confirm that this is Siri or Insteon+. I think it is Insteon+ - although I haven't played with the iOS APIs, I think they can specify the characteristic value type. In this case, it should be a float...

Thanks!

**Comment by nfarina** [comment]
It seems like we should be able to have Siri speak in Fahrenheit directly without conversion issues. See #71 for discussion.

**Comment by minarcia** [comment]
Fordracerguy,

Did you end up getting your CT50 accessory working with Homebridge?

Thanks.

**Comment by skiksc** [comment]
Fordracerguy,

I am also interested if get my CT50 working with homebridge.  Any luck?

**Comment by fordracerguy** [comment]
Yes, I got it working. I wrote a custom accessory. From what I recall, the celsius conversion issues were fixed after this posting. I ended up taking my Raspberry Pi to work so I don't use HomeKit right now.

**Comment by skiksc** [comment]
That's great.  Would you mind sharing the code for the accessory?  I’m not much of a programmer, so I’m struggling with how customize my own accessory.

**Comment by fordracerguy** [comment]
Here you go. Add this to your config

    "accessories": [
        {
            "accessory": "RadioThermostat",
            "name": "Air Conditioner",
            "host": "x.x.x.x"
        }
    ]

[RadioThermostat.txt](https://github.com/nfarina/homebridge/files/104160/RadioThermostat.txt)

**Comment by fordracerguy** [comment]
Rename file to .js

**Comment by skiksc** [comment]
Thank you.  However, being a node.js novice, I'm having some trouble getting things in the right spots.
- I created a directory at: /usr/local/lib/node_modules/homebridge-radiothermostat
- named the .js file index.js  (to match other plugins)
Do I need a package.json file to register the plugin?

I appreciate the guidance.

Here is the output from homebridge, using a duplicated package.json file from the homebridge-httpthermostat plugin.
=====================
Loaded plugin: homebridge-http
Registering accessory 'homebridge-httpstatus.Http'
---
Loaded plugin: homebridge-http-thermostat
Registering accessory 'homebridge-http-thermostat.http-thermostat'
---
====================
ERROR LOADING PLUGIN homebridge-radiothermostat:
Error: Cannot find module 'HAP-NodeJS/accessories/types.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-radiothermostat/index.js:1:75)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
====================
Loaded plugin: homebridge-thermostat
Registering accessory 'homebridge-thermostat.Thermostat'
---
Loaded config.json with 1 accessories and 0 platforms.
---
Loading 0 platforms...
Loading 1 accessories...
/usr/local/lib/node_modules/homebridge/lib/api.js:47
      throw new Error("The requested accessory '" + name + "' was not registered by any plugin.");
      ^

Error: The requested accessory 'RadioThermostat' was not registered by any plugin.
    at API.accessory (/usr/local/lib/node_modules/homebridge/lib/api.js:47:13)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:164:42)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:36:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:23:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:467:10)

**Comment by minarcia** [comment]
Fordracerguy,

Thanks for the code.  I appreciate the work you have done.

skiksc,

I was able to get it working to an extent, although I the project doesn't appear complete.  It currently seems to only operate cooling, not heating, but I'm trying to work through and add with my limited js knowledge.

I've added the files that I used, the RadioThermostatindex.txt is largely from Fordracerguy, except that I edited the first line to work with my setup and added lines 5-9.  That should become index.js in your /usr/local/lib/node_modules/homebridge-radiothermostat/ directory.  

The RadioThermostatpackage.txt file can be copied to package.json in the same directory.  I just hacked that one together from the sample one, but it works.

You'll also need the request function available.  I found it in /usr/local/lib/node_modules/homebridge-legacy-plugins/node_modules/request/.  You'll need to copy that over (or symlink) to /usr/local/lib/node_modules/homebridge-radiothermostat/node_modules/request/.

Hopefully when you restart homebridge it should work.  I had some initial problems with it taking any commands after adding the thermostat, so if you can't get it to work, delete ~/.homebridge/persist and reboot.  Then delete and re-add the homebridge on your iOS device and it should work.  Hopefully you won't need that step, but I did.

I hope this helps!

[RadioThermostatindex.txt](https://github.com/nfarina/homebridge/files/105595/RadioThermostatindex.txt)
[RadioThermostatpackage.txt](https://github.com/nfarina/homebridge/files/105596/RadioThermostatpackage.txt)

**Comment by fordracerguy** [comment]
I finally got around to making an updated home bridge plugin. I would say another week and I can upload it.

**Comment by namannik** [comment]
@fordracerguy, I'm very interested in this plugin as well!  I was considering starting to create one on my own since it didn't seem like one exists, but it looks like you've nearly completed it.  When it's complete, will you be publishing it on the NPM web site?

**Comment by fordracerguy** [comment]
I (think) I have published it under the name homebridge-radiothermostat - first time doing this... It could have bugs, but it's a whole lot better than the previous one I wrote! Please see the github at https://github.com/fordracerguy/radiothermostat
