### ISSUE TITLE
Graduating dimmer for dimmable lights (LightwaveRF)

### ISSUE THREAD

**Issue by JangoBritt** [nfarina/homebridge#652]
Hi all,

I'm hoping to find or create a "scene" where I can dim up a lightwaverf (or other) dimmer over time, to simulate a sunrise dimmer. 

For example, if I want my bedroom lights to come up slowly over 10 minutes, I could, for example send a command to increase the percentage once every 6 seconds. 

This might work with an AppleScript plugin, but how would you call that on HomeKit, or ask Siri?

**Comment by digiltd** [comment]
How are you sending the signal to the lights?

But the shorter answer is yes it can be done, but the script that runs the wake up sequence would have to be run on something else. You would set up a switch in homebridge (there are lots of plugins inc an applescript one that you can use) and use that switch to start/stop the sequence.

Whilst I don't use a wake up script the way I control the two Lightwave Dimmer Sockets in HomeKit. With a RFXcom RFXtrx433E attached to a Pi. Then the bedside lights are plugged into sockets. OpenHAB is the core of my home automation (I can't trust HomeKit yet, keeps letting me down) and handles either using a slider or button presses to control the lights. Then the homebridge-openhab plugin to allow HomeKit control.  

You do get a smoother grade of light to dark with LightwaveRF than say the cheaper MiLight/LimitelessLED bulbs, but for super smooth get Philips Hue.

... but. If you are going to make wake up script, then there isn't much need for Siri control as I assume you would be asleep. So you could set up the script on a timer without having to mess with HomeKit.

**Comment by mattrayner** [comment]
I agree with @digiltd - a Raspberry Pi would be perfect for this
