### ISSUE TITLE
Error Ocurred, pairing attempt failed

### ISSUE THREAD

**Issue by BenediktRPl** [nfarina/homebridge#653]
Hey out there :)

I am totally new to all of this, so please bear with me. I tried to install homebridge on a Raspberry Pi B model, installed the [homebridge-gpio-wpi plugin](https://www.npmjs.com/package/homebridge-gpio-wpi) and configured the config file like this:

![configjson](https://cloud.githubusercontent.com/assets/5982817/15805098/72172902-2b1f-11e6-8297-6fde97b65ff8.png)

Then I started the homebridge:

![homebridge](https://cloud.githubusercontent.com/assets/5982817/15805102/895fc754-2b1f-11e6-90bc-8b90640e7fdf.png)

and it was discovered on iDevices on my iPad Mini (iOS 9) and this showed up:

![confirmbeep](https://cloud.githubusercontent.com/assets/5982817/15805106/af9e59b2-2b1f-11e6-9fe6-c4cda8a67ede.PNG)

assuming it is just for security I told him "roger, target confirmed" and the next thing appears:

![addanyway](https://cloud.githubusercontent.com/assets/5982817/15805113/dd447cca-2b1f-11e6-840c-3692eb2c52cc.PNG)

well, that is also obvious when you are working with a RPi so "add anyway", then enter the code:

![entercode](https://cloud.githubusercontent.com/assets/5982817/15805117/0073da56-2b20-11e6-8237-c5c67604f849.PNG)

and then you are finally thinking whoo I got this but no, the iPad tells you it is a (bad) monday morning:

![error](https://cloud.githubusercontent.com/assets/5982817/15805118/24f7efe8-2b20-11e6-8677-3c04c03e1b17.PNG)

After having given up in the middle of the night I started all over, flashed the SD card, updated and upgraded, installed the lib, installed node v4.3.0, installed homebridge, installed gpio-plugin and tried again - but no luck. Any thoughts? What am I doing wrong other than getting more and more sarcastic over Apple protocols and not blaming myself?

Thanks for your help, I really appreciate it!

**Comment by tannebil** [comment]
IDevices says Bluetooth needs to be turned on but it appears to be off. I've only seen the pairing error with Bluetooth So my guess is you need to turn on Bluetooth.

**Comment by BenediktRPl** [comment]
Thanks for the idea! Unfortunately it did not work, it would have been too easy to be true, as I tried earlier with iDevices, Insteon+ and the Elgato app... Only in iDevices an error output shows up, in the two other apps there is just a fall back to the "add device" panel in the app(s) itself.

I had also the idea of changing the system time to my local time on the Pi but also no luck. I am going to try with my iPhone but need to charge it. When it works I will comment, if not not.
I should have done some wiring with the Pi in that case I would have bricked the Pi not the weekend :) 

Thank you for the comment tannebil

**Comment by jer78** [comment]
Do you have any other plugins you could try instead? Just to eliminate the plugin as being the culprit.

**Comment by KraigM** [comment]
Also is it reading the Pin correctly? Maybe try manually entering in the pin (it could be mistaking the 0 as 8 and assuming you entered an invalid pin)?

**Comment by BenediktRPl** [comment]
Now I am speechless 💃 I tried to science the sh*t out of this and finally, the easiest step when not depending on image recognition services is to type. With your fingertips. Hell no :D Thank you all for the help :) I feel dumb now but the feeling of the LED dancing to your own voice is all worth it! Thanks again...
