### ISSUE TITLE
No mirrors for ARM cpu (Rasberry Pi) version of libavahi-compat-libdnssd-dev

### ISSUE THREAD

**Issue by rongierlach** [nfarina/homebridge#659]
When  I run `sudo apt-get install libavahi-compat-libnssd-dev`
The response is `E: Unable to locate package libavahi-compat-libnssd-dev`

I took a look at the page for the package and there are no ARM versions listed:
http://packages.ubuntu.com/wily/armhf/libavahi-compat-libdnssd-dev/download

Using a Rasberry Pi 3, Model B with Raspbian installed.
Looked through some of the mirrors' directories and not finding anything.
Is there a way I can install without using apt-get?

**Comment by tanuva** [comment]
I think you might simply have forgotten a 'd' in the package name. :)
Searching for `libavahi-compat-libdnssd-dev`, it is [found for several architectures](http://packages.ubuntu.com/search?suite=wily&searchon=names&keywords=libavahi-compat-libdnssd-dev).

**Comment by rongierlach** [comment]
oh man... 😝 

thanks @tanuva
