### ISSUE TITLE
Help - error in Git GMD when installing Homebridge on Window using npm install -g homebridge

### ISSUE THREAD

**Issue by Sporekid** [nfarina/homebridge#661]
I am following instruction "Install Homebridge on Windows" to startoff

First I encountered error  at Running Homebridge: step 2, below is the debug log.
[npm-debug.log.txt](https://github.com/nfarina/homebridge/files/311354/npm-debug.log.txt)

I continued further and notice discrepancy to your instruction at 5.1 where the file I found was sample-config.json instead of config-sample.json.

Stuck currently at 6 due to directory not exist.
Only folder in homebridge folder is C:\Users\Sporekid\AppData\Roaming\npm\node_modules\homebridge\node_modules

To add on, at installation of software, 8.3\* - Copy following text in the file unistd.h, I had used Version of Patcher, not sure if this may affect the results.

**Comment by Sporekid** [comment]
To add on, at installation of software, 8.3* - Copy following text in the file unistd.h, I had used Version of Patcher, not sure if this may affect the results.

**Comment by Stagg62** [comment]
Hi, it seems that i am in the same case. Trying to install on Window 7 32bits. I followed the install on windows wiki  Tryed both unistd.h the second one seems to be better in my case but i already get errors reading dns_sd.h file.

C:\Users\Domoticz\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns>
if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\n
pm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  els
e (node  rebuild )
Génération des projets individuellement dans cette solution. Pour activer la gén
ération en parallèle, ajoutez le commutateur "/m".
  dns_sd.cpp
  dns_service_browse.cpp
c:\users\domoticz\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns
\src\mdns.hpp(32): fatal error C1083: Impossible d'ouvrir le fichier include :
'dns_sd.h' : No such file or directory (compilation du fichier source ..\src\dn
s_sd.cpp) [C:\Users\Domoticz\AppData\Roaming\npm\node_modules\homebridge\node_m
odules\mdns\build\dns_sd_bindings.vcxproj]
  dns_service_enumerate_domains.cpp
c:\users\domoticz\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns
\src\mdns.hpp(32): fatal error C1083: Impossible d'ouvrir le fichier include :
'dns_sd.h' : No such file or directory (compilation du fichier source ..\src\dn
s_service_browse.cpp) [C:\Users\Domoticz\AppData\Roaming\npm\node_modules\homeb
ridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  dns_service_get_addr_info.cpp
c:\users\domoticz\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns
\src\mdns.hpp(32): fatal error C1083: Impossible d'ouvrir le fichier include :
'dns_sd.h' : No such file or directory (compilation du fichier source ..\src\dn
s_service_enumerate_domains.cpp) [C:\Users\Domoticz\AppData\Roaming\npm\node_mo
dules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  dns_service_process_result.cpp
c:\users\domoticz\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns
\src\mdns.hpp(32): fatal error C1083: Impossible d'ouvrir le fichier include :
'dns_sd.h' : No such file or directory (compilation du fichier source ..\src\dn
s_service_get_addr_info.cpp) [C:\Users\Domoticz\AppData\Roaming\npm\node_module
s\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  dns_service_ref.cpp
c:\users\domoticz\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns
\src\mdns.hpp(32): fatal error C1083: Impossible d'ouvrir le fichier include :
'dns_sd.h' : No such file or directory (compilation du fichier source ..\src\dn
s_service_process_result.cpp) [C:\Users\Domoticz\AppData\Roaming\npm\node_modul
es\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  dns_service_ref_deallocate.cpp
c:\users\domoticz\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns
\src\mdns.hpp(32): fatal error C1083: Impossible d'ouvrir le fichier include :
'dns_sd.h' : No such file or directory (compilation du fichier source ..\src\dn
s_service_ref.cpp) [C:\Users\Domoticz\AppData\Roaming\npm\node_modules\homebrid
ge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  dns_service_ref_sock_fd.cpp
c:\users\domoticz\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns
\src\mdns.hpp(32): fatal error C1083: Impossible d'ouvrir le fichier include :
'dns_sd.h' : No such file or directory (compilation du fichier source ..\src\dn
s_service_ref_deallocate.cpp) [C:\Users\Domoticz\AppData\Roaming\npm\node_modul
es\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  dns_service_register.cpp
c:\users\domoticz\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns
\src\mdns.hpp(32): fatal error C1083: Impossible d'ouvrir le fichier include :
'dns_sd.h' : No such file or directory (compilation du fichier source ..\src\dn
s_service_ref_sock_fd.cpp) [C:\Users\Domoticz\AppData\Roaming\npm\node_modules\
homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  dns_service_resolve.cpp
c:\users\domoticz\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns
\src\mdns.hpp(32): fatal error C1083: Impossible d'ouvrir le fichier include :
'dns_sd.h' : No such file or directory (compilation du fichier source ..\src\dn
s_service_register.cpp) [C:\Users\Domoticz\AppData\Roaming\npm\node_modules\hom
ebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  dns_service_update_record.cpp
c:\users\domoticz\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns
\src\mdns.hpp(32): fatal error C1083: Impossible d'ouvrir le fichier include :
'dns_sd.h' : No such file or directory (compilation du fichier source ..\src\dn
s_service_resolve.cpp) [C:\Users\Domoticz\AppData\Roaming\npm\node_modules\home
bridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  mdns_utils.cpp
c:\users\domoticz\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns
\src\mdns.hpp(32): fatal error C1083: Impossible d'ouvrir le fichier include :
'dns_sd.h' : No such file or directory (compilation du fichier source ..\src\dn
s_service_update_record.cpp) [C:\Users\Domoticz\AppData\Roaming\npm\node_module
s\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  network_interface.cpp
c:\users\domoticz\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns
\src\mdns.hpp(32): fatal error C1083: Impossible d'ouvrir le fichier include :
'dns_sd.h' : No such file or directory (compilation du fichier source ..\src\md
ns_utils.cpp) [C:\Users\Domoticz\AppData\Roaming\npm\node_modules\homebridge\no
de_modules\mdns\build\dns_sd_bindings.vcxproj]
  socket_watcher.cpp
c:\users\domoticz\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns
\src\mdns.hpp(32): fatal error C1083: Impossible d'ouvrir le fichier include :
'dns_sd.h' : No such file or directory (compilation du fichier source ..\src\ne
twork_interface.cpp) [C:\Users\Domoticz\AppData\Roaming\npm\node_modules\homebr
idge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  txt_record_ref.cpp
c:\users\domoticz\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns
\src\mdns.hpp(32): fatal error C1083: Impossible d'ouvrir le fichier include :
'dns_sd.h' : No such file or directory (compilation du fichier source ..\src\so
cket_watcher.cpp) [C:\Users\Domoticz\AppData\Roaming\npm\node_modules\homebridg
e\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  txt_record_create.cpp
c:\users\domoticz\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns
\src\mdns.hpp(32): fatal error C1083: Impossible d'ouvrir le fichier include :
'dns_sd.h' : No such file or directory (compilation du fichier source ..\src\tx
t_record_ref.cpp) [C:\Users\Domoticz\AppData\Roaming\npm\node_modules\homebridg
e\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  txt_record_deallocate.cpp
c:\users\domoticz\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns
\src\mdns.hpp(32): fatal error C1083: Impossible d'ouvrir le fichier include :
'dns_sd.h' : No such file or directory (compilation du fichier source ..\src\tx
t_record_create.cpp) [C:\Users\Domoticz\AppData\Roaming\npm\node_modules\homebr
idge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  txt_record_set_value.cpp
c:\users\domoticz\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns
\src\mdns.hpp(32): fatal error C1083: Impossible d'ouvrir le fichier include :
'dns_sd.h' : No such file or directory (compilation du fichier source ..\src\tx
t_record_deallocate.cpp) [C:\Users\Domoticz\AppData\Roaming\npm\node_modules\ho
mebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  txt_record_get_length.cpp
c:\users\domoticz\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns
\src\mdns.hpp(32): fatal error C1083: Impossible d'ouvrir le fichier include :
'dns_sd.h' : No such file or directory (compilation du fichier source ..\src\tx
t_record_set_value.cpp) [C:\Users\Domoticz\AppData\Roaming\npm\node_modules\hom
ebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  txt_record_buffer_to_object.cpp
c:\users\domoticz\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns
\src\mdns.hpp(32): fatal error C1083: Impossible d'ouvrir le fichier include :
'dns_sd.h' : No such file or directory (compilation du fichier source ..\src\tx
t_record_get_length.cpp) [C:\Users\Domoticz\AppData\Roaming\npm\node_modules\ho
mebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
c:\users\domoticz\appdata\roaming\npm\node_modules\homebridge\node_modules\mdns
\src\mdns.hpp(32): fatal error C1083: Impossible d'ouvrir le fichier include :
'dns_sd.h' : No such file or directory (compilation du fichier source ..\src\tx
t_record_buffer_to_object.cpp) [C:\Users\Domoticz\AppData\Roaming\npm\node_modu
les\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files\MSBuild\14.0\bin\msbuild.exe` failed wit
h exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Domoticz\AppData\Roaming\npm\node_modules\homebridge\node_
modules\mdns
gyp ERR! node -v v5.0.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
- C:\Users\Domoticz\AppData\Roaming\npm\node_modules\homebridge\node_modules\big
num node_modules\homebridge\node_modules\bignum
npm WARN ENOENT ENOENT: no such file or directory, open 'C:\Users\Domoticz\AppDa
ta\Roaming\npm\node_modules\homebridge\package.json'
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "homebridge" "--unsafe-perm"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE

npm ERR! mdns@2.3.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mdns@2.3.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the mdns package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls mdns
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Domoticz\npm-debug.log

Any idea ?


[npm-debug.log.txt](https://github.com/nfarina/homebridge/files/311423/npm-debug.log.txt)

**Comment by PatcherMustermann** [comment]
@Sporekid: I have seen that you have Node.js 4.4.5 installed. In my description is the Version Node.js 5.0.0. I also had problems with the 4.x.x version! Test Node.js 5.0.0.

**Comment by PatcherMustermann** [comment]
@Sporekid: It works now?

**Comment by Sporekid** [comment]
@PatcherMustermann sorry I haven had the time to retry with Test Node.js 5.0.0
I recall I had problem downloading the 5.0.0 version at the link, i'll try agn soon and update

**Comment by Sporekid** [comment]
@PatcherMustermann Still encountering error. I have currently upgraded to Node.js v5.11.1
[npm-debug.log.txt](https://github.com/nfarina/homebridge/files/322077/npm-debug.log.txt)
