### ISSUE TITLE
iOS10 HomeKit new Service Types

### ISSUE THREAD

**Issue by JangoBritt** [nfarina/homebridge#663]
So last night, Apple announced 5 new Service types for HomeKit:

Air Conditioners
Cameras
Doorbells
Air Purifiers
Humidifiers.

I'm not sure how much more interesting the A/C, Purifiers, and Humidifiers, are going to be, at least in the UK, but I'm definitely interested in the cameras and doorbells services.

So what does everyone else think? What else do you have that could be integrated with HomeBridge, using these new Service Types?

**Comment by simonrb2000** [comment]
That's assuming we can get homebridge to work in iOS 10 :)

Sent from my iPhone

On 14 Jun 2016, at 09:07, JangoBritt <notifications@github.com<mailto:notifications@github.com>> wrote:


So last night, Apple announced 5 new Service types for HomeKit:

Air Conditioners
Cameras
Doorbells
Air Purifiers
Humidifiers.

I'm not sure how much more interesting the A/C, Purifiers, and Humidifiers, are going to be, at least in the UK, but I'm definitely interested in the cameras and doorbells services.

So what does everyone else think? What else do you have that could be integrated with HomeBridge, using these new Service Types?

-

**Comment by exsilium** [comment]
The Doorbell is interesting, it reminds me of a true push-button-like-service. Instead of that I currently need to use a switch that has a timeout to turn itself back off.

**Comment by apwelsh** [comment]
Irrigation controllers are missing from that list from what I can tell.  It would be nice to be abke to simply tell siri do not water ghe backyardbfor the next 24 hours, so the spinklers dont come on during a party, or to create a rule that delays watering until after goodnight mode is activated.

**Comment by respectTheCode** [comment]
@simonrb2000 Homebridge is working with iOS 10 and TvOS 10

**Comment by anthonycastelli** [comment]
I haven't been ablate get it to work. Everything returns `No Response`

**Comment by simonrb2000** [comment]
Cheer Kevin.

It's working on my iOS 10 and WatchOS 3 however it does play up a bit. For example when I open my garage door it notifies me about 5 times that it's closed then open which is strange lol

Sent from my iPhone

On 16 Jun 2016, at 15:41, Kevin Smith <notifications@github.com<mailto:notifications@github.com>> wrote:


@simonrb2000<https://github.com/simonrb2000> Homebridge is working with iOS 10 and TvOS 10

-

**Comment by xmuskrat** [comment]
I've be very interested in getting camera support.

**Comment by JangoBritt** [comment]
Anyone configured any new iOS 10 service types yet? I'm looking at my baby monitors specifically, and rubbing my hands together
