### ISSUE TITLE
/usr/lib/node_modules/homebridge/lib/server.js:176     throw err;

### ISSUE THREAD

**Issue by eztarget** [nfarina/homebridge#668]
i seem to be having similar issues to others i found here and not sure what to do.  i am running an ubuntu server in a Virtual BOX VM.  when i apply my config.json which checked out on JSONLint fine it throws the above error.  here is my file and the full error below.  i used nano to create the file - pasted in from notepad

{
"bridge": {
"name": "Homebridge",
"username": "D0:00:00:00:00:00",
"port": 51826,
"pin": "031-45-154"
},

"description": "JSON API",
"platforms": [{
"platform": "SmartThings",
"name": "SmartThings",
"app_url": "https://graph.api.smartthings.com:443/api/smartapps/installations/",
"app_id": “xxxxx“,
"access_token": “xxxxx“
}]
}

[6/16/2016, 3:46:28 PM] Registering platform 'homebridge-nest.Nest'
[6/16/2016, 3:46:28 PM] ---
[6/16/2016, 3:46:28 PM] There was a problem reading your config.json file.
[6/16/2016, 3:46:28 PM] Please try pasting your config.json file here to validate it: http://jsonlint.com
[6/16/2016, 3:46:28 PM]
/usr/lib/node_modules/homebridge/lib/server.js:176
    throw err;
    ^

SyntaxError: Unexpected token {
    at Object.parse (native)
    at Server._loadConfig (/usr/lib/node_modules/homebridge/lib/server.js:170:19)
    at new Server (/usr/lib/node_modules/homebridge/lib/server.js:44:23)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:148:18)
    at node.js:405:3

thanks
scott

**Comment by jer78** [comment]
The original config file has "accessories" too. Did you try leaving that part in even though you don't have accessories?

**Comment by eztarget** [comment]
i did try adding one i was having issues with the format of the file.  i could never seem to get it right and validated on the JSONLit

**Comment by jer78** [comment]
Try this...it validates fine for me. If you're having problems, it may be the ". Depending on the editor you're using it seems to use a different ASCII code:

{
    "bridge": {
        "name": "Homebridge",
        "username": "CA:27:4E:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    
    "description": "JSON API",

	"accessories": [
	{
		"accessory": "marantz-volume",
		"name": "Stereo Volume",
		"host": "192.168.1.50",
		"maxVolume": 55
	}
],
    "platforms": [
        {
            "platform": "SmartThings",
            "name": "SmartThings",
            "app_url": "https://graph.api.smartthings.com:443/api/smartapps/installations/",
            "app_id": "xxxxx",
            "access_token": "xxxxx"
        }
    ]
}

**Comment by eztarget** [comment]
ok i used that, validated it on JSONLit and still got the same error.  should i try a different text editor?  i paste the same thing into JSONLit as i did into nano

**Comment by jer78** [comment]
Yeah try a different editor. I use Text Wrangler on a Mac. They may have other platforms available too. It's most likely the " that's your problem

**Comment by eztarget** [comment]
oh the " throughout the file?  i tried notepad ++ and even saved it as a json file which is an option in that app - not sure if that would make a difference.  did not work.  tried atom and that did not work either.  so are you saying to try a different character in place of the "?

**Comment by jer78** [comment]
Yes, in my experience it's usually the type of " when copying and pasting that for some reason get changed. When you paste into JSONlit, look to see if some are different. The angled " are usually th culprit.

**Comment by eztarget** [comment]
so i manually typed it in using nano and have the same error.  thoughts?
![config json](https://cloud.githubusercontent.com/assets/18711442/16287180/efb8bcba-38a6-11e6-8785-bae980bf8db5.png)

**Comment by robertvorthman** [comment]
That's not valid JSON.  You have "accessory": followed by an open bracket with no closing bracket, just above the line that says "Stereo Volume".  I think your accessory should look like this:
```

   {
        "accessory": "marantz-volume",
        "name": "Stereo Volume",
        "host": "192.168.1.198",
        "maxVolume": 70
    }
```

**Comment by eztarget** [comment]
ok that was a typo.  removed and same thing...
