### ISSUE TITLE
iOS 10 & WeMo plugin crashing 

### ISSUE THREAD

**Issue by pauloruberto** [nfarina/homebridge#669]
Initially the plugin works, but once I leave it for a little while, it will throw an error.

http://i.imgur.com/5Y5Sm3i.png

**Comment by red-gee** [comment]
I've iOS 10 beta, and homebridge does not seem to work at all. 
How did you manage to let it run? 
I have iOS 10 on iPad 
And iOS 9.3 Beta on iPhone. 

Ios 9.3 Beta Runs without any problems.

**Comment by AppleTechy** [comment]
Have you narrowed down the issue to the WeMo Plugin? If so can you create a
new issue on the  WeMo Repo and if u want u can reference this issue on the
main homebridge repo.

**Comment by red-gee** [comment]
Sorry, but I think it's not the WeMo plugin for me.  I've deleted all of my plugins one by one and try to get connected to, but nothing works on my iOS 10. So I think I'm setting up a "fresh" HomeKit raspy and try it again.
