### ISSUE TITLE
Can only add one Device on Raspberry Pi 2

### ISSUE THREAD

**Issue by bahlo** [nfarina/homebridge#67]
Hello,

it works just great on my Mac, but when I run it on my Raspberry Pi 2, it wouldn't add a second device.

I tried resetting my HomeKit configuration and deleted the `persist`-Folder. 
I can add one device, the second one appears but when I select it, it wouldn't return and states as `busy`.

**Comment by nfarina** [comment]
Hm - doing the same thing on RPi as on Mac? And when you say "select it" you mean in your iOS app?

**Comment by bahlo** [comment]
Yes, the same configuration and the same network. Only difference may be the architecture.

I'm using this app: http://itunes.apple.com/app/id995994352

I can see it under devices but I won't get prompted for an authentication pin. It just does nothing.

**Comment by nfarina** [comment]
Well I just ordered a RPi 2 for myself so I guess we'll see if it works :)

**Comment by nfarina** [comment]
Closing this for now as Homebridge is exposed as a single device (and adding it works fine on my RPi 2). If you're still having the issue with the latest version then feel free to reopen!
