### ISSUE TITLE
UUID Problem

### ISSUE THREAD

**Issue by jer78** [nfarina/homebridge#670]
So here's a new problem I'm facing and not sure if it's a plug-in that's causing the issue or what. So I have multiple plugins (harmony-hub, applescript, netatmo etc.) I have been using these for months with no issues. I decided to add a few more plugins (applescript-lightbulb, Marantz-denon) and updated to the harmonyhub-0.2.0-alpha and now I'm getting this issue. 

Homebridge starts up fine, so there are no UUID collisions (or devices named the same thing). But after awhile, something causes homebridge to crash. Normally, I can restart Homebridge and it work fine again. But now, I'm getting the UUID error. It's as if, the first time all my plugin's register correctly, but then on relaunch, one plugin is trying to re-register it as a new device instead of as an existing one. I had to delete my persist and accessories folder and re-pair homebridge and once again it works until the crash then I'm at the same problem. 

Has anyone had certain plugins that are the culprits? or should I go through them one by one and figure which one is causing problems? Each time I will have to delete and restart from scratch so it's kind of annoying to do by trial and error.

**Comment by ncosper** [comment]
I had this problem when two devices had the same name. Caused the uuid error... Not sure if thats your problem but thats what I had

**Comment by jer78** [comment]
Thanks. It's true this error is caused by two devices having the same name but in my case, it's not that way when I first launch homebridge and pair. It seems to want to create a duplicate after the fact. I narrowed it down to the HarmonyHub 0.2.0 alpha plugin. Trying to still figure out what is causing the problem.

**Comment by ncosper** [comment]
mine was also from the harmonyhub... I had two things called TV on two different hubs.
