### ISSUE TITLE
Homebridge Start issue

### ISSUE THREAD

**Issue by andrewdutoit1978** [nfarina/homebridge#671]
Hi Guys,

Sorry new to this world, got everything compiled on windows server 2012 R2 but when I try to run homebridge I get this bignum not found error (see below). It looks like the path is correct? So not sure whats going on! I am sure it is something silly I am not seeing

Thanks
 Andrew 

C:\Users\Andrew\AppData\Roaming\npm\node_modules\homebridge\bin>homebridge
module.js:450
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: The specified module could not be found.
\?\C:\Users\Andrew\AppData\Roaming\npm\node_modules\homebridge\node_modules\big
num\binding\bignum.node
    at Error (native)
    at Object.Module._extensions..node (module.js:450:18)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\Andrew\AppData\Roaming\npm\node_modules\home
bridge\node_modules\bignum\index.js:4:11)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)

C:\Users\Andrew\AppData\Roaming\npm\node_modules\homebridge\bin>

**Comment by dolanmiu** [comment]
Did you try to npm install?

**Comment by PatcherMustermann** [comment]
@Andrew: Have you Node.js 5.0.0 installed?

**Comment by andrewdutoit1978** [comment]
Hi 

Thanks for the reply yes I ran npm install on homebridge and then also tried installing bignum globally with -g option. Didnt work, and yes I am running node 5.0

**Comment by PatcherMustermann** [comment]
Maybe this will help you: https://github.com/justmoon/node-bignum/issues/32

**Comment by andrewdutoit1978** [comment]
Sorry just to be clear the install process works fine. It has a lot of warnings around casting nr's to different types and it might loose data. But Homebridge installs successfully. The error happens when trying to run it

**Comment by mikeknoop** [comment]
Also having this same problem.
