### ISSUE TITLE
Homebridge still thinks an uninstalled plugin exists

### ISSUE THREAD

**Issue by MorningZ** [nfarina/homebridge#672]
So for my homebridge application running here, I have it running on a Mac Mini here on the house and all has been working great to get two WeMo switches and my Assurelink garage door working with HomeKit.

Back when I first set everything up, i installed/tried the homebridge-itunes plugin, but couldn't get it to work, so I uninstalled it (npm uninstall -g homebridge-itunes).  there is no sign of it in my config.json (~/.homebridge/config.json) yet you can see that homebridge is still trying to load something related to it. (see screen shot from terminal)

There are also all the iTunes-related "devices" listed in my HomeKit configuration as well (see screenshot from my phone, bottom 6 boxes)

What/where I am missing to eradicate this plugin from my homebridge/homekit configuration?  I don't understand where it's getting queued to get loaded.

![homebridge_issues_mac](https://cloud.githubusercontent.com/assets/444050/16172288/7d082454-3553-11e6-987e-f977b044d02a.jpg)

![homebridge_issues_phone](https://cloud.githubusercontent.com/assets/444050/16172289/81653582-3553-11e6-9be1-6572510d9298.PNG)

**Comment by JangoBritt** [comment]
This sorted it for me... I had previously already removed the persist folder, but it was the CachedAccessories file in the Accessories Folder that was doing it.

**Comment by kevingelion** [comment]
@MorningZ what app is in your screenshot?

**Comment by KhaosT** [comment]
Hesperus

**Comment by VeniceNerd** [comment]
@AppleTechy could you clarify the "repair" part of your comment? How does one do that?

**Comment by snowdd1** [comment]
It's supposed to read re-pair, as in *pair the homebridge with HomeKit again*

**Comment by dermotos** [comment]
I have this problem, will deleting the persist folder cause ALL my devices to reset and lose my configuration?

**Comment by Samfox2** [comment]
Unfortunatelly yes...

**Comment by JangoBritt** [comment]
Try emptying the CachedAccessories folder instead
