### ISSUE TITLE
Writing Plugin API Explanation Needed!

### ISSUE THREAD

**Issue by LongPotato** [nfarina/homebridge#673]
Hi,

Thank you for creating this awesome environment!

I am learning to write my own plugin for a socket switch, I have the node package and I can turn in it on and off using the command line already. Now i want to integrate it with homekit using homebridge.

I am having trouble understanding the API. I looked at the example and the wemo plugin, I can see the structure (create a platform and register it...) but I don't understand the flow.

For example: 
[Wemo](https://github.com/rudders/homebridge-wemo/blob/master/index.js)
`WeMoAccessory.prototype.getPowerOn = function(callback) { }`

To toggle the switch, how can homekit knows which function to executed? How can it know the function above, `getPowerOn`,  will switch the socket on?

All the plugins have different function names so I don't think naming matter. I don't understand how home bridge can call the proper function to execute the action.

If anyone can give me an overview about the structure, the flow or guide me to the right direction, I will really appreciate it!

Thank you!

**Comment by jschwalbe** [comment]
Seconded -- I "know" a few programming languages and am very computer literate but this is tricky! I also have a command line solution for one of my appliances.

@LongPotato I'm looking into https://www.npmjs.com/package/homebridge-readablehttp as it seems like a nice place to start. Haven't figured out how to do a shell command yet, though.

**Comment by Ricardo1980** [comment]
I totally agree. 
We need docs for that.

**Comment by cflurin** [comment]
You can install [homebridge-punt](https://github.com/cflurin/homebridge-punt), it has a build in simulator.
It isn't easy to understand but there are several `this.log.debug` (index.js, lib/accessory.js) that you can uncomment and then start homebridge this way:
```sh
homebridge -D
```
