### ISSUE TITLE
HomeBridge on Windows - moving installation to another PC

### ISSUE THREAD

**Issue by paulobriennz** [nfarina/homebridge#676]
Hello.  Have homebridge running on WIndows thanks to this awesome guide here - thanks very much for creating!!  https://github.com/nfarina/homebridge/wiki/Install-homebridge-on-Windows

Would anyone know what components are required if I wanted to move the homebridge implementation to another PC?  So all running on my laptop where I 'built' the solution using Visual Studio etc.. but wondering if i can possibly install NodeJS/Python and whatever other core components are needed and then move the compiled homebridge (and associated) folders under C:\Users\xxx\AppData\Roaming\npm to another machine and execute there?

Any help greatly appreciated..

**Comment by PatcherMustermann** [comment]
> Hello. Have homebridge running on WIndows thanks to this awesome guide here - thanks very much for creating!! https://github.com/nfarina/homebridge/wiki/Install-homebridge-on-Windows
 
You are Welcome :)

> Would anyone know what components are required if I wanted to move the homebridge implementation to another PC?

The same question already went me through my mind. If I had more time, I would experiment a little. Maybe, you can give me a answer later ;)


Greeting
Patcher

**Comment by paulobriennz** [comment]
Think im 99% sorted. 
I just started moving and installing bits until i got some joy :)

I have one issue that maybe isnt an issue due to moving the deployment but will document that below.

Here are the steps i followed to move the deployment and the 'gotcha' i struggled with.. maybe someone can comment on how to get round this too.

I moved this to an HP i5 Laptop running Windows 10.
The firewall was already off on this PC.. so i presume if your firewall was on youd need to open port 51.. that homebridge uses?

My laptop also had GIT installed on it as well.  Again, not sure if this is needed but it was on the laptop anyway so i left it there.

I copied the C:\Users\xxx\.homebridge folder (with the config file) from the machine i built the solution on initially to the new laptop in the same place.

I also copied the C:\Users\xxx\AppData\Roaming\npm folder (and its contents) to the new laptop as well.

I then tried to start homebridge and obviously got errors as dependencies were missing so i kept installing the bits below and running until i had some luck.  

Nodejs v5.0.0 32BIT (https://nodejs.org/en/download/releases/)
Python 2.7.11 32BIT (https://www.python.org/downloads/)
Open SSL 1.0.2h 32BIT (http://slproweb.com/products/Win32OpenSSL.html)
Bonjour for Developers 3.0.0.10 (https://developer.apple.com/bonjour/)

I am not 100% sure if i needed Bonjour - homebridge actually started before instaling Bonjour but i had an issue with my phone seeing it, hence why i thought maybe some mDNS bit was missing.. 

When i went to start homebridge on the new laptop, it did start but i realised, i should change the name and the ID in the config file so i know im dealing with the new implementation not the old.

I tried searching for new accessories, nothing.  I added a new house and tried searching for accessories.. nothing.

I then blitzed my homebridge config on my phone and retried setting up.. i then realised homebridge was still running on the old PC.  So i stopped it and tried again, and viola.. i saw the new homebridge accessory.  I connected and was away!!

So, i think by copying the implementation from oid to new, there was 'seomthing else' that was common between old and new install that was conflicting when i had both old and new bridges running???  i thought chaning the name and the id at the top of the config file would have been enough?  anyways, i dont plan to run the old implementation now as it is now living on the laptop i want to run it on for ever more.  Maybe someone can explain what needs to change so both bridges could run.. and the new bridge could be truly unique and run in parallel on the same LAN..


Last trick i had, and this may be nothing to do with the install.. is that with my config from my old pc, the start up crashed on this line in my basic light setup.
	"status_url":  "http://localhost/status/100059",		

It tried to check localhost - and got a Connection Refused 127.0.0.1:80 and homebridge crashed in the homebridge-http module.

This may very well be something on my new laptop listening and refusing the conection on Port 80.. as i wasnt using the status_url, i just removed the bogus URL and all is well.

So homebridge may have crashed at this stage if i had built the solution here..

Anyways, i moved the install and im happy.. im just not 100% sure i havent got some gremlins becuase of my hack move ;)
