### ISSUE TITLE
wink module doesnt get zwave nodes

### ISSUE THREAD

**Issue by grinch72** [nfarina/homebridge#68]
Wink module doesnt pull zwave lights via the API calls.  Only lights that return are zigbee lights?

**Comment by maddox** [comment]
That very well might be true. I used a simple "lights" function in the wink lib I used. Maybe it's scoped to just zigbee bulbs.

**Comment by grinch72** [comment]
I see you make a call to light_bulb.  In Wink there is also a binary_switch.  I think you need a function similar to lights to pull those in.  I'd also love to see the powerstrips come in as well.

**Comment by schenke72** [comment]
I too have the same issue. light_bulb are pulled in but binary_switches are not. Any help would be greatly appreciated

**Comment by aen3** [comment]
Did anyone figure out how to get this to work with binary_switches?  I got my binary switch accessories to load but I get "TypeError: Cannot read property 'on' of undefined" when trying to change the state.

**Comment by schenke72** [comment]
I have not seen a fix yet.
