### ISSUE TITLE
Multiple paired devices

### ISSUE THREAD

**Issue by ncosper** [nfarina/homebridge#681]
I cannot seem to get multiple devices to pair. 
I am running homebridge on a raspberry pi. Device 1 pairs and works perfect. One same icloud account ipad also works well. But when trying to pair a second device that has a different icloud account it won't acknowledge homebridge as an accessory without deleting the persist folder. I believe that deleting this folder also deletes the pairing from device 1. 
Is there any way to add a second device? I tried to add the device code from device 2 from accessoryinfo.xxx.json after device 1's code to the json file but that didn't work. 
Any solutions to this?

**Comment by justme-1968** [comment]
homekit devices can only be paired with one apple id. this is a security feature.

for all other iOS devices you have to use sharing from within homekit.

**Comment by ncosper** [comment]
bummer... The sharing just will not seem to work. I've probably invited the others 50 times and sometimes the invite goes through but never controls the devices.

**Comment by jer78** [comment]
I've had lots of problems with sharing too. A few troubleshooting tips are 1) sign in and out of iCloud on both devices. 2) Make sure the keychain is turned on for all devices and 3) all else fails and you're still seeing the "invited" status, reset HomeKit and rebuild. Unfortunately, step 3 has been the one that's worked the most often for me. It's a real PITA but seems like something gets corrupted and needs to be rebuilt

**Comment by jgillman** [comment]
For what it's worth it I invited a friend who has two emails associated with their Apple account: `example@gmail.com` and `example@icloud.com`

When I sent the invite to their Gmail one it didn't work. When I used the iCloud address they received a push notification invite immediately. Maybe that'll work for others!
