### ISSUE TITLE
Verify Fail error

### ISSUE THREAD

**Issue by jsg4** [nfarina/homebridge#683]
After running Homebridge with HomeAssistant platform and 2 Liftmaster garage accessories, I just saw this error which stopped homebridge. Any clue what it is related to? Had been running for probably 2 days no issue before.

Verify Fail
Layer Decrypt fail!
Verify Fail
Layer Decrypt fail!
undefined:1
{"characteristics":[{"aid":2,"iid":13,"ev":true},{"aid":2,"iid":16,"ev":true},{"aid":3,"iid":13,"ev":true},{"aid":3,"iid":16,"ev":true},{"aid":33,"iid":11,"ev":true},{"aid":33,"iid":14,"ev":true},{"aid":7,"iid":11,"ev":true},{"aid":7,"iid":14,"ev":true},{"aid":35,"iid":11,"ev":true},{"aid":35,"iid":14,"ev":true},{"aid":36,"iid":11,"ev":true},{"aid":36,"iid":14,"ev":true},{"aid":12,"iid":11,"ev":true},{"aid":12,"iid":14,"ev":true},{"aid":11,"iid":11,"ev":true},{"aid":11,"iid":14,"ev":true},{"aid":6,"iid":11,"ev":true},{"aid":6,"iid":14,"ev":true},{"aid":8,"iid":11,"ev":true},{"aid":8,"iid":14,"ev":true},{"aid":4,"iid":10,"ev":true},{"aid":4,"iid":13,"ev":true},{"aid":26,"iid":11,"ev":true},{"aid":26,"iid":14,"ev":true},{"aid":28,"iid":11,"ev":true},{"aid":28,"iid":14,"ev":true},{"aid":25,"iid":11,"ev":true},{"aid":25,"iid":14,"ev":true},{"aid":32,"iid":11,"ev":true},{"aid":32,"iid":14,"e

Here is my config file.

{
    "bridge": {
        "name": "Homebridge",
        "username": "MAC",
        "port": 8128,
        "pin": "031-45-154"
    },

```
"accessories": [{
    "accessory": "LiftMaster",
    "name": "Garage Door Left",
    "username": "email",
    "password": "password",
    "deviceID": "device"
}, {
    "accessory": "LiftMaster",
    "name": "Garage Door Right",
    "username": "email",
    "password": "pass",
    "deviceID": "device"
}],

"platforms": [{
    "platform": "HomeAssistant",
    "name": "HomeAssistant",
    "host": "http://IP:8123",
    "password": "",
    "supported_types": ["light", "switch", "media_player", "scene"]
}]
```

}

**Comment by giase82** [comment]
I faced the same issue today, after enabling iOS 10 beta 8 yesterday for the first time. Before it was running without any issues for 3 weeks.

These are the last lines of the homebridge.err:

`Tue, 30 Aug 2016 07:08:13 GMT EventedHTTPServer [192.168.1.102] HTTP Response is finished
Tue, 30 Aug 2016 07:08:18 GMT EventedHTTPServer [192.168.1.137] Sending HTTP event '113.9' with data: {"characteristics":[{"aid":113,"iid":9,"value":21.6}]}
Tue, 30 Aug 2016 07:08:20 GMT EventedHTTPServer [192.168.1.102] HTTP request: /characteristics
Tue, 30 Aug 2016 07:08:20 GMT HAPServer [CC:22:FF:E3:CE:30] HAP Request: PUT /characteristics
undefined:1
{"characteristics":[{"aid":122,"iid":12,"ev":true},{"aid":122,"iid":15,"ev":true},{"aid":36,"iid":11,"ev":true},{"aid":36,"iid":14,"ev":true},{"aid":37,"iid":11,"ev":true},{"aid":37,"iid":14,"ev":true},{"aid":38,"iid":12,"ev":true},{"aid":38,"iid":15,"ev":true},{"aid":39,"iid":15,"ev":true},{"aid":39,"iid":18,"ev":true},{"aid":40,"iid":12,"ev":true},{"aid":40,"iid":15,"ev":true},{"aid":123,"iid":13,"ev":true},{"aid":123,"iid":16,"ev":true},{"aid":42,"iid":12,"ev":true},{"aid":42,"iid":15,"ev":true},{"aid":43,"iid":15,"ev":true},{"aid":43,"iid":18,"ev":true},{"aid":44,"iid":12,"ev":true},{"aid":44,"iid":15,"ev":true},{"aid":143,"iid":13,"ev":true},{"aid":143,"iid":16,"ev":true},{"aid":144,"iid":13,"ev":true},{"aid":144,"iid":16,"ev":true},{"aid":125,"iid":11,"ev":true},{"aid":125,"iid":14,"ev":true},{"aid":28,"iid":11,"ev":true},{"aid":28,"iid":14,"ev":true},{"aid":4
                                                                                                                                   

SyntaxError: Unexpected token `

**Comment by jsg4** [comment]
Still seeing this error now and then. Here's a more recent log. 

http://pastebin.com/bzt9hWn5

**Comment by KhaosT** [comment]
I believe v0.4.9 fixes the problem. Please open the issue again if you experiences similar problem again.
