### ISSUE TITLE
Bosch Home Connect

### ISSUE THREAD

**Issue by DJay79** [nfarina/homebridge#685]
Guys I hope I'm on the right place here. Otherwise sorry. I bought a Bosch coffee maker CTL636ES6 with Home Connect feature. Works great with the App on iOS. But of course I'm curious if someone is getting this to work with Homebridge as a plug in or zway. https://developer.home-connect.com
If there is something I can help as a user of course please let me know. 
Thx, DJay

**Comment by PatcherMustermann** [comment]
Hello DJay,
I think you do not need "Z-Wave" necessarily. If I have understood correctly, your iPone or iPad communicates via wifi with the "Home Connect" ?! Then you need a pure network solution. 
Maybe running that via http -> Plugin: "https://www.npmjs.com/package/homebridge-http"

Greeting
Patcher

**Comment by DJay1** [comment]
Hi Patcher,
thanks for your reply. I will check your given information and the link. 
And ja, ich bin aus Deutschland. :)
Viele Grüße.

**Comment by PatcherMustermann** [comment]
Hello DJay,
I had little time to concern with "Bosch Home Connect". Unfortunately it is not easy to implement this. But I think there are two paths to do this.

1 - As a company, you can easily by "Bosch Home Connect" register and get access to an APP-Api. 
=> Link: https://developer.home-connect.com/

2 - Install an Android on a "Raspberry pi" or on a Windows. Then you can remotely control the "Bosch Home Connect APP" over Homekit.
=> Link: https://play.google.com/store/apps/details?id=com.bshg.homeconnect.android.release&hl=de

Gruß aus RLP
Patcher

**Comment by DJay1** [comment]
Thx. Great. Will have a look on this. 
Enjoy your Weekend and Guude aus Hesse. ;)

**Comment by coliflower** [comment]
Hello,

were somebody already able to implement Home-Connect to HomeKit ?

Thanks in advance !

**Comment by justme-1968** [comment]
there is a very preliminary home connect module for the fhem home automation system. this should work with the homebridge-fhem plugin.

**Comment by coliflower** [comment]
Do you have some more details, please ?

**Comment by justme-1968** [comment]
unfortunately no. i currently have no home connect capable appliances.

the (german) thread is in the fhem forum: https://forum.fhem.de/index.php/topic,29353.msg482906.html#msg482906 but remember that it is really really preliminary.

homebridge-fhem is here: https://www.npmjs.com/package/homebridge-fhem and is working for quite a while.

ps: my personaly opinion: it is generally better to connect hoembridge to a 'real' homautomation system and have this system handle die devices and automation tasks and use homebridge 'only' as an interface to siri/homekit instead of using many different homebridge plugins for all your devices.using homekit as the central hub is much to limiting and the wrong approach.

**Comment by coliflower** [comment]
Thank you for the links.

Instead of homebridge-fhem I use homebridge-knx and of course, the homebridge itself is a kind of gateway/hub to my home-automation and to other gadgets what are not connected to knx to be able to use siri in case of need.

**Comment by justme-1968** [comment]
i would connect knx and all other devices to fhem and then use homebridge-fhem :)

this allows for much more powerful automation and integration of the different systems and also there are quite a few systems like hue or harmony that benefit form having one central system.

hoembridge, the harmony remote and some others are also integrated in fhem but only as io devices.

i think this is much cleaner and safer. but this is a completely different discussion :)

**Comment by coliflower** [comment]
> but this is a completely different discussion :)

Yes :-) 
I do it with edomi.de

**Comment by drtp** [comment]
Well, instead of using a Home Connect plugin for Homebridge, it is possible to control most Home Connect devices via [IFTTT](https://ifttt.com/search/query/Home%20Connect) using the Webhooks and the respective IFTTT plugin for Homebridge. [Here](https://forum.smartapfel.de/forum/thread/524-home-connect-kaffeevollautomat-ifttt/) you can find a respective configuration manual in German language. Give it a try.

**Comment by tklaver** [comment]
I'm using the IFTTT Webhooks. Works fantastic, and they're incredibly easy to set up!

**Comment by PrzemyslawKlys** [comment]
@tklaver do you need to define webhooks yourself or you're using actions available in HomeConnect Ifttt ? Or how does it actually work? I've read the IFTTT article about home connect in german and few examples of config they pasted but I am not sure how to prepare IFTTT for usage in homebridge-ifttt

**Comment by tklaver** [comment]
@PrzemyslawKlys I did now run into the problem where the Remote Start feature resets itself every day, so you will need to make sure the feature is enabled on the oven if you want to run a Webhook.

To configure a Webhook, you create a new applet:
- If *Webhook* (you configure the event name of your webhook here, for example `oven_200C`)
- Then *Home Connect Oven* (you configure what happens with the oven here, for example `Set oven to 200° C`).

Then in homebridge-ifttt you paste your Webhook event names and Webhooks key so homebridge-ifttt knows what to load. After restarting Homebridge your buttons should show up in HomeKit!

**Comment by PrzemyslawKlys** [comment]
Hrmms..

![image](https://user-images.githubusercontent.com/15063294/41468081-ff107306-70a8-11e8-9c3b-c21cd5ea368f.png)

But even thou it's setup, when i press Check Now it doesn't do anything. The app itself works just fine when use the dedicated ios app.

**Comment by tklaver** [comment]
I'm not sure if Check Now actually runs the webhooks. Is Remote Start enabled on your oven? Otherwise I would recommend adding your webhook to homebridge-ifttt and try it from there.

**Comment by PrzemyslawKlys** [comment]
Yes, remote start is enabled. But you may be right that it requires diff action.

**Comment by PrzemyslawKlys** [comment]
![image](https://user-images.githubusercontent.com/15063294/41469158-8e525c02-70ac-11e8-9bec-f6bbc6e47b7f.png)

Assuming above naming is ok... as in the coffe part is correct

![image](https://user-images.githubusercontent.com/15063294/41469174-9a660a20-70ac-11e8-91e4-b6df79537c89.png)


do you see anything unusual here ? Why would it crash?

**Comment by PrzemyslawKlys** [comment]
Does the naming of 'name' and caption matter ? does it in any way is relevant to wht is in ifttt? or only triggerOn/TriggerOff matters and has to be to the letter with the ifftt? I've coffy maker , owen and dishwasher with it so just trying it out with coffe not owen thou..

**Comment by tklaver** [comment]
You need to configure `Oven_Turn_On` somewhere, so it knows that the button is connected to that webhook. Maybe `name` is where you need to add that.

I'm not an expert here so if that doesn't work I'm afraid this is all I can do… Sorry.

**Comment by PrzemyslawKlys** [comment]
You helped a lot! Thanks. My problem was with the type of brackets I've used. I had to changfe first { into [ 

![image](https://user-images.githubusercontent.com/15063294/41470759-e5c2bd24-70b1-11e8-8b9f-c271b56c1c06.png)

**Comment by TangoTaker** [comment]
Hey, I want to do it via IFTTT as well but IFTTT foesnt offer me to preheat with more then 120C. Is there a way to set it manually?

**Comment by thoukydides** [comment]
[homebridge-homeconnect](https://github.com/thoukydides/homebridge-homeconnect) might be of interest to anyone still trying to integrate Home Connect appliances with HomeKit/Homebridge...

**Comment by Apollon77** [comment]
Someone could check with ham adapter.

**Comment by PrzemyslawKlys** [comment]
> [homebridge-homeconnect](https://github.com/thoukydides/homebridge-homeconnect) might be of interest to anyone still trying to integrate Home Connect appliances with HomeKit/Homebridge...

Works here! Thank you :-)
