### ISSUE TITLE
Homebridge  Turns Off When I Exit Terminal

### ISSUE THREAD

**Issue by Dracoy** [nfarina/homebridge#686]
Everything works great when I start home bridge.

I think hit CNTRL + Z to exit the process and then hit "bg" to send it to background (still works at this point) and exit out of terminal. 

Home bridge immediately stops and kills the process. Any ideas?

**Comment by apwelsh** [comment]
I use screen.  This enables a little more control over the job than the bg, fg tools.

**Comment by Dracoy** [comment]
That gave me an idea. I logged into VNC and opened up terminal and ran this script and left it on. Instead of logging in via my iPad or computer that I shut down this keeps it on always.

**Comment by mactr0n** [comment]
Please don't get me wrong but this isn't the place to learn linux basics. You should start by learning some basics. Here are some useful links:
https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi#running-homebridge-on-bootup-initd
https://github.com/fhd/init-script-template
