### ISSUE TITLE
Accessories not responding but Platforms are.

### ISSUE THREAD

**Issue by MXPelez** [nfarina/homebridge#687]
So, I've got homebridge installed on my Pi and I've got my platforms (LIFX) and accessories (Xbox & SonyTV) set up with the HomeKit app on iOS 10, but for some reason, neither of the accessories work. They both just say no response. Anybody have any idea what is going on here?

**Comment by robertvorthman** [comment]
I'm having the same problem.  Did you find a fix?

**Comment by MXPelez** [comment]
I did manage to resolve my issues, my other thread may be of some help to you #641

**Comment by robertvorthman** [comment]
Thanks.  I ended up having to clear my persist folder and pair Homebridge again.
