### ISSUE TITLE
Install homebridge issue

### ISSUE THREAD

**Issue by balajeek** [nfarina/homebridge#689]
I have Raspberry Pi 2 B with Noobs 

I followed the instruction (and as per instruction i choose the latest node-js v6.2.2) and followed rest of install, then finally when installing 

sudo npm install -g --unsafe-perm homebridge

I get error, here is the bottom portion of the debug.log showing errors: (log file also attached)
Can someone help.  thanks in advance.

11078 silly install printInstalled
11079 verbose stack Error: mdns@2.3.3 install: `node-gyp rebuild`
11079 verbose stack Exit status 1
11079 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:245:16)
11079 verbose stack     at emitTwo (events.js:106:13)
11079 verbose stack     at EventEmitter.emit (events.js:191:7)
11079 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
11079 verbose stack     at emitTwo (events.js:106:13)
11079 verbose stack     at ChildProcess.emit (events.js:191:7)
11079 verbose stack     at maybeClose (internal/child_process.js:852:16)
11079 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
11080 verbose pkgid mdns@2.3.3
11081 verbose cwd /home/pi/node-v6.2.2-linux-armv7l
11082 error Linux 4.1.15-v7+
11083 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "--unsafe-perm" "homebridge"
11084 error node v6.2.2
11085 error npm  v3.9.5
11086 error code ELIFECYCLE
11087 error mdns@2.3.3 install: `node-gyp rebuild`
11087 error Exit status 1
11088 error Failed at the mdns@2.3.3 install script 'node-gyp rebuild'.
11088 error Make sure you have the latest version of node.js and npm installed.
11088 error If you do, this is most likely a problem with the mdns package,
11088 error not with npm itself.
11088 error Tell the author that this fails on your system:
11088 error     node-gyp rebuild
11088 error You can get information on how to open an issue for this project with:
11088 error     npm bugs mdns
11088 error Or if that isn't available, you can get their info via:
11088 error     npm owner ls mdns
11088 error There is likely additional logging output above.
11089 verbose exit [ 1, true ]

[npm-debug.zip](https://github.com/nfarina/homebridge/files/341960/npm-debug.zip)

**Comment by troyanskiy** [comment]
I have the same on synology

**Comment by stevens-r** [comment]
did either of you find a solution i'm getting a similar error

**Comment by byrain** [comment]
I also met the same issue on Synology 216j. I had tried installed GCC and upgrade to 4.2.3-1 but still failed with homebridge.  I wonder is it possible to install homebridge on Synology  without Docker?
