### ISSUE TITLE
Plugin for z-wave device without z-wave server?

### ISSUE THREAD

**Issue by ardevd** [nfarina/homebridge#691]
I'm fairly new to both Homekit and Z-wave but I've decided to standardize everything with Homekit and so far Homebridge is perfectly integrating all my non-homekit devices. However, I am looking to buy a smart lock and the only native homekit supported lock I've found is August Smart Lock but it's not compatible with Scandinavian locks at all. 

So I found a lock called Danalock which supports Z-Wave, and I've realized that I could set up a z-wave server with a RaZberry and then use the homebridge-zway plugin to integrate the lock with Homebridge. However, my question is if it's possible to write a plugin for the lock directly, removing the need for a dedicated z-wave component?

Thank you!

**Comment by aivs** [comment]
To communicate with z-wave device you should use z-way-server. But danalock have bluetooth support, so you can try to control danalock with plugin homebridge-bluetooth (if it exists, I dont know)

**Comment by ooii** [comment]
Hi,

I don't have any Razberry but the Aeon USB Z-wave stick. Do you know if I can I run Z-way anyway?
Thanks.

**Comment by gijoecool** [comment]
I think you should look into openHAB. I use it with the Aeon Z-Stick and it works quite well.

**Comment by ooii** [comment]
I have everything running in domoticz, can I just use the domoticz plugin and I'm done?

**Comment by gijoecool** [comment]
This *might* work: https://github.com/patchworkboy/homebridge-eDomoticz

If you have issues then you might be better off asking for support under Issues there.

**Comment by ooii** [comment]
It works like a charm. Wonderful.
