### ISSUE TITLE
Homebridge Win 10 install error on git cmd

### ISSUE THREAD

**Issue by fabiobortolin** [nfarina/homebridge#694]
Hi, 
I have this installation erros on (npm install -g homebridge)
Running clean install of win10
Thanks..

C:\Users\fabio>npm install -g homebridge
C:\Users\fabio\AppData\Roaming\npm\homebridge -> C:\Users\fabio\AppData\Roaming\npm\node_modules\homebridge\bin\homebridge

> bignum@0.12.5 install C:\Users\fabio\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://rvagg-node.s3-us-west-2.amazonaws.com/bignum/v0.12.5/bignum-v0.12.5-node-v47-win32-ia32.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for bignum@0.12.5 and node@5.0.0 (node-v47 ABI) (falling back to source compile with node-gyp)

C:\Users\fabio\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node  clean )

C:\Users\fabio\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build --module=C:\Users\fabio\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum\binding\bignum.node --module_name=bignum --module_path=C:\Users\fabio\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum\binding )  else (node  configure --fallback-to-build --module=C:\Users\fabio\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum\binding\bignum.node --module_name=bignum --module_path=C:\Users\fabio\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum\binding )

C:\Users\fabio\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" build --fallback-to-build --module=C:\Users\fabio\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum\binding\bignum.node --module_name=bignum --module_path=C:\Users\fabio\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum\binding )  else (node  build --fallback-to-build --module=C:\Users\fabio\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum\binding\bignum.node --module_name=bignum --module_path=C:\Users\fabio\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum\binding )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  bignum.cc
..\bignum.cc(328): warning C4244: 'argument': conversion from 'uint64_t' to 'unsigned int', possible loss of data [C:\U
sers\fabio\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum\build\bignum.vcxproj]
..\bignum.cc(348): warning C4244: 'argument': conversion from 'int64_t' to 'unsigned int', possible loss of data [C:\Us
ers\fabio\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum\build\bignum.vcxproj]
..\bignum.cc(413): warning C4244: '=': conversion from 'double' to 'uint64_t', possible loss of data [C:\Users\fabio\Ap
pData\Roaming\npm\node_modules\homebridge\node_modules\bignum\build\bignum.vcxproj]
..\bignum.cc(514): warning C4244: 'argument': conversion from 'uint64_t' to 'unsigned int', possible loss of data [C:\U
sers\fabio\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum\build\bignum.vcxproj]
..\bignum.cc(532): warning C4244: 'argument': conversion from 'uint64_t' to 'unsigned int', possible loss of data [C:\U
sers\fabio\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum\build\bignum.vcxproj]
..\bignum.cc(550): warning C4244: 'argument': conversion from 'uint64_t' to 'unsigned int', possible loss of data [C:\U
sers\fabio\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum\build\bignum.vcxproj]
..\bignum.cc(569): warning C4244: 'argument': conversion from 'uint64_t' to 'unsigned int', possible loss of data [C:\U
sers\fabio\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum\build\bignum.vcxproj]
..\bignum.cc(652): warning C4244: 'argument': conversion from 'uint64_t' to 'unsigned int', possible loss of data [C:\U
sers\fabio\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum\build\bignum.vcxproj]
..\bignum.cc(787): warning C4244: 'argument': conversion from 'uint64_t' to 'unsigned int', possible loss of data [C:\U
sers\fabio\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum\build\bignum.vcxproj]
  win_delay_load_hook.c
C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.c(31): error C2373: '__pfn
DliNotifyHook2': redefinition; different type modifiers [C:\Users\fabio\AppData\Roaming\npm\node_modules\homebridge\nod
e_modules\bignum\build\bignum.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\delayimp.h(134): note: see declaration of '__pfnDliNot
  ifyHook2'
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\Program Files (x86)\nodejs\node.exe" "C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "build" "--fallback-to-build" "--module=C:\Users\fabio\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum\binding\bignum.node" "--module_name=bignum" "--module_path=C:\Users\fabio\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum\binding"
gyp ERR! cwd C:\Users\fabio\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum
gyp ERR! node -v v5.0.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd build --fallback-to-build --module=C:\Users\fabio\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum\binding\bignum.node --module_name=bignum --module_path=C:\Users\fabio\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum\binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\fabio\AppData\Roaming\npm\node_modules\homebridge\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:818:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 10.0.10586
node-pre-gyp ERR! command "C:\Program Files (x86)\nodejs\node.exe" "C:\Users\fabio\AppData\Roaming\npm\node_modules\homebridge\node_modules\node-pre-gyp\bin\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\fabio\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum
node-pre-gyp ERR! node -v v5.0.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.29
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd build --fallback-to-build --module=C:\Users\fabio\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum\binding\bignum.node --module_name=bignum --module_path=C:\Users\fabio\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum\binding' (1)
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files (x86)\nodejs\node.exe" "C:\Program Files (x86)\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "homebridge"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE

npm ERR! bignum@0.12.5 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bignum@0.12.5 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the bignum package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls bignum
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\fabio\npm-debug.log

**Comment by IComplainInComments** [comment]
Im receiving this error on Arch Linux as well.

It appears that the binary location for node-bignum has moved.

**Comment by NiackBuster** [comment]
Same error i'm dealing with Patcher on #690.
Is there a way to change this broken path ?

**Comment by IComplainInComments** [comment]
I haven't seen anything on an attempt to fix, but I have filed an issue on their github page (node-bignum).

**Comment by gleep52** [comment]
Dang it - I knew I should have done this last week... any ETA on a fix for this?  I'm getting this too.

**Comment by samj** [comment]
Try this:

`sudo npm --unsafe-perm install -g homebridge`

**Comment by gleep52** [comment]
sudo doesn't work in a windows environment.  And this still gives me the same ERR feedback about not being able to download the bignum@0.12.5 install.

**Comment by gleep52** [comment]
When I try to click this link: https://rvagg-node.s3-us-west-2.amazonaws.com/bignum/v0.12.5/bignum-v0.12.5-node-v47-win32-ia32.tar.gz
It tells me access is denied.

**Comment by thmstec** [comment]
I'm also experiencing the issue documented in this issue with a fresh install on Windows 8.1.

I was able to install on OSX.

**Comment by andrasg** [comment]
I am also impacted by this issue. I even tried first installing bignum globally then installing homebridge but it doesn't seem to notice the global package and tries to dowload it again...

**Comment by snipem** [comment]
Some for me on Archlinux. Seems to be bignum related.

**Comment by PatcherMustermann** [comment]
Hello @all:
I wrote an answer here: https://github.com/nfarina/homebridge/issues/694

**Comment by jgrosstephanjr** [comment]
Has anyone actually fixed this error yet?

**Comment by wstoffels** [comment]
Nobody? ;/

**Comment by gleep52** [comment]
I guess this is just a dead project now.  Someone mentioned that "Patcher" was the one to fix it, but he hasn't fixed, nor explained/given directions for a manual fix...

**Comment by MikeFotta** [comment]
Bignum 0.12.0 seemed to be the issue for me.  I used bignum 0.11.0 instead and everything seems to be working.  bignum 0.12.0 was introduced in a dependency of a dependency (homebridge->HAP-NodeJS->node-srp) on 15-Jun-2016 via: https://github.com/KhaosT/node-srp/commit/6fd61e5b734c5d957acdced91cd527cf0b3cdfa7

Below is how I worked around this to use bignum 0.11.0 instead (there may be other/better ways, this worked for me).

clone the following from GitHub:
git clone https://github.com/KhaosT/node-srp.git
git clone https://github.com/KhaosT/HAP-NodeJS.git
git clone https://github.com/nfarina/homebridge.git

edit the file node-srp/package.json to change the following line in dependencies:
 before:  
"bignum": "^0.12.0"
after:
"bignum": "0.11.0”

edit the file HAP-NodeJS/package.json to change the following line in dependencies:
before:
"srp": "git://github.com/KhaosT/node-srp"
after:
"srp": “file:../node-srp”

edit the file homebridge/package.json to change the following line in dependencies:
before:
"hap-nodejs": "0.3.2",
after:
"hap-nodejs": "file:../HAP-NodeJS",

then install:
cd homebridge
sudo npm install -g

p.s. later if you run into "Error: dns service error: unknown"... when starting homebridge, try this:
sudo apt-get install -y avahi-daemon avahi-discover libnss-mdns
sed -i "s/rlimit-nproc=3/#rlimit-nproc=3/" /etc/avahi/avahi-daemon.conf
dbus-daemon --system
avahi-daemon -D
homebridge

**Comment by jgrosstephanjr** [comment]
When I do the method above I get the error: 
npm ERR! bignum@0.11.0 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bignum@0.11.0 install script 'node-gyp configure build'.
npm ERR! This is most likely a problem with the bignum package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls bignum
Do you know what is failing, or what I might have done wrong?

**Comment by MikeFotta** [comment]
@jgrosstephanjr what happens if you try to install just bignum?  
sudo npm install -g bignum@0.11.0

**Comment by jgrosstephanjr** [comment]
@MikeFotta I get the same exact error.
