### ISSUE TITLE
iOS 10 does NOT support homebridge

### ISSUE THREAD

**Issue by IComplainInComments** [nfarina/homebridge#699]
iOS 10 beta does NOT currently support homebridge. The system is currently running fine, and is showing no errors in its console.

On my iOS device, it is unable to add the device stating 

> Couldn't Add Accessory
>Home couldn't connect to this accessory.

**Comment by irrg** [comment]
Good username. Dupe? https://github.com/nfarina/homebridge/issues/662

**Comment by IComplainInComments** [comment]
Yup its a dupe, issue #662 address this issue.

Please close the ticket.

**Comment by irrg** [comment]
It's your ticket, I think you can close it. I am just an observer here!

**Comment by IComplainInComments** [comment]
Nope don't think I can close,

Any source Mods, please close this ticket.

**Comment by AppleTechy** [comment]
iOS 10 does support homebridge I have it running perfectly fine after a little bit of tweaking. Though I will look more into issue #662
