### ISSUE TITLE
How to update and quit/reopen Homebridge after initial install?

### ISSUE THREAD

**Issue by K-MTG** [nfarina/homebridge#701]
Hi,

I am new to this and plan on installing Homebridge to interact with my smartthings system. Quick question:
How to update the Homebridge app if any updates are made availibke for the code?

Also, how do I quit/reopen Homebridge after initial install?

Sorry for these basic questions. Thanks!

**Comment by K-MTG** [comment]
Update: I am a Mac user so I will be using Terminal

**Comment by K-MTG** [comment]
Also, how do you update plugins?

**Comment by KhaosT** [comment]
If you install homebridge and/or plugins using npm, you can use npm to update them. https://docs.npmjs.com/cli/update

**Comment by K-MTG** [comment]
So whenever a plugin or Homebridge update is available I can just type: sudo npm update -g homebridge

Will this require me to redo the setup?

Thanks!

Also, how do I close and relaunch Homebridge and the plugin??

**Comment by KhaosT** [comment]
@K-MTG if there is a homebridge update then that's the right command, for plugins, you need to type their name. Updating homebridge will not require you to setup again since the configuration file is at a different location.

Depends on how you start homebridge the answer will be different.

**Comment by K-MTG** [comment]
Appreciate the help!

What is the "normal" method to start homebridge? I plan on using only the smartthings plugin for now. 

Thanks

**Comment by KhaosT** [comment]
@K-MTG It varies based on the system... Like on macOS people might register homebridge as a daemon and will have launched to start homebridge when macOS boot up. On Debian people might use systemd or init.d.

**Comment by K-MTG** [comment]
For now, I just need to launch it normally, not on startup or anything like that (unless it is simple to do so).

Thanks

**Comment by KhaosT** [comment]
then just run ``homebridge`` in terminal to run it, and press control-c to quit it.

**Comment by K-MTG** [comment]
does typing homebrdige also run the plugin? Thanks!

**Comment by apwelsh** [comment]
Running homebridge launches homebridge. Upon startup, homebridge loads all plugins, in the same way that Photoshop loads all the plugins when Photoshop is loaded. That is how all plugins work.  The app loads the plugin when needed.

**Comment by patrickroux** [comment]
Well, homebridge doesn't reload all plugins at startup. I had to manually "sudo nano" each index.js of my plugins in /usr/local/lib/node_modules/ to debug a simple line of code...

Is there anyway to reload all plugins ?
