### ISSUE TITLE
Siri (Italian) - homebridge - iOs10

### ISSUE THREAD

**Issue by sdomotica** [nfarina/homebridge#702]
I installed public beta of iOs 10.
All work fine.
The problem is only Siri.
When ask in Italian "Siri tun on light Kitchen" "Siri accendi luce cucina", Siri don't is able to recognize message.
With iOs 9 worled fine.
There are  ohters with this problem?
Siri in English works fine?
Bye
Sandro

**Comment by simonegenovese** [comment]
Same problem.

**Comment by chioma91** [comment]
same here (ita)

**Comment by steppige** [comment]
Hello guys! To you it works iOS 10 - Homebridge? When there were beta Homebridge working, as soon as I installed the final or even RC funzioan no nothing .. :(

Ciao ragazzi! A voi funziona iOS 10 - Homebridge? Quando c'erano le beta homebridge funzionava, appena ho installato la definitiva o anche RC non funzioan più nulla.. :(

**Comment by joshhighet** [comment]
Personally running on iOS 10 Without any issues

**Comment by steppige** [comment]
Hello!! thanks for the reply! To you work with the beta version of iOS 10? Or with the final one? I have installed eDomoticz ...

**Comment by gijoecool** [comment]
I am also running iOS 10.0.1 (14A403) without any homebridge issues.

**Comment by joshhighet** [comment]
@steppige i'm running the final GM.

I have only ran the GM, So i can't give you any personal experience with other beta versions
