### ISSUE TITLE
Update characteristics

### ISSUE THREAD

**Issue by KimchaC** [nfarina/homebridge#703]
Hi,

I am writing a thermostat service and since the temperature changes over time, I would like to have the ability to tell all homekit clients to update the value after it has changed.

Is that somehow possible?

**Comment by andig** [comment]
Untested, but I've seen things like

    self.service.getCharacteristic(Characteristic.CurrentTemperature).setValue(temp);

...may be totally wrong though.

**Comment by plasticrake** [comment]
In addition you can also use `.updateValue(value)` on a characteristic. This won't trigger any other 'set' events for that characteristic. Depending on how you have your events setup you may run into unwanted loops and `updateValue` will avoid that.

They are defined here: https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/Characteristic.js
