### ISSUE TITLE
Craftsman Assurelink

### ISSUE THREAD

**Issue by Nate8727** [nfarina/homebridge#704]
I've added the homebridge successfully, but assurelink isn't showing up as an accessory.  On the home app it shows my Lutron lights with its bridge and then the homebridge as a bridge.

I changed the config.json to match the assurelink plugin with my login info.  It says it's added the accessory when starting homebridge but nothing after that.   I haven't tried adding any other non HomeKit accessories yet.

UPDATE: None of the accessories are being added when homebridge starts up.  here's the list:

> Last login: Sun Jul 17 21:24:21 on ttys000
OFFICEs-iMac:~ OFFICE$ homebridge
[7/17/2016, 9:39:46 PM] Loaded plugin: homebridge-philipshue
[7/17/2016, 9:39:46 PM] Registering platform 'homebridge-philipshue.PhilipsHue'
[7/17/2016, 9:39:46 PM] ---
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[7/17/2016, 9:39:46 PM] Homebridge is running on port 

> 51826.

Any ideas?

**Comment by Nate8727** [comment]
Well I figured out the problem.

I didn't realize the config.json file had to be in a different folder from where it's first created.  Everything is working now.

You might want to put that in the sample config.json file when a new user comes to the site.

**Comment by MorningZ** [comment]
Just one quirk I ran across with the Assurelink/Siri combo that i'll share with you.

Siri doesn't seem to like "Open Garage Door" as it will try to open the Assurelink app.  I named the door "The Garage" and now I can say "Open/Close the garage" and it works perfect
