### ISSUE TITLE
Homebridge for Windows wiki 

### ISSUE THREAD

**Issue by jmarq89** [nfarina/homebridge#706]
Hello, I am new to this and have followed the instructions pretty clearly but I am stuck on step 8 to 8.3 where it says I need the software but instead it says to just copy text onto a file I can't open. The steps says to open a file named unistd.h. Where am I opening this file? On which program?  I apologize in advance for my ignorance and thank you for any sort of help on this.

**Comment by PatcherMustermann** [comment]
@jmarq89: It's very easy. 

1 - Open Notepad
2 - Copy the "text" from the wiki to the Notepad
3 - Save the file with name unistd.h [()](http://lifehacker.com/5883860/change-the-file-extension-of-any-file-through-windows-save-as-menu)
4 - Finished :)
