### ISSUE TITLE
iOS 10 Http getting requests not working

### ISSUE THREAD

**Issue by JacoGasp** [nfarina/homebridge#708]
I wrote an http plugin based on [homebridge-better-http-rgb plugin](https://github.com/jnovack/homebridge-better-http-rgb) and [homebridge-readablehttp](https://github.com/mattharris5/homebridge-readablehttp) in way to get hue, saturation and brightness from my arduino project.

Setting those values it works properly, and it _should_ work also getting them.

The problem is that: if I use thirty apps to control my light, all works fine even if no getting function are called by homebridge.
If I open Home app, it gets stuck getting the lamp status and no requests are received by my device.

Can't figure out if it's my plugin's fault or it is homebridge + iOS 10

Edit: looking at homebridge log sometimes one or two of the getting functions work, but almost always it shows (after a while) "socket hang up" and arduino hasn't received nothing

**Comment by GaoMax** [comment]
I've got the very same problem. I even wrote my one http plugin for my NodeMCU project but i always get that status error.

**Comment by chioma91** [comment]
I'm working with arduino + ESP8266 and then I'm going to port my project to the NodeMCU.
I hope it's not a problem related with the ESP or its library.

Can you post your http response you wrote for the NodeMCU? Is it possible that homebridge is waiting for somewhat?

**Comment by GaoMax** [comment]
So i debugged my code. It seems like the request from the Home app is requested immediately after i open the control center, but sometimes the response comes 7 seconds to late. Im trying to find a solution.

**Comment by chioma91** [comment]
I noticed that if I set the plugin (or the configuration) to ask for one value per time (eg only the power status or the brightness) it works properly. It makes a mess requesting multiple values per time.
