### ISSUE TITLE
Need Help Setting up Home Bridge/Nest

### ISSUE THREAD

**Issue by delviacv2** [nfarina/homebridge#709]
Hello, I been Trying to set up homebridge on my iMac but so far no success :( this is the error that im getting any help will be Appreciated 

Delvi..

Last login: Tue Jul 19 18:34:50 on ttys000
iMac:~ delviacv2$ homebridge
[7/19/2016, 6:38:22 PM] Loaded plugin: homebridge-nest
[7/19/2016, 6:38:22 PM] Registering platform 'homebridge-nest.Nest'
[7/19/2016, 6:38:22 PM] ---
/usr/local/lib/node_modules/homebridge/lib/server.js:181
  var username = config.bridge.username;
                              ^

TypeError: Cannot read property 'username' of undefined
    at Server._loadConfig (/usr/local/lib/node_modules/homebridge/lib/server.js:181:31)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:44:23)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
iMac:~ delviacv2$ 

and this is my comfig.json

[{
	"platform": "Nest",

	"token": "c.5ABsTpo88k5yfNIxZlh...",

	"clientId": "5705ea59-8def-4156-a21b-9ae84d3a543f",
	"clientSecret": "F5ve7Lk2eMAlQmjS1JR8e5V2Z.",
	"code": "HXXPJPUE",

	"username": "xxxxxxx@yahoo.com",
	"password": "xxxxxxx"
}]

**Comment by tannebil** [comment]
Is that your entire config.json? If so, it's missing the "bridge" section and a "platforms" section header before "platform": "Nest".

If it's actually complete, a common problem is that it's in the wrong place. It needs to be a hidden directory named .homebridge in the user home directory

**Comment by delviacv2** [comment]
that is all I have for my comfig.json, where can I find the proper API?

when I try to set it up like this link , https://github.com/KraigM/homebridge-nest 
it give me an error in line 1 checking with this link http://jsonlint.com/

**Comment by tannebil** [comment]
Here’s what it should like:

{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": “xxx-xx-xxx"
	},
	"platforms": [
		{
			"platform": "Nest",
.
.
.
}
	]
}

Everything else looks OK although the values are specific to your install

**Comment by delviacv2** [comment]
Thankyou, this pin # is it the one from the nest website? I put it on "code"

**Comment by tannebil** [comment]
Read the setup information in github/homebridge

**Comment by delviacv2** [comment]
Ok Will check it out, thanks a lot for the help, Im getting closer and closer :)

**Comment by johnypony3** [comment]
# DANGER DANGER
**You publicly posted all of the information that is necessary for anyone in the world to control your nest device.**
I **highly** suggest you updated that post and change your nest password and create new keys.

**Comment by toshibochan** [comment]
@delviacv2 you show your Nest email and password for everyone! Better you change your password!

**Comment by delviacv2** [comment]
Coaching accepted, changed everything on my nest account.

Thankyou.

**Comment by AppleTechy** [comment]
@delviacv2 You get this all sorted out?

**Comment by jwl17330536** [comment]
This morning I went through the docs (https://www.npmjs.com/package/homebridge-nest) and installed / configured my Nest to work with Homebridge and can say that the steps are still accurate.

**Comment by delviacv2** [comment]
I got it to work but I probably Made a mistake somewhere because it gives me a big error in red letters and then it says something like defaulting back to legacy API but it works, Thanks to all for your help.

I'm Not a developer so Im not even going to try to get my wemo switches working : (

Delvi.
