### ISSUE TITLE
Accessories not loading from the config.json file

### ISSUE THREAD

**Issue by andykartman** [nfarina/homebridge#717]
Hi all

My system does not seem to recognise the Accessories that are listed in the config.json file. The plugins register OK. I have two accessories in the config file and one platform. The milights all work and controll fine. I even tried a fake accessory but no luck.

Help appreciated (running on Rpi with Jessy)

" Loaded config.json with 0 accessories and 1 platforms."

![image](https://cloud.githubusercontent.com/assets/14199863/17136093/baf92902-5376-11e6-8bdf-e18d13a4b1aa.png)

![image](https://cloud.githubusercontent.com/assets/14199863/17136219/7f93a918-5377-11e6-8b4f-a1c7ae3a70c5.png)

**Comment by nzhome** [comment]
I have the same problem today.  I have homebridge running on my Windows10 PC and also running on Debian, and on RaspberryPI, but today I went to install a fresh copy on debian, and it doesn't work :(  I changed the PIN number and the username, but it had zero effect.  How can we see what config.json file is actually being loaded and any errors during load?

**Comment by emeshuris** [comment]
Just wondering, why not post the json instead of an image?
It looks like you have an extra `}]` on the second line from the bottom.

![iscreenshot](http://i.imgur.com/DyOC7pG.jpg)

**Comment by nzhome** [comment]
We really need to move away from these silly json configs. can someone write a UI5 frontend for them :)

**Comment by nzhome** [comment]
Others have had this issue lately too.  there is too little error handling.  we need more error handling.  in my case it was this, once I displayed the real error that was being supressed by homebridge/lib/server.js


ERROR: Couldn't find a config.json file at '/root/.homebridge/config.json'. Look at config-sample.json for examples of how to format your config.js and add your home accessories.

**Comment by emeshuris** [comment]
> ERROR: Couldn't find a config.json file at '/root/.homebridge/config.json'. Look at config-sample.json for examples of how to format your config.js and add your home accessories.

Looks adequate to me, glad it worked out for you.

Probably time to close the issue.

**Comment by nzhome** [comment]
its actually a bug in homebridge.  I traced it back to this, NPM installed homebridge elsewhere, and then homebridge struggled to locate it properly. the problem homebridge code is this:

if (customStoragePath) return customStoragePath;
  var home = process.env.HOME || process.env.HOMEPATH || process.env.USERPROFILE;
