### ISSUE TITLE
Not working on IOS 9.3.3

### ISSUE THREAD

**Issue by tclearkin** [nfarina/homebridge#719]
Hi, 

Upgraded to IOS9.3.3 for the security fixes. My Homebridge that was working really well simply will not work now. I reinstalled everything on the Homebridge side to make sure I have latest versions etc and reset Homekit but Homebridge simply does not appear in the add accessory list for Homekit. Homebridge loads just fine on the Mac so looks like an IOS 9.3.3. thing? Anyone else had this problem? Any ideas?

Thanks

**Comment by jer78** [comment]
I can't verify 9.3.3 but it does work on 10 beta 2. Try deleting the accessories and cache folders. I find whenever I need to reset, simply deleting from iOS doesn't do the trick.

**Comment by gijoecool** [comment]
It works okay for me on 9.3.3.

**Comment by tclearkin** [comment]
Thanks - looks like all I had to do was wait. It showed up in Homekit several hours later when I went back to work on it. Homekit mysteries me.
