### ISSUE TITLE
minimum required characteristics for thermostat service

### ISSUE THREAD

**Issue by justme-1968** [nfarina/homebridge#72]
does anyone know what the minimum required characteristics for the thermostat service are?

with just TARGET_TEMPERATURE_CTYPE i can't add the device to eve or insteon+. insteon+ gives an error about not meeting homekit standards.

thanks
  andre

ps: this is for a platform shim for the FHEM home automation system. switches, lights, dimmers, color lights and temperature/humidity sensors are already working bidirectional including pushing updates from fhem to homekit and querying current device state if not cached.

pps: does the SPEAKER_STYPE service really work? my devices just appear as switches in eve. and OUTPUTVOLUME_CTYPE is not visible at all.

**Comment by nfarina** [comment]
All is revealed in the auto-generated [HomeKitTypes.js](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js#L1763). See `Service.Thermostat`.

**Comment by nfarina** [comment]
Note that many of those services are iOS 9 only. But the iOS 8 ones should be mostly the same. Closing this for now, let me know if you need more info.
