### ISSUE TITLE
Web Weather Forecast to Homebridge Temperature

### ISSUE THREAD

**Issue by JangoBritt** [nfarina/homebridge#721]
Hi all,

I'm looking for a plugin that will connect to something like Yahoo Weather, and be able to present the temperature and humidity back to Homebridge, as an outdoor temperature sensor. I guess this would work a bit like the Eve Weather sensor, and could be used for triggers, without spending £40 on a piece of plastic that tells me what I can already get off the internet.

I've seen some HTTP plugins, but they're only expecting a particular JSON input.

**Comment by andig** [comment]
I have seen a wunderground plugin, would that work for you? Just check npm for homebridge-plugin.

**Comment by ShermanThruGA** [comment]
I use the WUnderground plugin for just that and it works great! Highly recommended.

**Comment by JangoBritt** [comment]
Perfect, Thanks!
