### ISSUE TITLE
Homebridge MyQ  unconfigured parameters

### ISSUE THREAD

**Issue by azulon1** [nfarina/homebridge#722]
I did everything step by step, and copy pasted the config.json from this site.  then when I try to add the device on the iOS app devices, it says unconfigured parameter. I spent 22 hours reading and trying please help. thank you.  I am willing to pay for someone helping get this work.

    "platforms": [
       {
         "platform": "MyQ",
         "name": "MyQ",
         "MyQApplicationId": "NWknvuBd7LoFHfXmKNMBcgajXtZEgKUh4V7WNzMidrpUUluDpVYVZx+xT4PCM5Kx",
         "UserAgent": "Chamberlain/2793 (iPhone; iOS 9.3; Scale/2.00)",
         "BrandId": "2",
         "culture": "en",
         "username": “********@yahoo.com”,
         "password": “******”,
         "loglevel":"0"
       }
    ],

**Comment by azulon1** [comment]
My iPhone is on iOS 10 public beta, but I just copy pasted the config.son file anyways

**Comment by emeshuris** [comment]
Can you post your entire config file?
If that is your config file, it is incomplete and invalid.

You can see a sample for this platform here: [MyQ config-sample.json](https://github.com/chanomie/homebridge-myq/blob/master/config-sample.json)

**PROTIP**: to aleviate timesucks, validate your json: [json validator](https://jsonformatter.curiousconcept.com)

I am not sure why the author decided to add an extra platform, you can use this, based on what you provided:
```json
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:AA",
        "port": 51826,
        "pin": "031-45-154"
    },
    "description": "I will not get frustrated. I will not get frustrated. I will not get frustrated.",
    "platforms": [
        {
            "platform": "MyQ",
            "name": "MyQ",
            "MyQApplicationId": "NWknvuBd7LoFHfXmKNMBcgajXtZEgKUh4V7WNzMidrpUUluDpVYVZx+xT4PCM5Kx",
            "UserAgent": "Chamberlain/2793 (iPhone; iOS 9.3; Scale/2.00)",
            "BrandId": "2",
            "culture": "en",
            "username": "********@yahoo.com",
            "password": "******",
            "loglevel": "0"
        }
    ],
    "accessories": []
}
```

**Comment by azulon1** [comment]
[config.json.txt](https://github.com/nfarina/homebridge/files/391966/config.json.txt)


thats my config file man. Thanks so much buddy.  I will try your config now.

**Comment by azulon1** [comment]
i used your configuration file with just the username and password modified and then when I try to add device.   I get this issue (look picture).  Do I have to change any of the user agent/ ip. if so how do i change it.   i have a member in my family with disability who needs to be able to open door without taking out phone.  I am new to all this coding stuff.  but I think I am close to getting it to work.

![img_0764](https://cloud.githubusercontent.com/assets/6404147/17271570/230eb504-5645-11e6-99c6-80a0a5eda2aa.jpg)

**Comment by azulon1** [comment]
Oh also I am on the latest iOS 10 beta, if thats the problem. I could use a iOS 9.3 device, in fact let me try that.

**Comment by emeshuris** [comment]
I'm also using the beta on the iphone, this issue is most likely not related to the OS.
After upgrading to the new beta I had an issue where my screen was black, this may not be the same issue that you're having, but its worth a try. In IOS 10 you can uninstall the stock apps, and reinstall from the app store, although you'll have to recreate your home, its worth a shot.

If that is not it, it is probably plugin specific, as I'm not using it, I'll be of little help. 
You may want to post on the github repo for that plugin: [homebridge-myq](https://github.com/chanomie/homebridge-myq)

Homebridge logs to two places:

1. /var/log/homebridge.log
2. /var/log/homebridge.err

I suggest you look in them to see if anything jumps out at you, this will also help the people on that repo help you easier.

**PROTIP**: unix has the `tail` command, it makes it really nice to see logs in real time.

Assuming you have homebridge running, from that server run one of the following commands to see what is getting logged live.

```
tail -f /var/log/homebridge.log
tail -f /var/log/homebridge.err
```

**Comment by emeshuris** [comment]
I looked at that repo, it looks like it is retired. I suggest you try the plugin referenced.
Unfortunately, even this repo looks pretty stale, however its maintained by @nfarina who also maintains the repo we're on.

Good luck!

> Project Retired

> Already an existing project that does this called "Liftmaster": https://github.com/nfarina/homebridge-liftmaster

**Comment by nzhome** [comment]
your original problem was because you used the wrong kind of quote marks, I spotted it straight away.. those are inverted quote marks, you need to use straight up and down quote marks.  yes homebridge needs better config.json error handling, but its all we've got.

   "username": “********@yahoo.com”,
     "password": “******”,

**Comment by azulon1** [comment]
hey guys, let me try it when I get home. I will let you guys know how it goes

**Comment by treeiler** [comment]
I had issues getting the MyQ plugin to work, however the Liftmaster plugin works perfectly with the Chamberlain MyQ. Liftmaster and Chamberlain are the same company and make the same product, branded differently. Works perfect for me on iOS 10 beta, Watch OS 3 Beta, MacOS Sierra.

**Comment by azulon1** [comment]
Hey treeiler, to use the lift master, do I need to be using the lift master app on my phone? or make a new login on lift master?   also can you please give me your JSON?  thanks mate.

**Comment by azulon1** [comment]
I am having trouble understanding the fundamentals of whats happening. I mean I really don't want to learn it actually.  The guy at wal-mart told me this was home kit compatible. EVEN on their demo poster that walmart had it said home kit. I own ecobee3. and let me tell you THAT WAS SO EASY to setup, like i expect from apple, i am not too good at tech stuff.   

Anyways, I must get this working, because walmart denied me a return policy.  And my family member cannot be pulling out their phone to open garage, they need siri.


So to the point look at this JSON,  I modified Nothing
[config.json.txt](https://github.com/nfarina/homebridge/files/394958/config.json.txt)

**Comment by azulon1** [comment]
and I presume I add the device to a lift master account?


Thanks.

**Comment by tannebil** [comment]
The guy at Walmart was wrong. It's not HomeKit compatible. HomeBridge is a brilliant, amazing hack but it's not an Apple product.

Your family members better have another way to get in the house because hacks have a way of not working suddenly and without warning.

**Comment by azulon1** [comment]
yea man, I really fear that, but I don't know any other way. she is in a wheelchair, the only other way is that I get a smart lock on t he front door, but that has stairs you know.  So the way we have been doing it is I come having to help her in all the time, or uses siri to call me or another person.   Also I am not too lofty on money, if walmart won't take this back, then I am going to have to make this one work.   

I didn't mean to inconvenience, but I have no other option.

**Comment by tannebil** [comment]
Just wanted to make sure that you understood that even after you get it working, it's likely to be a less than 100% reliable solution so she definitely needs alternative ways to open the garage door.

**Comment by azulon1** [comment]
Well can you help me with lift master please

**Comment by tannebil** [comment]
I don't have one so have no personal experience. Assuming you installed the appropriate modules, there's a couple of things that look wrong in your config.json. First, you don't need the platform section since you are installing the LiftMaster accessory. Next, the username and password values in the accessory section need to be in double quotes. Your config.json shows some kind of special character as the current delimiter. 

You sudo installed Homebridge-liftmaster?

**Comment by azulon1** [comment]
yes sir I have

**Comment by tannebil** [comment]
Fix the config.sys issues and post the revised it along with the messages you get when you start Homebridge

**Comment by azulon1** [comment]
hey yo I will I am trying to google all these things.  I have a question. Is it alright that maybe we just add each other and chat through this.  Like I said I would definitely pay etc.

**Comment by tannebil** [comment]
Join homebridgeteam on Slack and go to the LiftMaster channel

**Comment by azulon1** [comment]
i am on the slack, I am new to slack. so i wrote stuff on there, let me know if your getting it.

**Comment by AppleTechy** [comment]
You all are using the home ridge-lift master plugin right? Not the MyQ
plugin...(Duplicate project and outdated)

**Comment by azulon1** [comment]
yea, I was advised to use the lift master.  so the myq is newer?  Would you help us with creating a config.son. I don't know if I have to look up IPS or anything , I am new to that. if you could tell me what the config fi
