### ISSUE TITLE
Problem just started and not sure what's going on.

### ISSUE THREAD

**Issue by flynhawaiian** [nfarina/homebridge#725]
For some reason I just started getting this error message.  Nothing has changed.  Trying to understand what is going on.

[7/29/2016, 12:02:05 PM] [SmartThings] Initializing homebridge-smartthings.SmartThings platform...
[7/29/2016, 12:02:05 PM] [SmartThings] Fetching Smart Things devices.
[7/29/2016, 12:02:06 PM] [SmartThings] Error received type undefined - undefined
[7/29/2016, 12:02:06 PM] [SmartThings] Unknown Capabilities: []
Scan this code with your HomeKit App on your iOS device to pair

**Comment by emeshuris** [comment]
Can you post your config?

**Comment by Nnk2** [comment]
May not be related, but same for me: no change (that I know of anyway), but my homebridge setup stopped working completely ~yesterday ...

The log shows a DNS name conflict, but I cannot see what is cousing it...

[2016-07-30 11:14:01] Homebridge is running on port (**withheld**).
/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/mdns/lib/advertisement.js:56
  dns_sd.DNSServiceRegister(self.serviceRef, flags, ifaceIdx, name,
         ^

Error: dns service error: name conflict
    at Error (native)
    at new Advertisement (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/mdns/lib/advertisement.js:56:10)
    at Object.create [as createAdvertisement] (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/mdns/lib/advertisement.js:64:10)
    at Advertiser.startAdvertising (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Advertiser.js:43:30)
    at Bridge.Accessory._onListening (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:510:20)
    at emitNone (events.js:67:13)
    at HAPServer.emit (events.js:166:7)
    at HAPServer._onListening (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:182:8)
    at emitNone (events.js:67:13)
    at EventedHTTPServer.emit (events.js:166:7)
    at EventedHTTPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:62:10)
    at emitNone (events.js:67:13)
    at Server.emit (events.js:166:7)
    at emitListeningNT (net.js:1257:10)
    at doNTCallback1 (node.js:418:9)
    at process._tickCallback (node.js:340:17)

**Comment by coolcom** [comment]
I am getting same error after working for quite some time

**Comment by Nnk2** [comment]
Could not find the root cause, but have resolved my issue by a reformat/clean install of my complete rpi. Basic homebridge functionality is working again now. (it will cost me weeks to get all of my scenes/commands/logic back in though :-(

**Comment by Wildcat1** [comment]
All, seeing the same issue, again everything was working fine up until the past few days then the 'type undefined' errors and now even the simple Smarthings accessories (motion, temp etc) are not passing through as they used to. Not sure what has caused this that we are all starting to see the error. @Nnk2 questions for you 1) when you mentioned a reformat/clean what exactly did you do ? 2) did this bring back all of your accessories as per before (albeit without the logic etc for scenes) ?

Thanks and hope we can get a fix on this soon

**Comment by Nnk2** [comment]
@Wildcat1:
1) I reformatted the rpi sd card, installed a new raspbian image, ran the update/upgrade routines and reinstalled homebridge & plugins.

2) no, unfortunately not. HomeKit/Apple sees these as new assessories I'm afraid ...

Good luck!

**Comment by Wildcat1** [comment]
@Nnk2 thanks for the update. I'm running this on a Mac so will take a look at blowing away things like the persistent caches for the accessories and seeing what that does to the config

**Comment by coolcom** [comment]
I'm also running it on a Mac. How would I clear persistent caches?

**Comment by Wildcat1** [comment]
@coolcom Sorry for not posting more detail, I was referring to the persistent caches for accessories in the JSCON complete directories on the Mac. Let it rebuild those and see what happens. Going to try that today

**Comment by coolcom** [comment]
is there a command to run or directory to remove to accomplish that?

**Comment by Wildcat1** [comment]
@coolcom I just resolved this for my instance of this on my Mac. First I went into the ~/.homebridge directory and in both accessories & persist subfolders, deleted CachedAccessories, AccessoryInfo & IdentifierCache. After this I went back into the SmartThings on iOS and removed all devices from the JSON Complete Api smart app. After this I re-added these which then generated the new access token and proceeded to update my JSON config file with this new token. I then reinstalled the plugins for the Mac and also removed Homebridge accessory from my iOS Homekit app of choice (Home by Matthias). After this ran Homebridge on the Mac, everything came up as expected without any issues or errors, re-added Homebridge as an accessory on iOS and all devices came back. Now onto the work of re-assigning to rooms and in configuration of scenes etc.

Let me know if that helps you as well

**Comment by coolcom** [comment]
@Wildcat1 thank you VERY much, I appreciate the detailed help! I have done everything but re-add to my 'Home' since I'm not local right now. I will let you know later of the status.

**Comment by coolcom** [comment]
Alright- so homebridge started with no errors, it loaded all my devices. I am unable to see it in my 'Home' app to re-add, but I will try rebooting my phone and some other stuff.

**Comment by Wildcat1** [comment]
@coolcom Definitely make sure you removed Homebridge as an accessory from the Home app first then try re-adding that way, using the manual entry method (entering the Homekit code) and should be good. Just finished resetting my scenes, commands, triggers and room assignments and working fine right now. Let me know

**Comment by coolcom** [comment]
It was not even there for me to remove.

**Comment by Wildcat1** [comment]
@coolcom Ok. Worst case you could always reset Homekit configuration but see if after your reboot you are able to add it back in. As I said for me I went into the manual entry again entered the code and paired back straight away. I have seen it be a bit 'sticky' in the past though

**Comment by coolcom** [comment]
Yes I have issues with this before- many, many times. I think I'll
eventually get it working.

**Comment by coolcom** [comment]
All is well now. I was able to re-add it back and it's been stable for the past few days.
