### ISSUE TITLE
Backup/Restore to new device (success)

### ISSUE THREAD

**Issue by leonmf** [nfarina/homebridge#726]
This is not a bug, but it's worth noting in the documentation that it is possible to move your configuration to a new device without having to rebuild your HomeKit setup.

I  had an old RPi 1 running HomeBridge and I was having significant performance problems. This may actually have been due to a service on the Z-Way server which I solved last night as well. Regardless, in the process of debugging the significant lags and control failures I was having, I decided to go ahead and upgrade to a RPi 3.
- I backed up the persist directory, the config.json and my init.d script.
- Installed Homebridge and my plugins
- restored the backed up files
- Set the init.d script to run

As far as HomeKit was concerned, I was running the same gateway!

I hope this helps someone else.

**Comment by emeshuris** [comment]
I'm glad it worked for you.
I would suggest that you put that into the wiki of this repo, as this is not an issue.
And closing this issue :D

**Comment by nzhome** [comment]
thanks thats quite helpful, firstly what path did you place your config.json file? and I don't have an init.d file, can you post your one up please, thanks.

**Comment by nzhome** [comment]
I am just upgrading from raspberry PI2  to  orangePIone  it is twice as fast and only $9

**Comment by nzhome** [comment]
I found this init.d, is it any good?   https://github.com/thkl/homebridge/blob/ceefebb4cdaafac90d47605fe027bd9166af4b86/homebridge

**Comment by leonmf** [comment]
@nzhome, see this page for instructions to setup init.d: https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi
