### ISSUE TITLE
Energenie

### ISSUE THREAD

**Issue by cjsmith87** [nfarina/homebridge#728]
Not sure if this is the right place for this but I am wondering if anyone has any Energenie MiHome products? https://energenie4u.co.uk/mihome/the_range/ It works similar to Lightwave rf and it has an API https://mihome4u.co.uk/docs/api-documentation

Anyone be able to point me in the right direction for how I could write a plugin to support this?

**Comment by PatchworkBoy** [comment]
Install Domoticz, add them as Coco GDR2 switches, use homebridge-eDomoticz plugin.

**Comment by TheChallinor** [comment]
How did you get on with this? @cjsmith87

**Comment by simonrb2000** [comment]
Is that right Marci? I set mine up as energenie in domoticz? Maybe I have set mine up wrong.

Sent from my iPhone

On 18 Sep 2016, at 22:19, TheChallinor <notifications@github.com<mailto:notifications@github.com>> wrote:


How did you get on with this? @cjsmith87<https://github.com/cjsmith87>

-

**Comment by TheChallinor** [comment]
@simonrb2000 I have a load of energenie sockets I'm currently adding to Homebridge using IFTTT maker channels but obviously the status does not sync. Does it with your solution?

**Comment by PatchworkBoy** [comment]
Depends on generation of energenie hardware in play. For older green-button devices & dumb purple button devices tend to be able to just add as coco gdr2 and hit the ON button in Domoticz to trigger the learn. This is using rfxtrx433e. Same sockets are also CLI controlled via pyenergenie

The MiHome API requires cloud connection to MiHome site etc. Unnecessary if you have a USB transceiver... skip the MiHome hub and cloud entirely and run it all via homebridge & domoticz & homebridge-edomoticz

**Comment by PatchworkBoy** [comment]
If sockets are dumb receivers you can only accurately reflect status if they're solely controlled by Domoticz. They don't transmit anything, just receive an on/off. Domoticz can't learn the energenie remote so can't tell when sockets have been activated by external means. I use an ATI TV AllInWonder remote to externally trigger things via Domoticz, thus for me everything stays in sync.

**Comment by TheChallinor** [comment]
Thanks @PatchworkBoy 

I'm using the Mi home adaptor plus x6 and 6 of the older green type sockets. If I can get them solely working in Homebridge then there won't be a need for the MiHome app. 

Is the USB transceiver your referring to the Mi Home Gateway or something else?

Ive just setup on / off command using IFTTT Maker but if I can report status it would be better as at the moment the Home app on iOS 10 says they are on for a few second then reports them as off ( obviously as its one way communication with no status reporting ).

**Comment by PatchworkBoy** [comment]
USB transceiver = RFXTRX433E = http://www.uk-automation.co.uk/rfxcom-rfxtrx433e/

Paired with Domoticz it supports a myriad of brands, switches, sensors etc.

**Comment by PatchworkBoy** [comment]
![img_0810](https://cloud.githubusercontent.com/assets/3514253/18619494/e61ecaa2-7df5-11e6-9656-44d2c83f38a2.PNG)

Top 2 light switches are energenie sockets. Thermostat is a Siemens, temp probes are Dallas 1-wire sensors, plasma and amp switches are an energenie IR Pi hat that controls anything IR

**Comment by TheChallinor** [comment]
So with my current setup I can connect the Mi Home Gateway with the domoticz & homebridge-edomoticz, set it up with Homebridge and away I go!

How is domoticz & homebridge-edomoticz to use?  Only stumbled on Homebridge 2 days ago and started coding with it. 

Energenie are actually working on HomeKit support ( new hub I guess, hopefully sockets will remain the same ).

**Comment by simonrb2000** [comment]
Energenie IR pi looks interesting. I have an SQ Blaster that controls everything in the living room but got nothing for upstairs. I might have to try that.. have one in each room I need IR. Most of my curtains are IR, blinds are RF.

@TheChallinor, I can't recommend a RFXCOM mentioned above enough. Amazing bit of kit.

@Marci, my energenie are the green button ones, they don't always seem to respond to domoticz when using the energenie, might try your suggestion. Yes they are dumb with no feedback but I exclusively use Domoticz to control them all (usually through Homebridge these days ;-) )

Sent from my iPhone

On 18 Sep 2016, at 23:20, TheChallinor <notifications@github.com<mailto:notifications@github.com>> wrote:


So with my current setup I can connect the Mi Home Gateway with the domoticz & homebridge-edomoticz, set it up with Homebridge and away I go!

How is domoticz & homebridge-edomoticz to use? Only stumbled on Homebridge 2 days ago and started coding with it.

Energenie are actually working on HomeKit support ( new hub I guess, hopefully sockets will remain the same ).

-

**Comment by TheChallinor** [comment]
Anyone got a good guide on where to start with Domoticz and Linking to Energenie and Homebridge? 

That can be phase 2 of the project I think!

**Comment by PatchworkBoy** [comment]
Domoticz forums covers all.
Domoticz > Homebridge: https://www.domoticz.com/forum/viewtopic.php?f=36&t=10272
