### ISSUE TITLE
Can't Change HomeBridge Pin or any settings

### ISSUE THREAD

**Issue by oharkins** [nfarina/homebridge#730]
The settings appear to be cached somewhere I have deleted ~/.homebridge files and that did not change it, i have no plugins installed and i changed the pin in the config.json file and it is not working, it's like there is a file that I am missing that is cashing the settings i cant find it, any help would be great. 

Specs: 
Mac OS X
Iphone 6s Plus IOS 10 
 
Output:

<img width="553" alt="screen shot 2016-08-05 at 16 24 42" src="https://cloud.githubusercontent.com/assets/5509758/17452073/282ad2fa-5b29-11e6-98f3-3dd582124caa.png">

config.json
{
    "bridge": {
        "name": "RandomBridge",
        "username": "BC:32:7D:E3:CE:40",
        "port": 51826,
        "pin": "123-45-154"
    },

    "description": "This is an example configuration file with one fake accesso$

    "accessories": [
        {
            "accessory": "WeMo",
            "name": "Coffee Maker"
        }
    ],

    "platforms": [
        {
            "platform" : "PhilipsHue",
            "name" : "Hue"
        }
    ]
}

**Comment by KhaosT** [comment]
I think you placed config.json at the wrong place...

**Comment by nzhome** [comment]
I think homebridge looks for config.json in the wrong place.

**Comment by oharkins** [comment]
For any other person that is not good at reading directions, the config.json file needs to be in the ~/.homebridge/ location, without it in there it finds a built in example. I would agree with nzhome that homebridge looks in the wrong place to find that file, I would have expected it to be where the sample-config.json is located.
