### ISSUE TITLE
Homebridge Goals: Use as Home Hub

### ISSUE THREAD

**Issue by JangoBritt** [nfarina/homebridge#732]
I know iOS 10 isn't out yet... but oh how I wish my Mac could act as a HomeKit Hub, instead of having to buy an AppleTV or new iPad (my son's clunky iPad2 won't get iOS 10, and mine comes to work with me every day :( )

**Comment by MorningZ** [comment]
iOS 10 isn't going to fix your issue when it comes out and you'll have two choices on a HomeKit hub, - newer iPad or an AppleTV, there's been no indication that OSX (macOS/whatever) will be able to do this

**Comment by JangoBritt** [comment]
Ah yes, I realise that, that's why I wrote it down as a goal 😉

**Comment by KhaosT** [comment]
This one is not really actionable due to the infrastructure Apple used to communicate between iOS device and designated Home Hub.

**Comment by AlexGustafsson** [comment]
It would be great to see someone with an AppleTV or newer iPad try to MITM the data to dump some data and try to reverse-engineer the protocol. Since Apples servers are involved, perhaps it's a bit harder, but still.

**Comment by pdlove** [comment]
While I think it's possible, I also think it's the quickest way to have Apple obliterate this project. We operate on the fringe of what they might allow by using an existing 3rd party interface they have created. As soon as we try to use their own proprietary internal interface directly to their servers I'm fairly sure they'll put their lawyers to work.
Be patient. I would be too surprised if the macOS that follows Sierra doesn't do this very thing.
I've also considered if a iPad in IOS simulator might be used for this functions somehow. I think that's the best approach to avoid potential issues.

**Comment by AlexGustafsson** [comment]
@pdlove You're absolutely right, perhaps I was a bit too eager to see it work that I forgot about all consequences.

**Comment by pdlove** [comment]
@AlexGustafsson It's easy to get caught up in trying to figure out what you're trying to do. If you could crack into your iCloud interface and tell it that homebridge is an iPad that runs triggers, we'd still have to write the entire backend for managing those triggers and firing when appropriate. My advice... get a cheap 16GB iPad off eBay capable of running IOS 10.

**Comment by JangoBritt** [comment]
yea, you're right... I went out and bought a second hand 3rd Gen Apple TV from eBay for £35... cheaper than the development time, I guess
