### ISSUE TITLE
Risk of using default password

### ISSUE THREAD

**Issue by spock888** [nfarina/homebridge#733]
Can anybody comment on the risk of using the default password? I realize that nobody can connect unless they hack my WiFi password. Other than that, are there any risks? I have already setup my iDevices with the default password and just don't want to go through the setup process again.

**Comment by KhaosT** [comment]
That password is only used for first time setup, after that, people cannot add the accessory using the direct add method, instead it has to use HomeKit's user sharing method. It shouldn't be a huge problem.
