### ISSUE TITLE
Can homebridge query the state of non-homebridge, official HomeKit devices?

### ISSUE THREAD

**Issue by robertvorthman** [nfarina/homebridge#736]
I have a Schlage Sense lock, which does not have any sort of API for querying lock state.  It does not support HomeKit triggers at all, like when somebody locks or unlocks it.  Can homebridge, or any open source software, periodically poll the lock state?  I am looking to integrate the Schlage Sense into home-assistant.io.  Maybe I am looking in the wrong place, but I thought I'd ask.

**Comment by KhaosT** [comment]
Homebridge itself cannot connect to other HomeKit accessories. Only iOS device can do that.

**Comment by robertvorthman** [comment]
Thanks
