### ISSUE TITLE
Homebridge Win 7 install error on git cmd

### ISSUE THREAD

**Issue by wstoffels** [nfarina/homebridge#739]
I'm getting the following error messages when running the "npm install -g homebridge" command:

C:\Users\user123>npm install -g homebridge
C:\Users\user123\AppData\Roaming\npm\homebridge -> C:\Users\user123\Ap
pData\Roaming\npm\node_modules\homebridge\bin\homebridge

bignum@0.12.5 install C:\Users\user123\AppData\Roaming\npm\node_modules\h
omebridge\node_modules\bignum
node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://rvagg-node.s3-us-west-2.amazonaws.c
om/bignum/v0.12.5/bignum-v0.12.5-node-v47-win32-ia32.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for bignum@0.12.5 and node@5.0.0
(node-v47 ABI) (falling back to source compile with node-gyp)
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
  bignum.cc
  win_delay_load_hook.cc
..\bignum.cc(328): warning C4244: 'argument': conversion from 'uint64_t' to 'un
signed int', possible loss of data [C:\Users\user123\AppData\Roaming\npm\n
ode_modules\homebridge\node_modules\bignum\build\bignum.vcxproj]
..\bignum.cc(348): warning C4244: 'argument': conversion from 'int64_t' to 'uns
igned int', possible loss of data [C:\Users\user123\AppData\Roaming\npm\no
de_modules\homebridge\node_modules\bignum\build\bignum.vcxproj]
..\bignum.cc(413): warning C4244: '=': conversion from 'double' to 'uint64_t',
possible loss of data [C:\Users\user123\AppData\Roaming\npm\node_modules\h
omebridge\node_modules\bignum\build\bignum.vcxproj]
..\bignum.cc(514): warning C4244: 'argument': conversion from 'uint64_t' to 'un
signed int', possible loss of data [C:\Users\user123\AppData\Roaming\npm\n
ode_modules\homebridge\node_modules\bignum\build\bignum.vcxproj]
..\bignum.cc(532): warning C4244: 'argument': conversion from 'uint64_t' to 'un
signed int', possible loss of data [C:\Users\user123\AppData\Roaming\npm\n
ode_modules\homebridge\node_modules\bignum\build\bignum.vcxproj]
..\bignum.cc(550): warning C4244: 'argument': conversion from 'uint64_t' to 'un
signed int', possible loss of data [C:\Users\user123\AppData\Roaming\npm\n
ode_modules\homebridge\node_modules\bignum\build\bignum.vcxproj]
..\bignum.cc(569): warning C4244: 'argument': conversion from 'uint64_t' to 'un
signed int', possible loss of data [C:\Users\user123\AppData\Roaming\npm\n
ode_modules\homebridge\node_modules\bignum\build\bignum.vcxproj]
..\bignum.cc(652): warning C4244: 'argument': conversion from 'uint64_t' to 'un
signed int', possible loss of data [C:\Users\user123\AppData\Roaming\npm\n
ode_modules\homebridge\node_modules\bignum\build\bignum.vcxproj]
..\bignum.cc(787): warning C4244: 'argument': conversion from 'uint64_t' to 'un
signed int', possible loss of data [C:\Users\user123\AppData\Roaming\npm\n
ode_modules\homebridge\node_modules\bignum\build\bignum.vcxproj]
     Creating library C:\Users\user123\AppData\Roaming\npm\node_modules\ho
  mebridge\node_modules\bignum\build\Release\bignum.lib and object C:\Users\sto
  ffels.wcs\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum\bui
  ld\Release\bignum.exp
  Generating code
  Finished generating code
  bignum.vcxproj -> C:\Users\user123\AppData\Roaming\npm\node_modules\home
  bridge\node_modules\bignum\build\Release\bignum.node
  bignum.vcxproj -> C:\Users\user123\AppData\Roaming\npm\node_modules\home
  bridge\node_modules\bignum\build\Release\bignum.pdb (Full PDB)
  Copying C:\Users\user123\AppData\Roaming\npm\node_modules\homebridge\nod
  e_modules\bignum\build\Release\/bignum.node to C:/Users/user123/AppData/
  Roaming/npm/node_modules/homebridge/node_modules/bignum/binding\bignum.node
          1 arquivo(s) copiado(s).

curve25519@1.1.0 install C:\Users\user123\AppData\Roaming\npm\node_module
s\homebridge\node_modules\curve25519
node-gyp rebuild

C:\Users\user123\AppData\Roaming\npm\node_modules\homebridge\node_modules\c
urve25519>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodej
s\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js
" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
  node_curve.cc
..\node_curve.cc(6): fatal error C1083: Cannot open include file: 'unistd.h': N
o such file or directory [C:\Users\user123\AppData\Roaming\npm\node_module
s\homebridge\node_modules\curve25519\build\curve.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_mo
dules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\Program Files (x86)\nodejs\node.exe" "C:\Program Files
(x86)\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "reb
uild"
gyp ERR! cwd C:\Users\user123\AppData\Roaming\npm\node_modules\homebridge\n
ode_modules\curve25519
gyp ERR! node -v v5.0.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files (x86)\nodejs\node.exe" "C:\Program Files (x8
6)\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "homebridge"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE

npm ERR! curve25519@1.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the curve25519@1.1.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the curve25519 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls curve25519
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\user123\npm-debug.log

Can someone show me how to solve this?

**Comment by bittles** [comment]
Double-check you have the right 32 bit or 64 bit applications downloaded exactly per the installation readme.  I ran into this problem, forget which program I had was 64 bit and not 32 bit like the wiki calls for.  I think it was python maybe.  Not sure, but I remember I had to go into the list of downloads to specify x86 instead of just clicking the download button that auto-detects for you.

**Comment by wstoffels** [comment]
Sadly that's not the reason, I double checked and they're all the right versions ;/
