### ISSUE TITLE
Some iPhones don't find homebridge

### ISSUE THREAD

**Issue by thegimliboy** [nfarina/homebridge#740]
Hey.
I installed homebridge on a fresh ubuntu 16.04 server using this german guide: http://www.fhemwiki.de/wiki/Homebridge_einrichten.
I tried to set homebridge up using the eve app, but my iPhones (5S and 4S) diddn't find anything, while my fathers iPhone found it, connected to it, and even after several restarts still connects. So I deleted the .homebridge folder, set it up again, my iPhone found it (only my 5S), but my 4S and my fathers iPhone diddn't find it. I looked this problem up but found no solution. (Btw. I also changed the username in conf.)

Greets.

**Comment by pdlove** [comment]
I believe only one device can register. Others must be shared over iCloud. I'm not sure why this limitation exists but it is across all HomeKit devices.

**Comment by thegimliboy** [comment]
Oh. That makes sense. Thanks for your answer. Have a nice day.
