### ISSUE TITLE
Error: dns_sd.DNSServiceRegister dns service error: unknown

### ISSUE THREAD

**Issue by chymerix** [nfarina/homebridge#741]
Hi,

I am getting the exact same errors listed here: https://github.com/nfarina/homebridge/issues/613

I tried applying the fixes in the above post (and others) but the errors persist. Any ideas what might be causing this?

This is on Bash on Ubuntu on Windows 10.

node -v
v.6.3.1

npm -v
3.10.3

Thank you

**Comment by mactr0n** [comment]
Since _Bash on Ubuntu on Windows 10_ is still beta and isn't fully implemented yet I wouldn't put too much effort into solving this problem. Might have something todo with how the network for _Bash on Ubuntu on Windows 10_ works.

**Comment by chymerix** [comment]
I purchased a Raspberry Pi and got everything to run fine there. Closing issue.
