### ISSUE TITLE
How do I tell HomeBridge to update when the state of one of my accessories has changed outside of homekit?

### ISSUE THREAD

**Issue by jasonteale** [nfarina/homebridge#742]
I have an MQTT light running on an ESP8266 which is registered as an accessory in HomeBridge.
Everything works great and I can turn it on/off, change brightness, and homekit can get it's current state when I ask Siri. 

The problem I have is that if I change the light's state from outside homekit, e.g. I send an MQTT message from a switch or from a "node-red flow", how does homekit know the state has changed?

If I ask Siri "is the light on", it does query the accessory and get it's real state.
Also when I first launch the apple "home" homekit app, it seems to request the real state of the accessory at launch time.

But if i have the home app open on my iPhone, and then change the state of the light from the mqtt switch, homekit does not update, and so gets out of sync with reality.

Ideally from my accessory in homebridge, I'd like to subscribe to an MQTT topic so that if the light's state is changed (and the new value is published to the topic), then I can tell homebridge to update it's current state.

Does anyone know if this is possible?

**Comment by cflurin** [comment]
Hi,
Take a look at:
https://github.com/cflurin/homebridge-mqtt
and
https://github.com/cflurin/homebridge-mqtt/wiki

**Comment by abataille** [comment]
Is there a way to access all accessories registered with a platform?

**Comment by derekmoyes** [comment]
FWIW, this happens with WeMo lights, too. I have IFTTT configured to turn lights on at Dusk, the time of which actually changes from season to season. HomeKit doesn't support dynamic time triggers like this. Once IFTTT turns on my light, Homebridge doesn't know it's correct status.

**Comment by abataille** [comment]
I am just creating a plugin for Osram Lightify.
I currently use a global variable to keep the found accessories (which I like to have at the platform level). With polling I am able to change the state of the accessory if it was modified outside of home bridge.

**Comment by jasonteale** [comment]
Thanks cflurin, I quite like the way you've approached your mqtt plugin actually.
I had previously just written my own mqtt accessory, but I didn't think of using mqtt to add the accessory automatically, it works really well.

In addition I've now got homebridge updating it's state if I send my mqtt device a command directly (outside of homebridge) which is nice.

Many thanks.

**Comment by shuaiger** [comment]
Hi Jasonteale, how did you do that? I mean updating homebridge's state if you send my mqtt device a command directly (outside of homebridge). Thanks!
