### ISSUE TITLE
Honeywell Total Connect Comfort Support?

### ISSUE THREAD

**Issue by kenderson** [nfarina/homebridge#744]
Is anyone working on (or have on a roadmap to work on) support for the Honeywell Total Connect Comfort thermostat product line?

Thanks All!

**Comment by gotwalt** [comment]
I was actually looking for the same thing a few weeks ago. A long time ago I built https://github.com/gotwalt/redlink, which provides a ruby wrapper for their SOAP api. It could probably be used as a guide for building something here if it doesn't already exist.

**Comment by lke523** [comment]
I'll throw my name in the ring, too, as someone who would love to see this.

**Comment by mikerpalmer-12** [comment]
+3

**Comment by morak82** [comment]
Try homebridge-evohome. 
It uses Total Connect Comfort so might work for non-evohome products.

**Comment by alienware00** [comment]
homebridge-evo does not work. Any update on this issue or am I buying new thermostats lol

**Comment by afrustagli** [comment]
I was just looking into this.  I'm thinking of writing a plugin myself, but I don't have a lot of free time and don't know when I'll actually get around to it.  In the meantime I'm thinking you could use a general cmd type plugin, like this one: https://github.com/doodieb15/homebridge-cmd_light_control, and use it to call a shell script that uses commands from a  project like this: https://github.com/willdollman/perl-total-connect-comfort/blob/master/Device/TotalConnectComfort.pm

It's not an ideal solution, but I'm pretty sure it can work with minimal effort.

**Comment by NorthernMan54** [comment]
I posted a beta version of a plugin for this, homebridge-tcc, yesterday.  It is based on the evohome plugin and some python scripts I found.  At this time I have only connected the ability to monitor or read the thermostat values, and have not completed the code for updates yet.

**Comment by propaganda-mars** [comment]
Thanks NorthernMan54 for putting the homebridge-tcc plugin together, it works nicely with my Honeywell total connect comfort thermostats.  I have had one issue though and the plugin doesn't want to accept 2 thermostat units at the same time although it will independently.  I have created a config.json file like this:

{
	"bridge": {
		"name": "Homebridge",
		"username": "xx:xx:xx:xx:xx:xx",
		"port": xxxxx,
		"pin": "xxx-xx-xxx"
	},

	"description": "Need your help",

	"platforms": [{
		"platform": "tcc",
		"name": "Downstairs Thermostat",
		"username": "xxxx@xxxx.com",
		"password": "xxxxxxxx",
		"deviceID": "xxxxxxx"
	},{
		"platform": "tcc",
		"name": "Upstairs Thermostat",
		"username": "xxxx@xxxx.com",
		"password": "xxxxxxxx",
		"deviceID": "xxxxxxx"
	},{
		"platform": "LiftMaster2",
		"username": "xxxx@xxxx.com",
		"password": "xxxxxxxx"
	}]
}

Is it even possible to have multiples of the same platform?

**Comment by NorthernMan54** [comment]
propaganda-mars can you open a new issue on homebridge-tcc https://github.com/NorthernMan54/homebridge-tcc and post the homebridge.log.  I'm curious to see what is happening.

**Comment by dishguy** [comment]
Any updates?? I’m trying to connect now as I type

**Comment by alexgarlock** [comment]
I never got this one to work. The one I got working was this one linked here.

https://www.npmjs.com/package/homebridge-tcc
