### ISSUE TITLE
missing script: start

### ISSUE THREAD

**Issue by bucknsty** [nfarina/homebridge#746]
i am new to this what is going on here?

thank you

pi@raspberrypi:~/homebridge$ npm run start
npm ERR! Linux 4.1.18-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7

npm ERR! missing script: start
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/homebridge/npm-debug.log
pi@raspberrypi:~/homebridge$

**Comment by nrobinson2000** [comment]
I would recommend using the latest version of Node:
```sh
curl deb.nodesource.com/setup_6.x | sudo bash
sudo apt-get install nodejs
```
