### ISSUE TITLE
Scenes

### ISSUE THREAD

**Issue by abataille** [nfarina/homebridge#747]
I have a intermittent problem with scenes.
I define a scene with 3 light bulbs, to switch them all on.
I play the scene and most times only the first bulb is switch on.
The debug log shows, that all on characteristics fired and the platform did set on.
Any idea ?

**Comment by cdanella** [comment]
I am also having a problem with scenes. I have a scene that I use to control multiple Nest thermostats at the same time. It worked great for months then about 3 weeks ago it only worked 50% of the time. Now the scene doesn't work at all. I can still control each thermostat separately with Siri.

**Comment by abataille** [comment]
You can close this issue from my side. Homebridge did send the correct commands in the correct sequence. The problem was net.Socket handling in the platform.
Sorry for the issue.
