### ISSUE TITLE
No config.json

### ISSUE THREAD

**Issue by 1liminal1** [nfarina/homebridge#749]
Hey guys,

I seem to be missing the config file and actually the homebridge dir as well

Homebridge works ok, I can find the bridge in the home app, I have installed the LIFX plugin. But thats as far as I can get?

Any ideas, im pretty new to Linux, but it all seemed to install ok?

**Comment by 1liminal1** [comment]
Sorry, figured it out :)

**Comment by steam0** [comment]
**PLEASE** answer your own question. Why would you just answer with "Sorry, figured it out?". How will that help the next guy that has the same problem as you?

I do understand that the answer to this question is very trivial, but come on, don't be that guy that asks questions, but never provide the solution.

**Comment by 1liminal1** [comment]
HAHA, you're right. I was rushing though it last night, I was going to update :)

For those of you that cant find the config-sample.json, following the guides for the Ubuntu install, you will find it @ /usr/lib/node_modules/homebridge

Also WIndows people using Linux, use nano as the text editor, less googling that way, much more intuitive.
