### ISSUE TITLE
Installation help (Windows)

### ISSUE THREAD

**Issue by cozdabuch** [nfarina/homebridge#751]
I'm 98% noob as anything code related goes.  
I was following the installation instructions for windows, and I got to  step 3.

> 3: Configuration Visual Studio
> - The Windows User-Account must have administrator rights!
> 
> 1 - Open Visual Studio Community and create a C++ Project to install "dev environment"

I also read through step 4, and as I have just about no idea what anything is doing, I'm not sure where and when dots need to be connected.  Could anyone expand on this install guide wither in writing or a brief video tutorial?

It would be extremely appreciated.

**Comment by evogta** [comment]
I tried to install homebridge to Windows10 64bit.
When I did install with WiKi page installation procedure.
I also confused above "create a C++ Project to install "dev environment"".

(1) Finally, that means "create a dummy project with Visual C++ template win32 console application".
        You don't need to care about project name and other project options.
        You can move to following steps.

Addtitionally, 
(2) unistd.h by "Version of Patcher " has error , I used "Version of WilliamHF " that had no error.
(3) In "npm install -g homebridge" step had error.
     So I updated npm module with "npm install npm -g". and again above command.
     But downloading error was reported , that module already installed then I ignored.

I hope this helpful.
