### ISSUE TITLE
if config.json doesn't exist, homebridge starts with default values.

### ISSUE THREAD

**Issue by cflurin** [nfarina/homebridge#752]
Hi,

If config.json doesn't exist, homebridge starts with the default values.
However the plugin config is null and this will lead to an error in the plugin.

I propose to insert an error message in server.js, line 162:

```
log.error("config.json (%s) doesn't exist. Continuing with default values.", configPath);
```

**Comment by justme-1968** [comment]
maybe it would even be better to stop completely. without any plugins it makes no sense to run homebride.

**Comment by cflurin** [comment]
OK, the modification would be:

```
log.error("config.json (%s) doesn't exist.", configPath);
process.exit(1)
```

**Comment by KhaosT** [comment]
That's the original behavior … with the introduction of plugin 2.0 system, it's techinically possible to run homebridge without a configuration file and later configure the supported plugin using an app on iOS device. However, it looks like there isn't a lot developer taking advantage of this feature so I'm not really sure what's the right thing to do then…

**Comment by cflurin** [comment]
That's the reason I've proposed to print a message and to continue.
I've changed homebridge-websocket, it prints a message and exits if config.json doesn't exist (config === null).

Maybe a warning would be enough:

```
log.warn("config.json (%s) doesn't exist. Continuing with default values.", configPath);
```

BTW all my plugins run with plugin 2.0.

**Comment by KhaosT** [comment]
Good suggestion :) If you can submit a PR, I'm happy to merge it, otherwise I'll try to add it after mid September.
