### ISSUE TITLE
Running Homebridge twice on the same device

### ISSUE THREAD

**Issue by giase82** [nfarina/homebridge#754]
Hey there,

I tried to run home bridge twice on my Raspberry Pi in order to get rid of the 99-devices-limitation. It once or twice succeeded if I do this manually, but it didn't work so far on startup.

I use two different configs and start them as separate services. I tried different ports in the config, but it seems it is using 51826 always. I used different identifiers ("username").

Can anybody tell me what else I need to do to be able to run 2 home bridge servers on the same device?

Cheers,
//Christof

**Comment by giase82** [comment]
I've created two deamons and it turned out I set permissions wrongly. No home bridge issue.

**Comment by AmitMY** [comment]
Hi @giase82 ! I too have the 99 devices limitation issue, and I was wondering if you could point me in the right direction on how to correctly setup 2 homebridges.
Thanks

**Comment by giase82** [comment]
Hi!

Sorry for the long silence!
You basically need to create two folders for you configs, e.g.:
/var/homebridge 
/var/homebridge2

Then, create two deamons using the "-U" switch to point to those locations.

Et voila.

Please let me know if you need more information!

//Christof 

Sent from a mobile device

**Comment by AmitMY** [comment]
Thanks! My home server encountered a problem, and is tomorrow being replaced (bug in their interface caused a system crash). 
I will try this tomorrow/the day after and will let you know.
