### ISSUE TITLE
Error during  install

### ISSUE THREAD

**Issue by MF-Bra** [nfarina/homebridge#76]
Trying to install homebridge on my Raspberry pi and got this error after the first "sudo npm install" 

npm ERR! Error: 1995645456:error:10067066:elliptic curve routines:ec_GFp_simple_oct2point:invalid encoding:../deps/openssl/openssl/crypto/ec/ecp_smpl.c:939:
npm ERR! 1995645456:error:1408D132:SSL routines:SSL3_GET_KEY_EXCHANGE:bad ecpoint:../deps/openssl/openssl/ssl/s3_clnt.c:1566:
npm ERR! 
npm ERR!     at CleartextStream._puller (tls.js:618:24)
npm ERR!     at CleartextStream.CryptoStream._pull (tls.js:552:19)
npm ERR!     at SecurePair.cycle (tls.js:842:20)
npm ERR!     at EncryptedStream.CryptoStream.write (tls.js:230:13)
npm ERR!     at Socket.ondata (stream.js:38:26)
npm ERR!     at Socket.EventEmitter.emit (events.js:88:17)
npm ERR!     at TCP.onread (net.js:395:14)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

Initially I posted this issue within npm github area but no luck so far, it seems related with OpenSSL

**Comment by nfarina** [comment]
Hard to tell from that error dump, but I just ordered a RPi myself and will see how it goes for me and report back.

**Comment by MF-Bra** [comment]
understand and thank you.

Actually i could make it work digging on this forum i found this commands : 

sudo apt-get install libavahi-compat-libdnssd-dev 
sudo wget http://node-arm.herokuapp.com/node_latest_armhf.deb
sudo dpkg -i node_latest_armhf.deb
sudo git clone https://github.com/nfarina/homebridge.git
cd homebridge
sudo git submodule init
sudo git submodule update
sudo npm install
sudo npm run start

But now i'm getting another error instead, it reads probably all my devices under ISY and presents this :

.....
[ISY] Initializing device with name <NAME REMOVED>...
Cannot find secret key, creating One...
TCP server accepting connection on port: 55XXX
HAP Server is listening
[ISY] Initializing device with name <NAME REMOVED>...
Cannot find secret key, creating One...
TCP server accepting connection on port: 55XXX
HAP Server is listening
[ISY] Initializing device with name <NAME REMOVED>...
Cannot find secret key, creating One...
TCP server accepting connection on port: 55XXX
HAP Server is listening
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1156:14)
    at listen (net.js:1182:10)
    at Server.listen (net.js:1267:5)
    at Object.startServer (/homebridge/node_modules/HAP-NodeJS/TCPServer.js:31:15)
    at Object.publishAccessory (/homebridge/node_modules/HAP-NodeJS/Accessory.js:13:28)
    at createHAPServer (/homebridge/app.js:169:15)
    at /homebridge/app.js:92:17
    at Request._callback (/homebridge/platforms/ISY.js:78:13)
    at Request.self.callback (/homebridge/node_modules/request/request.js:373:22)

npm ERR! Linux 3.18.11-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
npm ERR! node v0.12.6
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE
npm ERR! homebridge@0.0.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the homebridge@0.0.0 start script 'node app.js'.
npm ERR! This is most likely a problem with the homebridge package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls homebridge
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /homebridge/npm-debug.log

**Comment by micha149** [comment]
`EADDRINUSE` occurs when node will start a server on a port which is already in use. Homebridge has a hard coded starting port `51826` in `app.js`. From this port number it counts new port numbers for each accessory. Maybe one of this is already in use by another process…

**Comment by nfarina** [comment]
Added working instructions for installing on a RPi 2: https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi
