### ISSUE TITLE
"command not found" when running homebridge

### ISSUE THREAD

**Issue by taxidriver1138** [nfarina/homebridge#761]
I have Homebridge working perfectly on my Mac. I'm trying to install in on a friends Mac and the install doesn't give me any errors. But when I try to run the homebrige command I get "command not found". I can't seem to find anyone else online that had this problem

**Comment by JekaKey** [comment]
Seems like you miss -g key on install.
If you dont use it, you install package in current local folder, but not globally in you system.
You can simple check this:
Start terminal, got to node modules folder by `cd /usr/local/lib/node_modules/` and than show folder content by write `ls -la`, you cat see all node modules and homebridge (as part of node modules) too. If you dont, reinstall homebridge and homebridge plugin with -g key `sudo npm install -g homebridge`

**Comment by WhiskeyPapaTango** [comment]
Sorry to bump an old thread, but I appear to be having the same issue.

I am attempting to get it running on my raspberry pi, and was using [the wiki guide](https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi)

I have used `sudo npm install -g homebridge ` to install it and it appears to install without any errors.

However, I am still get the "command not found" error upon attempting to run the homebridge command.


```
pi@raspberrypi:~ $ sudo npm install -g homebridge
/opt/node/bin/homebridge -> /opt/node/lib/node_modules/homebridge/bin/homebridge
/opt/node/lib
└── homebridge@0.4.20 

pi@raspberrypi:~ $ homebridge
-bash: homebridge: command not found
```

**Comment by xoniq** [comment]
I solved this by adding the following to the `~/.bashrc` file (using nano or vi):

`PATH="/opt/node/lib/node_modules/homebridge/bin:$PATH"`

Then save the file, and run `. ~/.bashrc` to reinitialize the bashrc file on the current session.
Now you can run homebridge as a binary.

**Comment by rafiqaust** [comment]
Hi mate can u tell me where is exactly put this line PATH="/opt/node/lib/node_modules/homebridge/bin:$PATH"
To my raspberry pi

**Comment by xoniq** [comment]
@rafiqaust In the bottom of ~/.bashrc
When you have done this, you can reload the file with `. ~/.bashrc`

**Comment by AndreiFAD** [comment]
thx this has solved for me:

$ echo -e 'PATH="/opt/node/lib/node_modules/homebridge/bin:$PATH"' >> ~/.bashrc
$ . ~/.bashrc
$ echo -e 'PATH="/opt/node/lib/node_modules/homebridge/bin:$PATH"' >> ~/.profile
$ sudo reboot

**Comment by geofbuck** [comment]
I have the same issue on a mac. was running perfectly, updated with sudo and -g and now its broken.

**Comment by geofbuck** [comment]
I will try to update each plugin individually and see if that works

**Comment by geofbuck** [comment]
Comes back with this trying home bridge install:

/usr/local/bin/homebridge -> /usr/local/lib/node_modules/homebridge/bin/homebridge

> mdns@2.3.4 install /usr/local/lib/node_modules/homebridge/node_modules/mdns
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/homebridge/node_modules/mdns/build'
gyp ERR! stack     at Error (native)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/homebridge/node_modules/mdns
gyp ERR! node -v v6.10.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mdns@2.3.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mdns@2.3.4 install script.
npm ERR! This is probably not a problem with npm. There is likely a

**Comment by shtirlic** [comment]
I have the same issue, moreover, I do not use npm at all, I use yarn for packages and running homebridge.

**Comment by geofbuck** [comment]
I fixed it following various threads but the gist of it is: make sure you use "-g" and "--unsafeperm" when you are installing homebridge and plugins.

**Comment by FlorioManagement** [comment]
I cannot seem to get this to work either.  Home bridge was working fine then I ran a update to Homebridge now I can't get it to work.  

I have tried to run
`sudo npm install -g --unsafe-perm homebridge`

And I get no errors.  But I can't get hb to run trying
`sudo hb-service start`

and I get
`sudo: hb-service: command not found`

**Comment by geofbuck** [comment]
check to make sure it's be installed in the correct place. Sounds like some some elements were installed locally and not globally.

**Comment by FlorioManagement** [comment]
> check to make sure it's be installed in the correct place. Sounds like some some elements were installed locally and not globally.

Thank you Geof!  Do you have a recommend few command lines (or places in finder) I can use to check that?

**Comment by geofbuck** [comment]
try just running the command homebridge -I at the command line. then check to see if its running (systemctl status homebridge). not sure what platform you are running it on or if its running as a systemd or initd? Follow this guide for troubleshooting steps:  https://github.com/nfarina/homebridge/wiki/Basic-Troubleshooting <https://github.com/nfarina/homebridge/wiki/Basic-Troubleshooting>
