### ISSUE TITLE
Accessories must be created with a non-empty displayName.

### ISSUE THREAD

**Issue by tpitman** [nfarina/homebridge#762]
I just barely downloaded and installed homebridge on my RPi3B. I am getting the error that is the title of this issue.

I looked it up and there are fixes for it in the code, so I don't understand why I would get this error with the latest npm install.

My config.json file is the example given on the hap site. Here it is:

`{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},

	"description": "My Homebridge",

	"accessories": [{
		"accessory": "Fake-RGB",
		"name:": "RGB Bulb"
	}],

	"platforms": []
}
`

**Comment by JekaKey** [comment]
You have mistake in this place:
`"name:": "RGB Bulb"`
use this right code:
`"name": "RGB Bulb"`

**Comment by tpitman** [comment]
I can't believe I missed that. I looked so many times comparing and just couldn't see it.

Thanks a ton! Sorry to bug everyone.
