### ISSUE TITLE
Homebridge Web

### ISSUE THREAD

**Issue by aramaki87** [nfarina/homebridge#763]
Hi there

I was wondering if I can query the homebridge server like say from the network on a non apple device. I have a web server running on the raspberry 3 (parallel to the homebridge server on the same device) which could show some homebridge information on a screen. Is it possible to get some information to that web server from the home bridge. Like showing the temperature on a webpage. Or showing the state of some objects. Of course they need to be accurate. When I change a value with my iPhone they change on the website.

I hope you'll get what I mean ;-)
Thanks!

**Comment by toshibochan** [comment]
Homebridge is only for Apple HomeKit, only work for Siri.

**Comment by aramaki87** [comment]
Not sure if you know what I mean. As long as it is installed on a linux system I have access to all the resources on that device. Due to the parallel installed homebridge it should be easy to access (same computer).
Dirty would be: I can get the config.json to load in that website to get all the devices. For all devices I'll additionally check a boolean somewhere to query by the website.
Maybe I'll do it that way...

**Comment by toshibochan** [comment]
Sorry I don't know what you want do!

**Comment by aramaki87** [comment]
I would like to build a local website with the content of the homebridge. That page must only be able to show the states of all the homebridge devices and is unattended. I do not want to control anything from there.
To achieve this I need to get the states from the homebridge.

**Comment by toshibochan** [comment]
Homebridge is only for iOS devices.

**Comment by aramaki87** [comment]
Thx for your help. But you don't get the point.

-> In the end I used global variables to set the states of all the devices when I activate / deactivate them. The web server scans the config.json to dynamically build its content. I hope this helps anyone...
