### ISSUE TITLE
Pine64  Module version mismatch. Expected 48, got 46 - mdns

### ISSUE THREAD

**Issue by robertcedwards** [nfarina/homebridge#767]
Having this issue when running Homebridge. I've tried npm rebuild and npm -r on the mdns module and reinstalling it. No luck.

```
~$ node -v
v6.2.2
~$ npm -v
3.5.2
```

```
openhab@openhab:~$ homebridge
/usr/local/lib/node_modules/homebridge/node_modules/mdns/lib/dns_sd.js:35
    throw ex;
    ^

Error: Module version mismatch. Expected 48, got 46.
    at Error (native)
    at Object.Module._extensions..node (module.js:568:18)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/mdns/lib/dns_sd.js:24:20)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)

```

**Comment by brianhanifin** [comment]
I'm having this same issue. If you figure it out let me know. I wonder if finding a newer version of libavahi-compat-libdnssd-dev would fix it?

**Comment by robertcedwards** [comment]
I was able to fix it by rolling back to node 4.0 .0

**Comment by brianhanifin** [comment]
I installed [node-v4.5.0-linux-arm64.tar.gz](https://nodejs.org/download/release/latest-v4.x/) using [this method](http://www.thegeekstuff.com/2015/10/install-nodejs-npm-linux/), then reinstalled homebridge.

I am further along (I think), now I am getting a "Error: Not a valid username: undefined. Must be 6 pairs of colon-separated hexadecimal chars (A-F 0-9), like a MAC address." But I can work with that. :)

**Comment by brianhanifin** [comment]
Fixed by username added to conf. :)

Close this issue down kind admin.

**Comment by jwoertink** [comment]
For MacOS Sierra, I had to 
```
brew uninstall --force node
brew tap homebrew/versions
brew install homebrew/versions/node4-lts
npm install -g homebridge
```

Now I get the not a valid username error. @brianhanifin How did you fix that? I'm using Wink, and my username is an email address which doesn't conform to a MAC address style.
