### ISSUE TITLE
'Plugin /usr/lib/nodejs does not have a package name that begins with 'homebridge-'.'

### ISSUE THREAD

**Issue by olliegg123** [nfarina/homebridge#768]
Can anybody help me with this 'Plugin /usr/lib/nodejs does not have a package name that begins with 'homebridge-'.' please? It appears when i run 'homebridge'.
I can find my accessories in the home app, but they are all at no response and clicking them to trigger does nothing?

**Comment by DTO213** [comment]
same issue,any solutions?
