### ISSUE TITLE
Does Homebridge support  Koogeek Home Smart Plug? Or in the future?

### ISSUE THREAD

**Issue by Ricardo1980** [nfarina/homebridge#769]
Hello!

I saw this good offer in the UK:
http://www.tomtop.com/smart-equipments-accessories-51/p-p1.html?currency=GBP&lang=en&aid=gplagb&gclid=CMy4gMKLks8CFXgz0wodiUsBvw

http://www.koogeek.com/p1.html

It seems a nice device I could control with Siri. 
I wonder if in the future or now I could control it directly through Hombridge.

Thanks a lot.

**Comment by jaysettle** [comment]
I'm using koogeek with homebridge. It has worked well. 


-Jay

**Comment by Ricardo1980** [comment]
That is awesome!!! Thanks a lot. 

Are you using only the wall plug? Or do you have to use a special router?


What plugin are you using? Didnt see any related in the repo. 

Can you read current state from the plugin?

Thanks a lot! Very useful.

**Comment by jaysettle** [comment]
​Sorry should've offered a little info on this. I have homebridge running
from my mac with a couple homebridge-http devices. I bought the Koogeek and
plugged it in. I ran through the installation, which required the Koogeek
iphone app and a different pin other than the 031-45-154. After adding the
Koogeek accessory it populated in my other apple Homekit apps running on
iphone 9.3.2 such as Home, Hesperus, myHome+, MyTouchHome. It worked
seemlessly for a while with the other devices.
So I should say it wasn't running in homebridge, nor did I have a plugin at
all for it but it did work well with the apps I have. Sorry if that was
misleading.
However I should also state that there is a twist to the story which I
don't understand yet. As I powered off my mac, I noticed all my devices
were still online and I could control them through siri still. Did setting
up Koogeek being an Apple Certified device somehow move device hosting
somewhere else? Maybe someone knows.
I like the device, it's very well built and very simple.

**Comment by Ricardo1980** [comment]
I guess that is because this is a homekit device and uses wifi. 
In fact that is what dpecifitations say:

Size: 65*65*56(mm)
Power Input: 95~120V AC Max, 60Hz
Resistive: 15A,1800W
System Requirements:
Home Wi-Fi (802.11 b/g/n)
WPA or WPA2 Network Security

So, uf we use wifi to control it, perhaps it is possible using the http plugin.

**Comment by jaysettle** [comment]
Ricardo did you see my last post about the Koogeek? It's not showing in my email. 


-Jay

**Comment by Ricardo1980** [comment]
Yep
