### ISSUE TITLE
No notifications

### ISSUE THREAD

**Issue by KanKuzi** [nfarina/homebridge#771]
I running iOS 10 with the home app on a iPad and i don't get any notification either when a door opens or a motion dectector triggers, is there some specific parameter i need to set in my plugins?

I have allowed notifications in settings and on the unit.

**Comment by brushj** [comment]
Having the same issue on my iPhone. The really strange thing for me is that my iPad still receives notifications. I installed a few of the betas on it and it was working without an issue, I just updated it to the GM and it's fine as well. My phone is still a no go for me though.

**Comment by brushj** [comment]
Just updated to 10.1 and "Allow Notifications" for all of my sensors is back again. 10.1 appears to have fixed the issue.
