### ISSUE TITLE
Starting on boot Ubuntu server 16.04

### ISSUE THREAD

**Issue by Bigfellas** [nfarina/homebridge#772]
Can anyone help me. I have homebride  installed and running on Ubuntu server 16.04.
I would love to get it to start on boot. The Raspi tuts didn't work for me and I have been hunting the web. But I have had no joy. My linux skills are very limited. Any help would be appreciated massively.

Thanks Matt

**Comment by nrobinson2000** [comment]
Adding a line to `/etc/rc.local` worked for me.  Here is what I added:
```
su -c "screen -dmS homebridge homebridge" -s /bin/sh USERNAME
```
This makes `homebridge` run on boot inside of a screen under a certain user.  Replace `USERNAME` with your username.

You will need to have `screen` installed.
```
sudo apt-get install screen
```

**Comment by Bigfellas** [comment]
That's fantastic thanks. That worked on Ubuntu Cheers

**Comment by timleland** [comment]
Here is my guide in setting up Homebridge on Raspberry Pi to start on boot up and restart on errors. Hope it help!
https://timleland.com/setup-homebridge-to-start-on-bootup/
