### ISSUE TITLE
Adding homebridge to Home App fails

### ISSUE THREAD

**Issue by ameeuw** [nfarina/homebridge#773]
I am trying to pair my homebridge again with an iPad running iOS 10.
Starting the homebridge works fine and adds all my desired accessories. It shows up in the discovery of the Home.app and I can (after clicking 'Add anyway') enter the security code. Then the spinner spins until (an apparently iOS 10 related timeout is reached) the Home.app tells me that it cannot add the accessory.

What changed from last week? I managed to add homebridge fine before.

I am very thankful for any help and directions where to look for answers.
Thanks.

**Comment by ameeuw** [comment]
Homebridge runs on raspberry pi 2.

**Comment by stevenguh** [comment]
I paired my iPhone which is running iOS 10 with homebridge just fine.
Have your tried removing `persist/` directory?
Did you configure any accessory or platform in homebridge?

**Comment by ericmagnuson** [comment]
I'm also having the same problems adding Homebridge in the Home app in iOS 10.

**Comment by ameeuw** [comment]
Somehow it works on a MacMini that is running 10.8. but on the Pi I still did not manage to get it to run. 
@ericmagnuson what do mean by "I forgot to open up ports on my Homebridge server."? What did you change?

**Comment by ericmagnuson** [comment]
The server on which my homebridge node app is running had a firewall enabled (`ufw` firewall to be exact).  I had to open port 51826 (found in the configuration) so that my phone could talk to homebridge.

What OS are you running on your Pi?  I don't have any experience with Raspberry Pis, but I can try to help! 👍
