### ISSUE TITLE
Homebridge Stops working after a few days

### ISSUE THREAD

**Issue by maxtheeverything7** [nfarina/homebridge#774]
Homebridge ran normally for about a week then timed out, Then when I restarted it, it threw this error and wouldn't start.

http://pastebin.com/0gkTQjmc

**Comment by thegimliboy** [comment]
I got no idea, and I am not that good with js. But you may try to start it as root. (And copy your configurations from /home/pi/.homebridge to /root/). Maybe it helps. Also you could try to start it with -D and look if it gives out a better error. Have a nice day.

**Comment by maxtheeverything7** [comment]
Tried -D nothing different happened

**Comment by maxtheeverything7** [comment]
Tried the root thing didnt work either

**Comment by maxtheeverything7** [comment]
Ok i seemed to have fixed it by reinstalling homebridge

**Comment by lindskogen** [comment]
For future reference and debugging; `Error: listen EADDRINUSE` means that you have some other process running at the same port, most likely another instance of homebridge :)

**Comment by maxtheeverything7** [comment]
ok thankyou
