### ISSUE TITLE
No response

### ISSUE THREAD

**Issue by olliegg123** [nfarina/homebridge#775]
No response from any device on network with various plugins and accessories. Running on an RPi 2 with Node 4.0.0. The accessories appear, but nothing else.

**Comment by edgr-sanchez** [comment]
I'm experiencing the same issue... I'm going to try updating home bridge, rebooting the pi, etc. 

It just started happening though, all my 14 devices show as No Response in the Apple Home app, including the Homebridge itself.

**Comment by nrobinson2000** [comment]
I setup Homebrdge on my RPi 3 today and it is working great.  I would recommend using the latest version of Node.
```
curl deb.nodesource.com/setup_6.x | sudo bash
sudo apt-get install nodejs
```
