### ISSUE TITLE
Z-Wave thermostat

### ISSUE THREAD

**Issue by flynhawaiian** [nfarina/homebridge#78]
Is there anyway to get a wave thermostat working?  I'm running homebridge on my pi2 running through smart things.  I'm wondering if it would be possible to have Siri set the temperature or turn on and off the thermostat.  I'm guessing a Js needs to be written for it but I have no idea. any thoughts would be cool!

**Comment by flynhawaiian** [comment]
Sorry it was supposed to be zwave

**Comment by nfarina** [comment]
Hi, I'm not familiar with SmartThings but @jnewland added support for it originally so perhaps he can chime in here.

**Comment by flynhawaiian** [comment]
So the support for the thermostat is in the coding itself already?  Any idea which file it may be in so I can take a look at it.  I might be able to figure it out, but any help is really appreciated.

**Comment by flynhawaiian** [comment]
Okay it looks like the smartthings.js needs to be changed to add some code regarding the thermostat.  Looking at the nest.JS it seems like the basic for setting the temp would be:

But theres a function that would also be needed from the looks of the coding.

{
                cType: types.CURRENT_TEMPERATURE_CTYPE,
                onUpdate: null,
                onRead: function(callback) {
                    that.getCurrentTemperature(function(currentTemperature){
                        callback(currentTemperature);
                    });
                },
                perms: ["pr","ev"],
                format: "int",
                initialValue: 20,
                supportEvents: false,
                supportBonjour: false,
                manfDescription: "Current Temperature",
                unit: "fahrenheit"
            },
perms: ["pr","ev"],
                format: "int",
                initialValue: 20,
                supportEvents: false,
                supportBonjour: false,
                manfDescription: "Current Temperature",
                unit: "fahrenheit"
            },{
                cType: types.TARGET_TEMPERATURE_CTYPE,
                onUpdate: function(value) {
                    that.setTargetTemperature(value);
                },
                onRead: function(callback) {
                    that.getTargetTemperature(function(targetTemperature){
                        callback(targetTemperature);
                    });
                }

**Comment by tommyd75** [comment]
OK, so I'm trying to get a thermostat working on here, and I had it working before with the Thermostat_accessory.js  type of files on the HAP-NodeJS but I can't seem to get it working here. I've looked at the Nest platform file and I see how it's working but I'm trying to take out all the nest related stuff. The Nest file runs but them crashes because it tries to log into the website.
I removed some of the login info but that didn't help, I keep getting errors on other things, can anyone steer me in the right direction?

My old file looked like this.

// HomeKit types required
var types = require("./types.js")
var exports = module.exports = {};
var request = require("request");


var execute = function(accessory,characteristic,value){ console.log("executed accessory: " + accessory + ", and characteristic: " + characteristic + ", with value: " +  value + "."); }

exports.accessory = {
  displayName: "Living Room Thermostat",
  username: "CB:1E:BC:5D:6E:FC",  
  pincode: "031-45-154",
  services: [{
    sType: types.ACCESSORY_INFORMATION_STYPE, 
    characteristics: [{
    	cType: types.NAME_CTYPE, 
    	onUpdate: null,
    	perms: ["pr"],
		format: "string",
		initialValue: "Thermostat 1",
		supportEvents: false,
		supportBonjour: false,
		manfDescription: "Bla",
		designedMaxLength: 255    
    },{
    	cType: types.MANUFACTURER_CTYPE, 
    	onUpdate: null,
    	perms: ["pr"],
		format: "string",
		initialValue: "Oltica",
		supportEvents: false,
		supportBonjour: false,
		manfDescription: "Bla",
		designedMaxLength: 255    
    },{
    	cType: types.MODEL_CTYPE,
    	onUpdate: null,
    	perms: ["pr"],
		format: "string",
		initialValue: "Rev-1",
		supportEvents: false,
		supportBonjour: false,
		manfDescription: "Bla",
		designedMaxLength: 255    
    },{
    	cType: types.SERIAL_NUMBER_CTYPE, 
    	onUpdate: null,
    	perms: ["pr"],
		format: "string",
		initialValue: "A1S2NASF88EW",
		supportEvents: false,
		supportBonjour: false,
		manfDescription: "Bla",
		designedMaxLength: 255    
    },{
    	cType: types.IDENTIFY_CTYPE, 
    	onUpdate: null,
    	perms: ["pw"],
		format: "bool",
		initialValue: false,
		supportEvents: false,
		supportBonjour: false,
		manfDescription: "Identify Accessory",
		designedMaxLength: 1    
    }]
  },{
    sType: types.THERMOSTAT_STYPE, 
    characteristics: [{
    	cType: types.NAME_CTYPE,
    	onUpdate: null,
    	perms: ["pr"],
		format: "string",
		initialValue: "Thermostat Control",
		supportEvents: false,
		supportBonjour: false,
		manfDescription: "Bla",
		designedMaxLength: 255   
    },{
    	cType: types.CURRENTHEATINGCOOLING_CTYPE,
    	onUpdate: function(value) { console.log("Change:",value); execute("Thermostat", "Current HC", value); },
    	perms: ["pr","ev"],
		format: "int",
		initialValue: 0,
		supportEvents: false,
		supportBonjour: false,
		manfDescription: "Current Mode",
		designedMaxLength: 1,
		designedMinValue: 0,
		designedMaxValue: 2,
		designedMinStep: 1,    
    },{
    	cType: types.TARGETHEATINGCOOLING_CTYPE,
    	onUpdate: function(value) { 
   
    target = "0";
    if (value === 0) {target = "off%20mode";};
    if (value === 1) {target = "heat%20mode";};
    if (value === 2) {target = "cool%20mode";};
    if (value === 3) {target = "auto%20mode";};

    
    request("http://192.168.1.100/tenHsServer/tenHsServer.aspx?t=ab&f=RunEvent&d=set%20the%20thermostat%20to%20"+target);
},


    	perms: ["pw","pr","ev"],
		format: "int",
		initialValue: 0,
		supportEvents: false,
		supportBonjour: false,
		manfDescription: "Target Mode",
		designedMinValue: 0,
		designedMaxValue: 3,
		designedMinStep: 1,
    },{
    	cType: types.CURRENT_TEMPERATURE_CTYPE,
    	onUpdate: function(value) { console.log("Change:",value); execute("Thermostat", "Current Temperature", value); },
    	perms: ["pr","ev"],
		format: "int",
		initialValue: 18.333,
		supportEvents: false,
		supportBonjour: false,
		manfDescription: "Current Temperature",
		unit: "celsius"
    },{
    	cType: types.TARGET_TEMPERATURE_CTYPE,
    	onUpdate: function(value) { 
   
    target = "18.333";
    if (value === 18.333) {target = "65";};
    if (value === 18.888) {target = "66";};
    if (value === 19.443) {target = "67";};
    if (value === 19.998) {target = "68";};
    if (value === 20.558) {target = "69";};
    if (value === 21.113) {target = "70";};
    if (value === 21.668) {target = "71";};
    if (value === 22.223) {target = "72";};
    if (value === 22.778) {target = "73";};
    if (value === 23.333) {target = "74";};
    if (value === 23.888) {target = "75";};

    
    request("http://192.168.1.100/tenHsServer/tenHsServer.aspx?t=ab&f=RunEvent&d=Set%20temp%20to%20"+target);
},
        perms: ["pw","pr","ev"],
		format: "int",
		initialValue: 18.333,
		supportEvents: false,
		supportBonjour: false,
		manfDescription: "Target Temperature",
		designedMinValue: 18.333,
		designedMaxValue: 23.888,
		designedMinStep: 0.005,
		unit: "celsius"
    },{    	cType: types.TEMPERATURE_UNITS_CTYPE,
    	onUpdate: function(value) { console.log("Change:",value); execute("Thermostat", "Unit", value); },
    	perms: ["pr","ev"],
		format: "int",
		initialValue: 0,
		supportEvents: false,
		supportBonjour: false,
		manfDescription: "Unit",
    }]
  

}]
}
