### ISSUE TITLE
How to create a custom accessory ?

### ISSUE THREAD

**Issue by ghost** [nfarina/homebridge#784]
Hi

Sorry if this question has been probably asked before.

I would like to create a specific type of accessory for homebridge.

Most of the time accessories like temperature, humidity, others are used but in my case I would like
to implement an accessory to measure water acidity or water pressure.

I understood we could create some "custom" accessory with HomeKit and in this case Siri will not be useable if I am not wrong.

Is there any similar class in homebridge to do this?

Typically in case of pressure, do you think we could have Siri telling us "the pressure is xx mbars" ?

Best Regards
Marco

**Comment by lino-silva** [comment]
I'm actually curious about this as well. Basic sensors (like distance) aren't included in Siri's defaults, and it would be great if someone had any knowledge of its inner workings and whether the proposition above would work.

**Comment by MastroPino** [comment]
I'm actually try to develop a new configuration for Xiaomi Yeelight RGBA, an how to will be appreciated 👍

**Comment by Marco-ST** [comment]
Hello,

What I can tell you up to now, 

To define a sensor / light or other kind of devices, we device a HMService in Homekit framework.

To specify this kind of so called "service", there are two main params : 

The type of the accessory.
The characteristics of the service that is an array of individual characteristics types.

In HMService class.
There are these variables :
...
var accessory: HMAccessory?
...
var characteristics: [HMCharacteristic]
...

1/ inside HMAccessory, you could find a "categoryType" that is a string from the following types 

let HMAccessoryCategoryTypeOther: String     <------------
let HMAccessoryCategoryTypeBridge: String
let HMAccessoryCategoryTypeDoor: String
let HMAccessoryCategoryTypeDoorLock: String
let HMAccessoryCategoryTypeFan: String
let HMAccessoryCategoryTypeGarageDoorOpener: String
let HMAccessoryCategoryTypeIPCamera: String
let HMAccessoryCategoryTypeLightbulb: String
let HMAccessoryCategoryTypeOutlet: String
let HMAccessoryCategoryTypeProgrammableSwitch: String
let HMAccessoryCategoryTypeRangeExtender: String
let HMAccessoryCategoryTypeSecuritySystem: String
let HMAccessoryCategoryTypeSensor: String <---------
let HMAccessoryCategoryTypeSwitch: String
let HMAccessoryCategoryTypeThermostat: String
let HMAccessoryCategoryTypeVideoDoorbell: String
let HMAccessoryCategoryTypeWindow: String
let HMAccessoryCategoryTypeWindowCovering: String

As you can see there is a "TypeOther" and a "TypeSensor" that as this stage does not define what kind of accessory it is or which kind of sensor it is....

2/ Then inside HMCharacteristic, the characteristics type provides more infos on the service :

let HMCharacteristicTypePowerState: String
let HMCharacteristicTypeHue: String
let HMCharacteristicTypeSaturation: String
let HMCharacteristicTypeBrightness: String
let HMCharacteristicTypeTemperatureUnits: String
let HMCharacteristicTypeCurrentTemperature: String
let HMCharacteristicTypeTargetTemperature: String
let HMCharacteristicTypeCurrentHeatingCooling: String
let HMCharacteristicTypeTargetHeatingCooling: String
let HMCharacteristicTypeCoolingThreshold: String
let HMCharacteristicTypeHeatingThreshold: String
let HMCharacteristicTypeCurrentRelativeHumidity: String
let HMCharacteristicTypeTargetRelativeHumidity: String
let HMCharacteristicTypeCurrentDoorState: String
let HMCharacteristicTypeTargetDoorState: String
let HMCharacteristicTypeObstructionDetected: String
let HMCharacteristicTypeName: String
let HMCharacteristicTypeManufacturer: String
let HMCharacteristicTypeModel: String
let HMCharacteristicTypeSerialNumber: String
let HMCharacteristicTypeIdentify: String
let HMCharacteristicTypeRotationDirection: String
let HMCharacteristicTypeRotationSpeed: String
let HMCharacteristicTypeOutletInUse: String
let HMCharacteristicTypeVersion: String
let HMCharacteristicTypeLogs: String
let HMCharacteristicTypeAudioFeedback: String
let HMCharacteristicTypeAdminOnlyAccess: String
let HMCharacteristicTypeSecuritySystemAlarmType: String
let HMCharacteristicTypeMotionDetected: String
let HMCharacteristicTypeCurrentLockMechanismState: String
let HMCharacteristicTypeTargetLockMechanismState: String
let HMCharacteristicTypeLockMechanismLastKnownAction: String
let HMCharacteristicTypeLockManagementControlPoint: String
let HMCharacteristicTypeLockManagementAutoSecureTimeout: String
let HMCharacteristicTypeAirParticulateDensity: String
let HMCharacteristicTypeAirParticulateSize: String
let HMCharacteristicTypeAirQuality: String
let HMCharacteristicTypeBatteryLevel: String
let HMCharacteristicTypeCarbonDioxideDetected: String
let HMCharacteristicTypeCarbonDioxideLevel: String
let HMCharacteristicTypeCarbonDioxidePeakLevel: String
let HMCharacteristicTypeCarbonMonoxideDetected: String
let HMCharacteristicTypeCarbonMonoxideLevel: String
let HMCharacteristicTypeCarbonMonoxidePeakLevel: String
let HMCharacteristicTypeChargingState: String
let HMCharacteristicTypeContactState: String
let HMCharacteristicTypeCurrentHorizontalTilt: String
let HMCharacteristicTypeCurrentLightLevel: String
let HMCharacteristicTypeCurrentPosition: String
let HMCharacteristicTypeCurrentSecuritySystemState: String
let HMCharacteristicTypeCurrentVerticalTilt: String
let HMCharacteristicTypeFirmwareVersion: String
let HMCharacteristicTypeHardwareVersion: String
let HMCharacteristicTypeHoldPosition: String
let HMCharacteristicTypeInputEvent: String
let HMCharacteristicTypeLeakDetected: String
let HMCharacteristicTypeOccupancyDetected: String
let HMCharacteristicTypeOutputState: String
let HMCharacteristicTypePositionState: String
let HMCharacteristicTypeSmokeDetected: String
let HMCharacteristicTypeSoftwareVersion: String
let HMCharacteristicTypeStatusActive: String
let HMCharacteristicTypeStatusFault: String
let HMCharacteristicTypeStatusJammed: String
let HMCharacteristicTypeStatusLowBattery: String
let HMCharacteristicTypeStatusTampered: String
let HMCharacteristicTypeTargetHorizontalTilt: String
let HMCharacteristicTypeTargetSecuritySystemState: String
let HMCharacteristicTypeTargetPosition: String
let HMCharacteristicTypeTargetVerticalTilt: String

As you can see here, characteristics seems to be limited to a certain number set of values... No other type and extended type here.....

What is not clear yet, we have a TypeOther / TypeSensor in accessory type, so why not having a HMCharacteristicTypeOther where we could define the sensor unity returned for example... as strings....

To be continued or not.... :)

**Comment by RienduPre** [comment]
Tried a lot of things, but cannot get a custom sensor or device working :-(

**Comment by lagunacomputer** [comment]
https://github.com/lagunacomputer/homebridge-CurrentAmbientLightLevel

i made a light sensor.  you can just edit the code.

your possibilities are here: 
https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js
