### ISSUE TITLE
Fatal Error C1083, Windows Installation

### ISSUE THREAD

**Issue by TheChallinor** [nfarina/homebridge#787]
Tried for many many hours tonight and now totally stuck, any help is appreciated as I really want to get this running on my Windows file server ( Win 10 64bit ).

See screenshot below. 

<img width="1825" alt="screenshot 2016-09-22 02 04 10" src="https://cloud.githubusercontent.com/assets/22248204/18734109/f58c7ae6-8068-11e6-8257-d15202619564.png">

**Comment by jocamero** [comment]
Any luck getting this resolved?

**Comment by TheChallinor** [comment]
I messed around for a LONG time, googling loads and ending up on visual studio support pages. Eventually I got it sorted, running it on Windows is a PITA and it doesn't seem to be all that reliable as well to be honest.

I ran it for a limited time on one of my Mac's and it seemed much better.
