### ISSUE TITLE
HomeBridge totally unresponsive since MacOS Sierra update

### ISSUE THREAD

**Issue by JangoBritt** [nfarina/homebridge#789]
Hi all,

I've tried clearing the persist folder, rebooting numerous times, removing the homebridge from my iPhone, but I still can't get homebridge to respond at all.

In fact now, I can't get the server to complete the reboot at all.

I get the full logs, but it never gets round to telling me my homebridge connection code any more.

 This makes me think that the program is hanging somewhere, but I'm still receiving regular updates from the particle script, and the HomeBridge-Controller is successfully connected to the app.

I can't add the homebridge back to my iPhone at all any more :-(

**Comment by JangoBritt** [comment]
Log dump
`0:00:00 - [9/22/2016, 7:37:25 PM] shutting down servers...
19:37:27 - | * * * * * * * * * *  Start of log * * * * * * * * * * |
00:00:00 - [9/22/2016, 7:37:26 PM] Loaded plugin: homebridge-controllerlink
00:00:00 - [9/22/2016, 7:37:26 PM] Registering platform 'homebridge-controllerlink.HomeBridgeControllerLink'
00:00:00 - [9/22/2016, 7:37:26 PM] ---
00:00:00 - [9/22/2016, 7:37:27 PM] Loaded plugin: homebridge-harmonyhub
00:00:00 - [9/22/2016, 7:37:27 PM] Registering platform 'homebridge-harmonyhub.HarmonyHub'
00:00:00 - [9/22/2016, 7:37:27 PM] ---
00:00:00 - [9/22/2016, 7:37:27 PM] Loaded plugin: homebridge-ifttt
00:00:00 - [9/22/2016, 7:37:27 PM] Registering platform 'homebridge-ifttt.IFTTT'
00:00:00 - [9/22/2016, 7:37:27 PM] Loaded plugin: homebridge-lightwaverf
00:00:00 - [9/22/2016, 7:37:27 PM] Registering platform 'homebridge-lightwaverf.LightWaveRF'
00:00:00 - [9/22/2016, 7:37:27 PM] Loaded plugin: homebridge-particle
00:00:00 - [9/22/2016, 7:37:27 PM] Registering platform 'homebridge-particle.Particle'
00:00:00 - [9/22/2016, 7:37:27 PM] Loaded plugin: homebridge-readablehttp
00:00:00 - [9/22/2016, 7:37:27 PM] Registering accessory 'homebridge-readablehttp.Http'
00:00:00 - [9/22/2016, 7:37:27 PM] Loaded plugin: homebridge-wunderground
00:00:00 - [9/22/2016, 7:37:27 PM] Registering accessory 'homebridge-wunderground.WUNDERGROUND'
00:00:00 - [9/22/2016, 7:37:27 PM] Loaded config.json with 2 accessories and 3 platforms.
00:00:00 - [9/22/2016, 7:37:27 PM] Loading 3 platforms...
00:00:00 - [9/22/2016, 7:37:27 PM] Initializing HomeBridgeControllerLink platform...
00:00:00 - [9/22/2016, 7:37:27 PM] [Living Room Harmony Hub] Initializing HarmonyHub platform...
00:00:00 - [9/22/2016, 7:37:27 PM] [Living Room Harmony Hub] Searching for Logitech Harmony remote hubs...
00:00:00 - [9/22/2016, 7:37:27 PM] [LightWaveRF] Initializing LightWaveRF platform...
00:00:00 - [9/22/2016, 7:37:27 PM] [LightWaveRF] LightWaveRF Platform Plugin Version 0.0.6
00:00:00 - [9/22/2016, 7:37:27 PM] [LightWaveRF] Fetching LightWaveRF switches and dimmers...
19:37:27 - No email or pin specified. The server configuration (rooms, devices, etc.) cannot be obtained
19:37:27 - device =
19:37:27 - { roomId: 3,
  roomName: 'Thomas',
  deviceId: 3,
  deviceName: 'Light',
  deviceType: 'D' }
19:37:27 - { roomId: 3,
  roomName: 'Thomas',
  deviceId: 1,
  deviceName: 'Monitor',
  deviceType: 'S' }
19:37:27 - { roomId: 3,
  roomName: 'Thomas',
  deviceId: 2,
  deviceName: 'Fan',
  deviceType: 'S' }
19:37:27 - { roomId: 1,
  roomName: 'Office',
  deviceId: 1,
  deviceName: 'LEGO Street',
  deviceType: 'L' }
19:37:27 - { roomId: 1,
  roomName: 'Office',
  deviceId: 3,
  deviceName: 'Light',
  deviceType: 'D' }
19:37:27 - { roomId: 1,
  roomName: 'Office',
  deviceId: 2,
  deviceName: 'Display',
  deviceType: 'L' }
19:37:27 - { roomId: 2,
  roomName: 'Nursery',
  deviceId: 1,
  deviceName: 'Light',
  deviceType: 'D' }
00:00:00 - [9/22/2016, 7:37:27 PM] [LightWaveRF] Initializing platform accessory 'Thomas Light'...
00:00:00 - [9/22/2016, 7:37:27 PM] [LightWaveRF] Initializing platform accessory 'Thomas Monitor'...
00:00:00 - [9/22/2016, 7:37:27 PM] [LightWaveRF] Initializing platform accessory 'Thomas Fan'...
00:00:00 - [9/22/2016, 7:37:27 PM] [LightWaveRF] Initializing platform accessory 'Office LEGO Street'...
00:00:00 - [9/22/2016, 7:37:27 PM] [LightWaveRF] Initializing platform accessory 'Office Light'...
00:00:00 - [9/22/2016, 7:37:27 PM] [LightWaveRF] Initializing platform accessory 'Office Display'...
00:00:00 - [9/22/2016, 7:37:27 PM] [LightWaveRF] Initializing platform accessory 'Nursery Light'...
00:00:00 - [9/22/2016, 7:37:27 PM] Loading 2 accessories...
00:00:00 - [9/22/2016, 7:37:27 PM] [Outside] Initializing WUNDERGROUND accessory...
00:00:00 - [9/22/2016, 7:37:27 PM] [Thomas Lullabies] Initializing ApplescriptFileLightbulb accessory...
19:37:27 - Receiver socket listening 0.0.0.0:9761
00:00:00 - [9/22/2016, 7:37:28 PM] Started HomeBridgeControllerLink on port 51828
`

and there it stays

**Comment by KhaosT** [comment]
Can you see the homebridge via Bonjour Browser on your mac?

**Comment by JangoBritt** [comment]
Yes, and on the iPhone. 

HomeBridge._hbctrllink._tcp.local.

MacMini.local:51828
192.168.1.19:51828
fe80::8f5:6f40:8822:5924%en0:51828

Id = CC223DE3CE3D
LinkVersion = 0.7.0
Name = HomeBridge
OS = 1
Version = 0.3.4

**Comment by KhaosT** [comment]
@JangoBritt not this one, the one for _hap._tcp

**Comment by JangoBritt** [comment]
Hmm. I see that one on the Mac, but not on the iPhone. 

I guess that means I've got a bonjour problem? Annoyingly, I think that happens regularly for me. I have a BT Home Hub 5, which so many people report as being bad with bonjour.

**Comment by KhaosT** [comment]
@JangoBritt yeah, if you cannot see the service on your iOS device then there may have something wrong with Bonjour... Sometime try reboot your computer and router may resolve the problem...

**Comment by JangoBritt** [comment]
sorry. I was wrong.. I don't see _hap._tcp on the Mac any more.

Also, I'm still hung up on the fact that Homebridge hasn't got as far as publishing my HomeKit PIN yet???

**Comment by KhaosT** [comment]
@JangoBritt 🤔 can you try disable all plugins and then run homebridge so we can see if one of the plugin blocked the process?

**Comment by JangoBritt** [comment]
*sigh* yep. that did it.

Infuriatingly enough, I've re-enabled all the plugins, and it's now working again.

I wish this system was more robust. I can't wait for my LightWaveRF and Harmony Hub to get HomeKit. lol
