### ISSUE TITLE
Assigning Accessory to a Room?

### ISSUE THREAD

**Issue by dsully** [nfarina/homebridge#792]
Is there any way in a plugin to assign an accessory to a Room? Optionally creating a Room on the fly?

Background: Lutron's RadioRa2 system has an XML file that describes the layout. I'm working on extracting that information into JSON for the config file. It'd be great to be able to use the Room information that already exists, so lights and shades can show up in their appropriate room in the Home app.

**Comment by KhaosT** [comment]
Nope, HomeKit on iOS owns room information. Accessory have no way to modify that.

**Comment by dsully** [comment]
Bummer. Thanks.

**Comment by justme-1968** [comment]
it would be nicht to have a iOS homebridge companion app. this app could use some sort of private communication channel with homebridge to allow accessing rooms and other homekit configuration that is not available with the homekit protokoll. it could even allow backup and restore of the homekit configuration.

**Comment by BruceBuckland** [comment]
the homekit framework documents the addRoom func so you should be able to make an app that takes RadioRa2 config info and creates rooms.  Have you broken out the RadioRa2 room table yet?
