### ISSUE TITLE
Multiple Subnets/Network Interfaces

### ISSUE THREAD

**Issue by dezza69** [nfarina/homebridge#798]
Hi,

I'm wondering if HomeBridge is capable of spanning multiple subnets/network cards, or does it only bind to one address??

I have a load (30+) WeMo devices on their own VLan, which are not accessible via HomeBridge although all the routes work correctly and the WeMo app functions fine.

Thanks,

Dezza

**Comment by dkrizic** [comment]
You can have multiple networks, but a mDNS responder between those networks, for example Avahi.
