### ISSUE TITLE
Homebridge starts with default settings and won't load config file

### ISSUE THREAD

**Issue by geberr** [nfarina/homebridge#800]
Running Homebridge 0.3.4 on OS X El Capitan 10.11.6.
I have installed a plugin and created a config.json file in the homebridge folder (same folder where I found config-sample.json) but for some reason it starts with the default settings. 

===
[9/25/2016, 1:30:32 PM] Loaded plugin: homebridge-soundtouch
[9/25/2016, 1:30:32 PM] Registering accessory 'homebridge-soundtouch.SoundTouch'
[9/25/2016, 1:30:32 PM] ---
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:                       
[9/25/2016, 1:30:32 PM] Homebridge is running on port 51826.
===

If I delete the config file, I get no errors. 
Home bridge works and I can find it in the home app, but I see no accessory...

Am I missing something here?

**Comment by geberr** [comment]
The config file I am editing is in: /usr/local/lib/node_modules/homebridge

**Comment by rmarinho** [comment]
@geberr you need to edit the one in ~/.homebridge/config.json

**Comment by geberr** [comment]
yes, of course, thanks, worked!
