### ISSUE TITLE
homebridge fails to install macos sierra

### ISSUE THREAD

**Issue by andybno1** [nfarina/homebridge#804]
trying to install homebridge on macos sierra it fails can anyone help?
[npm-debug.txt](https://github.com/nfarina/homebridge/files/494074/npm-debug.txt)

**Comment by kondratk** [comment]
Same here 
[npm-debug.txt](https://github.com/nfarina/homebridge/files/494184/npm-debug.txt)

**Comment by KhaosT** [comment]
@kondratk can you post the the log from terminal... the npm-debug seems omit the compiling error...

**Comment by kondratk** [comment]
@KhaosT 
Here it is:

`sudo npm install -g --unsafe-perm homebridge
(node:41876) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:41876) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:41876) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:41876) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:41876) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
/usr/local/bin/homebridge -> /usr/local/lib/node_modules/homebridge/bin/homebridge

> mdns@2.3.3 install /usr/local/lib/node_modules/homebridge/node_modules/mdns
> node-gyp rebuild

  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_browse.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_enumerate_domains.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_get_addr_info.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_process_result.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_ref.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_ref_deallocate.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_ref_sock_fd.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_register.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_resolve.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_update_record.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/mdns_utils.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/network_interface.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/socket_watcher.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_ref.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_create.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_deallocate.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_set_value.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_get_length.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_buffer_to_object.o
  SOLINK_MODULE(target) Release/dns_sd_bindings.node
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9

> curve25519-n@1.1.0 install /usr/local/lib/node_modules/homebridge/node_modules/curve25519-n
> node-gyp rebuild

  CXX(target) Release/obj.target/curve/node_curve.o
  SOLINK_MODULE(target) Release/curve.node
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9

> ed25519@0.0.4 install /usr/local/lib/node_modules/homebridge/node_modules/ed25519
> node-gyp rebuild

  CC(target) Release/obj.target/ed25519/src/ed25519/keypair.o
  CC(target) Release/obj.target/ed25519/src/ed25519/sign.o
  CC(target) Release/obj.target/ed25519/src/ed25519/open.o
  CC(target) Release/obj.target/ed25519/src/ed25519/crypto_verify_32.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_double_scalarmult.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_frombytes.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_scalarmult_base.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_precomp_0.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_p2_0.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_p2_dbl.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_p3_0.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_p3_dbl.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_p3_to_p2.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_p3_to_cached.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_p3_tobytes.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_madd.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_add.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_msub.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_sub.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_p1p1_to_p3.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_p1p1_to_p2.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_tobytes.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_0.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_1.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_cmov.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_copy.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_neg.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_add.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_sub.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_mul.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_sq.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_sq2.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_invert.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_tobytes.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_isnegative.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_isnonzero.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_frombytes.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_pow22523.o
  CC(target) Release/obj.target/ed25519/src/ed25519/sc_reduce.o
  CC(target) Release/obj.target/ed25519/src/ed25519/sc_muladd.o
  CXX(target) Release/obj.target/ed25519/src/ed25519.o
  SOLINK_MODULE(target) Release/ed25519.node
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9

> bignum@0.12.5 install /usr/local/lib/node_modules/homebridge/node_modules/bignum
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! UNCAUGHT EXCEPTION
node-pre-gyp ERR! stack TypeError: Cannot read property 'uid' of undefined
node-pre-gyp ERR! stack     at /usr/local/lib/node_modules/homebridge/node_modules/graceful-fs/polyfills.js:264:16
node-pre-gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
node-pre-gyp ERR! System Darwin 16.0.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/6.6.0/bin/node" "/usr/local/lib/node_modules/homebridge/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/homebridge/node_modules/bignum
node-pre-gyp ERR! node -v v6.6.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.30
node-pre-gyp ERR! This is a bug in `node-pre-gyp`.
node-pre-gyp ERR! Try to update node-pre-gyp and file an issue if it does not help:
node-pre-gyp ERR!     <https://github.com/mapbox/node-pre-gyp/issues>
/usr/local/lib
└── (empty)

npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/Cellar/node/6.6.0/bin/node" "/usr/local/bin/npm" "install" "-g" "--unsafe-perm" "homebridge"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.7
npm ERR! code ELIFECYCLE

npm ERR! bignum@0.12.5 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the bignum@0.12.5 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bignum package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bignum
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bignum
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kondratk/npm-debug.log
npm ERR! code 1`

**Comment by kolyanok** [comment]
Same problem :|

**Comment by andybno1** [comment]
here is my terminal log also:

> sudo npm install -g homebridge
> Password:
> -
> > curve25519-n@1.1.0 install /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/curve25519-n
> > node-gyp rebuild
> 
> shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
> sh: node-gyp: command not found
>  
> > ed25519@0.0.4 install /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/ed25519
> > node-gyp rebuild
> 
> shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
> sh: node-gyp: command not found
>  
> > mdns@2.3.3 install /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/mdns
> > node-gyp rebuild
> 
> shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
> sh: node-gyp: command not found
> \
> > bignum@0.12.5 install /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/srp/node_modules/bignum
> > node-pre-gyp install --fallback-to-build
> 
> shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
> sh: node-pre-gyp: command not found
> npm ERR! Darwin 16.1.0
> npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "homebridge"
> npm ERR! node v4.5.0
> npm ERR! npm  v2.15.9
> npm ERR! file sh
> npm ERR! code ELIFECYCLE
> npm ERR! errno ENOENT
> npm ERR! syscall spawn
> 
> npm ERR! curve25519-n@1.1.0 install: `node-gyp rebuild`
> npm ERR! spawn ENOENT
> npm ERR! 
> npm ERR! Failed at the curve25519-n@1.1.0 install script 'node-gyp rebuild'.
> npm ERR! This is most likely a problem with the curve25519-n package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-gyp rebuild
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs curve25519-n
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR! 
> npm ERR!     npm owner ls curve25519-n
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /Users/npm-debug.log

**Comment by KhaosT** [comment]
Oops someone breaks [a package](https://github.com/isaacs/node-graceful-fs/issues/89) we bignum depends on...

**Comment by KhaosT** [comment]
Okay try again now ... it should be fixed.

**Comment by kondratk** [comment]
@KhaosT Problem solved, thx ;)

**Comment by kolyanok** [comment]
Yes, it's working fine now, Thanks!

**Comment by andybno1** [comment]
any ideas what is going on with mine?

**Comment by KhaosT** [comment]
@andybno1 can you post log from terminal instead of the npm-debug file... thanks

**Comment by andybno1** [comment]
I have a couple posts up

**Comment by KhaosT** [comment]
oops sorry I missed that ... 😅

**Comment by andybno1** [comment]
would you like to borrow my glasses? lol

**Comment by andybno1** [comment]
I used the lts installer for mac I'll try the stable 6.6.0 but I still had issues with that version too

**Comment by andybno1** [comment]
ok then 6.6.0 installed and yeh still a no go:

> > sudo npm install -g homebridge
> Password:
> /usr/local/bin/homebridge -> /usr/local/lib/node_modules/homebridge/bin/homebridge
> 
> > mdns@2.3.3 install /usr/local/lib/node_modules/homebridge/node_modules/mdns
> > node-gyp rebuild
> 
> shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
> sh: node-gyp: command not found
> /usr/local/lib
> └── (empty)
> 
> npm ERR! Darwin 16.1.0
> npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "homebridge"
> npm ERR! node v6.6.0
> npm ERR! npm  v3.10.3
> npm ERR! file sh
> npm ERR! code ELIFECYCLE
> npm ERR! errno ENOENT
> npm ERR! syscall spawn
> 
> npm ERR! mdns@2.3.3 install: `node-gyp rebuild`
> npm ERR! spawn ENOENT
> npm ERR! 
> npm ERR! Failed at the mdns@2.3.3 install script 'node-gyp rebuild'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the mdns package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-gyp rebuild
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs mdns
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls mdns
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /Users/andyb/npm-debug.log
> npm ERR! code 1

**Comment by KhaosT** [comment]
```
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
sh: node-gyp: command not found
```
This two lines... not really sure why. If there is no important package under ``/usr/local/lib/node_modules/``, just nuke the folder and try again I guess?

**Comment by andybno1** [comment]
deleted the folder now says npm: command not found guess it was important I have no idea what it going on

**Comment by KhaosT** [comment]
@andybno1 and now if you reinstall the ``node-v6.6.0.pkg``, does the error still persist?

**Comment by andybno1** [comment]
```

> sudo npm install -g homebridge
> /usr/local/bin/homebridge -> /usr/local/lib/node_modules/homebridge/bin/homebridge
> 
> > mdns@2.3.3 install /usr/local/lib/node_modules/homebridge/node_modules/mdns
> > node-gyp rebuild
> 
> shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
> sh: node-gyp: command not found
> /usr/local/lib
> └── (empty)
> 
> npm ERR! Darwin 16.1.0
> npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "homebridge"
> npm ERR! node v6.6.0
> npm ERR! npm  v3.10.3
> npm ERR! file sh
> npm ERR! code ELIFECYCLE
> npm ERR! errno ENOENT
> npm ERR! syscall spawn
> 
> npm ERR! mdns@2.3.3 install: `node-gyp rebuild`
> npm ERR! spawn ENOENT
> npm ERR! 
> npm ERR! Failed at the mdns@2.3.3 install script 'node-gyp rebuild'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the mdns package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-gyp rebuild
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs mdns
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls mdns
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /Users/andyb/npm-debug.log
> npm ERR! code 1

```

**Comment by KhaosT** [comment]
try ``sudo npm install -g --unsafe-perm homebridge`` ? from [here](http://superuser.com/questions/817192/getting-shell-init-error-retrieving-current-directory-getcwd-cannot-access-pa)

**Comment by andybno1** [comment]
looks like that has worked thanks alot

**Comment by KhaosT** [comment]
:)
