### ISSUE TITLE
brightness setting also turns device on - race ensues

### ISSUE THREAD

**Issue by b3nj1** [nfarina/homebridge#807]
This is like issue #240, but also happens with http plugin. When requesting a brightness setting for a lightbulb, the power state on command is also activated. This results in a race between the brightness and power commands. The resolution of the race is random, so sometimes the light is full bright or sometimes it is the requested brightness. I've tried to hunt around the source of the http plugin as well as homebridge, but wasn't able to find where this fork occurs.

Sep 26 19:28:41 raspberrypi homebridge[32763]: [9/26/2016, 7:28:41 PM] [Sofa] Setting brightness to 15
Sep 26 19:28:41 raspberrypi homebridge[32763]: [9/26/2016, 7:28:41 PM] [Sofa] Setting power state to on
Sep 26 19:28:43 raspberrypi homebridge[32763]: [9/26/2016, 7:28:43 PM] [Sofa] HTTP set power function succeeded!
Sep 26 19:28:43 raspberrypi homebridge[32763]: [9/26/2016, 7:28:43 PM] [Sofa] HTTP brightness function succeeded!

Thanks,
Benjamin

**Comment by justme-1968** [comment]
this is not the same as #240. it looks like current homekit versions explicitly send an on command before brightness changes. i think this is something apple has to fix. at least the behaviour changed fro ios9 to ios10

**Comment by stipus** [comment]
They should have changed the (unordered) set of commands to an (ordered) array.... but they didn't want to change the API, and preferred bad workarounds like this ;(

**Comment by maragelis** [comment]
To give my two cent working with mqtt and mqttLighbuld plugin i can safely say this is not the case. You can change the brightness without triggering the ON state, you just have to remove the on event in the brightness setstate.. I dont see the point in this because it makes no sense someone asking siri to change the brightness in a room and the light staying off. The samething can be said for 0% brightness, should homekit show the light ON or OFF the correct is to show it OFF. Lifx bulbs work in the same way

**Comment by justme-1968** [comment]
what is not the case?

the homekit behaviour has definitively changed from ios9 to ios10. 

the problem ist that there are lights that will switch to 100% if they get an on event if they are already on and automatically switch on if they are off an get a brightness. 

homekit should not link the two settings automatically and leave it to the device to decide.

is the on event visible when handling the brightness event? how do you remove an event from the queue?

**Comment by b3nj1** [comment]
For now, I've hacked around this by pausing 800ms before all brightness commands. Using a shorter time didn't always let the power on win the race. For a multi-light scene, there is a bit of a light show before things settle to the proper state.

**Comment by tannebil** [comment]
Similar issue using Homebridgr/OpenHAB/omnilink except it interprets the "1" passed as "power on" as a "dim to 1%" command. Had to change all my dimmers to switches and rebuild my scenes for the moment.

**Comment by randyinla** [comment]
Same issue with homeseer.js.  I have Hue lights directly connected to HomeKit and they always work with on/off/dimming Siri commands.  Haven't looked at the communication to see if Siri is sending an extra 'on' command when dimming, but I believe the Hue lights actually need it to be sent.  X10 lighting doesn't need a separate on command when dimming.  With the X10 standard LM465 Lamp Module, If the light is off, sending only a dim value turns the light on to full brightness and then dims to the value.  When HomeBridge sends the value I requested and also a value of 100, they are not always sent in the same order:  

- 100 "on" sent first, followed by the requested dim value sets my lighting to the requested value.
- Dim value sent first, followed by 100 'on' always results in full brightness.  

With one of my x10 receivers (SmartLinc Lite wall switch) it has an adjustable speed control on the switch that will fade between lighting levels.  When off, It doesn't turn itself on to full brightness like the Lamp Module when sending a dim value, it just fades up to the value.  With HomeBridge, if the 100 is sent 2nd, the light fades on to the requested value and then fades up to 100.  (with x10 Lamp Modules, the light just turns on to 100 and stays there) This definitely needs to be configurable per LightBulb type, so I guess Apple has to agree?

In the meantime, two possible HomeBridge patches could possibly fix this behavior:
1) If the current API stores the events in an unordered fashion, why not scan the unordered hash for on and dim commands and then always execute them in the following order: on first, dimming 2nd?  Add in a programmable delay between the two commands for some users/products that need to adjust it and problem solved.

2) Is there a way to block the extra 'on' event from being passed through HomeBridge to the homeseer.js shim based on an extra lightbulb parameter that HomeKit doesn't know about?  ie.set some boolean named "dimmingRequiresOnCommand" to true or false for each accessory in the config.json file.  HomeKit won't know about it or care, but HomeBridge could then block the extra 'on' event when dimming.

**Comment by randyinla** [comment]
Taking a cue from b3nj1 above, I wrapped my HomeSeer.js "setValue: -> httpRequest" in a setTimeout() of 800ms.  Now I can see in my HomeBridge log that the delayed dimming value command always fires after any 'on' command Siri sends when dimming.  First time I've been able to control dimming up/down via Siri in a logical way!  Thanks, b3nj1.

**Comment by stipus** [comment]
You should double-check that the setValue function is not used for anything else than light brightness.
If so, you should replace it with a setBrightness() function...

**Comment by randyinla** [comment]
Stipus: I didn't see where anything in HomeSeer.js was calling setValue: so I assumed it was being called directly from HomeKit via HomeBridge?  If I added a setBrightness() function to HomeSeer.js, how would HomeKit/Homebridge know to call it?  I haven't looked at any HomeKit coding practices, documents or the api directly.  Is there a way to actually implement a separate dimming function into the shim?

The way things are working now with the latest iOS 10 update, without the setValue delay in place, the on/value commands are triggered in random order.  Sometimes on first, sometimes value first.  At least by delaying the value command, I am forcing 'on' to fire first followed by the dim value, which should work for anything, no?  Best thing would be for HomeKit to sense if the on command is needed in the first place when issuing a dim command and to not send it in my case...and to also change over to an ordered Array.  Delaying the setValue call is just a temp bandaid so I can dim my lighting again.

For my setup, even though I have the JowiHue plugin for HomeSeer so I can control Hue lights via Homeseer, I connected my Hue bridge to HomeKit directly.  Siri commands work great with Hue natively.  The only dimmable things I have in my HomeSeer.js config.json file are three x10 lights, x10 motion sensors and a bunch of virtual status devices.

**Comment by stipus** [comment]
If you only control a few lights and no other accessory types, it's not going to be a problem if you delay the setValue function. Regards. Stipus

**Comment by drewcovi** [comment]
just resolved this in http://github.com/damianxd/homebridge-vera

**Really does seem like an obvious need:** provide some degree of a traceback to the original request to differentiate between a solo Characteristic.On and two requests sent with Characteristic.Brightness.

I'm not terribly surprised by the two-request behavior, but no matter what, using timeouts is a hack.

**Comment by snowdd1** [comment]
Hi @drewcovi   
Just had a look at your solution, and have some questions.

I assume Vera lights do never report a brightness back, do they? Otherwise the saved brightness in the brightness characteristic would be 0% after switching off, right?  

I also assume that Vera lights do not have a configurable switch-on brightness, which would make the extra 100% brightness commands on switching lights in Home app an annoyance, right?

Because I thought several times about how to solve that for the KNX bus system, which has above two features, and didn't really come to a solution. I simply cannot distinguish between "user switched the light on on home and didn't set the brightness" which should result in the light dimming to its predefined dimming level and only issue an ON command (currently Home app sends a 100% along , but not always); and the case "user said to Siri 'set the light to 100%'" for which a brightness value would be right, but not an ON command because that would trigger the predefined switch-on brightness in the light actuator.

**Comment by justme-1968** [comment]
i think the real fix is for apple to stopp sending two unrelated events for one action. the homekit device itself should decide if an additional on is needed. 

this is especially true if you controll devices from different manufacturers.
- hue bulbs will keep their last brightness setting if switched off and report it back
- hue living colors lights will keep their last brightness only for some time and then report 0 back
- homematic devices will go to fill brighntness if you are using on
- ...

as the to events are really completely unrelated there is no way other than the delay to handle this. even if it is a hack

**Comment by drewcovi** [comment]
@snowdd1: Correct. Vera returns OK when an action is called. Vera doesn't yet support setting an "onlevel" but it is in the UPnP spec. I was able to make this a configurable option by just tracking the last level awhile back. But I need to revisit it. 

My solution is to simply delay any On state by less than a second (enough time for the Brightness command to be called) and then set a flag right away in brightness that has a longer timeout to reset that flag. Then the On state checks for the flag after it's sub-second delay resumes and if the flag wasn't set by Brightness it's allowed to proceed. Otherwise it's dropped.

**Comment by boojew** [comment]
With ios11 our and no change in this behavior, are there any plans to solve  this here?

**Comment by B1tMaster** [comment]
Is this a bug? This is how all dimmers work in real world.
You cant change brightness without having the bulb on.

**Comment by boojew** [comment]
The problem that I experience - and as I understand this thread is addressing - is that when I change the brightness level, it first send a a full on and then sets the correct brightness

**Comment by snowdd1** [comment]
And vice versa: if you switch the light on, home app sends (randomly) an extra 100% brightness.

**Comment by boojew** [comment]
How do official HomeKit accessories handle this? Is a 2nd command in x ms to be ignored?

**Comment by ebaauw** [comment]
Don’t know about official HomeKit accessories, but in my homebridge-hue plugin, I combine multiple characteristic changes for the same light within 20ms into a single request to the Hue bridge.  I also needed this to support colours, where Hue and Saturation need to be combined into one request, and to support HomeKit scenes without flooding the bridge with requests.

**Comment by boojew** [comment]
Thanks. Is anyone aware of any plans to address the way HAPNodeJS breaks up the characteristics?

**Comment by spencerryan** [comment]
I'm running into this issue with MisterHouse and Insteon. The Insteon gear responds much faster than Homekit sends the requests, so if I try and adjust brightness the lights rapidly oscillate between 100% and whatever the brightness setting is until the dimmer is let go on the iOS device. Misterhouse/Insteon treats "on" as 100% and anything else as the percentage. Doesn't matter if the light is on or off it will go to that brightness. This is super annoying.

**Comment by JornHermans** [comment]
Is there any way to resolve this? I'm having the same issue....

**Comment by soumaxetuirk** [comment]
I have created a python script with Paho MQTT. It reads the slider value and writes to a file.  So whenever a "ON" command is sent from Home App, Another script read the slider value from file and sent it to device along the ON command. 
`import time
import csv
import pickle
import paho.mqtt.client as mqtt
    
def on_connect(client, userdata, flags, rc):
    client.subscribe("py/irsend")
  
def on_message(client, userdata, msg):
        global temp
        temp = str(msg.payload)
        file = open('temp.txt', 'w')
        file.write(temp)
        file.close()
        
client = mqtt.Client()
client.connect("localhost",1883,60)
client.on_connect = on_connect
client.on_message = on_message
client.loop_forever()`
Output : 
1. In "OFF" condition, If I change the slider then it will send slider value and "ON".
2. In "OFF" condition, If I click only "ON" then it will send last saved slider value along with "ON"
