### ISSUE TITLE
cannot get to install on windows 10

### ISSUE THREAD

**Issue by andybno1** [nfarina/homebridge#811]
I had a successful install on my macbook pro last night but didn't realise this works best on a always on computer so I have a windows tower PC but I cant get the damn thing to install I get a stack error, I have tried this: https://stackoverflow.com/questions/38149603/npm-install-fails-with-error-c2373-with-vs2015-update-3#comment63949167_38249826 with no joy here is GIT CMD log:

> C:\Users\AndyB>npm install -g --unsafe-perm homebridge
> C:\Users\AndyB\AppData\Roaming\npm\homebridge -> C:\Users\AndyB\AppData\Roaming\npm\node_modules\homebridge\bin\homebridge
> 
> > mdns@2.3.3 install C:\Users\AndyB\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns
> > node-gyp rebuild
> 
> C:\Users\AndyB\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns>if not defined npm_config_node_gyp (node "C:\Users\AndyB\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
> Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
>   dns_sd.cpp
>   dns_service_browse.cpp
>   dns_service_enumerate_domains.cpp
>   dns_service_get_addr_info.cpp
>   dns_service_process_result.cpp
>   dns_service_ref.cpp
>   dns_service_ref_deallocate.cpp
>   dns_service_ref_sock_fd.cpp
>   dns_service_register.cpp
>   dns_service_resolve.cpp
>   dns_service_update_record.cpp
>   mdns_utils.cpp
> ..\src\dns_service_register.cpp(122): warning C4267: '=': conversion from 'size
> _t' to 'uint16_t', possible loss of data [C:\Users\AndyB\AppData\Roaming\npm\no
> de_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
> ..\src\dns_service_update_record.cpp(45): warning C4267: '=': conversion from '
> size_t' to 'uint16_t', possible loss of data [C:\Users\AndyB\AppData\Roaming\np
> m\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
>   network_interface.cpp
>   socket_watcher.cpp
>   txt_record_ref.cpp
>   txt_record_create.cpp
> ..\src\txt_record_create.cpp(29): warning C4267: '=': conversion from 'size_t'
> to 'uint16_t', possible loss of data [C:\Users\AndyB\AppData\Roaming\npm\node_m
> odules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
>   txt_record_deallocate.cpp
>   txt_record_set_value.cpp
>   txt_record_get_length.cpp
>   txt_record_buffer_to_object.cpp
> ..\src\txt_record_buffer_to_object.cpp(28): warning C4267: 'argument': conversi
> on from 'size_t' to 'uint16_t', possible loss of data [C:\Users\AndyB\AppData\R
> oaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxp
> roj]
> ..\src\txt_record_buffer_to_object.cpp(35): warning C4267: 'argument': conversi
> on from 'size_t' to 'uint16_t', possible loss of data [C:\Users\AndyB\AppData\R
> oaming\npm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxp
> roj]
> ..\src\txt_record_set_value.cpp(44): warning C4267: 'argument': conversion from
>  'size_t' to 'uint8_t', possible loss of data [C:\Users\AndyB\AppData\Roaming\n
> pm\node_modules\homebridge\node_modules\mdns\build\dns_sd_bindings.vcxproj]
>   win_delay_load_hook.cc
>      Creating library C:\Users\AndyB\AppData\Roaming\npm\node_modules\homebridg
>   e\node_modules\mdns\build\Release\dns_sd_bindings.lib and object C:\Users\And
>   yB\AppData\Roaming\npm\node_modules\homebridge\node_modules\mdns\build\Releas
>   e\dns_sd_bindings.exp
>   Generating code
>   Finished generating code
>   dns_sd_bindings.vcxproj -> C:\Users\AndyB\AppData\Roaming\npm\node_modules\ho
>   mebridge\node_modules\mdns\build\Release\dns_sd_bindings.node
>   dns_sd_bindings.vcxproj -> C:\Users\AndyB\AppData\Roaming\npm\node_modules\ho
>   mebridge\node_modules\mdns\build\Release\dns_sd_bindings.pdb (Full PDB)
> 
> > curve25519-n@1.1.0 install C:\Users\AndyB\AppData\Roaming\npm\node_modules\homebridge\node_modules\curve25519-n
> > node-gyp rebuild
> 
> C:\Users\AndyB\AppData\Roaming\npm\node_modules\homebridge\node_modules\curve25519-n>if not defined npm_config_node_gyp (node "C:\Users\AndyB\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
> Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
>   node_curve.cc
>   win_delay_load_hook.cc
> C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\unistd.h(9): err
> or C2006: '#include': expected a filename, found 'newline' (compiling source fi
> le ..\node_curve.cc) [C:\Users\AndyB\AppData\Roaming\npm\node_modules\homebridg
> e\node_modules\curve25519-n\build\curve.vcxproj]
> C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\unistd.h(9): fat
> al error C1083: Cannot open include file: '': No such file or directory (compil
> ing source file ..\node_curve.cc) [C:\Users\AndyB\AppData\Roaming\npm\node_modu
> les\homebridge\node_modules\curve25519-n\build\curve.vcxproj]
> gyp ERR! build error
> gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
> gyp ERR! stack     at ChildProcess.onExit (C:\Users\AndyB\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
> gyp ERR! stack     at emitTwo (events.js:106:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
> gyp ERR! System Windows_NT 10.0.10586
> gyp ERR! command "C:\Program Files (x86)\nodejs\node.exe" "C:\Users\AndyB\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
> gyp ERR! cwd C:\Users\AndyB\AppData\Roaming\npm\node_modules\homebridge\node_modules\curve25519-n
> gyp ERR! node -v v6.6.0
> gyp ERR! node-gyp -v v3.4.0
> gyp ERR! not ok
> C:\Users\AndyB\AppData\Roaming\npm
> `-- (empty)
> 
> npm ERR! Windows_NT 10.0.10586
> npm ERR! argv "C:\Program Files (x86)\nodejs\node.exe" "C:\Users\AndyB\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "install" "-g" "--unsafe-perm" "homebridge"
> npm ERR! node v6.6.0
> npm ERR! npm  v3.10.8
> npm ERR! code ELIFECYCLE
> 
> npm ERR! curve25519-n@1.1.0 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the curve25519-n@1.1.0 install script 'node-gyp rebuild'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the curve25519-n package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-gyp rebuild
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs curve25519-n
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls curve25519-n
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     C:\Users\AndyB\npm-debug.log
> npm ERR! code 1

**Comment by ddilbaz** [comment]
Error: Cannot find module 'C:\Users\asus\homebridge'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Comment by jocamero** [comment]
Has anyone got this working on Windows???  Judging from the posts here I think a lot of people could use some help getting this setup in a Windows environment.

I got it up and running no problem on OS X, but the Windows instructions are a bit lacking to say the least.
