### ISSUE TITLE
Homebridge not pairing with ios10

### ISSUE THREAD

**Issue by nemesisos** [nfarina/homebridge#812]
Hi all. I cant seem to get homebridge work with ios10
I have the exact same behavior as described in the first post of this, but none of the suggestions helps: https://github.com/nfarina/homebridge/issues/662. As described there, I enter the PIN on my iPhone or iPad, it says pairing and then it fails
It's a brand new setup, running in a bitnami VM. Ubuntu 14.04 with node.js 6.6.0-0 (64-bit)
I tried another new setup in a different VM as well, but no luck
Any suggestions? Thanks

**Comment by anusoft** [comment]
Plug your iphone to your mac and open XCode to view logs.

Mine happen too, it show that I hit the 100 limit of max accessories

```
Sep 28 14:39:41 iPhone homed(CoreHAP)[139] <Info>: [HAP Accessory Server IP XXX] Creating HAP Bridged Accessory with instanceID 111
Sep 28 14:39:41 iPhone homed(CoreHAP)[139] <Notice>: ### Accessory Server exceeds maximum number of allowed accessories
Sep 28 14:39:41 iPhone homed(HomeKitDaemon)[139] <Notice>: [Accessory Browser] Failed HAP service discovery on accessory server <HAPAccessoryServerIP: 0x100778990>    Device ID: CC:22:3D:E3:CE:30    Model: Homebridge    Protocol Version: 1.0    Source Version: (null)    Config Number: 113    Category: 2    Status Flags: 0x1 with error: Error Domain=HMErrorDomain Code=49 "(null)"
Sep 28 14:39:41 iPhone homed(HomeKitDaemon)[139] <Info>: [Pairing] Sending pairing completion with error Error Domain=HMErrorDomain Code=49 "(null)"
Sep 28 14:39:41 iPhone homed(CoreHAP)[139] <Info>: Sending request to accessory to remove the pairing for the current controller XXXX
Sep 28 14:39:41 iPhone homed(CoreHAP)[139] <Info>: Releasing transaction '<OS_os_transaction: com.apple.CoreHAP.get-att-db161D62FD-DBE2-4286-A9B6-2C81FF1938FE>' - held for 434.048 milliseconds
Sep 28 14:39:41 iPhone homed(HomeKitDaemon)[139] <Notice>: Failed to add accessory Homebridge with error: Error Domain=HMErrorDomain Code=49 "(null)"
Sep 28 14:39:41 iPhone homed(HomeKitDaemon)[139] <Info>: [AWD] HMDAccessoryPairingEvent -- Accessory Pairing event took 10774.634583 ms, isAdd: YES, success: NO
Sep 28 14:39:41 iPhone homed(HomeKitDaemon)[139] <Notice>: Answering incoming message kAddAccessoryRequestKey (2FA01D37-A165-4277-96E9-16AB30759F22) from client 'HomeUIService' that does expect a response
Sep 28 14:39:41 iPhone HomeUIService(Home)[2007] <Notice>: startPairing failed with error: <private>
Sep 28 14:39:41 iPhone HomeUIService(Home)[2007] <Error>: Failed pairing with accessory: <private> error: <private>
Sep 28 14:39:41 iPhone HomeUIService(Home)[2007] <Notice>: Transitioning phase: AttemptingToPair -> PermanentlyFailed
Sep 28 14:39:41 iPhone HomeUIService(Home)[2007] <Notice>: Updating status text: (null)
Sep 28 14:39:41 iPhone HomeUIService(Home)[2007] <Notice>: Cancel requested for accessory: (<private>)
```

**Comment by anusoft** [comment]
Have you tried disable IPv6?

https://github.com/nfarina/homebridge/issues/607#issuecomment-236471712

and ensuring your firewall is allow homebridge port.

**Comment by jovrtn** [comment]
I had an issue when using homebridge-itunes where homebridge was maxing out the CPU usage on my Mac Mini. Reverting to an earlier build of that plugin solved my issue and allowed me to pair with iOS 10; could be something similar with your setup.

**Comment by bartdorsey** [comment]
I'm having a similar problem but I'm running homebridge on my raspberry pi 3. I've disabled ipv6 on both the pi's kernel and avahi-daemon. Homebridge now shows in Bonjour browser. Only the Home App still doesn't see it.  No firewalls between me and the homebridge... I'm at a loss at this point.

**Comment by klaasjoerg** [comment]
Not a big help maybe, but I am running homebridge on a raspberry pi3 jessie (100% standard installation incl. zwave) and it definitively works smoothly with IOS10. So it doesn't seem to be general problem...

**Comment by bartdorsey** [comment]
So, I nuked all my modules and setup homebridge again from scratch and it's working now... so I'm not sure what the hang up was.

**Comment by nemesisos** [comment]
Got it to work! I reinstalled everything on an new VM with node.JS 6.7.0.0, disabled ipv6 and enabled the firewall port..not sure which one fixed it, but it working now. Thanks for all the help

**Comment by glentregoning** [comment]
Issue was the firewall for me on Mac
