### ISSUE TITLE
Multiple ios 8 devices

### ISSUE THREAD

**Issue by ddtlabs** [nfarina/homebridge#82]
Is there a known way to get homebridge working with more than one ios 8.4 device at the same time? 
When my light devices are assigned to an ios 8 device then other ios devices can not find them (eve app). Devices that are not assigned could be used. Trying IOS 9 beta 2 did not work for me at all because "eve" could not access icloud homekit database for an unknown reason.
Thanx in advance.

PS: using FHEM platform shim which can be found here (german thread): http://forum.fhem.de/index.php/topic,32652.msg314166.html#msg314166

**Comment by nfarina** [comment]
So this is "by design" to comply with Apple's new requirement in iOS 9 for Accessories to only be able to pair with one phone at a time. See [HAP-NodeJS Issue #69](https://github.com/KhaosT/HAP-NodeJS/issues/69) for more details:

> It seems that iOS 9 starts enforcing the requirement that one accessory can only be paired directly with one iCloud account.

**Comment by nfarina** [comment]
Note that once you pair with the first device, you can invite other HomeKit users to your Home and they will be able to use the accessories.

**Comment by wbros** [comment]
Can we not spawn another instance listening on a different port?

**Comment by nfarina** [comment]
@wbros Sure, that would technically work as well.
