### ISSUE TITLE
Specify Server IP address

### ISSUE THREAD

**Issue by JangoBritt** [nfarina/homebridge#821]
Hi all,

I've found myself battling with a router that doesn't support Multicast / Bonjour(mDNS). The theory being that Bonjour isn't multicasting the packets across the three network segments (2.4GHz, 5GHz, and Wired Ethernet)

The solution I've decided upon is to separate my 2.4Ghz and my 5Ghz WiFi networks into separate SSIDs.

So-far-so-good, I've got all my devices back up on the right network for their capabilities. only... it hasn't made a blind bit of difference for connecting to Homebridge (Updating..../ No Response)

How can I tell my Homebridge (Mac OS) only to use my Wireless IP (GHz) rather than my Wired IP? 

Thanks for the help!

**Comment by lemonkey** [comment]
I have the same desire.

**Comment by lemonkey** [comment]
@jangobritt Did you ever solve this?
