### ISSUE TITLE
Homebridge wont start - hap-nodejs error

### ISSUE THREAD

**Issue by Irish-link** [nfarina/homebridge#823]
Hi. I recently tried to install a new addition on my main server and after reinstalling homebridge i get an error on startup that prevents it from running. 

/usr/lib/node_modules/hap-nodejs/lib/util/eventedhttp.js:62
    let port = this._tcpServer.address().port;
    ^^^
SyntaxError: Unexpected strict mode reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/lib/node_modules/hap-nodejs/lib/HAPServer.js:11:25)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

I even tried doing a fresh install of my server on a different machine to test. 

Running fedora 23 

To make sure i wasn't missing anything that was causing the errors I installed the "Development Tools" the "Development Libraries" and then make, automake, gcc, gcc-c++, kernel-devel. (overkill i know but i wanted to make sure somthing else wasn't causing the issue before I started a new issue)

then 
sudo dnf install npm
sudo dnf install avahi avahi-compat-libdns_sd avahi-compat-libdns_sd-devel
sudo npm install -g --unsafe-perm homebridge

as a test i tried to run homebridge on this new clean server. I ended up with the exact same errror. Can anyone shed any light on this?

**Comment by KhaosT** [comment]
@Irish-link what's the node version you are using?

**Comment by Irish-link** [comment]
Original server 6.6.0
new clean 0.10.42

**Comment by KhaosT** [comment]
@Irish-link please use node v5.0 or later...

**Comment by Irish-link** [comment]
so 6.6.0 is not later than 5.0?

**Comment by KhaosT** [comment]
@Irish-link it is, so what's "new clean 0.10.42" means?

**Comment by Irish-link** [comment]
It meant that after my main server was having issue i set up a separate server to test a clean install and got the same exact error.

**Comment by KhaosT** [comment]
@Irish-link interesting...so you see the exact same error (Unexpected strict mode reserved word) on the machine with node v6.6.0? I know under node v0.10.42 it won't work but should work under v6.6.0

**Comment by Irish-link** [comment]
Thats what i was getting yeah. I just remove nodejs on my new test environment and then forced the 6.7 to be installed. Now i get a different error. This is odd. So now i have two systems that are 0.1 version apart in nodejs now getting different errors. 


/usr/lib/node_modules/homebridge/node_modules/mdns/lib/dns_sd.js:35
    throw ex;
    ^

Error: Module did not self-register.
    at Error (native)
    at Object.Module._extensions..node (module.js:583:18)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/mdns/lib/dns_sd.js:24:20)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
[user@Homekit ~]$ node -v
v6.7.0

**Comment by KhaosT** [comment]
@Irish-link maybe your old machine have both and system picked the wrong one? for the new problem, try remove ``/usr/lib/node_modules/homebridge/node_modules/`` and then under ``/usr/lib/node_modules/homebridge/`` run ``npm install``

**Comment by Irish-link** [comment]
My god they've gone to plaid! 

Thanks a ton KhaosT. I got it running now. Now to see if i can get it running on my main server again that runs 24/7 with your advice.
