### ISSUE TITLE
Installing on Windows 10

### ISSUE THREAD

**Issue by derek-zhan** [nfarina/homebridge#825]
Hi guys,
I have been having trouble installing on my computer. I used WilliamHF's version of unistd.h. I also tried fix the node-gyp issue. However still giving me errors. Any help would be much appreciated :)

LINK : fatal error LNK1181: cannot open input file 'C:\OpenSSL-Win64\lib\libeay
32.lib' [C:\Users\Derek\AppData\Roaming\npm\node_modules\homebridge\node_module
s\ed25519\build\ed25519.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe failed with exit code: 1
gyp ERR! stack at ChildProcess.onExit (C:\Users\Derek\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack at emitTwo (events.js:87:13)
gyp ERR! stack at ChildProcess.emit (events.js:172:7)
gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Users\Derek\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Derek\AppData\Roaming\npm\node_modules\homebridge\node_modules\ed25519
gyp ERR! node -v v4.6.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
C:\Users\Derek\AppData\Roaming\npm
`-- (empty)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Users\Derek\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "install" "-g" "homebridge"
npm ERR! node v4.6.0
npm ERR! npm v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! ed25519@0.0.4 install: node-gyp rebuild
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ed25519@0.0.4 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ed25519 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR! npm bugs ed25519
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! npm owner ls ed25519
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR! C:\Users\Derek\npm-debug.log
npm ERR! code 1

**Comment by simeonhalsey** [comment]
Try removing Visual studio (your probably using the latest one) and install Visual Studio 2013 wdexpress_full.exe instead

**Comment by simeonhalsey** [comment]
And you may have the incorrect version of Open SSL... You want this one below,
Win32OpenSSL-1_0_2j.exe
