### ISSUE TITLE
Accessory count limits

### ISSUE THREAD

**Issue by dgburton** [nfarina/homebridge#827]
Hi,

Apologies if this has been asked elsewhere but could someone please confirm the accessory limits that apply when bridging accessories via Homebridge into HomeKit.

Is the limit 100 accessories across *all* platforms set up in your config.json?

I.e. If you had the Hue platform with 50 Hue bulbs and the Wemo platform for 50 wemo switches that would be the limit?

I'm seeing that HomeKit fails to sync between my iOS devices when I have more than 100 accessories behind Homebridge (no error is shown in the iOS 10 Home app) and wondered whether this was the issue?

Possible to run multiple Homebridge instances to get around this if it's the case?

Thanks!

**Comment by KhaosT** [comment]
Yeah, HomeKit enforces a limit of 100 accessories per bridge. So if all accessories exposed by your platform exceeded 100, the setup will fail from iOS side.

It's possible to run multiple instances of homebridge, just run the regularly and point each of them to a different config path and persistence path. You can run homebridge --help to see how.

**Comment by dgburton** [comment]
Great, thanks @KhaosT

**Comment by simonrb2000** [comment]
Sorry using homebridge --help I couldn't find how to do this. I am at my 100 device limit and trying to workout how to run multiple instances

**Comment by fingpop** [comment]
Sorry using homebridge --help I couldn't find how to do this. I am at my 100 device limit and trying to workout how to run multiple instances
