### ISSUE TITLE
Platform AccessoryInformation

### ISSUE THREAD

**Issue by benzman81** [nfarina/homebridge#835]
Is the AccessoryInformation for a platform changeable? I didnt find any code hints on how to do this. Currently only "Defautl-xxx" ist displayed.

**Comment by Realank** [comment]
same question...

**Comment by snowdd1** [comment]
Yes, example: https://github.com/snowdd1/homebridge-knx/blob/v0.3.10/lib/knxdevice.js#L73  
You'll need this service for each accessory.

**Comment by Realank** [comment]
thanks for you response @snowdd1 , I will try it later, hopefully it will work 😄

**Comment by Realank** [comment]
@benzman81 @snowdd1 
Thanks for your support, I know how to config AccessoryInformation for a accessory in homebridge plugin, my question is how to config manufacturer/model/serialNumber for entire home(which mean config these info of bridge).
As read the source code in [here](https://github.com/nfarina/homebridge/blob/master/lib/server.js#L100), I found how to config,

Just add some field in config.json in .homebridge folder:
    "bridge": {
        "manufacturer": "Realank",
        "model": "HomeV1",
        "serialNumber": "001",
        "name": "realank homee",
        "username": "CC:22:3D:E3:CE:22",
        "port": 51810,
        "pin": "xxx-xx-xxx"
    },

**Comment by snowdd1** [comment]
@Realank You want to change the information for the bridge itself?  

As you can see here https://github.com/nfarina/homebridge/blob/v0.4.10/lib/server.js#L97 the bridge section of _config.json_ supports the attributes

- manufacturer
- model
- serialNumber

However, that info will only show in *Home* app if you look at the details of the bridge itself - as the bridge has no user functionality, most user will put it somewhere hidden (I created a virtual room "system devices" for all things that have no user value for my family. So just curious, what are you going to do with it?

**Comment by Realank** [comment]
@snowdd1 yeah, bridge has no user functionality, it represents home(or room) in our Home App. It's useless, I just don't want to see "Default -xxx" at the details of the bridge 😜
