### ISSUE TITLE
how does the status work (Arduino project)

### ISSUE THREAD

**Issue by DaPeace80** [nfarina/homebridge#837]
I have a small problem.
Im not sure how the status is working. I want to switch a lamp on and off via homebridge.
I use this setup:

> "accessory": "Http",
>         "name": "Lampe",
>         "switchHandling": "yes",
>         "http_method": "GET",
>         "on_url":      "http://192.168.0.100/lampe/1",
>         "off_url":     "http://192.168.0.100/lampe/0",
>   "status_url":  "http://192.168.0.100/lampe/status",
>         "service": "Switch",
>         "brightnessHandling": "no",
>         "brightness_url":     "",
>         "brightnesslvl_url":  "",
>         "sendimmediately": "",
>         "username" : "",
>         "password" : ""

the status-url gives back 1 or 0 if i open it in the browser.
I can switch the lamp with curl http://192.168.0.100/lampe/0 or 1.
Do i need to send an answer when switching on the lamp?

I have following string that is sended when status_url is triggered.
Code for that:

```
String s = "<body><html>\r\n";
s += 0;
s += "</html>\n";
client.print(s);
client.flush();
```

Is that the right behavior for the status_url?

Regards, DaPeace

**Comment by lagunacomputer** [comment]
http://www.instructables.com/id/HomeKit-Enabled-Arduino-ESP8266-Self-Powered-110v-/

check my arduino code

**Comment by FarinUrlaub** [comment]
Hi, I have the same problem. I don't understand the url_status. 
url_status gets the status from the Arduino isn't is? for example: when I'm switching the state of a Lamp with a hardware button homebrdige gets this information and sends it to homekit?

But I don't unterstand which Arduino Code is needed
 "status_url": "http://192.168.0.177/1status",
                "status_on": "ON",
                "status_off": "OFF",
Do you found a solution?

**Comment by lagunacomputer** [comment]
i dont think you get a 'status' with homebridge.  Homebridge sends the URL periodically, triggering the arduino device.  if the Siri tells HomeKit and therefore Homebridge to send the URL, the arduino does it
Homekit/bridge sends "on_url": "http://192.168.0.100/lampe/1", the lamp turns on.
Homekit/bridge sends "off_url": "http://192.168.0.100/lampe/0",the lamp turns on.

It is basically the same as if you typed it manually into the browser address bar yourself.

**Comment by FarinUrlaub** [comment]
so it's not possible to get information from the arduino to homebridge?
My problem is, I want to activate a lamp with homekit and per hardware button. 
But if I activate the lamp with the button, the homekit doesn't get the information and don't know the status of the lamp

**Comment by lagunacomputer** [comment]
the problem is Homekit.  Homekit does not ask for status.

**Comment by FarinUrlaub** [comment]
I found a lot of tutorials with temperature and humidity. Here is homebridge asking vor ne status and I hoped, it would work with simple switches as well

**Comment by lagunacomputer** [comment]
i think when homebridge pushes an 'on' or 'off' switch command, homebridge just updates itself, "i send an on command, so i will show myself as on'.   but as far as temperature and humidity, it is not constantly polling or asking, maybe only every 1 minute or so.

**Comment by FarinUrlaub** [comment]
OK thank you. I'm so desperately. I thought I'm not the only one who wants to turn of a light, not just by Homekit. But I can't find a tutorial or something else. If you know or find something please write a comment;)

**Comment by lagunacomputer** [comment]
you can just use a web browser + Arduino, or use a commercial product like iDevices Switch,

**Comment by FarinUrlaub** [comment]
I tried it with a webserver, but I still don't get the information from the webserver into homekit

**Comment by FarinUrlaub** [comment]
I tried it with a webserver, but I still don't get the information from the webserver into homekit. I also want to connect a lot of lamps 20-30. with the comercial iDevices it would be to expensive.

**Comment by lagunacomputer** [comment]
if you are trying to switch 110/220v lamps, it's going to require relays no matter what.  Honestly it's cheaper and SAFER to buy x10 modules or idevices switch, than to make your own. See my instructable if you must do it yourself. https://www.instructables.com/id/HomeKit-Enabled-Arduino-ESP8266-Self-Powered-110v-/

don't electrocute yourself.

this is how I understand HomeBridge to work:

Correct/available:

lamp <- relay -< controller/arduino <- homebridge <-> homekit -<-> siri/iphone
                                                       ^
                                                 yes +<-> get status, when HB decides to update
                                                        |            or:
                                                        v
                                                        |->-<-  any time ok using web browser



Not available/not supported, or only when homebridge queries arduino, periodically:

           controller/arduino send status -> no           
lamp <- relay -< controller/arduino <-> homebridge <-> homekit -<-> siri/iphone
                                                   yes  <- get status, when HB decides to update

**Comment by NorthernMan54** [comment]
For device status there are 5 different paradigms in use with HomeKit, each with different levels of complexity and integration.

1) Fire and forget, HomeKit/homebridge plugin sends an on/off command to the device and doesn't know if it worked or not. And HomeKit doesn't know if the device is on/off, it just knows what command was last sent.  This pattern is typically seen with IR blaster type devices.  HomeKit would not know if the command failed.

2) Devices with distinct on/off commands, like your example with on/off urls.  In this case HomeKit would know that the command worked, and what command was last sent, but homekit would not be aware if the device was controlled locally

3) Is similar to number 2, except that the device also supports status commands, and responds to periodic status requests from HomeKit with the current status, including if the device was controlled locally.  When you change rooms in Home, it typically updates the device status.

4) Is similar to 3, except that the plugin polls the device on a regular interval for status, and updates any changes to HomeKit.  Homebridge-hue uses this pattern, as the Philip's hub doesn't support event notifications.

5) Is similar to 2, but the device supports event notifications.  And HomeKit is updated immediately with any status changes on the device.  As programming this is quite intensive and requires support in the device itself, only a few plugins use this model.

I have written several plugins, and have used all these patterns, with the deciding factoring what the device API supports.

In your question, if the device has a status URL you can have a plugin track status with pattern 4, and poll the device regularly.

**Comment by FarinUrlaub** [comment]
hey thanks to both of you for the answers. NorthernMan54 so there are plugin witch are asking for with an URL for the status of a lamp in a defined time period? So I can get an update of my lamp if it's changend locally? That would solve my problem with the commuication.

**Comment by TomInIowa** [comment]
I am looking for what to send  when my  esp8266 with arduino gets a status request.
what is the server expecting?        
something like    200, "text/plain", "{\"battery\":100,\"statusCode\":200}"

I started my arduino with  ESP8266 HTTP Lock
   Make a Siri HomeKit enabled lock with ESPea 

It handles on and off just fine.  I am trying to figure out the status call.
