### ISSUE TITLE
RM pro or othe IR remote wifi support 

### ISSUE THREAD

**Issue by viuuuu** [nfarina/homebridge#838]
I was looking for a pluggin for control IR items. The only one that I saw is IRKIT and it's discontuined.
Could be possible a plugin for broadlink IR remote or xiaomi ir smart remote or something similar?
Thanks you

**Comment by cocacola89** [comment]
Just wanted to share some thoughts/experience on this subject:

**Bad news 1:**
Most of IR-controlled non-smart devices (e.g. Air Conditioners, Media Players, TVs, etc.) are stateless in terms of home automation kits. That means that even if you manage to send them IR commands, there is no way of polling its' state. Obviously, you can introduce some kind of virtual state in homebridge plugin, but it would lead to a non-user-friendly experience. 
Imagine you have an AirCon and you know how to send 'power on' and 'power off' IR-commands (or most likely just one 'power on/off' command). You can expose it from Homebridge as a power outlet with a virtual on/off state stored in homebridge and sending IR commands when switching with Homebridge. Than you can sync initial virtual state with the real state by starting homebridge when your AirCon is switched off. But if you dare to switch your AirCon not through HomeBridge (e.g. with good old physical remote) it will get out of sync and you will see incorrect information about your device in Home app. Not quite Homekit-y.

**Bad news 2:**
Universal IR-remote devices like Broadlink and Xiaomi don't expose appropriate public API that can be used from Homebridge plugin as those manufacturers don't want their devices to be used in generic home automation environments. They need to bind you to their solutions for home automation where all devices from one manufacturer are somehow integrated.

**Good news:**
Just yesterday I finally managed to develop Homebridge plugin for my Philips TV that uses Broadlink RM3 Mini to send IR commands. It seems to be reliable and does not depend on Internet connection. 
What made it possible is that Philips TVs expose public HTTP REST API to your local network so you can poll your TV state and send commands without any kind of IR (just HTTP-requests). Except for one command - 'power on' (at least for my TV model). I'm aware of Homebridge plugin with quite the same functionality - [https://www.npmjs.com/package/homebridge-philipstv](url), but my TV doesn't support WOWL-packets, so there's no way of turning it on via Philips API. That's where I use RM3 Mini - I send 'power on' command if my TV is powered off.

I was thinking of publishing this plugin, but it requires quite a lot of configuration before you can use it (including intercepting UDP-packets on your local network), so I decided to not.

But if you are really interested in using Broadlink IR remotes from Homebridge and ready for some challenging configuration process - just write me, I will post it to GitHub.

**Comment by viuuuu** [comment]
Thanks for the answer.
It's true the cons that you tell me.
I was looking for a solution and I found this one. http://iotathome.co/en/voice-control-system/24-voice-control-broadlink-rmpro-apple-siri-home-kit-apps.html
I will try.
Thaks for your help

**Comment by felipesalomao** [comment]
@cocacola89 And if we could detect olf fashion remote ir command, and sync status of homekit device... We could use ir sensor on gpio or simply use RM3 Pro to do it.. This way all devices could be really smart.. I dont found any software for that yet.. What you think?
