### ISSUE TITLE
Running  Homebridge on Bootup (init.d) error

### ISSUE THREAD

**Issue by junior466** [nfarina/homebridge#840]
I am trying to follow the init.d guide but when trying to start the service manually

 `sudo /etc/init.d/homebridge start`

 I get the following error in log 

`sudo: /usr/local/bin/homebridge: command not found
`

I am a beginner and apologize if this has already been answered.

**Comment by jcbriones** [comment]
What system are you running on? What type of linux? Raspbian?

**Comment by junior466** [comment]
Sorry, I am running Raspbian on Raspberry Pi.

**Comment by gijoecool** [comment]
Does the user you're using have sudo privileges?

**Comment by junior466** [comment]
Yes, I believe. This is a fresh install of Raspbian with the default user Pi.

**Comment by maragelis** [comment]
Read this mostly the section running at boot
[https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi]()

**Comment by junior466** [comment]
That's the guide I am following and having trouble with.

**Comment by RXM307** [comment]
try running

which homebridge
and/or
sudo find / -name "homebridge"

my
/usr/local/bin/homebridge is symlinked to
/usr/local/lib/node_modules/homebridge/bin/homebridge

you may need to run this to symlink

ln -s /usr/local/lib/node_modules/homebridge/bin/homebridge
/usr/local/bin/homebridge

Cheers,

Anthony

**Comment by timleland** [comment]
Most likely homebridge is in /usr/bin/  so removing the "local" should fix it. Here is my guide if you want to use systemd to start on boot up and restart on errors.
https://timleland.com/setup-homebridge-to-start-on-bootup/

**Comment by junior466** [comment]
Yes Tim! I simply removed "local"  from the script and its works perfectly! 

Thank you very much!!

**Comment by junior466** [comment]
Sorry to revive this but recently I have set my Pi to boot to the command line and Homebridge no longer auto starts. It only works if booting to the desktop. Is this normal behavior?

**Comment by timleland** [comment]
My steps should work either way(desktop/command line). Did you change anything else?

**Comment by junior466** [comment]
No.  I followed the steps exactly.

**Comment by timleland** [comment]
Check the status by running _systemctl status homebridge_

**Comment by junior466** [comment]
This is the result of running the above command

`● homebridge.service - Node.js HomeKit Server
   Loaded: loaded (/etc/systemd/system/homebridge.service; enabled)
   Active: inactive (dead) since Wed 2016-10-19 07:34:38 EDT; 2min 2s ago
  Process: 540 ExecStart=/usr/bin/homebridge $HOMEBRIDGE_OPTS (code=exited, status=0/SUCCESS)
 Main PID: 540 (code=exited, status=0/SUCCESS)`
