### ISSUE TITLE
No connection to homebridge on second iOS with same Apple-ID

### ISSUE THREAD

**Issue by borni110** [nfarina/homebridge#841]
Hello, 

i'm using homebridge on a Raspi and have connected it with the EVE-App on my iPad Air. This connection works and control items with homebridge works also.
I also have an iPhone, which is connected with iCloud over the same Apple ID, sync of key ring is activated. Unfortunately the EVE-App on iPhone cant connect to homebridge (Setting are Synced from EVE-App of iPad). 
Is sharing this not possible, or what could be my mistake?

regards Borni

**Comment by maragelis** [comment]
Are you using the same iCloud Id ? You must enable two factor authentication under iCloud settings on the iPhone or iPad

**Comment by snowdd1** [comment]
If they are, wait some hours. Initial sync my take some time. If all is replicated to the other iDevice, you should be able to use homebridge from both devices.

If the iPhone is out of the WLAN, and the iPad is still home, and the iPad is configured as Home Hub, it should still work (using mobile network) if the Home was created under iOS10 on the iPad. 

Regards

**Comment by borni110** [comment]
I only had activated normal iCloud Sync without two factor authentication. Now i activated it and waiting for synchronisation. 
Hope it will work fine. Tell it later.

**Comment by borni110** [comment]
Unfortunately it did'nt work. Also waiting 2 Days for sync of iPad/iPhone the control of homebridge components from my iPhone is'nt working.

**Comment by borni110** [comment]
Now it works. I have deleted the complete Home on Ipad and made a new installation of the homebridge.
