### ISSUE TITLE
Script to Restart Homebridge after an error state  - For RPI

### ISSUE THREAD

**Issue by kenderson** [nfarina/homebridge#845]
I've seen a couple examples of how to do this on Mac and Windows, but nothing for RPI. If there's something out there that I've missed, feel free to shoot me a link and kill this issue.

Thank You!

**Comment by timleland** [comment]
Here is my guide in setting up Homebridge on Raspberry Pi to start on boot up and restart on errors. Hope it help!
https://timleland.com/setup-homebridge-to-start-on-bootup/

**Comment by kenderson** [comment]
@timleland Thanks for chiming in here! Your write-up for onboot is fantastic! But I'm really looking for something that will restart homebridge after it encounters an error state and shuts itself down.

Any thoughts?

Thanks Again!

**Comment by snowdd1** [comment]
Did you really **read** his guide? Because that's one of the advantages of the described systemd method.

**Comment by timleland** [comment]
@kenderson My method should restart on errors and will also start on boot. Is there a reason you wouldn't want it to start on bootup?

**Comment by gmoneyyy** [comment]
@kenderson You mentioned you seen example of this for Windows.  Do you know where I can find that information?  I can't seem to find it.

**Comment by mbnn** [comment]
Is it also possible to make a script or sorts to auto update all homebridge and homebridge plugins?
