### ISSUE TITLE
Error: Could not locate the bindings file

### ISSUE THREAD

**Issue by feritobus** [nfarina/homebridge#846]
I had a clean install but when running >node homebridg or homebridge I am getting this error

C:\Users\Fer\AppData\Roaming\npm\node_modules\homebridge\bin>homebridge
C:\Users\Fer\AppData\Roaming\npm\node_modules\homebridge\node_modules\bindings\bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 →C:\Users\Fer\AppData\Roaming\npm\node_modules\homebridge\node_modules\ed25519\build\ed25519.node
 →C:\Users\Fer\AppData\Roaming\npm\node_modules\homebridge\node_modules\ed25519\build\Debug\ed25519.node
 →C:\Users\Fer\AppData\Roaming\npm\node_modules\homebridge\node_modules\ed25519\build\Release\ed25519.node
 →C:\Users\Fer\AppData\Roaming\npm\node_modules\homebridge\node_modules\ed25519\out\Debug\ed25519.node
 →C:\Users\Fer\AppData\Roaming\npm\node_modules\homebridge\node_modules\ed25519\Debug\ed25519.node
 →C:\Users\Fer\AppData\Roaming\npm\node_modules\homebridge\node_modules\ed25519\out\Release\ed25519.node
 →C:\Users\Fer\AppData\Roaming\npm\node_modules\homebridge\node_modules\ed25519\Release\ed25519.node
 →C:\Users\Fer\AppData\Roaming\npm\node_modules\homebridge\node_modules\ed25519\build\default\ed25519.node
 →C:\Users\Fer\AppData\Roaming\npm\node_modules\homebridge\node_modules\ed25519\compiled\5.0.0\win32\ia32\ed25519.node
    at bindings (C:\Users\Fer\AppData\Roaming\npm\node_modules\homebridge\node_modules\bindings\bindings.js:88:9)
    at Object.<anonymous> (C:\Users\Fer\AppData\Roaming\npm\node_modules\homebridge\node_modules\ed25519\index.js:1:99)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\Fer\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\lib\HAPServer.js:6:15)
    at Module._compile (module.js:425:26)

**Comment by SpeedmaxX** [comment]
Hi, got a fix for that?

**Comment by pug205** [comment]
I'm struggling with the same issue... Any updates?

**Comment by pdlove** [comment]
I was able to get past this by installing Open SSL 1.0.2k from http://slproweb.com/products/Win32OpenSSL.html
After that I deleted homebridge's node_modules folder and reinstalled via npm.
I'm getting an error building curve25519-n now.

**Comment by KhaosT** [comment]
@pdlove Would you mind to manually try the HAP-NodeJS master from GitHub and see if it build? Someone pushed a fix for curve25519 for Windows, I haven't publish that version to npm yet.

**Comment by aheissenberger** [comment]
my problem was related to the node-gyp parts - I removed homebridge and reinstalled it and this fixed the problem

**Comment by jocamero** [comment]
I've been getting similar errors on upgrades the last few months.  The only solution I've found is to delete the /usr/local/lib/node_modules/homebridge/node_modules folder and reinstall.

**Comment by jocamero** [comment]
@nfarina this still appears to be an issue on upgrades.  Can you please reopen this issue for further investigation?  Thanks.

**Comment by Elypson** [comment]
Still an issue... what is this "bindings"? None of the above comments work

**Comment by mikebronner** [comment]
@Elypson @wbpluto's solution worked for me. First I deleted the following folder:
```sh
rm -rf /usr/lib/node_modules/homebridge/node_modules
```

Then I ran the nom install command:
```sh
sudo npm -g install homebridge --unsafe-perm
```

That allowed it to build for me.
