### ISSUE TITLE
Wait for http responses

### ISSUE THREAD

**Issue by fausto1124** [nfarina/homebridge#848]
Hi, so i been using homebridge-http and homebrige-better-http-rgb plugins with an arduino. The problem i have is that the http requests are made so quickly. 

I was wondering if is there a way to make homebridge wait for the response of the previous request to start the next one.

Thanks!

**Comment by lagunacomputer** [comment]
try adding this to your void(loop);

delay(100);

**Comment by fausto1124** [comment]
@lagunacomputer  where is that file? is that a homebridge file? or the plugin?

Thanks

**Comment by rafaelncarvalho** [comment]
I have a similar problem, I'm using an Arduino with homebridge-http too, but the Arduino freeze when I run a scenes because it makes multiples HTTP requests at the same time.

**Comment by lagunacomputer** [comment]
Try the 'V4' code attached to the Instructables, I broke up the Light, PIR and temp sensors into individual http requests.  Also, you want to slow down the loop, ds18b20 and DHT11 sensors can only poll every 2-4 seconds. If you don't have enough delay in your loop, the code will loop faster than the sensors can provide info.  Try adding a 5 second delay to the void loop .  Also, Homebridge on RasPI may crash unless you have all sensors listed in config.json online and reachable. Homebridge will crash and restart if it can't find a sensor via ip/http

**Comment by lagunacomputer** [comment]
Also, it seems the ESP8266 does not like certain functions on certain pins, unlike original arduino uno or mega. Try changing pins if you can't get a sensor to read
