### ISSUE TITLE
Notify Homekit about changes

### ISSUE THREAD

**Issue by micha149** [nfarina/homebridge#85]
I looked a lot around in homebride and HAP-NodeJS code to figure out how to notify any homekit device about changes of an accessory. For example a thermostat: it detects periodically the current temperature and through a node library I'll receive an event. How can I pass this value to the hap service?

Another case are my light switches. The light is not only switchable through an app. There are light switches spread over the whole building. How to tell homekit about the actual bulb state when a switch will be actuated?!

I know about the `onRead` callback, but this seems only be triggered if i ask Siri about a specific state…

**Comment by nfarina** [comment]
So this is an area that I'm just about to get into. `HAP-NodeJS` does have support for "events" for subscribed clients, but it's a bit basic right now. I'm currently working on a PR that will improve event support as well as expose it to HomeBridge plugins.

I'm curious though - how are you hoping to use events? Right now the only place I see them used is when you're browsing an accessory in an iOS app and you want to watch changes in realtime. I understand that iOS 9 will allow you to create triggers based on events - is that what you're working towards?

**Comment by nfarina** [comment]
Oh duh, I just re-read your post and I see what you're trying to do - connect the light switches and bulbs obviously :) Are you running iOS 9? And is there an app that permits these relationships to be setup? HomeBridge/HAP-NodeJS is just a "dumb" event sink - it's up to iOS (or Apple TV, etc.) to manage the "if this then that" stuff.

**Comment by micha149** [comment]
I think you missunderstood me. I want to change the state of an characteristic on a specific event. There seems to be a way to notify any homekit device (iPhone, iPad) when a light is switched from off to on. When I open my homekit app (Insteon+) on two devices the one shows the changed state when I tap on a button on the other device.

What I want to do is to notify homekit that a light is not activated anymore because somebody has pressed the light switch next to the door.

You talked about events. That is a piece of code I could imagine:

```javascript
// connection is a service for my knx bus and 1/1/25 is the address where the light tells its state
// the following callback is triggered each time the light goes on or off
connection.on('1/1/25', function(message) {
    var switchCharacteristic = service[1][2], // some characteristic of my hap service
        newState = message.getData()[0] === 1; // data is an array with one number, 1 is on 0 is off

    // tell hap that the light status has changed...
    switchCharacteristic.emit('update', newState);
});
```

**Comment by nfarina** [comment]
Got it. I half-understood you then.

> When I open my homekit app (Insteon+) on two devices the one shows the changed state when I tap on a button on the other device.

This is happening with HomeBridge today? If so, I believe this is powered by the `Characteristic` instances in `app.js`. These `HAP-NodeJS` classes support sending events for value changes.

Right now HomeBridge provides no way to retrieve these instances and change their state programmatically as your code snippet desires, but it's something I'm working on now.

**Comment by micha149** [comment]
Yes, I noticed this behavior on accessories from the homebridge server. I had a look into `app.js` but there is no explicit handling of update notifications. Maybe its implemented by `HAP-NodeJS` in the Characteristic prototype or whatever. This is something weird for me. There is an option `supportEvents` but its not extending or implementing any EventEmitter…

I'll wait for your changes… Tell me if I could help you…

**Comment by nfarina** [comment]
Yes I believe it's implemented by Characteristic in HAP-NodeJS and operates using a delegate-method-like pattern internally (not using EventEmitter).

**Comment by justme-1968** [comment]
set characteristic.eventEnabled = true; (for example in the onRegister callback). and then if you receive the event call characteristic.updateValue(value, null); with the value you received from your device. this will push the new value to homekit and all listening apps.

works perfectly.

**Comment by micha149** [comment]
Works on my iPad but not on my iPhone, but this would be another problem. Thanks!

@nfarina for your interest: you get the characteristic instance in the `onRegister` callback. This is my quick test code:
```javascript
{
    cType: types.POWER_STATE_CTYPE,
    // ...
    onRegister: function(characteristic) {
          characteristic.eventEnabled = true;
          that.connection.on(that.switchAddress, function(msg) {
              var newValue = msg.getData()[0] === 1;
              characteristic.updateValue(newValue, null);
          });
    },
    // ...
}
```

**Comment by snowdd1** [comment]
@micha149 Arme you boing to implement an KNX shim as a platform? I might save a lot of work then!

**Comment by micha149** [comment]
@snowdd1 I have created a native library for knxip… have a look at https://github.com/micha149/homelib. There is currently no readme because I don't want too much traffic on this project until all is fine. But you can use it already for some experiments.

I'm not sure if a platform is the right way, because an automatic device discovery seems not to be possible with knx, so you have to configure it manually. Also reading some export form ETS software makes no sense. For example: You have 3 group addresses for dimm value, switch on/off and switch status report. But there is no indicator that these three objects are for one single dimming lamp.

If you are interested in my test implementations I would paste the accessory files into a gist…

**Comment by snowdd1** [comment]
You might as well have a look into my repository. I have found a way to connect the different group addresses using hints in the names in ETS. HTTPS://github.com/snowdd1/HAP-NodeJS-KNX 
This is which I am thinking about to bring into a platform shim, see #95

**Comment by andig** [comment]
For sake of curiosity- I'm currently doing something like this to update homebridge with external changes via `setValue()`:

    FritzWifiAccessory.prototype.update = function() {
        this.platform.log("Updating guest WLAN");

        this.platform.fritz('getGuestWlan').then(function(res) {
            this.service.getCharacteristic(Characteristic.On).setValue(res.activate_guest_access, undefined, FritzPlatform.Context);
        }.bind(this));
    };

Through this issue I've happened to notice that there's also `Characteristic.updateValue()`. Is there advantage of using the one vs. the other?

**Comment by snowdd1** [comment]
Opposed to setValue() , updateValue() does not trigger the set event within homebridge, so you don't need to store a context and inspect it in the set event routine to avoid loops.

**Comment by andig** [comment]
> Opposed to setValue() , updateValue() does not trigger the set event within homebridge, so you don't need to store a context and inspect it in the set event routine to avoid loops.

@snowdd1 Thank you. Meaning I could refactor but also use `setValue` and take care of the context.

I'm still confused how to react to external events/update or how to enable those. In https://github.com/andig/homebridge-fritz/issues/14 user claims that external updates are not picked up although I'm already running a timer and call `setValue()` with the poll result.

Is it still- in the current version- necessary to use something like `eventEnabled`? I've also checked your knx code but couldn't find it?

**Comment by snowdd1** [comment]
The service you're going to use must have characteristic(s) that have the `ev` flag set in their properties, most defaults have that.  
I am not using any special code, other then invoking setValue or updateValue on the characteristic, homebridge and HomeKit take care of the rest.
