### ISSUE TITLE
No response from devices after restart - Raspberry Pi 3

### ISSUE THREAD

**Issue by rjmcfadd** [nfarina/homebridge#851]
I have homebridge installed on my Raspberry Pi 3 on the latest version of Raspbian. Homebridge is set to start on boot with systemd but my devices aren't connecting. In order to get everything to connect i need to run: sudo killall homebridge - then homebridge - to start it back up and that works.

**Comment by toshibochan** [comment]
You can share your file to make homebridge to start automatic. What you version of node?

**Comment by rjmcfadd** [comment]
Attached is the file I am using. I have node v6.7.0. Thank you!

[Unit]
Description=Node.js HomeKit Server 
After=syslog.target network-online.target

[Service]
Type=simple
User=homebridge
EnvironmentFile=/etc/default/homebridge
ExecStart=/usr/lib/node_modules/homebridge/bin/homebridge $HOMEBRIDGE_OPTS
Restart=on-failure
RestartSec=10
KillMode=process

[Install]
WantedBy=multi-user.target

[homebridge.service.txt](https://github.com/nfarina/homebridge/files/531519/homebridge.service.txt)

**Comment by timleland** [comment]
See my guide on setting up to start on boot. Most likely it's a permission issue https://timleland.com/setup-homebridge-to-start-on-bootup/

**Comment by rjmcfadd** [comment]
Yes, thank you @timleland!!! That fixed the issue. I think the only thing I had that was wrong was ExecStart=/usr/lib/node_modules/homebridge/bin/homebridge $HOMEBRIDGE_OPTS instead of ExecStart=/usr/bin/homebridge $HOMEBRIDGE_OPTS.

Thanks again!

**Comment by timleland** [comment]
No problem! Glad it helped.
