### ISSUE TITLE
Automation without AppleTV or iPad

### ISSUE THREAD

**Issue by DataFran** [nfarina/homebridge#853]
I have a dumb question:

I have Philips Hue lights, and a couple of Amazon Dash buttons. I have a script running on an Ubuntu server to sniff for the Dash button and trigger the lights to turn on/off but it's complicated and I was hoping Homebridge would offer a streamlined solution.

Unfortunately I own neither an AppleTV nor an iPad, just an iPhone.

Is there any way to use Homebridge to connect the Dash button to the Hue lights without an AppleTV or iPad?

Any help would be appreciated.

**Comment by RXM307** [comment]
You'd probably be better served by https://github.com/ide/dash-button

and use the HTTP Hue Integration mentioned here
http://www.openremote.org/display/docs/OpenRemote+2.0+How+To+-+Philips+Hue

homebridge is very iOS centric

**Comment by DataFran** [comment]
There's actually a Hue node app that works reasonably well. I'm not opposed to the iOS specific nature of Homebridge, I was just hoping it could operate as the hub, rather than as the translator for the hub, what with me not having a hub device.

**Comment by RXM307** [comment]
In that case perhaps http://www.openhab.org/ or one of the other Opensource
home automation hubs
https://opensource.com/life/16/3/5-open-source-home-automation-tools would
be better suited, whereas homebridge while it is a controller as far as I
know there is no Android client App

**Comment by MWDelaney** [comment]
I believe the actual answer is that Homebridge is a bridging tool for hardware and tools that don't (or don't yet) support HomeKit and still requires a hub like an AppleTV or iPad.

This fact is actually very poorly communicated by the documentation which could lead someone to believe (as I did at first) that Homebridge can replace the AppleTV or iPad in a HomeKit environment (this is NOT the case as I learned after a few hours). 

So since Homebridge is a _bridge_ between technologies you still need a hub (AppleTV or iPad) to perform the kind of automation tasks you're asking about.

@rxm307 rightly notes that OpenHAB is kind of this, but I've never had any luck with it. I don't know where RXM got the idea you were looking for Android support as you clearly state that you're an iPhone user.

**Comment by gijoecool** [comment]
If you only want to control the lights from an Amazon Dash button then I think homebridge is overkill. It would have the nice benefit of being able to control your lights through Siri on your iPhone though.

**Comment by justme-1968** [comment]
in my optinion homekit should not be seen and used as a smart home hub. there are much much better tools available for this. open hap is one, fhem would be another. there are many more.

homekit is an additional user interface to such a system. for example via siri and for remote access without a vpn or opened ports.

to have remote access for siri you have to have an atv3, atv4, or ipad.  there is no other way. and the ipad is not the best solution as it goes to sleep.

homebridge can be used as a tool to integrate different systems into homekit. each with its own plugin. but this leads to homekit being the hub. which is not a good solution.

homebridge can be used to bridge a 'real' home automation system as fhem or open hap or ... to homekit and use homekit as a frontend. this is the perfect solution.

**Comment by lagunacomputer** [comment]
I use the iOS app called "iDevices" with great effect

**Comment by lagunacomputer** [comment]
sorry, you need an ATV4 or iOS10 ipad for the encryption support that HomeKit Automation offers.  The iDevices app does let you make Scenes and Schedules, so more of a 'manual automation' via Scenes and or Schedules.  However there is in sensor input that full Automation may offer

**Comment by cflurin** [comment]
the best experience I made so far is to use homekit as a frontend/dashboard and a smart home "hub". I used several home automation  systems in the past but now node-red is my favorite one. Node-Red is preinstalled on raspberry and offers almost all API's you need: mqtt websocket, http, zwave, enocean, etc. I use my homebridge-mqtt plugin and the build in node mqtt in node-red to add accessories to homebridge and get/set values in both directions.

**Comment by klaasjoerg** [comment]
@cflurin
Do you also use zwave razberry and/or zwave.me with node-red ?

**Comment by cflurin** [comment]
@klaasjoerg 
I use the razberry z-wave module but I don't use the z-way-software.

I installed this node:
https://github.com/cflurin/node-red-contrib-openzwave
and
https://github.com/OpenZWave/open-zwave-control-panel
for configuring and setting the z-wave devices.

The control-panel creates a zwcfg_xxxx.xml file that you can copy to the openzwave-shared dir.
You' ll find "how-to" on node-red-contrib-openzwave.

Note: node-red-contrib-openzwave works also with other z-wave-controller (usb-adapter).
