### ISSUE TITLE
GE Fan Control shows as dimmable light in HomeKit

### ISSUE THREAD

**Issue by travismmorgan** [nfarina/homebridge#854]
I am using a GE Fan Control in the smart things app but when I access it via HomeKit, it shows up as a light and the type cannot be changed.

**Comment by gijoecool** [comment]
Was there any solution to this?

**Comment by travismmorgan** [comment]
No. I moved it to the homebridge-smartthings plugin GitHub instead.

**Comment by jansantanna** [comment]
did it fix the problem ?
