### ISSUE TITLE
DoorBird plugin...

### ISSUE THREAD

**Issue by gshewan** [nfarina/homebridge#856]
Hi, I'm looking for guidance, or indeed help, in writing a home bridge plugin for DoorBird intercoms (see www.doorbird.com).  They have an open API, but I'm just not clued up enough to write it myself.
I've managed to get the camera output showing via homebridge-camera-ffmpeg plugin and can trigger the door opener using homebridge-httpdoor, but it would be great to see be able to converse with the caller via the Home app, or even have the Home app popup when the door bell rings, as it did in the Apple Keynote some time ago.

Any assistance for a newbie please?

**Comment by tommyd75** [comment]
I would love to know how you got the camera to show up on the homebridge plugin. I tried but it wouldn't display any video. What does your config file look like?
Also what is homebridge running on?
I had tried it on a Raspberry Pi3. 
I thought the Home app would have that pop up as a feature as well. Maybe it's a setting in the notification of the device itself?

**Comment by gshewan** [comment]
Hi tommyd75, I'm running this on a RPi3.  Firstly I installed ffmpeg using the instructions [here](http://owenashurst.com/?p=242), then I installed homebridge-Camera-ffmpeg plugin.  My config.json looks like this:

	"platform": "Camera-ffmpeg",
	"cameras": [{
      		"name": "Gates",
      		"videoConfig": {
	       		"source": "-re -i http://x.x.x.x:80/bha-api/video.cgi?http-user=xxxxxxxxxx&http-password=xxxxxxxxxxx",
        		"maxStreams": 2,
        		"maxWidth": 1280,
        		"maxHeight": 720,
        		"maxFPS": 6
      		}
    	}]

I've also installed homebridge-Httpdoor plugin, which allows you to trigger the gate opening from within the Home app too, config.json looks like this:

    "accessories": [{
        "accessory": "Httpdoor",
        "name": "Gates",
        "controlURL": "http://username:password@x.x.x.x/bha-api/open-door.cgi",
        "statusURL": "http://username:password@x.x.x.x/bha-api/info1.cgi"
    }]

It doesn't do anything anything else, so notifications still come through the Doorbird app... at the moment... I'm still working it :)

**Comment by tommyd75** [comment]
@gshewan, Thanks!
OK, got it working perfect via Wifi, but when I turn off the wifi on the phone, I can only get the small preview window to show but when I try to open the larger window it just opens a black picture.
Any ideas?
Terminal doesn't show anything either like it does when I open the larger window on wifi.

**Comment by gshewan** [comment]
@tommyd75, yeah I get the same thing. I noticed that the preview default to a 60 second update frequency, instead of 10 seconds when on wifi... so assume it's something to do with HomeKit that changes this.  I'll have a poke around the homebridge-camera-ffmpeg code to see if it's in there.

**Comment by tommyd75** [comment]
Ok. Thanks. Please post here if you find anything can tweak to make it happen.

**Comment by gkirstei** [comment]
For door opening i am using homebridge-http-simple-switch and syntax is like:
{                                                                            
           "accessory": "SimpleHttpSwitch",                                     
           "name": "Gates",                                                     
           "url": "http://xxxx:xxxxxx@192.0.66.15/bha-api/open-doo$
           "default_state_off": true,                                           
           "sendimmediately": "",                                               
           "http_method": "GET"                                                 
       }           

Status always is off - door closed, changes state to open only for moment when you open the gate.

**Comment by tommyd75** [comment]
Ok, I rebooted my phone and now it's showing 640 X 480 video when I'm not at home or turn wifi off. I had to change the settings to 640 X 480. Now the icing on the cake would be how to get notifications and see that live preview on the notification like in the WWDC demo. Does anyone have notifications working on homebridge camera?

**Comment by RealDeemer** [comment]
I have a setup running where the Doorbird Doorbell triggers my Homematic, since that one is connected to homebridge that might work for me. 

However, using the notification request (http://<device-ip>/bha-api/notification.cgi?) can potentially trigger any http url. You just need find a homebridge plugin that can receive such a call in your configuration. 

Since we are now also having full RTSP and SIP available in the Doorbird API, an application as above should be possible.

**Comment by Samfox2** [comment]
Yes it's possible. I made a basic doorbell plugin from infos found on the internet. It's a doorbell accessory that (if placed in a room with a camera) sends such a notification and a snapshot and stream right to the ios screen. For testing purposes the "identify" event is connected as trigger. 

You can find the plugin under: 
https://github.com/Samfox2/homebridge-doorbell

**Comment by gshewan** [comment]
Thanks Samfox2 (snigger), I'll take a look at that!

**Comment by brownad** [comment]
Was it possible to push the event and snapshot to home screen when the doorbird is triggered?

**Comment by RienduPre** [comment]
I tried the plugin of Samfox2, but it doesn't work

**Comment by Samfox2** [comment]
Oh it does work but action is hardcoded to identify command. You need to implement a method that connects the ring action of your doorbird.

**Comment by brownad** [comment]
The doorbird api needs to be tied to this. Either the notification api, monitor or check requests.

Running with notification on my zipato it's worked very well on doorbell event pushing to an http endpoint. Needs some time to make it work. Suggest asking or making a request for the plugin I think a few would want it.  Soon the doorbell to video will be a better experience

**Comment by brownad** [comment]
Crude plugin for Doorbird but does what is needed on Doorbell events, or combine with motion too.  Will make a few more updates so you can experience something tighter inside HomeKit app

https://github.com/brownad/homebridge-doorbird

there is also official support on Zipatile now too

Can probably close this now @nfarina

**Comment by nfarina** [comment]
Awesome! Will reopen if needed.

**Comment by Krishan93** [comment]
I am tried to register a sip User in doorbird. but it has not to work. this way I have been trying. http://192.168.0.12/bha-api/sip.cgi?action=registration&user=ggzvvx0002&password=n7KqC&url=192.168.0.149?http-user=ggzvvx0002&http-password=n7KqC

**Comment by brownad** [comment]
Careful with your credentials..

Also SIP registered to what?  Only the listed SIP devices work as per doobird’s listed integrations.  However if you want to register a user do it from the doorbird app directly it’s documented on the doorbird LAN API.

**Comment by Krishan93** [comment]
this Latest API documentation only.When I register Sip User Ip. here incoming user IP address not changed.that why how to register user. In documentation mentioned like this
http://<deviceip>/bha-api/sip.cgi?
action=registration&user=foo&password=bar&url=192.168.123.22
{
    "BHA": {
        "RETURNCODE": "1",
        "SIP": [
            {
                "ENABLE": "1",
                "PRIORITIZE_APP": "1",
                "REGISTER_URL": "192.168.0.149",
                "REGISTER_USER": "ggzvvx0002",
                "REGISTER_PASSWORD": "n7KqC",
                "AUTOCALL_MOTIONSENSOR_URL": "",
                "AUTOCALL_DOORBELL_URL": "",
                "SPK_VOLUME": "81",
                "MIC_VOLUME": "33",
                "DTMF": "1",
                "relais:1": "",
                "LIGHT_PASSCODE": "",
                "INCOMING_CALL_ENABLE": "1",
                "INCOMING_CALL_USER": "sip:192.168.0.115",
                "ANC": "1",
                "LASTERRORCODE": "408",
                "LASTERRORTEXT": "Request Timeout",
                "RING_TIME_LIMIT": "180",
                "CALL_TIME_LIMIT": "180"
            }
        ]
    }
}

**Comment by brownad** [comment]
What are you trying to achieve with SIP here, what are you registering the doorbird with?  

Look at the doorbird app properly you can add SIP users directly and set permissions for the users in the app avoiding the need to hit the API.

**Comment by Krishan93** [comment]
I am working on third party device driver development. The app allowed the only API permission. In API documentation. any third party wants to communicate to door bird they should follow this way. they mentioned. balance video, image, door open are working fine. This Sip registration only balance.

**Comment by brownad** [comment]
I don’t think homebridge is the right place for doorbird specific questions reach out to doorbird directly they will help you on the driver.
