### ISSUE TITLE
Homebridge ethernet connection and access point

### ISSUE THREAD

**Issue by bworby** [nfarina/homebridge#857]
I was wondering if anyone has had an issue with Homebridge with access point(s). My setup is as follows:

wifi router > switchA 
                  > switchA > homebridge
                  > switchA > Ubiquity AP
                  > switchA > Phillips HUE HUB

*Homebridge running on a Qnap Nas hardwired into a switch. This switch has a wifi router feeding it. It also has a Ubiquity AP connected as well as a Phillips hue hub. 

If my iOS device is connected to the wifi router, I see homebridge and it responds no problem. If I switch to connecting the the AP the iOS device shows homebridge as un-responsive. 

I have tried connecting the AP and homebridge NAS directly to router and turned off the wifi, but that did not work. 

I am having trouble understanding why this would be happening. I have a few other hubs on the switch that are available if you are connected to the router or the AP.

There appears to be something specific about homebridge that doesn't allow for discovery through the AP. 

Any thoughts are appreciated!  

Thanks, 
b

**Comment by iancorbitt** [comment]
Can you access the Qnap when connected via the AP?

**Comment by bworby** [comment]
yes, everything is assessable from router or when connected to AP. I reset my AP this evening and it appears homebridge is now responding when I connect to my AP. I will test this more.

**Comment by iancorbitt** [comment]
Might have been just a odd snafu. Cheers to getting it working.

**Comment by gijoecool** [comment]
Could be a bonjour broadcasting issue. Could you download "Discovery - Bonjour Browser" from the App Store on the iOS device and see if you're able to see homebridge on the iOS device while it's connected to the AP?

**Comment by bworby** [comment]
Its currently working, but ill check out that app. It will help with testing more in the future. I can see it via "Bonjour Browser" on my computer when its connected to AP.
