### ISSUE TITLE
Callback?

### ISSUE THREAD

**Issue by FrankC2000** [nfarina/homebridge#858]
Hi there. How do my device "tells" homebridge some status changing? For instance, lights have been turned off directly. Could you be provide some example? Thanks.

**Comment by lagunacomputer** [comment]
If you turn a lamp off manually, I don't see how homebridge would ever get the message, unless you had somesort of 'smartsocket' that could self monitor electrical usage.  Then that would have to 'report back' via a Homebridge plugin https://www.npmjs.com/search?q=homebridge-plugin
