### ISSUE TITLE
Get npm ERR when install homebridge

### ISSUE THREAD

**Issue by stantang986** [nfarina/homebridge#863]
Raspberry3b jessie
node v6.9.1

when run the `sudo npm install -g --unsafe-perm homebridge`, it shows below:

`npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/KhaosT/node-srp.git /root/.npm/_git-remotes/git-github-com-KhaosT-node-srp-git-7ab735e3: 克隆到裸版本库 '/root/.npm/_git-remotes/git-github-com-KhaosT-node-srp-git-7ab735e3'...
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/KhaosT/node-srp.git /root/.npm/_git-remotes/git-github-com-KhaosT-node-srp-git-7ab735e3: fatal: Could not read from remote repository.
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/KhaosT/node-srp.git /root/.npm/_git-remotes/git-github-com-KhaosT-node-srp-git-7ab735e3: 
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/KhaosT/node-srp.git /root/.npm/_git-remotes/git-github-com-KhaosT-node-srp-git-7ab735e3: Please make sure you have the correct access rights
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/KhaosT/node-srp.git /root/.npm/_git-remotes/git-github-com-KhaosT-node-srp-git-7ab735e3: and the repository exists.
npm ERR! Linux 4.4.21-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "--unsafe-perm" "homebridge"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code 128

npm ERR! Command failed: git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/KhaosT/node-srp.git /root/.npm/_git-remotes/git-github-com-KhaosT-node-srp-git-7ab735e3
npm ERR! 克隆到裸版本库 '/root/.npm/_git-remotes/git-github-com-KhaosT-node-srp-git-7ab735e3'...
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/npm-debug.log
`

how can i fix it, pls help~~~~

**Comment by RXM307** [comment]
Do you have git installed?

try
sudo git clone --template=/root/.npm/_git-remotes/_templates --mirror git://
github.com/KhaosT/node-srp.git /root/.npm/_git-remotes/git-
github-com-KhaosT-node-srp-git-7ab735e3

if that fails install git

sudo apt-get install git

**Comment by stantang986** [comment]
Thank you @RXM307 , but it's still not working
Same output: 
`fatal: Could not read from remote repository.
Please make sure you have the correct access rights
`

"git clone..." for other sources all fine
