### ISSUE TITLE
Searches config.json in wrong directory

### ISSUE THREAD

**Issue by martinb07** [nfarina/homebridge#864]
Hi
After restore a backup to my Rasperry Pi homebridge won't start. I get the following error:

> `module.js:338
>     throw err;
>     ^
> 
> Error: Cannot find module '/usr/local/bin/node/config.json'
>     at Function.Module._resolveFilename (module.js:336:15)
>     at Function.Module._load (module.js:286:25)
>     at Module.require (module.js:365:17)
>     at require (module.js:384:17)
>     at new Server (/usr/local/lib/node_modules/homebridge-server/index.js:16:22)
>     at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:291:32)
>     at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:77:36)
>     at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
>     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
>     at Module._compile (module.js:434:26)`

Please help, to get this awesome tool running again.
Thanks.

**Comment by gshewan** [comment]
@martinb07 Try starting homebridge with the -U switch and the location of the config.json, e.g.:
homebridge -U /var/homebridge

**Comment by martinb07** [comment]
I reinstalled installed homebridge and now it works again, like a charm.
