### ISSUE TITLE
Failed at the bignum@0.12.5 install script

### ISSUE THREAD

**Issue by dasoutherland** [nfarina/homebridge#869]
Hello all, starting to pull my hair out. I've tried to install home bridge but keep hitting the road block of node and npm versions. Any help would be appreciated. I have also tried to remove and reinstall node and npm but it just won't update to the newer versions. 

npm ERR! Linux 4.4.26+
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "homebridge"
npm ERR! node v0.10.29
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! bignum@0.12.5 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bignum@0.12.5 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bignum package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bignum
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bignum
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/npm-debug.log

**Comment by KhaosT** [comment]
```
npm ERR! node v0.10.29
```
You are still using node 0.10.29... Try install node v6.x using the following command

```
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y nodejs
```

**Comment by dasoutherland** [comment]
Thank you for the quick reply. I ran that command. Here is the outcome.

`pi@raspberrypi:~ $ curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -


## Installing the NodeSource Node.js v6.x repo...


## You appear to be running on ARMv6 hardware. Unfortunately this is not currently supported by the NodeSource Linux distributions. Please use the 'linux-armv6l' binary tarballs available directly from nodejs.org for Node.js v4 and later.

pi@raspberrypi:~ $ sudo apt-get install -y nodejs
Reading package lists... Done
Building dependency tree       
Reading state information... Done
nodejs is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.`

**Comment by KhaosT** [comment]
Ah, you are running on the old raspberry pi. Have you tried using ``n`` to switch version? https://www.npmjs.com/package/n

**Comment by dasoutherland** [comment]
I just followed this tut.
https://blog.wia.io/installing-node-js-v4-0-0-on-a-raspberry-pinode -v 
now shows V4.0.0

**Comment by KhaosT** [comment]
I'd afraid you need at least 4.5 or higher... you can try to follow the same article and replace 4.0.0 with 6.9.1

**Comment by dasoutherland** [comment]
Ya, 
looks like its wanting at least 4.3.2 
engine homebridge@0.4.6: wanted: {"node":">=4.3.2"} (current: {"node":"4.0.0","npm":"2.14.2"})

**Comment by dasoutherland** [comment]
I followed the same tut but went with v5. so far so good.

**Comment by dasoutherland** [comment]
Ran into some snags. Looks npm is also outdated. 
I will try again when I get home later today. Thanks.

**Comment by mehrdadnavid** [comment]
edit package.json and bignum 0.13.0
