### ISSUE TITLE
Installing Homebridge on Raspberry Pi using puppet

### ISSUE THREAD

**Issue by dustinrue** [nfarina/homebridge#872]
I created a puppet module that simplifies the installation of Homebridge on a Raspberry Pi running Raspbian Jessie. It's located at https://forge.puppet.com/dustinrue/homebridgepi. Not sure if this is something that interests people so I didn't want to simply update the wiki.

**Comment by EMCSizl** [comment]
I Was just starting to look into this for homebridge on docker.  I'll take a look when I get a chance thanks!

**Comment by dustinrue** [comment]
I tested it on Ubuntu 16.04 and it failed. Pretty sure it's because I need to pin packages or set priorities but with some effort it could be made to work for more distros.

**Comment by cgHome** [comment]
Try my one: https://github.com/cgHome/cflat but is still alpha

**Comment by Glavin001** [comment]
I use Resin.io (with Docker) for deploying to Raspberry Pi: https://github.com/Glavin001/resin-homebridge
