### ISSUE TITLE
DEBUG=* How do I access the log ?

### ISSUE THREAD

**Issue by KmanOz** [nfarina/homebridge#873]
Hi

I am trying to debug an issue with the HomeBridge-HomeAssistant plugin and have installed NPM DEBUG. When I run HomeBridge with the command 'DEBUG=\* homebridge' I can see the console is in debug mode but I am unsure where the log is written or if in fact it is written at all.

Can someone please point me in the right direction to get DEBUG writing to a log file that can be analyzed later?

Thanks in advance

**Comment by snowdd1** [comment]
see https://github.com/nfarina/homebridge/issues/881

It is not written until you route it to a file - but then you wouldn't see it in the console.

If you are using **bash** (or compatible) as console, you can:  
- redirect stdout `DEBUG=* homebridge > file.ext`  
- redirect stderr `DEBUG=* homebridge 2> file.ext`  
- redirect both `DEBUG=* homebridge &> file.ext`

**Comment by KmanOz** [comment]
Thank you. Yep it's bash.

**Comment by deboy69** [comment]
[6/8/2020, 12:28:36 PM] [Thermostat] ERROR: pollDevices 
[1591640917255] INFO  (886 on homebridge): incoming request
    reqId: 6
    req: {
      "method": "GET",
      "url": "/api/plugins",
      "hostname": "192.168.1.XXX:8581",
      "remoteAddress": "::ffff:192.168.1.XX",
      "remotePort": 58217
