### ISSUE TITLE
Fetching HomeAssistant devices.

### ISSUE THREAD

**Issue by shihw** [nfarina/homebridge#875]
Fetching HomeAssistant devices.
Failed getting devices: Error: connect ECONNREFUSED 192.168.199.175:8123. Retrying...

My terminal has been prompted this.How to solve it. thank you

**Comment by Nitee** [comment]
I got this issue once I installed DuckDNS and started a cron job while setting up letsencrypt also. Did you do the same?

**Comment by shihw** [comment]
OK, I'll try it. Thank you.
