### ISSUE TITLE
Error while starting homebridge

### ISSUE THREAD

**Issue by bhaap** [nfarina/homebridge#878]
Hi im getting this error while trying to start homebridge 

/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/mdns/lib/dns_sd.js:35

throw ex;
^

Error: Module did not self-register.
at Error (native)
at Object.Module._extensions..node (module.js:597:18)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at Object. (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/mdns/lib/dns_sd.js:24:20)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)

**Comment by BeardedSimmo** [comment]
Are you trying to start the node in the correct folder?

/homebridge/bin

**Comment by bhaap** [comment]
No. I did not know this was required. Will try it

**Comment by bhaap** [comment]
I am unable to find /homebridge/bin

the folders i have containing homebridge is:

/home/****/.npm/homebridge
/home/******/.npm/registry.npmjs.org/homebridge
/tmp/npm-52118-73751d66/registry.npmjs.org/homebridge
/usr/bin/homebridge
/usr/lib/node_modules/homebridge
/usr/lib/node_modules/homebridge/bin/homebridge
/usr/local/bin/homebridge
/usr/local/lib/node_modules/homebridge
/usr/local/lib/node_modules/homebridge/bin/homebridge

**Comment by ericcirone** [comment]
I too am getting this issue after upgraded to LTS 6.9.1 and doing a homebridge update.

**Comment by bhaap** [comment]
Im also running nodejs 6.9.1.

hmm wonder if it will work with an older version then, is there an easy way to downgrade?

**Comment by ericcirone** [comment]
So all i did was npm -g uninstall homebridge and then npm -g install homebridge and it all worked again for me.

**Comment by bhaap** [comment]
That did not fix it for me, did you have to run the command as su? I had to because /usr/lib/node_modules is owned by root.

Is this correct?

**Comment by ericcirone** [comment]
I'm on a Mac. This is what I did.

1. Download new LTS 6.9.1 package from nodejs.org
2. Install
3. Fix permissions `sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules,bin,share}`
4. Update NPM `npm -g install npm`
5. Uninstall homebridge `npm -g uninstall homebridge`
6. Install homebridge `npm -g install homebridge`

Every time i update Node i do 1-4. This time to get homebridge working i did 5 and 6.

**Comment by bhaap** [comment]
Tried that aswell. Same issue :(

**Comment by bhaap** [comment]
Im getting a new rPI soon so im gonna try a fresh install on that one and see if I can get that to work as i am unable to reinstall the current linux computer running other stuff aswell

**Comment by bhaap** [comment]
So after using nvm to run nodejs 6.8.0 and removing everything that had homebridge in the name on the system after a sudo npm -g uninstall homebridge i finally ran npm -g install homebridge and got the app to run. Guessing there is some compability-error with the newest nodejs?
