### ISSUE TITLE
homebridge does not create homebridge.log & homebridge.err

### ISSUE THREAD

**Issue by juergenschubert** [nfarina/homebridge#881]
Folks,
I do have 
$ gcc --version
gcc (Raspbian 4.9.2-10) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
$ node -v
v5.0.0
$ uname -a
Linux homebridge 4.4.26+ #915 Thu Oct 20 17:02:14 BST 2016 armv6l GNU/Linux
and my /var/log looks like:
$ ls -l /var/log
total 1256
-rw-r--r-- 1 root root  19327 Oct 30 19:17 alternatives.log
drwxr-xr-x 2 root root   4096 Sep 23 02:25 apt
-rw-r--r-- 1 root root   7022 Oct 30 19:07 aptitude
-rw-r----- 1 root adm   18044 Oct 30 19:54 auth.log
-rw-r--r-- 1 root root   4803 Oct 30 17:18 boot.log
-rw-r--r-- 1 root root  74647 Sep 23 02:24 bootstrap.log
-rw------- 1 root utmp   1536 Oct 30 17:17 btmp
-rw-r----- 1 root adm   50516 Oct 30 19:54 daemon.log
-rw-r----- 1 root adm    3114 Oct 30 17:18 debug
-rw-r----- 1 root adm      31 Sep 23 02:23 dmesg
-rw-r--r-- 1 root root 423980 Oct 30 19:19 dpkg.log
-rw-r--r-- 1 root root  24024 Oct 30 19:19 faillog
-rw-r--r-- 1 root root    751 Oct 30 19:15 fontconfig.log
drwxr-xr-x 2 root root   4096 Sep 23 02:23 fsck
-rw-r----- 1 root adm   67901 Oct 30 17:18 kern.log
-rw-rw-r-- 1 root utmp 292292 Oct 30 19:19 lastlog
-rw-r----- 1 root adm   74129 Oct 30 19:53 messages
drwxr-xr-x 2 ntp  ntp    4096 Jul 25 22:36 ntpstats
-rw-r--r-- 1 root root    543 Oct 30 17:16 regen_ssh_keys.log
drwxr-x--- 2 root adm    4096 Jun  1 15:17 samba
-rw-r----- 1 root adm  128467 Oct 30 19:54 syslog
-rw-r----- 1 root adm    6864 Oct 30 19:52 user.log
drwxr-xr-x 2 root root   4096 Oct 30 19:17 wicd
-rw-rw-r-- 1 root utmp  10368 Oct 30 18:43 wtmp

so where do I get the logs from homebridge?

**Comment by snowdd1** [comment]
Hallo Jürgen, 
How do you start homebridge? Homebridge writes to stdout and stderr, those are dependent on how you invoke the process. I start it as a service in productive use, and have all output routed to the systemd's log; the development instance is started via console shell file and prints everything to the console.

**Comment by juergenschubert** [comment]
Hi Snowdd1,
I am in the experient phase, so I start it manual after I log into as User PI from the commandline.
So I do see all the events. Struggle on .... there is no log or err file and thougth I do  miss and configuration. Do you have a tutorial you used to start your homebridge on reboot? Just wonder what an how you use homebridge.

**Comment by snowdd1** [comment]
Hi Jürgen,
guessing from your name I assume you can read German? I found a nice article here:  https://www.boernyblog.de/knx-homekit-anbindung-mit-raspberry-pi-kurzanleitung/
If you don't happen to have KNX, just skip the parts about *homebridge-knx* and *knxd*  
Good luck
Raoul

**Comment by RXM307** [comment]
>
> From the Wiki
>
https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi#running-homebridge-on-bootup-initd

**Comment by snowdd1** [comment]
Depends on his raspbian, could be on systemd already, then the section before is more valuable to him: https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi#running-homebridge-on-bootup-systemd

**Comment by juergenschubert** [comment]
Thanks everybody. it is running now. ANY Idea how I get the baby to write logs into homebridge.log?

**Comment by Kolbi** [comment]
I encounter the same issue. Homebridge is working but no logs?

**Comment by snowdd1** [comment]
MY homebridge is set up as a service in systemd and writes its log (together with all other processes) in `/var/log/daemon.log`

I can either use something `sudo journalctl --unit=homebridge.service --since=2016-11-01` or just tail it with `tail -F /var/log/daemon.log` 

For setup, I used above [methods](https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi#running-homebridge-on-bootup-systemd).

**Comment by iDevo** [comment]
Hi there! I just switched from initd to systemd, because of the autostart functionality. Just to get this straight, there is no other chance to get logs than parsing `sudo journalctl --unit=homebridge.service --since=2017-12-01`? 

For me it's confusing because I was used to the great log functionality with the two separated .sys and .err log files. Is there a way to launch Homebridge using systemd *and* logging everything into the files located in `/var/log/homebridge.`?

**Comment by Erokani** [comment]
Hi iDevo,
I'd like the same. Could not find helpful hint on the net. Any help welcomed guys :)

**Comment by joelsdc** [comment]
+1 on logging to homebridge.log and homebridge.err

**Comment by divineblade7** [comment]
i cant seem to find where logs are saved for windows or how to get logs saved either. im sure im missing something obvious.

**Comment by ferazambuja** [comment]
Same here. Files are nowhere to be found. I'm not running any bootup..

**Comment by jeffl78** [comment]
Same, need them to get a token from homebridge-nest

**Comment by J4YRY4N** [comment]
How is this closed? There’s no solution here!

**Comment by jeffl78** [comment]
I did get it working internally but because of this and other issues I migrated to home assistant.  I like it but it has its own set of challenges, mainly if you want ssl remote access.
