### ISSUE TITLE
SSH Plugin

### ISSUE THREAD

**Issue by fboulegue** [nfarina/homebridge#883]
I did try to find a ssh plugin all i want to do is send a ssh command for "on" and one for "off"
https://github.com/alexguev/homebridge-ssh
but i did not get it to work with my following information,

```
"accessories": [
    {
              "accessory": "SSH",
              "name": „Ambilight",
              "on": „sudo reboot",
              "off": „sudo kill 2244",
              "state": "",
              "on_value" : "",
              "exact_match":,
              "ssh": {
                "user": „pi",
                "host": „192.168.2.22",
                "port": 22,
                "password": „raspberry",
                "key": ""
              }
    }
]
```

anyone ever got this plugin working?

**Comment by snowdd1** [comment]
Your quotes are broken. Use another text editor, that doesn't try to be *smart* about the quotes.  
That isn't literature, that's coding.

See here: 

`"on": „sudo reboot",` instead of  
`"on": "sudo reboot",`   

And that's in multiple lines.

**Comment by fboulegue** [comment]
sorry this was already fixed :-) just was a error after copy from pi into github :( so it still seem to be something else

**Comment by AppleTechy** [comment]
Not sure if you actually needed the SSH part of it but here is a plugin to trigger any actions in CMD or Terminal. (https://www.npmjs.com/package/homebridge-cmdswitch2). Part of your issue with the SSH plugin may be due to it being 2 years old
