### ISSUE TITLE
Node 7 Support

### ISSUE THREAD

**Issue by macjeff** [nfarina/homebridge#884]
I upgraded NODE accidentally from 6.x to 7.0 when I was trying to upgrade to 6.91 which fixed some permissions issues when installing plugins under OS X.

I received errors that parts were compiled under 6.x so I downloaded the installer for 6.9.1 and it worked great.

Are you going to release support for NODE 7 or is there no reason to upgrade to it anyways. 

Sorry if this is a stupid (or already asked) question but just trying to know the facts.

Jeff

**Comment by thib5** [comment]
I think i may have the same issue as you ... how do you downgrade to 6.9.1 ? 

Thanks

**Comment by sholzmayer** [comment]
Did you remove all old binaries (as you can see http://stackoverflow.com/a/22458067/2013798)?

**Comment by thoduh** [comment]
Node 7 is working fine, but you must delete homebridge and all plugins first.

**Comment by macjeff** [comment]
any reason to upgrade if all is working?

Jeff

**Comment by thoduh** [comment]
No
