### ISSUE TITLE
Garage door opener showing as just a switch in HomeKit

### ISSUE THREAD

**Issue by marcgetter** [nfarina/homebridge#885]
I have HomeBridge setup connecting to my VeraPlus using homebridge-vera.  It seems to be working ok for lights and basic sensors, but the Garage door is showing up incorrectly.  It's being detected as a Switch that is on when the door is closed and off when it's open.  Presumably because of the tilt switch.  Is there a way to get my Linear Garage Door opener (GD00Z) to be recognized correctly in HomeKit?

**Comment by snowdd1** [comment]
You should ask the question at the `homebridge-vera` repository. I guess the Vera plugin has no native support for garage door openers, it uses the switch as work-around. 

@damianxd isn't that yours?

**Comment by damianxd** [comment]
Yes it is, but I haven't done much on garage doors since I don't have a way to test those. I will try to improve that for a next version

**Comment by marcgetter** [comment]
Since I'm still new to all this, I ended up rearranging my whole ecosystem.  I sent the VeraPlus back and I'm now using a Wink 2 connected to HomeAssistant. Then using HomeBridge to pull the devices to HomeKit. Garage door is showing up correctly now.

**Comment by jonsteinmetz** [comment]
I have a ZWave garage door opener and a VeraPlus, @damianxd is there anything I could do to help get this implemented? Thanks.

**Comment by AppleTechy** [comment]
Could you please create an issue on the Homebridge-Vera plugin page. This override would need to be implemented  in the plugin.
