### ISSUE TITLE
Suddenly rooms no longer recognized

### ISSUE THREAD

**Issue by drewcovi** [nfarina/homebridge#888]
Any idea why rooms would suddenly go unrecognized? Rooms and groups return with "I don't understand" "can you use another word?"

**Comment by Apollon77** [comment]
duplicate to #874?

**Comment by drewcovi** [comment]
I don't think so... everything in the Home app appears to be correct. It's actually just Siri that's growing senile. And devices still work fine. Just rooms and group names are not recognized when spoken.

**Comment by drewcovi** [comment]
I have a call with Apples beta team today to see if its on their end or somehow related to this. I'm pretty sure it's on their end.

**Comment by justme-1968** [comment]
i think these problems are on apples side.

for example with ios10 it is now possible to have devices with the same name. so i named all my sonos players radio. that worked fine. suddenly radio was no longer recognized for switching on. but still for switching off. then switching off stopped working. and now both work again. without any changes on my side.

**Comment by pierrenicolasr** [comment]
Same here - with French siri. Tried latest beta (on watch, iPhone and the iPad used as central), same issue. Scenes / switches are working fine from the app, but siri is not able to understand them anymore

**Comment by jjiburg** [comment]
Just tested with two devices, one running 10.1 and the other 10.2 PB1. Device running 10.1 can issue commands using rooms without issue, such as "turn living room lights off". Device running 10.2 PB1 fails 100% of the time.

**Comment by rehafer** [comment]
Same with me, Siri doesn't recognize devices with 10.2 PB1. I asked Siri to 'turn on the Tower Lamp' was interpreted as 'power lamp' and turned on lights all over the house

**Comment by drgonz0** [comment]
I had the same thing with 10.2. Beta 1.  Sadly 10.2 beta 1 fixes an issue with home bridge cameras, but totally broke all SIRI Homekit room names, and scenes.  Rolled back.

**Comment by drewcovi** [comment]
Yay! Beta 2 landed and it's fixed!
