### ISSUE TITLE
status not updated, only when entering and leaving home app (iKettle / Smarter Coffee devices)

### ISSUE THREAD

**Issue by Tristan79** [nfarina/homebridge#894]
Hi!

I'm trying to use homebridge to bridge between an iKettle (and Smarter Coffee) using
https://github.com/Tristan79/iBrew (my own code), I currently use cmdSwitch2 (as recommended by another ibrew user), but there is a little situation.
 
I can get the kettle on/off and I can get status of the device... but the status only changed sometimes, but it does reflect the proper status when I leave the home app and open it again (I see the home app update the status). So I do not know if cmdSwitch2 is the right way to go...

Is there a way to push status changed to homebridge that it reflects the change? Or an example for polling it such that the status in the home app reflects the actual status? Or any hints how to do this?

**Comment by snowdd1** [comment]
In my plug-in I am using event handlers that are triggered by my bus system to update the value of characteristics:

https://github.com/snowdd1/homebridge-knx/blob/plugin-2.0/lib/knxaccess.js#L278

Using the setValue() method of characteristic updates the value of the object, and also triggers events to all registered listeners - and almost all HomeKit app registers themselves when opened (you can see the registering process if you start homebridge in debug mode).

Good luck with your plug-in!

**Comment by bhaap** [comment]
Sadly the dev did not feel the need to implement event polling. 

Anyone want to create a fork and see if they can implement it? Im not a js dev so im shooting blind if i was to try :P

https://github.com/luisiam/homebridge-cmdswitch2/issues/4

**Comment by Tristan79** [comment]
Happily he did... :-) https://github.com/luisiam/homebridge-cmdswitch2

**Comment by erfinb** [comment]
Greetings, 

I was wondering if you could help with the homebridge-people plugin as we are having a similar issue where the status is only checked when the Home app is opened. Could you all take a look and help us out?

Ethan

**Comment by bhaap** [comment]
You could check out how homebridge-cmdswitch2 did it here:

https://github.com/luisiam/homebridge-cmdswitch2/commit/c5378c9402b64cf81017234ea06f2fc85eecd0f8
