### ISSUE TITLE
Debug breakpoint malloc_error_break

### ISSUE THREAD

**Issue by rooi** [nfarina/homebridge#895]
Hi,

Homebridge crashes quite frequently. This is probably due to a plugin, but I cannot get good indications on what causes it exactly (even with homebridge in debug mode). Most times it crashes with a segmentation fault 11, but sometimes with  the one below. I think this can be used to find the issue and solve it, but I don't know how to set malloc_error_break breakpoints in combination with homebridge.

Any pointers? Thx!

homebridge(21335,0x7fffc452c3c0) malloc: *** error for object 0x1020a3838: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6

**Comment by KhaosT** [comment]
🤔 are there more logs or something like a full crash report?

**Comment by rooi** [comment]
i've got this debug log earlier from a while ago for the segmentation fault:

Accessory [Foscam C2] Processing characteristic set: [{"aid":1,"iid":35,"ev":true}] +0ms
Accessory [Foscam C2] Registering Characteristic "Streaming Status" for events +0ms
EventedHTTPServer [::ffff:10.0.1.9] HTTP Response is finished +0ms
EventedHTTPServer [::ffff:10.0.1.9] HTTP request: /characteristics +3ms
HAPServer [C2:2D:FB:F3:9B:26] HAP Request: PUT /characteristics +1ms
Accessory [Foscam C2] Processing characteristic set: [{"aid":1,"iid":28,"ev":true}] +0ms
Accessory [Foscam C2] Registering Characteristic "Streaming Status" for events +0ms
EventedHTTPServer [::ffff:10.0.1.9] HTTP Response is finished +0ms
EventedHTTPServer [::ffff:10.0.1.9] HTTP request: /characteristics +4m
HAPServer [C2:2D:FB:F3:9B:26] HAP Request: PUT /characteristics +0ms
Accessory [Foscam C2] Processing characteristic set: [{"aid":1,"iid":44,"ev":true}] +0ms
Accessory [Foscam C2] Registering Characteristic "Motion Detected" for events +0ms
EventedHTTPServer [::ffff:10.0.1.9] HTTP Response is finished +1ms
EventedHTTPServer [::ffff:10.0.1.9] HTTP request: /characteristics +4ms
HAPServer [C2:2D:FB:F3:9B:26] HAP Request: PUT /characteristics +0ms
Accessory [Foscam C2] Processing characteristic set: [{"aid":1,"iid":14,"ev":true}] +0ms
Accessory [Foscam C2] Registering Characteristic "Streaming Status" for events +0ms
EventedHTTPServer [::ffff:10.0.1.9] HTTP Response is finished +0ms
EventedHTTPServer [::ffff:10.0.1.9] HTTP request: /characteristics?id=1.14 +5ms
HAPServer [C2:2D:FB:F3:9B:26] HAP Request: GET /characteristics?id=1.14 +0ms
Accessory [Foscam C2] Getting value for Characteristic "Streaming Status" +0ms
Accessory [Foscam C2] Got Characteristic "Streaming Status" value: AQEA +0ms
EventedHTTPServer [::ffff:10.0.1.9] HTTP Response is finished +0ms
EventedHTTPServer [::ffff:10.0.1.9] HTTP request: /characteristics?id=1.21 +5ms
HAPServer [C2:2D:FB:F3:9B:26] HAP Request: GET /characteristics?id=1.21 +0ms
Accessory [Foscam C2] Getting value for Characteristic "Streaming Status" +0ms
Accessory [Foscam C2] Got Characteristic "Streaming Status" value: AQEA +0ms
EventedHTTPServer [::ffff:10.0.1.9] HTTP Response is finished +1ms
EventedHTTPServer [::ffff:10.0.1.9] HTTP request: /characteristics?id=1.35 +3ms
HAPServer [C2:2D:FB:F3:9B:26] HAP Request: GET /characteristics?id=1.35 +0ms
Accessory [Foscam C2] Getting value for Characteristic "Streaming Status" +0ms
Accessory [Foscam C2] Got Characteristic "Streaming Status" value: AQEA +0ms
EventedHTTPServer [::ffff:10.0.1.9] HTTP Response is finished +0ms
EventedHTTPServer [::ffff:10.0.1.9] HTTP request: /characteristics?id=1.28 +6ms
HAPServer [C2:2D:FB:F3:9B:26] HAP Request: GET /characteristics?id=1.28 +0ms
Accessory [Foscam C2] Getting value for Characteristic "Streaming Status" +0ms
Accessory [Foscam C2] Got Characteristic "Streaming Status" value: AQEA +0ms
EventedHTTPServer [::ffff:10.0.1.9] HTTP Response is finished +0ms
EventedHTTPServer [::ffff:10.0.1.9] HTTP request: /characteristics +4ms
HAPServer [C2:2D:FB:F3:9B:26] HAP Request: PUT /characteristics +0ms
Accessory [Foscam C2] Processing characteristic set: [{"aid":1,"iid":21,"ev":true}] +0ms
Accessory [Foscam C2] Registering Characteristic "Streaming Status" for events +0ms
EventedHTTPServer [::ffff:10.0.1.9] HTTP Response is finished +0ms
EventedHTTPServer [::ffff:10.0.1.9] HTTP request: /characteristics +3ms
HAPServer [C2:2D:FB:F3:9B:26] HAP Request: PUT /characteristics +0ms
Accessory [Foscam C2] Processing characteristic set: [{"aid":1,"iid":35,"ev":true}] +0ms
Accessory [Foscam C2] Registering Characteristic "Streaming Status" for events +0ms
EventedHTTPServer [::ffff:10.0.1.9] HTTP Response is finished +1ms
EventedHTTPServer [::ffff:10.0.1.9] HTTP request: /characteristics +3ms
HAPServer [C2:2D:FB:F3:9B:26] HAP Request: PUT /characteristics +0ms
Accessory [Foscam C2] Processing characteristic set: [{"aid":1,"iid":28,"ev":true}] +0ms
Accessory [Foscam C2] Registering Characteristic "Streaming Status" for events +0ms
EventedHTTPServer [::ffff:10.0.1.9] HTTP Response is finished +0ms
EventedHTTPServer [::ffff:10.0.1.9] HTTP request: /characteristics?id=1.14 +2m
HAPServer [C2:2D:FB:F3:9B:26] HAP Request: GET /characteristics?id=1.14 +0ms
Accessory [Foscam C2] Getting value for Characteristic "Streaming Status" +0ms
Accessory [Foscam C2] Got Characteristic "Streaming Status" value: AQEA +0ms
EventedHTTPServer [::ffff:10.0.1.9] HTTP Response is finished +0ms
EventedHTTPServer [::ffff:10.0.1.9] HTTP request: /characteristics?id=1.21 +3ms
HAPServer [C2:2D:FB:F3:9B:26] HAP Request: GET /characteristics?id=1.21 +0ms
Accessory [Foscam C2] Getting value for Characteristic "Streaming Status" +1ms
Accessory [Foscam C2] Got Characteristic "Streaming Status" value: AQEA +0ms
EventedHTTPServer [::ffff:10.0.1.9] HTTP Response is finished +0ms
EventedHTTPServer [::ffff:10.0.1.9] HTTP request: /characteristics?id=1.35 +3ms
HAPServer [C2:2D:FB:F3:9B:26] HAP Request: GET /characteristics?id=1.35 +0ms
Accessory [Foscam C2] Getting value for Characteristic "Streaming Status" +0ms
Accessory [Foscam C2] Got Characteristic "Streaming Status" value: AQEA +0ms
EventedHTTPServer [::ffff:10.0.1.9] HTTP Response is finished +0ms
EventedHTTPServer [::ffff:10.0.1.9] HTTP request: /characteristics?id=1.28 +4ms
HAPServer [C2:2D:FB:F3:9B:26] HAP Request: GET /characteristics?id=1.28 +0ms
Accessory [Foscam C2] Getting value for Characteristic "Streaming Status" +0ms
Accessory [Foscam C2] Got Characteristic "Streaming Status" value: AQEA +0ms
EventedHTTPServer [::ffff:10.0.1.9] HTTP Response is finished +0ms
EventedHTTPServer [::ffff:10.0.1.9] HTTP request: /characteristics +10ms
HAPServer [C2:2D:FB:F3:9B:26] HAP Request: PUT /characteristics +0ms
Accessory [Foscam C2] Processing characteristic set: [{"aid":1,"iid":44,"ev":true}] +0ms
Accessory [Foscam C2] Registering Characteristic "Motion Detected" for events +0ms
EventedHTTPServer [::ffff:10.0.1.9] HTTP Response is finished +1ms
EventedHTTPServer [::ffff:10.0.1.9] HTTP request: /characteristics +3ms
HAPServer [C2:2D:FB:F3:9B:26] HAP Request: PUT /characteristics +0ms
Accessory [Foscam C2] Processing characteristic set: [{"aid":1,"iid":14,"ev":true}] +1ms
Accessory [Foscam C2] Registering Characteristic "Streaming Status" for events +0ms
EventedHTTPServer [::ffff:10.0.1.9] HTTP Response is finished +0ms
EventedHTTPServer [::ffff:10.0.1.9] HTTP request: /characteristics +4ms
HAPServer [C2:2D:FB:F3:9B:26] HAP Request: PUT /characteristics +0ms
Accessory [Foscam C2] Processing characteristic set: [{"aid":1,"iid":21,"ev":true}] +0ms
Accessory [Foscam C2] Registering Characteristic "Streaming Status" for events +0ms
EventedHTTPServer [::ffff:10.0.1.9] HTTP Response is finished +1ms
EventedHTTPServer [::ffff:10.0.1.9] HTTP request: /characteristics +3ms
HAPServer [C2:2D:FB:F3:9B:26] HAP Request: PUT /characteristics +0ms
Accessory [Foscam C2] Processing characteristic set: [{"aid":1,"iid":35,"ev":true}] +1ms
Accessory [Foscam C2] Registering Characteristic "Streaming Status" for events +0ms
EventedHTTPServer [::ffff:10.0.1.9] HTTP Response is finished +0ms
EventedHTTPServer [::ffff:10.0.1.9] HTTP request: /characteristics +8ms
HAPServer [C2:2D:FB:F3:9B:26] HAP Request: PUT /characteristics +0ms
Accessory [Foscam C2] Processing characteristic set: [{"aid":1,"iid":28,"ev":true}] +0ms
Accessory [Foscam C2] Registering Characteristic "Streaming Status" for events +0ms
EventedHTTPServer [::ffff:10.0.1.9] HTTP Response is finished +0ms
EventedHTTPServer [::ffff:10.0.1.11] Client connection closed +24s
EventedHTTPServer [::ffff:10.0.1.11] HTTP connection was closed +0ms
EventedHTTPServer [::ffff:10.0.1.11] HTTP server was closed +0ms
EventedHTTPServer [::ffff:10.0.1.11] Client connection closed +2ms
EventedHTTPServer [::ffff:10.0.1.11] HTTP connection was closed +0ms
EventedHTTPServer [::ffff:10.0.1.11] HTTP server was closed +0ms
EventedHTTPServer [::ffff:10.0.1.11] New connection from client +4s
EventedHTTPServer [::ffff:10.0.1.11] HTTP server listening on port 60500 +0ms
EventedHTTPServer [::ffff:10.0.1.11] HTTP request: /pair-verify +2ms
HAPServer [C2:2D:FB:F3:9B:26] HAP Request: POST /pair-verify +0ms
HAPServer [C2:2D:FB:F3:9B:26] Pair verify step 1/2 +0ms
EventedHTTPServer [::ffff:10.0.1.11] HTTP Response is finished +1ms
EventedHTTPServer [::ffff:10.0.1.11] New connection from client +16ms
EventedHTTPServer [::ffff:10.0.1.11] HTTP server listening on port 60502 +1ms
EventedHTTPServer [::ffff:10.0.1.11] HTTP request: /pair-verify +1ms
HAPServer [CC:22:3D:E3:CE:32] HAP Request: POST /pair-verify +0ms
HAPServer [CC:22:3D:E3:CE:32] Pair verify step 1/2 +0ms
EventedHTTPServer [::ffff:10.0.1.11] HTTP Response is finished +1ms
EventedHTTPServer [::ffff:10.0.1.11] HTTP request: /pair-verify +20ms
HAPServer [C2:2D:FB:F3:9B:26] HAP Request: POST /pair-verify +1ms
HAPServer [C2:2D:FB:F3:9B:26] Pair verify step 2/2 +0ms
HAPServer [C2:2D:FB:F3:9B:26] Client E3EE11F8-1908-4356-BB34-82463474C31D verification complete +0ms
EventedHTTPServer [::ffff:10.0.1.11] HTTP Response is finished +0ms
EventedHTTPServer [::ffff:10.0.1.11] HTTP request: /accessories +5ms
HAPServer [C2:2D:FB:F3:9B:26] HAP Request: GET /accessories +0ms
EventedHTTPServer [::ffff:10.0.1.11] HTTP Response is finished +1ms
EventedHTTPServer [::ffff:10.0.1.11] HTTP request: /pair-verify +6ms
HAPServer [CC:22:3D:E3:CE:32] HAP Request: POST /pair-verify +0ms
HAPServer [CC:22:3D:E3:CE:32] Pair verify step 2/2 +0ms
HAPServer [CC:22:3D:E3:CE:32] Client E3EE11F8-1908-4356-BB34-82463474C31D verification complete +0ms
EventedHTTPServer [::ffff:10.0.1.11] HTTP Response is finished +1ms
EventedHTTPServer [::ffff:10.0.1.11] HTTP request: /accessories +3ms
HAPServer [CC:22:3D:E3:CE:32] HAP Request: GET /accessories +0ms
Segmentation fault: 11

**Comment by rooi** [comment]
Using latest homebridge, and nodejs 6.9.1 BTW

**Comment by KhaosT** [comment]
interesting, does this crash only start recently or have you always experience something like this?

**Comment by rooi** [comment]
It crashed after running for about a day (sometime more frequently). It started after upgrading nodejs to 6.9.1 from a 4... version, but I also upgraded my plugins (it seemed to work fine after the upgrade ;).
