### ISSUE TITLE
tail homebridge.log & homebridge.err returns "No such file or directory"

### ISSUE THREAD

**Issue by RickNunn** [nfarina/homebridge#897]
I have just got homebridge up and running on a Pi Zero. However Homebridge crashed overnight (Pi was running fine and Homebridge started straight away with the command) so I went to check the error logs. I ran both `tail -f /var/log/homebridge.log` and `tail -f /var/log/homebridge.err` but they both returned `tail: cannot open ‘/var/log/homebridge.log’ for reading: No such file or directory`

Any ideas why these wouldn't be written? 

```
Homebridge: 0.4.7
Node: v6.8.0
Distributor ID: Raspbian
Description: Raspbian GNU/Linux 8.0 (jessie)
Release: 8.0
Codename: jessie
```

**Comment by snowdd1** [comment]
Hi @RickNunn 
how do start homebridge? The redirection of stdout and stderr to files depends on your start command.

This might be a duplicate to https://github.com/nfarina/homebridge/issues/881

**Comment by RickNunn** [comment]
Definitely looks to be a duplicate, I shall close this one down.
