### ISSUE TITLE
Issues - general

### ISSUE THREAD

**Issue by duecedriver** [nfarina/homebridge#904]
Perhaps I am not doing something right so here is an overview

Setup
VM running Home-assistant - openzwave - homebridge - home assistant plugin

Ubuntu server 16.04

After much trial and error and having to setup avahi and some other issues. I have basic functionality where ios Home on ios 10 saw my homebridge and. I was able to add it brining in only 7 devices which are really just 3 lights and some scenes around those lights

Smoke alarms did not come over --- Bug, not supported?

Everything just comes into home tagged as default ... more on that later

If I edit each light in more and select room to living room they move from default to living room - great

After a reboot of the server --- the living room goes away .. all devices are re imported into Home under default

Any scenes built in home like the standard 'good night' go away as well and have to be redone?

What am I doing wrong... ?

Thanks!!

**Comment by kolossboss** [comment]
Try to install home assistant directly from git for the newest version

npm install -g home-assistant/homebridge-homeassistant
