### ISSUE TITLE
 Unreachable after stopping and restarting homebridge

### ISSUE THREAD

**Issue by cflurin** [nfarina/homebridge#91]
Hi,

I've installed homebridge on a Mac mini (OS X 10.10.4) and I'm using the EVE App on my iPhone 6 (iOS 8.4). It works fine, however after restarting homebridge EVE shows the message "unreachable".
In order to reactivate the communication I've to restart (power off/on) my iPhone.
 
For testing I just defined a simple Dummy.js Accessory.

**Comment by nfarina** [comment]
Hello - most of HomeBridge is based on [HAP-NodeJS](https://github.com/KhaosT/HAP-NodeJS) - could you try the out-of-the-box `Code.js` or `BridgedCore.js` examples from that repository and see if the same problem occurs?

**Comment by cflurin** [comment]
Hi,
Thank you for the quick replay.
I tried the BridgedCore.js example with the HAP-NodeJS server and actually I've got the same issue.
I will report it to the HAP-NodeJS author.

**Comment by cflurin** [comment]
https://github.com/KhaosT/HAP-NodeJS/issues/108
