### ISSUE TITLE
Yi Home Camera RTSP

### ISSUE THREAD

**Issue by joq3** [nfarina/homebridge#910]
Hi,

This is more a question than an issue. I just installed Homebridge, and I love the functionality. What I want to know is if it is possible to get a IP-camera that supports RTSP to show up in the Home-app?
The camera is a Xiaomi Yi Home Camera, which has this firmware: https://github.com/fritz-smh/yi-hack

And if this is possible, will I be able to access it from outside my Wifi if I haven't got a Apple TV?

Thank you!

**Comment by KhaosT** [comment]
It's possible but since iOS 10.1 all video stream requires SRTP, you need to make extra changes to support it. For more details please see [the wiki article](https://github.com/nfarina/homebridge/wiki/Supporting-IP-Camera).

**Comment by iCarl** [comment]
@joq3 Did you manage to get this to work?

**Comment by joq3** [comment]
@iCarl nope, sorry!
