### ISSUE TITLE
How to enable notifications?

### ISSUE THREAD

**Issue by mmancini403** [nfarina/homebridge#911]
Within the IOS Home App, long pressing the accessory, tapping Details, Status and Notifications, shows no options for notifications.  Is this something that needs to be enabled/coded in the plug-in (ISY-JS in my case), or is this not supported by Homebridge?

Thanks and regards, Mike

**Comment by justme-1968** [comment]
these notifications are only available for security devices like locks and door/window openers.

not for regular devices like lights and switches.

**Comment by mmancini403** [comment]
Thanks for the info.  Its too bad that is the case.  Notifications when a door is opened, etc., are quite useful.

**Comment by bprskalo** [comment]
will be in ios 10.2 :-) !

**Comment by mmancini403** [comment]
Duh!  It's there in the beta.  Did not notice it until now.  Thanks!

**Comment by ToddGreenfield** [comment]
Reverse of the question - is there a way to (mass) disable the notifications, not though the Home app though, but maybe through some flag in a config? Maybe an overriding default of off? I am running the envisalink plugin and all my windows and doors have notifications turned on and I would like to not have to manually turn each one off every time (like setting up my wife's phone).
