### ISSUE TITLE
IKEA lights with homebridge?

### ISSUE THREAD

**Issue by joq3** [nfarina/homebridge#912]
Hi,

I'm not able to find any plugin that's supporting the IKEA lights that's released in europe.
http://www.ikea.com/se/sv/catalog/products/10318263/

They are according to IKEA themselves using ZigBee Light Link and compatible with everything in ZigBee Alliance. They are using 2.4ghz.

This all sounds good, and some people here have been able to link them to their Philips Hue Bridge (but only bridges running older firmware).

What plugins should I be looking at. I'm willing to buy these lights and test them out, but don't know which plugins to start with.

Thank you in advance!

EDIT: By the way, I have no bridge, and I rather not buy one. Is there any plugin which the lights can connect directly to? I have a server always running (debian) and Logitech Harmony Hub.

**Comment by cflurin** [comment]
One solution might be to use node-red and homebridge-mqtt:

http://nodered.org/
http://flows.nodered.org/node/node-red-contrib-zblight

https://github.com/cflurin/homebridge-mqtt

**Comment by joq3** [comment]
Great! Going to read up on that! Do I need any additional hardware or does this allow my server to directly connect to the lights with these applications?

**Comment by cflurin** [comment]
Probably like zwave and enocean you'll need an adapter.
The xbee-api used in this node provides more details about the hardware:
https://github.com/andrewrapp/xbee-api

**Comment by joq3** [comment]
Would it work with this software:
https://github.com/bwssytems/ha-bridge
And connect the lights to this "bridge emulator" and then sync homebridge with this "bridge emulator"?

**Comment by justme-1968** [comment]
the problem ist not the homebridge part but the zigbee part. there is currently no api to control the Ikea lights and they are currently not compatible with current hue bridges or lightly gateways.

**Comment by joq3** [comment]
Okey, but according to this youtube-video there are people who has been successfull with pairing the Ikea-lights with Hue Bridge (just not on the latest firmware). https://www.youtube.com/watch?v=jcBp3wamIU0

So maybe it would be possible with Hue Bridge emulator?

**Comment by justme-1968** [comment]
no

**Comment by luc-ass** [comment]
I just read on the meethue-forum that Philips and IKEA are working on a fix. Let us hope this goes the way it went with the Osram bulbes that are now supported again.

**Comment by boikedamhuis** [comment]
Any updates on this topic?

**Comment by stenehall** [comment]
https://github.com/stenehall/homebridge-ikea my very quick hack to get a lamp working. It controls dimming of the light and works for now. I'll iterate over it this weekend

**Comment by Hedda** [comment]
There is now a third-party Python library that makes it relativly easy to implement

https://github.com/ggravlingen/pytradfri
