### ISSUE TITLE
Working on Orange Pi Zero H2?

### ISSUE THREAD

**Issue by guilhermelirio** [nfarina/homebridge#914]
I have a Orange Pi Zero and wanted to know if Homebridge works normally!

Thanks!

**Comment by Sunrise17** [comment]
Somebody used Orange pi Zero or Nanopi neo for Homebridge and mqtt server???

**Comment by soptikopava** [comment]
I'm using Orange PI Zero with Armbian. Homebridge can not run. I'm probably stupid.

**Comment by Sunrise17** [comment]
As i heard that orange pi zero is running Homebridge well.

**Comment by donders** [comment]
Currently stuck with issues surrounding mdns and node-gyp.

**Comment by AppleTechy** [comment]
I don't see why it would be an issue. You would just need to configure your linux distro correctly.

**Comment by donders** [comment]
@AppleTechy I'll try again in the weekend. Want me to open an issue, if the problem shows up again?

**Comment by AppleTechy** [comment]
We can go ahead and reopen this issue if you end up having problems. I think the only issues that you will have will be related to the OS your are running on it
