### ISSUE TITLE
Where am I going wrong! 

### ISSUE THREAD

**Issue by miguelmolez** [nfarina/homebridge#918]
Not sure what i'm missing here, but it won't accept the JSON in jsonlint,  I can't see where I'm going wrong. 

{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},

	"accessories": [{

			"accessory": "SSH",

			"name": "Christmas Music",
			"on": "osascript /users/michaelhatton/scripts/spotify.scpt",
			"off": "osascript -e 'tell application \"Spotify\" to pause'",
			"state": "osascript -e 'tell application \"Spotify\" to get player state'",
			"on_value": "playing",
			"exact_match": true,
			"ssh": {
				"user": "username",
				"host": "192.168.0.24",
				"port": 22,
				"password": "password"

			},
			{

				"accessory": "SSH",
				"name": "Mac Mini Airplay",
				"on": "osascript -e 'tell application \"Spotify\" to play'",
				"off": "osascript -e 'tell application \"Spotify\" to pause'",
				"state": "osascript -e 'tell application \"Spotify\" to get player state'",
				"on_value": "playing",
				"exact_match": true,
				"ssh": {
					"user": "username",
					"host": "192.168.0.24",
					"port": 22,
					"password": "password"

				}
			}]
	}

**Comment by maragelis** [comment]
Delete the } before ] ,

**Comment by maragelis** [comment]
192.168.0.24",
                "port": 22,
                "password": "password"

            }
        ]
