### ISSUE TITLE
Server doesn't want to start. Have spent days trying to learn how to make this work, NEED HELP PLEASE

### ISSUE THREAD

**Issue by mignlou** [nfarina/homebridge#92]
I'm trying to connect to my wink hub. I feel like I'm very close but can't seem to get the server to run. I really need some help.  Any help would be greatly appreciated. Here is the messages I get.

administrator@HomeBridge:~/homebridge$ node -v && npm -v
v0.12.7
2.11.3

administrator@HomeBridge:~/homebridge$ sudo npm run start
> homebridge@0.0.0 start /home/administrator/homebridge
> node app.js
Starting HomeBridge server...
*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
Loading 1 platforms...
[Wink] Initializing Wink platform...
[Wink] Fetching Wink devices.
Loading 0 accessories...
response in http: {"data":{"access_token":"**************","refresh_token":"************","token_type":"bearer","token_endpoint":"https://winkapi.quirky.com/oauth2/token","scopes":"full_access"},"errors":[],"pagination":{},"access_token":"***********","refresh_token":"*************","token_type":"bearer","token_endpoint":"https://winkapi.quirky.com/oauth2/token","scopes":"full_access"}
response in http: {"data":[],"errors":[],"pagination":{"count":0}}
administrator@HomeBridge:~/homebridge$

**Comment by nzhome** [comment]
@mignlou  sorry I don't have a wink hub to check for you.  did you get it working in the end? does it work with the new version now?

**Comment by mignlou** [comment]
I was able to get the wink hub to work I can even detect it with the elgato eve app. Unfortunately I cannot control the aeon labs appliance module. I can however control some features of my Nest through the home bridge and wink. My goal is to control the appliance module "dining Room A/C" with Siri. Not sure how to accomplish that.

**Comment by nzhome** [comment]
ok great, can you close this issue using the close button below, and perhaps open another for your aeon labs with the error message or log. thanks.
