### ISSUE TITLE
Installed homebridge on windows 2012 r2 standard, won't start?

### ISSUE THREAD

**Issue by gleep52** [nfarina/homebridge#921]
When trying to run the start command: node homebridge

I get:

`c:\Users\administrator.IT-TANK\AppData\Roaming\npm\node_modules\homebridge\bin>n
ode homebridge
[11/14/2016, 12:59:59 PM] Warning: skipping plugin found at 'C:\Users\administra
tor.IT-TANK\AppData\Roaming\npm\node_modules\homebridge-http' since we already l
oaded the same plugin from 'c:\Users\administrator.IT-TANK\AppData\Roaming\npm\n
ode_modules\homebridge-http'.
[11/14/2016, 1:00:00 PM] Loaded plugin: homebridge-http
[11/14/2016, 1:00:00 PM] Registering accessory 'homebridge-http.Http'
[11/14/2016, 1:00:00 PM] ---
[11/14/2016, 1:00:00 PM] Loaded config.json with 1 accessories and 0 platforms.
[11/14/2016, 1:00:00 PM] ---
[11/14/2016, 1:00:00 PM] Loading 1 accessories...
[11/14/2016, 1:00:00 PM] [Alfresco Lamp] Initializing Http accessory...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:

    ┌────────────┐
    │ 031-45-154 │
    └────────────┘

[11/14/2016, 1:00:00 PM] Homebridge is running on port 51826.
[11/14/2016, 1:00:01 PM] [Alfresco Lamp] HTTP get power function failed: connect
 ECONNREFUSED 127.0.0.1:80
c:\Users\administrator.IT-TANK\AppData\Roaming\npm\node_modules\homebridge-http\
index.js:45
                                callback(error);
                                ^

ReferenceError: callback is not defined
    at c:\Users\administrator.IT-TANK\AppData\Roaming\npm\node_modules\homebridg
e-http\index.js:45:19
    at Request._callback (c:\Users\administrator.IT-TANK\AppData\Roaming\npm\nod
e_modules\homebridge-http\index.js:115:4)
    at self.callback (c:\Users\administrator.IT-TANK\AppData\Roaming\npm\node_mo
dules\homebridge-http\node_modules\request\request.js:186:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Request.onRequestError (c:\Users\administrator.IT-TANK\AppData\Roaming\np
m\node_modules\homebridge-http\node_modules\request\request.js:845:8)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketErrorListener (_http_client.js:265:9)
    at emitOne (events.js:77:13)
`

What can I do to get this loaded?  I'm trying to get my wink hub to talk to homebridge so I can use siri to control my lights... Thanks in advance.

**Comment by gleep52** [comment]
It looks like there's a conflict with the config.json file.  It states the port is on 51826, but then the localhost doesn't use that (uses 80 by default).  I added :51826 to the end of each of the lines and now it works!

I can't wait to get home to see what else I can screw up :)

**Comment by CMaxim77** [comment]
im getting the same error, should my config.json file in the Homebridge folder say this?

{
     "bridge": {
        "name": "HomeBridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    
    "description": "HomeBridge HTTP Status Control",

    "accessories": [ {
	        "accessory": "Http",
                "name": "Alfresco Lamp",
			"switchHandling": "realtime",
				"http_method": "GET",
				"on_url":      "http://localhost/controller/1700/ON",
				"off_url":     "http://localhost/controller/1700/OFF",
				"status_url":  "http://localhost/status/100059",				
			"service": "Light",
				"brightnessHandling": "yes",
				"brightness_url":     "http://localhost/controller/1707/%b",
				"brightnesslvl_url":  "http://localhost/status/100054"			
									    
       } 
    ]
}

**Comment by CMaxim77** [comment]
I really want to figure this out, im so fustrated already and i havent even go homebridge installed yet. I can only imagine all the issuesill have trying to install commands. is there any step by step videos or instructions for dummies anywhere? No joke i have spent days just to get to this point.

please anybody help........

**Comment by gleep52** [comment]
I struggled with this on windows for far too long.  I found a guide to setup a basic ubuntu box on my windows server via hyper-v - had it installed and running flawlessly in about 20 minutes (after install).  I have been using it ever since without hardly a hiccup.  Wish I would have done it ages ago instead of fiddling around in windows since I feel more comfortable there...  I tried a pi first and the guides I had for that didn't work well or commands were missing, etc.  Here is the guide I followed for ubuntu, just last month, which still worked even though all the modules and versions are newer than what is listed - it was a great guide to follow through and get the ball all setup.  Hardest part was having to type in my config.json file manually since I'm not apt enough to download it via command line from somewhere else and it really wasn't too much typing... YMMV

**Comment by CMaxim77** [comment]
Thanks for the info, do you have alink to the page that got it working for you?

**Comment by gleep52** [comment]
Sorry I could swear I left the link.  Here it is again.

https://www.reddit.com/r/winkhub/comments/3zst32/wink_homebridge_how_to_do_it/

**Comment by CMaxim77** [comment]
@gleep52 Thanks You very much, now all i have to do is figure out how too install ubuntu because i dont think you can use hyper v on windows 10 home. Ill keep trying. I really appreciate your time! I owe you one :)

**Comment by gleep52** [comment]
Yeah I think you have to have Win10 pro for hyper-v but I could be wrong... There's always vmware too... good luck!

**Comment by gleep52** [comment]
I should point out that the only part of the link/instructions above that didn't work for me was the config.json file where it has all four values:

 "client_id": "quirky_wink_android_app",
 "client_secret": "e749124ad386a5a35c0ab554a4f2c045",
 "username": "your_email@address.com",
 "password": "your_secure_password"

In the latest version of homebridge-wink (3?) it no longer needs hte username/password values and will fail if you include them with authentication permissions.  If you remove the username and password and keep just the client_id and client_secret  values - you should be in business.
