### ISSUE TITLE
Door lock status

### ISSUE THREAD

**Issue by scordinskyc** [nfarina/homebridge#922]
Hello, 

Having an issue with Siri knowing and being able to control door locks. I can go through the Home app and control fine. However, when using Siri, it replies that it "didn't hear back." This has been the case on 10.2b3, b2 and b1.  Other switches and devices seem to be controlled with Siri fine.

I'm using 0.4.9 of homebridge, and also I am using the homebridge-smartthings plugin.

**Comment by mend1** [comment]
Might not be a homebridge issue. I sometimes get the "didn't hear back" response from Siri with my Schlage Sense locks, which are HomeKit compatible and therefore do not require homebridge. For me, it appears that Siri succeeds in locking or unlocking the door, but the lock does not report back its status in time (I think I read somewhere that Siri will wait a maximum of 10 seconds for a response).
