### ISSUE TITLE
How to stop homebridge when running from startup ?

### ISSUE THREAD

**Issue by khazaee** [nfarina/homebridge#923]
Hi !!

How to stop homebridge when running from startup ?

**Comment by toshibochan** [comment]
On my raspberry pi I do
" sudo /etc/init.d/homebridge stop "
For start you just change "stop" to "start"

**Comment by snowdd1** [comment]
if you're on a systemd operating System, issue  
`sudo systemctl stop homebridge`  
given you have named the Service [according to the book](https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi#running-homebridge-on-bootup-systemd)

**Comment by khazaee** [comment]
thanks
