### ISSUE TITLE
"Accessory is not reachable" error

### ISSUE THREAD

**Issue by xmanjimmy** [nfarina/homebridge#925]
Hi, I am having problem trying to add accessory to HMHome, the problem happens both with HomeKit Accessory Simulator, and with Homebridge running on raspberry PI.
The code to add accessory:

    - (IBAction)unwindToAccessoryList:(UIStoryboardSegue* )segue {
    NewAccessoryTableViewController* sourceController = [segue sourceViewController];
    if(sourceController.accessoryItemArray.count > 0) {
        for(AccessoryItem* item in sourceController.accessoryItemArray) {
            if(item.selected) {
                // add selected item to home
                [self.home addAccessory:item.accessory completionHandler:^(NSError * _Nullable error) {
                    if(error) {
                        NSLog(@"AccessoryTableViewController:addAccessory(), error adding accessory to home, error:%@", error);
                    }
                }];
            }
        }
        [self.tableView reloadData];
    }
    }

the log I get:
2016-11-17 10:02:39.253 LearnIOSApp2[1438:16151] AccessoryTableViewController:addAccessory(), error adding accessory to home, error:Error Domain=HMErrorDomain Code=4 "Accessory is not reachable." UserInfo={NSLocalizedDescription=Accessory is not reachable.}

and I have a dialog saying "the accessory is not certified", after I click "Add anyway", I don't have a prompt asking for Setup Code.

Thanks for any help!

**Comment by SPopenko** [comment]
@xmanjimmy were you able to solve the issue?
