### ISSUE TITLE
New EVE app missing lights etc object

### ISSUE THREAD

**Issue by sdomotica** [nfarina/homebridge#926]
The last version don't show lights objects, but only some accessories.
The problem is common?
Sandro

**Comment by KhaosT** [comment]
A screenshot of Room view please?

**Comment by sdomotica** [comment]
![img_9289](https://cloud.githubusercontent.com/assets/781294/20366844/2cfd7402-ac4d-11e6-8f58-da10f82d42ee.PNG)
![img_9290](https://cloud.githubusercontent.com/assets/781294/20366847/2ef680aa-ac4d-11e6-9287-d41c4da1de3b.PNG)

Two images. 
The image with big characters refers the new app the other to EVE app for iOs 9. Same Homebridge.

**Comment by KhaosT** [comment]
Sorry I mean inside the room view. Like this

![img_1819](https://cloud.githubusercontent.com/assets/1725664/20366944/412b37e8-ac02-11e6-8fff-56e7163928be.PNG)

Do you see your accessories there?

**Comment by sdomotica** [comment]
I have accessory only in settings  tab.  not in Rooms. My homebridge and hap isn't up to date.

**Comment by KhaosT** [comment]
Are those accessories from a particular plugin? If so I think the plugin failed to provide a service name so Elgato Eve decided to hide it.

**Comment by sdomotica** [comment]
It's mine, I'll check with other plugin. What are you using in your screenshot?

**Comment by KhaosT** [comment]
those are Philips Hue and Elgato Eve products.

For your plugin, make sure when you add service, provide a name to it. [Example](https://github.com/nfarina/homebridge/blob/master/example-plugins/homebridge-samplePlatform/index.js#L193)

**Comment by sdomotica** [comment]
Thanks a lot KahosT, the missed object don't had name. I added and now works fine.
Bye
Sandro

**Comment by mrose17** [comment]
@KhaosT - i don't think that a missing name is the issue. when i upgraded to the new eve app (which is very nice!), it stopped showing the amazon dash input device, and the nest cam/protects.

the old version of the app (which is nice, but not as nice) didn't have any issues with it.

i submitted a support ticket to the folks at elgato, but haven't heard back yet...

/mtr

ps: thanks for the great work on this package!

pps: i'm not suggesting you re-open this issue... i suspect the issue is elsewhere!

**Comment by KhaosT** [comment]
@mrose17 no it's not a bug in their app. HomeKit has a property on HMService (https://developer.apple.com/reference/homekit/hmservice/1615891-isuserinteractive) which informs app whether or not it should show the service. The property is populated based on whether or not it has a name characteristic.

**Comment by mrose17** [comment]
@KhaosT - thanks for clarifying that, but (no offense), it don't think i'm buying it!

i'm using your amazondash plugin and it's not showing up in the new app (it did show up in the old app) and according to https://github.com/KhaosT/homebridge-amazondash/blob/master/index.js#L80 -- the name is being set. am i missing something obvious?

**Comment by KhaosT** [comment]
@mrose17 but can you see the accessory when you try to create rules? I assume the button is not shown since it's not "controllable"...

**Comment by mrose17** [comment]
all - @KhaosT and myself discussed this offline and i now believe that his analysis is correct, viz., there probably is a bug with the evo app with respect to displaying input event devices. however, i forked/fixed the nest repo and submitted a PR. you can run this:

      npm install -g https://github.com/homespun/homebridge-nest.git

until the repo maintainer decides what to do. that leaves the myq plugin for homebridge, which i am looking at now.
