### ISSUE TITLE
Red warnings on Homebridge and Nest

### ISSUE THREAD

**Issue by inzlabs** [nfarina/homebridge#928]
I am not a developer, but I can understand the logic. But somehow my homebridge on a raspberry pi 3 stop worked, suddenly. When I tried to re-start it this came up. 

Have a look to the screenshot. Any idea how can I fix this?

Thank you!

 
<img width="1769" alt="screen shot 2016-11-18 at 7 59 08 pm" src="https://cloud.githubusercontent.com/assets/23566512/20452887/84956ea4-adc9-11e6-83d5-851fc7bc9952.png">

**Comment by inzlabs** [comment]
I got this fixed. Looks like was a situation of homebridge-nest. Probably Developer-nest platform changed their protocols and forced to create a new product and re-pair with the plugin again.

**Comment by AppleTechy** [comment]
Next time please create an issue on the plugin's github page since this was due to the Nest plugin not the Homebridge framework
