### ISSUE TITLE
Autostart Homebridge cannot find HomeAssistant accessories

### ISSUE THREAD

**Issue by supakdee** [nfarina/homebridge#930]
Hi,

I'm running homebridge to connect iphone -> Homebridge -> HomeAssistant (Using with self signed SSL certificates).

On manual commands by:
export NODE_TLS_REJECT_UNAUTHORIZED=0
homebridge

Manual commands work flawlessly

However, when I tried to have homebridge autostart following below instruction, the thing didn't go so well - Homebridge started but cannot find any HomeAssistant accessories.

Can you help to let me know what I should do?

https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi#running-homebridge-on-bootup

Status using "sudo systemctl status homebridge" after boot up:
● homebridge.service - Node.js HomeKit Server
   Loaded: loaded (/etc/systemd/system/homebridge.service; enabled)
   Active: active (running) since Sat 2016-11-19 13:20:37 ICT; 6min ago
 Main PID: 605 (homebridge)
   CGroup: /system.slice/homebridge.service
           └─605 homebridge

Nov 19 13:20:44 raspberrypi homebridge[605]: [11/19/2016, 1:20:44 PM] Registering platform 'homebridge-homeassistant.HomeAssistant'
Nov 19 13:20:44 raspberrypi homebridge[605]: [11/19/2016, 1:20:44 PM] ---
Nov 19 13:20:44 raspberrypi homebridge[605]: [11/19/2016, 1:20:44 PM] config.json (/var/homebridge/config.json) not found.
Nov 19 13:20:44 raspberrypi homebridge[605]: Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
Nov 19 13:20:44 raspberrypi homebridge[605]:
Nov 19 13:20:44 raspberrypi homebridge[605]:     ┌────────────┐
Nov 19 13:20:44 raspberrypi homebridge[605]:     │ 031-45-154 │
Nov 19 13:20:44 raspberrypi homebridge[605]:     └────────────┘
Nov 19 13:20:44 raspberrypi homebridge[605]:
Nov 19 13:20:44 raspberrypi homebridge[605]: [11/19/2016, 1:20:44 PM] Homebridge is running on port 46250.

homebridge.service file under /etc/systemd/system
[Unit]
Description=Node.js HomeKit Server 
After=syslog.target network-online.target

[Service]
Type=simple
User=homebridge
EnvironmentFile=/etc/default/homebridge
ExecStart=export NODE_TLS_REJECT_UNAUTHORIZED=0
ExecStart=/usr/lib/node_modules/homebridge/bin/homebridge $HOMEBRIDGE_OPTS
Restart=on-failure
RestartSec=10
KillMode=process

[Install]
WantedBy=multi-user.target

**Comment by kolossboss** [comment]
Hi,

do you change the location of the homebridge config.json? When you autostart with systemd the location changed to `/var/homebridge/config.json`
When you only do `homebridge` then homebridge needs the config in /home/pi/.homebridge

Look at your log. 
`Nov 19 13:20:44 raspberrypi homebridge[605]: [11/19/2016, 1:20:44 PM] config.json (/var/homebridge/config.json) not found.`

**Comment by supakdee** [comment]
Hi,

I copied config.json to /var/homebridge and now I got the different error as below.

What should I do?

pi@raspberrypi:~ $ sudo systemctl status homebridge -l
● homebridge.service - Node.js HomeKit Server
   Loaded: loaded (/etc/systemd/system/homebridge.service; enabled)
   Active: active (running) since Fri 2016-11-25 23:17:05 ICT; 1h 9min ago
 Main PID: 602 (homebridge)
   CGroup: /system.slice/homebridge.service
           └─602 homebridge

Nov 26 00:26:17 raspberrypi homebridge[602]: [11/26/2016, 12:26:17 AM] [Home] Fetching HomeAssistant devices.
Nov 26 00:26:17 raspberrypi homebridge[602]: [11/26/2016, 12:26:17 AM] [Home] Failed getting devices: Error: Hostname/IP doesn't match certificate's altnames: "IP: 192.168.1.41 is not in the cert's list: ". Retrying...
Nov 26 00:26:22 raspberrypi homebridge[602]: [11/26/2016, 12:26:22 AM] [Home] Fetching HomeAssistant devices.
Nov 26 00:26:22 raspberrypi homebridge[602]: [11/26/2016, 12:26:22 AM] [Home] Failed getting devices: Error: Hostname/IP doesn't match certificate's altnames: "IP: 192.168.1.41 is not in the cert's list: ". Retrying...
Nov 26 00:26:27 raspberrypi homebridge[602]: [11/26/2016, 12:26:27 AM] [Home] Fetching HomeAssistant devices.
Nov 26 00:26:27 raspberrypi homebridge[602]: [11/26/2016, 12:26:27 AM] [Home] Failed getting devices: Error: Hostname/IP doesn't match certificate's altnames: "IP: 192.168.1.41 is not in the cert's list: ". Retrying...
Nov 26 00:26:32 raspberrypi homebridge[602]: [11/26/2016, 12:26:32 AM] [Home] Fetching HomeAssistant devices.
Nov 26 00:26:32 raspberrypi homebridge[602]: [11/26/2016, 12:26:32 AM] [Home] Failed getting devices: Error: Hostname/IP doesn't match certificate's altnames: "IP: 192.168.1.41 is not in the cert's list: ". Retrying...
Nov 26 00:26:37 raspberrypi homebridge[602]: [11/26/2016, 12:26:37 AM] [Home] Fetching HomeAssistant devices.
Nov 26 00:26:37 raspberrypi homebridge[602]: [11/26/2016, 12:26:37 AM] [Home] Failed getting devices: Error: Hostname/IP doesn't match certificate's altnames: "IP: 192.168.1.41 is not in the cert's list: ". Retrying...

**Comment by kolossboss** [comment]
Yes,
thats the same problem I have, because of using SSL certificat in Home-Assistant.
And your Systemd  does not work.

First of all, you cannot use two ExecStart in Typ Simple. You can use ExecStartPre.
And its not possible to execute a command in the systemd. You have to use a absolute path. E.g. to a script that includes this command: `export NODE_TLS_REJECT_UNAUTHORIZED=0`

But I did this and its not working, too. I dont why. 
Execute this command `export NODE_TLS_REJECT_UNAUTHORIZED=0` and `homebridge` manually works fine. But not with systemd :-(

**Comment by kolossboss** [comment]
OK found a nice and easy solution.

I simply modified the homebridge executable set up file .

This file is located here:

`/usr/lib/node_modules/homebridge/bin`

Just added the command: `process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";`

Then the file look like this:

```
#!/usr/bin/env node

//
// This executable sets up the environment and runs the HomeBridge CLI.
//

'use strict';

process.title = 'homebridge';

// Find the HomeBridge lib
var path = require('path');
var fs = require('fs');
var lib = path.join(path.dirname(fs.realpathSync(__filename)), '../lib');
process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";

// Run HomeBridge
require(lib + '/cli')();
```

Now restart homebridge service. And the ssl errors are gone.

NOTE: THIS DISABLES ALL KINDS OF SECURITY CHECKS

I think everything is local if I put in the local home Assistant IP in config.json, so I hope this is not a big deal.

I dont know if this is the right way but this works for me and works this autostart and systemd service.

**Comment by supakdee** [comment]
Hi,

Nice - your solution works well.

After removed that line in "homebridge.service file under /etc/systemd/system" and add a line in "/usr/lib/node_modules/homebridge/bin/homebridge", homebridge autostart works like a charm.

Thanks a lot for your help

**Comment by botho** [comment]
best way to set env variable for a systemd service is to create an override.conf as :

`sudo systemctl edit homebridge
`
And add this :

> [Service]
> Environment="NODE_TLS_REJECT_UNAUTHORIZED=0"



(this command will create /etc/systemd/system/homebridge.service.d/override.conf that will service home bridge upgrade ...)
