### ISSUE TITLE
init.d bootup -- help --

### ISSUE THREAD

**Issue by khazaee** [nfarina/homebridge#932]
hello my friends
i have homebridge in my raspberry but i cabt set it on startup plz help me.

i installed homebridge with : sudo npm install -g homebridge --unsafe-perm
but i cant use this : sudo /etc/init.d/homebridge start  -and- bootup homebridge.

**Comment by jata1** [comment]
what version of RPi - wheezy or jessie? I did homebridge with nest plug-in yesterday on a pi 3 jessie. didn't use init.d method for for startup but i will try to help if i can

**Comment by khazaee** [comment]
Jessie on RPi 3. i want use init.d method

**Comment by jata1** [comment]
ok. what text editor are you using to edit the init script?

just checking but does homebridge start ok normally?

**Comment by jata1** [comment]
any error messages you see might also help me to help

**Comment by khazaee** [comment]
in using putty and when i type homebridge its work. but when i type sudo /etc/init.d/homebridge start. not gonna hapen

**Comment by jata1** [comment]
what changes did you make to the init file? you need to make sure the variables are correct for your install

**Comment by khazaee** [comment]
do you want access my pi ?!
my email address khazaee.amir@gmail.com.

**Comment by jata1** [comment]
haha. not really and not right now as i have friends over this afternoon. will have a look for you later if you are really stuck. do you have ports & firewall setup for ssh access to your pi from internet?

**Comment by khazaee** [comment]
i write a NAT on my router for u to access to my RPi

**Comment by jata1** [comment]
ok. can you set it up and test nat working from outside lan - e.g. from iphone with wi-fi OFF.

i'll email you for connection details later if you still need help.

**Comment by jata1** [comment]
do you still need some help? happy to look but i'm not an expert!

**Comment by jata1** [comment]
have just emailed you a corrected homebridge init.d script/file. i couldn't write it directly to your pi as i don't have write permissions.
