### ISSUE TITLE
Extreme temperature variations Trane Thermostat + Wink?

### ISSUE THREAD

**Issue by Bowsa2511** [nfarina/homebridge#935]
I have a Trane AC set-up with Wink as a Generic Z-Wave Thermostat. I then installed Home bridge with the Wink Addon, and when I set the AC via siri, it reports as setting the AC to say "65 Degree AND 57 degrees". It seems to set the temperature twice and default on the lower temperature. 

When I check the AC on the home app, it's even more confusing. It'll report 57 degrees, or 2 degrees, or 100 degrees and just keep fluctuating on its own. 

Asking SIRI, the temperature the AC, is SET to, it reports whatever it wants. Is there a way to stabilize this? 

It seems to be defaulting on whatever is configured on WINK

**Comment by djmcp** [comment]
Did you ever get anywhere with this? Just set up homebridge to my Wink w/ Trane thermostat and having crazy temps as well. The data going out of homebridge is accurate per the logs, e.g. Cool to 75 degrees, but the Home app is seeing cool to 165 degrees. Both the temp sensor and the temp setting are off by 90 degrees.

**Comment by AppleTechy** [comment]
Please create an issue on the Plugin's github page. I would also verify that you are running the latest version of the Wink plugin. https://www.npmjs.com/package/homebridge-wink3
