### ISSUE TITLE
HomeKit/Home App doubles renamed (Fibaro) devices

### ISSUE THREAD

**Issue by Krillle** [nfarina/homebridge#936]
Hi. I am using your great homebride with Fibaro Plugin on a Raspberry Pi. Works amazingly. Thanks a lot!

Just I have the following issue: When I rename a device in the Fibaro control center web interface, hombrigde adds it as a new accessory (at it's next start) - without removing the existing predecessor, which is known under the old name. In result the iOS 10 Apple Home App shows two (or after repeated renaming even more) entries for the same device. Both/all entries are working.

I have learned I should delete the ~/.homebridge/persist folder. This indeed resolves to problem - while all other existing entries in the Home app loose connection to their relevant devices too. As I cannot (or don't know how to) delete entries in Home app, I have to delete the whole house and add it from the scratch, which is very time consuming with 50 devices.

Is doubling the device entries a bug or user failure?
How to remove single devices or entries from Homebride (from the cached accessories)?

Thanks for your advice. Christian

**Comment by ilcato** [comment]
@Krillle , the current version of the plugin enable the updates of the devices in Home Center.
Simply perform the update in Home Center and restart homebridge.

**Comment by Krillle** [comment]
Yes, thank you. I am using it already, and very happy with that!

Btw, there seems to be an issue with the Fibaro RGBW controller: The color stored in HomeKit scenes is not always set correctly. I have the impression the white channel is not always set.

Thanks again for your great plugin, Christian



Am 08.05.2017 um 17:56 schrieb ilcato <notifications@github.com<mailto:notifications@github.com>>:


@Krillle<https://github.com/Krillle> , the current version of the plugin enable the updates of the devices in Home Center.
Simply perform the update in Home Center and restart homebridge.

**Comment by ilcato** [comment]
@Krillle , just published version 1.1.2 of the Fibaro Home Center plugin that should fix the RGBW issue.
Do not create issues in the homebridge repository if it is specifically related to the Fibaro Home Center plugin, use [this](https://github.com/ilcato/homebridge-Fibaro-HC2/issues).
And close this issue please.
