### ISSUE TITLE
Question: HomeBridge NAS compatibility?

### ISSUE THREAD

**Issue by Ryan747800B** [nfarina/homebridge#937]
Is it possible to install HomeBridge on this NAS [(Link)](https://en.wikipedia.org/wiki/Western_Digital_My_Book#My_Book_Live) a Western Digital My Book Live?

**Comment by AppleTechy** [comment]
I don't have a My Book Live, but most of those NAS run some sort distro of Linux. If it is running Linux and you can enabled ssh access you should be able to install Node and in turn install Homebridge
