### ISSUE TITLE
Software Button...

### ISSUE THREAD

**Issue by fboulegue** [nfarina/homebridge#938]
I currently think of a way to create a homekit software button.
To trigger a "scene", the button should listen and change his state by a ssh command or something else.

Is there already a plugin for that, or someone that create a "software" button for homekit?

**Comment by justme-1968** [comment]
as far as i know there is no such thing in homekit.

homebridge-fhem does something like this with a timer that will reset an on/off button back to off after 0.5 seconds.

**Comment by cflurin** [comment]
Have a look here:
https://github.com/nfarina/homebridge-dummy

**Comment by fboulegue** [comment]
mmh ok let make it more clear what I try todo :) I try to find a way to trigger a home kit automation via macOS ... so send a SSH command or something like that

**Comment by cflurin** [comment]
well i don't use homekit-scenes but  just search for homebridge-ssh, homebridge-http, homebridge-http-simple-switch or homebridge-mqtt and try one of them.

**Comment by fboulegue** [comment]
well thats what I tried but all of these only can "send out http/ssh" and not "get triggered by

**Comment by Samfox2** [comment]
You can control homebridge with a simple bash script as I wrote at the end of the following issue:

[https://github.com/nfarina/homebridge/issues/506](url)

**Comment by cflurin** [comment]
Okay, I use node-red for my home automation and I've defined "software buttons" like "at_home" or "heating_control". I can set this buttons on/off using the node-red-dashboard and send the status via homebridge-mqtt to homekit.

**Comment by fboulegue** [comment]
@cflurin can you pass some more information on that?

**Comment by cflurin** [comment]
https://github.com/cflurin/homebridge-mqtt
https://github.com/cflurin/homebridge-mqtt/wiki/homebridge2NodeRED
http://flows.nodered.org/

Node-RED is preinstalled on raspbian jessie: Menu > Programming > node-RED
I use mosquitto (MQTT broker). Homebridge, Node-RED and mosquitto run on the same Rpi.

https://mosquitto.org/

**Comment by abataille** [comment]
I was able with the curl command (issue #506) to switch a lamp on and off.
What is the command to just read the status or value of a characteristic ?
Any idea?

**Comment by qudarr** [comment]
@abataille Something like this?
curl -X GET http://127.0.0.1:51826/characteristics?id=2.9 --header "Content-Type:Application/json" --header 'authorization: 031-45-123'
