### ISSUE TITLE
get complete config contents

### ISSUE THREAD

**Issue by justme-1968** [nfarina/homebridge#940]
is there a way to access the complete config contents?

using User.config() (with User initialised from homebridge.user) does not work as it crashes due to unknown Config.

is this supposed to work?

**Comment by snowdd1** [comment]
In the sample platform it would be `api.user.config()` as the API object is passed as `api`

**Comment by justme-1968** [comment]
this does not work with the 'old' 
''''
module.exports = function(homebridge){
...
}
''''
way of doing this. if i try to use homebridge.user.config() there i get this error:
''''
/home/andre/.nvm/versions/v0.12.7/lib/node_modules/homebridge/lib/user.js:24
  return config || (config = Config.load(User.configPath()));
                             ^
ReferenceError: Config is not defined
''''

the same error happens if i try to use api from the platform initialisation.

and if i look at the User.config() method i don't see where Config would come from as it is not mentioned anywhere else in the file...

**Comment by snowdd1** [comment]
Right. Need a dynamic platform for it.

**Comment by justme-1968** [comment]
but even for dynamic platforms i don't see where Config would be declared and initialised in user.js

**Comment by snowdd1** [comment]
You're right. Config loading has been moved to server.js  
I thing that stub is legacy there, however one could think about moving it back to user.js where it must have been some time back, I'd guess.  

@nfarina What about loading config.json in user.js?

**Comment by KhaosT** [comment]
I can put config back to user if necessary. Would you mind to share why you want to access user's complete configurations instead of just the ones that are relevant to the plugin?

**Comment by justme-1968** [comment]
i have implemented an amazon alexa backend for fhem that shares quite a lot of code and configuration with homebridge-fhem. i'm currently converting it back so it is just an small extension of the homebridge-fhem plugin and users can just use this and geht siri/homekit and alexa integration both. therefore i would like to add a top level "alexa" entry in addition to the "bridge" entry. 

currently i have to roll my own get file name and import json to do this.

**Comment by cflurin** [comment]
We discussed this feature last year: https://github.com/nfarina/homebridge/pull/293

nfarina added a plugin folder for plugin configurations:
```sh
.homebridge/plugin/homebridge-pluginname
```
the get the storagePath:
```sh
storagePath = homebridge.user.storagePath();
```
