### ISSUE TITLE
Wink Issues

### ISSUE THREAD

**Issue by sefeing** [nfarina/homebridge#943]
Have it all connected and have tried both my API key and the Android stock API key. It seems to login, and it recognized the two devices I have connected to my Wink. I'm able to register them in Insteon+ and Apple Home, but when I attempt to trigger them, it sends the command and nothing happens and eventually times out.

**Comment by TrueSolutionsLLC** [comment]
Same here. I can control the locks through the home app, etc but when using Siri to lock or unlock it just says hold on and then says it didn't hear anything back. Harmony remotes and lights all work great just this wink issue.

**Comment by AppleTechy** [comment]
Try the [latest wink plugin](https://www.npmjs.com/package/homebridge-wink3). If the problem persists please post and issue on the plugin related page. If it is later determined to be an issue with the Homebridge framework, please create a new issue and reference the issue number from the plugin's github page
