### ISSUE TITLE
Unable to set up Homebridge OSX

### ISSUE THREAD

**Issue by blkfrm** [nfarina/homebridge#945]
Hi,

I am getting the below error messages, any idea's?

Thanks,
DK
![screen shot 2016-11-23 at 10 54 07 pm](https://cloud.githubusercontent.com/assets/18690772/20560937/f2ea08a6-b1cf-11e6-8497-54ef2b3ed040.png)
![screen shot 2016-11-23 at 10 53 42 pm](https://cloud.githubusercontent.com/assets/18690772/20560938/f337430a-b1cf-11e6-98a7-e4f21383c760.png)

**Comment by RXM307** [comment]
Try ./homebridge

Anthony

**Comment by snowdd1** [comment]
What's that extra $ before `homebridge`?
