### ISSUE TITLE
IOS "Home couldn't connect to this accessory"

### ISSUE THREAD

**Issue by talisker-ca** [nfarina/homebridge#947]
decided to try to make use of HomeBridge to 'initially' connect to my Nest devices in the house.
I installed HomeBridge on my Linux server (OEL7) which had some of its own challenges, but eventually installed ok.  I added the Nest plugin, and configured it according to the instructions ... 

config.json file...
{
        "bridge": {
                "name": "Homebridge",
                "username": "CC:22:3D:E3:XX:XX",
                "port": 38XXX,
                "pin": "031-XX-XXX"
        },

        "description": "This is the configuration file for my devices",

        "platforms": [{
                "platform": "Nest",
                "token": "c.h4AEXXX..."
        }]
}

It certainly _seems_ to connect to the Nest device(s) ok ... 

# homebridge 
[11/23/2016, 6:34:07 PM] Loaded plugin: homebridge-nest
[11/23/2016, 6:34:07 PM] Registering platform 'homebridge-nest.Nest'
[11/23/2016, 6:34:07 PM] ---
[11/23/2016, 6:34:07 PM] Loaded config.json with 0 accessories and 1 platforms.
[11/23/2016, 6:34:07 PM] ---
[11/23/2016, 6:34:07 PM] Loading 1 platforms...
[11/23/2016, 6:34:07 PM] Initializing Nest platform...
[11/23/2016, 6:34:07 PM] Fetching Nest devices.
[11/23/2016, 6:34:08 PM] Software version for Family Room Thermostat (Nest) is: 5.6-7
[11/23/2016, 6:34:08 PM] Current temperature for Family Room Thermostat (Nest) is: 20.5 C
[11/23/2016, 6:34:08 PM] Current humidity for Family Room Thermostat (Nest) is: 30%
[11/23/2016, 6:34:08 PM] Target temperature for Family Room Thermostat (Nest) is: 21 C
[11/23/2016, 6:34:08 PM] Target heating for Family Room Thermostat (Nest) is: Heating
[11/23/2016, 6:34:08 PM] Away for Family Room Thermostat (Nest) is: 0
[11/23/2016, 6:34:08 PM] Software version for Hallway Nest Protect is: 3.1rc9
[11/23/2016, 6:34:08 PM] Software version for Basement Nest Protect is: 3.1rc9
[11/23/2016, 6:34:08 PM] Initializing platform accessory 'Family Room Thermostat (Nest)'...
[11/23/2016, 6:34:08 PM] Initializing platform accessory 'Hallway Nest Protect'...
[11/23/2016, 6:34:08 PM] Initializing platform accessory 'Basement Nest Protect'...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
031-XX-XXX
[11/23/2016, 6:34:09 PM] Homebridge is running on port 38XXX.
[11/23/2016, 7:01:48 PM] Current temperature for Family Room Thermostat (Nest) is: 21 C

but the Home app on IOS does not want to connect to HomeBridge ... 

the Accessory 'Homebridge" shows up ok, when you click it you get the warning message "This accessory is not certified and may not work reliably with HomeKit"   selected add anyway ... and manually entered the 8 digit code  which eventually results in the message "Couldn't add Homebridge / Home couldn't connect to this accessory"

I have tried changing the listen port, the 'username', the pin, removed the 'persist' folder, restarted HomeBridge, but the IOS Home app just won't connect.

I have gone through the similar issues posted here, but don't see an answer for this specific problem ...

**Comment by KhaosT** [comment]
This is normally caused by plugin returns invalid values for accessory. Please contact developer of ``homebridge-nest`` to sort this out.

**Comment by talisker-ca** [comment]
Thanks KhaosT ... I have reposted on "KraigM/homebridge-nest", If I get an answer, I will post an update here as well.

**Comment by Neelrp12** [comment]
I have this same issue with connect my wink hub to home kit.

**Comment by AdenFlorian** [comment]
I've got the same issue, and I don't have any plugins installed yet.

**Comment by KhaosT** [comment]
@AdenFlorian Huh interesting... what iOS version are you using?

**Comment by AdenFlorian** [comment]
@KhaosT 10.3.1 (14E304)

**Comment by KhaosT** [comment]
@AdenFlorian Would you mind to run homebridge with flag `-I` and then try to grab contents from http://localhost:51826/accessories and post it here?

**Comment by AdenFlorian** [comment]
@KhaosT https://hastebin.com/paheyitana.json

**Comment by KhaosT** [comment]
@AdenFlorian it looks okay to me... Can you try add the accessory again in Home app?

**Comment by AdenFlorian** [comment]
@KhaosT Same issue. Couldn't add Homebridge...

**Comment by KhaosT** [comment]
@AdenFlorian Sorry for the trouble. There are two more things you can try to gather more information to figure out what's wrong. First is try run homebridge with debug settings, like `DEBUG=* homebridge`, and the second is that if you are using a Mac (with macOS Sierra), try connect your iOS device to the Mac and open the Console.app
From the sidebar you should be able to select your iOS device and view its log. Try to filter the log using "homed" and repeat the pairing process. See if there are any useful information showing why iOS refuse to connect.

**Comment by AdenFlorian** [comment]
@KhaosT 

```
pi@raspberrypi:~ $ DEBUG=* homebridge
*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
[5/5/2017, 11:15:37 PM] No plugins found. See the README for information on installing plugins.
[5/5/2017, 11:15:37 PM] config.json (/home/pi/.homebridge/config.json) not found.
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:

    ┌────────────┐
    │ 031-45-154 │
    └────────────┘

  EventedHTTPServer Server listening on port 42589 +0ms
[5/5/2017, 11:15:37 PM] Homebridge is running on port 42589.
```

I unfortunately do not have a Mac :(

Thanks for your help so far :)

**Comment by KhaosT** [comment]
@AdenFlorian after running with DEBUG, you need to repeat the pairing process in order to get to the place where we may print out the error.

**Comment by AdenFlorian** [comment]
@KhaosT Yup, I did that but nothing was printed out.

**Comment by KhaosT** [comment]
@AdenFlorian Huh interesting, so does the app ask to you input the setup code at all? or just show "couldn't connect to this accessory" directly after you taping it?

**Comment by AdenFlorian** [comment]
@KhaosT Here are my steps:
- Add accessory
- Tap Homebridge
- Tap Add Anyway
- It tries to scan code from my screen but eventually gives up and asks me to enter the code
- I enter the code
- It says Pairing Homebridge
- After about a minute it fails (Couldn't add Homebridge...)

**Comment by KhaosT** [comment]
@AdenFlorian I'm not really sure then ... "After about a minute" feels like iOS cannot establish a connection to your Raspberry Pi. Can you make sure the port (51826) is accessible from iOS device?

**Comment by AdenFlorian** [comment]
@KhaosT I'm so sorry, I'm an idiot, my firewall was only allowing port 22 for SSH...
It's all good now after disabling the firewall, I'll find out which ports I need to allow for Homebridge in a bit and add them.

**Comment by KhaosT** [comment]
@AdenFlorian good to know :)
