### ISSUE TITLE
NPM owner ls curve25519-n Node won't compile on debian strech rpi

### ISSUE THREAD

**Issue by symgryph** [nfarina/homebridge#949]
mdns@2.3.3 install /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/mdns
> node-gyp rebuild

gyp ERR! configure error
gyp ERR! stack Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/mdns/build/config.gypi'
gyp ERR! stack     at Error (native)
gyp ERR! System Linux 4.4.34-v7+
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/mdns
gyp ERR! node -v v4.6.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm ERR! curve25519-n@1.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the curve25519-n@1.1.0 install script.
npm ERR! This is most likely a problem with the curve25519-n package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls curve25519-n
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.4.34-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "--unsafe-perm" "homebridge"
npm ERR! cwd /root
npm ERR! node -v v4.6.1
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

> ed25519@0.0.4 install /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/ed25519
> node-gyp rebuild

**Comment by jata1** [comment]
Hi,
I'm not an expert at this but...I had a similar error when i was installing on my RPi - following the instructions on the wiki.

to troubleshoot the issue i progressed the installation in sequence to try to find where the install failed. using the following commands (one at a time)

sudo npm install -g --unsafe-perm node-gyp
sudo npm install -g --unsafe-perm hap-nodejs
sudo npm install -g --unsafe-perm homebridge 

With one of the commands above (can't remember which) i noticed an error message in the output that said something about make CC - command not found. This meant that I was missing the C compiler.

you can check to see if you have the C compiler by running the following command

sudo gcc --version

If installed, you will see (or similar)
gcc (Raspbian 4.9.2-10) 4.9.2

if not installed, you can add the C compiler using the following
sudo apt-get install build-essential

then try the install commands again. 
sudo npm install -g --unsafe-perm node-gyp
etc...

good luck.

**Comment by jata1** [comment]
forgot to say you must also check g++ compiler

sudo g++ --version
