### ISSUE TITLE
platform support

### ISSUE THREAD

**Issue by snowdd1** [nfarina/homebridge#95]
I am thinking about turning my KNX additions into a platform shim for homebridge instead of refactoring (for https://github.com/KhaosT/HAP-NodeJS/pull/110) for a "naked" HAP-nodeJS, as KNX users might also have smart devices for which shims already exist in your project. 

Do have some doc or can recommend on some platform as a template? Which functions are supposed to be there for what purpose?

I searched your wiki for some more hints but was unable to find. I am still pretty new to JS and github, so excuse me if everything is plain before my eyes!

**Comment by nfarina** [comment]
So there aren't docs for this yet, although it's pretty straightforward - basically your module just exposes a single function "accessories" that passes a callback you call when you're done creating your accessories. The simplest example is probably the [Sonos](https://github.com/nfarina/homebridge/blob/master/platforms/Sonos.js) platform.

But! I'm right now working on a "real" plugin system for homebridge that will support loading modules installed globally via `npm`. That way all the shims don't have to be in homebridge itself. It would be great to work together on the API for this - I'd like to make it as easy as possible for you to expose Accessories to homebridge via the new HAP-NodeJS classes. I will work on a draft spec and post it here shortly.

**Comment by justme-1968** [comment]
i would also be interested in this api. some things that come to my mind:

- callbacks for pairing and unpairing and for instantiating an accessory (after all internal initialization is done. so that the username is already set)
- a way for an accessory to know if it paired (to optimize caching and event subscription)
- a way to dynamically publish new devices behind a bridge if they are added to the system. and also removing them.
-  a better way of handling the user visible name (and not deriving the id from this)
- addition and remove and pairing and unpairing without the need to remove persist files and restart

@snowdd1: ps: maybe the FHEM platform shim is also something that might interest you. i think it is quite complete feature wise. including a cache for the values received from the external system and pushing data back to homekit. the current version can be found here: https://github.com/justme-1968/homebridge/blob/master/platforms/FHEM.js

**Comment by nfarina** [comment]
So the direction I'm going with HomeBridge is to publish _all_ accessories behind a single bridge. Hopefully that simplifies things a lot for developers writing shims.

> callbacks for pairing and unpairing and for instantiating an accessory (after all internal initialization is done. so that the username is already set)

Would love to understand this more - what username do you mean?

> a way for an accessory to know if it paired (to optimize caching and event subscription)

Curious about this also - if you're using HomeBridge wouldn't you expect it to always be paired with at least one iOS device? Otherwise what's the point of running the server?

> a way to dynamically publish new devices behind a bridge if they are added to the system. and also removing them.

This is something I'm investigating right now - it would be awesome to have. It's very tricky for a few reasons which I'll probably lay out in a separate issue soon.

> a better way of handling the user visible name (and not deriving the id from this)

So the new HAP-NodeJS API proposal would require providing a globally-unique UUID for all accessories - you can generate it however you like, perhaps based on a serial number. Would this work?

> addition and remove and pairing and unpairing without the need to remove persist files and restart

You shouldn't have to remove the persist files ever ... at least not with the new version. Unless I'm not following?

**Comment by justme-1968** [comment]
>So the direction I'm going with HomeBridge is to publish all accessories behind a single bridge. Hopefully that simplifies things a lot for developers writing shims.

maybe it should not be one singe bridge but one bridge per platform. (and the pin code should also come from the shim and not be hardcoded)

>Would love to understand this more - what username do you mean?

the unique id that is currently generated in app.js. i would like to push the generated id back to fhem for display. the current onRegister callback for a characteristic is called to early for this. for the enduser this would be easier than the mini debug browser that i have currently integrated into the shim to get the file name that hast to be removed from persist. see below also.

>Curious about this also - if you're using HomeBridge wouldn't you expect it to always be paired with at least one iOS device? Otherwise what's the point of running the server?

in my home automation setup i have three figure number of devices. not all of them will be paired to homekit. the bridge (and also the current shim) will export most of them but not all will be paired. i think this will also be the case for snowdd1's knx installation. the pairing state should also be pushed back to fhem for display.

>This is something I'm investigating right now - it would be awesome to have. It's very tricky for a few reasons which I'll probably lay out in a separate issue soon.

that would be great. i think it is essential for the bridge concept. if you say it is tricky then it looks like you already have an idea how to do it :)

>So the new HAP-NodeJS API proposal would require providing a globally-unique UUID for all accessories - you can generate it however you like, perhaps based on a serial number. Would this work?

yes. this would be my suggestion. the accessory should generate this id and it should not be automatically based on the user visible name as this can change.

>You shouldn't have to remove the persist files ever ... at least not with the new version. Unless I'm not following?

with the new version :). yes i know. but i have not switched yet and at the moment (and especially during the development of a new service for the shim) you have to remove and restart quite often :(

**Comment by nzhome** [comment]
I too am looking into using homebridge as a simple way to get some home automation going from a Raspberry Pi2 for LimitlessLED/Milight.

 

Homebridge gives users access to Siri, and some nice integrated Scenes.    I am glad that homekit is bringing us developers together to make it better for end users.

 

Does homebridge give users ability to schedule scenes whilst the users phone is off?


Hamish.

-LimitlessLED

www.limitlessled.com

**Comment by snowdd1** [comment]
I support @justme-1968 's thoughts on the API. It would be nice to be able to put callbacks to almost all status changes (or events, but I am not familiar with the event system) a service can have.

**Comment by nfarina** [comment]
So the new API is in place and you can see some examples in [Http shim](https://github.com/nfarina/homebridge/blob/master/accessories/Http.js), as well as the Lock+Light+TemperatureSensor accessories in HAP-NodeJS repo. @snowdd1 will this API work for your purposes?

**Comment by snowdd1** [comment]
Yesterday a tried a very basic light shim for knx ( you'll can find it here: https://gist.github.com/snowdd1/628d19bd87317f11afe0 ) that I created by modding the http shim. I still need to figure out how to use the onRegister replacement to get the cached values updated, I saw some of it (maybe all) in @cflurin 's gists with the fhem platform shim, I think. 
Thanks both of you for the fine work!

**Comment by snowdd1** [comment]
Ok. didn't find it there. fhem shims actively uses `longpoll()` timer events. I simply want to assign a callback that has access to characteristic.setValue().
I have understood that - as we don't do the copying process any more - we can somehow directly get the characteristics object during API filling of the details.

In the fhem shim I found:
````
    var FhemSwitchService = new Service.Switch();
    this.currentCharacteristic = FhemSwitchService
      .getCharacteristic(Characteristic.On)
      .on('get', this.getPowerState.bind(this))
      .on('set', this.setPowerState.bind(this));
````
so I now _assume_ I can use the characteristics object immediatly to pass it to my callback?

like
```` 
var mySwitchService = new Service.Switch();
currentCharacteristic= mySwitchService.getCharacteristic(Characteristic.On);
// assume a function that takes an KNX address and a callback(value)
registerKnxCallback(this.myKNXaddress, currentCharacteristic.setValue(value).bind(this));
````
so when the event kicks in and calls the callback with a new value it should hit the right Characteristics object. 
   -   Do I need the `.bind(this)` thing for `setValue()` to hit the right `this`? 
   -   What about the `context` we talked about above?

Best regards
Raoul

**Comment by cflurin** [comment]
Try
``` javascript
var mySwitchService = new Service.Switch();
var currentCharacteristic= mySwitchService.getCharacteristic(Characteristic.On);
// assume a function that takes an KNX address array and a callback(value)
registerKnxCallback(this.listen_addresses, currentCharacteristic).bind(this));
````
and in your KNX function:
````jaavascript
currentCharacteristic.setValue(your KNX value);
````

**Comment by snowdd1** [comment]
Cool, thanks I'll try this evening!

**Comment by snowdd1** [comment]
By the way, what exactly does the `Characteristic.On` in 
`lightbulbService.getCharacteristic(Characteristic.On)` do?
From the `Service.js` I read that `getCharacteristic(name)` requires a string to search for the characteristic. What is *Characteristic.On*?

**Comment by nfarina** [comment]
The `getCharacteristic` and `getService` methods can search based on the name string, or can also search for a characteristic and service instance that matches the given type. `Characteristic.On` is a subclass of `Characteristic` (see [HomeKitTypes.js](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js).

You can also just hang on to your instance of Characteristic that you created and call it directly if you don't want to search for it like this every time - this is just a convenience method.

**Comment by snowdd1** [comment]
Ahhh, I found it! So if you do a `var myService = new Switch.Service()` you get a prepared service object with an "On" characteristic. As it is not returned directly, you have to go searching using `myService.getCharacteristic(TemplateCharacteristic)`
Right

**Comment by nfarina** [comment]
Ah; yes that's correct :)

**Comment by snowdd1** [comment]
I have now started with a accessory type shim (for practicing :smile: ) and still end up with strange errors. The first ten were spelling mistakes on my side like typos in my ip addresses :-1: .
I put the shim in a gist at https://gist.github.com/snowdd1/628d19bd87317f11afe0 
I currently fail with

> Accessory [Homebridge] Setting Characteristic "On" to value 1 +2ms
>Setting power to 1
>DEBUG in knxwrite
>DEBUG in created empty connection, trying to connect socket to 192.168.178.205:6720
>DEBUG got dest=2821
>DEBUG opened TGroup
>knx data sent
>  EventedHTTPServer [192.168.178.85] HTTP Repsonse is finished +45ms
>/home/pi/homebridge/node_modules/HAP-NodeJS/lib/Characteristic.js:121
>  if (this.listeners('set').length > 0) {
>           ^
>TypeError: undefined is not a function
>    at Object.Characteristic.setValue (/home/pi/homebridge/node_modules/HAP-NodeJS/lib/Characteristic.js:121:12)

and now wonder why `this` or so is undefined. But I see midnight coming to my time zone and I should better have a second look at it tomorrow :grimacing:

**Comment by snowdd1** [comment]
Ok, it was a parameter unmatched or a wrong `.bind(this)`.
Now a have a pretty loop with the `setValue` events, have to look for the `context` thing.

**Comment by cflurin** [comment]
"pretty loop" do you mean an endless loop?

**Comment by snowdd1** [comment]
right, but I just found it. Now I have a `context='fromKNXbus'` set in the `setValue` and a comparision in `setPowerstate()`for the context.
Right now I am investigating why *EVE* does not react on events. If I do a setValue() with an updated value, it was supposed to be pushed to the iOS devices. I already included an `onCharacteristic.supportsEventNotification=true;` in my service. You can see it in my updated gist.

**Comment by snowdd1** [comment]
Solved by waiting some minutes :smile: for an unknown background update of EVE's properties, now she's reacting also to the changes on the bus (Wife turns light on/off by using hardware switch :grin: )
Hooray!

**Comment by snowdd1** [comment]
I left some of my learning in the wiki. Please have a look if was totally off.

**Comment by nfarina** [comment]
Glad to hear you got things working! So is the connection between physical switch and lights accomplished via Siri? Or by your accessory code?

Also *huge* thanks for writing up that wiki page, that is incredibly helpful.

**Comment by cflurin** [comment]
Comment on:
````javascript
      .addCharacteristic(new Characteristic.Brightness())
```
I used it without "new" (probably incorrect)
````javascript
      .addCharacteristic(Characteristic.Brightness())
````
but it works.

**Comment by nfarina** [comment]
If you'd like cleaner syntax, you can omit the new and the parens entirely:

```js
.addCharacteristic(Characteristic.Brightness)
```

I'm not sure what will happen if you omit new but leave the parens :)

**Comment by cflurin** [comment]
You are right! In used it without parens.

**Comment by snowdd1** [comment]
The connection between physical switch and the light is the KNX bus, more exact: the bus connects the switch (called a sensor) with an actuator that is turning the energy on the cable to the lamp on and off. That bus wire connects all wall light switches, all room thermostats, all blind actuators, light actuators, floor heating vents, a sunlight and a rain sensor on the roof etc. 
The app is really a bridge between the KNX world and the HomeKit World, allowing events to pass to the other side.

**Comment by snowdd1** [comment]
@cflurin Did you manage to get a platform shim for the new API to running?

**Comment by snowdd1** [comment]
>exposes a single function "accessories" that passes a callback you call **when you're done** creating your accessories

> The simplest example is probably the Sonos platform

@nfarina  Does the Sonos platform work with more than one device? It calls the callback once for each sonos device, which might or might not work depending on how the `publish` function works in https://github.com/nfarina/homebridge/blob/master/app.js#L139
Or am I completely wrong?

**Comment by snowdd1** [comment]
Once again, me. The platforms expose (export) their accessory prototype, though I do not see why; except for the FHEM platform (old API) which doesn't. I would assume that platforms can have accessories of all types, which might have different prototypes?

**Comment by justme-1968** [comment]
i did not export the accessory prototype as it was not necessary. and i think it is cleaner and see no reason why it should be exposed. 

currently all fhem devices use the same accessory type but that will probably change if i switch it ti the new api.

**Comment by cflurin** [comment]
@snowdd1: It isn't my intention to implement a platform Shim ( justme is working on that). I think the Accessory Shim is more flexible an allows to use Shims from different developers. But more important for me: I can adapt my Shims for my requirements and for special devices (Fhem supports several protocols and numerous devices).

**Comment by nfarina** [comment]
@snowdd1 You are correct! The Sonos platform shim is incorrect - this will not work. It needs to wait until all accessories are discovered then call the callback once.

**Comment by snowdd1** [comment]
After some working with homebridge, I discovered that the platform idea is great, but does not apply to a naked KNX network, as auto discovery is not possible there. If you have FHEM set up for KNX, that might be possible, but I am not into FHEM. 
Using the platform pattern has only one little advantage: to have one module where singleton-like objects can reside, such as the listener connection on the bus; that's why I will keep it there.
However, I will code the functionality of the accessories into accessory shims that are then summoned by the platform shim, so it is basically behaving like `loadAccessories()` in `app.js` except it makes use of `loadPlatforms()`and `loadPlatformAccessories` to create the log and proper objects.

**Comment by nfarina** [comment]
How do you identify your KNX devices if they can't be auto-discovered? Does the user need to input the IP address of each one or something like that?

**Comment by snowdd1** [comment]
*Something like that* it is. KNX devices are listening to "Group Addresses", one or many, but these all have to be configured using a special software tool. 
The bus system is quite old - it dates back to the 1980's, so it is no wonder that it talks a strange dialect at 9600 baud on a thin twisted pair cable that resembles a telephone wire more than an Ethernet cable.
I tried to use an export file from the configuration software to save users from creating their own lists again - but the file seems to be different at various versions of the software, so I got mixed feedback (in German KNX user forum, that is)

In the config.json for the accessory shims you need to enter something like
````javascript
     "accessories": [
        {
            "accessory": "knxlamp",
            "name": "Office Lamp",
            "description": "KNX Basic Light shim",
            "group_address": "1/3/5",
            "listen_addresses": ["1/0/0"],
            "can_dim": true, 
            "brightness_group_address" : "1/3/10",,
            "brightness_listen_addresses" : "1/3/12",
            "knxd_ip": "192.168.178.205"  ,
            "knxd_port": 6720        
         }
    ]
````
(sample for my office ceiling light)

The knxd is a peace of software that can talk to KNX hardware, e.g. using a raspberry and a tpuart chip set.

**Comment by snowdd1** [comment]
Off topic for platforms, but HAP nevertheless:
After a lot of restarts today my server stopped reacting to http events - did you ever had that?
I already cleared the homekit config in iCloud, thinking that I messed up there in between, but did not help, neither did clearing persist/ , nor restarting the raspberry pi.
Any idea?

**Comment by cflurin** [comment]
try changing the username:
````javascript
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
````
e.g. 
````javacrispt
        "username": "CC:22:3D:E3:CE:31",
````

**Comment by snowdd1** [comment]
30 minutes after clearing everything it commenced working again, seems to be some kind of iCloud propagating everything to the devices or so.

**Comment by snowdd1** [comment]
A more general question regarding the distinction between DEVICES and SERVICES:
I was just thinking about putting more or less everything that is in ONE ROOM into ONE DEVICE, why should we need artificial devices (or physical) in an iCloud world?
As far as I have understood now, a DEVICE can have a lot of services, so why shouldn't I put the lightbulb SERVICE and the thermostat SERVICE and the blinds SERVICE into one DEVICE?

Any opinions on that?

**Comment by snowdd1** [comment]
oh, can I have multiple services of the same type in one device?

**Comment by cflurin** [comment]
As far as I know you can't do it. Take a look at the HK Simulator.

**Comment by snowdd1** [comment]
... I don't even have a mac :disappointed:

**Comment by snowdd1** [comment]
:warning: I just learned (again :cry: ) that iCloud synced activities are VERY slow. Cleared my homekit on my iPad, to no avail, then on the iPhone, no changes... ten minutes later it was empty when looking at the iPad, created a new home, added homebridge, AND THEN IT GOT CLEARED AGAIN from the second request I made on the iPhone (I think, it was the latter).

**Comment by snowdd1** [comment]
I put my first platform version online in my fork, branch knx-dev.

**Comment by justme-1968** [comment]
i'm not sure why you would want to mix the lightbulb and the thermostat into one device. this would make it impossible to address them by siri, you would get conflicts for characteristics like power as (most?) apps will show the power state on the device level.

**Comment by snowdd1** [comment]
I already changed my mind on that issue. Though Siri is adressed by the SERVICE name, not the accessory name (my first HAP-nodeJS implementation for KNX failed at that), EVE and myTouchHome cannot properly handle multiple "On" service-characteristics. EVE mixes them up and myTouchHome does not show the service names at all, so you end up having a lot of "LIGHTBULB (on/off)" buttons but no names on them. See #139 (closed).
I now leave it to the end user to decide how to package the services, see 
https://github.com/nfarina/homebridge/blob/master/config-sample-knx.json#L21

**Comment by snowdd1** [comment]
>@snowdd1 You are correct! The Sonos platform shim is incorrect - this will not work. It needs to wait until all accessories are discovered then call the callback once.

Didn't I say... #153 ...

**Comment by snowdd1** [comment]
I have added the timeout example from sonos to the [wiki page on platforms](https://github.com/nfarina/homebridge/wiki/On-Programming-Platforms)

By the way: If you notice completely strange words in my posts I've certainly forgotten to switch my iPhone keyboard language (and hence auto-correct) from German to English. Some of them I found myself and edited my posts.. :-1:

**Comment by nfarina** [comment]
What do you think of platforms being more for discovery at setup-time, and not for discovery every time the server starts? So for instance, you might run a command line like:

```sh
> homebridge discover sonos
Discovering "sonos" platform devices...
Found 2 new sonos devices:
   1. Master Bedroom
   2. Living Room
Which devices would you like to add to your config.json file?
> all
Added 2 devices to config.json.
```

So now when you startup homebridge, it starts instantly since it will remember all previously discovered devices.

**Comment by maddox** [comment]
What about stale IP addresses?

**Comment by nfarina** [comment]
Ah, good point. That kind of sinks it.

**Comment by snowdd1** [comment]
What happens to devices that are discovered once and re-discovered after a reboot, probably with changed IP addresses? Are they identified as the same device as the name did not change, or has the user to re-assign them to the HK room/zone whatever? 

What about platforms being able to "inject" accessories at runtime?
I tried to read the code of accessory.js but found no hint whether an accessory could be added at runtime, but also no hint against it either. So probably neither setup-time nor start-time would be the best, but the ability to add device at any time - you could also buy and power a new device! If the platforms are either able to poll the network say, every 15 Minutes or any definable interval, or are actively notified by the device by broadcasting its presence (are there device that do that?), they could create a new accessory.
I think the HAP-nodeJS code is currently able to cope with that in non-bridged mode, as long as you 
>Core.js
````javascript
  // publish this Accessory on the local network
  accessory.publish({
    port: targetPort++,
    username: accessory.username,
    pincode: accessory.pincode
  });
````
publish the new accessory after discovery.
I am not yet through the code, but would assume that
>BrisgedCore.js
````javascript
// Add them all to the bridge
accessories.forEach(function(accessory) {
  bridge.addBridgedAccessory(accessory);
});
````
would also be able to do the trick. 
Any thoughts on that?

**Comment by nfarina** [comment]
So that would be the best user experience in my opinion - being able to automatically discover and add new accessories at runtime. But how would old devices that you've removed from, say, KNX, get removed from homebridge?

**Comment by justme-1968** [comment]
i still had no time to look into this and convert the fhem shim to the new api but i think this is how it should work. newly discovered devices should automatically appear in the pairing dialog if not paired and should disappear if they are not available. this is how the wwdc demo looked like.

**Comment by snowdd1** [comment]
I think Nick is right we still might need a `removeBridgedAccessory()` to remove accessories at runtime. It might also be a good idea to put accessories with no traffic (ie no events) for a given time span in "presumably dead" list for the user to remove them in the future web list. 
I do not have a platform with dynamic discovery (a wired KNX installation is rather static, changes require programming anyhow) so I am not sure how the platform can notify about the "vanishing " of devices.

**Comment by nzhome** [comment]
In the milight platform, multiple LimitlessLED bridges should be discoverable.  It can work like their app, it stores MAC address and IP address. after .255 UDP discovery broadcast, when the ip address changes it still matches the MAC address. and keeps the same names of the accessories.

**Comment by justme-1968** [comment]
i have just started to convert the fhem platform shim to the new bridge api.

is there a reason that the new context parameter for the set event ist has not also been added to the onUpdate callback?

that makes porting a little easier.

**Comment by justme-1968** [comment]
one more problem: i'm using a custom characteristic vor the volume of sonos devices. this did work with the old version. in the new version the current volume is displayed in eve but not adjustable. with homekitdemo i can see that the min and max values are nil

after some looking in HAP-NodeJS/lib/Characteristic.js  and HAP-NodeJS/lib/AccessoryLoader.js i found that the first uses maximumValue and minimumValue but the later initializes minValue and maxValue from designedMinValue and designedMaxValue. is this intentional? 

but changing AccessoryLoader.js to use maximumValue and minimumValue does not help. what is it that i'm missing ?

**Comment by snowdd1** [comment]
@justme-1968 
> after some looking in HAP-NodeJS/lib/Characteristic.js  and HAP-NodeJS/lib/AccessoryLoader.js

If you ended up in [parseCharacteristicJSON](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/AccessoryLoader.js#L124) then your shim is still using the old format, or the use of the API was not recognized by [loadDirectory](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/AccessoryLoader.js#L48).
I had a similar issue (see #41) when trying to install homebridge-knx as a plugin, the required Dependency to hap-nodejs first led to another copy of node-hapjs, which in turn made it fail *`instanceof Accessory`*

**Comment by justme-1968** [comment]
yes i know. i'm trying to switch slowly to the new api and it works for all standard services and characteristics. only for this custom characteristic it does not work.

**Comment by snowdd1** [comment]
> only for this custom characteristic it does not work

Let me guess: There is no custom characteristic in the new API. I think it is not listed in the homekit file Nick Farina parsed for obtaining the HomeKitTypes.js - or in a complete different way, so the parser soe not get it.

**Comment by nfarina** [comment]
Custom characteristics _should_ be supported in both new and old APIs.

**Comment by justme-1968** [comment]
i have now switched completely to the new api and everything works. except the custom volume characteristic. it is displayed with eve but the +/- buttons are grayed out. in HomeKitDemo i still see that the maximum, minmum and step values are nil. 

what i'm doing is this:
```
      var characteristic = new Characteristic('Volume', '99000027-0000-1000-8000-0026BB765291'); // FIXME!!!
      controlService.addCharacteristic(characteristic);

      if( !that.mappings.volume.nocache ) {
        FHEM_subscribe(characteristic, that.mappings.volume.informId, that);
        characteristic.value = FHEM_cached[that.mappings.volume.informId];
      } else {
        characteristic.value = 10;
      }

      characteristic.format = 'uint8';
      characteristic.unit = 'percentage';
      characteristic.maximumValue = 100;
      characteristic.minimumValue = 0;
      characteristic.stepValue = 1;
      characteristic.readable = true;
      characteristic.writable = true;
      characteristic.supportsEventNotification = true;
```

this is basically what worked with the old version (even with int as format, omitting the unit and a different UUID).

do you have an idea where to put some debug code to see what is actually send to homekit? ideally for the old and new version so i can compare.

or do you know of a debug homekit client that can dump more information?

the output from Characteristic.prototype.toHAP does include the correct values.

**Comment by snowdd1** [comment]
> do you have an idea where to put some debug code to see what is actually send to homekit? ideally for the old and new version so i can compare.

You can see the json at
http://\<your homebridge ip\>:\<your homebridge port\>/accessories 
like in http://127.0.0.1:51826/accessories

How do you differentiate multiple custom characteristics?

**Comment by snowdd1** [comment]
And by the way: I get the control buttons greyed out if the service type is not supported by iOS version, eg. blinds (aka window covering).
On my testing device (iPh5 with iOS9.1) I can control the blinds, on my productive Device (iPh6 iOS8.4.1) the +/- buttons are greyed out.

**Comment by justme-1968** [comment]
should the http access to the json also work with the old version? i get no result there.
the custom characteristics have the same set and get events as all other characteristics. so differentiation is no problem.

i can control my shutters with eve on iOS8.4.1 with the old and the new api. ma last test with a ios9.0 beta did also work but i have the problem that siri at least in german does not know how to control shutters with these versions.

**Comment by justme-1968** [comment]
json for the old version:
```
{"iid":10,"type":"00000027-0000-1000-8000-0026BB765291","perms":["pw","pr","ev"],"format":"int","events":true,"bonjour":false,"value":10,"description":"Adjust the Volume of this device","minValue":0,"maxValue":100,"minStep":1}]}]}]}
``` 
json for the new version:
```
{"iid":10,"type":"00000027-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"int","value":7,"description":"Adjust the Volume of this device","maximumValue":100,"minimumValue":0,"stepValue":1}]}]}]}
```

is this really the date send to homkit? then i do not understand the difference in the max/min/step names. the only other difference are the missing events and bonjour entries. but they have been removed for the standard characteristics also...

**Comment by snowdd1** [comment]
> "minValue":0,"maxValue":100,

> "maximumValue":100,"minimumValue":0

We might have an issue here. I had something similar in [another issue](https://github.com/nfarina/homebridge/issues/139#issuecomment-137994915) but thought I had a flaw at another point. @KhaosT : Do you know what HomeKit is expecting as variable names?

**Comment by KhaosT** [comment]
@snowdd1 it has to be "minValue"/"maxValue"

**Comment by snowdd1** [comment]
I'll do later this evening (Time Zone GMT+1!)

**Comment by maddox** [comment]
What exactly gets accomplished by having a custom characteristic? I just set up media players in #170 and just hacked it with the `brightness` characteristic. 

Will having this volume characteristic change the interaction with siri/homekit at all? Or will it just show different values in info.

**Comment by nfarina** [comment]
I don't think you could have Siri control it directly but you could assign it to scenes!

**Comment by maddox** [comment]
> I don't think you could have Siri control it directly but you could assign it to scenes!

What was this in reference to?

**Comment by nfarina** [comment]
Custom characteristics - but I only saw your last message so might have missed the context?

**Comment by maddox** [comment]
I was just wondering what the point of even making a custom one is, since it's providing the same thing brightness does.

**Comment by justme-1968** [comment]
@maddox siri can not control custom characteristics. at least not at the moment.

the point is that it appears as volume and not as brightness in the ui. it is grouped as volume which can give quick access in eve for example.

i think it is much cleaner. and we can at least hope that siri support will come...

@KhaosT i will check if this fixes my issue with the custom characteristic. at least it looks like it will restore the old names. but i think there is still a difference in minStep vs. stepValue between the old and new versions. which one ist the correct?

**Comment by maddox** [comment]
@justme-1968 :thumbsup:

Should this just be available from HAP-NodeJS so that's available to all of the accessories in homebridge? I'd love to use this for the things I made the other day, and the [MPD](https://github.com/nfarina/homebridge/blob/master/accessories/mpdclient.js) accessory would benefit from it as well. So we don't all have to implement it individually.

**Comment by nfarina** [comment]
I'm not clear on what modification is proposed - you should be able to define all this stuff however you'd like using the new or old API in either HAP-NodeJS or homebridge?

**Comment by maddox** [comment]
Sure, but it means everyone is going to be redefining their own volume characteristic. I figured that if it was provided already, we could avoid that.

**Comment by nfarina** [comment]
I think it would be better for HAP-NodeJS as an "official HAP library" to only define official Apple Characteristics - it should be up to users of the library to define their own (even if it involves some copy and paste).

**Comment by justme-1968** [comment]
i think it would be a good think to try to standardize on the UUID for such common things like volume. 

this would also allow to automatically switch to an homekit provided UUID for volume if apple decides to standardize this.

**Comment by maddox** [comment]
> I think it would be better for HAP-NodeJS as an "official HAP library" to only define official Apple Characteristics - it should be up to users of the library to define their own (even if it involves some copy and paste).

I hear ya on that. It keeps things honest. But @justme-1968 has a point. Since homebridge is the "hack" maybe it could keep track of those?

**Comment by justme-1968** [comment]
@KhaosT with your fix my custom characteristic works again. great! 

what about the remaining difference between minStep vs. stepValue?

**Comment by KhaosT** [comment]
@justme-1968 "stepValue" is the key HomeKit use to check against characteristic, changing it to minStep won't work...

**Comment by justme-1968** [comment]
perfect. i was just wondering about this additional difference between the old and new version.

**Comment by KhaosT** [comment]
@justme-1968 my bad, you're right... just checked with HomeKit Accessory Simulator and "minStep" is the right one. Updated the repo to fix that. Thanks for noticing ^^

**Comment by justme-1968** [comment]
even better :)

**Comment by snowdd1** [comment]
I think the issues I wanted *originally* adress with this topic have been thoroughly discussed. And others, too.
