### ISSUE TITLE
Homebridge Amazing! - Yamaha AV

### ISSUE THREAD

**Issue by jata1** [nfarina/homebridge#952]
Hi,

I wanted to say thanks to all the contributors and community. This is great work. I have homebridge working with my Nest thermostat on my RPi. I thought it was impossible for google/nest to talk to homekit/apple! 

My next project is my Yamaha AVR. I see there is a home bridge-yamaha plugin but it's limited to zone 1 so it doesn't meet my needs.

I have seen yamaha-nodejs has good functionality but i don't know how i can integrate this with home bridge / home kit.

I have also heard about node red. I think this allows you to link devices and i was hoping that i could somehow link my AVR to home bridge using this. 

My aim is to control the AVR using the home app. I need to select zone, select source on the zone and control volume.

**Comment by simonrb2000** [comment]
You wouldn't be able to control all of the features within HomeKit as there is no standard. You can map power and volume to a light dimmer and do it that way. Selecting zones won't work, maybe as a custom characteristic however it won't work within the native Home App, you'd need to use Eve or the non native Home app.

Sent from my iPhone

On 26 Nov 2016, at 09:30, jata1 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

I wanted to say thanks to all the contributors and community. This is great work. I have homebridge working with my Nest thermostat on my RPi. I thought it was impossible for google/nest to talk to homekit/apple!

My next project is my Yamaha AVR. I see there is a home bridge-yamaha plugin but it's limited to zone 1 so it doesn't meet my needs.

I have seen yamaha-nodejs has good functionality but i don't know how i can integrate this with home bridge / home kit.

I have also heard about node red. I think this allows you to link devices and i was hoping that i could somehow link my AVR to home bridge using this.

My aim is to control the AVR using the home app. I need to select zone, select source on the zone and control volume.

-

**Comment by jata1** [comment]
thank you for the help. so there is no way to link yamaha-nodejs to homebridge?

Is the only option to develop home bridge-yamaha to include a setting for zone?
