### ISSUE TITLE
using two (or more) accessories in one combined accesory

### ISSUE THREAD

**Issue by aleksandrsivanovs** [nfarina/homebridge#953]
Hi!

I'm looking for a way to use already written accessory plugin inside another accessory plugin.
My usecase is such: I have [homebridge-eq3ble](https://github.com/maxnowack/homebridge-eq3ble) plugin which can show the target temperature on thermostat. However, the device doesn't provide way to get current temperature. 
for current temperature I have accurite sensors which report to mqtt and then feed to homebridge with help of [homebridge-mqtt-temperature](https://github.com/mcchots/homebridge-mqtt-temperature).
So, I want to bridge those two accessories in one thermostat. 
However, I want to make it universal and give the ability to connect any temperature sensors registered in homebridge and this eq-3 thermostat.

so, the question is:
a) is there possibility to programmatically get all registered accessories from inside another accessoryA (or serviceA), feed the accessoryA with values from chosen accessoryB (how to subscribe and get values - I know)  and hide the chosen accessoryB from homebridge advertised accessories set?

or:
b) is there a way given name and configuration parameters of accessoryA initialize it inside other accessoryB (universally, without knowing the constructor and other methods of chosen accessoryA) ? (and then I know the way to subscribe to the values of abstract TemperatureAccessory and feed it's values to accessoryB)

**Comment by cflurin** [comment]
As far as I know this isn't possible.
But have a look at:
http://nodered.org/ (Node-RED is a tool for wiring together hardware devices, APIs and online services.)
https://flows.nodered.org/node/node-red-contrib-eq3-bluetooth
and
https://github.com/cflurin/homebridge-mqtt

Node-red is preinstalled on Rpi (jessie) and a mqtt-broker like mosquitto is easy to install on the same Rpi running node-red and homebridge.

**Comment by aleksandrsivanovs** [comment]
yeah, that was understanding as well (on topic of homebridge).
I think I will do just consuming temperature from mqtt topic - as this is general enough. 
(I just didn't want to add more dependencies like node-red for such simple task.

thank you
