### ISSUE TITLE
Multiple Platform/Accessories

### ISSUE THREAD

**Issue by zfoo83** [nfarina/homebridge#954]
Hi all, I am trying to add fibaro and LGTv2 plugin and got an error. Can anyone help? The error is 

[11/27/2016, 9:18:02 PM] There was a problem reading your config.json file.
[11/27/2016, 9:18:02 PM] Please try pasting your config.json file here to validate it: http://jsonlint.com
[11/27/2016, 9:18:02 PM] 
/usr/lib/node_modules/homebridge/lib/server.js:194
    throw err;
    ^

SyntaxError: Unexpected token a in JSON at position 473
    at Object.parse (native)
    at Server._loadConfig (/usr/lib/node_modules/homebridge/lib/server.js:188:19)
    at new Server (/usr/lib/node_modules/homebridge/lib/server.js:49:23)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22

My Config.Json is as below.

{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": ****,
		"pin": "****"
	},

	"description": "This is an example configuration file. You can use this as a template for creating your own configuration file.",

	"platforms": [{
		"platform": "FibaroHC2",
		"name": "FibaroHC2",
		"host": "xxxxx",
		"username": "xxxx",
		"password": "xxxxx",
		"grouping": "none",
		"pollerperiod": "2"
}],

"accessories": [{
	"accessory": "LGTv2",
      "name": "TV",
      "mac": "*****",
      "ip": "xxxx"
    }
  ]

}

Can anyone help on this?

**Comment by cflurin** [comment]
port and pin missing!
```sh
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},
```

**Comment by zfoo83** [comment]
Hi, 

I have tried input the port and pin, but still having the same error. Any more ideas?

**Comment by cflurin** [comment]
have you checked you config.json here?: http://jsonlint.com
Valid JSON?

**Comment by zfoo83** [comment]
Yes. I have checked and its a valid Json. not sure whats wrong! :(

**Comment by cflurin** [comment]
try using only the platform or the accessory at once.

homebridge version?
Raspberry Pi?
OS version? 
node version?

**Comment by maragelis** [comment]
You are missing " quotes on the word platform

**Comment by zfoo83** [comment]
Hi,

I have tried. If its only the Platform, it works. But when I only run with
the accessory, it does not. And the same error happens when I run with both.

Any more ideas? Sorry for the trouble as I am totally new to this and not
sure what is going on.

Thanks

**Comment by cflurin** [comment]
I'm afraid, but if you don't answer the questions, wen cannot help you.

homebridge version?
Raspberry Pi?
OS version?
node version?

**Comment by maragelis** [comment]
Can you try this and tell us


{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},
	
	"platforms": [{
		"platform": "FibaroHC2",
		"name": "FibaroHC2",
		"host": "xxxxx",
		"username": "xxxx",
		"password": "xxxxx",
		"grouping": "none",
		"pollerperiod": "2"
	}],

	"accessories": [{
		"accessory": "LGTv2",
		"name": "TV",
		"mac": "3b:3b:3b:3b:66:33",
		"ip": "192.168.2.1"
	}]

}
