### ISSUE TITLE
Unable to view camera feed using homebridge-camera-ffmpeg

### ISSUE THREAD

**Issue by andreweller** [nfarina/homebridge#955]
Trying out homebridge-camera-ffmpeg plugin but not getting far. 

I have a valid URL that will play camera's video in VLC on a Mac on the same local network, but when I try to pull up the video using Home app on iOS, I don't get a video to appear. Instead I get an icon of a camera with a slash through it, along with the text "No Response This camera is not responding".

here is what I see in homebridge output log: 
[11/27/2016, 8:59:14 AM] Homebridge is running on port 51826.
-re -i rtsp://<redactedUNAME>:<redactedPASS>@10.0.1.45:88/videoMain -threads 0 -vcodec libx264 -an -pix_fmt yuv420p -r 30 -f rawvideo -tune zerolatency -vf scale=1280:720 -b:v 299k -bufsize 299k -payload_type 99 -ssrc 1 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params l37rfafaE1zXMpXOYdSlx/2+M60MSRZDpqUQo+qp srtp://10.0.1.54:64634?rtcpport=64634&localrtcpport=64634&pkt_size=1378
[11/27/2016, 8:59:22 AM] Loaded plugin: homebridge-camera-ffmpeg
[11/27/2016, 8:59:22 AM] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
[11/27/2016, 8:59:22 AM] ---

here is what I see in homebridge error log:
Error: spawn ffmpeg ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
events.js:160
      throw er; // Unhandled 'error' event
      ^

here is what I have in the config.json:
        {
  			"platform": "Camera-ffmpeg",
  			"cameras": [
    			{
      				"name": "Back Door",
      				"videoConfig": {
      					"source": "-re -i rtsp://<redactedUNAME>:<redactedPASS>@10.0.1.45:88/videoMain",
      					"maxStreams": 2,
      					"maxWidth": 1280,
      					"maxHeight": 720,
      					"maxFPS": 30
      				}
    			}
  			]
		}

**Comment by andreweller** [comment]
for privacy/security reasons I removed username and password from the rtsp URL, pretend they are still there :)

**Comment by KhaosT** [comment]
ENOENT meaning system cannot find ffmpeg. Please make sure you installed it before using the plugin.

**Comment by andreweller** [comment]
but it is installed:

Last login: Sun Nov 27 08:45:00 on ttys002
server:~ andrew$ which ffmpeg
/usr/local/bin/ffmpeg
server:~ andrew$ ffmpeg
ffmpeg version 3.2.1 Copyright (c) 2000-2016 the FFmpeg developers
  built with Apple LLVM version 8.0.0 (clang-800.0.42.1)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/3.2.1 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-libmp3lame --enable-libx264 --enable-libxvid --enable-opencl --disable-lzma --enable-vda
  libavutil      55. 34.100 / 55. 34.100
  libavcodec     57. 64.101 / 57. 64.101
  libavformat    57. 56.100 / 57. 56.100
  libavdevice    57.  1.100 / 57.  1.100
  libavfilter     6. 65.100 /  6. 65.100
  libavresample   3.  1.  0 /  3.  1.  0
  libswscale      4.  2.100 /  4.  2.100
  libswresample   2.  3.100 /  2.  3.100
  libpostproc    54.  1.100 / 54.  1.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man ffmpeg'
server:~ andrew$

**Comment by KhaosT** [comment]
Can you do a ``echo $PATH`` in terminal and see what's there?

**Comment by andreweller** [comment]
server:~ andrew$ echo $PATH
/opt/local/bin:/opt/local/sbin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Server.app/Contents/ServerRoot/usr/bin:/Applications/Server.app/Contents/ServerRoot/usr/sbin

**Comment by KhaosT** [comment]
So ``/usr/local/bin/`` is missing from there and nodejs uses $PATH to figure out where to look for executables. Try run ``export PATH="/usr/local/bin:$PATH"`` in the terminal and then run homebridge again.

**Comment by andreweller** [comment]
isn't /usr/local/bin the 5th one in the list?
anyways, I ran that command and then re-ran homebridge but it didn't change behavior.

**Comment by KhaosT** [comment]
Ah my bad, I did a search on "/usr/local/bin/" which returns no result. Not quite sure why this is happening then...

**Comment by andreweller** [comment]
me either 😢

**Comment by KhaosT** [comment]
If you don't mind manually make some changes to the code, try edit ``/usr/local/lib/node_modules/homebridge-camera-ffmpeg/ffmpeg.js``, change [here](https://github.com/KhaosT/homebridge-camera-ffmpeg/blob/master/ffmpeg.js#L127) and [here](https://github.com/KhaosT/homebridge-camera-ffmpeg/blob/master/ffmpeg.js#L238). Instead of just ``ffmpeg``, try replace it with ``/usr/local/bin/ffmpeg`` and see if it makes a difference

**Comment by andreweller** [comment]
same behavior, but slightly different error messages:

Error: spawn ffmpeg ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
(node:3463) DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead.
(node:3481) DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead.
(node:603) DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead.

**Comment by KhaosT** [comment]
@andreweller are you sure you changed the right place? If it's the same error, it should print ``Error: spawn /usr/local/bin/ffmpeg ENOENT`` instead of what you have there.

**Comment by andreweller** [comment]
maybe not....

I did this:
```
  let ffmpeg = spawn('/usr/local/bin/ffmpeg', (imageSource + ' -t 1 -s '+ resolution + ' -f image2 -').split(' '), {env: process.env});
```
...
```
  let ffmpeg = spawn('/usr/local/bin/ffmpeg', ffmpegCommand.split(' '), {env: process.env});
```

**Comment by andreweller** [comment]
After saving those changes, I killed homebridge and retried. When it did the same thing, I rebooted machine and retried. When it continued to do the same thing I replied with the results.

**Comment by andreweller** [comment]
oh! another reboot and now it seems to work.

 ¯\_(ツ)_/¯

**Comment by KhaosT** [comment]
This is really strange... Guess some module caches in nodejs maybe.

**Comment by andreweller** [comment]
hmm.... not live video though... it is showing a preview with a counter in the top corner... was XXs ago, not Xm ago.

**Comment by KhaosT** [comment]
The ``XXs ago`` is a Home app thing. When you tap the view, you didn't get a live stream?

**Comment by andreweller** [comment]
viewing it full screen shows a still frame of the camera view, with an incrementing counter in the top right.

**Comment by KhaosT** [comment]
Wat? Can you post a screenshot?

**Comment by andreweller** [comment]
sure, just don't judge my messy house :)
![img_0116](https://cloud.githubusercontent.com/assets/6276167/20653035/e07e742a-b4ba-11e6-9412-e8ad1fcc6a51.PNG)

**Comment by KhaosT** [comment]
@andreweller the one with the navigation bar, I want to see what's the status of the streaming

**Comment by andreweller** [comment]
![img_0117](https://cloud.githubusercontent.com/assets/6276167/20653053/48cf3a64-b4bb-11e6-9050-009b4119bc22.PNG)

**Comment by KhaosT** [comment]
It's ``Loading...`` so it didn't fail yet. If you wait a few seconds, does it change to live or show an error?

**Comment by andreweller** [comment]
the top left indicator seems to be a lie. 
The image doesn't update even though the status does:
![img_0118](https://cloud.githubusercontent.com/assets/6276167/20653092/b79e6212-b4bb-11e6-926f-486b208fee3c.PNG)
![img_0119](https://cloud.githubusercontent.com/assets/6276167/20653094/c1d935ae-b4bb-11e6-930d-1fb3ead2bc19.PNG)

**Comment by KhaosT** [comment]
If it says "Live" then HomeKit believes it's streaming live. If you move in front of the camera, you don't see anything changes?

**Comment by andreweller** [comment]
ah... my wife and cat are just very good at the mannequin challenge. 
the image does refresh, but less than 1fps. and it is very delayed.

**Comment by KhaosT** [comment]
The low fps and latency can be caused by a lot of stuff...What is the device running homebridge and what camera are you using?

**Comment by andreweller** [comment]
2009 era Mac mini, foscam camera.
just peeped activity monitor and ffmpeg is cranking ~140% cpu utilization. I guess that explains it.

**Comment by KhaosT** [comment]
In that case if Foscam provides a lower resolution stream you can try to switch to that. Also, try to lower the maxWidth and maxHeight to 640 and 360 and see if situation improves. You may need to remove the accessory from HomeKit and add them back in order for this to take effect.

**Comment by alessandro893** [comment]
Hello, I have the same issue, still picture reloads, but video did not starts.
ffmpeg installed from Macports.

![img_0976](https://cloud.githubusercontent.com/assets/4077478/20656462/9fdaacde-b557-11e6-8ab6-0bc1bbc79e90.PNG)

**Comment by Maxmudjon** [comment]
@alessandro893 Привет это у тебя работает, у меня что то не хочется запускать

**Comment by alessandro893** [comment]
@Maxmudjon У меня работает только статичная картинка, если у тебя не цепляется ffmpeg, то попробуй добавить путь к бинарнику в исполняемый launchdaemon файл homebridge'а.
![img_0979](https://cloud.githubusercontent.com/assets/4077478/20703874/9fde1cac-b647-11e6-8f92-1ac73fc169ad.JPG)

**Comment by Maxmudjon** [comment]
@alessandro893 запускал но видео или стрим зависает с шахматами показывают

**Comment by Maxmudjon** [comment]
![photo1204279221268145](https://cloud.githubusercontent.com/assets/23142922/20861881/edf4b3ec-b9bc-11e6-87ab-2da2b2d1c82f.jpg)

**Comment by Maxmudjon** [comment]
@alessandro893 я Raspberry PI 3 изпользываю а не MACBOOK
