### ISSUE TITLE
Homebridge Automation Service does not start

### ISSUE THREAD

**Issue by ChrisSthler** [nfarina/homebridge#956]
Hey can someone help me?

It starts running and then stops it again.

`pi@raspberrypi:~ $ sudo systemctl start homebridge
pi@raspberrypi:~ $ sudo systemctl status homebridge
● homebridge.service - Homebridge Automation Service
   Loaded: loaded (/etc/systemd/system/homebridge.service; disabled)
   Active: active (running) since So 2016-11-27 20:40:57 CET; 267ms ago
     Docs: https://github.com/nfarina/homebridge
 Main PID: 790 (node)
   CGroup: /system.slice/homebridge.service
           └─790 /usr/bin/node /home/pi/node_modules/homebridge/bin/homebridge -D

Nov 27 20:40:57 raspberrypi systemd[1]: Started Homebridge Automation Service.
pi@raspberrypi:~ $ sudo systemctl status homebridge
● homebridge.service - Homebridge Automation Service
   Loaded: loaded (/etc/systemd/system/homebridge.service; disabled)
   Active: failed (Result: start-limit) since So 2016-11-27 20:41:00 CET; 1s ago
     Docs: https://github.com/nfarina/homebridge
  Process: 812 ExecStart=/usr/bin/node /home/pi/node_modules/homebridge/bin/homebridge -D (code=exited, status=1/FAILURE)
 Main PID: 812 (code=exited, status=1/FAILURE)

Nov 27 20:40:59 raspberrypi systemd[1]: homebridge.service: main process exited, code=exited, status=1/FAILURE
Nov 27 20:40:59 raspberrypi systemd[1]: Unit homebridge.service entered failed state.
Nov 27 20:41:00 raspberrypi systemd[1]: homebridge.service holdoff time over, scheduling restart.
Nov 27 20:41:00 raspberrypi systemd[1]: Stopping Homebridge Automation Service...
Nov 27 20:41:00 raspberrypi systemd[1]: Starting Homebridge Automation Service...
Nov 27 20:41:00 raspberrypi systemd[1]: homebridge.service start request repeated too quickly, refusing to start.
Nov 27 20:41:00 raspberrypi systemd[1]: Failed to start Homebridge Automation Service.
Nov 27 20:41:00 raspberrypi systemd[1]: Unit homebridge.service entered failed state.
`

**Comment by ynnoj** [comment]
Encountering the same issue. Service starts, but is constantly restarting.

**Comment by cbredesen** [comment]
I'm having a similar but unrelated problem. Have you tried upping the debut level and looking at the output?  In /etc/default/homebridge, un-comment the DEBUG=* line. Then restart it. 

You can then use `sudo systemctl -u homebridge` to see what's up. What does that report?

**Comment by TS-Tec** [comment]
I have problems too... after updating my system, I get:
```
pi@raspberrypi:~ $ systemctl status homebridge
● homebridge.service - Node.js HomeKit Server
   Loaded: loaded (/etc/systemd/system/homebridge.service; enabled)
   Active: activating (auto-restart) (Result: exit-code) since Wed 2016-12-21 22:47:36 CET; 3s ago
  Process: 1588 ExecStart=/usr/local/bin/homebridge $HOMEBRIDGE_OPTS (code=exited, status=1/FAILURE)
 Main PID: 1588 (code=exited, status=1/FAILURE)
```

Checked everything.. I should work!
I uncommented the DEBUG=* line but with `journalctl -u home bridge` i get
`No journal files were found.`

Any idea??

**Comment by snowdd1** [comment]
Try `journalctl` with `sudo`

**Comment by TS-Tec** [comment]
Thank you snowdd1!

Here is the relevant output:
```
Dec 21 23:48:25 raspberrypi homebridge[745]: /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:222
Dec 21 23:48:25 raspberrypi homebridge[745]: throw new Error("Cannot add a bridged Accessory with the same UUID as another bridged Accessory: " + existing.UUID);
Dec 21 23:48:25 raspberrypi homebridge[745]: ^
Dec 21 23:48:25 raspberrypi homebridge[745]: Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 5490dcc9-e006-4758-bf38-30006adfbeaa
Dec 21 23:48:25 raspberrypi homebridge[745]: at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:222:13)
Dec 21 23:48:25 raspberrypi homebridge[745]: at Server._configCachedPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:348:18)
Dec 21 23:48:25 raspberrypi homebridge[745]: at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:83:8)
Dec 21 23:48:25 raspberrypi homebridge[745]: at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
Dec 21 23:48:25 raspberrypi homebridge[745]: at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
Dec 21 23:48:25 raspberrypi homebridge[745]: at Module._compile (module.js:409:26)
Dec 21 23:48:25 raspberrypi homebridge[745]: at Object.Module._extensions..js (module.js:416:10)
Dec 21 23:48:25 raspberrypi homebridge[745]: at Module.load (module.js:343:32)
Dec 21 23:48:25 raspberrypi homebridge[745]: at Function.Module._load (module.js:300:12)
Dec 21 23:48:25 raspberrypi homebridge[745]: at Function.Module.runMain (module.js:441:10)
Dec 21 23:48:25 raspberrypi homebridge[745]: at startup (node.js:134:18)
Dec 21 23:48:25 raspberrypi homebridge[745]: at node.js:962:3
Dec 21 23:48:25 raspberrypi systemd[1]: homebridge.service: main process exited, code=exited, status=1/FAILURE
Dec 21 23:48:25 raspberrypi systemd[1]: Unit homebridge.service entered failed state.
Dec 21 23:48:35 raspberrypi systemd[1]: homebridge.service holdoff time over, scheduling restart.
```

**Comment by snowdd1** [comment]
There are still 3 platform plugins active according to the output. If you want to do a clean start you need to remove the installations as well.

**Comment by TS-Tec** [comment]
Is this necessary? How should I do this?

What about
`Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 5490dcc9-e006-4758-bf38-30006adfbeaa`

Can you explain what this means?

**Comment by justinshuls** [comment]
@TS-Tec did you ever solve?

**Comment by pdlove** [comment]
Typically what your presenting is caused by a faulty version 2 plugin. I know HomebridgeHub is written properly and the other two don't appear to be version 2. My gut says that the zway plugin is at fault. Uninstall that and the tadoheating plugin and see if you can start it correctly.

**Comment by cpvbruno** [comment]
I could solve it by running "forever start /usr/local/bin/homebridge -U /var/homebridge" forever is a npm lib which restart script after fails
