### ISSUE TITLE
Homebridge Spotify?

### ISSUE THREAD

**Issue by joq3** [nfarina/homebridge#957]
Hi,

As Siri don't want to play music via Spotify I want to know if I can do a workaround?
I want to be able to press a button in iOS Home or say to Siri "Play Music" and it starts my receiver, changes input and starts playing Spotify automatically where I left off.
I can make the first part work, but I either have to start Spotify manually on my phone, and then select my Airplay receiver or my Android TV (Spotify Connect) to play music.

Is it possible to have Spotify on my Debian server which will autoconnect to Airplay or Spotify connect? And somehow integrate this to Homebridge?

Any ideas?

**Comment by fboulegue** [comment]
would be possible maybe via python plugin or some of the others that are available yet.

**Comment by AppleTechy** [comment]
The only way possible I see to do this is to have a homebridge plugin for your receiver and then some sort of script to trigger your Spotify action. I think HomeAssistant may be a better framework for you to work this in, and then use Homebridge to allow you to invoke the action via Siri
