### ISSUE TITLE
Apple Home App detects yamaha AVR as a switch or fan - no volume control

### ISSUE THREAD

**Issue by jata1** [nfarina/homebridge#958]
I'm using home bridge with a Nest Thermostat (nest plugin) and Yamaha AVR (yamaha plugin). Both accessories are working within the Home app in iOS 10. 

The problem i have with the Yamaha AVR is that the Home app thinks it is a switch, fan or light and it only has on/off. I need to be able to control volume but it doesn't show a volume control or any other settings.

i have also installed the Xcode app HomeKit Catalogue. This app does show audio functions in the configuration but they are flagged as custom configurations - so i think everything is available/working.

I'd like to have the volume as a slider from the long click/hold on the accessory section of the home app. 

Any ideas how to achieve this?

**Comment by fboulegue** [comment]
lights should have a % value like Philips hue LEDs ...

**Comment by jata1** [comment]
thanks but for some reason it is registered as a simple switch with only on/off. I think it needs to be registered as a dimmer switch to have this control. I have no idea how and what to configure so that the accessory is registered as a dimmer. Can you help?
