### ISSUE TITLE
How to edit config.json file for multiple platform

### ISSUE THREAD

**Issue by ChesterZhou** [nfarina/homebridge#959]
I have two platforms and worked well in separately and wonder how to combine them together into one config.json file. 
One is below:

`"platforms": [
        {
            "platform" : "yeelight",
            "name" : "yeelight"
        }`

and another is 

`"platforms": [
        {
                "platform": "AqaraPlatform",
                "sid": ["6409802da3b3", "f0b4299a5b2b", "f0b4299a77dd"],
                "password": ["02i44k56zrgg578b", "g250s2vtne8q9qhv", "syu3oasva3uqd5qd"]
        }]`

So how to combine them.

**Comment by jata1** [comment]
you need a comma (,) between each platform. something like outlined below.

copy and paste the config.json connects into http://jsonlint.com to check syntax.
 
"platforms": [ 
{ 
"platform" : "yeelight", "name" : "yeelight" 
}, 
{ 
"platform": "AqaraPlatform", "sid": ["6409802da3b3", "f0b4299a5b2b", "f0b4299a77dd"], "password": ["02i44k56zrgg578b", "g250s2vtne8q9qhv", "syu3oasva3uqd5qd"] 
}
]

**Comment by ChesterZhou** [comment]
Thanks a lot! Really appreciated as a new guy here.

**Comment by biffdog** [comment]
I am trying to add Lifx, Dyson and nest plugins but I am finding it quite difficult so could anyone help correct my work?

{
"bridge": {
"name": "Homebridge",
"username": "CC:22:3D:E3:CE:30",
"port": 51826,
"pin": "053-73-874"
},

"accessories": [
{
"accessory": "dyson-coollink",
"name": "Purifier Cool Tower",
"ip": "10.0.1.x",
"username": "...",
"password": "..."
}
],
"platforms": [
{
"platform" : "LifxLan",
"name" : "LIFX"
}
{
"platform": "Nest",

	"token" : "c.5ABsTpo88k5yfNIxZlh...",
	
	"clientId": "developer client id",
	"clientSecret": "developer client secret.",
	"code": "Pin Code",
	
	"username" : "username",
	"password" : "password"
}
],

**Comment by 4Xsample** [comment]
Let me see if I understood

I have the ewelink pluguin to use Sonoff with oem firmware and works flawless.
And I have some other pluguin I've tried but does not work and I don't know if is because there's something wrong with my JSON or with something else.

As I understood this should work, it isnt?


{ 

  "bridge": 
    { 
    "name": "Homebridge", 
    "username": "CC:12:3D:E3:**:**", 
    "port": 51816, 
    "pin": "***-09-980", 
    "manufacturer": "@nfarina", 
    "model": "Homebridge", 
    "serialNumber": "0.4.20"
    },
    
    "description": "Do the robot",
    "accessories": [],

    "platforms": 
        [{
        "platform" : "eWeLink",
        "name" : "eWeLink",
        "authenticationToken" : "*********da7e95db4c5b2c95d87b86*********",
        "apiHost" : "eu-api.coolkit.cc:8080",
        "webSocketApi" : "eu-pconnect3.coolkit.cc"
        }],

        "platform": "Camera-IP",
        "cameras": 
            [{
              "name": "iCam",
              "videoConfig": {
      	           "source": "-re -i rtsp://192.168.1.151",
                   "maxStreams": 2,
      	           "maxWidth": 1280,
      	           "maxHeight": 720,
      	           "maxFPS": 30
                              }
            }]

}

**Comment by Mtl-Biker** [comment]
I'm brand new to this and am stuck with adding more than one platform to my config.json file.  I just don't see what is wrong and I've tried several changes.  Any help would be greatly appreciated.

   	"platforms": [{
    		"platform": "Hue",
    		"name": "Hue",
    		"users": {
    			"001788FFFE66F9B9": "*******qNmI9vId8OMNZIcLz9rHD6rRyQo3sE"
    		},
    		{
    			"platform": "WeatherPlus",
    			"name": "WeatherPlus",
    			"service": "darksky",
    			"key": "*********0e753e997085be293e756510",
    			"locationGeo": [**.51284302, -**.85730743]
    		}
    	}]

**Comment by MiniGordini** [comment]
> you need a comma (,) between each platform. something like outlined below.
> 
> copy and paste the config.json connects into http://jsonlint.com to check syntax.
> 
> "platforms": [
> {
> "platform" : "yeelight", "name" : "yeelight"
> },
> {
> "platform": "AqaraPlatform", "sid": ["6409802da3b3", "f0b4299a5b2b", "f0b4299a77dd"], "password": ["02i44k56zrgg578b", "g250s2vtne8q9qhv", "syu3oasva3uqd5qd"]
> }
> ]

Thank you!
