### ISSUE TITLE
OSX 10.12.1 Can't complete the sudo npm install -g homebridge command

### ISSUE THREAD

**Issue by spopky** [nfarina/homebridge#960]
Hi I can't get homebridge to install, I had it installed and I tried adding a TP-link node and something broke so I tried uninstalling everything and starting fresh but now I can't get it to work. I know there are many threads about node.gyp but I have tried everything they suggest and I am still getting the following outputs:

SyntaxError: invalid syntax
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.1.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/homebridge/node_modules/ed25519
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
/usr/local/lib
└── (empty)

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "--unsafe-perm" "homebridge"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! ed25519@0.0.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ed25519@0.0.4 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ed25519 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ed25519
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ed25519
npm ERR! There is likely additional logging output above.

Python is at V 2.7.1

Please help, thank you.

**Comment by maragelis** [comment]
Have you installed Xcode ?

**Comment by spopky** [comment]
Yes updated to the new version which fixed some errors I was getting
previously but not the ones I pasted that have been there all along.

Steve Popky
Tombstonecity
631-903-3113

**Comment by maragelis** [comment]
I am stating the obvious, you ran the install with sudo ?
You opened xcode and agreed to the agreement ?
I also remember having to reinstall nodejs.
Had the exact same problem with the same error.
after the above it sorted its self out.
