### ISSUE TITLE
HomeBridge Hubs only work on local wifi 

### ISSUE THREAD

**Issue by jpstephens** [nfarina/homebridge#961]
For some reason the devices added to homebridge (nest and alarm.com) only work while I am connected to my home wifi network.  Once I leave the house the devices become unresponsive. 

Any idea what causes this?

**Comment by maragelis** [comment]
Thats how homekit works, you need an ipad or appletv on your local wifi network to have access to it when away from the network.

**Comment by stevenmcastano** [comment]
Wait, so you’re saying that if there is a local device still connected to wifi, I can still control homebridge using siri remotely?

**Comment by maragelis** [comment]
yes, only an iPad or Appletv. Then you can use siri and homekit remotly like you are home

**Comment by jpstephens** [comment]
Good Morning
The thing is Siri and HomeKit work for all other devices outside the home. The only devices that not only accessible on the local network is the homebridge stuff. 
Any idea what's causing this?

Get Outlook for iOS




On Thu, Dec 1, 2016 at 2:43 AM -0500, "Peter" <notifications@github.com> wrote:












yes, only an iPad or Appletv. Then you can use siri and homekit remotly like you are home

**Comment by jpstephens** [comment]
To clarify, I do have an Apple TV setup and my HomeKit devices all work remotely. The only devices that show unresponsive once I leave the home wifi is the homebridge stuff.

**Comment by jpstephens** [comment]
To clarify, I do have an Apple TV setup and my HomeKit devices all work remotely. The only devices that show unresponsive once I leave the home wifi is the homebridge stuff.

**Comment by bryanbartow** [comment]
@jpstephens I had this same issue when I upgraded from iOS 9 to iOS 10 on my devices. Unfortunately, the only solution that worked for me was removing all Homekit devices (including Homebridge) from the Home app on all of my iOS devices and then starting over and adding them from scratch. Once I did that it all worked as advertised.
