### ISSUE TITLE
Raspberry pi - cannot load bindings error

### ISSUE THREAD

**Issue by a2ron44** [nfarina/homebridge#962]
I'm getting an error when trying to get Homebridge working on a Raspberry Pi B+.  Anyone seen this?

Node:  6.9.1
Npm:  3.10.8

Installing per Pi instructions, but need to install a slightly different node package since I only have the arm6 architecture.  No issues on install, but on running homebridge command I get the following:

`
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
/usr/local/lib/node_modules/homebridge/node_modules/bindings/bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /usr/local/lib/node_modules/homebridge/node_modules/ed25519/build/ed25519.node
 → /usr/local/lib/node_modules/homebridge/node_modules/ed25519/build/Debug/ed25519.node
 → /usr/local/lib/node_modules/homebridge/node_modules/ed25519/build/Release/ed25519.node
 → /usr/local/lib/node_modules/homebridge/node_modules/ed25519/out/Debug/ed25519.node
 → /usr/local/lib/node_modules/homebridge/node_modules/ed25519/Debug/ed25519.node
 → /usr/local/lib/node_modules/homebridge/node_modules/ed25519/out/Release/ed25519.node
 → /usr/local/lib/node_modules/homebridge/node_modules/ed25519/Release/ed25519.node
 → /usr/local/lib/node_modules/homebridge/node_modules/ed25519/build/default/ed25519.node
 → /usr/local/lib/node_modules/homebridge/node_modules/ed25519/compiled/6.9.1/linux/arm/ed25519.node
    at bindings (/usr/local/lib/node_modules/homebridge/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/ed25519/index.js:1:99)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:6:15)`

**Comment by cbredesen** [comment]
I see this also but it doesn't seem to have any adverse effects. Others might know more.

**Comment by a2ron44** [comment]
This error does not allow me to go forward.  I cannot load plugins and it does not create my “.homebridge” folder.

**Comment by mogeryt** [comment]
Try 'npm install -g bindings' and run again.

**Comment by a2ron44** [comment]
Looks like Node 6.9.1 on the B+ is not compatible for some reason.  I installed Node 4.3.2 and everything works.

**Comment by stardustliu** [comment]
my solution is :
cd /usr/local/lib/node_modules/homebridge/node_modules/ed25519
sudo node-gyp BUILDTYPE=Release rebuild

**Comment by SzilagyiR** [comment]
Hi!

I got this error massage too.

NODE version v7.8.0
NPM version: 5.0.3

Trying `sudo npm install -g bindings`, no error massage, but runing the homebridge error is the same.

Trying `
cd /usr/local/lib/node_modules/homebridge/node_modules/ed25519
sudo node-gyp BUILDTYPE=Release rebuild
`

I got this error:
```
In file included from ../src/ed25519.cc:4:0:
../../nan/nan.h:326:47: error: ‘REPLACE_INVALID_UTF8’ is not a member of ‘v8::String’
   static const unsigned kReplaceInvalidUtf8 = v8::String::REPLACE_INVALID_UTF8;
                                               ^
ed25519.target.mk:122: recipe for target 'Release/obj.target/ed25519/src/ed25519.o' failed
make: *** [Release/obj.target/ed25519/src/ed25519.o] Error 1
make: Leaving directory '/usr/local/lib/node_modules/homebridge/node_modules/ed25519/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Linux 4.4.50-v7+
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "BUILDTYPE=Release" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/homebridge/node_modules/ed25519
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
```

**Comment by Timmeehhh** [comment]
@stardustliu Your solution worked for me.

Don't forget to install node-gyp first through NPM.
