### ISSUE TITLE
??Scratching Head??

### ISSUE THREAD

**Issue by dasoutherland** [nfarina/homebridge#964]
So I've been back and forth with some issues getting homebridge to run.
It was running fine for a few days and then stopped. I went down a path of trying a few things and then gave up for about a week. 
So tonight I decided to mess around and all of a sudden the Home app see's the bridge. But what is this error?

<img width="971" alt="screen shot 2016-11-30 at 9 36 14 pm" src="https://cloud.githubusercontent.com/assets/23044278/20779871/4feed174-b745-11e6-91ac-ff7c934f1cd2.png">

**Comment by KhaosT** [comment]
EADDRINUSE meaning there is already an instance of homebridge running on this machine.

Best Wishes,
Tian

**Comment by dasoutherland** [comment]
WEIRD!!!!

@KhaosT I know you have seen the issues I've been having and now all of a sudden it starts working??? WTF!!!
Either way, I will ride it out till it breaks!
