### ISSUE TITLE
Updating multiple characteristics with one request...

### ISSUE THREAD

**Issue by luc-ass** [nfarina/homebridge#965]
Hey there,

I just wanted to ask wether one can update multiple characteristics on a single request. My plugin updates several values from the same URL but does individual requests (each with the same JSON-response) wich seams like a waste.

I would rather want to request the data once and then update all characteristics...

thanks!

**Comment by NorthernMan54** [comment]
Yes, entirely feasible. If you look at homebridge-mcuiot I'm updating multiple characteristics in a single get request. This is even across multiple accessories on the same platform.

**Comment by dasoutherland** [comment]
Could you give an example as to why you'd want something like this. Just curious!

**Comment by NorthernMan54** [comment]
I have a bme 280 temperature/humidity/atmospheric pressure sensor that returns multiple values.  As I only poll the device once, at it returns multiple values, it was easiest to update them all at one time and avoid device thrashing.  It also increases the responsiveness of the apps, as they aren't requesting each characteristic individually.  I have about 30 accessories, and loading at a glance page takes a long period of time.   Also very useful for thermostat's, as the same use case applies.
