### ISSUE TITLE
Outdated dependancies

### ISSUE THREAD

**Issue by volschin** [nfarina/homebridge#97]
I have monitored the project with gemnasium and found 3 dependancies out of date:
Request
Wink-js 
Xmldoc

Perhaps you should check for updating for the refactoring branch at least.

**Comment by nfarina** [comment]
So the first two are used by shims (and I'd like to spin those out into separate projects anyway) and `xmldoc` is my own creation and the updates are trivial but should be safe, so I'll do that in the refactor branch thanks!
