### ISSUE TITLE
Video brakes in homebridge-camera-ffmpeg

### ISSUE THREAD

**Issue by Maxmudjon** [nfarina/homebridge#970]
![photo1204279221268145](https://cloud.githubusercontent.com/assets/23142922/20861896/b08edd10-b9bd-11e6-912b-1c089e0de239.jpg)

Camera - IP Camera with resolution 1280x720
Raspberry PI 3 OS - with Jessie

what is the problem ?

**Comment by mogeryt** [comment]
We can't say anything without logs, but most likely the Pi is not strong enough to handle the stream.

**Comment by Negenii** [comment]
Confirm, I have the same with some test video stream.
BTW is it possible no to decode and re-encode the stream back, if the stream it self fits requirements? Can we just "proxy" it?

**Comment by KhaosT** [comment]
@Negenii you certainly can. The camera support for homebridge is designed to be expanded easily. If you have more control to the camera feed, feel free to write your plugin to do the stream instead of using general purpose ffmpeg plugin :)
