### ISSUE TITLE
Running on homebridge on Android TV?

### ISSUE THREAD

**Issue by rlester** [nfarina/homebridge#972]
I have an NVIDIA shield and was wondering if anyone has home bridge running as a server on an Android device. 

I was able to get node js installed running through the Termux app but it doesn't look like  "libavahi-compat-libdnssd-dev" has been ported to Termux.

Would appreciate some help if anyone had any other ideas.

**Comment by mogeryt** [comment]
Well, you could always port it yourself, or try to switch to an older version of Homebridge.

**Comment by smpgallagher** [comment]
I have it running on my old android phone via a debian install, i assume you can do the same on the android tv? the last step that nearly stopped me was to start the avahi daemon as follows
avahi-daemon --no-chroot --no-drop-root (otherwise it fails with a socket permission execption)

**Comment by goooseman** [comment]
I've used Linux deploy Android app to install Ubuntu 14.04.
Avahi-daemon was not starting but, `--no-chroot --no-drop-root` fixed it (thx @smpgallagher)

I've edited `/etc/init.d/avahi-daemon` to include this options to
`$DAEMON -d` line

**Comment by anubhavmajumder** [comment]
Hello.
You can install any distro of linux as a secondary OS using this on your android. https://github.com/meefik/linuxdeploy

After that setup homebridge as usual. https://github.com/nfarina/homebridge
And plugins from here. https://www.npmjs.com/search?q=homebridge-plugin

Cheers!

**Comment by yepecece** [comment]
Hi,
I’m interesting on installing this and have some questions.

I guess the shield has to be rooted in order to install Linux.

Also, would it be possible to start linux and homebridge on boot automatically?

Cheers!

**Comment by goooseman** [comment]
Yes, you should root first.

And yes, you can make Linux to autostart automatically. There is an option
in the settings of Linux deploy.

And you can make homebridge to autostart automatically. To do that you need
to choose run-parts in the init section of configure screen before
installing Linux. Install Linux, install homebdridge and add the command,
which starts homebridge to /etc/rc.local
