### ISSUE TITLE
Homekit native accessory plugin

### ISSUE THREAD

**Issue by llemtt** [nfarina/homebridge#978]
Hi, has someone already developed a plugin for native homekit accessories such as Elgato's?

**Comment by Samfox2** [comment]
Yes there are a few philips hue plugins, although the new bridge has direct homekit support.

**Comment by llemtt** [comment]
> although the new bridge has direct homekit support

great! do you mean current or upcoming version?

**Comment by Samfox2** [comment]
Current

**Comment by llemtt** [comment]
Cool, can you indicate me some documentation about it?

**Comment by llemtt** [comment]
Hi, where do I find some "direct homekit support" documentation?

**Comment by Samfox2** [comment]
"direct homekit support" means that if you own the 2nd version of the hue bridge (not the round one) you do not need homebridge, the bridge itself has homebridge support.

**Comment by ebaauw** [comment]
See the official Philips Hue app, http://www2.meethue.com/en-us/philips-hue-app, and/or the Hue developers forum, https://developers.meethue.com/forums/apple-homekit.
