### ISSUE TITLE
can someone help me with creating a plugin?

### ISSUE THREAD

**Issue by xhalfbakedguy** [nfarina/homebridge#986]
Hey,
first of all im a java noob and know just the first 4 lessons of the oracle java tutorial because i just read them. All the plugin needs to do is to run the ps4 waker script (https://github.com/dhleong/ps4-waker) to turn the ps4 on and off. i learn pretty fast so if someone could just help with getting started that would help a lot.

**Comment by xhalfbakedguy** [comment]
i just need to know how i use the api..like:
-how do i create a new accessory(switch in HomeKit/Home App)
-what does the api pass once a switch is toggled (and idetified to belong to my plugin)
-how do i tell homebridge x device is  on/off ( i want to use switches to start games)
I want it to create a new switch once a game is started the first time by searching the string the ps4-waker search -d ps4.ip for the game id and check if there is a switch already but this i getting too far right now. the code is basically ready and the last thing i need to implent homebridge..

**Comment by snowdd1** [comment]
Did you see there's a sample in the repository?  
https://github.com/nfarina/homebridge/blob/master/example-plugins/homebridge-samplePlatform/index.js

A liitle easier to implement are "older" style accessory shims, a wiki page explaining how to is located here: https://github.com/nfarina/homebridge/wiki/The-http-sample:-comments-on-the-accessory-shim 

To update the value in Homekit: the Characteristic class provides `setValue()` and `updateValue` (the latter not triggering the `set` event in homebridge itself.  

good luck!

**Comment by xhalfbakedguy** [comment]
I ended up using another plugin called programmable switch that executes a python script which then executes the wanted command line commands. sounds weird but ended up working. I can post the python stuff if someone is interested but its very basic. I just started learning node with not knowing javascript before so it will take some time to work out a homebridge-ps4-waker plugin haha

**Comment by thechrisreese** [comment]
I'm curious how you execute the python commands
