### ISSUE TITLE
Duplicating plugin for 2 accessories 

### ISSUE THREAD

**Issue by JohnSanchirico** [nfarina/homebridge#988]
I recently finished configuring this plugin to fit my needs, all I need now is 2 of these accessories and when running homebridge is runs both plugins and registers accessores but doesn't load both of them any help? Thanks
Console Log: http://pastebin.com/sABwqCwG
Homebridge Config: http://pastebin.com/2YzfU46x

**Comment by KhaosT** [comment]
Are you sure you put the edited config file to the right place? Your configuration looks ok to me and it should work...

**Comment by KhaosT** [comment]
Oops sorry pressed wrong button.

**Comment by JohnSanchirico** [comment]
Sorry, my mistake here. Was getting very late and was frustrated with my code not working, ended up make a whole new config.json in the wrong directory. Wondered why it wasn't working, that's probably it... LOL. Please close this thread, thanks for the help KhaosT anyway
