### ISSUE TITLE
Run at startup

### ISSUE THREAD

**Issue by TylerBecause** [nfarina/homebridge#99]
I would like this to automatically start up if my Raspberry Pi restarts.
I have read that someone created a .sh init.d script but have not been able to find the details.

**Comment by nfarina** [comment]
Homebridge can be run as a daemon like any other linux process. Depending on what OS is on your RPi, each one has a different "native" mechanism for running long-lived tasks on bootup. It might be nice to supply an example init.d script if someone has one already.

**Comment by nfarina** [comment]
I wrote up a complete example of how to do this in the new Raspberry Pi section of the wiki: https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi

**Comment by snowdd1** [comment]
Maybe adding "forever" to the start script would be a nice feature.

**Comment by maddox** [comment]
I'd like to do this on OS X as well. I gave it a go with another node app a couple weeks ago, but couldn't get a node app to start with `launchd`.

**Comment by lukeredpath** [comment]
Anyone found a reliable way to do this on OSX?

**Comment by maddox** [comment]
@lukeredpath I have a [pattern for this](https://github.com/maddox/itunes-api/pull/3) for node apps using a combination of Forever + launchd to kick off forever. 

I've been meaning to open a pull on Homebridge for a while, but I hadn't been using it. I just set it back up last night though. I'll probably push this up tonight.

**Comment by lukeredpath** [comment]
This would be really useful, thanks Jon. I’ve finally got around to trying to get this running on my Domoticz server so it would be nice to keep it running.
