### ISSUE TITLE
Help with Nest json for homebridge

### ISSUE THREAD

**Issue by twennywonn** [nfarina/homebridge#992]
I get the error "[Error: You did not specify {'token'} or {'clientId','clientSecret','code'}, one set of which is required for the new API]"

Im thinking I need to delete stuff but im not sure how to write the json.  I have all fields populated and I do have the token. How do I specify?

Sorry for my noobness.

{
    "bridge": {
        "username": "xx",
        "name": "Homebridge",
        "pin": "987-xx-432"

    },

    "platforms": [{
        "platform": "Nest",

        "token": "xx",

        "clientId": "xx",
        "clientSecret": "xx",
        "code": "xx",

        "username": "xx",
        "password": "xx"
    }, {

        "platform": "Nest",
        "username": "xx",
        "password": "xx"
    }, {
        "platform": "SmartThings",
        "name": "SmartThings",
        "app_url": "https://graph-naxx/api/smartapps/installations/",
        "app_id": "xx",
        "access_token": "xxx"
    }]
}

**Comment by rickvdl** [comment]
@twennywonn Probably because you have specified the `Nest` platform twice, remove the second one without the token.
Then you'll end up with something like this.
```
{
    "bridge": {
        "username": "xx",
        "name": "Homebridge",
        "pin": "987-xx-432"
    },
    "platforms": [{
        "platform": "Nest",
        "token": "xx",
        "clientId": "xx",
        "clientSecret": "xx",
        "code": "xx",
        "username": "xx",
        "password": "xx"
    }, {
        "platform": "SmartThings",
        "name": "SmartThings",
        "app_url": "https://graph-naxx/api/smartapps/installations/",
        "app_id": "xx",
        "access_token": "xxx"
    }]
}
```
